### PR TITLE
Improve test output to better pin-point failing code (#2407)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
**CC:** @trilinos/teuchos, @mhoemmen 

## Description

This makes it easier to see which code is failing in the type conversion from
long double as string to double (see #2407).

This now shows which unit test code is failing and why on `ride` build `gnu-debug-openmp`:

```
1. asSafe_stringToReal_UnitTest ... 
 minLD = -1.79769e+308
 minusOneLD = -1
 maxLD = 1.79769e+308
 Testing string -> float conversions ...
 Test that code {valF = asSafe<float> (os.str ());} does not throw : passes
 valF = -3.40282347e+38 == -3.40282347e+38 : passed
 Test that code {valF = as<float> (os.str ());} does not throw : passes
 valF = -3.40282347e+38 == -3.40282347e+38 : passed
 Test that code {valF = asSafe<float> (os.str ());} does not throw : passes
 valF = 3.40282347e+38 == 3.40282347e+38 : passed
 Test that code {valF = as<float> (os.str ());} does not throw : passes
 valF = 3.40282347e+38 == 3.40282347e+38 : passed
 Test that code {valF = asSafe<float> (os.str ());} does not throw : passes
 valF = -1.00000000e+00 == -1.00000000e+00 : passed
 Test that code {valF = as<float> (os.str ());} does not throw : passes
 valF = -1.00000000e+00 == -1.00000000e+00 : passed
 Test that code {valF = asSafe<float> (os.str ());} does not throw : passes
 valF = -1.00000000e+00 == -1.00000000e+00 : passed
 Test that code {valF = as<float> (os.str ());} does not throw : passes
 valF = -1.00000000e+00 == -1.00000000e+00 : passed
 Testing string -> float conversions that should throw ...
 Test that code {valF = asSafe<float> (os.str ());} throws std::range_error: passed
 
 Exception message for expected exception:
 
  /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:558:
  
  Throw number = 1
  
  Throw test that evaluated to true: errno == ERANGE && (val != 0)
  
  Teuchos::ValueTypeConversionTraits<float, std::string>::convert: The value in the given string "-1.79769313e+308" overflows float.
  
 Test that code {valF = asSafe<float> (os.str ());} throws std::range_error: passed
 
 Exception message for expected exception:
 
  /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:558:
  
  Throw number = 2
  
  Throw test that evaluated to true: errno == ERANGE && (val != 0)
  
  Teuchos::ValueTypeConversionTraits<float, std::string>::convert: The value in the given string "1.79769313e+308" overflows float.
  
 Testing string -> double conversions ...
 Test that code {valD = asSafe<double> (os.str ());} does not throw : passed
 valD = -1.79769313486231571e+308 == -1.79769313486231571e+308 : passed
 Test that code {valD = as<double> (os.str ());} does not throw : passed
 valD = -1.79769313486231571e+308 == -1.79769313486231571e+308 : passed
 Test that code {valD = asSafe<double> (os.str ());} does not throw : passed
 valD = 1.79769313486231571e+308 == 1.79769313486231571e+308 : passed
 Test that code {valD = as<double> (os.str ());} does not throw : passed
 valD = 1.79769313486231571e+308 == 1.79769313486231571e+308 : passed
 Test that code {valD = asSafe<double> (valToString(minusOneD));} does not throw : passed
 valD = -1.00000000000000000e+00 == -1.00000000000000000e+00 : passed
 Test that code {valD = as<double> (valToString(minusOneD));} does not throw : passed
 valD = -1.00000000000000000e+00 == -1.00000000000000000e+00 : passed
 Testing converting from 'long double' to 'double' that does not fit ...
 Test that code {valD = asSafe<double>(valToString(minLD));} throws std::range_error: failed (code did not throw an exception at all)
 valD = -1.79769e+308
 Test that code {valD = asSafe<double>(valToString(maxLD));} throws std::range_error: failed (code did not throw an exception at all)
 valD = 1.79769e+308
 Testing string -> long double conversions ...
 Test that code {valLD = asSafe<long double> (os.str ());} does not throw : passed
 valLD = -1.79769e+308 == -1.79769e+308 : passed
 Test that code {valLD = as<long double> (os.str ());} does not throw : passed
 valLD = -1.79769e+308 == -1.79769e+308 : passed
 Test that code {valLD = asSafe<long double> (os.str ());} does not throw : passed
 valLD = 1.79769e+308 == 1.79769e+308 : passed
 Test that code {valLD = as<long double> (os.str ());} does not throw : passed
 valLD = 1.79769e+308 == 1.79769e+308 : passed
 Test that code {valLD = asSafe<long double> (os.str ());} does not throw : passed
 valLD = -1 == -1 : passed
 Test that code {valLD = as<long double> (os.str ());} does not throw : passed
 valLD = -1 == -1 : passed
 [FAILED]  (0.00042 sec) asSafe_stringToReal_UnitTest
 Location: /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp:287
 

The following tests FAILED:
    1. asSafe_stringToReal_UnitTest ... 
```

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
This is included in the updated branch and PR #2409.  I am closing this PR.  Please just review #2409.

**Comment by bartlettroscoe** [comment]
> Status Flag 'Pull Request AutoTester' - ERROR: A user has commited a change to the PR before testing completed. The testing SHA = 74bc1f5 Does not match the current commit SHA = 08f67a0. Testing of this PR must occur again.

@allevin, @trilinos/framework 

I closed this PR and opened a new one #2409 before this comment [above](https://github.com/trilinos/Trilinos/pull/2408#issuecomment-373946110) was created.

This is a use case that the auto PR test should likely handle better.  It should recognize that the PR is closed and either say nothing at all (i.e. not bother adding another comment) or add a comment that notes that the PR is closed and then say anything it wants about the status of testing.

**Comment by jwillenbring** [comment]
@allevin One possibility here that would be simple would be to update the wording to say something like:

ERROR: Before testing completed, either the PR was modified with a new commit, or closed. The testing SHA... If the PR is still open the next time the Autotester runs, testing will occur again.

The one question I have here is what the “current commit SHA” represents if Ross just closed, but did not update the PR.

**Comment by allevin** [comment]
@jwillenbring @bartlettroscoe What happened here is related to what's going on behind the scenes.  When the autotester starts testing, it only monitors Jenkins.  It does not look at the PR to see if anything changed.  When testing finishes, it then posts the results.

Therefore is actually 3 separate operational issues on Autotester:

1) The autotester should monitor the status of the PR, and if closed or new commit, cancel testing, and notify user (this is the message that Ross is commenting on).  This will free up testing resources sooner under these 2 conditions.  I have created an issue against the Autotester for this.  

1) The autotester should not adjust add comments or adjust the status flags if the PR is closed.  We already have an open issue against this.  

1) The message about the SHA's changing (due to a commit) is still valid, but the above two issues would take precedence.  

---

> The one question I have here is what the “current commit SHA” represents if Ross just closed, but did not update the PR.

In this case, there was a new commit just before the PR was closed.  However the autotester was still testing the PR, and went ahead an commented on it.  The above changes would eliminate any comments being made to the closed PR.

**Comment by bmpersc** [comment]
@allevin I'm not sure I agree fully with your item 2. I do agree that the autotester should not update status flags on a closed issue. However, if the autotester is going to force stop tests due to item 1 then it should definitely comment that in the closed PR.

**Comment by allevin** [comment]
@bmpersc I agree.  We need to think about the implementation of these special cases.

**Pull request closed without merging**
