### PR TITLE
Tpetra/Ctest: Trying to set up performance testing

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA e67fadd

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@csiefer2, to be clear, you can get the right set of tests defined when you run locally but not when you try to use the ctest -S driver to submit to CDash?  Since I don't have an account on 'rocketman' I may not be able to reproduce things with that script.  Can you attach some log files for the XML files that ctest -S creates and the STDOUT from ctest -S?

**Comment by csiefer2** [comment]
@bartlettroscoe I cannot get the right tests defined when I run locally.  No tests run when I run cdash.

**Comment by csiefer2** [comment]
@bartlettroscoe  Have you had a chance to see why the ctest isn't working?

**Comment by bartlettroscoe** [comment]
@csiefer2 I will try to take a look tody

**Comment by bartlettroscoe** [comment]
@csiefer2, I was able to trigger the enable of this test just fine as described below (one-line run of [checkin-test-sems.sh](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing)) but it gives a configure error.  Did you not see this configure error?

Why was this PR merged before it was known to work?

----

So on 'ceerws1113' with Trilinos version:

```
7f130b7 "Merge Pull Request #5597 from gsjaardema/Trilinos/seacas-remove-cgns-patch-detection-error"
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Tue Jul 30 11:29:31 2019 -0600 (6 hours ago)
```

I did:

```
$ cd /scratch/rabartl/Trilinos.base/BUILDS/CHECKIN/

$ ./checkin-test-sems.sh \
  --enable-packages=Teuchos,Tpetra \
  --test-categories=PERFORMANCE \
  --allow-no-pull --configure
```

That showed the configure failure:

```
CMake Error at cmake/tribits/core/package_arch/TribitsAddTestHelpers.cmake:469 (IF):
  if given arguments:

    "1" "4" "9" "16" "25" "36" "MATCHES" "[0-9]+-[0-9]+"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAddTest.cmake:893 (TRIBITS_ADD_TEST_GET_NUM_PROCS_USED)
  packages/tpetra/core/example/Finite-Element-Assembly/CMakeLists.txt:98 (TRIBITS_ADD_TEST)


-- Configuring incomplete, errors occurred!
```

**Comment by bartlettroscoe** [comment]
Note that the above configure correctly added the existing Teuchos PERFORMANCE tests I wrote years ago (but are never run anymore :-( )

```
$ grep "Added test" MPI_RELEASE_DEBUG_SHARED_PT_OPENMP/configure.out 
-- TeuchosCore_RCP_PerformanceTests_basic_MPI_1: Added test (BASIC, PERFORMANCE, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- TeuchosCore_RCP_PerformanceTests_performance_MPI_1: Added test (PERFORMANCE, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- TeuchosCore_Array_PerformanceTests_basic_MPI_1: Added test (BASIC, PERFORMANCE, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- TeuchosCore_Array_PerformanceTests_performance_MPI_1: Added test (PERFORMANCE, NUM_MPI_PROCS=1, PROCESSORS=1)!
```

**Comment by csiefer2** [comment]
> @csiefer2, I was able to trigger the enable of this test just fine as described below (one-line run of [checkin-test-sems.sh](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing)) but it gives a configure error. Did you not see this configure error?

Configure worked just fine for me, both from a hand configure and from manually firing off the driver.  Let me see if I can reproduce your error.

**Comment by csiefer2** [comment]
It took me half an hour to get checkin-test-sems.sh to get the TPLs right, but now I can finally reproduce your error.

**Comment by csiefer2** [comment]
@bartlettroscoe Figured out the problem:  The NUM_MPI_PROCS in the TRIBITS_ADD_TEST command can only take continuous processor ranges.

Which is unfortunate, since this test only is only useful on perfect square numbers of procs.  Easy enough to fix, though.

Allowing non-contiguous processor ranges might be a nice extension to TriBITS to consider...

**Comment by bartlettroscoe** [comment]
> It took me half an hour to get checkin-test-sems.sh to get the TPLs right, but now I can finally reproduce your error.

ARe you not on a SEMS machine?


> Allowing non-contiguous processor ranges might be a nice extension to TriBITS to consider...

Yea, that would not be that hard.

**Pull request merged**
