### PR TITLE
Adds Templating for Types in OpenMP SpMV Benchmark Kernels

### PR DESCRIPTION
**Pull request by nmhamster**
Adds templates to OpenMP kernels requested by @mhoemmen. This does appear to make any difference to benchmark performance or optimization.

### CODE REVIEW

**Comment by nmhamster** [comment]
@crtrott / @mhoemmen - can you approve this PR soon please? I am trying to run this using the Trilinos mainline everywhere I can.

**Comment by mhoemmen** [comment]
Sorry @nmhamster; I'll take a look tonight.

**Comment by mhoemmen** [comment]
I'm approving this PR.  It does not build with the CMake build system yet, so approving the PR has no consequences for testing.

**Comment by mhoemmen** [comment]
Had to do this with a merge commit, since rebase causes conflicts.

**Comment by mhoemmen** [comment]
@nmhamster I realize now that both LocalOrdinal and Scalar are implied in AType.  You have two options: Either get LocalOrdinal and Scalar from the typedefs in KokkosSparse::CrsMatrix, or use the following expressions:
```
typedef typename std::decay<decltype (A.values[0])>::type scalar_type; 
typedef typename std::decay<decltype (A.graph.entries[0])>::type local_ordinal_type;
```

**Pull request merged**
