### PR TITLE
Fix long double string to double conversion on shiller (#2407)

### LINKED ISSUE #2407: Test TeuchosCore_TypeConversions_UnitTest_MPI_1 fails with failed asSave<double> conversion in all white/ride builds
**CC:** @trilinos/teuchos, @nmhamster 

## Description

The test ` TeuchosCore_TypeConversions_UnitTest_MPI_1` fails in all of the `gnu` and `cuda` builds on `white` and `ride` as shown at:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-03-17&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=TeuchosCore_TypeConversions_UnitTest_MPI_1&field3=status&compare3=61&value3=failed

All of these show failures for an invalid `saveAs<double>()` conversion to thrown an exception in the test `asSafe_stringToReal_UnitTest` showing:

```
 Test that code {valD = asSafe<double> (os.str ());} throws std::range_error: failed (code did not throw an exception at all)
 Test that code {valD = asSafe<double> (os.str ());} throws std::range_error: failed (code did not throw an exception at all)
```

The test code that is failing looks to be:

```
TEUCHOS_UNIT_TEST( asSafe, stringToReal ) {
   ...
  const long double minLD = -std::numeric_limits<long double>::max ();
  const long double minusOneLD = -1;
  const long double maxLD = std::numeric_limits<long double>::max ();
  ...
  if (sizeof (long double) > sizeof (double)) {
    {
      std::ostringstream os;
      os.precision (36);
      os << minLD;
      TEST_THROW(valD = asSafe<double> (os.str ()), std::range_error);
    }
    {
      std::ostringstream os;
      os.precision (36);
      os << maxLD;
      TEST_THROW(valD = asSafe<double> (os.str ()), std::range_error);
    }
  }
  ...
```

So it looks like that on this system and GCC compiler that even though the type `long double` appears to exist and is larger than `double` it seems that the code that implements `safeAs<double>()` is not catching this invalid conversion.

## Steps to Reproduce

This can be reproduced on `white` or `ride` as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

Just enable the Teuchos package and run the tests for any of the supported builds on `white` or `ride`.  For example, try the build `gnu-debug-openmp`.

### PR DESCRIPTION
**Pull request by bartlettroscoe**
This fixes the asSafe() test for the cuda builds on 'shiller' described in https://github.com/trilinos/Trilinos/issues/2407#issuecomment-374319847.  This should fix #2407 once and for all.

I tested this locally on 'shiller' (same system as 'hansen') with:

```
$ srun ./checkin-test-atdm.sh cuda-opt gnu-opt-serial intel-opt-serial \
  --ctest-options="-j16 -R TeuchosCore_TypeConversions_UnitTest" \
  --enable-packages=TeuchosCore --local-do-all
```

and it returned:

```
PASSED (NOT READY TO PUSH): Trilinos: shiller03

Tue Mar 20 13:14:06 MDT 2018

Enabled Packages: TeuchosCore

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => Test case MPI_RELEASE_DEBUG_SHARED_PT was not run! => Does not affect push readiness! (-1.00 min)
1) cuda-opt => passed: passed=1,notpassed=0 (2.07 min)
2) gnu-opt-serial => passed: passed=1,notpassed=0 (0.97 min)
3) intel-opt-serial => passed: passed=1,notpassed=0 (2.15 min)
```
The interesting bits of test output created from:

```
$ ./TeuchosCore_TypeConversions_UnitTest.exe --test=stringToReal --details=ALL
```

for each of these builds is shown below.

**cuda-opt**

```
1. asSafe_stringToReal_UnitTest ... 
 minF = -3.4e+38
 maxF = 3.4e+38
 minD = -1.8e+308
 maxD = 1.8e+308
 minLD = -inf
 maxLD = inf
...
 sizeof_long_double = 16
 sizeof_double = 8
 max_exponent10_long_double = 4932
 max_exponent10_double = 308
 Testing converting from 'long double' to 'double' that does not fit ...
 maxTooBigLD_for_D = 1.8e+309
 minTooBigLD_for_D = -1.8e+309
 Test that code {valD = asSafe<double>(valToString(minTooBigLD_for_D));} throws std::range_error: passed
 
 Exception message for expected exception:
 
  /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:558:
  
  Throw number = 3
  
  Throw test that evaluated to true: errno == ERANGE && (val != 0)
  
  Teuchos::ValueTypeConversionTraits<double, std::string>::convert: The value in the given string "-1.797693134862315708145274237e+309" overflows double.
  
 valD = -1
 Test that code {valD = asSafe<double>(valToString(maxTooBigLD_for_D));} throws std::range_error: passed
 
 Exception message for expected exception:
 
  /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:558:
  
  Throw number = 4
  
  Throw test that evaluated to true: errno == ERANGE && (val != 0)
  
  Teuchos::ValueTypeConversionTraits<double, std::string>::convert: The value in the given string "1.797693134862315708145274237e+309" overflows double.
  
 valD = -1
...
 [Passed] (0.000769 sec)

Total Time: 0.00111 sec

Summary: total = 116, run = 1, passed = 1, failed = 0

End Result: TEST PASSED
```

**gnu-opt-serial**

```
1. asSafe_stringToReal_UnitTest ... 
 minF = -3.4e+38
 maxF = 3.4e+38
 minD = -1.8e+308
 maxD = 1.8e+308
 minLD = -1.19e+4932
 maxLD = 1.19e+4932
 ...
 sizeof_long_double = 16
 sizeof_double = 8
 max_exponent10_long_double = 4932
 max_exponent10_double = 308
 Testing converting from 'long double' to 'double' that does not fit ...
 maxTooBigLD_for_D = 1.8e+309
 minTooBigLD_for_D = -1.8e+309
 Test that code {valD = asSafe<double>(valToString(minTooBigLD_for_D));} throws std::range_error: passed
 
 Exception message for expected exception:
 
  /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:558:
  
  Throw number = 3
  
  Throw test that evaluated to true: errno == ERANGE && (val != 0)
  
  Teuchos::ValueTypeConversionTraits<double, std::string>::convert: The value in the given string "-1.797693134862315708145274237e+309" overflows double.
  
 valD = -1
 Test that code {valD = asSafe<double>(valToString(maxTooBigLD_for_D));} throws std::range_error: passed
 
 Exception message for expected exception:
 
  /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:558:
  
  Throw number = 4
  
  Throw test that evaluated to true: errno == ERANGE && (val != 0)
  
  Teuchos::ValueTypeConversionTraits<double, std::string>::convert: The value in the given string "1.797693134862315708145274237e+309" overflows double.
  
 valD = -1
 ...
   [Passed] (0.00135 sec)

Total Time: 0.00169 sec

Summary: total = 116, run = 1, passed = 1, failed = 0

End Result: TEST PASSED
```

**intel-opt-serial**

```
1. asSafe_stringToReal_UnitTest ... 
 minF = -3.4e+38
 maxF = 3.4e+38
 minD = -1.8e+308
 maxD = 1.8e+308
 minLD = -1.19e+4932
 maxLD = 1.19e+4932
 ...
 sizeof_long_double = 16
 sizeof_double = 8
 max_exponent10_long_double = 4932
 max_exponent10_double = 308
 Testing converting from 'long double' to 'double' that does not fit ...
 maxTooBigLD_for_D = 1.8e+309
 minTooBigLD_for_D = -1.8e+309
 Test that code {valD = asSafe<double>(valToString(minTooBigLD_for_D));} throws std::range_error: passed
 
 Exception message for expected exception:
 
  /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:558:
  
  Throw number = 3
  
  Throw test that evaluated to true: errno == ERANGE && (val != 0)
  
  Teuchos::ValueTypeConversionTraits<double, std::string>::convert: The value in the given string "-1.797693134862315708145274237e+309" overflows double.
  
 valD = -1
 Test that code {valD = asSafe<double>(valToString(maxTooBigLD_for_D));} throws std::range_error: passed
 
 Exception message for expected exception:
 
  /home/rabartl/Trilinos.base/Trilinos/packages/teuchos/core/src/Teuchos_as.hpp:558:
  
  Throw number = 4
  
  Throw test that evaluated to true: errno == ERANGE && (val != 0)
  
  Teuchos::ValueTypeConversionTraits<double, std::string>::convert: The value in the given string "1.797693134862315708145274237e+309" overflows double.
  
 valD = -1
 ...
 [Passed] (0.00148 sec)

Total Time: 0.00186 sec

Summary: total = 116, run = 1, passed = 1, failed = 0

End Result: TEST PASSED
```

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
CC: @trilinos/teuchos

**Comment by bartlettroscoe** [comment]
The auto PR build that posts to CDash shown at:


* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=338195

shows a build failure in the file `packages/amesos2/src/Amesos2_Tacho.cpp` shown at:


* https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=3381958

It is impossible that the changes to a test in Teuchos is breaking the build of that file.  Therefore, this failure must have gotten into the 'develop' branch somehow.  How did that happen?

Anyway, it looks like the PR #2428 will fix this.  It sounds like this change resulted from some ShyLU-related code being promoted from EX to ST or PT or something?

But that PR build shown at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=338195

does show that the Teuchos tests are passing, so I can go ahead and merge this PR.  This should result in this test passing in all of the ATDM builds!

**Comment by bartlettroscoe** [comment]
To be safe, I merged and pushed with the checkin-test-sems.sh script which pushed the commit  9aec6349a738376df4aad8a14801dcb53bad4996:

```
commit 9aec6349a738376df4aad8a14801dcb53bad4996
Merge: b989575 a1bc4fe
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Mar 20 15:16:37 2018 -0600

    Merge remote-tracking branch 'rab-github/2407-fix-cuda-shiller' into develop (#2407)
    
    Build/Test Cases Summary
    Enabled Packages: TeuchosCore
    Disabled Packages: PyTrilinos,Claps,TriKota
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=59,notpassed=0 (1.01 min)
    Other local commits for this build/test group: a1bc4fe
```

**Comment by mhoemmen** [comment]
@bartlettroscoe Looks good to me! Thanks!

**Pull request merged**
