### PR TITLE
Tempus: Embedded explicit rk

### PR DESCRIPTION
**Pull request by sconde**
Add explicit embedded RK capability to Tempus. For explicit rk pairs, this will compute embedded solution and estimate local truncation error.  

I also added the explicit Bogacki-Shampine 3(2) pair Butcher Tableau. This is the pair that is used in Matlab's ODE23. Additionally, updated the stepper parameterlist to tell stepper in PL to use Embedded or not. This will allow Embedded Butcher Tableau to be used in non-adaptive way (As regular RK). 

I updated the Explicit RK test: update ExplicitRK convegence test for Bogacki-Shampine 3rd order scheme, 
testing the non-embedded Butcher Tableau by telling the stepper in the PL to not use embedded, and test the embedded RK by telling the stepper to use Embedded.¬

@trilinos/tempus 

## Related Issues

* Closes 
* Blocks 
* Is blocked by #2204 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## How Has This Been Tested?
All tests passed!

[Tuesday-2018-02-06-13_32-build_tempus_dev-test.log](https://github.com/trilinos/Trilinos/files/1700750/Tuesday-2018-02-06-13_32-build_tempus_dev-test.log)

## Screenshots
initial_result_vdp2

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by sconde** [comment]
@ccober6 The integrator should keep count of the number of time step failures. 

When the integration is completed, I'm able to get the number of time steps taken with `iStep = integrator->getSolutionHistory()->getCurrentState()->getIndex();` Its a good idea to test not only the status of the integrator but also the total number of steps taken. In the embedded case, I also want to test the total number of step failures during the integration (not just the number of consecutive step failures). This information is not available in `integrator->getSolutionHistory()->getCurrentState()` nor am I able to get it from the metadata. 

Before adding this, I just wanted to get your opinion on the matter.

**Comment by ccober6** [comment]
So I believe what you want is there, and you can access the number of failures via integrator->getSolutionHistory()->getCurrentState()->getMetaData()->getNFailures().  We may want to add an accessor at the state level, e.g., integrator->getSolutionHistory()->getCurrentState()->getNFailures()

**Comment by sconde** [comment]
That says there were no failures after the integration was completed when 4 steps were rejected by the embedded method.

**Comment by ccober6** [comment]
Hmm ...   Did you mark the step as a failure (workingState->getStepperState()->stepperStatus_ = Status::FAILED;)?  If so we probably got a bug.

**Comment by sconde** [comment]
I believe we have a bug.

[number_of_failures_bug.log](https://github.com/trilinos/Trilinos/files/1712849/number_of_failures_bug.log)

As you can see from the log, the stepper does report a step failure and the step is repeated. When the integrator is done

` nFailure = integrator->getSolutionHistory()->getCurrentState()->getMetaData()->getNFailures()` reports that zero steps failed.

**Comment by sconde** [comment]
[So in `acceptTimeStep()`, the number of step failure is decreased. I think we should be decreasing the number of consecutive step failure instead.](https://github.com/sconde/Trilinos/blob/8e1fa0dab5c4f793c3cbcd8bac5fc3cd2004753f/packages/tempus/src/Tempus_IntegratorBasic_impl.hpp#L532)

We should differentiate between the number of consecutive step failure and (total) number of step failure.

**Comment by sconde** [comment]
@ccober6 I've updated Tempus to only decrement `NConsecutiveFailures` when the step has been accepted. `NFailures` should never be decremented.

**Comment by ccober6** [comment]
@sconde I think we are on the same page but should just decide what names we want to use.

* NConsecutiveFailures - the number of consecutive failures, so once it passes it should go to zero.
* NFailures - the "total" number of failures.  Originally this was similar to a MPSalsa variable, which kept count of the number of failures and decremented with each timestep that passed (see NRunningFailures).
* NRunningFailures - the number of failures and decremented with each timestep that passes

Thoughts?  Do we need or have a use for NRunningFailures?

**Comment by sconde** [comment]
@ccober6 When comparing adaptive time stepping results, we normally use the total number of step failures that occurred during the integration. A ratio of the total number steps attempted vs number of accepted steps is used to determine the efficiency of the embedded technique (combination of method and time step adaptive strategy). We need something that is not decremented. Not really sure if others will care for this information. So I can just grep and count the step failures from the output log. 

This way no change is necessary.

**Comment by sconde** [comment]
@ccober6 @rppawlo @ikalash I think I'm ready for a final review 

I did a small experiment using the 3(2) Pair
bogackishampine32_vdp_workprecision

What this shows is that the embedded RK implementation is working! Using the PID controller, the accuracy is very close to the prescribed tolerance (top figure). As the tolerance changes, the number of time steps (and work) also changes. This is what you would expect.

I've also tested that `General ERK` work with Embedded RK.

**Pull request merged**
