### PR TITLE
shards: update Doxyfile for tag file

### PR DESCRIPTION
**Pull request by romintomasetti**
@trilinos/shards

## Motivation

Change location of generated Doxygen tag file for `Shards` package so that it is aligned with what other packages do.

### CODE REVIEW

**Comment by maartenarnst** [comment]
Hi @mperego, would you have a moment to take a look at this PR? Thanks in advance!

**Review by mperego — APPROVED** [review]
Thanks for the fix. Looks good to me.

**Comment by maartenarnst** [comment]
Hi @mperego, thanks for approving! Would you have a moment to add the labels to move this forward? @romintomasetti and I don’t have permissions to set labels. Also, there seems to be something weird with a python script in the actions complaining about many MPI_COMM_WORLD even though this PR doesn’t touch on any of such lines.

**Comment by mperego** [comment]
@maartenarnst The MPI_COMM_WORLD issue should be fixed by this PR #12199.

**Comment by romintomasetti** [comment]
> Hi @mperego, thanks for approving! Would you have a moment to add the labels to move this forward? @romintomasetti and I don’t have permissions to set labels. Also, there seems to be something weird with a python script in the actions complaining about many MPI_COMM_WORLD even though this PR doesn’t touch on any of such lines.

@mperego What should we do here?

**Comment by romintomasetti** [comment]
@mperego I just did :wink:

**Review by mperego — DISMISSED** [review]

**Comment by mperego** [comment]
> @mperego I just did 😉 (I don't know why I created the branch based on a very old Trilinos version... Up to date now 😉)

thanks!

**Comment by sebrowne** [comment]
I recommend rebasing this branch given the 'develop' history change.

**Comment by mperego** [comment]
@romintomasetti I'm sorry, bad luck/timing with this PR. The history of the develop branch has been rewritten to remove large size files that were accidentally committed. Would you mind rebasing the branch on top of the develop branch and force push the changes? Thanks.

**Comment by maartenarnst** [comment]
Done :)

**Review by mperego — APPROVED** [review]

**Comment by mperego** [comment]
Thanks @maartenarnst and @romintomasetti, sorry for the troubles.

**Pull request merged**
