### PR TITLE
Xpetra: Fix triple matrix product for epetra builds

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/xpetra 

## Description
Fix issue with undefined variable when Epetra specialization of triple matrix product is used without Tpetra.

### CODE REVIEW

**Comment by lucbv** [comment]
@ibaned this should fix #2872

**Comment by ibaned** [comment]
Thanks @lucbv !

**Comment by brian-kelley** [comment]
@cgcgcg This fixed my test failures in #2868. Thanks!

**Comment by cgcgcg** [comment]
@trilinos/framework Any idea why the Pre-Merge Inspection does not pass? It's been hanging for over an hour, dismissing the review and re-approving does not seem to change anything.

**Pull request merged**
