### PR TITLE
Sacado: Fix clang -Wdtor-name warning

### PR DESCRIPTION
**Pull request by maartenarnst**
@trilinos/sacado

@etphipp

## Motivation

When compiling with `clang`, we get the warning:

```
/opt/Trilinos/.../include/Sacado_Fad_VectorImp.hpp:88:66: error: ISO C++ requires the name after '::~' to be found in the same scope as the name before '::~' [clang-diagnostic-dtor-name]
   88 | Sacado::Fad::Vector< OrdinalType, Sacado::Fad::DVFad<ValueType> >::
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                  ::Vector
11957 warnings and 1 error generated.
``` 

This PR solves this issue by putting this piece of code explicitly in the namespace `Sacado::Fad`. 

Note that I've tried fixing it the other way around by writing something like 

```
~Vector<OrdinalType, Sacado::Fad::DVFad<ValueType>()
```

That works with `clang`, but then `gcc` complains. The proposed fix seems to work for both `clang` and `gcc`.

### CODE REVIEW

**Review by etphipp — APPROVED** [review]

**Comment by maartenarnst** [comment]
Hi @etphipp. 

It seems one of the builds failed for this PR. Would you have a moment to take a look to have some info on the cause?

Perhaps just a word about this PR, which may seem a bit random :)

-> We compile our code with "warning as error". Because this issue is in a header file, it shows up as an error in our builds.

-> In our builds, it's actually `Intrepid2_OrientationTools.hpp` that we include, and this include leads, after a long sequence of includes, to including the Sacado header with this issue.

Thanks in advance!

**Comment by etphipp** [comment]
Sorry, I somehow missed the failed autotester.  There are several build errors in the Intel build, all of the form
```
icpc: error #10106: Fatal error in /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/intel-oneapi-compilers/2021.3.0/gcc/8.3.0/base/fptsktp/compiler/2021.3.0/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for ../Trilinos/packages/intrepid2/unit-test/MonolithicExecutable/AnalyticPolynomialsMatchTests.cpp (code 1)
```
They are all in Intrepid2 and Panzer.  It isn't clear to me how to resolve that.

**Comment by maartenarnst** [comment]
Ok, thanks. It’s not very clear indeed. Should we try a retest to make sure there’s a problem?

**Comment by etphipp** [comment]
Its a compiler problem, most likely a bug (which is not unusual for this compiler).  If you give me access to your branch I have two potential workarounds we can try.

**Comment by maartenarnst** [comment]
OK. Thanks a lot. I've just added you to our fork of Trilinos. I think GitHub should have sent an invite.

**Comment by etphipp** [comment]
Well, that didn't work.  Trying something else.

**Comment by etphipp** [comment]
Well, I tried a couple of things, but nothing seems to work with the Intel compiler.  I'm not sure what else to do.  Are you getting the warning that motivated this PR when compiling with '-pedantic'?  All I can suggest is removing that flag.

**Review by etphipp — APPROVED** [review]

**Comment by maartenarnst** [comment]
Thanks, Eric!

**Pull request merged**
