### PR TITLE
tribits: add CUDA::cuda_driver target in FindTPLCUDA.cmake

### PR DESCRIPTION
**Pull request by ndellingwood**
This change is necessary to prevent linker errors in codes calling to Cuda Driver API routines

Compatibility update need for kokkos, see kokkos/kokkos#6693

@trilinos/tribits @bartlettroscoe

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Review by bartlettroscoe — APPROVED** [review]
If this fixes the problem and works on the PR platforms, this should be fine.

After this merges to Trilinos, I will pull back to the TriBITS repo.

**Comment by ndellingwood** [comment]
Thanks @bartlettroscoe !

I tested these changes with a local Cuda build (Trilinos@develop with kokkos@develop branches) and confirmed it resolved the linker issues reported at https://github.com/kokkos/kokkos/issues/6693

**Comment by dalg24** [comment]
This is fixing the symptoms not the source.  The problem is that Kokkos should be dictating how to link against CUDA, not TriBITS.

**Comment by bartlettroscoe** [comment]
> This is fixing the symptoms not the source. The problem is that Kokkos should be dictating how to link against CUDA, not TriBITS.

The problem is the handling of external dependencies in the general case.  The TriBITS CUDA External Package/TPL must provide the union of features needed by all downstream packages.  In this case, Kokkos increased is dependence on CUDA so the CUDA External Package/TPL had to be updated.

**Pull request merged**
