### PR TITLE
kokkos-kernels: Fix #3493 (incorrect dot product results & segfaults for complex Tpetra::MultiVector)

### LINKED ISSUE #3493: Tpetra::MultiVector unit tests fail for Scalar=complex<double>, likely due to kokkos-kernels changes
https://testing.sandia.gov/cdash/testDetails.php?test=55163267&build=3970561

```
The following tests FAILED:
    1. MultiVector_double_default_local_ordinal_type_default_global_ordinal_type_Kokkos_Compat_KokkosSerialWrapperNode_ComplexDotOneColumn_UnitTest ... 
    56. MultiVector_int_int_std_complex0double0_Kokkos_Compat_KokkosSerialWrapperNode_NonContigView_UnitTest ... 
```
Further inspection shows large relative errors, so this isn't just an issue of needing to adjust the tolerance for complex numbers.  When I run the tests locally on a Mac, I get a segfault.

I'm curious if this is related to the recent kokkos-kernels update.

@trilinos/tpetra 

## Motivation and Context

Salinas depends on Tpetra with complex Scalar types.

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @trilinos/kokkos-kernels @kddevin @kyungjoo-kim 

## Description

`KokkosBlas::dot` for 1-D Views gave incorrect complex dot product results, due to incorrect assumptions about the Fortran ABI for complex return values.  This made Tpetra tests fail with complex enabled.  I fixed this by patching kokkos-kernels not to use the BLAS for those functions.

NOTE: I have not yet patched kokkos-kernels.  https://github.com/kokkos/kokkos-kernels/issues/307 discusses various ways to fix the issue.  I would prefer to let kokkos-kernels developers decide how to do that in a more permanent way.
 
## Motivation and Context

Salinas uses Tpetra with complex arithmetic.

## Related Issues

* Closes #3493
* Related to https://github.com/kokkos/kokkos-kernels/issues/307 

## How Has This Been Tested?

Mac, Clang, OpenMPI.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@mhoemmen Does the naive version (simple for loop over two views) in kokkoskernels fix the problem ?

**Comment by mhoemmen** [comment]
@kyungjoo-kim The fix in the PR just disables TPL support for complex-valued dot products, so it does whatever `KokkosBlas::dot` does if it doesn't have TPL support.

**Comment by mhoemmen** [comment]
@jhux2 I've cleaned up the tests already.  The tests are not the point; fixing the broken kokkos-kernels stuff is the point.  Thanks!

**Comment by mhoemmen** [comment]
@DrBooom Thanks for the review! :-D

> Is there a good reason to leave in the commented out code?

It reminds the kokkos-kernels developers that this is a temporary solution and that they will need to think of something more permanent (even if that just means not calling the TPL for complex dot products etc.).

**Comment by mhoemmen** [comment]
@micahahoward @prwolfe @rrdrake

**Pull request merged**
