### PR TITLE
MueLu interface aggregation

### LINKED ISSUE #2687: MueLu: structured/unstructured aggregation strategy
@trilinos/muelu 
@mayrmt @rstumin 

## Expectations
The goal is to be able to use different aggregation algorithm on different parts of the problem.

## Current Behavior
Currently structured and unstructured aggregation cannot be called together on the same problem.

## Motivation and Context
Some aerodynamic problems have structured mesh close to the object being modelled and unstructured meshes in the far field, having structured algorithm close to the object or in regions of shock wave can be beneficial as it will allow for local line smoothing.

## Definition of Done
- [x] Implement a new phase of unstructured aggregation that takes external input to create aggregates on an interface
- [x] Implement an aggregation factory that can decide at run-time which aggregation algorithm has to run locally.

## Related Issues
* Related to #2430 
* Part of #2230

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/muelu 

## Description
These commits implement hybrid aggregation which is used to coarsen using both structured and unstructured aggregation at the same time.

## Motivation and Context
This work is part of ongoing feature enhancements required to implement HHG and block structured algorithms in MueLu

## Related Issues

* Closes #2687 
* Blocks #2230 

## How Has This Been Tested?
A new unit test has been created to test the new factory. Also a subsequent PR to trilinosCouplings will add larger examples showing more capabilities of this algorithm. The separation into two PR should allow us to track problems/bugs more easily.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

**Comment by lucbv** [comment]
@trilinos/framework I think the last three builds are passing the auto-tester yet it reports a failure on github. Can you check what happened with the auto-tester? If there is an error I'm happy to fix it but I can't find it...

**Comment by allevin** [comment]
@lucbv @trilinos/framework 

The builds/tests according to Jenkins are failing (hence why the autotester is reporting the failure).

I looked at the 4.9.3 build #936,938, and 940 and see this:

```
    ..................................................  Size: 4299K
    ..................................................  Size: 4350K
    ..................................................  Size: 4399K
    ..................................................  Size: 4449K
    ..................................................  Size: 4500K
    ..................................................  Size: 4550K
    ..................................................  Size: 4599K
    ..................................................  Size: 4650K
    ..................................................  Size: 4700K
    ..................................................  Size: 4750K
    ...... Size of output: 4756K
Build succeeded.
build submit error = 0
Starting testing step.
CMake Error at /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/TFW_testing_single_configure_prototype/simple_testing.cmake:193 (message):
  Test failed with error -1


test submit error = 0
File upload submit error = 0
Single configure/build/test failed. The error code was: 255
Build step 'Execute shell' marked build as failure
Finished: FAILURE

```

The 4.8.4 and Intel builds are also reporting similar failures with simple_testing.cmake.  

Hopefully this helps you out.

**Comment by prwolfe** [comment]
I looked into the gcc 4.9.3 build # 943 which has a clean CDash line and failed in Jenkins.  It had communication issues in Jenkins itself

> Command close created at
> 	at hudson.remoting.Command.<init>(Command.java:60)
> 	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1216)
> 	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1214)
> 	at hudson.remoting.Channel.close(Channel.java:1389)
> 	at hudson.remoting.Channel.close(Channel.java:1356)
> 	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1221)
> Caused: hudson.remoting.Channel$OrderlyShutdown
> 	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1222)
> 	at hudson.remoting.Channel$1.handle(Channel.java:557)
> 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:83)
> Caused: java.io.IOException: Backing channel 'ascic142-trilinos' is disconnected.
> 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:192)

Not sure we could catch that, but I will look into it.

**Comment by lucbv** [comment]
@allevin thanks for checking the output!
@prwolfe thanks for confirming this, it was my suspicion based on the auto-tester output, thankfully the following round of testing was successful and I was able to merge without major delays.
It seems that if such an error is caught the only reasonable action is to try to rerun the auto-tester anyway... we probably have to live with it, although maybe not deleting the build directory if such an event is detected could accelerate the re-run quite a bit.

**Pull request merged**
