### PR TITLE
Framework: Match CPU parallelism with AT1 args

### PR DESCRIPTION
**Pull request by sebrowne**
@trilinos/framework 

## Motivation
Will allow us to better compare AT1 vs. AT2 performance and evaluate if we're ready to move builds onto the new system.

### CODE REVIEW

**Review by achauphan — APPROVED** [review]

**Comment by sebrowne** [comment]
First pass (this PR itself) shows near-perfect timing comparisons:

```
 GCC        | AT1 | AT2 |     GCC+OpenMPI | AT1 | AT2 | 
=========================     =========================
Build times | 9m  | 3m  |     Build times | 20m | 49m |
Test times  | 8m  | 5m  |     Test times  | 14m | 43m |
```

**Comment by ccober6** [comment]
> First pass (this PR itself) shows excellent timing comparisons:
> 
> ```
> GCC         | AT1 | AT2 |     GCC+OpenMPI | AT1 | AT2 | 
> =========================     =========================
> Build times | 9m  | 3m  |     Build times | 20m | 49m |
> Test times  | 8m  | 5m  |     Test times  | 14m | 43m |
> ```

@sebrowne, am I reading this correctly that GCC+OpenMPI is 2-3x slower with AT2?

**Comment by sebrowne** [comment]
> @sebrowne, am I reading this correctly that GCC+OpenMPI is 2-3x slower with AT2?

Doh, no, I flipped the axes on accident.  I fixed it in my original comment.

**Comment by ccober6** [comment]
Ah, very good!

**Pull request merged**
