### PR TITLE
MueLu: cleaning unit-tests and code for build with Scalar=float

### LINKED ISSUE #3946: MueLu: Scalar=float build errors
@trilinos/muelu 
Reported by @davydden in [this comment](https://github.com/trilinos/Trilinos/issues/3572#issuecomment-442327278).  Here are the reported build errors:

```
    8158    In file included from /Users/davydden/spack/var/spack/stage/trilinos-develop-p6xmhguuqtomai5fy4a36qmnn4wpqzfq/Trilinos/spack-build/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_Zoltan2Interface.cpp:55:
  >> 8159    /Users/davydden/spack/var/spack/stage/trilinos-develop-p6xmhguuqtomai5fy4a36qmnn4wpqzfq/Trilinos/packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp:197:24: error: no matching constructor for initialization of 'InputAdapterType' (aka 'XpetraMultiVe
             ctorAdapter<MultiVector<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >')
     8160          InputAdapterType adapter(coords, weights, strides);
     8161                           ^       ~~~~~~~~~~~~~~~~~~~~~~~~
     8162    /Users/davydden/spack/var/spack/stage/trilinos-develop-p6xmhguuqtomai5fy4a36qmnn4wpqzfq/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:45: note: in instantiation of member function 'MueLu::Zoltan2Interface<float, int, int, Kokkos::Compat::KokkosDevi
             ceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Build' requested here
     8163      TPETRA_INSTANTIATE_SLGN_NO_ORDINAL_SCALAR(MUELU_ETI_GROUP)
     8164                                                ^
     8165    /Users/davydden/spack/var/spack/stage/trilinos-develop-p6xmhguuqtomai5fy4a36qmnn4wpqzfq/Trilinos/packages/zoltan2/src/input/Zoltan2_XpetraMultiVectorAdapter.hpp:119:3: note: candidate constructor not viable: no known conversion from 'std::vector<const double
              *>' to 'std::vector<const scalar_t *> &' (aka 'vector<const float *> &') for 2nd argument
```

It's possible that this could block Sierra promotion, since they enable Scalar=float.

### PR DESCRIPTION
**Pull request by lucbv**
@jhux2 @csiefer2 @cgcgcg please look at how tolerances have been modified in various unit-tests and let me know if it seems reasonable to you before we merge this!

@trilinos/muelu 

## Description
This work primarily switches convergence criteria in tests from being hard coded values to Scalar epsilon values using `Teuchos::ScalarTraits<magnitude_type>::eps()`.
The tests are still passing for both `Scalar=double` and `Scalar=float`.
The main issue is the convergence behavior observed in the `Hierarchy_Iterate` unit-tests.

## Motivation and Context
Cleaning up some code before closing issue #3946 

## Related Issues

* Closes #3946
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## How Has This Been Tested?
I did a local build with `Trilinos_ENABLE_Float=ON`, observed good compilation but tests are not always passing. More work would be needed to get a clean float build.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by lucbv** [comment]
@mhoemmen I see a strange Tpetra error in the last run of the auto-tester on Cuda.
Here is the error message:
```
p=0: *** Caught standard std::exception of type 'std::invalid_argument' :

 /home/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp:1034:
 
 Throw number = 4
 
 Throw test that evaluated to true: condition
 
 unpackAndCombineIntoCrsArrays: CRS_rowptr[last] = 3971!= mynnz = 3228.
```
I am fairly confident that my changes should not affect the matrix in the unit-test.
I will wait for a rebuild/retest before concluding anything but it looks a bit odd...

**Comment by mhoemmen** [comment]
@lucbv wrote:
> I see a strange Tpetra error in the last run of the auto-tester on Cuda.

Does this only happen for `Scalar=float`?

@tjfulle FYI

**Comment by lucbv** [comment]
@mhoemmen asked:
> Does this only happen for `Scalar=float`?
I actually do not think that the auto-tester instantiate on float so I would say no, it happens for double.
Here is the ETI output from MueLu:
```
-- MueLu ETI support enabled
-- <float,   int, int>       : OFF
-- <double,  int, int>       : ON
-- <double,  int, long>      : OFF
-- <double,  int, long long> : ON
-- <complex, int, int>       : OFF
-- HAVE_MUELU_SERIAL       : ON
-- HAVE_MUELU_PTHREAD      : OFF
-- HAVE_MUELU_OPENMP       : OFF
-- HAVE_MUELU_CUDA         : ON
```

**Comment by tjfulle** [comment]
Are the changes in the code against the most recent develop?  In #5268 Tpetra gained the ability to resize a matrix with `StaticProfile` during import/export operations.  The changes shouldn't affect code paths that end up in `unpackIntoCrsArrays`, but I could be wrong.

**Comment by lucbv** [comment]
@tjfulle I think that the auto-tester does bring the tested branch up-to-date with develop before it starts to build so the resizable matrix should be in at that point.
Interestingly this happens only for the cuda build even though there is no kokkos related changes.

**Comment by lucbv** [comment]
@mhoemmen @tjfulle it seems that on the latest round of auto-testing the problem disappeared...
I hope this was an unfortunate transient problem but I'll keep an eye on it.
Thanks for your help!

**Pull request merged**
