### PR TITLE
Removed warnings

### PR DESCRIPTION
**Pull request by bathmatt**
@trilinos/<teamName>

### CODE REVIEW

**Review by mperego — APPROVED** [review]
It looks good. Thanks!

**Comment by CamelliaDPG** [comment]
Thanks, @bathmatt!

**Comment by bathmatt** [comment]
@jmgate do you wanna pull this into our trilinos?  do you know how long the pull request tester takes?  Thinking getting trilinos on line would be worth it,

**Comment by CamelliaDPG** [comment]
@bathmatt, my recent experience with the PR tester is that it takes 2-3 hours from the time it says "STARTING".  So it probably will be done in the next hour and a half or so.

**Comment by jmgate** [comment]
@bathmatt, do we need this update today (manual), or is tonight sufficient (automatic)?

**Pull request merged**
