### PR TITLE
teuchos: rename namespace Profiling->Tools for kokkos-tools

### PR DESCRIPTION
**Pull request by ndellingwood**
compatibility update with kokkos/kokkos#7096
avoid "conflicts with a previous declaration" errors and undefined linker issues

@trilinos/teuchos @bartlettroscoe 

## Motivation

compatibility update with kokkos/kokkos#7096
avoid "conflicts with a previous declaration" and undefined linker issues

* Closes kokkos/kokkos#7101

## Testing
Local build with kokkos/kokkos@53b3202

### CODE REVIEW

**Comment by ndellingwood** [comment]
I'm not sure why the `extern` usage was originally needed (maybe past legacy api needs?), referencing when it was added here https://github.com/trilinos/Trilinos/pull/2888
@bartlettroscoe or @csiefer2 (#2888 author), would you be fine with @masterleinad 's suggestion above?

**Comment by masterleinad** [comment]
Just to be clear: either solution is fine with me. I don't think we considered that someone would forward declare `Kokkos::Profiling::pushRegion/popRegion` in https://github.com/kokkos/kokkos/pull/7096.

**Comment by ndellingwood** [comment]
@rppawlo are you able to review? Relatively minor changes, but needed for integration testing with kokkos core and kernels develop branches

**Review by rppawlo — APPROVED** [review]

**Comment by rppawlo** [comment]
Thanks for updating this @ndellingwood !

**Pull request merged**
