### PR TITLE
MiniTensor: add doxygen site

### PR DESCRIPTION
**Pull request by mayrmt**
@lxmota 

## Motivation

We are exploring to use `MiniTensor` in our own code to replace our implementation of tensor algebra with a proper tensor library. To make it easer to explore the API of `MiniTensor`, a Doxygen site seems useful. This PR adds a basic Doxygen configuration and defines a build target to create the Doxygen site via `make doc_minitensor` (workflow adopted from the MueLu Doxygen setup).

## Stakeholder Feedback

Hopefully useful to users of `MiniTensor`

## Testing

I ran `make doc_minitensor` locally and inspected the generated html sites manually.

### CODE REVIEW

**Review by lxmota — APPROVED** [review]
Looks good to me. Thank you for adding this.

**Comment by mayrmt** [comment]
There are no explicit code owners for the `minitensor` package.

> Here's the (commented) line form the CODEOWNERS file:
> ```
> #/packages/minitensor/        @trilinos/
>```

Is there any special approval required to merge these changes?

**Comment by lxmota** [comment]
> There are no explicit code owners for the `minitensor` package.
> 
> > Here's the (commented) line form the CODEOWNERS file:
> > ```
> > #/packages/minitensor/        @trilinos/
> > ```
> 
> Is there any special approval required to merge these changes?

I don't think there is a need for special approval. The merge should happen automatically since you tagged the PR with AT:AUTOMERGE. I'm mentioning @mperego, who owns Trilinos discretizations, just in case.

**Comment by mperego** [comment]
@lxmota is right, if the tests pass, the branch should be automatically merged, since it has already been approved.

**Pull request merged**
