### PR TITLE
Switch default submit to trilinos-cdash.sandia.gov and https (#10876)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @trilinos/framework

### Description

As per #10876, this changes the default CDash submit location from the open CDash site `testing.sandia.gov/cdash/` to the internal CDash site `trilinos-cdash.sandia.gov`.  I also left the secondary submits going to `testing-dev.sandia.gov/cdash/` as that site is going to be moved internally.

### How was this tested?

I tested this through a throw-away-integration-test-branch [10807-kokkos-kernels-cublas-titb](https://github.com/bartlettroscoe/Trilinos/tree/10807-kokkos-kernels-cublas-titb) as part of trying to reproduce some build errors as documented in https://github.com/trilinos/Trilinos/issues/10836#issuecomment-1216017031.  Which submitted to:

* https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=hpws055.sandia.gov&field2=buildname&compare2=61&value2=Linux-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug&field3=buildstamp&compare3=61&value3=20220815-0128-Experimental
* https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascicgpu17&field2=buildname&compare2=61&value2=Linux-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug&field3=buildstamp&compare3=61&value3=20220815-0334-Experimental

and

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=hpws055.sandia.gov&field2=buildname&compare2=61&value2=Linux-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug&field3=buildstamp&compare3=61&value3=20220815-0128-Experimental
* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascicgpu17&field2=buildname&compare2=61&value2=Linux-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug&field3=buildstamp&compare3=61&value3=20220815-0334-Experimental

### CODE REVIEW

**Review by e10harvey — APPROVED** [review]
Thanks, Ross!

**Comment by bartlettroscoe** [comment]
FYI: With the manual merge of of this branch to the 'atdm-nightly' branch, we are not seeing the ATDM Trilinos builds at:

* https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&date=2022-08-17

or

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2022-08-17

@e10harvey, are the ATDM Trilinos builds being run out of?

**Comment by e10harvey** [comment]
> @e10harvey, are the ATDM Trilinos builds being run out of?

@bartlettroscoe: Not tracking. Can you please rephrase?

**Comment by bartlettroscoe** [comment]
> > @e10harvey, are the ATDM Trilinos builds being run out of?
> 
> @bartlettroscoe: Not tracking. Can you please rephrase?

@e10harvey, what Jenkins sites and what Jenkins jobs are currently running the ATDM Trilinos builds?  I need to look at what those Jenkins jobs are doing to see what is happening when they try to submit to CDash.

**Comment by e10harvey** [comment]
> @e10harvey, what Jenkins sites and what Jenkins jobs are currently running the ATDM Trilinos builds? I need to look at what those Jenkins jobs are doing to see what is happening when they try to submit to CDash.

Gotcha. They are in the same place you previously maintained them.

**Comment by bartlettroscoe** [comment]
> > @e10harvey, what Jenkins sites and what Jenkins jobs are currently running the ATDM Trilinos builds? I need to look at what those Jenkins jobs are doing to see what is happening when they try to submit to CDash.
> 
> Gotcha. They are in the same place you previously maintained them.

@e10harvey, the seem to all be missing:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/

**Comment by bartlettroscoe** [comment]
@e10harvey, I am outside of my scope of work here.  I am going to back out this change in the 'atdm-nightly' branch and leave it to the @trilinos/framework team to figure out what to do with this PR and the ATDM Trilinos builds.  I just demonstrated [above](https://github.com/trilinos/Trilinos/pull/10887#issue-1339694868) that the basics are addressed with this PR.

**Comment by e10harvey** [comment]
> @e10harvey, the seem to all be missing:

@bartlettroscoe: Ok, please check your permissions.

**Comment by e10harvey** [comment]
> @e10harvey, I am outside of my scope of work here. I am going to back out this change in the 'atdm-nightly' branch and leave it to the @trilinos/framework team to figure out what to do with this PR and the ATDM Trilinos builds. I just demonstrated [above](https://github.com/trilinos/Trilinos/pull/10887#issue-1339694868) that the basics are addressed with this PR.

Ok, thanks Ross!

**Pull request closed without merging**
