### PR TITLE
Stokhos:  Remove use of deprecated code

### PR DESCRIPTION
**Pull request by etphipp**
Fixes build errors when Tpetra deprecated code is turned off.

### CODE REVIEW

**Review by kliegeois — DISMISSED** [review]
It looks good to me.

**Comment by etphipp** [comment]
Looks like the last run of the autotester did not include my latest commit.

**Comment by etphipp** [comment]
@kliegeois Can you re-review?

**Comment by kliegeois** [comment]
@etphipp yes, sure! I was waiting for the tests to pass.

**Review by kliegeois — APPROVED** [review]
Looks good to me; it would have been best without the 2 casts but I guess that there are no ways around that here.

**Pull request merged**
