### PR TITLE
Tpetra,Ifpack2,Stokhos: Fix #2290

### LINKED ISSUE #2290: Tpetra: Purge 'classic' template parameter
Purge Tpetra's `classic` template parameter.

WARNING: This will break code (e.g., Nalu) that does forward declarations of Tpetra classes.

@trilinos/tpetra 

## Motivation and Context

Use of the 'classic' template parameter was already deprecated in Trilinos 12.0, and we need to get rid of this in order to move ahead with FY18 Tpetra plans.  This will also facilitate using a type alias to let us get rid of other template parameters, like `GlobalOrdinal` and `Node`.

### PR DESCRIPTION
**Pull request by mhoemmen**
Fix #2290.  I only made tiny changes to Ifpack2 (edited 23 Feb 2018: and Stokhos).  Almost all the changes were in Tpetra.

@trilinos/tpetra @trilinos/ifpack2 (ed. 23 Feb 2018: @trilinos/stokhos )

WARNING: This will break code (e.g., Nalu) that does forward declarations of Tpetra classes.

### CODE REVIEW

**Comment by mhoemmen** [comment]
There appeared to be a missing header file in Panzer or Drekar.  I'll take a look again.

**Comment by rppawlo** [comment]
> There appeared to be a missing header file in Panzer or Drekar. I'll take a look again.

It's probably that the testing machine needs the build directory wiped due to ETI changes.

**Comment by mhoemmen** [comment]
@rppawlo Good point; is that something I can do?

**Comment by rppawlo** [comment]
No - you need @jwillenbring  to go in and clean the build. This issue is from a change in early January, but since we can't control which machine jenkins launches the test, we keep hitting these stale build tress that are now corrupt. Just relaunching the test and getting lucky in not hitting that machine again usually gets you through this. Jim is working on a solution to allow us to specify if a build needs to be cleaned out in the autotester so this doesn't hit us in the future.

**Comment by jwillenbring** [comment]
I went in and wiped out both current workspaces.

**Comment by jwillenbring** [comment]
The build failed again. This is what I am seeing in the console:
<pre>
[ 91%] Building CXX object packages/stokhos/src/CMakeFiles/stokhos_tpetra.dir/Tpetra_MultiVector_UQ_PCE_Serial.cpp.o
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/tpetra/core/src/Tpetra_MultiVector.hpp:1:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/stokhos/src/Tpetra_MultiVector_UQ_PCE_Serial.cpp:47:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp:72:56: error: redeclared with 4 template parameters
   template<class S, class LO, class GO, class N> class Vector;
                                                        ^
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_ETI_Helpers_UQ_PCE.hpp:43:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/stokhos/src/Tpetra_MultiVector_UQ_PCE_Serial.cpp:45:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp:314:61: note: previous declaration ‘template<class S, class L, class G, class N, bool <anonymous> > class Tpetra::Vector’ used 5 template parameters
   template <class S, class L, class G, class N, bool> class Vector;
                                                             ^
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/tpetra/core/src/Tpetra_MultiVector.hpp:1:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/stokhos/src/Tpetra_MultiVector_UQ_PCE_Serial.cpp:47:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp:75:56: error: redeclared with 4 template parameters
   template<class S, class LO, class GO, class N> class MultiVector;
                                                        ^
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_ETI_Helpers_UQ_PCE.hpp:43:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/stokhos/src/Tpetra_MultiVector_UQ_PCE_Serial.cpp:45:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp:313:61: note: previous declaration ‘template<class S, class L, class G, class N, bool <anonymous> > class Tpetra::MultiVector’ used 5 template parameters
   template <class S, class L, class G, class N, bool> class MultiVector;
                                                             ^
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/tpetra/core/src/Tpetra_MultiVector.hpp:1:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/stokhos/src/Tpetra_MultiVector_UQ_PCE_Serial.cpp:47:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp:139:40: error: wrong number of template arguments (4, should be 5)
   deep_copy (MultiVector<DS, DL, DG, DN>& dst,
                                        ^
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_ETI_Helpers_UQ_PCE.hpp:43:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/stokhos/src/Tpetra_MultiVector_UQ_PCE_Serial.cpp:45:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp:313:61: error: provided for ‘template<class S, class L, class G, class N, bool <anonymous> > class Tpetra::MultiVector’
   template <class S, class L, class G, class N, bool> class MultiVector;
                                                             ^
</pre>
...

**Comment by mhoemmen** [comment]
@jwillenbring Thanks so much!  I know exactly what to fix now -- the instantiations in Stokhos.

**Comment by mhoemmen** [comment]
Marked as [WIP] since this is not done yet.

**Comment by mhoemmen** [comment]
I just pushed the Stokhos fixes as a separate commit.  I've tested the build, but would like the automatic pull tester to try it too, in order to exercise @jwillenbring 's latest work.

**Comment by mhoemmen** [comment]
FYI I get one test failure -- `Stokhos_TpetraCrsMatrixUQPCEUnitTest_OpenMP_MPI_4` -- but I want to see what the autotester says.

**Comment by mhoemmen** [comment]
I get the following output right before the above test segfaults:
```
45:   Matrix filtering (MueLu::FilteredAFactory)
45:    Build (MueLu::CoalesceDropFactory)
45:     Build (MueLu::AmalgamationFactory)
45:     lightweight wrap = 1
45:     algorithm = "classical": threshold = [ 0 ], blocksize = 1
45:     Detected 2 Dirichlet nodes
45:     Number of dropped entries in unamalgamated matrix graph: 0/26 (0%)
45:    Filtered matrix is not being constructed as no filtering is being done
45:   Build (MueLu::TentativePFactory)
45:    Build (MueLu::UncoupledAggregationFactory)
45:     BuildAggregates (Phase - (Dirichlet))
45:       aggregated : 2 (phase), 2/10 [20.00%] (total)
45:       remaining  : 8
45:       aggregates : 0 (phase), 0 (total)
45:     BuildAggregates (Phase 1 (main))
45:       aggregated : 6 (phase), 8/10 [80.00%] (total)
45:       remaining  : 2
45:       aggregates : 3 (phase), 3 (total)
45:     BuildAggregates (Phase 2a (secondary))
45:       aggregated : 0 (phase), 8/10 [80.00%] (total)
45:       remaining  : 2
45:       aggregates : 0 (phase), 3 (total)
45:     BuildAggregates (Phase 2b (expansion))
45:       aggregated : 1 (phase), 9/10 [90.00%] (total)
45:       remaining  : 1
45:       aggregates : 0 (phase), 3 (total)
45:     BuildAggregates (Phase 3 (cleanup))
45:       aggregated : 1 (phase), 10/10 [100.00%] (total)
45:       remaining  : 0
45:       aggregates : 1 (phase), 4 (total)
45:     "UC": MueLu::Aggregates{nGlobalAggregates = 4}
45:    Build (MueLu::CoarseMapFactory)
45:   Using cached max eigenvalue estimate
45:   Prolongator damping factor = [ 0.72 ] ([ 1.33 ] / [ 1.84 ])
```

**Comment by mhoemmen** [comment]
Hm, above failing test is a known issue: https://github.com/trilinos/Trilinos/issues/2254

**Comment by mhoemmen** [comment]
Huh, I guess it passed.  Does the pull request tester not exercise Stokhos?  Anyway, I did test w/ Stokhos (OpenMP enabled even) and only the one test failed that was failing before (see above comment), so I think this is OK to merge.

**Comment by etphipp** [comment]
The MueLu commit that caused this Stokhos test to fail was reverted last week.  Do you not have that revert in your branch?

**Comment by mhoemmen** [comment]
@etphipp wrote:
> The MueLu commit that caused this Stokhos test to fail was reverted last week. Do you not have that revert in your branch?

That's weird, I was pretty sure I had rebased against develop.... I tested w/ OpenMP enabled; could that have made a difference?

**Comment by etphipp** [comment]
I looked into this and the issue you are seeing is different from the one in #2254.  The seg-fault you are seeing is due to POD assumptions in the jacobi_A_B_newmatrix_LowThreadGustavsonKernel() which is selected by default when the node is OpenMP.  I'll open a separate issue for that.

I have no idea how long this has been failing.  Apparently, as far I can tell, there is no regular testing of Stokhos with anything other than Serial.

**Comment by jwillenbring** [comment]
@mhoemmen 

> Does the pull request tester not exercise Stokhos? Anyway, I did test w/ Stokhos (OpenMP enabled even) and only the one test failed that was failing before (see above comment), so I think this is OK to merge.

Yes, Stokhos was tested. 75/75 tests passed:

[https://testing-vm.sandia.gov/cdash/viewTest.php?buildid=3331370](https://testing-vm.sandia.gov/cdash/viewTest.php?buildid=3331370)

**Comment by mhoemmen** [comment]
@etphipp wrote:
> Apparently, as far I can tell, there is no regular testing of Stokhos with anything other than Serial.

Hm, is that true of Sacado as well?  (I guess "Sacado through Tpetra" only gets tested in Stokhos, right?)  I can think of at least two applications that use Sacado + (OpenMP or CUDA).

**Comment by etphipp** [comment]
Looking through the dashboard, there are a couple of builds that appear to enable OpenMP (based on their name), but no tests are run for Sacado or Stokhos.  And regarding the pull request tester, I think it only tests serial, which is why this error was not caught.

**Comment by jwillenbring** [comment]
@etphipp 
@trilinos/framework 

> Looking through the dashboard, there are a couple of builds that appear to enable OpenMP (based on their name), but no tests are run for Sacado or Stokhos. And regarding the pull request tester, I think it only tests serial, which is why this error was not caught.

The pull request tester tests MPI, not serial, but it does not enable OpenMP.

**Pull request merged**
