### PR TITLE
Tempus: Identify usage of FSAL

### LINKED ISSUE #8105: Tempus: Identify usage of FSAL
## Enhancement
@trilinos/tempus 

Identify a Stepper as able to use FSAL (useFSAL=true), not use FSAL (useFSAL=false), or both.

### PR DESCRIPTION
**Pull request by ccober6**
* Identify a Stepper as able to use FSAL (useFSAL=true), not use
   FSAL (useFSAL=false), or both, through the set functions
   setUseFSALTrueOnly(), setUseFSALFalseOnly(), or setUseFSAL(),
   respectively.
 * There are just two Steppers that only use useFSAL=true, Trapezoidal
   and NewmarkImplicitAForm.  This is primarily due to wanting to only
   have one ODE evaluation per time step.
 * Most Steppers have useFSAL=false as they do not meet the
   requirements for FSAL.  If the application tries to set
   it to true, a warning is given but will remain useFSAL=false.
 * Currently we have 6 Steppers that can set useFSAL to either
   true or false:
    - ForwardEuler
    - NewmarkExplicitAForm
    - RK Forward Euler
    - Bogacki-Shampine
    - EDIRK 2-Stage Theta
    - RK Trapezoidal Rule

   There are two advantages for useFSAL=true:
    - x and xDot are at the same time level at the end of the timestep
    - Save an evaulation of the ODE
   However this does require the ICs to be consistent, i.e., x and
   xDot satisfy xDot_0 = f(x_0,t=0).  By default these Steppers have
   useFSAL=true.  This is why these Steppers have the IC consistency
   turned on by default (ICConsistency = "Consistent").
 * OperatorSplit should, in general, set useFSAL=false as each operator
   will change xDot, but there can be situations where useFSAL=true could
   be useful.  So it can be set to either true or false.
 * Removed getUseFSALDefault(), getICConsistencyDefault() and
   getICConsistencyCheckDefault().  Defaults are now set explicitly
   in the Stepper constructors.
 * Fixed a few situations where FSAL should not be used if the previous
   time step failed.
 * Changed and added tests to explicitly test (previous testing was
   "hidden").
   - useFSAL = true and false
   - ICConsistency = "Consistent" and ICConsistencyCheck = true

Miscellaneous
 * Removed tabs from files.

@trilinos/tempus 

## Motivation
Better identify each Steppers FSAL capabilities.

* Closes #8105 

## Stakeholder Feedback
This was a request from @ikalash. 

## Testing
All current tests passes, and additional tests added to cover FSAL settings.

### CODE REVIEW

**Comment by ccober6** [comment]
@ikalash @michael-a-hansen @sconde Theses changes could effect Albany, SPARC, Drekar and EMPIRE.  Before committing them could you check to see if there is any issues with it.  I will check EMPIRE.  I will turn on the autotester to get results and WIP to make sure it does not get through until we are ready.

**Comment by ccober6** [comment]
@sconde you can hold off on the review as there is a failure I can not reproduce at the moment on my Mac.  I will likely need to commit a fix and then get it reviewed... :)

**Review by sconde — APPROVED** [review]

**Comment by ccober6** [comment]
So EMPIRE is ready for this PR.

@ikalash @michael-a-hansen @sconde Have you had a chance to test this?

**Comment by sconde** [comment]
Looks good on my end.

**Comment by michael-a-hansen** [comment]
Looks good on the SPARC side. Thanks for the notification!

**Comment by ccober6** [comment]
@michael-a-hansen Thanks for the confirmation that everything is good on the SPARC side!

**Comment by ccober6** [comment]
@ikalash Sorry to pester, but will you have a chance to check this branch?  Thanks.

**Comment by sconde** [comment]
So I build Piro and ran the tests during my review. My understanding is that Albany uses Tempus through Piro.

**Comment by ikalash** [comment]
@ccober6 : Yes, absolutely.  I was interested in the PR when I saw it opened per our earlier discussion about FSAL, but I was on vacation at the time.  I am still getting caught up, but I will look at this and test Albany this week.

**Comment by ccober6** [comment]
@ikalash Oh, sorry.  Hope you had a great vacation!  I guess it is a down side to communicating through the PR; we do not see any out of office notices.  Thanks for the update, and let us know when you have tested this.  Thanks.

**Comment by ikalash** [comment]
I just looked at this PR and tested Albany.  Everything is clean in Albany.  It looks good except I have a qualm with one thing: 

> * Most Steppers have useFSAL=false as they do not meet the
>   requirements for FSAL.  If the application tries to set
>   it to true, a warning is given but will remain useFSAL=false.

We talked about this already @ccober6 , I know.  I would say the right thing to do is if a user tries to set useFSAL=false and the stepper does not support that, the code should throw not print a warning.  The reasoning is as follows.  If a user is setting useFSAL=false, it is likely intentional, as in general users will just use whatever is default, not knowing what the option means.  A lot of users don't really look at warnings in their output, so they may think useFSAL=false is being used when it is not.  Just my two cents.  Perhaps other Tempus folks can weigh in, e.g., @sconde ?

**Comment by ccober6** [comment]
Yeah, I know we talked about this, and I have been on the fence in situations like this.  I believe you would suggest instead of a warning message, you should suggest error'ing out.  Most users have suggested in situations like this, they want the code to continue unless it is a fatal error.  The use case goes ... My job has been sitting in the queue days/weeks and it error'ed out on input with a value that does not effect the solution.  They do not want this to happen.

So for the case of useFSAL, whether you use useFSAL=true or useFSAL=false, the solution will be exactly the same, so long as the ICs are consistent (i.e., x and xDot satisfy xDot_0 = f(x_0,t_0) or f(x_0,xDot_0,t_0)).  The two main advantages of useFSAL=true are
 1. Can save a function evaluation each timestep.
 1. x and xDot will be at the same time level at the end of the timestep.
The first is a computational savings, and the latter may effect diagnostics (so there is some question if this effects the application's usage of the solution). 

Another piece I tried to factor in here is some applications additional do not want even warning/informational messages printed from TPLs.  I could not quite go that far.  

Hopefully, this explains the current reasoning.  Let us know if you have any suggestions.

**Comment by ikalash** [comment]
@ccober6 : I see.  I guess I was thinking of the Albany use case where one of the options doesn't work properly with our BC implementation, but that is on us.

**Comment by ccober6** [comment]
Yeah, getting back in the mind frame of your situation, where the BCs are being "set" within the ModelEvaluator and is dependent on what the currentState->getXDot() is, can cause issues.  I think you are right that Tempus will not have this knowledge, and the applications need to cover that situation.

**Pull request merged**
