### PR TITLE
MueLu: rocketman, you task me

### PR DESCRIPTION
**Pull request by jhux2**
Auto-PR for SHA 72df647

---
This change is [Reviewable](https://reviewable.io/reviews/trilinos/trilinos/3718)

### CODE REVIEW

**Comment by csiefer2** [comment]
@trilinos/framework Compiler license issues persist.  #autotesterissad

**Comment by jhux2** [comment]
Why is this PR even trying to get a compiler license?  Aren't these sorts of changes supposed to avoid wasting compile cycles?!

**Comment by csiefer2** [comment]
> Why is this PR even trying to get a compiler license? Aren't these sorts of changes supposed to avoid wasting compile cycles?!

Yes.  Give in to your hatred.

**Comment by jhux2** [comment]
> > Why is this PR even trying to get a compiler license? Aren't these sorts of changes supposed to avoid wasting compile cycles?!
> 
>> Yes. Give in to your hatred.

It tasks me. It tasks me, and I shall have it. I'll chase it round the Moons of Nibia and round the Antares Maelstrom and round Perdition's flames before I give it up!

**Comment by prwolfe** [comment]
> Why is this PR even trying to get a compiler license? Aren't these sorts of changes supposed to avoid wasting compile cycles?!

It's the configure step making sure it has a working compiler.

**Comment by jhux2** [comment]
> It's the configure step making sure it has a working compiler.

Ah, that makes sense, thanks.

**Pull request merged**
