### PR TITLE
Muelu tpetra dep

### PR DESCRIPTION
**Pull request by bathmatt**
This is to get muelu compiling without tpetra deprcated code

### CODE REVIEW

**Review by cgcgcg — DISMISSED** [review]
Let's see what the AT thinks.

**Comment by bathmatt** [comment]
you'll have to approve to get the at to work btw,
it's cuz i'm using a foreign repo

**Review by cgcgcg — DISMISSED** [review]
re-approve

**Comment by bathmatt** [comment]
@cgcgcg this is based off two other MR which are in flight, one for xpetra
and one for zoltan2.  I won't merge this until those go in and I can rebase
off those two

**Review by jhux2 — APPROVED** [review]
Approving to allow for testing.

**Review by GrahamBenHarper — DISMISSED** [review]
re-approve for testing

**Review by jhux2 — APPROVED** [review]
Loosing the AT hounds.

**Comment by bathmatt** [comment]
@jhux2 closing this in favor of one I can test since no NGA staff but me are working the issue

**Pull request closed without merging**
