### PR TITLE
KokkosKernels: Update d2_graph_color following deprecation

### PR DESCRIPTION
**Pull request by ndellingwood**
Addresses issue #4829

@trilinos/kokkos-kernels

### CODE REVIEW

**Comment by ndellingwood** [comment]
@william76 Here is a PR with a fix for #4829, testing didn't pick up the change because deprecated code is enabled by default. This change should fix it either way and matches kokkos-kernels' develop branch. If you see anything else that should be changed you can discard this PR or work off of this branch of Trilinos (I pushed to the Trilinos repo so it can be used as a collaborative branch). Thanks!

**Comment by william76** [comment]
Thanks @ndellingwood 

Is this something that needs to get reflected back into Kokkos-Kernels?  

If you haven't already, I can put in a PR today to get these changes into Kokkos-Kernels.

Also, I didn't catch this in my local testing and in the PR tests of Trilinos... do you know what option I could have enabled in Trilinos that would have caught this?  Is it just a matter of disabling `KOKKOS_ENABLE_DEPRECATED_CODE` that would catch it?

**Comment by ndellingwood** [comment]
@william76 

> Is this something that needs to get reflected back into Kokkos-Kernels?

Thanks for checking but no, the spgemm thing didn't pop up in the Trilinos testing because deprecated code is on by default and the change made in this PR was already made in the kokkos-kernels' dev branch (in your original PR there). The perf_test stuff popped up today when the switch was flipped in kokkos to disable deprecated code but has been fixed there already.

**Comment by ndellingwood** [comment]
@william76 also the PR is already in so don't worry about a fix. 
Trilinos CMake configuration option to disable deprecated code is
`-D KOKKOS_ENABLE_DEPRECATED_CODE:BOOL=OFF`

**Comment by william76** [comment]
@ndellingwood thanks!

**Comment by william76** [comment]
@ndellingwood hmmm, I'd have thought that the autotester would have run this by now.  Shoot me a yell in the morning if it doesn't go overnight.

**Comment by ndellingwood** [comment]
@william76 will do, thanks! I'm going to add the AUTOMERGE label while here.

**Pull request merged**
