### PR TITLE
Tpetra: add two additional nightly builds

### PR DESCRIPTION
**Pull request by jhux2**
@trilinos/tpetra
## Description

Adds additional nightly testing for Tpetra.
## How Has This Been Tested?

Unnecessary, not part of code base.

## Checklist
- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

---
This change is [Reviewable](https://reviewable.io/reviews/trilinos/trilinos/5977)

### CODE REVIEW

**Comment by jhux2** [comment]
@trilinos/framework This PR is held up, and I can't tell why.

**Comment by prwolfe** [comment]
@jhux - it looks like none of the jobs are running due to an issue with the autotester's repository. I will look into it.

**Comment by jhux2** [comment]
Thanks!

**Comment by prwolfe** [comment]
@juhux - The access issue has been corrected thanks to @allevin and we are back in operation.

Thanks for the notice!

**Comment by jhux2** [comment]
@prwolfe Thank you.

**Pull request merged**
