### PR TITLE
Tacho : remove KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*

### PR DESCRIPTION
**Pull request by iyamazaki**
@trilinos/shylu 

## Motivation

This PR removes the deprecated `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*` in Tacho

## Related Issues

* Closes https://github.com/trilinos/Trilinos/issues/11508

## Testing

Being tested on Weaver with CUDA & Host builds

### CODE REVIEW

**Comment by iyamazaki** [comment]
@ndellingwood @dalg24 This is my first pass to remove `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*`. Please let me know what you think.

**Review by dalg24 — COMMENTED** [review]
Looks good.  You could consider defining a variable template helper considering how many times you use the same pattern
```C++
template <class ExecutionSpace>
inline constexpr bool runs_on_host_v = !std::is_same_v<ExecutionSpace, Kokkos::DefaultExecutionSpace> || std::is_same_v<Kokkos::DefaultExecutionSpace, Kokkos::DefaultHostExecutionSpace>;

**Comment by iyamazaki** [comment]
Thank you, @dalg24. I was also not sure how to fix [this](https://github.com/iyamazaki/Trilinos/blob/8beb43d49afe84ea2d1e251f92d14b3d808bce6b/packages/shylu/shylu_node/tacho/src/impl/Tacho_Util.hpp#L476-L482). Do I need to add a template, or are there other way around?

**Comment by dalg24** [comment]
> Thank you, @dalg24. I was also not sure how to fix [this](https://github.com/iyamazaki/Trilinos/blob/8beb43d49afe84ea2d1e251f92d14b3d808bce6b/packages/shylu/shylu_node/tacho/src/impl/Tacho_Util.hpp#L476-L482). Do I need to add a template, or are there other way around?

Ideally you refactor the code more but you could try something like
```C++
#if !defined(KOKKOS_ENABLE_CUDA) && !defined(KOKKOS_ENABLE_HIP)
KOKKOS_FUNCTION constexpr bool runsOnCudaOrHIP() { return false; }
#else
KOKKOS_FUNCTION constexpr bool runsOnCudaOrHIP() {
  KOKKOS_IF_ON_HOST(return false;)
  KOKKOS_IF_ON_DEVICE(return true;)
}
#endif
template <bool isCudaOrHIP>
struct ActiveAlgorithmHelper { using type = Algo::Internal; };
template <>
struct ActiveAlgorithmHelper<false> { using type = Algo::Extenal; };
```
and then replace `ActiveAlgorithm` by `ActiveAlgorithmHelper<runsOnCudaOrHIP()>`.
Not tested (nor actually tried to compile)

**Comment by iyamazaki** [comment]
Thank you @dalg24!! I updated the PR with your suggestions.

**Comment by iyamazaki** [comment]
Thank you, @ndellingwood. I just re-built with the flag, and both CPU & GPU build passed:

````
    Start 1: ShyLU_NodeTacho_Tacho_Test_Util.x
1/9 Test #1: ShyLU_NodeTacho_Tacho_Test_Util.x ........................   Passed    0.97 sec
    Start 2: ShyLU_NodeTacho_Tacho_Test_ETI_double_Serial.x
2/9 Test #2: ShyLU_NodeTacho_Tacho_Test_ETI_double_Serial.x ...........   Passed    0.62 sec
    Start 3: ShyLU_NodeTacho_Tacho_Test_ETI_float_Serial.x
3/9 Test #3: ShyLU_NodeTacho_Tacho_Test_ETI_float_Serial.x ............   Passed    0.64 sec
    Start 4: ShyLU_NodeTacho_Tacho_Test_ETI_complex_double_Serial.x
4/9 Test #4: ShyLU_NodeTacho_Tacho_Test_ETI_complex_double_Serial.x ...   Passed    0.89 sec
    Start 5: ShyLU_NodeTacho_Tacho_Test_ETI_complex_float_Serial.x
5/9 Test #5: ShyLU_NodeTacho_Tacho_Test_ETI_complex_float_Serial.x ....   Passed    0.60 sec
    Start 6: ShyLU_NodeTacho_Tacho_Test_ETI_double_CUDA.x
6/9 Test #6: ShyLU_NodeTacho_Tacho_Test_ETI_double_CUDA.x .............   Passed    0.77 sec
    Start 7: ShyLU_NodeTacho_Tacho_Test_ETI_float_CUDA.x
7/9 Test #7: ShyLU_NodeTacho_Tacho_Test_ETI_float_CUDA.x ..............   Passed    0.61 sec
    Start 8: ShyLU_NodeTacho_Tacho_Test_ETI_complex_double_CUDA.x
8/9 Test #8: ShyLU_NodeTacho_Tacho_Test_ETI_complex_double_CUDA.x .....   Passed    0.57 sec
    Start 9: ShyLU_NodeTacho_Tacho_Test_ETI_complex_float_CUDA.x
9/9 Test #9: ShyLU_NodeTacho_Tacho_Test_ETI_complex_float_CUDA.x ......   Passed    0.61 sec

100% tests passed, 0 tests failed out of 9

Label Time Summary:
ShyLU_Node    =   6.26 sec*proc (9 tests)

Total Test time (real) =   6.33 sec
````
I am also making sure no performance degradation (making sure it is ran on GPU).

**Review by ndellingwood — APPROVED** [review]
Thanks @iyamazaki !

**Comment by dalg24** [comment]
Could we get this merged in?  @crtrott

**Comment by iyamazaki** [comment]
Thank you, @ndellingwood & @dalg24!!

**Pull request merged**
