### PR TITLE
Teuchos: more complete and consistent YAML support

### PR DESCRIPTION
**Pull request by ibaned**
This enhancement supports gahansen/Albany#74.
Albany uses TwoDArray type ParameterLists,
and getting these supported in the YAML parser
would streamline our migration from XML to YAML.
There should be no compatibility issue, as I
don't think the current parser can handle nested
Sequences.
A unit test is included.

@trilinos/teuchos 

This builds on #1111, please resolve that one first.

### CODE REVIEW

**Comment by ibaned** [comment]
I've added the other missing half (support for writing to files), generally improved the YAML system, and rebased on to the merged #1111. @bartlettroscoe let me know what you think. With these changes we should be ready to start using YAML pretty seriously in Albany.

**Comment by ibaned** [comment]
It would be good if we could get this processed in the next week or so

**Comment by lxmota** [comment]
@bartlettroscoe @ibaned 

This is a great idea and a big usability improvement for input files in Albany.

The LCM project under Albany has a mandate to improve usability. I have already shown examples of YAML input to some of our users and they are eager to start using this. Hopefully it won't take long to get approval for this pull request.

**Comment by bartlettroscoe** [comment]
> It would be good if we could get this processed in the next week or so

What is needed to be "processed"?

**Comment by ibaned** [comment]
@bartlettroscoe  Sorry, I wasn't clear. You looked at this earlier when there were just a few changes related to TwoDArray. I've added more completeness, tests, etc. If you'd like to take another look at it, thats what I meant. Otherwise, I can go ahead with a checkin test and push.

**Comment by bartlettroscoe** [comment]
I did not review every line of code in detail but everything looks reasonable except for two questions:

1. Is there a way to get around using try/catch as a switch statement?  See [above](https://github.com/trilinos/Trilinos/pull/1112#discussion_r104763099).

2. What is deal with the DependencySheet argument (see [above](https://github.com/trilinos/Trilinos/pull/1112#discussion_r105742582))?  Why was that taken out of the argument list?

Otherwise, this looks fine to push as long as it passes all the tests.

**Comment by ibaned** [comment]
1. I was mainly maintaining consistency with the existing code. I think the reason they do it is that there is a hierarchy of types and it is searching for the most specific type that all array entries can be interpreted as. For example, the array `[1, 1.5, 2, 2.5]` has two entries for which `as<int>` succeeds (including the first entry) but two entries that don't succeed until you try `as<double>`. Unfortunately, it looks like exceptions from `as<T>` are the conventional way to check this (see [here](https://github.com/jbeder/yaml-cpp/issues/226#issuecomment-87523449) and [here](http://stackoverflow.com/questions/19994312/obtain-type-of-value-stored-in-yamlnode-for-yaml-cpp) for example). I don't generally like using exceptions as booleans, but its forced on us by the yaml-cpp library.

2. Honestly, I don't know much about dependencies. Basically, they were not supported by the existing internal read and write functions, and so I thought I'd remove them from the API so people didn't get the impression that they did anything. That API wasn't even implemented until this PR, so its not like I removed existing functionality. I don't know if there is a good way to encode dependencies in YAML, but if there is I see that as an enhancement beyond the scope of this PR.

**Comment by bartlettroscoe** [comment]
> I don't generally like using exceptions as booleans, but its forced on us by the yaml-cpp library.

Okay, if you have no choice then so be it.

> That API wasn't even implemented until this PR, so its not like I removed existing functionality. I don't know if there is a good way to encode dependencies in YAML, but if there is I see that as an enhancement beyond the scope of this PR.

I think you can safely ignore DependencySheet for now.  I think only Optika was using it and that package is not being maintained anymore.  I just wise someone would build a usable and portable GUI for managing PLs (but that is not a YAML issue).

From my perspective, if this meets Albany's needs and passes the Trilinos test suite, I see go ahead and run checkin-test-sems.sh and push.  The Trilinos CI build looks clean:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.7.2-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now

**Comment by ibaned** [comment]
okay, these are in develop as c570303 and parents. Thanks @bartlettroscoe !

**Pull request closed without merging**
