### PR TITLE
Tempus: (fix) output integrator info at interval specified

### LINKED ISSUE #2163: Tempus commits on 1/10 causing slow-downs in Albany dynamic problems
Continuing the discussion of the following Albany issue https://github.com/gahansen/Albany/issues/243 which is really a Trilinos issue.  

Some recent Tempus commits have slowed down substantially (5x) several Albany dynamic problems that utilize Tempus.  Here are some sample timings for the Schwarz_Alternating_Dynamics_Cubes test in Albany along with Trilinos commit tags:

6ab30362499394c06a019be52ee6a243a379dd35 : 19.14 sec 
1d0aae2911cd77a48965cd0afe9057b15fc560a8 : 104.95 sec

This means that the commit 1d0aae2911cd77a48965cd0afe9057b15fc560a8 (Tempus: move integrator output to observer) started this problem.

Here is some sample verbose output from the Albany CDash:

1/10 run: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3387873&build=65282
1/11 run (slower one): http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3390813&build=65335

@trilinos/tempus

### PR DESCRIPTION
**Pull request by sconde**
Was outputing at every time step and this could possibly have slowed down Albany's tests

[Verbose output for the Explicit RK test before the fix](https://github.com/trilinos/Trilinos/files/1639804/after_verbose_explicit_rk.txt) vs 
[Verbose output for the Explicit RK test before the fix](https://github.com/trilinos/Trilinos/files/1639810/tempus_explicit_rk.txt)

@trilinos/tempus 

## Related Issues

* Closes #2163 

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by ikalash** [comment]
@sconde : I just pulled / built this branch of Trilinos and build Albany on top of it.  Unfortunately it does not seem to fix issues https://github.com/trilinos/Trilinos/issues/2163 and https://github.com/gahansen/Albany/issues/243 .  Here is the time with your fix for the test:

  Start 1: Schwarz_Alternating_Dynamics_Cubes
 Test #1: Schwarz_Alternating_Dynamics_Cubes ............   Passed  103.77 sec

Would it be helpful for you to be able to run Albany to reproduce the problem?  I could give you an account on my workstation (I assume you have SRN access) where I have scripts to build both Albany and Trilinos if you wanted to play around there.

**Comment by sconde** [comment]
@ikalash Is it possible to get a copy of your build script? I can build Albany on my workstation (if I can access it). This way I will make sure to always test with Albany in the future.

If not, I have SRN access if you want to give me an account on your machine.

**Comment by ikalash** [comment]
Yes, absolutely, I'm happy to share my build scripts and build instructions (and if you can test major changes against Albany that would be great!).  I will follow up with you offline (through email) later today.  Question: do you have sems modules on your workstation?  If so, I'll send you instructions for building with them.  It should be very straightforward.

**Comment by sconde** [comment]
Yes, I build with SEMS. Thank you so much.

**Pull request merged**
