### PR TITLE
[WIP] Panzer orientation fix

### PR DESCRIPTION
**Pull request by eric-c-cyr**
This is a work in progress for the panzer orientation fix. This branch is built on @kyungjoo-kim patch (rebased several times). We are having a few problems with making sure Charon/Drekar/Panzer pass all the tests. I'll update the current state for this branch soon in the discussion. 

Also, this is not yet ready to push as things will be very broken.

### CODE REVIEW

**Comment by eric-c-cyr** [comment]
@rppawlo and @seamill are also interested in this pull request.

**Comment by eric-c-cyr** [comment]
The panzer tests currently failing are 

- PanzerAdaptersSTK_PoissonExample-ConvTest-Tri-Order-3 (Failed)
- PanzerAdaptersSTK_PoissonExample-ConvTest-Tri-Order-4 (Failed)
- PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Order-2 (Failed)
- PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Order-3 (Failed)
- PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Order-4 (Failed)

Drekar tests fail as well. These need to be sorted out before we can make progress elsewhere

**Comment by eric-c-cyr** [comment]
I've looked more carefully at the "PoissonExample-ConvTest-Tri-Order-3". The result (fine version included below), seems fine, with values in the right range. The errors are bad, with L2 errors of [0.104849, 0.101546, 0.101107, 0.101022, 0.101003]. 

3rdorder

**Comment by eric-c-cyr** [comment]
The Curl examples all have a seg fault. Also there is a problem with the EdgeBasis Dirichlet Residual evaluator.

**Comment by eric-c-cyr** [comment]
This is the stack trance for the curl laplacian example that is seg faulting (run in serial only).

```
#0  0x00007fffdac02e14 in Kokkos::atomic_exchange<Kokkos::Impl::SharedAllocationRecord<void, void>*> (
    dest=0x7ffff7888498 <Kokkos::Impl::(anonymous namespace)::deallocate<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Serial, double, true> >(Kokkos::Impl::SharedAllocationRecord<void, void>*)+40>, val=@0x7fffdac07530: 0x0)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp:211
#1  0x00007fffdac0293f in Kokkos::Impl::SharedAllocationRecord<void, void>::decrement (arg_record=0x16eaea0)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp:238
#2  0x00007ffff7914ce4 in operator= (rhs=..., this=0x7ffff726cc00 <Intrepid2::CellTools<Kokkos::Serial>::subcellParamData_+896>)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:377
#3  Kokkos::Experimental::DynRankView<double, Kokkos::Serial>::operator=(Kokkos::Experimental::DynRankView<double, Kokkos::Serial>&&) (
    this=0x7ffff726cc00 <Intrepid2::CellTools<Kokkos::Serial>::subcellParamData_+896>, 
    rhs=<unknown type in /home/eccyr/Packages/build/mpi-panzer-debug-serial/packages/panzer/adapters-stk/src/libpanzer-stk.so.12, CU 0xc135d, DIE 0x22dd8b>)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/kokkos/containers/src/Kokkos_DynRankView.hpp:802
#4  0x00007ffff5e897e0 in Intrepid2::CellTools<Kokkos::Serial>::setSubcellParametrization (subcellParam=..., subcellDim=2, parentCell=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefParametrization.hpp:231
#5  0x00007ffff5e66ed7 in Intrepid2::CellTools<Kokkos::Serial>::setSubcellParametrization ()
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefParametrization.hpp:82
#6  0x00007ffff5e4f740 in Intrepid2::CellTools<Kokkos::Serial>::getSubcellParametrization (subcellParam=..., subcellDim=1, parentCell=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefParametrization.hpp:143
#7  0x00007ffff5e765e3 in Intrepid2::CellTools<Kokkos::Serial>::getReferenceEdgeTangent<Sacado::Fad::DFad<double>, Kokkos::Serial>(Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double><Kokkos::Serial> >, int, shards::CellTopology) (refEdgeTangent=..., edgeOrd=3, parentCell=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefNodeInfo.hpp:382
#8  0x00007ffff5e5b718 in Intrepid2::CellTools<Kokkos::Serial>::getPhysicalEdgeTangents<Sacado::Fad::DFad<double>, Kokkos::Serial, Sacado::Fad::DFad<double><Kokkos::Serial> > (edgeTangents=..., worksetJacobians=..., worksetEdgeOrd=3, parentCell=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefNodeInfo.hpp:543
#9  0x00007ffff66a9910 in panzer::DirichletResidual_EdgeBasis<panzer::Traits::Jacobian, panzer::Traits>::evaluateFields (this=0x16a1280, workset=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_EdgeBasis_impl.hpp:132
#10 0x00007ffff60d9a36 in PHX::DagManager<panzer::Traits>::evaluateFields (this=0x165afe8, d=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/phalanx/src/Phalanx_DAG_Manager_Def.hpp:434
#11 0x00007ffff60d73a7 in PHX::EvaluationContainer<panzer::Traits::Jacobian, panzer::Traits>::evaluateFields (this=0x165afe0, d=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/phalanx/src/Phalanx_EvaluationContainer_Def.hpp:184
#12 0x00007ffff63dfc8a in PHX::FieldManager<panzer::Traits>::evaluateFields<panzer::Traits::Jacobian> (this=0x1922b48, d=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/phalanx/src/Phalanx_FieldManager_Def.hpp:239
#13 0x00007ffff63df2e8 in panzer::AssemblyEngine<panzer::Traits::Jacobian>::evaluateBCs (this=0x17ec4a0, bc_type=panzer::BCT_Dirichlet, in=..., preEval_loc=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/panzer/disc-fe/src/Panzer_AssemblyEngine_impl.hpp:381
#14 0x00007ffff63de6ba in panzer::AssemblyEngine<panzer::Traits::Jacobian>::evaluateDirichletBCs (this=0x17ec4a0, in=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/panzer/disc-fe/src/Panzer_AssemblyEngine_impl.hpp:260
#15 0x00007ffff63dd449 in panzer::AssemblyEngine<panzer::Traits::Jacobian>::evaluate (this=0x17ec4a0, in=...)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/panzer/disc-fe/src/Panzer_AssemblyEngine_impl.hpp:113
#16 0x00000000005dedf9 in main (argc=1, argv=0x7fffffff8918)
    at /home/eccyr/Packages/ForkedTrilinos/eric-c-cyr/Trilinos/packages/panzer/adapters-stk/example/CurlLaplacianExample/main.cpp:509
```

**Comment by kyungjoo-kim** [comment]
Eric,

I updated the repo but it is not pushed. Do you know what is the right command for push to this branch ?

**Comment by eric-c-cyr** [comment]
Did you merge or rebase?

**Comment by kyungjoo-kim** [comment]
I thought that I did but it does not show up in the repo and after I pull again my fix was gone. the kokkos problem should be fixed already. sigh sigh... I am doing again now and this time I will make sure of my push.

**Comment by eric-c-cyr** [comment]
It looks like its there if you click on commits.

**Comment by eric-c-cyr** [comment]
Okay, after the last set of changes including some extra ones from @kyungjoo-kim and I today we have the following tests failing (this is progress):
```
	 24 - PanzerDiscFE_basis_values2_MPI_1 (Failed)
	111 - PanzerAdaptersSTK_tPointBasisValuesEvaluator_MPI_1 (Failed)
	126 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Order-2 (Failed)
	127 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Order-3 (Failed)
	128 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Order-4 (Failed)
```
basis_values2 and PointBasisValues fail because they are calling the wrong applyOrientation method in BasisValues2. This is protected with an assertion now.

This is progress. We have all the HGrad tests passing and:
* PanzerAdaptersSTK_CurlLaplacianExample: 😄 
* PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Order-1 : 😄 

The high order tests are failing for similar reasons as the low order did. Basically the boundary conditions are being set improperly. The solution is known.

**Comment by kyungjoo-kim** [comment]
@eric-c-cyr  I fixed the dirichlet bounary conditions general enough for higher order elements. I checked the it set up correct boundary conditions (even if it is wrong, our test problem uses homogeneous boundary conditions and it does not matter in this particular case). Still we do not get the right convergence even if the visualization shows roughly the solution we inteded to reproduce.

Can we modify the manufactured solution as 2nd order polynomial and see if the code reproduce the polynomial first ?

**Comment by kyungjoo-kim** [comment]
BTW, the following test failures are due to my exception throw when MD field orientation is used.

```
	 24 - PanzerDiscFE_basis_values2_MPI_1 (Failed)
	111 - PanzerAdaptersSTK_tPointBasisValuesEvaluator_MPI_1 (Failed)
```

**Comment by kyungjoo-kim** [comment]
This is the commit I checked the high order hcurl is working.

```
      1 commit 36745f97b3f163853ed3e27f41f17f5885c24b30
      2 Author: Kyungjoo Kim <kyukim@sandia.gov>
      3 Date:   Wed Jun 7 23:32:31 2017 -0600
      4
      5     Panzer - hcurl laplacian example is working for high order
```

You should be able to run the code and see the following results for 2nd order elements
```
3: MPE-ConvTest-2-32: Convergence order of 1.999574 is within 10 percent of 2.000000: PASSED                                                                                                                                   
3: ('L2 errors   : ', [0.0643108, 0.0162263, 0.00406228, 0.00101587])                                                                                                                                                          
3: ('Curl errors : ', [0.0643117, 0.0162263, 0.00406228, 0.00101587])                                                                                                                                                          
3: ('HCurl errors   : ', [0.1286225, 0.0324526, 0.00812456, 0.00203174])                                                                                                                                                       
3: ('Conv rate   : ', [1.986737063981028, 1.997972478492858, 1.9995738899348117])                                                                                                                                              
3: Test Passed    
```

**Comment by kyungjoo-kim** [comment]
@eric-c-cyr 
Some test with a single curl element with order 2. I tested orientation coefficient matrix is correctly applied for both cases. So I tested both codes without orientations.

```
/// previous version "without" applying orientation
/// here the resulting matrix is diagonal 
/// however, it should be curl E curl F + EF (stiffness + mass)
/// am I supposed to see diagonal matrix ???
   Processor    Row Index    Col Index           Value     
       0             0             0                       1    
       0             0             1                       0    
       0             0             2                       0    
       0             0             3                       0    
       0             0             4                       0    
       0             0             5                       0    
       0             0             6                       0    
       0             0             7                       0    
       0             0             8                       0    
       0             0             9                       0    
       0             0            10                       0    
       0             0            11                       0    
 
/// current version "without" applying orientation
/// the matrix is not diagonal as seen above
/// however, i am very sure that this is wrong. 
/// if we print out the entire matrix, the matrix is not symmetric
/// this is before orientation is applied, 
/// so we need to separately check mass and stiffness matrix construction 
/// and its assembly. Or I need to check intrepid2 routines 
  Processor    Row Index    Col Index           Value     
       0             0             0                 1.38889    
       0             0             1               -0.185185    
       0             0             2                       0    
       0             0             3                       0    
       0             0             4                0.185185    
       0             0             5              -0.0246914    
       0             0             6                       0    
       0             0             7                       0    
       0             0             8               -0.185185    
       0             0             9               0.0246914    
       0             0            10                       0    
       0             0            11                       0    
       0             1             0                 1.38889    
       0             1             1               -0.185185    
       0             1             2                       0    
       0             1             3                       0    
       0             1             4                0.185185    
       0             1             5              -0.0246914    
       0             1             6                       0    
       0             1             7                       0    
       0             1             8               -0.185185    
       0             1             9               0.0246914    
       0             1            10                       0    
       0             1            11                       0

**Comment by kyungjoo-kim** [comment]
@eric-c-cyr I found where is the problem. mauro did put bugs in high order elements. We can merge tomorrow.

**Comment by kyungjoo-kim** [comment]
Here all the tests are passed. basis values2 and point value evaluator failures are due to deprecated orientations in panzer. Can we remove the md field version of orientations now (probably @bathmatt need to know this so that he can also remove orientation dependence if he use orientation field directly in his evaluators). 

```
97% tests passed, 5 tests failed out of 145

Label Time Summary:
Panzer    = 537.08 sec (145 tests)

Total Test time (real) = 537.23 sec

The following tests FAILED:
         24 - PanzerDiscFE_basis_values2_MPI_1 (Failed)
        105 - PanzerAdaptersSTK_tPointBasisValuesEvaluator_MPI_1 (Failed)
        143 - PanzerAdaptersIOSS_tIOSSConnManager1_MPI_1 (Failed)
        144 - PanzerAdaptersIOSS_tIOSSConnManager2_MPI_2 (Failed)
        145 - PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 (Failed)
Errors while running CTest
```

**Comment by eric-c-cyr** [comment]
Before removing, lets try to get this request through. I'm looking at the few remaining tests now (and running Drekar/Charon)

**Comment by eric-c-cyr** [comment]
Before removing, lets try to get this request through. I'm looking at the few remaining tests now (and running Drekar/Charon)

**Comment by eric-c-cyr** [comment]
Before removing, lets try to get this request through. I'm looking at the few remaining tests now (and running Drekar/Charon)

**Comment by eric-c-cyr** [comment]
I've tracked part of the current issue to the weighted_basis_vector object. It seem not to be oriented correctly if I compare it to the old version. In a two element case, it seems that its orientations are incorrect.

**Comment by eric-c-cyr** [comment]
Adding unit test showing what I believe is a mistake in the orientation. Two cells connected through basis index 1 and 3 seems to have vectors pointing in the opposite direction.

**Comment by kyungjoo-kim** [comment]
@eric-c-cyr how do I trigger the test toe be failed ?

**Comment by eric-c-cyr** [comment]
Okay, this last test issue is fixed by ensuring applyOrientations is applied only once to a basis values object in the basis values. This is confusing and needs to be rearchitected because of the complexity associated with the needs vector. I will modify the test to excercise the issue explicitly and checkin a suboptimal fix before really fixing the needs interactions.

**Comment by eric-c-cyr** [comment]
Fixes for the two panzer tests failing are just pushed, now just 4 drekar tests

**Comment by eric-c-cyr** [comment]
There was a problem with how dirichlet conditions were enforced. I've fixed the evaluator and now have only one Drekar test failing (associated with how the tets are setup). After @kyungjoo-kim pushes that @jmgate can run Charon and we should be able to merge.

As a warning, I'm sure there are cases that we need that are not fully tested. This will effect Drekar most heavily, but possibly EMPIRE as well. @egboman @rppawlo @bathmatt need to be aware of this when we push.

**Comment by kyungjoo-kim** [comment]
I compiled the Drear. Which branch should I use ? The master branch I have does not include failed test.

**Comment by jmgate** [comment]
Using 4703cf9, I'm seeing all Panzer, Drekar, and Charon tests pass except:
* `Drekar_source_inversion` (this has always shown an `exodiff` failure for me with ROL on&mdash;@eric-c-cyr, you'll want to make sure this passes for you)
* `Drekar_plasma_oscillation_tetmesh` (I assume this is the last failing Drekar test you refer to)

**Comment by eric-c-cyr** [comment]
@jmgate Thanks, good to know. These are known and I will fix the source_inversion today (just a rebase line for the gold standard). @kyungjoo-kim is working on the tetmesh one.

@kyungjoo-kim are you building with MHD and SystemTests on? You would have to look at your configure file to figure this out.

**Comment by eric-c-cyr** [comment]
I just rebased the drekar source inversion file, we shouldn't be seeing problems here anymore.

**Comment by kyungjoo-kim** [comment]
@eric-c-cyr 

I fixed the last unresolved unit test. Please check drekar and other applications. 

One issue is that tangent definition is sometimes normalized or not normalized. 

Tangent gather evaluator should make sure this consistently. Some restructuring might be needed.

**Comment by jmgate** [comment]
With @kyungjoo-kim's latest commit (9602edf), I'm seeing **100%** of Panzer's, Drekar's, and Charon's tests passing.  There are still conflicts with `develop` to resolve, but beyond that, are we finally ready to merge?

**Comment by eric-c-cyr** [comment]
I'm rebuilding and testing now. I will do a fetch and merge into develop after that we should be ready.

**Comment by eric-c-cyr** [comment]
Just merged this after updating with develop. Yay!

**Pull request merged**
