### PR TITLE
Set Werror for ML

### PR DESCRIPTION
**Pull request by ZUUL42**
@trilinos/framework 

## Description

Sets Werror for ML in the GC 7.2.0 PR build.
## Motivation and Context

This is work toward #3178, setting -Werror for all packages.

Allowed by work from Issue #4512 & PR #4625.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

**Comment by lucbv** [comment]
@jhux2 it looks like a couple of return values are unused, should we declare them void?

**Comment by jhux2** [comment]
@lucbv wrote:
> it looks like a couple of return values are unused, should we declare them void?

I hope these were fixed by #4722.  Let's see what the autotester has to say.

**Comment by ZUUL42** [comment]
> @lucbv wrote:
> I hope these were fixed by #4722. Let's see what the autotester has to say.

The changes in that PR don't seem to address the issues reported in [the CDash report](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4746115):
- /Trilinos/packages/ml/src/Utils/ml_MultiLevelPreconditioner_Filtering.cpp:177:7: error: unused variable ‘CL’ [-Werror=unused-variable]
    int CL = ML_Gen_MultiLevelHierarchy_UsingAggregation(flt_ml_,1,
- /Trilinos/packages/ml/test/MatrixFree/MatrixFree.cpp:229:7: error: unused variable ‘MFP2Iters’ [-Werror=unused-variable]
    int MFP2Iters = solver.NumIters();
- /Trilinos/packages/ml/test/MatrixFree/MatrixFree.cpp:258:7: error: unused variable ‘MLPIters’ [-Werror=unused-variable]
    int MLPIters = solver.NumIters();

I was looking at it and fixed it with some quick ifdefs around the variables it's complaining about.
@jhux2, @lucbv, if you don't mind I can pull in the commit from [Werror_ML_fix](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:Werror_ML_fix) and get this PR & issue closed out.

**Comment by jhux2** [comment]
> I was looking at it and fixed it with some quick ifdefs around the variables it's complaining about.
@jhux2, @lucbv, if you don't mind I can pull in the commit from Werror_ML_fix and get this PR & issue closed out.

@ZUUL42 Thanks.  One correction.  Rather than

```cpp
#ifndef NDEBUG
  int CL = ML_Gen_MultiLevelHierarchy_UsingAggregation(flt_ml_,1,
                                                       ML_DECREASING,
                                                       flt_agg_);

  assert (CL == 2);
#endif
```

you want instead

```cpp
#ifndef NDEBUG
  int CL =
#endif
 ML_Gen_MultiLevelHierarchy_UsingAggregation(flt_ml_,1,
                                                       ML_DECREASING,
                                                       flt_agg_);

  assert (CL == 2);
```

because `flt_ml` is a pointer affected by this call.

**Comment by ZUUL42** [comment]
Ahh. Right. Thanks. I'll make the change, push it up and you can look it over before we retest.

**Comment by ZUUL42** [comment]
@jhux2 looks like there's still some trouble with the builds, but I think the Werror PR itself is done. Thanks. Little bit closer to having Werror set for the whole GCC 7.2.0 build.

**Pull request merged**
