### PR TITLE
include <mpi.h>, not "mpi.h"

### PR DESCRIPTION
**Pull request by ibaned**
see #1480

This affects many packages, not sure if I want to mention them all...

### CODE REVIEW

**Comment by mhoemmen** [comment]
Looks good to me!

**Comment by ibaned** [comment]
Thanks everyone who has taken a look!

For some reason I haven't received GitHub notifications of your approvals...

Anyway, I think I'll start the `checkin-test-sems.sh` script for this.
Its fairly straightforward and individual commits correspond to packages so they can be reverted if someone complains.

**Comment by mhoemmen** [comment]
Thanks @ibaned ! :-D

**Comment by ibaned** [comment]
The checkin script succeeded.

**Pull request closed without merging**
