### PR TITLE
Tpetra:  Reproducer for #10008

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/tpetra 

## Motivation

This PR has a reproducer for #10008.

The test creates a matrix with all entries on one processor.  It attempts to importAndFillComplete it to a matrix on all processors.

The test will throw and error on one rank and hang on the others.

The error is thrown from lowCommunicationMakeColMapAndReindex.

The error is reproducible on ascicgpu machines with SerialNode and SEMS gcc7.2 modules.

### CODE REVIEW

**Comment by tjfulle** [comment]
I'm building and running the reproducer right now.  Will update #10008 when more info is learned.

**Comment by tjfulle** [comment]
@kddevin and @csiefer2 - the changes in this PR now pass @kddevin's tests.  Waiting to see if the changes have side effects in the PR testing...

**Review by csiefer2 — APPROVED** [review]

**Comment by kddevin** [comment]
@tjfulle do you have time to fix the warnings-as-errors compilation failures?

**Comment by kddevin** [comment]
@csiefer2  The tests finally passed.  Whew!  Would you please re-review?  Thank you!

**Comment by kddevin** [comment]
@trilinos/tpetra. This PR has passed but needs review.  Please help. Thanks.

**Comment by tasmith4** [comment]
@kddevin what is the change in CrsMatrix_def?  Is that the fix for the problem this test reproduces?

**Comment by tjfulle** [comment]
@tasmith4 - the matrix packing routine puts -1 in the array of TargetPids for local entries (rather than its own pid). We believe it is a hold over from Epetra to ensure proper ordering of pids when sorted (local entries first).  This change is to replace the -1 with the actual pid before calling other routines (that expect an actual pid)

**Pull request merged**
