### PR TITLE
Thyra: added support for x_dot_dot

### PR DESCRIPTION
**Pull request by rppawlo**
Issue #1008 

@bartlettroscoe can you review? Checkin test script passed.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@rppawlo, I will have a look in a few hours. I have some meetings and some project reporting to do :-)

**Comment by bartlettroscoe** [comment]
@rppawlo, the changes look very straightforward and reasonable.  Also, thanks for adding a unit test for some of these.  We need to add unit tests for more of this stuff (since I wrote most of this prior to 2007 when I learned about the importance and proper techniques for unit testing).

Do you know if all of this is being used (and therefore also tested) by Tempus and/or Drekar?   I am asking because I will need to manually address some of these changes in my local branch for #795 where I have been moving things around to better organize and partition all of this (in preparation for adding a whole bunch of new InArgs and OutArgs to support Hessians) and I want to make sure that I don't break anything.

**Comment by rppawlo** [comment]
@bartlettroscoe The Thyra model evaluator is used by a number of codes - Albany, Drekar, and a bunch of others internally. So it is exercised pretty well. Testing against Drekar should catch any issues. The new support for x_dot_dot that this pull request covers will be used by Tempus but development using this new feature will not start until next week.

**Comment by agsalin** [comment]
Thanks for working on this. Also looking forward to Hessian changes, Ross. 

Yes, we will know very quickly if anything is accidentally broken in ThyraME. 

With regards to testing the integration algs when they come online, I have one test in Piro that solves a single equation  x_dot_dot=-1, x(0)=0, x_dot(0)=1 t=[0,2] (throwing a ball in the air until it hits the ground) that we can hook up to the Piro_TempusSolver.

**Comment by ikalash** [comment]
It would be great to get this test into Tempus once @lxmota and I have the Newmark-Beta stepper implemented in Tempus.

**Comment by ccober6** [comment]
I agree, and it should be easy to add once the Newmark-Beta stepper is ready.

**Pull request merged**
