### PR TITLE
tpetra: compatibility update with KOKKOS_VERSION>=40499

### PR DESCRIPTION
**Pull request by ndellingwood**
Compatibility update with kokkos@develop changes merged in kokkos/kokkos#7394

@trilinos/tpetra @csiefer2 

## Motivation
Resolve compilation errors with kokkos@develop branch

## Related Issues

* Closes `put-issue-number-here`

## Testing
Tested with local build to confirm compilation errors resolved

### CODE REVIEW

**Comment by ndellingwood** [comment]
Namespace update required for `int_for_synchronization_reason` call (routine removed from `Impl` namespace)

**Comment by ndellingwood** [comment]
@trilinos/framework the PR results listed all jobs failing above https://github.com/trilinos/Trilinos/pull/13487#issuecomment-2386629279, but the posted cdash link  https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-13487-test&field2=buildstarttime&compare2=84&value2=NOW seems to only be posting partial results for a couple of the jobs only showing configuration results (no errors), can you offer any guidance on what is failing in the PR jobs?

**Comment by ndellingwood** [comment]
One test failure in the [TrilinosInstallTests_reduced_tarball](https://trilinos-cdash.sandia.gov/test/65099180) shouldn't be related to changes in the PR 

```

TEST_2: Return code = 0
TEST_2: Pass criteria = Match all REGEX {Final set of non-enabled top-level packages:  0} [FAILED]
TEST_2: Pass criteria = Match all REGEX {-- Configuring done} [PASSED]
TEST_2: Pass criteria = Match all REGEX {-- Generating done} [PASSED]
TEST_2: Pass criteria = ALWAYS_FAIL_ON_NONZERO_RETURN [PASSED]
TEST_2: Result = FAILED

================================================================================

OVERALL FINAL RESULT: TEST FAILED (TrilinosInstallTests_reduced_tarball)
```

Retesting

**Comment by ndellingwood** [comment]
@trilinos/framework @sebrowne this PR has failed the [TrilinosInstallTests_reduced_tarball](https://trilinos-cdash.sandia.gov/test/65125343) twice in the https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=1882245&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and job, but I don't see how it can be related to this PR (the guards added here should make no change from the current version of Tpetra) , can you help direct me to the underlying issue? The output shows this as the failure: `TEST_2: Pass criteria = Match all REGEX {Final set of non-enabled top-level packages:  0} [FAILED]`, but all other configuration, build and test stages passed...


```

TEST_2: Return code = 0
TEST_2: Pass criteria = Match all REGEX {Final set of non-enabled top-level packages:  0} [FAILED]
TEST_2: Pass criteria = Match all REGEX {-- Configuring done} [PASSED]
TEST_2: Pass criteria = Match all REGEX {-- Generating done} [PASSED]
TEST_2: Pass criteria = ALWAYS_FAIL_ON_NONZERO_RETURN [PASSED]
TEST_2: Result = FAILED

================================================================================

OVERALL FINAL RESULT: TEST FAILED (TrilinosInstallTests_reduced_tarball)
```

**Comment by jhux2** [comment]
@trilinos/framework Unrelated, there's a misspelled cmake option ("Fortran") in [`TrilinosInstallTests_reduced_tarball`](https://trilinos-cdash.sandia.gov/test/65125343):
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_Fortan_COMPILER
```

**Comment by sebrowne** [comment]
I took a brief look and agree that the failure should not have been triggered by your changes.  I'll see if I can reproduce manually.
@jhux2 no the typo _shouldn't_ matter but I'll fix it anyway to avoid confusion in the future.

**Pull request merged**
