### PR TITLE
Set Werror for SEACAS

### PR DESCRIPTION
**Pull request by ZUUL42**
@trilinos/framework

## Description

This sets Werror for SEACAS.
## Motivation and Context

This is work toward #3178 turning Werror on for all packages.

Allowed by work from Issue #4514 & PR #4518.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by gsjaardema** [comment]
This will hopefully work now.

**Comment by ZUUL42** [comment]
Looks like this one was closed without having SEACAS set for Werror.

**Comment by gsjaardema** [comment]
This *should* now work.  I figured out what was causing the `throw()` (It was the use of `free()` in a template function parameter) and fixed it.

**Comment by ZUUL42** [comment]
Looks like all of the SEACAS code is building error-free with Werror set.
However, now we've got some Stratimikos & Belos test failures. I see they've got some fixes inbound. So, I'll retest when those get merged in.

**Comment by mhoemmen** [comment]
I think the problem is that the fixes can't merge because of the test failures. @trilinos/framework

**Pull request merged**
