### PR TITLE
Intrepid2: replace CellTopology member in Basis class with its key

### PR DESCRIPTION
**Pull request by mperego**
@trilinos/intrepid2

## Motivation

We want to be able to copy the Intrepid2::Basis class on device for calling virtual functions, but CellTopology member is not device friendly. For this reason we replace it with its identifier (the cell topology key) and add the function getCellTopologyData(unsigned key) in CellData file that allows to retrieve the Cell topology from its key.

## Testing

No changes to interface (except for protected member), no additional tests needed.

### CODE REVIEW

**Review by CamelliaDPG — DISMISSED** [review]
@mperego, this looks good to me.  Thanks!

One minor niggle: my preferred abbreviation of `cellTopology` for variable names is `cellTopo` (I use this all over the place in Camellia; I'm not sure whether it's present in Intrepid2 already).  If you're so inclined and have a chance to do so, I'd love a change from `cellTop` to `cellTopo` in this PR.  But it's not a big deal, and I can always change it later.  :-)

**Comment by mperego** [comment]
> @mperego, this looks good to me. Thanks!
> 
> One minor niggle: my preferred abbreviation of `cellTopology` for variable names is `cellTopo` (I use this all over the place in Camellia; I'm not sure whether it's present in Intrepid2 already). If you're so inclined and have a chance to do so, I'd love a change from `cellTop` to `cellTopo` in this PR. But it's not a big deal, and I can always change it later. :-)

I can do that. I used `CellTop` following the `FaceTop` and `EdgeTop` names, but I agree `cellTopo` is better.

**Comment by mperego** [comment]
@CamelliaDPG , I've renamed `cellTop`. Can you please re-approve?

**Review by CamelliaDPG — APPROVED** [review]
Thanks, @mperego!

**Pull request merged**
