### PR TITLE
Framework: Remove Python 2 use from PR test driver

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework 

Remaking RP #8288 - the CDash logs were getting a little confusing with the reporting. This PR should clean things up a bit.

The GCC 8.3.0 build seems to be having some odd SEACAS error in the other PR -- will have to investigate why it's happening if it continues.

## Motivation
Python 2.x is beyond its end-of-life, so it's time to remove its support from our PR driver scripts.

This should only affect the PR drivers which are run by the Autotester.

### CODE REVIEW

**Comment by william76** [comment]
FYI @jmgate This is the PR I have currently testing out the Python 2.x removal.

**Comment by william76** [comment]
@prwolfe this one is passing now with upping the CMake version to the SEMS 3.12.2 one in the gcc 8.3.0 test.

I enabled the automerge flag, if you're ok with merging in feel free to approve... or we can do a review pass first if you want.

FYI @jwillenbring @ZUUL42 looks like it's the gcc 8.3.0 test that requires some CMake higher than 3.10.x to work... I changed it to 3.12 and it's passing now.

**Comment by prwolfe** [comment]
Will - do we understand what the newer python provides for the gcc 8.3 build? This looks good, but unexplained items always bug me.

**Review by prwolfe — APPROVED** [review]

**Comment by william76** [comment]
> 
> 
> Will - do we understand what the newer python provides for the gcc 8.3 build? This looks good, but unexplained items always bug me.

Not really... the gcc 8.3.0 build always failed if we used CMake 3.10.3.  This was the one that @ZUUL42 mentioned yesterday that wouldn't work with 3.10.x so he had raised it in the old setup to the 3.17.x version.  In this PR it looks like 3.12.x is sufficient but the error was funny and I'm not sure what was going on there.  It was that 1 build warning that triggered a warning-as-error I think down in SEACAS.  No tests failed, just that one build issue.

@ZUUL42 Henry, correct me if I got what you said yesterday incorrect...

**Comment by jmgate** [comment]
Does this mean we're Python 3.6+ from now on?  If so, that's good&mdash;just making sure I understand the PR.

**Pull request merged**
