### PR TITLE
MueLu: makepr.sh updates

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA 308c3b7

### CODE REVIEW

**Comment by csiefer2** [comment]
For this guy, I ran:

makepr.sh -l MueLu -l nitpick MueLu: makepr.sh updates

AT: AUTOMERGE is always added.

Cool, huh?

**Comment by jhux2** [comment]
@csiefer2 Do you know if reviewers can also be added?

**Comment by jhux2** [comment]
I suspect that Trilinos teams are not set up to allow that.  See https://help.github.com/articles/requesting-a-pull-request-review.

**Comment by csiefer2** [comment]
@jhux2 Some teams can be PR review requestees (try it) but not ours.  @trilinos/framework any ideas?

**Comment by jhux2** [comment]
@csiefer2 You're right.  See issue #3761.

**Pull request merged**
