### PR TITLE
Belos fixed point solver: Allow right preconditioning

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/belos 

## Description
Add code path for right preconditioning in the Belos fixed point solver.

Addresses #3582

### CODE REVIEW

**Comment by cgcgcg** [comment]
@mhoemmen Will do. I'll have to fix the current Tpetra test for the fixed point solver, since it's actually building a CG...

**Comment by hkthorn** [comment]
Sorry, but the implementation has extra vector copies that are inefficient and the use of multi vector methods that allow the underlying linear algebra to detect that this is an axpy operation would be better.

**Comment by cgcgcg** [comment]
@hkthorn Are you referring to the combination of `Assign` and `MvAddMv`? This was a pattern match to the old implementation. I didn't know that `MvAddMv` can work inplace. I'll definitely change this then!

**Comment by hkthorn** [comment]
Many thanks!  I just want to make sure it is as efficient as possible.

**Pull request merged**
