### PR TITLE
FEM assembly

### PR DESCRIPTION
**Pull request by GeoffDanielson**
@trilinos/tpetra 

## Motivation

Fix the FEA example in tpetra so that it 1) works, and 2) is more in-line with our refactor using wrapped dual views.

## Testing

This is a change to the test, so the test should actually work now.

### CODE REVIEW

**Comment by csiefer2** [comment]
This a great start!  From the perspective of being normative, I would suggest getting all the calls to getHostView/getDeviceView out of the loops and just store the host or device view (whichever you need) when you grab the guy from the mesh database.

**Comment by kddevin** [comment]
Please document results running the tests with and without UVM.  Thanks!

**Comment by GeoffDanielson** [comment]
> Please document results running the tests with and without UVM. Thanks!

This does indeed pass with UVM both off and on.

**Comment by GeoffDanielson** [comment]
> This a great start! From the perspective of being normative, I would suggest getting all the calls to getHostView/getDeviceView out of the loops and just store the host or device view (whichever you need) when you grab the guy from the mesh database.

Done.

**Comment by GeoffDanielson** [comment]
UVM in Tpetra and Kokkos OFF:

`ninja -C ../../../../..  packages/tpetra/core/example/Finite-Element-Assembly/test
ninja: Entering directory `../../../../..'
[0/1] Running tests...
Test project /ascldap/users/gcdanie/uvm_off/packages/tpetra/core/example/Finite-Element-Assembly
    Start 1: TpetraCore_FEMAssembly_InsertGlobalIndicesFESP_MPI_4
1/4 Test #1: TpetraCore_FEMAssembly_InsertGlobalIndicesFESP_MPI_4 .........   Passed    7.35 sec
    Start 2: TpetraCore_FEMAssembly_InsertGlobalIndicesFESPKokkos_MPI_4
2/4 Test #2: TpetraCore_FEMAssembly_InsertGlobalIndicesFESPKokkos_MPI_4 ...   Passed    6.94 sec
    Start 3: TpetraCore_FEMAssembly_TotalElementLoopSP_MPI_4
3/4 Test #3: TpetraCore_FEMAssembly_TotalElementLoopSP_MPI_4 ..............   Passed    6.90 sec
    Start 4: TpetraCore_FEMAssembly_TotalElementLoopSPKokkos_MPI_4
4/4 Test #4: TpetraCore_FEMAssembly_TotalElementLoopSPKokkos_MPI_4 ........   Passed    6.92 sec

100% tests passed, 0 tests failed out of 4
`

**Comment by GeoffDanielson** [comment]
UVM in Tpetra and Kokkos ON:

>ninja -C ../../../../..  packages/tpetra/core/example/Finite-Element-Assembly/test
ninja: Entering directory `../../../../..'
[0/1] Running tests...
Test project /ascldap/users/gcdanie/uvm_on/packages/tpetra/core/example/Finite-Element-Assembly
    Start 1: TpetraCore_FEMAssembly_InsertGlobalIndicesFESP_MPI_4
1/4 Test #1: TpetraCore_FEMAssembly_InsertGlobalIndicesFESP_MPI_4 .........   Passed    7.05 sec
    Start 2: TpetraCore_FEMAssembly_InsertGlobalIndicesFESPKokkos_MPI_4
2/4 Test #2: TpetraCore_FEMAssembly_InsertGlobalIndicesFESPKokkos_MPI_4 ...   Passed    7.08 sec
    Start 3: TpetraCore_FEMAssembly_TotalElementLoopSP_MPI_4
3/4 Test #3: TpetraCore_FEMAssembly_TotalElementLoopSP_MPI_4 ..............   Passed    6.95 sec
    Start 4: TpetraCore_FEMAssembly_TotalElementLoopSPKokkos_MPI_4
4/4 Test #4: TpetraCore_FEMAssembly_TotalElementLoopSPKokkos_MPI_4 ........   Passed    7.08 sec

100% tests passed, 0 tests failed out of 4

**Pull request merged**
