### PR TITLE
[WIP] Panzer: Modifications to panzer::Traits

### PR DESCRIPTION
**Pull request by seamill**
These changes are discussed in #1865 

Modified Evaluators (mainly gather/scatter), tests, and utilities to reflect the changes in panzer::Traits.

### CODE REVIEW

**Comment by seamill** [comment]
@rppawlo @eric-c-cyr @jmgate @bathmatt: These are the changes as I see them. I updated the tests, and everything passes (though PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 takes about 500 seconds). 

The only real issue I came across was having to change all the 
```c++
panzer::Traits::SetupData sd;
sd.worksets_ = ...
```
constructions into
```c++
panzer::Traits::SD sd;
sd.worksets_ = ...
```
since ``panzer::Traits::SetupData`` is now a const references. Not pretty, but it works.

**Comment by jmgate** [comment]
@seamill, is there an associated branch to check out in Drekar, or not yet?

**Comment by jmgate** [comment]
Nevermind&mdash;I'll push up a `1865_panzer_modifications_to_panzer_traits` branch up to Drekar in a bit.

**Comment by jmgate** [comment]
I pushed `1865_panzer_modifications_to_panzer_traits` branches up to Drekar and Charon.  @eric-c-cyr, @rppawlo, either of you care to look at them?  Everything builds&mdash;tests running now.

**Comment by rppawlo** [comment]
everything looks fine. feel free to push if tests pass.

**Comment by jmgate** [comment]
Changes pushed to Drekar and Charon.  Anything in EMPIRE need to change?

**Comment by seamill** [comment]
Good god man, that was fast... I can handle empire-fluid, but the main empire code will probably have issues with this.

**Comment by jmgate** [comment]
Ruh roh!  I'll get on EMPIRE then.

**Comment by jmgate** [comment]
Looks like EMPIRE might not need any updating due to this.

**Pull request merged**
