### PR TITLE
Import stk development from the Sierra development stream

### PR DESCRIPTION
**Pull request by prwolfe**
This imports stk development as of: 4.49.7-149-g0e77be7
After passing all tests against gcc 4.9.3 with openmpi

Last stk commit was 

commit e19a770431c2d07005ade5a6093599a04b5912e3
Author: Johnathan Vo <jvo@sandia.gov>
Date:   Tue Aug 21 14:58:34 2018 -0600

    Remove an unnecessary include that was added by clang header cleanup

@trilinos/stk

## Description
Incremental update from the Sierra development stream

## Motivation and Context
This brings in a fix for an extra unneeded include that breaks non-gcc based builds (clang, xlC, etc.)

## How Has This Been Tested?
The Sierra build of stk using gcc 4.9.3 ran and passed all tests

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ x ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by prwolfe** [comment]
The gcc 4.9.3 build ran into the rcp error we have been seeing, so I killed all the jobs and will let it re-run.

**Comment by prwolfe** [comment]
@alanw0 - It looks like the 4.8.4 compiler is not happy with the changes from put_field to put_field_on_mesh. Haven't looked into why yet.

**Comment by alanw0** [comment]
@prwolfe I clicked on the 'console output' links above but couldn't find compile-error output.

**Comment by prwolfe** [comment]
@alanw0 - Try this direct link

https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=3862624

**Comment by prwolfe** [comment]
Spoke With @alanw0 and am abandoning this to wait for his fixes to the gcc 4.8.4 build issues.

**Pull request closed without merging**
