### PR TITLE
KokkosKernels: temp. fix for #11655

### PR DESCRIPTION
**Pull request by brian-kelley**
(Temporary) In SpGEMM, disable the check that the input matrices are sorted if the KokkosKernels (non-TPL) implementation is going to be called. This impl does not actually require sorted inputs. Tpetra's MatrixMatrix::Multiply logic needs some nontrivial changes to have a sorted B, but that will be the long-term fix for #11655.

@trilinos/kokkos-kernels 
@trilinos/tpetra

## Motivation

With this change, all Panzer-MiniEM tests pass in an OpenMP+Debug build (develop branch had 6 failures).

### CODE REVIEW

**Review by cgcgcg — APPROVED** [review]
Thanks @brian-kelley !

**Review by rppawlo — APPROVED** [review]

**Comment by rppawlo** [comment]
Thanks @brian-kelley and @cgcgcg !

**Comment by brian-kelley** [comment]
@ndellingwood Hmm... I was hoping this could just be a short-term change that could be reverted soon. It's really a workaround for a Tpetra issue that evaded testing, rather than a KokkosKernels issue.

When are you planning to put together the 4.0.1 release candidate? Depending on that I will either patch to KK, or go for the permanent fix in Tpetra and (at the same time) revert this PR.

**Comment by ndellingwood** [comment]
> I was hoping this could just be a short-term change that could be reverted soon

@brian-kelley thanks for the update, I hadn't realized that. No ETA on a 4.0.01 patch yet, I'll check in the kokkos meeting this week. I'll check back in with you closer to snapshot time with 4.0.01, if I don't see a PR to Tpetra with the long-term fix we can coordinate the patch to eventual release candidate branch

**Pull request merged**
