### PR TITLE
MueLu: Extend RegionRFactory to allow multiple DOFs per node

### PR DESCRIPTION
**Pull request by GrahamBenHarper**
@trilinos/muelu 

## Motivation
This allows for multiple variable equations, such as elasticity, to be solved.

## Testing
I reran the region unit tests on skyridge with a debug build and they pass.

## Additional Information
@lucbv I'd like you to look at the loops for a moment. The current access pattern definitely isn't optimal because the outer loop is `l`.
What I currently have looks like
```
      LO rowIdx = 0, columnOffset = 0, entryOffset = 0;
      for(LO l = 0; l < blkSize; ++l) {
        row_map_h(rowIdx + 1 + l) = entryOffset + cornerStencilLength*blkSize + l;
        for(LO k = 0; k < 3; ++k) {
          for(LO j = 0; j < 3; ++j) {
            for(LO i = 0; i < 3; ++i) {
              entries_h(entryOffset + (k*9 + j*3 + i)*blkSize + l) = columnOffset
                + (k*lFineNodesPerDim[1]*lFineNodesPerDim[0] + j*lFineNodesPerDim[0] + i)*blkSize + l;
              values_h(entryOffset + (k*9 + j*3 + i)*blkSize + l)  = coeffs[k + 2]*coeffs[j + 2]*coeffs[i + 2];
	    }
          }
        }
        for(int dim = 0; dim <numDimensions; ++dim) {
          coarseCoordData[dim][rowIdx + l] = fineCoordData[dim][columnOffset + l];
        }
      }
```
however, I'm wondering if the best approach to make sure the access patterns are optimal would look more like this:
```
      LO rowIdx = 0, columnOffset = 0, entryOffset = 0;
      for(LO k = 0; k < 3; ++k) {
        for(LO j = 0; j < 3; ++j) {
          for(LO i = 0; i < 3; ++i) {
            for(LO l = 0; l < blkSize; ++l) {
              entries_h(entryOffset + (k*9 + j*3 + i)*blkSize + l) = columnOffset
                + (k*lFineNodesPerDim[1]*lFineNodesPerDim[0] + j*lFineNodesPerDim[0] + i)*blkSize + l;
              values_h(entryOffset + (k*9 + j*3 + i)*blkSize + l)  = coeffs[k + 2]*coeffs[j + 2]*coeffs[i + 2];
	    }
          }
        }
      }
      for(LO l = 0; l < blkSize; ++l) {
        row_map_h(rowIdx + 1 + l) = entryOffset + cornerStencilLength*blkSize + l;
        for(int dim = 0; dim <numDimensions; ++dim) {
          coarseCoordData[dim][rowIdx + l] = fineCoordData[dim][columnOffset + l];
        }
      }
```

### CODE REVIEW

**Comment by GrahamBenHarper** [comment]
I forgot to check the 4MPI ranks test. It should be fixed in just a minute.

**Comment by GrahamBenHarper** [comment]
```
9. RegionRFactory_double_int_longlong_Kokkos_Compat_KokkosSerialWrapperNode_RegionRFactLaplace3D_UnitTest ... [Passed] (0.1 sec)
10. RegionRFactory_double_int_longlong_Kokkos_Compat_KokkosSerialWrapperNode_RegionRFactElasticity3D_UnitTest ... [Passed] (1.48 sec)
```
Yep I definitely need to fix those access patterns...

**Comment by GrahamBenHarper** [comment]
```
9. RegionRFactory_double_int_longlong_Kokkos_Compat_KokkosSerialWrapperNode_RegionRFactLaplace3D_UnitTest ... [Passed] (0.106 sec)
10. RegionRFactory_double_int_longlong_Kokkos_Compat_KokkosSerialWrapperNode_RegionRFactElasticity3D_UnitTest ... [Passed] (1.52 sec)
```
Well, that makes no sense. Maybe I should check the release build instead...

**Comment by GrahamBenHarper** [comment]
Here's a comment on the timing results on a Skybridge compute node using a 31x31x34 sample problem:
 - Without "optimize access patterns"
   - With 1 MPI rank: 54.8sec
   - With 4 MPI ranks: 14.3sec
 - With "optimize access patterns"
   - With 1 MPI rank: 53.9sec
   - With 4 MPI ranks: 14.7sec

Here's results for 61x61x64: 
 - Without "optimize access patterns"
   - With 1 MPI rank: 405sec
   - With 4 MPI ranks: 108sec
 - With "optimize access patterns"
   - With 1 MPI rank: 405sec
   - With 4 MPI ranks: 108sec

This is strange because I know I'm checking the different commits and recompiling and rerunning the test, but it seems like it should go much more quickly.

**Comment by GrahamBenHarper** [comment]
@lucbv As requested, here is the impact of these changes on the Laplace3D solver on a 61x61x64 mesh:
 - Before this PR:
   - With 1 MPI rank: 10.2 sec
   - With 4 MPI ranks: 2.79 sec
 - After this PR:
   - With 1 MPI rank: 10.2 sec
   - With 4 MPI ranks: 2.77 sec

It looks like it does just fine.

**Review by lucbv — APPROVED** [review]
Excellent, then I'm happy to approve this PR

**Pull request merged**
