### PR TITLE
WIP: Amesos2: Add "example" to test #3647

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/amesos2

## Description

Add "example" for testing #3647.  The example does not include the linear system files.  For the files and instructions, see #3647.  This PR should be harmless to merge, but I've nevertheless marked it as a WIP, with the intent that Amesos2 developers use it to develop a true nightly test.

## Related Issues

* Part of #3647 

## How Has This Been Tested?

Linux, GCC, OpenMPI.

### CODE REVIEW

**Comment by srajama1** [comment]
I see this being useful as both example and a nightly test (as most users don't check the tests directory). If you agree, we can merge the example in.

**Comment by ndellingwood** [comment]
I'll help get this tested soon so we can merge, working on a couple other things with integration testing for now. Sorry for the delay responding, I never got an email pinging me as a reviewer.

**Comment by mhoemmen** [comment]
Thanks @ndellingwood ! :D

**Comment by ndellingwood** [comment]
Replaced AT:WIP due to test failures.

**Comment by mhoemmen** [comment]
@ndellingwood It just looks like some PR tests didn't finish or report.  What tests actually failed?

**Comment by ndellingwood** [comment]
@mhoemmen these tests were marked failing:

Trilinos_pullrequest_intel_17.0.1
Trilinos_pullrequest_gcc_4.9.3
Trilinos_pullrequest_gcc_4.8.4

When I looked at cdash for the matching build numbers it shows all tests passed (lots of green). Is this an issue reporting results properly to Github with the autotester? I don't see any actual failures...

**Comment by mhoemmen** [comment]
> Is this an issue reporting results properly to Github with the autotester?

Almost certainly.  See other active issues today.

**Comment by ndellingwood** [comment]
@mhoemmen may I close this PR? I incorporated parts of it (the matrix market reader parts to handle gapped row ids) within #4454, I added you as an author on that file for credit.

**Comment by mhoemmen** [comment]
Thanks @ndellingwood !  I'll close this PR.

**Pull request closed without merging**
