### PR TITLE
Belos: Change all default parameters to be constexpr (#2483)

### PR DESCRIPTION
**Pull request by MicheldeMessieres**
Change all belos solver manager defaults from static const to static constexpr.
This prepares for PR #2483 to avoid static initialization order conflicts.

@trilinos/belos 

## Description

The purpose of these changes is to prepare for premain
registration for the new DII system. The statics were
causing some initialization order issues that could
sometimes seg fault the managers when they were constructed.

Some older clang versions fail on the linkage of
the constexpr when calling the set method for ParameterList.
Using a static_cast seems to work around this though
the cast is simply assignining the constexpr to their
original type. I'm anticipating that would be removed eventually.

Using c++17 resolves this.

Note this PR is being used to test #2483 now and seems to
resolve all the static linkage issues allowing for pre-main
registration of DII to work. So that PR will depend on this one.

## Motivation and Context

The  new DII belos system #PR 2483 will have pre-main registration which conflicts with these statics. Changing them to constexpr resolves the issue.

## How Has This Been Tested?

SEMS, linux builds, and clang builds.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
FYI for readers: This change does _not_ require C++17.  The change contains a work-around that is correct for both C++11 and C++17.

**Comment by mhoemmen** [comment]
I examined the build warnings -- it doesn't look like these changes introduced any new warnings.  Thanks @MicheldeMessieres ! :D

**Comment by etphipp** [comment]
Stokhos has an optional configure parameter that changes the magnitude type for one of its scalar types, Sacado::MP::Vector, from double to Sacado::MP::Vector.  These changes are problematic in this case, since these changes assume magnitudeType has a suitable constexpr constructor to initialize the values.  I have local modifications on a branch [here](https://github.com/etphipp/Trilinos/tree/mp_vector_constexpr_fix) that add the necessary constexpr constructors, but I still get linking errors, I think because of C++11's rules on which kinds of types need definitions for static constexpr data members.  Would you be willing to add back the data member definitions, e.g.,
```
template<class ScalarType, class MV, class OP>
constexpr typename PseudoBlockGmresSolMgr<ScalarType,MV,OP>::MagnitudeType PseudoBlockGmresSolMgr<ScalarType,MV,OP>::convTol_default_;
```
to eliminate these linking errors?  This technically only needs to be done for the scalar/magnitude type data members, but it could be a good idea to do this for all of them (since similar linking errors can easily arise if the data member becomes odr-used, e.g., if you take the address of it or it becomes a non-inlined argument to a function).  Alternatively I could just do this in Stokhos for its scalar types.

**Comment by etphipp** [comment]
@mhoemmen I agree completely.  `Sacado::MP::Vector` does define such a type (it's called `value_type`, however with a line like:
```
static constexpr MagnitudeType convTol_default_ = 1e-8;
```
Belos is assuming `MagnitudeType` defines an implicit conversion from `double`, which I think is a reasonable assumption.  And I don't see any way you can put in an inline initialization of these values without such an assumption.  Why not just change the type of all of floating-point default values to `double`?

A related question is what the type of the corresponding parameters in the parameter list should be.  I would argue that those should be `double` as well, regardless of what `MagnitudeType` is, since that is how a user would likely want to define them in an XML file.

**Comment by mhoemmen** [comment]
@etphipp wrote:
> Why not just change the type of all of floating-point default values to double?

This is a good idea.  The only concern would be the possibility that `MagnitudeType` lacks an implicit conversion from `double`, but it's hard to imagine us wanting to support such a type.

> A related question is what the type of the corresponding parameters in the parameter list should be. I would argue that those should be `double` as well, regardless of what `MagnitudeType` is, since that is how a user would likely want to define them in an XML file.

Belos should support both `double` and `MagnitudeType`.  For example, it would be natural for users to assume `float` parameters when `Scalar=float`.  Also, if we revive extended-precision solvers, users will need to be able to specify very small convergence tolerances.

**Comment by mhoemmen** [comment]
I'm working on it now :)

**Comment by mhoemmen** [comment]
@etphipp Here's my PR: https://github.com/trilinos/Trilinos/pull/2915

**Pull request merged**
