### PR TITLE
Bring in changes to fix Trilinos for Futility and MPACT

### PR DESCRIPTION
**Pull request by bartlettroscoe**
@trilinos/kokkos-kernels, @trilinos/kokkos 

This is just incorrect CMake code.  Not sure how this works with Trilinos-based TriBITS builds but it does not work with Futrility-based TriBITS builds.

I will create PRs for the native kokkos and kokkos-kernels github repos as well so these changes don't get overwritten.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
> None of this CMake code really exists anymore. Temporary fixes are totally fine with me if necessary.

**Comment by bartlettroscoe** [comment]
> None of this CMake code really exists anymore. Temporary fixes are totally fine with me if necessary.

@jjwilke, so there is no more code like:

```
IF (${SOME_VAR})
  ...
```

?

You want just:

```
IF (SOME_VAR)
  ...
```

**Comment by jjwilke** [comment]
Correct. I mean, I may have missed some. You'll definitely want to review the PR.
The `ProjectCompilerPostConfig` mistake might still be there.

**Comment by bartlettroscoe** [comment]
> The `ProjectCompilerPostConfig` mistake might still be there.

That file lives directly under Trilinos/cmake/ so the kokkos snapshot will not overwrite it the Kokkos 2.99 promotion branch should just merge with it.

**Comment by mhoemmen** [comment]
@bartlettroscoe Did you actually mean to merge into master?  Normally I would just change this without asking, but it could be that there's some need to do this, so I'm asking first :-) .

Also, is there seriously a project called "Futility"?

**Comment by ndellingwood** [comment]
> That file lives directly under Trilinos/cmake/ so the kokkos snapshot will not overwrite it the Kokkos 2.99 promotion branch should just merge with it.

@bartlettroscoe the PR with the kokkos snapshot also includes changes to Trilinos for compatibility. In this particular release there were changes to `Trilinos/cmake/ProjectCompilerPostConfig` to support backward compatibility following updates to the kokkos build system.

**Comment by ndellingwood** [comment]
Cross-referencing #6671

**Comment by bartlettroscoe** [comment]
@jjwilke and @srajama1, can one of you please re-approve?  I accidentally had the base branch as 'master' instead of 'develop'.

**Comment by bartlettroscoe** [comment]
> Also, is there seriously a project called "Futility"?

@mhoemmen, "Fortran Utility"

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> "Fortran Utility"

"Futility" does sometimes describe the feelings we get maintaining software....

**Comment by bartlettroscoe** [comment]
Ironic the name "Futility" is in this PR and that is the status of getting this merged due to the broken PR build described in https://github.com/trilinos/Trilinos/issues/3276#issuecomment-580457742

**Pull request merged**
