### PR TITLE
lcm-mods: Modifications required for Schwarz alternating method in Albany (LCM)

### PR DESCRIPTION
**Pull request by lxmota**
This proposed changes to LOCA and Piro are necessary for the implementation of the Schwarz alternating method in Albany, specifically LCM.

This is really important for LCM, as the Schwarz method is currently being used for production runs in concurrent multiscale calculations for coupling small scale microstructure to macroscopic models.

I understand that they are not the cleanest changes, in that they expose some internals, but they are needed.

### CODE REVIEW

**Comment by ibaned** [comment]
@trilinos/nox

**Comment by ibaned** [comment]
Once a NOX developer approves the LOCA changes, I can run the checkin script for this.

**Comment by rppawlo** [comment]
Since the accessor methods are declared const, I would suggest that all of these accessors return const objects - const solver and const parameterLists. Otherwise it is too easy for the user to pull out and corrupt underlying objects. For example, if you change the parameter list, the LOCA stepper has no way of knowing it changed and needs to be reparsed/reinitialized. 

@etphipp

**Comment by ibaned** [comment]
As it happens, I believe this is actually the goal of the changes. @lxmota needed to alter the start and end time of the stepper, for example.

**Comment by lxmota** [comment]
Indeed, this is the very reason they are not constant, so they can be modified.

**Comment by rppawlo** [comment]
So if I understand correctly, you have a const Stepper object and are asking for methods to access the internal data as non-const so that you can change the Stepper anyway? That seems to defeat the purpose of declaring the Stepper const. 

Personally, I would rather see the user perform a const_cast here to modify things so that they know this is dangerous. What guarantee is there that changing the parameter list will keep the loca stepper in sync. It may have already parsed the parameter list for construction of subobjects.  Just my two cents - it's up to @etphipp to sign off on this.

**Comment by etphipp** [comment]
I'll echo Roger's comments here.  If the methods are declared const, the methods should return const objects.  Why does the LOCA Stepper you are calling these methods on need to be const?

**Comment by lxmota** [comment]
@rppawlo @etphipp Yes, quite right. Those were leftovers from sometime ago. I just removed the const for those methods.

**Comment by ibaned** [comment]
Awesome, I think @etphipp is the key approver here. I'll start the checkin script.

**Comment by lxmota** [comment]
@ibaned Great, thanks! This helps LCM a lot.

**Pull request merged**
