### PR TITLE
Seacas update embedded fmt version

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas 

## Motivation
Update the embedded fmt library used in SEACAS for Trilinos builds to be the latest version to see if that fixes any problems encountered with the C++20 compiler

### CODE REVIEW

**Review by rppawlo — APPROVED** [review]
Thanks @gsjaardema !

**Comment by gsjaardema** [comment]
@rppawlo Let me know if this fixes the C++20 constexpr issues you were seeing or if we need to look deeper.

**Comment by rppawlo** [comment]
@gsjaardema - unfortunately, the errors are still there. Here's an example.
```
/tmp/BUILD_EMPIRE/Trilinos/packages/seacas/libraries/ioss/src/Ioss_DecompositionUtils.C:523:21:   in ‘constexpr’ expansion of ‘fmt::v9::basic_format_string<char, long unsigned int&, long unsigned int&, fmt::v9::group_digits_vie\
w<long unsigned int>, long unsigned int&, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(format)’
/tmp/BUILD_EMPIRE/Trilinos/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:3167:62:   in ‘constexpr’ expansion of ‘((fmt::v9::basic_format_string<char, long unsigned int&, long unsigned int&, fmt::v9::group_digit\
s_view<long unsigned int>, long unsigned int&, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>*)this)->fmt::v9::basic_format_string<char, long unsigned int&, long unsigned int&, fmt::v9\
::group_digits_view<long unsigned int>, long unsigned int&, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::str_.fmt::v9::basic_string_view<char>::basic_string_view<std::char_traits<ch\
ar>, std::allocator<char> >((* & s))’
/tmp/BUILD_EMPIRE/Trilinos/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:463:21:   in ‘constexpr’ expansion of ‘(& s)->std::__cxx11::basic_string<char>::data()’
/projects/empire/devel/x86_64/compilers/gcc-12.2.0/include/c++/12.2.0/bits/basic_string.h:2568:23:   in ‘constexpr’ expansion of ‘((const std::__cxx11::basic_string<char>*)this)->std::__cxx11::basic_string<char>::_M_data()’
/tmp/BUILD_EMPIRE/Trilinos/packages/seacas/libraries/ioss/src/Ioss_DecompositionUtils.C:523:21: error: the value of ‘format’ is not usable in a constant expression
  523 |           fmt::print(format, i, proc_width, fmt::group_digits(elem_per_rank[i]), work_width,
      |           ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  524 |                      elem_per_rank[i] / avg_work, stars);
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/BUILD_EMPIRE/Trilinos/packages/seacas/libraries/ioss/src/Ioss_DecompositionUtils.C:505:21: note: ‘format’ was not declared ‘constexpr’
  505 |         std::string format = "\tProcessor {:{}}, work = {:{}}  ({:.2f})\t{}\n";
      |                     ^~~~~~
```

**Comment by gsjaardema** [comment]
So this is just basically seen by building Trilinos and/or SEACAS with C++20 enabled is that right?

**Comment by gsjaardema** [comment]
OK, I can't reproduce yet, but can you try changing `format` on line 523 to `fmt::runtime(format)` and see if that does anything.  

Maybe also/instead add a `const` to the `std::string format` on line 505...

**Comment by gsjaardema** [comment]
OK, I can get the failure on the CEE machines; just not on my Mac...   Will see what I can do now that it isn't "try this..." debugging.

**Comment by rppawlo** [comment]
Thanks @gsjaardema ! That's where I was seeing this - on the cee machines.

**Comment by gsjaardema** [comment]
See #13405 for more fixes related to C++20 build

**Pull request merged**
