### PR TITLE
MueLu: region matvec, see issue #7175

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/muelu

## Motivation
This should accelerate significantly the matvec costs associated with the region format as it now performs only one neighbor communication instead of tow.

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of #7175
* Composed of 

## Stakeholder Feedback
This work is part of an ASCR project with @rstumin and @lucbv 

## Testing
Local tests have been performed and so far all are passing except for elasticity problems since this PR only addresses the scalar equation case. A follow-up PR will tackle the multiple dof per node case, in the meantime, a runtime parameter can be selected to use the "slow path" for matvec that works with system of PDEs.

## Additional Information
Work remaining before this PR is complete:
1. add capabilities for multiple dofs per node
2. modify the matvec implementation to expose the Kokkos-kernel call which will allow to easily write higher performance matvec algorithm based on structured grid assumptions
3. create a matvec specific driver to assess the performance of various kernels implementations based on the structure of the grid

### CODE REVIEW

**Comment by mayrmt** [comment]
@lucbv I have completed the first steps towards multiple DOFs per node. Here's what I did:
- create unit test for FastMatVec using an "Elasticity2D" matrix
- adapt indexing in in `createRegionData()`, when computing the LIDs and GIDs of interface DOFs

I've verified the outcome of `createRegionData()` with a 7x7 nodes/4 regions mesh w/ 2 DOFs per node as sketched out here: 
IMG_3020_small
List of LIDs/GIDs are computed as expected.

When proceeding to call `SetupMatVec()`,  the lines
```c++
  Teuchos::Array<GO> regionMatVecGIDs;
  Array<ArrayRCP<const LO> > regionsPerGIDWithGhostsData(maxRegPerGID);
  Array<ArrayRCP<const GO> > interfaceGIDsData(maxRegPerGID);
  for(LO regionIdx = 0; regionIdx < maxRegPerGID; ++regionIdx) {
    regionsPerGIDWithGhostsData[regionIdx] = regionsPerGIDWithGhosts->getData(regionIdx);
    interfaceGIDsData[regionIdx] = interfaceGIDsPerGrp[0]->getData(regionIdx); /* That's the line causing trouble */
    for(LO idx = 0; idx < static_cast<LO>(regionsPerGIDWithGhostsData[regionIdx].size()); ++idx) {
      if((regionsPerGIDWithGhostsData[regionIdx][idx] != -1)
         && (regionsPerGIDWithGhostsData[regionIdx][idx] != myRank)) {
        regionMatVecLIDs.push_back(idx);
        regionMatVecGIDs.push_back(interfaceGIDsData[regionIdx][idx]);
      }
    }
  }
```
(Troubling line marked with comment)
results in this error:
```
p=0: *** Caught standard std::exception of type 'std::logic_error' :
 
  /ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:2917:
  
  Throw number = 1
  
  Throw test that evaluated to true: (static_cast<size_t> (hostView_j.extent (0)) < static_cast<size_t> (dataAsArcp.size ()))
  
  Tpetra::MultiVector<long long,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::getData: hostView_j.extent(0) = 32 < dataAsArcp.size() = 64.  Please report this bug to the Tpetra developers.
```
According to the code in `packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:2917:`, this error occurs during the `getData()` call.

Any ideas?

**Comment by mayrmt** [comment]
Update: Above's error is independent of the choice of `<Scalar,LocalOrdinal,GlobalOrdinal>` template parameters. It occurs for both `<int,int,int>` and `<long long, int, long long>`.

**Comment by lucbv** [comment]
@mayrmt will get a look at this tomorrow, hopefully this can be fixed easily?

**Comment by mayrmt** [comment]
@lucbv I haven't pushed my changes yet. Since @rstumin might use this branch for performance testing, I don't want to break it.

Just let me know, if you need my current status of the code and how I should provide it.

**Pull request merged**
