### PR TITLE
Resolves "Fill out CONTRIBUTING.md"

### PR DESCRIPTION
**Pull request by jmgate**
As per #1823, the basics of creating an issue, working it, and submitting a pull request are now here.  We'll likely want to refine what's in here though.  For instance:
* Do we want developers with push-access to Trilinos to use a fork anyway?
* Do we want to specify a feature branch naming convention?
* Do we care if contributors update their feature branches via `merge`s or `rebase`s?
* Should there be more detail in the **Feedback** section?

Note that these changes assume #1822 gets merged into `develop`, as the detailed instructions for filling out new issues and pull requests are contained in those templates.

@trilinos/framework

### CODE REVIEW

**Comment by jmgate** [comment]
@maherou, @bmpersc, @jwillenbring, can I get a review on this?

**Comment by jmgate** [comment]
Based on @kddevin's suggestions, I'll update this PR with more specifics on the git commands to accomplish the workflow.

**Comment by jmgate** [comment]
@kddevin, can you take a look at [this CONTRIBUTING.md file](https://github.com/jmgate/Trilinos/blob/1823-fillOutContributing/CONTRIBUTING.md) and let me know if that's roughly what you are looking for in a one-page instruction sheet for interacting with Trilinos as far as git is concerned?  If anything is unclear, needs more explanation, or is otherwise missing, please let me know.  Many thanks.

**Comment by jmgate** [comment]
@jwillenbring, do we want to tie in to the [Trilinos New Developer Checklist](https://docs.google.com/document/d/1QrnbxQVubimMGeQwmajr_zXtd-QLAksBbfsvTyMDGY4/edit) in this [CONTRIBUTING.md](https://github.com/jmgate/Trilinos/blob/1823-fillOutContributing/CONTRIBUTING.md) file?  Or any other pages on the Trilinos wiki for that matter?

**Comment by jmgate** [comment]
@wfspotz, this may be useful for whatever "Trilinos Bootcamp" you put together for summer students.

**Comment by maherou** [comment]
I am merging this PR.  It is a good starting point.

**Comment by jmgate** [comment]
Thanks again.

**Comment by kddevin** [comment]
@jmgate Thank you for drafting a "How To" page for working with the fork / branch / pull request model.  I am working through the instructions and ran into the following problem:
-  I created the fork
-  I cloned the fork
-  I cd'ed to the fork's directory
-  I tried to add the upstream repo, but I get a fatal error:
% git add upstream git@github.com:trilinos/Trilinos
fatal: pathspec 'upstream' did not match any files

Is there a step missing?  Thanks.

**Comment by jmgate** [comment]
@kddevin, thanks for catching this.  The command should be `git` **`remote`** `add upstream git@github.com:trilinos/Trilinos`.  I'll fix this in `CONTRIBUTING.md` and push.

**Comment by kddevin** [comment]
Thanks, @jmgate .  Should the fix appear on the wiki page now (using the links to CONTRIBUTING.md above)?  I do not see it there.

**Comment by jmgate** [comment]
Since this pull request was already merged into `develop`, I made the update on `develop` itself.  You can view the updated file [here](https://github.com/trilinos/Trilinos/blob/develop/CONTRIBUTING.md).

**Comment by kddevin** [comment]
Does the "git remote add upstream..."  have to be done in every clone of the fork (e.g., if I clone it on two different workstations)?  Or just the first time the fork is cloned is used?

**Comment by jmgate** [comment]
Adding a remote is something that's done to a local repository, so every time you create a new local repository via `clone`, you'll have to go through these same setup steps.  If you're unsure whether or not the local repository you're currently using has an `upstream` remote, you can `git remote -v` to list all the remotes you're connected to.

**Comment by kddevin** [comment]
Thanks, @jmgate 
Is this file something I can edit to change "After you clone" to "Each time you clone" (or similar)?  I understand if you prefer to limit the people who edit.

**Comment by jmgate** [comment]
Yes, just look for `CONTRIBUTING.md` in the root `Trilinos/` directory (it should be a sibling of `README.md`, for instance).  Feel free to make that change and push to `develop`.  I'd expected to iterate on the design a bit in this pull request, but since we went ahead and merged it in, we can just make the necessary modifications on `develop` as we would any other file in Trilinos.  Thanks @kddevin for being the beta-tester here.

**Pull request merged**
