### PR TITLE
Master merge 20221027 175815

### PR DESCRIPTION
**Pull request by e10harvey**
@trilinos/<teamName>

### CODE REVIEW

**Comment by e10harvey** [comment]
@DaveBeCoding: Note that https://github.com/trilinos/Trilinos/pull/11181 was closed due to a blocking issue. This PR was then opened to unblocked master merge.

**Comment by e10harvey** [comment]
@trilinos/zoltan, FYI - https://trilinos-cdash.sandia.gov/test/14773654. Judging by the [CDash history of this test](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-10-03&end=2022-10-27&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=Zoltan_canarySelfMessages_MPI_2&field2=buildname&compare2=63&value2=cuda-11&field3=status&compare3=61&value3=Failed), this looks like a random failure.

**Comment by e10harvey** [comment]
@trilinos/ifpack2: Is this a random failure or something that needs to be addressed https://trilinos-cdash.sandia.gov/test/15143406:
```
Every proc reading parameters from xml_file: test_Cheby_calore1_mm.xml
Matrix Market file for sparse matrix A: calore1.mtx
Matrix Market file for right-hand-side(s) B: calore1_rhs.mtx
Configuring, initializing, and computing Ifpack2 preconditioner
 Time Init: 4.91142e-05
 Finished computing Ifpack2 preconditioner
  Time (s): 0.00065589
Converged in 34 iterations.
Preconditioner attributes:
 "Ifpack2::Chebyshev":
  Template parameters:
   Scalar: double
   LocalOrdinal: int
   GlobalOrdinal: long long
   Device: Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>
  Initialized: true
  Computed: true
   "Ifpack2::Details::Chebyshev":
    degree: 3
    lambdaMax: -8.47801
    alpha: 30
    lambdaMin: -0.2826
    boost factor: 1.1
  Global matrix dimensions: [99, 99]
  Global nnz: 1531
2-Norm of 0th RHS      vec: 6.76023
2-Norm of 0th residual vec: 4.85573e-07 -> 7.18279e-08
Achieved tolerance: 7.18279e-08, Requested tolerance: 1e-07
Actual iters(34) > expected number of iterations (32), or resid-norm(7.18279e-08) >= 1e-07
proc 0 total program time: 0.0206459
End Result: TEST FAILED
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[12866,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

CC: @DaveBeCoding, @ccober6

**Comment by e10harvey** [comment]
> That's something that needs to be addressed. Producing eigenvalue estimate of `lambdaMax: -8.47801` is definitely not ok.

@cgcgcg: Thanks! If you flag me in the PR that fixes this I will rebase these changes on top of develop once the PR merges.

**Comment by cgcgcg** [comment]
I'll need some instructions on how to reproduce it. In my local build it seems to pass just fine.

**Comment by e10harvey** [comment]
It also seems to have passed fine in the previous 4 test iterations before this last failure.

**Comment by cgcgcg** [comment]
It passed a
```
ctest --repeat-until-fail 1000 -R Ifpack2_Cheby_belos_MPI_1
```
on my system.

**Comment by GrahamBenHarper** [comment]
> It also seems to have passed fine in the previous 4 test iterations before this last failure.

FYI @cgcgcg and I looked into this in detail, and I was able to reproduce the failures on my machine. The problem uses a random vector to solve a fixed matrix, but the fixed matrix has some additionally bad properties (two dominant eigenvalues, one being 12.5839, the other being -10.6639), so it occasionally gets confused and stuck on the wrong eigenvalue. I'll fix this on develop by increasing the iteration count slightly, but overall it's a rarely-occuring non-issue.

**Pull request merged**
