### PR TITLE
move ML_Operator_Copy_Statistics to ml_op_utils

### LINKED ISSUE #860: ML: implicit declaration of function ‘ML_Operator_Copy_Statistics’
From [the Debian build](https://qa.debian.org/bls/packages/t/trilinos.html):
```
"/<<PKGBUILDDIR>>/packages/ml/src/Coarsen/ml_aggregate.c"
/<<PKGBUILDDIR>>/packages/ml/src/Coarsen/ml_aggregate.c: In function ‘ML_repartition_matrix’:
/<<PKGBUILDDIR>>/packages/ml/src/Coarsen/ml_aggregate.c:2097:3: warning: implicit declaration of function ‘ML_Operator_Copy_Statistics’ [-Wimplicit-function-declaration]
   ML_Operator_Copy_Statistics(mat,permuted_Amat);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by nschloe**
Fixes #860.

### CODE REVIEW

**Comment by ibaned** [comment]
@trilinos/ml @aprokop

**Comment by nschloe** [comment]
Is there anything I can do to help getting this merged?

**Comment by ibaned** [comment]
@aprokop has approved this, so I guess I'll go ahead and merge it via the `checkin-test-sems.sh` script

**Comment by ibaned** [comment]
By the way, in the future please point pull requests to the `develop` branch, not `master`. Then people can accept them via the GitHub interface if they are small enough changes (I was wondering why the "merge" button was not accessible to me for this PR...)

**Comment by nschloe** [comment]
Thanks @ibaned for the reminder. I faintly remember that I ran into this master-develop issue before, but I can't quite remember which to clone and which to point PRs to. It's weird that they aren't the same.

**Comment by ibaned** [comment]
The changes are in `develop` via `checkin-test-sems`.

**Comment by aprokop** [comment]
Thanks, @ibaned !

**Pull request closed without merging**
