### PR TITLE
Tpetra: revert TAFC changes

### PR DESCRIPTION
**Pull request by jhux2**
Until we can diagnose segfaults reported wrt PR #13598.

This reverts commit 7eb5fe535ba8dd8bcd0172292e7b19c194c1c852, reversing changes made to e20e3cddc5391f2e148f4a4cf88f127badcdd457.

@trilinos/<teamName>

## Motivation

Segfaults reported in MiniEM.

## Related Issues

* Closes `put-issue-number-here`

## Stakeholder Feedback

N/A

## Testing

@skennon10 confirmed that reverted this MR fixes observed segfaults.

### CODE REVIEW

**Comment by jhux2** [comment]
@NyquilDreams

**Comment by eugeneswalker** [comment]
Without this PR I was seeing segfaults for all of the following tests:
```
Amesos2_KLU2_Solver_Test_MPI_2
Amesos2_KLU2_UnitTests_MPI_2
Amesos2_SolverFactory_UnitTests_MPI_4
Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4
TpetraCore_AdditiveSchwarzHalo_MPI_4
TpetraCore_AsyncTransfer_UnitTests_MPI_4
TpetraCore_BlockCrsMatrix_MPI_4
TpetraCore_Bug10008_MPI_4
TpetraCore_CrsMatrix_Bug8447_MPI_2
TpetraCore_CrsMatrix_transpose_sortedRows_MPI_4
TpetraCore_FECrs_MatrixMatrix_UnitTests_MPI_4
TpetraCore_ImportExport2_UnitTests_Alltoall_MPI_4
TpetraCore_ImportExport2_UnitTests_ISend_MPI_4
TpetraCore_ImportExport2_UnitTests_Send_MPI_4
TpetraCore_MatrixMatrix_UnitTests_MPI_4
TpetraCore_RowMatrixTransposer_test_MPI_4
TpetraCore_RowMatrixTransposer_UnitTests_MPI_4
Zoltan2_Coloring1_commanchedual_D1_nonzeros_MPI_4
Zoltan2_Coloring1_commanchedual_D1_rows_MPI_4
Zoltan2_Coloring1_commanchedual_D1-2GL_nonzeros_MPI_4
Zoltan2_Coloring1_commanchedual_D1-2GL_rows_MPI_4
Zoltan2_Coloring1_commanchedual_D2_MPI_4
Zoltan2_Coloring1_commanchedual_D2_nonzeros_MPI_4
Zoltan2_Coloring1_commanchedual_D2_rows_MPI_4
Zoltan2_Coloring1_commanchedual_PD2_MPI_4
Zoltan2_Coloring1_commanchedual_PD2_nonzeros_MPI_4
Zoltan2_Coloring1_commanchedual_PD2_rows_MPI_4
Zoltan2_Coloring1_complete_D2_MPI_4
Zoltan2_Coloring1_complete_PD2_MPI_4
Zoltan2_Coloring1_simple_D1_nonzeros_MPI_4
Zoltan2_Coloring1_simple_D1_rows_MPI_4
Zoltan2_Coloring1_simple_D1-2GL_nonzeros_MPI_4
Zoltan2_Coloring1_simple_D1-2GL_rows_MPI_4
Zoltan2_Coloring1_simple_D2_MPI_4
Zoltan2_Coloring1_simple_D2_nonzeros_MPI_4
Zoltan2_Coloring1_simple_D2_recolor_degrees_MPI_4
Zoltan2_Coloring1_simple_D2_rows_MPI_4
Zoltan2_Coloring1_simple_D2_serial_threshold_25_MPI_4
Zoltan2_Coloring1_simple_PD2_MPI_4
Zoltan2_Coloring1_simple_PD2_nonzeros_MPI_4
Zoltan2_Coloring1_simple_PD2_recolor_degrees_MPI_4
Zoltan2_Coloring1_simple_PD2_rows_MPI_4
Zoltan2_Coloring1_simple_PD2_serial_threshold_25_MPI_4
Zoltan2_GraphModel_MPI_4
Zoltan2_Partitioning1_ParMETIS_EWeights_MPI_4
Zoltan2_Partitioning1_ParMETIS_MPI_4
Zoltan2_Partitioning1_ParMETIS_OneProc_EWeights_MPI_4
Zoltan2_Partitioning1_ParMETIS_OneProc_MPI_4
Zoltan2_Partitioning1_ParMETIS_OneProc_VWeights_MPI_4
Zoltan2_Partitioning1_ParMETIS_VWeights_MPI_4
Zoltan2_Partitioning1_Quotient_MPI_4
Zoltan2_Partitioning1_Quotient_OneProc_MPI_4
Zoltan2_Partitioning1_Quotient_OneProc_Threshold1_MPI_4
Zoltan2_Partitioning1_Quotient_OneProc_Threshold2_MPI_4
Zoltan2_Partitioning1_Quotient_Threshold1_MPI_4
Zoltan2_Partitioning1_Quotient_Threshold2_MPI_4
Zoltan2_TpetraCrsColorer_galeri1_MPI_4
Zoltan2_TpetraCrsColorer_galeri2_MPI_4
Zoltan2_TpetraCrsColorer_simple_MPI_4
Zoltan2_TpetraCrsColorer_simple_nodistrib_MPI_4
Zoltan2_TpetraCrsColorer_troublecauser_MPI_4
Zoltan2_TpetraCrsColorer_west0067_MPI_4
Zoltan2_TpetraCrsColorer_west0067_nodistrib_MPI_4
Zoltan2_XpetraCrsMatrixInput_MPI_4
Zoltan2_XpetraTraits_MPI_4
```

With this PR I only see the following test from the above list continuing to segfault:
* Amesos2_SolverFactory_UnitTests_MPI_4
```
root@17e849900a29:/build# ctest --timeout 180 --output-on-failure -R "Amesos2_SolverFactory_UnitTests_MPI_4"
Test project /build
    Start 785: Amesos2_SolverFactory_UnitTests_MPI_4
1/1 Test #785: Amesos2_SolverFactory_UnitTests_MPI_4 ...***Failed  Required regular expression not found. Regex=[End Result: TEST PASSED
]  4.15 sec
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name 17e849900a29 and rank 0!

***
*** Unit test suite ...
***


Sorting tests by group name then by the order they were added ... (time = 2.58e-06)

Running unit tests ...

0. SolverFactory_double_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_Solve_UnitTest ... Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name 17e849900a29 and rank 1!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name 17e849900a29 and rank 2!
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name 17e849900a29 and rank 3!

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 1346602 RUNNING AT 17e849900a29
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions


0% tests passed, 1 tests failed out of 1

Subproject Time Summary:
Amesos2    =  16.61 sec*proc (1 test)

Total Test time (real) =   4.72 sec

The following tests FAILED:
	785 - Amesos2_SolverFactory_UnitTests_MPI_4 (Failed)
Errors while running CTest
```

**Comment by NyquilDreams** [comment]
> Without this PR I was seeing segfaults for all of the following tests:
> 
> ```
> Amesos2_KLU2_Solver_Test_MPI_2
> Amesos2_KLU2_UnitTests_MPI_2
> Amesos2_SolverFactory_UnitTests_MPI_4
> Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4
> TpetraCore_AdditiveSchwarzHalo_MPI_4
> TpetraCore_AsyncTransfer_UnitTests_MPI_4
> TpetraCore_BlockCrsMatrix_MPI_4
> TpetraCore_Bug10008_MPI_4
> TpetraCore_CrsMatrix_Bug8447_MPI_2
> TpetraCore_CrsMatrix_transpose_sortedRows_MPI_4
> TpetraCore_FECrs_MatrixMatrix_UnitTests_MPI_4
> TpetraCore_ImportExport2_UnitTests_Alltoall_MPI_4
> TpetraCore_ImportExport2_UnitTests_ISend_MPI_4
> TpetraCore_ImportExport2_UnitTests_Send_MPI_4
> TpetraCore_MatrixMatrix_UnitTests_MPI_4
> TpetraCore_RowMatrixTransposer_test_MPI_4
> TpetraCore_RowMatrixTransposer_UnitTests_MPI_4
> Zoltan2_Coloring1_commanchedual_D1_nonzeros_MPI_4
> Zoltan2_Coloring1_commanchedual_D1_rows_MPI_4
> Zoltan2_Coloring1_commanchedual_D1-2GL_nonzeros_MPI_4
> Zoltan2_Coloring1_commanchedual_D1-2GL_rows_MPI_4
> Zoltan2_Coloring1_commanchedual_D2_MPI_4
> Zoltan2_Coloring1_commanchedual_D2_nonzeros_MPI_4
> Zoltan2_Coloring1_commanchedual_D2_rows_MPI_4
> Zoltan2_Coloring1_commanchedual_PD2_MPI_4
> Zoltan2_Coloring1_commanchedual_PD2_nonzeros_MPI_4
> Zoltan2_Coloring1_commanchedual_PD2_rows_MPI_4
> Zoltan2_Coloring1_complete_D2_MPI_4
> Zoltan2_Coloring1_complete_PD2_MPI_4
> Zoltan2_Coloring1_simple_D1_nonzeros_MPI_4
> Zoltan2_Coloring1_simple_D1_rows_MPI_4
> Zoltan2_Coloring1_simple_D1-2GL_nonzeros_MPI_4
> Zoltan2_Coloring1_simple_D1-2GL_rows_MPI_4
> Zoltan2_Coloring1_simple_D2_MPI_4
> Zoltan2_Coloring1_simple_D2_nonzeros_MPI_4
> Zoltan2_Coloring1_simple_D2_recolor_degrees_MPI_4
> Zoltan2_Coloring1_simple_D2_rows_MPI_4
> Zoltan2_Coloring1_simple_D2_serial_threshold_25_MPI_4
> Zoltan2_Coloring1_simple_PD2_MPI_4
> Zoltan2_Coloring1_simple_PD2_nonzeros_MPI_4
> Zoltan2_Coloring1_simple_PD2_recolor_degrees_MPI_4
> Zoltan2_Coloring1_simple_PD2_rows_MPI_4
> Zoltan2_Coloring1_simple_PD2_serial_threshold_25_MPI_4
> Zoltan2_GraphModel_MPI_4
> Zoltan2_Partitioning1_ParMETIS_EWeights_MPI_4
> Zoltan2_Partitioning1_ParMETIS_MPI_4
> Zoltan2_Partitioning1_ParMETIS_OneProc_EWeights_MPI_4
> Zoltan2_Partitioning1_ParMETIS_OneProc_MPI_4
> Zoltan2_Partitioning1_ParMETIS_OneProc_VWeights_MPI_4
> Zoltan2_Partitioning1_ParMETIS_VWeights_MPI_4
> Zoltan2_Partitioning1_Quotient_MPI_4
> Zoltan2_Partitioning1_Quotient_OneProc_MPI_4
> Zoltan2_Partitioning1_Quotient_OneProc_Threshold1_MPI_4
> Zoltan2_Partitioning1_Quotient_OneProc_Threshold2_MPI_4
> Zoltan2_Partitioning1_Quotient_Threshold1_MPI_4
> Zoltan2_Partitioning1_Quotient_Threshold2_MPI_4
> Zoltan2_TpetraCrsColorer_galeri1_MPI_4
> Zoltan2_TpetraCrsColorer_galeri2_MPI_4
> Zoltan2_TpetraCrsColorer_simple_MPI_4
> Zoltan2_TpetraCrsColorer_simple_nodistrib_MPI_4
> Zoltan2_TpetraCrsColorer_troublecauser_MPI_4
> Zoltan2_TpetraCrsColorer_west0067_MPI_4
> Zoltan2_TpetraCrsColorer_west0067_nodistrib_MPI_4
> Zoltan2_XpetraCrsMatrixInput_MPI_4
> Zoltan2_XpetraTraits_MPI_4
> ```
> 
> With this PR I only see the following test from the above list continuing to segfault:
> 
> * Amesos2_SolverFactory_UnitTests_MPI_4
> 
> ```
> root@17e849900a29:/build# ctest --timeout 180 --output-on-failure -R "Amesos2_SolverFactory_UnitTests_MPI_4"
> Test project /build
>     Start 785: Amesos2_SolverFactory_UnitTests_MPI_4
> 1/1 Test #785: Amesos2_SolverFactory_UnitTests_MPI_4 ...***Failed  Required regular expression not found. Regex=[End Result: TEST PASSED
> ]  4.15 sec
> Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name 17e849900a29 and rank 0!
> 
> ***
> *** Unit test suite ...
> ***
> 
> 
> Sorting tests by group name then by the order they were added ... (time = 2.58e-06)
> 
> Running unit tests ...
> 
> 0. SolverFactory_double_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_Solve_UnitTest ... Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name 17e849900a29 and rank 1!
> Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name 17e849900a29 and rank 2!
> Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name 17e849900a29 and rank 3!
> 
> ===================================================================================
> =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
> =   PID 1346602 RUNNING AT 17e849900a29
> =   EXIT CODE: 139
> =   CLEANING UP REMAINING PROCESSES
> =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
> ===================================================================================
> YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
> This typically refers to a problem with your application.
> Please see the FAQ page for debugging suggestions
> 
> 
> 0% tests passed, 1 tests failed out of 1
> 
> Subproject Time Summary:
> Amesos2    =  16.61 sec*proc (1 test)
> 
> Total Test time (real) =   4.72 sec
> 
> The following tests FAILED:
> 	785 - Amesos2_SolverFactory_UnitTests_MPI_4 (Failed)
> Errors while running CTest
> ```

@eugeneswalker Hi Eugene, can you inform me of how you got these errors so I can recreate and fix them? A reproducer and information about your configuration would be helpful. Thanks.

**Comment by eugeneswalker** [comment]
> @eugeneswalker Hi Eugene, can you inform me of how you got these errors so I can recreate and fix them? A reproducer and information about your configuration would be helpful. Thanks.

Yes, absolutely.

We do our Trilinos builds inside Docker with GPU mapped in via nvidia-container-toolkit at the University of Oregon.

Here is how you could reproduce it:
```
$> docker run -it --name trici-reproducer --gpus all esw123/trilinos-ci-cuda12.2.2:2024.11.05

# Clone source
root@460687cf30e1:/build# git clone https://github.com/trilinos/Trilinos /Trilinos
root@460687cf30e1:/build# git -C /Trilinos checkout d7d7ee234aaecf6fbed4bf3360d34770adc5d0d1

# CMake
root@17e849900a29:/build# export SOURCE_DIR=/Trilinos
root@17e849900a29:/build# export MPICH_CXX=$SOURCE_DIR/packages/kokkos/bin/nvcc_wrapper
root@17e849900a29:/build# export KOKKOS_ARCH=AMPERE80
root@460687cf30e1:/build# ./cmake.sh 2>&1 | tee cmake.output

# Build
root@460687cf30e1:/build# time ninja -j32
...

# Run tests
ctest --timeout 180 --output-on-failure -R "TpetraCore_BlockCrsMatrix_MPI_4|TpetraCore_Bug10008_MPI_4|TpetraCore_CrsMatrix_Bug8447_MPI_2|TpetraCore_ImportExport2_UnitTests_Send_MPI_4|TpetraCore_ImportExport2_UnitTests_ISend_MPI_4|TpetraCore_ImportExport2_UnitTests_Alltoall_MPI_4|TpetraCore_AsyncTransfer_UnitTests_MPI_4|TpetraCore_MatrixMatrix_UnitTests_MPI_4|TpetraCore_FECrs_MatrixMatrix_UnitTests_MPI_4|TpetraCore_RowMatrixTransposer_test_MPI_4|TpetraCore_RowMatrixTransposer_UnitTests_MPI_4|TpetraCore_CrsMatrix_transpose_sortedRows_MPI_4|TpetraCore_AdditiveSchwarzHalo_MPI_4|Amesos2_KLU2_UnitTests_MPI_2|Amesos2_KLU2_Solver_Test_MPI_2|Amesos2_SolverFactory_UnitTests_MPI_4|Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4|Zoltan2_XpetraTraits_MPI_4|Zoltan2_XpetraCrsMatrixInput_MPI_4|Zoltan2_GraphModel_MPI_4|Zoltan2_Partitioning1_ParMETIS_MPI_4|Zoltan2_Partitioning1_ParMETIS_OneProc_MPI_4|Zoltan2_Partitioning1_ParMETIS_VWeights_MPI_4|Zoltan2_Partitioning1_ParMETIS_OneProc_VWeights_MPI_4|Zoltan2_Partitioning1_ParMETIS_EWeights_MPI_4|Zoltan2_Partitioning1_ParMETIS_OneProc_EWeights_MPI_4|Zoltan2_Partitioning1_Quotient_MPI_4|Zoltan2_Partitioning1_Quotient_OneProc_MPI_4|Zoltan2_Partitioning1_Quotient_Threshold1_MPI_4|Zoltan2_Partitioning1_Quotient_Threshold2_MPI_4|Zoltan2_Partitioning1_Quotient_OneProc_Threshold1_MPI_4|Zoltan2_Partitioning1_Quotient_OneProc_Threshold2_MPI_4|Zoltan2_TpetraCrsColorer_simple_MPI_4|Zoltan2_TpetraCrsColorer_simple_nodistrib_MPI_4|Zoltan2_TpetraCrsColorer_west0067_MPI_4|Zoltan2_TpetraCrsColorer_west0067_nodistrib_MPI_4|Zoltan2_TpetraCrsColorer_galeri1_MPI_4|Zoltan2_TpetraCrsColorer_galeri2_MPI_4|Zoltan2_TpetraCrsColorer_troublecauser_MPI_4|Zoltan2_Coloring1_simple_D1_rows_MPI_4|Zoltan2_Coloring1_simple_D1_nonzeros_MPI_4|Zoltan2_Coloring1_commanchedual_D1_rows_MPI_4|Zoltan2_Coloring1_commanchedual_D1_nonzeros_MPI_4|Zoltan2_Coloring1_simple_D1-2GL_rows_MPI_4|Zoltan2_Coloring1_simple_D1-2GL_nonzeros_MPI_4|Zoltan2_Coloring1_commanchedual_D1-2GL_rows_MPI_4|Zoltan2_Coloring1_commanchedual_D1-2GL_nonzeros_MPI_4|Zoltan2_Coloring1_simple_D2_MPI_4|Zoltan2_Coloring1_simple_D2_recolor_degrees_MPI_4|Zoltan2_Coloring1_simple_D2_serial_threshold_25_MPI_4|Zoltan2_Coloring1_simple_D2_rows_MPI_4|Zoltan2_Coloring1_simple_D2_nonzeros_MPI_4|Zoltan2_Coloring1_commanchedual_D2_MPI_4|Zoltan2_Coloring1_commanchedual_D2_rows_MPI_4|Zoltan2_Coloring1_commanchedual_D2_nonzeros_MPI_4|Zoltan2_Coloring1_complete_D2_MPI_4|Zoltan2_Coloring1_simple_PD2_MPI_4|Zoltan2_Coloring1_simple_PD2_recolor_degrees_MPI_4|Zoltan2_Coloring1_simple_PD2_serial_threshold_25_MPI_4|Zoltan2_Coloring1_simple_PD2_rows_MPI_4|Zoltan2_Coloring1_simple_PD2_nonzeros_MPI_4|Zoltan2_Coloring1_commanchedual_PD2_MPI_4|Zoltan2_Coloring1_commanchedual_PD2_rows_MPI_4|Zoltan2_Coloring1_commanchedual_PD2_nonzeros_MPI_4|Zoltan2_Coloring1_complete_PD2_MPI_4"
...
0% tests passed, 65 tests failed out of 65

Subproject Time Summary:
Amesos2    =  40.32 sec*proc (4 tests)
Tpetra     = 183.10 sec*proc (13 tests)
Zoltan2    = 696.32 sec*proc (48 tests)

Total Test time (real) = 234.73 sec
```

I shared this with @kuberry and I believe he shared with @ndellingwood and they were able to reproduce it. They may have used podman instead of Docker, but same concept.

Here is a failed pipeline run that shows the error:
* [Trilinos NVIDIA-A100](https://gitlab.e4s.io/uo-public/trilinos/-/jobs/329060)
* Build artifacts here: https://gitlab.e4s.io/uo-public/trilinos/-/jobs/329060/artifacts/browse/artifacts/

**Comment by jhux2** [comment]
@kuberry @ndellingwood Is there an image that @NyquilDreams could use on the CEE lan?

**Comment by ndellingwood** [comment]
@jhux2 It may require signin to dockerhub, but the esw123/trilinos-ci-cuda12.2.2:2024.11.05 image is publicly available, this should pull it to a machine:
```
podman pull esw123/trilinos-ci-cuda12.2.2:2024.11.05
```

I've had some issues with podman on cee hpws related to subuid/gid and have not tested the image myself

**Comment by kuberry** [comment]
Hi @jhux2, the following should work for you:
```
>> ssh caraway
>> salloc -N 1 -p A100
>> docker login -u your_username
>> docker pull esw123/trilinos-ci-cuda12.2.2:2024.11.05
>> docker run -it --name trici-reproducer --device nvidia.com/gpu=all esw123/trilinos-ci-cuda12.2.2:2024.11.05
container>> git clone https://github.com/trilinos/Trilinos /Trilinos
container>> git -C /Trilinos checkout d7d7ee234aaecf6fbed4bf3360d34770adc5d0d1
container>> export SOURCE_DIR=/Trilinos
container>> export MPICH_CXX=$SOURCE_DIR/packages/kokkos/bin/nvcc_wrapper
container>> export KOKKOS_ARCH=AMPERE80
container>> ./cmake.sh 2>&1 | tee cmake.output
container>> time ninja -j32
container>> ctest --timeout 180 --output-on-failure -R "TpetraCore_BlockCrsMatrix_MPI_4|TpetraCore_Bug10008_MPI_4|TpetraCore_CrsMatrix_Bug8447_MPI_2|TpetraCore_ImportExport2_UnitTests_Send_MPI_4|TpetraCore_ImportExport2_UnitTests_ISend_MPI_4|TpetraCore_ImportExport2_UnitTests_Alltoall_MPI_4|TpetraCore_AsyncTransfer_UnitTests_MPI_4|TpetraCore_MatrixMatrix_UnitTests_MPI_4|TpetraCore_FECrs_MatrixMatrix_UnitTests_MPI_4|TpetraCore_RowMatrixTransposer_test_MPI_4|TpetraCore_RowMatrixTransposer_UnitTests_MPI_4|TpetraCore_CrsMatrix_transpose_sortedRows_MPI_4|TpetraCore_AdditiveSchwarzHalo_MPI_4|Amesos2_KLU2_UnitTests_MPI_2|Amesos2_KLU2_Solver_Test_MPI_2|Amesos2_SolverFactory_UnitTests_MPI_4|Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4|Zoltan2_XpetraTraits_MPI_4|Zoltan2_XpetraCrsMatrixInput_MPI_4|Zoltan2_GraphModel_MPI_4|Zoltan2_Partitioning1_ParMETIS_MPI_4|Zoltan2_Partitioning1_ParMETIS_OneProc_MPI_4|Zoltan2_Partitioning1_ParMETIS_VWeights_MPI_4|Zoltan2_Partitioning1_ParMETIS_OneProc_VWeights_MPI_4|Zoltan2_Partitioning1_ParMETIS_EWeights_MPI_4|Zoltan2_Partitioning1_ParMETIS_OneProc_EWeights_MPI_4|Zoltan2_Partitioning1_Quotient_MPI_4|Zoltan2_Partitioning1_Quotient_OneProc_MPI_4|Zoltan2_Partitioning1_Quotient_Threshold1_MPI_4|Zoltan2_Partitioning1_Quotient_Threshold2_MPI_4|Zoltan2_Partitioning1_Quotient_OneProc_Threshold1_MPI_4|Zoltan2_Partitioning1_Quotient_OneProc_Threshold2_MPI_4|Zoltan2_TpetraCrsColorer_simple_MPI_4|Zoltan2_TpetraCrsColorer_simple_nodistrib_MPI_4|Zoltan2_TpetraCrsColorer_west0067_MPI_4|Zoltan2_TpetraCrsColorer_west0067_nodistrib_MPI_4|Zoltan2_TpetraCrsColorer_galeri1_MPI_4|Zoltan2_TpetraCrsColorer_galeri2_MPI_4|Zoltan2_TpetraCrsColorer_troublecauser_MPI_4|Zoltan2_Coloring1_simple_D1_rows_MPI_4|Zoltan2_Coloring1_simple_D1_nonzeros_MPI_4|Zoltan2_Coloring1_commanchedual_D1_rows_MPI_4|Zoltan2_Coloring1_commanchedual_D1_nonzeros_MPI_4|Zoltan2_Coloring1_simple_D1-2GL_rows_MPI_4|Zoltan2_Coloring1_simple_D1-2GL_nonzeros_MPI_4|Zoltan2_Coloring1_commanchedual_D1-2GL_rows_MPI_4|Zoltan2_Coloring1_commanchedual_D1-2GL_nonzeros_MPI_4|Zoltan2_Coloring1_simple_D2_MPI_4|Zoltan2_Coloring1_simple_D2_recolor_degrees_MPI_4|Zoltan2_Coloring1_simple_D2_serial_threshold_25_MPI_4|Zoltan2_Coloring1_simple_D2_rows_MPI_4|Zoltan2_Coloring1_simple_D2_nonzeros_MPI_4|Zoltan2_Coloring1_commanchedual_D2_MPI_4|Zoltan2_Coloring1_commanchedual_D2_rows_MPI_4|Zoltan2_Coloring1_commanchedual_D2_nonzeros_MPI_4|Zoltan2_Coloring1_complete_D2_MPI_4|Zoltan2_Coloring1_simple_PD2_MPI_4|Zoltan2_Coloring1_simple_PD2_recolor_degrees_MPI_4|Zoltan2_Coloring1_simple_PD2_serial_threshold_25_MPI_4|Zoltan2_Coloring1_simple_PD2_rows_MPI_4|Zoltan2_Coloring1_simple_PD2_nonzeros_MPI_4|Zoltan2_Coloring1_commanchedual_PD2_MPI_4|Zoltan2_Coloring1_commanchedual_PD2_rows_MPI_4|Zoltan2_Coloring1_commanchedual_PD2_nonzeros_MPI_4|Zoltan2_Coloring1_complete_PD2_MPI_4"
```

**Comment by jhux2** [comment]
Thank you!

**Pull request merged**
