### PR TITLE
TrilinosCouplings: adding a new example to use structured algorithm in MueLu

### PR DESCRIPTION
**Pull request by lucbv**
The new example is almost identical to the unstructured example except for
small extra data that needs to be collected and passed to MueLu in order
to the structured algorithms.

@trilinos/muelu 

## Description
These changes add a new example in TrilinosCouplings that will be used to test new structured algorithm developed in MueLu

## Motivation and Context
There is no easy way to test this type of algorithm anywhere else since most tests/examples do not provide structured meshes information

## How Has This Been Tested?
The example has been run in serial and parallel

## Checklist
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

**Comment by lucbv** [comment]
@bartlettroscoe I looked at the report on testing-vm and it seems that the configure and build did not proceed for some reason. Is there some maintenance performed on the machine?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I looked at the report on testing-vm and it seems that the configure and build did not proceed for some reason. Is there some maintenance performed on the machine?

@lucbv,

Hum, I don't see a PR build for this PR at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildstarttime&compare2=84&value2=now

@trilinos/framework work team, do you know what happened here?

**Comment by bartlettroscoe** [comment]
@lucbv,

Just for your FYI, but I don't have any more visibility or really even any more knowledge about the auto PR system than any average Trilinos developer.  Therefore, these types of questions really need to be directed to the @trilinos/framework team.  But you can CC me and I can try to answer the question if I know the answer.

**Comment by prwolfe** [comment]
@lucbv - This is both correctly failing and incorrectly not reporting.  The build did run and fail, but the dashboard reporting seems to have gone south. Not just for this PR, but for all of the failing ones (which are of course the ones we want to see the most.) The actual build error I found after sorting through a large number of warnings was

'[100%] Building CXX object packages/trilinoscouplings/examples/scaling/CMakeFiles/TrilinosCouplings_IntrepidPoisson_Pamgen_Tpetra.dir/IntrepidPoisson_Pamgen_Tpetra_main.cpp.o
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp: In function ‘int main(int, char**)’:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp:269:84: error: no matching function for call to ‘makeMatrixAndRightHandSide(Teuchos::RCP<Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::Array<Teuchos::Array<double> >&, Teuchos::Array<int>&, Teuchos::RCP<const Teuchos::Comm<int> >&, Teuchos::RCP<Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >&, std::string&, Teuchos::RCP<Teuchos::basic_FancyOStream<char> >&, Teuchos::RCP<Teuchos::basic_FancyOStream<char> >&, bool&, bool&)’
                                     comm, node, meshInput, out, err, verbose, debug);
                                                                                    ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp:269:84: note: candidates are:
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp:67:0:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.hpp:159:1: note: void TrilinosCouplings::TpetraIntrepidPoissonExample::makeMatrixAndRightHandSide(Teuchos::RCP<Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, const Teuchos::RCP<const Teuchos::Comm<int> >&, const Teuchos::RCP<Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >&, const string&, const Teuchos::RCP<Teuchos::basic_FancyOStream<char> >&, const Teuchos::RCP<Teuchos::basic_FancyOStream<char> >&, bool, bool)
 makeMatrixAndRightHandSide (Teuchos::RCP<sparse_matrix_type>& A,
 ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.hpp:159:1: note:   candidate expects 11 arguments, 13 provided
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.hpp:173:1: note: void TrilinosCouplings::TpetraIntrepidPoissonExample::makeMatrixAndRightHandSide(Teuchos::RCP<Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, Teuchos::RCP<Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >&, const Teuchos::RCP<const Teuchos::Comm<int> >&, const Teuchos::RCP<Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >&, const string&, const Teuchos::RCP<Teuchos::basic_FancyOStream<char> >&, const Teuchos::RCP<Teuchos::basic_FancyOStream<char> >&, bool, bool)
 makeMatrixAndRightHandSide (Teuchos::RCP<sparse_matrix_type>& A,
 ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.hpp:173:1: note:   candidate expects 11 arguments, 13 provided
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp:315:62: warning: ‘Teuchos::RCP<MueLu::TpetraOperator<Scalar, LocalOrdinal, GlobalOrdinal, Node> > MueLu::CreateTpetraPreconditioner(const Teuchos::RCP<Tpetra::CrsMatrix<S, LO, GO, N> >&, const Teuchos::RCP<Tpetra::MultiVector<double, LocalOrdinal, GlobalOrdinal, Node> >&, const Teuchos::RCP<Tpetra::MultiVector<DS, DL, DG, DN> >&) [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]’ is deprecated (declared at /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/muelu/adapters/tpetra/MueLu_CreateTpetraPreconditioner.hpp:221) [-Wdeprecated-declarations]
        M = MueLu::CreateTpetraPreconditioner<ST,LO,GO,Node>(A);
                                                              ^
In file included from /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi.h:253:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/teuchos/core/src/Teuchos_Time.hpp:56,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/teuchos/comm/src/Teuchos_TimeMonitor.hpp:70,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Tpetra_main.cpp:62:
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi_portable_platform.h:374:34: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                  ^
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi_portable_platform.h:374:63: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)'

I will look into the reporting question.

**Comment by jwillenbring** [comment]
@trilinos/framework 

@prwolfe I am not seeing anything reported to the dashboard now, failing or passing. The builds that are supposed to report the dashboard are reporting the correct status back to GitHub now, but they don't seem to be reporting to CDash at all.

**Comment by lucbv** [comment]
@jwillenbring  and @prwolfe thanks for commenting on this, I found my errors and I think the next build should be fine. But indeed it would be nice to see them on testing-vm so I can diagnose without recompiling.
Hopefully a fix will be found soon!

**Comment by bmpersc** [comment]
@jwillenbring, @lucbv, it seems that there is something wrong with the submissions, but I can't say what since the raw files have been deleted. The jobs are submitting, but only their names and for some reason they are ending up in the experimental track instead of the Pull Request track.

From what I've seen the report from the autotester is still accurate as to the pass/fail state of the tests so I don't think this will hold up PRs being merged. However, it will make it harder to know what, if anything, is broken.

We will have to dig into this to see why the submissions are now going to the wrong place and are incomplete.

**Comment by csiefer2** [comment]
Did you mean to re-enable some of the output in MueLu?

**Pull request merged**
