### PR TITLE
Intrepid2: Removing Experimental namespace used for projections (part2)

### PR DESCRIPTION
**Pull request by mperego**
@trilinos/intrepid2 

## Motivation

In this PR we continue the work started in PR #12141 and remove legacy projection functions in the `Experimental` namespace.

We also further improve the performance of Projections by fully working at the level of the reference element and map the basis coefficient back to the oriented frame at the end of the projection computation.

### CODE REVIEW

**Review by CamelliaDPG — DISMISSED** [review]
@mperego, this looks good to me.  Just one question: what is the criterion for merging?  (Are we waiting for Empire's OK?)

**Comment by mperego** [comment]
> @mperego, this looks good to me. Just one question: what is the criterion for merging? (Are we waiting for Empire's OK?)

Thanks! Yes, that's correct. Waiting for Empire to comply with the removal of the experimental namespace and the legacy projection functions.

**Comment by CamelliaDPG** [comment]
> > @mperego, this looks good to me. Just one question: what is the criterion for merging? (Are we waiting for Empire's OK?)
> 
> Thanks! Yes, that's correct. Waiting for Empire to comply with the removal of the experimental namespace and the legacy projection functions.

Sounds good.  Thanks!

**Comment by sebrowne** [comment]
This branch MUST be rebased prior to merge given the 'develop' change (re-adds forbidden files).

**Comment by mperego** [comment]
> This branch MUST be rebased prior to merge given the 'develop' change (re-adds forbidden files).

@sebrowne Github `Squash and merge` should do the right thing, right?

**Comment by sebrowne** [comment]
> > This branch MUST be rebased prior to merge given the 'develop' change (re-adds forbidden files).
> 
> @sebrowne Github `Squash and merge` should do the right thing, right?

I would not expect so based on the description.  You need to forcibly rewrite the branch so that it no longer contains the old (bad) history because it was created prior to the 'develop' rewrite.

I will note, I'm not an expert with the GitHub UI.  I pretty much exclusively perform git operations from the console.

**Review by sebrowne — CHANGES_REQUESTED** [review]
Please rebase to eliminate extraneous commits.

**Comment by mperego** [comment]
@rppawlo let me know when we can merge this PR. At that point I'll rebase the PR.

**Review by sebrowne — APPROVED** [review]
Looks good from a rebase/no git LFS perspective.  Thanks!

**Review by CamelliaDPG — APPROVED** [review]

**Review by rppawlo — APPROVED** [review]
Thanks @mperego !

**Review by rppawlo — APPROVED** [review]

**Comment by mperego** [comment]
@CamelliaDPG @rppawlo can you please approve one more time?

**Review by rppawlo — APPROVED** [review]

**Comment by mperego** [comment]
@rppawlo Not sure what's going on. It's the second time that you approve and your approval gets dismissed.

**Comment by rppawlo** [comment]
Maybe I am not in the intrepid2 group? @sebrowne - can you help us figure out why my approvals keep getting dismissed for this PR?

**Comment by sebrowne** [comment]
@mperego are you rebasing the branch after Roger approves it?

**Comment by mperego** [comment]
> @mperego are you rebasing the branch after Roger approves it?

no. I'm not doing anything. I found this thread
https://github.com/orgs/community/discussions/58535

They suggest to change the base branch (e.g., to master) and then change it back to what it was (develop). I'll try doing that.

**Comment by sebrowne** [comment]
Are you doing _anything_ after Roger approves it?  If not, I'm stumped :(

**Review by sebrowne — DISMISSED** [review]

**Comment by sebrowne** [comment]
Oh I see, it did it to me too.  Maybe what it's saying is that you NEED to rebase it?  I'm not sure that makes a ton of sense either.  I'll ponder this.

**Comment by sebrowne** [comment]
Try closing it and re-opening maybe?

**Review by sebrowne — APPROVED** [review]

**Comment by sebrowne** [comment]
Seems to be working now?

**Comment by mperego** [comment]
Oh, cool. That seemed to have fixed the issue without triggering the PR testing.

**Comment by mperego** [comment]
Thanks!

**Pull request merged**
