### PR TITLE
MueLu: Update/fix MueMex build (matlab interface)

### PR DESCRIPTION
**Pull request by brian-kelley**
- When adding the matlab subdirectory, check ``Tpetra_INST_INT_INT`` first to
  make error messages clearer. If that is off, then Xpetra's Epetra support
  is automatically disabled but MueLu doesn't tell you that
- Add -fPIC flag to compilation of muemex.mexa64
- Guard uses of complex-valued Tpetra/Xpetra objects by
 ``HAVE_TPETRA_INST_COMPLEX_DOUBLE`` (build succeeds with complex disabled now)
- Update the calls to CreateEpetra/TpetraPreconditioner, which no longer have
 overloads taking coordinates. Instead, setting coordinates in the parameter list.
- Change old ``DynRankView::dimension(i)`` syntax with ``::extent(i)``. This fixed build with Intrepid2 enabled.

@trilinos/muelu 

## Motivation

Build of muemex was broken (reported by @dridzal)

## Testing

Tested by successfully building MueMex on cee-compute19 using this configuration:
```
cmake \
-DTrilinos_ENABLE_Ifpack2=ON \
-DTrilinos_ENABLE_Tpetra=ON \
-DTrilinos_ENABLE_Epetra=ON \
-DTpetra_INST_INT_INT=ON \
-DTrilinos_ENABLE_MueLu=ON \
-DTPL_ENABLE_MATLAB=ON \
-DMATLAB_ARCH=glnxa64 \
-DMATLAB_ROOT=/usr/local/matlab/R2019b \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DTrilinos_ENABLE_CXX11:BOOL=ON \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
-DTrilinos_ENABLE_PyTrilinos=OFF \
-DTPL_ENABLE_HWLOC:BOOL=OFF \
-DTPL_ENABLE_Matio=OFF \
-DTPL_ENABLE_BLAS:BOOL=ON \
-DTPL_ENABLE_LAPACK:BOOL=ON \
-DTPL_ENABLE_MPI:BOOL=OFF \
../Trilinos
```

### CODE REVIEW

**Comment by brian-kelley** [comment]
@rstumin I added ``-fPIC`` to the flags for mlmex too, since that was also getting link errors about sections of mlmex.cpp.o not being relocatable.

**Comment by jhux2** [comment]
@csiefer2 Was this being tested on the now-defunct lightsaber?

**Comment by brian-kelley** [comment]
@dridzal Did it end up working for you, after you enabled shared libraries and complex?

**Comment by dridzal** [comment]
@brian-kelley , unfortunately I'm still getting an error, see below.  I pulled your most recent changes.  Maybe it's a Mac issue.  I could try compiling on my Linux workstation instead.

`Undefined symbols for architecture x86_64:
  "MueLu::Aggregates<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Aggregates(Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&)", referenced from:
      Teuchos::RCP<MueLu::Aggregates<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > MueLu::loadDataFromMatlab<Teuchos::RCP<MueLu::Aggregates<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > >(mxArray_tag const*) in MueLu_MatlabUtils.cpp.o
  "MueLu::Exceptions::RuntimeError::RuntimeError(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      MueLu::TwoLevelFactoryBase::CallBuild(MueLu::Level&) const in MueLu_TwoLevelMatlabFactory.cpp.o
      MueLu::MatlabSmoother<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Apply(Xpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Xpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool) const in MueLu_MatlabSmoother.cpp.o
      MueLu::MatlabSmoother<std::__1::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Apply(Xpetra::MultiVector<std::__1::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Xpetra::MultiVector<std::__1::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, bool) const in MueLu_MatlabSmoother.cpp.o`

**Comment by dridzal** [comment]
@brian-kelley , I have confirmed that the build works on RHEL6 with SEMS modules, and shared libs turned on.  I have not tried a static build yet (I'll test MueLu in Matlab next, hope it'll work).  So, there must be something funky with the Mac environment.  I think your changes are sufficient to consider this particular issue fixed.

**Pull request merged**
