### PR TITLE
Framework: Disable randomly failing tests

### PR DESCRIPTION
**Pull request by ZUUL42**
@trilinos/teuchos 

## Motivation

There are 2 tests that randomly fail in 8 builds.
This will clean up those builds until the tests can be addressed.

Should close out #8759

### CODE REVIEW

**Comment by e10harvey** [comment]
Thanks, @ZUUL42 ! Please run the following on ats2 and post the cdash link to the results:
```bash
mkdir pr9250; cd pr9250
ln -s /path/to/cmake/std/atdm/ctest-s-local-test-driver.sh .
nohup env ./ctest-s-local-test-driver.sh all &>ctest-s-local-test-driver.out &
```

**Review by bartlettroscoe — COMMENTED** [review]
That is a lot of duplication.  Why not just put these in a single file:

```
cmake/std/atdm/ats2/tweaks/Tweaks.cmake
```

?

See:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#disable-a-test-for-several-or-all-builds-on-a-specific-platform

**Comment by ZUUL42** [comment]
@bartlettroscoe it is a lot of duplication, but I didn't realize there was any other way to hit just the 8 builds specifically.
I can look into doing it the other way.

**Comment by bartlettroscoe** [comment]
> Please run the following on ats2 and post the cdash link to the results:

@ZUUL42, actually, if you modify/add just the one file `cmake/std/atdm/ats2/tweaks/Tweaks.cmake` and put in the two disable lines, you only need one configure and just Teuchos so following:

*  https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ats-2

you would just run on 'vortex':

```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh <any-build-name>
$ cmake -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Teuchos=ON \
  $TRILINOS_DIR \
  &> configure.out
$ grep "NOT added" configure.out
```

That should show those two tests being disabled.  See:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#disabling-failing-tests

That will run very fast compared to running all of the full builds on that platform.

**Review by e10harvey — CHANGES_REQUESTED** [review]
Please run the following on ats2 and post the cdash link to the results:
```bash
mkdir pr9250; cd pr9250
ln -s /path/to/cmake/std/atdm/ctest-s-local-test-driver.sh .
nohup env ./ctest-s-local-test-driver.sh all &>ctest-s-local-test-driver.out &
```

**Pull request closed without merging**
