### PR TITLE
Amesos2: add new options for SuperLU

### PR DESCRIPTION
**Pull request by iyamazaki**
## Motivation

This PR is to add a few new options for SpTRSV with SuperLU, and also an option to call METIS before SuperLU

### CODE REVIEW

**Comment by cgcgcg** [comment]
@trilinos/framework This PR had master set as base and was running the dev->master autotester. I don't think that's intended.

**Comment by iyamazaki** [comment]
Thank you, @cgcgcg..

**Comment by william76** [comment]
> @trilinos/framework This PR had master set as base and was running the dev->master autotester. I don't think that's intended.

Correct. Merging to `master` is restricted.

**Review by ndellingwood — APPROVED** [review]
thanks @iyamazaki !

**Pull request merged**
