### PR TITLE
Fixes for teko utilities

### PR DESCRIPTION
**Pull request by egphill**
@trilinos/<teamName>

## Description

Found a couple little bugs in the Teko utilities. First, a typo in the Tpetra version of explicit triple matrix product read in one of the input matrices wrong. Second, the blocked op version of explicit add was not writing to the supplied destination operator, but creating an RCP to a brand new linear op.

## Motivation and Context

Discovered these bugs in using Teko tools in EMPIRE.

## How Has This Been Tested?

All existing Teko tests pass. These capabilities give the expected result in EMPIRE now.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by cgcgcg** [comment]
@egphill Could you change the branch from master to develop?

**Comment by eric-c-cyr** [comment]
I'm okay with the  Teko changes. Not sure why all the other stuff is included, but it didn't seem to bad to me.

**Comment by eric-c-cyr** [comment]
Also, you have "master" as the merge branch.

**Comment by mhoemmen** [comment]
I changed the base branch to develop.

**Pull request merged**
