### PR TITLE
cmake/std/atdm: Disable Kokkos timing based test

### PR DESCRIPTION
**Pull request by e10harvey**
Addresses #8545

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@e10harvey, it is considered good practice to put the GitHub Issue IDs in the top of the PR description to tie them together.  Otherwise, it may look like these things come out of the blue.  (I did that above.)

**Comment by bartlettroscoe** [comment]
@e10harvey, did you want to set the label `AT: AUTOMERGE` instead of `AT: RETEST`?

**Review by bartlettroscoe — APPROVED** [review]
Thanks should take care of #8545.

**Comment by e10harvey** [comment]
> @e10harvey, did you want to set the label `AT: AUTOMERGE` instead of `AT: RETEST`?

No. I selected master instead of develop -- so I fixed that and thrn applied `AT: RETEST`.

**Pull request merged**
