### PR TITLE
Tpetra develop

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
This removes Tpetra::Details::gemm and gemv functions and they are replaced by Kokkos::Blas::gemm and gemv. So far, gemm is only used in Tpetra and Stokhos. 

This PR also requires updates from Kokkos and KokkosKernels (when do we integrate them again ?)
I also submitted another PR (kokkos/kokkos-kernels#277) which is required KokkosKernels. This PR should not be tested by the auto tester until kokkos family is snapshotted or the changes are directly pushed into trilinos repo. 

## Description

@mhoemmen I did not delete test/blas but disable them. We probably need to delete them.  
@etphipp I also modified stokhos code that uses tpetra details gemm. I did not test the code yet. I will update this page after finishing testing stokhos.

## Motivation and Context

Tpetra Diet

<!---
If applicable, let us know how this merge request is related to any other open
issues or pull requests:

## How Has This Been Tested?

Tested on blake (SKX)

### CODE REVIEW

**Comment by mhoemmen** [comment]
@kyungjoo-kim Instead of deleting the test, could you please just change it to call the kokkos-kernels routines?  Thanks!

**Comment by kyungjoo-kim** [comment]
@mhoemmen Aren't kokkoskernels unit tests sufficient for testing them ?

**Comment by mhoemmen** [comment]
@kyungjoo-kim wrote:
> Aren't kokkoskernels unit tests sufficient for testing them ?

This test exercises `Teuchos::BLAS` too :)  We can't get rid of `Teuchos::BLAS`, at least not yet, because some users cannot build Kokkos, and need to build MueLu with Epetra only.

**Comment by kyungjoo-kim** [comment]
Okay. I will restore the tests.

**Comment by kyungjoo-kim** [comment]
@mhoemmen tests are restored and passed. For TPL interface, it would be better to wait kokkos snapshot, which might be delayed a bit later the next week. Currently I can include patches for cmake environment without TPL blas interface (native kokkos implementation exist in the Trilinos/package/kokkos-kernels) to finish this PR. How do you think ? we have time to wait until kokkos integration  ?

**Comment by kyungjoo-kim** [comment]
I figured out. It has a typo (Kokkos::Blas -> KokkosBlas) but I do not understand why it is compiled on my workstation.

**Comment by kyungjoo-kim** [comment]
@etphipp I pushed the fix and remove wip label to take PR test.

**Comment by kyungjoo-kim** [comment]
@etphipp could you approve this pr ?

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe I am not sure if I keep trying this PR test as it keep failing from fetching the repo. GCC 4.9.3 and Intel 17.0.1 pass the test. However, the gcc 4.8.4 test keep failing ``ERROR: Error fetching remote repo 'origin'``.  Should I wait until the network or github issues are resolved ?

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim said:

> @bartlettroscoe I am not sure if I keep trying this PR test as it keep failing from fetching the repo. GCC 4.9.3 and Intel 17.0.1 pass the test. However, the gcc 4.8.4 test keep failing ERROR: Error fetching remote repo 'origin'. Should I wait until the network or github issues are resolved ?

@trilinos/framework, can you answer @kyungjoo-kim's question?

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe @trilinos/framework This PR never be merged with the fetching failure on gcc 4.8.4 testing. I am not going to put the retest label anymore until this network is resolved.   

FYI: @kddevin

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe I did not get a reponse from @trilinos/framework. As this PR keeps failing because of unstable network on the gcc 4.8.4 testing, can we just merge this with your superpower ? I don't think it is worth for put retest again without knowing the main problem on gcc 4.8.4 testing.

**Comment by mhoemmen** [comment]
@william76 (see above comment; thanks!)

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim, I am not a member of the framework team and don't have any super powers with the github repo.

**Comment by prwolfe** [comment]
I am helping the framework team although I don't have any special privileges. I can get the autotester retest cycle to run faster until I get a good set.  I will start that for you.

**Comment by prwolfe** [comment]
All three jobs got through the checkout stage, I will monitor to see if they timeout.

**Comment by kyungjoo-kim** [comment]
@prwolfe Finally it is done. Thanks a lot. What is your magic to make this work ?

**Comment by prwolfe** [comment]
@kyungjoo-kim Luck - I would have killed the jobs and restarted in minutes instead of hours if they failed, but it ran fine. We still aren't sure whats up with this one, but Will moved us to mirrors the internal gitlab until this gets resolved.

**Pull request merged**
