### PR TITLE
New sub-package ShyLU/FROSch

### PR DESCRIPTION
**Pull request by searhein**
Adding the new sub-package ShyLU/FROSch, which includes a parallel implementation of the GDSW preconditioner. GDSW is a two-level Schwarz preconditioner with special coarse space.

In order to resolve circular dependencies, the ShyLU package was partitioned into ShyLU_DD (Domain Decomposition) and ShyLU_SDS (SubDomain Solvers).

### CODE REVIEW

**Comment by aprokop** [comment]
@trilinos/shylu 

You know your PR is too large when Github is like `The table of contents is too big for display.` :)

**Comment by searhein** [comment]
Yeah, it includes quite some new code, and we partitioned the ShyLU package. 
I wouldn't want to review it ;)

**Comment by srajama1** [comment]
Technically, I have reviewed the major changes to Trilinos, the dependencies, ShyLU refactor etc as we sat together. It is hard to review every line of the preconditioner. I think of this PR as a way for the Tpetra team to test the do Import() hang. I am not worried about someone reviewing this.

**Comment by mhoemmen** [comment]
@searhein It would be helpful if you could summarize for me what files relate to Tpetra.  Thanks!

**Comment by searhein** [comment]
@srajama1 I just changed the name of ShyLU_DD to ShyLU_Node.

**Comment by mhoemmen** [comment]
Hi @searhein !  It looks like there is a bug in overlap computation.  Please refer to my comment here:

https://github.com/trilinos/Trilinos/issues/1752#issuecomment-333424315

The code looks wrong with either Epetra or Tpetra.

**Pull request closed without merging**
