### PR TITLE
WIP: Tpetra: Fix DistObject LID array DualView semantics

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra This is a work in progress; please do NOT merge!

### CODE REVIEW

**Comment by mhoemmen** [comment]
@vbrunini Check this out.  I've only fixed MultiVector thus far.  CrsMatrix and BlockCrsMatrix (at least) will need fixing too.  Also I need to test more extensively.

**Comment by mhoemmen** [comment]
I'll want to resolve the conflicts before attacking BlockCrsMatrix, which is the last class that implements the "new" DistObject interface.

**Comment by kddevin** [comment]
@mhoemmen said this PR should be closed in favor of #4328 so I am closing it

**Comment by mhoemmen** [comment]
Thanks @kddevin!

**Pull request closed without merging**
