### PR TITLE
Xpetra,MueLu,ShyLU: Drop kokkos refactor

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/xpetra @trilinos/muelu 

## Motivation
A while back, Xpetra and MueLu changed Kokkos to a required dependency. 
This PR removes `HAVE_XPETRA_KOKKOS_REFACTOR` and `HAVE_MUELU_KOKKOS_REFACTOR`.

### CODE REVIEW

**Comment by GrahamBenHarper** [comment]
Does this still require us to drop the non-kokkos factories or merge them with their kokkos counterparts?

**Comment by cgcgcg** [comment]
@GrahamBenHarper I wouldn't call it a requirement, but it would be good to do that at some point. Always building the Kokkos factories is one step in that direction.

**Comment by GrahamBenHarper** [comment]
Right. I suppose this means certain factories wouldn't be used anymore once it merges?

**Comment by GrahamBenHarper** [comment]
Thanks! I follow what this does now.

**Comment by jhux2** [comment]
> No, it means that both non-Kokkos and Kokkos factories will always be compiled. Before you had to build with "MueLu_ENABLE_Kokkos_Refactor" to get that. At runtime, you can still select to either category of factories.

@cgcgcg Are you sure about that?  After Kokkos became a required dependency, I thought the Kokkos factories are now always compiled, i.e., `HAVE_MUELU_KOKKOS_REFACTOR` is true.

Whether the Kokkos factories are enabled at runtime is a different matter.  Serial node defaults to the non-Kokkos factories, but the Kokkos factory chain can be enabled by setting `use kokkos refactor` to `true`.

**Review by jhux2 — APPROVED** [review]
@cgcgcg wins the negative-lines-of-code PR of the week!

**Comment by cgcgcg** [comment]
@trilinos/framework @sebrowne I'm not sure why this PR and #11602 aren't merging. Do they need to be retested after being switched from draft mode?

**Comment by sebrowne** [comment]
I think the autotester just hasn't gotten back to them believe it or not.  It's currently testing #11484, so once it's done with that it will continue advancing through the even-numbered PRs until it gets to this one and (hopefully) merges it.

**Comment by cgcgcg** [comment]
Sounds good. Thanks for the quick reply!

**Pull request merged**
