### PR TITLE
Cray cce patches

### PR DESCRIPTION
**Pull request by bavier**
These patches allow Amesos, Amesos2, and STKUtil to build with Cray's compiler.

### CODE REVIEW

**Comment by bavier** [comment]
Has anyone had a chance to look at this PR?

**Comment by mhoemmen** [comment]
@bavier Sorry, I need at least five of me to do all the work there is to do :(

**Comment by bavier** [comment]
@mhoemmen Understood.  Yes, I'll split the STKUtil commits into another pull request.

**Comment by mhoemmen** [comment]
Thanks @bavier ! :-D  btw, what TPLs do we need to test the Amesos and Amesos2 patches fully?

**Comment by bavier** [comment]
@mhoemmen No specific TPLs; I think just KLU and KLU2 being configured is enough.

**Comment by jwillenbring** [comment]
@srajama1 should be aware of this pull request.

**Comment by srajama1** [comment]
Sorry, I didn't get any notification for this. Eric, please include me as or @trilinos/amesos2 in future for us to get to it quickly. Let me take a quick look and merge it.

**Comment by jwillenbring** [comment]
This pull request should be resubmitted if it is still needed after the recent change for the more general case. The cray case should now build, but wouldn't include the flag mentioned in this PR.

**Comment by jwillenbring** [comment]
@bavier I am going to close this PR. Please open a new one if needed. As stated above, the cray case should now build, but it won't include the flag mentioned in this PR.

**Pull request closed without merging**
