### PR TITLE
Import stk development from Sierra

### PR DESCRIPTION
**Pull request by prwolfe**
This imports stk development as of:

commit 0282faea2a69e6e60e8fda3c799ae1eb4752b6e7
Author: Alan Williams <william@sandia.gov>
Date:   Tue Jun 12 16:24:16 2018 -0600

    Minor tweaks to stk_ngp mesh.

    Default constructor for Entities, make StaticMesh constructor explicit.

From the Sierra development stream.

@trilinos/stk 

## Motivation and Context

Developers in APRC have requested a newer version of stk.

## Related Issues

* Is blocked by the need for a newer seacas version so I am setting the WIP label
#2625 #2650 

## How Has This Been Tested?
Sierra has a cmake build that runs every night.  The build and tests were clean as of this commit.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ x ] My code follows the code style of the affected package(s).
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ x ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
```
.../Trilinos/packages/seacas/libraries/ioss/src/Ioss_GroupingEntity.h:494:52: error: call of overloaded ‘get_field_type(long unsigned int)’ is ambiguous
   field.check_type(Ioss::Field::get_field_type(T(0)));
                                                    ^
```

**Comment by prwolfe** [comment]
@mhoemmen 

that's why this is marked as WIP - we need a newer Seacas before this will function.

**Comment by mhoemmen** [comment]
@gsjaardema (not sure if tag right)

**Comment by gsjaardema** [comment]
@prwolfe I have not had a chance to track down the issues in #2650 yet.

**Comment by prwolfe** [comment]
Ok - Thanks for the update!

**Comment by mhoemmen** [comment]
The build errors look legit:
```
.../Trilinos/packages/seacas/libraries/ioss/src/Ioss_GroupingEntity.h:447:52: error: call of overloaded ‘get_field_type(unsigned int)’ is ambiguous
   field.check_type(Ioss::Field::get_field_type(T(0)));
                                                    ^
```

**Comment by prwolfe** [comment]
Alan,

The failing test on Intel is calling from 

stk/stk_math/unit_tests/UnitTestStkvector.cpp line 341 into
stk/stk_math/stk_math/StkVector.hpp line 156 and testing the result at 
stk/stk_math/unit_tests/UnitTestStkvector.cpp line 331.

For whatever reason, the zero length vector gets subscripts 0 and 1 reset to NaN but not 2 (although this may be because the loop is vectorized and all of them are wrong.) Not sure why this didn't fail in Sierra - we do have a definition for it and it seems to be passing.

You can find this on cdash at https://testing-vm.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3813183

**Comment by prwolfe** [comment]
If needed we can turn this off while you sort through it of course.

**Comment by prwolfe** [comment]
Just needs an inspection from @alanw0

**Comment by prwolfe** [comment]
@mhoemmen - @alanw0 seems to be out today.  Can you look at and review this one for us when you get a chance?

Thanks!

**Comment by mhoemmen** [comment]
@prwolfe I'm at a week of all-day meetings, but I'll do my best!

**Comment by prwolfe** [comment]
Sounds right. Bet Alan is as well ;->

**Pull request merged**
