### PR TITLE
MueLu: Fix "pointer being freed was not allocated" error

### PR DESCRIPTION
**Pull request by tjfulle**
PR from topics branch instead of develop since I have another open PR on it (the develop branch).

The build/test cases summary from ceerws1106 (using the standard SEMs checkin script):

Build/Test Cases Summary
Enabled Packages: MueLu
Disabled Packages: PyTrilinos,Claps,TriKota,FEI,Moertel,STK,SEACAS,ThreadPool,OptiPack,Rythmos,Intrepid,ROL,Panzer
Enabled all Forward Packages
0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=138,notpassed=0 (58.20 min)

### CODE REVIEW

**Comment by tjfulle** [comment]
@trilinos/muelu, @tawiesn, @aprokop

**Comment by tawiesn** [comment]
@tjfulle Thanks. Your changes look good to me. No objections from my side.

**Comment by tjfulle** [comment]
@tawiesn, FYI, I don't have write access, so another @trilinos/muelu Devi will have to merge the PR :)

**Comment by jhux2** [comment]
You don't have write access to the Trilinos repo?!  @bmpersc or @jwillenbring can fix that.  That may also be why you can't edit the Trilinos wiki (issue #1344).

**Pull request merged**
