### PR TITLE
Fixed deprecated code

### LINKED ISSUE #9381: Tpetra: call to deprecated code not protected and should be replaced
## Bug Report
@trilinos/tpetra 

### Description

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp:6748

has a call to getLocalGraph and should be getLocalGraphHost most likely.  Fixing and sending to @cgcgcg

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

### PR DESCRIPTION
**Pull request by bathmatt**
@trilinos/tpetra

## Motivation

* Closes #9381

### CODE REVIEW

**Comment by bathmatt** [comment]
@cgcgcg please merge and close this.

**Comment by cgcgcg** [comment]
@bathmatt Is it obvious that the graph needs to be used on host?

**Comment by bathmatt** [comment]
> @bathmatt Is it obvious that the graph needs to be used on host?

No, but assume the non-uvm auto-tester would figure it out. Let me look at something

**Comment by bathmatt** [comment]
> @bathmatt Is it obvious that the graph needs to be used on host?

you're correct, getLocalGraph returns a device graph, making it the same., pushed commit

**Comment by bathmatt** [comment]
@cgcgcg i think you can approve this and close it out

**Review by cgcgcg — APPROVED** [review]

**Pull request merged**
