### PR TITLE
Ctest: Enabling non-UVM Ifpack2 tests

### PR DESCRIPTION
**Pull request by csiefer2**
Tests: Turn 'em on!

### CODE REVIEW

**Review by GrahamBenHarper — APPROVED** [review]

**Review by lucbv — DISMISSED** [review]
This is a good idea, thanks @csiefer2 
Somewhat related question: should we set this build to post its results in the PR section of CDash with the other PR builds? I always find it unhelpful to have to scroll around to find this one.

**Comment by csiefer2** [comment]
Wait.  It doesn't show in the PR section?  Uh @trilinos/framework is there a reason for that?

**Comment by lucbv** [comment]
It's in experimental which I also understand but now that we have good progress I think we could move it from `Experimental` to `Pull Request` track. The change is most likely a one liner so should be easy : )

**Comment by csiefer2** [comment]
Why don't open a PR that does that and send it to @jwillenbring to review?

**Review by cgcgcg — APPROVED** [review]

**Comment by csiefer2** [comment]
@william76 's terrible diagram FTW!

**Comment by jwillenbring** [comment]
> It's in experimental which I also understand but now that we have good progress I think we could move it from `Experimental` to `Pull Request` track. The change is most likely a one liner so should be easy : )

@ZUUL42 Could you please move this build to the PR track instead of experimental?

**Comment by csiefer2** [comment]
Random GCC compiler failures.  Lovely,

@william76 's terrible diagram!!!!!!

**Comment by kddevin** [comment]
The compiler error is not so random; I've been getting nightly emails with tests having the same failure.  @trilinos/framework

**Comment by jhux2** [comment]
> The compiler error is not so random; I've been getting nightly emails with tests having the same failure.

If this is an out-of-memory error, reducing the parallelism would help.  It currently looks like it's "-j 20".  Could Tpetra changes be affecting the memory required by ETI?

**Comment by ZUUL42** [comment]
@jwillenbring I made the change in the UVM OFF Jenkins job to move PULLREQUEST_CDASH_TRACK from "Experimental" to "Pull Request".

**Comment by csiefer2** [comment]
@william76 's terrible diagram #3

**Comment by csiefer2** [comment]
Autotester how I wait for thee,
For my code to merge.
Please end thy broken slumber,
and from thy nap emerge!

**Comment by ccober6** [comment]
Nice!

**Pull request closed without merging**
