### PR TITLE
Move certain Kokkos symbols out of Experimental

### PR DESCRIPTION
**Pull request by ibaned**
Satisfies most of #1426

These symbols have matured and are no longer just Experimental (they are in both right now). They may be removed from Experimental in the near future. Therefore, the way forward is to use them outside the Experimental namespace.

@trilinos/muelu @trilinos/sacado @trilinos/shylu @trilinos/stokhos 

Also, does anyone know who should be mentioned w.r.t. TrilinosCouplings?

### CODE REVIEW

**Comment by etphipp** [comment]
The Sacado and Stokhos changes look fine to me.

**Comment by mhoemmen** [comment]
@ibaned Nobody owns TrilinosCouplings.  You'll have to look at the specific example or code there to see what packages it touches.

**Comment by ibaned** [comment]
The modified TrilinosCouplings file is `packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp`, and I actually think the most relevant team regarding the change is @trilinos/intrepid2, so I'll drag them in as well.

**Comment by mperego** [comment]
@ibaned Your changes look fine to me.

**Comment by ibaned** [comment]
I guess we are just missing @trilinos/muelu and @trilinos/shylu comments.

**Comment by ibaned** [comment]
This now also affects @trilinos/Tpetra.

@etphipp , there were more Sacado changes introduced as the `ViewMapping` templated class is moved to `Kokkos::Impl`.

Since these changes will only compile with the Kokkos `develop` branch, they will be merged in conjunction with the next Kokkos snapshot.

**Comment by jhux2** [comment]
> I guess we are just missing @trilinos/muelu and @trilinos/shylu comments.

@ibaned Your changes to MueLu are fine.  Thanks.

**Comment by ibaned** [comment]
This was completed a while ago as part of a Kokkos promotion snapshot.

**Pull request closed without merging**
