### PR TITLE
Tpetra/MueLu: Fixing shared space support

### PR DESCRIPTION
**Pull request by csiefer2**
Issue: #12621
Stakeholder feedback: In progress
Tests: n/a

### CODE REVIEW

**Review by jhux2 — COMMENTED** [review]
Are these for console output and profiling, or something else?

**Review by brian-kelley — COMMENTED** [review]
If the wrapper node's name only involves the exec space, why not just have one version of name in the header?

```
template<typename Node>
static std::string name ()
{
  return std::string(ExecutionSpace().name()) + "/Wrapper";
}
```

**Comment by brian-kelley** [comment]
After I said that, I realized it's for ETI... but this is such a tiny function and it only saves build time in translation units where name() actually gets called, which isn't that many places

**Review by jhux2 — DISMISSED** [review]
lgtm

**Review by cgcgcg — APPROVED** [review]

**Review by cgcgcg — CHANGES_REQUESTED** [review]
This needs clang-format fixing. My guess is that it's not yet blocking cause the action hasn't propagated yet to master.

**Review by cgcgcg — APPROVED** [review]

**Review by GrahamBenHarper — APPROVED** [review]
Thanks for cleaning up some of the templating from #11726. AT looked like it had a random Belos failure, so I slapped a retest on there.

**Pull request merged**
