### PR TITLE
Shylu/Tacho - fix a problem due to disabled serial space

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
serial space can be disabled and it causes a compile error. this pr fixes the problem.

### CODE REVIEW

**Comment by mhoemmen** [comment]
Merged on urgent request by @micahahoward

**Comment by mhoemmen** [comment]
This is weird: the Dashboard build for this PR claims that while the ShyLU package was enabled, no tests were run:

https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3397288

@bartlettroscoe that looks a bit weird....

**Comment by bartlettroscoe** [comment]
> This is weird: the Dashboard build for this PR claims that while the ShyLU package was enabled, no tests were run:

@mhoemmen, the `ShyLU` package is not a real package.  It is just a dummy package to trigger the enable of the `ShyLU_Node` and `ShyLU_DD` packages that have subpackages of their own.   I think this was done to address circular dependencies.  To avoid confusion, the `ShyLU` packge should just likely be removed since it gives the false impression that it is a parent package but it does not have the behaviors of a parent package in TriBITS (for example, `Trilinos_ENABLE_ShyLU=OFF` will not disable anything like is the case for a real parent package a described [here](https://tribits.org/doc/TribitsDevelopersGuide.html#enable-disable-of-parent-package-is-enable-disable-for-subpackages)).

CC: @trilinos/shylu

**Comment by mhoemmen** [comment]
@bartlettroscoe Huh that's weird.  Thanks for clarifying!  Shouldn't the `ShyLU_Node` package have been enabled, though, since these changes were to a file in that package?

**Comment by bartlettroscoe** [comment]
> Huh that's weird. Thanks for clarifying! Shouldn't the ShyLU_Node package have been enabled, though, since these changes were to a file in that package?

@mhoemmen, I don't know the answer to that.  I think what gets enabled is determined by a custom hand-written bash script produced by the @trilinos/framework team.

**Comment by srajama1** [comment]
@bartlettroscoe : We cannot add or remove packages based on what TriBITS or frameworks can support. That logic is backwards. Frameworks need to support the use cases what the packages need.

ShyLU is a logical collection of domain decomposition solvers and node level preconditioners and triangular solves used by them. This is what a packages should and that is why it is that way.

The trouble is on the top level different packages have other dependences and then have ShyLU  dependency as well. If you have other suggestions, other than removing the package, we are all ears :)

**Comment by bartlettroscoe** [comment]
@srajama1, given the desire the allow users to set `-DTrilinos_ENABLE_ShyLU=ON`, this solution is reasonable given the current TriBITS implementation.  It is just that it is not a regular package and therefore it will confuse some people (like it confused @mhoemmen above).

What is really needed is the concept of a TriBITS "meta-package" which would allow defining names for these collections of TriBITS packages to allow enabling and disabling the aggregation of packages, similar to the relationship between packages and subpackages.

But given that ShyLU is the only example of such a meta-package so far, it is likely not worth the work and added complexity to add that feature.  People will learn what this ShyLU package actually is for in time.  Not a big deal.  Sorry for the suggestion that the `ShyLU` package be removed to remove confusion.

**Comment by jwillenbring** [comment]
I think what might be happening here is that the list of packages we are sending up to CDash includes ShyLU, but not any other ShuLU_*. I see on the dashboard there are no tests for ShyLU in general, or for ShyLU_DD, but there are for ShyLU_Node. Is this expected?

**Comment by srajama1** [comment]
@jwillenbring : No there should be tests for basker and tacho at the least.

**Comment by jwillenbring** [comment]
CC: @trilinos/framework @bmpersc 

@srajama1 I see tests for [Tacho](https://testing-vm.sandia.gov/cdash/viewTest.php?onlypassed&buildid=3400346) generally on the dashboard. Both Tacho and Basker are listed as subpages of ShyLU_Node. Basker is categorized as experimental, so those tests wouldn't be running.

So it seems that what I should do is add ShyLU_Node and ShyLU_DD to the list of packages that gets sent up to the dashboard. This will get cleaned up in a later phase of development of the testing driver, but I think that is the issue currently. Any concerns about trying this approach?

**Comment by srajama1** [comment]
@jwillenbring : I think this would work for now. It would be nice to support treating the meta-package, so the ShyLU_Node and ShyLU_DD tests appear under ShyLU. 

In the long run, I would like one meta package say TrilinosSolvers with one interface for all the solvers (Stratimikos like, but simpler). This would give one entry point for all the solvers instead of the current buffet like approach. I believe @maherou will agree.

**Comment by srajama1** [comment]
@bartlettroscoe Thank you, that makes sense now. 

I would like both the functionality for a potential TrilinosSolvers package :). It will hide all the complexity underneath and it would be a meta-package, enabling  which enable all Trilinos solvers and disabling it will disable all Trilinos solvers. This is the only thing a naive user should other with. Stratimikos probably was this (without Thyra maybe). Does it make sense ? I would like a much leaner Stratimikos.

**Comment by mhoemmen** [comment]
We did work on a "leaner Stratimikos" a while back (circa 2015), called LinearSolverFactory.  There was a technical issue with dependency inversion and injection (DII) across library boundaries with static libraries.  However, we are using it internally to some packages.  We're also reusing some of the ideas now for intrapackage DII to reduce build time.

**Comment by srajama1** [comment]
Yes, LinearSolverFactory could be a good first step towards this. I believe it went inside Teuchos for lack of a better place. It needs to be elevated to a higher level. (DII ?)

**Pull request merged**
