### PR TITLE
MueLu: Add yaml-cpp to MueLu's optional TPL libraries

### PR DESCRIPTION
**Pull request by johntfoster**
This is required to add the include paths and libraries to TPL_INCLUDE_DIRS
and TPL_LIBRARIES upstream.  This may be required if applications dependent on
Trilinos want to use the Muelu YAML parser.

### CODE REVIEW

**Comment by tawiesn** [comment]
@csiefer2 Shall we merge this or are you already working on moving it to Teuchos? 
We should also re-check CMakeLists.txt. I am afraid that the YamlParameterListInterpreter is not installed with "make install".

**Comment by mhoemmen** [comment]
I changed the title to avoid confusion.  yaml-cpp is already a Trilinos TPL, just not a TPL of the package.

**Comment by johntfoster** [comment]
It would be nice if this could be merged and the change moved to Teuchos when the YAML interface moves.  I've already checked in a YAML input file reader into Peridigm that depends on this change.  I'll refactor the Peridigm interface when this is moved to Teuchos.

**Comment by mhoemmen** [comment]
We should CC @brian-kelley too, just to make sure he knows what's going on with the YAML code he wrote :-)

**Comment by johntfoster** [comment]
Understand this has nothing to do with the YAML code, but rather is a CMake issue such that the proper paths get placed in TPL_LIBRARIES and TPL_INCLUDE_DIR variables upstream.

**Comment by johntfoster** [comment]
Guys, can we get this merged?  This is a very benign change to a single line of a CMake configuration file that propagates the path variables forward correctly.  

I've already checked in yaml supported input decks to Peridigm and now users are running into configuration errors because the yaml-cpp header and library paths are not populated forward into the master Trilinos cmake config file that Peridigm reads at configuration.

**Comment by mhoemmen** [comment]
Ok, I fixed it in develop.  Note that I'm not a MueLu developer so I didn't test it.

**Comment by tawiesn** [comment]
Thanks, Mark!

**Pull request closed without merging**
