### PR TITLE
Frosch : add an option to call Zoltan2 before local ILU

### PR DESCRIPTION
**Pull request by iyamazaki**
@trilinos/shylu 

## Motivation

This PR adds an option to call Zoltan2 before local ILU

### CODE REVIEW

**Comment by iyamazaki** [comment]
Hi, @searhein.. No, this is just for ILU. Sparse direct solvers usually come with different options for the fill-reducing ordering but if such options are needed, just let me know.

**Comment by searhein** [comment]
It could be interesting to have a node-level DD method for the local solve. Therefore, I though one could implement the METIS in a general way such that all node-level solvers can use it?

**Review by brian-kelley — APPROVED** [review]
Ifpack2 changes look good to me.

**Comment by iyamazaki** [comment]
Thank you, @brian-kelley!!

**Comment by iyamazaki** [comment]
@searhein. For this PR, I put Zoltan2 in Ifpack2 solver interface for local matrix ordering, not for partitioning. Maybe, we could discuss your use case?

**Comment by searhein** [comment]
@iyamazaki Oh, I see. I just had a very quick look. So I mixed this up. Thanks!

**Review by searhein — APPROVED** [review]

**Pull request merged**
