### PR TITLE
VariableDofPerNodeTest

### PR DESCRIPTION
**Pull request by rstumin**
Auto-PR for SHA 020903a

### CODE REVIEW

**Comment by csiefer2** [comment]
@trilinos/framework @rstumin  is having problems reproducing the test fail.  Can we get an assist here?

**Comment by william76** [comment]
@bartlettroscoe Hey Ross, the `packageEnables.cmake` file that gets generated in the PR testing just lives on Jenkins currently and I don't believe it's being cached anywhere.  The configure line that's being used to build just loads that file... but it'd be nice if we could get at the list of packages that it enabled for the test to replicate the results.  Do you know where we'd look in the CDash output to get the information of what was in that file?  

If this info is not really captured by CDash, it might be something that @trilinos/framework should considering appending to the autotester console message.

**Comment by bartlettroscoe** [comment]
> Hey Ross, the packageEnables.cmake file that gets generated in the PR testing just lives on Jenkins currently and I don't believe it's being cached anywhere.

@william76, it does not need to be cached because it prints out the list of packages that it will enabled, in the Jenkins script STDOUT output, for example, the line:

```
D) Filter list of changed packages to get only the PT packages


CHANGED_PACKAGES_PT_LIST='MueLu'
```

and it prints out the vars that it sets automatically when it is loaded in CMake as shown in the last Itel PR build shown above shown [here](https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3929690) which shows:

```
loading initial cache file /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/packageEnables.cmake
-- Setting Trilinos_ENABLE_MueLu = ON
```

Make sense?

**Comment by william76** [comment]
@bartlettroscoe 
Ah, ok... I think I got it... so from the link you provided, right at the top this section:

```
loading initial cache file /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/cmake/std/PullRequestLinuxIntelTestingSettings.cmake
loading initial cache file /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/packageEnables.cmake
-- Setting Trilinos_ENABLE_MueLu = ON

Configuring Trilinos build directory
...
```

Captures what's in the `packageEnables.cmake` file... so all @rstumin needs to do is set `Trilinos_ENABLE_MueLu=ON` in his configuration and that would get him everything that this test built...?

Am I following that correctly?

**Comment by bartlettroscoe** [comment]
> Am I following that correctly?

Exactly!  Can some @trilinos/framework person document that little bit of info at:

* https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

?

**Comment by jhux2** [comment]
@trilinos/framework @william76 @bartlettroscoe  Does the PR tester use SEMS modules?  If so, it would be great if the module environment was captured in the cdash output.  One could probably ferret out the versions by staring the configure output, but that could be error prone or incomplete.

**Comment by william76** [comment]
@jhux2 The autotester uses SEMS modules... The modules loaded are actually printed out onto the console output -but- it's just slightly above the point where the 'last 100 lines' gets cut off.  You can actually see it at the very top of the output in the intel job for this PR

```
 17) atdm-ninja_fortran/1.7.2
MPI type = sems-mpich/3.2
CDash Track = Pull Request
```

-but- the Wiki page https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors does address this:

> source <Trilinos_home_dir>/cmake/std/sems/PullRequestGCC4.X.YTestingEnv.sh
> or
> source <Trilinos_home_dir>/cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh

**Comment by jhux2** [comment]
@william76 There's a wiki?!  Thanks for the pointer, I had no idea.  Maybe the PR tester could print a helpful message pointing to the wiki whenever there's a failure, e.g.,

```
Puny human, some checks were not successful.  If the dashboard output isn't helpful,
see https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors
for instructions on how to reproduce the build locally.
```

**Comment by william76** [comment]
@bartlettroscoe Ross, I added an extra section to that wiki page to (hopefully) explain how to get the list of packages that were enabled.  It's probably worth bringing up in the @trilinos/framework meeting ways that we can make this information easier to access.

@jhux2 Yeah, I had even forgotten about that wiki page until I got links to it from Ross and Paul... I think it would be handy to just put a "How Do I Replicate a Failing PR Build" link directly into the autotester messages ;)

**Pull request merged**
