### PR TITLE
Tpetra: Add team parallelism to a couple kernels associated with matrix equilibration

### PR DESCRIPTION
**Pull request by vbrunini**
@trilinos/tpetra

## Motivation
Modest GPU performance improvements when using matrix equilibration.

## Related Issues

* Closes `put-issue-number-here`

## Testing
There are tpetra unit tests for all of these kernels, TpetraCore_Equilibration_MPI_4 and TpetraCore_CrsMatrix_LeftRightScale_MPI_4.

### CODE REVIEW

**Comment by vbrunini** [comment]
@jhux2

**Review by jhux2 — APPROVED** [review]
Lgtm, thanks!

**Comment by achauphan** [comment]
Apologies for having the non-blocking PR test `Trilinos_PR_non_blocking_gcc-8.5.0` actually block the passing status of the AutoTester. We added a fix into our AutoTester configs and it should propagate through.

**Comment by jhux2** [comment]
> Apologies for having the non-blocking PR test Trilinos_PR_non_blocking_gcc-8.5.0 actually block the passing status of the AutoTester. We added a fix into our AutoTester configs and it should propagate through.

No worries!

**Comment by jhux2** [comment]
@achauphan In the latest round of testing, the dashboard is clean, but the AT still reports failures.  The non-blocking test reports as failing if I expand the details above, I don't know if this could still be a problem.

**Comment by achauphan** [comment]
@jhux2 still looking into this and am going to have to pick this back up over the long weekend. apologies for all the hiccups this week :(

**Comment by jhux2** [comment]
@sebrowne @trilinos/framework I don't see any failure information from the latest round of PR testing.

**Comment by sebrowne** [comment]
@jhux2 there was a machine defect for the GCC build,  RETESTing.  We have a lot of machine OS changes going on right now which is responsible for some of the instability.

**Pull request merged**
