### PR TITLE
Framework: Add several upgraded RHEL8 Nightly configurations

### PR DESCRIPTION
**Pull request by achauphan**
@trilinos/framework

## Motivation

Several Nightly builds are still using RHEL7 configurations which are no longer acceptable due to now only have RHEL8 machines. Therefore, we need to upgrade any RHEL7 Nightly configuration to use RHEL8 modules.

This PR also includes a new `ALL-NO-EPETRA` version of our existing Nightly coverage configuration.
## Related Issues

- [TRILFRAME-654](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-654)

## Testing

- `gcc-8.5.0-serial_all-no-epetra` built and tested locally, no errors
- `clang-11.0.1-openmpi-asan` built and tested locally, no errors
- `cxx-20-gcc-8.5.0-openmpi` built and tested, no errors
- `gcc-8.5.0-openmpi_coverage_all-no-epetra` NOT tested, will observe behavior in Nightly tests.

### CODE REVIEW

**Review by sebrowne — APPROVED** [review]
Same comments as in the other repository, could we move the cxx20 so that it's not part of the environment name and don't have to have a second (duplicate) environment entry?

**Comment by achauphan** [comment]
> Same comments as in the other repository, could we move the cxx20 so that it's not part of the environment name and don't have to have a second (duplicate) environment entry?

@sebrowne I did look into this and there are few options that wouldn't require much work, and then there is probably the correct way to go about it that requires more work and testing.

The two easy options:
- ride existing `package-enables` flag in [supported-config-flags.ini](https://github.com/trilinos/Trilinos/blob/9b42dd24264587914627a034fddbfffee2b41a2d/packages/framework/ini-files/supported-config-flags.ini#L246) and add a option for `cxx20-all`
- ride along the `debug` option with something like `debug-cxx20` (this is what the [coverage build flag](https://github.com/trilinos/Trilinos/blob/9b42dd24264587914627a034fddbfffee2b41a2d/packages/framework/ini-files/supported-config-flags.ini#L138) does).

However, to be its own flag option, it would require more work and testing as to add a NEW flag indicating a standard, we would need to modify **every** `config-specs.ini` since [config-specs.ini requires the at least one option](https://github.com/trilinos/Trilinos/blob/9b42dd24264587914627a034fddbfffee2b41a2d/packages/framework/ini-files/config-specs.ini#L18) from every flag defined in `supported-config-flags.ini`. 

I do agree that having the cxx20 name further down is more ideal and would make more sense, but with how the current flags are set up and the requirements of `config-specs.ini`, it would require a lot of changes to existing configuration names.

I think adding it as an option to the `debug` flag is probably the best way if we want to move this `cxx20` thing down.

**Comment by achauphan** [comment]
Perhaps to give us more flexibility for the future, it would be worth adding a `optionals` flag to `supported-config-flags` with `SELECT_MANY`  and have any optional flags we want present in the environment name here with a default of something like `no-optionals`.

This would require going through and adding this to **every** configuration, but only once.

**Review by sebrowne — APPROVED** [review]

**Comment by sebrowne** [comment]
Glad to hear you considered it, I'm fine leaving it how it is

**Pull request merged**
