### PR TITLE
Rythmos: Removed unused var and shadowed typedef (#634)

### LINKED ISSUE #634: Fix warnings for dashboard builds
This effort will be to fix various warnings seen in dashboard builds.
Those errors are at:
http://my.cdash.org/index.php?project=Trilinos&parentid=1052339

Pull requests to fix the warnings will be made separately for each package.

The current list of packages with issues (from Jim's e-mail):
ROL
Stokhos - probably fixed already
Pamgen
ShyLU
Piro
Kokkos
Rythmos
Mesquite
Panzer
ML (will skip for this round because previous pull request is outstanding)
Pliris (will skip for this round because previous pull request is outstanding)

### PR DESCRIPTION
**Pull request by MicheldeMessieres**
This pull request is one of a set of pull requests being submitted to resolve #634.

### CODE REVIEW

**Comment by jwillenbring** [comment]
@bmpersc do you want to do an initial assessment of this pull request?

**Comment by bmpersc** [comment]
I have questions regarding this and suspect Curt Ober will need to review this. The biggest concern is that I think that "Scalar one = ST::one();" was intended to be used in the following lines instead of ignored. I don't know if there is a performance(compile time or runtime) cost to using the traits function to get a one or if there is benefit to doing it the way it is. Curt would need to say.

I have sent a request to Curt to get his github ID so we can add him to this issue and Trilinos in general.

**Comment by bmpersc** [comment]
I believe that @ccober6 should have a look at this.

**Comment by jwillenbring** [comment]
@MicheldeMessieres Since @ccober6 approved, please feel free to merge this.

**Pull request merged**
