### PR TITLE
STK snapshot 8-3-20

### PR DESCRIPTION
**Pull request by tasmith4**
@trilinos/stk

### CODE REVIEW

**Comment by jvo1012** [comment]
@bartlettroscoe

**Comment by bartlettroscoe** [comment]
@jvo1012, how urgent is it to get this merged?

**Comment by jvo1012** [comment]
> @jvo1012, how urgent is it to get this merged?

These changes are needed by the sparc team to get StkSimd working for them so we would like to get it pushed soon, but it is not critical.

**Comment by bartlettroscoe** [comment]
> These changes are needed by the sparc team to get StkSimd working for them so we would like to get it pushed soon, but it is not critical.

@jvo1012, okay, I will try to look at this tomorrow.

**Pull request closed without merging**
