### PR TITLE
Tpetra - giving a choice of little block layout between layout left and layout right

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
@trilinos/tpetra 

## Motivation

In block crs, we currently use layout right (row major) as its default little block layout. Since the little block is an internal object, changing the layout between layout right and layout left should be possible unless users directly access the pointer assuming either of the layout. This PR provides configure option to choose between layout left and layout right for the little block. In my opinion, using the layout left would be more performant in terms of vectorization on both CPUs and GPUs as the little block mat-vec operation consists of vector scaling operations instead of horizontal sum (vector reduce).  

Ifpack2 block tri diag container code directly accesses the little block pointer. Necessary changes are made to respect Tpetra little block layout. 

## Testing

Currently, the layout left is enabled by giving a CFLAGS ``-D TPETRA_ENABLE_BLOCKCRS_LITTLEBLOCK_LAYOUTLEFT`` for evaluation purpose (not a cmake option). I confirmed that layout left passes the PR test.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
Still testing to see if the code change pass the pr test.

**Comment by kyungjoo-kim** [comment]
@tcclevenger This is the PR that I am expecting some performance benefits for larger block sizes (in particular on CPUs).

**Comment by kyungjoo-kim** [comment]
weird pr test system error ``Error: A license for Comp-CL is not available now ``. Put retest label

**Comment by kyungjoo-kim** [comment]
weird test failure is reported from the latest pr test. the tester looks for "TEST PASSED" and the output of a bug7745 test shows "T PASSED". I am not sure if this is just one time hiccup or not and just re-run the test.

**Comment by kyungjoo-kim** [comment]
@trilinos/tpetra The failure from [TpetraCore_CrsMatrix_Bug7745_MPI_4](https://testing.sandia.gov/cdash/test/115424865) seems to be repeatable. From the output of the test, it passes but it does not seem to print "TEST PASSED". Instead, it prints "T PASSED" at the end. Or the output of the test does not include all verbose output of the test ? Any idea @trilinos/framework ? 

https://testing.sandia.gov/cdash/test/115424865

**Comment by e10harvey** [comment]
> https://github.com/orgs/trilinos/teams/tpetra The failure from [TpetraCore_CrsMatrix_Bug7745_MPI_4](https://testing.sandia.gov/cdash/test/115424865) seems to be repeatable. From the output of the test, it passes but it does not seem to print "TEST PASSED". Instead, it prints "T PASSED" at the end.

Related to https://github.com/trilinos/Trilinos/issues/10043#issuecomment-1015812299.

**Comment by kyungjoo-kim** [comment]
@e10harvey the Cuda failure is not reported in the cdash and it seems to be related with auto-tester.

**Comment by e10harvey** [comment]
> @e10harvey the Cuda failure is not reported in the cdash and it seems to be related with auto-tester.

@kyungjoo-kim: We are working on a fix. See https://github.com/trilinos/Trilinos/issues/10167. The failure stopped the script before cdash submission.

**Comment by kyungjoo-kim** [comment]
@e10harvey Upon the request, I close and reopen a new PR.

**Pull request closed without merging**
