### PR TITLE
ATDM: Disable packages GEMMA does not use in all cuda+complex builds (ATDV-265)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
We don't have the human resources to continue to keep testing and trying to maintain builds and tests that ATDM does not use.  If ATDM APPs are not directly impacted, Trilinos developers mostly just ignore the GitHub issues we create so it is a waste of computer resources and human time maintaining them. 

For more details, see [ATDV-261](https://sems-atlassian-srn.sandia.gov/browse/ATDV-261), [ATDV-262](https://sems-atlassian-srn.sandia.gov/browse/ATDV-262), and [ATDV-265](https://sems-atlassian-srn.sandia.gov/browse/ATDV-265).

## How was this tested?

Doing configure of Trilinos with GEMMA packages:

```
$ ssh ascicgpu15

$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CHECKIN/

$ ./checkin-test-atdm.sh \
  sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug \
  --enable-packages=Phalanx,KokkosCore,KokkosAlgorithms,Teuchos,Tpetra,Belos,Triutils,Pliris,Gtest \
  --configure
```

The set of packages enabled and *not* enabled is:

* `Final set of enabled packages:  Gtest Kokkos Teuchos KokkosKernels RTOp Sacado Epetra Zoltan Shards Triutils EpetraExt Tpetra TrilinosSS Thyra Xpetra Pliris AztecOO Galeri Amesos Ifpack ML Belos Phalanx 23`

* `Final set of non-enabled packages:  TrilinosFrameworkTests MiniTensor GlobiPack Domi OptiPack Isorropia Claps Pamgen Zoltan2 ShyLU_Node Amesos2 SEACAS Trios Komplex Anasazi Ifpack2 Stratimikos FEI Teko TriKota Intrepid Intrepid2 STK Percept NOX Moertel MueLu ShyLU_DD ShyLU Rythmos Tempus Stokhos ROL Piro Panzer PyTrilinos NewPackage TrilinosCouplings Pike 39`

Therefore, we can add the extra disables for the extra packages not already disabled in ATDM Trilinos builds. ... Done.

Now to test with all enabled packages and verify the same set of enabled packages:

```
$ ssh ascicgpu15

$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CHECKIN/

$ ./checkin-test-atdm.sh \
  sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug \
  --enable-all-packages=on --configure
```

After that, there is the set of enabled packages:

* `Final set of enabled packages:  Gtest Kokkos Teuchos KokkosKernels RTOp Sacado Epetra Zoltan Shards Triutils EpetraExt Tpetra TrilinosSS Thyra Xpetra AztecOO Galeri Amesos Pamgen Zoltan2 Ifpack ML Belos Phalanx 24`

That is exactly the same set of packages except for Zoltan2, which we are allowing for testing purposes.

Now to test this updated configuration, just to be safe:

```
$ ssh ascicgpu15

$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CTEST_S/

$ ./ctest-s-local-test-driver.sh \
  sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

***
*** ./ctest-s-local-test-driver.sh
***

ATDM_TRILINOS_DIR = '/scratch/rabartl/Trilinos.base/Trilinos'

Load some env to get python, cmake, etc ...

Hostname 'ascicgpu15' matches known ATDM host 'sems-rhel7' and system 'sems-rhel7'
Setting compiler and build options for build-name 'default'
Using SEMS RHEL7 compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL

Running builds:
    sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

Running Jenkins driver Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug.sh ...

    See log file Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/smart-jenkins-driver.out

real    144m20.654s
user    1215m23.769s
sys     171m38.605s
```

That posted results to:

* [Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug-exp](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5078129)

That shows 11 failing tests for TpetraCore and Zoltan2 which are already failing and are already tracking in:

* https://github.com/trilinos/Trilinos/issues/6333
* https://github.com/trilinos/Trilinos/issues/6333
* https://github.com/trilinos/Trilinos/issues/6418
* https://github.com/trilinos/Trilinos/issues/6412

### CODE REVIEW

**Comment by mhoemmen** [comment]
@bartlettroscoe Does this mean we now have no CUDA + complex testing on the Dashboard?

**Comment by bartlettroscoe** [comment]
> Does this mean we now have no CUDA + complex testing on the Dashboard?

@mhoemmen, no, we are still testing the packages that GEMMA uses as you can see at:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5079713

which includes:

Kokkos | 65e50b | 0 | 3 | 0 | 0 | 0 | 0 | 28 | 2m 21s | 1
Teuchos | 65e50b | 0 | 3 | 0 | 0 | 0 | 0 | 144 | 2m 14s | 2
KokkosKernels | 65e50b | 0 | 3 | 0 | 0 | 0 | 0 | 8 | 4m 32s | 3
Sacado | 65e50b | 0 | 3 | 0 | 0 | 0 | 0 | 303+1 | 6m 2s | 4
Tpetra | 65e50b | 0 | 3 | 0 | 19+19 | 0 | 9+2 | 215-2 | 1h 18m 38s | 5
TrilinosSS | 65e50b | 0 | 3 | 0 | 0 | 0 | 0 | 0 | 0s | 6
Thyra | 65e50b | 0 | 3 | 0 | 0 | 0 | 1+1 | 81-1 | 1m 42s | 7
Xpetra | 65e50b | 0 | 3 | 0 | 2+2 | 0 | 0 | 15 | 6m 51s | 8
Zoltan2 | 65e50b | 0 | 3 | 0 | 18+18 | 0 | 8+4 | 110-4 | 48m 13s | 9
Belos | 65e50b | 0 | 3 | 0 | 11+11 | 0 | 4+4 | 112-4 | 14m 57s | 10
Phalanx | 65e50b | 0 | 3 | 0 | 0 | 0 | 0 | 30 | 1m 22s | 11

All other packages are not being used by GEMMA in cuda+complex builds.

If other customers want us to test capabilities not used by ATDM, then they need to supply people to help triage failures.  It is trivial to allow the enable of more packages.  It is just that Trilinos develoeprs typically ignore the GitHub Issues we create unless something is urgently impacting an ATDM customer.  We need to focus our time providing value for ATDM.

**Comment by mhoemmen** [comment]
@bartlettroscoe Sierra needs to build with CUDA + complex.  Is there at least one of those builds on the Dashboard?

**Comment by bartlettroscoe** [comment]
> Sierra needs to build with CUDA + complex. Is there at least one of those builds on the Dashboard?

@mhoemmen, then SIERRA needs to set up their own cuda+complex build and post to the Dashboard.  I know that sounds harsh but we don't have the staff time to test and debug other customer's stuff.

**Comment by mhoemmen** [comment]
@bartlettroscoe That's alright; I understand.

@rrdrake @sebrowne FYI

**Pull request merged**
