### PR TITLE
Remove old framework/CI settings and infrastructure

### PR DESCRIPTION
**Pull request by e10harvey**
@trilinos/framework
## Motivation

Now that GenConfig has been deployed, we can remove the old cmake and environment settings as well as their associated driver scripts.

## Testing

This was tested manually via pipeline replays that ran off of both the source and target branches:
[Source branch results.](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-__UNKNOWN__-test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-106&field3=buildstamp&compare3=61&value3=20220622-1528-Experimental)
[Target branch results.](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-__UNKNOWN__-test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-107&field3=buildstamp&compare3=61&value3=20220622-1532-Experimental)

This PR resolves _TRILFRAME-312: Remove old pre-GenConfig infrastructure._

**Reviewers:** Please verify that this old infrastructure is not used outside of MasterMerge and PullRequest testing. If this infrastructure is in use outside of MasterMerge and PullRequest testing, we should consider disabling that or migrating it to GenConfig before this merges.

CC: @srbdev

### CODE REVIEW

**Review by bartlettroscoe — APPROVED** [review]
The changes from my last review are shown [here](https://github.com/trilinos/Trilinos/compare/baebf2d26708c44a5a9112205a490b889034c381..d4188c8879a071e54b5692194f56b1a7ba49b890).  It shows the 4 files added back:

* [cmake/std/sems/SEMSDevEnv.cmake](https://github.com/trilinos/Trilinos/compare/baebf2d26708c44a5a9112205a490b889034c381..d4188c8879a071e54b5692194f56b1a7ba49b890#diff-7e68dd9d1ccf7d7bb716a410bcb73379003531901f684f3c6693ea912f58e645)
* [cmake/std/sems/checkin-test-sems.sh](https://github.com/trilinos/Trilinos/compare/baebf2d26708c44a5a9112205a490b889034c381..d4188c8879a071e54b5692194f56b1a7ba49b890#diff-c997c136124ea065012696175859d5c94d17ee4e7dd77cb95e0425a2cd0f1181)
* [cmake/std/sems/get_default_modules.sh](https://github.com/trilinos/Trilinos/compare/baebf2d26708c44a5a9112205a490b889034c381..d4188c8879a071e54b5692194f56b1a7ba49b890#diff-fe286253c71f1b917cb48f3ee151c06ae2036961dad04757bc00c9043712e295)
* [cmake/std/sems/trilinos_jsrun](https://github.com/trilinos/Trilinos/compare/baebf2d26708c44a5a9112205a490b889034c381..d4188c8879a071e54b5692194f56b1a7ba49b890#diff-4053f7012da9c88dff9196166dc6b509eac06485ddbfb1e91f4cb6ab5d56597b)


@e10harvey, a potentially better way to add back these 4 files is to create a single commit to do it and make it clear what you are doing.  For example, you can do this:

```
$ cd Trilinos/
$ git checkout TRILFRAME-312
$ git reset --hard baebf2d26708c44a5a9112205a490b889034c381
$ git checkout e2d0f8fba270e2a1eb4ed045fe8074a4b939e6b8^ -- \
  cmake/std/sems/SEMSDevEnv.cmake \
  cmake/std/sems/checkin-test-sems.sh \
  cmake/std/sems/get_default_modules.sh \
  cmake/std/sems/trilinos_jsrun
$ git commit -a -m "Bring back files not unique to old Trilinos PR testing"
$ git push -f
```

Just a suggestion for achieving a cleaner and more obvious Git History.

(Note, I believe that it is usually better to create new commits to address reviewer comments than to redo the old commits and force push.   That provides an easy-to-follow history for the development and review of a PR branch.)

**Comment by bartlettroscoe** [comment]
FYI: The [above PR iteration](https://github.com/trilinos/Trilinos/pull/10648#issuecomment-1164260029) failed due to 3318 mass random failures for the cuda build on vortex shown [here](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-10648-test-ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables-251&field2=status&compare2=62&value2=Passed&field3=testoutput&compare3=95&value3=Error%20initializing%20RM%20connection.%20Exiting) showing:

```
Error initializing RM connection. Exiting
```

which was reported many years ago in #6861 and one test failed showing:

```
jsrun return value: 255
```

which was reported years ago in #7122.

I will reopen those issues.


The machine 'vortex' is not a good machine to drive PR testing due to these random jsrun failures on this machine (which the vender has never been able to fix).

**Review by jwillenbring — APPROVED** [review]
Nice to remove these now obsolete files. Thanks.

**Review by ZUUL42 — APPROVED** [review]
It's good to see a lot of cleanup.

**Pull request merged**
