### PR TITLE
Revert "Remove old framework/CI settings and infrastructure"

### PR DESCRIPTION
**Pull request by e10harvey**
Reverts trilinos/Trilinos#10648.

@dridzal, @bartlettroscoe: Please feel free to merge this or pull it into your working branch as a quick work around to #11101.

### CODE REVIEW

**Comment by dridzal** [comment]
@bartlettroscoe:  I'm willing to try this within my sync process.  Recall we do

```
>> cd rol-trilinos/Trilinos
>> git checkout develop           # tracking rol-trilinos/develop
>> git fetch rol-trilinos
>> git reset --hard @{u}          # wipe out any local state you don't want
>> git fetch upstream             # this is the main Trilinos repo
>> git merge --no-ff --no-edit upstream/develop    # allow backouts with explicit merge commit
>> cd CHECKIN/
>> ./checkin-test-sems.sh --wipe-clean --no-enable-fwd-packages --enable-all-packages=off --enable-packages=ROL --no-rebase --do-all --push --no-append-test-results
```

Where in the sequence of commands would I apply the revert commit by @e10harvey , and how?

**Comment by e10harvey** [comment]
@dridzal: I think after `git merge --no-ff --no-edit upstream/develop` and before `cd CHECKIN` you can add:
```
git cherry-pick b86a7834d8d161d8dddc4519ca0db77ecc44a613
```

**Comment by dridzal** [comment]
@e10harvey : Ok, but I would probably not want to merge in this revert ... so I may have to stop the checkin test script from pushing.  In other words, let it perform all the testing with the revert enabled, then undo the revert commit, then push into our private ROL repo.  @bartlettroscoe , do you have advice?  This is just a temporary solution, I agree we need to upgrade the checkin test script.

**Comment by bartlettroscoe** [comment]
> @e10harvey : Ok, but I would probably not want to merge in this revert ... so I may have to stop the checkin test script from pushing. In other words, let it perform all the testing with the revert enabled, then undo the revert commit, then push into our private ROL repo. @bartlettroscoe , do you have advice? This is just a temporary solution, I agree we need to upgrade the checkin test script.

@dridzal, you can do that but then you need to hard reset your local branch to remove the cherry-pick of the revert commit.

Another option is to get your local repo in the state ready to push and then run a Trilinos PR build locally with the new tool that I created:

* https://gitlab-ex.sandia.gov/rabartl/run_trilinos_pr_builds

I can give you the exact command(s) to run if you tell me what PR builds you want to check.

That way you are using a Trilinos PR GenConfig configuration and you are more likely to avoid failures not addressed in the old reverted Trilinos PR configuration files.  Otherwise, I can almost guarantee you will see build or test failures you will have to traige.

Also, that way, it will not pollute your local repo branch with anything.

**Comment by dridzal** [comment]
@bartlettroscoe : Yes, I would have to remove the last commit, which is the cherrypick.  However, I am also worried about the old reverted configuration files.  We could create a mess.

Let's consider your alternative.  When you say "ready to push", is that right after the command `git merge --no-ff --no-edit upstream/develop` in the old sync script?  In other words, merge all changes from Trilinos proper into ROL-Trilinos, and then perform GenConfig testing?  And then push manually if successful?

**Comment by bartlettroscoe** [comment]
> Let's consider your alternative. When you say "ready to push", is that right after the command `git merge --no-ff --no-edit upstream/develop` in the old sync script? In other words, merge all changes from Trilinos proper into ROL-Trilinos, and then perform GenConfig testing? And then push manually if successful?

@dridzal, right, you basically replace:

```
./checkin-test-sems.sh --wipe-clean --no-enable-fwd-packages --enable-all-packages=off --enable-packages=ROL --no-rebase --do-all --push --no-append-test-results
```

with:

```
./run_trilinos_pr_bulids.py \
  -b rol-sync -p ROL -f off -j 16 clang-10.0.0
```

(run `./run_trilinos_pr_builds.py` to see what those short-hand options mean).

If you don't want to post that build to CDash, prefix that command with `env CTEST_DO_SUBMIT=OFF `.

Then if it reports 100% passing tests, go ahead and run:

```
$ cd rol-trilinos/Trilinos/
$ git push
```

I would not trust the `./run_trilinos_pr_bulids.py` tool to return 0 or non-zero at this point without some more careful testing.  But if you see "100% passed, 0 tests failed out of ???" in the STDOUT, then go ahead and push.

**Comment by dridzal** [comment]
@bartlettroscoe :  Ok, I'll give that a shot.  I'm looking at how to set up your tool.  It looks pretty straightforward.  My only question so far is if the the build directory should be outside of Trilinos source.

**Comment by bartlettroscoe** [comment]
> My only question so far is if the the build directory should be outside of Trilinos source.

@dridzal, it does not have to be but I never put build dirs under the base Trilinos/ repo dir so I can cleanly copy the repos around and do full cleaning with `git clean -xdf`.  I almost always use the directory structure:

```
Trilinos.base/
    Trilinos/
    BUILDS/
         pr_builds/
```

or something close to that.

That is also recommend by Craig Scott in his book [Professional CMake](https://bssw.io/items/cmake-tutorial-and-reference-resources).

**Comment by dridzal** [comment]
@bartlettroscoe : I've tried your tool.  It's promising, but there are problems with modules.  I'll move the discussion to email.

**Pull request closed without merging**
