### PR TITLE
Fix PR packages selection logic (#6697) and static list of CDash subprojects (#3272)

### LINKED ISSUE #3272: package_subproject_list.cmake static in Trilinos PR tester?
@trilinos/framework,

Is the file package_subproject_list.cmake used at:

https://github.com/trilinos/Trilinos/blob/0df591fd6d9b9ccd91bd2695cc22665aa468886d/cmake/std/PullRequestLinuxDriver.sh#L206

statically generated and require manual updating?  If so, that would explain why the PR builds are not testing the new PT package TrilinosFrameworkTests.

### LINKED ISSUE #6697: Why are Trilinos PR builds enabling Secondary Tested Code?
## Question
@trilinos/framework, @rppawlo, @trilinos/phalanx, @kddevin (Trilinos Data Services lead), @srajama1 (Trilinos Linear Solvers Lead), @

I just noticed that the Trilinos PR builds (or at least some of them are enabling secondary tested code as shown by, for example, the broken gcc_7.2.0 PR build shown [here](https://testing.sandia.gov/cdash/viewConfigure.php?buildid=6300498) which shows:

```
Enabling all SE packages that are not currently disabled because of Trilinos_ENABLE_ALL_PACKAGES=ON (Trilinos_ENABLE_SECONDARY_TESTED_CODE=ON) ...
```

That results in the enable of all of the secondary tested packages:

* `Final set of enabled packages:  TrilinosFrameworkTests Gtest Kokkos Teuchos KokkosKernels RTOp Sacado MiniTensor Epetra Zoltan Shards Triutils EpetraExt Tpetra TrilinosSS Domi Thyra Xpetra Isorropia Pliris AztecOO Galeri Amesos Pamgen Zoltan2 Ifpack ML Belos ShyLU_Node Amesos2 SEACAS Komplex Anasazi Ifpack2 Stratimikos FEI Teko Intrepid Intrepid2 STK Percept Phalanx NOX Moertel MueLu ShyLU_DD ShyLU Rythmos Tempus Stokhos ROL Piro Panzer TrilinosCouplings Pike 55`

and only the non-enabled packages:

* `Final set of non-enabled packages:  TriKota PyTrilinos NewPackage 3`

But the problem is that the ctest -S driver is **not** listing all 55 of these packages as CDash subjects as shown here:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=6300498

It only shows 53 of these 55 packages.  In particular, it is missing the 3 packages:

* TrilinosFrameworkTest
* Percept
* Moertel

One consequence of this is that it is listing Moertel build failures as Phalax build failures.

But the real question is, why is `Trilinos_ENABLE_SECONDARY_TESTED_CODE=ON`?  By definition, no important SNL customer is using non Primary-Tested packagse so why are Secondary Tested Packages getting enabled.

NOTE: The only Primary Tested Package that is not also a Secondary Tested package other than PyTrilinos and TriKota is Moertel.

### PR DESCRIPTION
**Pull request by bartlettroscoe**
@trilinos/framework 

This updates the logic to also enable ST packages in addition to PT packages.  This will fix #6697.

The updated `get-changed-trilinos-packages.sh` script now also produces a file `package_subproject_list.cmake` that is used to replace the static list of packages currently being used in PR testing that control what rows are displayed on CDash.  This fixes #3272.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
FYI: This is not ready to merge.  The logic for selecting the CDash subprojects is not correct.  What is needed is to run the full TriBITS dependency logic to determine the full list of TriBITS packages that will need to be tested given an input list of SE package enables.  This is going to be duplicating what is already in the `TRIBITS_CTEST_DRIVER()` function.  (I should refactor that out into its own TriBITS function and then create a CMake -P script to driver this.)

**Comment by prwolfe** [comment]
> FYI: This is not ready to merge. The logic for selecting the CDash subprojects is not correct. What is needed is to run the full TriBITS dependency logic to determine the full list of TriBITS packages that will need to be tested given an input list of SE package enables. This is going to be duplicating what is already in the `TRIBITS_CTEST_DRIVER()` function. (I should refactor that out into its own TriBITS function and then create a CMake -P script to driver this.)

This was my original thoughts on the work. Thanks for taking this on!

**Comment by bartlettroscoe** [comment]
@prwolfe, as of the last commit https://github.com/trilinos/Trilinos/pull/7414/commits/3e9a1ac9faf4b595f768ec6785cf9d86a974d261 in this PR, this is now ready to merge  Can you go ahead and review and approve so we can merge this?

For now, it just defines the variable `CTEST_LABELS_FOR_SUBPROJECTS` as the full set of packages that is tested in PR testing.  But at least know this list is automatically up-to-date for what is in Trilinos.  It includes all PT and ST package except for some specifically filtered-out packages (in this case 'TriKota' and 'PyTrilinos').

And this PR also makes it so that ST package and subpackage get tested correctly such as ShyLU_NodeHTS (see #7229).

Therefore, this PR solves two big problems that PR testing currently has:

* It did not test ST packages (e.g. see #6699 and #7162 
* It did not adjust the CDash subprojects and packages were added and removed from Trilinos (see #7414 

Until this gets merged, the PR tester is still not going to be testing some important packages being used by ATDM and have resulted in a broken 'develop' branch (see the cases that lead to #6697).

As a later follow-on PR later we can do:

* Fix logic to select a reduced set of CDash Subprojects based on what is being tested:
  - Create module `tribits/ci_support/TribitsCISupport.cmake` that will factor code out of `TribitsCTestDriverCore[Helpers].cmake` that determines the set of packages to be tested given a set of changed packages ...
  - Create a cmake -P script `tribits/ci_support/TribitsGetToplevelPackagesToTestScript.cmake` that will produce the list of toplevel packages to be tested given set of changed packages ...
  - Create TriBITS Python tool `tribits/ci_support/get-toplevel-packages-to-test.py` that will take a list of SE package enables (for changed packages) and turn it into a list of toplevel packages to test (to be used as CDash subprojects) ...
  - Use new tool `get-toplevel-packages-to-test.py` to create set the var `CTEST_LABELS_FOR_SUBPROJECTS` in the script `get-changed-trilinos-packages.sh`  ...

and of course add unit testing for all of that along the way.

**Comment by bartlettroscoe** [comment]
@prwolfe 

> did you intend to submit the new script get-tribits-packages.py and the changes to TribitsDependencies.py without testing? I recommend comprehensive unit testing here.

They have unit tests in TriBITS under TriBITS/tests/ as shown [here](https://github.com/TriBITSPub/TriBITS/compare/1389f63d9d61032e88b6ba39fc5d7cd86522a1d3..7adcf81a08b653e4f8871ff679f01c2a18dad4e9)  When TriBITS is snapshotted into Trilinos, only the production code TriBITS/tribits/ dir snapshotted, not the test code.

> the test that you modified for the DriverTest.py script now leaves a package_subproject_list.cmake behind when it is run. That could actually cause a conflict if the unit test is run in a clone used for other testing (we currently do not do this.)

That file gets generated along side the generated `enablePackages.cmake` so if a lingering `enablePackages.cmake` file is not a problem for other PRs, then neither should be a lingering  `package_subproject_list.cmake` file.  And note that that file gets generated for every PR anew so there should be no risk of having a left over file because it gets overwritten each time.

Please let me know if you have if there are any other issues.  It would be good to get this merged to fix the current problems with the PR system outlined [above](https://github.com/trilinos/Trilinos/pull/7414#issuecomment-633733113).

**Comment by bartlettroscoe** [comment]
@prwolfe, thanks for the patches in https://github.com/bartlettroscoe/Trilinos/pull/3.  I approved and merged into this PR.

**Comment by prwolfe** [comment]
> They have unit tests in TriBITS under `TriBITS/test/` as shown [here](https://github.com/TriBITSPub/TriBITS/compare/1389f63d9d61032e88b6ba39fc5d7cd86522a1d3..7adcf81a08b653e4f8871ff679f01c2a18dad4e9) When TriBITS is snapshotted into Trilinos, only the production code in the `TriBITS/tribits/` dir gets snapshotted, not the test code.

Sounds good - Thanks for working this one.

**Comment by bartlettroscoe** [comment]
Thanks @prwolfe!  I put on `AT: AUTOMERGE` so as soon as the PR tester complete, it will merge.

**Pull request merged**
