### PR TITLE
NOX: Fix race condition in HouseholderBorderedSolve unit test

### PR DESCRIPTION
**Pull request by JacobDomagala**
Related to #8492

Ok I think I finally fixed it.

### CODE REVIEW

**Comment by JacobDomagala** [comment]
@rppawlo

**Review by rppawlo — APPROVED** [review]
Thanks @JacobDomagala !

**Review by rppawlo — APPROVED** [review]

**Comment by rppawlo** [comment]
@trilinos/framework - can you tell me why the PR testing has not started for this issue? I approved it a week ago.

**Review by rppawlo — APPROVED** [review]

**Review by cgcgcg — APPROVED** [review]

**Comment by cgcgcg** [comment]
@rppawlo No idea if "AT: PRE-TEST INSPECTED" is required for external contributions, but I figured I'd add it.

**Comment by ZUUL42** [comment]
@rppawlo, I did take a look at this earlier as I was working on something else.
There was nothing obvious that would have held it up.
The connectivity issues could have explained it, but only going back to last night. Back to last week, we'd have to dig deeper.
If you notice it happen again, please let us know.

**Pull request merged**
