### PR TITLE
Fix for ghost orientations.

### PR DESCRIPTION
**Pull request by seamill**
@trilinos/panzer

### CODE REVIEW

**Comment by seamill** [comment]
@rppawlo Could you review this? Most of it is copying functions from panzer_stk to panzer namespace to ensure ghost cell indexing is consistent across the code.

**Review by rppawlo — DISMISSED** [review]
Thanks @seamill ! I don't see a unit test to reproduce the issue in empire. Is this something you could quickly add?

**Comment by seamill** [comment]
@rppawlo Maybe, I'm still not sure how to drive that error (it really should have segfaulted at some point). I can put in a parallel_apply_orientations test that makes sure we apply orientations to the ghost cells though. That will at least exercise the capability.

**Comment by seamill** [comment]
@rppawlo I added the parallel test.

**Review by rppawlo — DISMISSED** [review]
Thanks @seamill !

**Comment by seamill** [comment]
@rppawlo Oop, missed a warning. One more review please.

**Review by rppawlo — APPROVED** [review]

**Pull request merged**
