### PR TITLE
Piro/Panzer: remove dependency from deprecated packages Rythmos and TriKota

### PR DESCRIPTION
**Pull request by mperego**
@trilinos/piro 
@trilinos/panzer

## Motivation

Packages Rythmos and TriKota will be removed in next release of Trilinos. 

## Testing
Removed the tests that depend on Rythmos and on Dakota (TriKota). 
Tempus tests should cover the transient solvers. 
In my understanding, Dakota is no longer used for analysis through Piro.

### CODE REVIEW

**Review by kliegeois — COMMENTED** [review]
It looks good to me @mperego . Thanks for doing this!
I have a small comment though.

**Review by kliegeois — DISMISSED** [review]
Looks good to me!

**Comment by mperego** [comment]
OK, I was a bit naive. I didn't consider that Panzer depends on Rythmos through Piro. I'll try to get that sorted out in the next days. @rppawlo please let me know if it's OK for me to do so.

**Comment by mperego** [comment]
@rppawlo my last commit should have fixed the compiler warnings.

**Comment by rppawlo** [comment]
Please hold off on merging this. It is disabling test coverage of panzer capabilities. I need to transition some of these tests from rythmos to tempus rather than disabling. @mperego - I'm in town and will stop by to talk a bit about this.

**Comment by mperego** [comment]
No problem. I thought that all the wanted capabilities were already covered by Tempus tests.
It's probably fine holding his for a while, however @kliegeois is developing Piro, so we might have to resolve some conflicts when we are able to merge this.

**Comment by ikalash** [comment]
@mperego : do we still have any Rythmos tests in Albany?  We should remove them if we do.

**Comment by mperego** [comment]
> @mperego : do we still have any Rythmos tests in Albany? We should remove them if we do.

We got rid of them. https://github.com/sandialabs/Albany/pull/949

**Comment by ikalash** [comment]
@mperego : great!

**Review by rppawlo — APPROVED** [review]
@mperego - looks good to me. This is ready to merge. I may restore the meshmotion.xml file, but we can do that in a separate request.

**Pull request merged**
