### PR TITLE
Tpetra: Permanent fix for #11655

### PR DESCRIPTION
**Pull request by brian-kelley**
@trilinos/tpetra
@trilinos/kokkos-kernels 

## Motivation

Permanent fix for #11655, where Tpetra was passing unsorted matrices to KokkosKernels SpGEMM and triggering debug checks. Revert the workaround in KokkosKernels (#11663).

## Testing

@rppawlo With these changes, all MiniEM tests are still passing with OpenMP+Debug. I would be surprised if EMPIRE still runs into the issue, but could you please check (either before or after this merges)?

### CODE REVIEW

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by brian-kelley** [comment]
@jhux2 There isn't really a timeline for that.

@cgcgcg I'm realizing now that enforcing sortedness unconditionally was a mistake, it would be better to have both paths. Some TPLs require it and some don't, so for the ones that do we can call KK as a fallback (for the time being, anyway). Also, it should not be enforced if the Tpetra LTG algo is used.

I'm going to try to get this into KK for the 4.1 release. Until then, the workaround can stay.

**Comment by cgcgcg** [comment]
Thanks, @brian-kelley! That makes sense to me.

**Comment by ndellingwood** [comment]
@brian-kelley should the kokkos-kernels changes from https://github.com/trilinos/Trilinos/pull/11663 get cherry-picked to the release-candidate-4.0.01 branch to avoid clobber with the Trilinos #11663 patch (since the long-term update to kokkos-kernels will be part of later 4.1 release)?

**Pull request closed without merging**
