### PR TITLE
Fix (workaround) DGEMM issue in kokkos kernels.

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
## Description
Problem is described in #3417 

## Motivation and Context
The possible explanation of this problem is a compiler bug. ``const int`` variable is changed in the middle of a function.

## Related Issues
#3417 

## How Has This Been Tested?
I tested on white with the ATDM script. All tpetra tests are passed.

## Additional Information
This error comes from a POWER system and it is not revealed from the previous PR test nor from x86 systems as the PR test does not include POWER systems.

### CODE REVIEW

**Comment by srajama1** [comment]
@kyungjoo-kim : You need to submit this as a PR for KK develop as well. Otherwise, these changes will be overwritten when we update new KK.

Can some C++ expert say why is the old code and new code behaving differently ? They look exactly the same to me and from @kyungjoo-kim 's decriptions he believes the same. I am worried how many other places we have the pattern on the left - X = something[atest?0:1]. Is that the problem ?

It would be nice to know the root cause.

**Comment by kyungjoo-kim** [comment]
@srajama1 I am going to submit another one to KK after I confirmed that this resolve the POWER8 issue. The issue is not on strides nor something[atest?0:1]. I confirmed that the variable is correctly defined with printing. The main problem is that the ``const int `` varialbe is changed after it is defined. We has nothing to dig further but cross fingers when we compile on the ibm machines or macs.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim and @srajama1, can I put the `AT: AUTOMERGE` label on this to merge if PR testing passes?  That would give a shot at having this change merged in time for the nightly ATDM Trilios builds starting tomorrow morning.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe It already has auto merge.

**Comment by srajama1** [comment]
@bartlettroscoe : Fine with me to get this merged. 

However, I have a bad feeling that this bug exists in the background on a platform we care about. We are treating the symptom and leaving the problem out there.

**Comment by srajama1** [comment]
@kyungjoo-kim - Your comment makes me worry even more :). Should we go to a different version of the compiler ?

**Comment by kyungjoo-kim** [comment]
1. I don't have a choice of compilers. The error depicted in #3417 does not include kokkoskernels test, which means that kokkoskernels gemm test passes and it includes the same code which is tested in a similar way. I don't understand why this happens only in Trilinos level tests and not from kokkoskernels unit tests. This is problematic.

2. Someone from ATDM may want to check if this is due to gcc 7.2 or POWER8. Currently this happens in that combination without enabling CUDA. @tjfulle also reports that he experienced the similar issue from clang and gcc 7.2 on his mac (mac is also the formal architecture that we support, I think). I might say that gcc 7.2 may cause this problem (PR tests include gcc 4.8.4 and 4.9.2 and intel compilers on intel platforms) but I am not sure.

**Comment by kddevin** [comment]
@kyungjoo-kim 's fix makes the problem go away on my mac; I also don't see any problems on waterman with an ATDM build.

Regarding cause:  I am not going to blame the compiler.  I think Kokkos has an array-out-of-bounds write in two of the four implementations of stride() in Kokkos_ViewMapping.hpp.  Indeed, in the original Kokkos-Kernels code, increasing the strides array from strides[2] to strides[3] also resolves the issue.

@kyungjoo-kim sanity-checked my findings.  I'll file a Kokkos bug report. 

No need to blame the compiler this time.  :)

**Comment by crtrott** [comment]
Oh my, I think Karen put her fingers on the wound: the strides array needs to be length 3 (rank+1). This is probably why this fails. And yes that interface is a bit silly. Maybe we should just change that internally in Kokkos. I.e. deprecate the old one which returns the total span as well in the array and make it only return rank values instead of rank+1. Also please use view.stride(r) instead of view.stride_r(). 

So the bug here is in KokkosKernels which uses a two short array for getting the strides, caused by a somewhat silly design decision in Kokkos (which if Kokkos had started under C++11 would probably have been avoided by using a std::array as parameter instead of a raw pointer). valgrind should have caught this btw. And so far we were just lucky that nothing important got overwritten on other compiler / platform combinations.

**Comment by kddevin** [comment]
Note that not all implementations of stride(int *s) fill s[rank].  Three do, two do not.

**Comment by mhoemmen** [comment]
@crtrott Please please deprecate that silly array output strides interface :D

**Comment by srajama1** [comment]
@crtrott : Thanks ! Consider my vote for fixing the Kokkos design as well. Does it matter if we use stride(r) or stride_r() ?

**Comment by kyungjoo-kim** [comment]
Yes.... the array stride interface which requires rank+1 size is totally non-intuitive. It is good that this is not a compiler issue.

**Pull request merged**
