### PR TITLE
Fix mingw template blas declaration

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by krcb** [comment]
This seems to be only needed in a specific circumstance; the VS9-12 compilers have no apparent problems compiling this code, nor does ICL15. Is this only needed for MINGW? If so, this should be done in a way that doesn't have side effects for other windows compilers.

**Comment by xantares** [comment]
The fix is only needed with msvc, gcc (mingw) is fine.

**Comment by jwillenbring** [comment]
Can the pull request be updated to be less general and target only the impacted compilers?

**Comment by xantares** [comment]
It is correct: it fixes only the code seen by mingw compilers (#if _WIN32), the code seen by msvc compiler remains the same (#if _MSVC_VER).

**Pull request closed without merging**
