### PR TITLE
Tpetra:  enable ReplaceDiagonal to work for CrsMatrix with overlapped row map

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/tpetra 

## Motivation

Tpetra's code to replace diagonal values assumed 1D row-wise distribution of the matrix.  It was incorrect when other distributions were used.   These changes fix replaceDiagonalCrsMatrix to remove the assumption of 1D row-wise matrix distribution.

These changes are needed to use Tpetra in Grafiki. Power-law matrices (e.g., social networks) perform better using 2D matrix distributions than 1D (row-wise) distributions.

## Related Issues

* Closes 
* Blocks  #8472 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Stakeholder Feedback

@ndellingwood @seheracer 
Needed by #8472 

## Testing

Added new test ReplaceDiagonalOverlapRowMap added to CrsMatrix_ReplaceDiagonal.cpp that creates 2D block-wise distribution of tridiagonal matrix and replace diagonal values with row's globalID.
Also implemented check in old ReplaceDiagonal test to ensure that non-diagonal matrix entries were not changed.

Tested on mac with 1,2,3,4,...,9,12,16 processors.

### CODE REVIEW

**Review by csiefer2 — COMMENTED** [review]
Looks good to me!

**Review by brian-kelley — APPROVED** [review]
LGTM

**Comment by kddevin** [comment]
Thanks, @csiefer2 and @brian-kelley !

**Comment by kddevin** [comment]
@prwolfe  @trilinos/framework Please can you tell me what this PR is waiting for?   It has one approving review and no change requests, and all the tests passed.  But it hasn't given me the merge button.  Thanks!

**Comment by jwillenbring** [comment]
@kddevin The Autotester needs to verify the inspection in its next pass. Things are backed up and we have had to decrease the frequency of the Autotester running, and the number of concurrent jobs due to GitHub limitations. It should eventually correct itself.

**Comment by kddevin** [comment]
@jmwille. Thanks!

**Pull request merged**
