### PR TITLE
Tacho fix when kokkos bound check 

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
This fixes the issue #2439

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe 

The auto tester does not test the debug build but I checked it on my workstation. Am I good to merge this PR ?

**Comment by bartlettroscoe** [comment]
> The auto tester does not test the debug build but I checked it on my workstation. Am I good to merge this PR ?

@kyungjoo-kim, where a) you able to reproduce the failures on your local machine first, then update the code and verify that the tests passed?  Or did b) you just make specualtive changes that you thought would fix the tests?  If the answer is 'a', then go ahead and merge and then I will check again after everyone says that these errors are fixed.  If the answer is 'b', then you can merge in my PR branch listed at #2440 into your **local only** branch on your local repo and the run the same build I described in #2439.  Make sense?

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe 

Yes a) I reproduced the failures and tests passed.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim, thanks for addressing this so quickly!

**Pull request merged**
