### PR TITLE
Xpetra: PR to close #6082 and #6765

### LINKED ISSUE #6082: MueLu:  Potential typing mistake in BelosXpetraStatusTestGenResSubNorm (edited)
## Bug Report
@trilinos/muelu 
@tawiesn 

### Description
There is, from time to time, a seg fault in file [BelosXpetraStatusTestGenResSubNorm.hpp](https://github.com/trilinos/Trilinos/blob/develop/packages/muelu/adapters/belos/BelosXpetraStatusTestGenResSubNorm.hpp) in the block of lines 289-306:

```
    for (; p2<curLSIdx_.end(); ++p2) {
      // Check if this index is valid
      if (*p != -1) {
        // Check if any of the residuals are larger than the tolerance.
        if (testvector_[ *p2 ] > tolerance_) {
          // do nothing.
        } else if (testvector_[ *p2 ] == Teuchos::ScalarTraits<Scalar>::magnitude(Teuchos::ScalarTraits<Scalar>::zero())) {
          reset();
        } else if (testvector_[ *p2 ] <= tolerance_) {
          ind_[have] = *p2;
          have++;
        } else {
          // Throw an std::exception if a NaN is found.
          status_ = Failed;
          TEUCHOS_TEST_FOR_EXCEPTION(true,StatusTestError,"StatusTestGenResSubNorm::checkStatus(): NaN has been detected.");
        }
      }
    }
```
It seems that the seg fault is due to `testvector_[ *p2 ]` and that `*p2` is equal to `-1`.

I think that the test `if (*p != -1)` should be replaced by `if (*p2 != -1)` as [BelosXpetraStatusTestGenResSubNorm.hpp](https://github.com/trilinos/Trilinos/blob/develop/packages/muelu/adapters/belos/BelosXpetraStatusTestGenResSubNorm.hpp) is a template specialization of [BelosStatusTestGenResSubNorm.hpp](https://github.com/trilinos/Trilinos/blob/develop/packages/belos/src/BelosStatusTestGenResSubNorm.hpp) where the test is indeed `if (*p2 != -1)`.

### PR DESCRIPTION
**Pull request by kliegeois**
@trilinos/xpetra 
@trilinos/muelu 

## Motivation

The motivation behind this PR is to resolve issues #6765 and #6082.

Issue #6082 is resolved by correcting the typo.

Issue #6765 is resolved by computing the static size required to store the merged blocked crs matrix.
To do so, the implementation relies on the member function getNumEntriesInLocalRow which was not fully implemented yet.
The provided implementation of `getNumEntriesInLocalRow` relies on `getMapIndexForGID` to access the block id of a global id.

Therefore, this PR provides:
- An implementation of `getNumEntriesInLocalRow` and `getNumEntriesInGlobalRow` which supports both Thyra and Xpetra mode.
- The computation of the required memory which has to be allocated to store the merged blocked crs matrix.

## Testing

This branch has been tested on the Blake system.

### CODE REVIEW

**Comment by kliegeois** [comment]
@mhoemmen wrote:
> Are there any tests already for either of these groups of changes? It's a bit surprising that the MueLu Belos adapter ever actually worked, if the loop index was completely wrong like that. I don't know enough about @trilinos/xpetra to judge the second set of changes, though I'm happy to see you get the right entry counts. Do these changes need to go in urgently? If not, I'd rather wait to get an Xpetra developer's opinion on them. Thanks!

There are some tests for the second group of changes, i.e. the changes related to the merge. 
I am pretty sure that the MueLu Belos adapter (BelosXpetraStatusTestGenResSubNorm.hpp) is not tested by the AutoTester as the .hpp file is only included by one .cpp file packages/muelu/research/tawiesn/crada/Driver.cpp .

Concerning the second set of changes, there is still one issue when nesting blocked crs matrices without MPI (this raised the timeout) but I am on it.

This PR does not need to go in urgently. However, I will need it "soon" to create a tag of trilinos:develop (instead of using a forked version with modifications) for my code which is built against trilinos.

**Comment by mhoemmen** [comment]
@kliegeois wrote:
> I am pretty sure that the MueLu Belos adapter (BelosXpetraStatusTestGenResSubNorm.hpp) is not tested by the AutoTester as the .hpp file is only included by one .cpp file packages/muelu/research/tawiesn/crada/Driver.cpp .

If your changes are using it, would you consider please adding a unit test?  I do wish MueLu had a test for it; it's painful to have to build all of Stokhos to exercise a MueLu-only thing.

**Comment by kliegeois** [comment]
@mhoemmen  wrote:
> If your changes are using it, would you consider please adding a unit test? I do wish MueLu had a test for it; it's painful to have to build all of Stokhos to exercise a MueLu-only thing.

My changes are not using it directly, it is used by my software which is built against Trilinos.
Stokhos will not have to be built to exercise a MueLu-only thing.
However, I can try to include a test if you want.

**Comment by mhoemmen** [comment]
@kliegeois wrote:
> However, I can try to include a test if you want.

Yes, please :-)

**Comment by kliegeois** [comment]
@mhoemmen wrote:
> Yes, please :-)

No problem! I just relaunch the AutoTester to confirm that now it works and then, I add the test.

**Comment by mhoemmen** [comment]
@kliegeois I really appreciate it -- I don't mean to make more work for you; it's just that this is our only chance to add a test for something that was completely untested before.

**Comment by kliegeois** [comment]
I do not understand why it is failing.
Nevertheless, the test requested by @mhoemmen is not yet ready so it is not an issue if the last jobs failed.

**Comment by mhoemmen** [comment]
@trilinos/framework @prwolfe It looks like something went wrong with that last Python build:
```
NODE_OWNER_EMAIL = ceeadmin@sandia.gov
SEMS_GIT_LOCAL_PYTHON_VERSION = 2.7.5
NODE_NAME = tr-test-8-trilinos
SEMS_NINJA_FORTRAN_VERSION = 1.7.2
SSH_CLIENT = 205.137.81.17 44710 22
JENKINS_URL = https://ascic-jenkins.sandia.gov/
LOGNAME = trilinos
NODE_LABELS = tr-test-8-trilinos trilinos-CAPACITY trilinos-any trilinos-cloud-32 trilinos_cloud_32_node_8
PATH = /projects/sierra/linux_rh7/install/Python/3.6.3/bin:/projects/sierra/linux_rh7/install/Python/extrasbin:/projects/sems/install/rhel7-x86_64/atdm/utility/ninja_fortran/1.7.2/sbin:/projects/sems/install/rhel7-x86_64/atdm/utility/ninja_fortran/1.7.2/bin:/projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.10.3/sbin:/projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.10.3/bin:/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/bin:/projects/sems/install/rhel7-x86_64/sems/utility/git/2.10.1/sbin:/projects/sems/install/rhel7-x86_64/sems/utility/git/2.10.1/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/trilinos/.local/bin:/ascldap/users/trilinos/bin
SEMS_NINJA_FORTRAN_LOCAL_PYTHON_VERSION = 2.7.5
GIT_PREVIOUS_SUCCESSFUL_COMMIT = fdfd85e611d64d7cd6baa38d1db0b0b710541950
no_proxy = localhost,localnets,127.0.0.1,169.254.0.0/16,forge.sandia.gov
CC = gcc
SEMS_CMAKE_LOCAL_COMPILER_VERSION = 4.8.5
JOB_OWNER_EMAIL = prwolfe@sandia.gov
PULLREQUEST_CDASH_TRACK = Pull Request
BUILD_ID = 1682
JOB_COOWNERS_EMAILS = prwolfe@sandia.gov,trilinos@sandia.gov
GIT_URL = https://github.com/trilinos/Trilinos
SEMS_GCC_LOCAL_COMPILER_VERSION = 4.8.5
LOADEDMODULES = sems-env:sems-git/2.10.1:sems-gcc/7.2.0:sems-cmake/3.10.3:atdm-env:atdm-ninja_fortran/1.7.2
SEMS_COMPILER_VERSION = 7.2.0
Currently Loaded Modulefiles:
  1) sems-env                   4) sems-cmake/3.10.3
  2) sems-git/2.10.1            5) atdm-env
  3) sems-gcc/7.2.0             6) atdm-ninja_fortran/1.7.2
Build name               = PR-6834-test-Trilinos_pullrequest_python_3-1682
Cur dir                  = /scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/TFW_testing_single_configure_prototype
Source dir               = /scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/Trilinos
Binary dir               = /scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/pull_request_test
Parallel level           = 20
skip_by_parts_submit     = OFF
skip_single_submit       = ON
skip_update_step         = ON
skip_upload_config_files = OFF
skip_clean_build_dir     = ON
Subproject count         = 53
Dashboard model          = Experimental
Dashboard track          = Pull Request
Running configuration:
/projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.10.3/bin/cmake 
  -C "/scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/Trilinos/cmake/std/PullRequestLinuxPython3.cmake"
  -C "/scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/packageEnables.cmake"
  -DTrilinos_ENABLE_TESTS:BOOL=ON
  -DTrilinos_PARALLEL_LINK_JOBS_LIMIT:STRING=2
  -G "Ninja"
  /scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/Trilinos
CTEST_DROP_LOCATION = /cdash/submit.php?project=Trilinos
CDash URL1 = https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=tr-test-8.novalocal&field2=buildname&compare2=61&value2=PR-6834-test-Trilinos_pullrequest_python_3-1682&field3=buildstamp&compare3=61&value3=20200219-1325-Pull Request
CDash URL2 = https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=0&filtercombine=and&field1=buildname&compare1=61&value1=PR-6834-test-Trilinos_pullrequest_python_3-1682&field2=buildstamp&compare2=61&value2=20200219-1325-Pull Request
CDash URL3 = https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=0&filtercombine=and&field1=buildname&compare1=61&value1=PR-6834-test-Trilinos_pullrequest_python_3-1682&field2=buildstamp&compare2=61&value2=20200219-1325-Pull Request
Starting configure step.
   Each . represents 1024 bytes of output
    ...................... Size of output: 21K
configure submit error = 0
Configure suceeded.
Starting build step.
   Each symbol represents 1024 bytes of output.
    . Size of output: 0K
Build succeeded.
build submit error = 0
Starting testing step.
Unable to find required file: CMND_PATH-NOTFOUND
Unable to find required file: CMND_PATH-NOTFOUND
Unable to find required file: CMND_PATH-NOTFOUND
Unable to find required file: CMND_PATH-NOTFOUND
Unable to find required file: CMND_PATH-NOTFOUND
Unable to find required file: CMND_PATH-NOTFOUND
CMake Error at /scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/TFW_testing_single_configure_prototype/simple_testing.cmake:213 (message):
  Test failed with error -1

test submit error = 0
File upload submit error = 0
SEMS_CMAKE_VERSION = 3.10.3
HISTCONTROL = ignoredups
SERIAL_CXX = g++
PWD = /scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3
JENKINS_SERVER_COOKIE = 248910a9cd8de38c
BUILD_DISPLAY_NAME = #1682
PULLREQUESTNUM = 6834

==========================================================================================
None
PULLREQUEST_CDASH_TRACK is set. Setting CDASH_TRACK=Pull Request
Enabled packages:
-- Setting Trilinos_ENABLE_TrilinosFrameworkTests = ON

Set CWD = /scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/TFW_testing_single_configure_prototype
Traceback (most recent call last):
File "/scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/Trilinos/cmake/std/PullRequestLinuxDriverTest.py", line 590, in 
returnValue = run()
File "/scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/Trilinos/cmake/std/PullRequestLinuxDriverTest.py", line 584, in run
'package_subproject_list.cmake'])
File "/projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ctest', '-S', 'simple_testing.cmake', '-Dbuild_name=PR-6834-test-Trilinos_pullrequest_python_3-1682', '-Dskip_by_parts_submit=OFF', '-Dskip_update_step=ON', '-Ddashboard_model=Experimental', '-Ddashboard_track=Pull Request', '-DPARALLEL_LEVEL=20', '-Dbuild_dir=/scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/pull_request_test', '-Dconfigure_script=/scratch/trilinos/jenkins/tr-test-8/workspace/trilinos-folder/Trilinos_pullrequest_python_3/Trilinos/cmake/std/PullRequestLinuxPython3.cmake', '-Dpackage_enables=../packageEnables.cmake', '-Dsubprojects_file=../TFW_single_configure_support_scripts/package_subproject_list.cmake']' returned non-zero exit status 255
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

**Comment by prwolfe** [comment]
@mhoemmen - this is odd
- this looks like the python executable is missing, but I looked and it is definitely in place and executable.  I did some maintenance on the machine this morning, but it should not have affected this at all.
-  The errors extend back before I did that maintenance work and that makes even less sense. I will dig

**Comment by prwolfe** [comment]
I reconfigured in the exact same Jenkins workspace and it resolved the issue.  I think this may have hit just as I was shutting the machine down for maintenance and that gave it fits.  My apologies.

**Comment by kliegeois** [comment]
Thanks for your inputs @mhoemmen  and @prwolfe !

@mhoemmen would it be fine for you if the test is included in the following PR?
It would be easier for me as the next PR will include an interface aggregation factory for, for instance, contact problems. This is based on the work of the PhD thesis of @tawiesn. I would like to add a test for that interface aggregation factory and this test will require a GMRES solve with a blocked crs matrix. Adding a stopping criteria based on the norm of the residual of one particular block would be super easy on that test.

**Comment by mhoemmen** [comment]
@kliegeois wrote:
> would it be fine for you if the test is included in the following PR?

Sure, that's fine -- I just want to make sure that we don't forget.

@prwolfe thanks for fixing this! : - D

**Comment by kliegeois** [comment]
@mhoemmen I do not need it right away, I can wait for the review of @cgcgcg or @csiefer2!

**Pull request merged**
