### PR TITLE
Epetra: Add test for #3192 (Epetra64 issue)

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/epetra @maherou 

## Description

Add a test for #3192.  The test fails, so I'm marking this PR as a WIP.

## Related Issues

* Part of #3192

## How Has This Been Tested?

Linux, GCC, OpenMPI.

### CODE REVIEW

**Comment by jwillenbring** [comment]
@mhoemmen @william76 

Unfortunately, leaving PR's open causes a measure of trouble for PR testing. I am going to close this PR. Perhaps we can capture this information in an issue or in some other way?

**Comment by mhoemmen** [comment]
@jwillenbring Epetra64 has zero support.  I think we should feel comfortable deprecating and removing it.

**Comment by jwillenbring** [comment]
@mhoemmen 

We should check with @kddevin and maybe others before deprecating Epetra64.

**Comment by mhoemmen** [comment]
@jwillenbring I didn't say I would do it, just that I have no objections.  Somebody who owns it (I don't) must make an executive decision.

**Comment by jwillenbring** [comment]
@mhoemmen Understood. I was mostly adding a useful @ mention more than pushing back against you.

**Pull request closed without merging**
