### PR TITLE
Xpetra: Fixing typo

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA 77c85c3

### CODE REVIEW

**Comment by csiefer2** [comment]
Stochastic STK fails ftw @trilinos/framework

**Comment by alanw0** [comment]
@csiefer2 what do you mean by 'stochastic STK fails ftw' ?

**Comment by prwolfe** [comment]
> @csiefer2 what do you mean by 'stochastic STK fails ftw' ?

I think he is seeing the same issues on intel builds I did. There is a PR to turn that off while the team looks for the cause ( #5814 )

**Comment by prwolfe** [comment]
#5814 has merged - I am going to retest this.

**Pull request merged**
