### PR TITLE
zoltan2: Workaround c++20 deprecation of implicit this capture via [=].

### PR DESCRIPTION
**Pull request by vbrunini**
@trilinos/<teamName>

### CODE REVIEW

**Comment by vbrunini** [comment]
@trilinos/zoltan2

**Review by ndellingwood — COMMENTED** [review]
@vbrunini just a question (I'm not a zoltan2 dev), but can the capture just be changed to capture by reference `[&]` to avoid the if-else guards?

**Comment by vbrunini** [comment]
> @vbrunini just a question (I'm not a zoltan2 dev), but can the capture just be changed to capture by reference `[&]` to avoid the if-else guards?

That would also prevent the deprecation warning yes. I have not read through the surrounding code to determine if the semantic change to capturing the variables other than "this" by reference would still be correct though.

**Comment by jhux2** [comment]
@trilinos/zoltan2 This looks fine to me.  Adding a label to get it tested.

**Comment by egboman** [comment]
Looks good to me. Thanks.

**Review by jhux2 — APPROVED** [review]
Approving (@egboman already signed off on this)

**Pull request merged**
