### PR TITLE
Pamgen: Exposing some innards

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA cd72474

### CODE REVIEW

**Comment by rppawlo** [comment]
Have these changes been pushed to the actual pamgen repo? pamgen is snapshotted in with stk snapshots and theses changes will be overwritten on the next update.

**Comment by csiefer2** [comment]
@rppawlo Since when?

**Comment by rppawlo** [comment]
@csiefer2 - sorry i misread percept. my mistake.

**Comment by csiefer2** [comment]
@rppawlo Whew.  You were scaring me :)

**Comment by alanw0** [comment]
Hi guys, the occurrence of 'stk' made this get through my filters into my inbox... Like you've now concluded, pamgen doesn't come in with stk, but percept often does. stk and percept both live in the sierra repo so we often snapshot them into trilinos together. As for pamgen, I'm not as familiar with its origins, I thought that Dave Hensiger wrote it. Greg Sjaardema (@gsjaardema ) might be more familiar with it since there is some wrapper code in IOSS related to it.

**Comment by csiefer2** [comment]
Yeah, Dave did pamgen and it's been primarily developed in Trilinos since it got yanked out of alegra.

**Pull request merged**
