### PR TITLE
Tacho: Fix compiling with SYCL

### PR DESCRIPTION
**Pull request by masterleinad**
@trilinos/tacho
## Motivation
This should fix compiling with `SYCL` using `Tacho`.

## Related Issues
* Related to #12428

### CODE REVIEW

**Comment by iyamazaki** [comment]
Thank you @masterleinad. All these changes look good with me.

**Comment by iyamazaki** [comment]
Hi, @masterleinad. The failed tests may be due to my previous [PR](https://github.com/trilinos/Trilinos/pull/12496)? Maybe, I needed parentheses around those?

**Comment by masterleinad** [comment]
> Hi, @masterleinad. The failed tests may be due to my previous [PR](https://github.com/trilinos/Trilinos/pull/12496)? Maybe, I needed parentheses around those?

Can you copy the error/failing test here? I don't have access to `CDash`.

**Comment by masterleinad** [comment]
> Here is an example of the error: [...]

This looks like I need to fix it here.

**Comment by masterleinad** [comment]
Should be fixed in https://github.com/trilinos/Trilinos/pull/12577/commits/197060042b12c342fb71eff72b7d0366a4087b0a.

**Comment by masterleinad** [comment]
@iyamazaki Can you reapprove/reinspect?

**Review by iyamazaki — APPROVED** [review]
Thank you, @masterleinad!!

**Pull request merged**
