### PR TITLE
KokkosKernels: Fix for spgemm unit_test mkl macro

### PR DESCRIPTION
**Pull request by ndellingwood**
Address Trilinos issue #3438, incorporates part of fix from
PR kokkos/kokkos-kernels#290

@trillinos/kokkos-kernels

### CODE REVIEW

**Comment by ndellingwood** [comment]
@kyungjoo-kim @srajama1 this patch is the relevant part from the fix from kokkos-kernels develop branch for similar issue. 

Other interested parties: @bartlettroscoe @fryeguy52

**Comment by srajama1** [comment]
Please apply a patch in Trilinos.

**Comment by ndellingwood** [comment]
The MKL issues are resolved by the PR but the CUSPARSE problems remain; it may be that the unit test may need to be altered to better guard when CUSPARSE is / is not enabled, unless there is some configure issue resulting in a macro being incorrectly set. 
@kyungjoo-kim @srajama1 what are your thoughts on this, and should this PR include that resolution as well or simply merge in as a fix for the MKL problem (after autotester results pass) and issue separate PR for CUSPARSE stuff?
Here's link to a bit of additional info I extracted from the tests - [issue 3438 comment](https://github.com/trilinos/Trilinos/issues/3438#issuecomment-421181287)

**Comment by kyungjoo-kim** [comment]
let me try this at home.

**Comment by srajama1** [comment]
@bartlettroscoe - I will wait for @kyungjoo-kim to yes or now.

**Comment by ndellingwood** [comment]
@kyungjoo-kim - Spoke with @srajama1 and we're going ahead with the merge of this PR which partially addresses issues #3438. Did you get a chance to look at the cusparse part? We can follow up discussion in the issue and file a PR to deal with that part separately.

**Pull request merged**
