### PR TITLE
Fixed lapack and blas lib locations.

### PR DESCRIPTION
**Pull request by bbraunj**
@trilinos/EM-Plasma

## Description

Changed `Trilinos/cmake/std/atdm/sems-rhel7/environment.sh` lines that include:

```
export ATDM_CONFIG_LAPACK_LIBS="-L${LAPACK_ROOT};-llapack"
export ATDM_CONFIG_BLAS_LIBS="-L${BLAS_ROOT}/lib;-lblas" 
```

to:

```
export ATDM_CONFIG_LAPACK_LIBS="/usr/lib64/liblapack.so.3"
export ATDM_CONFIG_BLAS_LIBS="/usr/lib64/libblas.so.3"
```

## Motivation and Context

Ran into an issue where Trilinos would not build successfully on a RHEL7 machine because it could not find the `lapack` and `blas` libraries.  This points to the right library files.

## How Has This Been Tested?

The configure command that was used:

```
cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake,cmake/std/atdm/apps/empire/EMPIRETrilinosEnables.cmake \
  -DCMAKE_INSTALL_PREFIX=/home/josbrau/Documents/aaa/Trilinos_Install \
  /home/josbrau/Documents/aaa/Trilinos_Src
```

The build command that was used:

```
ninja -j 8
```
 

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by bbraunj** [comment]
@bartlettroscoe This won't let me assign a reviewer, but here is the pull request.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> In general, we don't want to hard-code paths like this. Is this an issue that affects all RHEL7 machines? Also, who are you?

This is specifically for SNL COE RHEL7 machines and this is the system BLAS/LAPACK on these machines.  For consistency, you want to hard-code paths to specific systems.  This is the whole reason for the ATDM Trilinos configuration scripts.

**Comment by bartlettroscoe** [comment]
On my 'crf450' machine (regular COE RHEL6 machine):

```
[rabartl@crf450 ~ (crf450)]$ ls /usr/lib64/libblas.so.3 /usr/lib64/liblapack.so.3
/usr/lib64/libblas.so.3  /usr/lib64/liblapack.so.3
```

On 'ceerws1113' (CEE RHEL6 machine):

```
[rabartl@ceerws1113 sparc (master)]$ ls /usr/lib64/libblas.so.3 /usr/lib64/liblapack.so.3
/usr/lib64/libblas.so.3  /usr/lib64/liblapack.so.3
```

On 'ascicgpu15' (same as used for the ATDM Trilinos 'sems-rhel7' builds):

```
[rabartl@ascicgpu15 ~ (cee-lan)]$  ls /usr/lib64/libblas.so.3 /usr/lib64/liblapack.so.3
/usr/lib64/libblas.so.3  /usr/lib64/liblapack.so.3
```

On 'cortado' (used for the EMPIRE Trilinos integration testing builds):

```
[rabartl@cortado ~ (cordado)]$  ls /usr/lib64/libblas.so.3 /usr/lib64/liblapack.so.3
/usr/lib64/libblas.so.3  /usr/lib64/liblapack.so.3
```

See, the same everywhere.

Let me pull this branch and do a quick build to make sure this is working and then I will let merge.

**Comment by dridzal** [comment]
>  Ran into an issue where Trilinos would not build successfully on a RHEL7 machine because it could not find the lapack and blas libraries. This points to the right library files.

This contradicts

>  This is specifically for SNL COE RHEL7 machines and this is the system BLAS/LAPACK on these machines.

If these machines are all "the same" then the problem should not have occurred in the first place.  This goes back to the misconception that the environments can be easily replicated on all RHEL6 and RHEL7 machines.  Why did cmake not find the libraries?  What is the difference between this specific machine and all other RHEL7 machines?

**Comment by krcb** [comment]
We need to make sure that this works correctly with the apps. In particular, that MKL is still found correctly.

**Comment by bartlettroscoe** [comment]
@dridzal,

> If these machines are all "the same" then the problem should not have occurred in the first place. 

Actually, what happens is that people manually put in symlinks `liblbas.so` and `liblapack.so` to point to these so that CMake can in fact find them.  But to do that you have to have sudo.  You can argue that the RHEL6 and RHEL7 BLAS and LAPACK install packages are broken but it is what is.  Making this change avoids having to do that.

I will state it again, but for enhanced reproduciblilty you absolutely want to hard-code paths so that the LAPACK picked up by one user on one machine is the same for another use on another machine.  (I wish SEMS would have just built BLAS and LAPACK but they did not so here we are.)  If this does not make sense then I am happy to discuss this.

Note, this does not impact the default Trilinos configuration, just the ATDM Trilinos configurations.

**Comment by bartlettroscoe** [comment]
@krcb said:

> We need to make sure that this works correctly with the apps. In particular, that MKL is still found correctly.

The SEMS configurations don't use MKL, they use the system BLAS.  They have to because downstream TPLs like SuperLU where built with the System BLAS/LAPACK and not the MKL.  

For the Spack builds being developed, we can consider some optimized builds that use MKL but not with SEMS.

**Comment by bartlettroscoe** [comment]
@bartlettroscoe said:

> The SEMS configurations don't use MKL, they use the system BLAS. They have to because downstream TPLs like SuperLU where built with the System BLAS/LAPACK and not the MKL.

To be more correct, the ATDM Trilinos 'sems-rhely' **gnu** builds don't use MKL (they use the default system blass/lapcak) but the **intel** configurations do.  Look for yourself, for example, at:

* https://github.com/trilinos/Trilinos/blob/78d1b0805dd1c77a9a53ca6631253d67b6f8a18e/cmake/std/atdm/sems-rhel7/environment.sh#L172

Any other concerns?

I am testing right now on 'ascicgpu15' and if that comes back clean, I will merge this.

**Comment by bartlettroscoe** [comment]
On 'ascicgpu15':

```
$ /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CTEST_S/

$ ./ctest-s-local-test-driver.sh \
    sems-rhel7-clang-3.9.0-openmp-complex-shared-release-debug \
    sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug
```

Will point to results on CDash once complete.

**Comment by bartlettroscoe** [comment]
For some history the old configuration was copied from EMPIRE's Trilinos configuration almost 2 years ago and as @jmgate and I saw, it was not picking up BLAS and LAPACK from `/usr/lib64/atlas`, it was picking it up from `/usr/lib64/` using manually added symlinks on the various machines.  This change just removes the need for manually creating symlinks `/usr/lib64/libblas.so` and `/usr/lib64/liblapack.so`, the exactly same same libs `/usr/lib64/libblas.so.3` and `/usr/lib64/liblapack.so.3` are being used on these systems.

**Comment by bbraunj** [comment]
@mhoemmen I am @jmgate's intern. I am working on the EMPIRE team to improve some software/testing infrastructure.

**Comment by bartlettroscoe** [comment]
On 'ascicgpu15' I ran:

```
$ /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CTEST_S/

$ ./ctest-s-local-test-driver.sh \
    sems-rhel7-clang-3.9.0-openmp-complex-shared-release-debug \
    sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug


***
*** ./ctest-s-local-test-driver.sh
***

ATDM_TRILINOS_DIR = '/scratch/rabartl/Trilinos.base/Trilinos'

Load some env to get python, cmake, etc ...

Hostname 'ascicgpu15' matches known ATDM host 'sems-rhel7' and system 'sems-rhel7'
Setting compiler and build options for build-name 'default'
Using SEMS RHEL7 compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL

Running builds:
    sems-rhel7-clang-3.9.0-openmp-complex-shared-release-debug
    sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug

Running Jenkins driver Trilinos-atdm-sems-rhel7-clang-3.9.0-openmp-complex-shared-release-debug.sh ...

Creating directory: Trilinos-atdm-sems-rhel7-clang-3.9.0-openmp-complex-shared-release-debug
Creating directory: SRC_AND_BUILD

real    40m54.837s
user    599m3.435s
sys     60m34.246s

Running Jenkins driver Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug.sh ...

Creating directory: Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug
Creating directory: SRC_AND_BUILD

real    49m47.116s
user    734m38.027s
sys     87m16.111s
```

which posted to the CDash builds:

* [Trilinos-atdm-sems-rhel7-clang-3.9.0-openmp-complex-shared-release-debug-exp](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=4713370)
* [Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug-exp](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=4713422)

The latter showed 1 failing test:

* [Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4](https://testing-dev.sandia.gov/cdash/testDetails.php?test=71340082&build=4713424)

but we know about that one from #3585.

Therefore, this is clean and I am going to go ahead and merge this PR.

**Comment by mhoemmen** [comment]
@bbraunj Welcome!  Sorry to be a bit suspicious -- we've gotten spam PRs before and need to watch out for worse.

**Comment by bbraunj** [comment]
@mhoemmen No problem! I completely understand.

**Pull request merged**
