### PR TITLE
Patch SuperLU_Dist interface for version 5.0

### PR DESCRIPTION
**Pull request by amklinv**
Warning: This almost certainly breaks the Doxygen for these interfaces.

### CODE REVIEW

**Comment by amklinv** [comment]
@BarrySmith @jwillenbring @jdbooth @srajama1 @trilinos/amesos2

Referencing the appropriate parties...

**Comment by jwillenbring** [comment]
I assigned Siva to this pull request. Feel free to delegate as necessary.

**Comment by srajama1** [comment]
Alicia : I am on vacation and won't have time to get to this quickly. Can you make sure checkin tests pass  (or muelu tests pass, which will ensure the primary user of Amesos2 will work) and commit it. Also adding @jdbooth to see if he can help. Please coordinate among you and Josh.

**Comment by jdbooth** [comment]
I will take a look at the pull request tonight and test.  
 If this request is only for the type structs, I think we should wait see if Sherry add the version Macro (see other open issues).  
We have had  trouble with CMake test in past and we are patching for a version of SuperLU_DIST that final.

**Comment by jdbooth** [comment]
commit 7e355fb3be7dd3c665e203846bccd8f861c43386
Fixes the issues this patch was for, but with out having to use the cmake test.
In place use new superlu_dist version macro.
have been tested by myself v (4.1,4.2,5.0) and @amklinv

**Pull request closed without merging**
