### PR TITLE
Testing: rocketman: speed up nightly testing

### PR DESCRIPTION
**Pull request by jhux2**
Disable avatar testing.
Merge two cronjobs to eliminate gap between testing (hopefully).

---
This change is [Reviewable](https://reviewable.io/reviews/trilinos/trilinos/6173)

### CODE REVIEW

**Comment by jhux2** [comment]
@trilinos/framework @prwolfe Not sure why this is failing.  It's a change to `Trilinos/cmake/ctest/drivers` only.

**Comment by cgcgcg** [comment]
@trilinos/framework Looks like the intel build is broken.

**Comment by prwolfe** [comment]
Looks like proxy settings are changing a bit and this was the only job not on the new pattern. I changed that and am re-trying the run.

**Comment by jhux2** [comment]
> Looks like proxy settings are changing a bit and this was the only job not on the new pattern. I changed that and am re-trying the run.

@prwolfe Thanks, that fixed it!

**Pull request merged**
