### PR TITLE
Panzer: fix interface conditions

### PR DESCRIPTION
**Pull request by rppawlo**
@trilinos/<teamName>

### CODE REVIEW

**Review by bathmatt — APPROVED** [review]

**Comment by bathmatt** [comment]
@rppawlo sorry, i'm sure that was me who f'ed this up :(

**Comment by rppawlo** [comment]
@bathmatt - no worries! I reviewed it and missed it too. 2D now passes but 3D is still failing. Getting incorrect error rates. Still trying to figure that out. I replaced all uses in panzer of OverwriteAll with ReadWrite but that didn't fix it, so need to start looking in other places.

**Comment by bathmatt** [comment]
trying a retest, since this failed for some unknown reason

**Comment by e10harvey** [comment]
This is fixed. I will let the developer know that they should create a copy of the python-3 job.

**Pull request merged**
