### PR TITLE
Ifpack2: Fix bugs in RILUK that not clearing old matrix values in reuse case and seg fault with empty matrix

### PR DESCRIPTION
**Pull request by vqd8a**
@trilinos/ifpack2

## Motivation

This PR is to fix two bugs reported by @vbrunini: (i) the RILUK preconditioner not taking the new matrix values when preconditioner->compute() is called in the reuse case; (ii) seg fault when dealing with empty matrix

## Testing

Tests were performed on ```white``` with CTest. The two changes were confirmed fixing the bugs by @vbrunini .

### CODE REVIEW

**Comment by vqd8a** [comment]
Cross-referencing matching kokkos-kernels PR kokkos/kokkos-kernels#871

**Comment by ndellingwood** [comment]
Changes look good, should wait for #8490 to be merged to prevent clobbering the kokkos-kernels changes

**Review by jhux2 — APPROVED** [review]
@vqd8a The Ifpack2 changes look fine to me.  I didn't review the KokkosKernels change.

**Comment by vqd8a** [comment]
@jhux2 Thanks for approving. I already had the KokkosKernels change in the matching PR https://github.com/kokkos/kokkos-kernels/pull/871. This KK PR was reviewed and merged to the KK ```develop``` branch . 
However, @ndellingwood told me this Trilinos PR should wait for the Kokkos release 3.3.1 PR merged in first.

**Comment by ndellingwood** [comment]
@vqd8a @vbrunini we are making progress on a blocker preventing merge of #8490, once resolved we can get this merged in, sorry for the delay

**Comment by crtrott** [comment]
#8490 should hopefully now pass I pushed the fix we needed (largely too much stuff got instantiated which resulted in up to 1GB binary size increase).

**Comment by ndellingwood** [comment]
PR #8490 is merged, adding the RETEST and AUTOMERGE labels

**Review by ndellingwood — APPROVED** [review]
lgtm, kokkos-kernels changes already merged to develop branch of the repo

**Comment by vqd8a** [comment]
@vbrunini The fixes were in. Please let me know if you need anything else. Thanks.

**Comment by vbrunini** [comment]
Thanks!

**Pull request merged**
