### PR TITLE
Fix msvc compilation

### PR DESCRIPTION
**Pull request by ViNN280801**
# Motivation

This change addresses a compilation issue under MSVC in Visual Studio 2022. The compiler reports a C2535 error indicating that two overloaded functions are identical, despite having different `enable_if` conditions. Adding additional conditions to the `enable_if` clauses ensures that the MSVC compiler can distinguish between the two overloaded functions.

# Testing

The changes have been tested locally to ensure that they resolve the compilation issue without affecting the functionality of the code.

# Request for Improved Windows Support

During the process of compiling Trilinos on Windows, I encountered numerous issues related to the build system and compatibility with MSVC in Visual Studio 2022. These challenges included but were not limited to:

- Overloaded functions causing compilation errors under MSVC.
- Long file path issues that Windows doesn't support (260 symbols max), for exaple path: `C:\Users\vladislavsemykin\Downloads\Trilinos\Trilinos\build\packages\kokkos-kernels\sparse\eti\generated_specializations_cpp\gauss_seidel_symbolic\Sparse_gauss_seidel_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_SERIAL_MEMSPACE_HOSTSPACE.cpp`
- and other issues, even "syntax errors" (though I compile it in C++20 and C17 (all the projects)).

Given the increasing use of Windows as a development platform, I kindly request the Trilinos development team to consider making the build process more accessible and robust for Windows users. Enhancements such as detailed Windows-specific build instructions, automated scripts to handle common issues, and pre-configured environment setups would greatly benefit the community.

Thank you for considering this request, and please let me know if there is anything I can do to assist with improving the Windows build process.

# "Syntax errors" under MSVC

```
31>C:<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(33,107): error C2146: syntax error: missing ')' before identifier 'A'
31>C:<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(33,107): error C3646: 'A': unknown override specifier
31>C:<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(33,108): error C2988: unrecognizable template declaration/definition
31>C:<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(33,108): error C2059: syntax error: ','
31>C:<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(34,91): error C2059: syntax error: ')'
31>C:<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(34,93): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
31>C:<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(69,107): error C2146: syntax error: missing ')' before identifier 'A'
```

### CODE REVIEW

**Comment by cgcgcg** [comment]
@ViNN280801 Thank you for your PR. Would you mind splitting off the Kokkos changes and opening a PR against https://github.com/kokkos/kokkos instead? The ShyLU/Tacho changes can stay in this PR.

**Comment by ViNN280801** [comment]
@cgcgcg, yes, of course I will split, thanks

**Comment by ViNN280801** [comment]
I compiled Kokkos properly with MSVC, its version of the functions that I corrected from `core/src/Kokkos_View.hpp` differs. In Trilinos repo elder functions `operator()` and `access()` as I see:

### Kokkos:latest. Example of the `access()`:

```cpp
  template <typename I0, typename I1, typename... Is>
  KOKKOS_FORCEINLINE_FUNCTION std::enable_if_t<
      (Kokkos::Impl::always_true<I0, I1, Is...>::value && (2 == rank) &&
       is_default_map &&
       (is_layout_left || is_layout_right || is_layout_stride)),
      reference_type>
  access(I0 i0, I1 i1, Is... extra) const {
    check_access_member_function_valid_args(i0, i1, extra...);
    KOKKOS_IMPL_VIEW_OPERATOR_VERIFY(m_track, m_map, i0, i1, extra...)
    if constexpr (is_layout_left) {
      if constexpr (rank_dynamic == 0)
        return m_map.m_impl_handle[i0 + m_map.m_impl_offset.m_dim.N0 * i1];
      else
        return m_map.m_impl_handle[i0 + m_map.m_impl_offset.m_stride * i1];
    } else if constexpr (is_layout_right) {
      if constexpr (rank_dynamic == 0)
        return m_map.m_impl_handle[i1 + m_map.m_impl_offset.m_dim.N1 * i0];
      else
        return m_map.m_impl_handle[i1 + m_map.m_impl_offset.m_stride * i0];
    } else {
      static_assert(is_layout_stride);
      return m_map.m_impl_handle[i0 * m_map.m_impl_offset.m_stride.S0 +
                                 i1 * m_map.m_impl_offset.m_stride.S1];
    }
#if defined KOKKOS_COMPILER_INTEL
    __builtin_unreachable();
#endif
  }
```

### Kokkos from Trilinos 16.0.0

```cpp
template <typename I0, typename I1, typename... Is>
  KOKKOS_FORCEINLINE_FUNCTION std::enable_if_t<
      (Kokkos::Impl::always_true<I0, I1, Is...>::value && (2 == rank) &&
       is_default_map && is_layout_right && (rank_dynamic == 0)),reference_type>
  access(I0 i0, I1 i1, Is... extra) const {
    check_access_member_function_valid_args(i0, i1, extra...);
    KOKKOS_IMPL_VIEW_OPERATOR_VERIFY(m_track, m_map, i0, i1, extra...)
    return m_map.m_impl_handle[i1 + m_map.m_impl_offset.m_dim.N1 * i0];
  }

template <typename I0, typename I1, typename... Is>
  KOKKOS_FORCEINLINE_FUNCTION std::enable_if_t<
      (Kokkos::Impl::always_true<I0, I1, Is...>::value && (2 == rank) &&
      is_default_map && is_layout_right && (rank_dynamic != 0)),
      reference_type>
  access(I0 i0, I1 i1, Is... extra) const {
    check_access_member_function_valid_args(i0, i1, extra...);
    KOKKOS_IMPL_VIEW_OPERATOR_VERIFY(m_track, m_map, i0, i1, extra...)
    return m_map.m_impl_handle[i1 + m_map.m_impl_offset.m_stride * i0];
  }
```

Hence, everything is fine in Kokkos.

**Comment by ViNN280801** [comment]
And I wanted to ask u about helping with such kind of problems.

image

Do you need to fix these problems for the Windows? I think, I can help you with this (compile Trilinos without error using MSVC Visual Studio 17 2022)

**Pull request closed without merging**
