### PR TITLE
Amesos2: Fix #4194

### LINKED ISSUE #4194: Amesos2 tests don't build with ETI OFF
@trilinos/amesos2

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/amesos2 @rrdrake @theguruat12 

## Related Issues

* Closes #4194 

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@ndellingwood I tested this with ETI OFF.  PR testing should take care of the ETI ON case, though I'm trying it now (it's so much faster to build with ETI ON).

**Comment by mhoemmen** [comment]
I can't actually add labels or do some other github stuff with this ancient web browser that I'm stuck using for the next couple days, so if one of you could add the automerge label, that would be great :-)  Thanks all!

**Comment by ndellingwood** [comment]
@mhoemmen added AT:AUTOMERGE

**Comment by mhoemmen** [comment]
Thanks @ndellingwood !  Some github things work for me and others don't.

**Comment by ndellingwood** [comment]
@mhoemmen I had that problem with my older version of firefox also before I updated, fwiw I'm using 60.3.0esr (64-bit) and it works fine, make sure to backup bookmarks etc before the update though.

**Comment by mhoemmen** [comment]
@ndellingwood I tried a newer Firefox but it doesn't run on this system (which happens to be some old workstation).  Thanks for the pointer, though!

**Pull request merged**
