### PR TITLE
intrepid2: compatibility update has_rank_member

### PR DESCRIPTION
**Pull request by ndellingwood**
Compatibility update with Kokkos with eventual 4.1 release

Co-authored-by: Damien L-G <dalg24+github@gmail.com>

@trilinos/intrepid2 

## Motivation
Update to enable Trilinos to compile against kokkos' develop branch (currently the eventual 4.1 release)

## Testing
Local nightly testing issues resolved; AT will add testing

### CODE REVIEW

**Comment by ndellingwood** [comment]
Adding @mperego @CamelliaDPG

**Comment by CamelliaDPG** [comment]
Thanks, @ndellingwood!  In 4.1, does View have a `rank()` method instead of a `rank` member?

**Comment by ndellingwood** [comment]
Hi @CamelliaDPG , here is the kokkos PR with the summary of relevant changes:
https://github.com/kokkos/kokkos/pull/5870

In 4.1, Kokkos will have a `rank()` member function for View

**Comment by CamelliaDPG** [comment]
> Hi @CamelliaDPG , here is the kokkos PR with the summary of relevant changes: [kokkos/kokkos#5870](https://github.com/kokkos/kokkos/pull/5870)
> 
> In 4.1, Kokkos will have a `rank()` member function for View

Glad to hear it; thanks for the detail!

**Review by CamelliaDPG — APPROVED** [review]
Looks good to me.  Thanks!

**Pull request merged**
