### PR TITLE
Fixed bug where the wrong basis was being constructed

### PR DESCRIPTION
**Pull request by bathmatt**
#2112 fix..

### CODE REVIEW

**Comment by bathmatt** [comment]
So, does  Pre-Test Inspection — INSPECTED  mean it is tested?

**Comment by jmgate** [comment]
@bathmatt, nope.  "**Pull Request AutoTester** &mdash; Under Test on Build #'s [182, 99]: See Comments" tells you that testing is in progress, though there should be comments in the discussion from the autotester to that effect.  I might need to submit a bug report against the autotester.

**Comment by jmgate** [comment]
For instance, see #2047 for an example of all the comments the @trilinos-autotester will add to the PR.

**Comment by jmgate** [comment]
Ah, there we go&mdash;testing is starting.

**Pull request merged**
