### PR TITLE
Intrepid2 Tetrahedral Hierarchical Bases

### PR DESCRIPTION
**Pull request by CamelliaDPG**
@trilinos/intrepid2

## Motivation
This PR fills in missing H(curl), H(div), and H(vol) hierarchical bases on the tetrahedron.  This follows #10662, which did the same for the triangle.

Forthcoming PRs will similarly add missing hierarchical bases on the wedge, and pyramid.

## Testing
Some basic "basis equivalence" tests, which establish that the hierarchical bases span the same space as existing nodal bases, are included here.  Additionally, I have done offline comparison with the ESEAS implementation of each basis, testing up to 8th order, with excellent agreement.  (One exception is that for p=5,6,7,8, the curls of certain functions disagree with ESEAS.  Given that the values agree with ESEAS (establishing that our dof numbering agrees), and given that the basis equivalence tests pass for these orders (establishing that the curls and values are consistent in the new implementation), I believe that this is either an issue with ESEAS, or something wrong with the interface I have set up to ESEAS for the comparison.  I have made some offline notes on which degrees of freedom are implicated; if I do find a bug in ESEAS or "smoking gun" evidence of incorrect curls there, I will communicate that to the ESEAS developers.)

### CODE REVIEW

**Comment by CamelliaDPG** [comment]
Added AT:WIP to the PR until I have a chance to address the failures (looks like some warnings-as-errors for serial builds, but some actual test failures for at least some CUDA builds).

**Comment by CamelliaDPG** [comment]
The tests that are now failing appear to be systemic testing-system failures, in which most(/all?) tests fail in a fraction of a second, with errors like this:

```
/scratch/trilinos/workspace/Trilinos_PR_gcc-7.2.0-debug/pull_request_test/packages/intrepid2/unit-test/MonolithicExecutable/Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests.exe: symbol lookup error: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/lib/libmca_common_verbs.so.7: undefined symbol: ompi_common_verbs_usnic_register_fake_drivers
```

**Comment by GrahamBenHarper** [comment]
@CamelliaDPG, that's right, this is blocked by one of the pinned issues #10999

**Comment by CamelliaDPG** [comment]
> @CamelliaDPG, that's right, this is blocked by one of the pinned issues #10999

Thanks, @GrahamBenHarper, that's good to know!

**Review by mperego — CHANGES_REQUESTED** [review]
It looks good to me. 
Would you mind checking if this works smoothly with orientations/projections? To do so just comment out these lines:
https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/unit-test/Projection/test_convergence_TET.hpp#L689
https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/unit-test/Projection/test_convergence_TET.hpp#L952
https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/unit-test/Projection/test_convergence_TET.hpp#L1214
Thanks!

**Comment by CamelliaDPG** [comment]
> It looks good to me.
> Would you mind checking if this works smoothly with orientations/projections? To do so just comment out these lines:
> https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/unit-test/Projection/test_convergence_TET.hpp#L689
> https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/unit-test/Projection/test_convergence_TET.hpp#L952
> https://github.com/trilinos/Trilinos/blob/master/packages/intrepid2/unit-test/Projection/test_convergence_TET.hpp#L1214
> Thanks!

Thanks for suggesting that, @mperego -- those tests did help me to find some errors in the implementation; should now be fixed.

**Comment by CamelliaDPG** [comment]
@mperego, if this looks good to you, would you please approve this PR?  Then I'll go ahead and merge.

**Review by mperego — APPROVED** [review]
Thanks for the changes. Looks good to me!

**Comment by CamelliaDPG** [comment]
> Thanks for the changes. Looks good to me!

Thanks @mperego!

**Pull request merged**
