### PR TITLE
Kokkos execution spaces' print_configuration is not static

### PR DESCRIPTION
**Pull request by masterleinad**
Corresponds to https://github.com/kokkos/kokkos/pull/4806 replacing all `static` calls to execution spaces not explicitly named with a member function called. `print_configuration` is not required to be static and, in fact, isn't for the `OpenMPTarget` and `SYCL` backends.

@trilinos/intrepid2
@trilinos/muelu
@trilinos/panzer
@trilinos/phalanx
@trilinos/seacas
@trilinos/shylu

## Motivation
Trying to get the `SYCL` backend working with `Trilinos`.

## Testing
Compiling with `Kokkos+SYCL`.

### CODE REVIEW

**Review by rppawlo — APPROVED** [review]

**Comment by rppawlo** [comment]
@gsjaardema - the seacas changes in this PR will need to be merged back to prevent regression on next snapshot.

**Comment by kyungjoo-kim** [comment]
For the changes in @trilinos/intrepid2 , it might be better to include these change directly in kokkos-promotion branch. There is some change, I made in that branch incorporating with deprecated kokkos code and there could be some conflicts.

**Comment by masterleinad** [comment]
> For the changes in @trilinos/intrepid2 , it might be better to include these change directly in kokkos-promotion branch. There is some change, I made in that branch incorporating with deprecated kokkos code and there could be some conflicts.

Honestly, I prefer not to split this up and not to clutter the `kokkos-promotion` branch with this. The fixes here are pretty straightforward and I'm happy to rebase after `kokkos-promotion` is merged.

**Comment by jhux2** [comment]
@trilinos/intrepid2
@trilinos/muelu
@trilinos/panzer
@trilinos/phalanx
@trilinos/seacas
@trilinos/shylu

**Review by jhux2 — APPROVED** [review]
MueLu change is fine with me.  Thanks, @masterleinad.

**Comment by kyungjoo-kim** [comment]
@ndellingwood Since Nathan works on the promotion branch, I just tag him for his information. This PR can cause some merge conflict with the promotion branch. I am fine either way this PR is merged before or after the promotion branch is merged. It can also add more tedious work for you to resolve the possible conflicts.

**Review by kyungjoo-kim — APPROVED** [review]

**Comment by masterleinad** [comment]
I rebased to resolve conflicts.

**Review by kyungjoo-kim — APPROVED** [review]

**Comment by GrahamBenHarper** [comment]
@masterleinad are you planning to revisit this since #10962 merged?

**Comment by masterleinad** [comment]
> @masterleinad are you planning to revisit this since #10962 merged?

Looks like it's all fixed now in `develop`.

**Pull request closed without merging**
