### PR TITLE
Framework: Add AT2 PR Tests

### PR DESCRIPTION
**Pull request by triple3567**
@trilinos/<teamName>

### CODE REVIEW

**Review by fryeguy52 — APPROVED** [review]

**Comment by sebrowne** [comment]
@triple3567 the approval label doesn't seem to be working?

**Comment by triple3567** [comment]
> @triple3567 the approval label doesn't seem to be working?

I don't have an account in the "Developers" team, hence the failing approval label.

**Review by fryeguy52 — APPROVED** [review]

**Review by sebrowne — APPROVED** [review]

**Comment by sebrowne** [comment]
Timeouts, RETESTing

**Comment by triple3567** [comment]
Removing until AT2 first release

**Review by trilinos-cicd — APPROVED** [review]
Triggering AT2 PR Test

**Review by trilinos-cicd — APPROVED** [review]
Triggering AT2 PR Tests

**Review by e10harvey — APPROVED** [review]
at2 testing

**Review by achauphan — APPROVED** [review]
Triggering AT2 PR Tests

**Review by e10harvey — APPROVED** [review]
at2 test

**Review by e10harvey — APPROVED** [review]
at2 test

**Review by fryeguy52 — APPROVED** [review]

**Comment by sebrowne** [comment]
Closing in favor of #12845

**Pull request closed without merging**
