### PR TITLE
Panzer: Modest changes to the blocked tpetra LOF exposing features

### PR DESCRIPTION
**Pull request by eric-c-cyr**
Modified a handful of functions and exposed a few more capabilities in the blocked Tpetra LOF

@trilinos/panzer

### CODE REVIEW

**Comment by jmgate** [comment]
I wonder if the Jenkins build failed due to the recent file renaming.

**Comment by rppawlo** [comment]
> I wonder if the Jenkins build failed due to the recent file renaming. Not sure how to check that, as I'm not sure how to find the Jenkins jobs that ran the testing.

I'm betting it is. @allevin - is there any mechanism for being able to specify that a PR requires the build directory to be wiped for this particular code change? This particular commit removes ETI, but the old autogenerated ETI file header is still in the build directory and breaks the build.

**Comment by eric-c-cyr** [comment]
@allevin Also, can we see the auto-tester results. I'd like to understand the failure better. Is there a way to put a link to the jenkins results?

**Comment by jmgate** [comment]
Not having a link to the Jenkins results is a know issue and the Framework team is working on it.

**Comment by allevin** [comment]
@rppawlo I don't think we have the ability to force the build directory to be wiped.  @jwillenbring might be able to shine more light on this.

@eric-c-cyr As @jmgate mentioned, the Frameworks team is working to address this.

**Comment by eric-c-cyr** [comment]
All right. Since I can't understand what is failing, can someone build and tests this for me so I can push? I don't want to loose track of these changes.

**Comment by eric-c-cyr** [comment]
Okay, this is the last chance to check. @allevin sent me the failures and does appear the old Panzer_DOF.hpp file is still hanging out in the build. So this is the same conversation happening with the framework folks right now. I think this commit is good to go, let me know in the next hour or so if you object to a push.

**Comment by jmgate** [comment]
I'll pull and test real quick.

**Comment by jmgate** [comment]
I'm seeing a dozen Drekar tests fail, though that may be unrelated to your changes.  Debugging&hellip;

**Comment by jmgate** [comment]
Sorry this is taking so long @eric-c-cyr&mdash;I'm having to do a clean rebuild.  Not sure how my build got so messed up.

**Pull request merged**
