### PR TITLE
zoltan:  minor change to fix #5106

### LINKED ISSUE #5106: Zoltan: Remove Build Warnings
## Enhancement
@trilinos/zoltan 

Issue #3178 is working toward turning Warnings as Errors on for _all_ packages in order in ensure Trilinos maintains a high level of SQA practices across the project.
Currently Zoltan has a warning that need to be handled before we can set Werror for Zoltan and eventually all packages.

A recent test build was performed with -Werror set. [The CDash report can be found here.](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4989925&filtercount=2&showfilters=1&field1=buildstamp&compare1=63&value1=Experimental&field2=buildstarttime&compare2=83&value2=2019/04/30&filtercombine=and)
Once the Zoltan build doesn't emit any warnings that will be promoted to errors, [we can set `-Werror` in the GCC 7.2.0 automated build](https://github.com/ZUUL42/Trilinos/tree/Werror_Zoltan).

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/zoltan 

## Description
Minor change to fix warning in test code (not Zoltan library code) reported in #5106.
I increased the size of the receiving string str to 32 bytes to more than comfortably hold an integer.

## Motivation and Context
Provided in #5106

### CODE REVIEW

**Comment by mhoemmen** [comment]
@trilinos/framework Looks like PR test submission is broken:
```
Tests succeeded.
   Error when uploading file: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/pull_request_test/Testing/20190508-1721/Test.xml
   Error message was: The requested URL returned error: 500 Internal Server Error
   Problems when submitting via HTTP
test submit error = -1
   Error when uploading file: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/pull_request_test/Testing/20190508-1721/Upload.xml
   Error message was: The requested URL returned error: 500 Internal Server Error
   Problems when submitting via HTTP
```

**Comment by kddevin** [comment]
@ZUUL42 @trilinos/framework 
I cannot see the test failures.  When I follow the link, I get some sort of search/filter query page.  See attached.
Untitled

**Comment by ZUUL42** [comment]
@kddevin, there were some server issues yesterday that had CDash completely unreachable and were still offline when I left around 1800 MDT. I'm not sure when they came back online. I suspect the results never made it to CDash when the tests finished. The easiest thing would be to just let them run again.

**Comment by kddevin** [comment]
OK, the current failures must be from some configuration or job launch problem.  I know changing two array sizes from four bytes to 32 bytes in zoltan's tests did not cause these.  
@trilinos/framework @ZUUL42   please help! Thanks!

```
p=0: *** Caught standard std::exception of type 'std::runtime_error' :

 cudaGetDeviceCount( & m_cudaDevCount ) error( cudaErrorNoDevice): no CUDA-capable device is detected /home/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:203
 Traceback functionality not available
```

and

```
ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0x1000c44d430 valid_mask = 0x1)
[ride10][[50419,1],3][btl_openib_component.c:1648:init_one_device] error obtaining device attributes for mlx5_0 errno says Invalid argument
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   ride10
  Local device: mlx5_0
--------------------------------------------------------------------------
[ride10][[50419,1],0][btl_openib_proc.c:330:mca_btl_openib_proc_get_locked] 0: error exit from mca_btl_openib_proc_create
[ride10][[50419,1],2][btl_openib_proc.c:330:mca_btl_openib_proc_get_locked] 2: error exit from mca_btl_openib_proc_create
[ride10][[50419,1],1][btl_openib_proc.c:330:mca_btl_openib_proc_get_locked] 1: error exit from mca_btl_openib_proc_create
[ride10][[50419,1],0][btl_openib_proc.c:330:mca_btl_openib_proc_get_locked] 0: error exit from mca_btl_openib_proc_create
[ride10][[50419,1],1][btl_openib_proc.c:330:mca_btl_openib_proc_get_locked] 1: error exit from mca_btl_openib_proc_create
[ride10][[50419,1],2][btl_openib_proc.c:330:mca_btl_openib_proc_get_locked] 2: error exit from mca_btl_openib_proc_create
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetDeviceCount( & m_cudaDevCount ) error( cudaErrorNoDevice): no CUDA-capable device is detected /home/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:203
Traceback functionality not available
```

**Comment by ZUUL42** [comment]
@kddevin, ya I'm sure your changes didn't cause the Cuda build to fail like that.
I'll flag this for retest once we've got a fix for the Cuda PR test in place.

**Pull request merged**
