### PR TITLE
MueLu: Adding a weighted distance Laplacian capability

### PR DESCRIPTION
**Pull request by csiefer2**
Motivation:  Allowing directional-weighted coarsening via the distance Laplacian, so you can semi-coarsen (like if you know the material constant doesn't transmit data effectively in one direction).

ISSUE (or n/a if non-ASC): n/a

TESTS: RHEL7

### CODE REVIEW

**Comment by jhux2** [comment]
@csiefer2 What's the objective/motivation for the PR?  Maybe put that here or in an issue?

**Comment by csiefer2** [comment]
> 
> 
> @csiefer2 What's the objective/motivation for the PR? Maybe put that here or in an issue?

See above.

**Review by jhux2 — APPROVED** [review]
lgtm.  Thanks for adding context to the PR!

**Review by jhux2 — APPROVED** [review]
jawohl!

**Review by cgcgcg — APPROVED** [review]

**Pull request merged**
