### PR TITLE
Update MueLu's GetMatrixDiagonal function (Kokkos version), to return RCP<Vector>

### PR DESCRIPTION
**Pull request by JacobDomagala**
Changes:
- Make `Utilities_kokkos::GetMatrixDiagonal` return RCP \<Vector> 
- Use `getLocalDiagCopy` to obtain the diagonal values

### CODE REVIEW

**Comment by bathmatt** [comment]
I'm going to approve to just run the PR tester, don't merge until someone real reviews like. @jhux2 @cgcgcg

**Review by bathmatt — APPROVED** [review]
fire off auto tester

**Review by cgcgcg — APPROVED** [review]
Same deal, just to get the AT running

**Comment by bathmatt** [comment]
@cgcgcg i know you approved, but assuming it was to fire off the autotester, can we get an official o.k. or just hit merge if you're down w/ the changes?

**Pull request merged**
