### PR TITLE
Amesos2_MUMPS : remove deprecated code

### PR DESCRIPTION
**Pull request by iyamazaki**
@trilinos/amesos2 

## Motivation

This PR updates Amesos2_MUMPS code to remove the deprecated codes.

## Related Issues

* https://github.com/trilinos/Trilinos/issues/11813

## Testing
```
    Start 1: Amesos2_KLU2_UnitTests_MPI_2
1/7 Test #1: Amesos2_KLU2_UnitTests_MPI_2 .........................   Passed    1.50 sec
    Start 2: Amesos2_KLU2_Solver_Test_MPI_2
2/7 Test #2: Amesos2_KLU2_Solver_Test_MPI_2 .......................   Passed    1.79 sec
    Start 3: Amesos2_LAPACK_Solver_Test_MPI_4
3/7 Test #3: Amesos2_LAPACK_Solver_Test_MPI_4 .....................   Passed    1.60 sec
    Start 4: Amesos2_MUMPS_UnitTests_MPI_4
4/7 Test #4: Amesos2_MUMPS_UnitTests_MPI_4 ........................   Passed    1.55 sec
    Start 5: Amesos2_SolverFactory_UnitTests_MPI_4
5/7 Test #5: Amesos2_SolverFactory_UnitTests_MPI_4 ................   Passed    1.57 sec
    Start 6: Amesos2_Tpetra_MultiVector_Adapter_UnitTests_MPI_4
6/7 Test #6: Amesos2_Tpetra_MultiVector_Adapter_UnitTests_MPI_4 ...   Passed    1.77 sec
    Start 7: Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4
7/7 Test #7: Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4 .....   Passed    2.12 sec

100% tests passed, 0 tests failed out of 7

Label Time Summary:
Amesos2    =  41.02 sec*proc (7 tests)

Total Test time (real) =  11.95 sec
```

### CODE REVIEW

**Comment by iyamazaki** [comment]
We are working on this PR to fix the issues with MUMPS. I hope it will fix your issues, @LeaSassmannshausen @vryy.

**Comment by vryy** [comment]
> We are working on this PR to fix the issues with MUMPS. I hope it will fix your issues, @LeaSassmannshausen @vryy.

@iyamazaki this is good news. Let me know when I can already test it.

**Comment by iyamazaki** [comment]
You could already pull in the changes for testing, if you have time, @vryy. :)

**Review by ndellingwood — APPROVED** [review]
Changes look reasonable, thanks @iyamazaki ! Mumps is not tested as part of CI, so we should get a separate confirmation that issues are resolved before merging

**Comment by iyamazaki** [comment]
Thank you for the review, @ndellingwood. I posted the output results of tests above!!

**Pull request merged**
