### PR TITLE
Framework: Move PR build GCC 8.3.0 to use SEMS' current spack-cm TPL modules

### PR DESCRIPTION
**Pull request by ZUUL42**
@trilinos/Framework

## Motivation

This will refactor all of the sets that were moved to use sems-archive modules to use associated names.
Then the GCC 8.3.0 has been converted to use sems-2.1 modules.

### CODE REVIEW

**Review by e10harvey — COMMENTED** [review]
Thanks, @ZUUL42 ! I believe `PullRequestLinuxDriver.sh` needs to be updated to source `sems-v2-modules-init.{sh,csh}` for the GCC 8.3.0 build. @fryeguy52: Is that correct?

**Comment by ZUUL42** [comment]
@e10harvey, yes, I believe that's it.
I think I had changed it in an earlier iteration that never made it to develop.
I'm working on that now to source the correct one at the correct time.

**Comment by ZUUL42** [comment]
This build is now working with the currently SEMS offered spack-cm TPLs.
There are 3 Zoltan tests failing. An issue has been filed for that, #10340.
Those have been turned off to get this change in place and [can always be turned back on](https://github.com/trilinos/Trilinos/commit/4e7378e4d9cb433e6d18c0cf12cfe8d2c48e6b53) once a solution has been found.
CDash results:
https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-spack-cm-gcc%2Bboost1.74.0-test-Trilinos_pullrequest_gcc_8.3.0-7006&field2=buildstamp&compare2=63&value2=Experimental

**Comment by ZUUL42** [comment]
Think I found the mistake. I copied the new [SEMS-DEFAULT] section from pullrequest.ini into trilinos_pr_test.ini.
It has the `use SIERRA-PYTHON-3.6.3:` line in it ... except the test.ini doesn't have that SIERRA-PYTHON section.

**Comment by ZUUL42** [comment]
Review please @e10harvey @fryeguy52 @jwillenbring before the PASSED status expires.
It's just creating a SEMS-DEFAULT block and then moving everything over to SEMS-ARCHIVE-DEFAULT before applying changes to the GCC 8.3.0 build.

**Review by jwillenbring — APPROVED** [review]
Looks good. For clarity, the changes to reference SEMS-archive are refactoring. SEMS-archive was used already, but the label was not previously changed. This improves clarity.

**Pull request merged**
