### PR TITLE
Enable builds on MacOSX

### PR DESCRIPTION
**Pull request by hmaarrfk**
xref: https://github.com/conda-forge/pytrilinos-feedstock/pull/22

@trilinos/<teamName>

### CODE REVIEW

**Comment by mhoemmen** [comment]
@hmaarrfk Thanks for the contribution!  There are a couple issues: 

1. Trilinos pull requests must merge into the `develop` branch, not the `master` branch.  Only nightly automated tests are allowed to merge from develop to master.

2. kokkos-kernels is maintained in a separate repository and snapshotted into Trilinos.  It's OK to patch the version in Trilinos, but we also need to make sure to fix the version here: github.com/kokkos/kokkos-kernels.

**Comment by hmaarrfk** [comment]
Meh, don't worry about it. I got the patch I needed and the reference.

I made the upstream PR 
https://github.com/kokkos/kokkos-kernels/pull/557

**Comment by mhoemmen** [comment]
@hmaarrfk Thanks for making the kokkos-kernels PR!  If that gets merged in, it will eventually get into Trilinos (snapshots of kokkos-kernels into Trilinos happen every few months).  Is that OK for you, or do you need Trilinos to be patched sooner than that?

**Comment by hmaarrfk** [comment]
Just tryign to get it packaged on conda-forge. Honestly, patching it up doesn't matter so much. I just don't like to have patches that aren't upstreamed.

Having the ability to use the `.patch` trick a the end of the github url is also very helpful and help justify the use of the patch.

This repo is huge and taking a while to clone. Maybe i can rebase locally to ensure that the diff isn't huge.

**Comment by hmaarrfk** [comment]
this has now been merged upstream

**Pull request merged**
