### PR TITLE
MueLu: add no-qr mode for kokkos version

### PR DESCRIPTION
**Pull request by aprokop**
@trilinos/muelu 

## Description
Add "skip QR" mode to Kokkos variant of TentativePFactory. For now, only for scalar problems.

## Motivation and Context
Exawind input decks use noqr.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@aprokop If y'all want to help me with Kokkos QR, I've started down that path in `tpetra/tsqr`.

**Comment by mhoemmen** [comment]
@aprokop No worries! :D Just curious if you were working on it already.

**Comment by aprokop** [comment]
@mhoemmen We have a stupid implementation in MueLu with unknown performance. It works but is very slow. That's the extent of the efforts so far.

**Comment by mhoemmen** [comment]
@aprokop I prefer the more generous phrase "initial prototype" :-)

**Pull request merged**
