### PR TITLE
Sacado:  Fix macro logic for enabling the new design for clang.

### PR DESCRIPTION
**Pull request by etphipp**
Apparently clang defines __GNUC__ too.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@etphipp If you need to get this through, just let me know and I'll approve it.

**Comment by etphipp** [comment]
@mhoemmen I guess if you wouldn't mind, I would appreciate it.

I realize other compilers might be problematic too, but I'll cross that bridge when I get to it.  This is only for experimental stuff anyway that isn't enabled by default.

**Comment by mhoemmen** [comment]
@etphipp done! :D

**Comment by etphipp** [comment]
Thanks @mhoemmen!

**Pull request merged**
