### PR TITLE
Zoltan2 parameter lists

### PR DESCRIPTION
**Pull request by MicheldeMessieres**
Refactors the Zoltan2 parameter list traits so they are loaded from static functions corresponding to the problems and algorithms instead from one large defined xml define.

### CODE REVIEW

**Comment by kddevin** [comment]
@MicheldeMessieres Thanks for your work on this issue.  I think this code will be much more maintainable than that old XML string.

Some initial questions are below. I know that, for some of these questions, the answer is "that's the way it was before, so it was kept that way."  But if there is time, perhaps we can look at the code to see why it was done that way before.  I'll do that in a second pass.
I haven't thoroughly reviewed the location of specific parameters; I'll do that in the second pass, too.

1.  Why does the code have separate pl.set() and pl.getEntryRCP()->setValidator() calls instead of passing the validator to the constructor?

2.  We should remove text like "(default false)" from the descriptions, as it can get out-of-sync with the actual defaults;  the parameter list print methods print the default values, so they aren't needed in the strings.

3.  Scotch and PuLP have getDefaultParameters() methods.  Since Scotch and PuLP are TPLs, I'm not convinced they should have these methods; they should use TPL sublists, I think.  

4.  Can validators be reused?  See, for example, debug_output_stream_Validator and timer_output_stream_Validator in the Environment.  They are the same, right?  Do we need to create two of them, or can the same one be used for both parameters?  Similarly, in several places, we create a validator that accepts true/false, yes/no, on/off, or 1/0; can that validator be reused instead of creating it in several locations?  
(The obvious auxiliary question is whether this level of acceptance is overkill. :)  Is there a simple true/false or 1/0 validator that we should use instead?)

More to come.

@trilinos/zoltan2

**Comment by MicheldeMessieres** [comment]
@kddevin 

Summary: Updated the branch to be current to the latest develop branch.
The new code resolves the mentioned issues except for a question regarding item 3.

_(1) Why does the code have separate pl.set() and pl.getEntryRCP()->setValidator() calls instead of passing the validator to the constructor?_

I’ve now changed these so they always use the constructor - this eliminates all getEntryRCP calls.

Note there is a difference in behavior - passing the validator in the constructor will cause it to immediately check the default while adding it afterwards did not.
The change force-reminded me that ‘color_method’ and ‘color_choice’ had improper default values in the original XML setup - they had been set to ‘rcm’ and ‘amd’.
I changed the default of ‘color_method’ to ‘SerialGreedy’ - the only choice.
I changed the default of ‘color_choice’ arbitrarily to the first option ‘FirstFit’ - possibly we will want to change that to a different default.

_(2) We should remove text like "(default false)" from the descriptions, as it can get out-of-sync with the actual defaults; the parameter list print methods print the default values, so they aren't needed in the strings._

I’ve removed all cases where the default was described.

In a few places the default was described with more info so I changed it so it preserves that info but not sound like it was the default setting.
For example: 'default is a balance of speed and quality’ becomes ‘balance is a balance of speed and quality’.

_(3) Scotch and PuLP have getDefaultParameters() methods. Since Scotch and PuLP are TPLs, I'm not convinced they should have these methods; they should use TPL sublists, I think._ 

I’ll need clarification as I originally thought these Algorithm parameters were going to be included in the full list like the others - wasn’t sure what you intended here.

_(4) Can validators be reused? See, for example, debug_output_stream_Validator and timer_output_stream_Validator in the Environment. They are the same, right? Do we need to create two of them, or can the same one be used for both parameters? Similarly, in several places, we create a validator that accepts true/false, yes/no, on/off, or 1/0; can that validator be reused instead of creating it in several locations?_

The validators can be reused.

To clean that up I made a general true/false validator defined as Environment::getTrueFalseValidator() and used that in the various places.

I unified the debug_output_stream_Validator and timer_output_stream_Validator and did the same in several other places.

_(The obvious auxiliary question is whether this level of acceptance is overkill. :) Is there a simple true/false or 1/0 validator that we should use instead?)_

I went ahead and changed these to just be true/false which is the most common use - replaced various places in code and xml test files which used the other conventions.

If we decide we want to go back to the broader list, we now only need to add the other options (yes,no,0,1) in the one place: Environment::getTrueFalseValidator().

**Comment by kddevin** [comment]
In the Trilinos/develop branch, I updated zoltan2/test/unit/environment/AllParameters.cpp.  It exercises validators.  For now, it is disabled in zoltan2/test/unit/CMakeLists.txt, as it fails for parameter imbalance_tolerance, even in the original code.  We must have  the wrong validator for this parameter in the original code.  The parameter imbalance_tolerance should be a number greater than or equal to one (e.g., 1.05).  In the test, the validator currently says the string "invalid_option" is OK input.  @MicheldeMessieres, do you have time to fix this validator?  Fixing it only in this branch is sufficient; there's no need to also fix it in Trilinos/develop (since we'll merge this branch soon).

**Comment by kddevin** [comment]
A few more questions/comments:

-  The change made to test/unit/environment/Parameters.cpp:105 breaks my compilation.  Was it needed for this work?  Or can it be reverted?  I see no problems when I revert the change.

-  I like that PartitioningProblem calls the partitioning algorithms' getDefaultParameters methods.  Is it possible for Problem::getDefaultParameters() to call getDefaultParameters for the PartitioningProblem, OrderingProblem, MappingProblem (instead of calling these three from the Environment)?   That way, the calls maintain the same hierarchy as the class structure.

-  Is there any possibility that using a dummy adapter type in the Environment will break with certain ETI instantiations?  Currently the dummy adapter type is a BasicVector adapter with scalar_t = lno_t = gno_t = int.  Might this break if we build without, say, gno_t=int?  Also, if this usage seems OK, perhaps we should use the simplest adapter (BasicIdentifierAdapter) as the dummy type.

-  We should note that changing yes/no/on/off/true/false/1/0 to true/false breaks backward compatibility.  But since the validator will accept only true/false, codes using something else will discover the problem quickly, right?  So I am not too concerned.

-  Parameters that can be removed:  
average_cuts
bisection_num_test_cuts
speed_versus_quality
memory_versus_speed
topology
randomize_input
objects_to_partition (this one propagates through the code, so I can take care of it)

-  Parameters that should be moved (note: moving doesn't change functionality, just aesthetics)
color_method to ColoringProblem
color_choice to AlgSerialGreedy
rectilinear to PartitioningProblem
subset_graph and symmetrize_input to Problem

**Comment by MicheldeMessieres** [comment]
@kddevin: I’ve pushed changes which address several of these concerns but have some questions about the first issue - currently the branch is in a state with AllParameters active but not passing.

_In the Trilinos/develop branch, I updated zoltan2/test/unit/environment/AllParameters.cpp. It exercises validators. For now, it is disabled in zoltan2/test/unit/CMakeLists.txt, as it fails for parameter imbalance_tolerance, even in the original code. We must have the wrong validator for this parameter in the original code. The parameter imbalance_tolerance should be a number greater than or equal to one (e.g., 1.05). In the test, the validator currently says the string "invalid_option" is OK input.  @MicheldeMessieres, do you have time to fix this validator? Fixing it only in this branch is sufficient; there's no need to also fix it in Trilinos/develop (since we'll merge this branch soon)._

My understanding is that this a general problem true of all the int or int/double validators which were set for any number - these would be:

**_currently int/string types_**
mj_concurrent_part_count
mj_keep_part_boxes
mj_enable_rcb
mj_recursion_depth
mapping_type

**_currently double/int/string types_**
imbalance_tolerance
mj_minimum_migration_imbalance
pulp_vert_imbalance
pulp_edge_imbalance
scotch_imbalance_ratio

**_set up in AllParameters.cpp as int but validators set up as double_**
random_seed                   _validator allows double - not sure if this should be pure int_
num_global_parts             _validator allows double - I think only because we need long long_
num_local_parts               _validator allows double - I think only because we need long long_ 

I added those that were missing to AllParameters.cpp, perhaps temporarily, just to keep the total list straight.

I expect we will want to convert some/all of these to use EnhanceNumberValidator.
Then we can set min/max values for int or double types - but string type would not be allowed - which may be exactly what we want.

The proper solution here may be to treat the pure double types the way AllParameters.cpp handles int types using a special anyIntParams list. So I could make anyDoubleParams and convert the string to double first, then let the validator execute.

But I think both anyIntParams and anyDoubleParams need additional changes to make sure a string which does not convert will properly fail. For example, those invalid parameters in anyIntParams will currently not properly detect the string as invalid. I expect the idea here is to make AllParameters find the same errors that a type loaded from an xml would find if a string did not match the expected format.

I have not fully explored the implications of changing these types to validators which do not allow strings - especially regarding loading xml files. So I think the goals here are fairly clear but probably makes sense to clarify we are on the same page before continuing.

Note on num_global_parts and num_local_parts: I saw in PartitioningSolution<Adapter>::setPartDistribution you had a conversion from double to int for the num_global_parts and num_local_parts parameters. I haven’t done any changes for those yet - I saw the xml files load num_global_parts as a string type - not double or int. I understand this is probably due to a need for a long long parameter type.

_(1) The change made to test/unit/environment/Parameters.cpp:105 breaks my compilation. Was it needed for this work? Or can it be reverted? I see no problems when I revert the change._

This was a mistake I made pushing that branch - it should be as you said in the original form and is fixed now.

_(2) I like that PartitioningProblem calls the partitioning algorithms' getDefaultParameters methods. Is it possible for Problem::getDefaultParameters() to call getDefaultParameters for the PartitioningProblem, OrderingProblem, MappingProblem (instead of calling these three from the Environment)? That way, the calls maintain the same hierarchy as the class structure_

It think it would be better to have it as you describe except we’ll have a circular class setup as Zoltan2_Problem.hpp will depend on its derived classes for includes.

This was an issue that came up in our original discussions. The other option would be to make global functions to handle getDefaultParameters() which are not class methods. That would have the disadvantage of making them live outside the classes but then they could be implemented in a cpp file, allow us to place those calls in a Zoltan2_Problem.cpp file resolving the issue you raised, and eliminate the need for the dummy adapter (next issue below). So both ways have some advantages/disadvantages I think.

_Is there any possibility that using a dummy adapter type in the Environment will break with certain ETI instantiations? Currently the dummy adapter type is a BasicVector adapter with scalar_t = lno_t = gno_t = int. Might this break if we build without, say, gno_t=int? Also, if this usage seems OK, perhaps we should use the simplest adapter (BasicIdentifierAdapter) as the dummy type._

I changed this to BasicIdentifierAdapter - I think it will always be ok since the types chosen have no relevance to behavior, but it may create extra compiling so it might be nice to improve this to use any correct types already in play.

However if we made getDefaultParameters() not a class method it could be independent of the adapter - see prior issue.

_We should note that changing yes/no/on/off/true/false/1/0 to true/false breaks backward compatibility. But since the validator will accept only true/false, codes using something else will discover the problem quickly, right? So I am not too concerned._

I added a comment regarding this to the new getTrueFalseValidator() function
These should immediately be given the error that true/false are the only valid options so I think it will be clear what needs to be changed.

_Parameters that can be removed: average_cuts, bisection_num_test_cuts. speed_versus_quality, memory_versus_speed, topology, randomize_input
  objects_to_partition (this one propagates through the code, so I can take care of it)_

These have been removed except for: objects_to_partition

_Parameters that should be moved (note: moving doesn't change functionality, just aesthetics)
color_method to ColoringProblem, color_choice to AlgSerialGreedy, rectilinear to PartitioningProblem, subset_graph and symmetrize_input to Problem_

These were moved and I added getDefaultParameters() methods and calls as necessary.

**Comment by kddevin** [comment]
Thanks, @MicheldeMessieres .

Regarding issue (2) above:  We'll keep the code's structure as is.  I like having the getDefaultParameters methods as part of the classes, and I understand the circular include dependence if we try to change it.  Thanks.

Regarding the validators:  AnyNumberParameterEntryValidator doesn't work as I expected; see #612.  I thought the validator would complain about a non-number string (e.g., "invalid_option").  And I thought the parameter would work with a number string (e.g., "0.5" could be returned as double(0.5)).  Neither appears to be true.  We should know more about #612 early next week; then we can decide what to do with the parameters that are using this validator.

I like the validators for numerical values that accept strings or numbers.  With them, users can read parameters from a file and pass the strings to us, without having to interpret and convert them.  But given #612, I don't know whether supporting that option is feasible.  If not, we'll just accept numbers.  

In the meantime:

We can remove parameter random_seed.

The following parameters should be true/false, not integers:  mj_enable_rcb, mj_keep_part_boxes

Parameter mj_migration_option has only these valid values:  0, 1, 2

Parameters num_global_parts and num_local_parts should have int-like values; num_global_parts should be > 0 and num_local_parts should be >= 0.  I don't recall the complication that had us fetching them as doubles, but the fetching code looks as if it always converts to int anyway.  Probably safest for these is to getValues<part_t>, which will work for int and will legitimately cause problems if we change part_t in the future.

More to come.  Thanks for your patience.

**Comment by MicheldeMessieres** [comment]
@kddevin Thanks I will take care of those changes.

I had noticed earlier this code in Zoltan2_PartitioningSolution.hpp.
This is in PartitioningSolution<Adapter>::setPartDistribution:

  const Teuchos::ParameterEntry *pe = pl.getEntryPtr("num_global_parts");
  if (pe){
    val = pe->getValue<double>(&val);  // TODO: KDD Skip this double get
    haveGlobalNumParts = 1;            // TODO: KDD Should be unnecessary once
    numGlobal = static_cast<int>(val); // TODO: KDD paramlist handles long long.
    nGlobalParts_ = part_t(numGlobal); // TODO: KDD  also do below.
  }
I would probably end up removing some of this code when we convert to int - let me know if there is anything special I should do to handle this.

**Comment by kddevin** [comment]
I think the code becomes something like this:

const Teuchos::ParameterEntry *pe = pl.getEntryPtr("num_global_parts");
if (pe){
  nGlobalParts_ = pe->getValue<part_t>(&nGlobalParts_); 
  haveGlobalNumParts = 1; 
}

If that doesn't work, let me know; maybe you'll refresh my memory of why it was done with double previously.

**Comment by MicheldeMessieres** [comment]
@kddevin 

I’ve pushed new changes which should address everything you mentioned.
Also a few comments below which may be useful for upcoming discussions on the string issues with validators.

**Updates with the latest push:**
random_seed - removed
mj_enable_rcb and mj_keep_part_boxes were changed to true/false validators.
    _Note that mj_keep_part_boxes originally defaulted to -1 - I have changed that to “false”.
    But wanted to verify there’s wasn’t a 3rd ‘unset’ use case - the tests are all passing._
mj_migration_option was changed to an EnhancedNumberValidator accepting only 0, 1, 2
num_global_parts was changed to an EnhancedNumberValidator accepting >= 1
num_local_parts was changed to an EnhancedNumebrValidator accepting >= 0
I changed the code in Zoltan2_PartitioningSolution.hpp as you indicated so reads num_local_parts and num_global_parts directly.

**Origin of the double issue:**

You asked about the origin of the double setting for num_local_parts and num_global_parts. I am not sure but it seems this was probably a typo going back several years to when the validator lists were first set up. It may have just stuck around and propagated - for example in 2012 we had a commit to Metric.cpp casting to double to set num_local_parts. But it sounds like this may all be fine now that they are set as true int values - I have changed the various places which referred to double.

**AllParameters.cpp comment:**

I mention the following because we will need to change the behavior of anyIntParams in AllParameters.cpp depending on decisions made about accepting strings:

For AllParameters.cpp I moved the entries that currently don’t work into a commented out list.
I disabled the anyIntParams setup as I don’t think it applies until we have decided the string   issues. I can fix this all up once we resolve our plan but I expect it will need to be redone.

**EnhancedNumberValidator and AnyNumberParameterEntryValidator comment:**

I mention the following because I think the planned string discussion will probably want to consider both these types together:
    
We are using both EnhancedNumberValidator and AnyNumberParameterEntryValidator. I notated the problematic parameters in AllParameters.cpp with the current validator type they use. EnhancedNumberValidator will only accept number types - not string. AnyNumberParameterEntryValidator accepts string but has the problem of not validating the bad types.

**True/False Validator Comment:**

I mention the following because we may want to consider changing our true/false validator to be a true bool validator.

The “true” “false” validator was originally mapped to an int type - meaning it can be read as an int 1 or 0. This validator could potentially be changed to a true bool type so we would read it to a bool, not an int.This will change code in quite a few places but I think it will be straight forward and perhaps preferable. For example, in Zoltan2_AlgMultiJagged.hpp member variables corresponding to params such as mj_run_as_rcb could be true bool types instead of int.

**Comment by kddevin** [comment]
Thanks, Michel.
Answering your questions above:
True/False validators:  I'm happy to use bool types wherever the code changes are trivial.  I think they are for the MJ parameters; I don't know if they would be trivial everywhere.  Which variables would we have to change?
And, yes, your default change from -1 to false is fine.
I haven't had the discussion about #612 yet.  For now, the EnhancedNumberValidator is good.

**Comment by MicheldeMessieres** [comment]
@kddevin
I’ve added string support to EnhancedNumberValidator as we discussed. This will use std::stod & std::stoi or std::atof & std::atoi based on CXX11, same as AnyNumberParameterEntryValidator. Also added unit tests for EnhancedNumberValidator accepting strings. Now all parameters in the Zoltan2 AllParameters unit test are properly detecting passing and failing string events.

**Some notes:**
EnhancedNumberValidator is a template over type T while AnyNumberParameterEntryValidator is not and just handles types int, double, and string types. This means determining whether EnhancedNumberValidator is a number type versus a decimal type is handled differently.
Right now I’ve got explicit checks for number types and then it falls back to double conversion for everything else. The result is always cast back to the template type T.

It seems we may want to consider some general reorganization with string conversions perhaps handled in the base class. Then we could unify AnyNumberParameterEntryValidator and EnhancedNumberValidator which share some behaviors. But this would probably need some further discussion to decide how to best handle the template type T.

**Comment by kddevin** [comment]
@MicheldeMessieres This work sounds great; thank you.
I'll look through the pull request.  We can discuss with the frameworks team whether further changes to Teuchos should be pursued.

**Comment by kddevin** [comment]
I reviewed the changes.  The following tests passed:
100% tests passed, 0 tests failed out of 547

Label Time Summary:
Amesos       =  12.11 sec
Amesos2      =   4.88 sec
Belos        =  20.95 sec
Epetra       =  64.71 sec
EpetraExt    =   5.35 sec
Galeri       =   6.16 sec
Ifpack       =  12.14 sec
Ifpack2      =  43.39 sec
MueLu        = 1024.83 sec
Teuchos      =  81.15 sec
Tpetra       = 101.08 sec
Zoltan2      = 100.59 sec

Thus, I am going to merge.

**Comment by pwxy** [comment]
One of the many commits mentioned in this thread changed the parameter remap_parts from "string" to "bool":

"Zoltan2: Parameter list update (#497)"

-    pl.set("remap_parts", "no", "remap part numbers to minimize migration "
-      "between old and new partitions");
-    pl.getEntryRCP("remap_parts")->setValidator(remap_parts_Validator);
+      "If \"bipartite\", A becomes [[0 A][ATranspose 0]].",
+      symmetrize_input_Validator);
+
+    pl.set("remap_parts", "false", "remap part numbers to minimize migration "
+      "between old and new partitions", Environment::getTrueFalseValidator());

I didn't see any discussion of this in the above thread, but I assume there was good reason to change the type of "remap_parts."
However, changes like these can have a substantial impact on users.

**Pull request merged**
