### PR TITLE
Tpetra equilibration interface; thread-parallelize CrsMatrix::{left,right}Scale (was: "Move equilibration from Ifpack2 to Tpetra")

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/ifpack2 @trilinos/tpetra 
See #2820 for details.

### CODE REVIEW

**Comment by mhoemmen** [comment]
I realize now that I don't like this interface, especially `leftAndOrRightScaleCrsMatrix`, so I would appreciate some actual feedback here :-) .  I will mark it as a W(ork)I(n)P(rogress) and it will almost certainly change.

It's true that RowMatrix already has `leftScale` and `rightScale`.  I'm not a fan because RowMatrix is otherwise an entirely read-only interface; these two methods break that.  On the other hand, the methods exist in Epetra and do get used there: see e.g., https://github.com/trilinos/Trilinos/blob/f0350316239aaf41e8e6b82378612aaedf9cc72c/packages/epetra/src/Epetra_LinearProblem.cpp#L125 .  The methods may also be used for the Jacobi version of sparse matrix-matrix multiply; @jhux2 is that right?

In any case, I think the interface should change as follows:

  1. Make available a local (`KokkosSparse::CrsMatrix` and `Kokkos::View`) interface
  2. Make the global interface take a `Kokkos::View` for the scaling factors, instead of an `EquilibrationInfo` (so that users can provide their own scaling factors)
  3. Add an overload for the global interface that takes a `Tpetra::Vector` (not really preferred, since it entails a `Kokkos::DualView` -- it's also redundant, since `Tpetra::Vector` has a Map, but the CrsMatrix determines the valid Map to use for left resp. right scaling)
  4. Use the overload to implement CrsMatrix's `leftScale` and `rightScale` methods.  This will thread-parallelize these methods for free and also remove their current UVM assumption.

I welcome suggestions! :-)

**Comment by tjfulle** [comment]
I like this idea:

> Make the global interface take a `Kokkos::View` for the scaling factors, instead of an `EquilibrationInfo` (so that users can provide their own scaling factors)

Also, why not name the new files `Tpetra_Detals_*` like other files that implement things in `Tpetra::Details`?  (not meant to be rhetorical, I'm genuinely curious :)

How does

> overload to implement CrsMatrix's leftScale and rightScale methods. This will thread-parallelize these methods for free and also remove their current UVM assumption.

remove the UVM assumption?  Is it for the fact that the new algorithms operate in specified execution spaces?

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> Also, why not name the new files `Tpetra_Details_*` like other files that implement things in `Tpetra::Details`? (not meant to be rhetorical, I'm genuinely curious :)

The new functions are in the public interface.  EquilibrationInfo is in the Details namespace only because I'm not committing to its final contents yet.  Users can still pass it around but they shouldn't yet assume anything about its contents.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> How does
> 
> > overload to implement CrsMatrix's leftScale and rightScale methods. This will thread-parallelize these methods for free and also remove their current UVM assumption.
>
> remove the UVM assumption? Is it for the fact that the new algorithms operate in specified execution spaces?

The current `leftScale` and `rightScale` implementations are sequential and run on host, accessing both the matrix and the input vector on host.  The new implementations run on device.

**Comment by tjfulle** [comment]
Thanks @mhoemmen, I figured there was an intended reason :)

**Comment by mhoemmen** [comment]
@trilinos/tpetra 

I just pushed more commits that do the following:

  - Change the leftAndOrRightScaleCrsMatrix interface to be more suitable for public use
  - Thread-parallelize CrsMatrix::leftScale and rightScale, using helper functions I had written anyway

**Comment by mhoemmen** [comment]
@csiefer2 Oh no, I think I dismissed your review by mistake!  Sorry!

**Comment by mhoemmen** [comment]
@trilinos/tpetra Now I'm done :-D

**Comment by csiefer2** [comment]
You just sped up the MSAK kernels too :)  Yay!

**Comment by mhoemmen** [comment]
@trilinos/tpetra I just pushed a fix; Xpetra's tests now pass for me.

**Comment by mhoemmen** [comment]
Thanks all! :D

**Pull request merged**
