### PR TITLE
Ifpack2: Do not allocate views associated to the Schur complements if the number of sublines per line is not at least 2

### PR DESCRIPTION
**Pull request by kliegeois**
Do not allocate views associated to the Schur complements if the number of sublines per line is not at least 2.

@trilinos/ifpack2

### CODE REVIEW

**Review by lucbv — APPROVED** [review]
As long as the variables `pack_td_ptr_schur_last` and `num_packed_blocks_schur` are not needed anywhere else I'm fine with this.

**Comment by kliegeois** [comment]
@sebrowne it seems that the configuration failed on CUDA, do you know why?

**Comment by sebrowne** [comment]
@kliegeois yes, the NetCDF include directory that we specify there has disappeared.  I've notified at @fryeguy52 who is one of the responsible SEMS parties for those libraries.  He's investigating.

**Comment by kliegeois** [comment]
Thanks a lot for the update @sebrowne !

**Comment by sebrowne** [comment]
Adding RETEST now that we believe the HDF5/NetCDF issue is fixed.  Using this PR as the test case.

**Pull request merged**
