### PR TITLE
Belos: Change default orthogonalization to ICGS[2]

### PR DESCRIPTION
**Pull request by jennloe**
@trilinos/belos 

## Motivation
This PR makes ICGS[2] the default orthogonalization scheme for all solvers, to be consistent with the default behavior in `PseudoBlockGmres` and in AztecOO.  

I also removed some unused header files in `RCGSolMgr.hpp` related to orthogonalization. 

## Related Issues
This PR closes issue #4657. (See also PR #4650.)

### CODE REVIEW

**Comment by jhux2** [comment]
@spdomin @sayerhs This could potentially affect Nalu and Nalu-Wind.

**Comment by jennloe** [comment]
This PR has uncovered a bug in the ICGS and IMGS orthogonalization for a few obscure test cases.  @hkthorn is working to fix.  It will be a few more days before this is merged.

**Comment by iyamazaki** [comment]
At least my Nalu-wind runs use ICGS. I am not sure if this is the only place we set up Belos, but it looks like LinearSolverConfig sets it to be ICGS?

**Comment by sayerhs** [comment]
Thanks @jhux2 . As @iyamazaki mentions, nalu has been using ICGS as the default 

https://github.com/Exawind/nalu-wind/blob/master/src/LinearSolverConfig.C#L71-L72

**Comment by jennloe** [comment]
Bug should be fixed now. See PR #7392

**Comment by spdomin** [comment]
@jhux2, thank you for looking out for Nalu-based codes - much appreciated!

As noted above, this has been our default for a while as our intent was to benchmark Belos vs AztecOO.

Do you suggest that we remove the setting or expose this to the user?

**Comment by jhux2** [comment]
> @jhux2, thank you for looking out for Nalu-based codes - much appreciated!
> 
> As noted above, this has been our default for a while as our intent was to benchmark Belos vs AztecOO.
> 
> Do you suggest that we remove the setting or expose this to the user?

I would think only a power user would want to toggle this.

**Pull request merged**
