### PR TITLE
fix installation of generated ETI headers

### PR DESCRIPTION
**Pull request by jjwilke**
@trilinos/kokkos-kernels 

## Motivation
Need to install ETI headers that preserve tree structure. Currently installed in wrong place.

### CODE REVIEW

**Comment by crtrott** [comment]
@trilinos/framework what do we need to do to make this actually run?

**Comment by prwolfe** [comment]
> @trilinos/framework what do we need to do to make this actually run?

not sure I understand. The builds are running now. There was a wait while the previous PR (7179) completed.

**Comment by crtrott** [comment]
Yeah I thought the PR Tester will immediately schedule stuff, but it will just take a while until all in-queue stuff is done. So the PR-Tester will only react when it comes back from a currently running test?

**Comment by prwolfe** [comment]
Yes - we don't have infinite capacity so we have to wait to have the slots. Our scheduling method at the moment is not particularly efficient either.

**Pull request merged**
