### PR TITLE
Fix 12648

### PR DESCRIPTION
**Pull request by tjfulle**
fix spelling error in environment variable name.

closes: #12648

### CODE REVIEW

**Review by brian-kelley — CHANGES_REQUESTED** [review]
I grepped for the misspelled version in case it appears in other places, and it's in ``core/src/Tpetra_Details_ExecutionSpaces.hpp`` too, could you take are of that one in this PR also?

**Comment by jhux2** [comment]
@tjfulle Is there a test for this option?

**Comment by jhux2** [comment]
@tjfulle Looks like many options aren't tested.  I'll open a separate issue.

**Comment by jhux2** [comment]
> I grepped for the misspelled version in case it appears in other places, and it's in `core/src/Tpetra_Details_ExecutionSpaces.hpp` too, could you take are of that one in this PR also?

@tjfulle Not sure if you noticed this comment from @brian-kelley.

**Comment by tjfulle** [comment]
Thanks @jhux2 - I hadn’t seen Brian’s comment. I’ll update the PR

**Review by brian-kelley — APPROVED** [review]

**Pull request merged**
