### PR TITLE
MueLu: Set "aggregation: match ML phase2a" in ML2MueLu translation

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
This seems reasonable, but I'll wait for @rstumin's feedback.

### CODE REVIEW

**Comment by jhux2** [comment]
@rstumin @cgcgcg This does exactly what the name implies?

**Comment by cgcgcg** [comment]
If I can trust my past self, then yes.

**Comment by cgcgcg** [comment]
The option was added/modified in PR #9747.

I wrote up the story behind it in this comment:
https://github.com/trilinos/Trilinos/pull/9747#issuecomment-994086900

**Review by rstumin — APPROVED** [review]
looks good.

**Comment by jwillenbring** [comment]
@cgcgcg @trilinos/framework Yes, this does seem odd. The AT only ran the one time, and the testing was stale, and was properly marked as stale, yet the merge was allowed to happen.

It almost seems like the AT would not automatically merge, but for some reason it did allow a manual merge. Not sure if there is some glitch with the timing of the review?

**Pull request merged**
