### PR TITLE
Framework: Make Kokkos-Kernels build in PR testing...

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework 	

# DO NOT MERGE THIS INTO TRILINOS!

This is a trivial edit to a file in Kokkos-Kernels to make the
PR testing system build the Kokkos-Kernels package to see if the
pthreads error from nightly clean builds is replicated.

### CODE REVIEW

**Comment by william76** [comment]
Dangit... it helps when I don't put a typo in. 🤬

**Comment by crtrott** [comment]
Ok we merge this in to get the builds clean. We can't get a new pull request in today anyway considering the time it takes to get through testing. We will fix this differently permanently by disabling gtest pthread usage in our source code in Kokkos.

**Comment by srajama1** [comment]
@william76 Please remove " // DO NOT MERGE THIS PR INTO TRILINOS! " in the code ...

**Comment by crtrott** [comment]
@srajama1 moving that comment out would require full test cycle again :-(. So I decided to just move this in. We can fix this later.

**Comment by william76** [comment]
@srajama1 	
@crtrott 	

Note the comment at the top of this PR, so WHY did you merge this!?  Please don't set automerge and/or merge Framework team pull requests.  I did not label it with Kokkos-Kernels because I wanted it to not be merged. The purpose of this PR was for me to see what happened on the SERIAL testing for Pull Requests.

**Comment by crtrott** [comment]
This was a executive decision from the Kokkos team. This is the change we want to make for now until we have a permanent solution - which actually would do this slightly different (i.e. a code change inside our gtest copy). I merged this because it takes forever to get a full Kokkos test cycle through the autotester, and I dont' want this issue to mask problems with the new Kokkos release tonight.

**Pull request merged**
