### PR TITLE
MueLu/Xpetra: various minor changes & fixes

### PR DESCRIPTION
**Pull request by mayrmt**
@trilinos/muelu 
@trilinos/xpetra 

## Motivation

Changes of this PR were made during work on an `InterfaceAggregationFactory` for surface-coupled problems with multipler dual DOFs per node. To make the review easier, this PR just contains

- adding safety checks
- renaming to more descriptive names
- renaming in preparation for the muliple-DOFs-per-node interface aggregation
- more consistent use of MueLu's pre-defined short names
- fixes to the documentation

**Note:** There's no change in functionality.

## Testing

`ctest -j 12` passes on a local build on a Ubuntu workstation.

### CODE REVIEW

**Comment by mayrmt** [comment]
@trilinos/muelu @trilinos/framework Here are parts of the error message taken from CDash:
```
Throw number = 1

Throw test that evaluated to true: file_ == NULL

FileInputStream ctor failed to open file: myXML.xml

[....]

/scratch/trilinos/jenkins/ascic166/workspace/trilinos-folder/Trilinos_pullrequest_gcc_8.3.0/pull_request_test/packages/muelu/test/meshtying/MueLu_MeshTyingBlocked_SimpleSmoother.exe[0x4a5505]
```

The failing test `MueLu_MeshTyingBlocked_SimpleSmoother.exe` on 4 MPI ranks tries to open the xml-file `myXML.xml`, which has been renamed to `smoother_1dof.xml` as part of this PR. The current code in branch `mayrmt:various-fixes` does not contain any reference to `myXML.xml` anymore, yet the autotester tries to read it. Weird! Any ideas? Does the autotester always build from scratch or is there a chance, that just the update to the current version of this branch failed in some test configurations?

**Comment by cgcgcg** [comment]
@mayrmt Since compilation failed, it might be running a leftover executable from a previous build..

**Comment by mayrmt** [comment]
Just saw that I overlooked warning-as-errors compiler errors. I've pushed some changes to hopefully fix that.

**Comment by kliegeois** [comment]
Thanks @mayrmt for this PR and thanks @jhux2 for your comment.

I am currently on vacations and I cannot comment the changes before the middle of next week. Can we wait for that time to merge the PR or should the PR be merged sooner?

**Comment by mayrmt** [comment]
@kliegeois There's no hurry. Enjoy your vacation!

**Comment by jhux2** [comment]
@mayrmt I labelled this PR as WIP untiluntil it can be reviewed, in order to keep the auto-tester from needlessly retesting.

**Comment by mayrmt** [comment]
@kliegeois Here's some more background information, that hopefully motivate my changes to `InterfaceAggregationFactory`: I'm currently extending the `InterfaceAggregationFactory` to the case of multiple dual DOFs per node. This requires to distinct more clearly between DOFs and nodes, so I renamed variables to clearly indicate whether they are node-based or DOF-based. Since interface aggregates are not only applicable to solid mechanics/meshtying/contact problems, but also to other PDEs, I renamed "displacement" to "primal unknown", as this could also be a fluid velocity or a chemical species in a transport problem.

Changes to `interfaceAggregationFactory` are purely cosmetic. I haven't changed its behavior, yet.

This PR contains all preparatory steps for the extension to multiple DOFs per node. A separate PR will then bring in the new implementation and tests.

**Comment by kliegeois** [comment]
Thanks @mayrmt for the context!

I will be back in the office tomorrow.

Is the objective of the PR to have multiple primal or dual DOFs per node?

I will have to verify tomorrow, but I think that the current implementation can already support both of those cases provided that some assumptions hold true. At least the tests that I made several months ago were fine.

Nevertheless, the renaming is a good thing and I am looking forward to review your changes regarding the number of DOFs per node.

I will give a review of your PR tomorrow.

**Comment by mayrmt** [comment]
@kliegeois This PR is not about multiple DOFs per node, but the next one will be. 

I saw your implementation for the multiple-dofs-per-node case, though I don't get a correct coarse level map from it. As far as  I saw, the test in `packages/muelu/tests/meshtying/` just tests the single-dof-per-node case. 

Anyways, take your time. There's no rush.

**Comment by kliegeois** [comment]
@mayrmt , thanks again for the renaming and the cleanup, I think that the InterfaceAggregation factory is easier to understand now and, as you stated, uses more general names.

The PR looks fine to me.

In your next PR about multiple DOFs per node, could you add some tests?
I tested that capability in my own code and it worked fine. However, I did not try all possible cases.
I would be interested to try your future developments on my examples.

**Comment by mayrmt** [comment]
@kliegeois Thanks for the review and the approval.

Removing the WIP label to get this merged...

**Pull request merged**
