### PR TITLE
MueLu: tests: add ETI for certain Galeri functions

### PR DESCRIPTION
**Pull request by jhux2**
Implement ETI for the Galeri function CreateMap that is used by MueLu's
unit tests.  Addresses issue #2232.

Note that this does not rely on having ETI enabled within Trilinos.

@trilinos/<teamName>

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

## Additional Information

---
This change is [Reviewable](https://reviewable.io/reviews/trilinos/trilinos/2248)

### CODE REVIEW

**Comment by jhux2** [comment]
So ... where do I find the autotester results?

**Comment by lucbv** [comment]
@jhux2 I see that you use `NT` as your third template argument, should it not be `NO` usually?

**Comment by jwillenbring** [comment]
@jhux2 

> So ... where do I find the autotester results?

We are still in the process of making this visible. The major hurdle has been overcome - submitting the results through a new test driver into an upgraded version of CDash that handles single configure, build, test submissions, but there are some smaller issues related to making it clear how to find the results and moving the testing to the new driver that have yet to be handled.

**Comment by jhux2** [comment]
> We are still in the process of making this visible. The major hurdle has been overcome - submitting the results through a new test driver into an upgraded version of CDash that handles single configure, build, test submissions, but there are some smaller issues related to making it clear how to find the results and moving the testing to the new driver that have yet to be handled.

@jwillenbring So for the time being, if the autotester does not pass, how should we proceed?

**Comment by jhux2** [comment]
> Seems reasonable. Does it make sense to add other ETIs?

Yes, as they are needed.  So far, this is the only one I had problems with.

**Pull request merged**
