### PR TITLE
Kokkos + KokkosKernels Promotion To 4.3.0

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos @trilinos/kokkos-kernels 

## Motivation

Snapshot Kokkos Ecosystem 4.3.0 to Trilinos

## Testing
Various nightly testing jobs of release candidate, AT pre-test with #12863; AT

### CODE REVIEW

**Comment by ndellingwood** [comment]
The majority of the changes were pre-tested by the AT in #12863 
In that round of testing, the `ROL_example_PDE-OPT_navier-stokes_example_01_MPI_4` test timed out in the clang/11 build; if that recurs here, it may indicate candidacy to be marked with `SET_RUN_SERIAL` to test if that resolves potential issue

**Comment by ndellingwood** [comment]
I scanned the compilation errors and looked back at the code changes, I found a couple artifacts that showed up following the merge-to-master before snapshot (unrelated to merge conflicts). I'll fix these in their respective repo PRs and update the snapshots to this PR

**Comment by ndellingwood** [comment]
Merge artifacts fixed in the release PRs https://github.com/kokkos/kokkos/pull/6908 and https://github.com/kokkos/kokkos-kernels/pull/2163, and snapshots updated here

**Comment by ndellingwood** [comment]
CDash failure summary:

The clang/11 job https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=1454586 failed with reports of:
```
 ccache: error: Failed to create directory /fgs/trilinos/ccache/cache/a/c: Stale file handle 
```
@sebrowne @trilinos/framework is there a label available to clean the ccache? If not, can you give guidance?


The intel/2021.3 and gnu/8.3.0 jobs reported two panzer test failures:

* `PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2`
```
...
Belos::PseudoBlockGmresSolMgr::solve(): Warning! NaN has been detected!
terminate called after throwing an instance of 'std::logic_error'
  what():  ../Trilinos/packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp:632:

Throw number = 2

Throw test that evaluated to true: !(false)

Error!
```

* `PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3`
```
...
Belos::PseudoBlockGmresSolMgr::solve(): Warning! NaN has been detected!
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::logic_error'
std::logic_error'
  what():  ../Trilinos/packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp:632:

Throw number = 2

Throw test that evaluated to true: !(false)

Error!  what():  ../Trilinos/packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp:632:

Throw number = 2

Throw test that evaluated to true: !(false)

Error!
```

I didn't see those failures with with the test PR https://github.com/trilinos/Trilinos/pull/12863 , this is a list of the changes since that PR:

Kokkos: previous test PR sha: kokkos/kokkos@772e745a1a2ab6a0fe3e2f2692561a74cc239587
updates
* kokkos/kokkos#6903 (Cuda: Fix configuring with CMake 3.28.4)
* kokkos/kokkos#6886 (changelog)

KokkosKernels: previous test PR sha kokkos/kokkos-kernels@f909de6f4187a102326acf619140572f33ace33e
updates
* kokkos/kokkos-kernels#2157 (macro update in KokkosBlas1_axpby.hpp to resolve MueLu test failures)
* kokkos/kokkos-kernels#2148 (changelog)

The panzer test has some noisy output, maybe the change in kokkos/kokkos-kernels#2157 was sufficient to silence the issues in the MueLu tests but introduced some unexpected extra output in the panzer tests? Launching a build to check

**Comment by ndellingwood** [comment]
I bisected the failures to changes merged with https://github.com/trilinos/Trilinos/pull/12852

I retested with changing the guarded `KOKKOSKERNELS_VERSION` from `40299` to `40399` and the failing Panzer examples passed - @brian-kelley @lucbv what are your thoughts on changing the version checked to `40399`, is this a reasonable thing to do? If not, can give some suggestions or guidance on what changes may be needed?

I attached a diff of what I tested for clarity:

[tpetra-kver-patch.txt](https://github.com/trilinos/Trilinos/files/14856851/tpetra-kver-patch.txt)

**Comment by brian-kelley** [comment]
@ndellingwood I'm trying to replicate and then debug this now.

Changing the KK version threshold to 40399 is basically equivalent to reverting #12852 right? Do the panzer tests pass with KK develop which has version=40399 now? If not I would say just change
``#if KOKKOSKERNELS_VERSION >= 40299`` to ``#if 0`` to get the release out, and then I'll submit a new PR later to re-enable those paths.

**Comment by ndellingwood** [comment]
Thanks for the response @brian-kelley , I'll share a reproducer configuration with you (slight modification to the genconfig fragments posted in cdash)

> Changing the KK version threshold to 40399 is basically equivalent to reverting #12852 right?

yeah, basically :(

> Do the panzer tests pass with KK develop which has version=40399 now?

Build is almost complete, I'll let you know shortly

**Comment by brian-kelley** [comment]
@ndellingwood I would be surprised if KK develop fixes this - I just looked at a diff between develop and the release candidate, and the changes should have no effect unless a) multiple streams are used with a single spmv handle, or b) rocsparse and BSR matrices are used together. But obviously those aren't in play here because the build is serial backend.

**Comment by ndellingwood** [comment]
@brian-kelley you're right, my build just finished with the develop branch and the tests still fail there like expected

**Comment by ndellingwood** [comment]
Kokkos and KokkosKernels snapshots have been updated, @brian-kelley provided a patch to resolve the panzer example failures (sha [d21345a](https://github.com/trilinos/Trilinos/pull/12879/commits/d21345a1dd73d041ddd217d20c16e9122819364b)) , ready for retest

**Comment by rppawlo** [comment]
@brian-kelley - Thanks for getting this fixed! Could you comment on what you had to do to get the panzer tests passing? Just wondering if there is something we should look at from the panzer side for future kokkos releases.

**Comment by brian-kelley** [comment]
@rppawlo The output vector y to a ``CrsMatrix::apply`` contained NaNs on input. When beta=0, y is supposed to get completely overwritten with zero before alpha*A*x is computed. If it's just multiplied by beta (which is what was happening in the merge path implementation), 0*NaN is still NaN. So the output vector contained NaNs when it shouldn't and the Belos solver immediately failed.

It's not really a Panzer issue. We do support this beta=0 case, we just have to test it better in KokkosKernels I think: https://github.com/kokkos/kokkos-kernels/issues/2166

**Comment by rppawlo** [comment]
Thanks @brian-kelley ! The nans are most likely from panzer - added specifically to catch just this type of error. See the comments on the far right in the code block below:  
```
disc-fe/src/Panzer_AssemblyEngine_InArgs.hpp:       , alpha(Teuchos::ScalarTraits<double>::nan())   // also setup some painful and
disc-fe/src/Panzer_AssemblyEngine_InArgs.hpp:       , beta(Teuchos::ScalarTraits<double>::nan())    // hopefully loud initial values
disc-fe/src/Panzer_AssemblyEngine_InArgs.hpp:       , time(Teuchos::ScalarTraits<double>::nan())
disc-fe/src/Panzer_AssemblyEngine_InArgs.hpp:       , step_size(Teuchos::ScalarTraits<double>::nan())
disc-fe/src/Panzer_AssemblyEngine_InArgs.hpp:       , alpha(Teuchos::ScalarTraits<double>::nan())   // also setup some painful and
disc-fe/src/Panzer_AssemblyEngine_InArgs.hpp:       , beta(Teuchos::ScalarTraits<double>::nan())    // hopefully loud initial values
disc-fe/src/Panzer_AssemblyEngine_InArgs.hpp:       , time(Teuchos::ScalarTraits<double>::nan())
disc-fe/src/Panzer_AssemblyEngine_InArgs.hpp:       , step_size(Teuchos::ScalarTraits<double>::nan())
```

**Comment by ndellingwood** [comment]
CDash summary:

Two jobs failed at compilation (Trilinos_PR_gcc-8.3.0, Trilinos_PR_gcc-8.3.0-debug), looks like changes in sha [d21345a](https://github.com/trilinos/Trilinos/pull/12879/commits/d21345a1dd73d041ddd217d20c16e9122819364b) left a potentially unused `maxRowImbalance` variable  triggering `-Werror` in various places:
```
../Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:5089:18: error: variable ‘maxRowImbalance’ set but not used [-Werror=unused-but-set-variable]
     LocalOrdinal maxRowImbalance = 0;
```

I'm guessing the variable just needs to be moved to a guarded region, taking a look now

**Comment by ndellingwood** [comment]
Just pushed b1a4376ee32f4fdbd3946318135e5c96b9e0d073 which should resolve the `-Werror`

**Review by lucbv — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
