### PR TITLE
Tpetra: Transfer and fill complete refactor

### PR DESCRIPTION
**Pull request by NyquilDreams**
@trilinos/tpetra @jhux2

## Motivation

 Converts transfer and fill complete to use Kokkos to make it performance portable.

## Related Issues

- Related to
  - #11689 
  - #12297.

## Stakeholder Feedback

N/A

## Testing

Covered by existing unit tests.

### CODE REVIEW

**Comment by jhux2** [comment]
@NyquilDreams Please change to merge against `develop` branch.

**Comment by jhux2** [comment]
@trilinos/framework Two testing instances failed, both in the test `TrilinosInstallTests_reduced_tarball`.  This also happened last week in PR #13282.

**Comment by achauphan** [comment]
> @trilinos/framework Two testing instances failed, both in the test `TrilinosInstallTests_reduced_tarball`. This also happened last week in PR #13282.

@jhux2 after looking into this, the `TrilinosInstallTests_reduced_tarball` failure for this PR is likely due to a file system hiccup causing the test to hit its timeout. I tried searching the test to see if there was a history of this timing out, and didn't find another timeout in the last 6 months ([CDash Query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2024-04-22&end=2024-10-22&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=TrilinosInstallTests_reduced_tarball&field2=buildname&compare2=64&value2=anaconda&field3=details&compare3=63&value3=Timeout)).

As for the `TrilinosInstallTests_reduced_tarball` failure for the `aue-anaconda` builds seen on CDash, this has been known about and was introduced in #13421 ([CDash Query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2024-04-22&end=2024-10-22&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=TrilinosInstallTests_reduced_tarball&field2=buildname&compare2=63&value2=anaconda)). We turned the `aue-anaconda` PR test to be a non-blocking one as we scheduled a fix for this soon... apologies as this causes a bad UX when reading CDash and is very misleading. :(

**Comment by achauphan** [comment]
> @trilinos/framework Two testing instances failed, both in the test `TrilinosInstallTests_reduced_tarball`. This also happened last week in PR #13282.

@jhux2 after looking into this, the `TrilinosInstallTests_reduced_tarball` failure for this PR is likely due to a file system hiccup causing the test to hit its timeout. I tried searching the test to see if there was a history of this timing out, and didn't find another timeout in the last 6 months ([CDash Query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2024-04-22&end=2024-10-22&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=TrilinosInstallTests_reduced_tarball&field2=buildname&compare2=64&value2=anaconda&field3=details&compare3=63&value3=Timeout)).

As for the `TrilinosInstallTests_reduced_tarball` failure for the `aue-anaconda` builds seen on CDash, this has been known about and was introduced in #13421 ([CDash Query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2024-04-22&end=2024-10-22&filtercount=2&showfilters=1&filtercombine=and&field1=testname&compare1=61&value1=TrilinosInstallTests_reduced_tarball&field2=buildname&compare2=63&value2=anaconda)). We turned the `aue-anaconda` PR test to be a non-blocking one as we scheduled a fix for this soon... apologies as this causes a bad UX when reading CDash and is very misleading. :(

**Comment by jhux2** [comment]
@achauphan Thanks for looking into this and the explanation.

**Review by jhux2 — APPROVED** [review]
lgtm

**Pull request merged**
