### PR TITLE
Ifpack2 - put complex into instanciataion list

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
this fixes issue #2871 and will build ifpack2 with complex. as PR testing does not support complex, PR testing here should pass.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@lucbv @mhoemmen I already tested them. It compiles.

**Comment by kyungjoo-kim** [comment]
@lucbv It looks like that you can generate complex unit tests in ifpack2 but I could not. I use the configure script with complex on but it is not tested. How do you do that ?

**Comment by kyungjoo-kim** [comment]
@lucbv 
I set ``Trilinos_ENABLE_COMPLEX_DOUBLE=ON``, ``Teuchos_ENABLE_COMPLEX=ON`` and  ``Tpetra_INST_COMPLEX_DOUBLE=ON`` but it does not include ifpack2 complex eti. help me.

**Comment by mhoemmen** [comment]
@kyungjoo-kim wrote:
> It correctly build the library with std::complex but somehow it does not include in the test.

What is the value of `Ifpack2_ETI_SCALARS` in your `CMakeCache.txt` file?

**Comment by kyungjoo-kim** [comment]
double,complex<double> but Teuchos testing does not include complex.

**Comment by lucbv** [comment]
@kyungjoo-kim, here is what I have in my configure script:
```
	    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
	    -D BUILD_SHARED_LIBS=ON \
	    -D Trilinos_ENABLE_CXX11=ON \
            -D Trilinos_ENABLE_Fortran=OFF \
	    -D TPL_ENABLE_MPI=ON \
	    -D Trilinos_ENABLE_OpenMP=ON \
            -D Trilinos_ENABLE_COMPLEX_DOUBLE=ON \
	    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
	    -D Trilinos_ENABLE_Ifpack2=ON \
              -D Ifpack2_ENABLE_TESTS=ON \
              -D Ifpack2_ENABLE_EXAMPLES=ON \
```
this eventually leads to the following configuration output:
```
Processing ETI support: Ifpack2
-- Ifpack2: Processing ETI / test support
-- Enabled Scalar types:        double|std::complex<double>
-- Enabled LocalOrdinal types:  int
-- Enabled GlobalOrdinal types: int|long long
-- Enabled Node types:          Kokkos::Compat::KokkosOpenMPWrapperNode
-- User/Downstream ETI set: 
-- Excluded type combinations: 
-- Set of enabled types, before exclusions: S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long}
```

I am using the sems modules loaded from the `Trilinos/cmake/load_sems_dev_env.sh`, this should be fairly standard. Feel free to stop by if you continue to have problems enabling complex.

**Comment by kyungjoo-kim** [comment]
Oh.... This should not be merged.

**Comment by kyungjoo-kim** [comment]
I am going to place another PR.

**Comment by mhoemmen** [comment]
@kyungjoo-kim Sorry; I'll wait next time :)

**Pull request merged**
