### PR TITLE
MueLu: Remove coupled aggregation

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
- Removes coupled aggregation capabilities.
- Does **not** remove construction of tentative P when aggregates cross process boundaries. The reason for this is that other types of aggregation (brick at least) might construct aggregates that span more than one process.

Addresses #11682. Should merge after #11684.

### CODE REVIEW

**Comment by jhux2** [comment]
Dashboard error:
```
[CTest: warning matched] /usr/bin/ld: warning: libgfortran.so.3, needed by /lib64/liblapack.so.3, may conflict with libgfortran.so.5
packages/stokhos/src/libstokhos_muelu_mp_16_cuda.a(MueLu_FacadeClassFactory_MP_Vector_16_Cuda.cpp.o): In function `MueLu::FacadeClassFactory<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Cuda> >, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> >::FacadeClassFactory()':
tmpxft_00015e64_00000000-6_MueLu_FacadeClassFactory_MP_Vector_16_Cuda.cudafe1.cpp:(.text._ZN5MueLu18FacadeClassFactoryIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEC2Ev[_ZN5MueLu18FacadeClassFactoryIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEC2Ev]+0x83): undefined reference to `MueLu::FacadeSimple<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Cuda> >, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> >::FacadeSimple()'
tmpxft_00015e64_00000000-6_MueLu_FacadeClassFactory_MP_Vector_16_Cuda.cudafe1.cpp:(.text._ZN5MueLu18FacadeClassFactoryIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEC2Ev[_ZN5MueLu18FacadeClassFactoryIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEC2Ev]+0x2b3): undefined reference to `MueLu::FacadeBGS2x2<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Cuda> >, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> >::FacadeBGS2x2()'
packages/stokhos/src/libstokhos_muelu_mp_16_cuda.a(MueLu_FacadeClassFactory_MP_Vector_16_Cuda.cpp.o): In function `MueLu::FacadeClassFactory<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Cuda> >, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> >::FacadeClassFactory()':
tmpxft_00015e64_00000000-6_MueLu_FacadeClassFactory_MP_Vector_16_Cuda.cudafe1.cpp:(.text._ZN5MueLu18FacadeClassFactoryIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEC1Ev[_ZN5MueLu18FacadeClassFactoryIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEC1Ev]+0x132): undefined reference to `MueLu::FacadeSimple<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Cuda> >, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> >::FacadeSimple()'
tmpxft_00015e64_00000000-6_MueLu_FacadeClassFactory_MP_Vector_16_Cuda.cudafe1.cpp:(.text._ZN5MueLu18FacadeClassFactoryIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEC1Ev[_ZN5MueLu18FacadeClassFactoryIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEC1Ev]+0x36e): undefined reference to `MueLu::FacadeBGS2x2<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Cuda> >, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> >::FacadeBGS2x2()'
packages/stokhos/src/libstokhos_muelu_mp_16_cuda.a(MueLu_FacadeClassFactory_MP_Vector_16_Cuda.cpp.o):(.data.rel.ro._ZTVN5MueLu12FacadeSimpleIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEE[_ZTVN5MueLu12FacadeSimpleIN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEE]+0x38): undefined reference to `MueLu::FacadeSimple<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Cuda> >, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> >::SetParameterList(Teuchos::ParameterList const&)'
packages/stokhos/src/libstokhos_muelu_mp_16_cuda.a(MueLu_FacadeClassFactory_MP_Vector_16_Cuda.cpp.o):(.data.rel.ro._ZTVN5MueLu12FacadeBGS2x2IN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEE[_ZTVN5MueLu12FacadeBGS2x2IN6Sacado2MP6VectorIN7Stokhos18StaticFixedStorageIidLi16EN6Kokkos4CudaEEEEEixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIS7_NS6_9CudaSpaceEEEEE]+0x38): undefined reference to `MueLu::FacadeBGS2x2<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Cuda> >, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> >::SetParameterList(Teuchos::ParameterList const&)'
collect2: error: ld returned 1 exit status
```

**Comment by jhux2** [comment]
@cgcgcg Progress, just one test failing now:

<details>

```
Testing: default/EasyParameterListInterpreter/aggregation5_np4.xml

p=3: *** Caught standard std::exception of type 'std::logic_error' :

 ../Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_def.hpp:207:
 
 Throw number = 1
 
 Throw test that evaluated to true: !(!aggregates->AggregatesCrossProcessors())
 
 Error!

p=0: *** Caught standard std::exception of type 'std::logic_error' :

 ../Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_def.hpp:207:
 
 Throw number = 1
 
 Throw test that evaluated to true: !(!aggregates->AggregatesCrossProcessors())
 
 Error!

p=2: *** Caught standard std::exception of type 'std::logic_error' :

 ../Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_def.hpp:207:
 
 Throw number = 1
 
 Throw test that evaluated to true: !(!aggregates->AggregatesCrossProcessors())
 
 Error!

p=1: *** Caught standard std::exception of type 'std::logic_error' :

 ../Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_def.hpp:207:
 
 Throw number = 1
 
 Throw test that evaluated to true: !(!aggregates->AggregatesCrossProcessors())
 
 Error!
[ascic114:09472] *** Process received signal ***
[ascic114:09472] Signal: Segmentation fault (11)
[ascic114:09472] Signal code: Address not mapped (1)
[ascic114:09472] Failing at address: 0x30
[ascic114:09471] *** Process received signal ***
[ascic114:09471] Signal: Segmentation fault (11)
[ascic114:09471] Signal code: Address not mapped (1)
[ascic114:09471] Failing at address: 0x30
[ascic114:09469] *** Process received signal ***
[ascic114:09469] Signal: Segmentation fault (11)
[ascic114:09469] Signal code: Address not mapped (1)
[ascic114:09469] Failing at address: 0x30
[ascic114:09470] *** Process received signal ***
[ascic114:09470] Signal: Segmentation fault (11)
[ascic114:09470] Signal code: Address not mapped (1)
[ascic114:09470] Failing at address: 0x30
[ascic114:09469] [ 0] [ascic114:09472] [ 0] [ascic114:09471] [ 0] [ascic114:09470] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7f386cb77630]
[ascic114:09471] [ 1] /lib64/libpthread.so.0(+0xf630)[0x7fd63504a630]
[ascic114:09469] [ 1] /lib64/libpthread.so.0(+0xf630)[0x7fe479372630]
[ascic114:09472] [ 1] /lib64/libpthread.so.0(+0xf630)[0x7f67961bc630]
[ascic114:09470] [ 1] /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/lib64/libstdc++.so.6(_ZNSo5flushEv+0x1b)[0x7fd63557b43b]
[ascic114:09469] [ 2] /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/lib64/libstdc++.so.6(_ZNSo5flushEv+0x1b)[0x7f67966ed43b]
[ascic114:09470] [ 2] /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/lib64/libstdc++.so.6(_ZNSo5flushEv+0x1b)[0x7fe4798a343b]
[ascic114:09472] [ 2] /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/lib64/libstdc++.so.6(_ZNSo5flushEv+0x1b)[0x7f386d0a843b]
[ascic114:09471] [ 2] /scratch/trilinos/jenkins/ascic114/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos19ActiveRCPNodesSetupD1Ev+0x44)[0x7fd6375bfab4]
[ascic114:09469] [ 3] /scratch/trilinos/jenkins/ascic114/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos19ActiveRCPNodesSetupD1Ev+0x44)[0x7f386f0ecab4]
[ascic114:09471] [ 3] /scratch/trilinos/jenkins/ascic114/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos19ActiveRCPNodesSetupD1Ev+0x44)[0x7f6798731ab4]
[ascic114:09470] [ 3] /scratch/trilinos/jenkins/ascic114/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos19ActiveRCPNodesSetupD1Ev+0x44)[0x7fe47b8e7ab4]
[ascic114:09472] [ 3] /lib64/libc.so.6(__cxa_finalize+0x9a)[0x7f386c7d405a]
[ascic114:09471] [ 4] /lib64/libc.so.6(__cxa_finalize+0x9a)[0x7f6795e1905a]
[ascic114:09470] [ 4] /lib64/libc.so.6(__cxa_finalize+0x9a)[0x7fd634ca705a]
[ascic114:09469] [ 4] /lib64/libc.so.6(__cxa_finalize+0x9a)[0x7fe478fcf05a]
[ascic114:09472] [ 4] /scratch/trilinos/jenkins/ascic114/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(+0x2c2d3)[0x7f386f08e2d3]
[ascic114:09471] *** End of error message ***
/scratch/trilinos/jenkins/ascic114/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(+0x2c2d3)[0x7f67986d32d3]
[ascic114:09470] *** End of error message ***
/scratch/trilinos/jenkins/ascic114/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(+0x2c2d3)[0x7fe47b8892d3]
[ascic114:09472] *** End of error message ***
/scratch/trilinos/jenkins/ascic114/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(+0x2c2d3)[0x7fd6375612d3]
[ascic114:09469] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node ascic114 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

</details>

**Comment by jhux2** [comment]
@cgcgcg Is there overlap with the include removal?

**Comment by cgcgcg** [comment]
@jhux2 Yes, only the last commit should actually be merged as part of this PR. All other commits will be merged by #11684.

**Review by jhux2 — APPROVED** [review]
I reviewed only `7073b7543bc8399e79c6f433b27177ec50363900`.  Lgtm, thanks!

**Pull request merged**
