### PR TITLE
Intrepid2 - compiling on hip compiler

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
## Motivation

Testing the code in compiling with AMD and hip compiler.

## Stakeholder Feedback

@rppawlo I confirmed that the all unit tests in Intrepid2 pass on caraway. Current Intrepid2 unit test may not cover all SACADO use case though. 

## Additional Information

@CamelliaDPG The hip compiler gets an error while compiling your test.
```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/unit-test/MonolithicExecutable/StructuredIn\
tegrationTests.cpp:101:44: error: cannot pass non-trivial object of type 'basic_string<char>' to variadic fun\
ction; expected type from format string was 'char *' [-Wnon-pod-varargs]
                                           "cellMeasures point dimension (" + std::to_string(cellMeasures.ext\
ent_int(1)) +
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
~~~~~~~~~~~~~
``` 
Currently I fix this issue by removing the ``std::to_string`` and simplifying the error message.

### CODE REVIEW

**Comment by CamelliaDPG** [comment]
> @CamelliaDPG The hip compiler gets an error while compiling your test.
> 
> ```
> /ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/unit-test/MonolithicExecutable/StructuredIn\
> tegrationTests.cpp:101:44: error: cannot pass non-trivial object of type 'basic_string<char>' to variadic fun\
> ction; expected type from format string was 'char *' [-Wnon-pod-varargs]
>                                            "cellMeasures point dimension (" + std::to_string(cellMeasures.ext\
> ent_int(1)) +
>                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
> ~~~~~~~~~~~~~
> ```
> 
> Currently I fix this issue by removing the `std::to_string` and simplifying the error message.

@kyungjoo-kim, thanks for letting me know.  Could you fix by replacing that line with the following:

```
INTREPID2_TEST_FOR_EXCEPTION_DEVICE_SAFE(cellMeasures.extent_int(1) != vectorDataLeft.extent_int(2), std::invalid_argument,
                                           std::string("cellMeasures point dimension (" + std::to_string(cellMeasures.extent_int(1)) +
                                           ") must match vectorData point dimension (" + std::to_string(vectorDataLeft.extent_int(2)) + ")").c_str());
```

If I've understood the compiler error, this should fix it while maintaining behavior.  Please let me know if that doesn't do the trick.

**Comment by kyungjoo-kim** [comment]
@CamelliaDPG That seems to be working fine.

**Comment by kyungjoo-kim** [comment]
@etphipp I modify sacado cuda guard with __HIPCC__. I do not touch about memory pool dfad and other parts that exposes cuda details.

**Comment by kyungjoo-kim** [comment]
As reported from @rppawlo , DFAD is not working on HIP. This PR does not address the problem as it cannot remove the entire temporal variable usages.
```
	 28 - Intrepid2_unit-test_Discretization_Basis_HCURL_QUAD_In_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	 29 - Intrepid2_unit-test_Discretization_Basis_HCURL_QUAD_In_FEM_test_01_HIP_SLFAD_DFAD (Subprocess aborted)
	 38 - Intrepid2_unit-test_Discretization_Basis_HCURL_HEX_In_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	 39 - Intrepid2_unit-test_Discretization_Basis_HCURL_HEX_In_FEM_test_01_HIP_SLFAD_DFAD (Subprocess aborted)
	 48 - Intrepid2_unit-test_Discretization_Basis_HCURL_TRI_In_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	 58 - Intrepid2_unit-test_Discretization_Basis_HCURL_TET_In_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	 78 - Intrepid2_unit-test_Discretization_Basis_HDIV_QUAD_In_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	 79 - Intrepid2_unit-test_Discretization_Basis_HDIV_QUAD_In_FEM_test_01_HIP_SLFAD_DFAD (Subprocess aborted)
	 88 - Intrepid2_unit-test_Discretization_Basis_HDIV_HEX_In_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	 89 - Intrepid2_unit-test_Discretization_Basis_HDIV_HEX_In_FEM_test_01_HIP_SLFAD_DFAD (Subprocess aborted)
	 98 - Intrepid2_unit-test_Discretization_Basis_HDIV_TRI_In_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	108 - Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	145 - Intrepid2_unit-test_Discretization_Basis_HGRAD_LINE_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	155 - Intrepid2_unit-test_Discretization_Basis_HGRAD_QUAD_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	156 - Intrepid2_unit-test_Discretization_Basis_HGRAD_QUAD_Cn_FEM_test_01_HIP_SLFAD_DFAD (Subprocess aborted)
	167 - Intrepid2_unit-test_Discretization_Basis_HGRAD_HEX_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	168 - Intrepid2_unit-test_Discretization_Basis_HGRAD_HEX_Cn_FEM_test_01_HIP_SLFAD_DFAD (Subprocess aborted)
	181 - Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	195 - Intrepid2_unit-test_Discretization_Basis_HGRAD_TET_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	209 - Intrepid2_unit-test_Discretization_Basis_HVOL_LINE_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	219 - Intrepid2_unit-test_Discretization_Basis_HVOL_QUAD_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	220 - Intrepid2_unit-test_Discretization_Basis_HVOL_QUAD_Cn_FEM_test_01_HIP_SLFAD_DFAD (Subprocess aborted)
	229 - Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	230 - Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_test_01_HIP_SLFAD_DFAD (Subprocess aborted)
	239 - Intrepid2_unit-test_Discretization_Basis_HVOL_TRI_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
	249 - Intrepid2_unit-test_Discretization_Basis_HVOL_TET_Cn_FEM_test_01_HIP_DFAD_DFAD (Subprocess aborted)
```

**Comment by kyungjoo-kim** [comment]
@ndellingwood This also fixes #10271.

**Comment by etphipp** [comment]
The Sacado changes seem fine, but I'm surprised this didn't come up in @rppawlo's porting to HIP.

**Comment by kyungjoo-kim** [comment]
@etphipp The DFAD error pops up from high order elements and empire may not use the high order elements with DFAD. This DFAD error is runtime.

**Comment by kyungjoo-kim** [comment]
@etphipp Does SACADO test DFAD on device ? I am not sure if we can simply ignore this device allocation and DFAD issue for now or we need to ask AMD to add the feature with higher priority.

**Comment by CamelliaDPG** [comment]
Oh, sorry!  Hit the wrong button, and closed the PR.  Just reopened.

**Comment by kyungjoo-kim** [comment]
@CamelliaDPG Then could you approve this PR as well ?

**Review by CamelliaDPG — APPROVED** [review]

**Comment by mperego** [comment]
Thanks @kyungjoo-kim !

**Pull request merged**
