### PR TITLE
Tpetra: make sort optional for LTG

### PR DESCRIPTION
**Pull request by csiefer2**
Making sort optional for LTG

### CODE REVIEW

**Comment by mhoemmen** [comment]
@csiefer2 @jhux2 Should we label this "Results Impacting"?

**Comment by csiefer2** [comment]
@mhoemmen  Nope. Defaults are not changing

**Comment by srajama1** [comment]
@csiefer2 : Why is sort optional ?

**Comment by csiefer2** [comment]
@srajama1 It happens to be optional (defaulting to sorted) for all other SpGEMM kernels.  But I missed it for LTG.  This is a "make everything work the same way" thing.

**Comment by srajama1** [comment]
@csiefer2 Sure got it. Thanks !

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> Nope. Defaults are not changing

Sweet; just checking :D

**Pull request merged**
