### PR TITLE
Kokkos prerelease test

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos-kernels @trilinos/kokkos 

## Motivation

Testing of release candidate branches

## Related Issues

* Closes `put-issue-number-here`

## Testing
AT for additional feedback to nightly integration builds

### CODE REVIEW

**Comment by ndellingwood** [comment]
PR for additional testing feedback, @crtrott @lucbv @dalg24 @masterleinad

**Comment by ndellingwood** [comment]
The `rhel8_sems-cuda-11.4.2-gnu-10.1.0-openmpi-4.1.6_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables` job had 36 failures in intrepid2 unit tests

Sample output snips from [Intrepid2_unit-test_Discretization_Basis_HCURL_HEX_In_FEM_test_02_CUDA_DFAD_DFAD_MPI_1](https://trilinos-cdash.sandia.gov/test/67073891) :

```
...
Order: 1: Computing values and curls for 5 cells and 10 points using team-level getValues function
Max Recommended team size: 4, Requested team size: 10
Max Recommended team size: 4, Requested team size: 10
[Intrepid2] Error in file /scratch/trilinos/workspace/PR_cuda/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_HEX_In_FEMDef.hpp, line 618
# repeated many times
            Test that evaluated to true: !((subcellDim == -1) && (subcellOrdinal == -1))
# repeated many times
            >>> ERROR: (Intrepid2::Basis_HCURL_HEX_In_FEM::getValues), The capability of selecting subsets of basis functions has not been implemented yet. 
# repeated many times
:0: : block: [0,0,0], thread: [0,0,0] Assertion `[Intrepid2] Abort
` failed.
# similar output repeated many times
```

The output message pattern is similar from the sample of unit test failures I looked at

@trilinos/intrepid2 @mperego @CamelliaDPG can you help me understand the output messages? In particular, what would trigger the ` >>> ERROR: (Intrepid2::Basis_HCURL_HEX_In_FEM::getValues), The capability of selecting subsets of basis functions has not been implemented yet` message?

**Comment by mperego** [comment]
That's weird. Any reason why the default instantiation of `subcellDim` and `subcellOrdinal` would not work?
https://github.com/trilinos/Trilinos/blob/develop/packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_HEX_In_FEM.hpp#L196C1-L203C62

Or maybe is the `INTREPID2_TEST_FOR_ABORT` macro that is not working?

**Comment by mperego** [comment]
> @mperego thanks for the info, this is helpful. Are `subcellDim` and/or `subcellOrdinal` used for setting a team_size or related variable in the getValues function? If so, the use of -1 may be incompatible with updates to internal handling of negative team size, for example in [kokkos/kokkos#7423](https://github.com/kokkos/kokkos/pull/7423)

No, at the moment they are not used at all.

**Comment by ndellingwood** [comment]
@mperego thanks for clarifying (I missed that you mentioned that prior). I'm working on reproducing, hopefully the debugger gives me useful info to share

**Comment by ndellingwood** [comment]
Stacktrace for 

```
#0  0x00007fffa788b94c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007fffa783e646 in raise () from /lib64/libc.so.6
#2  0x00007fffa78287f3 in abort () from /lib64/libc.so.6
#3  0x00000000008dd789 in Kokkos::Impl::host_abort(char const*) ()
#4  0x0000000000904ed4 in Kokkos::Impl::cuda_internal_error_abort(cudaError, char const*, char const*, int) ()
#5  0x0000000000900c57 in Kokkos::CudaSpace::impl_deallocate(char const*, void*, unsigned long, unsigned long, Kokkos_Profiling_SpaceHandle) const ()
#6  0x0000000000900cde in Kokkos::CudaSpace::deallocate(char const*, void*, unsigned long, unsigned long) const ()
#7  0x0000000000904b7b in Kokkos::Impl::CudaInternal::resize_team_scratch_space(int, long, bool) ()
#8  0x00000000004dfa76 in Kokkos::Impl::ParallelFor<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(bool), &(int Intrepid2::Test::HCURL_HEX_In_FEM_Test02<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >(bool)), 2u>, void (Kokkos::Impl::CudaTeamMember), Kokkos::DynRankView<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, Intrepid2::Basis_HCURL_HEX_In_FEM<Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> > >*, Kokkos::DynRankView<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, int>, Kokkos::TeamPolicy<Kokkos::Cuda>, Kokkos::Cuda>::ParallelFor(__nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(bool), &(int Intrepid2::Test::HCURL_HEX_In_FEM_Test02<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >(bool)), 2u>, void (Kokkos::Impl::CudaTeamMember), Kokkos::DynRankView<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, Intrepid2::Basis_HCURL_HEX_In_FEM<Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> > >*, Kokkos::DynRankView<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, int> const&, Kokkos::TeamPolicy<Kokkos::Cuda> const&) ()
#9  0x00000000004dff2d in void Kokkos::parallel_for<Kokkos::TeamPolicy<Kokkos::Cuda>, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(bool), &(int Intrepid2::Test::HCURL_HEX_In_FEM_Test02<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >(bool)), 2u>, void (Kokkos::Impl::CudaTeamMember), Kokkos::DynRankView<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, Intrepid2::Basis_HCURL_HEX_In_FEM<Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> > >*, Kokkos::DynRankView<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, int>, void>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Kokkos::TeamPolicy<Kokkos::Cuda> const&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(bool), &(int Intrepid2::Test::HCURL_HEX_In_FEM_Test02<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >(bool)), 2u>, void (Kokkos::Impl::CudaTeamMember), Kokkos::DynRankView<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, Intrepid2::Basis_HCURL_HEX_In_FEM<Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> > >*, Kokkos::DynRankView<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, int> const&) ()
#10 0x000000000047f477 in int Intrepid2::Test::HCURL_HEX_In_FEM_Test02<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >(bool) [clone .isra.0] ()
#11 0x0000000000430d16 in main ()
```

**Comment by ndellingwood** [comment]
Stacktrace for Intrepid2_unit-test_Discretization_Basis_HCURL_HEX_In_FEM_test_02_CUDA_DOUBLE_DOUBLE.exe:

```
#0  0x00007fffa788b94c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007fffa783e646 in raise () from /lib64/libc.so.6
#2  0x00007fffa78287f3 in abort () from /lib64/libc.so.6
#3  0x0000000000b573f9 in Kokkos::Impl::host_abort(char const*) ()
#4  0x0000000000b7eea4 in Kokkos::Impl::cuda_internal_error_abort(cudaError, char const*, char const*, int) ()
#5  0x0000000000b7ac27 in Kokkos::CudaSpace::impl_deallocate(char const*, void*, unsigned long, unsigned long, Kokkos_Profiling_SpaceHandle) const ()
#6  0x0000000000b7acae in Kokkos::CudaSpace::deallocate(char const*, void*, unsigned long, unsigned long) const ()
#7  0x0000000000b7eb4b in Kokkos::Impl::CudaInternal::resize_team_scratch_space(int, long, bool) ()
#8  0x00000000004ccf36 in Kokkos::Impl::ParallelFor<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(bool), &(int Intrepid2::Test::HCURL_HEX_In_FEM_Test02<double, double, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >(bool)), 2u>, void (Kokkos::Impl::CudaTeamMember), Kokkos::DynRankView<double, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, Intrepid2::Basis_HCURL_HEX_In_FEM<Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, double, double>*, Kokkos::DynRankView<double, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, int>, Kokkos::TeamPolicy<Kokkos::Cuda>, Kokkos::Cuda>::ParallelFor(__nv_hdl_wrapper_t<false, false, __nv_dl_tag<int (*)(bool), &(int Intrepid2::Test::HCURL_HEX_In_FEM_Test02<double, double, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >(bool)), 2u>, void (Kokkos::Impl::CudaTeamMember), Kokkos::DynRankView<double, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, Intrepid2::Basis_HCURL_HEX_In_FEM<Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, double, double>*, Kokkos::DynRankView<double, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >, int> const&, Kokkos::TeamPolicy<Kokkos::Cuda> const&) ()
#9  0x0000000000481fce in int Intrepid2::Test::HCURL_HEX_In_FEM_Test02<double, double, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >(bool) [clone .isra.0] ()
#10 0x0000000000425576 in main ()
```

**Comment by ndellingwood** [comment]
@sebrowne adding note for occurrence of `nvcc error   : 'ptxas' died due to signal 11 (Invalid memory reference)` in the Cuda job, similar to what occurs with the nightly kokkos integration build https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=1950837

**Pull request closed without merging**
