### PR TITLE
MueLu: 

### LINKED ISSUE #5952: MueLu: expected type-specifier error
## Bug Report
@trilinos/\MueLu

### Description
Following  error when compile in Ubuntu with gcc

> MueLu_FactoryManager_def.hpp:163:108: error: expected type-specifier before ‘ScaledNullspaceFactory’

### PR DESCRIPTION
**Pull request by hillyuan**
@trilinos/MueLu

## Description
Compilation error exists when compiled in Ubuntu with gcc

> MueLu_FactoryManager_def.hpp:163:108: error: expected type-specifier before ‘ScaledNullspaceFactory’  == "Scaled Nullspace")   return SetAndReturnDefaultFactory(varName, rcp(new ScaledNullspaceFactory()));

## Motivation and Context
It seems that the above error is due to that the file "MueLu_ScaledNullspaceFactory_fwd.hpp" is not included in declaration.   And, after includes the above file, declaration of "using SNF = ScaledNullspaceFactory<Scalar,LocalOrdinal,GlobalOrdinal,Node>;" in file MueLu_ParameterListInterpreter_def.hpp in not needed anymore

## Related Issues

* Closes #5952

## How Has This Been Tested?
Compilation tested in Ubuntu with gcc

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by DABH** [comment]
@hillyuan This allows Trilinos to successfully build again (nice!) but when I build my application which uses MueLu, I get the following linker errors still:
```
/usr/bin/ld: CMakeFiles/bar.dir/main.cpp.o:(.data.rel.ro._ZTVN5MueLu22ScaledNullspaceFactoryIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN5MueLu22ScaledNullspaceFactoryIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0x58): undefined reference to `MueLu::ScaledNullspaceFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::GetValidParameterList() const'
/usr/bin/ld: CMakeFiles/solver_benchmarking.dir/main.cpp.o:(.data.rel.ro._ZTVN5MueLu22ScaledNullspaceFactoryIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN5MueLu22ScaledNullspaceFactoryIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0x60): undefined reference to `MueLu::ScaledNullspaceFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::DeclareInput(MueLu::Level&) const'
/usr/bin/ld: CMakeFiles/bar.dir/main.cpp.o:(.data.rel.ro._ZTVN5MueLu22ScaledNullspaceFactoryIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN5MueLu22ScaledNullspaceFactoryIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0x68): undefined reference to `MueLu::ScaledNullspaceFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::Build(MueLu::Level&) const'
/usr/bin/ld: CMakeFiles/bar.dir/main.cpp.o:(.data.rel.ro._ZTVN5MueLu22ScaledNullspaceFactoryIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE[_ZTVN5MueLu22ScaledNullspaceFactoryIdiiN6Kokkos6Compat23KokkosDeviceWrapperNodeINS1_6OpenMPENS1_9HostSpaceEEEEE]+0xc0): undefined reference to `non-virtual thunk to MueLu::ScaledNullspaceFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >::GetValidParameterList() const'
```
So I think this PR may need a little more work to make it fully working...

Sounds like maybe missing explicit template instantiations?

**Comment by hillyuan** [comment]
@DABH I see. It seems that a new class like ScaledNullspaceFactory_kokkos, which use Kokkos::Compat::KokkosDeviceWrapperNode as a template member, be needed and replace ScaledNullspaceFactory by this class when HAVE_MUELU_KOKKOS_REFACTOR turns on.  But it is a little difficult for me because I am not a development member of MueLu. Suppose someone else would do it.

**Comment by mhoemmen** [comment]
@trilinos/muelu

**Comment by jhux2** [comment]
Superceded by #5963.

**Pull request closed without merging**
