### PR TITLE
ROL: hidden virtual function warning fixes

### PR DESCRIPTION
**Pull request by japlews**
@trilinos/rol

## Motivation
Fix some warnings (suspect code?) about hidden virtual functions seen in Sierra builds.

### CODE REVIEW

**Comment by japlews** [comment]
@dridzal this is the PR related to our Sierra discussion.

**Comment by japlews** [comment]
@dridzal @cgcgcg Going back through some old PRs... Can I get a review of these chages?

**Comment by dridzal** [comment]
@japlews :  I'm doing ROL maintenance today, and I can incorporate your changes directly in the ROL private repo.  Then I'll perform the merge with the public Trilinos repo.  I'll leave the PR open until that's done, and I'll let you know.

**Comment by japlews** [comment]
@dridzal Sounds great, thanks!

**Comment by dridzal** [comment]
@japlews :  These changes have been merged with commit 75dfc04ddb6b62292dd20c4c451083954dc4f17e in Trilinos PR #12513.

**Comment by japlews** [comment]
Thanks @dridzal

**Pull request closed without merging**
