### PR TITLE
Shylu::FastILU fix for complex types

### PR DESCRIPTION
**Pull request by jgfouca**
The diagFact view is Real, not Scalar, so must be assigned to Reals.

@trilinos/shylu 

## Motivation
Code did not build when complex doubles are enabled.

## Testing
Built and ran ifpack2 tests that use shylu with `-DTrilinos_ENABLE_COMPLEX_DOUBLE=ON`

### CODE REVIEW

**Review by lucbv — APPROVED** [review]
Thanks for the update, did you investigate why the auto-tester did not catch this?
We should have a build with complex type enabled somewhere?

**Comment by jgfouca** [comment]
@lucbv , I think that's probably a question for the Trilinos Framework team? I don't know how the Trilinos AT is set up. Do the packages have control over the test configurations?

**Comment by lucbv** [comment]
I see that the unit-test are guarded with: `IF(Tpetra_INST_DOUBLE AND Ifpack2_ENABLE_ShyLU_NodeFastILU)` do these get enabled by our auto-tester builds?

**Comment by jgfouca** [comment]
@lucbv , @srajama1 , I can see looking at the old cdash for the original block FastILU PR that Ifpack2_FILU* tests are not getting run, at least for the builds I looked at.

**Comment by jgfouca** [comment]
Investigating further, in this file:

`packages/ifpack2/cmake/Dependencies.cmake`

I see this:

```
SET(LIB_REQUIRED_DEP_PACKAGES Belos Teuchos Tpetra KokkosKernels)
SET(LIB_OPTIONAL_DEP_PACKAGES Xpetra Zoltan2Core ThyraTpetraAdapters Amesos2 ShyLU_NodeBasker ShyLU_NodeHTS ShyLU_NodeFastILU)
SET(TEST_REQUIRED_DEP_PACKAGES Belos Galeri)
SET(TEST_OPTIONAL_DEP_PACKAGES Amesos2 ShyLU_NodeHTS ML AztecOO Epetra)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS HYPRE Cholmod Lemon METIS MPI)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS QD HYPRE METIS)
```

I think if we added `ShyLU_NodeFastILU` to `TEST_REQUIRED_DEP_PACKAGES`, then we would pick up the FILU* tests in the AT. For what it's worth, it looks like all the ShyLU, not just FastILU, stuff is off by default and therefore not tested.

@srajama1 , thoughts?

**Pull request merged**
