### PR TITLE
All of TriBITS works with Python 3.x (TriBITSPub/TriBITS#309, #7376)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
For details, see commit message https://github.com/trilinos/Trilinos/commit/97d56259dcd3869f9782912149a79bc976bfd274 and #7376 and TriBITSPub/TriBITS#309.

NOTE: Please don't review TriBITS changes in this PR.  Instead, preview them in the matching TriBITS PRs:

* https://github.com/TriBITSPub/TriBITS/pull/343
* https://github.com/TriBITSPub/TriBITS/pull/344

Those PRs have more context, individual commits, and lots of tests.

## How was this tested?

Extensive TriBITS unit tests with pre-push testing with Python 2.7.5 and Python 3.5.2 as documented in the TriBITS commits TriBITSPub/TriBITS@15a2540cfed47c3e163a6b5abfdb926f7155c8ab and TriBITSPub/TriBITS@c1c110d26ebd68211940d9972130a94e0419b143.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@jmgate, thanks for the review of https://github.com/TriBITSPub/TriBITS/pull/343.  NOTE: The only issue you flagged was a formatting problem with the TriBITS Developers Guide which does not directly impact Trilinos.  I will fix this on the TriBITS side and push.

**Comment by jmgate** [comment]
Sounds good.  Ping me once pushed and I can give this the 👍

**Comment by bartlettroscoe** [comment]
@jmgate, I just merged the updated TriBITS snapshot in this branch to the new TriBITS PR https://github.com/TriBITSPub/TriBITS/pull/344 that you just approved.

Can you please approve this Trilinos PR so it can be merged to Trilinos 'develop'?

**Review by jmgate — APPROVED** [review]

**Comment by bartlettroscoe** [comment]
Related to:
* SEPW-213
* SEPW-214

**Pull request merged**
