### PR TITLE
MueLu RefMaxwell

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Description
With these changes, MueLu's RefMaxwell should work in the same way as ML's. RefMaxwell is now Xpetra based, instead of Tpetra. The construction of the special prolongator on the finest level has been rewritten to avoid the construction of auxiliary matrices. The MueLu test runs with arbitrary scalar type, std::complex in particular. The solver is exposed to Stratimikos. The new interface is tested through an example in TrilinosCouplings.

## Checklist
- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [x] These changes break backwards compatibility.

## Additional Information
Changing the parameter name "refmaxwell: disable add-on" to "refmaxwell: disable addon" to match ML's parameter breaks backwards compatibility.

### CODE REVIEW

**Comment by ibaned** [comment]
@trilinos/muelu this has based spot-check testing and has been approved by @egphill . it should probably be merged or marked as `[WIP]` until someone can get around to merging it.

**Comment by mhoemmen** [comment]
@ibaned I marked it as WIP.  Thanks!

**Comment by jmgate** [comment]
@egphill, do you mind re-reviewing on behalf of @trilinos/panzer?  It looks like commits have been added since you approved this PR.

**Comment by cgcgcg** [comment]
I did not make any big changes, merely made sure that a merge conflict was resolved..

**Comment by egphill** [comment]
@jmgate The latest commit looks good to me.

**Pull request merged**
