### PR TITLE
Fix #10892

### LINKED ISSUE #10892: Teuchos:  undefined functions
## Bug Report
@trilinos/teuchos 
@bartlettroscoe @cgcgcg 

### Description
It seems that there are 2 functions which are declared but are not defined in Teuchos:
- `make_char_nfa` is declared [here packages/teuchos/parser/src/Teuchos_FiniteAutomaton.hpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parser/src/Teuchos_FiniteAutomaton.hpp#L66) and then defined [here packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp#L417) with a different signature. 
- `aboutBuild` is declared [here packages/teuchos/core/src/Teuchos_Utils.hpp](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/src/Teuchos_Utils.hpp#L64) and is not defined.

It looks like both of them could be remove.

This has been noticed when trying to import a shared library built using pybind11 of Teuchos from python.
It is strange that these undefined symbols have never been an issue up to today.

### PR DESCRIPTION
**Pull request by kliegeois**
@trilinos/teuchos 
@bartlettroscoe @cgcgcg 

## Motivation

Fix https://github.com/trilinos/Trilinos/issues/10892

## Testing

It passed on my workstation.

### CODE REVIEW

**Review by bartlettroscoe — APPROVED** [review]
If it passes the builds then I say this is good to go.

**Comment by kliegeois** [comment]
@bartlettroscoe thanks for the review! Teuchos built correctly on my workstation and the symbols are gone from the .so.
We just have to wait for the AutoTester now.

**Comment by kliegeois** [comment]
@bartlettroscoe I can't access the CDash results. Can you let me know why it failed?

**Comment by kliegeois** [comment]
Thanks @bartlettroscoe for the update! I will keep an eye on the status of https://github.com/trilinos/Trilinos/issues/10893 and will add the `AT: RETEST` label once it is resolved.

**Comment by kliegeois** [comment]
@bartlettroscoe it looks like the issue https://github.com/trilinos/Trilinos/issues/10893 has been closed, can I reenable the AutoTester on this PR?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe it looks like the issue #10893 has been closed, can I reenable the AutoTester on this PR?


Yes!

**Pull request merged**
