### PR TITLE
Clean up ATDM builds for CMake upgrade (#10355)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Disabled builds and tests that have failed for all recorded history on CDash (see https://github.com/trilinos/Trilinos/issues/10355#issuecomment-1303693318).

See individual commits for details.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
FYI: I merged this branch to the 'atdm-nightly-manual-updates' branch in the commit https://github.com/trilinos/Trilinos/commit/bfda89f4c0ceee9b609d7ae24f11990e1c61b591 so we will see how this cleans up the ATDM Trilinos nightly builds.  Then I will have a better foundation to test the CMake upgrade in these builds.

**Review by rppawlo — DISMISSED** [review]

**Comment by bartlettroscoe** [comment]
FYI: With this change, the ATDM Trilinos builds are fairly clean.  Less than 16 or so twoif each day.

This is ready to merge.

**Comment by bartlettroscoe** [comment]
Hello @rppawlo, can you please reapprove?  Your approval got dismissed with the push of commit [`f742113` (#11229)](https://github.com/trilinos/Trilinos/pull/11229/commits/f7421133d0e5897bb21f8923e884b98cc76e9261).

**Review by jhux2 — APPROVED** [review]
lgtm

**Review by rppawlo — APPROVED** [review]

**Pull request merged**
