### PR TITLE
Tpetra: adding missing code for proper ETI with 'long double' ST for TpetraExt routines

### PR DESCRIPTION
**Pull request by ikalash**
Related to issue #9325 .  @csiefer2 could you please review.  @trilinos/tpetra .  I have modified one of the ifpack2 tests to use the routines affected by the code related to this PR.

### CODE REVIEW

**Review by csiefer2 — DISMISSED** [review]
LGTM

**Review by csiefer2 — APPROVED** [review]

**Comment by cgcgcg** [comment]
@trilinos/framework Why is this not mergeable? Github thinks it is.

**Comment by ikalash** [comment]
> @trilinos/framework Why is this not mergeable? Github thinks it is.

I was wondering the same thing...

**Comment by allevin** [comment]
@ikalash @cgcgcg The problem is that there is a failing status check.   For some reason the Master Merge AT ran and failed, and put a failing status into the PR system... @prwolfe and I are reviewing why this happened.  I would recommend setting the PR to WIP for a moment till we figure out a solution.

**Comment by prwolfe** [comment]
Thanks Aaron!

**Comment by ikalash** [comment]
Thanks @allevin.  Isn't it sufficient to remove the AT_RETEST label?  Then the retest won't keep going on while things are broken.  Just to clarify, is the problem something in the PR or with the auto-tester?

**Comment by allevin** [comment]
@ikalash The status flags are a feature of Github.   All status flags must be passing before the merge can take place.  However, they can only be manipulated by the API, not the GUI.  @prwolfe explained what happened to me.  This PR was targeted at master which caused the "master merge autotester" to run and add its failing status flag.  Setting the AT_RETEST label only clears the status flags for the normal PR autotester, it does not know anything about the "master merge autotester", hence that is why the status flag is not cleared.  

At this point, the PR can either be merged manually or this PR must be closed and a new one added.   Since no commits have occurred since the testing, you should be fine to manually merge.  

I am adding a ticket against the Autotester, to look into methods to prevent this situation from happening again.

**Comment by ikalash** [comment]
Thanks @allevin I see.  I just merged manually.

**Pull request merged**
