### PR TITLE
Add fileIO and scanf to Pamgen/RTC

### PR DESCRIPTION
**Pull request by jgfouca**
Adds fileIO, specifically the readline function to Pamgen's RTC package. Also adds scanf to make the read lines usable.

## Description

Example usage:
```
  int numRead = 0;
  int index = 0;
  while (numRead != -1) {
    char buffer[256];
    numRead = readline("table.dat", buffer);
    if (numRead != -1) {
      scanf(buffer, testCol1[index], testCol2[index], testCol3[index]);
    }
    index = index + 1;
  }
```
This would read in a file with 3 columns of data into the testColN arrays.

## Motivation and Context
Requested by Thomas Smith for Drekar.

## How Has This Been Tested?
RTC has a test in Pamgen. I added to that test to test readline and scanf. It passes for both RELEASE and DEBUG builds on rhel6.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
I could review this but I'd rather somebody who knows RTC did it.  @csiefer2 , do you know an RTC developer?

**Comment by jgfouca** [comment]
@mhoemmen , thanks! This is my first trilinos PR in ages. Should I be worried about the autotester fail?

**Comment by mhoemmen** [comment]
Glad that you are back in the saddle! :-D  

@jgfouca wrote:
> Should I be worried about the autotester fail?

It's been a bit wonky the last few days.  Framework is working on it.

**Comment by jgfouca** [comment]
Thanks, @mhoemmen !

**Pull request merged**
