### PR TITLE
Panzer hierarchic

### PR DESCRIPTION
**Pull request by rppawlo**
This adds hierarchic parallelism to a subset of panzer.

### CODE REVIEW

**Comment by rppawlo** [comment]
disabling automerge. Want to test the performance degradation with these changes for non-hierarchic  builds first.

**Comment by rppawlo** [comment]
@trilinos/framework - the PR testing is failing the 4.8 build (twice) and returns the message below. Can someone on the framework team help me figure out what is going on here? 
```
Starting testing step.
CMake Error at /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/TFW_testing_single_configure_prototype/simple_testing.cmake:193 (message):
Test failed with error -1
```

**Comment by rppawlo** [comment]
@trilinos/framework - please disregard request for help. Figured it out.

**Comment by rppawlo** [comment]
> Re-re-approving?

@jmgate - thanks! had to make some changes for non-cuda builds...

**Comment by jmgate** [comment]
I'm kind of hoping you push another commit just so I can comment "Rerere-approving&hellip;".

**Pull request merged**
