### PR TITLE
EpetraExt: Recursively check for existing HDF5 groups

### PR DESCRIPTION
**Pull request by Sbte**
@trilinos/EpetraExt

## Description
Nested groups are not handled correctly in EpetraExt_HDF5. These groups are denoted by `/Group A/Group B/Group C/data`. Writing and reading from these groups actually works fine, just the `IsContained` method, which only does some safety checks, does not handle them correctly.

I also added a missing const while I was working on the code anyway.

## Motivation and Context
Reason why one might need this is when writing a data structure which contains an array of `Epetra_Vectors`. Doing this without nested groups would look like a mess since all data is sorted alphabetically.

## How Has This Been Tested?
A new unit test file was added and tests were added to confirm the behaviour of the changed functionality.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@Sbte Thanks for contributing!  Would it be difficult to isolate a unit test from your code?

**Comment by mhoemmen** [comment]
@trilinos/epetraext

**Comment by Sbte** [comment]
@mhoemmen It would be quite easy. I could just create some groups and try to write an integer, which would currently fail and work with my code. I even have tests for this in my own code (with google test).

However, the current test file for inout, `packages/epetraext/test/inout/cxx_main.cpp`, looks like a complete mess to me, and I would prefer not to write my tests like that. Also, I have no clue how to handle compiling these tests only when linked to the right version of HDF5. I would know how to do this with standard CMake, but not with the Trilinos build environment.

**Comment by mhoemmen** [comment]
@Sbte If you can write a test using your own main.cpp file, we can make it work with Trilinos' build system and test framework.

**Comment by Sbte** [comment]
@mhoemmen I added the requested changes

**Comment by mhoemmen** [comment]
Thanks @Sbte ! :D

**Pull request merged**
