### PR TITLE
Teuchos: use provided stream formatting flags in TimeMonitor summarize()

### PR DESCRIPTION
**Pull request by aprokop**
@trilinos/teuchos @bartlettroscoe 

This allows the user to control the formatting of the timer columns.
The cost is storing an extra std::ios_base::fmtflags in TableEntry.

The original output may look like this:
```
MueLu: CoalesceDropFactory_kokkos: Build (total)                                                6.066 (4)                  
MueLu: CoalesceDropFactory_kokkos: Build (total, level=0)                                       4.69 (1)                   
MueLu: CoalesceDropFactory_kokkos: Build (total, level=1)                                       1.276 (1)                  
MueLu: CoalesceDropFactory_kokkos: Build (total, level=2)                                       0.0962 (1)                 
MueLu: CoalesceDropFactory_kokkos: Build (total, level=3)                                       0.003703 (1)               
MueLu: CoarseMapFactory_kokkos: Build                                                           0.0007512 (4)              
MueLu: CoarseMapFactory_kokkos: Build (level=0)                                                 0.0005596 (1)              
---------------------------------------------------------------------------------------------------------------------------
MueLu: CoarseMapFactory_kokkos: Build (level=1)                                                 4.289e-05 (1)              
MueLu: CoarseMapFactory_kokkos: Build (level=2)                                                 4.606e-05 (1)              
MueLu: CoarseMapFactory_kokkos: Build (level=3)                                                 3.998e-05 (1)              
MueLu: CoarseMapFactory_kokkos: Build (total)                                                   0.0007804 (4)              
MueLu: CoarseMapFactory_kokkos: Build (total, level=0)                                          0.000583 (1)               
MueLu: CoarseMapFactory_kokkos: Build (total, level=1)                                          5.083e-05 (1)              
MueLu: CoarseMapFactory_kokkos: Build (total, level=2)                                          5.396e-05 (1)              
MueLu: CoarseMapFactory_kokkos: Build (total, level=3)                                          4.722e-05 (1)
```
which is a mix of scientific and non-scientific notations with different precisions. The new output (when controlled with `std::fixed` or `std::scientific` before `TimeMonitor::report`) will look like this:
```
Driver: 5 - Belos Solve                                                                  3.1061 (1)
Driver: S - Global Time                                                                  7.2109 (1)
Ifpack2::Chebyshev::apply                                                                1.4155 (96)
Ifpack2::Chebyshev::compute                                                              0.3570 (3)
--------------------------------------------------------------------------------------------------------------------
MueLu: AggregationPhase1Algorithm: BuildAggregates (total)                               0.0687 (3)
MueLu: AggregationPhase2aAlgorithm: BuildAggregates (total)                              0.0266 (3)
MueLu: AggregationPhase2bAlgorithm: BuildAggregates (total)                              0.0454 (3)
MueLu: AggregationPhase3Algorithm: BuildAggregates (total)                               0.0010 (3)
MueLu: AmalgamationFactory: Build                                                        0.0001 (3)
```
or this
```
Driver: 1 - Matrix Build                                                                 5.7187e+00 (1)
Driver: 2 - MueLu Setup                                                                  9.0275e+00 (1)
Driver: 3 - LHS and RHS initialization                                                   8.5122e-03 (1)
Driver: 5 - Belos Solve                                                                  9.9469e+00 (1)
Driver: S - Global Time                                                                  2.4731e+01 (1)
Ifpack2::Chebyshev::apply                                                                4.5091e+00 (96)
Ifpack2::Chebyshev::compute                                                              1.1264e+00 (3)
--------------------------------------------------------------------------------------------------------------------
MueLu: AggregationPhase1Algorithm: BuildAggregates (total)                               2.3058e-01 (3)
MueLu: AggregationPhase2aAlgorithm: BuildAggregates (total)                              9.2283e-02 (3)
MueLu: AggregationPhase2bAlgorithm: BuildAggregates (total)                              1.5934e-01 (3)
```

### CODE REVIEW

**Comment by aprokop** [comment]
@bartlettroscoe Thanks for the review. I personally don't consider this functionality to be important, it's more of a quality of life improvement, particularly when I'm diffing two timer files. Regarding the test, I don't have any ideas at the moment. The only one I have is to create a single timer, then catch the report into a string, and then to parse the string by something like `\d*.\d{4}` and `\d{1}.\d{4}e[+-]\d*` with `\d` corresponding to a digit, and 4 being the number of digits. This way, theoretically, we could somewhat check the result. Not sure exactly how easy it is to do such parsing in C++, though.

**Comment by aprokop** [comment]
Add a *not so great* unit test, but at least something.

**Comment by aprokop** [comment]
Thanks!

> Go ahead and merge and then and run the checkin-test-sems.sh script to test and push.

This I don't understand. I cannot merge the PR as it hasn't been through checkin yet. I think I'm learning that one should run checkin without `--push` and with `--apend-test-results` and then push to a remote branch that is used for a PR. Is that correct?

**Comment by ibaned** [comment]
Sorry to digress, but this is also something I'd like clarified (how to checkin test PRs). What I do now is the merge the PR into my local develop branch, and then run the checkin test on that. My issue with that approach is that the script tends to rebase things such that it is no longer a separate path with a merge commit. Is there a better approach?

**Comment by aprokop** [comment]
@ibaned Yeah, I have the same issue. I think checkin script is missing the functionality to be able to compare a local branch vs a remote branch that it is going to be merged in. Right now, from my experiments, it compares against the current tracking branch which does not do what we want to because tracking branch for PR and local branch for PR have the same commits and thus checkin simply stops.

I think if we have checkin to check against a specified remote that is not tracking, the workflow would be:
- Create and develop in local branch
- Run the checkin locally without `--push` and specify `upstream/develop` as a branch to compare to. Add `--append-test-results` so that we have that in the commit.
- Push this local branch to your fork, and create a PR with it
- Merge the PR

**Comment by bartlettroscoe** [comment]
> My issue with that approach is that the script tends to rebase things such that it is no longer a separate path with a merge commit. Is there a better approach?

After you manually merge the branch to 'develop', you can run with:

```
$ ./checkin-test-sems.sh --no-rebase --do-all --push
```

That will avoid the rebase (but does allow for a trivial merge commit in case new commits are pushed to github/developer after you did the merge).

But in a case like this, we are only talking about 2 commits so using a merge commit for 2 commits is a bit silly.  So in that case, I would just allow the rebase to occur and then manually note the rebased commits and manually close the PR.

**Comment by aprokop** [comment]
Finally pushed in c59963d0319c2c8cdd27a531b5293c44e44fe25a.

**Pull request closed without merging**
