### PR TITLE
Tpetra: Introduce type aliases for classes (fix #3321; make progress on #57 & #2548)

### LINKED ISSUE #3321: Tpetra: Add forward declaration header files for classes
@trilinos/tpetra 

Users want to avoid exposure to class declarations and definitions, if they only handle classes by pointer or reference.  Users also want their code to be insulated from changes to Tpetra classes' template parameters.  If users make their own forward declarations of Tpetra's templated classes, those forward declarations may break if Tpetra classes' change their template parameters in ways that would otherwise not break backwards compatibility.

Tpetra should instead provide forward declaration header files for major user interface classes.

## Related Issues
* Related to #57, #2548

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra 

## Description

Replace `Tpetra::${CLASS}` with a type alias to `Tpetra::Classes::${CLASS}`.  This will let us eventually get rid of Tpetra template parameters (#57 and #2548), but retain backwards compatibility for users.  Users will be able to specify the template parameters as before.

This technically will break backwards compatibility for code that makes forward declarations of Tpetra classes.  This is why I had to edit other Trilinos packages.  However, I added forward declaration header files to mitigate issues like this in the future.

## Related Issues

* Closes #3321
* Part of #57, #2548 

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [x] These changes break backwards compatibility.

## Additional Information

These changes technically change backwards compatibility for forward declarations of Tpetra classes.  I have mitigated this issue by introducing forward declaration header files.

### CODE REVIEW

**Comment by tjfulle** [comment]
@mhoemmen, I'm about 10% of the way through!!!  :rofl:

**Comment by mhoemmen** [comment]
@tjfulle If it helps, I changed all the classes in the same way:

1. Create a forward declaration header file for the Tpetra class.
2. In the new header, put the Tpetra class in Tpetra::Classes (or Tpetra::Details::Classes or ...).
3. In the new header, add a type alias in the Tpetra namespace, to the above Tpetra class.
4. Include the forward declaration header in the `..._decl.hpp` header for the Tpetra class.
5. In the `..._def.hpp` header for the Tpetra class, fix the explicit instantiation macro to point to the class (in Tpetra::Classes), not the type alias.
6. Replace any downstream forward declarations with including the forward declaration header file.

The next step, _not_ in this PR, is to replace the simple type alias (in (3)) with a more complicated rule that canonicalizes template parameters, as in the examples I've shown the Tpetra developers previously.

@jhux2 This is a tutorial on how I did this process in Tpetra.

**Comment by mhoemmen** [comment]
Thanks @jmgate ! :D

**Comment by mhoemmen** [comment]
Thanks @csiefer2 ! :D

**Pull request merged**
