### PR TITLE
Ifpack2: Add support for using kokkos kernels under RBILUK

### PR DESCRIPTION
**Pull request by jgfouca**
@trilinos/ifpack2 

## Motivation

Make use of new capability in KokkosKernels: spiluk support for Bsr.

## Testing
Added a new test RBILUK_hb_belos_block

## Stakeholder

This feature was requested by SPARC; they have BSRs that the want to do ILU factorizations on.

## Other changes

Cleaned up trailing whitespaces in a number of files, so this PR is best viewed with filtering of whitespace-only changes.

### CODE REVIEW

**Review by jhux2 — CHANGES_REQUESTED** [review]
@jgfouca Thanks for the contribution.  Could you please add some context, such as the requesting stakeholder?

**Comment by jgfouca** [comment]
@cgcgcg , the AT failed in 4 minutes and there were no updates to cdash. Is something with the AT broken?

**Comment by jhux2** [comment]
@trilinos/framework @sebrowne Is something wonky with the AT?

**Comment by sebrowne** [comment]
> @trilinos/framework @sebrowne Is something wonky with the AT?

There was a typo that snuck in, I think I fixed it, will RETEST.  Thanks for catching that!

**Comment by jgfouca** [comment]
@vqd8a , @lucbv , after a bit of wrestling with the AT, this PR is ready for final review.

@jhux2 , I added some stakeholder info to the PR description.

**Review by jhux2 — APPROVED** [review]
@jgfouca Thank you, this will be helpful for the next round of SQE.

I'll let @vqd8a and @lucbv comment on the PR.

**Comment by jhux2** [comment]
@tcfisher

**Comment by jgfouca** [comment]
@sebrowne , what is the `AT2-EXPERIMENTAL / gcc10-openmpi416-EXPERIMENTAL (pull_request_review)` check that failed? `Details` isn't providing any info.

**Comment by jhux2** [comment]
@jgfouca This is ready to merge, I don't see any errors.

**Comment by jhux2** [comment]
@vqd8a @lucbv Could one of you please review?

**Comment by sebrowne** [comment]
> @sebrowne , what is the `AT2-EXPERIMENTAL / gcc10-openmpi416-EXPERIMENTAL (pull_request_review)` check that failed? `Details` isn't providing any info.

That is the new GitHub Actions-based AutoTester.  It is currently not a required check and should not block merges.  If it doesn't have any output, it is likely encountering a deadlock issue that we're working to mitigate.  The good news is that it should time out after ~5-10 minutes, and you can re-run JUST that build if you want to confirm it all works (and that behavior will persist with the new autotester, eliminating the need to re-run all builds each time one fails for sporadic system-related issues).

**Comment by jgfouca** [comment]
Thanks, @sebrowne . I did exactly that and it looks like it's passing now.

**Pull request merged**
