### PR TITLE
KokkosKernels: patch in supernodal fix

### PR DESCRIPTION
**Pull request by brian-kelley**
@trilinos/kokkos-kernels 

## Motivation

Fixes build with devices other than Serial and KokkosKernels supernodal SpTRSV enabled. Uses explicit exec+mem space pair to match correct ETI versions of SpMV, while before would get an undefined reference link time error.

## Stakeholder Feedback

Issue reported by @iyamazaki 
## Testing

Just a build change, but SpTRSV is tested in KokkosKernels

### CODE REVIEW

**Comment by iyamazaki** [comment]
Thank you @brian-kelley ! This fixed my builds (OpenMP on White and Cuda on Summit), with supernodal enabled. 

One question: there seems to be another work_view_t in [UpperTriTranSupernodalFunctor](https://github.com/trilinos/Trilinos/blob/e07ef9d8feeee9fc116e1bb6548186017da6b938/packages/kokkos-kernels/src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp#L1031). Should that have execution_space, just to be consistent?

**Comment by brian-kelley** [comment]
@iyamazaki Hmm, good catch. I did not get an error from that one, so I'm going through again and seeing if I can simply use memory_space for the workspace rather than the full Device<exec, mem>.

**Comment by brian-kelley** [comment]
@iyamazaki I'm opening a new PR to make that type consistent. In general the workspace_t does need to have the full Device spelled out (the build broke when I changed them to ``View<scalar*, memory_space>``).

**Review by iyamazaki — APPROVED** [review]
Thank you, @brian-kelley , again!!

**Comment by brian-kelley** [comment]
@srajama1 Can one of you review this for kokkos-kernels? It is just patching in https://github.com/kokkos/kokkos-kernels/pull/884 and https://github.com/kokkos/kokkos-kernels/pull/885 which Nathan looked over.

**Review by srajama1 — APPROVED** [review]
Thanks @brian-kelley !

**Pull request merged**
