### PR TITLE
ATDM/van1-tx2: Add openmpi 4.0.5 toolchain

### PR DESCRIPTION
**Pull request by e10harvey**
CC: @jwillenbring, @tcfisher

@sebrowne: Thank you for all your hard work on this. Apologies for the delay due to testing and proxy issues. When testing the tip of https://github.com/sebrowne/Trilinos/tree/develop, I saw all the builds fail [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-04-9&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=van1&field2=groupname&compare2=63&value2=Experiment) on cdash. I rebased your changes on-top of the Trilinos develop branch and things are running smoothly now. We can either merge this PR and close #8850 or close this one and update your PR accordingly.

Since `van1-tx2_arm-20.1_openmpi-4.0.3_openmp_static_opt` is marked as a 'Primary Build' I have marked `van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_opt` as a 'Primary Build' meaning that it will be monitored and triaged on a daily basis by the framework team. I flagged @jmgate as a reviewer since this includes changes to `van1-tx2_arm-20.1_openmpi-4.0.3_openmp_static_opt`.

## How was this tested?
On van1-tx2 via:
1. A quick 'preliminary test'
```bash
nohup env CTEST_DO_SUBMIT=OFF Trilinos_PACKAGES=Kokkos ./ctest-s-local-test-driver.sh van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_opt &>ctest-s-local-test-driver.out &
```
2. A 'full test':
```bash
nohup env ./ctest-s-local-test-driver.sh all &>ctest-s-local-test-driver.out &
```
The 'full test' is still running and posting to cdash [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-04-12&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=van1&field2=groupname&compare2=63&value2=Experiment).

### CODE REVIEW

**Comment by jmgate** [comment]
This looks fine to me.

**Comment by e10harvey** [comment]
The 'full test' failed with build errors too. I'll see what's going on here.

**Comment by jjellio** [comment]
These errors are because the Fortran support in the build stat wrappers isn't merged in yet - I thought Ross had mentioned he was going to disable it. (Or atleast that looks like the error)
@bartlettroscoe

**Comment by e10harvey** [comment]
Another round of testing using b73c40f will post [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-04-12&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=van1&field2=groupname&compare2=63&value2=Experiment&field3=buildstarttime&compare3=83&value3=2021-04-12T13%3A02%3A19) on cdash today.

**Comment by e10harvey** [comment]
Testing is passing now but the full test results will not be posted for several hours. @sebrowne, @prwolfe, @jwillenbring please approve and merge or close this and update #8850 when you're ready.

**Comment by e10harvey** [comment]
The testing results match our known failing tests for all builds except for the following build errors:
- [Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_dbg-exp](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=6278710)
- [Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.3_openmp_static_opt-exp](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=6278548)

Fortunately, these build errors on cdash show that there was just a connectivity issue from the compiler to the license server. I have started those builds from where they left off. Results will post [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-04-13&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=van1&field2=groupname&compare2=63&value2=Experiment) on cdash later today.

**Comment by e10harvey** [comment]
The build failures due to license errors are resolved.

**Review by jwillenbring — APPROVED** [review]
These changes look good for adding the new builds. My only question is if we should now go back and remove the builds that are being upgraded. Perhaps that should be delayed slightly until the new configuration is well in place, but I don't want to forget about cleaning up if that is appropriate.

**Comment by e10harvey** [comment]
> These changes look good for adding the new builds. My only question is if we should now go back and remove the builds that are being upgraded. Perhaps that should be delayed slightly until the new configuration is well in place, but I don't want to forget about cleaning up if that is appropriate.

@jmgate: Is the 4.0.3 build still needed?

**Comment by jmgate** [comment]
EMPIRE currently uses `ARM-20.0_OPENMPI-4.0.2`.  I'd recommend rolling out the new environment, encouraging teams to migrate to it, deprecating the old environment(s), and then eventually removing them.  Once these changes make it into EMPIRE's fork, I'll recommend to the team that they try the new environment out and we'll see if we can make the switch.

**Comment by e10harvey** [comment]
> EMPIRE currently uses `ARM-20.0_OPENMPI-4.0.2`. I'd recommend rolling out the new environment, encouraging teams to migrate to it, deprecating the old environment(s), and then eventually removing them. Once these changes make it into EMPIRE's fork, I'll recommend to the team that they try the new environment out and we'll see if we can make the switch.

Excellent. 4.0.3 will be left for now in case it's needed during migration from 4.0.2. Please let @trilinos/framework know when an environment is no longer needed.

**Pull request merged**
