### PR TITLE
Tpetra:  Remove Unused Parameter Warnings

### PR DESCRIPTION
**Pull request by jmgate**
@trilinos/tpetra 

## Description
Comment out parameter names in function definitions to avoid unused parameter warnings.  In cases where their use is hidden behind an `#ifdef`, `(void)` the parameters in the `#else` block.

This is a second attempt at #3317&mdash;for some reason GitHub wouldn't let me simply reopen that one after a force push to the branch.

## Motivation and Context
Just hoping for a clean build.

## How Has This Been Tested?
This works on my RHEL7 machine with gcc-7.3.0.

### CODE REVIEW

**Comment by jmgate** [comment]
@mhoemmen, this is ready for a re-approval.

**Comment by jmgate** [comment]
BTW, this reduces the Tpetra warning count on my build by ~3000.

**Comment by mhoemmen** [comment]
@kddevin Let's talk about this today -- thanks!

**Comment by mhoemmen** [comment]
We decided in the @trilinos/tpetra meeting that we want this now -- thanks!!!

**Pull request merged**
