### PR TITLE
Tempus: Improve Observer Names.

### LINKED ISSUE #3697: Tempus: Improve Observer Names
Several users have had confusion with the name for Integrator::acceptTimeStep() and IntegratorObserver::observeAcceptTimeStep().  To reduce confusion the names will be changed to Integrator::checkTimeStep() and observeAfterCheckTimeStep().

@trilinos/tempus 

## Definition of Done
- [ ] Change function names.
- [ ] Passes tests.

### PR DESCRIPTION
**Pull request by ccober6**
Made changes to reduce confusion related to
IntegratorObserver::acceptTimeStep().  acceptTimeStep() checked if
the timestep should be accepted or failed and promoting if passing.
“acceptTimeStep” was being read as a statement, "accept the timestep",
when it was meant as a question, “accept the timestep?”.  To reduce
this confusion, acceptTimeStep has been split into the determination
of the time step passing (now checkTimeStep()) and promotion of the
time step (now promoteWorkingState() is part of the Integrator time
loop).  Also two observers, observeAfterCheckTimeStep() and
observeEndTimeStep, have replaced the observeAcceptedTimeStep().
Work previously completed in observeAcceptedTimeStep() will likely
move into observeEndTimeStep(), unless it deals with the acceptance
of a time step as passing which would go into observeAfterCheckTimeStep().

Passed all tests.

Closes #3697 

@trilinos/tempus 

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [x] These changes break backwards compatibility.

### CODE REVIEW

**Comment by ccober6** [comment]
Hi @rppawlo @ikalash @sconde ,

I wanted to make sure you all were aware of this change as it does break backward compatibility.  Overall I think this is a good change to improve understandability of the "accepting the time step" portion of the integrator time loop.

@rppawlo, since you first mentioned this issue, I wanted to make sure it meets your expectations for improvement.  Let me know what you think.

Thanks,

Curt

**Comment by rppawlo** [comment]
@ccober6 - One thing I have used in the past was the ability to observe a failed time step. We sometimes had to reset certain objects depending on the application. Is this still supported by this change? In observeAfterCheckTimeStep can I access whether the step was successful or not?

**Comment by ccober6** [comment]
So there is not an explicit "failed time step" observer, but yes observeAfterCheckTimeStep() will always be called.  So the application can test for failure and do whatever it sees fit.

**Comment by ccober6** [comment]
@rppawlo I needed to make some changes to Piro for the PR.  Can I get another review?

**Pull request merged**
