### PR TITLE
Disable tests timing out in PR autotester

### PR DESCRIPTION
**Pull request by ndellingwood**
Temporarily address #4614 to get PR tests passing.

Not adding AUTOMERGE label, will let @trilinos/framework make the call or close this PR with their preferred solution.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@ndellingwood You also probably need to add Ifpack2 BlockTridiag test as it is a failure due to debugging check.

**Comment by jwillenbring** [comment]
It might be worth holding off on merging this to see if lowering the parallel level to 9 resolves the issue. That change was merged late this morning.

**Comment by ndellingwood** [comment]
@jwillenbring thanks! I figured I'd get something in so testing could start just in case it's needed to get the PRs moving again, hopefully the parallel level change works so this PR is unnecessary.

**Comment by ndellingwood** [comment]
Talked to @kyungjoo-kim , marking this WIP until we see if PR #4608 passes with the changed parallel level in testing; if that PR still fails due to the timeouts, will update this PR to disable the failing Ifpack2 test temporarily to break the PR testing deadlock (otherwise this PR will fail as well). @jhux2

**Comment by ndellingwood** [comment]
Closing this PR, unnecessary after change of parallel level for autotesting.

**Pull request closed without merging**
