### PR TITLE
Ifpack2: writing test for Belos Block GMRES solver + new extended ScalarTypes (float128, long double)

### PR DESCRIPTION
**Pull request by ikalash**
Adding a couple tests for the newly added float128 and long double ScalarTypes.  I was having trouble getting these to compile (as discussed here: https://github.com/trilinos/Trilinos/pull/9254) but was able to get this to work with the right includes.

### CODE REVIEW

**Review by csiefer2 — DISMISSED** [review]

**Comment by jhux2** [comment]
@ikalash Thank you for adding these tests!

**Comment by jhux2** [comment]
@ikalash Thank you for adding these tests!

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by ikalash** [comment]
@trilinos/framework : it seems this PR has been hanging on the pre-test inspection since Friday.  Is there an issue with the autotester?

**Comment by jhux2** [comment]
@ikalash I think so, there are other PRs that haven't started testing over the weekend.

**Comment by ikalash** [comment]
> @ikalash I think so, there are other PRs that haven't started testing over the weekend.

Thanks, @jhux2 .  I'll keep waiting - hopefully this will be resolved soon.

**Comment by lucbv** [comment]
Will this work in a build with `GO=int` ?

**Comment by jwillenbring** [comment]
@ikalash Yes, there is currently a problem with the autotester that is being investigated.

**Comment by ikalash** [comment]
@lucbv : there was no particular reason to use 'long long int' for GO - that's just what we used in Alegra and what I believe is the default GO type in Tpetra (or am I wrong on that?).  I was going to tell you there is no reason 'GO=int' would not work but the I tried it and it did not work.  The errors look like this:
```
/home/ikalash/TrilinosFromNightlies/packages/ifpack2/test/belos/belos_solve_longdouble.cpp:139:69:   required from here
:297:19: error: cannot convert ‘Tpetra::CrsMatrix<long double, int, int>*’ to ‘const Tpetra::Operator<long double>*’ in initialization
  297 |   : ptr_(r_ptr.get()), // will not compile if T is not base class of T2
      |          ~~~~~~~~~^~
      |                   |
      |                   Tpetra::CrsMatrix<long double, int, int>*
```
It seems the cast done in Teuchos is returning a Tpetra::Operator that does not have all the template parameters, I'm not sure why.  Let me know if you have any thoughts.

**Comment by lucbv** [comment]
I am suspecting that you need to use Tpetra's default GO defined here: `Tpetra_Details_DefaultTypes.hpp`?

**Comment by ikalash** [comment]
Thanks @lucbv - what you suggest works and I agree it's a better thing to do.  I've modified the tests.

**Comment by ikalash** [comment]
@lucbv : could you or someone else re-review please?

**Review by jhux2 — DISMISSED** [review]
lgtm

**Comment by ikalash** [comment]
> Making note of this PR- These changes are relevant to the multiprecision project. We might want to include some experiments in our reports. I presume you have a specific ALEGRA use case in mind? (@iyamazaki might also want to look at this.)

@jennloe : yes, we are interested in using this in the ALEGRA XFEM contact solve.  It's a sort of multiprecision use case as well - XFEM is very sensitive to the solution coming out of the linear solve and using a longer precision for the solve can help us avoid parallel-serial discrepancies (by using a type with a longer mantissa, the differences b/w a parallel and serial run will get removed when we down-cast to a double in ALEGRA following the solve).  Note that the usage of the extended scalar types in Trilinos is currently somewhat limited (I found).  A lot of solvers are not implemented for long double or float128 (b/c they rely on LAPACK).  Also, changes are needed to get things to work with ETI=ON.  I was thinking to open an issue about that if there are more people interested in the capability.

**Comment by hkthorn** [comment]
@ikalash Thanks for the information!  I think there are several people interested in this, so we should open an issue.

**Comment by jennloe** [comment]
@hkthorn  I'm also working with @e10harvey to start testing the new Kokkos half precision capabilities within the GMRES solver.  Some of the issues are likely to overlap.

**Comment by ikalash** [comment]
> @hkthorn I'm also working with @e10harvey to start testing the new Kokkos half precision capabilities within the GMRES solver. Some of the issues are likely to overlap.

@jennloe : FYI, since you mention Kokkos, there will be separate PRs to enable the 'long double' and 'float128' types in Kokkos.  @dalg24 is working on that.

**Comment by iyamazaki** [comment]
I've been also curious about this PR. As @jennloe mentioned, we've been looking at using double-double arithmetic for Cg on GPUs, but very experimentally (and just for a particular operations within s-step Cg iteration).

**Comment by ikalash** [comment]
@jwillenbring : any update on the autotester?  I got an email about another PR's autotesting, so presumably it's back up.  Do I need to do something for the checks to start?

**Comment by jennloe** [comment]
@ikalash  Seems like we need to wait a bit longer on the autoTester.  Tests have been running, but then they are immediately failing.  Something is still not configured correctly.

**Comment by prwolfe** [comment]
We are one step closer - the next fix is in PR #9286 and then I think it will all be back up and going.

**Comment by ikalash** [comment]
@jwillenbring : it looks like the problem with the autotester has to do with the proxies changing a few days ago.  I think you need to set the proxy to ```https://proxy.sandia.gov``` from ```https://wwwproxy.sandia.gov```.

**Comment by jwillenbring** [comment]
> @jwillenbring : it looks like the problem with the autotester has to do with the proxies changing a few days ago. I think you need to set the proxy to `https://proxy.sandia.gov` from `https://wwwproxy.sandia.gov`.

@ikalash It is more complicated than just that unfortunately. We have not been able to get things working fully.

**Comment by ikalash** [comment]
> @ikalash Thanks for the information! I think there are several people interested in this, so we should open an issue.

@hkthorn : I'll do this once this PR goes in - I need these test cases merged in to demonstrate the compilation issue with ETI=ON.

**Comment by ikalash** [comment]
@jwillenbring : will the tests restart automatically when the autotester is fixed?  If not, will we be notified somehow that things are working again so we can get the tests relaunched?

**Comment by jwillenbring** [comment]
> @jwillenbring : will the tests restart automatically when the autotester is fixed? If not, will we be notified somehow that things are working again so we can get the tests relaunched?

@ikalash I or someone on the @trilinos/framework team will send a note to the developer list again when things are working.

**Comment by jwillenbring** [comment]
> > @jwillenbring : will the tests restart automatically when the autotester is fixed? If not, will we be notified somehow that things are working again so we can get the tests relaunched?
> 
> @ikalash I or someone on the @trilinos/framework team will send a note to the developer list again when things are working.

Acutally @prwolfe sent out such a note. We are still verifying if everything is working, but things look promising.

**Comment by ikalash** [comment]
@jwillenbring : I did not receive the note.  Maybe I am not on the developers list?  How do I kick off the tests again?

**Comment by jwillenbring** [comment]
> @jwillenbring : I did not receive the note. Maybe I am not on the developers list? How do I kick off the tests again?

I will check the developer list. This PR will be tested again when it gets to the top of the queue because the retest flag is already on it.

**Comment by ccober6** [comment]
@ikalash You were not on the trilinos-developers@trilinos.org mailing list.  I have added you.  Please let know if did not want that.  :)

**Comment by ikalash** [comment]
Thank you @ccober6 !

**Comment by jennloe** [comment]
> @ikalash You were not on the [trilinos-developers@trilinos.org](mailto:trilinos-developers@trilinos.org) mailing list. I have added you. Please let know if did not want that. :)

@ccober6 Can you add me to that list as well?  Thanks!

**Comment by ccober6** [comment]
> > @ikalash You were not on the [trilinos-developers@trilinos.org](mailto:trilinos-developers@trilinos.org) mailing list. I have added you. Please let know if did not want that. :)
> 
> @ccober6 Can you add me to that list as well? Thanks!

@jennloe You bet!  You should receive an email from trilinos-developers@trilinos.org.   Also this is a standard GNU Mailman mailing list, so you should be able to subscribe and manage your subscription (e.g., http://www.list.org/mailman-member/node13.html).

**Comment by ikalash** [comment]
@jhux2 : could you please reapprove again?  I made a couple minor improvements while waiting for the autotester to get fixed.

**Review by tjfulle — APPROVED** [review]

**Pull request merged**
