### PR TITLE
Amesos2: Update ShyLUBasker tests for Tpetra changes

### PR DESCRIPTION
**Pull request by ndellingwood**
This is a follow up to #3094 by @mhoemmen to pattern match Tpetra
changes (relevant to issue #57) made by PR #3094 to a unit test file
added after that PR was submitted.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@ndellingwood What I mean is that these changes are fine and achieve the desired goal of removing use of DefaultPlatform, but it would also be helpful at a later time to replace Teuchos::GlobalMPISession with Tpetra::ScopeGuard.

**Comment by ndellingwood** [comment]
@mhoemmen I don't see use of `Teuchos::GlobalMPISession` in this modified unit test file, but will work on making those changes when I see them elsewhere.

**Comment by ndellingwood** [comment]
For reference, compiled and tests pass with gcc/5.4.0, OpenMP and MPI enabled, and complex<double> types.

**Comment by ndellingwood** [comment]
That's weird, I looked at this link CDash link about test results [(cdash link)](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-3097-test&field2=buildstarttime&compare2=84&value2=NOW) but there are no build errors and no test failures. Further, the file I modified is not even tested by the auto-tester (I tested locally). 
@jwillenbring @allevin could you help me understand what went wrong?

**Comment by allevin** [comment]
@ndellingwood 

CC: @jwillenbring 

> That's weird, I looked at this link CDash link about test results (cdash link) but there are no build errors and no test failures. Further, the file I modified is not even tested by the auto-tester (I tested locally).
@jwillenbring @allevin could you help me understand what went wrong?

There were 3 jobs launched, a gcc 4.9.3, a gcc 4.8.4, and an Intel 17.0.1, the CDash is reporting for the gcc 4.8.4 and Intel builds, but the gcc 4.9.3 had a git clone issue.  When this happens, the cmake system cannot run and therefore cannot report to CDash, However Jenkins still reports the build as failing.   The frameworks team is aware of the issue and have had discussions on solutions.

Hope this helps.

**Comment by ndellingwood** [comment]
@allevin That helps, thanks for the info!

**Pull request merged**
