### PR TITLE
Ifpack2:  Remove Unused Parameter Warnings

### PR DESCRIPTION
**Pull request by jmgate**
@trilinos/ifpack2 

## Description
Comment out unused parameters in function definitions to avoid
`-Wunused-parameter` warnings.

## Motivation and Context
Clean build.

### CODE REVIEW

**Comment by jmgate** [comment]
Thanks for the heads-up, @mhoemmen.

**Comment by amklinv** [comment]
Just wanted to say, as a person who frequently uses the -Wall flag, I appreciate you doing this :-)

**Comment by jmgate** [comment]
Thanks, @amklinv&mdash;glad to know someone appreciates it.

**Comment by kyungjoo-kim** [comment]
The big PR is merged now.

**Comment by jmgate** [comment]
Handled merge conflicts.  Can someone review?

**Pull request merged**
