### PR TITLE
EXODUS: bring up-to-date with SEACAS github

### PR DESCRIPTION
**Pull request by gsjaardema**
* Primarily refactoring of the error functions and valid id checks.
* parallel consistency fix in sideset distribution factor  read/write
* Update copyright dates based on new copyright assertion
* Added 'ex_get|put_partial_coord_comp()' functions
* Reformatting via clang-format
* Updated doxygen documentation to include more details from original sand report
* Added support for a few more element types.

@trilinos/seacas 

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@gsjaardema, is this a snapshot of your GitHub seacas/seacas into Trilinos/packages/seacas/?  If so, what version of that repo does this come from?

**Comment by gsjaardema** [comment]
@bartlettroscoe 
It is a partial snapshot -- only the exodus-related changes have been pulled, so there isn't really a repo version.  The branch name is misleading in this case.

**Comment by bartlettroscoe** [comment]
@gsjaardema, okay, it is not a big deal if we don't capture the version info from the originating seacas git repo of one partial snapshot.   Hopefully we can get back to full snapshots in the near future to make this easier and more sustainable.

Just curious, but who is the customer for this update?  There are no mention of a Trilinos GitHub Issue or of a customer.

**Comment by mhoemmen** [comment]
@micahahoward This may be of relevance to your interests.

**Pull request merged**
