### PR TITLE
Patch in Kokkos Kernels #1204 to fix #9856

### LINKED ISSUE #9856: KokkosBlas:  limited vector size in norm calculation?
## Bug Report
@trilinos/tpetra 

### Description
@jennloe  reports

I have this Trilinos (Belos + Tpetra) code which is crashing, and I don't understand why

```
76   typedef double                            ScalarType;
77   typedef int                               OT;
78   typedef Tpetra::MultiVector<ScalarType>   MV;
79   typedef Tpetra::MultiVector<ScalarType>::mag_type   MT;
...
132   RCP<Tpetra::MultiVector<ScalarType>> X1 = rcp( new Tpetra::MultiVector<ScalarType>(map, 1008) );
133   X1->randomize();
134   RCP<Tpetra::MultiVector<ScalarType>> XCopy = rcp(new Tpetra::MultiVector<ScalarType>(*X1, Teuchos::Copy)); //Deep copy of X1.
....
154   // DEBUG: //Verify coefficients:
155   MV coeffs_mv = makeStaticLocalMultiVector (*X1, 1008, 1008);
156   std::cout << "Starting deep copy" << std::endl;
157   Tpetra::deep_copy(coeffs_mv, *coeffMat);
158   std::cout << "Finished deep copy" << std::endl;
159   XCopy->multiply(Teuchos::NO_TRANS, Teuchos::NO_TRANS, 1.0, *X1, coeffs_mv, -1.0);
160   std::cout << "Passed multiply." << std::endl;
161   std::vector<MT> norms(1008);
162   Teuchos::ArrayView<MT> normView(norms);
163   std::cout << "created norms array" << std::endl;
164   XCopy->norm2(normView);
165   std::cout << "Here are the QR-Orig norms.  Should be zero." << std::endl;
166   std::cout << normView << std::endl << std::endl;
```

And the output is:

```
$ ./Belos_TpetraOrthogCoeffs.exe
Starting deep copy
Finished deep copy
Passed multiply.
created norms array
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaStreamSynchronize(m_stream) error( cudaErrorIllegalAddress): an illegal memory access was encountered /ascldap/sers/jloe/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:314
Traceback functionality not available
Aborted (core dumped)
```

At first glance, the problem appears to be a mismatch between the norms argument (on host) and the vector argument (on device)

### Steps to Reproduce
Reproduced with simple test program on ascicgpu with no UVM.

### PR DESCRIPTION
**Pull request by brian-kelley**
Patching in https://github.com/kokkos/kokkos-kernels/pull/1204 :

Remove runtime-sized array reductions from BLAS-1 MV functions. Where
possible, use the same approach as dot-based GEMM (have multiple teams
work on a reduction, and use atomics to contribute to the final result).
If that is not possible, just process each column one at a time. Both
approaches give better performance than array reductions, and also work
for any number of columns (before, both Cuda and HIP had limits, see #9856).

I checked that the tests to replicate the issue (from #9860), pass with these changes.

@trilinos/kokkos-kernels 
@trilinos/tpetra 

## Testing

All the changes are within Kokkos Kernels. KokkosKernels_blas_* has unit tests for each of these functions.

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]
These changes previously reviewed and tested in kokkos/kokkos-kernels#1204, thanks @brian-kelley

**Review by hkthorn — COMMENTED** [review]
Thanks for the thorough explanation of the issue in this test.  I agree with the argument for putting a tolerance on the norm comparisons.  I'm wondering if that tolerance should be hard-coded or based on the scalar type being used in the test?

**Comment by brian-kelley** [comment]
@hkthorn Good catch. I was thinking that ``double`` was always the default scalar type for MultiVector, but it can also be float. I'll fix it.

**Comment by brian-kelley** [comment]
@hkthorn OK, now it is using ``Teuchos::ScalarTraits<S>::eps()``.

**Review by hkthorn — DISMISSED** [review]
LGTM

**Review by cgcgcg — APPROVED** [review]

**Pull request merged**
