### PR TITLE
Geminga: Add CUDA build with UVM disabled

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
Add a build with UVM disabled. This build currently fails all over the place..

### CODE REVIEW

**Review by jhux2 — COMMENTED** [review]
It looks this would run multiple times a week ... is that useful right now?

**Comment by cgcgcg** [comment]
Does it hurt? It's nice to see it on the dashboard every day. And the build is probably quite quick anyway :-P

**Comment by jhux2** [comment]
> Does it hurt? It's nice to see it on the dashboard every day. And the build is probably quite quick anyway :-P

Fair enough!

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by lucbv** [comment]
I think it's a good idea too, I am guessing it fails right-away in Tpetra or something like that at the moment?
The effort to remove UVM should get started soon, it will be helpful to have a regular build that tests that : )

**Review by lucbv — APPROVED** [review]
Good idea : )

**Comment by cgcgcg** [comment]
Yep. It fails first in Tpetra, but that can be "fixed" in a way that it compiles. It the fails in Amesos2, Belos and Xpetra. Most of these issues don't seem terrible, but that's obviously only results in compiling, but not necessarily working code.

**Comment by lucbv** [comment]
I guess we will take it one step as a time, first compile it, then make it work x)

**Pull request merged**
