### PR TITLE
Piro: Decouple MassSpringDamperModel from the rest

### PR DESCRIPTION
**Pull request by kliegeois**
@trilinos/piro
@mperego 

This PR decouples MassSpringDamperModel to be run with only one MPI rank.

### CODE REVIEW

**Review by rppawlo — APPROVED** [review]

**Comment by sebrowne** [comment]
Yes.  It's failing because Piro is explicitly disabled for the CUDA builds (no Epetra packages), but the reduced tarball test is deciding that it should be included (since this PR changes Piro).  I'll look at the test real quick to see if there's a way to fix it.

**Comment by sebrowne** [comment]
Wait, now that I say that, should Piro be disabled for non-epetra builds?  It looks like Piro's dependency on Epetra is optional.

**Comment by mperego** [comment]
> Wait, now that I say that, should Piro be disabled for non-epetra builds? It looks like Piro's dependency on Epetra is optional.
I think Piro should be enabled in non-epetra builds.

**Comment by sebrowne** [comment]
Oh darn it.  This was my fault.  When I supplied the list of packages to deprecate to the team earlier this year I typed 'Piro' when I meant 'Pike'.  Please delete any lines that say `opt-set-cmake-var Trilinos_ENABLE_Piro BOOL : OFF` from `packages/framework/ini-files/gen-config.ini` (lines 922 and 940 I believe) and add them to the PR, then this should work.

**Comment by sebrowne** [comment]
Also I apologize, this will likely build/test everything since it touches the Framework directory.  Completely my fault here.

**Comment by mperego** [comment]
> Also I apologize, this will likely build/test everything since it touches the Framework directory. Completely my fault here.

No worries, Sam. It's good we quickly figured out the issue.

**Comment by kliegeois** [comment]
Thanks @sebrowne @csiefer2 @rppawlo and @mperego for the comments, fixes, and reviews!

**Pull request merged**
