### PR TITLE
Amesos Package Warnings Fix

### PR DESCRIPTION
**Pull request by bddavid**
##### Attention:
@jwillenbring 
@trilinos/amesos

 - Removed unused timing code.
 - Removed unused variables.
 - Please refer to issue #66 for a detailed summary of the applied patch

Signed-off-by: bddavid <davidson@txcorp.com>

### CODE REVIEW

**Comment by jwillenbring** [comment]
@srajama1 

I want to make sure Siva is aware of this pull request.

**Comment by srajama1** [comment]
Jim, How does one accept such pull requests ? Just follow the standard instructions above or do we have a separate process for Trilinos ?

**Comment by jwillenbring** [comment]
Siva,

I  recommend using the command line instructions option to pull the change into your local clone and then using your usual checkin testing process to test. For cosmetic changes (comments, etc), using the merge button may be appropriate.

**Comment by jwillenbring** [comment]
@srajama1 
Siva,

I realized that you may not have seen my reply above because I didn't "mention" you in my reply. If that is the case, here is my reply:

I recommend using the command line instructions option to pull the change into your local clone and then using your usual checkin testing process to test. For cosmetic changes (comments, etc), using the merge button may be appropriate.

**Comment by srajama1** [comment]
Thanks, Jim. I actually saw the reply as all participants get the e-mail. I am just slow, sorry ! There are lot of other high priority things going that we need to deliver. I know this could be something simple, let me try and find some time to integrate it.

**Comment by srajama1** [comment]
Commit  8c1c89.. fixes this

**Comment by bartlettroscoe** [comment]
Can the associated Milestone "0002-Amesos-Package-Warnings-Fixes" be closed at this point?  It would be nice to unclutter the list of Trilinos/Milestones epics if possible.

**Comment by bartlettroscoe** [comment]
I am closing the associated milestone ""0002-Amesos-Package-Warnings-Fixes" to remove clutter.

**Pull request closed without merging**
