### PR TITLE
Zoltan2:  use same default data types at Tpetra

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/zoltan2 

## Description and Motivation

Zoltan2's default data types differed from Tpetra's, which could cause problems with explicit instantiation or confusing behavior for users.  This change makes Zoltan2's default data types match Tpetra's.  
Because Pamgen assumes coordinates are double, some changes were needed to copy coordinates into scalar_t arrays.
This PR addresses #604 .
To enable testing with default scalar_t = float, this PR also include the changes suggested in #3366.

## How Has This Been Tested?

Mac Clang with default Tpetra Explicit Instantiation and
Mac Clang with Tpetra_INST_DOUBLE=OFF and Tpetra_INST_FLOAT=ON.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).

- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [Maybe] These changes break backwards compatibility.

### CODE REVIEW

**Comment by kddevin** [comment]
I tested Zoltan2 with scalar=double disabled; it all works.
Since we expect all Trilinos users to want Scalar=double always, we wouldn't expect them to disable it.  With or without this change to Tpetra, disabling Scalar=double for other packages will not work.

**Comment by kddevin** [comment]
Let me run the Tpetra tests in the double=off configuration, too.  Stay tuned.

**Comment by mhoemmen** [comment]
@kddevin PR testing is failing and timing out a lot.  Framework folks are working on it, but for now, I would just mark everything as WIP and wait until the queue drains out a bit.

**Comment by kddevin** [comment]
With Tpetra_INST_DOUBLE=OFF and Tpetra_INST_FLOAT=ON, the Tpetra tests all compile and run.  Only the MatrixMatrix_UnitTests fail, as the operation does not satisfy the default epsilon (1e-10) specified in the test.

**Comment by prwolfe** [comment]
@kddevin I noticed that the 4.8.4 build failed on a communication error early so I reset the intel build as it takes the longest.  I am going to restart this and watch it directly.

**Pull request merged**
