### PR TITLE
Sacado: Fix relocatable device code ifdefs.

### PR DESCRIPTION
**Pull request by vbrunini**
@trilinos/Sacado

## Description
Correct ifdefs checking for whether or not relocatable device code is enabled.

## Motivation and Context
Prior to this building Sacado with rdc enabled would lead to multiple definition errors at link time.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by vbrunini** [comment]
@etphipp

**Comment by vbrunini** [comment]
Do I need to do something to trigger the autotester?

**Comment by etphipp** [comment]
No.  It is probably just busy.

**Comment by mhoemmen** [comment]
@trilinos/sacado

**Pull request merged**
