### PR TITLE
Tpetra: Fix #2681 (test randomly timing out w/ CUDA)

### LINKED ISSUE #2681: Test TpetraCore_ImportBug5430_MPI_4 randomly timing out in Trilinos-atdm-white-ride-cuda-opt build on 'white' and 'ride'
**CC**: @trilinos/tpetra, @fryeguy52 

## Next Action Status

Next: Temporarily disable the test so that the build `Trilinos-atdm-white-ride-cuda-opt` can be promoted to the "ATDM" CDash Track/Group ...

## Description

The query:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride-cuda-opt&field2=testname&compare2=61&value2=TpetraCore_ImportBug5430_MPI_4&field3=site&compare3=61&value3=white&field4=buildstarttime&compare4=84&value4=now

seems to show that the test `TpetraCore_ImportBug5430_MPI_4` is randomly hanging for in the build `Trilinos-atdm-white-ride-cuda-opt`.  When the test passes, it finished in less than 2 sec.   And then it times out every so often at 10 minutes.  It timed out 8 times out of 44 days.

That suggests a race condition involving threads or something?

## Steps to reproduce

Anyone with access to the machines 'white' or 'ride' should be able to build and run this test with as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

Specifically, one should be able to do:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-opt

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Tpetra=ON \
  $TRILINOS_DIR

$ make NP=16

$ bsub -x -Is -q rhel7F -n 16 ctest -R TpetraCore_ImportBug5430_MPI_4
```

However, given that this test is failing randomly, one may need to run it a bunch of times in hope of getting it to time out.  Also, you might need to run the entire Tpetra test suite many times in order to reproduce this behavior.

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra Fix #2681: Don't create Kokkos::View (or things that contain them) at main() scope, since their destructors will get called before Kokkos::finalize gets called.  The test was otherwise fine.  As soon as I moved the objects to be created and destroyed before Kokkos::finalize was called, the test passed.

@trilinos/tpetra

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@mhoemmen, why not just have this test use Teuchos::GlobalMPISession and then the destructor for that object will call Kokkos::finalize()?  That is why you want to use an object with a destructor.

Otherwise, this looks fine.  But the design of is unfortunate.

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> @mhoemmen, why not just have this test use Teuchos::GlobalMPISession and then the destructor for that object will call Kokkos::finalize()? That is why you want to use an object with a destructor.
> 
> Otherwise, this looks fine. But the design of is unfortunate.

Thanks Ross!  I didn't actually write this test.  Better practice would be to use the Teuchos unit test framework.  Some Tpetra tests have a modified Teuchos unit test main, that uses scope guards and correctly gives `argc` and `argv` to Kokkos::initialize.  I think that would be the best idea.

**Comment by mhoemmen** [comment]
@bartlettroscoe Oh wait, I see what you mean: `GlobalMPISession` _does_ call `Kokkos::finalize_all`: https://github.com/trilinos/Trilinos/blob/07763eba3410a652dd67c783f46bf34cb378339b/packages/teuchos/core/src/Teuchos_GlobalMPISession.cpp#L192

**Comment by bartlettroscoe** [comment]
The point of using an object Tuechos::GlobalMPISession is that its destructor will be the last one called in main().  Therefore, if you construct that object first, it will be destructed last.  That is the trick.

**Pull request merged**
