### PR TITLE
Tempus: Initial Documentation for Iteration Matrix.

### LINKED ISSUE #6637: Tempus:  Document Iteration Matrices
## Documentation
@trilinos/tempus 

Document the iteration matrix that is used in Tempus.  In some places it is different than what was used in Rythmos which could cause confusion.

### PR DESCRIPTION
**Pull request by ccober6**
No code changes, just new doxygen.  The iteration matrix, W,
for all the steppers, except IMEX-RK and IMEX-RK Partition,
have been documented.

@trilinos/tempus 

Closes #6637 

## Motivation
Clearly document what is the iteration matrix and its expression for the first-order implicit ODEs.

## Testing
Doxygen builds correctly.

### CODE REVIEW

**Comment by ccober6** [comment]
@sconde @asteyer @rppawlo I have started some documentation on the iteration matrix to help clarify its definition and usage.  If you have time, please review this and give me feedback (e.g., is it clear?, and are there errors?).

At the moment I am working on IMEX-RK and IMEX-RK Partition, but all the other first-order implicit steppers should be documented.  Please look at StepperImplicit for the general discussion.  Thanks!

**Comment by ccober6** [comment]
FYI, this came about in helping @sconde on the Drekar BC issue when using Tempus (https://github.com/rppawlo/DrekarBase/issues/378#issuecomment-577412023).

**Comment by sconde** [comment]
Thank you so much for doing this!

**Comment by ccober6** [comment]
@asteyer can you review this and approval if ready?  Thanks!

**Pull request merged**
