### PR TITLE
Kokkos promotion to 3.3.01

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos
@trilinos/kokkos-kernels

Integration update of Kokkos + KokkosKernels release 3.3.00

Testing results posted at kokkos/kokkos#3673

### CODE REVIEW

**Comment by ndellingwood** [comment]
@srajama1 @lucbv @dalg24

**Comment by ndellingwood** [comment]
Adding @rppawlo for interest in testing with EMPIRE

**Comment by rppawlo** [comment]
@ndellingwood - tried to test against empire but am getting an installation failure with this PR:
```
CMake Error at packages/kokkos/cmake_install.cmake:75 (file):
  file INSTALL cannot find
  "/ascldap/users/rppawlo/tmp/Trilinos/bin/nvcc_wrapper": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:156 (include)

```

**Comment by ndellingwood** [comment]
@rppawlo thanks for testing, I'm looking into that now

**Comment by ndellingwood** [comment]
@rppawlo fixes for the install issue (as well as the stokhos failure during PR testing) have been resolved, this should be ready for retest

**Comment by rppawlo** [comment]
Thanks @ndellingwood !

**Comment by crtrott** [comment]
@prwolfe @jwillenbring Note when this goes in C++14 is mandatory. Is the rest of the testing ready for it? As soon as @rppawlo comes back and this is OK for empire, we will release in Kokkos itself. We will leave this to you guys for merging into Trilinos.

**Comment by rppawlo** [comment]
clang/serial and gcc/openmp have passed. cuda build is going now but will probably take a couple of hours. Looks good so far!

**Comment by crtrott** [comment]
Great! Thanks Roger. Having you test Empire certainly makes us feel a bit more confident that we didn't screw something up. And I mean we already did with the install issue you caught!

**Comment by crtrott** [comment]
@rppawlo any update?

**Comment by rppawlo** [comment]
@crtrott - currently finished 883 out of 1230 tests. So far all tests have passed. We have hit all the major capabilities in all repos so I would say yes - this is ready to push. Probably an hour away from completing the last 300 tests. I'll post when they finish but feel free to push.

**Comment by rppawlo** [comment]
@crtrott - everything passed. Good to go! Thanks!

**Comment by prwolfe** [comment]
I think everything is ready to merge with the exception of Vortex. It looks like I will need the ability to use -iSystem to pass the -std=c++1y flag through. That change does not appear to be in this patch set (not did I see it in the 3_3_0 branch of kokkos when I pulled that.) Can you point me at that?

Paul

**Comment by crtrott** [comment]
FYI: I updated this to Kokkos 3.3.1 which fixes a severe performance issue in DualView which we only found Christmas Eve.

**Review by crtrott — DISMISSED** [review]

**Comment by crtrott** [comment]
I am checking an XL build on Vortex too and looks like I am successful (see comment in #8317 ). The two main steps are: I needed a new cfg file for XL using GCC 7.3.0 for headers (the existing 8.3 doesn't work). And I needed to use a newer cmake (loaded the 3.18 module on vortex).

**Review by crtrott — APPROVED** [review]

**Comment by bartlettroscoe** [comment]
This version of Kokkos requires C++14?

**Comment by crtrott** [comment]
Yes it does.

**Comment by crtrott** [comment]
Note we have now decoupled Kokkos release from merging into Trilinos, since this is still being held up due to atdm configuration issues PR testing the first time passed for the 3.3 release mid December and was confirmed by @rppawlo to work with full Empire testing in multiple configurations. The PR was then broken again by additional changes to Trilinos develop, but we fixed that again.

**Comment by bartlettroscoe** [comment]
> was confirmed by @rppawlo to work with full Empire testing in multiple configurations. 

@crtrott, @rppawlo,

That was confirmed on the the 'ats2' machine 'vortex'?  If so, how?

**Comment by crtrott** [comment]
He didn't do an XL test and didn't deem it important. They run CUDA with GCC as the host compiler primarily is my understanding.

**Comment by rppawlo** [comment]
not on vortex - I did cuda, clang (serial) and gcc (openmp) builds on the empire testing machines. Whole suite passed in all cases. I don't know of any empire builds with XL compiler. cc'ing @bathmatt to be sure.

**Comment by bartlettroscoe** [comment]
> not on vortex - I did cuda, clang (serial) and gcc (openmp) builds on the empire testing machines

@crtrott, @rppawlo,

Yup, CUDA builds on the sems-rhel7 machines and every other CUDA build were fine (except for known failing tests) for Trilinos as well as I documented in https://github.com/trilinos/Trilinos/pull/8317#issuecomment-723138268 (way back on 11/06/2020) and can see at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2020-11-06&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda

showing:

| Site | Build Name | Update | Update Time | Conf Error| Conf Warn | Conf Time | Build Error| Build Warn | Build Time | Test Not Run | Test Fail | Test Pass | Test Time | Test Proc Time | Start Test Time | Labels |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_static_dbg | 55906c | 1m 6s | 0 | 4 | 4m 53s | 0 | 50 | 12h 33m 49s | 0 | 16 | 2306 | 2h 21m 44s | 9h 3m 42s | Nov 06, 2020 - 02:28 MST | (31 labels)
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_static_dbg_cuda-aware-mpi |   |   | 0 | 4 | 4m 9s | 0 | 0 | 1m 31s | 0 | 2295 | 27 | 47m 23s | 3h 6m 1s | Nov 06, 2020 - 17:31 MST | (31 labels)
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_static_opt | 55906c | 1m | 0 | 4 | 4m 48s | 0 | 50 | 6h 3m 53s | 0 | 16 | 2363 | 1h 24m 16s | 5h 20m 47s | Nov 06, 2020 - 03:01 MST | (31 labels)
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_static_opt_cuda-aware-mpi |   |   | 0 | 4 | 5m 5s | 0 | 0 | 2m 3s | 0 | 12 | 2367 | 1h 20m 59s | 5h 9m 28s | Nov 06, 2020 - 10:37 MST | (31 labels)
vortex | Trilinos-atdm-ats2-cuda-10.1.243-xl-2020.03.18_spmpi-rolling_static_dbg | 55906c | 2m 18s | 0 | 4 | 3m 52s | 20 | 0 | 5m 20s | 0 | 0 | 0 | 0s | 0s | Nov 06, 2020 - 06:02 MST | (16 labels)
vortex | Trilinos-atdm-ats2-cuda-10.1.243-xl-2020.03.18_spmpi-rolling_static_opt | 55906c | 1m 12s | 0 | 4 | 2m 54s | 20 | 0 | 3m 5s | 0 | 0 | 0 | 0s | 0s | Nov 06, 2020 - 04:35 MST | (16 labels)
cee-rhel6 | Trilinos-atdm-cee-rhel6_mini-no-mpi_cuda-10.1.243_gcc-7.2.0_static_opt | 55906c | 0s | 0 | 3 | 24s | 0 | 1 | 4m 8s | 0 | 0 | 84 | 51s | 4m 34s | Nov 06, 2020 - 09:17 MST | (2 labels)
cee-rhel6 | Trilinos-atdm-cee-rhel6_mini_cuda-10.1.243_gcc-7.2.0_openmpi-4.0.3_static_dbg | 55906c | 6s | 0 | 4 | 27s | 0 | 1 | 4m 20s | 0 | 1 | 97 | 2m 30s | 11m 46s | Nov 06, 2020 - 09:09 MST | (2 labels)
cee-rhel6 | Trilinos-atdm-cee-rhel6_mini_cuda-10.1.243_gcc-7.2.0_openmpi-4.0.3_static_opt | 55906c | 0s | 0 | 4 | 26s | 0 | 1 | 4m 25s | 0 | 0 | 98 | 1m 17s | 9m 27s | Nov 06, 2020 - 09:03 MST | (2 labels)
sems-rhel7 | Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | 55906c | 6s | 0 | 3 | 1m 9s | 0 | 50 | 45m 33s | 0 | 3 | 1150 | 55m 46s | 3h 33m 9s | Nov 06, 2020 - 03:33 MST | (15 labels)
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug | 55906c | 12s | 0 | 21 | 3m 9s | 0 | 50 | 8h 23m 53s | 0 | 3 | 2120 | 1h 45m 32s | 6h 25m 46s | Nov 06, 2020 - 10:08 MST | (29 labels)
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug | 55906c | 12s | 0 | 21 | 3m 9s | 0 | 50 | 7h 13m 4s | 0 | 3 | 2156 | 2h 10m 27s | 8h 6m 35s | Nov 06, 2020 - 03:39 MST | (29 labels)
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release | 55906c | 18s | 0 | 21 | 3m 23s | 0 | 50 | 1h 7m 5s |   |   |   |   |   | Nov 06, 2020 - 20:21 MST | (29 labels)
ride | Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug | 55906c | 24s | 0 | 21 | 3m 14s | 0 | 50 | 8h 20m 45s |   |   |   |   |   | Nov 06, 2020 - 13:06 MST | (29 labels)
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_complex_static_opt | 55906c | 1m 6s | 0 | 5 | 2m 27s | 0 | 50 | 2h 13m 33s | 0 | 6 | 1145 | 29m | 1h 48m 51s | Nov 06, 2020 - 02:16 MST | (15 labels)
vortex | Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_complex_static_opt_cuda-aware-mpi |   |   | 0 | 5 | 2m 29s | 0 | 0 | 1m 10s | 0 | 6 | 1145 | 29m 6s | 1h 50m 16s | Nov 06, 2020 - 05:03 MST | (15 labels)
cee-rhel6 | Trilinos-atdm-cee-rhel6_cuda-10.1.243_gcc-7.2.0_openmpi-4.0.3_shared_dbg | 55906c | 0s | 0 | 5 | 3m 14s | 0 | 51 | 6h 28m 50s | 0 | 5 | 2328 | 1h 21m 37s | 9h 53m 30s | Nov 06, 2020 - 01:09 MST | (31 labels)
cee-rhel6 | Trilinos-atdm-cee-rhel6_cuda-10.1.243_gcc-7.2.0_openmpi-4.0.3_shared_opt | 55906c | 0s | 0 | 5 | 3m 18s | 0 | 51 | 1h 15m 36s | 0 | 4 | 2375 | 1h 4m 48s | 7h 54m 21s | Nov 05, 2020 - 22:45 MST | (31 labels)

**Comment by bartlettroscoe** [comment]
> He didn't do an XL test and didn't deem it important. They run CUDA with GCC as the host compiler primarily is my understanding.

@crtrott, EMPIRE does not care about XL but SPARC does.

CC: @tcfisher, @sebrowne, @rppawlo

**Comment by crtrott** [comment]
I believe I remember that @tcfisher said they are ok if the XL ATDM test breaks for a while, since they use their own version of Trilinos anyway?

**Comment by tcfisher** [comment]
> I believe I remember that @tcfisher said they are ok if the XL ATDM test breaks for a while, since they use their own version of Trilinos anyway?

If it's just that we need to change flags or XL backends then yes I'm fine with this breaking. We do not wish to hold up the move to c++14 over XL.

**Comment by crtrott** [comment]
Given Travis's comment what else do we need to get in to merge this? Do we need to get #8317 in? Also that one says "DO NOT MERGE" still.

**Comment by crtrott** [comment]
Alternative approach is we merge this here, and then fix what breaks ...

**Comment by crtrott** [comment]
Adding auto merge flag, the C++ 14 requirement went through

**Pull request merged**
