### PR TITLE
Add support for Kokkos::atomic_add() with Sacado Fad types

### PR DESCRIPTION
**Pull request by etphipp**
Requested by @CamelliaDPG.  This provides overloads of Kokkos::atomic_add() for all Fad types.  It also implements operator&() for ViewFad, allowing you to do things like 
```
Kokkos::atomic_add(&v(i,j,k),x);
```
Note that because of this overload, ViewFad::operator&() does not return ViewFad*, which required a small change in Phalanx.  Since you could only safely take the address of a ViewFad in limited situations, I am hoping this kind of change is not needed in many places.

### CODE REVIEW

**Comment by CamelliaDPG** [comment]
@etphipp, thanks for working on this!  Maybe I'm missing something, but I'm getting the same build errors as I was before.  Do you expect that this should work even with a `DynRankView`?  Here's an example error:
```
/Users/nvrober/intrepid-performance/Assembly.cpp:1106:34: error: taking the address of a temporary object of type 'typename std::enable_if<!(std::is_same<typename drvtraits::specialize, void>::value &&
      std::is_integral<int>::value), reference_type>::type' (aka 'Sacado::Fad::ViewFad<double, 10, 1, Sacado::Fad::SFad<double, 10> >') [-Waddress-of-temporary]
              Kokkos::atomic_add(&cellStiffness(cellOrdinal,iNode,jNode), (iGradient * jGradient) * ptMeasure);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
where `cellStiffness` is a `DynRankView` of a Fad type (at the moment, I'm trying `Sacado::Fad::SFad<double,10>`).

**Comment by etphipp** [comment]
Hmm, no using DynRankView doesn't matter.  These changes all have to do with the Fad types themselves, not with View/DynRankView.

What compiler are you using?  It is possible the compiler you are using always warns about taking the address of a temporary if you have -Waddress-of-temporary, which you appear to do.  The compiler I tested with, gcc 4.9.3, gives an error without these changes and doesn't with them.

**Comment by etphipp** [comment]
I did some digging and that appears to be a clang warning.  Are you using clang?  If so, can you try adding -Wno-address-of-temporary to your CXX flags and see if it works?

If that's the case, we might want to consider using some traits function to form the first argument to atomic_add() instead of the & operator.

**Comment by CamelliaDPG** [comment]
@etphipp, yes that is indeed a clang error; I am using clang.  I tried adding `-Wno-address-of-temporary` to my CXX_FLAGS, and that did eliminate the error I cited above.  There is, however, another:

```
/Users/nvrober/intrepid-performance/Assembly.cpp:1104:15: error: no matching function for call to 'atomic_add'
              Kokkos::atomic_add(&cellStiffness(cellOrdinal,iNode,jNode), Scalar((iGradient * jGradient) * ptMeasure));
              ^~~~~~~~~~~~~~~~~~
/Users/nvrober/intrepid-performance/Assembly.cpp:469:14: note: in instantiation of function template specialization 'Assembly<Sacado::Fad::SFad<double, 10>, 10>::performFusedQuadratureSimplex<3,
      Intrepid2::Basis_HGRAD_TET_Cn_FEM<Kokkos::Serial, Sacado::Fad::SFad<double, 10>, double>, 0>' requested here
      return performFusedQuadratureSimplex<spaceDim,Basis,0>(meshWidth,gradientAlgorithm);
             ^
/Users/nvrober/trilinos-builds/etphipps-release-master-minimal-intrepid2/include/impl/Kokkos_Atomic_Fetch_Add.hpp:380:6: note: candidate template ignored: deduced conflicting types for parameter 'T'
      ('Sacado::Fad::ViewFad<double, 10, 1, Sacado::Fad::SFad<double, 10> >' vs. 'Sacado::Fad::SFad<double, 10>')
void atomic_add(volatile T * const dest, const T src) {
```

**Comment by CamelliaDPG** [comment]
@etphipp, I had a `checkout master` line in my `do-config` script that clobbered my checkout of the correct branch.  That was the source of the above issue.  However, now that I've corrected that, I do (alas) have another:
```
/Users/nvrober/trilinos-builds/etphipps-release-master-minimal-intrepid2/include/Sacado_Fad_ViewFad_tmpl.hpp:281:9: error: 
      no member named 'cache' in 'Sacado::Fad::Expr<Sacado::Fad::SFadExprTag<double, 10>, Sacado::Fad::ExprSpecDefault>'
      x.cache();
      ~ ^
/Users/nvrober/intrepid-performance/Assembly.cpp:1104:23: note: in instantiation of function template specialization
      'Sacado::Fad::atomic_add<double, 10, 1, Sacado::Fad::SFad<double, 10>, Sacado::Fad::SFadExprTag<double, 10> >'
      requested here
              Kokkos::atomic_add(&cellStiffness(cellOrdinal,iNode,jNode), Scalar((iGradient * jGradient) * ptMeasure));
                      ^
/Users/nvrober/intrepid-performance/Assembly.cpp:469:14: note: in instantiation of function template specialization
      'Assembly<Sacado::Fad::SFad<double, 10>, 10>::performFusedQuadratureSimplex<3,
      Intrepid2::Basis_HGRAD_TET_Cn_FEM<Kokkos::Serial, Sacado::Fad::SFad<double, 10>, double>, 0>' requested here
      return performFusedQuadratureSimplex<spaceDim,Basis,0>(meshWidth,gradientAlgorithm);
```

**Comment by etphipp** [comment]
Btw, I believe the auto-tester failed because they have shut down the Jenkins server for maintenance.

**Comment by etphipp** [comment]
@CamelliaDPG, Great!  Would you be willing to approve the PR then?  I still want to get Roger's approval before merging though, because this involved a Phalanx change.

**Pull request merged**
