### PR TITLE
KokkosKernels: Patch in Distance-2 graph coloring update

### PR DESCRIPTION
**Pull request by william76**
Patching in the Distance-2 Graph Coloring to get in the new code + deprecations for the upcoming Trilinos release.

Adding @csiefer2 to reviewers because I touched the MueLu use of the call to `d2_graph_color`.  I didn't change which algorithm is being used (still using the serial D2 coloring), but the function name was changed.  The old one exists and prints out a deprecation warning, but since I'm here I might as well just point MueLu at the new call.

@trilinos/kokkos-kernels 
@trilinos/muelu 
@ndellingwood

### CODE REVIEW

**Comment by william76** [comment]
I am seeing that this failed builds on [CDash][1]. It looks like I missed some stuff on my patch in the [Kokkos-Kernels testing][2].  

Added the WIP flag to look for the stuff I've missed.


[1]: https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PR-4811
[2]: https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4835978

**Comment by lucbv** [comment]
@william76 I notice that you have some commits in your branch that have already merged into the develop branch, can you rebase you branch on top of develop so that these duplicate won't appear anymore?

**Comment by william76** [comment]
@lucbv ok, so I tried rebasing and now it's got even more junk in from develop.  everything on this is from develop so I'm not sure why it's trying to pull in branches that are already in develop.  :/

**Comment by jmgate** [comment]
> @lucbv ok, so I tried rebasing and now it's got even more junk in from develop. everything on this is from develop so I'm not sure why it's trying to pull in branches that are already in develop. :/
> 
> you know how to fix that? nothing in here wouldn't already be in develop though... so does it really matter?

I'm not sure what you did, but it involved using rebase improperly.  We now have a handful of identical (in terms of the diffs) commits with differing SHA1s that have been merged into `develop` at different points.  Not the end of the world, but not ideal.  Next time you see a bunch of commits in a PR that look like they shouldn't be there, remove the "AT: AUTOMERGE" label and have someone fix the branch.

**Pull request merged**
