### PR TITLE
Amesos2: 7413 STRUMPACK interface in Amesos2 (new)

### PR DESCRIPTION
**Pull request by pghysels**
This is a new PR, replacing https://github.com/trilinos/Trilinos/pull/7417, which I messed up by doing a rebase.

See this issue: https://github.com/trilinos/Trilinos/issues/7413

This PR is to include an interface to the STRUMPACK sparse solver in Amesos2.
See 
https://github.com/pghysels/STRUMPACK
https://portal.nersc.gov/project/sparse/strumpack/

@trilinos/Amesos2

## Motivation
This is for an ECP milestone.

### CODE REVIEW

**Comment by pghysels** [comment]
I configured STRUMPACK (5.0.0) as follows:
```
export METIS_DIR=$HOME/local/metis-5.1.0/install
cmake ../ \
          -DCMAKE_BUILD_TYPE=Debug \
          -DSTRUMPACK_USE_MPI=ON \
          -DCMAKE_INSTALL_PREFIX=../install \
          -DTPL_SCALAPACK_LIBRARIES="$HOME/local/scalapack-2.1.0/install/lib/libscalapack.a"
```

and Trilinos with:
```
cmake ../ \
      -DCMAKE_INSTALL_PREFIX=../install \
      -DTPL_ENABLE_MPI=ON \
      -DTrilinos_ENABLE_COMPLEX=ON \
      -DTrilinos_ENABLE_COMPLEX_FLOAT=ON \
      -DTrilinos_ENABLE_COMPLEX_DOUBLE=ON \
      -DTeuchos_ENABLE_COMPLEX:BOOL=ON \
      -DTrilinos_ENABLE_OpenMP=ON \
      -DTPL_ENABLE_Netcdf=OFF \
      -DTPL_ENABLE_METIS=ON \
      -DMETIS_LIBRARY_DIRS="$HOME/local/metis-5.1.0/install/lib" \
      -DMETIS_INCLUDE_DIRS="$HOME/local/metis-5.1.0/install/include" \
      -DTPL_ENABLE_BLACS=OFF \
      -DTrilinos_ENABLE_Amesos2=ON \
      -DAmesos2_ENABLE_TESTS=ON \
      -DAmesos2_ENABLE_STRUMPACK=ON \
      -DTPL_ENABLE_STRUMPACK=ON \
      -DSTRUMPACK_LIBRARY_DIRS='/home/pieterg/LBL/STRUMPACK/STRUMPACK/install/lib' \
      -DSTRUMPACK_INCLUDE_DIRS='/home/pieterg/LBL/STRUMPACK/STRUMPACK/install/include' \
      -DTrilinos_EXTRA_LINK_FLAGS="-L$HOME/local/scalapack-2.1.0/install/lib/ -lscalapack -lopenblas"
```

**Comment by pghysels** [comment]
@cgcgcg 
@ndellingwood 
@srajama1 
@jhux2 

(@lisaclaus  @xiaoyeli)

**Comment by jwillenbring** [comment]
@srajama1 Could you take a look at this PR, or ask another appropriate developer to do so?

**Comment by jwillenbring** [comment]
Looks like @ndellingwood was previously involved in this conversation. Perhaps it would be better for him to look at this?

**Comment by ndellingwood** [comment]
@jwillenbring I'll attempt to rebuild locally and confirm this afternoon, the previous PR had review comments that appear to have already been addressed.

**Comment by xiaoyeli** [comment]
@jwillenbring @ndellingwood 
Thank you very much for following up with this!   We have an ECP milestone due on Oct. 31.  It is about the STRUMPACK integration with Trilinos:  https://jira.exascaleproject.org/browse/STMS08-80
Thanks for your help!

**Comment by ndellingwood** [comment]
I'm still having some link issues in Trilinos, though I'm assuming it is due to my configuration since @pghysels is able to compile and test successfully.

Here is what I'm seeing:
```duplicate symbol _scombssq_ in: 
    /Users/ndellin/Research/TPL/TPL_GCC8/OpenBLAS-0.3.9/install/lib/libopenblas.a(scombssq.o)
    /Users/ndellin/Research/TPL/TPL_GCC8/scalapack-2.1.0/install/lib//libscalapack.a(pstreecomb.f.o)
duplicate symbol _dcombssq_ in: 
    /Users/ndellin/Research/TPL/TPL_GCC8/OpenBLAS-0.3.9/install/lib/libopenblas.a(dcombssq.o)
    /Users/ndellin/Research/TPL/TPL_GCC8/scalapack-2.1.0/install/lib//libscalapack.a(pdtreecomb.f.o)
ld: 2 duplicate symbols for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [packages/amesos2/test/solvers/Amesos2_STRUMPACK_UnitTests.exe] Error 1
make[1]: *** [packages/amesos2/test/solvers/CMakeFiles/Amesos2_STRUMPACK_UnitTests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Here is my configuration, modified slightly from above based on my tpl paths etc:

```bash
TRILINOS_DIR=${PWD}/../..

TPL_PATH=/Users/ndellin/Research/TPL/TPL_GCC8
OPENBLAS_PATH=${TPL_PATH}/OpenBLAS-0.3.9/install

BLAS_LIBRARIES="${OPENBLAS_PATH}/lib/libopenblas.a;gfortran;gomp;m"
LAPACK_LIBRARIES="${OPENBLAS_PATH}/lib/libopenblas.a;gfortran;gomp;m"

SCOTCH_PATH=${TPL_PATH}/scotch_6.0.3
PARMETIS_PATH=${TPL_PATH}/parmetis-4.0.3/install
METIS_PATH=${TPL_PATH}/metis-5.1.0/install

SCALAPACK_PATH=${TPL_PATH}/scalapack-2.1.0/install
STRUMPACK_PATH=${TPL_PATH}/STRUMPACK-4.0.0/install

cmake ${TRILINOS_DIR} \
      -DCMAKE_INSTALL_PREFIX=${PWD}/install \
      -DTrilinos_ENABLE_TESTS:BOOL=OFF \
      -DTrilinos_ENABLE_EXAMPLES:BOOL=OFF \
      -DTrilinos_ENABLE_COMPLEX_DOUBLE=ON \
      -DTPL_ENABLE_MPI=ON \
      -DTrilinos_ENABLE_OpenMP=ON \
      -DTPL_ENABLE_BLAS:STRING=ON \
      -DTPL_ENABLE_LAPACK:STRING=ON \
        -DTPL_BLAS_LIBRARIES:PATH="${BLAS_LIBRARIES}" \
        -DTPL_LAPACK_LIBRARIES:PATH="${LAPACK_LIBRARIES}" \
      -DTPL_ENABLE_Netcdf=OFF \
      -DTPL_ENABLE_METIS=ON \
       -DMETIS_LIBRARY_DIRS="${METIS_PATH}/lib" \
       -DMETIS_INCLUDE_DIRS="${METIS_PATH}/include" \
      -DTPL_ENABLE_BLACS=OFF \
      -DTrilinos_EXTRA_LINK_FLAGS="-L${SCALAPACK_PATH}/lib/ -lscalapack" \
      -DTrilinos_ENABLE_Amesos2=ON \
      -DAmesos2_ENABLE_STRUMPACK=ON \
       -DAmesos2_ENABLE_TESTS=ON \
       -DAmesos2_ENABLE_EXAMPLES=ON \
      -DTPL_ENABLE_STRUMPACK=ON \
        -DSTRUMPACK_LIBRARY_DIRS="${STRUMPACK_PATH}/lib" \
        -DSTRUMPACK_INCLUDE_DIRS="${STRUMPACK_PATH}/include"\
```

I had tried variations on the extra link flags similar to the how it was posted without success, e.g.

-DTrilinos_EXTRA_LINK_FLAGS="-L${SCALAPACK_PATH}/lib/ -lscalapack -L${OPENBLAS_PATH}/lib/ -lopenblas"

@pghysels did you run into linkage issues when setting up your Trilinos configuration, and what changes did you make to get around them if so? Which version of OpenBLAS are you using?

**Comment by pghysels** [comment]
I was using OpenBLAS 0.3.8, and scalapack 2.1.0., on Ubuntu 20.04.
I have not seen that specific error before.

I will try myself with OpenBLAS 0.3.9.

**Comment by srajama1** [comment]
@ndellingwood : Thanks for helping with this ! @xiaoyeli @pghysels : I didn't realize this was an ECP milestone. We will help you with the integration as soon as you can check with the different version of OpenBLAS.

**Comment by pghysels** [comment]
I have no issues with OpenBLAS 0.3.9 either.

```
OPENBLAS_PATH=$HOME/local/OpenBLAS-0.3.9/
BLAS_LIBRARIES="${OPENBLAS_PATH}/libopenblas.a;gfortran;gomp;m"
LAPACK_LIBRARIES="${OPENBLAS_PATH}/libopenblas.a;gfortran;gomp;m"
cmake ../ \
      -DCMAKE_INSTALL_PREFIX=../install \
      -DTPL_ENABLE_MPI=ON \
      -DTrilinos_ENABLE_COMPLEX=ON \
      -DTrilinos_ENABLE_COMPLEX_FLOAT=ON \
      -DTrilinos_ENABLE_COMPLEX_DOUBLE=ON \
      -DTeuchos_ENABLE_COMPLEX:BOOL=ON \
      -DTrilinos_ENABLE_OpenMP=ON \
      -DTPL_ENABLE_Netcdf=OFF \
      -DTPL_ENABLE_METIS=ON \
      -DMETIS_LIBRARY_DIRS="$HOME/local/metis-5.1.0/install/lib" \
      -DMETIS_INCLUDE_DIRS="$HOME/local/metis-5.1.0/install/include" \
      -DTPL_ENABLE_BLAS:STRING=ON \
      -DTPL_ENABLE_LAPACK:STRING=ON \
        -DTPL_BLAS_LIBRARIES:PATH="${BLAS_LIBRARIES}" \
        -DTPL_LAPACK_LIBRARIES:PATH="${LAPACK_LIBRARIES}" \
      -DTPL_ENABLE_BLACS=OFF \
      -DTrilinos_ENABLE_Amesos2=ON \
      -DAmesos2_ENABLE_TESTS=ON \
      -DAmesos2_ENABLE_STRUMPACK=ON \
      -DTPL_ENABLE_STRUMPACK=ON \
      -DSTRUMPACK_LIBRARY_DIRS='/home/pieterg/LBL/STRUMPACK/STRUMPACK/install/lib' \
      -DSTRUMPACK_INCLUDE_DIRS='/home/pieterg/LBL/STRUMPACK/STRUMPACK/install/include' \
      -DTrilinos_EXTRA_LINK_FLAGS="-L$HOME/local/scalapack-2.1.0/install/lib/ -lscalapack -lopenblas"

```

**Comment by pghysels** [comment]
I also tried with GCC 8.4.0 (before I was using gcc 9.3.0). That also works for me.

I have a file with the link command:
build/packages/amesos2/test/solvers/CMakeFiles/Amesos2_STRUMPACK_UnitTests.dir/link.txt

for me this file contains:
`/usr/bin/g++-8   -pedantic -Wall -Wno-long-long -Wwrite-strings -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include -fopenmp  -O3 -DNDEBUG   CMakeFiles/Amesos2_STRUMPACK_UnitTests.dir/STRUMPACK_UnitTests.cpp.o CMakeFiles/Amesos2_STRUMPACK_UnitTests.dir/__/__/__/teuchos/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o  -o Amesos2_STRUMPACK_UnitTests.exe  ../../src/libamesos2.a ../../../shylu/shylu_node/tacho/src/libtacho.a ../../../common/auxiliarySoftware/SuiteSparse/src/libtrilinosss.a ../../../kokkos/algorithms/src/libkokkosalgorithms.a ../../../kokkos/containers/src/libkokkoscontainers.a ../../../kokkos/core/src/libkokkoscore.a ../../../../liblast_lib.a ../../../tpetra/core/ext/libtpetraext.a ../../../tpetra/core/inout/libtpetrainout.a ../../../tpetra/core/src/libtpetra.a ../../../tpetra/tsqr/src/libkokkostsqr.a ../../../kokkos-kernels/src/libkokkoskernels.a ../../../kokkos/algorithms/src/libkokkosalgorithms.a ../../../kokkos/containers/src/libkokkoscontainers.a ../../../tpetra/classic/LinAlg/libtpetraclassiclinalg.a ../../../tpetra/classic/NodeAPI/libtpetraclassicnodeapi.a ../../../tpetra/classic/src/libtpetraclassic.a ../../../epetraext/src/libepetraext.a ../../../triutils/src/libtriutils.a ../../../epetra/src/libepetra.a ../../../teuchos/kokkoscomm/src/libteuchoskokkoscomm.a ../../../teuchos/kokkoscompat/src/libteuchoskokkoscompat.a ../../../teuchos/remainder/src/libteuchosremainder.a ../../../teuchos/numerics/src/libteuchosnumerics.a /home/pieterg/local/OpenBLAS-0.3.9/libopenblas.a -lgfortran -lgomp /home/pieterg/local/OpenBLAS-0.3.9/libopenblas.a -lgfortran -lgomp -lm ../../../teuchos/comm/src/libteuchoscomm.a ../../../teuchos/parameterlist/src/libteuchosparameterlist.a ../../../teuchos/parser/src/libteuchosparser.a ../../../teuchos/core/src/libteuchoscore.a ../../../kokkos/core/src/libkokkoscore.a /usr/lib/x86_64-linux-gnu/libdl.so /home/pieterg/LBL/STRUMPACK/STRUMPACK/install/lib/libstrumpack.a /home/pieterg/local/metis-5.1.0/install/lib/libmetis.a -pthread -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi_cxx -lmpi -L/home/pieterg/local/scalapack-2.1.0/install/lib/ -lscalapack -lopenblas -lgfortran -lquadmath 
`

I tried some variations of this link line, like swapping the order of scalapack and openblas, but I cannot reproduce your error.

**Comment by ndellingwood** [comment]
Thanks for the extra checks @pghysels, this is good to know. I have a couple more tpl configure/build questions to try and find a common build setup.

1. Maybe I'm building OpenBLAS in an incompatible way with this PR, do you have any comments on my steps or could you share how are you building OpenBLAS (your local 0.3.9 version)?

Here are my OpenBLAS compilation steps I've been using the Makefile (I'm compiling with gcc/8):
```bash
cd <OPENBLAS-0.3.9_DIR>
make CC=`which gcc` FC=`which gfortran` PREFIX=`pwd`/install USE_OPENMP=1 VERBOSE=1 -j 4
make CC=`which gcc` FC=`which gfortran` PREFIX=`pwd`/install USE_OPENMP=1 VERBOSE=1 -j 4 install
```

2. Similarly, how are you building scalapack? I used the Makefile, here is my `SLmake.inc` file, the only changes form the example was to point BLASLIB and LAPACKLIB to my OpenBLAS install:
```bash
############################################################################
#
#  Program:         ScaLAPACK
#
#  Module:          SLmake.inc
#
#  Purpose:         Top-level Definitions
#
#  Creation date:   February 15, 2000
#
#  Modified:        October 13, 2011
#
#  Send bug reports, comments or suggestions to scalapack@cs.utk.edu
#
############################################################################
#
#  C preprocessor definitions:  set CDEFS to one of the following:
#
#     -DNoChange (fortran subprogram names are lower case without any suffix)
#     -DUpCase   (fortran subprogram names are upper case without any suffix)
#     -DAdd_     (fortran subprogram names are lower case with "_" appended)

CDEFS         = -DAdd_

#
#  The fortran and C compilers, loaders, and their flags
#

FC            = mpif90
CC            = mpicc 
NOOPT         = -O0 
FCFLAGS       = -O3 
CCFLAGS       = -O3 
FCLOADER      = $(FC)
CCLOADER      = $(CC)
FCLOADFLAGS   = $(FCFLAGS)
CCLOADFLAGS   = $(CCFLAGS)

#
#  The archiver and the flag(s) to use when building archive (library)
#  Also the ranlib routine.  If your system has no ranlib, set RANLIB = echo
#

ARCH          = ar
ARCHFLAGS     = cr
RANLIB        = ranlib

#
#  The name of the ScaLAPACK library to be created
#

SCALAPACKLIB  = libscalapack.a

#
#  BLAS, LAPACK (and possibly other) libraries needed for linking test programs
#

BLASLIB       = "-L/Users/ndellin/Research/TPL/TPL_GCC8/OpenBLAS-0.3.9/install/lib -lopenblas"
LAPACKLIB     = "-L/Users/ndellin/Research/TPL/TPL_GCC8/OpenBLAS-0.3.9/install/lib -lopenblas"
LIBS          = $(LAPACKLIB) $(BLASLIB)
```

I'll follow up rebuilding tpls and a clean build of the PR.

**Comment by pghysels** [comment]
For OpenBLAS 0.3.9, I just did "make" in the main openblas directory.
For scalapack, I was using the CMake build. But I don't see any differences.

I checked for the scombssq symbol, and for me it's also defined in both openblas and scalapack:

nm -A libscalapack.a | grep scombssq
libscalapack.a:pstreecomb.f.o:0000000000000500 T scombssq_

nm -A libopenblas.a | grep scombssq
libopenblas.a:scombssq.o:0000000000000000 T scombssq_

**Comment by pghysels** [comment]
Would it be an option to test with netlib BLAS/LAPACK? Or MKL?

**Comment by ndellingwood** [comment]
Thanks @pghysels for the update, I'm stumped on my TPL issues but will approve to get this in the queue for the autotester to kick off

**Review by ndellingwood — APPROVED** [review]

**Pull request merged**
