### PR TITLE
Tpetra bcrs layoutleft

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
@trilinos/tpetra 

## Motivation

To resolve a PR test error, we close the previous #10101 (I like this number though) and reopen the same PR.

## Testing

Tested with Cuda and openmp on kokkos-dev-2.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@e10harvey This is the new PR.

**Comment by ZUUL42** [comment]
We have opened an internal TRILINOSHD-72 ticket for the Cuda merge issue and will report back when we have something.

**Comment by kyungjoo-kim** [comment]
Finally, it passes. Would you take a look at the PR and approve it if you are fine with the changes ?

**Comment by jwillenbring** [comment]
@kyungjoo-kim This passed finally. Is this something that you want to get reviewed and merged for the minor release?

**Comment by kyungjoo-kim** [comment]
@jwillenbring This is a feature addition and there is no urgency here. It does not have to be included in the minor release.

**Review by csiefer2 — APPROVED** [review]

**Pull request merged**
