### PR TITLE
SEACAS: rename grope to explore

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas 

Based on a user-request and approved by management, the 'grope' executable has been 
renamed to 'explore'

In the 'seacas' github change related to this change, there was a symbolic link created at install which would forward 'grope' to 'explore'.  I do not see a way to install symbolic links via TriBits, so that step is not done in the Trilinos change.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [x] These changes break backwards compatibility.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@gsjaardema ,

Will making this change to Trilinos complicate future syncs of SEACAS into Trilinos?  Looking at the git history of the `Trilinos/packages/seacas` directory, it looks like you have been making individual patch fixes to SEACAS in Trilinos.  Have you given up on syncing SEACAS as a whole into Trilinos?

**Comment by gsjaardema** [comment]
@bartlettroscoe This change should not complicate future syncs.  I am in the process of doing some "incremental syncs" since Trilinos has gotten so far out of sync.  Once I get it back under control, I will do more frequent syncs with hopefully fewer changes.

**Comment by bartlettroscoe** [comment]
@gsjaardema said:

> @bartlettroscoe This change should not complicate future syncs. I am in the process of doing some "incremental syncs" since Trilinos has gotten so far out of sync. Once I get it back under control, I will do more frequent syncs with hopefully fewer changes.

Thanks, that sounds good.

On the next big SEACAS sync Trilinos PR (i.e. where you sync all of SEACAS into Trilinos), please add me as a reviewer and I will test the branch on some of the [ATDM Trilinos builds](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos) like some of the CUDA builds to see if there are problems.  Or, we can let it merge and see what happens after the merge to 'develop'.  If something bad happens, we can just back out the merge commit like last time.  No big deal.

**Comment by gsjaardema** [comment]
Yes, permanent name change.

**Comment by mhoemmen** [comment]
Thanks for doing this @gsjaardema :D

**Pull request merged**
