### PR TITLE
New Driver script and intel config file for PR testing

### PR DESCRIPTION
**Pull request by prwolfe**
@trilinos/framework 

## Motivation and Context
Note that this will not yet enable the intel build as
the autotester does not yet have the configuration. It
just provides the files needed.

## Related Issues
* Part of issue #2463

## How Has This Been Tested?
I set up an autotesterinstance pointed at my fork and created a PR from this branch to develop on my fork.  The results can be seen at https://github.com/prwolfe/Trilinos/pull/2 and https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-2-test&field2=buildstarttime&compare2=84&value2=NOW

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
I think there needs to be a different *.cmake file for each specific build in order to allow setting targeted test disables for those builds.  You have to be able to (temporarily) disable a test if needed.  For example, it looks like the Intel 17.0.1 build needs some cleaning up (see https://github.com/trilinos/Trilinos/issues/2463#issuecomment-383946447).  There would be almost no clean ATDM Trilinos builds if we required fixing every test before the build was promoted.

**Comment by prwolfe** [comment]
@bartlettroscoe That is in fact a good part of why I had a second file. And those failures are why I didn't send in a pull request to enable this yet. All of those tests should be easy to clean up except possibly the kokkos one, so I would favor fixing rather than disabling.

**Comment by bartlettroscoe** [comment]
@prwolfe, having a separate file for each build is good.  Duplicating every var is not good.  A system of `*.cmake` fragment files and includes, like demonstrated in the files:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/MpiReleaseDebugSharedPtSerial.cmake
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/MpiReleaseSharedPtSerial.cmake

Those outer files (which are just a few lines long) could be copied to `GCC-4.8.4-PullRequestBuild.cmake` and `Intel-17.0.1-PullRequestBuild.cmake`, respectively, and that should do it.  Then you could add any extra tweaks you needed.

**Comment by prwolfe** [comment]
The variable was an attempt on my part to get the sims modules to load without the error.  Turns out that despite referencing this the intel module then ignores it and hard code 4.8.4 as the default so we alway s get the warning message.  I will get it out of the script and clean up the comments.

**Comment by prwolfe** [comment]
@jwillenbring - I fixed up that environment script.  I will take a look at the failing tests. I don't want to turn this on without those resolved.

**Pull request merged**
