### PR TITLE
Tpetra: matrix apply TPL improvements

### PR DESCRIPTION
**Pull request by brian-kelley**
- Integrate SPMVHandle (for KokkosKernels 4.3+), enabling reuse of matrix analysis
- Rework how int-typed rowptrs are handled. Now works for BlockCrsMatrix too, and rocsparse can be used (not just cusparse)

This adds a new helper struct ``Tpetra::Details::MatrixApplyHelper`` which deals with the rowptrs and SPMVHandles (one for the int-rowptr typed matrix and one for the standard local device matrix). This is temporary - in KokkosKernels 4.4, int will become the default rowptr type so we can get rid of the helper and replace it with a simple SPMVHandle.

@trilinos/tpetra 

## Motivation

- Performance improvements for ``CrsMatrix::apply`` and ``BlockCrsMatrix::apply``.

### CODE REVIEW

**Comment by brian-kelley** [comment]
@csiefer2 I realized that this unholy smart pointer thing was not necessary and shared_ptr is actually what should manage the SPMVHandle and the temporary helper. I think this is reasonably clean now - I could get rid of the helper now too, but everything in it would have to be duplicated between CrsMatrix and BlockCrsMatrix.

I'll take any suggestions though, we'll still be living with this for several months so any obvious issues should be fixed now.

**Comment by jhux2** [comment]
The bottom line is that in order to call rocSparse, the row pointers are expected to be of type `int`, which they're not right now?  What's the performance difference?  It might be good to put numeric results and the high level description into an accompanying issue.

**Comment by jhux2** [comment]
> The answe, I suspect, is less of a difference than one might hope. But we have tests that measure that sort of thing...

Sure.  I'm probably not the only who will ask, so if it's not hard to capture, it's good data to have (for multiple reasons).

**Comment by brian-kelley** [comment]
> The bottom line is that in order to call rocSparse, the row pointers are expected to be of type `int`, which they're not right now? What's the performance difference? It might be good to put numeric results and the high level description into an accompanying issue.

That's correct.

We were already doing this for cuSPARSE CRS, so the only benefit in that case is that we don't have to size/allocate/free the temp buffer every call. This turns out to be only a few% of the cost of spmv.

But for rocSPARSE CRS, we weren't doing it so this PR now lets Tpetra use the TPL instead of the KK native. This does provide a significant speedup for the local apply:

| Time: CRS, MI250 | Before      | After       |
|------------------|-------------|-------------|
| Laplace          | 0.000419695 | 0.000117951 |
| Elasticity       | 0.000691061 | 0.000487767 |
| af_shell         | 0.000296489 | 0.000186852 |
| Hook             | 0.00100534  | 0.000614966 |

For BSR, I tried native vs. cuSPARSE 11.8 on the sparc single_gpu matrix. It turned out to be 1% slower than native (0.640328ms vs 0.64761ms).

I wanted to do a native vs. rocSPARSE BSR comparison too, but rocSPARSE doesn't have a rank-2 bsr spmv yet. It is still possible to add some logic to KokkosKernels to call the rank-1 version if there is only one column, see https://github.com/kokkos/kokkos-kernels/issues/2156.

**Pull request merged**
