### PR TITLE
tpetra: workaround gcc/7.2.0 bug with c++14

### PR DESCRIPTION
**Pull request by ndellingwood**
Add work-around in unit test
tpetra/core/test/CrsMatrix/Equilibration.cpp
to resolve internal compiler errors of type
`internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1705`

@trilinos/tpetra 

## Motivation
Workaround compilation error with cuda/9.2+gcc/7.2 with c++14 support enabled

## Related Issues
This is an internal gcc compiler error that pops up with c++14 support, see for example
https://github.com/kokkos/kokkos-kernels/issues/349

## Testing
Tested with a contributed atdm script I am working (essentially the same as sems-rhel7 env instead of kokkos-dev-2)

```bash
export TRILINOS_DIR=${HOME}/Trilinos
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/kokkos-dev-2
source ~/Trilinos/cmake/std/atdm/load-env.sh kokkos-dev-2-cuda-opt
#source ~/Trilinos/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel7-cuda-opt
 
cmake  \
  -GNinja  \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake  \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Kokkos=ON \
  -DTrilinos_ENABLE_TpetraCore=ON \
  -DCMAKE_CXX_STANDARD=14 \
  $TRILINOS_DIR
```

### CODE REVIEW

**Review by kddevin — APPROVED** [review]
Whoa! This is twisted and sick.  (Assign a const int to a const int and use the new copy.)  
How did you find this solution?  
Is there some pattern we should avoid in the future to avoid this problem?
I don't really like the way the test uses the lambda function -- seems needlessly complicated -- but I'm grateful that you took the time to fix the problem for us, @ndellingwood .  Thank you!

Do you have time to add the PR number #8031 to the workaround comments in the code?  Always nice to have that cross-reference.

**Comment by ndellingwood** [comment]
@kddevin I pushed an update for the comment to include link to this PR.

Here's the bug report for the gcc/7.2 issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882855

Since it's an internal compiler error, I couldn't say this happens consistently enough to prescribe a pattern for avoidance, though I've seen it show up elsewhere in the past and was familiar. Sometimes when a const variable is captured by a lambda and used within a loop this occurs, and the workaround is to create a local copy of the const var in the lambda outside of the loop. It is pretty gross.

**Comment by ndellingwood** [comment]
@kddevin looks like an updated review is required after my push to update the comments, though it looks like the autotester is restarting without the RETEST label.

**Review by kddevin — APPROVED** [review]

**Comment by kddevin** [comment]
Thanks, @ndellingwood !  You saved us a lot of time hunting that down.

**Pull request merged**
