### PR TITLE
Epetra & AztecOO: Fix some warnings

### PR DESCRIPTION
**Pull request by ibaned**
The misleading indentation warning found
a legitimate bug in these print statements.

Not sure who to mention... @alanw0 @sconde ?

### CODE REVIEW

**Comment by ibaned** [comment]
Threw in an Epetra fix because its exactly the same issue being fixed.

@trilinos/epetra

**Comment by maherou** [comment]
@ibaned, Can you say something about tests run and changes observed?  These look like good changes, but want to make sure.  Also, for codes that compare to a reference trusted text output, these changes could be "Results Impacting", so they should be marked with that label.

**Comment by ibaned** [comment]
@maherou thank you for taking a look. Once I'm in the office tomorrow I can run the checkin script without pushing which will give some data about tests run.

**Comment by mhoemmen** [comment]
Some @trilinos/muelu tests may depend on output.  On the other hand, I don't think MueLu uses Epetra's Msr or Vbr.

**Comment by ibaned** [comment]
I just ran the checkin script without pushing, and all tests passed. This includes 17 AztecOO tests and 61 Epetra tests.

Does anyone object to me pushing this?

**Comment by maherou** [comment]
Please do.  Thanks for your efforts.

**Pull request merged**
