### PR TITLE
Switch ATDM SEMS 7.2.0 build to use CMake 3.11.1 and all-at-once approach

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @fryeguy52 

## Description

This small PR switches the ATDM SEMS-based GCC 7.2.0 build to use CMake 3.11.1 and use the all-at-once approach with ctest/cdash.  This should be the last ATDM Trilinos build to be swtiched over to the all-at-once approach.

## Motivation and Context

CMake 3.11.1 is faster at running tests than CMake 3.10.1 and most of the other ATDM Trilinos builds are using CMake 3.11.1.

The all-at-once approach is faster at configure, build, and running tests and displays results better on CDash.

## How Has This Been Tested?

I ran this locally on crf450 using:

```
time env \
>  CTEST_DASHBOARD_ROOT=$PWD \
>  Trilinos_PACKAGES=Kokkos,Teuchos \
>  CTEST_TEST_TYPE=Experimental \
>  CTEST_DO_SUBMIT=OFF \
>  CTEST_DO_UPDATES=OFF \
>  CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=TRUE \
> ~/Trilinos.base/Trilinos/cmake/ctest/drivers/atdm/sems_gcc-7.2.0/drive_linux_mpi_sems_atdm_7.2.0.sh \
> &> console.out

real    4m25.828s
user    29m23.354s
sys     1m57.741s
```

That `console.out` log file showed:

```
...


***
*** Configure, build, test and submit results all-at-once for all enabled packages ...
***
...

100% tests passed, 0 tests failed out of 158

Subproject Time Summary:
Kokkos     =  42.01 sec*proc (23 tests)
Teuchos    = 120.18 sec*proc (135 tests)

Total Test time (real) =  21.99 sec
File '' does NOT exist so all tests passed!
```

and I verified that CMake 3.11.1 was being used in the configure output file under Testing/Temporary/.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

The [above](https://github.com/trilinos/Trilinos/pull/3093#issuecomment-404288831) comment says that the GCC 4.9.3 and GCC 4.8.4 builds failed but there are no build or test results shown on CDash at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-3093-test&field2=buildstarttime&compare2=84&value2=NOW

Can you look at the Jenkins jobs for these two builds and see what happened?  Is there way that we can directly look at the Jenkins driver results to diagnose problems like this ourselves?

**Comment by allevin** [comment]
@bartlettroscoe 
@trilinos/framework 

> The above comment says that the GCC 4.9.3 and GCC 4.8.4 builds failed but there are no build or test results shown on CDash at:

> https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-3093-test&field2=buildstarttime&compare2=84&value2=NOW
Can you look at the Jenkins jobs for these two builds and see what happened? Is there way that we can directly look at the Jenkins driver results to diagnose problems like this ourselves?

The Jenkins clients during Builds 1051 for gcc 4.9.3 & 756 for gcc 4.8.4 both had a Java crash and were unable to report to CDash.   This kind of issue is being discussed with the frameworks team.

**Comment by bartlettroscoe** [comment]
FYI: It took three auto PR build attempts to get a passing set of builds to allow this PR to be merged.   Due to this, we lost the chance to merge this yesterday so that we could see the impact today.  Now we wait an additional day.  (And this is in a case where no builds should be run at all because these changes don't impact any of the auto PR builds.  We need to fix that logic in the PR testing system.)

I just fear that if this occurs to frequently, then we may see people alter their workflows where they try to bypass the 'develop' branch more. But perhaps that will get people to learn git better and learn how to use side branches for collaboration and testing, so perhaps this additional delay is not a bad thing.

**Comment by jwillenbring** [comment]
I am confused. I see the output for 1051 and 756 when I look at the results [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-3093-test&field2=buildstarttime&compare2=84&value2=NOW)

**Comment by bartlettroscoe** [comment]
> I am confused. I see the output for 1051 and 756 when I look at the results here

That is strange.  Those results for the first tree builds were not showing up when I looked at this yesterday.  Does that suggest a lag in the processing of updated *.xml files uploaded to CDash?  How can we diagnose that?

Doubling strange is that the builds `PR-3093-test-Trilinos_pullrequest_gcc_4.8.4-756` and `PR-3093-test-Trilinos_pullrequest_gcc_4.9.3-1051` are now showing build errors that could not possibly have been caused by the changes on this topic branch.  What is the cause of these build errors?

Also strange is why are there no results shown on CDash for the GCC 4.9.3 build num 1055 or the GCC 4.8.4 build num 760 builds for the second auto PR build iteration shown [above](https://github.com/trilinos/Trilinos/pull/3093#issuecomment-404373675) 17 hours ago.  What happened to those builds?  The auto PR tester says those builds failed, yet there is no results for these builds on CDash.  Is this a case where the updated *.xml files are not being processed by CDash or were the *.xml files never submitted?

Is there a way that we can look at the Jenkins jobs and see what is happening with these builds?

**Comment by jwillenbring** [comment]
>Also strange is why are there no results shown on CDash for the GCC 4.9.3 build num 1055 or the GCC 4.8.4 build num 760 builds for the second auto PR build iteration shown above 17 hours ago.

The clone failed for both of these builds. This is a fairly common problem unfortunately.

**Comment by jwillenbring** [comment]
> Does that suggest a lag in the processing of updated *.xml files uploaded to CDash? How can we diagnose that?

It could. I see no immediate evidence of that right now. I logged into CDash and looked under "Monitor / Processing Statistics" and nothing is backed up now. The other statistics shown also do not indicate backups, but at times things may get backed up.

**Comment by jwillenbring** [comment]
> Doubling strange is that the builds PR-3093-test-Trilinos_pullrequest_gcc_4.8.4-756 and PR-3093-test-Trilinos_pullrequest_gcc_4.9.3-1051 are now showing build errors that could not possibly have been caused by the changes on this topic branch. What is the cause of these build errors?

Digging into that, there are some possible signs of odd system issues at that time, and none of the failures look like real failures - 2/3 tests indicate they passed in the output, and the other one shows no sign of failure. The build failures have blank error output. It could be a hiccup at an inopportune time.

**Pull request merged**
