### PR TITLE
Tpetra: Adding Kokkos::fence tracking support to timer injection

### PR DESCRIPTION
**Pull request by csiefer2**
Issue: #12106
Tests:n/a
Stakeholder Feeback: n/a

### CODE REVIEW

**Review by jhux2 — COMMENTED** [review]
What's the difference between a fence and a deep fence?  Is the goal to add fences to prevent timer drift, to time the fences themselves, or both?  Does this depend on #112188, or does #12188 depend on this?

**Review by jhux2 — DISMISSED** [review]
Lgtm.  Squash is also a delicious vegetable.

**Comment by sebrowne** [comment]
This branch requires rebasing given the 'develop' history change.

**Review by sebrowne — DISMISSED** [review]
Please rebase to eliminate extraneous commits.

**Comment by sebrowne** [comment]
If you do that, will it remove https://github.com/trilinos/Trilinos/pull/12223/files#diff-9b65e3d3b275fb61a637c9eb551e8bd17c71c01317c4548484106727e9679502 ?  This PR contains some of the same bad changes that I had to clip out of the develop branch.  The PRs that I noted "I would recommend" may be safe to squash, but the ones I reviewed and requested changes I do think _need_ to be rebased.

I could be wrong, of course.

**Comment by sebrowne** [comment]
@csiefer2 I can do it and send it to my fork if you'd like

**Comment by sebrowne** [comment]
Try this branch: https://github.com/sebrowne/Trilinos/commits/csiefer-3cf8280

I think I have it fixed

**Comment by sebrowne** [comment]
> Now I have to clobber my old version

Do you want me to force push it over your branch?  If the changes look fine in my branch, I think I can just push them over this branch and then all will be well.

**Comment by sebrowne** [comment]
How's that look?

**Comment by sebrowne** [comment]
Sorry for the hassle :(

**Review by jhux2 — APPROVED** [review]
⚡

**Pull request merged**
