### PR TITLE
CMakeLists.txt for Intrelab

### PR DESCRIPTION
**Pull request by kuberry**
@trilinos/intrepid 

## Motivation

Updates the configuration of Intrelab to use the CMake output from Trilinos rather than the Makefile export that is no longer installed with Trilinos.

### CODE REVIEW

**Review by dridzal — CHANGES_REQUESTED** [review]
@kuberry : with the latest revision of CMakeLists.txt I get the build error

```
Building with 'Xcode Clang++'.
clang: error: invalid version number in '-mmacosx-version-min='
```

**Comment by kuberry** [comment]
Interesting. There is no way to override this value anyways (it is hard coded in `mex`), so we don't need to include this flag anyways. I'm curious what the value was that caused this error though for `${CMAKE_OSX_DEPLOYMENT_TARGET}`.

**Review by dridzal — CHANGES_REQUESTED** [review]
This worked for MacOS Catalina with Matlab 2020a.  However, it doesn't work for Linux (Sandia RHEL7 with SEMS modules) and Matlab 2018b.  It can't find lapack and blas.  Here is the full build command with error:

```
/home/dridzal/software/MATLAB/R2018b/bin/mex CXX=/projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/7.3.0/gcc/4.8.5/base/47wbtzd/bin/g++ CXXFLAGS=\ -std=c++11\ -O3\ -DNDEBUG\ -std=c++17 -largeArrayDims -I/ascldap/users/dridzal/development/ROL-Trilinos/build/intrelab/install/include -L/ascldap/users/dridzal/development/ROL-Trilinos/build/intrelab/install/lib -lintrepid -lshards -lsacado -lteuchosremainder -lteuchosnumerics -lteuchoscomm -lteuchosparameterlist -lteuchosparser -lteuchoscore -lshards -lsacado -lteuchosremainder -lteuchosnumerics -lteuchoscomm -lteuchosparameterlist -lteuchosparser -lteuchoscore -lteuchosremainder -lteuchosnumerics -lteuchoscomm -lteuchosparameterlist -lteuchosparser -lteuchoscore -lteuchosremainder -lteuchoscore -lteuchosnumerics -lteuchoscomm -lteuchosparameterlist -lteuchosparser -lteuchoscore -lteuchoscomm -lteuchosparameterlist -lteuchosparser -lteuchoscore -lteuchosparameterlist -lteuchosparser -lteuchoscore -lteuchosparser -lteuchoscore -lteuchoscore -lgtest -l/usr/lib64/liblapack.so -l/usr/lib64/libblas.so -l/usr/lib64/liblapack.so -l/usr/lib64/libblas.so -l/usr/lib64/liblapack.so -l/usr/lib64/libblas.so -l/usr/lib64/liblapack.so -l/usr/lib64/libblas.so /ascldap/users/dridzal/development/ROL-Trilinos/packages/intrepid/matlab/intrelab/build/objs/intrepid_multiplyVectorDataField.o /ascldap/users/dridzal/development/ROL-Trilinos/packages/intrepid/matlab/intrelab/build/objs/m2i_helpers.o
Building with 'gcc'.
/usr/bin/ld: cannot find -l/usr/lib64/liblapack
/usr/bin/ld: cannot find -l/usr/lib64/libblas
/usr/bin/ld: cannot find -l/usr/lib64/liblapack
/usr/bin/ld: cannot find -l/usr/lib64/libblas
/usr/bin/ld: cannot find -l/usr/lib64/liblapack
/usr/bin/ld: cannot find -l/usr/lib64/libblas
/usr/bin/ld: cannot find -l/usr/lib64/liblapack
/usr/bin/ld: cannot find -l/usr/lib64/libblas
collect2: error: ld returned 1 exit status
```
The files /usr/lib64/libblas.so and /usr/lib64/liblapack.so exist.  I've tried manually changing `-l/usr/lib64/liblapack` to just `-llapack`, however then I get the following error:

`/usr/bin/ld: /ascldap/users/dridzal/development/ROL-Trilinos/packages/intrepid/matlab/intrelab/build/objs/intrepid_multiplyVectorDataField.o: relocation R_X86_64_32 against .rodata.str1.1 can not be used when making a shared object; recompile with -fPIC`

I'm not sure I understand this specific issue.  We shouldn't have to recompile with -fPIC.

**Comment by kuberry** [comment]
`-fPIC` is only needed in the call to the MEX compiler, not to Trilinos. I just made a commit that adds the `-fPIC` flag. On mac, everything is a .dylib and is position independent by default, so we never saw this there.

If using shared Trilinos libraries is causing an issue in Matlab, it could be that the `RPATH` doesn't point towards the Trilinos installation. Can you give what I just pushed a try and then let me know?

**Comment by dridzal** [comment]
I'll try the new cmake file with MacOS and Linux.

**Comment by kuberry** [comment]
The most recent commit should clean up RPATH issues on Linux. I haven't tried building intrelab for Trilinos that is built without shared libraries.

**Comment by dridzal** [comment]
Thanks @kuberry !  I'll start working on the documentation for the new build.

**Pull request merged**
