### PR TITLE
Thyra: add support for object extensible InArgs and OutArgs

### PR DESCRIPTION
**Pull request by rppawlo**
Issue #1285

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@rppawlo, I have looked over the code.  In general, the idea and implementation looks very good.  This looks like a nice way to extend a ME InArgs and OutArgs.  With this, hopefully, we can move some of the existing odd-ball stuff currently in the ME InArgs and OutArgs (like taylor time polynomicals and Stokhos stuff) into some of these extended argument sets.

A few issues/comments:

1. I see that some C++11 features are used like `auto`.  Are we allowed to make Thyra require C++11?  What about Xyce?  If not, then we will need to test this with C++11 disabled to make sure it works as well (or we need to typedef this new stuff for C++11 only).

2. There is quite a bit of behavior involved with the supports(), set(), and get() functions.  This is more complex that what is used by existing built-in arguments.  I think this suggests we need to come up with some unit tests for helping to test these use cases.  Either that, or just comment out and/or put in TEST_FOR_EXCEPT(true) calls for now to make sure that people don't call code that is not yet tested.

3. There is no documentation added for this yet.  That is okay for now but we should add that when we clean up the ME interface and documentation.  I started that in the branch https://github.com/trilinos/Trilinos/compare/develop...bartlettroscoe:thyra-me-hessians-795.  I will have to manually merge that branch with the current state of the ME but we can make that a follow-on story of you like so I am okay with no documentation for now.

**Comment by rppawlo** [comment]
@bartlettroscoe Thanks for the review! I don't seem to be getting all the github emails. Didn't see your review until now.

1. I noticed that current thyra tests do use auto, so I started using it. You are correct that thyra does still need to support 98 for xyce. I will remove auto calls from the core library but leave them in unit tests. That is consistent with what is currently there.
2. Can you give some specific use cases? I did put in simple unit testing for the supports(). 
3. I did doxygenate the methods. Do you want a section on the main thyra page for this? Should be easy to add.

**Comment by bartlettroscoe** [comment]
> Can you give some specific use cases? I did put in simple unit testing for the supports().

I did not see any obvious unit test code that would, for example, trigger the exception at:

* https://github.com/trilinos/Trilinos/pull/1307/files#diff-f7839fe2012edbea911df8687ccc73bdR1205

for instance, or execute the code in the line:

* https://github.com/trilinos/Trilinos/pull/1307/files#diff-f7839fe2012edbea911df8687ccc73bdR1238

We can build this code with coverage turned on and submit the results to CDash as described at:

* https://trilinos.org/docs/files/TrilinosBuildReference.html#enabling-support-for-coverage-testing

That is the least labour-intensive way to check to see if things are covered.  The other trick I use is to put in `TEST_FOR_EXCEPT(true)` calls in blocks of code that I suspect are not being tested.  If you put those in and all of the automated tests pass, then you know that code is not covered.

> I did doxygenate the methods. Do you want a section on the main thyra page for this? Should be easy to add.

Yea, I guess in the main Thyra::ModelEvaluator class Doxygen block.  Whatever we can say about what this is and how to use it would be helpful.

The ME (and Thyra in general) needs some targeted tutorials and examples to help demonstrate how to properly use it.

**Comment by rppawlo** [comment]
I ran lcov and manually checked that all new code is now being covered. Removed all uses of auto from the source code but left the use in the tests. This is consistent as other tests are using auto. Also added documentation with example use cases to both inARgs and outArgs objects. Checkin test script passed so all this is pushed. closing ticket.

**Pull request closed without merging**
