### PR TITLE
Tempus: Add Initialize state to Steppers

### PR DESCRIPTION
**Pull request by ccober6**
* Added initialization flag for Steppers to allow indication if
   it has been initialized after construction or setting of member
   data ModelEvaluator, Solver, Initial Conditions, ParameterList,
   etc.  IsInitialized is checked at the beginning of takeStep().
 * Added unit test directory, and tests on Stepper initialization.
 * Added initialization for SolutionHistory.
 * Fixed IMEX Steppers for General IMEX RK schemes.  Construction
   without a ParameterList failed.

All passses all on a Mac in both opt and debug.

@trilinos/tempus 

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

**Comment by ccober6** [comment]
Hi Roger, did you get a chance to look at this?  Thanks, Curt

**Comment by rppawlo** [comment]
@ccober6 - did you test this against empire? I'm seeing initialization failures. We might want to revert if we can't fix it fast.

**Comment by ccober6** [comment]
No I did not get a chance to.  Revert in EMPIRE-Trilinos or Trilinos-Trilinos?

**Comment by rppawlo** [comment]
Was thinking of trilinos-trilinos. It won't make it into empire-trilinos. We've been trying to resurrect the trilinos updates into empire-trilinos. It has been broken for over a week. We got it clean this morning, but this tempus commit will now block the update tonight. The failure is claiming that initialize has not been called. Might be an easy fix.

**Comment by ccober6** [comment]
Yeah, it might be.  I do not want to hold things, so you might want to revert.  When I tried to build EMPIRE last week, it of course completely failed many tests.  I will try again.

**Comment by ccober6** [comment]
Roger go ahead and revert.  I think I have reproduced the error, but have not tracked it down and I need to leave for the day.  I will pick it up again tonight or tomorrow.

**Comment by ccober6** [comment]
So it appears that after the initialize() calls in EMPIRE, some set functions are called.  Placing another initialize() after those set functions (TimeStepEM.hpp:56) got past not being initialized, but ...

The solver was "Replace the stepper's nonlinear solver" (em_solvers/TimeStepBase.hpp:155) also after the initialize(), and it appears that the initialize() undoes this because I get 

`Throw test that evaluated to true: !(nonnull(lows_factory_))`

from Trilinos/packages/nox/src-thyra/NOX_Thyra_Group.C:121.

We should revert this commit, while I track this down.  I have not reverted in Trilinos before.  Can you do it, or tell me what needs to happen? Thanks, Curt.

**Comment by ccober6** [comment]
Pinging @rppawlo to make sure he sees this...  Look at previous message.

**Comment by ccober6** [comment]
@rppawlo  OK, I switched around the set functions and the initialize and EMPIRE is passing...  onto EMPIRE-PIC and EMPIRE-Fluid.

**Comment by ccober6** [comment]
EMPIRE-PIC is fixed, but EMPIRE-Fluid fails on a null pointer?!  @rppawlo is it OK for the following objects to be null in NOX?

      User Defined Scaling = Teuchos::RCP<Thyra::VectorBase<double> >{ptr=0,node=0,strong_count=0,weak_count=0}   [default]

      Observer = Teuchos::RCP<NOX::Observer>{ptr=0,node=0,strong_count=0,weak_count=0}   [default]

      User Defined Pre/Post Operator = Teuchos::RCP<NOX::Observer>{ptr=0,node=0,strong_count=0,weak_count=0}   [default]

      User Defined Merit Function = Teuchos::RCP<NOX::MeritFunction::Generic>{ptr=0,node=0,strong_count=0,weak_count=0}   [default]

**Comment by ccober6** [comment]
@rppawlo  FYI the null pointer is failing in NOX.

**Comment by rppawlo** [comment]
@ccober6 - need some more information. How is it failing? seg fault? exception? Can you post the output? WRT the null objects, normally it is fine for those to be null when constructing the group. Where is the nox object being constructed? Is this in tempus? There was a recent change to the group to add an extra optional parameter for dynamic right scaling but all tempus tests were passing. Can you point me to the branch with your changes for the empire repos so I can reproduce?

**Comment by ccober6** [comment]
Here is the full output from the failing test I am looking at

```
cee-build013: ~/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/tests/regression/plasma 
[564]-> bash OWave_1fluid_tempus_IMEX_CG-MPI2.sh 
Running input file '/ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/tests/regression/plasma/OWave_1fluid_tempus_IMEX_CG-MPI2-0.yaml'
p=0 | CubeHexMesh: Building sub cells
 Warning -- Constructing Backward Euler without ModelEvaluator!
   - Can reset ParameterList with setParameterList().
   - Requires subsequent setModel() and initialize() calls
     before calling takeStep().
 
 Warning -- Constructing Backward Euler without ModelEvaluator!
   - Can reset ParameterList with setParameterList().
   - Requires subsequent setModel() and initialize() calls
     before calling takeStep().
 

Tempus - IntegratorBasic
Wed Jul 31 05:02:26 2019

  Stepper = IMEX RK SSP2
  Simulation Time Range  [0, 1.00138e-09]
  Simulation Index Range [0, 40]
============================================================================
  Step       Time         dt  Abs Error  Rel Error  Order  nFail  dCompTime

************************************************************************

-- Parameters Passed to Nonlinear Solver --

     Nonlinear Solver = Line Search Based   [default]
     Printing -> 
      MyPID = 0   [default]
      Output Processor = 0   [default]
      Output Precision = 3   [default]
      Output Information -> 
       Linear Solver Details = 1
       Parameters = 1
       Details = 1
       Outer Iteration = 1
       Debug = 0   [default]
       Error = 0   [default]
       Inner Iteration = 0   [default]
       Outer Iteration StatusTest = 0   [default]
       Stepper Details = 0   [default]
       Stepper Iteration = 0   [default]
       Stepper Parameters = 0   [default]
       Test Details = 0   [default]
       Warning = 0   [default]
     Status Tests -> 
      Test Type = Combo
      Combo Type = OR
      Number of Tests = 2
      Test 0 -> 
       Test Type = Combo
       Combo Type = AND
       Number of Tests = 2
       Test 0 -> 
        Test Type = RelativeNormF
        Tolerance = 1e-06
        Scale Norms by Length = 0   [default]
       Test 1 -> 
        Test Type = NormWRMS
        Tolerance = 1
        Relative Tolerance = 0.001
        Absolute Tolerance = 1e-06
        BDF Multiplier = 1   [default]
        Alpha = 1   [default]
        Beta = 0.5   [default]
        Disable Implicit Weighting = 1   [default]
      Test 1 -> 
       Test Type = NStep
       Number of Nonlinear Iterations = 10
       Number of Initial Ramping Steps = 0   [default]
       Number of Nonlinear Iterations in Ramping Phase = 10   [default]
     Thyra Group Options -> 
      Function Scaling = None   [default]
      Update Row Sum Scaling = Before Each Nonlinear Solve   [default]
      User Defined Scaling = Teuchos::RCP<Thyra::VectorBase<double> >{ptr=0,node=0,strong_count=0,weak_count=0}   [default]
      Do Right Scaling First = 0   [default]
     Solver Options -> 
      Status Test Check Type = Minimal   [default]
      Observer = Teuchos::RCP<NOX::Observer>{ptr=0,node=0,strong_count=0,weak_count=0}   [default]
      User Defined Pre/Post Operator = Teuchos::RCP<NOX::Observer>{ptr=0,node=0,strong_count=0,weak_count=0}   [default]
      User Defined Merit Function = Teuchos::RCP<NOX::MeritFunction::Generic>{ptr=0,node=0,strong_count=0,weak_count=0}   [default]
      Fixed Point Iteration Type = Seidel   [default]
     Line Search -> 
      Method = Full Step   [default]
      Full Step -> 
       Full Step = 1   [default]
     Direction -> 
      Method = Newton   [default]
      Newton -> 
       Rescue Bad Newton Solve = 1   [default]
       Forcing Term Method = Constant   [default]
       Linear Solver -> 
        Tolerance = 1e-10   [default]

************************************************************************
-- Nonlinear Solver Step 0 -- 
||F|| = 1.823e+01  step = 0.000e+00  dx = 0.000e+00
************************************************************************

       CALCULATING FORCING TERM
       Method: Constant
       Forcing Term: 1e-10
[cee-build013:74445] *** Process received signal ***
[cee-build013:74446] *** Process received signal ***
[cee-build013:74446] Signal: Segmentation fault (11)
[cee-build013:74446] Signal code: Address not mapped (1)
[cee-build013:74446] Failing at address: 0x38
[cee-build013:74445] Signal: Segmentation fault (11)
[cee-build013:74445] Signal code: Address not mapped (1)
[cee-build013:74445] Failing at address: 0x38
[cee-build013:74445] [ 0] [cee-build013:74446] [ 0] /lib64/libpthread.so.0[0x336920f7e0]
[cee-build013:74445] [ 1] /lib64/libpthread.so.0[0x336920f7e0]
[cee-build013:74446] [ 1] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0xe66c8b]
[cee-build013:74445] [ 2] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0xe66c8b]
[cee-build013:74446] [ 2] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1dcbf58]
[cee-build013:74446] [ 3] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1dcbf58]
[cee-build013:74445] [ 3] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1dcc4b3]
[cee-build013:74446] [ 4] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1dcc4b3]
[cee-build013:74445] [ 4] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1dcd7a6]
[cee-build013:74446] [ 5] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1dcd7a6]
[cee-build013:74445] [ 5] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1e44568]
[cee-build013:74445] [ 6] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1e44568]
[cee-build013:74446] [ 6] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1de7597]
[cee-build013:74446] [ 7] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1de7597]
[cee-build013:74445] [ 7] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1de8871]
[cee-build013:74445] [ 8] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1de8871]
[cee-build013:74446] [ 8] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1dd3fb2]
[cee-build013:74445] [ 9] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1dd3fb2]
[cee-build013:74446] [ 9] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1840beb]
[cee-build013:74445] [10] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x1840beb]
[cee-build013:74446] [10] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x182ceac]
[cee-build013:74445] [11] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x182ceac]
[cee-build013:74446] [11] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x17cf19c]
[cee-build013:74445] [12] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x17cf19c]
[cee-build013:74446] [12] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0xb42106]
[cee-build013:74445] [13] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x4ab05f]
[cee-build013:74445] [14] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0xb42106]
[cee-build013:74446] [13] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x4d4252]
[cee-build013:74445] [15] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x4ab05f]
[cee-build013:74446] [14] /lib64/libc.so.6(__libc_start_main+0xfd)[0x3368a1ed1d]
[cee-build013:74445] [16] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x4d4252]
[cee-build013:74446] [15] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x4a7fd9]
[cee-build013:74445] *** End of error message ***
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3368a1ed1d]
[cee-build013:74446] [16] /ascldap/users/ccober/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/src/empire-fluid.exe[0x4a7fd9]
[cee-build013:74446] *** End of error message ***
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 74445 on node cee-build013 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
Failed to run step 0
 
cee-build013: ~/Empire_Workspace/EMPIRE-build-GNU-7.2.0-RELEASE-SERIAL/EMPIRE-Fluid/tests/regression/plasma 
[565]->
```

**Comment by ccober6** [comment]
I am working on creating the branches let you know as soon as I get them setup.

**Pull request merged**
