### PR TITLE
Tempus output to root only

### PR DESCRIPTION
**Pull request by sconde**
@trilinos/tempus 

## Motivation

When in parallel, the warnings are printed by each rank. On small number processor count, this is not an issue. However, on large number of processor counts, this fills up the log file ( space issue ) and burdens the user.

So to fix it, define the output stream to be a Teuchos fanceOSstream and set output to root only to true.

### CODE REVIEW

**Comment by sconde** [comment]
@crockatt This PR should help with warnings filling up the log file

**Comment by ccober6** [comment]
@sconde I do not think we use processor dependent output anywhere in Tempus, so I would add this to all the usages of FancyOStream (I came up with ~56 files that should be checked).  Can you make sure we are using setOutputToRootOnly(0) everywhere we can?  Thanks, Curt

**Comment by sconde** [comment]
I think I've caught all of the `FancyOStream` instances

**Comment by ccober6** [comment]
@sconde Should we worry about the uses of FancyOStream that are past in?  The tough one here is the application may pass a FancyOStream, and then Tempus changes it?  In talking with Roger about it, there is probably not an unset setOutputToRootOnly.  So if we are worried about this, we probably need to make a local copy and then set setOutputToRootOnly.  Thoughts?

**Comment by sconde** [comment]
I think that's a valid point. I will explore it

**Comment by ccober6** [comment]
@sconde Actually Roger suggested grabbing the stream from the incoming FancyOStream, and construct a local FancyOStream from that and set setOutputToRootOnly on it.

**Comment by sconde** [comment]
yes, that is what I'm looking at now.

**Review by ccober6 — APPROVED** [review]
Looks good!

**Pull request merged**
