### PR TITLE
Belos: Have OrthoManager inherit from Teuchos::ParameterListAcceptorDefaultBase

### PR DESCRIPTION
**Pull request by jennloe**
This PR makes the Belos::OrthoManager class inherit from Teuchos::ParameterListAcceptorDefaultBase instead of each of the OrthoManager subclasses inheriting from it individually.  This step will allow the Belos solvers to set parameters in any instance of OrthoManager.  

@trilinos/belos 

## Testing
Expanded Epetra OthoManager test to use the get and set functions.

### CODE REVIEW

**Comment by jhux2** [comment]
@jennloe Is this intended to address #965?  Just curious.

**Comment by jennloe** [comment]
@jhux2 Yes, this is one of the first steps in that direction.  Several more pieces to go before it will all be working.

**Comment by etphipp** [comment]
Is @trilinos/framework aware of the ride issues?  It looks like the tests were moved to the pascal nodes, but the build configuration wasn't changed to use the appropriate Kokkos-Cuda arch flag for pascal instead of kepler.

**Comment by jhux2** [comment]
> Is @trilinos/framework aware of the ride issues? It looks like the tests were moved to the pascal nodes, but the build configuration wasn't changed to use the appropriate Kokkos-Cuda arch flag for pascal instead of kepler.

Yes, see #7498.

**Pull request merged**
