### PR TITLE
Xpetra: Make deprecation warnings optional

### LINKED ISSUE #13250: Xpetra: Turn off warnings for deprecated code
## Question
@trilinos/xpetra @mayrmt 

Currently one can set the following flag `Trilinos_SHOW_DEPRECATED_WARNINGS=OFF` to avoid all the warnings related to the deprecation of `Epetra`. In addition one can set the flag `Xpetra_ENABLE_DEPRECATED_CODE=ON` to enable the `Epetra` backend of `Xpetra`, which again results in deprecation warnings, which are not caught by `Trilinos_SHOW_DEPRECATED_WARNINGS`.

Would it be possible to also supress these warnings (Epetra related in Xpetra) with `Trilinos_SHOW_DEPRECATED_WARNINGS`?

### PR DESCRIPTION
**Pull request by sebrowne**
@trilinos/xpetra 

## Motivation
Want to be able to hide deprecated warnings in the same manner as other packages/warning types.

## Related Issues
Closes #13250 

## Testing
I tested with `Trilinos_SHOW_DEPRECATED_WARNINGS` (and `Xpetra_SHOW_DEPRECATED_WARNINGS`) on and off, behavior was as expected based on the name.

### CODE REVIEW

**Review by mayrmt — APPROVED** [review]

**Comment by mayrmt** [comment]
@sebrowne Thanks for providing this fix!

**Comment by maxfirmbach** [comment]
@sebrowne Thanks for looking into it! :smiley:

**Comment by jhux2** [comment]
> @csiefer2 (no xpetra team)

There is an @trilinos/xpetra team (or is that not what you meant?)

**Comment by sebrowne** [comment]
> > @csiefer2 (no xpetra team)
> 
> There is an @trilinos/xpetra team (or is that not what you meant?)

It was, I updated it.  Would you believe me if I said I tried it before and it didn't show that team so I thought the team didn't exist?

**Review by cgcgcg — APPROVED** [review]

**Pull request merged**
