### PR TITLE
Tempus: Remove All StepperObservers

### LINKED ISSUE #8216: Tempus:  Remove All Stepper::Observer
## Enhancement
@trilinos/tempus 

Remove all Stepper::Observer and get depreciated.

### PR DESCRIPTION
**Pull request by ccober6**
Removed all objects and references to StepperObserver, which
has been replaced with AppActions.  This removes most of the
outstanding TEMPUS_HIDE_DEPRECATED_CODE.

Miscellaneous
 * Removed tabs.

@trilinos/tempus 

## Motivation
Remove legacy and duplicate means to add application specific code to Steppers.

* Closes #8216 

## Testing
All tests still pass.

### CODE REVIEW

**Comment by ccober6** [comment]
@sconde Do not merge yet, as I am testing against EMPIRE.  After which I will get everyone (Irina, Mike and you) to do the testing on the other apps.

**Comment by ccober6** [comment]
@sconde @ikalash @michael-a-hansen  Ok, after an easy mod for Piro, and testing on EMPIRE (which needed some mods), this branch is passing Trilinos tests and EMPIRE tests.  Can you check it against Albany, SPARC and Drekar? Thanks!

**Review by sconde — APPROVED** [review]
Good on my end. Thank you for doing this :)

**Comment by ikalash** [comment]
I will test Albany with this PR later today and report back if everything is OK or not.

**Comment by ikalash** [comment]
I've run Albany with this branch and all tests are clean.

**Comment by michael-a-hansen** [comment]
@ccober6 Looks good from the SPARC side 👍

**Comment by ccober6** [comment]
@sconde @ikalash @michael-a-hansen  Thanks everyone for looking this over!

**Pull request merged**
