### PR TITLE
MueLu: Correct uses of MUELU_HAVE_* macros

### LINKED ISSUE #11843: MueLu: MUELU_HAVE_* preprocessor defines are incorrect
@trilinos/muelu 

As pointed out by @jhux2 in https://github.com/trilinos/Trilinos/pull/11777#issuecomment-1532166976, we check quite a few preprocessor defines of the form `MUELU_HAVE_*` which do not exist.
```
$ cd packages/muelu
$ grep -rn MUELU_HAVE
src/Graph/Containers/MueLu_Zoltan2GraphAdapter.hpp:457:#endif// MUELU_HAVE_ZOLTAN2
test/unit_tests/GenericRFactory.cpp:92:#   if !defined(MUELU_HAVE_IFPACK)
test/unit_tests/GenericRFactory.cpp:95:#   if !defined(MUELU_HAVE_IFPACK2)
test/unit_tests/GenericRFactory.cpp:227:#   if !defined(MUELU_HAVE_IFPACK)
test/unit_tests/GenericRFactory.cpp:230:#   if !defined(MUELU_HAVE_IFPACK2)
test/unit_tests/TentativePFactory.cpp:541:#   if !defined(MUELU_HAVE_IFPACK)
test/unit_tests/TentativePFactory.cpp:544:#   if !defined(MUELU_HAVE_IFPACK2)
test/unit_tests/Repartition.cpp:909:#   if !defined(MUELU_HAVE_AMESOS) || !defined(MUELU_HAVE_IFPACK)
test/unit_tests/Repartition.cpp:912:#   if !defined(MUELU_HAVE_AMESOS2) || !defined(MUELU_HAVE_IFPACK2)
test/unit_tests/Repartition.cpp:1022:#   if !defined(MUELU_HAVE_AMESOS) || !defined(MUELU_HAVE_IFPACK)
test/unit_tests/Repartition.cpp:1025:#   if !defined(MUELU_HAVE_AMESOS2) || !defined(MUELU_HAVE_IFPACK2)
```
Those are typos and anything of the form `MUELU_HAVE_*` is never true, so we should fix them.

### PR DESCRIPTION
**Pull request by GrahamBenHarper**
@trilinos/muelu 

`MUELU_HAVE_*` is not correct, but `HAVE_MUELU_*` is correct :)

Closes #11843.

### CODE REVIEW

**Review by cgcgcg — APPROVED** [review]

**Review by mayrmt — DISMISSED** [review]

**Comment by GrahamBenHarper** [comment]
Ironic. I didn't run the tests since I was removing preprocessor defines, but it looks like maybe `GenericRFactory` has been broken since it was never tested (the use of wrong macros caused it to always skip testing).
```
The following tests FAILED:
    334. GenericRFactory_double_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_SymmetricProblem_UnitTest ... 
    337. GenericRFactory_double_int_longlong_Tpetra_KokkosCompat_KokkosSerialWrapperNode_SymmetricProblem_UnitTest ... 
    340. GenericRFactory_std_complex0double0_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_SymmetricProblem_UnitTest ... 
    343. GenericRFactory_std_complex0double0_int_longlong_Tpetra_KokkosCompat_KokkosSerialWrapperNode_SymmetricProblem_UnitTest ... 
```
I'll dig into it later

**Comment by GrahamBenHarper** [comment]
There we go. I don't think the `GenericRFactory` SymmetricProblem test has been run since circa 2015, but it just needed to compute global constants. It should pass testing now.

**Review by jhux2 — DISMISSED** [review]
lgtm.  Thanks @GrahamBenHarper!

**Comment by GrahamBenHarper** [comment]
Originally I tried something like
```
    Teuchos::ParameterList paramList;
    paramList.sublist("matrixmatrix: kernel params").set("compute global constants",true);
    Pfact->SetParameterList(paramList);
```
and I thought it worked, but I was making changes on a different branch and my open editor cached the `MUELU_HAVE_IFPACK2` when I changed branches, which made it look like it worked when it didn't. I didn't want to fight with parameterlists too much, so I just manually called `computeGlobalConstants()` on P1 and P2.

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by GrahamBenHarper** [comment]
I haven't had a chance to fully revisit this, but here's a summary.

There are cuda-exclusive failures related to the re-enabled tests since they haven't been run in a long time, meaning there probably needs to be slightly more fixing than just correcting the associated `MUELU_HAVE_*` macros.
```
The following tests FAILED:
    334. GenericRFactory_double_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_SymmetricProblem_UnitTest ... 
    340. GenericRFactory_std_complex0double0_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_SymmetricProblem_UnitTest ... 
    691. Repartition_double_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_NodePartition_UnitTest ... 

Total Time: 66.3 sec

Summary: total = 968, run = 968, passed = 965, failed = 3

End Result: TEST FAILED
```

It seems the only test for the `NodeComm` feature never ran because of this, and it's unclear why this only happens in a cuda build
```
 p=0: *** Caught standard std::exception of type 'MueLu::Exceptions::RuntimeError' :
 
  ../Trilinos/packages/muelu/src/MueCentral/MueLu_Level.hpp:196:
  
  Throw number = 523
  
  Throw test that evaluated to true: !IsKey(fac, ename)
  
  "Aggregates" generated by factory "MueLu::UncoupledAggregationFactory_kokkos" not found on level 0.
 [FAILED]  (3 sec) Repartition_double_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_NodePartition_UnitTest
 Location: ../Trilinos/packages/muelu/test/unit_tests/Repartition.cpp:1016
```

The failures in `GenericRFactory` still remain unclear because they both report something like this
```
 Setup loop: startLevel = 0, lastLevel = 2 (stop if numLevels = 3 or Ac.size() < 1)
 Using default factory (RAPFactory[1821]) for building 'A'.
 Using default factory (TentativePFactory_kokkos[1822]) for building 'Ptent'.
 Using default factory (CoalesceDropFactory_kokkos[1823]) for building 'Graph'.
 Using default factory (AmalgamationFactory[1824]) for building 'UnAmalgamationInfo'.
 Using default factory (CoarseMapFactory[1825]) for building 'CoarseMap'.
 
 Level 0
 Setup Smoother (MueLu::Ifpack2Smoother{type = RELAXATION})
 "Ifpack2::Relaxation": {Initialized: true, Computed: true, Type: Symmetric Gauss-Seidel, sweeps: 1, damping factor: 1, Global matrix dimensions: [63, 63], Global nnz: 187}
 Using default factory (NullspaceFactory_kokkos[1833]) for building 'Nullspace'.
 
 Level 1
 Prolongator smoothing (MueLu::SaPFactory)
 Build (MueLu::TentativePFactory_kokkos)
 Build (MueLu::UncoupledAggregationFactory)
 Build (MueLu::CoalesceDropFactory_kokkos)
 Build (MueLu::AmalgamationFactory)
 
 ******* WARNING *******
 AmalagamationFactory::Build(): no striding information available. Use blockdim=1 with offset=0
 algorithm = "classical": threshold = 0, blocksize = 1
 Detected 0 Dirichlet nodes
 Level::Set: Not storing "A" generated by factory CoalesceDropFactory_kokkos[1823] on level 0, as it has not been requested and no keep flags were set for it
 
 p=0: *** Caught standard std::exception of type 'Teuchos::bad_any_cast' :
 
  ../Trilinos/packages/muelu/src/MueCentral/MueLu_VariableContainer.hpp:101:
  
  Throw number = 161
  
  Throw test that evaluated to true: data_->type() != typeid(T)
  
  Error, cast to type Data<Teuchos::RCP<MueLu::GraphBase<int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> > >> failed since the actual underlying type is 'Teuchos::RCP<MueLu::LWGraph_kokkos<int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Cuda, Kokkos::CudaSpace> > >!
 [FAILED]  (0.0209 sec) GenericRFactory_double_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_SymmetricProblem_UnitTest
 Location: ../Trilinos/packages/muelu/test/unit_tests/GenericRFactory.cpp:88
```

**Pull request closed without merging**
