### PR TITLE
support for builds using SCOREC core-sim

### PR DESCRIPTION
**Pull request by cwsmith**
The packages that wrap the Simmetrix API are added to the package and TPL list to support builds against SCOREC/core-sim .

### CODE REVIEW

**Comment by jwillenbring** [comment]
Ross, were you going to merge this? I can, but then I wouldn't plan to test the SCOREC build, as I don't have experience with that and presumably that was already tested.

**Comment by bartlettroscoe** [comment]
This is really strange but I don't remember ever seeing this PR before.  I don't remember changing the title.

Is there someone on the Trilinos development team who has Trilinos push access who has some involvement with SCOREC?  If so, that is the right person to review, test, and push this.  Is there any automated testing against SCOREC?  If not, if it gets broken, who would know?

**Comment by ibaned** [comment]
Trilinos + SCOREC builds are typically to support the Albany application. There is nightly testing for that combination of software, although this PR in particular enables a more rare type of build not tested nightly.

**Comment by bartlettroscoe** [comment]
I reviewed the changes and they look to be very minor and safe.   Basically, two new ST TriBITS TPLs "SimMesh" and "SimModel" were added and two new ST TriBITS packages "SCORECgmi_sim" and "SCORECapf_sim" were added.  If this passes the push with the checkin script for the PT default builds, then it should not break anything.  But someone who has the TPLs "SimMesh" and "SimModel" installed on their machine should test the build and tests with these TPLs enabled.  If this has already been done, then just document that test here and then someone can push.

If anyone needs help setting up the checkin-test.py script for usage on their machine, let me know. We can pair program this using Skype for Business.

**Comment by cwsmith** [comment]
The modified trilinos compiles, links with ghansen/Albany, and succesfully runs a test case of ours (J2 plasticity with creep).  My Trilinos build notes are here:
https://github.com/cwsmith/Trilinos/wiki/Building-with-SCOREC-core-sim

**Comment by bartlettroscoe** [comment]
Cameron (@cwsmith), are you set up to run the checkin-test.py script on your machine?  Do you have push access to the main Trilinos git repo?  If you have push access but are not set up to run the checkin-test.py script, then let's get you set up so that you can push this change yourself.  If you don't have push access, then I will do it later today.

**Comment by cwsmith** [comment]
@bartlettroscoe I do not have checkin-test.py setup or push access to the main repo.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I do not have checkin-test.py setup or push access to the main repo.

Okay, I will push the change later today.  But in the future, a Trilinos developer who is working or supporting Albany should really review these types of pull requests and do the merging an pushing.

@agsalin and @gahansen , who is the right Trilinos developer with a connection to Albany who can review and push PRs of this nature?  I think that would make the most sense.

**Comment by bartlettroscoe** [comment]
I rebased and pushed this branch.  See the commits:

```
a72132b "order matters?"
Author: Cameron Smith <smithc11@rpi.edu>
Date:   Tue Mar 29 13:41:33 2016 -0400 (5 hours ago)

M       PackagesList.cmake

de90b4e "add the simmetrix interface libs and tpls"
Author: Cameron Smith <smithc11@rpi.edu>
Date:   Tue Mar 29 13:31:05 2016 -0400 (5 hours ago)

M       PackagesList.cmake
M       TPLsList.cmake
```

Cameron, you can close this PR if you want or can wait for the Albany developers to sign off.  I will assign this to Andy to decide.

**Pull request closed without merging**
