### PR TITLE
EpetraExt: Support HDF5 1.10 with Example added to Trilinos

### PR DESCRIPTION
**Pull request by MicheldeMessieres**
This appends to the original PR #1062.
It was decided we should build the HDF5_IO.cpp in as an example so this code will be tested with routine testing. It was also decided not to do all of them right now. I will open an issue for the others.

### CODE REVIEW

**Comment by krcb** [comment]
@jwillenbring Is there someone who could review and push as appropriate?

**Comment by bavier** [comment]
What needs to be done yet for this to be merged?

**Comment by jwillenbring** [comment]
@MicheldeMessieres Let’s discuss this Tuesday.

**Comment by MicheldeMessieres** [comment]
This was tested with hdf5 1.8.13 and 1.10.0.

**Comment by mhoemmen** [comment]
Thanks all!

**Comment by mhoemmen** [comment]
@rrdrake @prwolfe @micahahoward

**Comment by bavier** [comment]
Indeed, thank you everyone for getting this through. :)

**Comment by mhoemmen** [comment]
@bavier Thanks! :D

**Comment by MicheldeMessieres** [comment]
Just accidentally discovered the example I added wasn't guarded for HDF5 off - so EpetraExt examples on with no HDF5 leads to a compile error. I'll open a PR to fix shortly.

**Comment by mhoemmen** [comment]
@MicheldeMessieres I just merged your latest PR -- thanks for fixing!

**Pull request merged**
