### PR TITLE
Tpetra: Potential fix for #12574

### PR DESCRIPTION
**Pull request by csiefer2**
Issue: #12574 
Stakeholder feedback: Pending
Tests: n/a

Let's see what the AT has to say

@jewatkins @mperego Assuming this passes the AT, could one of you check to see if this fixes Albany

### CODE REVIEW

**Comment by mperego** [comment]
@mcarlson801, do you have time to test this with Albany?

**Comment by mcarlson801** [comment]
Yeah, I'll give it a shot later today.

**Comment by mcarlson801** [comment]
I built this branch and Albany on Weaver with no issue. All tests are passing except for `demoPDEs_Advection1D_with_Source_Dist_Param_Adjoint_Sens_Explicit_ConsistentM` and `demoPDEs_Thermal1D_with_Source_Dist_Param_Adjoint_Sens_Explicit` but that is expected and unrelated to this issue. Looks good on our end.

**Review by jhux2 — APPROVED** [review]
lgtm

**Pull request merged**
