### PR TITLE
Intrepid2: Fix compiling with SYCL

### PR DESCRIPTION
**Pull request by masterleinad**
@trilinos/intrepid2
## Motivation
This should fix compiling with `SYCL` using `Intrepid2`.

## Related Issues
* Related to #12428

### CODE REVIEW

**Review by mperego — APPROVED** [review]
Looks good to me. Thanks!

**Comment by masterleinad** [comment]
Can someone set the `AT: PRE-TEST INSPECTED` label?

**Comment by masterleinad** [comment]
What was the failure in the CI here?

**Comment by ndellingwood** [comment]
@masterleinad CI failure unrelated to your PR, due to system running out of memory during compilation, likely related to #12571 

For reference, this occurs in a couple locations:
```
icpc: error #10106: Fatal error...
```

**Comment by masterleinad** [comment]
@mperego Can we merge this?

**Pull request merged**
