### PR TITLE
MueLu: fix dashboard failures

### PR DESCRIPTION
**Pull request by jhux2**
Auto-PR for SHA 3b57c07

---
This change is [Reviewable](https://reviewable.io/reviews/trilinos/trilinos/3527)

### CODE REVIEW

**Comment by jhux2** [comment]
@trilinos/framework Can someone please explain why this failed?  When I check the dashboard, it's green.

**Comment by prwolfe** [comment]
Note that the dashboard contains only two builds of the expected three.  Looking in the autotester notes above for the missing intel17 build I see 

fatal: unable to access 'https://github.com/trilinos/Trilinos/': Proxy CONNECT aborted
Source remote fetch failed. The error code was: 128
./Trilinos/cmake/std/PullRequestLinuxDriver.sh: line 107: i: command not found


Which is a failure in one of our scripts as well as a failure to fetch from GitHub.

Hope that helps!

**Comment by jhux2** [comment]
> Note that the dashboard contains only two builds of the expected three. Looking in the autotester notes above for the missing intel17 build I see
> 
> fatal: unable to access 'https://github.com/trilinos/Trilinos/': Proxy CONNECT aborted
> Source remote fetch failed. The error code was: 128
> ./Trilinos/cmake/std/PullRequestLinuxDriver.sh: line 107: i: command not found
> 
> Which is a failure in one of our scripts as well as a failure to fetch from GitHub.
> 
> Hope that helps!

@prwolfe Thanks for the explanation.  Is this a bug in the script?   Shouldn't the line in that script read
```
if $i != num_retries
```

**Comment by jhux2** [comment]
Actually,
```
   if $i != $num_retries
```
?

**Comment by prwolfe** [comment]
Yes, yes it should.

**Comment by prwolfe** [comment]
@jhux2 - Note that hitting this bug is infrequent. If you want to add at:retest and have another go at it your odds are good.  My PR will be in soon if you want to leave this however.

**Pull request merged**
