### PR TITLE
Fix running of tests on 'serrano' for ATDM Trilinos builds

### PR DESCRIPTION
**Pull request by bartlettroscoe**
**CC:** @fryeguy52 

## Description

This appears to mostly fix the problems with running tests on 'serrano' as reported in #2699.  I changed the arguments passed to `mpiexec` and I changed from `srun` to `salloc`.   I basically followed the guidelines at:

* https://computing.sandia.gov/platforms/cts1/submitting_jobs

exactly as stated.

## How Has This Been Tested?

I ran the Jenkins driver locally for Panzer and it produced:

```
100% tests passed, 0 tests failed out of 156

Label Time Summary:
Panzer    = 1257.04 sec*proc (156 tests)

Total Test time (real) = 162.90 sec

Panzer: File '' does NOT exist so all tests passed!

Panzer: Skipping running memory checking tests due to CTEST_DO_MEMORY_TESTING='FALSE'!

Done with the incremental building and testing of Trilinos packages!

TRIBITS_CTEST_DRIVER_ERROR_QUEUE is empty. All is well.

See results for:
  Site: serrano
  Build Name: Trilinos-atdm-toss3-intel-opt-openmp-panzer
at:
  http://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project

TRIBITS_CTEST_DRIVER: OVERALL: ALL PASSSED
```

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@trilinos/framework team,

This PR passed the auto PR builds and @fryeguy52 just approved it.  However, it is not letting me merge and it says "Pre-Merge Inspection  Pending -- NOT INSPECTED YET - NO REVIEWS FOUND".  How can that be?

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Okay, I just got the comment:

> Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ fryeguy52 ]!

So it looks like the auto PR tester has to run to verify all of this.  It is not GitHub itself notes that inspection has taken place.

How often does this the auto PR tester run to do these checks?  Is it still a 20 minute loop?

**Comment by allevin** [comment]
CC:@trilinos/framework 

@bartlettroscoe you are correct.  The status flags that we use (pre-test, pre-merge, Pull Request AutoTester) are controlled only via the Github API.  They are now set as required and will block merges until the autotester makes an API call to set them to "success".  The autotester instances are all on a 20 minute loop.

**Comment by bartlettroscoe** [comment]
> The autotester instances are all on a 20 minute loop.

@allevin, is there a major performance or other impediment why this loop could not be done say ever 5 minutes?  Why 20 minutes between iterations?

**Pull request merged**
