### PR TITLE
Updated to cmake 19 for Ross' cuda schedule fixes

### PR DESCRIPTION
**Pull request by bathmatt**
We need this to go to the new resource management stuff.

@jmgate @rppawlo @bartlettroscoe

### CODE REVIEW

**Review by bartlettroscoe — DISMISSED** [review]
@bathmatt, I will assume you tested this locally?

In any case, it seems that version of CMake does exist for SEMS RHEL7 systems as shown by running the following on my CEE RHEL7 machine:

```
$ module avail 2>&1 | grep sems-cmake
sems-cmake/2.8.11          sems-ninja_fortran/1.10.0
sems-cmake/2.8.12          sems-ninja_fortran/1.8.2
sems-cmake/3.10.3(default) sems-pcre/8.41
sems-cmake/3.11.1          sems-serf/1.3.8
sems-cmake/3.12.2          sems-subversion/1.7.19
sems-cmake/3.17.1          sems-swig/3.0.10
sems-cmake/3.19.1          sems-tex/2015
sems-cmake/3.3.2           sems-tex/2019
sems-cmake/3.5.2           sems-vvtest/1.0
```

You might also consider upgrading Ninja to 'sems-ninja_fortran/1.10.0'.  That version of Ninja is the official Google version that supports Fortran natively (without a Kitware fork).

**Comment by bathmatt** [comment]
@bartlettroscoe can you approve again?

**Review by bartlettroscoe — APPROVED** [review]
@bathmatt, sorry I meant to approve.  Again, I am assuming someone tested this locally (I have not).

**Comment by bathmatt** [comment]
I'll merge once I test the new ninja with a full thing

**Comment by bathmatt** [comment]
Tested new version, all is well,

**Comment by bartlettroscoe** [comment]
Related to:
* SEPW-215

**Pull request merged**
