### PR TITLE
EpetraExt: Support HDF5 1.10.

### PR DESCRIPTION
**Pull request by bavier**
From #566

### CODE REVIEW

**Comment by jwillenbring** [comment]
@srajama1 do you know who this should be assigned to?

**Comment by krcb** [comment]
@jwillenbring @srajama1 Siva and I discussed this. @MicheldeMessieres and I will review and test.

**Comment by MicheldeMessieres** [comment]
@jwillenbring I've added PR #1105 which modified this PR to also add the HDF5_IO.cpp example as a routine tested example.

**Comment by jwillenbring** [comment]
@MicheldeMessieres Is this ready to merge as far as you know?

**Comment by MicheldeMessieres** [comment]
@jwillenbring I believe so but I think should be SEMS checked again as it was a while ago. I could do this now.

**Comment by prwolfe** [comment]
Our current version is 1.8.19.  We tend to use the stable version as determined by @gdsjaar. I presume this preserves backward compatibility?

**Comment by bavier** [comment]
Issue #566 notes that 1.8.0 is the earliest compatible hdf5 version.  This patch was tested with that version.

**Comment by mhoemmen** [comment]
Should we close this PR if the other one subsumes it?

**Comment by MicheldeMessieres** [comment]
@mhoemmen I would say yes.

**Pull request closed without merging**
