### PR TITLE
Panzer add hip support

### PR DESCRIPTION
**Pull request by rppawlo**
## Motivation

Get Panzer (and Mini-EM) running with HIP backend.

## Testing

All panzer tests are now passing!

### CODE REVIEW

**Review by kyungjoo-kim — APPROVED** [review]

**Comment by e10harvey** [comment]
> @trilinos/framework - can you take a look at the most recent failure of this PR and help me understand what is going on? The failure is in zoltan, yet I have not changed any code in zoltan and it is far upstream of the package I am testing. It's almost as if the PR tester is reporting the results of other PR tests in this PR. Maybe the tester is not resetting the git repo from previous PR tests? If I look at the previous round of testing, which tested the exact same commits - all tests passed, but it was flagged as failed. It looks like the cuda just did not run at all as nothing is reported to cdash for the cuda build.

@rppawlo: You can find the [cuda build here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables&field2=groupname&compare2=61&value2=Pull%20Request).

Are you referring to [these build errors](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=10572802&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and) in the intel-17 build?

**Comment by rppawlo** [comment]
@e10harvey - In the autotester post from last round of testing there is a link "CDash Test Results for PR# 10129". Following that link, and sorting by "Start Time" show no cuda builds for any testing this week.

Yes - those are the errors I am talking about. The intrepid2 errors are probably valid and something I need to address. But there are 3 zoltan errors that I can't explain. I haven't made any changes to zoltan or it's dependencies.

**Comment by e10harvey** [comment]
> @e10harvey - In the autotester post from last round of testing there is a link "CDash Test Results for PR# 10129". Following that link, and sorting by "Start Time" show no cuda builds for any testing this week.

Correct. The current temporary cuda builds (which are from Dev2Master) post to a different cdash instance.

**Comment by e10harvey** [comment]
> Yes - those are the errors I am talking about. The intrepid2 errors are probably valid and something I need to address. But there are 3 zoltan errors that I can't explain. I haven't made any changes to zoltan or it's dependencies.

Are the 3 zoltan errors due to an icpc failure?

**Comment by rppawlo** [comment]
looks like intel compiler seg fault:
```
source file: packages/zoltan2/test/core/TpetraCrsColorer/Bug9500.cpp 
...
icpc: error #10106: Fatal error in /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/base/compilers_and_libraries_2017.1.132/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /scratch/trilinos/jenkins/ascic142/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/Trilinos/packages/zoltan2/test/core/TpetraCrsColorer/Bug9500.cpp (code 1)
```

**Comment by rppawlo** [comment]
@e10harvey - I did a retest without changing the code base and all the intel compiler failures disappeared. This PR still failed due to the cuda build. It looks like the git repo is not being reset correctly. The output from the cuda build shows the PR tester calling the command ```git checkout -B develop origin/develop``` and failing with conflicts. This PR has no changes associated with those files and is not even trying to merge my changes in at this point. This looks like a problem resetting the git repo to develop on vortex. Can you help figure out what is going on?
```
PRLinuxDriverMerge> git reset --hard HEAD
Previous HEAD position was f3fbfe7a6a2 Panzer: fix for cuda testing
Switched to and reset branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Your branch is up to date with 'origin/develop'.
PRLinuxDriverMerge> OK
PRLinuxDriverMerge> 
PRLinuxDriverMerge> Checked Call:
PRLinuxDriverMerge> git checkout -B develop origin/develop
Removing packages/tempus/doc/index.dox
Removing packages/stk/stk_unit_tests/stk_io/UnitTestIossTextMesh.cpp
Removing packages/stk/stk_unit_test_utils/stk_unit_test_utils/TextMeshUtils.cpp
Removing packages/stk/stk_unit_test_utils/stk_unit_test_utils/Iotm_TextMesh.hpp
Removing packages/stk/stk_unit_test_utils/stk_unit_test_utils/Iotm_TextMesh.cpp
Removing packages/stk/stk_unit_test_utils/stk_unit_test_utils/Iotm_DatabaseIO.hpp
Removing packages/stk/stk_unit_test_utils/stk_unit_test_utils/Iotm_DatabaseIO.cpp
Removing packages/seacas/libraries/suplib_c/getline.h
Removing packages/seacas/libraries/suplib_c/getline.c
Auto-merging packages/sacado/test/UnitTests/Fad_Kokkos_CommTests_Serial.cpp
CONFLICT (content): Merge conflict in packages/sacado/test/UnitTests/Fad_Kokkos_CommTests_Serial.cpp
Auto-merging packages/sacado/test/UnitTests/Fad_KokkosTests_HIP.cpp
CONFLICT (add/add): Merge conflict in packages/sacado/test/UnitTests/Fad_KokkosTests_HIP.cpp
Auto-merging packages/sacado/test/UnitTests/Fad_KokkosTests.hpp
CONFLICT (content): Merge conflict in packages/sacado/test/UnitTests/Fad_KokkosTests.hpp
Auto-merging packages/sacado/test/UnitTests/CMakeLists.txt
CONFLICT (content): Merge conflict in packages/sacado/test/UnitTests/CMakeLists.txt
Removing packages/muelu/doc/UsersGuide/MueLu_MasterList.cpp
Removing packages/krino/cmake_install_test/load_gcc_modules
Removing cmake/ctest/drivers/typhon/valgrind_suppressions_typhon_mpich2_1.4.1p1.txt
```

**Comment by e10harvey** [comment]
> Can you help figure out what is going on?

@rppawlo: There appears to be a corrupt workspace. I think that has been fixed now - can you try it out?

**Comment by rppawlo** [comment]
@e10harvey - retest failed again. Got the same failure on cuda. Also had the intel compiler seg fault pop up on one test as well.

**Comment by e10harvey** [comment]
@rppawlo: Can you try rebasing your topic branch on-top of develop and force pushing?

**Comment by ZUUL42** [comment]
@e10harvey, I was just looking at that:
https://github.com/trilinos/Trilinos/compare/develop...rppawlo:panzer-add-hip-support
It appears to be perfectly auto-mergeable.
Though doing a rebase & force push certainly shouldn't hurt anything.

@rppawlo, I'm about out for the day. I'll look into it further tomorrow.

**Comment by rppawlo** [comment]
@e10harvey @ZUUL42 - the rebase did not work. still failing the cuda build with the merge issue.

**Comment by e10harvey** [comment]
> @e10harvey @ZUUL42 - the rebase did not work. still failing the cuda build with the merge issue.

Hi Roger. We are working to resolve this. See https://github.com/trilinos/Trilinos/issues/10147 and #10167. Thank you for your patience.

**Pull request closed without merging**
