### PR TITLE
Panzer: cleanup cuda warnings from lambda capture of mdfields

### PR DESCRIPTION
**Pull request by rppawlo**
@trilinos/panzer

## Motivation

fix warnings

## Testing

N/A

### CODE REVIEW

**Comment by bathmatt** [comment]
@rppawlo the same thing happened to my job, the cuda runs never launched.  @trilinos/framework any idea on why?

**Comment by rppawlo** [comment]
Definitely looks like a PR testing issue - the merge is failing in one of the builds for some reason. @trilinos/framework can you help us with this?

**Comment by prwolfe** [comment]
Ride cannot see GitHub

> fatal: unable to access 'https://github.com/trilinos/Trilinos/': SSL certificate problem: unable to get local issuer certificate

Not sure why.

**Review by bathmatt — APPROVED** [review]

**Comment by prwolfe** [comment]
I have a change in proxy setting on ride that I would like to check so I am setting the AT: Retest label.

**Pull request merged**
