### PR TITLE
Added RHEL7

### PR DESCRIPTION
**Pull request by bathmatt**
I added the files from RHEL6 to RHEL7 and now I can compile on RHEL7 with sems modules..  Thoughts?

### CODE REVIEW

**Comment by bathmatt** [comment]
Doesn't jenkins have a rhel7 machine?  We're moving away from shiller to a nightly test to a rhel7/sems.

I'm going to look at cuda as well on this.  Not sure how to do so though.

**Comment by nmhamster** [comment]
@bathmatt - way are you moving away from Shiller?

**Comment by bathmatt** [comment]
Becasue the filesystem is jacked up making h5part files...  We get random failures tracked down to either HW/SW issues that @nmhamster and one of the admins couldn't figure out..

**Comment by bartlettroscoe** [comment]
Looks like there is a "RHEL7" Jenkins label:

* https://jenkins-srn.sandia.gov:8443/label/RHEL7/

and at least one SEMS RHEL7 node:

* https://jenkins-srn.sandia.gov:8443/computer/sems-srn-rhel7-slave-01/

@bathmatt, is it your plan to run EMPIRE builds on that machine?

**Comment by bartlettroscoe** [comment]
@trilinos/framework, this PR says it is ready to merge.  Yet there is not PR testing builds run.  How can that be?

**Comment by bathmatt** [comment]
We're going to be adding a machine to jenkins, empire dedicated.

**Comment by bathmatt** [comment]
Do you want to merge this now?  We are still working through the adding of jenkins slave.

**Comment by prwolfe** [comment]
It's going into master instead of develop.  Shouldn't it be blocked for that?

**Comment by bathmatt** [comment]
Oh crap, I'll change that..

**Comment by bathmatt** [comment]
Sorry, fixed now, screwed up my initial checkout..

**Comment by bartlettroscoe** [comment]
> Do you want to merge this now? We are still working through the adding of jenkins slave.

@bathmatt, if this works for local builds of Trilinos and EMPIRE then it is fine to merge this.   We can add documentation for this env once we set up automated builds.

**Comment by bartlettroscoe** [comment]
After thinking about this, since the file `sems-rhel7/enviornment.sh` looks to be almost 100% identical to `sems-rhel6/enviornment.sh`, should we create a file `sems-rhel/enviornment.sh` that contains the bulk of this info and then have these two source that?  That is what we did for the `serrano` and `chama` envs that both use the same `toss3/enviornment.sh` script.  But if the `sems-rhel7/enviornment.sh` will diverge at some point (which might happen when we stand up an ATDM GCC 7.2.0 env that will support SPARC and EMPIRE).

**Comment by bartlettroscoe** [comment]
Is there a SEMS RHEL7 machine that we can log in to test out this 'sems-rhel7' env?  Is there some shared machine on the CEE LAN for example that we could use to experiment with this build?

**Comment by bathmatt** [comment]
Not sure on the sems RHEL7 machine, I can get you access to one of ours..

**Comment by bartlettroscoe** [comment]
> Not sure on the sems RHEL7 machine, I can get you access to one of ours..

@bathmatt, can you get me an account on one of these machines so that I can log in?  (You can contact me offline).   That way I can help get a setup that reduces duplication between the 'sems-rhel6' and 'sems-rhel7' envs and gets this env in.  But until we set up automated builds with this env, it is subject to get broken.

**Comment by bartlettroscoe** [comment]
I am putting label `AT: WIP` so that we stop getting spammed by the autotester that this is not merged yet.  I need to get access to a SEMS RHEL7 machine in order to fix this update and integrate this in.

**Comment by bartlettroscoe** [comment]
FYI: This has been superseded by PR #4021.  Closing this PR.

**Pull request closed without merging**
