### PR TITLE
Framework: Improve support for LMOD module() command

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework 

## Motivation
Pulling in some of the changes that I added in to @prwolfe Vortex test addition branch. I have also expanded on some of the testing in the `setenvironment` module to catch a few more corner cases.

The main changes here are related to the use of an `lmod` based `module()` command that is loaded from the `env_modules_python` file that comes with the LMOD package. The default LMOD function has no return value based on success or failure which is different from how we wrote our `module()` function which uses modulecmd when lmod isn't available.

For expediency, we created a thin wrapper around the `module()` command for LMOD based systems that always returns a 0 status and passes along an exception if one occurs:
https://github.com/william76/Trilinos/blob/8d8d50b730b4cad0415adfcec83a6d81c4c60e41/cmake/std/trilinosprhelpers/setenvironment/ModuleHelper.py#L33-L63

Related to #7383

## Testing
<details><summary>Local MOCK testing only</summary>
<pre>
0 $ ./test_pr_overhaul.sh
================================================================================== test session starts ==================================================================================
platform darwin -- Python 3.8.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.0', 'Platform': 'macOS-10.15.7-x86_64-i386-64bit', 'Packages': {'pytest': '6.1.2', 'py': '1.9.0', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.10.0', 'cov': '2.10.0', 'xdist': '2.0.0', 'sphinx': '0.3.1', 'forked': '1.3.0', 'osxnotify': '0.1.7'}, 'PLATFORM': 'darwin'}
rootdir: /Users/wcmclen/dev/trilinos/trilinos-dev-framework/source/Trilinos/cmake/std
plugins: metadata-1.10.0, cov-2.10.0, xdist-2.0.0, sphinx-0.3.1, forked-1.3.0, osxnotify-0.1.7
collected 102 items

trilinosprhelpers/gitutility/unittests/test_GitUtility.py::GitUtilityTest::test_check_minimum_version PASSED                                                                      [  0%]
trilinosprhelpers/gitutility/unittests/test_GitUtility.py::GitUtilityTest::test_pretty_print PASSED                                                                               [  1%]
trilinosprhelpers/gitutility/unittests/test_GitUtility.py::GitUtilityTest::test_version PASSED                                                                                    [  2%]
trilinosprhelpers/gitutility/unittests/test_GitUtility.py::GitUtilityTest::test_version_str PASSED                                                                                [  3%]
trilinosprhelpers/jenkinsenv/unittests/test_EnvvarHelper.py::EnvvarHelperTest::test_envvar_found PASSED                                                                           [  4%]
trilinosprhelpers/jenkinsenv/unittests/test_EnvvarHelper.py::EnvvarHelperTest::test_envvar_notfound_with_error PASSED                                                             [  5%]
trilinosprhelpers/jenkinsenv/unittests/test_EnvvarHelper.py::EnvvarHelperTest::test_envvar_notfound_without_error PASSED                                                          [  6%]
trilinosprhelpers/jenkinsenv/unittests/test_EnvvarHelper.py::EnvvarHelperTest::test_get_or_create_if_missing PASSED                                                               [  7%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_build_id PASSED                                                                                   [  8%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_build_number PASSED                                                                               [  9%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_build_tag PASSED                                                                                  [ 10%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_build_url PASSED                                                                                  [ 11%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_cvs_branch PASSED                                                                                 [ 12%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_executor_number PASSED                                                                            [ 13%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_git_branch PASSED                                                                                 [ 14%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_git_commit PASSED                                                                                 [ 15%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_git_url PASSED                                                                                    [ 16%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_java_home PASSED                                                                                  [ 17%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_jenkins_home PASSED                                                                               [ 18%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_jenkins_job_weight PASSED                                                                         [ 19%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_jenkins_test_weight PASSED                                                                        [ 20%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_jenkins_url PASSED                                                                                [ 21%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_job_base_name PASSED                                                                              [ 22%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_job_name PASSED                                                                                   [ 23%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_node_labels PASSED                                                                                [ 24%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_node_name PASSED                                                                                  [ 25%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_svn_revision PASSED                                                                               [ 26%]
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py::JenkinsEnvTest::test_workspace PASSED                                                                                  [ 27%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_force_clean PASSED                                                                [ 28%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_pullrequest_cdash_track PASSED                                                    [ 29%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_pullrequestnum PASSED                                                             [ 30%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_trilinos_source_branch PASSED                                                     [ 31%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_trilinos_source_repo PASSED                                                       [ 32%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_trilinos_source_sha PASSED                                                        [ 33%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_trilinos_target_branch PASSED                                                     [ 34%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_trilinos_target_repo PASSED                                                       [ 35%]
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py::TrilinosJenkinsEnvTest::test_trilinos_target_sha PASSED                                                        [ 36%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_load_args_as_list PASSED                                                           [ 37%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_load_error_by_mlstatus PASSED                                                      [ 38%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_load_error_exception PASSED                                                        [ 39%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_load_error_module_returns_nonetype PASSED                                          [ 40%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_load_error_no_modulecmd PASSED                                                     [ 41%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_load_status_error PASSED                                                           [ 42%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_load_status_ok PASSED                                                              [ 43%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_load_success_by_mlstatus PASSED                                                    [ 44%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_swap_status_ok PASSED                                                              [ 45%]
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py::moduleHelperTest::test_module_unload_status_ok PASSED                                                            [ 46%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_ModulePurge PASSED                                                     [ 47%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_ModuleRemoveMulti PASSED                                               [ 48%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_ModuleUnloadMulti PASSED                                               [ 49%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_Profile001_F PASSED                                                    [ 50%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_Profile001_P PASSED                                                    [ 50%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_Profile002_P PASSED                                                    [ 51%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_Profile003_P PASSED                                                    [ 52%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_Profile004_P PASSED                                                    [ 53%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_Profile005_P PASSED                                                    [ 54%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_Profile006_P PASSED                                                    [ 55%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_actions_A PASSED                                                       [ 56%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_actions_B PASSED                                                       [ 57%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_actions_C PASSED                                                       [ 58%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_actions_D PASSED                                                       [ 59%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_actions_E PASSED                                                       [ 60%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_config PASSED                                                          [ 61%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_expand_envvars_error PASSED                                            [ 62%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_missing_file PASSED                                                    [ 63%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_missing_section_name PASSED                                            [ 64%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_module_returns_NoneType PASSED                                         [ 65%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_module_too_many_params PASSED                                          [ 66%]
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py::SetEnvironmentTest::test_SetEnvironment_pretty_print_envvars PASSED                                            [ 67%]
trilinosprhelpers/sysinfo/unittests/test_SysInfo.py::SysInfoTest::test_GetMem_meminfo PASSED                                                                                      [ 68%]
trilinosprhelpers/sysinfo/unittests/test_SysInfo.py::SysInfoTest::test_GetMem_psutil PASSED                                                                                       [ 69%]
trilinosprhelpers/sysinfo/unittests/test_SysInfo.py::SysInfoTest::test_SysInfo_have_psutil_error PASSED                                                                           [ 70%]
trilinosprhelpers/sysinfo/unittests/test_SysInfo.py::SysInfoTest::test_compute_num_usable_cores PASSED                                                                            [ 71%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBase PASSED                                             [ 72%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseBuildNameGCC720 PASSED                              [ 73%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBasePackageEnablesGCC720 PASSED                         [ 74%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBasePackageEnablesGCC720_ERROR PASSED                   [ 75%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBasePackageEnablesGCC720_dryrun PASSED                  [ 76%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBasePackageEnablesPython2 PASSED                        [ 77%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBasePackageEnablesPython2_dryrun PASSED                 [ 78%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_concurrency_test_err PASSED                [ 79%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_config_script PASSED                       [ 80%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_get_multi_property_from_config_FAIL PASSED [ 81%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_get_multi_property_from_config_PASS PASSED [ 82%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_get_property_from_config_FAIL PASSED       [ 83%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_get_property_from_config_PASS PASSED       [ 84%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_package_enables_file PASSED                [ 85%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_subprojects_file PASSED                    [ 86%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBaseProperty_working_directory_ctest PASSED             [ 87%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBase_execute_test PASSED                                [ 88%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBase_prepare_test PASSED                                [ 89%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBase_prepare_test_FAIL PASSED                           [ 90%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationBuildNamePython2 PASSED                                 [ 91%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationCDashTrack PASSED                                       [ 92%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationValidateBranchNameDevelop PASSED                        [ 93%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationValidateBranchNameMasterFAIL PASSED                     [ 94%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py::TrilinosPRConfigurationTest::test_TrilinosPRConfigurationValidateBranchNameMasterPASS PASSED                     [ 95%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationInstallation.py::TrilinosPRConfigurationInstallationTest::test_TrilinosPRConfigurationInstallationDryRun PASSED           [ 96%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationInstallation.py::TrilinosPRConfigurationInstallationTest::test_TrilinosPRConfigurationInstallationExec PASSED             [ 97%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py::TrilinosPRConfigurationStandardTest::test_TrilinosPRConfigurationStandardDryRun PASSED                       [ 98%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py::TrilinosPRConfigurationStandardTest::test_TrilinosPRConfigurationStandardExec PASSED                         [ 99%]
trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py::TrilinosPRConfigurationStandardTest::test_TrilinosPRConfigurationStandardPython3 PASSED                      [100%]

---------- coverage: platform darwin, python 3.8.0-final-0 -----------
Name                                                                      Stmts   Miss  Cover   Missing
+------------------------------------------------------------------------------------------------------
trilinosprhelpers/TrilinosPRConfigurationBase.py                            245      9    96%   275-276, 433-439
trilinosprhelpers/TrilinosPRConfigurationInstallation.py                     30      3    90%   71-73
trilinosprhelpers/TrilinosPRConfigurationStandard.py                         30      3    90%   71-73
trilinosprhelpers/__init__.py                                                 7      0   100%
trilinosprhelpers/gitutility/GitUtility.py                                   40      0   100%
trilinosprhelpers/gitutility/__init__.py                                      1      0   100%
trilinosprhelpers/gitutility/unittests/__init__.py                            1      0   100%
trilinosprhelpers/gitutility/unittests/test_GitUtility.py                    70      0   100%
trilinosprhelpers/jenkinsenv/EnvvarHelper.py                                 21      0   100%
trilinosprhelpers/jenkinsenv/JenkinsEnv.py                                   64      0   100%
trilinosprhelpers/jenkinsenv/TrilinosJenkinsEnv.py                           31      0   100%
trilinosprhelpers/jenkinsenv/__init__.py                                      3      0   100%
trilinosprhelpers/jenkinsenv/unittests/__init__.py                            1      0   100%
trilinosprhelpers/jenkinsenv/unittests/test_EnvvarHelper.py                  29      0   100%
trilinosprhelpers/jenkinsenv/unittests/test_JenkinsEnv.py                   110      0   100%
trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py            55      0   100%
trilinosprhelpers/setenvironment/ModuleHelper.py                             68     11    84%   30-63
trilinosprhelpers/setenvironment/SetEnvironment.py                          205      0   100%
trilinosprhelpers/setenvironment/__init__.py                                  1      0   100%
trilinosprhelpers/setenvironment/unittests/__init__.py                        1      0   100%
trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py             128      0   100%
trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py           216      0   100%
trilinosprhelpers/sysinfo/SysInfo.py                                         44      0   100%
trilinosprhelpers/sysinfo/__init__.py                                         1      0   100%
trilinosprhelpers/sysinfo/unittests/__init__.py                               1      0   100%
trilinosprhelpers/sysinfo/unittests/test_SysInfo.py                          82      0   100%
trilinosprhelpers/unittests/__init__.py                                       1      0   100%
trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py             318      0   100%
trilinosprhelpers/unittests/test_TrilinosPRConfigurationInstallation.py      85      0   100%
trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py          93      0   100%
+------------------------------------------------------------------------------------------------------
TOTAL                                                                      1982     26    99%
</pre>
</details>

## Additional Information
The missing coverage in the `ModuleHelper` module is due to a lack of explicit _mock_ testing for `lmod` based Module support. Right now this is all controlled based on whether or not `import env_modules_python` succeeds and I'm not currently sure how to get mock testing to mimic a successful import when that module doesn't actually exist on the local machine. @prwolfe do you know how one might mock out an import?

In the longer term, now that I have a much better understanding of what our `modulecmd` based module loader and the lmod based `module` commands are doing we might want to re-engineer the `ModuleHelper` code to provide a more robust capability with better cross-platform error checking.  Part of a full 'lmod' support should also bake in support for the notion of a "sticky" module from LMOD.

### CODE REVIEW

**Comment by prwolfe** [comment]
It looks like Ride is unhappy with these. It is failing during environ setup - see https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_pullrequest_cuda_9.2/6066/console

```
20:34:06 +--------------------------------------------------------------------+
20:34:06 |   E N V I R O N M E N T   S E T   U P   S T A R T
20:34:06 +--------------------------------------------------------------------+
20:34:06 Module Operations
20:34:06 +---------------+
20:34:06 [module] module load git/2.10.1 OK
20:34:06 [module] module load devpack/20180521/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88An ERROR occurred during execution of module commands
20:34:06 Traceback (most recent call last):
20:34:06   File "/home/trilinos/jenkins/ride/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/cmake/std/PullRequestLinuxDriverTest.py", line 259, in <module>
20:34:06     status = main(args)
20:34:06   File "/home/trilinos/jenkins/ride/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/cmake/std/PullRequestLinuxDriverTest.py", line 249, in main
20:34:06     pr_config.prepare_test()
20:34:06   File "/home/trilinos/jenkins/ride/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/cmake/std/trilinosprhelpers/TrilinosPRConfigurationBase.py", line 563, in prepare_test
20:34:06     rval = tr_config.apply(throw_on_error=True)
20:34:06   File "/home/trilinos/jenkins/ride/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/cmake/std/trilinosprhelpers/setenvironment/SetEnvironment.py", line 176, in apply
20:34:06     cmd_status = max(ModuleHelper.module(op, params[0]), status)
20:34:06   File "/home/trilinos/jenkins/ride/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/cmake/std/trilinosprhelpers/setenvironment/ModuleHelper.py", line 135, in module
20:34:06     raise error
20:34:06   File "/home/trilinos/jenkins/ride/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/cmake/std/trilinosprhelpers/setenvironment/ModuleHelper.py", line 123, in module
20:34:06     exec(output, pGlobals, pLocals)
20:34:06   File "<string>", line 1, in <module>
20:34:06 NameError: name 'os' is not defined
20:34:06 Build step 'Execute shell' marked build as failure
20:34:06 Archiving artifacts
20:34:06 [Checks API] No suitable checks publisher found.
20:34:06 Finished: FAILURE
```

**Comment by william76** [comment]
> It looks like Ride is unhappy with these. It is failing during environ setup - see https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_pullrequest_cuda_9.2/6066/console

@prwolfe I believe I've fixed it.  The issue was that it was throwing an error saying it can't find the `os` module, which is loaded in the file... _but_ I was doing something silly with `exec()`. I should have that fixed now so I'll remove the WIP flag.

**Comment by william76** [comment]
Closes #8371

**Comment by william76** [comment]
https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_pullrequest_gcc_8.3.0/2840/console

**Comment by william76** [comment]
bump @prwolfe @jwillenbring

**Review by prwolfe — APPROVED** [review]

**Comment by william76** [comment]
Dear autotester, please stop marking this as stale!

**Pull request merged**
