### PR TITLE
ATDM:  Turn Anasazi on for EMPIRE

### PR DESCRIPTION
**Pull request by jmgate**
## Motivation
EMPIRE needs to turn Anasazi on in order to solve eigen systems to obtain TE and TM modes on surfaces.

## Testing
Testing manually now.

### CODE REVIEW

**Review by egphill — APPROVED** [review]
Looks good. Thank you.

**Comment by jmgate** [comment]
Looks like Trilinos configured and is building fine with Anasazi turned on.  Will start building EMPIRE soon.

**Review by e10harvey — APPROVED** [review]
Thanks, @jmgate!

**Comment by jmgate** [comment]
@e10harvey, do you know if this might adversely affect any existing nightly builds?

**Comment by jmgate** [comment]
@egphill, are there any changes needed in EMPIRE to build with Anasazi on?  Or should our current `develop` branch build against a Trilinos with Anasazi just fine?

**Comment by egphill** [comment]
@jmgate It should work with develop.

**Comment by e10harvey** [comment]
> @e10harvey, do you know if this might adversely affect any existing nightly builds?

I do not. Shall we merge this into develop and if tonight's builds show problems, revert this PR?

**Comment by jmgate** [comment]
Yup, sounds good.

**Comment by jmgate** [comment]
@trilinos/framework, @william76, can you take a look at [this failure](https://testing.sandia.gov/cdash/test/52316255)?  I think the regex is matching `FAILED` in
```
--- /projects/sierra/linux_rh7/install/Python/3.6.10/bin/python3 ./get-pip.py --user --proxy=http://wwwproxy.sandia.gov:80 --no-setuptools --no-wheel
Collecting pip
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

and that's causing the unit test suite to fail when it shouldn't.  FWIW, I'm running into the same problems trying to get pip to work on my Mac and Linux machines.  I haven't gotten back to it yet, but I was told a `kinit` might fix things for me.

**Comment by e10harvey** [comment]
> @trilinos/framework, @william76, can you take a look at [this failure](https://testing.sandia.gov/cdash/test/52316255)?

@jmgate: #8643 addresses this.

**Comment by jmgate** [comment]
Gracias.

**Pull request merged**
