### PR TITLE
Intrepid2: fix shadow variables

### PR DESCRIPTION
**Pull request by japlews**
@trilinos/intrepid2
@CamelliaDPG @mperego 

## Motivation

Fix shadow warnings in builds of Sierra.

### CODE REVIEW

**Comment by japlews** [comment]
@mperego This issue comes up frequently in Sierra builds. We always build with `-Wshadow` and thus `-Werror` results in build failures; do you think the Trilinos teams would be amenable to adding this compiler flag to CI builds?

**Comment by rppawlo** [comment]
> do you think the Trilinos teams would be amenable to adding this compiler flag to CI builds?

@japlews - this will be a big lift. There are tons of shadow warnings in trilinos packages. We would have to clean all packages, not just the ones sierra is using. It's the right thing to do, but will take some time. What compilers/versions do you enable the "shadow warnings as error" in? The shadow warnings change from version to version and across compilers, so it would be best to mirror your builds where possible.

**Comment by mdmosby** [comment]
@rppawlo -- the current SIERRA development PE with all warnings as errors is gcc-10.2-openmpi-4.0.5. While we use many Trilinos packages (I've communicated the list of packages previously and can do so again if needed), this is the only one that consistently emits shadowing warnings and reintroduces them from time-to-time.

If making the CI use -Wshadow is too big a lift, would it make sense to deactivate those warnings in the Intrepid2 package via pragmas in the includes? That way, Trilinos/Intrepid2 can continue to "own" the behavior without breaking SIERRA and it is clear in the source code that there are issues with shadowing.

@japlews -- would this approach work for our use of Intrepid2? Could we try it with patch files in our spack build?

**Comment by japlews** [comment]
> @japlews -- would this approach work for our use of Intrepid2? Could we try it with patch files in our spack build?

@mdmosby Yes, kinda, but it would not involve a patch. We would need to protect all our `#include`s of Intrepid2 headers with these `#pragma`s.

**Comment by mdmosby** [comment]
Couldn’t the pragmas be pushed/popped in the Intrepid headers?

From: japlews ***@***.***>
Reply-To: trilinos/Trilinos ***@***.***>
Date: Wednesday, November 9, 2022 at 2:42 PM
To: trilinos/Trilinos ***@***.***>
Cc: "Mosby, Matthew David" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [trilinos/Trilinos] Intrepid2: fix shadow variables (PR #11245)


@japlews<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjaplews&data=05%7C01%7Cmdmosby%40sandia.gov%7C344153dc427c490942ea08dac28a90fa%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638036197634471315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iCJ3KGq%2F59MsT7esydWXtuZUGu%2BEyKhVkPAGCsaLgT8%3D&reserved=0> -- would this approach work for our use of Intrepid2? Could we try it with patch files in our spack build?

@mdmosby<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmdmosby&data=05%7C01%7Cmdmosby%40sandia.gov%7C344153dc427c490942ea08dac28a90fa%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638036197634627556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yVCKQ0ClUnC%2FfwTF%2BmuJt%2Fs4FTEwa8Qev5WZMhIuWo4%3D&reserved=0> Yes, kinda, but it would not involve a patch. We would need to protect all our #includes of Intrepid2 headers with these #pragmas.

**Comment by jjellio** [comment]
Don't forget, you can do things like "Tpetra_CXX_FLAGS=-Wshadows" or something like that (you can add package specific flags at configure is my point).  That's saved my butt a few times.

**Comment by rppawlo** [comment]
We talked about this at the trilinos product leaders meeting today. After the 14.0 release (expected a the end of this month), we will prioritize getting a build set up with shadow warnings as errors. Each package team will be notified and be responsible for removing shadow warnings in their package. There are flags to enable warnings as errors at the package level so each package can do this work independently. We followed this procedure the last time we enabled a "warnings as error" build for sierra and it worked well. We can't promise when all the packages will be clean, but we will work towards it during this FY. If there are certain packages you would like prioritized, please let us know. @ccober6

**Review by mperego — APPROVED** [review]
Looks good. Thanks @japlews !

**Pull request merged**
