### PR TITLE
Kokkos + KokkosKernels promotion

### PR DESCRIPTION
**Pull request by crtrott**
Changes for Kokkos:

## [2.04.04](https://github.com/kokkos/kokkos/tree/2.04.04) (2017-09-11)
[Full Changelog](https://github.com/kokkos/kokkos/compare/2.04.00...2.04.04)

**Implemented enhancements:**

- OpenMP partition: set number of threads on nested level [\#1082](https://github.com/kokkos/kokkos/issues/1082)
- Add StaticCrsGraph row\(\) method [\#1071](https://github.com/kokkos/kokkos/issues/1071)
- Enhance Kokkos complex operator overloading [\#1052](https://github.com/kokkos/kokkos/issues/1052)
- Tell Trilinos packages about host+device lambda [\#1019](https://github.com/kokkos/kokkos/issues/1019)
- Function markup for defaulted class members [\#952](https://github.com/kokkos/kokkos/issues/952)
- Add deterministic random number generator [\#857](https://github.com/kokkos/kokkos/issues/857)

**Fixed bugs:**

- Fix reduction\_identity\<T\>::max for floating point numbers [\#1048](https://github.com/kokkos/kokkos/issues/1048)
- Fix MD iteration policy ignores lower bound on GPUs [\#1041](https://github.com/kokkos/kokkos/issues/1041)
- (Experimental) HBWSpace  Linking issues in KokkosKernels [\#1094](https://github.com/kokkos/kokkos/issues/1094)
- (Experimental) ROCm:  algorithms/unit\_tests test\_sort failing with segfault [\#1070](https://github.com/kokkos/kokkos/issues/1070)

### CODE REVIEW

**Comment by ambrad** [comment]
@crtrott, awesome. Am testing now.

**Comment by crtrott** [comment]
Apparently the automatic testing doesn't work yet so we still need to run checkin-test manually.

**Comment by crtrott** [comment]
As documentation here is output from the four integration testbuilds:

**Comment by crtrott** [comment]
* White Cuda
    * No Build Errors
    * Test Output (Matches unpatched develop Trilinos Branch):
```
95% tests passed, 76 tests failed out of 1671

Label Time Summary:
Amesos2          =  11.70 sec (8 tests)
Anasazi          = 231.97 sec (71 tests)
Belos            = 297.41 sec (70 tests)
Ifpack           = 240.63 sec (41 tests)
Ifpack2          =  87.15 sec (34 tests)
Intrepid         = 370.48 sec (153 tests)
Intrepid2        = 223.59 sec (154 tests)
Isorropia        =   3.59 sec (4 tests)
Kokkos           = 208.53 sec (23 tests)
KokkosKernels    =  41.70 sec (8 tests)
ML               =  39.79 sec (16 tests)
MueLu            = 807.31 sec (84 tests)
NOX              = 540.13 sec (92 tests)
Panzer           = 542.76 sec (111 tests)
Phalanx          =  15.60 sec (20 tests)
ROL              = 404.27 sec (63 tests)
Sacado           = 102.98 sec (299 tests)
Stokhos          = 313.58 sec (82 tests)
Stratimikos      =  25.03 sec (23 tests)
Thyra            =  57.55 sec (80 tests)
Tpetra           = 199.54 sec (139 tests)
Xpetra           =  66.86 sec (17 tests)
Zoltan2          = 140.43 sec (88 tests)

Total Test time (real) = 4942.47 sec

The following tests FAILED:
        720 - Belos_pseudo_gmres_hb_MPI_4 (Failed)
        721 - Belos_bl_pgmres_hb_0_MPI_4 (Failed)
        722 - Belos_bl_pgmres_hb_1_MPI_4 (Failed)
        723 - Belos_bl_pgmres_hb_2_MPI_4 (Failed)
        724 - Belos_pseudo_pgmres_hb_MPI_4 (Failed)
        725 - Belos_bl_fgmres_hb_MPI_4 (Failed)
        741 - Belos_gcrodr_hb_MPI_4 (Failed)
        743 - Belos_prec_gcrodr_hb_1_MPI_4 (Failed)
        744 - Belos_rcg_hb_MPI_4 (Timeout)
        789 - Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)
        791 - Anasazi_Epetra_OrthoManagerTester_0_MPI_4 (Failed)
        792 - Anasazi_Epetra_OrthoManagerTester_1_MPI_4 (Failed)
        793 - Anasazi_Epetra_OrthoManagerTester_2_MPI_4 (Failed)
        794 - Anasazi_Epetra_OrthoManagerTester_3_MPI_4 (Failed)
        795 - Anasazi_Epetra_OrthoManagerTester_4_MPI_4 (Failed)
        796 - Anasazi_Epetra_OrthoManagerTester_5_MPI_4 (Failed)
        797 - Anasazi_Epetra_OrthoManagerMatTester_0_MPI_4 (Failed)
        798 - Anasazi_Epetra_OrthoManagerMatTester_1_MPI_4 (Failed)
        799 - Anasazi_Epetra_OrthoManagerMatTester_2_MPI_4 (Failed)
        800 - Anasazi_Epetra_OrthoManagerMatTester_3_MPI_4 (Failed)
        801 - Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4 (Failed)
        802 - Anasazi_Epetra_OrthoManagerMatTester_5_MPI_4 (Failed)
        803 - Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 (Failed)
        804 - Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)
        805 - Anasazi_Epetra_BlockDavidson_solvertest_MPI_4 (Failed)
        806 - Anasazi_Epetra_BlockDavidson_test_0_MPI_4 (Failed)
        807 - Anasazi_Epetra_BlockDavidson_test_1_MPI_4 (Failed)
        808 - Anasazi_Epetra_BlockDavidson_test_2_MPI_4 (Failed)
        809 - Anasazi_Epetra_BlockDavidson_test_3_MPI_4 (Failed)
        810 - Anasazi_Epetra_BlockDavidson_test_4_MPI_4 (Failed)
        811 - Anasazi_Epetra_BlockDavidson_test_5_MPI_4 (Failed)
        812 - Anasazi_Epetra_BlockDavidson_test_6_MPI_4 (Failed)
        813 - Anasazi_Epetra_BlockDavidson_test_7_MPI_4 (Failed)
        814 - Anasazi_Epetra_BlockDavidson_test_8_MPI_4 (Failed)
        815 - Anasazi_Epetra_BlockDavidson_auxtest_MPI_4 (Failed)
        816 - Anasazi_Epetra_BKS_solvertest_MPI_4 (Failed)
        818 - Anasazi_Epetra_BKS_test_1_MPI_4 (Failed)
        822 - Anasazi_Epetra_BKS_nh_test_1_MPI_4 (Failed)
        823 - Anasazi_Epetra_GeneralizedDavidson_solvertest_MPI_4 (Failed)
        826 - Anasazi_Epetra_LOBPCG_solvertest_MPI_4 (Failed)
        827 - Anasazi_Epetra_LOBPCG_simpletest_MPI_4 (Failed)
        828 - Anasazi_Epetra_LOBPCG_test_MPI_4 (Failed)
        829 - Anasazi_Epetra_LOBPCG_auxtest_MPI_4 (Failed)
        830 - Anasazi_Epetra_IRTR_test_0_MPI_4 (Failed)
        831 - Anasazi_Epetra_IRTR_test_1_MPI_4 (Failed)
        832 - Anasazi_Epetra_IRTR_test_2_MPI_4 (Failed)
        833 - Anasazi_Epetra_IRTR_test_3_MPI_4 (Failed)
        834 - Anasazi_Epetra_IRTR_auxtest_0_MPI_4 (Failed)
        835 - Anasazi_Epetra_IRTR_auxtest_1_MPI_4 (Failed)
        836 - Anasazi_Epetra_IRTR_auxtest_2_MPI_4 (Failed)
        837 - Anasazi_Epetra_IRTR_auxtest_3_MPI_4 (Failed)
        838 - Anasazi_Epetra_IRTR_auxtest_4_MPI_4 (Failed)
        845 - Anasazi_BlockDavidsonThyra_test_MPI_4 (Failed)
        848 - Anasazi_IRTRThyra_test_0_MPI_4 (Failed)
        849 - Anasazi_IRTRThyra_test_1_MPI_4 (Failed)
        850 - Anasazi_IRTRThyra_test_2_MPI_4 (Failed)
        851 - Anasazi_IRTRThyra_test_3_MPI_4 (Failed)
        852 - Anasazi_LOBPCGThyra_test_MPI_4 (Failed)
        859 - Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4 (Failed)
        899 - Stratimikos_Thyra_Belos_StatusTest_UnitTests_MPI_1 (Failed)
        907 - Stratimikos_Belos_GCRODR_strattest_MPI_4 (Failed)
        1158 - Intrepid2_refactor_unit-test_Discretization_Basis_L2_LINE_Cn_FEM_Serial_Test_01_MPI_1 (Not Run)
        1223 - Intrepid2_refactor_unit-test_Orientation_Serial_Test_Orientation_TET_MPI_1 (Failed)
        1256 - NOX_LOCA_AnasaziJacobianInverse_MPI_1 (Timeout)
        1257 - NOX_LOCA_AnasaziNotConverged_MPI_1 (Timeout)
        1330 - NOX_LOCA_MultiPointTcubed_MPI_2 (Failed)
        1356 - MueLu_UnitTestsTpetra_MPI_4 (Timeout)
        1357 - MueLu_UnitTestsEpetra_kokkos_MPI_1 (Failed)
        1358 - MueLu_UnitTestsEpetra_kokkos_MPI_4 (Failed)
        1359 - MueLu_UnitTestsTpetra_kokkos_MPI_1 (Failed)
        1360 - MueLu_UnitTestsTpetra_kokkos_MPI_4 (Failed)
        1509 - ROL_NonlinearProblemTest_MPI_4 (Timeout)
        1557 - ROL_test_elementwise_TpetraMultiVector_MPI_4 (Failed)
        1669 - PanzerAdaptersIOSS_tIOSSConnManager1_MPI_1 (Failed)
        1670 - PanzerAdaptersIOSS_tIOSSConnManager2_MPI_2 (Failed)
        1671 - PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 (Failed)
```

**Comment by crtrott** [comment]
* White OpenMP
    * No Build Errors
    * Test Output (Matches unpatched develop Trilinos Branch):
```
96% tests passed, 75 tests failed out of 1673^M
^M
Label Time Summary:^M
Amesos2          =  10.52 sec (8 tests)^M
Anasazi          =  62.86 sec (71 tests)^M
Belos            =  72.69 sec (70 tests)^M
Ifpack           =  35.49 sec (41 tests)^M
Ifpack2          =  34.81 sec (34 tests)^M
Intrepid         = 150.03 sec (153 tests)^M
Intrepid2        =  66.44 sec (165 tests)^M
Isorropia        =   3.20 sec (4 tests)^M
Kokkos           =  86.72 sec (23 tests)^M
KokkosKernels    =  32.07 sec (8 tests)^M
ML               =  16.83 sec (16 tests)^M
MueLu            = 261.40 sec (84 tests)^M
NOX              = 538.58 sec (92 tests)^M
Panzer           = 155.85 sec (111 tests)^M
Phalanx          =  11.94 sec (20 tests)^M
ROL              = 187.59 sec (63 tests)^M
Sacado           =  78.34 sec (296 tests)^M
Stokhos          = 107.80 sec (78 tests)^M
Stratimikos      =  22.73 sec (23 tests)^M
Thyra            =  54.73 sec (80 tests)^M
Tpetra           = 100.85 sec (137 tests)^M
Xpetra           =  17.22 sec (17 tests)^M
Zoltan2          =  80.03 sec (88 tests)^M
^M
Total Test time (real) = 2184.61 sec^M
^M
The following tests FAILED:^M
        715 - Belos_pseudo_gmres_hb_MPI_4 (Failed)^M
        716 - Belos_bl_pgmres_hb_0_MPI_4 (Failed)^M
        717 - Belos_bl_pgmres_hb_1_MPI_4 (Failed)^M
        718 - Belos_bl_pgmres_hb_2_MPI_4 (Failed)^M
        719 - Belos_pseudo_pgmres_hb_MPI_4 (Failed)^M
        720 - Belos_bl_fgmres_hb_MPI_4 (Failed)^M
        736 - Belos_gcrodr_hb_MPI_4 (Failed)^M
        738 - Belos_prec_gcrodr_hb_1_MPI_4 (Failed)^M
        784 - Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)^M
        786 - Anasazi_Epetra_OrthoManagerTester_0_MPI_4 (Failed)^M
        787 - Anasazi_Epetra_OrthoManagerTester_1_MPI_4 (Failed)^M
        788 - Anasazi_Epetra_OrthoManagerTester_2_MPI_4 (Failed)^M
        789 - Anasazi_Epetra_OrthoManagerTester_3_MPI_4 (Failed)^M
        790 - Anasazi_Epetra_OrthoManagerTester_4_MPI_4 (Failed)^M
        791 - Anasazi_Epetra_OrthoManagerTester_5_MPI_4 (Failed)^M
        792 - Anasazi_Epetra_OrthoManagerMatTester_0_MPI_4 (Failed)^M
        793 - Anasazi_Epetra_OrthoManagerMatTester_1_MPI_4 (Failed)^M
        794 - Anasazi_Epetra_OrthoManagerMatTester_2_MPI_4 (Failed)^M
        795 - Anasazi_Epetra_OrthoManagerMatTester_3_MPI_4 (Failed)^M
        796 - Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4 (Failed)^M
        797 - Anasazi_Epetra_OrthoManagerMatTester_5_MPI_4 (Failed)^M
        798 - Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 (Failed)^M
        799 - Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)^M
        800 - Anasazi_Epetra_BlockDavidson_solvertest_MPI_4 (Failed)^M
        801 - Anasazi_Epetra_BlockDavidson_test_0_MPI_4 (Failed)^M
        802 - Anasazi_Epetra_BlockDavidson_test_1_MPI_4 (Failed)^M
        803 - Anasazi_Epetra_BlockDavidson_test_2_MPI_4 (Failed)^M
        804 - Anasazi_Epetra_BlockDavidson_test_3_MPI_4 (Failed)^M
        805 - Anasazi_Epetra_BlockDavidson_test_4_MPI_4 (Failed)^M
        806 - Anasazi_Epetra_BlockDavidson_test_5_MPI_4 (Failed)^M
        807 - Anasazi_Epetra_BlockDavidson_test_6_MPI_4 (Failed)^M
        808 - Anasazi_Epetra_BlockDavidson_test_7_MPI_4 (Failed)^M
        809 - Anasazi_Epetra_BlockDavidson_test_8_MPI_4 (Failed)^M
        810 - Anasazi_Epetra_BlockDavidson_auxtest_MPI_4 (Failed)^M
        811 - Anasazi_Epetra_BKS_solvertest_MPI_4 (Failed)^M
        813 - Anasazi_Epetra_BKS_test_1_MPI_4 (Failed)^M
        817 - Anasazi_Epetra_BKS_nh_test_1_MPI_4 (Failed)^M
        818 - Anasazi_Epetra_GeneralizedDavidson_solvertest_MPI_4 (Failed)^M
        821 - Anasazi_Epetra_LOBPCG_solvertest_MPI_4 (Failed)^M
        822 - Anasazi_Epetra_LOBPCG_simpletest_MPI_4 (Failed)^M
        823 - Anasazi_Epetra_LOBPCG_test_MPI_4 (Failed)^M
        824 - Anasazi_Epetra_LOBPCG_auxtest_MPI_4 (Failed)^M
        825 - Anasazi_Epetra_IRTR_test_0_MPI_4 (Failed)^M
        826 - Anasazi_Epetra_IRTR_test_1_MPI_4 (Failed)^M
        827 - Anasazi_Epetra_IRTR_test_2_MPI_4 (Failed)^M
        828 - Anasazi_Epetra_IRTR_test_3_MPI_4 (Failed)^M
        829 - Anasazi_Epetra_IRTR_auxtest_0_MPI_4 (Failed)^M
        830 - Anasazi_Epetra_IRTR_auxtest_1_MPI_4 (Failed)^M
        831 - Anasazi_Epetra_IRTR_auxtest_2_MPI_4 (Failed)^M
        832 - Anasazi_Epetra_IRTR_auxtest_3_MPI_4 (Failed)^M
        833 - Anasazi_Epetra_IRTR_auxtest_4_MPI_4 (Failed)^M
        840 - Anasazi_BlockDavidsonThyra_test_MPI_4 (Failed)^M
        843 - Anasazi_IRTRThyra_test_0_MPI_4 (Failed)^M
        844 - Anasazi_IRTRThyra_test_1_MPI_4 (Failed)^M
        845 - Anasazi_IRTRThyra_test_2_MPI_4 (Failed)^M
        846 - Anasazi_IRTRThyra_test_3_MPI_4 (Failed)^M
        847 - Anasazi_LOBPCGThyra_test_MPI_4 (Failed)^M
        854 - Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4 (Failed)^M
        861 - Ifpack2_Jacobi_hb_belos_MPI_1 (Failed)^M
        862 - Ifpack2_Jacobi_hb_belos_MPI_2 (Failed)^M
        870 - Ifpack2_GS_belos_MPI_1 (Failed)^M
        871 - Ifpack2_SGS_belos_MPI_1 (Failed)^M
        894 - Stratimikos_Thyra_Belos_StatusTest_UnitTests_MPI_1 (Failed)^M
        902 - Stratimikos_Belos_GCRODR_strattest_MPI_4 (Failed)^M
        1229 - Intrepid2_refactor_unit-test_Orientation_Serial_Test_Orientation_TET_MPI_1 (Failed)^M
        1262 - NOX_LOCA_AnasaziJacobianInverse_MPI_1 (Timeout)^M
        1263 - NOX_LOCA_AnasaziNotConverged_MPI_1 (Timeout)^M
        1336 - NOX_LOCA_MultiPointTcubed_MPI_2 (Failed)^M
        1363 - MueLu_UnitTestsEpetra_kokkos_MPI_1 (Failed)^M
        1364 - MueLu_UnitTestsEpetra_kokkos_MPI_4 (Failed)^M
        1365 - MueLu_UnitTestsTpetra_kokkos_MPI_1 (Failed)^M
        1366 - MueLu_UnitTestsTpetra_kokkos_MPI_4 (Failed)^M
        1671 - PanzerAdaptersIOSS_tIOSSConnManager1_MPI_1 (Failed)^M
        1672 - PanzerAdaptersIOSS_tIOSSConnManager2_MPI_2 (Failed)^M
        1673 - PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 (Failed)^M
```

**Comment by crtrott** [comment]
* Shepard Serial
    * No Build Errors
    * Test Output (Matches unpatched develop Trilinos Branch):
```
99% tests passed, 9 tests failed out of 1631

Label Time Summary:
Amesos2          =   6.73 sec (8 tests)
Anasazi          = 103.11 sec (100 tests)
Belos            =  91.13 sec (85 tests)
Ifpack           =  39.53 sec (41 tests)
Ifpack2          =  36.93 sec (34 tests)
Intrepid         = 160.44 sec (153 tests)
Intrepid2        =  46.03 sec (87 tests)
Isorropia        =   3.53 sec (4 tests)
Kokkos           =  43.22 sec (21 tests)
KokkosKernels    =  23.97 sec (4 tests)
ML               =  18.76 sec (16 tests)
MueLu            = 260.45 sec (89 tests)
NOX              = 107.27 sec (92 tests)
Panzer           = 134.67 sec (111 tests)
Phalanx          =  14.35 sec (20 tests)
ROL              = 139.51 sec (63 tests)
Sacado           = 122.85 sec (292 tests)
Stokhos          =  92.74 sec (75 tests)
Stratimikos      =  22.20 sec (23 tests)
Thyra            =  59.81 sec (80 tests)
Tpetra           = 111.20 sec (137 tests)
Xpetra           =  19.48 sec (17 tests)
Zoltan2          =  88.98 sec (88 tests)

Total Test time (real) = 1747.40 sec

The following tests FAILED:
        688 - ML_MLP_Restart_MPI_4 (Failed)
        1261 - NOX_Thyra_Heq_MPI_1 (Failed)
        1319 - MueLu_UnitTestsEpetra_kokkos_MPI_1 (Failed)
        1320 - MueLu_UnitTestsEpetra_kokkos_MPI_4 (Failed)
        1321 - MueLu_UnitTestsTpetra_kokkos_MPI_1 (Failed)
        1322 - MueLu_UnitTestsTpetra_kokkos_MPI_4 (Failed)
        1629 - PanzerAdaptersIOSS_tIOSSConnManager1_MPI_1 (Failed)
        1630 - PanzerAdaptersIOSS_tIOSSConnManager2_MPI_2 (Failed)
        1631 - PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 (Failed)
```

**Comment by crtrott** [comment]
* Shepard Pthreads
    * Build Error in Xpetra and Panzer on unpatched Trilinos Branch
```
In file included from /home/crtrott/TrilinosBuild/Integration/Pthread-Kokkos-Kernels/trilinos-pristine/packages/xpetra/src/Map/Xpetra_MapFactory.hpp(53),
                 from /home/crtrott/TrilinosBuild/Integration/Pthread-Kokkos-Kernels/trilinos-pristine/packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp(69),
                 from /home/crtrott/TrilinosBuild/Integration/Pthread-Kokkos-Kernels/trilinos-pristine/packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.cpp(47):
/home/crtrott/TrilinosBuild/Integration/Pthread-Kokkos-Kernels/trilinos-pristine/packages/xpetra/src/Map/Xpetra_TpetraMap.hpp(534): error: identifier "map_" is undefined
        return map_->getLocalMap();
```

```
/home/crtrott/TrilinosBuild/Integration/Pthread-Kokkos-Kernels/trilinos-pristine/packages/teuchos/core/src/Teuchos_RCP.hpp(288): error: a value of type "const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::Threads::memory_space>> *" cannot be used to initialize an entity of type "const Tpetra::Map<int, int, panzer::TpetraNodeType> *"
    : ptr_(r_ptr.get()), // will not compile if T is not base class of T2
           ^
          detected during:
            instantiation of "Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2> &) [with T=const Tpetra::Map<int, int, panzer::TpetraNodeType>, T2=const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Threads, Kokkos::Threads::memory_space>>]" at line 131 of "/home/crtrott/TrilinosBuild/Integration/Pthread-Kokkos-Kernels/trilinos-pristine/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer_impl.hpp"
            instantiation of "void panzer::Filtered_UniqueGlobalIndexer<LocalOrdinalT, GlobalOrdinalT>::getOwnedAndGhostedNotFilteredIndicator(std::vector<int, std::allocator<int>> &) const [with LocalOrdinalT=int, GlobalOrdinalT=int]" at line 48 of "/home/crtrott/TrilinosBuild/Integration/Pthread-Kokkos-Kernels/trilinos-pristine/packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer.cpp"
```

**Comment by crtrott** [comment]
Running Checkin Test without pushing now and we wait for Andrew to confirm that the stuff works as desired for Ifpack2 changes to be committed later.

**Comment by crtrott** [comment]
Also we probably should  create issues for all of the errors ....

**Comment by ambrad** [comment]
@crtrott, the builds look good. Go ahead and push when you're ready. I'll start my check-script run for Ifpack2 as soon as this snapshot goes in.

**Comment by crtrott** [comment]
Great. I am waiting for my checkin-test run to finish and then will merge.

**Comment by crtrott** [comment]
One failing test from checkin-test same as last time. Known issue see: #1511

```
99% tests passed, 1 tests failed out of 2371

Label Time Summary:
Amesos               =   5.35 sec (14 tests)
Amesos2              =   1.84 sec (8 tests)
Anasazi              =  32.01 sec (71 tests)
AztecOO              =   2.49 sec (17 tests)
Belos                =  30.78 sec (70 tests)
Domi                 =  55.28 sec (125 tests)
Epetra               =  14.20 sec (61 tests)
EpetraExt            =   2.84 sec (10 tests)
FEI                  =  14.01 sec (43 tests)
Galeri               =   1.86 sec (9 tests)
GlobiPack            =   0.68 sec (6 tests)
Ifpack               =  17.33 sec (53 tests)
Ifpack2              =  21.11 sec (34 tests)
Intrepid             = 192.33 sec (152 tests)
Intrepid2            =  23.79 sec (87 tests)
Isorropia            =   1.38 sec (6 tests)
Kokkos               =  55.16 sec (21 tests)
KokkosKernels        =  47.11 sec (4 tests)
ML                   =  13.02 sec (34 tests)
MiniTensor           =   0.21 sec (2 tests)
MueLu                = 258.53 sec (74 tests)
NOX                  =  85.33 sec (106 tests)
OptiPack             =   2.08 sec (5 tests)
Panzer               = 189.02 sec (135 tests)
Phalanx              =   2.90 sec (24 tests)
Pike                 =   0.79 sec (7 tests)
Piro                 =  18.04 sec (12 tests)
ROL                  = 895.52 sec (136 tests)
RTOp                 =   2.55 sec (24 tests)
Rythmos              = 183.92 sec (83 tests)
SEACAS               =   7.77 sec (13 tests)
STK                  =  25.71 sec (12 tests)
Sacado               =  25.85 sec (292 tests)
Shards               =   0.43 sec (4 tests)
ShyLU                =   2.88 sec (5 tests)
Stokhos              =  72.92 sec (75 tests)
Stratimikos          =  29.86 sec (39 tests)
Teko                 =  88.20 sec (19 tests)
Tempus               = 971.35 sec (10 tests)
Teuchos              =  12.91 sec (128 tests)
Thyra                =  13.61 sec (80 tests)
Tpetra               =  24.36 sec (134 tests)
TrilinosCouplings    =  47.50 sec (19 tests)
Triutils             =   0.30 sec (2 tests)
Xpetra               =  28.98 sec (17 tests)
Zoltan2              =  38.75 sec (97 tests)

Total Test time (real) = 3559.96 sec

The following tests FAILED:
        1427 - Teko_testdriver_tpetra_MPI_1 (Failed)
```

**Comment by mhoemmen** [comment]
@crtrott Argh, I can't do everything at once! ;-) 

I haven't had a chance to review yet, as I've been cleaning up some last performance issues with Tpetra::CrsMatrix pack and unpack.  All the failing tests on White distress me, but I know that's not your fault.

**Comment by mhoemmen** [comment]
I assigned #1511 to some Teko developers, in hopes of getting movement.  I would like Teko tests to pass; see #1367 and #1606.

**Comment by aprokop** [comment]
I have a fix MueLu tests (MueLu_UnitTests_kokkos*) but it's not pushed yet.

**Comment by bartlettroscoe** [comment]
As noted in https://github.com/trilinos/Trilinos/issues/1511#issuecomment-328911246, that test is currently passing in the standard post-push CI build.  Please refer to that command (and later comments in that issue) for how to diagnose what is going on.

But since this test is failing on your machine, can you verify that it is also failing without your changes?  You can do that, for example, with:

```
$ cd Trilinos/
$ git checkout 8b060db  # version that passed full CI build this morning
$ cd CHECKIN/
$ ./checkin-test-sems.sh --allow-no-pull --configure
$ source ../cmake/load_sems_dev_env.sh   # must be on bash!
$ cd MPI_RELEASE_DEBUG_SHARED_PT/
$ cd packages/teko/tests/
$ make -j16 Teko_testdriver_tpetra
$ ctest -R Teko_testdriver_tpetra_MPI_1
```

Does that test pass or fail?  If it passes, one of your local commits must be triggering this failure or the failure could be random.  If so, run it again a few times.  If the test never fails, then you can assume that one of your local commits is triggering this failing test.  In which case you can't push or it will break the post-push CI build and break the checkin-test-sems.sh test for everyone else.

**Comment by crtrott** [comment]
As written above: all errors also occur without the snapshot of Kokkos and KokkosKernels. I never push (or now issue a pull request) if new errors are introduced.

**Comment by bartlettroscoe** [comment]
@crtrott,

> As written above: all errors also occur without the snapshot of Kokkos and KokkosKernels. I never push (or now issue a pull request) if new errors are introduced.

Okay, that means that this test must be failing on some machines and passing on others.  This actually makes this a bad CI test.  It passes on the COE RHEL 6 CEE LAN machine ceerws1113 that runs the standard CI build and it passes on my COE RHEL 6 machine crf450.sandia.gov.

What machine does this test fail on in your case?  We should document that in #1511.

In any case, if this test always fails on your machine even when the post-push CI build is clean that is not acceptable.

I will describe my recommendation for addressing this test in #1511.

**Comment by eric-c-cyr** [comment]
Can we see some failing output, is it the same as #1511

**Comment by eric-c-cyr** [comment]
Can someone run the test as a failure (without ctest) with a --verb=10? I think this should provide more output.

**Comment by bartlettroscoe** [comment]
> Can someone run the test as a failure (without ctest) with a --verb=10? I think this should provide more output.

FYI: you can see the exact command that ctest runs for a test using `ctest -N -VV -R "^<test-name>$"`.  From that, you can see how to run it manually.

**Pull request merged**
