### PR TITLE
Belos,Ifpack2,Thyra,Tpetra: Remove use of KOKKOS_ENABLE_DEPRECATED_CODE macro

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/belos @trilinos/ifpack2 @trilinos/thyra @trilinos/tpetra @kddevin 

## Description

Remove use of `KOKKOS_ENABLE_DEPRECATED_CODE` macro.

## Motivation and Context

In all cases I saw, both code paths (with or without the macro defined) now build fine.

### CODE REVIEW

**Comment by kddevin** [comment]
Wow, @mhoemmen , I did not expect you to do this work.  I talked with @ndellingwood after the Tpetra meeting today.  He indicated that the deprecated ON vs OFF code was provided to allow easier testing and let package developers see what was changing.  But he suspected that its removal would not have impact in most cases.  The Kokkos team anticipated removing this code in two Kokkos promotions.  The first promotion would disable Kokkos deprecated code by default; the second would remove the Kokkos deprecated code.

**Comment by kddevin** [comment]
@bartlettroscoe I don't suspect this will impact the ATDM builds, as it is removing the packages' use of features deprecated by **Kokkos**, not by a Trilinos package.  The capabilities provided by Trilinos to ATDM are not changed.

**Comment by mhoemmen** [comment]
@kddevin wrote:
> But he suspected that its removal would not have impact in most cases.

In this particular case, the code builds and has the same functionality, whether or not the macro was defined.  That may not have been true originally, but it's been true for a while.  Thus, removing the macro was harmless.

**Comment by kddevin** [comment]
Right; this was one case @ndellingwood cited as a potential complication:
```
  #ifdef KOKKOS_ENABLE_DEPRECATED_CODE
    if (Kokkos::Cuda::is_initialized ()) {
  #else
    if (Kokkos::Cuda::impl_is_initialized ()) {
  #endif
```
I see you just removed it -- even better.

**Comment by mhoemmen** [comment]
@kddevin wrote:
> I see you just removed it -- even better.

Right -- Kokkos has been discouraging per-execution-space checks for initialization or finalization for a while now.  If `KOKKOS_ENABLE_CUDA` is defined, then `Kokkos::initialize` or `Kokkos::ScopeGuard`'s constructor initialize `Kokkos::Cuda`.

**Comment by mhoemmen** [comment]
The only test that fails is `Ifpack2_BlockTriDiContainerUnitAndPerfTests*`.  It fails with error messages like the following:
```
0. Ifpack2BlockTriDi_double_int_int_Unit_UnitTest ... ScratchMemorySpace<...>::get_shmem: Failed to allocate 1600 byte(s); remaining capacity is 0 byte(s)
ScratchMemorySpace<...>::get_shmem: Failed to allocate 1600 byte(s); remaining capacity is 0 byte(s)
ScratchMemorySpace<...>::get_shmem: Failed to allocate 1600 byte(s); remaining capacity is 0 byte(s)
ScratchMemorySpace<...>::get_shmem: Failed to allocate 1600 byte(s); remaining capacity is 0 byte(s)
ScratchMemorySpace<...>::get_shmem: Failed to allocate 320 byte(s); remaining capacity is 0 byte(s)
ScratchMemorySpace<...>::get_shmem: Failed to allocate 320 byte(s); remaining capacity is 0 byte(s)
ScratchMemorySpace<...>::get_shmem: Failed to allocate 320 byte(s); remaining capacity is 0 byte(s)
ScratchMemorySpace<...>::get_shmem: Failed to allocate 320 byte(s); remaining capacity is 0 byte(s)
```
My changes did touch a "policy" that set the required scratch space.  My guess is that there's something wrong with the "not deprecated code" branch, that PR testing wasn't catching.  We can save that for later; I'll just restore that one change.

**Comment by mhoemmen** [comment]
I wasn't able to replicate the one test failure (in Ifpack2's BlockTriDiContainer) when I switched `KOKKOS_ENABLE_DEPRECATED_CODE` ON and OFF.  I just reverted my changes to the one file (`Ifpack2_BlockTriDiContainer_impl.hpp`) and force-pushed.

I recall @kyungjoo-kim reporting some Kokkos issues relating to the policy interface change.  Let me see if I can find the issue he filed.

**Comment by mhoemmen** [comment]
I think it was this issue: https://github.com/kokkos/kokkos/issues/2037

**Comment by mhoemmen** [comment]
@trilinos/tpetra could someone please review -- thanks!

**Comment by mhoemmen** [comment]
Thanks Karen!

**Pull request merged**
