### PR TITLE
SEACAS: Fix debug build

### PR DESCRIPTION
**Pull request by gsjaardema**
Assert in Conjoin was accessing a variable that had been removed in a recent refactor.  Change assert to use correct value.

Addresses #7331

@trilinos/seacas

### CODE REVIEW

**Comment by gsjaardema** [comment]
That is what I was wondering also.  It should have failed on all debug builds.

**Comment by prwolfe** [comment]
> That is what I was wondering also. It should have failed on all debug builds.

We don't do a debug build. The wait time is enough of an issue as things stand ;-)

**Comment by gsjaardema** [comment]
That answers that question.  Would only fail on a debug build.

**Comment by bartlettroscoe** [comment]
> We don't do a debug build. The wait time is enough of an issue as things stand ;-)

That is not really acceptable for protecting customers.  One of the faster builds needs to be converted to a full debug builds and then perhaps just run the `BASIC` test suite.

**Comment by bartlettroscoe** [comment]
Note: #5184

**Comment by bartlettroscoe** [comment]
For some reason, the PR tester never even started testing this PR in the 17 hours since it was opened.  What is the deal with that?

**Comment by bartlettroscoe** [comment]
FYI: I manually deployed this to the 'atdm-nightly' branch so it will run tomorrow in the ATDM Trilinos nightly builds.

**Pull request merged**
