### PR TITLE
Yaml fixes round 2

### PR DESCRIPTION
**Pull request by ibaned**
@lxmota @bathmatt

### CODE REVIEW

**Comment by ibaned** [comment]
This fixes the `any_cast<Teuchos::PLPair>(operand)` error.
Still working on the acceptance of commas in scalars though...

**Comment by ibaned** [comment]
@bathmatt I got commas to work as well, thats also in this PR

**Comment by bathmatt** [comment]
Testing, will push when it works :)

**Comment by bathmatt** [comment]
@ibaned 
it looks like this push broke the array stuff [ 10, 10]

Example

```
My Awesome Problem:
  Mesh:
    Inline:
      Type: Quad
      Elements: [     10,     10 ]
      Blocks:   [      1,      1 ]
      Start:    [   -1.0,   -1.0 ]
      End:      [    1.0,    1.0 ]
```

**Comment by ibaned** [comment]
@bathmatt it looks like it is coming in as an array, just an array of strings. So it thinks each `10` is a string... definitely a regression though, looking into this before the other stuff.

**Comment by ibaned** [comment]
Okay, found and fixed the regression, that fix is added to this PR.

**Comment by bathmatt** [comment]
Testing....

**Comment by bathmatt** [comment]
Pushed commits. 👍

**Pull request merged**
