### PR TITLE
Ifpack2: Adding unit test for BlockTriDi via the Ifpack2::Factory 

### PR DESCRIPTION
**Pull request by csiefer2**
Tests: RHEL7 (new one added)

Issue: #9200

Stakeholder feedback: n/a

### CODE REVIEW

**Comment by srajama1** [comment]
@csiefer2 I don't see any Amesos2, shylu or Kokkos Kernels changes. I am not sure why that got selected.

**Comment by csiefer2** [comment]
> 
> 
> @csiefer2 I don't see any Amesos2, shylu or Kokkos Kernels changes. I am not sure why that got selected.

Because I forgot to switch the target branch to develop from master when I submitted the PR.

**Review by GrahamBenHarper — APPROVED** [review]
lgtm

**Comment by csiefer2** [comment]
Random shylu failure.  Retesting

**Comment by jhux2** [comment]
@csiefer2 I see what you did there :P.

**Comment by csiefer2** [comment]
Well, seeing I didn't touch any *libraries* upstream of ShyLU, only tests, the only thing left to do is add AT: RETEST and hope the failed test beast doth not resurface!

**Pull request merged**
