### PR TITLE
[WIP] Anasazi: add Factory

### PR DESCRIPTION
**Pull request by aprokop**
@trilinos/anasazi @amklinv @hkthorn 

Adding a factory to return `SolMgr`. This would allow users to skip the if statements themselves.

Current PR concerns:
- [x] I came up with names myself, is there a standard documented list somewhere? Would probably need more alternative names, like "Generalized Davidson", "GENERALIZED_DAVIDSON", and the variants...
- [ ] This will need to be documented somewhere. I can put in doxygen comments, but anything else?
- [x] I have not tried fixing few issues with `std::complex`. Some solver managers cannot be instantiated on them (see below), but maybe that could be fixed?
  For now, adding the guards.
- [x] I'm not sure, does Anasazi require C++11? If it does not, I'll have to remove `auto`.
- [ ] Why do solver take non-const `ParameterList` as input?

### CODE REVIEW

**Comment by aprokop** [comment]
It also seems to me that many solver manager tests in Anasazi could be merged as they mostly differ just in the input decks. So you could envision a single driver to run those tests, reading multiple input decks.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> I have not tried fixing few issues with std::complex. Some solver managers cannot be instantiated on them, but maybe that could be fixed?

I dealt with this for Belos' factory by adding a "RealSolverManager" class, intermediate between SolverManager and the specific solver subclass.  It turns solvers that can't compile for std::complex into run-time stubs.

**Comment by aprokop** [comment]
@mhoemmen I guess that's one way of "fixing" it. I was mostly thinking about whether there is something inherent to specific algorithms that prevents them to work with `complex`, or whether it is just an implementation bug.

**Comment by aprokop** [comment]
So the 3 solver managers that don't work with complex are:
- Generalized Davidson
  It has a proper guard for `std::complex` instantiation
- TraceMin
  It has no guards, and fails to compile. Quick look shows it tries to compare complex with double in few places, and divide by complex. Should the guard be added, or would the algorithm work for complex with minor modifications?
- TraceMin Davidson
  Same issues as with TraceMin as they both use the TraceMinBase solver manager

**Comment by mhoemmen** [comment]
@amklinv Would TraceMin work with complex if the matrix is Hermitian positive definite?

**Comment by amklinv** [comment]
TraceMin/TD should work for Hermitian matrices; it's just a flaw in the implementation.  I say add the guard for now.

**Comment by aprokop** [comment]
@amklinv Thanks, I added the guards.

**Comment by aprokop** [comment]
@amklinv I would still like to resolve the issues mentioned in OP. To do that, I'd like some feedback from you.

**Comment by hkthorn** [comment]
@aprokop What are the remaining issues that you would like feedback on?  I did notice from your original discussion that there was a question about C++11.  Since Anasazi does not use any C++11 in the rest of the code, it doesn't require C++11.

**Comment by aprokop** [comment]
@hkthorn I need feedback on 
- Naming conventions
  So far I have hardcoded names (like TRACE_MIN). Should other variants be allowed, like Trace_Min, TraceMin, TRACEMIN, "TRACE MIN", etc)
- Documentation.
  How would you prefer me to document this?
- API
  Solver managers in Anasazi seem to take in non-const parameter list. Is there a reason for that, or should I try to change them to const versions (a la Ifpack2) ?

I will get rid of `auto` since you are allowed to compile it without C++11.

**Comment by aprokop** [comment]
OK, I got rid of `auto` to make C++11 not required. Can we discuss about naming and documentation?

**Comment by aprokop** [comment]
I added more variants to the names. Essentially, all names are converted to lower case for checking, and allow two variants: one with spaces and one with _ instead of spaces. I think that's sufficient.

**Comment by aprokop** [comment]
OK, I added some documentation. This is ready to merge. I'll run the checkin script and merge it to develop.

**Comment by aprokop** [comment]
Pushed in 025e7dafaad8e6196203c202b0b5e5c6e416a5e0.

**Pull request closed without merging**
