### PR TITLE
ROL Trilinos Sync 09-May-2019

### PR DESCRIPTION
**Pull request by dridzal**
@trilinos/rol 

## Description
Regular merge between the ROL-Trilinos repo and the main Trilinos repo, via a Trilinos fork.

## Motivation and Context
Dynamic optimization (PinT) additions, Fletcher's method, bug fixes, etc.

## How Has This Been Tested?
Trilinos check-in tests, performed in ROL-Trilinos and in the Trilinos fork.

### CODE REVIEW

**Comment by mhoemmen** [comment]
CUDA PR test is currently broken for reasons likely unrelated to Trilinos: #5147.

**Comment by dridzal** [comment]
@mhoemmen , thanks for letting us know.  Most of the PR errors seem to be due to that issue.  We may, however, a few real ones, but it's hard to tell.  Do you know if I need to set the retest label, or if that is automatic?

**Comment by mhoemmen** [comment]
@dridzal You shouldn't have to set the retest label.  The PR tester should revisit all the open PRs.  Once #5147 gets fixed, you might need to wait a while for all the open PRs to get through.

**Comment by prwolfe** [comment]
> @dridzal You shouldn't have to set the retest label. The PR tester should revisit all the open PRs. Once #5147 gets fixed, you might need to wait a while for all the open PRs to get through.

This is not correct. The attester will only run a PR twice in a given configuration (just to keep machines available). If a new commit is pushed or the retest label is applied it will start over.

**Comment by dridzal** [comment]
@prwolfe , so if I want to try again with the **same** code, I should set the retest label?

**Comment by prwolfe** [comment]
> @prwolfe , so if I want to try again with the **same** code, I should set the retest label?

Yep!

**Comment by dridzal** [comment]
Several bugs have been confirmed, and the fixes will be part of a new PR.

**Pull request closed without merging**
