### PR TITLE
Tacho - change hip stream destruction order.

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
## Motivation

hip stream is used when kokkos execution space instances are destroyed. so, the stream should be defalcated afterward. cuda stream does not have this problem even if the stream is deleted first. for consistency, cuda destruction order is also changed.

## Test

Tested on caraway03 with ROCM 5.2

### CODE REVIEW

**Comment by iyamazaki** [comment]
I will double-check, but this looks good to me. Are you filing an issue/question to Kokkos?

**Comment by kyungjoo-kim** [comment]
No. you can post issues for further discussion about Kokkos execution space behavior consistency.

**Comment by jjellio** [comment]
I won't be able to pull and test this on EAS3 today - but it's probably a viable work around. Just need to setup and issue with Kokkos and let them figure out the semantics they want (so it's consistent)

**Comment by kyungjoo-kim** [comment]
The code is tested on caraway03 with ROCM 5.2.

**Comment by kyungjoo-kim** [comment]
BTW, the order to delete streams and kokkos execution space instances should not matter. When a stream is destroyed, it should sync to finalize all submitted jobs. If kokkos execution space instance see that the stream is not valid, then they should not take any actions on the stream and necessary synchronization should happen when the stream is actually destroyed instead of when kokkos execution space instance is destroyed.

**Pull request merged**
