### PR TITLE
Allow to override build date with SOURCE_DATE_EPOCH

### PR DESCRIPTION
**Pull request by bmwiedemann**
Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.

This date call is designed to work with all variants of date.

Also use UTC to be independent of timezone.

As an alternative, the date could be dropped to reduce complexity.

This PR was done while working on reproducible builds for openSUSE.

@trilinos/<teamName>

### CODE REVIEW

**Comment by bmwiedemann** [comment]
@crtrott can you please review this? It seems, you added the date in commit 4dcdead

**Comment by jhux2** [comment]
@bmwiedemann This should probably be opened in the Kokkos project, https://github.com/kokkos/kokkos, since Kokkos is snapshotted into Trilinos.

**Comment by bmwiedemann** [comment]
Forwarded it to https://github.com/kokkos/kokkos/pull/3327

**Comment by william76** [comment]
@bmwiedemann @jhux2 
Can this PR be closed if it's been passed over to Kokkos?

**Comment by jhux2** [comment]
Closing.

**Comment by crtrott** [comment]
We are removing the date. Btw. this wasn't affecting Trilinos anymore since January, since Makefile.kokkos was not used after the 3.0 release.

**Pull request closed without merging**
