### PR TITLE
SEACAS: fix bad commits

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas

## Motivation

Remove uses of the lib::fmt include files in ioss header files that are installed and used by external clients.  Since lib::fmt is used only as an embedded library in the Trilinos instantiation of SEACAS/IOSS, the installed include files cannot reference fmt files.

Also protect the use of the `nc_def_var_fill` function since it only appears in later versions of the netCDF library or in earlier versions that use the netcdf-4 (HDF5) capability.

### CODE REVIEW

**Comment by ikalash** [comment]
I am still getting errors building Trilinos:
```
[ 81%] Building CXX object packages/seacas/libraries/ioss/src/main/CMakeFiles/io_info_lib.dir/volume.C.o
In file included from /home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/main/io_info.C:13:
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h: In instantiation of 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = const Ioss::ZoneConnectivity&]':
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:1795:29:   required from 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; fmt::v9::detail::type <anonymous> = fmt::v9::detail::type::custom_type; T = const Ioss::ZoneConnectivity&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:1919:77:   required from 'constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const Ioss::ZoneConnectivity&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {Ioss::ZoneConnectivity}]'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:1936:31:   required from 'constexpr fmt::v9::format_arg_store<Context, fmt::v9::remove_cvref_t<Args>...> fmt::v9::make_format_args(Args&& ...) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {const Ioss::ZoneConnectivity&}]'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:3314:44:   required from 'void fmt::v9::print(fmt::v9::format_string<T ...>, T&& ...) [with T = {const Ioss::ZoneConnectivity&}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const Ioss::ZoneConnectivity&>]'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/main/io_info.C:311:33:   required from here
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:1775:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1775 |       formattable,
      |       ^~~~~~~~~~~
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h: In instantiation of 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = const Ioss::BoundaryCondition&]':
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:1795:29:   required from 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; fmt::v9::detail::type <anonymous> = fmt::v9::detail::type::custom_type; T = const Ioss::BoundaryCondition&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:1919:77:   required from 'constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const Ioss::BoundaryCondition&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {Ioss::BoundaryCondition}]'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:1936:31:   required from 'constexpr fmt::v9::format_arg_store<Context, fmt::v9::remove_cvref_t<Args>...> fmt::v9::make_format_args(Args&& ...) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {const Ioss::BoundaryCondition&}]'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:3314:44:   required from 'void fmt::v9::print(fmt::v9::format_string<T ...>, T&& ...) [with T = {const Ioss::BoundaryCondition&}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const Ioss::BoundaryCondition&>]'
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/main/io_info.C:329:32:   required from here
/home/ikalash/Trilinos_Albany/nightlyAlbanyTests/Results/Trilinos_GS/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h:1775:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
make[2]: *** [packages/seacas/libraries/ioss/src/main/CMakeFiles/io_info_lib.dir/io_info.C.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [packages/seacas/libraries/ioss/src/main/CMakeFiles/io_info_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 81%] Linking CXX shared library libtpetra.so
[ 81%] Built target tpetra
make: *** [all] Error 2
```
This is with the ```gsjaardema:seacas-fix-bad-commits``` branch.  Hopefully I used the right branch.  Sorry that this is such a pain to fix...

**Comment by gsjaardema** [comment]
It looks like Ioss_ZoneConnectivity.h does need the fmt includes for building with Trilinos, but then they can't be present when being used external.  I guess i need to check more closely how this changed on my latest PR instead of assuming I know what changed...

**Comment by gsjaardema** [comment]
@ikalash One more try...  Sorry for the problems.

**Review by ikalash — APPROVED** [review]
It works now!  Thank you for fixing!

**Pull request merged**
