### PR TITLE
Tpetra: Fix #5647 & #5662

### LINKED ISSUE #5647: Tpetra::CrsMatrix: Add deep-copy constructor that takes RowMatrix
## Enhancement
@trilinos/tpetra 

### Description

Overload CrsMatrix's two-argument "deep copy constructor" (see #532) to take a RowMatrix as the first argument.  If the second argument is `Teuchos::Copy`, make a deep copy.  If it's `Teuchos::View`, attempt to cast the RowMatrix to CrsMatrix.  If the cast succeeds, do a shallow copy of the input CrsMatrix.  If the cast fails, throw.

### Motivation

Code for creating a CrsMatrix deep copy of a RowMatrix reappears often in Trilinos.  See PR #5640 for an example.

### Alternate  solutions

Tpetra developers @kddevin , @brian-kelley, and @GeoffDanielson discussed this in person with me.  We considered a `createCopy` overload like what already exists for MultiVector.  Karen pointed out that all such functions end up just calling a constructor anyway, so there is no value in adding a nonmember function.  Brian observed that the nonmember function might not compile, because CrsMatrix's shallow-copy constructor is currently deleted.  (We say "might" not compile because in C++11, [return value optimization is optional](https://en.cppreference.com/w/cpp/language/copy_elision).  In C++17, it is mandatory.)  We also talked about how CrsMatrix might not correctly implement shallow-copy semantics, due to the cached column Map and row Map MultiVectors that `apply` uses.  (They would need to be stored as RCP of RCP of MultiVector or `shared_ptr` of `shared_ptr` of MultiVector.  See comparable constructs in BlockCrsMatrix.)  We would want to address that in a separate issue.

We also considered a single-argument constructor `CrsMatrix(const RowMatrix&)`, but Karen pointed out that users could easily confuse that deep-copy constructor with the (currently deleted) shallow-copy constructor `CrsMatrix(const CrsMatrix&)`.

### Partial solution

Thanks to @brian-kelley -- this code shows how to build a deep copy of a CrsMatrix from a RowMatrix.  Note that RowMatrix has `isFillComplete` so the resulting CrsMatrix should only be made fillComplete if the input is fillComplete (and has all the Maps that it needs to have: column, domain, and range).
```c++
    {
      // The matrix that Amesos2 will build the preconditioner on must be a Tpetra::Crs matrix.
      // If A_local isn't, then we build one.
      A_local_crs_ = rcp_dynamic_cast<const crs_matrix_type> (A_local);

      if (A_local_crs_.is_null ()) {
        local_ordinal_type numRows = A_local->getNodeNumRows();
        Array<size_t> entriesPerRow(numRows);
        for(local_ordinal_type i = 0; i < numRows; i++)
        {
          entriesPerRow[i] = A_local->getNumEntriesInLocalRow(i);
        }
        RCP<crs_matrix_type> A_local_crs_nc =
          rcp (new crs_matrix_type (A_local->getRowMap (),
                                    A_local->getColMap (),
                                    entriesPerRow()));
        // copy entries into A_local_crs
        Teuchos::Array<local_ordinal_type> indices(A_local->getNodeMaxNumRowEntries());
        Teuchos::Array<scalar_type> values(A_local->getNodeMaxNumRowEntries());
        for(local_ordinal_type i = 0; i < numRows; i++)
        {
          size_t numEntries = 0;
          A_local->getLocalRowCopy(i, indices(), values(), numEntries);
          ArrayView<const local_ordinal_type> indicesInsert(indices.data(), numEntries);
          ArrayView<const scalar_type> valuesInsert(values.data(), numEntries);
          A_local_crs_nc->insertLocalValues(i, indicesInsert, valuesInsert);
        }
        A_local_crs_nc->fillComplete (A_local->getDomainMap (), A_local->getRangeMap ());
        A_local_crs_ = rcp_const_cast<const crs_matrix_type> (A_local_crs_nc);
      }
    }
```

### LINKED ISSUE #5662: Tpetra::CrsMatrixMultiplyOp: Methods overridden from Tpetra::Operator not marked override
## Bug Report
@trilinos/tpetra 

### Description

Methods that `Tpetra::CrsMatrixMatrixOp` overrides from `Tpetra::Operator` are not marked `override`.  This causes build warnings with Mac Clang.

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @trilinos/ifpack2 

Please don't merge this quite yet.  I want to discuss the interface design choice of creating a separate nonmember function `createDeepCopy`, rather than just putting all this in a new CrsMatrix constructor.  I'm really worried about two things:

1. `Tpetra_CrsMatrix_def.hpp` is very long.
2. CrsMatrix has a ton of constructors.  This makes checking instance invariants hard.

My design choice keeps new code out of `Tpetra_CrsMatrix_def.hpp`, and only uses the public interface of CrsMatrix.

I'm inclined to take this change further, and get rid of existing "deep copy" two-argument constructors in CrsMatrix and MultiVector, in favor of overloads of this new nonmember function.  However, I have not done that in this PR.

## Description

1. Fix #5647.  This makes it possible to create a CrsMatrix that is a deep copy of an existing RowMatrix (that isn't already a CrsMatrix).  That pattern shows up often in Ifpack2, so this should help reduce code duplication and improve build times and sizes.

2. Make `Tpetra::CrsMatrix`'s copy and move constructors, and copy and move assignment operators, `=default` instead of `=delete`.  This brings CrsMatrix in line with other Tpetra classes, like CrsGraph and MultiVector.

3. Add ETI (explicit template instantiation) for `Tpetra::CrsGraph` and other classes and functions that are templated on (LocalOrdinal, GlobalOrdinal, Node).  As part of this, fix CrsGraph's ETI macros.  (They depended unnecessarily on Scalar, which was a relic of now-gone templated instance methods.)

4. Fix #5662 (`Tpetra::CrsMatrixMultiplyOp` build warnings).

## Motivation and Context

Reduce code duplication downstream.  Reduce build times.

## Related Issues

* Closes #5647, #5662

### CODE REVIEW

**Comment by mhoemmen** [comment]
The above test failures come from me pushing commits to fix things and add a unit test.  I think it's pretty stable now.

**Comment by mhoemmen** [comment]
The above test failures come from me pushing commits to improve the unit test.

**Comment by mhoemmen** [comment]
Weird; I built with Clang just fine and it passed the test.

**Comment by mhoemmen** [comment]
I took a look at the build errors and think they are actually left over from previously cancelled tests.  @trilinos/framework might find that of interest.

**Comment by mhoemmen** [comment]
Build errors relate to Stokhos' instantiation of `Tpetra::CrsGraph` using the old four-argument macro. With my PR, Stokhos will no longer need to do that (yay! :-D ).
```
packages/stokhos/src/Tpetra_CrsGraph_UQ_PCE_Serial.cpp:53:1: error: macro "TPETRA_CRSGRAPH_INSTANT" passed 4 arguments, but takes just 3
 INSTANTIATE_TPETRA_UQ_PCE(TPETRA_LOCAL_INST_N)
 ^
In file included from packages/stokhos/src/Tpetra_CrsGraph_UQ_PCE_Serial.cpp:45:0:
packages/stokhos/src/Tpetra_CrsGraph_UQ_PCE_Serial.cpp:51:31: error: ‘TPETRA_CRSGRAPH_INSTANT’ does not name a type
   INSTANTIATE_TPETRA_UQ_PCE_N(TPETRA_CRSGRAPH_INSTANT, N)
                               ^
packages/stokhos/src/Stokhos_Tpetra_ETI_Helpers_UQ_PCE_Serial.hpp:47:3: note: in definition of macro ‘INSTANTIATE_UQ_PCE_STORAGE’
   INSTMACRO( Sacado::UQ::PCE<STORAGE>, LO, GO, N )
   ^
packages/stokhos/src/Stokhos_Tpetra_ETI_Helpers_UQ_PCE_Serial.hpp:61:3: note: in expansion of macro ‘INSTANTIATE_UQ_PCE_DS_SLD’
   INSTANTIATE_UQ_PCE_DS_SLD(INSTMACRO, double, int, D, LO, GO, N)
   ^
packages/stokhos/src/Stokhos_Tpetra_ETI_Helpers_UQ_PCE_Serial.hpp:68:3: note: in expansion of macro ‘INSTANTIATE_UQ_PCE_S_D’
   INSTANTIATE_UQ_PCE_S_D(INSTMACRO, DFN_ ## LO ## _ ## GO ## _ ## N, LO, GO, N)
   ^
packages/stokhos/src/Stokhos_Tpetra_ETI_Helpers_UQ_PCE_Serial.hpp:96:3: note: in expansion of macro ‘INSTANTIATE_UQ_PCE_S’
   INSTANTIATE_UQ_PCE_S(INSTMACRO, default_local_ordinal_type, default_global_ordinal_type, N)
   ^
packages/stokhos/src/Tpetra_CrsGraph_UQ_PCE_Serial.cpp:51:3: note: in expansion of macro ‘INSTANTIATE_TPETRA_UQ_PCE_N’
   INSTANTIATE_TPETRA_UQ_PCE_N(TPETRA_CRSGRAPH_INSTANT, N)
   ^
packages/stokhos/src/Stokhos_Tpetra_ETI_Helpers_UQ_PCE_Serial.hpp:102:3: note: in expansion of macro ‘TPETRA_LOCAL_INST_N’
   INSTMACRO(Kokkos_Compat_KokkosSerialWrapperNode)
   ^
packages/stokhos/src/Stokhos_Tpetra_ETI_Helpers_UQ_PCE_Serial.hpp:109:3: note: in expansion of macro ‘INSTANTIATE_TPETRA_UQ_PCE_WRAPPER_NODES’
   INSTANTIATE_TPETRA_UQ_PCE_WRAPPER_NODES(INSTMACRO)            \
   ^
packages/stokhos/src/Tpetra_CrsGraph_UQ_PCE_Serial.cpp:53:1: note: in expansion of macro ‘INSTANTIATE_TPETRA_UQ_PCE’
 INSTANTIATE_TPETRA_UQ_PCE(TPETRA_LOCAL_INST_N)
 ^
```

**Comment by mhoemmen** [comment]
I had deprecated code disabled in my local tests, so I didn't see the build errors.  I fixed them and pushed the fixes.  Let's try this again.

**Comment by tjfulle** [comment]
Sweet!  I prefer nonmember functions over member functions, where possible.  I like :)

**Comment by mhoemmen** [comment]
Thanks @tjfulle ! :-D I'll merge this, but if other folks don't like it, we can always change it back.

**Pull request merged**
