### PR TITLE
Kokkos: fix compilation with complex<float> by adding some static cas…

### PR DESCRIPTION
**Pull request by jthies**
…ts to scalar constants

@trilinos/<teamName>

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
Hi @jthies !  Thanks for the patch! :-D  This should actually go into kokkos-kernels first, but we can handle the details.  It's OK to push to Trilinos first.

https://github.com/kokkos/kokkos-kernels

**Comment by mhoemmen** [comment]
Hi @jthies !  Both kokkos and kokkos-kernels live in separate repos now and are snapshotted into Trilinos.  I will take care of separating out the kokkos and kokkos-kernels parts of the patch.  Here is the kokkos-kernels part:

https://github.com/kokkos/kokkos-kernels/pull/132

**Comment by crtrott** [comment]
Guys wait with the merge of this. This will otherwise get overwritten in short order. I am in the process of doing a master promotion right now. So wait until this is done, then we need to do another spot test and then we can merge this both into kokkos-kernels proper and here.

**Comment by mhoemmen** [comment]
@crtrott No problem!  I haven't yet submitted the Kokkos patch anyway.

@jthies

**Comment by mhoemmen** [comment]
@jthies I have split your Trilinos patch into two separate pull requests for submission to kokkos and kokkos-kernels:

https://github.com/kokkos/kokkos/pull/1285
https://github.com/kokkos/kokkos-kernels/pull/132

**Comment by mhoemmen** [comment]
Thanks @jthies ! :D

**Comment by jthies** [comment]
Hi Mark,

thanks too, I have  student working with Tpetra now, maybe we’ll contribute more in the future. I’ll make separate pull requests next time and put them in a branch.

Jonas

Von: Mark Hoemmen [mailto:notifications@github.com]
Gesendet: Sonntag, 17. Dezember 2017 06:26
An: trilinos/Trilinos
Cc: Thies, Jonas; Mention
Betreff: Re: [trilinos/Trilinos] Kokkos: fix compilation with complex<float> by adding some static cas… (#2077)


Thanks @jthies<https://github.com/jthies> ! :D

**Comment by mhoemmen** [comment]
@jthies Awesome!  Glad to hear that we're getting more contributors! :-D 

Here is the general policy about kokkos and kokkos-kernels contributions.  Each of these two projects has its own repository (https://github.com/kokkos/kokkos and https://github.com/kokkos/kokkos-kernels ).  Just like Trilinos, each of these projects has two main branches: develop and master.  Development happens in the develop branch.  Every so often, the develop branch of each of these projects gets merged into master.  Usually immediately after that, the master branch gets snapshotted into Trilinos.  "Snapshotted" means that the files get copied.  This overwrites any changes made to those files in the Trilinos repository.

This means that if something in kokkos or kokkos-kernels breaks Trilinos or an application that uses Trilinos, it is OK to change those files in Trilinos, via pull request (against Trilinos' develop branch).  However, those changes will be overwritten on the next snapshot.  Thus, it is important also to submit pull requests to kokkos and/or kokkos-kernels too.

If you want to add a new feature to kokkos or kokkos-kernels, best practice is to submit the pull request first to kokkos resp. kokkos-kernels.  The next snapshot will bring in the new feature.

Thanks! :-D

**Pull request merged**
