### PR TITLE
MueLu: extending the interface of LWGraph to give direct access to rowPtrs and entries

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/muelu

## Description
I am simply adding two host / device function that give access to the row pointers and entries from the `Kokkos::StaticCrsGraph`.

## Motivation and Context
Accessing the underlying local data avoid having to use methods that transfer data to host which is not always the right thing to do.

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of #5838
* Composed of 

## How Has This Been Tested?
I did  a local build and things seem OK so far.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by lucbv** [comment]
I am wondering if this point we should just add a method that gives direct access to the `StaticCrsGraph` something like:

```
    //! Return the local graph
    KOKKOS_INLINE_FUNCTION local_graph_type getLocalGraph() const {
      return graph_;
    }
```

@jhux2 @csiefer2 what do you think?

**Comment by jhux2** [comment]
> I am wondering if at this point we should just add a method that gives direct access to the `StaticCrsGraph` something like:

Yes, if you want something else about the graph besides the rowmap and entries.

**Comment by mhoemmen** [comment]
@lucbv I am partial to the `withLocalAccess` style of accessing local data:
```c++
withLocalAccess ([&] (const local_graph_type& lclGraph) { /* ... */ }, gblGraph);
```

**Comment by lucbv** [comment]
Adding a unit test for LWGraph that test the two new methods.

**Comment by lucbv** [comment]
It turns out if you don't commit the source code for the test it does not work that well...

**Pull request merged**
