### PR TITLE
Tpetra: Requested Updates to FEM Assembly

### LINKED ISSUE #2453: Tpetra: FEM Assembly -- Address Issues from PR #2443
@trilinos/tpetra 
@william76

## Motivation and Context
Implement the modifications @mhoemmen requested from the code in PR #2443 

## Add checklist later
- [x] Command line parameters: split dynamic profile from the assembly mode
  - i.e. --with-insert-global-indices-dp --> --with-insert-global-indices  [--with-dynamic-profile | --with-static-profile]
- [x] Nuance header guard macros more
- [x] Teuchos_GlobalMPISession.hpp --> Tpetra_Core.hpp
- [x] Allow only one 'type' to run at a time to keep the timings from getting mangled.
- [x] InsertGlobalIndices_DP (and others) --> Use `const comm_ptr_t&` rather than non-const.
- [x] Tpetra::DefaultPlatform --> Tpetra::getDefaultComm()
- [x] Other notes from #2443 (Add to this list as I see them)

### PR DESCRIPTION
**Pull request by william76**
@trilinos/tpetra

## Description
Addressing requested updates to FEM Assembly from @mhoemmen from PR #2443.

## Motivation and Context

- [x] Command line parameters: split dynamic profile from the assembly mode
  - Algorithm Types (**one** is required):
    - --with-insert-global-indices
    - --with-local-element-loop
    - --with-total-element-loop
  - Static/Dynamic Profile Selector
    - --with-StaticProfile (DEFAULT) 
    - --with-DynamicProfile
- [x] Nuance header guard macros, add `TPETRAEXAMPLES_` prefix.
- [x] Teuchos_GlobalMPISession.hpp --> Tpetra_Core.hpp
- [x] Allow only one 'type' to run at a time to keep the timings from getting confused.
- [x] InsertGlobalIndices_DP (and others) --> Use `const comm_ptr_t&` rather than non-const.
- [x] Tpetra::DefaultPlatform --> Tpetra::getDefaultComm()
- [x] Change parameters to `const comm_ptr_t&` in parameters to executors for each type
rather than non-const version.
- [x] Remove `Tpetra_getDefaultPlatform` from includes
- [x] Replace `Tpetra::DefaultPlatform::getDefaultPlatform().getComm()` with `Tpetra::getDefaultComm()` in `fem_assembly_main.cpp`

## Related Issues
* Closes #2453 

## How Has This Been Tested?
* PR Testing
* GPU on White
* Local workstation

### CODE REVIEW

**Comment by william76** [comment]
@mhoemmen confused...  

Should I make sure Tpetra::finalize() is called every place a premature exit can happen?  I imagine the command line checker dorks this up a bunch since it bails out... or is there something else that needs to be done in Tpetra::initialize() / Tpetra::finalize() to make it smarter?

**Comment by mhoemmen** [comment]
@william76 For now, if you exit from `main` by returning, and you have called `Tpetra::initialize`, then be sure to call `Tpetra::finalize` before returning from `main`.

The long-term solution is #2459.

**Comment by william76** [comment]
Not sure what the intended solution is in #2459... are you putting in some kind of checks in a d'tor to catch the exit and invoke a `Tpetra::finalize()`?

Is there something that needs to be done to the the finite element mesh assembly example code before merging in or are premature exits going to be magically fixed by #2459?

**Comment by william76** [comment]
@mhoemmen Pushed an update to my branch that will catch any premature exits from the command line parser and trigger a `Tpetra::finalize()` to be called prior to exiting out of main.

**Comment by mhoemmen** [comment]
@william76 thumbs-down was an accident :)

**Comment by mhoemmen** [comment]
@william76 Just approved the change; thanks!

**Comment by william76** [comment]
@mhoemmen Odd, Github still thinks the pre-merge inspection is failing.

@allevin What are we missing here?  Does Mark need to go up to the change above and click the "view changes" link to hit the 'approve' button(s)?

**Comment by mhoemmen** [comment]
@william76 I just approved of them EXTRA HARD ;-P let's see what happens

**Comment by allevin** [comment]
@william76 @mhoemmen This is checked by instance 1 of the autotester, which is busy right now testing PR 2461.  When it finishes testing, it will update the status on this PR.  It could be within 20 minutes after the finish testing (depending on if this PR was in its check queue or not).   

To quote Yoda... "Patience you must have my young padawan"

**Comment by william76** [comment]
lol

**Pull request merged**
