### PR TITLE
8541 Panzer: Lazy evaluation of intrepid components

### LINKED ISSUE #8541: Panzer: Lazy construction of BasisValues2 and IntegrationValues2 in workset
## Enhancement
@trilinos/panzer 

This work will make lazy evaluation of intrepid components an option though a specific workset construction method. Further changes are needed to make the update universal across all workset construction methods.

### PR DESCRIPTION
**Pull request by seamill**
@trilinos/panzer

### CODE REVIEW

**Comment by seamill** [comment]
@rppawlo Could you review this?

The changes are backward compatible with Drekar/Charon as far as I can tell (I will admit my build of Charon is suspect). EMPIRE requires a few small updates, but those are set to merge when needed.

Major changes:
- WorksetDescriptor now hashes the 'partitioned' flag and workset_size. This broke some things in Drekar, but the fix for those has already been merged.
- Partitioned worksets can now generate BasisValues2 and IntegrationValues2 on the fly. The non-partitioned worksets still need a few fixes before that can happen, but that will require many changes to Drekar/Charon.
- Orientations are now stored/shared at the workset level using an `OrientationsInterface`. This requires the WorksetFactory to have a valid GlobalIndexer set.

Red Flags:
- There is a bit of confusion in the code as to the difference between an OrientationsInterface and OrientationsContainer. I feel like these can be the same object, but I'm not sure how the OrientationsContainer works.
- Currently both the WorksetContainer (non-partitioned path) and WorksetFactory (partitioned path) require a GlobalIndexer for orientations. I have the fix for this in another branch, but it needs to be cleaned up. Those changes will not be backward compatible between Charon/Drekar/EMPIRE.
- The biggest issue here is that I have a bunch of hooks in the code for when we consolidate the workset construction. This is part of the branch that stalled out a while back. I can start moving chunks of it over, but until everything is consolidated, panzer/worksets will look very confusing.

**Review by rppawlo — DISMISSED** [review]
Looks good to me! Thanks @seamill !

**Review by rppawlo — APPROVED** [review]

**Comment by seamill** [comment]
Thanks @rppawlo, I'll prep the empire guys.

**Comment by rppawlo** [comment]
@seamill - I rebased this PR against Matt's changes and fixed the conflicts so you will need to update your branches.

**Review by rppawlo — APPROVED** [review]

**Review by rppawlo — APPROVED** [review]

**Comment by prwolfe** [comment]
Thanks for removing the auto merge label @rppawlo - and Thanks @allevin for finding this!

**Pull request merged**
