### PR TITLE
Xpetra: Update License and Copyright

### PR DESCRIPTION
**Pull request by ccober6**
Update the License and Copyright files to

 * Reflect NTESS and new contract
 * Utilize SPDX identifiers within files
 * Make copyright and license files consistent across Trilinos packages (i.e., LICENSE and COPYRIGHT)

@trilinos/xpetra

### CODE REVIEW

**Review by mayrmt — DISMISSED** [review]

**Comment by jhux2** [comment]
May be blocked by #13244.

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by cgcgcg** [comment]
@ccober6 Sorry...

**Comment by ccober6** [comment]
@cgcgcg I think I got this cleaned up.  Can I get another review?  :)

**Review by cgcgcg — DISMISSED** [review]

**Comment by ccober6** [comment]
@cgcgcg , I did not see that you patched this also.  :(  Can you re-review?

**Review by cgcgcg — APPROVED** [review]

**Pull request merged**
