### PR TITLE
Tpetra: Possible fix for #2382

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra Possible fix for #2382.
@micahahoward

### CODE REVIEW

**Comment by mhoemmen** [comment]
Passes local Serial-only Tpetra tests.

**Comment by micahahoward** [comment]
@mhoemmen, I pulled the patch, applied it and it appears to fix the error with a CUDA/dbg build of Trilinos (still building however).
When does this make it into the develop branch?  Once it's there I will cherry-pick that commit and deploy it for our Trilinos builds.

**Comment by mhoemmen** [comment]
Thanks all!  I had to stay up late tonight to help get a paper through here that wasn't formatted right, so this won't make it into tonight's nightlies, but it should get in soon.

**Comment by mhoemmen** [comment]
@micahahoward

**Pull request merged**
