### PR TITLE
Framework: Conditionally warn about including header for deprecated package

### PR DESCRIPTION
**Pull request by sebrowne**
If `<packagename>_SHOW_DEPRECATED_WARNINGS` is defined, emit a warning upon inclusion of any package header (used Epetra for an example).

@csiefer2 @cgcgcg @ccober6 what do you think about this approach?  I thought about it after discussing with Matt and came up with this change, which still works around the function and class deprecation flags.

Edit: Tagging @bartlettroscoe as well in case he has any input on any alternative ways to "deprecate a package".

Now here are the states:
`cmake -DTrilinos_ENABLE_Epetra=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_SHOW_DEPRECATED_WARNINGS=ON ..` gives me compile warnings (default)
`cmake -DTrilinos_ENABLE_Epetra=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_SHOW_DEPRECATED_WARNINGS=OFF ..` gives me no warnings or errors
`cmake -DTrilinos_ENABLE_Epetra=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_HIDE_DEPRECATED_CODE=ON ..` gives me configure failures (one cannot even configure Trilinos if hiding deprecated code and Epetra being enabled).

Packages to add deprecation warning to headers
- [x] Amesos
- [x] AztecOO 
- [x] Epetra 
- [x] EpetraExt
- [x] Ifpack
- [x] Intrepid
- [x] Isorropia
- [x] ML
- [x] NewPackage
- [x] Pliris
- [x] PyTrilinos
- [x] ShyLU_DDCore
- [x] ThyraEpetraAdapters
- [x] ThyraEpetraExtAdapters
- [x] Triutils

### CODE REVIEW

**Comment by mdmosby** [comment]
Wile I think this is a workable solution from SIERRA's perspective, I still strongly advocate for deprecating the interface with the `[[deprecated]]` attribute (reasons below). This could be achieved programmatically on the Trilinos side with an LLVM tool. As there is a multi-year package deprecation schedule on the books, this seems like a worthwhile investment and wouldn't be an immediate throw-away tool. Furthermore, deprecation warnings within Trilinos could make it easier to identify and update internal usage of deprecated APIs or packages. Finally, others could make use of this tool to derive a refactoring tool, i.e., refactor user code to the replacement package, or to manage their own API deprecations within Trilinos (e.g., STK). This approach seems to be better for Trilinos users in moving away from the deprecated packages/interfaces.

**Why deprecation attributes are preferred to header-level deprecation**

While there is a single warning per include of deprecated headers, that may be several layers of includes deep and far from usage of the deprecated interface. That distance from warning to actual use makes it difficult to track down, and may induce several false positives due to transitive includes in user code. Past experience suggests that these warnings will be largely ignored, whereas local deprecation warnings/errors are much more likely to be addressed in a timely manner. SIERRA will effectively need to set `-DTrilinos_SHOW_DEPRECATED_WARNINGS=OFF` and depend on teams being aware of the deprecation schedule and take action independently of build status. SIERRA already has a "disable deprecated code" build/test line, so we are probably OK so long as that line is taken into consideration when updating Trilinos.

**Comment by bartlettroscoe** [comment]
I agree with @mdmosby that it is preferrable to deprecate individual classes and functions using `[[deprecated]]` (but that should be done using the macro <PACKAGE_NAME_UC>_DEPRECATED as per [this standard](https://tribitspub.github.io/TriBITS/users_guide/index.html#deprecating-c-c-classes-structs-functions-typdefs-etc), which which needs to be updated to use `[[deprecated]]`).  For this, what you need is a C++-aware tool that can deprecate everything that can be deprecated in a given C++ header file.  But I am wondering if a poor-man's tool in Python might be possible to deprecate 95% of the needed constructs without needing a fully C++-aware tool (e.g. build with LLVM)?  Then a few manual fixes might be needed to fix it up?

I am curious about the requirements for this deprecation?  I don't see those listed anywhere.

**Comment by achauphan** [comment]
Force pushed as the commits adding deprecation warnings to Amesos and AztecOO did not have `TRIBITS_ADD_SHOW_DEPRECATED_WARNINGS_OPTION()` in their package's CMakeList.txt, causing the warnings to not output during configure

**Review by sebrowne — COMMENTED** [review]
Looked at the list of packages and they align correctly.  Looks good to me, but will require a different approver because I did some of the initial work.

**Review by cgcgcg — DISMISSED** [review]
LGTM. I guess if someone is still using the old packages, they will be faced with a deluge of warnings :-)

**Comment by sebrowne** [comment]
Added a RELEASE_NOTES entry, need new review.

**Review by jmlapre — APPROVED** [review]

**Pull request merged**
