### PR TITLE
SEACAS:  Use pragma once instead of include guards.

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas 

## Motivation

Separated out this change into a single PR to avoid the next seacas snapshot being too full of miscellaneous changes to be able to review cleanly.  This PR is only pragma changes.

### CODE REVIEW

**Comment by gsjaardema** [comment]
@prwolfe @alanw0  Would it be possible for one of you to give a quick review of this.  Minor changes -- just remove include guards and replace with `#pragma once`.  There will be more changes coming later, but this makes later snapshots smaller and easier to review.

This one finally made it through the regression tester...

**Review by alanw0 — APPROVED** [review]

**Comment by gsjaardema** [comment]
@alanw0 Thanks.

**Comment by alanw0** [comment]
> @alanw0 Thanks.

No problem. I'll be interested to see how that goes. We've considered using pragma once in stk, but haven't yet. After some reading, we weren't convinced that it was standard, maybe not guaranteed to be portable, etc. Although I know pretty much all compilers (or pre processors) are supporting it. It does seem cleaner than include-guards.

**Comment by gsjaardema** [comment]
@jwillenbring It looked like Autotester finished all tests correctly, but it is now retesting.  Not sure what is going on, but I know you've been having some issues with the autotester...

**Comment by jwillenbring** [comment]
@gsjaardema My mistake. I put a retest flag on it because I didn't see this had completed the testing since we fixed it late last night. I got the flag in there in the time between when the tests passed and the autotester swept past this PR again to see the tests had passed. In any case, the testing went again and this was automerged. Sorry for the confusion.

**Comment by gsjaardema** [comment]
@jwillenbring No problem. Just checking.  Thanks for explanation.

**Pull request merged**
