### PR TITLE
Teuchos: Remove Deprecated Code

### PR DESCRIPTION
**Pull request by jeforster**
@trilinos/teuchos

## Motivation
Removes several deprecated calls from the Teuchos package.  Here is a full list of everything that is removed by this PR:

- PerformanceMonitorBase::clearTimers method
- count() method in ArrayRCP, RCP, RCPNode Mitigation: Use strong count() methods
- LAPACK::POSVX, LAPACK::GESVX methods that take EQUED by value Mitigation: Pass pointer to EQUED.
- LAPACK::TREXC method that takes ifst and ilst by value Mitigation: Pass pointers to ifst and ilst.
- LAPACK::GEBAL method that takes ilo and ihi by value Mitigation: Pass pointers to ilo and ihi.
- ArrayArg class that creates an array of arguments Mitigation: Pass individual arguments to functions
- MPITraits class
- Operator overload of << in SerialDenseMatrix, SerialBandDenseMatrix, SerialSymDenseMatrix, SerialDenseVector
- Teuchos::Comm helpers reduceAll and scan that take pointers to return argument

## Related Issues

* Part of #6655 

## Testing
Configured Built and Tested using ATDM scripts on the cee-lan

```bash
mkdir -p $TRILINOS_DIR/build
cd $TRILINOS_DIR/build

source $TRILINOS_DIR/cmake/std/atdm/load-env.sh default

cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_MueLu=ON \
  -DTrilinos_ENABLE_Belos=ON \
  -DTrilinos_ENABLE_Teuchos=ON \
  -DTrilinos_ENABLE_Panzer=ON \
  -DTrilinos_ENABLE_STK=ON \
  -DTrilinos_ENABLE_Percept=ON \
  -DTrilinos_ENABLE_Intrepid=ON \
  $TRILINOS_DIR

make NP=16

ctest -j16
```

### CODE REVIEW

**Comment by kddevin** [comment]
@bartlettroscoe  It appears only the tests with the deprecated prototypes were removed from Teuchos_LAPACK.cpp, not the entire test.  Tests with the remaining prototypes remain in the file, and Techos_LAPACK.cpp remains in the testing environment.

**Comment by jeforster** [comment]
> @jeforster, what replaces the testing provided by teuchos/numeris/src/Teuchos_LAPACK.cpp? What is the coverage of the LAPACK wrappers without this test?

@bartlettroscoe I'm not sure what you mean.  I didn't remove any tests.  I just deleted the deprecated methods in that file which none of the tests were using.

**Comment by mhoemmen** [comment]
@trilinos/teuchos

**Comment by bartlettroscoe** [comment]
@kddevin, no @trilinos/teuchos developers were actually given a chance to do a detailed review before this PR was merged.  (I was planning on doing that tonight.)

**Pull request merged**
