### PR TITLE
ShyLU: Make `DebugManager` take a user's comm in constructor

### PR DESCRIPTION
**Pull request by JacobDomagala**
@trilinos/shylu 

This PR is part of the initiative to phase out the use of MPI_COMM_WORLD in Trilinos.

### CODE REVIEW

**Comment by ndellingwood** [comment]
@iyamazaki would you be able to review these changes to shylu_dd?

**Comment by jwillenbring** [comment]
> @iyamazaki would you be able to review these changes to shylu_dd?

Alternatively, @iyamazaki could you suggest someone else who could review this?

**Comment by jwillenbring** [comment]
@srajama1 Can you review this or suggest someone who can? We are trying to get all of these done by the end of the month. Thanks.

**Comment by cgcgcg** [comment]
ping @iyamazaki @ndellingwood @srajama1

**Comment by iyamazaki** [comment]
I am very sorry for missing this, but it looks like this file is not being used anymore, and it might be better if we just remove it, @ndellingwood?

**Comment by JacobDomagala** [comment]
File removed ✔️

**Review by iyamazaki — APPROVED** [review]
Thank you, @JacobDomagala. These look good to me!

**Pull request merged**
