### PR TITLE
SEACAS: Remove locale setting

### PR DESCRIPTION
**Pull request by gsjaardema**
The locale setting is affecting `stringstream` and causing it to always output thousand-seperated numbers which breaks several things.  Removing this until can determine the correct way to provide thousands-separated integers where desired, but not elsewhere.

@trilinos/<teamName>

### CODE REVIEW

**Comment by bathmatt** [comment]
EMPIRE cares @bartlettroscoe testing now

**Comment by gsjaardema** [comment]
@bartlettroscoe I will add some tests later once I figure out how best to do this.  For now backing out this change to get other code groups working again.

**Comment by bathmatt** [comment]
```
[69/69] Linking CXX executable src/EMPIRE.exe
(DESKTOP)-dir-emp-only [GNU-7.2.0]$ 35 $ ctest -j 22 -R Qui
Test project /home/mbetten/Trilinos/EMPIRE/emp-only
    Start 301: EMPIRE:Regression:SourceCurrentQuiescentFriedman-serial
    Start 302: EMPIRE:Regression:SourceCurrentQuiescentFriedman-MPI4
1/2 Test #301: EMPIRE:Regression:SourceCurrentQuiescentFriedman-serial ...   Passed    4.67 sec
2/2 Test #302: EMPIRE:Regression:SourceCurrentQuiescentFriedman-MPI4 .....   Passed    4.66 sec

```

**Comment by bartlettroscoe** [comment]
>  I will add some tests later once I figure out how best to do this. For now backing out this change to get other code groups working again.

Okay.  Just want to make sure important functionality has strong testing in Trilinos so we can well support customers going forward.

**Pull request merged**
