### PR TITLE
shylu_hts: comment out 'unused' variable in .cpp

### PR DESCRIPTION
**Pull request by ndellingwood**
This commit addresses Trilinos issue #2280, warning-as-error causes by
the 'usused' variable

Commented out 'unused' variable causing warning-as-error reported by issue #2280

@trilinos/shylu 

## Description

Commented out static int 'unused' variable in shylu_hts.cpp

## Motivation and Context

Address issue #2280 

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## How Has This Been Tested?

Autotester will test

### CODE REVIEW

**Comment by ndellingwood** [comment]
@ambrad added you as reviewer since since I made the 1-line change in your code - comment out an 'unused' variable causing a 'warning-as-error' issue reported in issue #2280

**Comment by ndellingwood** [comment]
@ambrad 

> At one time I thought all Trilinos subpackages required a symbol in a translation unit to build

I'm not sure if the configuration changed or not as far as requiring this, should I wait to merge in the PR before verifying?

**Comment by ambrad** [comment]
Have you built it locally and run the HTS unit test?

**Comment by ambrad** [comment]
Perhaps see packages/shylu/shylu_node/fastilu/src/shylu_dummyutil.cpp, which is another way it appears the build issue is handled.

**Comment by ndellingwood** [comment]
@ambrad the hts unit test built with the line commented out. How long is the test supposed to run? It seemed to hang when built with/without the commented line.
I built with sems-gcc/5.3.0, enabled hts, kokkos, kokkos-kernels and the OpenMP backend. I can provide more info if necessary.

**Comment by ambrad** [comment]
What is your OMP_NUM_THREADS setting? If unspecified, it might be defaulting to something large.

**Comment by ndellingwood** [comment]
@ambrad I had just ran `ctest` when I posted earlier so you're right about defaulting to large num threads, rerunning after setting OMP_NUM_THREADS resolved it, 
```
[ndellin@kokkos-dev test]$ OMP_NUM_THREADS=2 ./hts_test.exe
HTS Test: Passed
```

**Comment by ambrad** [comment]
Thanks @ndellingwood!

**Pull request merged**
