### PR TITLE
PyTrilinos: Set up a CI driver for testing PyTrilinos

### PR DESCRIPTION
**Pull request by wfspotz**
@trilinos/pytrilinos 

@bartlettroscoe 

## Description

First attempt at setting up a CI driver for PyTrilinos on my Mac Pro Gaia

## Motivation and Context

Provide first nightly testing of PyTrilinos, and apparently first Mac for Trilinos CI testing

## Related Issues

* Part of #891 

## How Has This Been Tested?

Not ready for testing yet. Pull request is to facilitate collaboration

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by wfspotz** [comment]
@bartlettroscoe What is the difference between a CI server and a nightly test driver?

**Comment by bartlettroscoe** [comment]
@wfspotz,

A CI server runs throughout the day and reruns whenever new commits are pushed.  A nightly build runs just once a day.  The former has extra logic the the latter does not need or want.

**Comment by bartlettroscoe** [comment]
@wfspotz, this has passed testing should be ready to merge.  Do you want to merged it?

**Comment by wfspotz** [comment]
Sure. All I did was create a new CI directory, copy some scripts from the sems_ci directory, change their names and change the corresponding file names within those scripts. They are not doing anything new, but they are a starting point.

**Comment by wfspotz** [comment]
@bartlettroscoe My desktop Mac Pro is from a previous project, and it is severely under-utilized. I am open to it becoming a CI server, especially since there isn't a Mac currently in circulation.

**Comment by wfspotz** [comment]
@bartlettroscoe Which script are you referring to?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Which script are you referring to?

@wfspotz,

The crontab entry I used to drive the CI server on my CEE LAN machine is:

```
  0  4  *  *  *  cd /scratch/rabartl/Trilinos.base/SEMSCIBuild && cp trilinos_ci_server.out trilinos_ci_server.last.out && ./Trilinos/cmake/ctest/drivers/sems_ci/trilinos_ci_sever.sh &> trilinos_ci_server.out
```

**Comment by wfspotz** [comment]
@bartlettroscoe How do you test your setup? It seems like I want to run `single_ci_iter.sh`, but it just reports that

    NEW_COMMITS =''

and exits.

**Comment by bartlettroscoe** [comment]
@wfspotz said:

> How do you test your setup?

You can set the env var `CI_FIRST_ITERATION=1` like with:

```
env CI_FIRST_ITERATION=1 <some-base-path>/single_ci_iter.sh
```

To test your local repo, make sure and run it like:

```
$ env \
     CI_FIRST_ITERATION=1 \
     CTEST_TEST_TYPE=Experimental \
     CTEST_DO_SUBMIT=OFF \
     CTEST_DO_UPDATES=OFF \
     CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=TRUE \
  <some-base-path>/single_ci_iter.sh
```

as hinted at in step 5 "Test CTest -S driver scripts":

* https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-submit-testing-results-to-a-cdash-site

Let me know if that does not work.

You can turn on or off various actions by setting the vars described at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#determining-what-testing-related-actions-are-performed-tribits-ctest-driver

**Pull request merged**
