### PR TITLE
Tempus: integrator getXDot name change

### PR DESCRIPTION
**Pull request by sconde**
@trilinos/tempus 

## Motivation

To get the method name in integrator consistent with the naming from the solutionstat - fix capitalization.

### CODE REVIEW

**Review by ccober6 — DISMISSED** [review]
Looks good!  Thanks for fixing this.

**Comment by sconde** [comment]
@ccober6 Made changes need in ROL.

**Review by ccober6 — DISMISSED** [review]
Looks good!

**Review by ccober6 — APPROVED** [review]
Looks good!

**Pull request merged**
