### PR TITLE
Framework: Setup PR build for Clang 11.0.1

### PR DESCRIPTION
**Pull request by ZUUL42**
@trilinos/framework

## Motivation

Setup a new build that uses Clang 11.0.1.
This is setup for the current PR system. It will need to be migrated to the new MM system.

## Testing

- Test ran through with one failing test: Zoltan_ch_simple_parmetis_parallel
  In the following commit, I disabled that test. @trilinos/zoltan
- There were also 11 tests that _were_ disabled in the Clang 7, 9, & 10 builds. I removed those test disables to determine their current status. It appears they will run successfully now. So, those disables have been left out of this build. See commit 131b4b04fc2c79cfad33fa64b7456365d118db10.

[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=clang11&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2022-05-14)

### CODE REVIEW

**Review by jwillenbring — DISMISSED** [review]
Looks good. Nice find that you could turn those 11 tests back on.

**Review by e10harvey — DISMISSED** [review]
Please add this to GenConfig.

**Comment by bartlettroscoe** [comment]
FYI: This PR and other PRs that happen to enable ShyLU_Node will never pass the intel-19.0.5 build and be allowed to merge until #10549 is addressed.

**Comment by ZUUL42** [comment]
Removed Automerge flag so that deployment can be discussed.

**Comment by ZUUL42** [comment]
@jwillenbring [the latest run built clean](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-clang11-test-Trilinos_pullrequest_clang_11.0.1-12&field3=buildstamp&compare3=61&value3=20220517-1950-Experimental) ... but that was on Friday.
I can make the change in the cfg now or so one more test run and make the change directly after that, just to be sure.

**Comment by ZUUL42** [comment]
To recheck, the last build on May 17 was successful, but I just started another build to be sure.
All builds against the current SHA can be found here: [CDash query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-clang11-test-Trilinos_pullrequest_clang_11.0.1&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2022-05-17)

**Review by jwillenbring — APPROVED** [review]
Looks good.

**Comment by ZUUL42** [comment]
PR no longer needed with changes moving such content.
Content will be useful for migrating to the new system though.
But this can be closed so it isn't unnecessarily merged.

**Pull request closed without merging**
