### PR TITLE
Kokkos + KokkosKernels Promotion To 4.2.1

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos @trilinos/kokkos-kernels 

## Motivation

Patch release snapshot of Kokkos Ecosystem 4.2.1 to Trilinos

## Testing
AT

### CODE REVIEW

**Comment by ndellingwood** [comment]
Adding @crtrott @lucbv @srajama1 @dalg24 @masterleinad for tracking

**Comment by ndellingwood** [comment]
The ` PR-12707-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp...` test failed due to compiler running out of memory:
```
Error building packages/intrepid2/unit-test/Projection/CMakeFiles/Intrepid2_unit-test_Projection_test_convergence_WEDGE_Serial_DOUBLE.dir/test_convergence_WEDGE_Serial_DOUBLE.cpp.o 
...
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```

Retesting

@trilinos/framework @sebrowne is there a preferred way to document occurrences like compiler out of memory issues to track frequency etc. in case the build parallelism needs to be throttled down?

**Review by dalg24 — APPROVED** [review]
Kokkos' changes look good

**Review by masterleinad — APPROVED** [review]

**Comment by ndellingwood** [comment]
Most recent run failures:

* On ascic166:  PR-12707-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-3609 looks like it failed due to the machine running out of space, for example in the first listed test failure `MueLu_CreateOperatorTpetra_MPI_1`
```
...
sed: couldn't flush kokkos/Output/sedCF1zhZ: No space left on device
```

* On ascic166: PR-12707-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-2098 failed to post any test results to cdash

@trilinos/framework @sebrowne  can someone help with the out of space issues? Both failures in this most recent case were on ascic166

**Review by crtrott — APPROVED** [review]

**Comment by sebrowne** [comment]
@ndellingwood I checked the disk on that machine, and it looked okay to me.  Checked the one that ran out this time (same issue) and it still looks okay as well.  Something is odd here.  I will look into it further to see if I can figure out what is running the machines out of space (if not this build/PR, which seems highly unlikely given that we have over 800GB free).

**Comment by ndellingwood** [comment]
@sebrowne the ` PR-12707-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-3615` job failed again with compiler crash (out of memory most likely):

[Error building packages/intrepid2/unit-test/Orientation/CMakeFiles/Intrepid2_unit-test_Orientation_test_orientation_HEX_newBasis_Serial_DOUBLE.dir/test_orientation_HEX_newBasis_Serial_DOUBLE.cpp.o](https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=1372095#)
```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```

The  `PR-12707-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-2104` job made it to the unit tests and failed in the [TrilinosInstallTests_reduced_tarball](https://trilinos-cdash.sandia.gov/test/46187844) test, apparently due to timeout though I don't expect that to be related to changes in this PR?

**Comment by sebrowne** [comment]
@ndellingwood I agree that the reduced tarball test timeout is unlikely to have been directly caused by this PR.  I will look into what the disk logs show later today.  Apologies for the long cycle time on this.

**Comment by ndellingwood** [comment]
Thanks for looking into this @sebrowne !

**Comment by ndellingwood** [comment]
Hi @sebrowne , any updates on the CI issues we are seeing with this PR? Should I attempt another retest?

**Comment by sebrowne** [comment]
For some reason I don't have the logging data from the machine that was showing the apparent issues.  I'm working with the service group to see what I can figure out.  In the meantime, removed it from the rotation and RETESTing.

**Comment by sebrowne** [comment]
@ndellingwood I'll be honest, I'm very shy about this PR.  The GCC + OpenMP build ran out of space again on a different machine.  That build has run out of space on several machines now.  Granted, what is most likely happening is a machine configuration problem somewhere behind the scenes, and that build happens to be the one that needs the most space, so it may just be highlighting the real issue.  I'm working on this as best I can right now and seeing if I can diagnose where the space is going.  I see the disk go from ~15% to 100% over about 5 hours this morning, but I can't yet figure out exactly what was running there.

**Comment by ndellingwood** [comment]
@sebrowne thanks for continuing to investigate

**Comment by ndellingwood** [comment]
Any final objections before merge?

**Comment by sebrowne** [comment]
@ndellingwood I think we can put it in from a system perspective, but if the out-of-space starts becoming systemic across other PRs, I think we should be prepared to revert (as undesirable as that is)

**Comment by ndellingwood** [comment]
@sebrowne sounds good, thanks for monitoring.
The changes here should not have had an impact on the compiler crashes or space issues, is it possible that multiple jobs hit the same node and/or the build level parallelism may be too high in the case of PRs with changes to e.g. kokkos that trigger testing with most of the downstream packages? One way to monitor/test could be to put in a dummy PR unintended for merge and make a single line change to kokkos (e.g. a new line in a header) and see if the issues occur

**Pull request merged**
