### PR TITLE
Teuchos: move SetScientific to Core

### PR DESCRIPTION
**Pull request by ibaned**
@trilinos/teuchos 
@trilinos/tpetra 
@trilinos/belos 
@trilinos/anasazi
@CamelliaDPG 

## Description

This functionality to set the precision
of a C++ stream such no losses are
incurred for floating point values,
and a convenient scope guard for it,
seem general enough to be take out of
the MatrixMarket sub-package.
Anecdotally, I have an application that
wants to use this, but it seems excessive
to require it to depend on MatrixMarket.

Although I left a backward-compatibility
header in the code, I did take the liberty
of updating the usage of this class in the
following packages:
 - Anasazi
 - Belos
 - Tpetra

## Motivation and Context

This is motivated by the desire to use this class in a lightweight application without depending on the `MatrixMarket` subpackage. It also makes sense from a design perspective, since dealing with floating point formatting to a stream is useful for more than just matrix data structures.

## How Has This Been Tested?
A small subset of Trilinos was compiled as a spot check (only up to Tpetra). Will rely on automatic PR testing.

### CODE REVIEW

**Comment by ibaned** [comment]
@jwillenbring okay, this time the check failed. what is the Jenkins link where I can see why it failed?

**Comment by jwillenbring** [comment]
@ibaned I was just looking at that. We need to consider if we need to get people access, or just wait until we convert to the new CDash. Anyway, the GCC 4.8.4 build failure was:

In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/numerics/src/Teuchos_MatrixMarket_Raw_Writer.hpp:45:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/numerics/test/MatrixMarket/MatrixMarket_Raw_InOutTest.cpp:44:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_SetScientific.hpp:90:3: error: expected unqualified-id before ‘{’ token
   {
   ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_SetScientific.hpp: In constructor ‘Teuchos::SetScientific<Scalar, true>::SetScientific(std::ostream&, int)’:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_SetScientific.hpp:89:39: error: expected ‘{’ at end of input
     originalPrecision_(out.precision());
                                       ^

**Comment by ibaned** [comment]
@jwillenbring thanks! I just edited your comment to put the error message in a monospace code box. I'll see if I can figure out a fix.

**Comment by ibaned** [comment]
My bad... I had fixed this compilation error during my spot check but not commited and pushed. I think by pushing a new commit I should trigger a restart of the auto-tester.

**Comment by jwillenbring** [comment]
>  I think by pushing a new commit I should trigger a restart of the auto-tester.

That is correct, mostly. More accurately the next time the auto-tester runs, it will test this PR again.

**Comment by allevin** [comment]
@ibaned We will be making a change soon to reduce the footprint of the "Starting" "Passed" and "Failed messages.  The data will all still be there but will require a mouse click to expand the message to see the details.

**Comment by ibaned** [comment]
@allevin I would welcome that, thank you!

**Comment by bartlettroscoe** [comment]
> We need to consider if we need to get people access, or just wait until we convert to the new CDash. Anyway, the GCC 4.8.4 build failure was:

You don't need to wait to convert to the new CDash.  You can post to the current CDash right now without having to do package-by-package builds.  I can show you how to do that.

**Comment by ibaned** [comment]
Hmm, there is another failure. It definitely seems unfair to the Framework team if they have to constantly respond to requests for error messages. Ideally, the system should post some extracted error text as a comment in the pull request. For now, could I please have access to see the jenkins output?

**Comment by allevin** [comment]
@ibaned Unfortunately, I also don't have access to the jenkins build output. 

@jwillenbring and I discussed this as a priority.  Figuring out how to extract the information is a bit of a pickle as I understand it.  @bartlettroscoe mentioned that he can help us out with the current CDash.  This may be a step towards a resolution to this problem.

**Comment by jwillenbring** [comment]
GCC 4.8.4

[ 88%] Building CXX object packages/tempus/test/BDF2/CMakeFiles/Tempus_BDF2.dir/Tempus_BDF2Test.cpp.o
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp: In function ‘void Tempus_Test::test_sincos_fsa(bool, bool, Teuchos::FancyOStream&, bool&)’:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:285:15: error: ‘DefaultMultiVectorProductVector’ in namespace ‘Thyra’ does not name a type
       typedef Thyra::DefaultMultiVectorProductVector<double> DMVPV;
               ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:295:19: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
         RCP<const DMVPV> x_prod_plot =
                   ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:295:24: error: template argument 1 is invalid
         RCP<const DMVPV> x_prod_plot =
                        ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:295:38: error: invalid type in declaration before ‘=’ token
         RCP<const DMVPV> x_prod_plot =
                                      ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:296:43: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
           Teuchos::rcp_dynamic_cast<const DMVPV>(solutionState->getX());
                                           ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:296:20: error: parse error in template argument list
           Teuchos::rcp_dynamic_cast<const DMVPV>(solutionState->getX());
                    ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:296:71: error: no matching function for call to ‘rcp_dynamic_cast(Teuchos::RCP<const Thyra::VectorBase<double> >)’
           Teuchos::rcp_dynamic_cast<const DMVPV>(solutionState->getX());
                                                                       ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:296:71: note: candidate is:
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_FancyOStream.hpp:45:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_Describable.hpp:46,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestBase.hpp:51,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestHarness.hpp:51,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:9:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp:763:1: note: template<class T2, class T1> Teuchos::RCP<T1> Teuchos::rcp_dynamic_cast(const Teuchos::RCP<T2>&, bool)
 Teuchos::rcp_dynamic_cast(const RCP<T1>& p1, bool throw_on_fail)
 ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp:763:1: note:   template argument deduction/substitution failed:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:296:71: error: template argument 1 is invalid
           Teuchos::rcp_dynamic_cast<const DMVPV>(solutionState->getX());
                                                                       ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:298:22: error: base operand of ‘->’ is not a pointer
           x_prod_plot->getMultiVector()->col(0);
                      ^
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/tempus/test/BDF2/Tempus_BDF2Test.cpp:300:22: error: base operand of ‘->’ is not a pointer
           x_prod_plot->getMultiVector()->subView(Teuchos::Range1D(1,num_param));
                      ^
[ 88%] Building CXX object packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_ReorderBlockAFactory.cpp.o
make[2]: *** [packages/tempus/test/BDF2/CMakeFiles/Tempus_BDF2.dir/Tempus_BDF2Test.cpp.o] Error 1
make[1]: *** [packages/tempus/test/BDF2/CMakeFiles/Tempus_BDF2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by jwillenbring** [comment]
GCC 4.9.3

 41%] Building CXX object packages/phalanx/example/FiniteElementAssembly/CMakeFiles/Phalanx_example_finite_element_assembly.dir/evaluators/Constant.cpp.o
In file included from /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi.h:253:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/teuchos/core/src/Teuchos_Time.hpp:56,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/teuchos/comm/src/Teuchos_TimeMonitor.hpp:70,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/teuchos/comm/src/Teuchos_CommUtilities.hpp:45,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/teuchos/comm/src/Teuchos_CommHelpers.hpp:46,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp:47,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:1260,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/sacado/src/Kokkos_View_Fad.hpp:33,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp:6,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/phalanx/test/EvaluatorUnitTester/EvaluatorUnitTester.cpp:44:
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi_portable_platform.h:374:34: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                  ^
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.6.5/include/mpi_portable_platform.h:374:63: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                                               ^

**Comment by ibaned** [comment]
@jwillenbring @bartlettroscoe I don't think that failure is due to my changes, I think it was caused by the merge of #1990 by @ccober6 which did not use the checkin script or automated PR testing.

**Comment by bartlettroscoe** [comment]
>  I don't think that failure is due to my changes, I think it was caused by the merge of #1990 by @ccober6 which did not use the checkin script or automated PR testing.

Yup, it broke the CI build:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3225262

Can someone please back out that bad merge?

**Comment by ibaned** [comment]
@jwillenbring is there a way to trigger another auto-test since recent fixes to the develop branch will improve the outcome?

**Comment by allevin** [comment]
@ibaned The autotester looks at the status check flag "Pull Request AutoTester" above (which is tied to the latest commit).  Since the Flag is set to failed, and there is only 1 run allowed it will not normally retest. 

@jwillenbring and I need to discuss the possibility of allowing multiple attempts of re-testing for cases like this.  

Since this is a special case of the failure due to a previous checkin, it makes no sense for you to perform another commit.  I will manually reset the status flag this should reset the system for testing.

**Comment by jwillenbring** [comment]
@bartlettroscoe @hkthorn @mhoemmen Would one of you be willing to review these changes for @ibaned? The PR testing has now passed.

**Comment by ibaned** [comment]
Thanks @mhoemmen !
Merging...

**Pull request merged**
