### PR TITLE
Revert "Issue4258 remove teuchos sdmatrix inheritance"

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @trilinos/teuchos 

Reverts trilinos/Trilinos#4259

Need to revert as per #4330.  Someone needs to create a new issue to make these changes that preserve the existing `operator<<()` function.

### CODE REVIEW

**Comment by jwillenbring** [comment]
Although the  Intel License server is down, because this PR is 

1) ATDM critical
and
2) a revert of a commit, not introducing new functionality

and we don't have an ETA for the Intel license server coming up, we are going to attempt to carefully guide this PR through testings while general testing is down. That is why I applied the retest flag.

**Comment by bartlettroscoe** [comment]
@trilinos/framework, why is this PR not getting tested again?  I put the label `AT: RETEST` on this PR almost 24 hours.

It would be great to get this merged since our SPARC 'master' + Trilinos 'develop' testing is completely dead in the water until this gets merged (see http://compsim-dashboard.sandia.gov/cdash/index.php?project=SPARC&date=2019-02-08&filtercombine=and&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Trilinos%20Integration).

**Comment by bartlettroscoe** [comment]
@trilinos/framework, can someone please manually merge this PR?  It passed all of the builds on the first testing iteration shown [above](https://github.com/trilinos/Trilinos/pull/4336#issuecomment-461234824) except for the Intel build which failed due to an Intel license server problem.

**Comment by bartlettroscoe** [comment]
Crossing fingers and trying PR testing attempt `#`7!

**Comment by mhoemmen** [comment]
@trilinos/framework The dreaded "can't find license server" issue has returned, alas.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> The dreaded "can't find license server" issue has returned, alas.

Where do you see that?  The problem currently is a bad Jenkins node as described in https://github.com/trilinos/Trilinos/issues/3276#issuecomment-462067485 and https://github.com/trilinos/Trilinos/issues/3276#issuecomment-462089890.

**Comment by bartlettroscoe** [comment]
FYI: I put `AT: WIP` on this PR since it just keeps failing.  Once the Trilinos PR testing system gets fixed, I will remove this label and get it tested again.  See https://github.com/trilinos/Trilinos/issues/3276#issuecomment-462198925 for more details.

**Comment by mhoemmen** [comment]
@bartlettroscoe I saw it when I clicked the link to get to the list of PR tests.  I suspect that includes old PR tests among the latest ones, but I'm not sure.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> I saw it when I clicked the link to get to the list of PR tests. I suspect that includes old PR tests among the latest ones, but I'm not sure.

Yea, the Intel license server problem is why it failed earlier in the week but lately, it is a bad jenkins node.

**Comment by jwillenbring** [comment]
I took the offending nodes out of the node pool for now for the 4.8.4 job and applied the retest flag.

**Pull request merged**
