### PR TITLE
Triple matrix product

### PR DESCRIPTION
**Pull request by cgcgcg**
Currently, MueLu computes the coarse grid matrix Ac using two sparse matrix-matrix products: Ac = R*(A*P). This pull request adds routines to compute Ac directly instead.

If R and P are not too dense, this new approach is faster than the double matrix-matrix product. The ideal use case are unsmoothed prolongators. With the MueLu parameters

    <Parameter name="rap: triple product"     type="bool" value="true"/>
    <Parameter name="transpose: use implicit" type="bool" value="true"/>

the computation of the coarse grid matrix can take only half as much time as the double matrix-matrix product.

_5-point Lapacian in 2D, unsmoothed aggregation, 100 repetitions:_
36-timings

When the prolongators are smoothed, using the new approach might only be of use on the finer levels.

    <ParameterList name="level 1">
      <Parameter name="rap: triple product" type="bool" value="true"/>
    </ParameterList>

_7-point Lapacian in 3D, smoothed aggregation, 100 repetitions:_
36-timings

For denser prolongators, the triple product is less efficient than the double matrix-matrix product. For this reason, it is disabled by default.

_Elasticity in 3D, smoothed aggregation, 100 repetitions:_
36-timings

### CODE REVIEW

**Comment by kddevin** [comment]
Yes, Zoltan2 uses matrix-matrix multiplication to identify second adjacencies in meshes, using the first adjacencies.  Is instantiation with SCALAR=int causing a problem with this pull request?

**Comment by cgcgcg** [comment]
I copied that part over from the regular matrix-matrix product, so I did not look at it too closely. Should I remove that stuff, given that Zoltan probably only calls the regular matrix-matrix product?

**Comment by aprokop** [comment]
> For denser prolongators, the triple product is less efficient than the double matrix-matrix product. For this reason, it is disabled by default.

@cgcgcg Do I understand it right that this option should produce results only for scalar problems+tentative, scalar problems + smoothed, but should not be enabled for vector problems? Or is there a heuristic base on the number of nonzeros in prolongator?

**Comment by cgcgcg** [comment]
@aprokop  It can be used for unsmoothed vector problems as well, e.g. unsmoothed 3D Elasticity is about 40% faster. I am working on having some heuristic to switch between the implementations, but that's not ready yet.

**Comment by mhoemmen** [comment]
@cgcgcg I would only remove it for your stuff (the matrix triple product).  Be sure to enable both MueLu and Zoltan2 (and all downstream packages), and see if everything builds and links (be sure to enable ETI).

@kddevin wrote:
> Yes, Zoltan2 uses matrix-matrix multiplication to identify second adjacencies in meshes, using the first adjacencies. Is instantiation with SCALAR=int causing a problem with this pull request?

It shouldn't cause problems at all, unless Zoltan2 plans on using the matrix triple product.  The issue of whether `Scalar=int` is necessary (hint: it's not ;-) just use `double` or `long long`) is completely separate.  Thanks for answering, though! :-)

**Comment by srajama1** [comment]
@cgcgcg : What do you do for local computation when node type is not Serial. May be this defaults to standard matrix-matrix multiply in that case. It is probably there, but hard to find in all the diffs.

**Comment by cgcgcg** [comment]
@mhoemmen Removed the unnecessary instantiation.

@srajama1 Currently, the serial implementation is run no matter what node type. The user needs to make a conscious decision to turn it on since the triple product is switched off by default, so maybe this is ok?

**Comment by mhoemmen** [comment]
@cgcgcg Thanks!  Does everything still build, Zoltan2 included?

**Comment by cgcgcg** [comment]
@mhoemmen Yep! But I will still run the checkin script in the end to push..

**Comment by mhoemmen** [comment]
@cgcgcg Thanks! :-D  If you decide to enable this by default, be sure to do a CUDA build first.  Sometimes CUDA surprises us ;-) .  It's hard to review all the code, but the stuff I looked at looks good.

**Comment by tawiesn** [comment]
@cgcgcg Why is there only a Tpetra implementation? What about Epetra?

**Comment by srajama1** [comment]
@cgcgcg : May be. I will let you or @jhux2 decide.

**Comment by cgcgcg** [comment]
@tawiesn Yes, this is Tpetra only. Epetra will just throw and tell you that this is not implemented.

**Comment by tawiesn** [comment]
@cgcgcg I've seen that. I'm just wondering whether there is a specific reason for that. Are you using special Tpetra routines? Was there a specific reason to put the routines in Tpetra rather than implementing them in Xpetra?

**Comment by cgcgcg** [comment]
@tawiesn I believe I tried that a while back, but gave up, cause I had to wrap a whole bunch of functions in Xpetra. Looking at the code now, I cannot remember though which ones..

**Pull request closed without merging**
