### PR TITLE
@trilinos/tpetra: Generalizes Crs Matrix tests that run for GO=int

### PR DESCRIPTION
**Pull request by tjfulle**
@mhoemmen, the PR addresses #698 

I built/tested with `checkin-tests-sems.sh --local-do-all --enable-all-packages=on`.  I'd be happy to test with other Tpetra instantiations if you'd like.

Summary of Build/Test cases
```
Pull: Not Performed
Configure: Passed (5.12 min)
Build: Passed (102.21 min)
Test: Passed (14.07 min)

100% tests passed, 0 tests failed out of 2278

Label Time Summary:
Amesos               =  23.00 sec (14 tests)
Amesos2              =  11.89 sec (7 tests)
Anasazi              = 132.34 sec (71 tests)
AztecOO              =  19.56 sec (17 tests)
Belos                = 118.32 sec (61 tests)
Domi                 = 194.63 sec (125 tests)
Epetra               =  66.29 sec (61 tests)
EpetraExt            =  16.14 sec (10 tests)
FEI                  =  49.83 sec (43 tests)
Galeri               =   6.24 sec (9 tests)
GlobiPack            =   2.68 sec (6 tests)
Ifpack               =  74.91 sec (53 tests)
Ifpack2              =  64.04 sec (33 tests)
Intrepid             = 281.07 sec (152 tests)
Intrepid2            =  65.95 sec (66 tests)
Isorropia            =   9.37 sec (6 tests)
Kokkos               = 332.36 sec (21 tests)
ML                   =  55.96 sec (34 tests)
MiniTensor           =   0.61 sec (2 tests)
MueLu                = 465.97 sec (54 tests)
NOX                  = 191.54 sec (101 tests)
OptiPack             =   7.48 sec (5 tests)
Panzer               = 446.36 sec (128 tests)
Phalanx              =   7.28 sec (15 tests)
Pike                 =   4.57 sec (7 tests)
Piro                 =  38.46 sec (11 tests)
ROL                  = 1424.70 sec (122 tests)
RTOp                 =  17.96 sec (24 tests)
Rythmos              = 254.51 sec (83 tests)
SEACAS               =  10.79 sec (8 tests)
STK                  =  18.54 sec (12 tests)
Sacado               = 119.30 sec (290 tests)
Shards               =   1.51 sec (4 tests)
ShyLU                =  11.66 sec (5 tests)
Stokhos              = 159.14 sec (74 tests)
Stratimikos          =  44.62 sec (39 tests)
Teko                 = 268.63 sec (19 tests)
Teuchos              =  75.79 sec (124 tests)
ThreadPool           =  17.96 sec (10 tests)
Thyra                =  79.78 sec (80 tests)
Tpetra               = 169.15 sec (134 tests)
TrilinosCouplings    =  80.29 sec (19 tests)
Triutils             =   3.18 sec (2 tests)
Xpetra               =  57.95 sec (17 tests)
Zoltan               = 220.15 sec (16 tests)
Zoltan2              = 150.24 sec (92 tests)

Total Test time (real) = 843.97 sec

Total time for MPI_RELEASE_DEBUG_SHARED_PT = 121.41 min
```

### CODE REVIEW

**Comment by mhoemmen** [comment]
Thanks @tjfulle !  Is this ready now or should I wait?

**Comment by tjfulle** [comment]
@mhoemmen , all tests passed with the standard checkin script.  I have not tested non-default Tpetra local and global ordinal values

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> I have not tested non-default Tpetra local and global ordinal values

The default are LO = int and GO = int, as long as GO = int is enabled.  See tpetra/core/src/Tpetra_ConfigDefs.hpp, lines 157-169.

**Comment by tjfulle** [comment]
@mhoemmen I rebuilt and ran with `-DTpetra_INST_INT_INT=OFF -DTpetra_INST_INT_LONG=ON` and `-DTpetra_INST_INT_INT=OFF -DTpetra_INST_INT_LONG_LONG=ON`.  All tests passed, but none of these tests were run involved in this PR were run.  Is that not the correct way to test different global ordinal types?

**Comment by tjfulle** [comment]
Bump: @mhoemmen

**Comment by mhoemmen** [comment]
> All tests passed, but none of these tests were run involved in this PR were run.

Could you clarify the latter phrase?

**Comment by tjfulle** [comment]
Sheesh, I had to read that like four times to remember what I meant...

I meant to say that this PR involved fixing up several tests in the `tests/CrsMatrix` directory.  The point of the fix up was to generalize the tests for different `LO` and `GO` types.  The tests have been modified and all pass for the default `checkin-sems-script.sh`.  I wanted to force all `LO` and `GO` types, so I explicitly set them as above, but the `CrsMatrix` tests in question don't run in this case.  I guess I'm confused as t why the don't run, but with non default `LO` and `GO` types.

I'm not sure that explanation even makes sense...

**Comment by mhoemmen** [comment]
I'm curious about the changes to the bug5978.cpp file -- it looks like an entire test was removed.

**Comment by tjfulle** [comment]
@mhoemmen  Look at some of the comments in the source code - I renamed it to `Bug_...` with a capitol B to be consistent with the `Bug_*` tests.  GitHub is not smart enough to diff the files if the name changed

**Comment by mhoemmen** [comment]
I just tested and merged @tjfulle 's branch into develop.

**Pull request closed without merging**
