### PR TITLE
SYTRF enabling for ROCSolver version 3.16 and higher

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
## Motivation

A license is added with a new SCR number. No code change. This PR also includes enabling sytrf for ROCSolver version 3.16 and higher.

## Testing

No actual code change was made.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@crdohrm this is code cleaning and license prepending to files.

**Comment by kyungjoo-kim** [comment]
@trilinos/framework Could you give me a clue why this PR does not even enter the pre-merge inspection ?

**Review by crdohrm — APPROVED** [review]

**Comment by kyungjoo-kim** [comment]
@trilinos/framework It said that the test is failed but I do not see anything from cdash.

**Comment by kyungjoo-kim** [comment]
@trilinos/framework the pr tester says that cuda uvm=off test is failed but it is not shown in the dashboard. how can I see the failure ?

**Pull request merged**
