### PR TITLE
Intrepid HGRAD Bases: avoid potential buffer overrun, eliminate extraneous console output, and avoid exceptions thrown when run in Debug mode

### PR DESCRIPTION
**Pull request by CamelliaDPG**
Fixes for HGRAD bases on hexahedra and triangles.

### CODE REVIEW

**Comment by dridzal** [comment]
@bmpersc , can you comment on the procedure for merging pull requests to master?  I'm getting Nate's CamelliaDPG emails, but I don't know if I can/should do anything.  My guess is that I can't do anything, because this is going to master and not develop.

**Comment by CamelliaDPG** [comment]
Should I be submitting the pull requests to develop, then?  Let me know, and I can close and recreate these.

**Comment by dridzal** [comment]
I really don't know; let's ask Ross @bartlettroscoe  or Brent @bmpersc .  I'm not familiar with the proper Trilinos procedure for pull requests.

**Comment by bmpersc** [comment]
Denis,
  First off this pull request is against master so you will not be able to just press the button that says "Merge pull request." However, if you've reviewed the commit(s) and feel that is appropriate in the future you can let github do all the work. However, I would strongly encourage you to test before merging. You can do that in several ways. There is a link "command line instructions" which are fine to follow. In this case those instructions need to be modified to push to the develop branch instead of master, but that is easily achieved by replacing master with develop in the commands given. If you plan to test you would do that between step 1 and 2 in the command line instructions.

**Comment by dridzal** [comment]
Brent, I believe that Nate @CamelliaDPG has now created a pull request against develop.  Nate, please confirm this; i.e., is pull request #589 the one to act on, and this one, #587, should be closed?  Also, have you run Intrepid tests; if not, would you suggest that I do this?  I see that some of the changes are trivial, but there is one where a chunk of code was replaced by a call to a function that was not there before.  Thanks.

**Comment by CamelliaDPG** [comment]
Denis, #589 is a separate issue (to do with Ifpack).  I can certainly resubmit to develop if you like.  I have not run Intrepid tests; that does seem like a good idea.  Yes, the changes in #587 should be non-controversial: just looking at the code, it should be obvious that the changes fix the issues mentioned.  The change in #588 (the new function call you refer to, I think) is more subtle, which is why I attached code that demonstrates the problem I'm fixing.  Please let me know if I should resubmit to develop.  Thanks!

**Comment by bartlettroscoe** [comment]
You can change the base branch for the merge. See:

* https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by CamelliaDPG** [comment]
Thanks, Ross.  I've done this for #587; will now do for #588.

**Comment by dridzal** [comment]
Nate, if you could make sure that the test are passing with bug fixes #587 , #588 and #589 , that would be great help.  Since the amount of code is fairly small (and I've reviewed it, and it all looks perfectly reasonable), I will merge the pull requests once I hear back from you.

**Comment by CamelliaDPG** [comment]
Hi Denis,

I'm a relative newbie for Trilinos tests, but I have now run them with each of #587, #588, #589.  Everything looks good, I think.  Two things to mention, though.  First, I changed the Ifpack_SparseContainer fix (#589) slightly, to use the more explicit Epetra_DataAccess::Copy in place of ::Copy.  I did this before running the Ifpack tests.

Second, I had a couple issues running the tests---though I don't think they have anything to do with my proposed changes.  First, when I built using openmpi, I found that the tests would frequently (but inconsistently) hang in an orterun process.  So I switched to using mpich.  This did not hang, but had inconsistent failures of its own, with console output of the form:

***Failed  Required regular expression not found.Regex=[OVERALL FINAL RESULT: TEST PASSED .TeuchosComm_UnitTestHarness_Parallel_UnitTests_MPI_no_reduce.

The test Epetra_lesson02_init_map_vec_MPI_4 in particular seemed to be prone to such failures.  But it sometimes passes.  Since none of the failures in any way reference the code that I'm submitting, I suspect the issues are something else.  The test Anasazi_Epetra_BlockDavidson_auxtest_MPI_4 also did, on one occasion, get stuck.  It ran 4 MPI processes for 7 minutes before I killed it.

Details of my setup:
I'm using OS X Yosemite 10.10.5, with Apple's clang compiler.  The enabled packages and TPLs are listed below.  For each branch, I did make -j2, followed by make test.  (Late in the game, I discovered the Trilinos docs that describe using ctest instead of make test.  I did try this, with similar results.)

Final set of enabled packages:  Gtest Kokkos Teuchos RTOp Sacado Epetra Zoltan Shards Triutils Tpetra EpetraExt Thyra Xpetra Isorropia AztecOO Galeri Amesos Pamgen Ifpack ML Belos Anasazi Intrepid 23

Final set of enabled SE packages:  Gtest KokkosCore KokkosContainers KokkosAlgorithms Kokkos TeuchosCore TeuchosParameterList TeuchosComm TeuchosNumerics TeuchosRemainder TeuchosKokkosCompat TeuchosKokkosComm Teuchos RTOp Sacado Epetra Zoltan Shards Triutils TpetraClassic TpetraKernels TpetraTSQR TpetraCore Tpetra EpetraExt ThyraCore ThyraEpetraAdapters ThyraEpetraExtAdapters ThyraTpetraAdapters Thyra Xpetra Isorropia AztecOO Galeri Amesos Pamgen Ifpack ML Belos Anasazi Intrepid 41

Final set of enabled TPLs:  Pthread MPI BLAS LAPACK HDF5 5

Cheers,
Nate

**Comment by dridzal** [comment]
Nate, it sounds like all (potential) issues are related to other packages.  I have not experienced issues with Epetra and Teuchos, which you describe, but I'm using compiler and runtime environment modules that are available on our network through the SEMS team.  Since there are no failing tests in Intrepid, I will merge your proposed changes.

**Pull request merged**
