### PR TITLE
Tpetra::Distributor: Fix #3580

### LINKED ISSUE #3580: Tpetra::Distributor: Fix "slow path" so we can use MPI_Isend
@trilinos/tpetra @jjellio @csiefer2 

Fix the "slow path" of `Distributor::doPosts`, so we can use nonblocking sends (`MPI_Isend`).  The "slow path" kicks in when the data to send are not neatly grouped in contiguous chunks per process.  It permutes the data into contiguous-by-target-process-rank chunks for sending.  Currently, the slow path uses the same send buffer for all the messages.  This means that it cannot use nonblocking sends.

We must fix both the "three-argument" (all messages have the same size) and "four-argument" (different messages may have different sizes) overloads of `doPosts`, and both the `Teuchos::ArrayRCP` and `Kokkos::View` versions of each.

## Motivation and Context

This is part of the overall effort to improve MPI+CUDA performance and make Tpetra's boundary exchange and sparse matrix-vector multiply communication nonblocking.

## Definition of Done

- [x] Fix 3-argument `Teuchos::ArrayRCP` overload of `doPosts`
- [x] Fix 3-argument `Kokkos::View` overload of `doPosts`
- [x] Fix 4-argument `Teuchos::ArrayRCP` overload of `doPosts`
- [x] Fix 4-argument `Kokkos::View` overload of `doPosts`

## Related Issues

* Part of #383

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @jjellio 

## Description

Fix #3580, by making all instances of the "slow path" in Distributor use a buffer long enough for all the messages, not just one at a time.  Ignore the "Send type" and "Barrier between..." options, and always use `MPI_Isend` for sends.

* Closes #3580 

## How Has This Been Tested?

Mac, Clang, OpenMPI.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@lucbv wrote:
> LGTM, nice to see you found the time to work this one out, it offers interesting avenues.

Thanks! :-D  @jjellio has been measuring this and wants to work on it too.  James and I will meet soon to talk about this.  #383 has some design discussion.  I suspect that the best design would involve pre-permuting the data before it reaches Distributor.  That way, the "slow path" would be subsumed in DistObject + {Ex,Im}port, and Distributor could be more of a pure boundary exchange.

**Comment by mhoemmen** [comment]
Oops, gotta include `<memory>` for `unique_ptr`.  Will do soon.

**Comment by mhoemmen** [comment]
Sorry @lucbv ; may I trouble you again?  Thanks! :-D

**Comment by mhoemmen** [comment]
@trilinos/framework PR tests didn't see the new commit, argh.  I'll try again :)

**Comment by mhoemmen** [comment]
@trilinos/framework @trilinos/tpetra @bartlettroscoe @jwillenbring @william76 

Not sure what's going on here.  I have the right include `<memory>` for `std::unique_ptr`.  It's a standard C++11 thing.  Why doesn't PR testing pick up on this change?

**Comment by mhoemmen** [comment]
> HIER CHECK EINFUEGEN

Um, I didn't write that ;-)  It looks like some Frosch thing got through PR testing.

**Comment by mhoemmen** [comment]
@searhein See error message above.  Did something go wrong in Frosch?

**Comment by mhoemmen** [comment]
@prwolfe Ah, I see.  Not sure why the old commit is showing up in only some of the PR tests.

@searhein Hold on; I have to look into this further.

**Comment by searhein** [comment]
@mhoemmen Let me know if you think that this is related to FROSch. Then, I will take a look at this. 

And yes: we need to work on our output ;-) However, this was not our priority so far.,

**Comment by mhoemmen** [comment]
@searhein wrote:
> Let me know if you think that this is related to FROSch. Then, I will take a look at this.

Thanks for offering!  I saw that a test failed in MueLu too, so I'll need to investigate more first.

> And yes: we need to work on our output ;-)

If you find yourself writing "hier check einfügen" then you'd better just put the check there ;-)

**Comment by mhoemmen** [comment]
@lucbv @jjellio Regarding today's questions about this branch: We found that this broke some unit tests in MueLu.  This tells me that Distributor doesn't have sufficient unit tests for the "slow path."  That should be the next step, before we start hacking stuff in there.

**Comment by william76** [comment]
@mhoemmen This PR is over a year old... should it be closed out?

**Comment by mhoemmen** [comment]
@william76 I'm OK with that, as long as it doesn't disappear and we can reopen it at some point.

**Comment by mhoemmen** [comment]
@trilinos/tpetra I'm closing this PR since Distributor has changed a lot in the meantime, but we should revisit the issue.

**Pull request closed without merging**
