### PR TITLE
Kokkos + KokkosKernels Promotion To Version 2.6.00

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos 
@trilinos/kokkos-kernels 

## Description

This merges Kokkos and KokkosKernels versions 2.6.00 into Trilinos.
This adds support for Volta GPUs and improves performance of all Cuda kernel launches and View shallow copies and atomics with Serial backend. 
This adds enhancement for KokkosKernels Batched BLAS and performance improvements for Spgemm hashing. 

## [2.6.00](https://github.com/kokkos/kokkos/tree/2.6.00) (2018-03-07)
[Full Changelog](https://github.com/kokkos/kokkos/compare/2.5.00...2.6.00)

**Part of the Kokkos C++ Performance Portability Programming EcoSystem 2.6**

**Implemented enhancements:**

- Support NVIDIA Volta microarchitecture [\#1466](https://github.com/kokkos/kokkos/issues/1466)
- Kokkos - Define empty functions when profiling disabled [\#1424](https://github.com/kokkos/kokkos/issues/1424)
- Don't use \_\_constant\_\_ cache for lock arrays, enable once per run update instead of once per call [\#1385](https://github.com/kokkos/kokkos/issues/1385)
- task dag enhancement. [\#1354](https://github.com/kokkos/kokkos/issues/1354)
- Cuda task team collectives and stack size [\#1353](https://github.com/kokkos/kokkos/issues/1353)
- Replace View operator acceptance of more than rank integers with 'access' function [\#1333](https://github.com/kokkos/kokkos/issues/1333)
- Interoperability: Do not shut down backend execution space runtimes upon calling finalize. [\#1305](https://github.com/kokkos/kokkos/issues/1305)
- shmem\_size for LayoutStride [\#1291](https://github.com/kokkos/kokkos/issues/1291)
- Kokkos::resize performs poorly on 1D Views [\#1270](https://github.com/kokkos/kokkos/issues/1270)
- stride\(\) is inconsistent with dimension\(\), extent\(\), etc. [\#1214](https://github.com/kokkos/kokkos/issues/1214)
- Kokkos::sort defaults to std::sort on host [\#1208](https://github.com/kokkos/kokkos/issues/1208)
- DynamicView with host size grow [\#1206](https://github.com/kokkos/kokkos/issues/1206)
- Unmanaged View with Anonymous Memory Space [\#1175](https://github.com/kokkos/kokkos/issues/1175)
- Sort subset of Kokkos::DynamicView [\#1160](https://github.com/kokkos/kokkos/issues/1160)
- MDRange policy doesn't support lambda reductions [\#1054](https://github.com/kokkos/kokkos/issues/1054)
- Add ability to set hook on Kokkos::finalize [\#714](https://github.com/kokkos/kokkos/issues/714)
- Atomics with Serial Backend - Default should be Disable? [\#549](https://github.com/kokkos/kokkos/issues/549)
- KOKKOS\_ENABLE\_DEPRECATED\_CODE [\#1359](https://github.com/kokkos/kokkos/issues/1359)

**Fixed bugs:**

- cuda\_internal\_maximum\_warp\_count returns 8, but I believe it should return 16 for P100  [\#1269](https://github.com/kokkos/kokkos/issues/1269)
- Cuda: level 1 scratch memory bug \(reported by Stan Moore\) [\#1434](https://github.com/kokkos/kokkos/issues/1434)
- MDRangePolicy Reduction requires value\_type typedef in Functor [\#1379](https://github.com/kokkos/kokkos/issues/1379)
- Kokkos DeepCopy between empty views fails [\#1369](https://github.com/kokkos/kokkos/issues/1369)
- Several issues with new CMake build infrastructure \(reported by Eric Phipps\) [\#1365](https://github.com/kokkos/kokkos/issues/1365)
- deep\_copy between rank-1 host/device views of differing layouts without UVM no longer works \(reported by Eric Phipps\) [\#1363](https://github.com/kokkos/kokkos/issues/1363)
- Profiling can't be disabled in CMake, and a parallel\_for is missing for tasks \(reported by Kyungjoo Kim\) [\#1349](https://github.com/kokkos/kokkos/issues/1349)
- get\_work\_partition int overflow \(reported by berryj5\) [\#1327](https://github.com/kokkos/kokkos/issues/1327)
- Kokkos::deep\_copy must fence even if the two views are the same [\#1303](https://github.com/kokkos/kokkos/issues/1303)
- CudaUVMSpace::allocate/deallocate must fence [\#1302](https://github.com/kokkos/kokkos/issues/1302)
- ViewResize on CUDA fails in Debug because of too many resources requested [\#1299](https://github.com/kokkos/kokkos/issues/1299)
- Cuda 9 and intrepid2 calls from Panzer. [\#1183](https://github.com/kokkos/kokkos/issues/1183)
- Slowdown due to tracking\_enabled\(\) in 2.04.00 \(found by Albany app\) [\#1016](https://github.com/kokkos/kokkos/issues/1016)
- Bounds checking fails with zero-span Views \(reported by Stan Moore\) [\#1411](https://github.com/kokkos/kokkos/issues/1411)

## [2.6.00](https://github.com/kokkos/kokkos-kernels/tree/2.6.00) (2018-03-07)
[Full Changelog](https://github.com/kokkos/kokkos-kernels/compare/2.5.00...2.6.00)

**Implemented enhancements:**

- Spgemm hash promotion [\#171](https://github.com/kokkos/kokkos-kernels/issues/171)
- Batched BLAS enhancement [\#170](https://github.com/kokkos/kokkos-kernels/issues/170)

**Fixed bugs:**

- d2\_graph\_color doesn't have a default coloring mechanism [\#168](https://github.com/kokkos/kokkos-kernels/issues/168)
- Build error when MKL TPL is enabled [\#135](https://github.com/kokkos/kokkos-kernels/issues/135)

## How Has This Been Tested?

This set of changes has been tested on Shepard and White with Intel 17, GCC 5.3, NVCC 8.
Configurations according to kokkos-kernels/scripts/trilinos-integration test scripts.
A detailed list of test failures is provided below. No additional test failures compared to the current
trilinos/develop branch were observed. Both individual packages are passing their comprehensive
nightly test suites. This includes testing of more than 200 configuration spanning 25+ compiler versions and 9 hardware platforms ( Intel Skylake, Intel SandyBridge, Intel Haswell, Intel Haswell + NVIDIA K40, Intel KNL, ARM, Power8, Power8 + K80, Power8 + P100).

### CODE REVIEW

**Comment by ndellingwood** [comment]
@trilinos/panzer please take a look at the change to this unit test in Panzer
`panzer/adapters-stk/test/gather_scatter_evaluators/scatter_field_evaluator.cpp`

The Kokkos finalize hook was needed for the global scope `linBasis` variable to remove a Cuda compilation error:
`cudaDeviceSynchronize() error(cudaErrorCudartUnloading)`

**Comment by ndellingwood** [comment]
# Testing Results Shepard Serial
Errors and test failures are a strict subset of the ones encountered on the develop branch of Trilinos (without the Kokkos or KokkosKernels snapshots) with the same configuration.

## Build Errors:
None

## General Test Results: 
Two failures that also failed with existing Trilinos develop branch

```
99% tests passed, 2 tests failed out of 1742

Label Time Summary:
Amesos2          =  10.39 sec (9 tests)
Anasazi          = 119.36 sec (100 tests)
Belos            = 108.98 sec (87 tests)
Ifpack           =  45.55 sec (41 tests)
Ifpack2          =  48.34 sec (35 tests)
Intrepid         = 184.78 sec (153 tests)
Intrepid2        =  94.80 sec (144 tests)
Isorropia        =   4.12 sec (4 tests)
Kokkos           =  46.60 sec (23 tests)
KokkosKernels    = 109.27 sec (4 tests)
ML               =  20.34 sec (16 tests)
MueLu            = 329.16 sec (96 tests)
NOX              = 121.15 sec (92 tests)
Panzer           = 156.44 sec (116 tests)
Phalanx          =  21.05 sec (22 tests)
ROL              = 146.92 sec (71 tests)
Sacado           = 162.98 sec (292 tests)
ShyLU_Node       =   1.78 sec (3 tests)
Stokhos          = 105.24 sec (75 tests)
Stratimikos      =  28.28 sec (24 tests)
Thyra            =  71.69 sec (81 tests)
Tpetra           = 145.21 sec (149 tests)
Xpetra           =  24.02 sec (18 tests)
Zoltan2          = 112.07 sec (96 tests)

Total Test time (real) = 2217.83 sec

The following tests FAILED:
        712 - ML_MLP_Restart_MPI_4 (Failed)
        1352 - NOX_Thyra_Heq_MPI_1 (Failed)
```

**Comment by ndellingwood** [comment]
# Testing Results White OpenMP

Errors and test failures are a strict subset of the ones encountered on the develop branch of Trilinos (without the Kokkos or KokkosKernels snapshots) with the same configuration.

## Build Errors:
None

## General Test Results:
```
96% tests passed, 70 tests failed out of 1805

Label Time Summary:
Amesos2          =   6.52 sec (9 tests)
Anasazi          = 261.55 sec (71 tests)
Belos            =  68.38 sec (72 tests)
Ifpack           =  35.88 sec (41 tests)
Ifpack2          =  42.16 sec (35 tests)
Intrepid         = 149.91 sec (153 tests)
Intrepid2        =  77.49 sec (240 tests)
Isorropia        =   3.17 sec (4 tests)
Kokkos           =  85.16 sec (26 tests)
KokkosKernels    = 173.75 sec (8 tests)
ML               =  16.26 sec (16 tests)
MueLu            = 319.40 sec (92 tests)
NOX              = 513.25 sec (92 tests)
Panzer           = 156.91 sec (116 tests)
Phalanx          =  12.93 sec (22 tests)
ROL              = 188.30 sec (71 tests)
Sacado           =  76.70 sec (296 tests)
ShyLU_Node       =   0.91 sec (4 tests)
Stokhos          = 102.79 sec (78 tests)
Stratimikos      =  22.19 sec (24 tests)
Thyra            =  48.56 sec (81 tests)
Tpetra           = 100.75 sec (149 tests)
Xpetra           =  18.29 sec (18 tests)
Zoltan2          =  86.20 sec (96 tests)

Total Test time (real) = 2564.32 sec
```

## Test Failures:
One additional failure on the develop branch not occurring on the kokkos-develop branch of Trilinos.
```
The following tests FAILED:
        740 - Belos_pseudo_gmres_hb_MPI_4 (Failed)
        741 - Belos_bl_pgmres_hb_0_MPI_4 (Failed)
        742 - Belos_bl_pgmres_hb_1_MPI_4 (Failed)
        743 - Belos_bl_pgmres_hb_2_MPI_4 (Failed)
        744 - Belos_pseudo_pgmres_hb_MPI_4 (Failed)
        745 - Belos_bl_fgmres_hb_MPI_4 (Failed)
        761 - Belos_gcrodr_hb_MPI_4 (Failed)
        763 - Belos_prec_gcrodr_hb_1_MPI_4 (Failed)
        816 - Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)
        818 - Anasazi_Epetra_OrthoManagerTester_0_MPI_4 (Failed)
        819 - Anasazi_Epetra_OrthoManagerTester_1_MPI_4 (Timeout)
        820 - Anasazi_Epetra_OrthoManagerTester_2_MPI_4 (Failed)
        821 - Anasazi_Epetra_OrthoManagerTester_3_MPI_4 (Failed)
        822 - Anasazi_Epetra_OrthoManagerTester_4_MPI_4 (Failed)
        823 - Anasazi_Epetra_OrthoManagerTester_5_MPI_4 (Failed)
        824 - Anasazi_Epetra_OrthoManagerMatTester_0_MPI_4 (Failed)
        825 - Anasazi_Epetra_OrthoManagerMatTester_1_MPI_4 (Failed)
        826 - Anasazi_Epetra_OrthoManagerMatTester_2_MPI_4 (Failed)
        827 - Anasazi_Epetra_OrthoManagerMatTester_3_MPI_4 (Failed)
        828 - Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4 (Failed)
        829 - Anasazi_Epetra_OrthoManagerMatTester_5_MPI_4 (Failed)
        830 - Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 (Failed)
        831 - Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)
        832 - Anasazi_Epetra_BlockDavidson_solvertest_MPI_4 (Failed)
        833 - Anasazi_Epetra_BlockDavidson_test_0_MPI_4 (Failed)
        834 - Anasazi_Epetra_BlockDavidson_test_1_MPI_4 (Failed)
        835 - Anasazi_Epetra_BlockDavidson_test_2_MPI_4 (Failed)
        836 - Anasazi_Epetra_BlockDavidson_test_3_MPI_4 (Failed)
        837 - Anasazi_Epetra_BlockDavidson_test_4_MPI_4 (Failed)
        838 - Anasazi_Epetra_BlockDavidson_test_5_MPI_4 (Failed)
        839 - Anasazi_Epetra_BlockDavidson_test_6_MPI_4 (Failed)
        840 - Anasazi_Epetra_BlockDavidson_test_7_MPI_4 (Failed)
        841 - Anasazi_Epetra_BlockDavidson_test_8_MPI_4 (Failed)
        842 - Anasazi_Epetra_BlockDavidson_auxtest_MPI_4 (Failed)
        843 - Anasazi_Epetra_BKS_solvertest_MPI_4 (Failed)
        845 - Anasazi_Epetra_BKS_test_1_MPI_4 (Failed)
        849 - Anasazi_Epetra_BKS_nh_test_1_MPI_4 (Failed)
        850 - Anasazi_Epetra_GeneralizedDavidson_solvertest_MPI_4 (Failed)
        853 - Anasazi_Epetra_LOBPCG_solvertest_MPI_4 (Failed)
        854 - Anasazi_Epetra_LOBPCG_simpletest_MPI_4 (Failed)
        855 - Anasazi_Epetra_LOBPCG_test_MPI_4 (Failed)
        856 - Anasazi_Epetra_LOBPCG_auxtest_MPI_4 (Failed)
        857 - Anasazi_Epetra_IRTR_test_0_MPI_4 (Failed)
        858 - Anasazi_Epetra_IRTR_test_1_MPI_4 (Failed)
        859 - Anasazi_Epetra_IRTR_test_2_MPI_4 (Failed)
        860 - Anasazi_Epetra_IRTR_test_3_MPI_4 (Failed)
        861 - Anasazi_Epetra_IRTR_auxtest_0_MPI_4 (Failed)
        862 - Anasazi_Epetra_IRTR_auxtest_1_MPI_4 (Failed)
        863 - Anasazi_Epetra_IRTR_auxtest_2_MPI_4 (Failed)
        864 - Anasazi_Epetra_IRTR_auxtest_3_MPI_4 (Failed)
        865 - Anasazi_Epetra_IRTR_auxtest_4_MPI_4 (Failed)
        872 - Anasazi_BlockDavidsonThyra_test_MPI_4 (Failed)
        875 - Anasazi_IRTRThyra_test_0_MPI_4 (Failed)
        876 - Anasazi_IRTRThyra_test_1_MPI_4 (Failed)
        877 - Anasazi_IRTRThyra_test_2_MPI_4 (Failed)
        878 - Anasazi_IRTRThyra_test_3_MPI_4 (Failed)
        879 - Anasazi_LOBPCGThyra_test_MPI_4 (Failed)
        886 - Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4 (Failed)
        893 - Ifpack2_Jacobi_hb_belos_MPI_1 (Failed)
        894 - Ifpack2_Jacobi_hb_belos_MPI_2 (Failed)
        902 - Ifpack2_GS_belos_MPI_1 (Failed)
        903 - Ifpack2_SGS_belos_MPI_1 (Failed)
        928 - Stratimikos_Thyra_Belos_StatusTest_UnitTests_MPI_1 (Failed)
        936 - Stratimikos_Belos_GCRODR_strattest_MPI_4 (Failed)
        1337 - Intrepid2_unit-test_Orientation_Serial_Test_Orientation_TET_MPI_1 (Failed)
        1373 - NOX_LOCA_AnasaziJacobianInverse_MPI_1 (Timeout)
        1374 - NOX_LOCA_AnasaziNotConverged_MPI_1 (Timeout)
        1447 - NOX_LOCA_MultiPointTcubed_MPI_2 (Failed)
        1585 - Stokhos_TpetraCrsMatrixUQPCEUnitTest_OpenMP_MPI_4 (Failed)
        1593 - Stokhos_TpetraCrsMatrixMPVectorUnitTest_OpenMP_MPI_4 (Failed)
```

**Comment by ndellingwood** [comment]
# Testing Results White Cuda

Errors and test failures are a strict subset of the ones encountered on the develop branch of Trilinos (without the Kokkos or KokkosKernels snapshots) with the same configuration.

## Build Errors:
No new build errors were introduced by the integration testing. The following errors occur with both develop and kokkos-develop branches of Trilinos:

**ROL**
`/mnt/netapp/OHPC_home/ndellin/IntegrationTests/cuda/trilinos-update/packages/rol/test/function/test_03.cpp(79): error: the type in a dynamic_cast must be a pointer or reference to a complete class type, or void *`

**MueLu**
```
/mnt/netapp/OHPC_home/ndellin/IntegrationTests/cuda/trilinos-update/packages/teuchos/core/src/Teuchos_RCP.hpp(288): error: a value of type "MueLu::Hierarchy<TrilinosCouplings::EpetraIntrepidPoissonExample::ST, int, int, KokkosClassic::DefaultNode::DefaultNodeType> *" cannot be used to initialize an entity of type "MueLu::EpetraOperator::Hierarchy *"
          detected during instantiation of "Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2> &) [with T=MueLu::EpetraOperator::Hierarchy, T2=MueLu::Hierarchy<TrilinosCouplings::EpetraIntrepidPoissonExample::ST, int, int, KokkosClassic::DefaultNode::DefaultNodeType>]"
/mnt/netapp/OHPC_home/ndellin/IntegrationTests/cuda/trilinos-update/packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_EpetraAztecOO_main.cpp(260): here

1 error detected in the compilation of "/tmp/tmpxft_0000a101_00000000-7_IntrepidPoisson_Pamgen_EpetraAztecOO_main.cpp1.ii".
```

## General Test Results:
```
96% tests passed, 71 tests failed out of 1816

Label Time Summary:
Amesos2          =  14.85 sec (8 tests)
Anasazi          =  97.19 sec (71 tests)
Belos            =  93.96 sec (72 tests)
Ifpack           =  38.49 sec (41 tests)
Ifpack2          = 123.86 sec (35 tests)
Intrepid         = 359.00 sec (153 tests)
Intrepid2        = 180.34 sec (247 tests)
Isorropia        =   3.18 sec (4 tests)
Kokkos           = 204.84 sec (26 tests)
KokkosKernels    = 160.33 sec (8 tests)
ML               =  17.50 sec (16 tests)
MueLu            = 1016.49 sec (92 tests)
NOX              = 538.94 sec (92 tests)
Panzer           = 613.70 sec (116 tests)
Phalanx          =  22.24 sec (22 tests)
ROL              = 399.15 sec (71 tests)
Sacado           = 102.40 sec (299 tests)
Stokhos          = 370.95 sec (82 tests)
Stratimikos      =  25.40 sec (24 tests)
Thyra            =  55.46 sec (81 tests)
Tpetra           = 380.63 sec (151 tests)
Xpetra           =  71.29 sec (18 tests)
Zoltan2          = 178.24 sec (96 tests)

Total Test time (real) = 5031.59 sec
```

## Test Failures:
One additional test failed on kokkos-develop branch during this testing, `PanzerAdaptersSTK_scatter_field_evaluator_MPI_1`, fixed by commit 6cd283d94de7fa72ac04c0d26fc931c7dc74a858 on the kokkos-develop branch. 
```
The following tests FAILED:
        745 - Belos_pseudo_gmres_hb_MPI_4 (Failed)
        746 - Belos_bl_pgmres_hb_0_MPI_4 (Failed)
        747 - Belos_bl_pgmres_hb_1_MPI_4 (Failed)
        748 - Belos_bl_pgmres_hb_2_MPI_4 (Failed)
        749 - Belos_pseudo_pgmres_hb_MPI_4 (Failed)
        750 - Belos_bl_fgmres_hb_MPI_4 (Failed)
        766 - Belos_gcrodr_hb_MPI_4 (Failed)
        768 - Belos_prec_gcrodr_hb_1_MPI_4 (Failed)
        816 - Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)
        818 - Anasazi_Epetra_OrthoManagerTester_0_MPI_4 (Failed)
        819 - Anasazi_Epetra_OrthoManagerTester_1_MPI_4 (Failed)
        820 - Anasazi_Epetra_OrthoManagerTester_2_MPI_4 (Failed)
        821 - Anasazi_Epetra_OrthoManagerTester_3_MPI_4 (Failed)
        822 - Anasazi_Epetra_OrthoManagerTester_4_MPI_4 (Failed)
        823 - Anasazi_Epetra_OrthoManagerTester_5_MPI_4 (Failed)
        824 - Anasazi_Epetra_OrthoManagerMatTester_0_MPI_4 (Failed)
        825 - Anasazi_Epetra_OrthoManagerMatTester_1_MPI_4 (Failed)
        826 - Anasazi_Epetra_OrthoManagerMatTester_2_MPI_4 (Failed)
        827 - Anasazi_Epetra_OrthoManagerMatTester_3_MPI_4 (Failed)
        828 - Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4 (Failed)
        829 - Anasazi_Epetra_OrthoManagerMatTester_5_MPI_4 (Failed)
        830 - Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 (Failed)
        831 - Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)
        832 - Anasazi_Epetra_BlockDavidson_solvertest_MPI_4 (Failed)
        833 - Anasazi_Epetra_BlockDavidson_test_0_MPI_4 (Failed)
        834 - Anasazi_Epetra_BlockDavidson_test_1_MPI_4 (Failed)
        835 - Anasazi_Epetra_BlockDavidson_test_2_MPI_4 (Failed)
        836 - Anasazi_Epetra_BlockDavidson_test_3_MPI_4 (Failed)
        837 - Anasazi_Epetra_BlockDavidson_test_4_MPI_4 (Failed)
        838 - Anasazi_Epetra_BlockDavidson_test_5_MPI_4 (Failed)
        839 - Anasazi_Epetra_BlockDavidson_test_6_MPI_4 (Failed)
        840 - Anasazi_Epetra_BlockDavidson_test_7_MPI_4 (Failed)
        841 - Anasazi_Epetra_BlockDavidson_test_8_MPI_4 (Failed)
        842 - Anasazi_Epetra_BlockDavidson_auxtest_MPI_4 (Failed)
        843 - Anasazi_Epetra_BKS_solvertest_MPI_4 (Failed)
        845 - Anasazi_Epetra_BKS_test_1_MPI_4 (Failed)
        849 - Anasazi_Epetra_BKS_nh_test_1_MPI_4 (Failed)
        850 - Anasazi_Epetra_GeneralizedDavidson_solvertest_MPI_4 (Failed)
        853 - Anasazi_Epetra_LOBPCG_solvertest_MPI_4 (Failed)
        854 - Anasazi_Epetra_LOBPCG_simpletest_MPI_4 (Failed)
        855 - Anasazi_Epetra_LOBPCG_test_MPI_4 (Failed)
        856 - Anasazi_Epetra_LOBPCG_auxtest_MPI_4 (Failed)
        857 - Anasazi_Epetra_IRTR_test_0_MPI_4 (Failed)
        858 - Anasazi_Epetra_IRTR_test_1_MPI_4 (Failed)
        859 - Anasazi_Epetra_IRTR_test_2_MPI_4 (Failed)
        860 - Anasazi_Epetra_IRTR_test_3_MPI_4 (Failed)
        861 - Anasazi_Epetra_IRTR_auxtest_0_MPI_4 (Failed)
        862 - Anasazi_Epetra_IRTR_auxtest_1_MPI_4 (Failed)
        863 - Anasazi_Epetra_IRTR_auxtest_2_MPI_4 (Failed)
        864 - Anasazi_Epetra_IRTR_auxtest_3_MPI_4 (Failed)
        865 - Anasazi_Epetra_IRTR_auxtest_4_MPI_4 (Failed)
        872 - Anasazi_BlockDavidsonThyra_test_MPI_4 (Failed)
        875 - Anasazi_IRTRThyra_test_0_MPI_4 (Failed)
        876 - Anasazi_IRTRThyra_test_1_MPI_4 (Failed)
        877 - Anasazi_IRTRThyra_test_2_MPI_4 (Failed)
        878 - Anasazi_IRTRThyra_test_3_MPI_4 (Failed)
        879 - Anasazi_LOBPCGThyra_test_MPI_4 (Failed)
        886 - Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4 (Failed)
        928 - Stratimikos_Thyra_Belos_StatusTest_UnitTests_MPI_1 (Failed)
        936 - Stratimikos_Belos_GCRODR_strattest_MPI_4 (Failed)
        1344 - Intrepid2_unit-test_Orientation_Serial_Test_Orientation_TET_MPI_1 (Failed)
        1380 - NOX_LOCA_AnasaziJacobianInverse_MPI_1 (Timeout)
        1381 - NOX_LOCA_AnasaziNotConverged_MPI_1 (Timeout)
        1454 - NOX_LOCA_MultiPointTcubed_MPI_2 (Failed)
        1482 - MueLu_UnitTestsTpetra_MPI_4 (Timeout)
        1594 - Stokhos_TpetraCrsMatrixUQPCEUnitTest_Cuda_MPI_4 (Failed)
        1604 - Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial_MPI_4 (Failed)
        1642 - ROL_NonlinearProblemTest_MPI_4 (Timeout)
        1647 - ROL_test_elementwise_TpetraMultiVector_MPI_4 (Failed)
        1651 - ROL_test_function_BlockOperatorCheck_MPI_1 (Not Run)
        1797 - PanzerAdaptersSTK_scatter_field_evaluator_MPI_1 (Failed)
```

**Comment by ndellingwood** [comment]
@crtrott Summary of build and test output posted.

**Comment by crtrott** [comment]
Ok considering Jims post we can go ahead and merge!!! The Teuchos::null thing in Panzer can be done later.

**Comment by crtrott** [comment]
Merged!!

**Comment by crtrott** [comment]
Nathan do you have the merge for Kokkos and KokkosKernels ready?

**Comment by crtrott** [comment]
I.e. is everything in develop and is it just a straightforward merge at this point?

**Comment by ndellingwood** [comment]
@crtrott I have the develop and master branches ready (on kokkos-dev) that we prepped for the snapshots into Trilinos. I don't have permissions to push them, how do we proceed?

**Comment by crtrott** [comment]
ok I open this up now so you can push, and then I close this again.

**Comment by crtrott** [comment]
OK Kokkos is open for you to push. Don't screw it up ;-)

**Comment by ndellingwood** [comment]
Kokkos is done!
Need permission still for KokkosKernels,
`remote: error: GH006: Protected branch update failed for refs/heads/develop.`

**Comment by crtrott** [comment]
ok opening up kokkos-kernels now.

**Comment by crtrott** [comment]
Try now.

**Comment by ndellingwood** [comment]
@crtrott I still need permission for the master branch on KokkosKernels, develop is done...

**Comment by crtrott** [comment]
Try again

**Comment by ndellingwood** [comment]
@crtrott develop and master branches updated in both Kokkos and KokkosKernels!

**Comment by crtrott** [comment]
Branches are closed again.

**Comment by crtrott** [comment]
Thanks Nathan for all the work on this !! Good job.

**Comment by ndellingwood** [comment]
Thanks for all the help!!

**Comment by mhoemmen** [comment]
YAY

**Comment by ibaned** [comment]
For what its worth, the checkin script run also passed.

**Pull request merged**
