### PR TITLE
Amesos : add Amesos::Create interface to CSS MKL

### PR DESCRIPTION
**Pull request by iyamazaki**
@trilinos/amesos

## Motivation

This PR adds ``Amesos::Create`` interface to CSS MKL

## Testing

Added CSS MKL to ``Test_Detailed``

### CODE REVIEW

**Comment by ndellingwood** [comment]
@trilinos/framework the cuda CI jobs did not post any results triggering the cdash failure, can you help advise?

**Review by ndellingwood — APPROVED** [review]
Looks reasonable, some reshuffling of routines from ctor to symbolic, renaming, variable fixups, etc.

**Comment by achauphan** [comment]
> @trilinos/framework the cuda CI jobs did not post any results triggering the cdash failure, can you help advise?

@ndellingwood from [Sam's older comment,](https://github.com/trilinos/Trilinos/pull/13102#issuecomment-2200033721), the cuda builds do not build or test any Epetra based packages.

As for the failing intel builds, it looks like the openmpi 4.1.4 module is now missing. I will look into this and put in a ticket.

**Comment by sebrowne** [comment]
Intel builds are now disabled, RETESTing.

**Review by ndellingwood — APPROVED** [review]

**Pull request merged**
