### PR TITLE
amesos2(cleaning): removing old type traits that are not supported by C++17

### PR DESCRIPTION
**Pull request by romintomasetti**
@trilinos/amesos2

## Motivation

I'm still working on that bug I mentioned in #12209.

I've removed old type traits that are now fully supported by C++17. Enjoy!

@iyamazaki

### CODE REVIEW

**Comment by maartenarnst** [comment]
Hi @iyamazaki and @srajama1, would you have a moment to look at this PR? Thanks in advance!

**Comment by sebrowne** [comment]
This branch MUST be rebased prior to merge given the 'develop' change (re-adds forbidden files).

**Review by sebrowne — CHANGES_REQUESTED** [review]
Please rebase to eliminate extraneous commits.

**Review by srajama1 — APPROVED** [review]
Thanks @maartenarnst @romintomasetti ! I approve the Amesos2 changes. Good to also make sure @etphipp is ok with stokhos changes as the scalar type there is different.

**Comment by maartenarnst** [comment]
Hi @etphipp! Would you have a moment to go over the changes in the Stokhos specialisations of Amesos2 for the PCE and ensemble types? The changes are about replacing the older Amesos2 `Meta::is_same` and `Meta::if_then_else` with `std::is_same` and `std::conditional`. Thanks in advance!

**Comment by maartenarnst** [comment]
Hi @sebrowne! Thanks for letting us know about the history change on this PR too. We did the rebase. However, as in the other PR, it seems GitHub is considering your suggestion to rebase as a request for changes. I don't know if that will block a merge. If it is blocking, would you have a moment to approve?

**Review by sebrowne — DISMISSED** [review]

**Review by etphipp — APPROVED** [review]
Stokhos changes look good to me.

**Comment by ndellingwood** [comment]
Here are a couple snips of compilation error output, two types of errors:

**Error 1**
```
Standard Error | In file included from ../Trilinos/packages/amesos2Amesos2_SolverCore.cpp:51: In file included from ../Trilinos/packages/amesos2Amesos2_SolverCore_def.hpp:59: In file included from ../Trilinos/packages/amesos2Amesos2_MultiVecAdapter_def.hpp:48: ../Trilinos/packages/amesos2Amesos2_TpetraMultiVecAdapter_def.hpp:270:7: error: use of undeclared identifier 'lda'       lda < requested_vector_length, std::invalid_argument,       ^ ../Trilinos/packages/amesos2Amesos2_TpetraMultiVecAdapter_def.hpp:273:50: error: use of undeclared identifier 'lda'       "communicator, the given stride lda = " << lda << " is not large enough "                                                  ^ 2 errors generated.
-- | --


Standard Error 	

In file included from ../Trilinos/packages/amesos2[Amesos2_SolverCore.cpp:51](https://github.com/trilinos/Trilinos//blob/master/Amesos2_SolverCore.cpp#L51):
In file included from ../Trilinos/packages/amesos2[Amesos2_SolverCore_def.hpp:59](https://github.com/trilinos/Trilinos//blob/master/Amesos2_SolverCore_def.hpp#L59):
In file included from ../Trilinos/packages/amesos2[Amesos2_MultiVecAdapter_def.hpp:48](https://github.com/trilinos/Trilinos//blob/master/Amesos2_MultiVecAdapter_def.hpp#L48):
../Trilinos/packages/amesos2[Amesos2_TpetraMultiVecAdapter_def.hpp:270](https://github.com/trilinos/Trilinos//blob/master/Amesos2_TpetraMultiVecAdapter_def.hpp#L270):7: error: use of undeclared identifier 'lda'
      lda < requested_vector_length, std::invalid_argument,
      ^
../Trilinos/packages/amesos2[Amesos2_TpetraMultiVecAdapter_def.hpp:273](https://github.com/trilinos/Trilinos//blob/master/Amesos2_TpetraMultiVecAdapter_def.hpp#L273):50: error: use of undeclared identifier 'lda'
      "communicator, the given stride lda = " << lda << " is not large enough "
                                                 ^
2 errors generated.
```

And here is the list of files where errors occur:

Amesos2 | lda error
-- | --
Amesos2 | Error building packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_SolverCore.cpp.o
Amesos2 | Error building packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_KLU2.cpp.o
Amesos2 | Error building packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_Lapack.cpp.o
Amesos2 | Error building packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_Tacho.cpp.o
Amesos2 | Error building packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_Superlu.cpp.o


**Error 2**
```
../Trilinos/packages/amesos2/test/adapters/Epetra_MultiVector_Adapter_UnitTests.cpp:148:19: error: no template named 'is_same'; did you mean 'std::is_same'?
    TEST_ASSERT( (is_same<double, ADAPT::scalar_t>::value) );
                  ^~~~~~~
                  std::is_same
[CTest: warning matched] ../Trilinos/packages/teuchos/core[Teuchos_LocalTestingHelpers.hpp:72](https://github.com/trilinos/Trilinos//blob/master/Teuchos_LocalTestingHelpers.hpp#L72):24: note: expanded from macro 'TEST_ASSERT'
  TEUCHOS_TEST_ASSERT( v1, out, success )
                       ^
[CTest: warning matched] ../Trilinos/packages/teuchos/core[Teuchos_TestingHelpers.hpp:309](https://github.com/trilinos/Trilinos//blob/master/Teuchos_TestingHelpers.hpp#L309):27: note: expanded from macro 'TEUCHOS_TEST_ASSERT'
    const bool l_result = v1; \
                          ^
[CTest: warning matched] /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../include[8.3.0/type_traits:1328](https://github.com/trilinos/Trilinos//blob/master/8.3.0/type_traits#L1328):12: note: 'std::is_same' declared here
    struct is_same
           ^
../Trilinos/packages/amesos2/test/adapters/Epetra_MultiVector_Adapter_UnitTests.cpp:149:19: error: no template named 'is_same'; did you mean 'std::is_same'?
    TEST_ASSERT( (is_same<int,    ADAPT::local_ordinal_t>::value) );
                  ^~~~~~~
                  std::is_same
[CTest: warning matched] ../Trilinos/packages/teuchos/core[Teuchos_LocalTestingHelpers.hpp:72](https://github.com/trilinos/Trilinos//blob/master/Teuchos_LocalTestingHelpers.hpp#L72):24: note: expanded from macro 'TEST_ASSERT'
  TEUCHOS_TEST_ASSERT( v1, out, success )
                       ^
[CTest: warning matched] ../Trilinos/packages/teuchos/core[Teuchos_TestingHelpers.hpp:309](https://github.com/trilinos/Trilinos//blob/master/Teuchos_TestingHelpers.hpp#L309):27: note: expanded from macro 'TEUCHOS_TEST_ASSERT'
    const bool l_result = v1; \
...
# Similar
```

And here is the list of files where errors occur:

Amesos2 | is_same error
-- | --
Amesos2 | Error building  packages/amesos2/test/adapters/CMakeFiles/Amesos2_Epetra_MultiVector_Adapter_UnitTests.dir/Epetra_MultiVector_Adapter_UnitTests.cpp.o
Amesos2 | Error building  packages/amesos2/test/adapters/CMakeFiles/Amesos2_Tpetra_MultiVector_Adapter_UnitTests.dir/Tpetra_MultiVector_Adapter_UnitTests.cpp.o
Amesos2 | Error building  packages/amesos2/test/adapters/CMakeFiles/Amesos2_Epetra_RowMatrix_Adapter_UnitTests.dir/Epetra_RowMatrix_Adapter_UnitTests.cpp.o
Amesos2 | Error building  packages/amesos2/test/adapters/CMakeFiles/Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests.dir/Tpetra_CrsMatrix_Adapter_UnitTests.cpp.o
Amesos2 | Error building packages/amesos2/test/solvers/CMakeFiles/Amesos2_KLU2_UnitTests.dir/KLU2_UnitTests.cpp.o

**Comment by maartenarnst** [comment]
Hi @ndellingwood. Thanks for giving us more details on the errors.

It seems the first group of errors comes from the fact that we had commented out a variable name in a function definition where this variable seemed unused. But it turned out that's not the case in a debug build. So, at all locations where this PR had made such a change for an unused variable, I've switched from commenting it out to using `[[maybe_unused]]`.

The second group of errors comes from the fact that a few uses of the old type trait `Meta::is_same` remained. I think I had already solved this issue in the previous commit. So my hypothesis is that you extracted the error messages from the log for the first run, without the second commit.

Hopefully things will work out now :) Would you have a moment to set it up for a retest? Thanks!

**Review by ndellingwood — APPROVED** [review]
Re-approving based on previous approvals (changes to the PR must have wiped the previous approvals)

**Pull request merged**
