### PR TITLE
Ifpack2: Fix #9400 and add test

### LINKED ISSUE #9400: Ifpack2 :  Gauss Seidel holds on to a host view of values of a matrix
## Bug Report
@trilinos/ifpack2
@csiefer2 @brian-kelley you two own this code based on git blame 
### Description
If you look at this constructor you can see that you grab a host copy of the values and that causes problems elsewhere

    at /scratch/mbetten/Trilinos/Trilinos/packages/ifpack2/src/Ifpack2_Details_GaussSeidel.hpp:132

```
    GaussSeidel(const bcrs_matrix_type& A, const InverseBlocks& inverseBlockDiag_, Teuchos::ArrayRCP<LO>& applyRows_, Scalar omega_)
    {
      numRows = A.getNodeNumRows();
      //note: next 2 lines are no-ops if inverseBlockDiag_ is already host-accessible
      inverseBlockDiag = Kokkos::create_mirror_view(inverseBlockDiag_);
      Kokkos::deep_copy(inverseBlockDiag, inverseBlockDiag_);
      applyRows = applyRows_;
      omega = omega_;
      auto AlocalGraph = A.getCrsGraph().getLocalGraphDevice();
      //A.sync_host();  //note: this only syncs values, not graph
      Avalues = A.getValuesHostNonConst();
//^^^^^ HERE ^^^^^^^
      Arowmap = Kokkos::create_mirror_view(AlocalGraph.row_map);
      Aentries = Kokkos::create_mirror_view(AlocalGraph.entries);
      Kokkos::deep_copy(Arowmap, AlocalGraph.row_map);
      Kokkos::deep_copy(Aentries, AlocalGraph.entries);
      blockSize = A.getBlockSize();
    }
```

should we make a copy? you do that elsewhere?  I'm not sure why it is doing this

This is causing muelu failures without UVM (like the last set so I'm ready to test).

### PR DESCRIPTION
**Pull request by brian-kelley**
@trilinos/ifpack2 

## Motivation

Relaxation's local Gauss-Seidel was breaking Tpetra's DualView rules by holding onto a persistent view of BlockCrsMatrix's values. Now, getting it from the matrix each apply.

Since this wasn't caught by testing before, made the unit test check if the preconditioner kept the values/graph views of CrsMatrix or BlockCrsMatrix at each step (construction, initialize() and compute()).

## Related Issues

* Closes #9400
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Stakeholder Feedback

Was a blocker for MueLu uvm removal.

## Testing

This case is now tested in Ifpack2.

### CODE REVIEW

**Comment by bathmatt** [comment]
I am testing that this fixes my issue, @brian-kelley

**Comment by bathmatt** [comment]
I confirm this fixed my issue.  Thank you lots @brian-kelley 
I'll approve the PR but probalby another ifpack2 guru should review

**Review by bathmatt — APPROVED** [review]
Confirmed this resolves the issue it was intended to fix,

**Review by csiefer2 — APPROVED** [review]

**Comment by bathmatt** [comment]
@brian-kelley are we ready to merge this?  
Thanks again for your help,

**Pull request merged**
