### PR TITLE
Small Tempus fixes to support ROL-Tempus interface

### PR DESCRIPTION
**Pull request by etphipp**
A couple small changes needed while creating a reduced-space interface for ROL with Tempus.

### CODE REVIEW

**Comment by etphipp** [comment]
I'm not sure why the auto tester keeps saying this failed.  The results on CDash say everything passed.  @trilinos/framework

**Comment by allevin** [comment]
@etphipp The first 2 runs failed on the Intel builds due to Git clone issues.  The last run, failed on gcc 4.8.4 due to a Git clone issue.  The CDash only reported the tests that ran.

**Comment by etphipp** [comment]
@trilinos/framework So what should we do here then?

**Comment by allevin** [comment]
@etphipp Set the AT: RETEST label and give it another go.

**Pull request merged**
