### PR TITLE
Framework: Split up the PR driver script

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework 	

This update partitions the old style PR driver script into two pieces:
1. Merge - This handles the merging of the incoming branch into the develop branch to prepare for testing.
2. Test  - This handles the actual execution of tests.

The most churn should be on the Test script, while the merge handler will generally be pretty stable. The purpose of this is to address chicken-and-egg issues with modifying the test driver script.

WIP: while doing some local testing.

### CODE REVIEW

**Comment by william76** [comment]
Kicked off a manual test in Jenkins... assuming it runs and submits to CDash, the results should be [here][1]

[1]: https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-11-10&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=3837

**Comment by william76** [comment]
@trilinos/framework 	
It looks like my test passed yesterday so I'll remove the WIP flag so the autotester can go ahead and test this.

@jwillenbring @prwolfe Let's go over the change in our meeting on Monday to make sure things look good this time before merging it.

**Comment by william76** [comment]
Updated the branch and kicked off a manual test on [Jenkins][1], cdash results should show up [here][2]

[1]: https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_pullrequest_gcc_4.9.3/2197/
[2]: https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PR-3837

**Comment by william76** [comment]
@trilinos/framework 	
@jwillenbring 	
@prwolfe 	

The manual test run passed on my fork.  I'll disable the `AT:WIP` flag so the autotester can test it, and it's probably time for you guys to have a look at the code and approve or request changes. Shoot me an email or @mention me if it's good so I can put in a test PR when we merge to catch any unforeseen issues that might come up.

**Comment by william76** [comment]
@prwolfe 	
I added in the modification you mentioned and the testing passed. Can I get a review when you have a chance :)

**Comment by prwolfe** [comment]
Done.

**Comment by william76** [comment]
A test PR, #3859, was entered after merging this to catch problems with the update if they occurred.  It looks like it ran through the tester and passed its tests.

**Pull request merged**
