### PR TITLE
STK: Snapshot 11-21-23 16:16 from Sierra 5.17.2-325-g069fd74a

### PR DESCRIPTION
**Pull request by alanw0**
@trilinos/<teamName>

### CODE REVIEW

**Comment by ldh4** [comment]
Looks like includes changes from Krino. Is this intended?

**Comment by alanw0** [comment]
> Looks like this pr includes changes from Krino. Is this intended?

Yes David Noble asked if we could include Krino with this snapshot.

**Comment by mperego** [comment]
There is now a check to make sure that packages do not assume the communicator to be `MPI_COMM_WORLD`. In the cases flagged in Krino, it makes sense to use `MPI_COMM_WORLD` as default communicator. 
My understanding is that it's enough to add
`// CHECK: ALLOW MPI_COMM_WORLD`
on the offending line to make the check pass.

**Review by ldh4 — APPROVED** [review]

**Comment by mperego** [comment]
Thanks @alanw0 . If it's not feasible to list all the details, can you at least mention the main changes?

**Pull request merged**
