### PR TITLE
Teuchos KokkosCompat: missing include, Kokkos::is_initialized

### PR DESCRIPTION
**Pull request by ibaned**
@trilinos/teuchos 

## Description

First, include `<functional>` in a file that uses `std::ref`. This error was being hidden by excessive includes in `Teuchos_ConfigDefs`, which @mhoemmen has been cleaning up. The need was revealed ultimately by this Albany dashboard:

http://my.cdash.org/viewBuildError.php?buildid=1324432

In addition, I noticed a function working around the lack of `Kokkos::is_initialized`, and changed it to call that function now that it exists.

## Motivation and Context

This change is required due to cleanups in the core of Teuchos to avoid compilation errors and also required for correct Kokkos initialization behavior (see kokkos/kokkos#1184).

## How Has This Been Tested?

None yet, will rely on new PR testing system or checkin script.

### CODE REVIEW

**Comment by ibaned** [comment]
Thanks @bartlettroscoe ! I'm going to treat this new PR AutoTester as the equivalent of the checkin script, so if it says okay, I'll click the merge button.

**Comment by ibaned** [comment]
Hmm... did it just restart testing because @bartlettroscoe approved the changes?
@jwillenbring could you clarify why we just got a second `STARTING` comment?

**Comment by ibaned** [comment]
Or was it due to my comment where I mentioned it, which triggered it to run again?

**Comment by jwillenbring** [comment]
>Hmm... did it just restart testing because @bartlettroscoe approved the changes?
@jwillenbring could you clarify why we just got a second STARTING comment?

@ibaned there are some network communication issues today between our network and GitHub and that essentially causes the driver job to lose track of the status of things and crash. @allevin has built into his tool a couple retries, but the network is particularly bad today apparently. He says he typically sees this once or twice a week, and it usually only causes a single complete crash, whereas here we have 2 already.

**Comment by jwillenbring** [comment]
@ibaned Fortunately the third attempt finished and passed.

**Comment by ibaned** [comment]
@jwillenbring excellent! thank you for looking at this with us.

Given that this pull request has passed the AutoTest and was approved by @bartlettroscoe , I'll go ahead and merge it.

**Pull request merged**
