### PR TITLE
Fix math precedence

### PR DESCRIPTION
**Pull request by ibaned**
@trilinos/teuchos 

## Description

Fix precedence of MathExpr operators

Fixed a couple of issues here:
1. The expression "-x^2" was being interpreted
   as "(-x)^2", I think most people expected
   "-(x^2)"
2. The expression "a^b^c" would have been interpreted
   as "(a^b)^c", whereas I think the expectation is
   "a^(b^c)".

## Motivation and Context

Correctness of initial conditions used by internal Sandia applications

Edit: @bartlettroscoe it is fairly non-trivial to check this with a unit test without building on code that is part of the application and not part of Teuchos.

### CODE REVIEW

**Comment by ibaned** [comment]
@bartlettroscoe It would actually take a significant amount of work to construct such a test... the code needed is not in Teuchos right now. This is also a serious bug, I'd like to if possible just merge the fix.

**Comment by bartlettroscoe** [comment]
> It would actually take a significant amount of work to construct such a test... the code needed is not in Teuchos right now. This is also a serious bug, I'd like to if possible just merge the fix.

@ibaned, I understand.  But for this to be sustainable code long-term, this stuff should be unit tested in Teuchos itself.

**Comment by ibaned** [comment]
@bartlettroscoe I managed to move some code over to generate a unit test. Note that I haven't run the unit test, so we should wait to see what the autotester says.

**Comment by ibaned** [comment]
It seems like the autotester has issues accessing GitHub right now... Hopefully @allevin and company are working on this

**Comment by bartlettroscoe** [comment]
> It seems like the autotester has issues accessing GitHub right now... Hopefully @allevin and company are working on this

FYI: I logged this as part of the larger issue #3276 at https://github.com/trilinos/Trilinos/issues/3276#issuecomment-413682726.

**Pull request merged**
