### PR TITLE
Restructure PR template

### PR DESCRIPTION
**Pull request by prwolfe**
This is what I came up with after our discussion on Wednesday. It looks better to me and is much slimmer without actually removing the less used pieces but instead leaves them in the comments.

Darts welcome ;->

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Would it be better to just have this template be very sparse and have it point to a GitHub wiki page that describes these various details?  I personally find it hard to wade through all of these comments and sections and end up starting from scratch with something very simple.

**Comment by tjfulle** [comment]
My experience/opinion is similar to @bartlettroscoe

**Comment by prwolfe** [comment]
That matches the intent here - it is a lot more readable now and takes up less space.

**Comment by william76** [comment]
/agree with @mhoemmen ... yay for fewer words.

What's _required_ on a PR?   Generally I would think of team mentions and probably individuals if possible too... anything required by policy on Trilinos should probably default to uncommented... optional stuff maybe stay commented?

**Pull request merged**
