### PR TITLE
Tempus: Add Ability to Get the RK Stage Number

### LINKED ISSUE #6993: Tempus:  Add Ability to Get the RK Stage Number
## Enhancement
@trilinos/tempus 

Started an RK base class for RK methods and member data.  First methods are related to getting and setting the stage number of the RK method.

### PR DESCRIPTION
**Pull request by ccober6**
Started an RK base class for RK methods and member data.
First methods are related to getting and setting the stage
number of the RK method.

Added simple test to ensure get/set are working.

All tests pass on Mac CLANG.

@trilinos/tempus 

* Closes  #6993

### CODE REVIEW

**Comment by ccober6** [comment]
@krcb @sconde FYI, this is backward compatible with EMPIRE.  Turning on Automerge, so go through after approval.

**Comment by sconde** [comment]
@ccober6 `StepperRKBase` should also have accessor to `stageX`

**Comment by krcb** [comment]
@ccober6 Could you add a unit test that demonstrates accessing the stage number from an explicit RK scheme using an observer and check that stage number returned is correct?

**Comment by sconde** [comment]
I've pushed the changes to the branch `6993-Tempus-Get-the-RK-Stage-Number-stage-x`

Going to test these changes on all the other APPS now.

**Comment by sconde** [comment]
@krcb I've attempted to add the test for ERK. Please let me know if this is enough.

**Comment by ccober6** [comment]
> @ccober6 `StepperRKBase` should also have accessor to `stageX`

@sconde I agree!  But I did not want to have issue creep with getting the accessor for the stage number.

**Pull request merged**
