### PR TITLE
Ifpack2: fix build with complex<float>

### PR DESCRIPTION
**Pull request by brian-kelley**
Use magnitude type, not double, since you can't directly multiply ``complex<float>`` by double

@trilinos/ifpack2 

## Motivation
#11845

### CODE REVIEW

**Comment by jhux2** [comment]
@brian-kelley Thanks.  I'm puzzled, though, as to why this wasn't caught in PR or nightly testing.

**Comment by brian-kelley** [comment]
@jhux2 Skimming the build list on cdash, it looks we have builds that do complex<double> but none with complex<float>.

@trilinos/framework Is it possible to create a new build with float/complex<float> enabled, or add them to an existing build? If it's a non-CUDA build, it doesn't appear to increase the parallel build time that much.

**Comment by jhux2** [comment]
> you can't directly multiply complex<float> by double

> Skimming the build list on cdash, it looks we have builds that do complex<double> but none with complex<float>.

Yes, I should have read your comment more carefully :P.

**Comment by brian-kelley** [comment]
@jhux2 You probably read it correctly the first time, I didn't know stuff in angle brackets dissapears unless you make it ``code style``. I fixed it a minute ago

**Comment by jennloe** [comment]
Note: I've confirmed that this PR fixes issue #11845.

**Comment by jennloe** [comment]
Linking to issue #10742

**Pull request merged**
