### PR TITLE
Teuchos: fix for #4145

### PR DESCRIPTION
**Pull request by rppawlo**
Addresses #4145.

### CODE REVIEW

**Comment by rppawlo** [comment]
@mhoemmen - I'm just being consistent with how Teuchos::Time implemented support for kokkos profiling. According to git blame it was you that added both macros ;)

```
6892e170 packages/teuchos/core/src/Teuchos_Time.cpp (Mark Hoemmen          2018-02-21 16:43:02 -0700  81) #if defined(HAVE_TEUCHOS_KOKKOS_PROFILING) && defined(HAVE_TEUCHOSCORE_KOKKOSCORE)
```

**Comment by rppawlo** [comment]
@mhoemmen - I take that back. You were the last to modify that line but @cgcgcg initially added it. It looks like we needed to enable kokkos yet disable the profiling for some reason.

**Comment by rppawlo** [comment]
@bartlettroscoe - it looks like profiling is disabled in all atdm builds:
```
S1002730:atdm rppawlo$ find . -name '*' | xargs grep -is PROF
./ATDMDevEnvSettings.cmake:ATDM_SET_CACHE(Kokkos_ENABLE_Profiling OFF CACHE BOOL)
```
This flag should probably be added to one of the PR testing builds.

**Comment by mhoemmen** [comment]
@rppawlo wrote:
> It looks like we needed to enable kokkos yet disable the profiling for some reason.

Let's find out that reason -- Kokkos profiling is supposed to be extremely low overhead, and Tpetra uses Kokkos profiling regions quite a bit, so I think y'all could benefit from turning it on.  If it's broken, we would like to fix it :)

**Pull request merged**
