### PR TITLE
ATDM/ats2: Update to CMake 3.18

### PR DESCRIPTION
**Pull request by e10harvey**
## How was this tested?
Via atdm-nightly. See [cdash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-01-13&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=ats2) for results.

### CODE REVIEW

**Review by jmgate — APPROVED** [review]
Looks good to me.  Do we need a review from SPARC?

**Comment by e10harvey** [comment]
> Looks good to me. Do we need a review from SPARC?

@bartlettroscoe can you chime in here?

I'm ready to merge once the nightlies are done posting to [cdash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-01-12&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=ats2) assuming that no major regressions show up.

**Comment by bartlettroscoe** [comment]
@jmgate, has this been tested?

**Comment by bartlettroscoe** [comment]
I mean @e10harvey, has this been tested?

**Comment by bartlettroscoe** [comment]
I do worry this might mess things up from SPARC but the risk should be low.

**Comment by e10harvey** [comment]
> I mean @e10harvey, has this been tested?

Partially. I merged this change into atdm-nightly last night and tests are still running as shown by [cdash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-01-12&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=ats2).

**Pull request merged**
