### PR TITLE
Issue #1178 (ROL build failure on Windows)

### PR DESCRIPTION
**Pull request by mplooster**
@trilinos/rol 
@trilinos/teuchos 

Added some defines to enable using the M_PI constant.
Changed a gcc-specific 'xor' to standard c++ operator ^.

### CODE REVIEW

**Comment by dridzal** [comment]
From the @trilinos/rol team:  The changes look fine, however, I wonder if this is the best way to handle Windows.  This approach results in a proliferation of platform-dependent preprocessor directives.  Is there a more automated way to handle this for all of Trilinos packages?  For example, can one define some macros (or something else) in Teuchos that could be used across Trilinos?

**Comment by mplooster** [comment]
@dridzal I could do the define once in a config file, and then include the config file before including <cmath> or <math.h>, which would achieve the same result.

@trilinos/framework Would it be beneficial to put this in a config file other than the ROL config file (for example, in Teuchos as was suggested)? So far ROL is the only package I've seen that has this particular issue with math defines, but other packages might benefit from it in the future.

**Comment by dridzal** [comment]
Hmm, I wonder why ROL is the only package with this issue ... are we maybe not using some Teuchos feature that everyone else knows about?  @trilinos/framework , could you take a look at the proposed code changes in ROL and let @trilinos/rol know if we've missed some Teuchos feature?

**Comment by mplooster** [comment]
@dridzal @trilinos/framework I should also mention that it is M_PI in particular that is causing build errors.

**Comment by ibaned** [comment]
A quick search of Trilinos reveals `M_PI` is commonly used and commonly worked around. Lots of example files use it, but usage in library source/headers is more rare. Anasazi seems to have workarounds, see [this](https://github.com/trilinos/Trilinos/blob/master/packages/anasazi/epetra/util/ModeLaplace/ModeLaplace2DQ2.cpp#L57) for example. It sounds like [this tribits file](https://github.com/trilinos/Trilinos/blob/master/cmake/tribits/win_interface/include/winmath.h#L20) is supposed to be the official workaround, although not everyone uses it yet. Also it seems to need [protection](https://github.com/trilinos/Trilinos/blob/f0350316239aaf41e8e6b82378612aaedf9cc72c/packages/sacado/test/tradoptest/tradoptest_43.cpp#L12), it might be nice if that conditional were moved into the file itself.

**Comment by mplooster** [comment]
So, here are the options that I see.

1. Use the proposed fix.
2. Change it to use a config file.
3. Change it to use the official workaround (include winmath.h, which in its present form still requires a platform specific preprocessor directive).
4. Create some ROL specific define for M_PI and replace M_PI with that.

What would the @trilinos/rol team like to have happen?

**Comment by bartlettroscoe** [comment]
> It sounds like [this tribits file](https://github.com/trilinos/Trilinos/blob/master/cmake/tribits/win_interface/include/winmath.h#L20) is supposed to be the official workaround, although not everyone uses it yet.

That file was written by Kitware (I think Bill Hoffman himself) to help Trilinos port to Windows many years ago (like 8 or 9 years ago).  I see no reason that it should not be used and/or expended on to help with portability to Windows.

In general, we need to push includes down to the lowest level source files to improve build times (see #351).

**Comment by mplooster** [comment]
> In general, we need to push includes down to the lowest level source files to improve build times (see #351).

Indeed, this is part of the reason I had to make a change to Teuchos_ConfigDefs.hpp in the first place. I will try removing my change from Teuchos_ConfigDefs.hpp, and use winmath.h in ROL instead.

**Comment by mplooster** [comment]
@trilinos/rol With this additional commit, are the changes acceptable?

**Comment by dridzal** [comment]
This looks good, and I'll go ahead and merge.  One last question:  Can we define a one-line macro instead of the five lines that select winmath.h or cmath?

**Comment by mplooster** [comment]
@dridzal Thanks. To answer your question, the problem is that macros can't be expanded into other pre-processor directives. See [here](http://stackoverflow.com/questions/2429240/c-preprocessor-macro-defining-macro) and [here](http://stackoverflow.com/questions/3314032/is-there-a-way-to-do-a-define-inside-of-another-define) where some people have asked that very question. IMO, the best way to achieve this would be to rename winmath.h to trilinos_math.h (or tribits_math.h) and do the conditional define and switch in that header file. Then, everyone could just include trilinos_math.h and get what they need consistently across platforms.

**Comment by dridzal** [comment]
That is a great idea!  @trilinos/framework -- what do you think?

**Comment by jjellio** [comment]
Perhaps Teuchos ScalarTraits<T> should define PI? And, M_PI should be deprecated in favor of using the Traits classes.

**Comment by bartlettroscoe** [comment]
>  IMO, the best way to achieve this would be to rename winmath.h to trilinos_math.h (or tribits_math.h) and do the conditional define and switch in that header file. Then, everyone could just include trilinos_math.h and get what they need consistently across platforms.

I am fine with that.  If you create a PR on github.com/TriBITSPub/TriBITS/ for the needed changes.  Details at:

* https://github.com/TriBITSPub/TriBITS/wiki/Develop-on-TriBITS-for-Trilinos

**Comment by bartlettroscoe** [comment]
> Perhaps Teuchos ScalarTraits should define PI? And, M_PI should be deprecated in favor of using the Traits classes.

I would vote for that.  Seems cleaner and it would extend to all scalar types.

**Comment by mplooster** [comment]
@jjellio @bartlettroscoe [Teuchos_Utils.hpp](https://github.com/trilinos/Trilinos/blob/4bfc9e957053212d76db4b09c9b66bbbeeaa80a9/packages/teuchos/core/src/Teuchos_Utils.hpp) already has a pi() function. Should we just use that?

**Comment by bartlettroscoe** [comment]
> Teuchos_Utils.hpp already has a pi() function. Should we just use that?

That class Teuchos::Utils was put there to support some other legacy code that was copied over a long time ago.  It is not used much even in Teuchos and there are zero unit tests as shown by:

```
[rabartl@crf450 Trilinos (develop)]$ find packages/teuchos -name "*pp" -exec grep -nH Utils:: {} \; | grep -v StrUtils | grep -v HashUtils
packages/teuchos/core/test/MemoryManagement/Array_UnitTests.cpp:71:  TEST_EQUALITY(Teuchos::Utils::trimWhiteSpace(""), "");
packages/teuchos/core/src/Teuchos_Utils.cpp:47:double Utils::chopVal_ = 1.0e-16;
packages/teuchos/core/src/Teuchos_Utils.cpp:49:double Utils::chop(const double& x)
packages/teuchos/core/src/Teuchos_Utils.cpp:55:std::string Utils::trimWhiteSpace( const std::string& str )
packages/teuchos/core/src/Teuchos_Utils.cpp:83:std::string Utils::toString(const int& x)
packages/teuchos/core/src/Teuchos_Utils.cpp:90:std::string Utils::toString(const unsigned int& x)
packages/teuchos/core/src/Teuchos_Utils.cpp:97:std::string Utils::toString(const double& x)
packages/teuchos/core/src/Teuchos_Utils.cpp:104:std::string Utils::getParallelExtension(
packages/teuchos/core/src/Teuchos_Array.hpp:719:  data = Utils::trimWhiteSpace(data);
packages/teuchos/core/src/Teuchos_Array.hpp:1577:  const std::string str = Utils::trimWhiteSpace(arrayStr);
packages/teuchos/core/src/Teuchos_Array.hpp:1605:    entryStr = Utils::trimWhiteSpace(entryStr);
packages/teuchos/parameterlist/src/Teuchos_StandardParameterEntryValidators.cpp:321:    return Utils::toString(any_cast<int>(anyValue));
packages/teuchos/parameterlist/src/Teuchos_StandardParameterEntryValidators.cpp:323:    return Utils::toString(any_cast<double>(anyValue));
```

I am not sure I would build a wide dependency on that class.

**Comment by mplooster** [comment]
Got it. I'm not very familiar with the Teuchos ScalarTraits. Is it a simple matter of adding a pi function in [Teuchos_ScalarTraitsDecl.hpp](https://github.com/trilinos/Trilinos/blob/f0350316239aaf41e8e6b82378612aaedf9cc72c/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp) that will be cast to the templated type, or would I return notDefined (like most of the functions), then reimplement it with an actual value for appropriate structs in [Teuchos_ScalarTraits.hpp](https://github.com/trilinos/Trilinos/blob/f0350316239aaf41e8e6b82378612aaedf9cc72c/packages/teuchos/core/src/Teuchos_ScalarTraits.hpp)?

**Comment by bartlettroscoe** [comment]
> Is it a simple matter of adding a pi function in Teuchos_ScalarTraitsDecl.hpp that will be cast to the templated type, or would I return notDefined (like most of the functions), then reimplement it with an actual value for appropriate structs in Teuchos_ScalarTraits.hpp?

The latter.  You need to provide an implementation of pi() that return Pi for every scalar type that can support it.   For example, you may not need to supply an implementation if `isOrdinal` is true (since Pi would not be very helpful rounded to an integer :-) ).

The Teuchos::ScalarTraits class is what Trilinos has standardized on for getting access to numeric information across various numeric types and platforms.  So I think that is the right place to define py().  Teuchos::ScalarTraits is used in a lot of Trilinos code as shown by:

```
$ find packages -type f -exec grep ScalarTraits {} \; | wc -l
7992
```

Does that make sense?

**Comment by mplooster** [comment]
It does indeed. I will try to do it that way. Thanks!

**Comment by mhoemmen** [comment]
There's a bit of a risk in adding new functions to Teuchos::ScalarTraits, because it's a traits class.  That means users may have specialized it for their Scalar types, which we can't see.  Adding a pi() method to ScalarTraits could cause build errors for those users.

**Comment by bartlettroscoe** [comment]
> There's a bit of a risk in adding new functions to Teuchos::ScalarTraits, because it's a traits class. That means users may have specialized it for their Scalar types, which we can't see. Adding a pi() method to ScalarTraits could cause build errors for those users.

This should not break anything since no current Trilinos packages use Teuchos::ScalarTraits::pi() (because it does not exist).  Therefore, adding this should be fine.  Does that make sense?  How would this break existing user code?

**Comment by mhoemmen** [comment]
Never mind, that makes sense, thanks.

**Comment by bartlettroscoe** [comment]
Also I doubt many people are using custom scalar types with Trilinos.  I bet you could count them on one hand.

**Comment by mplooster** [comment]
Here is another thing to consider. Doing a quick search of Trilinos, I can see that M_PI is used in about 1,900 places. Does adding this to Teuchos::ScalarTraits mean that eventually all of those places need to change? Will replacing a literal with a function call result in any kind of significant performance hit?

**Comment by mplooster** [comment]
I guess they are inline functions, so performance probably won't be an issue. However, the question still stands about replacing M_PI everywhere it is used.

**Comment by dridzal** [comment]
The @trilinos/rol team would welcome this change.

**Comment by bartlettroscoe** [comment]
I would say to do the following:

* For packages that already have a required dependency on Teuchos and use Teuchos::ScalarTraits::pi()
* For packages that don't already have a required dependency on Teuchos, just use the macro M_PI

And yes, these functions are inlined so there should be zero performance overhead to using Teuchos::ScalarTraits:pi().  If a C++ compiler can't inline that, then the whole program is going to run dirt slow anyway.

**Comment by mhoemmen** [comment]
Please note that Teuchos has customers who need to build with C++98, so please don't use `constexpr` or other C++11 features unless you protect them with the appropriate macro.

**Comment by mplooster** [comment]
@mhoemmen I don't think I did. Did I break something?

**Pull request merged**
