### PR TITLE
Framework: Add guard to PR test driver script to restrict PR's into master

### LINKED ISSUE #4037: Framework: Update PR testing script to prevent PR's to master from any branch other than develop
@trilinos/framework 
@william76 

Add a guard in the PR test driver script to auto-fail any Pull Request with `master` as the destination branch if the source branch is anything other than `develop`.

This will prevent accidentally getting PR's from a topic branch directly to master without going through develop first.

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework 

Since we added develop -> master PR testing, it has come up that it's possible to create a PR into the master branch from a topic branch.  This is not desired since the proper progression for code into the master branch is via the develop branch.  i.e., (topic branch) -[testing]-> (develop) -[more testing]-> (master) . 

This adds a constraint check into the PR test driver script that will do the following:
- FAIL any test where the DESTINATION is trilinos/Trilinos::master IF the source branch is not trilinos/Trilinos::develop
- Print out a useful message to the console log on Jenkins which will be visible in the console output snippet that gets posted to the PR by the autotester.

This will prevent PR's from accidentally being sent to the master branch rather than the develop branch, which can be easily missed.

### How this was tested

I prototyped this in a stand-alone script:

```bash
#!/usr/bin/env bash

TRILINOS_SOURCE_REPO="https://github.com/trilinos/Trilinos"
TRILINOS_SOURCE_BRANCH="develop"
#TRILINOS_SOURCE_REPO="https://github.com/rhoope/Trilinos"
#TRILINOS_SOURCE_BRANCH="issue_1909_Epetra64_gaps"
TRILINOS_TARGET_REPO="https://github.com/trilinos/Trilinos"
# TRILINOS_TARGET_BRANCH="master"
TRILINOS_TARGET_BRANCH="develop"

echo -e "Parameters:"
echo -e "- TRILINOS_SOURCE_BRANCH: ${TRILINOS_SOURCE_BRANCH:?}"
echo -e "- TRILINOS_SOURCE_REPO  : ${TRILINOS_SOURCE_REPO:?}"
echo -e ""
echo -e "- TRILINOS_TARGET_BRANCH: ${TRILINOS_TARGET_BRANCH:?}"
echo -e "- TRILINOS_TARGET_REPO  : ${TRILINOS_TARGET_REPO:?}"
echo -e ""

# Test the branch constraints for a Pull Request:
# - Only pull requests from trilinos/Trilnos::develop are allowed
#   to go into trilinos/Trilinos::master.  This check will help
#   reduce accidental PR's into master directly.
#
# Parameters:
#    src_repo   - Source repository of the PR (i.e., https://github.com/trilinos/Trilnos.git)
#    src_branch - Branchname from the source repository.
#    dst_repo   - Destination repository url
#    dst_branch - Branchname in the destination repository
#
# On error, this function will exit the script with error code 99.
#
function test_pr_constraints_master()
{
    src_repo=${1:?}
    src_branch=${2:?}
    dst_repo=${3:?}
    dst_branch=${4:?}

    echo -e "------------------------------------------------------------------------------------------"

    re_trilinos_url="(git@github.com:|https:\/\/github.com\/){1}trilinos\/Trilinos(\.git)?$"

    if [[ "${dst_repo:?}" =~ ${re_trilinos_url:?} ]] && [[ "${dst_branch:?}" == "master"  ]]
    then
        echo -e "NOTICE: Destination branch is trilinos/Trilnos::master"

        if [[ ! "${src_repo:?}" =~ ${re_trilinos_url:?} ]] || [[ ! "${src_branch:?}" == "develop" ]]
        then
            echo -e "ERROR : Source branch is NOT trilinos/Trilinos::develop"
            echo -e "      : This violates Trilinos policy, pull requests into the master branch"
            echo -e "      : are only allowed from the develop branch."
            echo -e "      : Perhaps you forgot to specify the develop branch as the target in your PR?"
            echo -e "------------------------------------------------------------------------------------------"
            echo -e ""
            exit 99
        else
            echo -e "NOTICE: Source branch IS trilinos/Trilinos::develop"
            echo -e "      : This is allowed, proceeding with testing."
        fi
    else
        echo -e "NOTICE: Destination branch is NOT trilinos/Trilinos::master"
        echo -e "      : PR testing will proceed."
    fi
}
test_pr_constraints_master ${TRILINOS_SOURCE_REPO:?} ${TRILINOS_SOURCE_BRANCH:?} \
                           ${TRILINOS_TARGET_REPO:?} ${TRILINOS_TARGET_BRANCH:?}
echo -e "Script Completed Successfully."
```

And I ran a series of tests using my jenkins simulator to test out the script responses.  The only condition I was not able to test in my simulated jenkins were PR's from develop to master since my scripts pull down the triinos/Trilinos::develop branch, which does not currently have this update.  Testing <branch> -> develop and <branch> -> master gave the expected results, allowing and failing the tests respectively.  

## Examples:

Console output snips from testing <topic branch> to <develop>, which should pass the constraint check:
```
TRILINOS_SOURCE_BRANCH: fmwk-pr-limit-master
TRILINOS_SOURCE_REPO  : https://github.com/william76/Trilinos
TRILINOS_SOURCE_SHA   : 4236c1db

TRILINOS_TARGET_BRANCH: develop
TRILINOS_TARGET_REPO  : https://github.com/trilinos/Trilinos
TRILINOS_TARGET_SHA   : 60186de0
...
------------------------------------------------------------------------------------------
NOTICE: Destination branch is NOT trilinos/Trilinos::master
      : PR testing will proceed.
------------------------------------------------------------------------------------------
```

Console output snips from testing <topic branch> to <master>, which fails the constraint check:
```
TRILINOS_SOURCE_BRANCH: fmwk-pr-limit-master
TRILINOS_SOURCE_REPO  : https://github.com/william76/Trilinos
TRILINOS_SOURCE_SHA   : 4236c1db

TRILINOS_TARGET_BRANCH: master
TRILINOS_TARGET_REPO  : https://github.com/trilinos/Trilinos
TRILINOS_TARGET_SHA   : 0cf3287f
...
------------------------------------------------------------------------------------------
NOTICE: Destination branch is trilinos/Trilnos::master
ERROR : Source branch is NOT trilinos/Trilinos::develop
      : This violates Trilinos policy, pull requests into the master branch
      : are only allowed from the develop branch.
      : Perhaps you forgot to specify the develop branch as the target in your PR?
------------------------------------------------------------------------------------------
```

Closes #4037 

@jwillenbring 
@prwolfe

### CODE REVIEW

**Comment by william76** [comment]
@prwolfe If a PR fails this check because someone accidentally creates a <topic branch> -> master request the developer will see this in the last 100 lines of console output that the autotester puts into the pull request.  They'd see the error notice that I showed in the snippet above since it's basically the last thing that the script will print before exiting with an error code:
```
------------------------------------------------------------------------------------------
NOTICE: Destination branch is trilinos/Trilnos::master
ERROR : Source branch is NOT trilinos/Trilinos::develop
      : This violates Trilinos policy, pull requests into the master branch
      : are only allowed from the develop branch.
      : Perhaps you forgot to specify the develop branch as the target in your PR?
------------------------------------------------------------------------------------------
```

**Comment by prwolfe** [comment]
Perfect – Thanks!

-----------------------------------------------------------------------
Recommending policy and creating automation to
enable DevOps in the Trilinos and CTH organizations.

**Comment by william76** [comment]
I fixed an error that popped up from my updates to this script.  Turns out, when I added:

```bash
echo -e "COMPILER_MODULE       : ${COMPILER_MODULE:?}"
echo -e "MPI_MODULE            : ${MPI_MODULE:?}"
echo -e "JENKINS_BUILD_TYPE    : ${JENKINS_BUILD_TYPE:?}"
echo -e "JENKINS_COMM_TYPE     : ${JENKINS_COMM_TYPE:?}"
echo -e "JENKINS_JOB_TYPE      : ${JENKINS_JOB_TYPE:?}"
echo -e "JENKINS_DO_COMPLEX    : ${JENKINS_DO_COMPLEX:?}"
``` 

the test failed because all the PR testng jobs didn't have the same set of parameters... so these failed the null-or-not-set check.

I updated the script to just require these parameters have been set, but can be null and I noted that these parameters aren't currently used.  I also updated the jenkins jobs so that they all have a consistent set of parameters.

| parameters | ignored? | gcc 4.8.4 | gcc 4.9.3 | gcc 4.9.3 Serial | gcc 7.2.0 | intel 17.0.1 |
| ----------- | :---------: | :---------: | :----------: | :---------------: | :---------: | :----------: |
| COMPILER_MODULE | X | X | X | X | X | X |
| MPI_MODULE |  X | X | X | X | X | X |
| JENKINS_BUILD_TYPE | X | X | X | X | X | X |
| JENKINS_COMM_TYPE | X | X | X | X | X | X |
| JENKINS_JOB_TYPE | X | X | X | X | X | X |
| JENKINS_DO_COMPLEX | X | X | X | X | X | X |
| | | X | X | X | X | X |
| | | X | X | X | X | X |
| | | X | X | X | X | X |
| | | X | X | X | X | X |
| | | X | X | X | X | X |
| | | X | X | X | X | X |

**Comment by william76** [comment]
Whether or not we should hang onto the parameters that are ignored by the PR testing or not is probably a different discussion - I think these got grandfathered in from the older parameterized builds, which do use those parameters.  

@prwolfe @jwillenbring @ZUUL42 when you get a chance, can I get a review on this PR :)

**Comment by william76** [comment]
Thanks!

**Comment by william76** [comment]
Yeah, I updated them all so they have the same set of parameters, but we might want to make a pass through and get rid of the ones that aren't used by the scripts the tester drives. :)

**Comment by william76** [comment]
@prwolfe @jwillenbring @ZUUL42 requesting a review.

**Pull request merged**
