### PR TITLE
Fix unused parameter warnings

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by mhoemmen** [comment]
@trilinos/teuchos 

Thanks @davydden !  Would you mind making this a pull request against our develop branch, rather than against master?  If it's too much trouble, don't worry, we could just cherry-pick the commits.

Also, I'm curious -- did you actually enable the Hypre TPL when fixing those warnings?  I think we might have more regular tests against Hypre now, but I'm not sure.  @amklinv , would you happen to know?

**Comment by davydden** [comment]
> Would you mind making this a pull request against our develop branch

done.

>  did you actually enable the Hypre TPL when fixing those warnings

yes, I see those warnings when compiling my code which uses deal.II which uses trilinos.

**Comment by mhoemmen** [comment]
@davydden wrote:
> yes, I see those warnings when compiling my code which uses deal.II which uses trilinos.

Awesome, thanks for testing this!

**Comment by mhoemmen** [comment]
I FIGHT FOR THE USERS
https://www.youtube.com/watch?v=DkTb7Pe2MtY

**Comment by davydden** [comment]
@mhoemmen is looks like this fix is not in the release versions of Trilinos, namely the most recent `12.10.1` still produce warnings. Could you please cherry-pick the two commits where appropriate to silence those warnings once and for all? Thank you advance.

**Pull request merged**
