### PR TITLE
Stratimikos Belos adapter: Do not filter Belos errors

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/stratimikos @trilinos/belos 

## Description
The Belos adapter in Stratimikos should not filter out all Belos errors, but let the user know that something went wrong. 

## Related Issues

* Adresses #2983

### CODE REVIEW

**Comment by cgcgcg** [comment]
@mhoemmen Yes, that's correct. I believe the use case for filtering out all exceptions was to use this within a time stepper. When UNCONVERGED is returned, the time step is reduced. However, I don't think that the Stratimikos adapter is the place where the exception should be caught. Also, it's not great that all the output that you get when something goes wrong is that the solver has not converged, without any justification. This PR is my quick hack to at least see the Belos error message..

**Comment by mhoemmen** [comment]
@cgcgcg Does this change need to go into Trilinos develop for now, or is this just for local experimentation?

**Comment by cgcgcg** [comment]
@mhoemmen It's not urgent for me to get it into develop, but I think that something does need to be changed. It's quite frustrating from a user perspective when all the output you get is that the solver did not converge in 10 iterations, but you set a maximum iteration count of 40.

**Comment by mhoemmen** [comment]
I would feel better if @bartlettroscoe or @rppawlo had some input into this.  My personal view is that we should spend a little more effort on Stratimikos' interface so that common issues like these become return codes.  I don't agree with how Belos handles this, either.  However, if this is what we have to do, it's what we have to do.

**Comment by cgcgcg** [comment]
@rppawlo I don't think that Belos throws an exception when the solver did not converge, or am I misunderstanding? From the look of it, it simply returns the status `Belos:Unconverged`.

**Comment by mhoemmen** [comment]
@rppawlo I think what @cgcgcg wants to do, is not lose information like "GMRES encountered a NaN."  I think the right way to propagate such information is by returning a status code in some way, not by throwing an exception.  

@cgcgcg I think what @rppawlo is trying to say, is that nonlinear solvers commonly encounter failed linear solves, and that linear solves commonly fail for reasons like "GMRES encountered a NaN," as well as for reasons like "reached maximum iteration count without converging."  Nonlinear solvers have ways to deal with transiently failing linear solves.  However, I agree that it would be useful to know _why_ a linear solve failed.

**Comment by bartlettroscoe** [comment]
I think all of this is addressed in:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1LinearOpWithSolveBase.html#LOWSB_solve_status_sec
* https://trilinos.org/docs/dev/packages/thyra/doc/html/classThyra_1_1LinearOpWithSolveBase.html#ac7c5b4c8553833778e88e3fb627c4009

Extra information that a human would want to read should be put into the `Thyra::SolveStatus<Scalar>::message` field:

* https://trilinos.org/docs/dev/packages/thyra/doc/html/structThyra_1_1SolveStatus.html#a5e0a6a08d4d9a1733869c78f91b735c1

If you really want to dump lots of info about the attempted solve, you can put that in string parameters in `Thyra::SolveStatus<Scalar>::extraParameters` and then the client can print that with a verbose print option.

Does that sound reasonable?

**Comment by cgcgcg** [comment]
Looking at the documentation that @bartlettroscoe linked, it seems to me that catching `BelosError` and raising `CatastrophicSolveFailure` is the correct approach. If we agree on that, I will merge this PR.

**Comment by mhoemmen** [comment]
It's up to Ross -- I'm not quite certain of the Stratimikos idioms.

**Comment by bartlettroscoe** [comment]
> Looking at the documentation that @bartlettroscoe linked, it seems to me that catching `BelosError` and raising `CatastrophicSolveFailure` is the correct approach. If we agree on that, I will merge this PR.

Yes, is the solver can't many any progress on solving the linear system it should throw `CatastrophicSolveFailure`.

**Comment by cgcgcg** [comment]
@mhoemmen Thanks!

**Pull request merged**
