### PR TITLE
MueLu: add convergence check for some scaling driver tests

### PR DESCRIPTION
**Pull request by jhux2**
Add check for convergence for some scaling driver based tests.

@trilinos/muelu

## Motivation

Even if tests fail to converge, ctest reports the test as passing.

## Stakeholder Feedback

N/A

## Testing

I confirmed locally that with this change, a test that doesn't converge is reported as failing.

### CODE REVIEW

**Review by cgcgcg — APPROVED** [review]

**Review by GrahamBenHarper — DISMISSED** [review]

**Comment by mayrmt** [comment]
Would it make sense and would it be possible to also check for the number of iterations? Otherwise, Belos could converge, even if the preconditioner does something weird.

**Review by cgcgcg — DISMISSED** [review]

**Comment by jhux2** [comment]
> Would it make sense and would it be possible to also check for the number of iterations? Otherwise, Belos could converge, even if the preconditioner does something weird.

Yes.  This could in principle be done on a per-test basis by setting a max number of iterations at the command line.

**Review by mayrmt — APPROVED** [review]

**Comment by jhux2** [comment]
> Would it make sense and would it be possible to also check for the number of iterations? Otherwise, Belos could converge, even if the preconditioner does something weird.

@mayrmt Thanks for the suggestion, I've added iteration counts.

**Comment by cgcgcg** [comment]
@jhux2 Did you add some fudge factor to the iteration counts on your system?

**Comment by jhux2** [comment]
> Did you add some fudge factor to the iteration counts on your system?

@cgcgcg Yes, I added a couple iterations, under the assumption there might be a bit of variation.  The AT will be the litmus test.

**Pull request merged**
