### PR TITLE
Framework: Update CODEOWNERS File

### PR DESCRIPTION
**Pull request by jmgate**
@trilinos/framework 

## Description
Request that `@trilinos/<package>/developers` teams review pull requests instead of the `@trilinos/<package>` teams.  The `developers` sub-teams will be given write-access to the repository.

## Motivation
See the discussion on #2013.

## Do Not Merge
We should hold off on merging this until all the `developers` sub-teams have been created and given write-access to the repository.

### CODE REVIEW

**Comment by lucbv** [comment]
I'm OK with the changes but should we create the teams, populate them with developer and give them correct write access first?
@trilinos/muelu and @trilinos/panzer are already using the code owner feature, it would be annoying for it to be broken while we reset things in Trilinos organization...

**Comment by jmgate** [comment]
Right, we shouldn't merge until the teams/permissions changes have been made behind the scenes.

**Comment by william76** [comment]
@jwillenbring 
@jmgate 
Is this PR still relevant? Should it be closed out? It's been in WIP since Feb 2020 without any updates.

**Comment by jwillenbring** [comment]
@william76 I would say it is still somewhat relevant . I don’t know that write access for a subset of developers is as big a deal as it was when you could just push to major branches. We could discuss this briefly at a standup if there is time, but it is not a huge priority. I am going to close this for now, and we could reopen it if it for some reason becomes a higher priority in the future.

**Pull request closed without merging**
