### PR TITLE
Transition SEMS RHEL7 builds in ATDM scripts from CUDA 9 to CUDA 10

### PR DESCRIPTION
**Pull request by rppawlo**
## Motivation

Switched the RHEL7 builds from CUDA 9.2 to 10.1 in the ATDM scripts.
@trilinos/framework 
@jwillenbring 
@bartlettroscoe 

requested by @bathmatt

### CODE REVIEW

**Comment by rppawlo** [comment]
@jmgate

**Comment by bartlettroscoe** [comment]
Someone should run a full Trilinos build before merging this?   Should just be a single command as per [here](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ctest-s-local-test-driversh) running:

```
$ cd <some_base_build_dir>/
$ ln -s <some_base_dir>/Trilinos/cmake/std/atdm/ctest-s-local-test-driver.sh .
$ ./ctest-s-local-test-driver.sh \
    sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug
```

and that will submit to CDash.

**Comment by bartlettroscoe** [comment]
Relates to:
* SESW-203

**Comment by jmgate** [comment]
Do we want to support both 9.2 and 10.1 for some amount of time before removing 9.2, rather than hot-swapping them?

**Review by e10harvey — APPROVED** [review]
Thank you, @rppawlo !
Please run:
```bash
$ cd <some_base_build_dir>/
$ ln -s <some_base_dir>/Trilinos/cmake/std/atdm/ctest-s-local-test-driver.sh .
$ ./ctest-s-local-test-driver.sh \
    sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug
```
and check the results before merging.

**Review by bartlettroscoe — COMMENTED** [review]
The changes look very straightforward to me.  They just need to be tested before it is merged.

@rppawlo, just to let you know, I am happy to review updates to the ATDM Trilinos configuration when asked but I can't approve them to be merged.  Someone on the @trilinos/framework needs to do that because they are responsible to traige problems triggered by such changes when they show up on CDash that result from such changes.  (Or you can remove the nighty builds for this configuration that posts to CDash then that would not be an issue anymore but there obvious downsides to that.)

Related to my epic SEPW-215

**Comment by rppawlo** [comment]
@e10harvey and @bartlettroscoe - I ran the build as you requested and the results had three failing tests, all in Adelus. Results are here:

https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=8987942

Is this good enough to commit? Not sure if the Adelus failures are new or known and currently failing.

@trilinos/framework

**Comment by bartlettroscoe** [comment]
> I ran the build as you requested and the results had three failing tests, all in Adelus

@rppawlo, those are known failing tests as per #8477.  BTW, I will be having Kitware extend CTest and CDash this year so that known failing tests like this can be marked with their issue tracker so it makes it clear that these are known failures.

> Is this good enough to commit? 

I would say yes.  But after the merge takes place, someone will need to update the Jenkins job:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/

(just changing the name of the Jenkins job should do the trick) and update the files:

* https://gitlab-ex.sandia.gov/atdm/TrilinosATDMStatus/-/blob/master/trilinosExpectedPrimaryBuilds.csv
* https://gitlab-ex.sandia.gov/atdm/TrilinosATDMStatus/-/blob/master/atdmTrilinosTestsWithIssueTrackers.csv

(just simple name changes in those files).

But I should not be doing that at this point.  Someone on the @trilinos/framework should be doing that at this point.

I am going to go ahead and unsubscribe.

**Comment by e10harvey** [comment]
> But after the merge takes place, someone will need to update the Jenkins job:

The name has been updated. CC: @ZUUL42, @prwolfe.

**Pull request merged**
