### PR TITLE
Tpetra - fix warning error from mismatched virtual functions

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
## Description

Fixiing mismatched virtual functions definitions. This could be a real error but somehow it works with other compilers and PR tests.  
## Related Issues

#4221 

## How Has This Been Tested?

As the error shows up from SRN machines with a clang compiler and this is not detected from PR tests, I cannot attempt to reproduce the error myself. From the error message, I matched the function signatures and hope that it will solve the problem.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
Sorry. I did a mistake to put markLoalErrorAndGetStream() to get a stream without a guard. When I test on my workstation, I probably do not set debug mode in tpetra.

**Comment by mhoemmen** [comment]
Thanks @kyungjoo-kim !  If you need help, just let me know.

> When I test on my workstation, I probably do not set debug mode in tpetra.

It should be on by default in a debug build (`CMAKE_BUILD_TYPE=DEBUG`).

**Comment by kyungjoo-kim** [comment]
I did ``CMAKE_BUILD_TYPE=DEBUG`` but it does not enable debug macro. ``Trilinos_ENABLE_DEBUG:BOOL=ON`` is the right flag which I did not enable before.

**Comment by mhoemmen** [comment]
Thanks @kyungjoo-kim ! :D

**Comment by mhoemmen** [comment]
FYI @theguruat12 @rrdrake @micahahoward (Kyungjoo fixed a thing that might have blocked promotion)

**Pull request merged**
