### PR TITLE
Tpetra: Fix fillComplete in matrix addition

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/tpetra 

## Motivation
Let's see if this passes the AT...

### CODE REVIEW

**Review by jhux2 — COMMENTED** [review]
I'm surprised this is necessary, shouldn't a call with arguments pick the domain and range maps up if they exist?

**Comment by cgcgcg** [comment]
@jhux2 This is where the `fillComplete` call went for EMPIRE:
https://github.com/trilinos/Trilinos/blob/e9f08ea4991bc9fe145894e37a03fa396a4e7893/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp#L4339-L4343
The problem is that it's then using the range map as the domain map.

**Comment by jhux2** [comment]
I see that.  This seems like a bug in CrsMatrix itself.

**Comment by jhux2** [comment]
> That's behavior dating back from Epetra. If you don't give it a domainMap/rangeMap it just uses your rowMap

In @cgcgcg's case, his matrix already has domain and range maps.  Shouldn't those be used?

**Comment by brian-kelley** [comment]
Yes I think this may be a bug in CrsMatrix, from the fillComplete with no domain/range parameters:
If the matrix does not yet have domain and range [Map](http://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1Map.html)s (i.e., if fillComplete has not yet been called on this matrix at least once), then this method uses the matrix's row Map (result of this->[getRowMap()](http://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1CrsMatrix.html#acb6cd1fcdfeb989fa7e3c716c18f36a1)) as both the domain [Map](http://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1Map.html) and the range [Map](http://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1Map.html). Otherwise, this method uses the matrix's existing domain and range Maps.

In this case, C was fill complete on input so it must have those domain and range maps already (according to this documentation)

**Pull request merged**
