### PR TITLE
(WIP DO NOT MERGE) Tpetra: First pass at fixing #6663

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @nate945 @shardest @crdohrm 

## Motivation

Our hypothesis is that double-counting incoming entries that could be merged into existing target matrix entries is the reason for the memory increase.  These changes will help test that.  They are also a first pass at fixing #6663.  This PR includes the following changes:

  1. Do not double-count incoming entries in `CrsMatrix::copyAndPermute` or `CrsMatrix::unpackAndCombine`.  (The way I did this may also benefit `CrsGraph::copyAndPermute` in the same way.)
  2. Remove redundant allocations in `CrsMatrix::applyCrsPadding`.
  3. Add verbose output for counting how much space (1) saved.

## Related Issues

* Part of #6663 

## Stakeholder Feedback

See #6663 discussion from Sierra SD developers.

## Testing

Tested TpetraCore on my Mac with Clang and OpenMPI.

### CODE REVIEW

**Comment by mhoemmen** [comment]
Build failures are for an unused variable warning.  I'll fix that, but the last commit should otherwise be fine.

**Comment by tjfulle** [comment]
thanks Mark!  i'll clone and run the thing tomorrow morning.

**Comment by mhoemmen** [comment]
I just pushed a fix for the build warning -- thanks @tjfulle ! :-D  I've been going through a lot of your code and am better appreciating what a challenging task it was to get rid of DynamicProfile.

**Comment by mhoemmen** [comment]
Oops, I think there are some unused typedef warnings in one of the builds still.  I'll push another commit for those tonight.

**Comment by mhoemmen** [comment]
The latest commit should fix those last build issues.

**Comment by mhoemmen** [comment]
@tjfulle I just pushed a couple optimizations -- my two last commits.  If test fail with those, try backing up to before those two commits.  Thanks!

**Comment by mhoemmen** [comment]
Oops, I missed an unused variable.  The CUDA build passes fine, which is weird considering it might be the same GCC version.  Anyway, @tjfulle , I'll push a commit to get rid of the unused variable, but this should be fine as is for testing.

**Comment by mhoemmen** [comment]
Hm, this doesn't actually fix the SD test.  I need to look into it a bit more closely.

**Comment by mhoemmen** [comment]
@tjfulle Interesting, it looks like `insertGlobalIndicesImpl` doesn't actually merge:
```
P: insertGlobalValuesFiltered threw an exception: .../Tpetra_CrsGraph_def.hpp:2021:

Throw number = 1

Throw test that evaluated to true: (true)

Tpetra::CrsGraph<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::insertGlobalIndicesImpl: On MPI Process 5: Not enough capacity to insert 96 indices into local row 32124, which currently has 96 entries and total allocation size 129.
```
I'll need to check, though; the error message doesn't tell me the input indices.

**Comment by mhoemmen** [comment]
I'm worried that this passed Tpetra's tests, but threw an exception when I ran the SD test with it.  Thus, I am marking this WIP.  Please do not merge it yet.

**Comment by tjfulle** [comment]
@mhoemmen that's strange that `insertGlobalIndices` does not merge.  There are tests that specifically hit the graph with repeated indices.

**Comment by mhoemmen** [comment]
@tjfulle I thought so too.  I'll run the test again with logging output that shows the input and current column indices in the failed `insertGlobalIndicesImpl` call.

**Comment by mhoemmen** [comment]
@tjfulle Hm, something looks wrong with the merging.  Here is a sample error message (for my branch Tpetra-Crs-memory-use-2):
```
Tpetra::CrsGraph<int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::insertGlobalIndicesImpl: Proc 5: Not enough capacity to insert 96 indices into local row 32124, which currently has 96 entries and total allocation size 129.  Input global column indices: [142944, 142945, 142946, 142947, 142948, 142949, 142950, 142951, 142952, 142953, 142954, 142955, 142959, 142960, 142961, 142965, 142966, 142967, 142968, 142969, 142970, 143142, 143143, 143144, 198279, 198280, 198281, 198282, 198283, 198284, 198291, 198292, 198293, 198303, 198304, 198305, 198309, 198310, 198311, 198333, 198334, 198335, 198336, 198337, 198338, 198339, 198340, 198341, 198342, 198343, 198344, 198345, 198346, 198347, 198348, 198349, 198350, 198351, 198352, 198353, 198354, 198355, 198356, 198699, 198700, 198701, 198702, 198703, 198704, 198705, 198706, 198707, 198708, 198709, 198710, 198711, 198712, 198713, 198729, 198730, 198731, 198732, 198733, 198734, 198735, 198736, 198737, 198738, 198739, 198740, 198741, 198742, 198743, 198744, 198745, 198746], 

Current global column indices: [166215, 166216, 166217, 166218, 166219, 166220, 166221, 166222, 166223, 166224, 166225, 166226, 166227, 166228, 166229, 166230, 166231, 166232, 166233, 166234, 166235, 166236, 166237, 166238, 166239, 166240, 166241, 166242, 166243, 166244, 166245, 166246, 166247, 198279, 198280, 198281, 198282, 198283, 198284, 198285, 198286, 198287, 198288, 198289, 198290, 198291, 198292, 198293, 198294, 198295, 198296, 198297, 198298, 198299, 198300, 198301, 198302, 198303, 198304, 198305, 198306, 198307, 198308, 198309, 198310, 198311, 198312, 198313, 198314, 198315, 198316, 198317, 198333, 198334, 198335, 198336, 198337, 198338, 198339, 198340, 198341, 198342, 198343, 198344, 198345, 198346, 198347, 198348, 198349, 198350, 198351, 198352, 198353, 198354, 198355, 198356]
```
Both input and current arrays have length 96, and their merged result _should_ have length 153, but the allocation size is only 129.  Let me work on this a bit.

**Comment by mhoemmen** [comment]
I just made a unit test fail that sends an entire row from Process 1 to Process 0.  I'm working on a fix.  I'll also add the unit test.  It looks like we need a lot more tests.

**Comment by mhoemmen** [comment]
@tjfulle My changes above include a unit test that exercises a partial merge on unpackAndCombine.  (See comments in the test for details.)  That test passes now.  I am currently rebuilding Sierra with these Trilinos changes.

**Comment by mhoemmen** [comment]
@tjfulle What does "padding" actually mean?  Does it refer to the current allocation size, or the current number of entries?

**Comment by mhoemmen** [comment]
@tjfulle I think I see the problem.  I printed the padding vector that `CrsGraph::computePaddingForCrsMatrixUnpack` computes.  On Process 5:
```
*** CrsMatrix::unpackAndCombineImpl: Local row 32124: paddingVec[60]=33
```
and on Process 1:
```
*** CrsMatrix::unpackAndCombineImpl: Local row 31107: paddingVec[5]=129
```
This 129 shows up above.  The issue could be that I was treating padding like a difference -- the required increment -- but it actually needs to be the new amount of the allocation.  It's not the right name -- it's not a "padding," but a new number of entries.

**Comment by tjfulle** [comment]
The intention was to be padding (increment), not the total required size.  Padding + current size is the new required size.  The padding is used to shift values, one rows ar a time

**Comment by tjfulle** [comment]
@mhoemen said:

> What does "padding" actually mean? Does it refer to the current allocation size, the increment in the required number of entries, or the total required number of entries? It looks like it refers to the total required number of entries.

That line looks to me to increase the number of entries in the row by the incoming number of entries minus the free space - or the increment required.  That was my intent, though now I'm starting to doubt the implementation since it's not clear to you...

**Comment by mhoemmen** [comment]
@tjfulle wrote:
>  That was my intent, though now I'm starting to doubt the implementation since it's not clear to you...

I think what I'll do next is take the test case straight from the log output above, write a separate Tpetra test that Imports the one row, and see if that fails.  If so, I should be able to figure this out.  Thanks for explaining! : - )

**Comment by mhoemmen** [comment]
Hm, I used the log output to replicate the test case, but didn't get the test to fail.

**Comment by tjfulle** [comment]
@mhoemmen, I'm searching through existing tests now, but I know I put in a test that created a matrix (or graph) and then just pounded it by inserting duplicate entries to make sure duplicates were merged during `insert*Indices`.

**Comment by mhoemmen** [comment]
@tjfulle What if a target matrix row receives data from more than one process?  That means more or less that we can't update the padding one row at a time -- we actually need to do the merges.  I think I can figure out a way to do it.

**Comment by tjfulle** [comment]
@mhoemmen, in that case the padding would be computed in `unpackAndCombine`, right?  Shouldn't all the nonlocal data be collected by then so that the padding is an upper bound?

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> Shouldn't all the nonlocal data be collected by then so that the padding is an upper bound?

Right, but it's possible for two different processes to send the target matrix data for a single row.  For example:

- On Process 0, target matrix row 42 has global column indices [5, 7, 9, 11].
- Process 1 sends target matrix row 42 global column indices [1, 3, 5].
- Process 2 sends target matrix row 42 global column indices [11, 13, 15].

If I only attempt merges pairwise, then I'll get a new count of 6, but it should be 8.

**Comment by mhoemmen** [comment]
@tjfulle The logical way to fix this problem is for the "compute padding" function to accumulate the actual column indices for each row to unpack.  We could later make that GPU friendly by using UnorderedMap with a fixed overallocation, and retrying if we run out.

**Comment by mhoemmen** [comment]
@tjfulle I may have gotten somewhere with this.  My branch Tpetra-Crs-memory-use-4 has a proposed fix.  CrsGraph and CrsMatrix tests pass.  I'm refactoring the solution now.

**Comment by mhoemmen** [comment]
Superseded by PR https://github.com/trilinos/Trilinos/pull/6806 .

**Comment by mhoemmen** [comment]
I just merged PR #6831, which fixes #6663.  Thus, I'm deleting this branch.

**Pull request closed without merging**
