### PR TITLE
Framework: Preparation for CMake minimum required version update

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework
This is a Work in Progress.

## Motivation
This is part of Issue #8520 to prepare the way for upgrading the minimum CMake required version to 17.0.0
* Part of #8520

## Testing
The PR updates will be tested through the usual PR driver.

The updates to the manual replication scripts will need to be tested manually.

This is due by January 29th, 2021.

### Update and Test PR Replication Scripts
These will need to be manually tested on an appropriate system.  See [Reproducing PR Testing Errors][1] for detailed instructions.
- [x] PullRequestClang10.0.0TestingEnv.sh
- ~~PullRequestClang7.0.1TestingEnv.sh~~
- ~~PullRequestClang9.0.0TestingEnv.sh~~
- [x] PullRequestCuda10.1.105TestingEnv.sh
- [x] PullRequestCuda9.2TestingEnv.sh
-  ~~PullRequestGCC4.8.4TestingEnv.sh~~
- ~~PullRequestGCC4.9.3TestingEnv.sh~~
- ~~PullRequestGCC4.9.3TestingEnvSERIAL.sh~~
- ~~PullRequestGCC7.2.0SerialTestingEnv.sh~~
- [x] PullRequestGCC7.2.0TestingEnv.sh
- [x] PullRequestGCC8.3.0TestingEnv.sh
- [x] PullRequestIntel17.0.1TestingEnv.sh
- [x] PullRequestIntel19.0.5TestingEnv.sh
- ~~PullRequestPython3TestingEnv.sh~~

Update: marked out .sh files that we don't use anymore for PR's.

[1]: https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

### CODE REVIEW

**Comment by william76** [comment]
@jwillenbring this branch is on the main Trilinos repo so we can all work on it as needed. Certainly we won't want to push this in until after the winter break ;) 

The CUDA systems may be tricky -- they get some version of CMake from the devpacks they load, and I didn't see any obvious stand-alone CMake packages to replace with. Perhaps @prwolfe or @ZUUL42 knows where we can snag a higher version of CMake on those systems?

**Comment by william76** [comment]
@prwolfe thanks!

It's still weird to me why that CMake 3.17.1 based Intel build is failing in CMake on the Fortran check.

I logged into ascic-158 and built a F90 hello-world using that compiler and the same modules as the job loads in and it works just fine.

Once this merges, I'll check retest on #8602 and see if it's still failing. Perhaps that error we saw last week / over the weekend was more anomalous?

**Comment by william76** [comment]
@prwolfe @ZUUL42 
I haven't been able to replicate that CMake error for the Intel 17 compiler in which it seems unable to compile a trivial test program.  I pushed in an update to see if CMake 3.19.1 works since we have that one now from SEMS.

I haven't been able to replicate any compilation problems using the intel F90 compiler, but I haven't tried it with a trivial CMake file yet.  If this 3.19.x test fails, I'll look into a minimal cmake hello-world app to see if that works.

**Comment by william76** [comment]
@e10harvey noted in our meeting this morning that #8495 might have some relevance to the intel compiler check failing.

**Comment by william76** [comment]
@e10harvey @ZUUL42 
I tried Evan's trick and didn't seem to get anywhere on my tests. I did see that the PR testing passed if I reverted to CMake 3.10.3 so I think that gives us a useful data point.

It looks like this might be a similar problem that some guys encountered last summer in #7740 and https://github.com/spack/spack/issues/15522 ?

**Review by e10harvey — DISMISSED** [review]
Thanks, @william76 !

**Comment by william76** [comment]
@e10harvey @jwillenbring @prwolfe @ZUUL42 
So, the Intel build still fails with that same error despite setting `CMAKE_EXE_LINKER_FLAGS=-lifcore` ... also seeing CLANG errors too?  🤦🏻‍♂️ 

I'm attempting my own run of the intel build on ascic158, which looks like it's going to actually work.  It's past that point of death on the config state now so I'm even more confused now. 

Any ideas?

**Comment by william76** [comment]
In looking at the current errors... things seem odd to me. we changed the `CMAKE_EXE_LINKER_FLAGS` to add `-lifcore` in the branch.  I can even see it on the PR:

https://github.com/trilinos/Trilinos/blob/dd73b2a39fc72d321623dd5b87a31fb34d0fdeb1/cmake/std/PullRequestLinuxIntel17.0.1TestingSettings.cmake#L78-L83

It works properly when I test it directly on the command line, etc. but when I had a look at the console log in [CDash][1], it looks like that -lifcore option isn't being passed in though.

```
-- Verifying Fortran/CXX Compiler Compatibility - Failed
CMake Error at /projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.17.1/share/cmake-3.17/Modules/FortranCInterface.cmake:383 (message):
  The Fortran compiler:

    /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/mpich/3.2/bin/mpif90

  and the CXX compiler:

    /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/mpich/3.2/bin/mpicxx

  failed to compile a simple test project using both languages.  The output
  was:

    Change Dir: /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/pull_request_test/CMakeFiles/FortranCInterface/VerifyCXX
    
    Run Build Command(s):/projects/sems/install/rhel7-x86_64/atdm/utility/ninja_fortran/1.7.2/bin/ninja VerifyFortranC && [1/8] Building Fortran preprocessed CMakeFiles/VerifyFortran.dir/VerifyFortran.f-pp.f
    [2/8] Generating Fortran dyndep file CMakeFiles/VerifyFortran.dir/Fortran.dd
    [3/8] Building C object CMakeFiles/VerifyFortranC.dir/main.c.o
    [4/8] Building C object CMakeFiles/VerifyFortranC.dir/VerifyC.c.o
    [5/8] Building CXX object CMakeFiles/VerifyFortranC.dir/VerifyCXX.cxx.o
    [6/8] Building Fortran object CMakeFiles/VerifyFortran.dir/VerifyFortran.f.o
    [7/8] Linking Fortran static library libVerifyFortran.a
    [8/8] Linking CXX executable VerifyFortranC
    FAILED: VerifyFortranC 
    : && /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/mpich/3.2/bin/mpicxx  -Wall -Warray-bounds -Wchar-subscripts -Wcomment -Wenum-compare -Wformat -Wuninitialized -Wmaybe-uninitialized -Wmain -Wnarrowing -Wnonnull -Wparentheses -Wpointer-sign -Wreorder -Wreturn-type -Wsign-compare -Wsequence-point -Wtrigraphs -Wunused-function -Wunused-but-set-variable -Wunused-variable -Wwrite-strings -O3 -DNDEBUG   CMakeFiles/VerifyFortranC.dir/main.c.o CMakeFiles/VerifyFortranC.dir/VerifyC.c.o CMakeFiles/VerifyFortranC.dir/VerifyCXX.cxx.o  -o VerifyFortranC  libVerifyFortran.a && :
    ld: libVerifyFortran.a(VerifyFortran.f.o): undefined reference to symbol 'for_write_seq_lis'
    /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/base/lib/intel64/libifcoremt.so.5: error adding symbols: DSO missing from command line
    ninja: build stopped: subcommand failed.
    
    
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsFortranMangling.cmake:50 (FortranCInterface_VERIFY)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:2143 (INCLUDE)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:193 (TRIBITS_SETUP_ENV)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)
```


[1]: https://testing.sandia.gov/cdash/build/8611355/configure

**Comment by william76** [comment]
In looking at the current errors... things seem odd to me. we changed the `CMAKE_EXE_LINKER_FLAGS` to add `-lifcore` in the branch.  I can even see it on the PR:

https://github.com/trilinos/Trilinos/blob/dd73b2a39fc72d321623dd5b87a31fb34d0fdeb1/cmake/std/PullRequestLinuxIntel17.0.1TestingSettings.cmake#L78-L83

It works properly when I test it directly on the command line, etc. but when I had a look at the console log in [CDash][1], it looks like that -lifcore option isn't being passed in though.

```
-- Verifying Fortran/CXX Compiler Compatibility - Failed
CMake Error at /projects/sems/install/rhel7-x86_64/sems/utility/cmake/3.17.1/share/cmake-3.17/Modules/FortranCInterface.cmake:383 (message):
  The Fortran compiler:

    /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/mpich/3.2/bin/mpif90

  and the CXX compiler:

    /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/mpich/3.2/bin/mpicxx

  failed to compile a simple test project using both languages.  The output
  was:

    Change Dir: /scratch/trilinos/jenkins/ascic158/workspace/trilinos-folder/Trilinos_pullrequest_intel_17.0.1/pull_request_test/CMakeFiles/FortranCInterface/VerifyCXX
    
    Run Build Command(s):/projects/sems/install/rhel7-x86_64/atdm/utility/ninja_fortran/1.7.2/bin/ninja VerifyFortranC && [1/8] Building Fortran preprocessed CMakeFiles/VerifyFortran.dir/VerifyFortran.f-pp.f
    [2/8] Generating Fortran dyndep file CMakeFiles/VerifyFortran.dir/Fortran.dd
    [3/8] Building C object CMakeFiles/VerifyFortranC.dir/main.c.o
    [4/8] Building C object CMakeFiles/VerifyFortranC.dir/VerifyC.c.o
    [5/8] Building CXX object CMakeFiles/VerifyFortranC.dir/VerifyCXX.cxx.o
    [6/8] Building Fortran object CMakeFiles/VerifyFortran.dir/VerifyFortran.f.o
    [7/8] Linking Fortran static library libVerifyFortran.a
    [8/8] Linking CXX executable VerifyFortranC
    FAILED: VerifyFortranC 
    : && /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/mpich/3.2/bin/mpicxx  -Wall -Warray-bounds -Wchar-subscripts -Wcomment -Wenum-compare -Wformat -Wuninitialized -Wmaybe-uninitialized -Wmain -Wnarrowing -Wnonnull -Wparentheses -Wpointer-sign -Wreorder -Wreturn-type -Wsign-compare -Wsequence-point -Wtrigraphs -Wunused-function -Wunused-but-set-variable -Wunused-variable -Wwrite-strings -O3 -DNDEBUG   CMakeFiles/VerifyFortranC.dir/main.c.o CMakeFiles/VerifyFortranC.dir/VerifyC.c.o CMakeFiles/VerifyFortranC.dir/VerifyCXX.cxx.o  -o VerifyFortranC  libVerifyFortran.a && :
    ld: libVerifyFortran.a(VerifyFortran.f.o): undefined reference to symbol 'for_write_seq_lis'
    /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/base/lib/intel64/libifcoremt.so.5: error adding symbols: DSO missing from command line
    ninja: build stopped: subcommand failed.
    
    
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsFortranMangling.cmake:50 (FortranCInterface_VERIFY)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:2143 (INCLUDE)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:193 (TRIBITS_SETUP_ENV)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)
```


[1]: https://testing.sandia.gov/cdash/build/8611355/configure

**Comment by william76** [comment]
Note: I added the `LDFLAGS=-lifcore` parameter to the `config.ini` file to see if that works on Jenkins and so far it looks like it _might_ be working... but from our meeting this week we had thought that is more of a hack than a permanent solution.

I'm still perplexed about why this might be working but setting `CMAKE_EXE_LINKER_FLAGS` in the cmake file didn't... /shrug

**Review by jwillenbring — APPROVED** [review]
I am not sure why this worked by hand without setting in the environment, and it needs to be set in the env here, but we did talk about this possibility. Approving.

**Comment by william76** [comment]
> 
> 
> I am not sure why this worked by hand without setting in the environment, and it needs to be set in the env here, but we did talk about this possibility. Approving.

@jwillenbring Yeah... was pretty weird.  My Jenkins emulator is basically a script that sets all the Jenkins envvars, etc. It gets close to what is actually happening in our PR's but it does inherit my environment so maybe something else is in there that doesn't show up in the PR's.  Fully diffing that will be a pain. 

Given that it did work properly in CMake 3.10.x, but not CMake 3.17 or 3.19, I wonder if it'd be good to reach out to Kitware.

**Comment by prwolfe** [comment]
And the PR’s are already using cmake 3.17 so this is blocking develop -> master…

**Pull request merged**
