### PR TITLE
Update tribits 2018 01 04

### PR DESCRIPTION
**Pull request by bartlettroscoe**
I am getting a single failing test `Zoltan2_OrderingScotch_MPI_4` with the checkin-test-sems.sh script but the changes in this PR branch should not impact that at all.  Therefore, I am doing this PR so that it gets tested so that I can see if it passes the automated PR builds and then I will push using the "merge" button.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Why is this PR not being tested by the auto PR tester?

**Comment by allevin** [comment]
@bartlettroscoe The autotester app is receiving some unexpected data from Jenkins and is not handling it properly.  I am investigating and hopefully will get it back up and running today.  Sorry for the inconvenience.

**Comment by allevin** [comment]
@bartlettroscoe Note: this PR will not be tested by the autotester app as it is targeted to the master branch.  The autotester only tests PR's targeted towards the develop branch.

**Comment by bartlettroscoe** [comment]
> Note: this PR will not be tested by the autotester app as it is targeted to the master branch. The autotester only tests PR's targeted towards the develop branch.

@allevin, thanks for the tip.  I did not catch that.  I created the PR pretty fast.

I already pushed another merge of this branch so I will just close.

**Pull request closed without merging**
