### PR TITLE
Seacas snapshot 11 25 2022

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas 

## Motivation

See commit messages for individual commits.

### CODE REVIEW

**Comment by gsjaardema** [comment]
@alanw0 @prwolfe Not sure if either of you have time, but if so, would you mind reviewing this PR.  I tried to commit in multiple commits, so can look at specific changes that way, or just wade in ...

Most of the IOSS-related changes are for Windows compatibility -- adding dllexport macro to all classes and free functions, also some warning reduction cleanup.

**Review by alanw0 — APPROVED** [review]

**Comment by gsjaardema** [comment]
@trilinos/framework All tests passed and it is reviewed, but doesn't seem to realize it can be merged...  What needs to be done to merge this?

**Comment by sebrowne** [comment]
@gsjaardema I hypothesize that the autotester was backed up and didn't get to the automerge until the next time it ran, when it detected Alan's approval and then decided that all the automerging conditions were met.  Do let us know if it happens again though, and we will investigate.  Is that satisfactory for now?

**Comment by gsjaardema** [comment]
Yes, thanks for the reply.  Everything is good.

**Pull request merged**
