### PR TITLE
Set Sacado_ENABLE_HIERARCHICAL_DFAD=ON for all CUDA builds (#2446, #3579, #2751)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
#2446, #3579, #2751, #3833 

Not ready to merge yet!

### CODE REVIEW

**Comment by rppawlo** [comment]
ok. I'll take a look at that. I need to fix some things in empire before we flip this switch anyway.

**Comment by bartlettroscoe** [comment]
CC: @bathmatt 

@rppawlo,

Using the driver script `run_all_builds.sh` shown below, I submited this to CDash with:

```
$ env \
  ATDM_LIST_OF_BUILDS=Trilinos-atdm-white-ride-cuda-9.2-debug \
  Trilinos_PACKAGES=Panzer \
  ./run_all_builds.sh
```

This submitted to CDash at:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4140530

This shows the following failures:

* PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4, Failed, 10m 200ms, Completed (Timeout)
* PanzerAdaptersSTK_MixedPoissonMultiblockExample-ConvTest-Hex-Order-1, Failed, 2m 28s 470ms, Completed (Failed)

----

**DRIVER SCRIPT:**

```
#!/bin/bash

if [ "${TRILINOS_DIR}" == "" ] ; then
  TRILINOS_DIR=/home/rabartl/Trilinos.base/Trilinos
fi

if [ "${ATDM_LIST_OF_BUILDS}" == "" ] ; then
  ATDM_LIST_OF_BUILDS="Trilinos-atdm-white-ride-cuda-9.2-debug-pt Trilinos-atdm-white-ride-cuda-9.2-debug Trilinos-atdm-white-ride-cuda-9.2-opt-Pascal60 Trilinos-atdm-white-ride-cuda-9.2-opt Trilinos-atdm-white-ride-gnu-debug-openmp Trilinos-atdm-white-ride-gnu-opt-openmp"

fi

BASEDIR=$PWD

if [ ! -e Trilinos ] ; then
  ln -s ${TRILINOS_DIR} .
fi

for build_name in $ATDM_LIST_OF_BUILDS ; do

  echo
  echo "Running Jenkins driver ${build_name}.sh ..."
  echo

  # Set up the directory for this build case

  if [ ! -e ${build_name} ] ; then
    mkdir ${build_name}
  fi
  cd ${BASEDIR}/${build_name}

  if [ ! -e Trilinos ] ; then
    ln -s ${TRILINOS_DIR} .
  fi

  # Set up the SRC_AND_BUILD dir for Trilinos already cloned

  if [ ! -e SRC_AND_BUILD ] ; then
    mkdir SRC_AND_BUILD
  fi

  if [ ! -e SRC_AND_BUILD/Trilinos ] ; then
    cd SRC_AND_BUILD/
    ln -s ${TRILINOS_DIR} .
    cd -
  fi

  time env \
    JOB_NAME=${build_name} \
    WORKSPACE=$PWD \
    CTEST_TEST_TYPE=Experimental \
    CTEST_DO_UPDATES=OFF \
    CTEST_DO_SUBMIT=ON \
  ${TRILINOS_DIR}/cmake/ctest/drivers/atdm/smart-jenkins-driver.sh \
    &> smart-jenkins-driver.out

done

#    CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=TRUE \
#    ATDM_CONFIG_BUILD_COUNT_OVERRIDE=32 \
#    ATDM_CONFIG_CTEST_PARALLEL_LEVEL_OVERIDE=16 \
```

**Comment by mhoemmen** [comment]
@rppawlo Would love to learn more about what this hierarchical dfad is :-)

**Comment by bartlettroscoe** [comment]
@rppawlo, on 'white' I am running:

```
$ env ATDM_LIST_OF_BUILDS=Trilinos-atdm-white-ride-cuda-9.2-debug \
  Trilinos_PACKAGES=Intrepid2,Phalanx,Panzer ./run_all_builds.sh
```

using the above driver script and I am getting all timeouts from Intrepid2 and Phalanx tests.  Is this expected?

**Comment by rppawlo** [comment]
> using the above driver script and I am getting all timeouts from Intrepid2 and Phalanx tests. Is this expected?

I have not tried on white lately. Will try to get to that soon. On waterman, all panzer tests were passing with hierarchic dfad enabled. One thing I did note today. In a non-hierarchic cuda build, running with -j16 resulted in 6 panzer tests timing out. Where running with -j1 had one panzer test time out. I think that as we convert more code to use gpus, running multiple tests at the same time is going to get worse as more tests are hitting the same cuda card.

**Comment by bartlettroscoe** [comment]
> I think that as we convert more code to use gpus, running multiple tests at the same time is going to get worse as more tests are hitting the same cuda card.

@rppawlo, that is unfortunate.  Hopefully the Kokkos developers can help us with this some.

**Comment by bartlettroscoe** [comment]
@rppawlo,

FYI: I rebased this topic branch on top of 'develop' and ran:

```
$ env ATDM_LIST_OF_BUILDS=Trilinos-atdm-white-ride-cuda-9.2-debug \
  Trilinos_PACKAGES=Intrepid2,Phalanx,Panzer \
  ./run_all_builds.sh

Running Jenkins driver Trilinos-atdm-white-ride-cuda-9.2-debug.sh ...


real    92m40.680s
user    0m0.690s
sys     0m0.422s
```

and it posted to:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4146711

The results are much better.  There is just the timing out test `PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4` shown here:

* https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4146713

The full set of tests run can be see at:

* https://testing.sandia.gov/cdash-dev-view/viewTest.php?buildid=4146711

Progress?

**Comment by rppawlo** [comment]
Thanks @bartlettroscoe ! Is this a true debug build or a build with trilinos debug code enabled but a release build for faster turnaround?

**Comment by bartlettroscoe** [comment]
> Is this a true debug build or a build with trilinos debug code enabled but a release build for faster turnaround?

@rppawlo, as described in the keyword `<release_or_debug>` type at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#quick-start

the build `Trilinos-atdm-white-ride-cuda-9.2-debug` is a full debug build.

I can go ahead and set up a `cuda-9.2-release-debug` build which uses `-O3` for the compiler options and see how that goes.  I will report results back here.

**Comment by rppawlo** [comment]
> Would love to learn more about what this hierarchical dfad is :-)

@mhoemmen - did you get the slides on hierarchic dfad that I sent?

**Comment by bartlettroscoe** [comment]
> That's ok - you don't have to do that. I may just disable these panzer tests for cuda debug builds and be done with it.

@rppawlo, it is already running :-)

You might want to change the default to not add some of these expensive tests if using non-optimized debug compiler options (e.g. `-O0`).  For example, using the [`TRIBITS_ADD_ADVANCED_TEST()` option `EXCLUDE_IF_NOT_TRUE`](https://tribits.org/doc/TribitsDevelopersGuide.html#overall-arguments-tribits-add-advanced-test), you can update the Panzer CMakeLists.txt files where these tests are defined as:

```
IF (CMAKE_BULID_TYPE STREQUAL "DEBUG")
  SET(${PACKAGE_NAME}_ADD_EXPENSIVE_TESTS_DEFAULT OFF)
ELSE()
  SET(${PACKAGE_NAME}_ADD_EXPENSIVE_TESTS_DEFAULT ON)
ENDIF()

SET( ${PACKAGE_NAME}_ADD_EXPENSIVE_TESTS
  ${PACKAGE_NAME}_ADD_EXPENSIVE_TESTS_DEFAULT}
  CACHE BOOL
  "Add some expensive tests.  Not recommended for CMAKE_BUILD_TYPE=DEBUG" )

...

TRIBITS_ADD_ADVANCED_TEST( CurlLaplacianExample-ConvTest-Quad-Order-4
  ...
  EXCLUDE_IF_NOT_TRUE ${PACKAGE_NAME}{_ADD_EXPENSIVE_TESTS
  ...
  )
```

The advantage of using the `EXCLUDE_IF_NOT_TRUE` option is that in [add test tracing mode](https://tribits.org/doc/TribitsBuildReference.html#trace-test-addition-or-exclusion), TriBITS will print a line listing the test and why it is not being enabled.

With this approach, regular developers will not get hit by these timing out tests by default and yet they can see why the test is not getting added in case they want to add them.

Let me know what you think about that approach.  It would simplify setting up builds on new platforms and envs.

**Comment by rppawlo** [comment]
yes - that's what I was thinking except it would only disable for debug+cuda. These tests seem to run fine on host with debug as they are all included in current PR testing.

**Comment by bartlettroscoe** [comment]
> yes - that's what I was thinking except it would only disable for debug+cuda. These tests seem to run fine on host with debug as they are all included in current PR testing.

Okay, this this would then be something like:

```
IF (CMAKE_BULID_TYPE STREQUAL "DEBUG" AND TPL_ENABLE_CUDA)
  SET(${PACKAGE_NAME}_ADD_EXPENSIVE_TESTS_DEFAULT OFF)
ELSE()
  SET(${PACKAGE_NAME}_ADD_EXPENSIVE_TESTS_DEFAULT ON)
ENDIF()

SET( ${PACKAGE_NAME}_ADD_EXPENSIVE_TESTS
  ${PACKAGE_NAME}_ADD_EXPENSIVE_TESTS_DEFAULT}
  CACHE BOOL
  "Add some expensive tests.  Not recommended for CMAKE_BUILD_TYPE=DEBUG" )

...

TRIBITS_ADD_ADVANCED_TEST( CurlLaplacianExample-ConvTest-Quad-Order-4
  ...
  EXCLUDE_IF_NOT_TRUE ${PACKAGE_NAME}{_ADD_EXPENSIVE_TESTS
  ...
  )
``

**Comment by bartlettroscoe** [comment]
@rppawlo,

FYI: I rebased the branch enabling this option on top of 'develop' again yesterday and ran a `release-debug` build on 'white' with:

```
$ env ATDM_LIST_OF_BUILDS=Trilinos-atdm-white-ride-cuda-9.2-release-debug \
  Trilinos_PACKAGES=Intrepid2,Phalanx,Panzer \
  ./run_all_builds.sh

Running Jenkins driver Trilinos-atdm-white-ride-cuda-9.2-release-debug.sh ...


real    105m49.879s
user    0m0.719s
sys     0m0.409s
```

and it submitted to CDash [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4150712) which showed two failing Panzer tests [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4150714) which were:

* PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 | Failed | 10m 200ms | Completed (Timeout) 
* PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 | Failed | 10m 190ms | Completed (Timeout) 

And yes, this is a `-O3` build as shown [here](https://testing.sandia.gov/cdash-dev-view/viewBuildError.php?type=1&buildid=4150714) showing the compiler options:

* `... "--std=c++11" "-lineinfo" "-g" "-Xcudafe" "--diag_suppress=esa_on_defaulted_function_ignored" "-expt-extended-lambda" "-arch=sm_37" "-O3" "-DNDEBUG" ...`

Still more work to do?

I will try running a full optimized build next on 'white' and see what happens.

**Comment by mhoemmen** [comment]
@rppawlo I did -- I'm in all-day off-site meetings all week so haven't quite gotten to them yet, but thanks for sending! :-)

**Comment by bartlettroscoe** [comment]
@rppawlo,

FYI: 

I ran a full optimized build on 'white' with:

```
$ env ATDM_LIST_OF_BUILDS=Trilinos-atdm-white-ride-cuda-9.2-opt \
   Trilinos_PACKAGES=Intrepid2,Phalanx,Panzer \
   ./run_all_builds.sh

Running Jenkins driver Trilinos-atdm-white-ride-cuda-9.2-opt.sh ...

/ascldap/users/rabartl/Trilinos.base/BUILD/WHITE/JENKINS_DRIVER/Trilinos-atdm-white-ride-cuda-9.2-opt

real    64m9.150s
user    0m0.771s
sys     0m0.332s
```

which posted to CDash here:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4154410

All of the tests passed and listed [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlypassed&buildid=4154410).

However, the three most expensive tests are:

* PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 | Passed | 9m 30s 620ms
* PanzerAdaptersSTK_PoissonInterfaceExample_2d_diffsideids_MPI_1 | Passed | 4m 51s 440ms
* PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2 | Passed | 3m 51s 450ms
* PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-3 | Passed | 2m 8s 190ms

Therefore, in an optimized build I think we may still need to disable the test `PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4` because that is a bit too close to a timeout.

I can try running this on 'waterman' and see what this looks like there.  Would that help?

**Comment by rppawlo** [comment]
@bartlettroscoe - I routinely run all panzer tests on waterman in opt mode and they all pass pretty fast. 

Here are the same tests on waterman in opt with -j1:
```
PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 ...   Passed  140.76 sec
PanzerAdaptersSTK_PoissonInterfaceExample_2d_diffsideids_MPI_1 ...   Passed  116.06 sec
PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2 ...   Passed   52.61 sec
PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-3 ...   Passed   64.63 sec

```
Here are the same convergence tests on waterman in opt for -j8
```
PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 .............   Passed  238.70 sec
PanzerAdaptersSTK_PoissonInterfaceExample_2d_diffsideids_MPI_1 .........   Passed  474.45 sec
PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2 ...............   Passed   76.50 sec
PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-3 .............   Passed  110.77 sec
```

Looks like we are playing whack-a-mole as multiple tests hit the same cuda card. Maybe white is much worse but I didn't think there was much of a difference for panzer testing when moving from pascal to volta (at least for -j1). I'm happy to disable the convergence tests for cuda debug builds but would like these enabled if possible for opt cuda builds. Until ctest can handle allocating device resources like cuda cards to separate executables, we should be running one executable test at a time for cuda. In the short term I'll disable a bunch of tests for cuda but really don't like this.

**Comment by bartlettroscoe** [comment]
@rppawlo, if the slowest test for a `cuda-9.2-opt` build on waterman is:

```
PanzerAdaptersSTK_PoissonInterfaceExample_2d_diffsideids_MPI_1 .........   Passed  474.45 sec
```

then that is well under 600s (10m) and I think we can run all of these tests on the nightly builds on 'waterman' for the `cuda-9.2-opt` build there (unless we see frequent timeouts later).

Let's just disable these expensive tests for CUDA debug-anything (compiler options or runtime debug checking) as described [above](https://github.com/trilinos/Trilinos/pull/3800#issuecomment-436655376) but leave them all enabled for the full CUDA opt builds for now.  Then if we see fairly frequent timeouts on some CUDA bulids on some platforms, we will disable individual tests just for those builds.  But looking at your `ctest -j8` numbers on 'waterman' above, there is a good chance that we will not have to disable any for the 'waterman' `cuda-9.2-opt` build at all.  That way, you would get all of the Panzer tests to run in a CUDA 9.2 build on 'waterman' (which is closer to Sierra than white/ride anyway).

Does that sound like a good plan?

**Comment by bartlettroscoe** [comment]
>  I'll put up a PR shortly.

@rppawlo, you can add those commits to this branch if you want in the same PR and then just test and push it together.  Otherwise not a big deal since this PR currently just changes files under the cmake/std/atdm/ directory which does not trigger building any packages so even if the PR tester crashes a bunch of times it will still go through pretty fast (a few hours).

**Comment by rppawlo** [comment]
@bartlettroscoe - it is all set if you want to review and push.

**Comment by bartlettroscoe** [comment]
>  it is all set if you want to review and push.

@rppawlo, I just rebased this on top of 'develop' and I removed the `AT: WIP` label so it will start the PR tester.    Can you approve this updated PR?

In the mean-time while the PR testing finishes, I will run configure, build, and run the Panzer test suite on 'white' with the builds `cuda-9.2-debug`, `cuda-9.2-opt`, and `cuda-9.2-release-debug` to see what that looks like.  If all of that looks good, then we can merge.

Sound good?

**Comment by rppawlo** [comment]
@bartlettroscoe sounds good! Thanks!

**Comment by bartlettroscoe** [comment]
@rppawlo, I tested this updated branch with:

```
$ env CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=FALSE \
  ATDM_LIST_OF_BUILDS="Trilinos-atdm-white-ride-cuda-9.2-debug Trilinos-atdm-white-ride-cuda-9.2-opt Trilinos-atdm-white-ride-cuda-9.2-release-debug" \
  Trilinos_PACKAGES=Panzer \
  ./run_all_builds.sh

Running Jenkins driver Trilinos-atdm-white-ride-cuda-9.2-debug.sh ...


real    17m35.590s
user    0m0.641s
sys     0m0.336s

Running Jenkins driver Trilinos-atdm-white-ride-cuda-9.2-opt.sh ...


real    24m28.444s
user    0m0.700s
sys     0m0.277s

Running Jenkins driver Trilinos-atdm-white-ride-cuda-9.2-release-debug.sh ...


real    39m36.349s
user    0m0.673s
sys     0m0.314s
```
and it posted results to:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-09&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride&field2=groupname&compare2=61&value2=Experimental

The test results for these three builds aggregated together are shown at:

* https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-white-ride&field2=groupname&compare2=61&value2=Experimental

This shows the most expensive tests sorted as:

| site | build name | status | time | details |
|--- |--- |--- | ---|--- |
| white25 | Trilinos-atdm-white-ride-cuda-9.2-release-debug | PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 | Failed | 10m 320ms | Completed (Timeout) |
| white25 | Trilinos-atdm-white-ride-cuda-9.2-release-debug | PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 | Failed | 10m 310ms | Completed (Timeout) |
| white24 | Trilinos-atdm-white-ride-cuda-9.2-opt | PanzerAdaptersSTK_PoissonInterfaceExample_2d_diffsideids_MPI_1 | Failed | 10m 80ms | Completed (Timeout) |
| white25 | Trilinos-atdm-white-ride-cuda-9.2-release-debug | PanzerAdaptersSTK_PoissonInterfaceExample_2d_diffsideids_MPI_1 | Failed | 10m 30ms | Completed (Timeout) |
| white24 | Trilinos-atdm-white-ride-cuda-9.2-opt | PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 | Passed | 5m 32s 430ms Completed |
| white25 | Trilinos-atdm-white-ride-cuda-9.2-release-debug | PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2 | Passed | 2m 57s 220ms | Completed |
| white24 | Trilinos-atdm-white-ride-cuda-9.2-opt | PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-2 | Passed | 2m 33s 830ms | Completed |

Let's just merge this branch and see what happens in automated testing.

I will go ahead and click the merge button!

**Pull request merged**
