### PR TITLE
Xpetra: update and test MapFactory

### PR DESCRIPTION
**Pull request by mayrmt**
@trilinos/xpetra 

## Motivation

When creating blocked systems, it is useful to be able to create maps with GID offsets. This PR enhances an existing `MapFactory::Build()` variant to accept such an offset. For backwards compatibility, the offset defaults to `0`.

Summary of changes:
- add unit tests for `MapFactory::Build()`
- add possibility to pass a user-defined GID offset to `MapFactory::Build(nodeMap, numDofsPerNode)`
- add some documentation

## Stakeholder Feedback

None.

## Testing

This PR adds unit tests.

## Additional Information

~~I'm not sure, if I got the ETI stuff for the new unit test file right. Any suggestions for improvement are welcome!~~

EDIT: Squashed my attempts to fix compiler warnings into one commit.

### CODE REVIEW

**Comment by mayrmt** [comment]
@trilinos/xpetra The auto-request for review by the Xpetra team via the code owner mechanism did not work.

**Comment by mayrmt** [comment]
Remove the RETEST label, as the auto-tested had started the third job in a row without the two previous one having finished. Weird...

**Comment by allevin** [comment]
@mayrmt I just took a look into the Autotester issue on this.  It looks like the Jenkins instance running the Autotester is having some issues.  Working to figure it out.

**Comment by mayrmt** [comment]
@allevin Thanks for looking into this!

**Comment by mayrmt** [comment]
Tests pass. This is ready for review and merging.

**Comment by mayrmt** [comment]
@trilinos/xpetra

**Review by cgcgcg — APPROVED** [review]

**Pull request merged**
