### PR TITLE
STK: Snapshot 06-11-21 09:00

### PR DESCRIPTION
**Pull request by tasmith4**
@trilinos/stk

### CODE REVIEW

**Review by alanw0 — DISMISSED** [review]
Just FYI that I will be putting in another snapshot this afternoon which will be either a fix or revert of the ghosting issue that is currently breaking nalu.

**Comment by spdomin** [comment]
@alanw0, is this held up for some process reason?

**Comment by alanw0** [comment]
@spdomin Yes the testing output shows stuff like this:
stderr: fatal: unable to access 'https://github.com/trilinos/Trilinos/': Could not resolve proxy: wwwproxy.sandia.gov; Name or service not known
As noted in the other email, Timothy has been in contact with the trilinos folks, who are try to resove the issue. Sorry for the delay, of course this couldn't have come at a worse time!

**Review by alanw0 — APPROVED** [review]

**Comment by spdomin** [comment]
Hi Alan. Is this still waiting? Does anyone have an idea or estimate when the ability to push will resume?

**Comment by tasmith4** [comment]
@spdomin I believe from a comment on another PR that @prwolfe is looking at it -- I haven't heard a recent estimate from him on the timeline.

**Comment by alanw0** [comment]
@spdomin @tasmith4 It looks like some other PRs got merged yesterday... I've reapplied the RETEST label on this one, hopefully it can get moving now...

**Comment by spdomin** [comment]
Yes, this seems like an uphill battle. I am still not sure what the core issue is here? Is this all about proxy changes?

**Comment by spdomin** [comment]
I will fire off a nightly test once I push some regression test tweaking..

**Pull request merged**
