### PR TITLE
Is STK really broken?

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Check to see if STK build is really broken in PR builds

### CODE REVIEW

**Comment by prwolfe** [comment]
Ross,

Did you look at the issues I filed - they explain why this got through the PR testing.

#3347  and #3348 

Basically one item was disabled in the PR build as it is a known issue and the other only occurs in a Serial build.

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52 

@prwolfe said:

> Did you look at the issues I filed - they explain why this got through the PR testing.
> 
> #3347 and #3348
> 
> Basically one item was disabled in the PR build as it is a known issue and the other only occurs in a Serial build.

The post-push CI build showed this failure since last Monday night and all of the ATDM Trilinos builds show this build failure.  How did the PR builds not show this?

**Comment by bartlettroscoe** [comment]
Okay, the [above PR build results](https://github.com/trilinos/Trilinos/pull/3357#issuecomment-416279604) show that indeed STK is not broken in all three PR builds.  Yet, STK is broken in almost every other Trilinos build shown yesterday [here](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2018-08-26&subproject=STK).

@prwolfe, what can we do to get the PR builds to be like all of the other ATDM and other Trilinos builds so that the PR builds properly protect all of these other builds?

**Comment by bartlettroscoe** [comment]
Okay, @jwillenbring explained that the PR builds passed because this test was disabled for the PR builds but for no other builds.  Looks like the PR #3361 will fix this.

I will go ahead and close this PR.  It served its purpose.

**Pull request closed without merging**
