### PR TITLE
EXODUS: Need to check whether nc_def_var_fill is defined in netCDF

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas

## Motivation
There are some older versions of netCDF that do not include the `nc_def_var_fill` call.  To avoid breaking the builds
of people using those versions, made the recent change that called that function only present if the netcdf library has the call enabled.

### CODE REVIEW

**Comment by gsjaardema** [comment]
Closes #12045

**Comment by ikalash** [comment]
I just tested this and unfortunately the error persists: 

```
FAILED: packages/seacas/applications/aprepro/aprepro
: && /tpls/install/bin/mpicxx -pedantic -Wall -Wno-long-long -Wwrite-strings -Wshadow -Woverloaded-virtual    -O3 -DNDEBUG  packages/seacas/applications/aprepro/CMakeFiles/aprepro.dir/aprepro.C.o -o packages/seacas/applications/aprepro/aprepro  -Wl,-rpath,/nightlyAlbanyTests/Results/Trilinos/build/packages/seacas/libraries/aprepro_lib:/nightlyAlbanyTests/Results/Trilinos/build/packages/seacas/libraries/exodus:/nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib:  packages/seacas/libraries/aprepro_lib/libaprepro_lib.so.14.3  packages/seacas/libraries/exodus/libexodus.so.14.3  /nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib/libnetcdf.so  /nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib/libhdf5.so  /usr/lib64/libz.so  /nightlyCDash/albany-tpls-gcc-11.1.1-openmpi-4.1.0/lib/libhdf5_hl.so && :
packages/seacas/libraries/exodus/libexodus.so.14.3: undefined reference to `nc_def_var_fill'
collect2: error: ld returned 1 exit status
```

**Comment by gsjaardema** [comment]
> I just tested this and unfortunately the error persists:
> 
> ```
> FAILED: packages/seacas/applications/aprepro/aprepro

OK, that's not good....  I will have to look at this a little more...
Is it correctly linking the exodus test programs, or is any link working?

**Comment by gsjaardema** [comment]
Found a call to the function that I had missed.  I built your version of netCDF with your config and then built seacas on top of it and it should work with the changes in this PR.  Sorry for the problems.

**Review by ikalash — APPROVED** [review]
This fixed the problem.  Thank you!

**Comment by ikalash** [comment]
This fixed the problem!  Thank you!  I just approved the PR.

**Pull request merged**
