### PR TITLE
Seacas 2021 06 24

### PR DESCRIPTION
**Pull request by gsjaardema**
Periodic Snapshot from SEACAS github repository:
 * FASTQ: Change mesage function name to message.  Makes it easier to check spelling of code.
 * FMT: Update to fmt-8.0.0
 * Eliminate unused variable warnings found by intel compiler.
 * additional spelling fixes found by `codespell`
 * GJOIN: Basic support for names
 * IOSS: Fix reading of embedded nodeblock fields in CGNS structured meshes
 * EXODUS: Python interface updates
 * IOSS: Intel build fixes -- intel identifies as a GCC compiler, but does not support all that GCC supports
 * IOSS: Eliminate maximum size limit on field suffices
 * IOSS: Handle mixed field with no separator and _ separator (will handle dispx, dispy, dispz, vel_x, vel_y, vel_z correctly)
 * IOSS: Add number_width test for >32 bit integers
 
@trilinos/seacas

### CODE REVIEW

**Comment by prwolfe** [comment]
@gdsjaar - The code looks ok, but can we get a bit more in the PR description?

**Review by prwolfe — APPROVED** [review]
Looks good, but the PR description needs fleshed out.

**Comment by gsjaardema** [comment]
@prwolfe Thanks.  I've updaed the PR description

**Comment by gsjaardema** [comment]
Looks like intel-17 can't handle the C++ code in the latest fmt-8.0.0 release...  Reverting that portion of this PR.

**Comment by prwolfe** [comment]
> Looks like intel-17 can't handle the C++ code in the latest fmt-8.0.0 release... Reverting that portion of this PR.

@jwillenbring, when we can stop supporting that one. I think Kokkos would like to let it go as well.

**Review by prwolfe — APPROVED** [review]

**Pull request merged**
