### PR TITLE
ROL: Remove nonexistent files from CMake

### LINKED ISSUE #3303: ROL missing ODEConstraint_TimeSimOpt.hpp
@trilinos/rol 

## Expectations

ROL installs without error

## Current Behavior

```
CMake Error at packages/rol/adapters/mpi/src/cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "/.../Trilinos/packages/rol/adapters/mpi/src/function/ODEConstraint_TimeSimOpt.hpp".
Call Stack (most recent call first):
  packages/rol/adapters/mpi/cmake_install.cmake:42 (include)
  packages/rol/cmake_install.cmake:72 (include)
  cmake_install.cmake:113 (include)
```

## Motivation and Context

Albany builds fail.

### PR DESCRIPTION
**Pull request by ibaned**
@trilinos/rol

## Description

Fix #3303 

## Motivation and Context

Albany builds

### CODE REVIEW

**Comment by dridzal** [comment]
So we’ve fixed this in ROL, and are running the ROL/Trilinos sync process.  Can we cancel this PR?  In the future, let’s coordinate.

**Comment by ibaned** [comment]
As long as the ROL/Trilinos sync process will complete within a day, thats fine. Otherwise it can be beneficial to patch this temporarily and then overwrite it with your sync, we do this for Kokkos bugs that slip into Trilinos as well.

**Comment by dridzal** [comment]
It will be done today.  Let's cancel this PR.

**Comment by dridzal** [comment]
As a side note, ROL is fully integrated into Trilinos; we are not snapshotting.  So, I don't think we can simply "overwrite," due to the two-way merge.  There may be conflicts, right?

**Pull request closed without merging**
