### PR TITLE
Workaround for Tpetra issue #1752. Enabling Tpetra test

### PR DESCRIPTION
**Pull request by searhein**
This is a workaround for the issue with Tpetra's import/export; see #1752.

### CODE REVIEW

**Comment by searhein** [comment]
@srajama1 I added `#ifdef Tpetra_issue_1752` to the changes.

**Comment by srajama1** [comment]
You have generated this PR to master. We cannot push to master. Can you close this and generate one against develop branch. You can push it yourself then.

**Comment by tjfulle** [comment]
@srajama1 @searhein , the PR can be edited to be against `develop`

**Comment by searhein** [comment]
Sorry. I changed the base to develop now.

**Pull request merged**
