### PR TITLE
Amesos2 Fix for older Umfpack versions. #1584 #1846

### PR DESCRIPTION
**Pull request by MicheldeMessieres**
For Umfpack versions <5 this changes the Umfpack test so it does not call complex.

This is because the wrapper currently relies on being able to pass Re-Im as a single array.
That is not supported in older Umfpack versions.

This PR also includes the changes taken from #1846 to remove the UMFPACK namespace and add the extern "C", which is not included in older umfpack.h files.

This PR will fix the Amesos2 Umfpack test to pass for both old and new versions.

This was tested on a gcc 4.8.5 linux machine for both Umfpack 4.1 and the most recent Umfpack from SuiteSparse.  Also ran a default SEMS for Amesos2 enabled.

### CODE REVIEW

**Comment by srajama1** [comment]
This looks good to me. @prwolfe , @MicheldeMessieres : Thank you for the fixes.

**Comment by ndellingwood** [comment]
Running checkin script now

**Comment by ndellingwood** [comment]
I pulled this PR, merged to develop, then ran checkin script. Everything passed and it was successfully pushed to Trilinos develop branch, and looks like @MicheldeMessieres and @prwolfe commits were preseverd. Thanks for the fixes!

**Comment by ndellingwood** [comment]
Closing this PR as the commits were pushed in via the checkin script and credit for work was preserved in the log messages.

**Pull request closed without merging**
