### PR TITLE
stokhos: revise use of Cuda impl routines from kokkos

### PR DESCRIPTION
**Pull request by ndellingwood**
Compatibility update needed for kokkos following kokkos/kokkos#6544
Address kokkos/kokkos#6561

Co-authored-by: Damien L-G <dalg24+github@gmail.com>

Thanks @dalg24 for suggested update!

@trilinos/stokhos @etphipp 

## Motivation

Resolve compilation errors with Cuda backend

## Testing

**Local test (stokhos only) with sems-cuda/11.4.2**:
```
...
98% tests passed, 1 tests failed out of 66

Label Time Summary:
Stokhos    = 132.16 sec*proc (66 tests)

Total Test time (real) =  74.11 sec

The following tests FAILED:
   45 - Stokhos_TpetraCrsMatrixUQPCEUnitTest_Cuda_MPI_4 (Failed)
Errors while running CTest
```

where Stokhos_TpetraCrsMatrixUQPCEUnitTest_Cuda_MPI_4 is known failure #12427 

**Configuration**:
```
module purge
module load sems-gcc/8.5.0 sems-cuda/11.4.2 sems-cmake sems-git sems-openmpi/4.1.4 sems-ninja
export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

# Configure Trilinos
cmake \
 -GNinja \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="17" \
 -DTPL_ENABLE_MPI:BOOL=ON \
 -DTPL_ENABLE_BLAS:BOOL=ON \
 -DTPL_ENABLE_LAPACK:BOOL=ON \
 -DTPL_ENABLE_CUSPARSE:BOOL=ON \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_ENABLE_CUDA_LAMBDA=ON \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
 -DTrilinos_ENABLE_Stokhos=ON \
  -DStokhos_ENABLE_TESTS=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

### CODE REVIEW

**Review by etphipp — APPROVED** [review]
Looks great, thanks!

**Comment by ndellingwood** [comment]
The cuda build failed in a Panzer test due to timeout [PanzerMiniEM_Darcy_MueLu_order1_MPI_1](https://trilinos-cdash.sandia.gov/test/39614928)
@cgcgcg @etphipp does this PanzerMiniEM_Darcy_MueLu_order1_MPI_1 test use Stokhos?

**Comment by ndellingwood** [comment]
I'm curious if the timeout occurs consistently with this change, retesting

**Comment by cgcgcg** [comment]
I don't think Panzer has a dependency on Stokhos. But it does depend on Sacado. Could that have an impact? I only added the test in question a couple of days ago, so it could also be that it takes too long under load.

**Comment by ndellingwood** [comment]
@cgcgcg Thanks for the quick reply! These changes would only impact Stokhos (and really should not result in any difference, they essentially move some impl stuff over from Kokkos). I suspect your guess that the test time may be impacted under load might be the case here. We'll see how it looks after a retest

**Comment by ndellingwood** [comment]
The [PanzerMiniEM_Darcy_MueLu_order1_MPI_1](https://trilinos-cdash.sandia.gov/test/39661729) test timed out in the Cuda build again

**Comment by ndellingwood** [comment]
There were two consecutive nightly builds with gcc/8.3.0 (no cuda) posting timeouts for the PanzerMiniEM_Darcy_MueLu_order1_MPI_1 test, independent of the changes in this PR. I'll test on the son sems gpu machine to see if I can reproduce the cuda failures in the PR and see if applying the RUN_SERIAL option to this test helps avoid the timeout

**Comment by rppawlo** [comment]
@ndellingwood - if that doesn't work, then please just disable the test. Its new and obviously there is something that needs to be fixed.

**Comment by ndellingwood** [comment]
@cgcgcg @rppawlo @etphipp I updated the frameworks ini config to set the `PanzerMiniEM_Darcy_MueLu_order1_MPI_1` to RUN_SERIAL to see how that goes with the AT. Since this occurred with cuda and serial gcc/8.3.0 builds I placed the setting in the most general location. My change marked the PR stale, could one of you reapprove?

Adding @trilinos/framework @sebrowne to the thread since I made an update to the config-specs.ini file, can you confirm if the change I made is acceptable or needs to be handled differently?

**Review by cgcgcg — DISMISSED** [review]
I approve of running that test in serial. If that indeed fixes things I should go back and see why this particular one likes to hang.

**Comment by rppawlo** [comment]
Thanks @ndellingwood ! I think we really want to set in this in the tribits_add_advanced_test macro for this test. Setting this in the .ini file means it only runs in serial for the autotester. Anyone not using genconfig (e.g. external users, devs with their own cmake scripts, and spack users) will probably see this issue in their local testing.

**Comment by ndellingwood** [comment]
Adding the RUN_SERIAL got the test to passing, so that is useful data point testing that in the AT environemtn

> I think we really want to set in this in the tribits_add_advanced_test macro for this test

@rppawlo @cgcgcg should I merge this as is (this will get Cuda builds with kokkos core/kernels develop branches compiling again) and I'll follow on with a `tribits_add_advanced_test` update?

**Comment by ndellingwood** [comment]
@rppawlo @cgcgcg I added the `RUN_SERIAL` option to the CMakeLists.txt file for the Darcy_MueLu test in b3d9fb62bf054e6e9527e92c82f51fc933a3d2fc, can you confirm and reapprove if this is sufficient for testing beyond the AT config option?

**Review by rppawlo — DISMISSED** [review]
Thanks @ndellingwood ! Looks good to me. You could remove the change to the .ini file since it is now covered in the change to the cmake file.

**Review by sebrowne — CHANGES_REQUESTED** [review]
As Roger stated, if we can omit an extra entry from `config-specs.ini` I'd like to do that for the sake of readability.  But yes, this change was correct if you wanted to change the setting in this file (FWIW I agree with Roger that this belongs in the `CMakeLists.txt`, so thanks!)

**Comment by ndellingwood** [comment]
cb94104f99b3bd7e75c9582d2d76b038cce40124 contains the revert of the `config-specs.ini` file change; @rppawlo @sebrowne I'll need a reapproval please, thanks!

**Review by sebrowne — COMMENTED** [review]
Approved from the perspective of it doesn't change Framework code any more.  Will defer to others for technical changes.

**Review by rppawlo — APPROVED** [review]

**Comment by sebrowne** [comment]
> @sebrowne the PR-gcc-openmpi build failed during runner setup:
> 
> ```
> CMakeCache.txt
>  Error: Value cannot be null. (Parameter 'ContainerId')
> ```
> 
> Should I just retest?

It shouldn't require that to pass to merge the PR.  This is intentional while the new github-actions-based stuff is being worked.  If you see failures, feel free to tag framework or @fryeguy52 and @cabejackson so that they can take a look.

**Comment by ndellingwood** [comment]
@trilinos/framework @fryeguy52 @cabejackson @sebrowne just to check this is intentional, it appears the AUTOMERGE label is disabled when the PR-gcc-openmpi job fails, e.g.
```
Cannot Merge Pull Request# 12466: Github Mergeability = unstable; Git Mergeable = True
```

The PR-gcc-openmpi failed earlier in this PR due apparent issues at the runner loading stage (some error with CMakeCache.txt)

**Comment by sebrowne** [comment]
Hmmmm perhaps not intentional, but I'm glad that it did allow you to merge.  We will investigate if there is a way to get AUTOMERGE to work even while the new PR build fails.  Worst case, AUTOMERGE is broken until we transition.  Although, once we get a few little hiccups resolved, that build should start passing so that may fix it as well.

**Pull request merged**
