### PR TITLE
Fix <tplName>Config.cmake files to not point into build dir (#10774)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Updated TriBITS snapshot that fixes the installed `<tplName>Config.cmake` files to not point into the build tree (part of #10774).

Snapshot contains the updates from the TriBITS PRs:

* https://github.com/TriBITSPub/TriBITS/pull/499
* https://github.com/TriBITSPub/TriBITS/pull/501

It is urgent to get this merged ASAP as this is breaking integration processes with SPARC and GEMMA.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Hello @rppawlo, can you please approve this PR?  This is needed to fix integration builds with SPARC and GEMMA (and likely many other codes as well).

**Review by rppawlo — APPROVED** [review]

**Comment by jwillenbring** [comment]
@bartlettroscoe I have been monitoring the status of this PR. The current tests are nearly complete, and 6 jobs have passed, 1 failed and 1 is still pending. If the other job passes, I am inclined to force merge this PR because the 2 tests that failed in the new CUDA 11 PR job are randomly failing for other PRs. We are working to solidify that job, but especially given the system downtime scheduled for early next week, I think we could merge this if everything else looks good. Please comment or react to indicate your agreement or disagreement with this plan.

**Comment by jwillenbring** [comment]
I looked more carefully at the context and contents of the commits, and I plan to force merge this after the testing completes unless someone objects or something very unexpected happens in the remaining test results.

**Comment by glhenni** [comment]
GEMMA is back up and running. Thanks @bartlettroscoe and @jwillenbring

**Comment by jwillenbring** [comment]
@glhenni 

> GEMMA is back up and running. Thanks @bartlettroscoe and @jwillenbring

Glad to hear it, thanks for reporting back.

**Pull request merged**
