### PR TITLE
Tempus: fails to be compiled in ubuntu with gcc (#7522)

### LINKED ISSUE #7522: Tempus: fail to compile with gcc in linux when Tempus_enable_tests turns on
## Bug Report
@trilinos/\Tempus

### Description
When compiled in Ubuntu 18 with gcc 7.5, or Centos 7.2 with gcc 4.8.5, Compiling fails with the following message

In file included from /Trilinos/packages/tempus/src/Tempus_StepperForwardEulerModifierDefault.hpp:14:0,
                 from Trilinos/packages/tempus/src/Tempus_StepperForwardEuler_impl.hpp:14,
                 from /Trilinos/build/packages/tempus/src/Tempus_StepperForwardEuler.hpp:2,
                 from /Trilinos/packages/tempus/src/Tempus_StepperForwardEulerAppAction.hpp:14,
                 from /Trilinos/packages/tempus/src/Tempus_StepperForwardEuler_decl.hpp:17,
                 from /Trilinos/build/packages/tempus/src/Tempus_StepperForwardEuler.hpp:1,
                 from /Trilinos/packages/tempus/src/Tempus_StepperFactory.hpp:13,
                 from /Trilinos/packages/tempus/src/Tempus_IntegratorBasic_impl.hpp:14,
                 from /Trilinos/build/packages/tempus/src/Tempus_IntegratorBasic.hpp:2,
                 from /Trilinos/packages/piro/src/Piro_TempusIntegrator.hpp:48,
                 from /Trilinos/packages/piro/src/Piro_TransientSolver.hpp:48,
                 from /Trilinos/packages/piro/src/Piro_TempusSolver.hpp:53,
                 from /Trilinos/packages/piro/src/Piro_SolverFactory_Def.hpp:60,
                 from /Trilinos/packages/piro/src/Piro_SolverFactory.hpp:94,
                 from /Trilinos/packages/piro/test/Main_ThyraSolver.cpp:48:
/Trilinos/packages/tempus/src/Tempus_StepperForwardEulerModifierBase.hpp:47:56: error: expected template-name before ‘<’ token
   : virtual public Tempus::StepperForwardEulerAppAction<Scalar>

  And vast number of relative errors. 

### Steps to Reproduce
Follows are my configuration:
cmake .. \
  -DCMAKE_INSTALL_PREFIX:FILEPATH="~/programs/solver/Trilinos/install" \
  -DCMAKE_CXX_COMPILER=mpic++ \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_BUILD_TYPE:STRING=RELEASE \
  -DHDF5_INCLUDE_DIRS=/usr/include/hdf5/openmpi  \
  -DHDF5_LIBRARY_DIRS=/usr/lib/x86_64-linux-gnu/hdf5/openmpi  \
  -DTPL_ENABLE_MPI:BOOL=ON \
  -DTPL_ENABLE_HDF5=ON  \
  -DTPL_ENABLE_Matio=OFF  \
  -DTrilinos_ENABLE_Fortran=ON \
  -DTrilinos_ENABLE_SEACAS=ON \
  -DTrilinos_ENABLE_Panzer=ON  \
  -DTrilinos_ENABLE_STK=ON  \
  -DPiro_ENABLE_TESTS=ON \

  Nothing happens when Tempus related tests, such as Tempus_ENABLE_TESTS or Pito_ENABLE_TESTS turns off.

### PR DESCRIPTION
**Pull request by hillyuan**
@trilinos/Tempus
@ccober6 

#### Compiling fails to be compiled by ubuntu + gcc and centos + gcc. It is considered due to the cross dependent between head files inside following four files:

> Tempus_StepperBackwardEulerAppAction.hpp
> Tempus_StepperForwardEulerAppAction.hpp
> Tempus_StepperOperatorSplitAppAction.hpp
> Tempus_StepperSubcyclingAppAction.hpp

The details are follows ( Tempus_StepperBackwardEulerAppAction.hpp as an example)
1.  Line 14: #include "Tempus_StepperBackwardEuler.hpp" seems like to include defintion of class StepperBackwardEuler, which is forward declared in line 20. It is therefore line 14 should not be needed.
2.  File Tempus_StepperBackwardEuler.hpp includes file "Tempus_StepperBackwardEulerAppAction.hpp". It means these two files depend upon each other, which would gives rise to compile error when using some, maybe some old, compilers

It is therefore this bug could be fixed just to delete line 14.

## Related Issues

Closes #7522

## Testing
Test passed in Ubuntu 18 with gcc 7.5 and  Centos 7.2 with gcc 4.8.5

### CODE REVIEW

**Comment by ccober6** [comment]
@hillyuan Ah very cool you tracked this down!  I want to include some documentation to this, along with make changes to some upcoming PRs for other stepper AppActions, so I am going to create another PR and incorporate your changes with it.  Hopefully this is agreeable to you.

**Comment by hillyuan** [comment]
Thanks @ccober6 . It would be great you can fix it.

**Comment by ccober6** [comment]
It is already in #7539, and should be reviewed in the next day or so.  Thanks for your efforts!

**Comment by ccober6** [comment]
Closed in favor of #7539

**Pull request closed without merging**
