### PR TITLE
Ifpack2 (and Tpetra): refined timers and parallel createMeshMap

### PR DESCRIPTION
**Pull request by kliegeois**
This PR adds extra (optional) timers and fences to the Ifpack2 BTD solvers and add a parallel implementation of the Tpetra function createMeshMap.

### CODE REVIEW

**Comment by jhux2** [comment]
@trilinos/framework There's a build error reported, but no details about the failure.

**Comment by kliegeois** [comment]
I fixed couple of warnings treated as errors. I am not sure if this solves the issue but that should not hurt!

**Comment by kliegeois** [comment]
> I fixed couple of warnings treated as errors. I am not sure if this solves the issue but that should not hurt!

They were already fixed in upstream/develop; I cleaned the PR but it is back to its original state.

**Comment by jmlapre** [comment]
FYI more gitlab issues, retesting.  @trilinos/framework will make our tooling more resilient to these failures given their frequency.

**Comment by sebrowne** [comment]
Trying to address those git issues via #13336 @jmlapre @achauphan

**Comment by kliegeois** [comment]
Retesting as #13336 is merged.

**Comment by kliegeois** [comment]
🎊

**Pull request merged**
