### PR TITLE
Fix and reapply: TriBITS: Pull in partial refactoring to modern CMake targets (TriBITSPub/TriBITS#299) (#9894, #9972, #9973)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
This PR reverts the revert commit from PR #9977 and therefore reapplies the merge of PR #9894.

This PR branch addresses the issues reported in #9972 and #9973 and listed in  TriBITSPub/TriBITS#433 and offers the chance for developers to try out these changes in their own configurations so we can get this fixed.

In addition to reverting the revert commit from PR #9977, this also pulls in the additional TriBITS PRs (listed most recent to least recent):

* TriBITSPub/TriBITS#459
* TriBITSPub/TriBITS#456
* TriBITSPub/TriBITS#453
* TriBITSPub/TriBITS#452
* TriBITSPub/TriBITS#450
* TriBITSPub/TriBITS#449
* TriBITSPub/TriBITS#447
* TriBITSPub/TriBITS#446
* TriBITSPub/TriBITS#445
* TriBITSPub/TriBITS#444
* TriBITSPub/TriBITS#441
* TriBITSPub/TriBITS#440
* TriBITSPub/TriBITS#439
* TriBITSPub/TriBITS#438
* TriBITSPub/TriBITS#436
* TriBITSPub/TriBITS#435
* TriBITSPub/TriBITS#432

This PR also addresses issues with several application codes.

**NOTE:** This PR breaks backward compatibility of the usage of `<Package>Config.cmake` files from Trilinos.  (See release note for Trilinos 14.0 [here](https://github.com/bartlettroscoe/Trilinos/blob/3281be9b5af148f16d9f507519d3e06b916b675c/RELEASE_NOTES#L7-L73))

## Tasks:

* [x] Reproduce and resolve issues with Albany (#9972 and [internal tribitsrefactoring#1](https://cee-gitlab.sandia.gov/rabartl/tribitsrefactoring/-/issues/1))
* [x] Bring back DEPRECATED non-namespace IMPORTED targets (see https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1011558738).
* [x] Reproduce and resolve issues with Nalu (#9973 and [internal tribitsrefactoring#2](https://cee-gitlab.sandia.gov/rabartl/tribitsrefactoring/-/issues/2))
* [x] Reproduce and resolve issues with SPARC ([SPAR-1074](https://sems-atlassian-srn.sandia.gov/browse/SPAR-1074) and [internal tribitsrefactoring#3](https://cee-gitlab.sandia.gov/rabartl/tribitsrefactoring/-/issues/3))
* [x] Add documentation on break in backward compatibility with `-I` to `-isystem` for Trilinos includes.
* [ ] Get green-light to merge this (i.e. once Trilinos 13.4 branch is created, see #10191)
* [ ] Get this PR approved to be merged and pass PR testing
* [ ] Merge this PR

### Testing against ATDM Trilinos builds using -mkl

To verify the problem with the `-mkl` option is resolved with the ATDM Trilinos builds described [below](https://github.com/trilinos/Trilinos/pull/9978#issuecomment-982834778) with this PR branch, I ran the ATDM Trilinos 'sems-rhel7' builds on the CEE machine 'cee-build015' and posted to CDash at:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-12-15&filtercount=4&showfilters=1&filtercombine=and&field1=site&compare1=63&value1=cee-build015&field2=buildname&compare2=62&value2=Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug-exp&field3=buildstarttime&compare3=83&value3=2021-12-15T18%3A31%3A11%20UTC&field4=buildstarttime&compare4=84&value4=2021-12-16T02%3A15%3A20%20UTC

This showed no new failures.  See details below.

<details>

<summary><b>Detailed ATDM Trilinos 'sems-rhel7' build and test results</b> (click to expend)</summary>

.

Running ATDM Trilinos 'sems-rhel7' builds on 'cee-build015':

```
$ cd cee-build015

$ /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CTEST_S/

$ rm -r Trilinos-atdm-sems-rhel7-*

$ env ./ctest-s-local-test-driver.sh all
```

That is submitting to CDash (excluding the CUDA build since that machine does not have a GPU):

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-12-15&filtercount=4&showfilters=1&filtercombine=and&field1=site&compare1=63&value1=cee-build015&field2=buildname&compare2=62&value2=Trilinos-atdm-sems-rhel7-cuda-10.1-Volta70-complex-shared-release-debug-exp&field3=buildstarttime&compare3=83&value3=2021-12-15T18%3A31%3A11%20UTC&field4=buildstarttime&compare4=84&value4=2021-12-16T02%3A15%3A20%20UTC

which gives:

<html>
<body>

| Site | Build Name | Conf Error| Conf Warn | Conf Test Time | Build Error| Build Warn | Build Test Time | Start Test Time | Labels |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
cee-build015 | Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug-exp | 0 | 1 | 2m 35s | 0 | 15 | 3h 55m 45s | 0 | 0 | 2152 | 17m 15s | 2h 23m 24s | 19 hours ago | (29 labels)
cee-build015 | Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-debug-exp | 0 | 1 | 2m 18s | 0 | 15 | 1h 42m 27s | 0 | 0 | 2147 | 41m 28s | 5h 17m 27s | 22 hours ago | (29 labels)
cee-build015 | Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug-exp | 0 | 0 | 1m 5s | 0 | 13 | 1h 47m 27s | 0 | 0 | 1252 | 6m 31s | 53m 20s | Dec 15, 2021 - 14:53 MST | (15 labels)
cee-build015 | Trilinos-atdm-sems-rhel7-gnu-7.2.0-openmp-complex-shared-release-debug-exp | 0 | 0 | 52s | 0 | 17 | 24m 31s | 0 | 0 | 1252 | 5m 39s | 47m 59s | Dec 15, 2021 - 14:22 MST | (15 labels)
cee-build015 | Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug-exp | 0 | 1 | 2m 15s | 4 | 39 | 1h 9m 14s | 1 | 0 | 2151 | 16m 3s | 2h 14m 18s | Dec 15, 2021 - 11:31 MST | (29 labels)

</body>
</html>

(NOTE: The build errors for the build `Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug` for the package `Krino` are also see in the reference Trilinos builds on 2021-12-12 and are therefore not caused by the TriBITS changes.)

The configure output for the Intel 18 build  showin [here](https://testing-dev.sandia.gov/cdash/build/6750367/configure) which uses `-mkl` shows:

```
Processing enabled TPL: BLAS (enabled explicitly, disable with -DTPL_ENABLE_BLAS=OFF)
-- BLAS_LIBRARY_NAMES='blas blas_win32'
-- TPL_BLAS_LIBRARIES='-mkl'
NOTE: Moving the general link argument '-mkl' in TPL_BLAS_LIBRARIES forward on the link line which may change the link and break the link!
Processing enabled TPL: LAPACK (enabled explicitly, disable with -DTPL_ENABLE_LAPACK=OFF)
-- LAPACK_LIBRARY_NAMES='lapack lapack_win32'
-- TPL_LAPACK_LIBRARIES='-mkl'
NOTE: Moving the general link argument '-mkl' in TPL_LAPACK_LIBRARIES forward on the link line which may change the link and break the link!
```

I also examined the generated generated files `BLASConfig.cmake` and `LAPACKConfig.cmake` show which show:

`Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug/SRC_AND_BUILD/BUILD/external_packages/BLAS/BLASConfig.cmake`
```
# Package config file for external package/TPL 'BLAS'
#
# Generated by CMake, do not edit!

include_guard()

add_library(BLAS::all_libs INTERFACE IMPORTED GLOBAL)
target_link_options(BLAS::all_libs
  INTERFACE "-mkl"
  )
```

`Trilinos-atdm-sems-rhel7-intel-18.0.5-openmp-shared-release-debug/SRC_AND_BUILD/BUILD/external_packages/LAPACK/LAPACKConfig.cmake` 
```
# Package config file for external package/TPL 'LAPACK'
#
# Generated by CMake, do not edit!

include_guard()

add_library(LAPACK::all_libs INTERFACE IMPORTED GLOBAL)
target_link_options(LAPACK::all_libs
  INTERFACE "-mkl"
  )
```

Those look correct.

But note that the targets `BLAS::all_libs` and `LAPACK:all_libs` are not used to actually link so this is not a full validation of this approach.  However, I manually tested moving `-mkl` option to the beginning of the link line and it still worked (but if you took, `-mkl` off the link lines, the link failed).

Therefore, I am pretty confident that this should work.

</details>

**Other tests?***

### CODE REVIEW

**Comment by ndellingwood** [comment]
@bartlettroscoe prior to the changes of #9894 I've had to configure my Trilinos builds (gcc compilers) that use locally installed BLAS and LAPACK (not found on system PATH) by specifying the libraries, as well as the gfortran and math libs to prevent linker errors, using sample configure commands like this (OpenBlas my local install referenced here):
```
...
  -D TPL_ENABLE_BLAS:STRING=ON \
   -D TPL_BLAS_LIBRARIES:PATH="${OPENBLAS_PATH}/lib/libopenblas.a;gfortran;gomp;m" \
  -D TPL_ENABLE_LAPACK:STRING=ON \
   -D TPL_LAPACK_LIBRARIES:PATH="${OPENBLAS_PATH}/lib/libopenblas.a;gfortran;gomp;m" \
...
```

After the #9894 changes my builds would fail at configuration with messages like:
```
CMake Error at cmake/tribits/core/utils/MessageWrapper.cmake:75 (message):
  ERROR: Can't handle argument 'm' in list TPL_BLAS_LIBRARIES
...
CMake Error at cmake/tribits/core/utils/MessageWrapper.cmake:75 (message):
  ERROR: Can't handle argument 'gomp' in list TPL_BLAS_LIBRARIES
...
```

Once this PR moves out of WIP, should TPL configure commands like I posted resume working? If not, is a different delimiter from the semi-colon expected, or will the process change for specifying additional libraries that need to be explicitly linked with TPLs?

**Comment by bartlettroscoe** [comment]
```
   -D TPL_ENABLE_BLAS:STRING=ON \
   -D TPL_BLAS_LIBRARIES:PATH="${OPENBLAS_PATH}/lib/libopenblas.a;gfortran;gomp;m" \
 ```

@ndellingwood, I was not aware that you could just pass in a library name `<libname>` instead of `-l<libname>` to `target_link_libraries()`.  But now I see that is a valid documented usage at:

* https://cmake.org/cmake/help/v3.17/command/target_link_libraries.html#overview

I will update the logic in the new TriBITS code to allow a raw string name `<libname>` to assume it is a a library name and treat it the same as `-l<libname>`.  That should resolve these use cases.

Thanks for reporting this!

**Comment by bartlettroscoe** [comment]
FYI: Another problem with the updated TriBITS in PR #9894 is not allowing options like `-mkl` like are used in a lot of the ATDM Trilinos builds as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-11-27&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=configureerrors&compare3=43&value3=0

We see errors like [here](https://testing.sandia.gov/cdash/build/10299926/configure) showing:

```
-- TPL_BLAS_LIBRARIES='-mkl'
CMake Error at /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/utils/MessageWrapper.cmake:75 (message):
  ERROR: Can't handle argument '-mkl' in list TPL_BLAS_LIBRARIES
Call Stack (most recent call first):
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/package_arch/TribitsExternalPackageWriteConfigFile.cmake:293 (message_wrapper)
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/package_arch/TribitsExternalPackageWriteConfigFile.cmake:208 (tribits_external_package_process_libraries_list)
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/package_arch/TribitsExternalPackageWriteConfigFile.cmake:67 (tribits_external_package_write_config_file_str)
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/package_arch/TribitsTplFindIncludeDirsAndLibraries.cmake:684 (tribits_external_package_write_config_file)
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/common_tpls/FindTPLBLAS.cmake:79 (TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES)
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:108 (include)
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1572 (tribits_process_enabled_tpl)
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:196 (tribits_process_enabled_tpls)
  /gpfs1/jenkins/chama-slave/workspace/Trilinos-atdm-tlcc2-intel-debug-openmp/Trilinos/cmake/tribits/core/package_arch/TribitsProject.cmake:93 (tribits_project_impl)
  CMakeLists.txt:109 (TRIBITS_PROJECT)
```

I think to address this, we need to update the TriBITS logic to allow the handling of compiler options like this.  I need to check and see if the location of the `-mkl` option matters or not.  If the order does matter, then I think we are in trouble.  If the order does not matter, then we can just handle it as a general linker flag.  I will see if that is the issue.

**Comment by bartlettroscoe** [comment]
Note that in both #9972 and #9973, the `find_package(Trilinos)` command is returning `FALSE` for `Trilinos_FOUND`.  It looks like these Apps may not be adding `REQUIRED` to their calls of `find_package(Trilinos COMPONENTS ...)`?

I will try to reproduce and see what is going on.

**Comment by bartlettroscoe** [comment]
FYI: I found the problem with #9972.  The issue is that Trilinos/TriBITS generated the `STKConfig.cmake` file with no includes of upstream packages or subpackages.  Instead, it contains the text:

```
## The TPLs enabled for this project
set(STK_TPL_LIST "")

# Include configuration of dependent packages

# Include configuration of dependent external packages/TPls

# Import STK targets
include("${CMAKE_CURRENT_LIST_DIR}/STKTargets.cmake")
```

I tried to reproduce with a full SEMS configuration of Trilinos and I could not reproduce.  But this should be easy to debug (and hopefully produce a TriBITS test to catch without a lot of work).

**Comment by alanw0** [comment]
@bartlettroscoe Let me know if that means that anything needs to be fixed or improved in stk's cmake stuff. Thanks!

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Let me know if that means that anything needs to be fixed or improved in stk's cmake stuff. Thanks!

@alanw0, it is definingly not a STK CMake bug, it is a TriBITS bug related to work for TriBITSPub/TriBITS#299.  I have reproduced the problem with a native TriBITS test and will fix this.  (I was missing a test case.)

**Comment by spdomin** [comment]
We are still trying to understand this latest change and why we are seeing diffs when running Nalu against this PR. 

Below is some recent activity:

Good:
 
12/16/2021 NaluRtest 
100% tests passed, 0 tests failed out of 75
NaluCFD/Nalu SHA1: 11940e2700d4b94d46b75efe572f2579148c098f
Trilinos/develop SHA1: 9732a48c693710143969237a949c5995c61d79a2
 
Bad:
 
commit 11940e2700d4b94d46b75efe572f2579148c098f (HEAD -> master, origin/master, origin/HEAD)
commit 963854c47d1233012ba176fbb1aea45cc9dddc17 (HEAD -> tribits-299-modern-cmake-targets-1-again, bartlettroscoe/tribits-299-modern-cmake-targets-1-again)
 
 1/75 Test #75: waleElemXflowMixFrac3.5m ...............***Failed  285.16 sec
      Start 33: hoHelium
 2/75 Test #73: oversetHybrid ..........................***Failed  495.67 sec
      Start 32: heliumPlume

However, running the current version of all codes results in:

Good:

100% tests passed, 0 tests failed out of 75
NaluCFD/Nalu SHA1: 11940e2700d4b94d46b75efe572f2579148c098f
Trilinos/develop SHA1: 93bbee4451491b12b2db522b4c4180d31f066234

**Comment by jewatkins** [comment]
This PR also still breaks the sparc arm build. For some reason, an old gtest from yaml-cpp is included and the build is prioritizing that path. One option is to unload yaml-cpp if this is getting pushed. @sebrowne would have to be included in that conversation though.

**Comment by bartlettroscoe** [comment]
> For some reason, an old gtest from yaml-cpp is included and the build is prioritizing that path.

@jewatkins, that is interesting.  I definingly need to be able to reproduce these builds on my own to examine what is happening here.   If someone can get met set up offline to be able to reproduce these builds, then that would be great.  If there is an internal issue tracking system we can use to track and resolve this, then that would would be best (opposed to emails).

**Comment by bartlettroscoe** [comment]
It seems pretty clear from Nalu testing documented [above](https://github.com/trilinos/Trilinos/pull/9978#issuecomment-996057077) (and in emails) and Albany testing documented in https://github.com/trilinos/Trilinos/issues/9972#issuecomment-996232035 that there is something wrong with this version of the build system in this branch.  Therefore, I am going to make sure and track down these issues with Nalu and Albany before merging this branch.

**Comment by bartlettroscoe** [comment]
FYI: The problem with Albany is resolved in https://github.com/sandialabs/Albany/pull/778 and was due to nonstandard usage of Trilinos.  But if other Apps are doing this as well, then we may have a major problem.  I discuss in more detail in TriBITSPub/TriBITS#299.

**Comment by spdomin** [comment]
> FYI: The problem with Albany is resolved in [sandialabs/Albany#778](https://github.com/sandialabs/Albany/pull/778) and was due to nonstandard usage of Trilinos. But if other Apps are doing this as well, then we may have a major problem. I discuss in more detail in [TriBITSPub/TriBITS#299](https://github.com/TriBITSPub/TriBITS/issues/299).

@bartlettroscoe, My apologies. These threads are multiple pages long - filled with much detail. Do we have a synapsis of what is an example of what Albany is doing that is nonstandard and if Nalu is doing this as well? My guess is that this would be a simple set of config changes on either code. Let me know how we can possibly improve our interface with Trilinos.

**Comment by bartlettroscoe** [comment]
> Do we have a synapsis of what is an example of what Albany is doing that is nonstandard and if Nalu is doing this as well? 

@spdomin, as is summarized in https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1012233092, don't directly link against the non-namepaced IMPORTED Trilinos targets like:

```
target_link_libraries(xml2yaml teuchosparameterlist)
```

to link against a subset of package libraries from Trilinos after calling `find_package(Trilinos)`.  Instead, use to the variables `${<Package>_LIBRARIES}`, in this case:

```
target_link_libraries(xml2yaml PUBLIC ${TeuchosParameterList_LIBRARIES})
```

which works with old and new TriBITS/Trilinos (and has worked for 8 years or so).

The problem is explained in more detail in https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1011558738.

But once we can merge this PR to Trilinos 'develop' and 'master' (and it stays merged), then customers can switch use modern CMake targets `<Package>::all_libs` by changing to:

```
target_link_libraries(xml2yaml PUBLIC TeuchosParameterList::all_libs)
```

and can eliminate usage of all of the `???_INCLUDE_DIDR` and `???_TPL_INCLUDE_DIR` vars.

However, I looked through the Nalu CMakeLists.txt files and I can't find any examples linking to non-namespaced Trilinos targets.  My next task with Nalu is to do a careful comparison of a working reference build of Nalu + Trilinos against the same versions with the TriBITS changes and then look for differences.  (That is how I debugged the Albany issue as documented in [internal tribitsrefactoring#1](https://cee-gitlab.sandia.gov/rabartl/tribitsrefactoring/-/issues/1).)

However, before that, I need to implement ***option-1*** summarized in https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1012363825 while the issues are fresh in my mind. (See the updated list of **Tasks** [above](https://github.com/trilinos/Trilinos/pull/9978#issue-1066483507).)

Thanks for keeping tabs on this.

**Comment by bartlettroscoe** [comment]
FYI: It was just announced that Trilinos 13.4 will be cut on 2/8/2022 and Trilinos 14.0 will be cut on 5/17/2022.  Given that we have identified that we need to [put back and deprecate non-namespaced targets](https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1012233092), it would be very helpful to get this PR updated and merged to Trilinos 'develop' and merge Trilinos 'develop' to 'master' before 2/8/2022.

Otherwise, anything we deprecate as part of this work may need to be maintained for several years to come waiting for Trilinos 15.0 to be cut.  (But perhaps that is how it should be given the nature of these changes.)

**Comment by ccober6** [comment]
@bartlettroscoe It is probably good to try to get in anything you would like for Trilinos 14.0, but I wanted to noted that we are shooting for an annual major release.

**Comment by bartlettroscoe** [comment]
I do believe that this branch does not break Nalu as summarized in https://cee-gitlab.sandia.gov/rabartl/tribitsrefactoring/-/issues/2#note_2139332.  There were zero build or test failures.

**Comment by bartlettroscoe** [comment]
FYI: I figured out the problem with SPARC.  See https://github.com/TriBITSPub/TriBITS/issues/443#issuecomment-1027507182.   We will discuss this in TriBITSPub/TriBITS#443.

**Comment by bartlettroscoe** [comment]
NOTE: With the merge of internal MR [sparc/sparc-ear99!890](https://cee-gitlab.sandia.gov/sparc/sparc-ear99/-/merge_requests/890), SPARC now has its own internal build of gtest that will be used instead of any other gtest installed in Trilinos or on the system (because the include dirs for the internally built gtest are included with -I and come before all other include dirs).

Therefore, the last thing to do before I can merge this TriBITS update to Trilinos 'develop' is to document the break in backward compatibility with this move to modern CMake (see **Tasks** in https://github.com/TriBITSPub/TriBITS/issues/443).

**Comment by bartlettroscoe** [comment]
NOTE: As this PR brings back the merge from PR #9977 which involves relevant commits from TriBITS going back to TriBITSPub/TriBITS@cccbfb810410793ec6a92bcff69224716278a892 from 9/7/2022.

That means that Trilinos 'develop' is now exactly 6 months behind TriBITS 'master'!  That is not good.

**Comment by bartlettroscoe** [comment]
FYI: The CUDA build results are shown at:

* https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-9978-test&field2=buildstarttime&compare2=84&value2=NOW

It shows the build:

* [PR-9978-test-ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables-503](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=53784&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and)

with a configure error:

```
-- Check for working CXX compiler: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx - broken
CMake Error at /projects/sparc/tools/cmake/3.19.4/ppc64le/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243/pull_request_test/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/projects/atdm_devops/vortex/ninja-fortran-1.8.2/ninja cmTC_934d0 && [1/2] Building CXX object CMakeFiles/cmTC_934d0.dir/testCXXCompiler.cxx.o
    nvcc_wrapper has been given GNU extension standard flag -std=gnu++14 - reverting flag to -std=c++14
    [2/2] Linking CXX executable cmTC_934d0
    FAILED: cmTC_934d0 
    : && /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx   @CMakeFiles/cmTC_934d0.rsp -o cmTC_934d0  && :
    nvcc fatal   : No input files specified; use option --help for more information
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1687 (enable_language)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:182 (tribits_setup_env)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (tribits_project_impl)
  CMakeLists.txt:109 (TRIBITS_PROJECT)
```

Well, that does not seem to have anything to do with the PR :-(

Looking at the rest of those builds at:

* https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-03-01&end=2022-03-07&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=test-ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables

this configure error is not seen in any other run of this build for this PR.

Setting `AT: RETEST` to give this another try.  (It would be great to rerun just this one build but that is not a supported feature of the autotester but is supported by GitLab CI and GitHub Actions, for example.)

**Comment by bartlettroscoe** [comment]
Wow, we are getting random failures in different builds the last 2 PR testing iterations.  In the last iteration the build [`PR-9978-test-Trilinos_pullrequest_intel_17.0.1-11992`](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=10698989&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and) failed with random compile errors that state:

```
icpc: error #10106: Fatal error in /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/base/compilers_and_libraries_2017.1.132/linux/bin/intel64/mcpcom, terminated by kill signal
```

This build was fine the previous iteration [`PR-9978-test-Trilinos_pullrequest_intel_17.0.1-11988`](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=10697663&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and).

But this last iteration, the build [`PR-9978-test-ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables-507`](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=54044&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and) 100% passed, proving that was a random error.

This is such a fragile system and we are seeing the cumulative probability of errors bringing down the PR testing process and wasting computing resources.

Putting `AT: RETEST` again.

**Comment by bartlettroscoe** [comment]
It does not look like this will be merged soon and the PR testing passing result as gone stale (and we are not getting daily reminders of this fact).  Therefore, I am putting the label `AT: WIP` back on to stop these daily reminders.

Once we get the green-light to merge this (i.e. after the Trilinos 13.4 release branch is created), then I will remove `AT: WIP`, add `AT: RETEST` and get this tested, approved, and merged .

**Comment by keitat** [comment]
FYI: I am trying this at:
(1) kahuna (Cluster system at CA V100 GPUs, CUDA 11.0.1 CMake 3.19.1)
(2) crusher (ORNL, Exascale TestBed, AMD CPU and GPUs,  CMake 3.21.1)

**Comment by bartlettroscoe** [comment]
> FYI: I am trying this at:

@keitat, if you could try this with Spack with the xSDK, that would be good.

**Comment by bartlettroscoe** [comment]
CC: @keitat 

@jwillenbring and @ccober6,

Does the below announcement mean that I can merge this Trilinos PR and other backward incompatible TriBITS changes to Trilinos 'develop' starting Thursday, May 19?

----

From: Willenbring, James M <jmwille@sandia.gov> 
Sent: Monday, May 16, 2022 9:03 AM
To: trilinos-announce@trilinos.org; trilinos-developers@trilinos.org
Cc: Ober, Curtis C <ccober@sandia.gov>
Subject: Deprecated code will soon be dropped from Trilinos develop branch

All,

The Trilinos 13.4 release branch was created last week. The Trilinos 13.4 release is anticipated to be finalized in the next couple of weeks. Beginning on May 19th, Trilinos developers will be removing deprecated code from the develop branch in preparation for the Trilinos 14 release, which we currently anticipate will be completed in about 3 months.

If you have questions or concerns, please contact Curt Ober or Jim Willenbring.

Thanks

Jim

**Comment by bartlettroscoe** [comment]
FYI: I think it is pretty clear that given the PRs #10504 and #10533 and all of the changes to TriBITS 'master' that have been made since this PR was last changed or updated that I am going to need to create a new PR with an updated snapshot of TriBITS and cherry-picking the revert revert commit and the release notes changes from this PR.  I will do some more Trilinos testing including against some application codes as mentioned [above](https://github.com/trilinos/Trilinos/pull/9978#issue-1066483507) and then do this all over again.

**Comment by bartlettroscoe** [comment]
Closing this PR for the new PR #10614.

**Pull request closed without merging**
