### PR TITLE
Teko: Add sub-solve capability in hierarchical Block Gauss-Seidel

### PR DESCRIPTION
**Pull request by MalachiTimothyPhillips**
@trilinos/teko
@cgcgcg

### CODE REVIEW

**Comment by MalachiTimothyPhillips** [comment]
@cgcgcg 

At the moment, there's something we are missing in the Belos Stratimikos adapter layer that's causing a segfault (see stack trace below).

Before I dig into this, do you have any immediate ideas?

```
SIERRA execution failed during execute with the following exception:
Segmentation violation error
occurred at:
 0# stk::output_stacktrace(std::ostream&) in aria
 1# 0x0000000014E381CF in aria
 2# sierra::SignalHandler::handle_signal(int) in aria
 3# 0x00007F1F0D994CF0 in /lib64/libpthread.so.0
 4# __dynamic_cast in /projects/cde/v2.1/spack/opt/spack/linux-rhel7-x86_64/gcc-8.4.0/gcc-10.2.0-fwnsolryzhrsu4k2f3gdwsr73rmap7qc/lib64/libstdc++.so.6
 5# Thyra::DefaultProductVectorSpace<double>::isCompatible(Thyra::VectorSpaceBase<double> const&) const in aria
 6# Teko::datacopy(Teuchos::RCP<Thyra::ProductMultiVectorBase<double> > const&, Teuchos::RCP<Thyra::ProductMultiVectorBase<double> >&) in aria
 7# Teko::BlockLowerTriInverseOp::implicitApply(Teuchos::RCP<Thyra::ProductMultiVectorBase<double> > const&, Teuchos::RCP<Thyra::ProductMultiVectorBase<double> >&, double, double) const in aria
 8# Teko::BlockImplicitLinearOp::applyImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, double, double) const in aria
 9# Thyra::DefaultMultipliedLinearOp<double>::applyImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, double, double) const in aria
10# Teko::PreconditionerLinearOp<double>::applyImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, double, double) const in aria
11# Belos::LinearProblem<double, Thyra::MultiVectorBase<double>, Thyra::LinearOpBase<double> >::applyRightPrec(Thyra::MultiVectorBase<double> const&, Thyra::MultiVectorBase<double>&) const in aria
12# Belos::LinearProblem<double, Thyra::MultiVectorBase<double>, Thyra::LinearOpBase<double> >::apply(Thyra::MultiVectorBase<double> const&, Thyra::MultiVectorBase<double>&) const in aria
13# Belos::PseudoBlockGmresIter<double, Thyra::MultiVectorBase<double>, Thyra::LinearOpBase<double> >::iterate() in aria
14# Belos::PseudoBlockGmresSolMgr<double, Thyra::MultiVectorBase<double>, Thyra::LinearOpBase<double> >::solve() in aria
15# Thyra::BelosLinearOpWithSolve<double>::solveImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, Teuchos::Ptr<Thyra::SolveCriteria<double> const>) const in aria
16# Thyra::DefaultInverseLinearOp<double>::applyImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, double, double) const in aria
17# Teko::applyOp(Teuchos::RCP<Thyra::LinearOpBase<double> const> const&, Teuchos::RCP<Thyra::MultiVectorBase<double> > const&, Teuchos::RCP<Thyra::MultiVectorBase<double> >&, double, double) in aria
18# Teko::applyOp(Teuchos::RCP<Thyra::LinearOpBase<double> const> const&, Teuchos::RCP<Thyra::ProductMultiVectorBase<double> > const&, Teuchos::RCP<Thyra::ProductMultiVectorBase<double> >&, double, double) in aria
19# Teko::NestedBlockGS::upperTriangularImplicitApply(std::vector<Teuchos::RCP<Thyra::ProductMultiVectorBase<double> >, std::allocator<Teuchos::RCP<Thyra::ProductMultiVectorBase<double> > > >&, std::vector<Teuchos::RCP<Thyra::ProductMultiVectorBase<double> >, std::allocator<Teuchos::RCP<Thyra::ProductMultiVectorBase<double> > > >&, double, double) const in aria
20# Teko::NestedBlockGS::implicitApply(Teuchos::RCP<Thyra::ProductMultiVectorBase<double> > const&, Teuchos::RCP<Thyra::ProductMultiVectorBase<double> >&, double, double) const in aria
21# Teko::BlockImplicitLinearOp::applyImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, double, double) const in aria
22# Teko::PreconditionerLinearOp<double>::applyImpl(Thyra::EOpTransp, Thyra::MultiVectorBase<double> const&, Teuchos::Ptr<Thyra::MultiVectorBase<double> > const&, double, double) const in aria
23# Teko::TpetraHelpers::TpetraOperatorWrapper::apply(Tpetra::MultiVector<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::MultiVector<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Teuchos::ETransp, double, double) const in aria
24# Belos::LinearProblem<double, Tpetra::MultiVector<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, Tpetra::Operator<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::applyRightPrec(Tpetra::MultiVector<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::MultiVector<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&) const in aria
25# Belos::BlockFGmresIter<double, Tpetra::MultiVector<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, Tpetra::Operator<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::iterate() in aria
```

**Comment by MalachiTimothyPhillips** [comment]
@cgcgcg As per our discussion, pre-allocating the scratch vectors in the ctor of the upper/lower tri solvers, as in https://github.com/trilinos/Trilinos/pull/13053/commits/e54630dee163be6caa189e40e62b39ffbc6e58cb, is sufficient to side-step the issues I was observing.

I'm happy with the changes on my side.

**Comment by MalachiTimothyPhillips** [comment]
@cgcgcg

Do you mind looking through some of the test failures?

They look to me like an unrelated, upstream error in Amesos2, e.g.:

```
[ascic142:30706] *** Process received signal ***
[ascic142:30706] Signal: Segmentation fault (11)
[ascic142:30706] Signal code: Address not mapped (1)
[ascic142:30706] Failing at address: (nil)
[ascic142:30706] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7f1c8c007630]
[ascic142:30706] [ 1] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/amesos2/src/libamesos2.so.15(dgstrf+0x11e)[0x7f1c9bfb9a7e]
[ascic142:30706] [ 2] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/amesos2/src/libamesos2.so.15(_ZN7Amesos211FunctionMapINS_7SuperluEdE5gstrfEPN3SLU17superlu_options_tEPNS3_11SuperMatrixEiiPiPviS8_S8_S7_S7_PNS3_13SuperLUStat_tES8_+0x56)[0x7f1c9beaa18d]
[ascic142:30706] [ 3] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/amesos2/src/libamesos2.so.15(_ZN7Amesos27SuperluIN6Tpetra9CrsMatrixIdixNS1_12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS5_9HostSpaceEEEEENS1_11MultiVectorIdixS8_EEE25numericFactorization_implEv+0xd02)[0x7f1c9beacca4]
[ascic142:30706] [ 4] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/amesos2/src/libamesos2.so.15(_ZN7Amesos210SolverCoreINS_7SuperluEN6Tpetra9CrsMatrixIdixNS2_12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS6_9HostSpaceEEEEENS2_11MultiVectorIdixS9_EEE20numericFactorizationEv+0x79)[0x7f1c9bfa78b5]
[ascic142:30706] [ 5] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZN5MueLu15Amesos2SmootherIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE5SetupERNS_5LevelE+0x1d9c)[0x7f1ca2f1a6b2]
[ascic142:30706] [ 6] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZN5MueLu12DirectSolverIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE5SetupERNS_5LevelE+0xe6)[0x7f1ca322ae4e]
[ascic142:30706] [ 7] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZNK5MueLu15SmootherFactoryIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE13BuildSmootherERNS_5LevelENS_9PreOrPostE+0x2f9)[0x7f1ca3a80107]
[ascic142:30706] [ 8] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZNK5MueLu15SmootherFactoryIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE5BuildERNS_5LevelE+0x30)[0x7f1ca3a7fe0c]
[ascic142:30706] [ 9] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZNK5MueLu22SingleLevelFactoryBase9CallBuildERNS_5LevelE+0x56e)[0x7f1ca2e16b4c]
[ascic142:30706] [10] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZN5MueLu5Level3GetIN7Teuchos3RCPINS_12SmootherBaseIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS8_9HostSpaceEEEEEEEEERT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_11FactoryBaseE+0x65e)[0x7f1ca2fd8c92]
[ascic142:30706] [11] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZNK5MueLu18TopSmootherFactoryIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE5BuildERNS_5LevelE+0x1b5)[0x7f1ca3b217a9]
[ascic142:30706] [12] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZN5MueLu9HierarchyIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE5SetupEiN7Teuchos3RCPIKNS_18FactoryManagerBaseEEESD_SD_+0x18c4)[0x7f1ca33dee14]
[ascic142:30706] [13] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZNK5MueLu16HierarchyManagerIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE14SetupHierarchyERNS_9HierarchyIdixS7_EE+0x13a0)[0x7f1ca2e2e258]
[ascic142:30706] [14] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/src/libmuelu.so.15(_ZNK5MueLu24ParameterListInterpreterIdixN6Tpetra12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS4_9HostSpaceEEEE14SetupHierarchyERNS_9HierarchyIdixS7_EE+0x6b)[0x7f1ca388edd9]
[ascic142:30706] [15] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/test/viz/MueLu_AggExport.exe[0x515a25]
[ascic142:30706] [16] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/test/viz/MueLu_AggExport.exe[0x505140]
[ascic142:30706] [17] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/test/viz/MueLu_AggExport.exe[0x505ef1]
[ascic142:30706] [18] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f1c8bc4c555]
[ascic142:30706] [19] /scratch/trilinos/jenkins/ascic142/workspace/Trilinos_PR_non_blocking_gcc-8.5.0/pull_request_test/packages/muelu/test/viz/MueLu_AggExport.exe[0x504279]
```

**Comment by MalachiTimothyPhillips** [comment]
Hit one GPU segfault with:

```
Iter  7, [ 1] :    1.544599e-03
[ascicgpu051:3217175] *** Process received signal ***
[ascicgpu051:3217175] Signal: Segmentation fault (11)
[ascicgpu051:3217175] Signal code: Address not mapped (1)
[ascicgpu051:3217175] Failing at address: (nil)
[ascicgpu051:3217175] [ 0] /lib64/libpthread.so.0(+0x12cf0)[0x7f8c17943cf0]
[ascicgpu051:3217175] [ 1] /lib64/libc.so.6(+0xc7322)[0x7f8c17633322]
[ascicgpu051:3217175] [ 2] /projects/sems/install/rhel7-x86_64/sems/tpl/openmpi/4.0.5/gcc/10.1.0/base/bxejupk/lib/libopen-rte.so.40(+0x37ea1)[0x7f8c1922bea1]
[ascicgpu051:3217175] [ 3] /projects/sems/install/rhel7-x86_64/sems/tpl/openmpi/4.0.5/gcc/10.1.0/base/bxejupk/lib/libopen-rte.so.40(orte_show_help_recv+0x147)[0x7f8c1922c307]
[ascicgpu051:3217175] [ 4] /projects/sems/install/rhel7-x86_64/sems/tpl/openmpi/4.0.5/gcc/10.1.0/base/bxejupk/lib/libopen-rte.so.40(orte_rml_base_process_msg+0x3a1)[0x7f8c192b62d1]
[ascicgpu051:3217175] [ 5] /projects/sems/install/rhel7-x86_64/sems/tpl/libevent/2.1.12/gcc/10.1.0/base/66qou5q/lib/libevent_core-2.1.so.7(+0x1b928)[0x7f8c17d6f928]
[ascicgpu051:3217175] [ 6] /projects/sems/install/rhel7-x86_64/sems/tpl/libevent/2.1.12/gcc/10.1.0/base/66qou5q/lib/libevent_core-2.1.so.7(event_base_loop+0x4b7)[0x7f8c17d70097]
[ascicgpu051:3217175] [ 7] /projects/sems/install/rhel7-x86_64/sems/tpl/openmpi/4.0.5/gcc/10.1.0/base/bxejupk/bin/mpiexec[0x4014ba]
[ascicgpu051:3217175] [ 8] /lib64/libc.so.6(__libc_start_main+0xe5)[0x7f8c175a6d85]
[ascicgpu051:3217175] [ 9] /projects/sems/install/rhel7-x86_64/sems/tpl/openmpi/4.0.5/gcc/10.1.0/base/bxejupk/bin/mpiexec[0x4012ae]
[ascicgpu051:3217175] *** End of error message ***
```

Other test failures are in the "non-blocking" section. Re-testing now.

**Comment by MalachiTimothyPhillips** [comment]
Marking as draft, as I seem to be hitting some throw when using this capability with MueLu:

```
  /scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel8-x86_64/clang-14.0.6/trilinos-2024.05.12-wi7x6dakpphfskldr2mjoo4mnhgjf2hn/include/Xpetra_ThyraUtils.hpp:250:
  Throw number = 15
  Throw test that evaluated to true: thyraTpetraMultiVector == Teuchos::null
  toXpetra failed to convert provided multi vector to Thyra::TpetraMultiVector. This is the general implementation for Tpetra only.
```

**Comment by MalachiTimothyPhillips** [comment]
@cgcgcg Okay, resolved the issue now by moving the scratch allocation into the first BGS preconditioner evaluation. I tested this works in conjunction with MueLu for the sub-block solves (both inside and outside the hierarchical Gauss-Seidel context).

**Comment by MalachiTimothyPhillips** [comment]
@cgcgcg Are we able to merge this? All of the test failures are in the "Non-blocking" section:

image

**Comment by cgcgcg** [comment]
@MalachiTimothyPhillips I think that "Trilinos_PR_cuda-11.4.20-uvm" needs to pass.

**Comment by MalachiTimothyPhillips** [comment]
> @MalachiTimothyPhillips I think that "Trilinos_PR_cuda-11.4.20-uvm" needs to pass.

image

Looks like it didn't run for whatever reason. I'll go ahead and mark this as "re-test".

**Review by cgcgcg — APPROVED** [review]

**Pull request merged**
