### PR TITLE
Tpetra: Moving selected deep_copy calls back to 2-arg for Panzer

### PR DESCRIPTION
**Pull request by csiefer2**
Issue: #10433
Tests: CUDA
Stakeholder Feedback: Via email

### CODE REVIEW

**Review by rppawlo — APPROVED** [review]
Thanks @csiefer2 !

**Comment by brian-kelley** [comment]
@csiefer2 What actually went wrong with these 3-arg deep copies? The only ways I can think of for a 3-arg and 2-arg to be different behavior is if multiple streams are in use, or if ``execution_space`` was the wrong type (like maybe it was fencing ``Kokkos::Serial()``, when it instead needed to fence ``Kokkos::Cuda()``). But looking at this code and grepping for stream usage, neither seems to be the case here.

**Comment by brian-kelley** [comment]
Maybe downstream is using ``MultiVector<SC, LO, GO, KokkosSerialWrappeNode>``, but the default Kokkos execution space is still being used in its doImport somewhere?

**Comment by csiefer2** [comment]
Panzer tests failed and when Roger and I started reverting to the 2-arg deep_copy those ones are the ones that had to switch back to make the test pass.

**Pull request merged**
