### PR TITLE
Sacado: fix cuda+rdc link issue #1943

### PR DESCRIPTION
**Pull request by rppawlo**
This fixes link issue with rdc enabled. Have not tested changes for non-rdc cuda build or any other node type yet.

assigning to @etphipp to review

### CODE REVIEW

**Comment by etphipp** [comment]
Unfortunately the changes don't work with RDC disabled:

```
/home/etphipp/Trilinos/Trilinos/packages/sacado/src/Sacado_DynamicArrayTraits.cpp:45:49: error: redefinition of âconst Kokkos::MemoryPool<Kokkos::Cuda>* Sacado::Impl::global_sacado_cuda_memory_pool_on_deviceâ
     __device__ const Kokkos::MemoryPool<Kokkos::Cuda>* global_sacado_cuda_memory_pool_on_device = 0;
                                                 ^
/home/etphipp/Trilinos/Trilinos/packages/sacado/src/Sacado_DynamicArrayTraits.hpp:92:49: note: âconst Kokkos::MemoryPool<Kokkos::Cuda>* Sacado::Impl::global_sacado_cuda_memory_pool_on_deviceâ previously declared here
     extern __device__ const Kokkos::MemoryPool<Kokkos::Cuda>* global_sacado_cuda_memory_pool_on_device;
```

So we probably have to ifdef this stuff for when it is enabled.  How do you enable RDC?

**Comment by rppawlo** [comment]
@etphipp - sorry for delay - just realized I am no longer getting emails from github again. You need to enable the kokkos flag and also set an option in the CXXFLAGS:

```
-D Kokkos_ENABLE_Cuda_RDC:BOOL=ON \
-D CMAKE_CXX_FLAGS:STRING="${EXTRA_CXX_FLAGS} --expt-extended-lambda --relocatable-device-code=true -std=c++11" \
```

**Comment by etphipp** [comment]
I tried pushing some changes to your PR that gets it to work when RDC is not enabled, but I got an error:
```
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/rppawlo/Trilinos.git/info/refs
```
I guess I can't push to your fork.

**Comment by rppawlo** [comment]
Sorry. I just added you to the repo access list. I can’t find a way to allow anyone with Trilinos push access to get the same access to my fork. It looks like I have to manually add developers. I am going to be out of the office most of the day with family in town visiting. I will test later tonight or first thing tomorrow morning. Thanks for taking care of this!

Roger

**Comment by etphipp** [comment]
I just pushed a change that gets it to work when RDC is not enabled.  Can you test it with RDC enabled to make sure it still resolves the issue?  If so we can merge it.

**Comment by rppawlo** [comment]
@etphipp - that does fix it for RDC. Thanks! Will you perform the merge or should I?

**Comment by etphipp** [comment]
OK.  I'll merge it.  I tested it with a non-RDC enabled CUDA build, and it is all protected by ifdefs for Cuda, so testing for non-GPU builds isn't necessary.

**Pull request merged**
