### PR TITLE
amesos2: solve style and performance warnings

### PR DESCRIPTION
**Pull request by romintomasetti**
@trilinos/amesos2

## Motivation

We're currently working on a bug of `KLU2`. I made these changes while working on it. Here they are, for free :smile:

It is basically some missing `override` and some `const std::string&`.

### CODE REVIEW

**Comment by maartenarnst** [comment]
Hi @iyamazaki, would you have a moment to take a look at this PR?  Thanks in advance!

**Comment by sebrowne** [comment]
This branch MUST be rebased prior to merge given the 'develop' change (re-adds forbidden files).

**Review by sebrowne — CHANGES_REQUESTED** [review]
Please rebase to eliminate extraneous commits.

**Review by srajama1 — APPROVED** [review]
Thanks @romintomasetti !

**Comment by maartenarnst** [comment]
Hi @sebrowne! Thanks for letting us know about the history change. We did the rebase. However, it seems GitHub is considering your suggestion to rebase as a request for changes. I don't know if that will block a merge. If it is blocking, would you have a moment to approve?

**Comment by maartenarnst** [comment]
Hi @sebrowne! Would you have a moment to approve to confirm that we did the rebase? Also, @sebrowne or @srajama1, would you have a moment to add the `AT: AUTOMERGE` label or do the merge? Thanks in advance!

**Review by sebrowne — APPROVED** [review]
Rebase looks good

**Comment by sebrowne** [comment]
Will defer to @srajama1 for the merge itself.

**Comment by maartenarnst** [comment]
Hi @srajama1. It seems the tests passed for this PR. Would it be OK for you to merge? It seems the PR would just require the `AT:AUTOMERGE` label or a manual merge. Thanks in advance :)

**Pull request merged**
