### PR TITLE
Panzer: Add edge block/field capability to STK_Interface

### LINKED ISSUE #7963: Panzer:  Add edge block/field capability to STK_Interface
## Enhancement
@trilinos/panzer

STK-IO has recently added the ability to write edge blocks and edge fields to Exodus files.  That capability needs to be added to the Panzer's STK_Interface.

### PR DESCRIPTION
**Pull request by tkordenbrock**
@trilinos/panzer

## Motivation

This PR adds edge block and edge field features of STK-IO to Panzer::STK_Interface.  Features include a method to create a new edge block, a method to add fields to an edge block and get methods to retrieve edges from an edge block.  The 3D mesh factories have been updated to create an edge block named "edge_block" that is populated with all edges in the new mesh.

Closes #7963 

## Testing

These changes are generally covered by the PanzerAdaptersSTK test set.  The new features are tested by PanzerAdaptersSTK _tExodusEdgeBlock.exe.

### CODE REVIEW

**Comment by tkordenbrock** [comment]
@rppawlo @eric-c-cyr I marked this WIP, because there is an inbound STK snapshot that has some updates related to edge blocks.  Before this gets merged, I want to make sure this still works with those updates.

**Comment by tkordenbrock** [comment]
@rppawlo @eric-c-cyr I have tested with the latest STK-IO snapshot and it looks good.  It's ready for review.

**Comment by rppawlo** [comment]
@tkordenbrock - Code looks good! Thanks for adding this. Any chance that the test can be converted to parallel? We could force it to always be a 2 mpi process test. This will allow for testing getMyEdges which looks to currently be uncovered. Also - not needed for this PR - at some point, we should add edge fields to the Append/Restart unit test in the same directory to make sure that restarts are working with edge fields.

**Comment by tkordenbrock** [comment]
> 
> 
> @tkordenbrock - Any chance that the test can be converted to parallel? We could force it to always be a 2 mpi process test. This will allow for testing getMyEdges which looks to currently be uncovered.

Will do.

Another potential change before merging is an option to disable this default edge block in the mesh factories.  Right now, all meshes created by the factories will have the edge block.  It shouldn't break any exodiff testing because exodiff doesn't compare edge blocks/fields at the moment.

**Comment by tkordenbrock** [comment]
@rppawlo I have updated the test to run in parallel with 2 ranks.  I also added a new test for the setEdgeFieldData()  method which required fixing setEdgeFieldData().  There is the potential to refactor a lot of the element vs edge code to create some common methods with front ends for each type, but I'd like to save that for a separate PR.

**Comment by tkordenbrock** [comment]
testme

**Comment by jmgate** [comment]
@tkordenbrock, the "testme" comment is how EMPIRE triggers its merge request testing.  Trilinos' autotester will automatically retest this PR when you add a new commit.

**Comment by tkordenbrock** [comment]
@jmgate OK.  I pushed a couple of fixes a while ago and the autotester didn't run.  I guess I just have to wait until there are Jenkins resources available?

**Comment by jmgate** [comment]
This may be more information than you want, but there are four instances of the autotester that kick off scattered throughout every every half hour.  PRs are assigned to an instance with PR # mod 4 = instance #.  You could just be waiting for your autotester instance to fire off again, or it could be busy testing another PR at the moment.

**Comment by tkordenbrock** [comment]
Thanks for the info.  I can never have too much.

**Review by rppawlo — APPROVED** [review]

**Pull request merged**
