### PR TITLE
Zoltan2 tpetra dep

### LINKED ISSUE #9235: zoltan2:  Cannot compile with deprecated interface
## Bug Report
@trilinos/zoltan2 

### Description
IF you disable the deprecated interface in tpetra and try to compile you get a lot of errors, this is expected but not correct.  I will work through the issues on this to resolve the problems but 

@ppebay
@kddevin

### PR DESCRIPTION
**Pull request by bathmatt**
@trilinos/zoltan2 
I modified zoltan2 to use the new interface in tpetra, this branch is based off the xpetra2 branch which has it's own PR @jhux2 is looking at.  Once that is ready to merge I will rebase this but if you want to take a look and even review the xpetra changes in it's own PR that would be great.

I've not tested this on cuda yet, waiting for my crypto in the mail

## Related Issues

* Closes #9235
* Is blocked by #9230

### CODE REVIEW

**Comment by bathmatt** [comment]
I just realized I don't have all the options on for zoltan2, can someoen get me a configure that does everything needed for zoltan2?  Thinking parmetis and stuff like that.

**Review by kddevin — APPROVED** [review]
Zoltan2 changes look OK to me.  Thanks, @bathmatt

**Comment by bathmatt** [comment]
Crap, found a bug in this with @kddevin build script, still seeing failing tests but waiting until I get access to a sems machine to really test.  Will push a fix later today

**Comment by bathmatt** [comment]
I squashed all the commits in this, we have a single commit off the xpetra work

**Comment by jhux2** [comment]
@bathmatt Does this need upstream changes in Xpetra before it can be tested?  If it's independent, I will approve so the AT can check it.

**Comment by bathmatt** [comment]
@kddevin closing this in favor of the MR based off a trilinos branch for simpler testing

**Pull request closed without merging**
