### PR TITLE
fix Zoltan CMake config

### PR DESCRIPTION
**Pull request by jmlapre**
Zoltan did not follow the proper guidance from the [TriBITS users guide](https://tribitspub.github.io/TriBITS/users_guide/index.html#setting-additional-test-properties-tribits-add-advanced-test) which resulted in strange CMake behaviors.

@trilinos/zoltan 

## Motivation
By not adhering to the guidance linked above, attempting to disable tests e.g., setting `Zoltan_ch_simple_parmetis_parallel_DISABLE:BOOL=ON` fails to actually disable the specified test and causes CMake to get confused.

### CODE REVIEW

**Review by bartlettroscoe — DISMISSED** [review]

**Comment by bartlettroscoe** [comment]
@jmlapre, it is a bit late now that testing has started, but you might consider merging this branch into your branch for #11212 and merge them both together in that PR.  That reduces the load in the PR testing infrastructure.  But if the PR builds pass for this PR, then merging this is fine (and then you can rebase your branch for #11212 on top of 'develop').

**Comment by jmlapre** [comment]
@bartlettroscoe I forgot that ch_7944 was failing as well.  I made a similar change to that CMakeLists.txt file.

**Comment by jmlapre** [comment]
Closes #11212

**Review by bartlettroscoe — APPROVED** [review]
Sorry, did not realize my review was holding this up.

**Comment by bartlettroscoe** [comment]
FYI: [Above](https://github.com/trilinos/Trilinos/pull/11226#issuecomment-1320811533) PR iteration failed due to one randomly timing-out test.

**Pull request merged**
