### PR TITLE
Teuchos: fixes to YAML grammar

### PR DESCRIPTION
**Pull request by ibaned**
The merge of #1779 has identified a couple of issues, namely:
 - #1794
 - gahansen/Albany#185

This PR should address both of those by adding the proper extensions to the YAML grammar.

@trilinos/teuchos

### CODE REVIEW

**Comment by bathmatt** [comment]
I'm testing for EMPIRE now.  Will push when tests pass.
Thanks!

**Comment by bathmatt** [comment]
Also, why is Parser optional when it is require by a required thing like parameter list??  Shouldn't the dependencies.cmake have it as required?

-- Setting Trilinos_ENABLE_TeuchosParameterList=OFF because TeuchosParameterList has a required library dependence on disabled package TeuchosParser

**Comment by ibaned** [comment]
@bathmatt I think you're right about that too...

**Comment by bathmatt** [comment]
Making progress.  I'll pull this one but there is a new bug report coming soon, sorry :)

**Comment by ibaned** [comment]
@bathmatt thanks for your help and patience

**Comment by lxmota** [comment]
I'll ask this here, not sure if there is a more appropriate thread. Thanks for fixing https://github.com/gahansen/Albany/issues/186, it works now.

I have a feature request/bug fix: If there are empty lines at the end of a YAML input file, I get the following error:

```
Initializing material database from materials_01.yaml

p=0: *** Caught standard std::exception of type 'Teuchos::ParserFail' :

 error: Parser failure at line 18 column 1 of materials_01.yaml
 Expected one of {", #, ', -, ., DEDENT, OTHERCHAR}
 Got: NEWLINE
 Parser was in state 160

```
The error goes away by removing empty lines at the end of the file.

I'm sure that users will have input files with empty lines at the end, so it seems to me that it would be prudent to handle this case by just ignoring them.

**Pull request merged**
