### PR TITLE
fix several hundred (thousand?)  spelling errors

### PR DESCRIPTION
**Pull request by nschloe**
Many of them are in the public documentation or command-line output.

Caught with lintian.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@nschloe It would be nice if you could break these commits up by package, though I appreciate the effort regardless.  Thanks!

**Comment by aprokop** [comment]
@nschloe Can you please also post the lintian command you used to do the check and correction? I think it may benefit to put it in git hooks, for instance.

**Comment by mhoemmen** [comment]
Also, not that Nico would do anything naughty, but in general, pull requests that touch many files, especially in inactive packages, are vulnerable to introduction of deliberate security bugs.  See e.g., the "Underhanded C Contest."

**Comment by aprokop** [comment]
I think in this particular case, it would be nice if github provided a quick way to do `git diff --word-diff`, or even `git diff --color-words=.`. This would make reviewing this PR trivial.

**Comment by nschloe** [comment]
> Can you please also post the lintian command you used to do the check and correction? I think it may benefit to put it in git hooks, for instance.

This is a simple
```
lintian *.deb
```
on the Trilinos deb packages. It's probably not feasible to do that as a git hook since the binaries need to be built first. The exact error is described here https://lintian.debian.org/tags/spelling-error-in-binary.html.

Since Trilinos is one of a handful of "monster" packages in Debian, lintian hygiene is taken rather seriously. Whenever easy-to-fix bugs like these here come up, I'll create a PR (or 50).

**Comment by nschloe** [comment]
> It would be nice if you could break these commits up by package

That'll be a significant amount of work, given the large number of packages affected. If there's no other way, I'll start breaking it up though.

**Comment by mhoemmen** [comment]
@nschloe wrote:
> That'll be a significant amount of work, given the large number of packages affected. If there's no other way, I'll start breaking it up though.

Does this tool work on plain old object files or libraries?  If so, maybe we can run it ourselves per package, and not trouble you.  It's not that we don't appreciate your work, just that it's a big commit and we're not familiar with this tool, so we don't know if it will mess something up.

**Comment by nschloe** [comment]
I've documented all spelling errors in #1949. `grep`, `sed`, and `vim` will be helpful in fixing them semi-automatically (which is exactly what I did, too). I'm not sure if a similar tool can be run on the object files themselves, but given the fact that 20 years of Trilinos development have produced only around 60 errors in the binaries, it should be enough if I run lintian once a year or so and notify you. (Most of the errors are in the source code comments.)

Feel free to close this PR unmerged, I'll see about splitting the PRs by package.

**Comment by mhoemmen** [comment]
Thanks @nschloe !  I'll close this PR in deference to the per-package PRs.

**Pull request closed without merging**
