### PR TITLE
Issue 8429

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework 
@bartlettroscoe 

## Motivation
With the updates to the PR drivers, the scripts to [reproduce PR errors][1] have become outdated. Especially where Python has been concerned. The main problem it appears from #8429 is that these scripts encounter a problem trying to load the right version of Python which conflicts with the work we put in to remove the use of Python 2.x from our PR scripts.

One problem is that loading the SEMS boost module also loads the `sems-python/2.7.x` module as a side-effect, so when we tried to load a Python 3.x module we got conflicts. 

I went in and modified the non CUDA scripts to perform a `module purge` in the beginning as well as a `module unload sems-python` before we load`sems-python/3.5.2`.  

## Related Issues
* Related to #8429 

## Testing
Ran tests on a RHEL COE system using a simple script:
```bash
#!/usr/bin/env bash

TRILINOS_DIR=${HOME:?}/dev/trilinos-dev/source/Trilinos

build_name="Trilinos_pullrequest_gcc_8.3.0"
env_file="PullRequestGCC8.3.0TestingEnv.sh"
cmake_file="PullRequestLinuxGCC8.3.0TestingSettings.cmake"

echo ""
echo "$ source ${TRILINOS_DIR}/cmake/std/sems/${env_file}"
echo ""
source ${TRILINOS_DIR}/cmake/std/sems/${env_file}

module list

rm -rf build-${build_name}
mkdir build-${build_name}
cd build-${build_name}

cmake_opts=(
    -C ${TRILINOS_DIR}/cmake/std/${cmake_file}
    -DTrilinos_ENABLE_Teuchos=ON
    ${TRILINOS_DIR}/.
    )

cmake ${cmake_opts[@]}

make -j 20
```
for these builds:
- [x] `Trilinos_pullrequest_gcc_8.3.0`
- [x] `Trilinos_pullrequest_clang_10.0.0`

They are still running but I'll go ahead and get this PR in so we can get a review from @bartlettroscoe and iterate over the fix.

[1]: https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

### CODE REVIEW

**Review by prwolfe — APPROVED** [review]

**Review by bartlettroscoe — COMMENTED** [review]
@william76, this looks okay but does this now mean that Trilinos is no longer supporting Python 2.7? It looks like all of the PR builds are now using Python 3.5?  If that is a requirement for Trilinos to use Python 3.5+, then that should be codified as described in:

* https://tribits.org/doc/TribitsDevelopersGuide.html#python-support

So Trilinos should set `PythonInterp_FIND_VERSION=3.5` if that is indeed the minimum supported version of Python.

If not, at least one PR build needs to run the inner Trilinos CMake configure, build, and test with Python 2.7.

**Comment by bartlettroscoe** [comment]
@william76, for the purposes of reporting and browsing, it is good to give a PR a better name name than "Issue 8429".  When you look at an issue/pr query, that name is meaningless.

Instead, how about a name like:

* "Change PR builds to use sems-python/3.5.2 (#8429)"

?

**Comment by william76** [comment]
> @william76, this looks okay but does this now mean that Trilinos is no longer supporting Python 2.7? It looks like all of the PR builds are now using Python 3.5? If that is a requirement for Trilinos to use Python 3.5+, then that should be codified as described in:
> 
>     * https://tribits.org/doc/TribitsDevelopersGuide.html#python-support
> 
> 
> So Trilinos should set `PythonInterp_FIND_VERSION=3.5` if that is indeed the minimum supported version of Python.
> 
> If not, at least one PR build needs to run the inner Trilinos CMake configure, build, and test with Python 2.7.

There is a bit of a nuance with the Python requirement -- we're primarily just addressing the python requirements of the PR driver infrastructure itself w/rt to the 3.x requiremet, not so much the Trilinos project as a whole (we _should_ move everything up to a Python 3 requirement but that's probably a conversation we should have with @jwillenbring and @prwolfe to look into what would be necessary for enforcing a Trilinos-wide requirement on Python 3.

I had hoped we wouldn't need to mess with the Python requirements for the replication scripts since we don't generally run the PR driver itself when replicating builds. TBH, the whole replication process needs to be revamped -- possibly part of the ATDM migration work? 

Python hit end of life on Jan 1, 2020 so it's time to move away from Python 2.x. (https://www.python.org/doc/sunset-python-2/) 

@bartlettroscoe I do not have the ability to edit the TribitsDevelopersGuide...

**Comment by bartlettroscoe** [comment]
> I do not have the ability to edit the TribitsDevelopersGuide...

@william76, the link I gave at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#python-support

just describes how TriBITS projects can specify their dependence on Python.  If you see typos, then you can post a PR to the TriBITS repo.  The source is at:

* https://github.com/TriBITSPub/TriBITS/tree/master/tribits/doc/developers_guide

Instructions on how to build are at:

* https://github.com/TriBITSPub/TriBITS/blob/master/tribits/doc/developers_guide/README

**Comment by bartlettroscoe** [comment]
CC: @rppawlo, @william76, @trilinos/framework 

Looking at the configure output for the last passing PR iteration shown [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-8442-test&field2=buildstarttime&compare2=84&value2=NOW) shows the Python versions:

* clang_10.0.0: /projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/bin/python
* cuda_9.2: /home/projects/ppc64le/python/3.7.3/bin/python
* gcc_7.2.0_debug: /projects/sierra/linux_rh7/install/Python/3.6.10/bin/python
* gcc_7.2.0_serial: /projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/bin/python
* gcc_8.3.0: /projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/bin/python
* intel_17.0.1: /projects/sierra/linux_rh7/install/Python/3.6.10/bin/python
* python_3: /projects/sierra/linux_rh7/install/Python/3.6.10/bin/python3

So Trilinos is getting tested with Python 2.7l.9 and various Python 2 and 3.x.

However, it looks like non-SEMS modules are getting used with several builds:

*  /projects/sierra/linux_rh7/install/Python/3.6.10/bin/python

So can we fix that as well?

**Pull request merged**
