### PR TITLE
Tpetra: Adding tests to resolve #1408

### LINKED ISSUE #1408: Tpetra: Add additional tests for matrix pack/unpack
Tests should exercise the case where the number of rows to pack is not the same as number of rows in matrix.

See #1374 for motivation and details.  Specifically, this [comment](https://github.com/trilinos/Trilinos/issues/1374#issuecomment-307107437) by @maherou  

@trilinos/tpetra

### PR DESCRIPTION
**Pull request by tjfulle**
Build/Test Cases Summary
Enabled Packages: TpetraCore
Disabled Packages: PyTrilinos,Claps,TriKota
0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=130,notpassed=0 (0.60 min)

### CODE REVIEW

**Comment by tjfulle** [comment]
Sorry @mhoemmen I rebased on top of the current develop branch and the old PR was lost.  I cleaned up `CMakeList.txt` to only run the tests once.  Because the three pack/unpack tests share common code, I left them in a single file for now.  If you would like them split in to three separate files, I can do that.

**Comment by tjfulle** [comment]
@trilinos/tpetra

**Comment by mhoemmen** [comment]
@tjfulle The new `CMakeLists.txt` changes lack a `NUM_MPI_PROCS` specification.  How many MPI processes do each of the three tests need in order to have meaningful test results?

**Comment by tjfulle** [comment]
The test is meant to test the pack/unpack serialization so can be run with/without MPI.

**Comment by tjfulle** [comment]
The previous version of `CMakeLists.txt` listed each test in `CrsMatrix_PackUnpack.cpp` individually and specified that each run with `NUM_MPI_PROCS=4`.  The updated version removes the mpi requirement.

**Comment by tjfulle** [comment]
@mhoemmen, I just re-read your last comment.  Just pushed an update to `CMakeLists.txt` to require 2 mpi processes (though any number would work).

**Comment by mhoemmen** [comment]
@tjfulle Thanks!  btw if you need 2 MPI processes, then you would want to say `COMM mpi`, not `COMM serial mpi`.  It's probably OK though (the test may build but not run).

**Comment by mhoemmen** [comment]
@tjfulle Would you like to squash the commits for me to merge in, or do you plan to run the check-in test script and push?

**Comment by tjfulle** [comment]
@mhoemmen, I guess I misunderstood the CMake command.  I understood it to mean "register the test and run it in serial or MPI, use 2 MPI processes if MPI is enabled".  That was my intent at least :)  The tests build and run using 2 MPI processes according to the log file.  If my interpretation of the test registration is incorrect, I would like to fix it to do what I thought it did first.

Wouldn't it be easier to just use the "Squash and Merge" option of "Merge pull request"

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> I understood it to mean "register the test and run it in serial or MPI, use 2 MPI processes if MPI is enabled".

`NUM_MPI_PROCS` imposes a requirement on the number of MPI processes to use.  You may specify a single number (2, in this case), or a contiguous range (e.g., `1-10`, `3-5`).  If you specify `NUM_MPI_PROCS 2` and MPI only gives you 1 MPI process, the test will not run at all.  This is what you want.  Furthermore, the test itself should fail if it was run with less than the required number of MPI processes.  That way, no one will get false positives.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> Wouldn't it be easier to just use the "Squash and Merge" option of "Merge pull request"

Probably, yes :-)

**Comment by tjfulle** [comment]
@mhoemmen, the `NUM_MPI_PROCESS` make sense, but what does having `COMM serial mpi` mean?  I just want this test to run with serial or mpi, and use 2 mpi processes if mpi is enabled.  I'm neck deep in TriBITs CMake files as we speak trying to figure it out :)

**Comment by tjfulle** [comment]
I just read `TribitsAddTest.cmake`, it appears my interpretation of the `COMM` and `NUM_MPI_PROCS` was correct.  So, I believe this can be squashed and merged (each intermediate commit was pushed with the checkin test script)

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> I just want this test to run with serial or mpi, and use 2 mpi processes if mpi is enabled.

If the test needs 2 MPI processes to run, then you don't want "serial" in your COMM specification.

**Comment by mhoemmen** [comment]
Thanks for the offline discussion!  Just for future reference, here is an example of how to build a test regardless of whether MPI is enabled, but ensure that it runs only if 2 MPI processes are available:
```
# I want this test to _build_ in either MPI or non-MPI ("serial"),
# but I only want it to _run_ in an MPI build with exactly 2 MPI
# processes.
TRIBITS_ADD_EXECUTABLE(
  ReadTriples
  SOURCES
    ReadTriples.cpp
    ${TEUCHOS_STD_UNIT_TEST_MAIN}
  COMM serial mpi
  )

TRIBITS_ADD_TEST(
  ReadTriples
  NAME ReadTriples_MPI_2
  ARGS ""
  COMM mpi
  NUM_MPI_PROCS 2
  STANDARD_PASS_OUTPUT
  )
```

**Comment by tjfulle** [comment]
@mhoemmen , `CMakeLists.txt` now builds the PackUnpack test unconditionally, but only runs it on MPI builds with `NUM_MPI_PROCS=1`.

**Comment by tjfulle** [comment]
@mhoemmen: bump 😀

**Comment by mhoemmen** [comment]
@tjfulle sorry, got sucked into Albany#182 and other issues....

**Comment by tjfulle** [comment]
@mhoemmen , no worries!  The code isn't going to wander off anytime soon...

**Comment by mhoemmen** [comment]
Hi @tjfulle !  I tested these with Clang 3.9 (debug and release), and CUDA 8.0 (debug and release).  It builds clean and passes.  I squashed the four commits into one commit, and pushed them.  Thanks for working on this!

**Pull request closed without merging**
