### PR TITLE
Intel ICE workaround removal

### PR DESCRIPTION
**Pull request by PhilMiller**
@trilinos/intrepid2

## Motivation

Remove detritus from working around bugs in old versions of the Intel Classic compiler that are no longer supported in Trilinos.

Spurred by inspection I was doing as part of reviewing kokkos/kokkos#5906

### CODE REVIEW

**Comment by PhilMiller** [comment]
@ndellingwood @rppawlo Could one of you please tag this for PR testing?

**Comment by PhilMiller** [comment]
I'm hopeful that current versions no longer require this particular workaround.

**Comment by PhilMiller** [comment]
Trilinos PR testing covers Intel 2021.3.0, while Kokkos still supports back to Intel 19. Does Trilinos also extend support that far back, without coverage, or is 2021.3 the accepted minimum requirement?

**Comment by PhilMiller** [comment]
I'd definitely agree that this should not be merged before Kokkos 4.0. I'll let you drive the process - I was just proposing the possibility, since this was an old workaround that may no longer be applicable.

**Comment by PhilMiller** [comment]
Gah, I wanted to mark this as a draft since it needs to wait before integration. But, that disables auto-testing too.

In https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface I realize that I hadn't read carefully enough to notice that Intel is not currently part of PR testing. That's unfortunate.

**Comment by sebrowne** [comment]
@PhilMiller with any amount of luck, it will be again soon.  I'm working on getting it restored to the PR configuration list.

**Comment by sebrowne** [comment]
@PhilMiller it is now re-enabled in PR testing, if you want to retest with Intel (classic) 2021.3.0

**Comment by PhilMiller** [comment]
@sebrowne Could you please tag it appropriately? I don't have permissions here on Trilinos to do it myself.

**Comment by PhilMiller** [comment]
And an ancillary question to this: Does Trilinos care about supporting any version of the Intel classic compiler older than the 2021.3.0 that's getting tested?

**Comment by sebrowne** [comment]
I'm not 100% sure I can answer that, but since we don't have testing with it, I don't see how we can guarantee quality with anything other than 2021.3.0.  That's not to say we _shouldn't_ have testing for it necessarily.

**Review by ndellingwood — APPROVED** [review]
PR #11600 is merged so this should be ready to merge, thanks for the clean up @PhilMiller 
Adding @mperego and @CamelliaDPG to they can also inspect the changes with this clean up

**Comment by sebrowne** [comment]
Retesting, last failure was due to machine load.  If it happens again I think I'll need to decrease the build parallelism for the Intel builds (sigh, I really hope the OneAPI LLVM-based Intel fixes the resource consumption issue)

**Comment by ndellingwood** [comment]
@mperego @CamelliaDPG this should be safe to merge, removes a previous intel compiler workaround, but I wanted to check in with you before merging

**Pull request merged**
