### PR TITLE
MueLu: Allow developer verbosity options in easy interface, fix RefMaxwell bug

### LINKED ISSUE #2149: MueLu: expose all verbosity options in "easy" interface
The only verbosity levels available through MueLu's "easy" parameter list interpreter, the one used by Nalu, are "none", "low", "medium", "high", "extreme", and "test".

The std::map of verbosity strings and corresponding enumerated types should be defined in one place, then all code can use this map.

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
Refactor handling of 'verbosity' parameter. Allow use of developer options from easy interface. Fix verbosity bug in RefMaxwell.

Closes #2149

@rstumin

### CODE REVIEW

**Comment by jhux2** [comment]
@cgcgcg Thanks for working on this.  What happens if no file name is specified?   Would this also capture output to std::err?

**Comment by cgcgcg** [comment]
When no file name is specified, then everything works as usual. (And that's the default.)
I believe we're not using `std::cerr` in MueLu except for tests.

**Comment by jhux2** [comment]
> When no file name is specified, then everything works as usual. (And that's the default.)
> I believe we're not using `std::cerr` in MueLu except for tests.

I guess what I'm wondering is what Matt is seeing when a test fails.  I'll ask him :).

**Comment by jhux2** [comment]
Ok, Matt confirmed that it's setup that he's seeing.

**Pull request merged**
