### PR TITLE
Don't unconditionally enable STK subpackages (#11205)

### LINKED ISSUE #11205: Framework:  STK subpackages being unconditionally enabled in ats2 PR build
## Bug Report
@trilinos/framework

### Related issues

* #11109

### Description

For some reason, as shown [here](https://trilinos-cdash.sandia.gov/build/560526/configure), the ats2 PR build on 'vortex':

* `ats2_cuda-10.1.243-gnu-8.3.1-spmpi-rolling_release_static_Volta70_Power9_no-asan_no-complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables`

is unconditionally enabling the following STK  subpakages regardless what is changed in the given PR topic-branch:

```
loading initial cache file /vscratch1/trilinos/jaas/workspace/Trilinos_PR_cuda-10.1.243/generatedPRFragment.cmake
loading initial cache file /vscratch1/trilinos/jaas/workspace/Trilinos_PR_cuda-10.1.243/packageEnables.cmake
-- Setting Trilinos_ENABLE_TrilinosFrameworkTests = ON

...

Explicitly enabled packages on input (by user):  TrilinosFrameworkTests STKUtil STKSimd STKTopology STKMesh STKIO STKSearch STKTransfer STKUnit_tests 9
```

For that PR #11200, only the package `TrilinosFrameworkTests` should be enabled.

This causes a PR like #11200 to take upwards of 2 hours to run when it too it should take about 10 seconds.

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Fixes #11205 

The PR testing will show that this is working (after examining the configure output on the 'ats2' build).

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@alanw0 and @rppawlo, can you please approve?

CC: @e10harvey, @trilinos/framework, anyone else,

If someone can make a case for why this PR should **not** be merged, I would love to hear that argument (or how these packages got unconditionally enabled in the first place).

**Review by alanw0 — APPROVED** [review]
Oh, ok, I didn't know this file existed, nor that these things were being forced on.
Looks good to me, to remove these lines. Thanks Ross!

**Comment by bartlettroscoe** [comment]
> Oh, ok, I didn't know this file existed, nor that these things were being forced on.
> Looks good to me, to remove these lines. Thanks Ross!

@alanw0, I promise you that STK will be tested in this PR build if anyone updates even a single fine under the package/stk/ directory in their topic branch.  (But if you are not sure, we can demonstrate this with a follow-one PR just to validate this.)

**Comment by bartlettroscoe** [comment]
FYI, the updated ats2 configuration for this PR shown [here](https://trilinos-cdash.sandia.gov/build/562139/configure) you see:

```
loading initial cache file /vscratch1/trilinos/jaas/workspace/Trilinos_PR_cuda-10.1.243@3/generatedPRFragment.cmake
loading initial cache file /vscratch1/trilinos/jaas/workspace/Trilinos_PR_cuda-10.1.243@3/packageEnables.cmake
-- Setting Trilinos_ENABLE_ALL_PACKAGES = ON
```

and:

* `Final set of enabled top-level packages:  ... STK ... 58`

* `Final set of enabled packages:  ... STKUtil STKEmend STKCoupling STKMath STKSimd STKNGP_TEST STKTopology STKMesh STKIO STKSearch STKTransfer STKTools STKBalance STKUnit_test_utils STKSearchUtil STKUnit_tests STKDoc_tests STKExprEval STK ... 136`

* `Final set of non-enabled top-level packages:  Pliris Komplex TriKota Compadre Moertel ShyLU PyTrilinos NewPackage 8`

* `Final set of non-enabled packages:  ... 26`

So, all of STK is being enabled when being asked to do so!

**Comment by bartlettroscoe** [comment]
FYI: The last PR iteration above failed due to a timing out test `MueLu_UnitTestsTpetra_MPI_4` that appears to be hanging randomly.  I posted:

* #11209

I will put on AT: RETEST.  But someone really needs to address that hanging test.

**Comment by bartlettroscoe** [comment]
Darn, the last PR iteration above failed due to:

* https://github.com/trilinos/Trilinos/issues/6861

Putting on 'AT: RETEST'.

**Comment by bartlettroscoe** [comment]
@jwillenbring and @ccober6,

This is an example a PR that should just be manually merged.  The failures have nothing to do with the changes in this PR.  This is just wasting PR testing resources at this point (and it builds and runs all of the package tests).

**Comment by alanw0** [comment]
> @jwillenbring and @ccober6,
> 
> This is an example a PR that should just be manually merged. The failures have nothing to do with the changes in this PR. This is just wasting PR testing resources at this point (and it builds and runs all of the package tests).

Meanwhile, I have another PR #11202 that won't even launch the testing. Is there something I can do to make the auto-tester start?

**Comment by ccober6** [comment]
> > @jwillenbring and @ccober6,
> > This is an example a PR that should just be manually merged. The failures have nothing to do with the changes in this PR. This is just wasting PR testing resources at this point (and it builds and runs all of the package tests).
> 
> Meanwhile, I have another PR #11202 that won't even launch the testing. Is there something I can do to make the auto-tester start?

@jwillenbring 

Let's give the new policy a test drive (https://sems-atlassian-son.sandia.gov/confluence/display/trilinos/Forced+Merge+Process).   :) 

@e10harvey please coordinate with @bartlettroscoe on getting this manually merged.

**Comment by bartlettroscoe** [comment]
> @e10harvey please coordinate with @bartlettroscoe on getting this manually merged.

@ccober6, well, we got lucky and the that PR testing iteration fired off passed all of the tests (with zero changes in the PR branch from when the PR was first created).  And that last PR testing iteration consumed another 6 or 7 hours of autotester wall-clock time.

**Pull request merged**
