### PR TITLE
Tpetra: Reapplying 2c4f08ff3881b7c5a1ac05fef55f78b480dca2d4

### PR DESCRIPTION
**Pull request by tjfulle**
Some github wizardry and black-magic removed changes committed as part of
2c4f08ff3881b7c5a1ac05fef55f78b480dca2d4.  Probably due to the fact that
@searhein and I were working concurrently on fixes to #1752.  This commit just
reapplies the fix to #1752 in 2c4f08ff3881b7c5a1ac05fef55f78b480dca2d4.

### CODE REVIEW

**Comment by searhein** [comment]
Thank you for fixing #1752 again :)

**Comment by tjfulle** [comment]
@searhein, I still have no idea how this happened.  Doing `git whatever-command sha` on individual commits makes everything seem fine.  But then, poof!  The files were gone.  Wizardry I tell you!

**Comment by searhein** [comment]
Haha :D Maybe we will understand some day.

**Comment by mhoemmen** [comment]
Thanks @tjfulle !

**Pull request merged**
