### PR TITLE
TrilinosCouplings: Extending STK example to work in 2D

### PR DESCRIPTION
**Pull request by csiefer2**
TESTS: RHEL7

### CODE REVIEW

**Comment by csiefer2** [comment]
@trilinos/framework Why is the autotester marking this a failure?  None of the tests are failing.

**Comment by prwolfe** [comment]
> @trilinos/framework Why is the autotester marking this a failure? None of the tests are failing.

The drop-downs show that all but the python tests are failing to build.

> Set CWD = /scratch/trilinos/jenkins/tr-test-9/workspace/trilinos-folder/Trilinos_pullrequest_clang_10.0.0/TFW_testing_single_configure_prototype
> Traceback (most recent call last):
> File "/scratch/trilinos/jenkins/tr-test-9/workspace/trilinos-folder/Trilinos_pullrequest_clang_10.0.0/Trilinos/cmake/std/PullRequestLinuxDriverTest.py", line 724, in 
> returnValue = run()
> File "/scratch/trilinos/jenkins/tr-test-9/workspace/trilinos-folder/Trilinos_pullrequest_clang_10.0.0/Trilinos/cmake/std/PullRequestLinuxDriverTest.py", line 717, in run
> '-Dsubprojects_file=../package_subproject_list.cmake'])
> File "/projects/sems/install/rhel7-x86_64/sems/compiler/python/2.7.9/lib/python2.7/subprocess.py", line 540, in check_call
> raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['ctest', '-S', 'simple_testing.cmake', '-Dbuild_name=PR-7702-test-Trilinos_pullrequest_clang_10.0.0-67', '-Dskip_by_parts_submit=OFF', '-Dskip_update_step=ON', '-Ddashboard_model=Experimental', '-Ddashboard_track=Pull Request', '-DPARALLEL_LEVEL=20', '-DTEST_PARALLEL_LEVEL=20', '-Dbuild_dir=/scratch/trilinos/jenkins/tr-test-9/workspace/trilinos-folder/Trilinos_pullrequest_clang_10.0.0/pull_request_test', '-Dconfigure_script=/scratch/trilinos/jenkins/tr-test-9/workspace/trilinos-folder/Trilinos_pullrequest_clang_10.0.0/Trilinos/cmake/std/PullRequestLinuxClang10.0.0TestingSettings.cmake', '-Dpackage_enables=../packageEnables.cmake', '-Dsubprojects_file=../package_subproject_list.cmake']' returned non-zero exit status 255
> Build step 'Execute shell' marked build as failure
> Archiving artifacts
> Finished: FAILURE

The lack of red on clash tells me it is failing very early (likely before and code is compiled.) The PR testing is working fine on other requests including the master-merge jobs, so you should see this if you re-create this locally using the instructions on the wiki. (https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors)

**Comment by csiefer2** [comment]
@prwolfe But which one should I try to reproduce?

**Comment by prwolfe** [comment]
I would use gcc 7.2 – but it failed on clang 9 and 10 as well, so I think anything you get is ok. I thought after my last comment this might be related to sitelicense being down, but that is the SON only so , probably not.

Paul

**Comment by csiefer2** [comment]
Well, there was a spelling error in a CMakeLists.txt file.  Make fails nice and cleanly with a message telling me that.

Why cdash wasn't that information in cdash?

**Comment by prwolfe** [comment]
> Why wasn't that information in cdash?

I don't know - and it can be hard to get everything without being overwhelming. I will look.

**Comment by prwolfe** [comment]
The code looks for unit_cube_int_tet.exo and the only file you added was unit_cube_int_tri.exo.

Just starting to look at the reporting question, but this should have failed in your shell (did for me at least)

**Comment by prwolfe** [comment]
I think I understand the reporting error at this point. CMake has a bug report for use of launchers (https://gitlab.kitware.com/cmake/cmake/-/issues/19545) and reading the referenced regex (https://gitlab.kitware.com/cmake/cmake/blob/v3.15.1/Source/CTest/cmCTestBuildHandler.cxx#L53) I am unsure if it will catch this form of the error from ninja instead of make. I expect "error:" will get caught, but there is not specific ninja rule for "missing and no rule to make it" where there is an equivalent rule for make..

**Comment by csiefer2** [comment]
@prwolfe Good to see that we figured out what was going wrong with the reporting!  

And thanks for catching the next typo!

**Pull request merged**
