### PR TITLE
Teuchos: use Parser, not yaml-cpp, to read YAML PL

### PR DESCRIPTION
**Pull request by ibaned**
This commit replaces the TPL yaml-cpp with a
built-in parser based on TeuchosParser.
The new parser is more limited in what it can
accept, but there are several reasons why this
change is beneficial:
 1. TPLs must be installed separately, which is
    often delegated to different people and is
    error-prone.
 2. yaml-cpp has yet to make a formal release despite
    numerous important changes, including dropping
    its Boost dependency.
 3. yaml-cpp throws exceptions internally during normal
    operation. this makes debugging a fatal exception
    later on much more difficult.
 4. yaml-cpp causes compiler warnings on compilers which
    Trilinos needs to support, but they refuse to accept
    patches for these warnings.
 5. Early versions of yaml-cpp would reorder items in
    a map, something this implementation doesn't do.
 5. Our own parser gives us full access to the text,
    opening up the possibility of:
     - identifying and preserving comments
     - extending the language

The Teuchos tests and all YAML files in Albany have
been updated and confirmed to work with this parser.

Nevertheless, this PR requires discussion amongst all those who care about YAML ParameterLists.
@trilinos/muelu 
@trilinos/teuchos 
@lxmota @ikalash

### CODE REVIEW

**Comment by ibaned** [comment]
@brian-kelley

**Comment by aprokop** [comment]
@ibaned Are the differences and/or incompatibilites between in-house implementation and upstream yaml-cpp documented anywhere? If not, it has to be done prior to merge.

**Comment by ibaned** [comment]
@aprokop that makes sense. What kind of documentation method do you think is most appropriate?

**Comment by aprokop** [comment]
@ibaned As Trilinos does not use anything like ReadTheDocs, the only remaining choice is Doxygen. Quick lookaround in Teuchos seems to indicate that Yaml by itself does not have documentation, and that the appropriate documentation is in the `ParameterList`. So I would add some comments to `getParametersFromYamlFile` and friends.

**Comment by lxmota** [comment]
@ibaned If this does not introduce disruptive changes to the YAML syntax that we are using now for all our input files in LCM, I'm all for it.

**Comment by ibaned** [comment]
@lxmota I tested this change with LCM, and pushed a commit Albany to fix the 6 or so YAML files that needed changes, so I think disruption is minimal, e.g. if I merge this now LCM will still pass all tests. Once I document the details for @aprokop we can all take a look at that.

**Comment by mhoemmen** [comment]
@ibaned This is amazing!  We need to clone you!!! :-D

**Comment by ibaned** [comment]
@mhoemmen I think you're still ahead of me in line for the cloning machine :)

**Comment by mhoemmen** [comment]
@ibaned awww thanks :D

**Comment by ibaned** [comment]
I've added a block of Doxygen to document the limitations I could think of, and because thats hard to see on GitHub I am attaching a PDF of the compiled page: 
[Teuchos_YAML_hpp.pdf](https://github.com/trilinos/Trilinos/files/1341103/Teuchos_YAML_hpp.pdf)

I chose to put this documentation in the header file for the TeuchosParser YAML Language, because these are fundamentally limitations of the grammar spec and not really anything to do with ParameterList. Also they appear in the file documentation because the Language is scattered across an enum and a function definition, which the file logically encapsulates.

**Comment by bathmatt** [comment]
I really love this feature, look forward to a push...  Any ETA?

**Comment by ibaned** [comment]
So far the only feedback has been @aprokop 's request to document the differences, which I've put up. Judging from his thumbs-up reaction, I assume that request is satisfied.

If there are no further objections, I might start the checkin script this afternoon.

On the other hand, I do hesitate a bit because I'll be traveling the next two weeks, so there is some risk of breaking things and disappearing. Still, I'll leave a merge commit that is easy for other Trilinos developers to revert as needed.

**Comment by bartlettroscoe** [comment]
> On the other hand, I do hesitate a bit because I'll be traveling the next two weeks, so there is some risk of breaking things and disappearing. Still, I'll leave a merge commit that is easy for other Trilinos developers to revert as needed.

Sounds good to me.  I backed out a similar merge commit a few days ago and it went fine.

**Comment by ibaned** [comment]
merged by the checkin script. If needed, the merge commit to revert is 815b282b82d4e93851a7c046e0eff79b595e23ff

**Pull request merged**
