### PR TITLE
Sort input file list

### PR DESCRIPTION
**Pull request by bmwiedemann**
@trilinos/<teamName>

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

Sort input file list 
so that variables_f.js builds in a reproducible way
in spite of indeterministic filesystem readdir order.

See https://reproducible-builds.org/ for why this is good.

This PR was done while working on reproducible builds for openSUSE.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
WIP: I need to run another round of testing on this.

**Comment by mhoemmen** [comment]
@trilinos/framework 

I don't think the pull request tests have a way to test these changes.  They look fine to me, but we would need reproduction instructions in order to evaluate them.

**Comment by bmwiedemann** [comment]
My test looked good.

One way to reproduce the original issue is to build on 2 different ext4 filesystems with dir_index enabled (is default on). This caused variations in search/variables_f.js files.
Another way to trigger it, would be to use the 'disorderfs' FUSE filesystem to randomize readdir order in the build dir.

**Comment by bmwiedemann** [comment]
Here is a snippet from a diff, but due to the random input, you will get different diffs.

```diff
+++ new//usr/share/doc/packages/trilinos-doc/packages/xpetra/doc/html/search/variables_f.js     2019-07-05 12:00:00.000000000 +0000
@@ -1,6 +1,4 @@
 var searchData=
 [
-  ['rangemaps_5f',['rangemaps_',['../classXpetra_1_1BlockedCrsMatrix.html#a20e4a341fac502c3d2c02c7a50d9c66b',1,'Xpetra::BlockedCrsMatrix']]],
-  ['right_5fside',['RIGHT_SIDE',['/home/abuild/rpmbuild/BUILD/Trilinos-trilinos-release-12-10-1/packages/xpetra/doc/../../../packages/teuchos/doc/html/namespaceTeuchos.html#a4d69c405faef2b64ef0583adadcdbf91af01e44b3bfce7cb55b7537f0b1e23bde',1,'Teuchos']]],
-  ['rowmap_5f',['rowMap_',['../classXpetra_1_1MatrixView.html#ab578ce61f1c75bb636b3431fd8390db1',1,'Xpetra::MatrixView']]]
+  ['thyramaps_5f',['thyraMaps_',['../classXpetra_1_1MapExtractor.html#a6c2728225e6db2f419856c5138be7ce7',1,'Xpetra::MapExtractor']]]
```

**Comment by bmwiedemann** [comment]
I would still like to see this merged. Can I help anything more?

**Comment by jmgate** [comment]
@mhoemmen, were you wanting documentation in the diff of this PR, or were @bmwiedemann's comments above sufficient?

**Comment by prwolfe** [comment]
This looks ok, but I have to ask
1) we have perl in out code base?
2) why is there not a test for this file directly as there would be for a python script of this type?

**Comment by jmgate** [comment]
@trilinos/framework, who owns the `doc` directory.  Should we merge this PR?

**Comment by mhoemmen** [comment]
@jmgate It's all good, as long as y'all think this is harmless.  Thanks!

**Pull request merged**
