### PR TITLE
Tpetra: De-CUDA-ification as per @seanofthemillers

### PR DESCRIPTION
**Pull request by csiefer2**
Issue: #11220 
Tests: n/a
Stakeholder feedback: n/a

@seanofthemillers This is the cut-down version of the PR without the fences.

### CODE REVIEW

**Review by cwpearson — APPROVED** [review]
Let's review Sean's suggested fences as a separate matter

**Comment by seanofthemillers** [comment]
I needed the following patch to compile (I don't have permissions to push):

```
diff --git a/packages/tpetra/core/src/Tpetra_Details_allReduceView.hpp b/packages/tpetra/core/src/Tpetra_Details_allReduceView.hpp
index 11020b08f2e..34613297f37 100644
--- a/packages/tpetra/core/src/Tpetra_Details_allReduceView.hpp
+++ b/packages/tpetra/core/src/Tpetra_Details_allReduceView.hpp
@@ -115,7 +115,7 @@ allReduceView (const OutputViewType& output,
   //if one or both is already in the correct layout, toLayout returns the same view
   auto inputContig = TempView::toLayout<InputViewType, Layout>(input);
   auto outputContig = TempView::toLayout<InputViewType, Layout>(output);
-  if(Tpetra::Details::Behavior::assumeMpiIsCudaAware())
+  if(Tpetra::Details::Behavior::assumeMpiIsGPUAware())
   {
     allReduceRawContiguous(outputContig, inputContig, comm);
```

Also, I am able to pass tests with these changes alone (no fences needed). I guess something must have changed since I last looked at this.

**Comment by cwpearson** [comment]
This builds on `rzvernal` at LLNL (AMD + AMD) with the following configuration:

```
module load cmake
module load amd/5.3.0
module load craype-accel-amd-gfx90a
export CRAYPE_LINK_TYPE=dynamic
```

```
$ module list

Currently Loaded Modules:
  1) craype-x86-trento            7) craype/2.7.17
  2) craype-network-ofi           8) cray-mpich/8.1.20
  3) libfabric/1.7.2-llnl         9) cray-libsci/22.10.1.2
  4) perftools-base/22.09.0      10) PrgEnv-amd/8.3.3
  5) StdEnv                 (S)  11) amd/5.3.0
  6) cmake/3.24.2                12) craype-accel-amd-gfx90a
```

```
cmake ../Trilinos \
-DCMAKE_CXX_COMPILER=hipcc \
-DCMAKE_CXX_FLAGS="-I ${CRAY_MPICH_DIR}/include" \
-DCMAKE_EXE_LINKER_FLAGS="-L ${CRAY_MPICH_DIR}/lib -L/opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11" \
-DTrilinos_EXTRA_LINK_FLAGS="-lmpi -lstdc++.so" \
-DTPL_ENABLE_MPI=ON \
-DTrilinos_SOURCE_DIR="$(readlink -f ../Trilinos)" \
-DTrilinos_ENABLE_Tpetra=ON \
-DTpetra_ENABLE_TESTS=ON \
-DTpetra_INST_HIP=ON \
-DKokkos_ENABLE_HIP=ON \
-DKokkos_ARCH_VEGA90A=ON \
-DKokkos_ARCH_ZEN3=ON
```

(discovered the right path to `libstdc++.so` by poking around in `hipcc --print-search-dirs`)

CTest on rzvernal is currently out of commision, so I can't run the unit tests

**Comment by csiefer2** [comment]
@seanofthemillers Nice catch, thanks!

**Review by cwpearson — APPROVED** [review]

**Pull request merged**
