### PR TITLE
Kokkos + KokkosKernels Promotion To 4.5.1

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos @trilinos/kokkos-kernels 

## Motivation

Snapshot Kokkos Ecosystem patch release 4.5.1 to Trilinos

* Closes `put-issue-number-here`

## Testing
Various CI and nightly testing

### CODE REVIEW

**Comment by ndellingwood** [comment]
Cross-reference
* https://github.com/kokkos/kokkos/pull/7620
* https://github.com/kokkos/kokkos-kernels/pull/2468

**Review by lucbv — DISMISSED** [review]

**Review by crtrott — APPROVED** [review]

**Comment by ndellingwood** [comment]
CDash failure summary:

**PR_cuda**

Multiple compilation failures in intrepid2 due to nvcc ice...
```
nvcc error   : 'ptxas' died due to signal 11 (Invalid memory reference)
nvcc error   : 'ptxas' core dumped
```
https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=2038117


All other jobs had lots of intrepid2 unit test failures, possibly related to https://github.com/kokkos/kokkos/pull/7606 ?

**PR_clang**
Test [Intrepid2_unit-test_Cell_test_04_Serial_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/testSummary.php?project=1&name=Intrepid2_unit-test_Cell_test_04_Serial_DOUBLE_MPI_1&date=2024-12-17) output
```
 Mapping a set of 3 points to one cell in a workset of 10 Line_2 cells. 
DynRankView operator() called with invalid number of arguments.
Backtrace:
[0x7f343a110ef2] Kokkos::Impl::save_stacktrace()
[0x7f343a0e7477] Kokkos::Impl::host_abort(char const*)
[0x43ce96] 
[0x6ced8d] 
[0x6ce7aa] 
[0x6a22ca] 
[0x69a50c] 
[0x6954e9] 
[0x425a0a] 
[0x421b9c] 
[0x4204e1] 
[0x7f343781ed85] __libc_start_main
[0x42036e] 
```

**Comment by ndellingwood** [comment]
Retested with changes corresponding to https://github.com/kokkos/kokkos/pull/7625
Only one spurious unit test failure with [TeuchosCore_RCP_PerformanceTests_basic_MPI_1](https://trilinos-cdash.sandia.gov/test/70494319) , unrelated to the PR

**Review by crtrott — DISMISSED** [review]

**Comment by ndellingwood** [comment]
Another spurious failure with [TeuchosCore_RCP_PerformanceTests_basic_MPI_1](https://trilinos-cdash.sandia.gov/test/70574445) in the sems-clang-11.0.1 job

**Review by lucbv — APPROVED** [review]
Looks fine and the previous issues have been resolved!

**Comment by ndellingwood** [comment]
The intel-2021.3 build had test failures in intrepid2 
https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=2043195

https://trilinos-cdash.sandia.gov/viewTest.php?onlypassed&buildid=2041732

**Comment by mperego** [comment]
> Looks like the intel-2021.3 build will have test failures in intrepid2
> 
> Apparently small diffs from the tolerance? Why did they occur with this rerun?
> 
> Sample case and output snip: [Intrepid2_unit-test_Discretization_Basis_HCURL_TET_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/test/70598939)
> 
> ```
> Order: 3: Comparing values and curls on host
>  order: 3, ic: 0, i: 7, j: 2, val A: [-0.438609, 1.48668], val B: [-0.438609, 1.48668], |diff|: 4.44089e-16, tol: 2.22045e-16
>  order: 3, ic: 0, i: 31, j: 2, val A: [-1.89616, 10.5888], val B: [-1.89616, 10.5888], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 0, i: 40, j: 2, val A: [1.50433, -6.50286], val B: [1.50433, -6.50286], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 1, i: 7, j: 2, val A: [-0.438609, 1.48668], val B: [-0.438609, 1.48668], |diff|: 4.44089e-16, tol: 2.22045e-16
>  order: 3, ic: 1, i: 31, j: 2, val A: [-1.89616, 10.5888], val B: [-1.89616, 10.5888], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 1, i: 40, j: 2, val A: [1.50433, -6.50286], val B: [1.50433, -6.50286], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 2, i: 7, j: 2, val A: [-0.438609, 1.48668], val B: [-0.438609, 1.48668], |diff|: 4.44089e-16, tol: 2.22045e-16
>  order: 3, ic: 2, i: 31, j: 2, val A: [-1.89616, 10.5888], val B: [-1.89616, 10.5888], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 2, i: 40, j: 2, val A: [1.50433, -6.50286], val B: [1.50433, -6.50286], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 3, i: 7, j: 2, val A: [-0.438609, 1.48668], val B: [-0.438609, 1.48668], |diff|: 4.44089e-16, tol: 2.22045e-16
>  order: 3, ic: 3, i: 31, j: 2, val A: [-1.89616, 10.5888], val B: [-1.89616, 10.5888], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 3, i: 40, j: 2, val A: [1.50433, -6.50286], val B: [1.50433, -6.50286], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 4, i: 7, j: 2, val A: [-0.438609, 1.48668], val B: [-0.438609, 1.48668], |diff|: 4.44089e-16, tol: 2.22045e-16
>  order: 3, ic: 4, i: 31, j: 2, val A: [-1.89616, 10.5888], val B: [-1.89616, 10.5888], |diff|: 8.88178e-16, tol: 2.22045e-16
>  order: 3, ic: 4, i: 40, j: 2, val A: [1.50433, -6.50286], val B: [1.50433, -6.50286], |diff|: 8.88178e-16, tol: 2.22045e-16
> ...
> ```
> 
> Full list: https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=2043195 @mperego can you take a glance and help advise?
> 
> The failures did not occur in the prior run, with similar set of changes (only difference is an added abort check on rank that is not relevant to the failures - no aborts were triggered):
> 
> Prior intel-2021.3 run: https://trilinos-cdash.sandia.gov/viewTest.php?onlypassed&buildid=2041732

I really don't know. I had the same issues with similar tests on the intel build and I increase the tolerance.  However, it might be better to disable those tests for now. I plan to work on that capability and fix a few issues that Christian identified when he looked at the code.  Sorry for the issues they are causing.

**Comment by ndellingwood** [comment]
Thanks @mperego , I wasn't sure how concerned to be about the diff and tol trigger of the failures. The failures didn't occur with the other host builds (some with Serial backend enabled) and didn't occur in the previous intel-2021.3 run (which had the same low-rank drv operators()).
Since this failed with the Serial backend I would expect the results to be consistent and deterministic...

**Comment by ndellingwood** [comment]
Ah, I glanced at the Intrepid2_unit-test_Discretization_Basis_HCURL_TET_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1 , there is random number generation used to initially fill the `inputPointsViewToUseRandom` , so results may not be consistent from run to run when using Serial backend

**Comment by ndellingwood** [comment]
Retest had the same test failures in the `rhel8_sems-intel-2021.3-sems-openmpi-4.1.6_release-debug_shared_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables` job:

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
</head>
<body>

Package | Test
-- | --
Intrepid2 | Intrepid2_unit-test_Discretization_Basis_HCURL_TET_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1
Intrepid2 | Intrepid2_unit-test_Discretization_Basis_HCURL_TRI_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1
Intrepid2 | Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1
Intrepid2 | Intrepid2_unit-test_Discretization_Basis_HDIV_TRI_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1
Intrepid2 | Intrepid2_unit-test_Discretization_Basis_HGRAD_TET_Cn_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1
Intrepid2 | Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1
Intrepid2 | Intrepid2_unit-test_Discretization_Basis_HVOL_TET_Cn_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1


</body>
</html>

[Intrepid2](https://trilinos-cdash.sandia.gov/viewTest.php?buildid=2043732)	[Intrepid2_unit-test_Discretization_Basis_HCURL_TET_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/test/70614978)
[Intrepid2](https://trilinos-cdash.sandia.gov/viewTest.php?buildid=2043732)	[Intrepid2_unit-test_Discretization_Basis_HCURL_TRI_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/test/70614961)
[Intrepid2](https://trilinos-cdash.sandia.gov/viewTest.php?buildid=2043732)	[Intrepid2_unit-test_Discretization_Basis_HDIV_TET_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/test/70615019)
[Intrepid2](https://trilinos-cdash.sandia.gov/viewTest.php?buildid=2043732)	[Intrepid2_unit-test_Discretization_Basis_HDIV_TRI_In_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/test/70615003)
[Intrepid2](https://trilinos-cdash.sandia.gov/viewTest.php?buildid=2043732)	[Intrepid2_unit-test_Discretization_Basis_HGRAD_TET_Cn_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/test/70615093)
[Intrepid2](https://trilinos-cdash.sandia.gov/viewTest.php?buildid=2043732)	[Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/test/70615084)
[Intrepid2](https://trilinos-cdash.sandia.gov/viewTest.php?buildid=2043732)	[Intrepid2_unit-test_Discretization_Basis_HVOL_TET_Cn_FEM_test_02_Serial_DOUBLE_DOUBLE_MPI_1](https://trilinos-cdash.sandia.gov/test/70615132)

@mperego I will try to disable as you [suggested](https://github.com/trilinos/Trilinos/pull/13679#issuecomment-2555909433) for later reevaluation

**Comment by ndellingwood** [comment]
@mperego I tried to disable those tests in [7f97667](https://github.com/trilinos/Trilinos/pull/13679/commits/7f976674d62c2ba874bc271da5529cfc679286ad)

**Review by sebrowne — APPROVED** [review]
Test disables look fine

**Review by crtrott — APPROVED** [review]

**Pull request merged**
