### PR TITLE
Piro: Fix Piro when Teko and Tpetra are not explicitly enabled.

### PR DESCRIPTION
**Pull request by sebrowne**
## Motivation
Correct build dependencies to avoid build errors.  Specifically was breaking a common configuration in Spack.  However, I will have to replicate this logic in Spack now since dependencies are changing.

## Related Issues
#12799

## Testing
Tested with
```
cmake -G Ninja -DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_ENABLE_Piro=ON -DTrilinos_ENABLE_Tempus=ON -DTrilinos_ENABLE_ROL=ON ..
```

before and after change, this fixes it.

### CODE REVIEW

**Comment by sebrowne** [comment]
@rppawlo is the mini-em UVM failure something I could have done here?  I promise the "all" build passed the last time I ran it (but I do now realize that was 02/27, I forgot to re-check it when I re-enabled the UVM PR build).  If not, is it something that can be fixed ASAP, or should I re-disable the UVM build until it can be fixed?

**Comment by cgcgcg** [comment]
I'm looking into the issue. Most likely caused by #12788.

**Comment by sebrowne** [comment]
@mperego this is the corresponding change to `develop`

**Review by mperego — APPROVED** [review]
Looks good to me.

**Pull request merged**
