### PR TITLE
ShyLU::FastILU promote to primary tested (PT)

### PR DESCRIPTION
**Pull request by jgfouca**
@trilinos/ifpack2 
@trilinos/shylu 

## Motivation

A recent PR to ifpack2 had build errors with complex doubles but passed CI because the relevant ShyLU subpackage was marked as experimental. This build error later impacted a user. We decided that this subpackage should be promoted to "primary tested" (PT) in order to avoid this in the future.

## Testing

I will watch the cdash link for the CI run and confirm that FILU tests are present.

### CODE REVIEW

**Comment by jhux2** [comment]
See discussion in #12335.

**Review by jhux2 — DISMISSED** [review]
lgtm

**Comment by lucbv** [comment]
Sticking auto-merge on this in case we are lucky and it goes through without issues : )

**Comment by jgfouca** [comment]
@lucbv , that may not give me a chance to look at the cdash page to confirm that the FILU tests are running.

**Comment by lucbv** [comment]
Fair enough I can remove it

**Comment by jgfouca** [comment]
Thanks, I will re-add it once I've confirmed the cdash looks good.

**Comment by jgfouca** [comment]
It looks like the cmake change has the desired effect and FILU tests were run. Unfortunately, looks like a ton variable shadowing was going on in shylu. I used an IDE to redo the naming scheme of FastILUPrec, adding `m_` to all member names. This went a long way towards avoiding shadowing with stack vars and function arguments.

**Comment by jgfouca** [comment]
OK, tests are passing and cdash again confirms that FILU tests are being run. I just need final approval from @lucbv  or @srajama1

**Comment by lucbv** [comment]
Okay, looking at it this morning, thanks for all the clean-up done to get it ready to merge : )

**Review by lucbv — APPROVED** [review]
Looks good to me, thanks for cleaning all the unused typedef and shadowed variables!

**Pull request merged**
