### PR TITLE
ROL Trilinos Sync 24-Jan-2020

### PR DESCRIPTION
**Pull request by dridzal**
@trilinos/rol 

## Description
Regular merge between the ROL-Trilinos repo and the main Trilinos repo, via a Trilinos fork.

## Motivation and Context
New examples.  Minor bug fixes.

## How Has This Been Tested?
Trilinos check-in tests, performed in ROL-Trilinos and in the Trilinos fork.

### CODE REVIEW

**Comment by dridzal** [comment]
@trilinos-autotester @trilinos/framework @bartlettroscoe @trilinos/rol 
We haven’t been able to get this PR through.  It contains important updates for Sierra.  Can someone please advise?  The PR test are passing.

**Comment by bartlettroscoe** [comment]
@dridzal, I don't know anything more about the PR tester than a regular Trilinos developer.  I did not write the PR tester system and I don't maintain it.  From looking at [CDash (all green)](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-6650-test&field2=buildstarttime&compare2=84&value2=NOW) and the [above](https://github.com/trilinos/Trilinos/pull/6650#issuecomment-578434617) output, there does not seem to be any indication of what failed that is clear at all.

**Comment by bartlettroscoe** [comment]
My guess is that there is something broken in the PR testing infrastructure that only the @trilinos/framework team can diagnose and fix.

**Comment by prwolfe** [comment]
re-testing due to a full disk

**Pull request merged**
