### PR TITLE
Tpetra: code reduction in MultiVector async group transfer tests

### PR DESCRIPTION
**Pull request by tasmith4**
@trilinos/tpetra 

## Motivation
Test refactoring and consolidation.  Copy of #10851 since odd-numbered PRs are backed up.

## Testing
Test refactoring -- tests should continue to pass

### CODE REVIEW

**Review by csiefer2 — DISMISSED** [review]

**Comment by bartlettroscoe** [comment]
@tasmith4, I think there must be a bug in the autotester because it just ran:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_0/4591/consoleFull'

and it assigned `ST: STALE` to this PR.  Take a look at the output starting at:

```
09:41:36 PROCESSING prnum = 10920
09:41:36    PROCESSING PULL REQ# 10920
09:41:36       - PRINFO - Mergeable: True; State: open; Title: Tpetra: code reduction in MultiVector async group transfer tests; By: tasmith4
09:41:36       - SOURCE - Repo: trilinos/Trilinos; branch: tasmit/multiple-async-transfer-2; sha: bd1f6c54d8f1740234b463b72941edb510f2b653; User: trilinos
09:41:36       - TARGET - Repo: trilinos/Trilinos; branch: develop; sha: 447fa7590863535be761f6e8e11bd7442909a9a0; User: trilinos
09:41:36       - PR From Fork = False
...
```

and see what the autotester is doing.

**Comment by tasmith4** [comment]
@bartlettroscoe I suspect it is searching for status by git SHA, and #10851, which has the same git SHA at the branch tip as the PR, just went stale, so it has tagged this one with "STALE".  Not sure this is a bug, what do you think?

**Comment by bartlettroscoe** [comment]
@tasmith4


**Update:** It seems that  GitHub stores the details of status checks associated with **commits** and it saw:

```
09:41:36    - COMMITS TO PULL REQ#: 10920
09:41:36      * Commit SHA: bd1f6c54d8f1740234b463b72941edb510f2b653
09:41:36      !!! THIS COMMIT (SHA: bd1f6c54d8f1740234b463b72941edb510f2b653) MATCHES THE SHA OF PR, THEREFORE IT IS THE LATEST COMMIT TO THE PR
09:41:36 Checking if PR #10920 is Stale...
09:41:36      * Looking for Data on Status Named 'TEST STATUS'
...
09:41:37        * Found Commit Status: Context = Pre-Test Inspection, Desc = INSPECTED, state = success, update at= 2022-07-08 17:17:56 utc
09:41:37      * ++ USING status 'TEST STATUS' : Context = Pull Request AutoTester, Desc = All Jobs Finished; status = PASSED, state = success, update at= 2022-08-18 00:34:23 utc
09:41:37   - Current Time = 2022-08-24 08:20:06.161580 utc, Last update Time = 2022-08-18 00:34:23 utc; Elapsed Time = 546343.16158
09:41:37   - Elapsed Time since last update = 546343.16158 >= Staleness Time secs = 518400; PR IS STALE
09:41:37   Found Existing Label 'AT: STALE' in Repo Trilinos...
09:41:37   - Adding/Setting Label to this PR = 'AT: STALE'
```

So to trick the autotester into testing this PR, remove the `AT: STALE`  label and try adding a new commit to this PR branch and push.  That should change the top commit the autotester is examining and allow it to be tested.  Then once this PR merged, GitHub will automatically merge the PR #10851 (because all of the commits in that PR would have been merged to 'develop').

NOTE: Don't rebase the existing commit or the original PR #10851 will not be marked as merged by Github!

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I suspect it is searching for status by git SHA, and #10851, which has the same git SHA at the branch tip as the PR, just went stale, so it has tagged this one with "STALE". Not sure this is a bug, what do you think?

@tasmith4, we came to the same conclusion.  See [above](https://github.com/trilinos/Trilinos/pull/10920#issuecomment-1225759439) for how to proceed.

**Comment by bartlettroscoe** [comment]
Okay, looks like this was resolved by just adding `AT: RETEST`.  So I guess the key is to just always set `AT: RETEST` if you want to be able to get the autotester to run a PR build in all states.

**Review by csiefer2 — APPROVED** [review]

**Pull request merged**
