### PR TITLE
Tpetra::CrsMatrix: Reduce build time by hiding local sparse mat-vec

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @sebrowne @micahahoward

## Description

1. Reduce build time of `Tpetra_CrsMatrix_*.cpp` by hiding the implementation of sparse matrix-vector multiply (in this case, `KokkosSparse::spmv`) behind an ETI wall.
2. Make a "local operator" abstract base class available to Ifpack2.  This will be useful for local sparse triangular solve.

## Motivation and Context

@sebrowne reported that SPARC's build of Trilinos for some compilers failed on a `Tpetra_CrsMatrix_*.cpp` file.  Using `-j1` for the build fixed the issue, so it's likely that the compiler was running out of memory.  This commit aims to reduce the memory footprint of compiling `Tpetra_CrsMatrix_*.cpp` files with ETI ON.

### CODE REVIEW

**Comment by mhoemmen** [comment]
Some downstream code was depending on CUDA headers that were included in `KokkosSparse_CrsMatrix.hpp`.  NEVER EXPOSE TPL HEADERS FOR NONTEMPLATED FUNCTIONS AAAAAAAAA

**Comment by mhoemmen** [comment]
I've fixed the MueLu scaling test and `Tpetra_MatrixIO.cpp` errors.  Now I'll need to add ETI for LocalCrsMatrixOperator to Stokhos:
```
ackages/stokhos/src/libstokhos_tpetra_mp_16_serial.a(Tpetra_CrsMatrix_MP_Vector_16_Serial.cpp.o): In function `Tpetra::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMatrix() const':
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:1126: undefined reference to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMatrix() const'
packages/stokhos/src/libstokhos_tpetra_mp_16_serial.a(Tpetra_CrsMatrix_MP_Vector_16_Serial.cpp.o): In function `construct<Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >, std::shared_ptr<KokkosSparse::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, Kokkos::Serial, void, long unsigned int> >&>':
/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.8.4/base/include/c++/4.8.4/ext/new_allocator.h:120: undefined reference to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::LocalCrsMatrixOperator(std::shared_ptr<KokkosSparse::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, Kokkos::Serial, void, unsigned long> > const&)'
packages/stokhos/src/libstokhos_tpetra_mp_16_serial.a(Tpetra_CrsMatrix_MP_Vector_16_Serial.cpp.o): In function `construct<Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >, std::shared_ptr<KokkosSparse::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, Kokkos::Serial, void, long unsigned int> > >':
/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.8.4/base/include/c++/4.8.4/ext/new_allocator.h:120: undefined reference to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::LocalCrsMatrixOperator(std::shared_ptr<KokkosSparse::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, Kokkos::Serial, void, unsigned long> > const&)'
packages/stokhos/src/libstokhos_tpetra_mp_16_serial.a(Tpetra_CrsMatrix_MP_Vector_16_Serial.cpp.o): In function `Tpetra::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalDiagCopy(Tpetra::Vector<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Teuchos::ArrayView<unsigned long const> const&) const':
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:4365: undefined reference to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMatrix() const'
packages/stokhos/src/libstokhos_tpetra_mp_16_serial.a(Tpetra_CrsMatrix_MP_Vector_16_Serial.cpp.o): In function `Tpetra::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalDiagCopy(Tpetra::Vector<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Kokkos::View<unsigned long const*, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> > const&) const':
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:4319: undefined reference to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMatrix() const'
packages/stokhos/src/libstokhos_tpetra_mp_16_serial.a(Tpetra_CrsMatrix_MP_Vector_16_Serial.cpp.o): In function `Tpetra::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::leftScale(Tpetra::Vector<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&)':
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:4429: undefined reference to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMatrix() const'
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:4441: undefined reference to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMatrix() const'
packages/stokhos/src/libstokhos_tpetra_mp_16_serial.a(Tpetra_CrsMatrix_MP_Vector_16_Serial.cpp.o): In function `Tpetra::CrsMatrix<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::rightScale(Tpetra::Vector<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&)':
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:4508: undefined reference to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMatrix() const'
packages/stokhos/src/libstokhos_tpetra_mp_16_serial.a(Tpetra_CrsMatrix_MP_Vector_16_Serial.cpp.o):/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:4520: more undefined references to `Tpetra::LocalCrsMatrixOperator<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMatrix() const' follow
collect2: error: ld returned 1 exit status
```

**Comment by mhoemmen** [comment]
@etphipp and I figured out how to make Stokhos ETI work for LocalCrsMatrixOperator, and we fixed some things in Stokhos' `KokkosSparse::spmv` overloads that were assuming that the input (multi)vector x was a View of nonconst.  I've also fixed some other ETI issues in Stokhos.  Now I'm just testing.

**Comment by mhoemmen** [comment]
Apparently `Kokkos::is_view<std::vector<Kokkos::View<...>>>::value` is true.  Huh.  My last commit works around that.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> Thanks, I can use this! Now only a few dozen more in other packages...

Thanks for the review!  I haven't finished testing the build yet so I might need another one in a bit ;-)

**Comment by mhoemmen** [comment]
Thanks @tjfulle ! :-D  I did manage to get through the Stokhos build with these changes.  Had to write a replacement for `std::void_t` but that's a normal day I suppose ;-P .

**Comment by tjfulle** [comment]
Sweet!  I'm stuck down in panzer, domi, ROL, and others.  The errors mostly come through matrices being instantiated with `GO=int`, but through factory type functions or macros, so finding all occurrences is proving... irritating.

**Comment by mhoemmen** [comment]
> but through factory type functions or macros, so finding all occurrences is proving... irritating.

It took me a few tries in Stokhos, even though most of those were just in macros, so I totally understand ;-) .

**Comment by tjfulle** [comment]
I have far surpassed a "few tries"...

**Comment by mhoemmen** [comment]
Unfortunately the build errors look legit.  I will keep working.

**Comment by mhoemmen** [comment]
Still working; wasn't able to replicate locally.

**Comment by mhoemmen** [comment]
Let's try this again.

**Comment by mhoemmen** [comment]
Argh, I caught a shadowing warning in Tpetra.  Just pushed a fix for that.

**Comment by mhoemmen** [comment]
The one build error is a [`-Werror` issue in kokkos-kernels](https://github.com/kokkos/kokkos-kernels/issues/448#issuecomment-517322131).  I will patch it by adding a commit to this PR.

**Comment by mhoemmen** [comment]
I added a commit that fixes #5624.  Let's try this again.

**Pull request merged**
