### PR TITLE
Added a reset call

### PR DESCRIPTION
**Pull request by bathmatt**
Added a reset call

### CODE REVIEW

**Review by rppawlo — APPROVED** [review]

**Comment by bathmatt** [comment]
Why can't I merge?  ANy ideas?  Roger can you merge @rppawlo

**Comment by bathmatt** [comment]
@jwillenbring do you know why I can't merge??  Roger approved it...  can you use your magic powers and hit button to merge?

**Comment by jwillenbring** [comment]
@bathmatt The autotester has not run again and verified the review from @rppawlo. I don't have the merge button available either. We have a backlog because of network problems and load issues, so it may take a little while for the autotester to verify the review.

**Comment by bathmatt** [comment]
> @bathmatt The autotester has not run again and verified the review from @rppawlo. I don't have the merge button available either. We have a backlog because of network problems and load issues, so it may take a little while for the autotester to verify the review.

OK, i added a retest, not sure why since nothing has changed it needs a retest.  Does @rppawlo need to reapprove since it is the non-check-mark-one

**Comment by jwillenbring** [comment]
@bathmatt I took the retest flag off. It doesn't need to retest, it just needs to see the review on the next run. I left the auto merge flags on however, as after the review is verified, it will auto merge.

**Pull request merged**
