### PR TITLE
Panzer: add scalar multiplier to DOFGradient

### PR DESCRIPTION
**Pull request by sconde**
DO NOT MERGE!!! 

@trilinos/panzer 

## Description

- computes multiplier * grad
- default multiplier = 1.0

## Motivation and Context

help reduce code duplication in Drekar

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

Drekar is testing the non-default case.

### CODE REVIEW

**Comment by rppawlo** [comment]
@sconde - this adds extra flops to every single code using a nodal basis and seems like a specific corner case. I'd like to support this using a separate code path. Let's talk offline later today.

**Comment by jmgate** [comment]
What's the use case here?  Seems like you could accomplish this in other ways given what Panzer already offers.

> help reduce code duplication in Drekar

Example?

**Comment by sconde** [comment]
@rppawlo  I didn't account for the performance hit. I might just do this in Drekar.

**Comment by sconde** [comment]
This is no longer necessary.

**Pull request closed without merging**
