### PR TITLE
tpetra: Remove unused `execSpace` parameter from checkMapInputArray

### PR DESCRIPTION
**Pull request by cwpearson**
Potential fix for https://github.com/trilinos/Trilinos/issues/11316

### CODE REVIEW

**Comment by mhoemmen** [comment]
@cwpearson Hi!  I haven't worked for Sandia or done any Trilinos development for nearly three years.  If I CC people below, it's just because I happen to think that they might know who reviews Tpetra pull requests now, not because I necessarily think that they are responsible for reviews.

@csiefer2 @jhux2 Sorry to call you out -- would you happen to know who should review this?  This PR looks OK.

**Comment by GrahamBenHarper** [comment]
> I haven't worked for Sandia or done any Trilinos development for nearly three years. 

But it doesn't stop @mhoemmen from stomping us at board game nights :)

**Comment by cwpearson** [comment]
@mhoemmen sorry to bother you, I just put you down because you were the last person who touched it :D I won't send any further review requests your way.

**Review by brian-kelley — DISMISSED** [review]
Weird that a function that doesn't do any kokkos would ever take exec_space!

Your changes look good to me.

**Review by jhux2 — APPROVED** [review]
lgtm

**Pull request merged**
