### PR TITLE
SEACAS: Add optional TPLs used by Seacas

### PR DESCRIPTION
**Pull request by gsjaardema**
Added a few optional TPLs that can be used with the SEACAS IOSS library to provide additional capabilities.  These include:

* DataWarp -- Cray's burst buffer library
* Faodel -- a collection of data management tools that Sandia is developing to improve how datasets migrate between memory and storage resources in a distributed system.
* Cereal -- used by Faodel for serialization
* Catalyst2 -- Embedded visualization capability

@trilinos/seacas

## Related Issues

* Related to #11154

### CODE REVIEW

**Review by bartlettroscoe — APPROVED** [review]
This is okay to merge.  See my comment in https://github.com/trilinos/Trilinos/pull/11154/files#r998765365 and https://github.com/sandialabs/seacas/pull/334/files/6bd477fbb5c2e8acaf4bf73776597faf4a29173f#r998302519.

**Comment by bartlettroscoe** [comment]
Also, note that the merging of this PR is related but can be merged independently from the merging of the PR #11154.

**Comment by gsjaardema** [comment]
@bartlettroscoe Thanks.  Any ideas on how to get the autotesting to run?  @trilinos/framework

**Comment by bartlettroscoe** [comment]
> Any ideas on how to get the autotesting to run? @trilinos/framework

@gsjaardema, looking at [this PR query](https://github.com/trilinos/Trilinos/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+-label%3A%22AT%3A+WIP%22+), it looks like there are a few even-numbered PRs ahead of it in the PR testing queue.  Looking at the [even-PR Jenkings job running](https://do.sandia.gov/trilinos-ci/job/Trilinos_autotester_driver_inst_0/5907/console), it looks like it is currently testing PR #11150.  So after it finishes testing that PR and merging the already-passed PR #11154, then it should start testing this PR #11156.

Given that a PR build now takes upwards of 6 hours to run (after rebuilds were turned off), it does not take much for the PR queue to get backed up.

**Comment by gsjaardema** [comment]
@bartlettroscoe Yes, but it looks like it has failed a couple times already with some strange error 
```
Status Flag 'Pull Request AutoTester' - Failure: Job Trilinos_PR_gcc-8.3.0-serial on Jenkins server at https://do.sandia.gov/trilinos-ci Does Not Exist
```

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Yes, but it looks like it has failed a couple times already with some strange error
> 
> ```
> Status Flag 'Pull Request AutoTester' - Failure: Job Trilinos_PR_gcc-8.3.0-serial on Jenkins server at https://do.sandia.gov/trilinos-ci Does Not Exist
> ```

@gsjaardema, I have no idea what that is about.

@trilinos/framework, any idea what this error is about?

**Pull request merged**
