### PR TITLE
Intrepid2: Fix shadowed usings

### LINKED ISSUE #9997: Intrepid2: shadow warnings related to ExecutionSpace typedefs
Several using declarations in function scope shadow base class member using declarations, and need to be made consistent to avoid warnings/errors in GCC 8+ builds.

### PR DESCRIPTION
**Pull request by japlews**
@mperego @trilinos/Intrepid2

## Motivation
Fix shadow warnings to allow clean compilation on GCC 8 and up. Also clean up some usings in template derived classes in Basis. Also add a few includes where classes are used.

## Related Issues
* Closes #9997

### CODE REVIEW

**Comment by mdmosby** [comment]
Please note that this is important for SIERRA in preparation for TOSS4 (RHEL8) which uses GCC 8.4 as the default compiler

**Review by mperego — APPROVED** [review]
Looks good to me. Thanks!

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by jhux2** [comment]
@mperego There was something weird going on with the autotester that @jwillenbring fixed.  I think this PR needed the pre-inspection tag because @japlews isn't part of the Trilinos group.  I hope it was ok that I auto-merged ... the changes seemed reasonable, and Matt M. said it was important.

**Comment by mperego** [comment]
Sure! And thanks for adding the pre-inspection tag, I'm not used to it yet.

**Comment by japlews** [comment]
Thanks, @jhux2!

**Pull request merged**
