### PR TITLE
MueLu LWGraph_kokkos unit test: Fix bug

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
Fix compilation error on HIP #12691

### CODE REVIEW

**Review by jhux2 — DISMISSED** [review]
lgtm

**Comment by jhux2** [comment]
@cgcgcg In "PR-12693-test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on", there's a single MueLu unit test failing for one and four ranks:
```
85. LWGraph_kokkos_double_int_longlong_Tpetra_KokkosCompat_KokkosCudaWrapperNode_LocalGraphData_UnitTest ... Kokkos::View ERROR: attempt to access inaccessible memory space (label="Tpetra::CrsGraph::ptr")
```

**Comment by cgcgcg** [comment]
@jhux2 Thanks!

**Comment by achauphan** [comment]
Looks like `Trilinos_PR_gcc-8.3.0-debug`, or it's full legal name `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables` Jenkins job for this PR failed to run the `clean_workspace.py` leading to there not being enough scratch space for this run. Seems like the issue has resolved itself as subsequent jobs on this same node have been able to run the clean up script and continue with their run.

**Review by jhux2 — APPROVED** [review]
lgtm

**Pull request merged**
