### PR TITLE
Kp precond

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos-kernels 

## Motivation
Patch with improvements to kokkos-kernels' spiluk and sptrsv routines for testing by Sierra

## Stakeholder Feedback
@srajama1 @vqd8a @jhux2 @jennloe 

## Testing
Already tested and merged into kokkos-kernels

### CODE REVIEW

**Comment by ndellingwood** [comment]
@jhux2 Now that #10253 has merged I think we can test + merge this PR unless additional changes are needed, @vqd8a would you be okay with this also?

**Comment by vqd8a** [comment]
@ndellingwood I am okay with it. Thanks.

**Review by vqd8a — APPROVED** [review]
@ndellingwood Thanks for making this PR

**Comment by ndellingwood** [comment]
Thanks @vqd8a ! Just a heads up, if we hit issues with the Cuda build this PR may get stalled until #10469 merges

**Comment by ndellingwood** [comment]
Cuda build failed at configure with error snip:
```
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx
-- Check for working CXX compiler: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx - broken
CMake Error at /projects/sparc/tools/cmake/3.19.4/ppc64le/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243@2/pull_request_test/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/projects/atdm_devops/vortex/ninja-fortran-1.8.2/ninja cmTC_3cc7b && [1/2] Building CXX object CMakeFiles/cmTC_3cc7b.dir/testCXXCompiler.cxx.o
    FAILED: CMakeFiles/cmTC_3cc7b.dir/testCXXCompiler.cxx.o 
    /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx    -o CMakeFiles/cmTC_3cc7b.dir/testCXXCompiler.cxx.o -c testCXXCompiler.cxx
    nvcc fatal   : Could not open output file '/tmp/trilinos/tmpxft_0000092f_00000000'
    ninja: build stopped: subcommand failed.
...
```

This should be resolved now that #10469 is merged, retesting

**Pull request merged**
