### PR TITLE
Update Trilinos to C++14

### PR DESCRIPTION
**Pull request by e10harvey**
Resolves conflicts from #8317.

### CODE REVIEW

**Review by prwolfe — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Comment by e10harvey** [comment]
@jwillenbring: Ready to merge?

**Comment by jwillenbring** [comment]
> @jwillenbring: Ready to merge?

I conferred with @prwolfe and yes, we are ready to merge. We will deal with the ATDM build separately. @prwolfe will work on what we hope are the final steps for that on Wednesday. I added the automerge flag. I will also follow up with a note to the user list.

**Comment by e10harvey** [comment]
CC: @ZUUL42, @crtrott, @jwillenbring, @prwolfe 

@bartlettroscoe, I don't see these changes in atdm-nightly. Was there an issue with the atdm-nightly update last night?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe, I don't see these changes in atdm-nightly. Was there an issue with the atdm-nightly update last night?

@e10harvey, looking at [this CDash query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-01-01&end=2021-02-02&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-cee-rhel7_clang-9.0.1_openmpi-4.0.3_serial_static_opt) it looks like there have been no updates to the 'atdm-nightly' branch since "Jan 22, 2021 - 22:35 MST".  Looking at the merge log (run under my account 'rabartl' on 'ceerws1113') it looks like there are merge conflicts in the file:

```
Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   packages/muelu/src/Misc/MueLu_FilteredAFactory_def.hpp
```

how this is possible defies imagination.  (It would be interesting to study this some).

I am going to resolve the merge conflict given what is on 'develop' and push.

I never imagined that process could fail so the process has not been carefully monitored.  (That was obviously a mistake.)

**Comment by bartlettroscoe** [comment]
@ZUUL42, @crtrott, @jwillenbring, @prwolfe, @e10harvey,

I pushed the updated 'atdm-nightly' branch.  So now the bomb goes off (with 11 days of changes).

We need to get the update of the 'atdm-nightly' branch run by a shared monitored process that sends out emails when it fails. Discussion of this can continue in https://sems-atlassian-srn.sandia.gov/browse/ATDV-374.

**Comment by rppawlo** [comment]
@e10harvey , @jwillenbring , @bartlettroscoe - the default being set in this PR is not actually being used. @glhenni  reported that they are seeing the default get set in tribits (sets it to c++11) and that they have to manually override in their build scripts:

```
This is what’s being used if I don’t set CMAKE_CXX_STANDARD explicitly:
 
TribitsGlobalMacros.cmake:2047
  # Set up C++ language standard selection.
  IF (NOT CMAKE_CXX_STANDARD)
    SET(CMAKE_CXX_STANDARD 11)
  ELSEIF (NOT CMAKE_CXX_STANDARD MATCHES "^(11|14|17|20)$")
    MESSAGE(FATAL_ERROR "CMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD} is not 11, 14, 17, or 20.")
  ENDIF ()
  SET(${PROJECT_NAME}_CXX_STANDARD_FEATURE cxx_std_${CMAKE_CXX_STANDARD})
  IF (NOT DEFINED CMAKE_CXX_STANDARD_REQUIRED)
    SET(CMAKE_CXX_STANDARD_REQUIRED ON)
  ENDIF ()
  IF (NOT DEFINED CMAKE_CXX_EXTENSIONS)
    SET(CMAKE_CXX_EXTENSIONS OFF)
  ENDIF ()
```

**Comment by bartlettroscoe** [comment]
> the default being set in this PR is not actually being used

@rppawlo,  I did pretty careful testing of this in the original PR #8317 where I created these first commits.  All of the code in tribits is overwritten with the Trilinos default set at:

https://github.com/e10harvey/Trilinos/blob/dfe5fb15e49a3466136db98ab358296b20f113c1/CMakeLists.txt#L89

which runs before that TriBITS logic.

Are you deleting the CMakeCache.txt file before reconfiguring?

Otherwise, I can look into what might be happening.

**Comment by bartlettroscoe** [comment]
@rppawlo, there is pretty good evidence that C++14 is getting used if you look at the PR builds on CDash for this PR.  For example, the [cuda build](https://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=8621934) you see the compiler option `-std=c++14`, for the [clang build](https://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=8621810) you see `-std=c++14` as well, and for the [intel build](https://testing.sandia.gov/cdash/viewBuildError.php?type=1&buildid=8621872) again you see the compiler option `-std=c++14`.

@glhenni, what are you seeing?  And what version of Trilinos are you using?

**Comment by rppawlo** [comment]
@glhenni said that he did a clean build and was still seeing this. He updated this morning. It's possible the charon builds scripts are pulling in some cmake fragment file. If no other teams are seeing this, then we will focus on charon before asking you to look at this.

**Comment by bartlettroscoe** [comment]
Related to:
* SEPW-213

**Comment by glhenni** [comment]
My latest builds are working with the c++14 requirement and I no longer need to hard-code any setting for that into our cmake invocation.

**Pull request merged**
