### PR TITLE
MueLu: fixing regionalToComposite() for region vectors

### LINKED ISSUE #6349: MueLu: region MG test fail in debug builds
## Bug Report
@trilinos/muelu @mayrmt 

### Description
When running `ctest -R` from `packages/muelu/research/regionMG/examples/structured` in a debug build, most of the tests fail (especially though with more than 1 MPI rank).
This might reveal a potential bug in the region MG code.

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/muelu 

## Motivation
A debug build of trilinos reveals that a potentially wrong map is used when importing into a composite vector inside function: regionalToComposite(). This is fixed by using the maps stored in the import object instead of input arguments to regionalToComposite(). Further interface simplifications could be done in regionalToComposite() and compositeToRegional().
I am adding the gdb stack trace that I get when running the tests: [debug_build_gdb_trace.txt](https://github.com/trilinos/Trilinos/files/3889006/debug_build_gdb_trace.txt)

## Related Issues

* Closes #6349
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Testing
Performed a local debug build and ran `ctest -R` on it, all tests are now passing.

### CODE REVIEW

**Comment by lucbv** [comment]
@mayrmt would you mind looking at these changes, they do fix the issue I discovered in the debug build but I did not dig too much into it...
Making sure that the maps that we have used until now were indeed the wrong maps to use would be reassuring!
Also I am marking this as `WIP` since I would like to make the following interface changes:
```
void compositeToRegional(RCP<Xpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Node> > compVec, ///< Vector in composite layout [in]
                         Array<RCP<Xpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Node> > >& regVecs, ///< Vector in regional layout [in/out]
                         const std::vector<RCP<Xpetra::Import<LocalOrdinal, GlobalOrdinal, Node> > > rowImportPerGrp ///< row importer in region layout [in]
                         )
```
the goal is to get rid of all input parameters than cannot be recovered from `rowImportPerGrp`

**Comment by mayrmt** [comment]
@mayrmt I'll have a look and then get back to you.

**Comment by mayrmt** [comment]
@lucbv I double checked. It's correct to acces the target map of the `rowImportPerGrp` importer when requiring the map in the quasiRegion layout. :heavy_check_mark:

**Comment by mayrmt** [comment]
@lucbv How are we gonna tackle the refactoring of the `compositeToRegional()` interface as you have proposed above?

**Comment by mayrmt** [comment]
@lucbv I just removed the `maxRegPerProc` parameter from the list of arguments of `compositeToRegional()`. It's a start, but there are still some more to go...

**Comment by mayrmt** [comment]
@lucbv I did some more quick clean-ups and removed unnecessary function arguments. Those were easy to replace. The other ones are not as straightforward. Any suggestions how to proceed?

**Comment by lucbv** [comment]
@mayrmt let us see how the autotester runs, I would be happy to merge this as is for now just to get the changes in RegionVector.cpp in. I have these changes in at least 3 local branches...

**Pull request merged**
