### PR TITLE
Adelus: Set up performance test

### PR DESCRIPTION
**Pull request by vqd8a**
@trilinos/adelus

## Motivation

Addressing Gemma's request: an automatic performance testing for Adelus. The perf test can run nightly to help monitor the performance over time. Teuchos ```StackedTimer``` and ```TimeMonitor``` are used to monitor factor time, backsolve time, permutation time and total time. Call ```stackedTimer->reportWatchrXML()``` at the end of the run to dump all the timing data to XML file.

### CODE REVIEW

**Comment by srajama1** [comment]
@vqd8a Can you take care of the failing tests please ?

**Comment by vqd8a** [comment]
@srajama1  It looks like there have been some Jenkins issues with git in most tests.

**Comment by vqd8a** [comment]
@srajama1 All tests passed. Could you please review this? Thanks.

**Review by srajama1 — APPROVED** [review]
Looks fine to me. Getting the input using cin is unconventional for Trilinos. I recommend getting it just as command line arguments. Thanks @vqd8a !

**Comment by vqd8a** [comment]
@srajama1 Thanks for reviewing and for your recommendation. I am going to address it when I am revising the entire code in the next PR.

**Pull request merged**
