### PR TITLE
found missing deep copy

### PR DESCRIPTION
**Pull request by bathmatt**
Fixed missing deep copy if conditional was not set to true

### CODE REVIEW

**Review by rppawlo — APPROVED** [review]
Thanks @bathmatt ! This one is my fault! Sorry.

**Comment by bathmatt** [comment]
@rppawlo how do we resolve this, assume a merge with develop once it gets the right fix in?

**Comment by rppawlo** [comment]
The intel compiler died with:
```
icpc: error #10106: Fatal error in /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/base/compilers_and_libraries_2017.1.132/linux/bin/intel64/mcpcom, terminated by kill signal
```
Think this is a system hiccup. It failed on a file we did not touch and there were muelu and stokhos failures as well. Hoping a retest will go through...

**Comment by rppawlo** [comment]
Once this goes in, I think we can enable panzer in the no UVM build! Thanks for all your hard work on this!

**Pull request merged**
