### PR TITLE
STK: Snapshot 09-04-24 16:01 from Sierra 5.21.3-843-gf6bffc7c

### PR DESCRIPTION
**Pull request by alanw0**
@trilinos/<teamName>

## Related Issues

* Closes `put-issue-number-here`

### CODE REVIEW

**Review by hpacella — APPROVED** [review]

**Comment by ldh4** [comment]
> `Check packages with clang-format / build (pull_request) Failing after 37s`

Was clang-formatting check always part of trilinos PR check?

**Review by ldh4 — DISMISSED** [review]

**Comment by alanw0** [comment]
> > `Check packages with clang-format / build (pull_request) Failing after 37s`
> 
> Was clang-formatting check always part of trilinos PR check?

It seems to just be checking muelu and a couple of other packages that I didn't touch.
I just ignore it.

**Comment by cgcgcg** [comment]
Please ignore clang-format. It's broken ATM because the workflow itself is broken.

**Comment by sebrowne** [comment]
This got hit with a bug in Framework unit testing, RETEST is an appropriate fix (that testing has been disabled).

**Review by ldh4 — APPROVED** [review]

**Comment by alanw0** [comment]
Should address https://github.com/trilinos/Trilinos/issues/13422

**Pull request merged**
