### PR TITLE
Fix misc. warnings

### PR DESCRIPTION
**Pull request by brian-kelley**
Fix some random warnings I've been seeing:
-using uninitialized var
-misleading indentation
-set-but-unused var
-catch polymorphic object (std::exception) by value

@trilinos/galeri 
@trilinos/tpetra 
@trilinos/isorropia 
@trilinos/epetraext 
## Motivation

No issue for these

### CODE REVIEW

**Comment by kddevin** [comment]
Thanks, @brian-kelley  
Can you add which compiler generated the warnings?

**Comment by brian-kelley** [comment]
@kddevin GCC 9.1.0, which is pretty new and seems to be more strict on warnings than other compilers.

**Comment by brian-kelley** [comment]
@kddevin Thanks!

**Comment by lucbv** [comment]
Does it makes sense to updates the warning as error list if we start doing this type of work?

**Pull request merged**
