### PR TITLE
Framework: Post 14.4 release update

### PR DESCRIPTION
**Pull request by cabejackson**
@trilinos/framework 

## Motivation
Trilinos 14.4 release

### CODE REVIEW

**Review by sebrowne — CHANGES_REQUESTED** [review]
You're going to want to set the new version on develop to 14.5 (and 140500).  Also wait until the release is done to merge this one.

**Comment by ccober6** [comment]
> You're going to want to set the new version on develop to 14.5 (and 140500). Also wait until the release is done to merge this one.

If we do another minor release it would be 14.6.

**Comment by sebrowne** [comment]
> > You're going to want to set the new version on develop to 14.5 (and 140500). Also wait until the release is done to merge this one.
> 
> If we do another minor release it would be 14.6.

Correct, but that variable appears to track the odd version immediately following the current release.  Meaning, if we just released 14.4, 'develop' would version as 14.5, and then update to 14.7 if we release a 14.6.

**Comment by ccober6** [comment]
Gotcha.  Thanks for the clarification!

**Review by sebrowne — APPROVED** [review]
Wait until the release is completed to merge this PR

**Comment by sebrowne** [comment]
This is the same SEACAS test that sporadically failed on some other toolchains for my PR earlier in the week.  There is no way that it is related to this PR.  @cabejackson you can disable it as part of this PR, which is unfortunate but acceptable.

**Comment by cabejackson** [comment]
New PR can be found [here](https://github.com/trilinos/Trilinos/pull/12101)

**Pull request closed without merging**
