### PR TITLE
Ifpack2: add an option to skip the reading of the line file

### PR DESCRIPTION
**Pull request by kliegeois**
Add the option to skip the reading of the line file to use block Jacobi instead of block TD

### CODE REVIEW

**Review by brian-kelley — APPROVED** [review]

**Comment by kliegeois** [comment]
@sebrowne it looks like the auto tester might be broken.

**Comment by jhux2** [comment]
@trilinos/framework I don't see any errors in the latest AT results.

**Comment by achauphan** [comment]
> @trilinos/framework I don't see any errors in the latest AT results.

@jhux2 the intel builds are going through due to some module issues (mentioned here #13125). Sam is planning on demoting the intel build to a non-blocking one if it does not get resolved by the end of today. apologies for the inconvenience!

**Comment by sebrowne** [comment]
Intel builds are now non-blocking, RETESTing

**Comment by kliegeois** [comment]
Thanks @sebrowne !

**Pull request merged**
