### PR TITLE
Set KOKKOS_NUM_DEVICES in ATDM Environment Scripts

### PR DESCRIPTION
**Pull request by jmgate**
## Description
@bathmatt wants `KOKKOS_NUM_DEVICES` to be set when you run `load_matching_env.sh` from a Trilinos install.

## Motivation and Context
Got this email from @bathmatt:

> dir-cuda-emp [CUDA-9.2]$ 14 $ grep KOKKOS_NUM_DEVICES /projects/empire/install-for-panzer/CUDA-9.2-RELEASE-CUDA-STATIC/load_matching_env.sh
>  
> that isn’t set anymore it seems like..

We have always only had `export KOKKOS_NUM_DEVICES=2` in EMPIRE's `build-test-and-install-trilinos.sh` script.  If we need `KOKKOS_NUM_DEVICES` to be set after sourcing `load_matching_env.sh` from a Trilinos install, we'll need the changes in this PR or something similar.

# Interested Parties
@bartlettroscoe, @fryeguy52, this look good to you?

# Notes
I only added this line to `environment.sh` scripts that also had
```bash
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
```

in them.  It's possible this new line also belongs in other `environment.sh` scripts, but I'll leave that up to the experts.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@jmgate, @bathmatt, and @trilinos/kokkos,

What is the impact of setting `NUM_KOKKOS_DEVICES`?  I did a web search on "NUM_KOKKOS_DEVICES" and nothing came up.

I looked for this name with:

```
$ cd Trilinos/
$ find packages/kokkos -type f -exec grep -nH NUM_KOKKOS_DEVICES {} \;
```

and nothing came up.

Has anyone tested this?

**Comment by bartlettroscoe** [comment]
@trilinos/kokkos,

We could use some help with our Kokkos/GPU/CUDA settings.

**Comment by bathmatt** [comment]
@bartlettroscoe 
First the greatest command ever.. git grep, much faster than find..  Works in subdirs as well..

Second, I think I typed it wrong when I sent Jason that email.  See below

Third, what it does.  It sets GPU = MPI_Rank%KOKKOS_NUM_DEVICES.  If you have 4 cards, it will not send all jobs to GPU 0..


s1000670:Trilinos mbetten$ git grep KOKKOS_NUM_DEVICE
packages/kokkos/core/src/impl/Kokkos_Core.cpp:    auto env_ndevices_str = std::getenv("KOKKOS_NUM_DEVICES");
packages/kokkos/core/src/impl/Kokkos_Core.cpp:            Impl::throw_runtime_exception("Error: cannot convert KOKKOS_NUM_DEVICES to an integer. Raised by Kok

**Comment by jmgate** [comment]
Sorry @bartlettroscoe&mdash;just a typo on my part in the PR title and description.  The commit had the right variable name in it.

**Comment by ibaned** [comment]
@bathmatt 's explanation is correct, and it is `KOKKOS_NUM_DEVICES`, but there is one sentence that is misleading:

> If you have 4 cards, it will not send all jobs to GPU 0..

Kokkos' selection of GPU is based on MPI rank, so if you launch 4 jobs, each with only one MPI rank, then all 4 jobs will use GPU 0.

**Comment by bathmatt** [comment]
@ibaned yeah, 
GPU = MPI_Rank%KOKKOS_NUM_DEVICES.
is what the code does..

**Comment by ibaned** [comment]
Yep, until the whole CTest-handles-everything idea gets figured out, this is a step in the right direction.

**Comment by jmgate** [comment]
Sorry folks.  Changed the base branch to `develop`.  Retesting&hellip;

**Pull request merged**
