### PR TITLE
 Kokkos + KokkosKernels Promotion To 3.6.0

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos 
@trilinos/kokkos-kernels 

## Motivation
Release 3.6.0 of Kokkos Ecosystem

## Testing
Autotester plus regular nightly testing

### CODE REVIEW

**Review by crtrott — DISMISSED** [review]

**Comment by ndellingwood** [comment]
```
CMake Error at packages/shylu/shylu_node/tacho/CMakeLists.txt:15 (MESSAGE):
  Tacho can not be build with Pthreads as the Kokkos Host Backend.
```

Not sure why the configure error is showing up in the serial configurations (Tacho was enabled in my Serial testing), looking into it

**Comment by ndellingwood** [comment]
PR https://github.com/kokkos/kokkos/pull/4830 is up with possible resolution to address the configure errors with Pthread.
This did not show up in nightly testing because we do not set `TPL_ENABLE_Pthread` in any builds, differing from the autotester builds which set this to ON

**Comment by ndellingwood** [comment]
Kokkos snapshot updated to include changes from kokkos/kokkos#4830 as well as changes to rename usage in Trilinos of the cache variable `Kokkos_ENABLE_PTHREADS` with SHA [1fff1aa](https://github.com/trilinos/Trilinos/pull/10253/commits/1fff1aac9be204ffff135a1ec8f419087392c58b)

**Comment by ndellingwood** [comment]
@trilinos/framework how to I check the results of the cuda build? I do not see it available with the other test results on the cdash link

**Comment by ndellingwood** [comment]
I saw this message in the cuda test output after the 3 url links:
```
>>> ctest_submit(PARTS        Build
                 RETRY_COUNT  5
                 RETRY_DELAY  3
                 RETURN_VALUE ctest_submit_error)
```
Does this indicate something like a timeout waiting for a node or something else?

**Comment by e10harvey** [comment]
> @trilinos/framework how to I check the results of the cuda build? I do not see it available with the other test results on the cdash link

They post [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=63&value1=Pull%20Request&field2=buildname&compare2=63&value2=PR-10253).

**Comment by e10harvey** [comment]
> Does this indicate something like a timeout waiting for a node or something else?

@ndellingwood It appears that the ctest process was interrupted via `SIGINT`.

**Comment by ndellingwood** [comment]
@trilinos/framework I'm having troubles getting usable info from the cuda failure, e.g. https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=63&value1=Pull%20Request&field2=buildname&compare2=63&value2=PR-10253
The job does not begin the ctest run, but I don't see compilation errors only warnings. Could someone help point me where to scan?

**Comment by jwillenbring** [comment]
What is the relationship of this PR with respect to the 13.4 minor release? Does it need to get into that? Should it for sure not get in before that release, or doesn't it matter either way?

**Comment by ndellingwood** [comment]
@e10harvey I'll message you regarding a reproducer build
@jwillenbring it would be nice to get this in for the Trilinos minor release if possible

**Review by crtrott — DISMISSED** [review]

**Comment by ndellingwood** [comment]
@trilinos/framework @e10harvey I need some help with the results of the most recent run of the PR - it lists all compiler builds as failing, but the most recent March 25 runs of gcc/8.3, gcc/7.2.0 and intel/17.0.1 are listed as passing on the cdash link though there are no clang/10 results for that day; the cuda cdash results show successful configure and compile, but no output regarding tests. Any suggestions?

**Comment by e10harvey** [comment]
> Any suggestions?

@ndellingwood: With respect to [the cuda 10.1.243 results from this iteration of testing](https://github.com/trilinos/Trilinos/pull/10253#issuecomment-1079600385), the tests timed out after running for 8 hours (the whole build, test, and configure ran for ~12 hours). Please see [this console output](https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/_cuda_10.1.243/635/consoleFull).

How long did the configure, build and test take when you reproduced these failures manually?

**Comment by ndellingwood** [comment]
@e10harvey thanks for the responses and suggestions

> How long did the configure, build and test take when you reproduced these failures manually?

I think about 10 hours or so. I built with `make -j16` (more parallelism resulted in some build errors I think due to memory issues) and `ctest` with no parallelism

**Comment by e10harvey** [comment]
> I think about 10 hours or so. I built with `make -j16` (more parallelism resulted in some build errors I think due to memory issues) and `ctest` with no parallelism

I see that we're using ctest -j4 via the pull request driver. Was there a particular reason you did not use any parallelism with `ctest`?

**Comment by e10harvey** [comment]
> > I think about 10 hours or so. I built with `make -j16` (more parallelism resulted in some build errors I think due to memory issues) and `ctest` with no parallelism
> 
> I see that we're using ctest -j4 via the pull request driver. Was there a particular reason you did not use any parallelism with `ctest`?

@ndellingwood: Thinking about this more now, do we need to set `KokkosCore_UnitTest_CudaInterOpStreams_MPI_1_SET_RUN_SERIAL=ON` and `KokkosCore_UnitTest_CudaInterOpInit_MPI_1_SET_RUN_SERIAL=ON` in the cuda 10.1.243 configuration?

**Comment by ndellingwood** [comment]
> @ndellingwood: Thinking about this more now, do we need to set `KokkosCore_UnitTest_CudaInterOpStreams_MPI_1_SET_RUN_SERIAL=ON` and `KokkosCore_UnitTest_CudaInterOpInit_MPI_1_SET_RUN_SERIAL=ON` in the cuda 10.1.243 configuration?

@e10harvey that could be helpful and likely avoid at least spurious failures

**Comment by e10harvey** [comment]
> > @ndellingwood: Thinking about this more now, do we need to set `KokkosCore_UnitTest_CudaInterOpStreams_MPI_1_SET_RUN_SERIAL=ON` and `KokkosCore_UnitTest_CudaInterOpInit_MPI_1_SET_RUN_SERIAL=ON` in the cuda 10.1.243 configuration?
> 
> @e10harvey that could be helpful and likely avoid at least spurious failures

Ok. I will set those options and add `AT: RETEST`.

For what it's worth, we have instances of the current configuration passing with Kokkos tests enabled. See https://trilinos-cdash.sandia.gov/build/75188.

**Comment by ndellingwood** [comment]
> For what it's worth, we have instances of the current configuration passing with Kokkos tests enabled.

@e10harvey yes, it's possible that either the update with the kokkos snapshot added enough new testing or caused enough shuffling of existing tests to disrupt the status quo, or that the use/dis-use of parallelism is a non-factor and there is something else at play with the timeouts

**Comment by e10harvey** [comment]
@ndellingwood
```
KokkosCore_UnitTest_CudaInterOpStreams_MPI_1_SET_RUN_SERIAL=ON and KokkosCore_UnitTest_CudaInterOpInit_MPI_1_SET_RUN_SERIAL=ON
```
have been set in the cuda 10.1.243 config.

CC: @trilinos/framework

**Comment by e10harvey** [comment]
> Based on these numbers, could the following tests get the `RUN_SERIAL` treatment for the Cuda builds?

Done. Please update your master branch of GenConfig and run `rm -rf CMake*` and `source gen-config.sh ...` from your build directory.

Please let me know if you would like the compadre tests disabled as well.

Going forward, would it be feasible for package maintainers to explicitly mark their tests as run serial rather than trying to play whack-a-mole again in the trilinos PR cmake configurations?

CC: @trilinos/framework

**Comment by ndellingwood** [comment]
@e10harvey excellent, thanks! Rerunning the build+tests

> Going forward, would it be feasible for package maintainers to explicitly mark their tests as run serial rather than trying to play whack-a-mole again in the trilinos PR cmake configurations?

The most practical way I can think of for that is as interaction with package maintainer as part of the PR where the test timeout is triggered since the nature of these types of issues is reactive. For example, PR's from the Tpetra team have not resulted in problems with timeouts in `TpetraCore_gemm_m_eq_1_MPI_1` etc. tests that I am seeing here, so I'm assuming this might not be straight forward to handle preemptively.
Something that might be helpful would be a post-processing step after tests are run to report any tests taking over a threshold of 100 sec or 500 sec for example (minus those on an "exemption" list known to take long) which package maintainers could then follow up on to mark as RUN_SERIAL. Is something like this reasonable for a feature request?

**Comment by ndellingwood** [comment]
The added marking of `RUN_SERIAL` didn't help with the Tpetra test timeouts with a clean launch on vortex last night running tests with `ctest -j4`. I looked at the CMakeLists.txt file in Tpetra for those tests and `RUN_SERIAL` is already passed as an option to each `TRIBITS_ADD_TEST`...
I've relaunched a build with `ctest -j1` to reconfirm the timing differences I reported

**Comment by e10harvey** [comment]
> The most practical way I can think of for that is as interaction with package maintainer as part of the PR where the test timeout is triggered since the nature of these types of issues is reactive. For example, PR's from the Tpetra team have not resulted in problems with timeouts in `TpetraCore_gemm_m_eq_1_MPI_1` etc. tests that I am seeing here, so I'm assuming this might not be straight forward to handle preemptively.
> Something that might be helpful would be a post-processing step after tests are run to report any tests taking over a threshold of 100 sec or 500 sec for example (minus those on an "exemption" list known to take long) which package maintainers could then follow up on to mark as RUN_SERIAL. Is something like this reasonable for a feature request?

I think so. I would just submit the partial test results to CDash; would that be a convenient way for you to retrieve this information?

**Comment by ndellingwood** [comment]
I relaunched a clean build with `ctest -j1` to be careful, but if I manually rerun one of the timeout Tpetra tests e.g. `TpetraCore_gemm_m_eq_1_MPI_1` then I don't see the timeout:

```
[ndellin@vortex30 build-kp-dev]$ ctest -R TpetraCore_gemm_m_eq_1_MPI_1
Test project /vscratch1/ndellin/Trilinos-dev/build-kp-dev
    Start 651: TpetraCore_gemm_m_eq_1_MPI_1
1/1 Test #651: TpetraCore_gemm_m_eq_1_MPI_1 .....   Passed   18.41 sec

100% tests passed, 0 tests failed out of 1

Subproject Time Summary:
Tpetra    =  18.41 sec*proc (1 test)

Total Test time (real) =  42.91 sec
```

This is the same ballpark of timing I saw in my previous testing with `ctest -j1`. Apparently the `RUN_SERIAL` may not be respected? @e10harvey any suggestions?

**Comment by e10harvey** [comment]
> I relaunched a clean build with `ctest -j1` to be careful, but if I manually rerun one of the timeout Tpetra tests e.g. `TpetraCore_gemm_m_eq_1_MPI_1` then I don't see the timeout:
> 
> ```
> [ndellin@vortex30 build-kp-dev]$ ctest -R TpetraCore_gemm_m_eq_1_MPI_1
> Test project /vscratch1/ndellin/Trilinos-dev/build-kp-dev
>     Start 651: TpetraCore_gemm_m_eq_1_MPI_1
> 1/1 Test #651: TpetraCore_gemm_m_eq_1_MPI_1 .....   Passed   18.41 sec
> 
> 100% tests passed, 0 tests failed out of 1
> 
> Subproject Time Summary:
> Tpetra    =  18.41 sec*proc (1 test)
> 
> Total Test time (real) =  42.91 sec
> ```
> 
> This is the same ballpark of timing I saw in my previous testing with `ctest -j1`. Apparently the `RUN_SERIAL` may not be respected? @e10harvey any suggestions?

@ndellingwood: Can you reproduce this timeout with ctest -j4 on the develop branch (without the changes from kokkos-promotion)?

**Comment by ndellingwood** [comment]
> Can you reproduce this timeout with ctest -j4 on the develop branch (without the changes from kokkos-promotion)?

I launched the job to check, will update with results when it completes

**Comment by ndellingwood** [comment]
The ctest -j1 build is still running tests, but the problematic timeout tests from Tpetra with -j4 have finished:

```
          Start  651: TpetraCore_gemm_m_eq_1_MPI_1
 651/3450 Test  #651: TpetraCore_gemm_m_eq_1_MPI_1 ............................................................................   Passed   18.25 sec
          Start  652: TpetraCore_gemm_m_eq_2_MPI_1
 652/3450 Test  #652: TpetraCore_gemm_m_eq_2_MPI_1 ............................................................................   Passed   18.66 sec
          Start  653: TpetraCore_gemm_m_eq_5_MPI_1
 653/3450 Test  #653: TpetraCore_gemm_m_eq_5_MPI_1 ............................................................................   Passed   17.85 sec
          Start  654: TpetraCore_gemm_m_eq_13_MPI_1
 654/3450 Test  #654: TpetraCore_gemm_m_eq_13_MPI_1 ...........................................................................   Passed   19.06 sec

```

I'm not sure why the tests are timing out with -j4 since they are marked as RUN_SERIAL...

**Comment by e10harvey** [comment]
> The ctest -j1 build is still running tests, but the problematic timeout tests from Tpetra with -j4 have finished:


Thank you for reproducing this on develop, @ndellingwood. Since this is a bug in develop, would you like me to disable the Tpetra tests and file a bug report with for Tpetra so we can merge this PR?

**Comment by rppawlo** [comment]
Are you sure that you are not overloading a single cuda card on the node? Maybe ctest is not configured correctly to spread jobs out to all the cuda cards? If not, this seems like a regression in kokkos performance from 3.5 to 3.6. Do you have performance comparisons of the test suite with the current 3.5 release?

**Comment by e10harvey** [comment]
I've changed the cuda_10.1.243 cuda settings including setting `KOKKOS_NUM_DEVICES=4`.

**Comment by rppawlo** [comment]
> I've changed the cuda_10.1.243 cuda settings including setting `KOKKOS_NUM_DEVICES=4`.

@e10harvey - can you try the tribits flags described at:

https://tribits.org/doc/TribitsBuildReference.html#spreading-out-and-limiting-tests-running-on-gpus

these make sure the ctest driver controls gpus allocation wrt multiple tests running at the same time.

**Comment by e10harvey** [comment]
> @e10harvey - can you try the tribits flags described at:

Thank you, @rppawlo. I have updated the cmake setting to turn Trilinos_AUTOGENERATE_TEST_RESOURCE_FILE ON.

**Comment by e10harvey** [comment]
Let's see if the current `RETEST` passes. Either way, the next `RETEST` will run with `Trilinos_AUTOGENERATE_TEST_RESOURCE_FILE=ON`.

In both instances, we have the following in `CMakeCache.txt`:
```
<snip>
//from .ini configuration
TPL_ENABLE_CUDA:BOOL=ON

//from .ini configuration
Trilinos_CUDA_NUM_GPUS:STRING=4

//from .ini configuration
Trilinos_CUDA_SLOTS_PER_GPU:STRING=2
<snip>
```

**Comment by rppawlo** [comment]
@e10harvey - with those settings, I think you will need to make sure the ctest command is run with -j8 so that at most 8 mpi processes are launched at any one time.

**Comment by e10harvey** [comment]
> @e10harvey - with those settings, I think you will need to make sure the ctest command is run with -j8 so that at most 8 mpi processes are launched at any one time.

ctest is currently run with -j4.

**Comment by ndellingwood** [comment]
@rppawlo @e10harvey thanks for testing out the new suggestions

Here is a recap of comparison focusing on the timing out Tpetra gemm_m* tests

Trilinos develop branch SHA f1b37fee3ab5d64c3abe623be45b52f1dc14e000 - ctest -j4
```
          Start  643: TpetraCore_gemm_m_eq_1_MPI_1
2321/3442 Test  #643: TpetraCore_gemm_m_eq_1_MPI_1 ............................................................................   Passed   19.55 sec
          Start  644: TpetraCore_gemm_m_eq_2_MPI_1
2322/3442 Test  #644: TpetraCore_gemm_m_eq_2_MPI_1 ............................................................................   Passed   19.45 sec
          Start  645: TpetraCore_gemm_m_eq_5_MPI_1
2323/3442 Test  #645: TpetraCore_gemm_m_eq_5_MPI_1 ............................................................................   Passed   20.48 sec
          Start  646: TpetraCore_gemm_m_eq_13_MPI_1
2324/3442 Test  #646: TpetraCore_gemm_m_eq_13_MPI_1 ...........................................................................   Passed   20.16 sec
```

Trilinos kokkos-promotion branch with merge of develop on Mar 30 SHA 3dee9747b2fa12bbfc47b069c35ed782c83be4c9, comparing ctest -j4 vs -j1 snipped from https://github.com/trilinos/Trilinos/pull/10253#issuecomment-1085034993

Test | j4 (sec) | j1 (sec)
-- | -- | --
PanzerAdaptersSTK_PoissonInterfaceTpetra_2d_diffsideids_MPI_1 | 1500.09 | 35.34
TpetraCore_gemm_m_eq_1_MPI_1 | 1500.16 | 17.92
TpetraCore_gemm_m_eq_2_MPI_1 | 1500.16 | 17.73
TpetraCore_gemm_m_eq_5_MPI_1 | 1500.16 | 18.18
TpetraCore_gemm_m_eq_13_MPI_1 | 1500.16 | 17.74

The gigantic discrepancy between the ctest -j4 vs -j1 times would indicate to me that this is due to running the tests in parallel, but these tests are already marked as `RUN_SERIAL` which should allow them to monopolize the GPU (i.e. no competition with other tests overloading the card)?
I saw no difference in timing of `TpetraCore_gemm_m_eq_*` tests between this PR and Trilinos develop branch when testing with ctest -j1, so I don't think this would indicate a performance regression due to Kokkos, right? Adding @crtrott so he is in the loop and in case he has any additional thoughts

**Comment by e10harvey** [comment]
> Here is a recap of comparison focusing on the timing out Tpetra gemm_m* tests

@ndellingwood Hang on. I thought ctest -j4 on develop was hanging during the Teptra gemm_m* tests; is that correct?

**Comment by ndellingwood** [comment]
> I thought ctest -j4 on develop was hanging during the Teptra gemm_m* tests; is that correct?

@e10harvey no, those tests are not hitting the timeout

**Comment by e10harvey** [comment]
> @e10harvey no, those tests are not hitting the timeout

Ok, is ctest -j4 hanging on develop with the set of package enables being used in this PR?

**Comment by ndellingwood** [comment]
> is ctest -j4 hanging on develop with the set of package enables being used in this PR?

@e10harvey no, I tested develop with the same batch script (same env, config, etc)

**Comment by e10harvey** [comment]
> @e10harvey no, I tested develop with the same batch script (same env, config, etc)

Ok. My mistake. Assuming there are no regressions from the cuda-10.1.243 cmake setting changes I have made today, those changes will not be reverted.

As far as I know, the only other cmake setting that may resolve this hang is `Trilinos_AUTOGENERATE_TEST_RESOURCE_FILE=ON` and that will be tested in the next `RETEST`.

Assuming the hang still persists with `Trilinos_AUTOGENERATE_TEST_RESOURCE_FILE=ON`, I would suggest triaging the culprit within this diff to resolve these `ctest -j4` hangs.

**Comment by ndellingwood** [comment]
@crtrott @e10harvey  Adding more info after some additional testing.

1. Testing this PR with `ctest -j4 -R Tpetra` to only parallelize over any tests with Tpetra in the regex did not reproduce the timeouts (all Tpetra tests passed)
2. Christian and I ran the same type of test above in the background then monitored with nvidia-smi, and it seems that the `.../Tpetra/core/test/Blas/TpetraCore_gemm.exe` executable (which includes the timing out `TpetraCore_gemm_m_eq_*` subtests) was run solo on the GPU, it seemed that the `RUN_SERIAL` marking was respected was output of the tests was generated
3. I reran all tests with `ctest -j4` in the background and with nvidia-smi output piped to file and noticed a couple things so far:

After the `Compadre_GMLS_Staggered_*` tests fail and timeout there is a hang of two runs of the executable on the GPU (this occurs on develop branch as well and is not caused by this PR), i.e. two runs of the executable persist throughout subsequent testing in the nvidia-smi output:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     77658      C   ...re/examples/Compadre_GMLS_Staggered.exe   407MiB |
|    0     77695      C   ...re/examples/Compadre_GMLS_Staggered.exe   383MiB |
```

When the `TpetraCore_gemm.exe` executable launches (and thus the `TpetraCore_gemm_m_eq_*` testing first begins), there is a single instance of the executable running on the GPU (along with the hanging Compadre exes):
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     77658      C   ...re/examples/Compadre_GMLS_Staggered.exe   407MiB |
|    0     77695      C   ...re/examples/Compadre_GMLS_Staggered.exe   383MiB |
|    0    118280      C   ...etra/core/test/Blas/TpetraCore_gemm.exe   427MiB |
+-----------------------------------------------------------------------------+
```

Apparently after one of the `TpetraCore_gemm_m_eq_*` tests completes or hangs, there is another launch of the executable on the same GPU:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     77658      C   ...re/examples/Compadre_GMLS_Staggered.exe   407MiB |
|    0     77695      C   ...re/examples/Compadre_GMLS_Staggered.exe   383MiB |
|    0    118280      C   ...etra/core/test/Blas/TpetraCore_gemm.exe   427MiB |
|    0    120512      C   ...etra/core/test/Blas/TpetraCore_gemm.exe   367MiB |
+-----------------------------------------------------------------------------+
```

Memory usage is far below the GPU's available limit (only using like 10% of available memory) though GPU utilization is at 100%.
I'm not sure why there are multiple launches of the `TpetraCore_gemm.exe` executable showing up in nvidia-smi as this seems to violate the `RUN_SERIAL` marking, maybe if a test hangs until timeout the executable is relaunched? I don't know what is happening here.

I launched another build with Compadre tests disabled to avoid the executables hanging on the GPU and to see how this alters the testing

**Comment by e10harvey** [comment]
> @e10harvey I retested with the Compadre tests disabled and tests pass 100% with the Cuda build. Can the Compadre tests be disabled for Cuda testing?

@ndellingwood Done. These are the disables I set:
```
Compadre_GMLS_Staggered_Dim2_QR_MPI_1_DISABLE
Compadre_GMLS_Staggered_Dim3_QR_MPI_1_DISABLE
Compadre_GMLS_Staggered_Manifold_Refinement_Study_DISABLE
```

Would you please file an issue for compadre and CC trilinos/framework in the issue?

CC: @trilinos/framework

**Comment by ndellingwood** [comment]
@trilinos/framework @e10harvey From the most recent build, the gcc/7.2.0 debug build failed but I don't see the job on cdash (job 5191). From the drop-down I see this:

```
./Trilinos/cmake/std/PullRequestLinuxDriver.sh: line 113: /projects/sierra/linux_rh7/install/Python/3.6.10/bin/python3: No such file or directory

+----------------------------------------------------------+
|              An error occurred during merge              |
|                                                          |
|                   2022-04-07 02:46:31                    |
+----------------------------------------------------------+
Build step 'Execute shell' marked build as failure
Archiving artifacts
[Checks API] No suitable checks publisher found.
Finished: FAILURE
```

Is this spurious or does this require some sort of intervention to resolve?

From the cuda build, `Test: Krino_krino_unit_MPI_4 (Failed) ` is unrelated to this PR and has been occurring with other PRs, appears to be a system or environment issue? See e.g. https://github.com/trilinos/Trilinos/pull/10406#issuecomment-1090877499

**Comment by e10harvey** [comment]
> @trilinos/framework @e10harvey From the most recent build, the gcc/7.2.0 debug build failed but I don't see the job on cdash (job 5191). From the drop-down I see this:

@ndellingwood: This is a system problem. We are working on resolving this.



> From the cuda build, `Test: Krino_krino_unit_MPI_4 (Failed) ` is unrelated to this PR and has been occurring with other PRs, appears to be a system or environment issue?

The krino failued is also affecting multiple PRs. We have not determined whether this is a system issue and are working with the krino maintainers to resolve this issue.

**Comment by ndellingwood** [comment]
Cross-referencing #10423, #10420 and #10429, once resolved and/or merged this PR should be ready for retest

**Review by srajama1 — APPROVED** [review]
Thanks @ndellingwood ! Reapproving.

**Comment by jwillenbring** [comment]
So it appears there were failures in the debug and intel builds.

https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=10885496&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and

https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=10885368&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and

**Comment by jwillenbring** [comment]
OK, so a lot of this is drives filled up...

**Comment by ndellingwood** [comment]
@trilinos/framework @e10harvey @jwillenbring  the intel/17 build is failing with internal compiler errors in intrepid2, e.g.:

```
icpc: error #10106: Fatal error in /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/base/compilers_and_libraries_2017.1.132/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for packages/intrepid2/unit-test/Projection/test_convergence_QUAD_Serial_DOUBLE.cpp (code 1)
```

The ICE issues weren't occurring with earlier rounds of testing (for example while chasing down the cuda test time outs https://github.com/trilinos/Trilinos/pull/10253#issuecomment-1088066182 and prior to the Jenkins agent issues)
https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=10820443&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and shows success for the most recent run before the Jenkins issues on Vortex

Did any changes occur with the intel/17-debug test env or config etc.? If not, and if the internal compiler errors continue in subsequent tests we'll need help finding a way to get past broken compiler problems. One option could be disabling the intrepid2 tests from building with intel/17 (would require intrepid2 dev approval). Experimenting with reducing the parallelism of the intel/17 debug build or dropping use of ninja (if enabled) may help resolve as well. Thoughts?

Adding @srajama1 @crtrott @lucbv

**Comment by ZUUL42** [comment]
I'm not seeing a common thread in this except for it being a build error for Intrepid2 and they are builds on ascic141, but it has changed and moved from GCC 8.3 to Intel 17.
I'll bring this up with the Framework team Monday morning.

**Comment by ndellingwood** [comment]
Thanks @ZUUL42 . In both cases (intel/17 previous build and gcc/8.3.0 most recent) the failures were compiler related, most recent gcc:

packages/intrepid2/unit-test/Projection/test_interpolation_projection_HEX_Serial_DOUBLE.cpp
```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```

**Comment by ndellingwood** [comment]
@srajama1 can you approve one more time? I had to resolve a merge conflict from a recent merge which discarded the previous review. The good news is the previous test run passed :)

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Retest this please

**Comment by ndellingwood** [comment]
@ZUUL42 @trilinos/framework the cuda build failed at configure with error:
```
...
-- The CXX compiler identification is unknown
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx
-- Check for working CXX compiler: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx - broken
CMake Error at /projects/sparc/tools/cmake/3.19.4/ppc64le/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /vscratch1/trilinos/jenkins/vortex-trilinos/workspace/trilinos-folder/_cuda_10.1.243/pull_request_test/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/projects/atdm_devops/vortex/ninja-fortran-1.8.2/ninja cmTC_f767e && [1/2] Building CXX object CMakeFiles/cmTC_f767e.dir/testCXXCompiler.cxx.o
    FAILED: CMakeFiles/cmTC_f767e.dir/testCXXCompiler.cxx.o 
    /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1/bin/mpicxx    -o CMakeFiles/cmTC_f767e.dir/testCXXCompiler.cxx.o -c testCXXCompiler.cxx
    nvcc fatal   : Could not open output file '/tmp/trilinos/tmpxft_0001f884_00000000'
    ninja: build stopped: subcommand failed.
...
```

The config error isn't due to this PR (it passed the previous build but a merge conflict required a retest)

Was there an update on Vortex or changes to the environment setup for this build? To get around, this may require either configuring on the login node before building/testing on compute, or disabling ninja (or figuring out some other way to resolve).

**Comment by e10harvey** [comment]
> Was there an update on Vortex or changes to the environment setup for this build? To get around, this may require either configuring on the login node before building/testing on compute, or disabling ninja (or figuring out some other way to resolve).

@ndellingwood: No, this appears to be a transient error; [the latest build](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&date=2022-04-26&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PR-10253-test) is progressing without configure errors. We will keep an eye on it.

**Comment by crtrott** [comment]
Ok this time something aborted the GCC 8 test, a test which passed before the restart. This is getting aggrevating.

**Comment by e10harvey** [comment]
> Ok this time something aborted the GCC 8 test, a test which passed before the restart. This is getting aggrevating.

There appears to be a transient error on that compute node... See https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2022-02-01&end=2022-04-26&filtercount=1&showfilters=1&field1=site&compare1=63&value1=vortex51. We are monitoring.

**Comment by jwillenbring** [comment]
The @trilinos/framework team has very carefully evaluated the recent runs of this PR and have decided it is reasonable and safe to force merge this. Here is our justification:

1) If we combine two runs of the autotester since the most recent commit to this PR, we have all builds passing at least once. https://github.com/trilinos/Trilinos/pull/10253#issuecomment-1109912705 https://github.com/trilinos/Trilinos/pull/10253#issuecomment-1109206034

2) The random CUDA failures are due to a hardware or config issue.

3) The random Failures for the GCC8.3 build have been happening sporadically for about a month for various PRs.

Due to the above, we will now move forward with force merging this PR.

**Comment by srajama1** [comment]
@jwillenbring Thanks for prioritizing this PR.

**Pull request merged**
