### PR TITLE
Panzer: fix ExprEval subpackage

### PR DESCRIPTION
**Pull request by rppawlo**
@trilinos/panzer 

## Motivation

Recent PR (#8569 ) ran a sed script that broke the ExprEval subpackage in panzer. Was not caught since the package is experimental and not enabled in PR or ATDM testing. Reverted the changes to this subpackage.

## Testing

All ExprEval tests were failing to compile and are now passing.

### CODE REVIEW

**Comment by bathmatt** [comment]
you want me to fix this?

**Comment by bathmatt** [comment]
How was this caught?

**Review by bathmatt — APPROVED** [review]

**Comment by rppawlo** [comment]
I put up a pr that fixes it. All set.

**Comment by rppawlo** [comment]
> How was this caught?

Albany nightly tests.

**Comment by mperego** [comment]
@rppawlo thanks!

**Comment by rppawlo** [comment]
@trilinos/framework - This PR was submitted on Thursday and seems to be ignored by the PR autotester. Any idea why? At least one other PR is reporting the same issue today too.

**Comment by allevin** [comment]
> @trilinos/framework - This PR was submitted on Thursday and seems to be ignored by the PR autotester. Any idea why? At least one other PR is reporting the same issue today too.

@rppawlo This is most likely due to PR #8542 being marked as draft (draft PR's are not supported by the Autotester).  This is causing problems for the Autotester at this time.  The @trilinos/framework team has been notified.

**Comment by rppawlo** [comment]
> @rppawlo This is most likely due to PR #8542 being marked as draft (draft PR's are not supported by the Autotester). This is causing problems for the Autotester at this time. The @trilinos/framework team has been notified.

@allevin - Thanks! Didn't even know a "draft" feature existed in github. I just removed it from that issue.

**Comment by ikalash** [comment]
Seems this is hanging on the autotester.  Could someone from @trilinos/framework have a look at what is happening?  The nightlies for Albany are still broken as a result of this and I would like to get them back up as soon as possible.

**Comment by prwolfe** [comment]
> Seems this is hanging on the autotester. Could someone from @trilinos/framework have a look at what is happening? The nightlies for Albany are still broken as a result of this and I would like to get them back up as soon as possible.

When the draft label was removed from #8542 the autotester started processing again. It is currently working on #8582

**Pull request merged**
