### PR TITLE
Update TriBITS snapshot 2024-01-24 and set Trilinos_SHOW_GIT_COMMIT_PARENTS=ON for PR builds

### PR DESCRIPTION
**Pull request by bartlettroscoe**
This TriBITS snapshot pulls in updates to TriBITS 'master' from the TriBITS PRs:

* TriBITSPub/TriBITS#598 (The main motivation for this TriBITS snapshot)
* TriBITSPub/TriBITS#599

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Wow, 11 hours and the autotester still has not picked up testing of this PR.

@achauphan and @sebrowne, I am wondering if it might not be a good idea to turn on [`Trilinos_SHOW_GIT_COMMIT_PARENTS`](https://tribitspub.github.io/TriBITS/build_ref/index.html#show-parent-s-commit-info-in-the-repo-version-output) for the PR builds right in this PR since it will take some time to get merged?  That way we will be able to see the results on CDash for the PR builds for this PR.

**Comment by bartlettroscoe** [comment]
CC: @achauphan, @sebrowne 

And we are seeing the parent commit info show for this PR.  For example [here](https://trilinos-cdash.sandia.gov/build/1361571/configure) shows:

```
Trilinos repos versions:
--------------------------------------------------------------------------------
*** Base Git Repo: Trilinos
6e6ab6d [Thu Jan 25 10:03:57 2024 -0700] <trilinos@sandia.gov>
Merge commit 'da7de59e4a2de0b4872bdafdfa1e2b9904f28d10' into develop
    *** Parent 1:
    74e4930 [Thu Jan 25 09:51:48 2024 -0700] <ndellin@sandia.gov>
    Merge pull request #12689 from ndellingwood/amesos2-shylubasker-runtime-trsolv
    *** Parent 2:
    da7de59 [Thu Jan 25 06:52:50 2024 -0700] <rabartl@sandia.gov>
    Set Trilinos_SHOW_GIT_COMMIT_PARENTS=ON for all GenConfig PR builds (TriBITSPub/
 --------------------------------------------------------------------------------
```

while another build [here](https://trilinos-cdash.sandia.gov/build/1361513/configure) shows:

```
Trilinos repos versions:
--------------------------------------------------------------------------------
*** Base Git Repo: Trilinos
f75fd6c [Thu Jan 25 10:03:03 2024 -0700] <trilinos@sandia.gov>
Merge commit 'da7de59e4a2de0b4872bdafdfa1e2b9904f28d10' into develop
    *** Parent 1:
    74e4930 [Thu Jan 25 09:51:48 2024 -0700] <ndellin@sandia.gov>
    Merge pull request #12689 from ndellingwood/amesos2-shylubasker-runtime-trsolv
    *** Parent 2:
    da7de59 [Thu Jan 25 06:52:50 2024 -0700] <rabartl@sandia.gov>
    Set Trilinos_SHOW_GIT_COMMIT_PARENTS=ON for all GenConfig PR builds (TriBITSPub/
 --------------------------------------------------------------------------------
```

So we can see that the local merge commit SHA1s are different (`6e6ab6d ` vs `f75fd6c `) but the parents 74e4930 (the tip of 'develop')  and da7de59 (the tip of the PR topic branch) are identical.

@achauphan and @sebrowne, cane one of you please approve this PR so that it can merge?  (Crossing fingers there will be no random failures :-))

**Comment by achauphan** [comment]
Sweet, it's working on all builds!

Interesting that the merge commit SHA1s are different here. That would suggest that time of commit is used for the hashing, which I didn't know.

**Comment by bartlettroscoe** [comment]
> Interesting that the merge commit SHA1s are different here. That would suggest that time of commit is used for the hashing, which I didn't know.

That does seem to be the case and that is the behavior we have observed for years with the autotester.

NOTE: Once Trilinos adopts GHA, then GH will create the merge commit in the central repo and that same merge commit will be checked out in every GHA runner.

**Comment by bartlettroscoe** [comment]
FYI: Look at the results on CDash [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-12695-&field2=buildstarttime&compare2=84&value2=now), it appears that one of the seven PR builds never fired off (or is not able to submit to CDash).  It is hard to match up the builds (given the huge long build names) but it looks like the missing build is the `Trilinos_PR_cuda-11.4.2-uvm-off` build:

* `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables`.

All of the other builds have completed and passed everything 🥲

From looking that [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2024-01-01&end=2024-01-26&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=63&value2=rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables), it appears that that build has not showed up on CDash since 2024-01-24 (and the two most recent builds yesterday did not show any build or test results).

@achauphan and @sebrowne, can someone see what happened to that build?  (I can't remember where the Jenkins site driving this builds is located.)

**Comment by bartlettroscoe** [comment]
Interesting, the [last PR testing iteration](https://github.com/trilinos/Trilinos/pull/12695#issuecomment-1911334222) took 10 hours to come back failed (it started at 12:02 PM and came back failed at 10:03 pm yesterday).  I am guessing there is a 10 hours time limit on the Jenkins runners (or the main driver Jenkins job).

**Comment by achauphan** [comment]
Referencing status update in #12696.

Looks like this job was started while all GPU nodes were offline and searched for an available node for about ~7 hours until all nodes GPU nodes were brought back up. Tests on this node were taking ~60s each which ran until the timeout limit. The node that picked up this job was previously turned off due to the same performance issues, but was brought back online along with the other recent offline nodes.

I've turned this node back offline. The other nodes seem to be performing as usual so I will add request a RETEST here.

**Comment by bartlettroscoe** [comment]
> Looks like this job was started while all GPU nodes were offline and searched for an available node for about ~7 hours until all nodes GPU nodes were brought back up. Tests on this node were taking ~60s each which ran until the timeout limit. The node that picked up this job was previously turned off due to the same performance issues, but was brought back online along with the other recent offline nodes.

@achauphan, does the autotester block until this last Jenkins job timed out?  If so, that would mean that the other active odd-numbers PRs were waiting to be tested while that one Jenkins job was trying to get a job running for 10 hours?

I am guessing that the GHA implementation will not have this behavior since it can better schedule jobs across available machines (unlike the current autotester implementation that just uses a simple modulo implementation `<pr-id> % <num-concurrent-autotester-tracks>`).

The Trilinos experience with autotester is a case study in why it is not trivial to write your own CI testing system.

**Comment by bartlettroscoe** [comment]
FYI, the last PR testing iteration [above](https://github.com/trilinos/Trilinos/pull/12695#issuecomment-1912741936) failed because the `Trilinos_PR_gcc-8.3.0-debug` build (long name `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`) did not submit results to CDash as (**not**) shown [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-12695-test&field2=buildstarttime&compare2=83&value2=2024-01-26T19%3A44%3A22%20UTC&field3=buildstarttime&compare3=84&value3=2024-01-26T19%3A45%3A46%20UTC).  That only shows 6 builds and there should be 7.

But as shown in [this query](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&begin=2024-01-24&end=2024-01-26&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables), that  `Trilinos_PR_gcc-8.3.0-debug` build `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables` has been run with other PRs recently (as recent as 2 hours ago) so I guess we can try again.  I will put on `AT: RETEST` again and cross out fingers.

**Comment by achauphan** [comment]
Looks like the `Trilinos_PR_gcc-8.3.0-debug` Jenkins job for this PR for some reason did not run the `clean_workspace.py` script leading to there not being enough scratch space. This seem to have also happened to #12693's latest `Trilinos_PR_gcc-8.3.0-debug` run... However, it looks like the subsequent jobs after those two ran the clean up script successfully and were able to continue with the PR script...

**Comment by achauphan** [comment]
Heads up, this next AT run is going to fail. Three of the nodes that the following builds were running on went offline in middle of their AutoTester run.
`Trilinos_PR_intel-2021.3`
`Trilinos_PR_gcc-8.3.0-debug`
`Trilinos_PR_gcc-8.3.0`

**Comment by bartlettroscoe** [comment]
> Three of the nodes that the following builds were running on went offline in middle of their AutoTester run.

When it rains, it pours ☹️

**Pull request merged**
