### PR TITLE
amesos2(fix): compilation error on hip with complex

### PR DESCRIPTION
**Pull request by romintomasetti**
@trilinos/<Amesos2>

## Motivation

This PR fixes a compilation issue for Amesos2 on HIP with complex type.

## Related Issues

This PR is related to:
* #10963

### CODE REVIEW

**Comment by iyamazaki** [comment]
Thank you for the fixes, @romintomasetti!! These look good, and my `complex` configure still built. I hope this also fixes [10952](https://github.com/trilinos/Trilinos/issues/10952).

**Comment by jhux2** [comment]
@romintomasetti Thank you!

@iyamazaki Shouldn't you be a member of the @trilinos/amesos2 team?

**Comment by iyamazaki** [comment]
I am not sure why this failed.. @jhux2, do you know where I can find the errors?

**Comment by romintomasetti** [comment]
@jhux2 Should the actions be re-launched then ? :smile:

**Comment by jhux2** [comment]
@romintomasetti I've made the Framework aware of the issue, hopefully they can resolve the problem soon.

**Comment by iyamazaki** [comment]
Thank you again for the fixes, @romintomasetti !!

**Pull request merged**
