### PR TITLE
TriBITS: Transition to find_package(Python3) (TriBITSPub/TriBITS#610)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
This TriBITS snapshot primarily brings in change to TriBITS for transitioning to `find_package(Python3)`:

* TriBITSPub/TriBITS#610

This brings in other changes to TriBITS as well, primarily from the PRs:

* TriBITSPub/TriBITS#608
* TriBITSPub/TriBITS#617
* TriBITSPub/TriBITS#616
* TriBITSPub/TriBITS#615
* TriBITSPub/TriBITS#611
* TriBITSPub/TriBITS#614
* TriBITSPub/TriBITS#613
* TriBITSPub/TriBITS#609

(If you want to review changes in TriBITS, please review them in the native TriBITS PRs listed above.)

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
FYI: I might make sense to add a Trilinos-level release note as well.  This could just be a copy of the new entry from the `tribits/CHANGELOG.md` file.

**Comment by bartlettroscoe** [comment]
@trilinos/muelu, @sebrowne.,

FYI: This PR and every PR will be blocked from merging due to:

* #13524

**Comment by bartlettroscoe** [comment]
I put on the label `AT: WIP` for now.  I forgot to run the `to-python3.sh` script on Trilinos and make other adjustments for this change.  I am testing locally.  Once I get a local build to work, I will run on the PR testing again.

**Comment by bartlettroscoe** [comment]
@sebrowne, @trilinos/framework, @trilinos/pytrilinos, @trilinos/pytrilinos2, @trilinos/compadre, @trilinos/epetraext, @trilinos/ifpack2, @trilinos/ifpack2, @trilinos/ml, @trilinos/muelu, @trilinos/rol, @trilinos/shylu,

This PR should be ready to review and merge.

A few notes:

* It does not look like PyTrilinos or PyTrilinos2 is getting tested in the PR testing builds.   And I don't have any way to test those changes.
* I left the non-TriBITS CMake code alone and did not replace `PYTHON_EXECUTABLE` with `Python3_EXECUTABLE`.

**Comment by bartlettroscoe** [comment]
FYI: I created a git pre-push hook script to detect commits that are not signed off so I avoid the hassle and wasted time and computing resources in pushing non-signed-off commits to a branch.  See:

*  https://github.com/TriBITSPub/TriBITS/pull/620

And I rebased the commits to make them all signed off.

**Comment by bartlettroscoe** [comment]
There were to failed tests last PR test iteration which can be see [here](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-13523-test-&field2=status&compare2=62&value2=Passed&field3=buildstarttime&compare3=84&value3=2024-10-11T21%3A00%3A46%20UTC&field4=buildstarttime&compare4=83&value4=2024-10-11T20%3A54%3A37%20UTC) showing:

| Site | Build Name | Test Name | Status | Time Status | Time | Proc Time | Details | Labels | Build Time | Processors |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| ascic0206 | PR-13523-test-rhel8_sems-gnu-8.5.0-openmpi-4.1.6-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-669 | Intrepid2_unit-test_Shared_Polylib_test_01_Serial_DOUBLE_MPI_1 | Failed | Passed | 10m 80ms | 10m 80ms | Completed (Timeout) |   | 2024-10-11T14:56:27 MDT | 1 |
| ascic0206 | PR-13523-test-rhel8_aue-gnu-12.1.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-4626 | TrilinosInstallTests_reduced_tarball | Failed | Passed | 2m 2s 340ms | 2m 2s 340ms | Completed (Failed) |   | 2024-10-11T14:55:48 MDT | 1 |

The test `Intrepid2_unit-test_Shared_Polylib_test_01_Serial_DOUBLE_MPI_1` is a timeout.

The failing test `TrilinosInstallTests_reduced_tarball` is more troubling.  That one if failing due to:

```
...

Final set of non-enabled top-level packages:  Gtest Kokkos Teuchos KokkosKernels RTOp Sacado MiniTensor Epetra Zoltan Shards Triutils EpetraExt Tpetra TrilinosSS Thyra Xpetra Isorropia AztecOO Galeri Amesos Pamgen Zoltan2Core Ifpack ML Belos Amesos2 Anasazi Ifpack2 Stratimikos Teko Intrepid Intrepid2 Compadre NOX MueLu Zoltan2Sphynx Zoltan2 Tempus Stokhos ROL Piro TrilinosCouplings TrilinosBuildStats TrilinosInstallTests 44

...

TEST_2: Pass criteria = Match all REGEX {Final set of non-enabled top-level packages:  0} [FAILED]
```

But what is strange is that that test passes in all of the other PR builds as shown in [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-13523-test-&field2=testname&compare2=61&value2=TrilinosInstallTests_reduced_tarball&field3=buildstarttime&compare3=84&value3=2024-10-11T21%3A00%3A46%20UTC&field4=buildstarttime&compare4=83&value4=2024-10-11T20%3A54%3A37%20UTC) showing:

Site | Build Name | Test Name | Status | Time Status | Time | Proc Time | Details | Labels | Build Time | Processors
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ascic0206 | PR-13523-test-rhel8_aue-gnu-12.1.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-4626 | TrilinosInstallTests_reduced_tarball | Failed | Passed | 2m 2s 340ms | 2m 2s 340ms | Completed (Failed) |   | 2024-10-11T14:55:48 MDT | 1
ascic166 | PR-13523-test-rhel8_sems-gnu-8.5.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-668 | TrilinosInstallTests_reduced_tarball | Passed | Passed | 3m 45s 560ms | 3m 45s 560ms | Completed |   | 2024-10-11T14:54:38 MDT | 1
ascic0206 | PR-13523-test-rhel8_sems-gnu-8.5.0-openmpi-4.1.6-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-669 | TrilinosInstallTests_reduced_tarball | Passed | Passed | 4m 11s 190ms | 4m 11s 190ms | Completed |   | 2024-10-11T14:56:27 MDT | 1
ascicgpu051 | PR-13523-test-rhel8_sems-cuda-11.4.2-gnu-10.1.0-openmpi-4.1.6_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables-666 | TrilinosInstallTests_reduced_tarball | Passed | Passed | 3m 57s 250ms | 3m 57s 250ms | Completed |   | 2024-10-11T14:57:12 MDT | 1
ascic0193 | PR-13523-test-rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-618 | TrilinosInstallTests_reduced_tarball | Passed | Passed | 4m 45s 330ms | 4m 45s 330ms | Completed |   | 2024-10-11T14:58:07 MDT | 1

So what is different about this `aue` build compared to the other `sems` builds?

**Comment by bartlettroscoe** [comment]
I seem to have some memory of a defect with that aue Python build so I will just select `AT: RETEST` and cross my fingers!

**Review by sebrowne — APPROVED** [review]
Approving assuming that the code has already been tested/reviewed in the TriBITS project and having read the summary of what capability is being introduced.

**Comment by bartlettroscoe** [comment]
@sebrowne, @rppawlo, @ccober6,

This PR has passed testing and has an approved review (from @sebrowne).  None of the package teams have provided a review yet.  While I believe the changes to their packages are good, proper, and correct (for the use cases as I understand them), I have no idea if PyTrilinos or PyTrilinos2 works (because they are not tested).  And I suspect that PyTrilinos will **not** work after this refactoring.

Should we go ahead and merge without additional reviews (and cross our fingers)?

**Comment by ccober6** [comment]
I believe PyTrilinos is not functioning at this point anyways (@cgcgcg ?), so I would not worry about it.  As far as the other CODEOWNERS, they have had a week to review, so I would suggest moving forward with the merge.

**Pull request merged**
