### PR TITLE
MueLu: diagonal modifications for Chebyshev and prolongator smoothing

### PR DESCRIPTION
**Pull request by jhux2**
@trilinos/muelu 

## Motivation
Modify diagonal inversion for prolongator smoothing and local iterative smoothing.

## Testing

---
This change is [Reviewable](https://reviewable.io/reviews/trilinos/trilinos/8479)

### CODE REVIEW

**Comment by jhux2** [comment]
@csiefer2 @rstumin

**Comment by jhux2** [comment]
The autotester has passed this. I'm applying the WIP label in order to save compute cycles.  I will be applying a few more changes.

**Comment by jhux2** [comment]
@csiefer2 @rstumin Can one of you review?

**Comment by rstumin** [comment]
@jhux2  This code looks good. The only issue that I have is tolReplacement. Right now, there is no way to set this for things like prolongator smoothing from the input deck. Is this something that you could change? This is needed for the sp10 problem.

**Comment by jhux2** [comment]
> @jhux2 This code looks good. The only issue that I have is tolReplacement. Right now, there is no way to set this for things like prolongator smoothing from the input deck. Is this something that you could change? This is needed for the sp10 problem.

@rstumin Ok, option added, and I've checked that the SP10 test now passes.

**Review by rstumin — DISMISSED** [review]
Looks awesome.

**Review by rstumin — APPROVED** [review]
Looks good.

**Pull request merged**
