### PR TITLE
FMT: Fixes for intel-19 compiler

### LINKED ISSUE #10172: SEACAS: build error under Intel 2020.2
## Bug Report
@trilinos/seacas @gsjaardema @jrood-nrel @paulmullowney 

### Description
Colleagues have reported the following Trilinos build error with Intel 2020.2 and (possibly) with gcc 9.3.0.  This is for Trilinos develop `ef73d14babf`.  (A previous build with `cbcdc150777` succeeded.

```
  >> 3952    /projects/ecp/exawind/exawind-testing/spack-manager/stage/jrood/sp
             ack-stage-trilinos-develop-srdtfhnbtdkqj7o2jp2auisdi4vlpqlr/spack-
             src/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h
             (1706): error: static assertion failed with "Cannot format a const
              argument."
     3953        static_assert(formattable_const, "Cannot format a const argume
             nt.");
     3954        ^
     3955              detected during:
     3956                instantiation of "auto fmt::v8::detail::make_arg<IS_PA
             CKED,Context,<unnamed>,T,<unnamed>>(T &&)->fmt::v8::detail::value<
             Context> [with IS_PACKED=true, Context=fmt::v8::basic_format_conte
             xt<fmt::v8::detail::buffer_appender<char>, char>, <unnamed>=fmt::v
             8::detail::type::custom_type, T=const fmt::v8::remove_cvref_t<cons
             t fmt::v8::remove_reference_t<fmt::v8::group_digits_view<std::size
             _t={unsigned long}>> &> &, <unnamed>=0]" at line 1848
```

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas 

## Motivation

This fixes the build problems related to lib::fmt on the intel-19 compiler.  The fixes were developed from discussions in https://github.com/fmtlib/fmt/issues/2746

* Closes #10172

### CODE REVIEW

**Comment by jhux2** [comment]
@gsjaardema I tested this PR on Summit.  The compile still fails in what looks like a similar error.

I should note that this build is with gcc 8.3.1 and CUDA 11, not Intel.


```
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h(416): warning: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "auto fmt::v8::detail::to_unsigned(Int)->std::make_unsigned<Int>::type [with Int=size_t]"
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/format.h(464): here
            instantiation of "auto fmt::v8::detail::fill_n(T *, Size, char)->T * [with T=char, Size=size_t]"
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/format.h(708): here
            instantiation of "fmt::v8::basic_memory_buffer<T, SIZE, Allocator>::basic_memory_buffer(const Allocator &) [with T=char, SIZE=500UL, Allocator=std::allocator<char>]"
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/format-inl.h(82): here

/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h(1705): error: static assertion failed with "Cannot format a const argument."
          detected during:
            instantiation of "auto fmt::v8::detail::make_arg<IS_PACKED,Context,<unnamed>,T,<unnamed>>(T &&)->fmt::v8::detail::value<Context> [with IS_PACKED=true, Context=fmt::v8::basic_format_context<fmt::v8::detail::buffer_appender<char>, char>, <unnamed>=fmt::v8::detail::type::custom_type, T=const fmt::v8::remove_cvref_t<const fmt::v8::remove_reference_t<fmt::v8::group_digits_view<std::size_t>> &> &, <unnamed>=0]"
(1847): here
```

**Comment by gsjaardema** [comment]
@jhux2 OK thanks.  It must be the nvidia compiler; I've had issues with that in the past.  Will hopefully have something tomorrow.

**Comment by gsjaardema** [comment]
@jhux2 Do you have a traceback of that error which shows the line of code that ther error is on?  The traceback above only shows fmt include files, not a reference to the ioss file that is calling fmt and triggering the error.

**Comment by jhux2** [comment]
> Do you have a traceback of that error which shows the line of code that ther error is on? The traceback above only shows fmt include files, not a reference to the ioss file that is calling fmt and triggering the error.

@gsjaardema Here's a traceback.  I'm not sure whether this was prior to testing this PR or afterwards.

```
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/libraries/suplib_cpp/fmt/core.h(1705): error: static assertion failed with "Cannot format a const argument."
          detected during:
            instantiation of "auto fmt::v8::detail::make_arg<IS_PACKED,Context,<unnamed>,T,<unnamed>>(T &&)->fmt::v8::detail::value<Context> [with IS_PACKED=true, Context=fmt::v8::basic_format_context<fmt::v8::detail::buffer_appender<char>, char>, <unnamed>=fmt::v8::detail::type::custom_type, T=const fmt::v8::remove_cvref_t<fmt::v8::group_digits_view<unsigned long> &> &, <unnamed>=0]"
(1847): here
            instantiation of "fmt::v8::format_arg_store<Context, Args...>::format_arg_store(T &&...) [with Context=fmt::v8::basic_format_context<fmt::v8::detail::buffer_appender<char>, char>, Args=<unsigned long, fmt::v8::group_digits_view<unsigned long>, unsigned long>, T=<const fmt::v8::remove_reference_t<unsigned long> &, const fmt::v8::remove_reference_t<fmt::v8::group_digits_view<unsigned long>> &, const fmt::v8::remove_reference_t<unsigned long> &>]"
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/libraries/suplib_cpp/fmt/format.h(850): here
            instantiation of "auto fmt::v8::make_args_checked<Args...,S,Char>(const S &, const fmt::v8::remove_reference_t<Args> &...)->fmt::v8::format_arg_store<fmt::v8::buffer_context<Char>, fmt::v8::remove_reference_t<Args>...> [with Args=<unsigned long, fmt::v8::group_digits_view<unsigned long>, size_t>, S=char [103], Char=char]"
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/libraries/suplib_cpp/fmt/ostream.h(131): here
            instantiation of "void fmt::v8::print(std::basic_ostream<Char, std::char_traits<Char>> &, const S &, Args &&...) [with S=char [103], Args=<unsigned long, fmt::v8::group_digits_view<unsigned long>, size_t>, Char=char]"
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/applications/exodiff/map.C(264): here
            instantiation of "void Compute_Maps(std::vector<INT, std::allocator<INT>> &, std::vector<INT, std::allocator<INT>> &, ExoII_Read<INT> &, ExoII_Read<INT> &) [with INT=int]"
/ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/seacas/applications/exodiff/map.C(1126): here
```

**Comment by jhux2** [comment]
@gsjaardema Thank you for the update.  I pulled your branch and built on Summit.  Unfortunately, the compiled failed, please see the attached make log.
[make.txt](https://github.com/trilinos/Trilinos/files/8063170/make.txt)

**Comment by gsjaardema** [comment]
@jhux2   What are the modules / compilers being used on Summit?  I have been unable to match your failure with various versions of nvcc on other systems...

**Comment by jhux2** [comment]
> What are the modules / compilers being used on Summit? I have been unable to match your failure with various versions of nvcc on other systems...

@gsjaardema Here are the modules I load on Summit.  I fairly certain the underlying compiler is gcc 8.3.1, but Summit is down today so I can't check.

```
module load cuda/11.0.3
module load spectrum-mpi/10.4.0.3-20210112
module load hdf5/1.10.7
module load netcdf-c/4.8.0
module load parallel-netcdf/1.12.2
module load superlu/5.2.1
module load netlib-lapack/3.9.1
module load cmake/3.20.2
module load boost/1.76.0
module load zlib/1.2.11
module load libxml2/2.9.10
module load parmetis/4.0.3
module load metis/5.1.0
module load yaml-cpp/0.7.0
```

**Comment by gsjaardema** [comment]
@jhux2 Thanks.  I will try to reproduce the failure, but if I have no luck today, then reverting the commit is probably the best option...

**Comment by gsjaardema** [comment]
@jhux2 Can you see if this fixes the issue.  It seems to work correctly doing a Sierra build with nvidia (the sierra build fails without fix)  [Sierra == application, not platform]

**Comment by jhux2** [comment]
>  Can you see if this fixes the issue. It seems to work correctly doing a Sierra build with nvidia (the sierra build fails without fix) [Sierra == application, not platform]

I can try when Summit comes back from system time.

**Review by jhux2 — APPROVED** [review]
@gsjaardema The compile passes on Summit.  Thank you for the fix!

**Comment by gsjaardema** [comment]
I apologize for the delay.  It turns out that the fix I put in last week was the correct fix, but I missed applying it to one file...  Hope it didn't cause too much churn.

**Comment by jhux2** [comment]
@gsjaardema No worries, thank you for fixing this.

**Pull request merged**
