### PR TITLE
Seacas partial snapshot 10 2023

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas 

## Motivation

Partial snapshot of SEACAS code into Trilinos.  Everything but some IOSS changes.  Reducing size of snapshot...

### CODE REVIEW

**Comment by gsjaardema** [comment]
@alanw0 @prwolfe @tokusanya Not sure if anyone's around today, but if so, would you mind doing a quick review of a partial seacas snapshot.  Should be fairly benign changes such as blank line removal, formatting, adding some documentation URL to help outputs...   Thanks.

**Review by alanw0 — APPROVED** [review]

**Comment by gsjaardema** [comment]
@alanw0 Thanks.

**Comment by gsjaardema** [comment]
recheck

**Comment by gsjaardema** [comment]
@e10harvey @jwillenbring  This PR seems to be stuck.  It has a review, but the check is saying that there are no reviewers defined.  Any idea how to get the check to rerun

**Pull request merged**
