### PR TITLE
MueLu ParameterListInterpreter: Don't compare to gold files on Cuda

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
Cuda runs are non-deterministic, so no point in comparing against gold files. Hopefully takes care of #6866

### CODE REVIEW

**Comment by mhoemmen** [comment]
@cgcgcg Do gold files not have a tolerance?  That's usually how the applications do it.  I'm a bit worried that this PR simply disables some tests for CUDA builds, but perhaps I don't quite understand how gold file checks work.

**Comment by cgcgcg** [comment]
@mhoemmen We are outright comparing the output of runs. We do filter some things, but we're not applying tolerances. We do have convergence test, but these are mostly meant to test that the inputs give us the behavior we expect. I'd also prefer keeping this test enabled on Cuda, but its not really feasible, unless we keep one set of gold files per system or test deterministic algos only.

**Comment by mhoemmen** [comment]
Perhaps I'm confused, but this feels like it just turns off a bunch of tests in CUDA builds.  If that's what it is, then I don't feel good about it.

**Comment by lucbv** [comment]
@mhoemmen
For GPU we check that the parameters passed by the user are leading to a non-crashing call to MueLu.
For serial and OpenMP we check the screen output against gold files.

We just do not know how to do gold file comparison in the case of GPUs so we do not perform that check. I am not sure if this means "turning off GPU tests" for you?
Also not that these tests never worked on GPU and now they should actually report something meaningful.

**Comment by mhoemmen** [comment]
@lucbv Thanks for explaining!  @csiefer2 told me not to worry, so I won't worry :-) .

**Pull request merged**
