### PR TITLE
Disable unit test openmp.gemm_double for KOKKOS_ENABLE_DEBUG=OFF (#2439)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC:: @trilinos/kokkos-kernels 

## Description

This PR seems to address the expensive KokkosKernel unit tests described in https://github.com/trilinos/Trilinos/issues/2439#issuecomment-376554303.

I ran the KokkosKernel tests for this build and it gave:

```
Test project /home/rabartl/Trilinos.base/BUILD/WHITE/CHECKIN/gnu-debug-openmp
    Start 1: KokkosKernels_blas_openmp_MPI_1
    Start 7: KokkosKernels_graph_serial_MPI_1
    Start 6: KokkosKernels_sparse_serial_MPI_1
    Start 2: KokkosKernels_sparse_openmp_MPI_1
    Start 3: KokkosKernels_graph_openmp_MPI_1
    Start 5: KokkosKernels_blas_serial_MPI_1
    Start 4: KokkosKernels_common_openmp_MPI_1
    Start 8: KokkosKernels_common_serial_MPI_1
1/8 Test #8: KokkosKernels_common_serial_MPI_1 ...   Passed    0.70 sec
2/8 Test #4: KokkosKernels_common_openmp_MPI_1 ...   Passed    1.40 sec
3/8 Test #1: KokkosKernels_blas_openmp_MPI_1 .....   Passed   73.80 sec
4/8 Test #5: KokkosKernels_blas_serial_MPI_1 .....   Passed  100.82 sec
5/8 Test #3: KokkosKernels_graph_openmp_MPI_1 ....   Passed  254.48 sec
6/8 Test #2: KokkosKernels_sparse_openmp_MPI_1 ...   Passed  263.20 sec
7/8 Test #6: KokkosKernels_sparse_serial_MPI_1 ...   Passed  341.99 sec
8/8 Test #7: KokkosKernels_graph_serial_MPI_1 ....   Passed  416.39 sec

100% tests passed, 0 tests failed out of 8

Subproject Time Summary:
KokkosKernels    = 1452.77 sec*proc (8 tests)

Total Test time (real) = 416.41 sec
```

So if this PR is accepted, hopefully we will not see these timeouts going forward for debug-mode builds.

### CODE REVIEW

**Comment by ibaned** [comment]
@bartlettroscoe is it problematic that this variable has the same name as the one I introduced?

**Comment by bartlettroscoe** [comment]
>  is it problematic that this variable has the same name as the one I introduced?

@ibaned, it is not idea but it harmless.  At first, I tried to just define that one var and use it in both unit test executables but that did not work.  We can use unique names.

**Comment by mhoemmen** [comment]
@bartlettroscoe We should actually have a simultaneous pull request against kokkos-kernels with these changes.  Otherwise, they will get clobbered on the next Kokkos->Trilinos promotion.  It's pretty easy to do that; I normally just make patch files for one repo, edit the file paths in the patch files directly, and apply them to the other repo.

**Comment by bartlettroscoe** [comment]
> We should actually have a simultaneous pull request against kokkos-kernels with these changes. Otherwise, they will get clobbered on the next Kokkos->Trilinos promotion. It's pretty easy to do that; I normally just make patch files for one repo, edit the file paths in the patch files directly, and apply them to the other repo.

Sure.  I will post that PR to the KokkosKernels git repo shortly.

**Comment by bartlettroscoe** [comment]
I posted https://github.com/kokkos/kokkos-kernels/pull/194 for this PR.

Note that this patch could not be pulled off cleanly and applied with git format-patch and am.  I did not inspect too carefully (because it is nearly impossible to directly debug why git will not apply a patch with git am) so I just manually made the change there.  I think it might have been rejected because the PR https://github.com/kokkos/kokkos-kernels/pull/193 is not even excepted yet (even though it has on the Trilinos side).  This is asking for trouble because if these PRs to the kokkos-kernels git repo are not accepted before the next time that kokkos and kokkos-kernels are updated in Trilinos, then our local changes will get wiped out.

**Pull request merged**
