### PR TITLE
STK: Snapshot 04-16-24 20:17 from Sierra 5.19.2-716-g2016503a

### PR DESCRIPTION
**Pull request by alanw0**
@trilinos/<teamName>

## Testing

Includes:
- stk_search: ArborX added as optional dependency beneath search
- stk_mesh: Multi-state-field state rotation now optionally rotates device fields without requiring sync/modify calls.
- stk_ngp_test: remove include of .cpp files
- numerous warning fixes
- numerous documentation-test additions and improvements
- stk_mesh: bug-fix in create_interior_block_boundary_sides
- stk_search: in-progress addition of GPU search APIs
- stk_search: move MORTON_LBVH implementation into stk
- stk_topology/stk_mesh/stk_io: in-progress support for edge-sides on shell elements. will continue changing!
-

### CODE REVIEW

**Comment by ldh4** [comment]
Looks like something isn't quite right with the cmake file changes:
```
CMake Error at cmake/tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake:989 (message):
  Error, the package variable LIB_REQUIRED_DEP_PACKAGES was not defined
  correctly for package STKMiddle_mesh_util!
```

**Comment by dalg24** [comment]
cc @aprokop 
@alanw0 Andrey and I had a glanced over the implementation and it looks like it is not taking advantage of ArborX's access traits facility which would avoid making a copy of your mesh data before building the acceleration structure and when querying.
We would be interested to see performance numbers if you ran benchmarks and help optimize.

**Comment by alanw0** [comment]
> cc @aprokop @alanw0 Andrey and I had a glanced over the implementation and it looks like it is not taking advantage of ArborX's access traits facility which would avoid making a copy of your mesh data before building the acceleration structure and when querying. We would be interested to see performance numbers if you ran benchmarks and help optimize.

Great, we would appreciate any help if we're not using ArborX optimally, thanks!
I'll tag Heather (@hpacella ) who can provide at least a sampling of benchmarking numbers. ArborX was a clear winner in our benchmarking!

**Comment by hpacella** [comment]
> > cc @aprokop @alanw0 Andrey and I had a glanced over the implementation and it looks like it is not taking advantage of ArborX's access traits facility which would avoid making a copy of your mesh data before building the acceleration structure and when querying. We would be interested to see performance numbers if you ran benchmarks and help optimize.
> 
> Great, we would appreciate any help if we're not using ArborX optimally, thanks! I'll tag Heather (@hpacella ) who can provide at least a sampling of benchmarking numbers. ArborX was a clear winner in our benchmarking!

Below are some basic benchmarking results that we did at the beginning of our current search effort. They show performance results for some standard application tests using ArborX and an in-house search method (Morton). These tests were run on our local V100 computing resources, and are for a single domain box and a single range box. Let me know if you have any questions. 

image

**Review by ldh4 — APPROVED** [review]

**Pull request merged**
