### PR TITLE
Went to all workset local index into orientation array

### PR DESCRIPTION
**Pull request by bathmatt**
See #3785

### CODE REVIEW

**Comment by bathmatt** [comment]
```
100% tests passed, 0 tests failed out of 159

Label Time Summary:
Panzer    = 773.96 sec (159 tests)

Total Test time (real) = 113.65 sec

```

**Comment by eric-c-cyr** [comment]
I don't think this is right. The change proposed doesn't make a whole lot of sense. For instance in Panzer_WorksetContainer.cpp:298 orientations_ is defined over all cells on the processor. While the loop is clearly over a workset.

```
          ortsPerBlock.clear();
          for (int k=0;k<worksets[i].num_cells;++k) {
            ortsPerBlock.push_back((*orientations_)[details.cell_local_ids[k]]);
          }
```

**Comment by bathmatt** [comment]
So you think what is written is correct, I changed it to push back just [k], the old code is listed below

> I don't think this is right. The change proposed doesn't make a whole lot of sense. For instance in Panzer_WorksetContainer.cpp:298 orientations_ is defined over all cells on the processor. While the loop is clearly over a workset.
> 
> ```
>           ortsPerBlock.clear();
>           for (int k=0;k<worksets[i].num_cells;++k) {
>             ortsPerBlock.push_back((*orientations_)[details.cell_local_ids[k]]);
>           }
> ```

**Comment by bathmatt** [comment]
Don't merge, this has a bug on big problems...  Probably problems where the workset size is bigger than the block size...

**Comment by rppawlo** [comment]
I'm working on converting CurlLaplacian and/or MixedPoisson to multiblock to see if we can replicate there. Have a meeting with @eric-c-cyr and Nate on Fluids/GPU. After that we will stay on and talk more about this. @bathmatt - do you want to call in? If so, will forward invite.

**Comment by eric-c-cyr** [comment]
@bathmatt, did the fix you push solve the problem for your example?

**Comment by eric-c-cyr** [comment]
@bathmatt, did the fix you push solve the problem for your example?

**Comment by eric-c-cyr** [comment]
@bathmatt, did the fix you push solve the problem for your example?

**Comment by bathmatt** [comment]
> @bathmatt, did the fix you push solve the problem for your example?

It fixed it for small problems, not for large problems.  
Let me try to tri meshes, it may be since all the meshes look the same.

**Comment by bathmatt** [comment]
visit0002

Triangles also work with my fixes, trilinos/develop gives
visit0003

**Comment by bathmatt** [comment]
Sure, i can call in @rppawlo

**Comment by bathmatt** [comment]
I can't figure out what magic fills the setup data or what the setup data is even,   sd.orientations_ 
```
template<typename EvalT, typename Traits>
void
BasisValues_Evaluator<EvalT, Traits>::
postRegistrationSetup(
  typename Traits::SetupData  sd,
  PHX::FieldManager<Traits>&  fm)
{
  int space_dim = basis->dimension();

  orientations = sd.orientations_;
```

**Comment by eric-c-cyr** [comment]
How big is the problem you are running, I assume there are issues in serial?

**Comment by eric-c-cyr** [comment]
Or is this in parallel?

**Comment by eric-c-cyr** [comment]
Or is this in parallel?

**Comment by bathmatt** [comment]
> How big is the problem you are running, I assume there are issues in serial?

the test problem 30 elements, serial

The real problem 150k elements, parallel, 

There is a bug in what I've done. still tracking that down..  but I think WorksetContainer::orientations_ is a global structure,

Trying to figure out where the local ones are really used.

**Comment by eric-c-cyr** [comment]
In BasisValues2 I suspect

**Comment by eric-c-cyr** [comment]
In BasisValues2 I suspect

**Comment by bathmatt** [comment]
> In BasisValues2 I suspect

I looked at the apply there, it takes in a copy from workset container of workset local orientations.  

```
      for(std::map<unsigned,Workset>::iterator itr=worksets.begin(); 
          itr!=worksets.end();++itr) { 
                // break out of the workset loop
        if(itr->second.num_cells<=0) continue;
        
        for(std::size_t j=0;j<itr->second.numDetails();j++) {  
          WorksetDetails & details = itr->second(j);
  
          ortsPerBlock.clear();
          for (int k=0;k<itr->second.num_cells;++k) {
            ortsPerBlock.push_back((*orientations_)[details.cell_local_ids[k]]);
          }
  
          for(const auto & id : needs.getIntegrators()) {
            // apply orientations for this basis
            details.getBasisValues(bd,id).applyOrientations(ortsPerBlock);
          }
        }
      }
    } // end for w

```

Then it passes that after a couple more copies into intrepid, 

```
        ots::modifyBasisByOrientation(drv_grad_basis, 
                                      drv_grad_basis_tmp, 
                                      drv_orts,
                                      intrepid_basis);
```

**Comment by bathmatt** [comment]
Please ignore the previous changes, I just force pushed something that fixes it and I understand why it was broken so the fix I trust.

**Comment by eric-c-cyr** [comment]
That seems pretty straight forward. Thanks for finding it.

**Pull request merged**
