### PR TITLE
Xpetra&MueLu: Stop warnings about unused short names

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/xpetra @trilinos/muelu 

## Motivation
Silence warnings about unused short names. Requires C++17, so cannot merge yet.

### CODE REVIEW

**Comment by jhux2** [comment]
Oh, that'll be nice!

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by csiefer2** [comment]
How did you even find out that feature exists?

**Review by GrahamBenHarper — APPROVED** [review]
How standard is this? Is this going to break some obscure compiler?

**Comment by lucbv** [comment]
@GrahamBenHarper Trilinos will start requiring c++17 very soon so it better means it supports it too: https://en.cppreference.com/w/cpp/language/attributes

**Comment by csiefer2** [comment]
It is in the C++17 standard, which we do require full support for...

**Pull request merged**
