### PR TITLE
Intrepid2: increase max orders for basis, cubature

### PR DESCRIPTION
**Pull request by CamelliaDPG**
This PR increases the maximum polynomial order for bases from 10 to 20, and the maximum cubature (quadrature) order on edges from 20 to 61.  Where necessary, tests which iterate over these orders have been modified to avoid too much increase in expense, with the goal of testing the additional high-order support while maintaining previous testing intensity/coverage at the lower orders.  Similarly, some tolerances have been loosened, but we aim to maintain the prior tolerances for the lower orders, and use looser tolerances for newly supported orders.

## Testing
The changes are well-covered by existing tests.

@trilinos/intrepid2

### CODE REVIEW

**Review by mperego — APPROVED** [review]
It looks good to me. Thanks!

**Comment by mperego** [comment]
@CamelliaDPG the failing test will be replaced by my PR, so don't spend much time on it.

**Comment by CamelliaDPG** [comment]
> @CamelliaDPG the failing test will be replaced by my PR, so don't spend much time on it.

Good to know.  I'll let this one run and see what I see (make sure nothing surprising is happening), but assuming it looks OK I'll probably just revise this to test the orders it was testing before, at which point it will almost certainly pass.

There were one or two integration tests that timed out under CUDA.  The implementation of the test utility `computeIntegralOfMonomial()` was quite inefficient (summing one point at a time on host, using subviews), so I've revised this to run on device.  I've now changed over all the tests, I think, so they're not calling that version anymore.  When I switched to using the new version (and going through my `allocate()` methods for cubature) for the pyramid, I found a substantial issue there with the subclassing of CubatureTensor.  I'm now wondering/hoping that this same error might be behind some of the failures I saw related to projection in the H(curl) pyramid implementation which stopped me from doing my final hierarchical pyramid basis merge.  (Probably not, given what I remember, but *maybe*.)

Anyway, I have now, I think, fixed that, and I'll push all those changes after the current autotester run finishes.

**Comment by CamelliaDPG** [comment]
@trilinos/muelu We are increasing the maximum polynomial order supported by Intrepid2 from 10 to 20.  When we do this, a couple of tests within `IntrepidPCoarsenFactory.cpp` fail: `GenerateRepresentativeBasisNodes_LINE_Equispaced` and `GenerateRepresentativeBasisNodes_QUAD_Equispaced`.  The output is

```
ERROR: GenerateRepresentativeBasisNodes: No candidates found!
```

Digging into why,  in `GenerateRepresentativeBasisNodes()` in `MueLu_IntrepidPCoarsenFactory_def.hpp` we have the following:

```
  for (size_t i = 0; i < numFieldsLo; i++) {
    // 1st pass: find the max value
    typename Teuchos::ScalarTraits<SC>::magnitudeType vmax = Teuchos::ScalarTraits<typename Teuchos::ScalarTraits<SC>::magnitudeType>::zero();
    for (size_t j = 0; j < numFieldsHi; j++)
      vmax = std::max(vmax, Teuchos::ScalarTraits<SC>::magnitude(LoValues_host(i, j)));

    // 2nd pass: Find all values w/i threshhold of target
    for (size_t j = 0; j < numFieldsHi; j++) {
      if (Teuchos::ScalarTraits<SC>::magnitude(vmax - LoValues_host(i, j)) < threshold * vmax)
        representative_node_candidates[i].push_back(j);
    }
  }

  // Sanity check
  for (size_t i = 0; i < numFieldsLo; i++)
    if (!representative_node_candidates[i].size())
    {
      throw std::runtime_error("ERROR: GenerateRepresentativeBasisNodes: No candidates found!");
    }
```

What this is doing is computing the low-order basis at each of the high-order basis's dofCoords, and finding the maximum-magnitude value.  It then fills the "candidates" list with any dofs that are within a threshold of that maximum magnitude.  But the second comparison (in the "2nd pass" for loop) is a signed comparison, so if the maximum-magnitude value is negative, then you need to have some other low-order dof that gets close to it with a positive value in order to have any candidates.

When we run this on a line with high-order of 10 and low-order of 7, the maximum-magnitude for `i=2` is a value of `-0.95`, and evaluating the `i=2` basis function at the other high-order nodes does not come close enough to this value, so the test fails.

For the moment, I have made these tests just run up to the old maximum order of testing (which was 9; the for loop for poly order uses `<` rather than `<=` for the comparison), so locally at least they pass.  But reading the code I'm wondering whether the "2nd pass" for loop comparison should instead be an unsigned comparison; the way it's written it seems like you are not guaranteed to have candidates for all basis combinations, as demonstrated by the new test cases.

Notably, the `QUAD_Spectral` variant of the test passed for orders up to 19.

**Comment by CamelliaDPG** [comment]
> @trilinos/muelu We are increasing the maximum polynomial order supported by Intrepid2 from 10 to 20. When we do this, a couple of tests within `IntrepidPCoarsenFactory.cpp` fail: `GenerateRepresentativeBasisNodes_LINE_Equispaced` and `GenerateRepresentativeBasisNodes_QUAD_Equispaced`. The output is
> 
> ```
> ERROR: GenerateRepresentativeBasisNodes: No candidates found!
> ```
> 
> Digging into why, in `GenerateRepresentativeBasisNodes()` in `MueLu_IntrepidPCoarsenFactory_def.hpp` we have the following:
> 
> ```
>   for (size_t i = 0; i < numFieldsLo; i++) {
>     // 1st pass: find the max value
>     typename Teuchos::ScalarTraits<SC>::magnitudeType vmax = Teuchos::ScalarTraits<typename Teuchos::ScalarTraits<SC>::magnitudeType>::zero();
>     for (size_t j = 0; j < numFieldsHi; j++)
>       vmax = std::max(vmax, Teuchos::ScalarTraits<SC>::magnitude(LoValues_host(i, j)));
> 
>     // 2nd pass: Find all values w/i threshhold of target
>     for (size_t j = 0; j < numFieldsHi; j++) {
>       if (Teuchos::ScalarTraits<SC>::magnitude(vmax - LoValues_host(i, j)) < threshold * vmax)
>         representative_node_candidates[i].push_back(j);
>     }
>   }
> 
>   // Sanity check
>   for (size_t i = 0; i < numFieldsLo; i++)
>     if (!representative_node_candidates[i].size())
>     {
>       throw std::runtime_error("ERROR: GenerateRepresentativeBasisNodes: No candidates found!");
>     }
> ```
> 
> What this is doing is computing the low-order basis at each of the high-order basis's dofCoords, and finding the maximum-magnitude value. It then fills the "candidates" list with any dofs that are within a threshold of that maximum magnitude. But the second comparison (in the "2nd pass" for loop) is a signed comparison, so if the maximum-magnitude value is negative, then you need to have some other low-order dof that gets close to it with a positive value in order to have any candidates.
> 
> When we run this on a line with high-order of 10 and low-order of 7, the maximum-magnitude for `i=2` is a value of `-0.95`, and evaluating the `i=2` basis function at the other high-order nodes does not come close enough to this value, so the test fails.
> 
> For the moment, I have made these tests just run up to the old maximum order of testing (which was 9; the for loop for poly order uses `<` rather than `<=` for the comparison), so locally at least they pass. But reading the code I'm wondering whether the "2nd pass" for loop comparison should instead be an unsigned comparison; the way it's written it seems like you are not guaranteed to have candidates for all basis combinations, as demonstrated by the new test cases.
> 
> Notably, the `QUAD_Spectral` variant of the test passed for orders up to 19.

@jhux2 @csiefer2 Could one of you take a look at this when you have a chance?  The most salient question for the present PR is whether it's OK to limit testing in `IntrepidPCoarsenFactory.cpp` to 9th order (as it has been tested previously) for now, even though Intrepid2 now supports up to 20th order.  But I would also be glad for you to think about the quoted code and whether the discrepancy between the "1st pass" and "2nd pass" should be resolved, so that we can test higher orders at least in 1D.

**Review by jhux2 — APPROVED** [review]
@CamelliaDPG The change to MueLu is ok with me.  I agree that getting the test to pass for the more general cases would be good, but that could be in a later PR.

**Pull request merged**
