### PR TITLE
Tpetra: fix typo in test instantiation

### PR DESCRIPTION
**Pull request by brian-kelley**
Replace TEUCHOS_UNIT_TEST_TEMPLATE_4_DECL with TEUCHOS_UNIT_TEST_TEMPLATE_4_INSTANT
at the bottom of Vector_offsetViewCtor.cpp. the ...DECL macro is already called for this test above, at the bottom it needs to be instantiated with the ...INSTANT macro. Note that this file is not actually compiled (@mhoemmen had commented out it in CMakeLists.txt) but it's tripping up the automatic LO/GO removal script.

@trilinos/tpetra 

## Motivation

Just allows the LO removal script to run on this file. It doesn't change any behavior or affect testing, since this file is never compiled.

### CODE REVIEW

**Comment by brian-kelley** [comment]
I did try uncommenting the build of this test in CMakeLists, but there are other build errors. At some point we should either fix this file or just delete it.

**Review by tasmith4 — APPROVED** [review]

**Comment by tasmith4** [comment]
@brian-kelley if one doesn't exist already, can you create a bug report to document that we need to circle back and fix this file or delete it?

**Comment by brian-kelley** [comment]
Also opened #8309 to deal with this file

**Comment by mhoemmen** [comment]
Dang, y'all still working on this?

**Pull request merged**
