### PR TITLE
Switch from Pascal60 to Volta70 for 'sems-rhel7' supported builds (TRIL-255)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @fryeguy52 

The machines 'ascicgpu14' and 'ascicgpu15' have Volta GPUs.  This seems to avoid some test failures we were seeing (see [TRIL-264](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-264)).

I tested this on 'ascicgpu15' with:

```
$ ./checkin-test-atdm.sh sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug \
  --enable-packages=KokkosKernels,Tpetra --local-do-all --wipe-clean
```

and it gave passing tests:

```
  Pull: Not Performed
  Configure: Passed (0.67 min)
  Build: Passed (27.65 min)
  Test: Passed (11.26 min)
  
  100% tests passed, 0 tests failed out of 208
  
  Subproject Time Summary:
  KokkosKernels    = 496.45 sec*proc (8 tests)
  Tpetra           = 5271.99 sec*proc (200 tests)
  
  Total Test time (real) = 675.82 sec
  
  Total time for sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug = 39.59 min
```

A few KokkosKernels and Tpetra tests were shown failing [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlyfailed&buildid=4673753) so this would seem to be improvement.

So still very long run-times but at least everything passed!

### CODE REVIEW

**Comment by jmgate** [comment]
It would have been nice to stage some deprecation period for Pascal60.  Since this is already merged, it will cause failures in our testing because we need to change our Pascal60 jobs to Volta70.  It'd be real nice to coordinate backwards compatibility breaks like this with the EMPIRE team.

**Comment by bartlettroscoe** [comment]
@jmgate said:

> It would have been nice to stage some deprecation period for Pascal60. Since this is already merged, it will cause failures in our testing because we need to change our Pascal60 jobs to Volta70. It'd be real nice to coordinate backwards compatibility breaks like this with the EMPIRE team.

Actually, it is okay.  No backward compatibility was broken here.  You can see that there is no default `KOKKOS_ARCH` for the 'sems-rhel7' env:

```
$ cd Trilinos/
$ find cmake/std/atdm/sems-rhel7/ -type f -exec grep -nH KOKKOS_ARCH {} \;
cmake/std/atdm/sems-rhel7/environment.sh:76:# Allow KOKKOS_ARCH which is needed for CUDA builds
cmake/std/atdm/sems-rhel7/environment.sh:79:if [ "$ATDM_CONFIG_KOKKOS_ARCH" == "DEFAULT" ] ; then
cmake/std/atdm/sems-rhel7/environment.sh:80:  unset ATDM_CONFIG_KOKKOS_ARCH
```

The only place that 'Volta70' is listed is in the list of known tested builds:

```
$ find cmake/std/atdm/sems-rhel7/ -type f -exec grep -nH Volta {} \;
cmake/std/atdm/sems-rhel7/all_supported_builds.sh:6:  sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug
cmake/std/atdm/sems-rhel7/all_supported_builds.sh:7:  sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug
```

So the assumption is that if you use [`./checking-test-atdm.sh all [other options]`](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ctest-s-local-test-driversh) or [.`/test-s-local-test-driver.sh all`](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ctest-s-local-test-driversh), then you need to be on a machine with a Volta70 GPU.  But it is just as easy explicitly list the builds you want to run with these tools.

Does that make sense?

**Comment by jmgate** [comment]
Ah, my mistake. I misread the diff to say that Pascal60 was no longer a supported node type, so if you tried to set up a RHEL7 environment with Pascal60 you'd get an error. Sorry for the misunderstanding. I was also in a poor mindset this morning due to things going on outside of work.

On Mar 8, 2019, at 9:13 AM, Roscoe A. Bartlett <notifications@github.com<mailto:notifications@github.com>> wrote:


@jmgate<https://github.com/jmgate> said:

It would have been nice to stage some deprecation period for Pascal60. Since this is already merged, it will cause failures in our testing because we need to change our Pascal60 jobs to Volta70. It'd be real nice to coordinate backwards compatibility breaks like this with the EMPIRE team.

Actually, it is okay. No backward compatibility was broken here. You can see that there is no default KOKKOS_ARCH for the 'sems-rhel7' env:

$ cd Trilinos/
$ find cmake/std/atdm/sems-rhel7/ -type f -exec grep -nH KOKKOS_ARCH {} \;
cmake/std/atdm/sems-rhel7/environment.sh:76:# Allow KOKKOS_ARCH which is needed for CUDA builds
cmake/std/atdm/sems-rhel7/environment.sh:79:if [ "$ATDM_CONFIG_KOKKOS_ARCH" == "DEFAULT" ] ; then
cmake/std/atdm/sems-rhel7/environment.sh:80:  unset ATDM_CONFIG_KOKKOS_ARCH


The only place that 'Volta70' is listed is in the list of known tested builds:

$ find cmake/std/atdm/sems-rhel7/ -type f -exec grep -nH Volta {} \;
cmake/std/atdm/sems-rhel7/all_supported_builds.sh:6:  sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug
cmake/std/atdm/sems-rhel7/all_supported_builds.sh:7:  sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug


So the assumption is that if you use ./checking-test-atdm.sh all [other options]<https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ctest-s-local-test-driversh> or ./test-s-local-test-driver.sh all<https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ctest-s-local-test-driversh>, then you need to be on a machine with a Volta70 GPU. But it is just as easy explicitly list the builds you want to run with these tools.

Does that make sense?

**Comment by bartlettroscoe** [comment]
@jmgate, no worries :-)

We will try very hard to not break backward compatibility or at least give a lot of notice before we do.

**Pull request merged**
