### PR TITLE
Zoltan2:  fix indexing for non-contiguous row maps in TpetraCrsColorer's bipartite symmetrization

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/zoltan2

## Motivation

In #9500, @kliegeois reported incorrect results from TpetraCrsColorer when using matrices in non-contiguous row maps.
This PR fixes the problem.

The bipartite symmetrization used the number of global entries in the row map as the first index of the column vertices.  However, for a non-contiguous map with the largest index greater than the global number of entries, the number of global entries is incorrect.  Using the maximum global ID instead solves the problem, at least for the new test Bug9500.cpp.

#9500 

## Stakeholder Feedback

@kliegeois 

## Testing

New test added:  Bug9500.cpp -- builds row maps with GIDs that are multiples of a specified "multiple"; does coloring for matrices with contiguous (multiple=1) and non-contiguous (multiple=2, 5) row maps.  
Test failed for multiple > 1; this PR allows the test to run with all multiples.
Run on ascicgpu with SEMS modules (serial node, CPU only)

### CODE REVIEW

**Review by egboman — APPROVED** [review]
Good catch. Thanks, @kddevin !

**Review by rsivascience — APPROVED** [review]
Thanks @kddevin !

**Review by srajama1 — APPROVED** [review]
Approving with right github account.

**Review by egboman — APPROVED** [review]
Approving again. Thanks, @kddevin !

**Pull request merged**
