### PR TITLE
Zoltan2 input traits

### PR DESCRIPTION
**Pull request by MicheldeMessieres**
This update adds type checking for the Zoltan2 InputTraits classes.

Compile errors will be generated for using incorrect types.
Two units tests have been added to confirm good and bad type checking.

Some initial setup for Jenkins testing has been added but that is currently in progress.

### CODE REVIEW

**Comment by bmpersc** [comment]
We will not want to add TrilinosCTestDriverCore.generic.jenkins.cmake to the repository, as the changes should be applied to the existing prototype file instead. We will need to do that, so changes to that file should be removed from the pull request before applying it.

I'm unclear on the purpose of the conditional IF( DEFINED CTEST_BINARY_DIRECTORY ). What is this doing exactly?

We should not be removing boost, but adding parmetis and scotch should be done. However, I'm not sure where the env vars SEMS_PARMETIS_LIBRARY_NAMES and SEMS_SCOTCH_LIBRARY_NAMES are coming from. These do not exist in the SEMS modules. Was this how you were working around the GKLib issue that you ran into?

Also why are you setting the mpi compilers directly? Were there issues with the MPI_BASE_DIR not finding them for you?

In the ctest_linux_nightly_jenkins_zoltan2.cmake file there are several calls to a runtest macro that seem to be testing different configurations in this single file. This is not they way that we want to test multiple configurations. These files, should be defining how to run a single job. To achieve multiple configurations we would have separate jobs that all use a single ctest file that pulls in the values which change through a mechanism such as jenkins parameters.

**Comment by MicheldeMessieres** [comment]
This question is about Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES.
 
The cdash system has some internal settings to set Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES on.

Is Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES required to be on for all cdash testing?
It does not seem possible to set this off in the configuration without creating build issues. 

We had tried this because it seemed more sensible to turn on the packages we wanted to test rather than start with everything on and then turning off the ones we don't want to test. Thanks.

**Comment by kddevin** [comment]
@MicheldeMessieres How much additional stuff gets build with Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES?  Is it just the packages that Zoltan2 lists as OPTIONAL, or does it propagate to include optional packages of our package dependencies? 

If it is the former, we can disable the optional packages manually, as there aren't many.
If it is the latter, I agree with you, then; it would be better to specify Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF, as we don't want our tests to change if one of our dependencies changes its dependencies.
@bmpersc @jwillenbring Can you advise regarding the defaults for Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES?

@MicheldeMessieres Also, what build issues do you see when you manually disable Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES?

**Comment by MicheldeMessieres** [comment]
For one test we had optional packages off, epetra on, parmetis on, scotch on.
Config log gives enabled packages: Kokkos Teuchos Epetra Zoltan Tpetra Xpetra Zoltan2

This was the build error:
/Users/micheldemessieres/Documents/trilinosall-cdash/Trilinos/packages/tpetra/core/src/Epetra_TsqrMessenger.hpp:71:10: fatal error: 'Tsqr_TeuchosMessenger.hpp' file not found

Then removing the off setting for optional packages gives us:
Config log gives enabled packages: Kokkos Teuchos RTOp Epetra Zoltan Triutils Tpetra EpetraExt Thyra Xpetra Galeri Pamgen Zoltan2

Which builds and runs Zoltan2 tests.

I will send the full logs in a moment.

**Comment by kddevin** [comment]
Thank you for these details.  To me, this looks like an error in the required dependencies of one of the packages, rather than an error with Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES.  I will take a quick look this afternoon.  To build Zoltan2, one should not also need Thyrs, RTOp, Triutils, or EpetraExt.

**Comment by MicheldeMessieres** [comment]
I've created a new issue #562 with more information about what I think is going on with this setting.

**Comment by MicheldeMessieres** [comment]
Closing this pull request as this effort will be split into two branches - I'll reopen them as they are ready.

**Pull request closed without merging**
