### PR TITLE
Removes stk_classic from the Trilinos repository

### LINKED ISSUE #3444: STK:  Removal of STKClassic (stk_classic) from Trilinos and STK
@trilinos/stk @trilinos/framework 

## Expectations

Soon we will remove STKClassic (a.k.a. stk_classic) from the STK and Trilinos repos.
Users who depend on STKClassic should respond to this issue ASAP with questions and concerns.  Thanks!

## Motivation and Context

STKClassic is no longer supported; it has been replaced by the superior capabilities in STK. 
Current STKClassic users can migrate to STK capabilities.

Removing unsupported, obsolete code is necessary to maintain the Trilinos code base.

## Definition of Done

Code and build options removed from Trilinos and STK code bases.
Remove unbuilt/untested trilinoscouplings/examples/example_Poisson_stkclassic.cpp
Remove ifdef-ed out stk_classic code from trilinoscouplings/examples/example_Poisson_stk.cpp
STK/Trilinos integration and tests complete.

### PR DESCRIPTION
**Pull request by prwolfe**
This will close #3444 as stk_classic is not longer supported.

@trilinos/stk 

* Closes #3444

### CODE REVIEW

**Comment by kddevin** [comment]
Hi, @prwolfe 
Thanks for doing this work.  Please do not merge yet, though.  I just heard from @rhoope that they are using stk_classic.  They will look at upgrading, but may need some time.  Let me talk with him to determine a timeframe that works.
Thanks again!

**Comment by prwolfe** [comment]
@kddevin No problem. I was thinking something like that might happen.

**Comment by prwolfe** [comment]
@kddevin - the build is showing a lot more that needs removed, particularly in trilinoscouplings. I won't likely have time to resolve this until Monday.

**Comment by kddevin** [comment]
Thanks, @prwolfe   
I looked at trilinoscouplings last week and put some notes in #3444 “Definition of Done.”  The stk_classic  code in trilinoscouplings is not really built, so it should be easy to remove.

**Comment by kddevin** [comment]
@prwolfe I got the go-ahead from @rhoope and I have not heard from anyone else regarding stk_classic usage.  Thus, I will remove the WIP tag and let this PR automerge.

**Comment by prwolfe** [comment]
I missed all the fireworks. Thanks @kddevin!

**Pull request merged**
