### PR TITLE
C++14 build fixes for Sierra

### PR DESCRIPTION
**Pull request by vbrunini**
@trilinos/tpetra @trilinos/ifpack2 @trilinos/tacho

## Motivation
These changes fix compiler errors when enabling -std=c++14 with Intel 19 and nvcc.

### CODE REVIEW

**Comment by vbrunini** [comment]
The lambda capture ones are definitely a compiler bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83204). I'll go through and add comments for those.

The added specialization for Tpetra::withLocalAccess I'm less clear on whether it is a compiler bug or actual language spec issue.

**Comment by kddevin** [comment]
@vbrunini Thank you!  
For the ASC SQ assessors:  can you please add a short comment on how you tested?  Thanks.

**Comment by crtrott** [comment]
Looks good to me. The capture clause things are a clear compiler bug, but the workaround is reasonably harmless. The intel 19 specialization issue is weirder, but if it passes everything I think this is good enough.

**Comment by vbrunini** [comment]
> @vbrunini Thank you!
> For the ASC SQ assessors: can you please add a short comment on how you tested? Thanks.

Built & tested intel-19 and cuda-10/gcc-7.2 builds with C++14 enabled locally. Beyond that I'm relying on the PR testing process.

**Comment by kddevin** [comment]
Thanks, @vbrunini 
Merging now.

**Comment by crtrott** [comment]
we may wanna switch at least one of the CUDA builds to C++14 in the PR testing

**Pull request merged**
