### PR TITLE
ifpack2: fix ambiguous MDF unit test

### PR DESCRIPTION
**Pull request by tmranse**
Fixes issue with ambiguous MDF unit with multiple valid permutations so that it is not sensitive to locale (order of operations, etc).

@trilinos/ifpack2

### CODE REVIEW

**Comment by tmranse** [comment]
@ndellingwood @lucbv this PR (along with https://github.com/kokkos/kokkos-kernels/pull/1916) should address https://github.com/kokkos/kokkos-kernels/issues/1901

**Review by ndellingwood — COMMENTED** [review]
@tmranse thanks for the work on this! Changes look reasonable, but just to clarify are these independent of https://github.com/kokkos/kokkos-kernels/pull/1916 ? If not, there will need to be some Kokkos version if-guards to preserve the behavior compatible with Trilinos develop branch

**Comment by tmranse** [comment]
@ndellingwood correct neither change should be affected by the version of the other, they're just two issues that contributed to the failure. So I think we're of with if-guards here.

**Review by ndellingwood — APPROVED** [review]

**Comment by ndellingwood** [comment]
Failures in the gnu/8.3.0 and clang/11.0.1 builds, here are output snips:

[Ifpack2_MDF](https://trilinos-cdash.sandia.gov/test/31159530)
```
2. Ifpack2MDF_double_int_longlong_Test2_UnitTest ... 
 Test that code {prec.setParameters(params);} does not throw : passed
 Comparing prec.getReversePermutations() == refPermuations ... 
 Error, prec.getReversePermutations()[0] = 1 == refPermuations[0] = 5: failed!
 
 Error, prec.getReversePermutations()[6] = 5 == refPermuations[6] = 3: failed!
 
 Error, prec.getReversePermutations()[7] = 3 == refPermuations[7] = 0: failed!
 
 Error, prec.getReversePermutations()[8] = 0 == refPermuations[8] = 1: failed!
 Comparing prec.getPermutations() == refPermuationsInv ... 
 Error, prec.getPermutations()[0] = 8 == refPermuationsInv[0] = 7: failed!
 
 Error, prec.getPermutations()[1] = 0 == refPermuationsInv[1] = 8: failed!
 
 Error, prec.getPermutations()[3] = 7 == refPermuationsInv[3] = 6: failed!
 
 Error, prec.getPermutations()[5] = 6 == refPermuationsInv[5] = 0: failed!
 
 p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  ../Trilinos/packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp:725:
  
  Throw number = 1
  
  Throw test that evaluated to true: (A_crs_->getLocalNumRows() > 0 && this->uplo_ == "N")
  
  Ifpack2::LocalSparseTriangularSolver<Tpetra::RowMatrix<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::localTriangularSolve: The matrix is neither upper triangular or lower triangular.  You may only call this method if the matrix is triangular.  Remember that this is a local (per MPI process) property, and that Tpetra only knows how to do a local (per process) triangular solve.
 [FAILED]  (0.000986 sec) Ifpack2MDF_double_int_longlong_Test2_UnitTest
 Location: ../Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestMDF.cpp:294
```

[Ifpack2_unit_tests](https://trilinos-cdash.sandia.gov/test/31159528)
```
...
p=0 | 35. Ifpack2MDF_double_int_longlong_Test1_UnitTest ... [Passed] (0.00219 sec)
p=0 | 36. Ifpack2MDF_double_int_longlong_Test2_UnitTest ... 
p=0 |  Test that code {prec.setParameters(params);} does not throw : passed
p=0 |  Comparing prec.getReversePermutations() == refPermuations ... 
p=0 |  Error, prec.getReversePermutations()[0] = 1 == refPermuations[0] = 5: failed!
p=0 |  
p=0 |  Error, prec.getReversePermutations()[6] = 5 == refPermuations[6] = 3: failed!
p=0 |  
p=0 |  Error, prec.getReversePermutations()[7] = 3 == refPermuations[7] = 0: failed!
p=0 |  
p=0 |  Error, prec.getReversePermutations()[8] = 0 == refPermuations[8] = 1: failed!
p=0 |  Comparing prec.getPermutations() == refPermuationsInv ... 
p=0 |  Error, prec.getPermutations()[0] = 8 == refPermuationsInv[0] = 7: failed!
p=0 |  
p=0 |  Error, prec.getPermutations()[1] = 0 == refPermuationsInv[1] = 8: failed!
p=0 |  
p=0 |  Error, prec.getPermutations()[3] = 7 == refPermuationsInv[3] = 6: failed!
p=0 |  
p=0 |  Error, prec.getPermutations()[5] = 6 == refPermuationsInv[5] = 0: failed!
p=0 |  
p=0 |  p=0: *** Caught standard std::exception of type 'std::runtime_error' :
p=0 |  
p=0 |   ../Trilinos/packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp:725:
p=0 |   
p=0 |   Throw number = 3
p=0 |   
p=0 |   Throw test that evaluated to true: (A_crs_->getLocalNumRows() > 0 && this->uplo_ == "N")
p=0 |   
p=0 |   Ifpack2::LocalSparseTriangularSolver<Tpetra::RowMatrix<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::localTriangularSolve: The matrix is neither upper triangular or lower triangular.  You may only call this method if the matrix is triangular.  Remember that this is a local (per MPI process) property, and that Tpetra only knows how to do a local (per process) triangular solve.
p=0 |  [FAILED]  (0.000795 sec) Ifpack2MDF_double_int_longlong_Test2_UnitTest
p=0 |  Location: ../Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestMDF.cpp:294
...
```

**Comment by tmranse** [comment]
> Failures in the gnu/8.3.0 and clang/11.0.1 builds, here are output snips:

@lucbv The root issue happening here is that the old version of this Trilinos test has identical discarded fill in all rows on the first iteration, but in floating points they might be slightly different and our tie breakers aren't applied. This change fixes the test to avoid that issue, but now hits the initialization issue fixed in https://github.com/kokkos/kokkos-kernels/pull/1916 . 

@ndellingwood The KK change is definitely a bug fix so I'm not sure I want to if-guard back to the old wrong behavior in Trilinos. I also don't want to reconfigure the test to pass by avoiding that bug because I want it covered in the future. I think its perhaps better to just keep this test disabled in Trilinos until the next Kokkos Kernels integration in Trilinos. 

Do either of you have thoughts?

**Comment by ndellingwood** [comment]
@tmranse I think once https://github.com/kokkos/kokkos-kernels/pull/1916 makes it through CI and merges it can be cherry-picked to this PR as an emergency bug-fix to Trilinos (this differs from our usual convention of merging kokkos-kernels changes primarily with release snapshots, but emergency bug fixes can merit this). @lucbv are you okay with this plan, or would you prefer to have the ifpack2 mdf tests disabled in Trilinos until the next release?

**Comment by tmranse** [comment]
FWIW I just checked and the existing test passes if I change the `==` logic to `KAS::abs(discarded_fill(src_perm) - discarded_fill(dst_perm)) <  KAS::epsilon()*10.0`

**Comment by tmranse** [comment]
@lucbv any thoughts on these options? looks like you merged https://github.com/kokkos/kokkos-kernels/pull/1916 so maybe cherrypicking is the easiest path forward?

**Comment by ndellingwood** [comment]
@tmranse if you don't mind, please go ahead and cherry-pick https://github.com/kokkos/kokkos-kernels/pull/1916 to the PR. I will review after the cherry-pick to ensure no files are clobbered with other bug-fixes merged to Trilinos

**Comment by lucbv** [comment]
Thanks @ndellingwood and @tmranse for this PR and sorry for the slow response, I created #12140 to cherry pick the changes from Kokkos Kernels. I am hoping this won't take long to merge with Trilinos and we should be able to rebase and retest this one?

**Comment by ndellingwood** [comment]
Thanks @lucbv !

**Comment by tmranse** [comment]
@ndellingwood @lucbv looks like https://github.com/trilinos/Trilinos/pull/12140 on its own has the same problem of being sensitive to the ambiguous test. cherrypicked here so the changes can go through together

**Comment by lucbv** [comment]
Thanks @tmranse in that case I will wait to see how testing goes here and we might just close the other PR if that happens.

**Review by lucbv — APPROVED** [review]
Looks fine to me

**Pull request merged**
