### PR TITLE
Fix valgrind errors for ifpack2 tests

### LINKED ISSUE #12379: Ifpack2 FastILU: Valgrind warnings
@trilinos/ifpack2 @jgfouca 

## Bug Report
Since some of the FastILU CMake logic was fixed (#12338) it is also run through our valgrind testing. It seems that there are a couple of warnings: https://testing.sandia.gov/cdash/viewDynamicAnalysis.php?buildid=11629407

### PR DESCRIPTION
**Pull request by jgfouca**
Fix valgrind errors coming from ifpack2. Also remove trailing whitespaces from a couple shylu headers.

@trilinos/shylu 
@trilinos/ifpack2 

## Motivation

Valgrind errors were showing up on the dashboard after some ifpack2 tests were promoted to nightly.

## Related Issues

Fixes #12379

## Testing

Ran a few tests with valgrind to confirm valgrind errors are fixed.

### CODE REVIEW

**Comment by jhux2** [comment]
@jgfouca The last round of the AT didn't post correctly.  Maybe just retest?

**Comment by jgfouca** [comment]
@jhux2 , I added the RETEST label a few hours ago. Looks like it hasn't run yet.

**Comment by cgcgcg** [comment]
@jgfouca Did you use the reproduction instructions for PR builds? Cause this looks like it's missing CuBLAS at link time.

**Comment by jgfouca** [comment]
@cgcgcg , I've never had much success reproducing cdash builds. The scripts involved always fail on the machines I try them on.

**Comment by jgfouca** [comment]
@cgcgcg , yep, they fail:

```
% source $TRILINOS_SRC/packages/framework/GenConfig/gen-config.sh --cmake-fragment gen-config.cmake rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables $TRILINOS_SRC
Using system 'rhel7' based on matching hostname 'sogpu01.sandia.gov'.
Overriding system to 'rhel7' based on specification in build name 'rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Matched environment name 'sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5' in build name 'rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Matched complete configuration 'rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables'
  for build name 'rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
* CMake fragment file written to: /home/jgfouca/Trilinos/build/gen-config.cmake

Using system 'rhel7' based on matching hostname 'sogpu01.sandia.gov'.
Overriding system to 'rhel7' based on specification in build name 'rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Matched environment name 'sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5' in build name 'rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Traceback (most recent call last):
  File "/ascldap/users/jgfouca/Trilinos/packages/framework/GenConfig/LoadEnv/load_env.py", line 547, in <module>
    main(sys.argv[1 :])
  File "/ascldap/users/jgfouca/Trilinos/packages/framework/GenConfig/LoadEnv/load_env.py", line 537, in main
    le.apply_env()
  File "/ascldap/users/jgfouca/Trilinos/packages/framework/GenConfig/LoadEnv/load_env.py", line 237, in apply_env
    rval = self.set_environment.apply(self.parsed_env_name)
  File "/ascldap/users/jgfouca/Trilinos/packages/framework/GenConfig/LoadEnv/setenvironment/SetEnvironment.py", line 323, in apply
    self.configparserenhanceddata[section]
  File "/ascldap/users/jgfouca/Trilinos/packages/framework/GenConfig/LoadEnv/configparserenhanced/ConfigParserEnhanced.py", line 1586, in __getitem__
    raise KeyError(key)
KeyError: 'rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5'
mv: cannot stat ‘*~’: No such file or directory
```

**Comment by jgfouca** [comment]
@sebrowne ^

**Comment by jgfouca** [comment]
@sebrowne , @cgcgcg , another AT run, another fail in Trilinos_PR_cuda-11.4.2-uvm-off. The cdash link again has blank columns for the gpu build.

**Comment by sebrowne** [comment]
> @sebrowne ^

Will investigate this later today assuming I have access to sogpu01.  Thanks for the reproducer!

**Comment by jgfouca** [comment]
@sebrowne , it looks like my PR got merged so it's no longer urgent. That said, this is the 3rd or 4th time I've hit this same KeyError when doing step 8 from: https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors  So I do think it's worth a look from someone on your team, thanks!

**Pull request merged**
