### PR TITLE
WIP: do not commit. Automatic snapshot commit from seacas at d7789af

### PR DESCRIPTION
**Pull request by gsjaardema**
Origin repo remote tracking branch: 'origin/master'
Origin repo remote repo URL: 'origin = https://github.com/gsjaardema/seacas'

At commit:

commit d7789af0cdfa0555fa245f9930f4723dc90e368b
Author:  Greg Sjaardema <gdsjaar@sandia.gov>
Date:    Wed Jun 19 07:57:42 2019 -0600
Summary: EPU: Enable smart assert for release builds also

* Some clang-format changes
* Run epu with SMART_ASSERT enabled even in release
* Fix some uses/conflicts of C-library functions (abs, fabs, mergesort)
* Eliminate some unused variable warnings
* Some exodus warnings were using stderr directly instead of ex_err.
* Exodus summary output uses dynamic width now
* io_shell has `add_processor_id_field` option to make easier to visualize a
  decomposition (structured and unstructured)
* refactor 'create_path' to make clearer
* update to Catch-2.9.1
* CGNS: Remove the single-file read in parallel since new CGNS-develop
  library has a faster solution (compact storage).
* CGNS: detect if not using patched CGNS library
* Fix heartbeat option to make easier to override default options.
* Refine cgns_decomp output and options.
* cleanup some old copyright info
* fix some fortran warnings

NOTE: This commit will not build until Trilinos is pointing to a patched version of the
      CGNS library.  The patch is in the SEACAS github repository TPL/CGNS/CGNS-sandia.patch
      and is applied to the current CGNS/develop version

@trilinos/seacas 

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [x] These changes break backwards compatibility.
         (Will not build with an unpatched CGNS library)

### CODE REVIEW

**Comment by gsjaardema** [comment]
Patch needed for CGNS library is at https://github.com/gsjaardema/seacas/blob/master/TPL/cgns/CGNS-sandia.patch

**Comment by bartlettroscoe** [comment]
@gsjaardema, given this requires a patch to CGNS, how do we get CGNS upgraded along with merging this commit?  If we merge to 'develop' before CGNS is patched, it will break our [SPARC Trilinos Integration testing](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/SPARC+Trilinos+Integration+Process), no?  Do we need to work with the SPARC developers on this?

**Comment by gsjaardema** [comment]
@bartlettroscoe Not sure how best to integrate this.  The patched version of CGNS will work OK with the code as it exists prior to this PR and in fact the previous code also needed the patched CGNS; I just made the build error out if not using the patched version instead of possibly hanging during execution.  So, I think the first step is to update the CGNS library used by Trilinos to be the patched version of `CGNS/develop`. `CGNS/3.4.0` will work, but doesn't scale very well (order or orders of magnitude slower at large scale).  The current code can be verified against the CGNS library and once that is verified, then the PR can be applied...

**Comment by mhoemmen** [comment]
(Wait, it looks like maybe I shouldn't have approved this)

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> (Wait, it looks like maybe I shouldn't have approved this)

I just dismissed your review.  Let's figure out what to do with CGNS before we approve this.

**Comment by bartlettroscoe** [comment]
@gsjaardema, what version of CGNS/develop should we apply this patch to?  What SHA1 for the CGNS repo should we use?

**Comment by bartlettroscoe** [comment]
CC: @sebrowne 

FYI: I created:

* https://sems-atlassian-srn.sandia.gov/browse/SPAR-574
* https://sems-atlassian-srn.sandia.gov/browse/CDOFA-50

to install this upgraded version of CGNS with this patch.

I think we need to get at least SPAR-574 done before we can merge this PR to Trilinos 'develop' or it will bring down the [SPARC Trilinos Integrations builds](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/SPARC+Trilinos+Integration+Process) (which have been very clean lately and therefore should allow SPARC to upgrade Trilinos whenever it wants to).

**Comment by gsjaardema** [comment]
@bartlettroscoe I usually always pull 'develop' without specifying SHA1, but current head of repository is b02cc3801f8e5c92c1e5d8bf735d01d67c046ed5 and I have verified that the patch applies and all my tests pass.

**Comment by sebrowne** [comment]
SPARC is in the process of upgrading HDF5, NetCDF, CGNS, and SuperLU-dist.  I've got CGNS as of 1f8a01e3, with Greg's patch, installed now, against HDF5-1.10.5 and NetCDF-4.7.0.

I'm not sure of the exact upgrade date, because we need to complete CNARS requests for all of these prior to deploying the change to the nightly builds, but it will be fairly soon.

**Comment by gsjaardema** [comment]
This is no longer needed.

**Pull request closed without merging**
