### PR TITLE
Revert "Remove Unnecessary Amesos2 dependence on Amesos"

### PR DESCRIPTION
**Pull request by krcb**
Reverts trilinos/Trilinos#918. This is a major change that needs to more review before it can be merged.

### CODE REVIEW

**Comment by srajama1** [comment]
@krcb: The message here says there are unmerged commits. Do you know how to verify ?

**Comment by krcb** [comment]
This is a PR to revert the changes from 918; I wasn't expecting these to be merged right now. As a result, I opened this PR to revert 918. The unmerged commits would be to revert 918.

**Comment by srajama1** [comment]
Got it ! Thanks !

**Comment by krcb** [comment]
PR #918 passed CI testing on 01/05/17. Closing this PR.

**Pull request closed without merging**
