### PR TITLE
Pliris Package Warnings Fixes

### PR DESCRIPTION
**Pull request by bddavid**
##### Attention:

@jwillenbring 
@trilinos/pliris 
- Removed unused variables
  - Had to separate out complex and real DIVIDE define to
    eliminate unused variable in the real case.
- Please refer to issue #66 for a detailed summary of the applied patch

Signed-off-by: bddavid davidson@txcorp.com

### CODE REVIEW

**Comment by jwillenbring** [comment]
@jdkotul I am just inquiring as to the status of this. If you can provide an update to the changes, it would be possible to get someone else to look at completing the merge if that would be better.

**Comment by jwillenbring** [comment]
@jdkotul Is there anything I could do to help get this PR resolved?

**Comment by mhoemmen** [comment]
@prwolfe @rrdrake I just found this old PR.  It might be relevant to #2276.

**Comment by prwolfe** [comment]
Nice - I will try and build this tomorrow and check it out.

Thanks!

**Comment by prwolfe** [comment]
So is pliris just abandoned in place?

**Comment by mhoemmen** [comment]
@prwolfe I'll contact you offline.

**Comment by prwolfe** [comment]
I pulled this PR and rebased it on top of master and then tested it locally with good success.  I am not sure if I should rebase and merge this since it's clean or do a new pull request so it will go through the PR testing process. What do you think?

**Pull request closed without merging**
