### PR TITLE
Kokkos + KokkosKernels Promotion To 4.2.00

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos @trilinos/kokkos-kernels 

## Motivation
Snapshot release 4.2.00 of kokkos and kokkos-kernels to Trilinos

### CODE REVIEW

**Comment by ndellingwood** [comment]
One failure in the `Trilinos_PR_intel-2021.3` build: [Ifpack2_unit_tests_MPI_4](https://trilinos-cdash.sandia.gov/test/40362252)

```
...
p=3 | 23. Ifpack2Filtering_double_int_longlong_Test0_UnitTest ... [Passed] (0.00273 sec)
p=3 | 24. Ifpack2Group0_double_Ifpack2Test0_UnitTest ... [Passed] (1.27e-05 sec)
p=3 | 25. Ifpack2Heap_double_int_Test1_UnitTest ... [Passed] (2.89e-05 sec)
p=3 | 26. Ifpack2Heap_double_int_Test3_UnitTest ... [Passed] (0.000126 sec)
p=3 | 27. Ifpack2Heap_float_int_Test1_UnitTest ... [Passed] (2.48e-05 sec)
p=3 | 28. Ifpack2Heap_float_int_Test3_UnitTest ... [Passed] (6.16e-05 sec)
||x_init||=4.47214
p=0 | 23. Ifpack2Filtering_double_int_longlong_Test0_UnitTest ... [Passed] (0.00273 sec)
p=0 | 24. Ifpack2Group0_double_Ifpack2Test0_UnitTest ... [Passed] (1.18e-05 sec)
p=0 | 25. Ifpack2Heap_double_int_Test1_UnitTest ... [Passed] (2.9e-05 sec)
p=0 | 26. Ifpack2Heap_double_int_Test3_UnitTest ... [Passed] (0.000124 sec)
p=0 | 27. Ifpack2Heap_float_int_Test1_UnitTest ... [Passed] (4.07e-05 sec)
p=0 | 28. Ifpack2Heap_float_int_Test3_UnitTest ... [Passed] (6.57e-05 sec)
||x_init||=4.47214
p=2 | 23. Ifpack2Filtering_double_int_longlong_Test0_UnitTest ... [Passed] (0.00273 sec)
p=2 | 24. Ifpack2Group0_double_Ifpack2Test0_UnitTest ... [Passed] (1.14e-05 sec)
p=2 | 25. Ifpack2Heap_double_int_Test1_UnitTest ... [Passed] (2.59e-05 sec)
p=2 | 26. Ifpack2Heap_double_int_Test3_UnitTest ... [Passed] (0.000122 sec)
p=2 | 27. Ifpack2Heap_float_int_Test1_UnitTest ... [Passed] (4.12e-05 sec)
p=2 | 28. Ifpack2Heap_float_int_Test3_UnitTest ... [Passed] (6.52e-05 sec)
||x_init||=4.47214
p=1 | 23. Ifpack2Filtering_double_int_longlong_Test0_UnitTest ... [Passed] (0.00273 sec)
p=1 | 24. Ifpack2Group0_double_Ifpack2Test0_UnitTest ... [Passed] (1.09e-05 sec)
p=1 | 25. Ifpack2Heap_double_int_Test1_UnitTest ... [Passed] (2.78e-05 sec)
p=1 | 26. Ifpack2Heap_double_int_Test3_UnitTest ... [Passed] (0.000126 sec)
p=1 | 27. Ifpack2Heap_float_int_Test1_UnitTest ... [Passed] (4.19e-05 sec)
p=1 | 28. Ifpack2Heap_float_int_Test3_UnitTest ... [Passed] (6.62e-05 sec)
||x_init||=4.47214
*** Error in `/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe': malloc(): memory corruption (fast): 0x0000000001e81190 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7f474)[0x7f2f0a776474]
/lib64/libc.so.6(+0x82bb0)[0x7f2f0a779bb0]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x7f2f0a77c78c]
/projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/lib64/libstdc++.so.6(_Znwm+0x18)[0x7f2f0af8b778]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos13RCPNodeTracer13addNewRCPNodeEPNS_7RCPNodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x7c7)[0x7f2f0c4ebdb7]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe(_ZN7Teuchos13RCPNodeHandleC1IdEEPNS_7RCPNodeEPT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESD_bNS_12ERCPStrengthE+0xbdd)[0x4a537d]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe(_ZN7Teuchos8ArrayRCPIdEC1EPdllbNS_14ERCPNodeLookupE+0x10d)[0x4a592d]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe(_ZN7Teuchos9ArrayViewIdEC1EPdlNS_14ERCPNodeLookupE+0x7ea)[0x65e6ba]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/tpetra/core/src/libtpetra.so.14(_ZNK6Tpetra11MultiVectorIdixNS_12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS3_9HostSpaceEEEE5norm2ERKNS3_4ViewIPdJS5_EEE+0x27)[0x7f2f15f70967]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe[0x5daf95]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZNK7Teuchos12UnitTestBase11runUnitTestERNS_18basic_FancyOStreamIcSt11char_traitsIcEEE+0x1c)[0x7f2f0c513a1c]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos18UnitTestRepository15runUnitTestImplERKNS_12UnitTestBaseERNS_18basic_FancyOStreamIcSt11char_traitsIcEEE+0x19)[0x7f2f0c51a659]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos18UnitTestRepository12runUnitTestsERNS_18basic_FancyOStreamIcSt11char_traitsIcEEE+0x167b)[0x7f2f0c51722b]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos18UnitTestRepository20runUnitTestsFromMainEiPPc+0x1c6)[0x7f2f0c514d26]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe[0x47b0fb]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f2f0a719555]
/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe[0x47afe9]
======= Memory map: ========
00400000-00820000 r-xp 00000000 08:09 58198685                           /scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe
00a20000-00a33000 r--p 00420000 08:09 58198685                           /scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe
00a33000-00a40000 rw-p 00433000 08:09 58198685                           /scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe
00a40000-00a42000 rw-p 00000000 00:00 0 
01d2a000-01f6e000 rw-p 00000000 00:00 0                                  [heap]
7f2ef0000000-7f2ef0021000 rw-p 00000000 00:00 0 
7f2ef0021000-7f2ef4000000 ---p 00000000 00:00 0 
7f2ef8000000-7f2ef805e000 rw-p 00000000 00:00 0 
7f2ef805e000-7f2efc000000 ---p 00000000 00:00 0 
7f2efdffb000-7f2efe3fc000 rw-s 00000000 00:13 383555189                  /dev/shm/vader_segment.ascic164.53f30001.3
7f2efe3fc000-7f2efe7fd000 rw-s 00000000 00:13 383571044                  /dev/shm/vader_segment.ascic164.53f30001.2
7f2efe7fd000-7f2efebfe000 rw-s 00000000 00:13 383500288                  /dev/shm/vader_segment.ascic164.53f30001.1
7f2efebfe000-7f2efefff000 rw-s 00000000 00:13 383567968                  /dev/shm/vader_segment.ascic164.53f30001.0
7f2efefff000-7f2eff3ff000 r--s 00000000 08:05 1442033                    /tmp/ompi.ascic164.91724/pid.59940/pmix_dstor_ds21_59940/smdataseg-1408434177-0
7f2eff3ff000-7f2eff7ff000 r--s 00000000 08:05 1442003                    /tmp/ompi.ascic164.91724/pid.59940/pmix_dstor_ds21_59940/smseg-1408434177-0
7f2eff7ff000-7f2eff800000 ---p 00000000 00:00 0 
7f2eff800000-7f2f00000000 rw-p 00000000 00:00 0 
7f2f00000000-7f2f00021000 rw-p 00000000 00:00 0 
7f2f00021000-7f2f04000000 ---p 00000000 00:00 0 
7f2f0401b000-7f2f0411c000 rw-p 00000000 00:00 0 
7f2f0411c000-7f2f0411d000 ---p 00000000 00:00 0 
7f2f0411d000-7f2f0491d000 rw-p 00000000 00:00 0 
7f2f0491d000-7f2f04a6d000 r-xp 00000000 00:40 9245909053128413691        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libiconv/1.16/intel/2021.3/base/3vjzzbm/lib/libiconv.so.2.6.1
7f2f04a6d000-7f2f04c6d000 ---p 00150000 00:40 9245909053128413691        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libiconv/1.16/intel/2021.3/base/3vjzzbm/lib/libiconv.so.2.6.1
7f2f04c6d000-7f2f04c6f000 r--p 00150000 00:40 9245909053128413691        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libiconv/1.16/intel/2021.3/base/3vjzzbm/lib/libiconv.so.2.6.1
7f2f04c6f000-7f2f04c70000 rw-p 00152000 00:40 9245909053128413691        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libiconv/1.16/intel/2021.3/base/3vjzzbm/lib/libiconv.so.2.6.1
7f2f04c70000-7f2f04ca3000 r-xp 00000000 00:40 9245909053117700660        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/xz/5.2.5/intel/2021.3/base/izpjosz/lib/liblzma.so.5.2.5
7f2f04ca3000-7f2f04ea2000 ---p 00033000 00:40 9245909053117700660        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/xz/5.2.5/intel/2021.3/base/izpjosz/lib/liblzma.so.5.2.5
7f2f04ea2000-7f2f04ea3000 r--p 00032000 00:40 9245909053117700660        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/xz/5.2.5/intel/2021.3/base/izpjosz/lib/liblzma.so.5.2.5
7f2f04ea3000-7f2f04ea4000 rw-p 00033000 00:40 9245909053117700660        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/xz/5.2.5/intel/2021.3/base/izpjosz/lib/liblzma.so.5.2.5
7f2f04ea4000-7f2f05160000 r-xp 00000000 00:40 9245909053114585152        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libxml2/2.9.12/intel/2021.3/base/qp543fg/lib/libxml2.so.2.9.12
7f2f05160000-7f2f0535f000 ---p 002bc000 00:40 9245909053114585152        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libxml2/2.9.12/intel/2021.3/base/qp543fg/lib/libxml2.so.2.9.12
7f2f0535f000-7f2f05368000 r--p 002bb000 00:40 9245909053114585152        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libxml2/2.9.12/intel/2021.3/base/qp543fg/lib/libxml2.so.2.9.12
7f2f05368000-7f2f0536d000 rw-p 002c4000 00:40 9245909053114585152        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libxml2/2.9.12/intel/2021.3/base/qp543fg/lib/libxml2.so.2.9.12
7f2f0536d000-7f2f0536e000 rw-p 00000000 00:00 0 
7f2f0536e000-7f2f05378000 r-xp 00000000 00:40 9245909053122179784        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libpciaccess/0.16/intel/2021.3/base/ooh35tk/lib/libpciaccess.so.0.11.1
7f2f05378000-7f2f05578000 ---p 0000a000 00:40 9245909053122179784        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libpciaccess/0.16/intel/2021.3/base/ooh35tk/lib/libpciaccess.so.0.11.1
7f2f05578000-7f2f05579000 r--p 0000a000 00:40 9245909053122179784        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libpciaccess/0.16/intel/2021.3/base/ooh35tk/lib/libpciaccess.so.0.11.1
7f2f05579000-7f2f0557a000 rw-p 0000b000 00:40 9245909053122179784        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libpciaccess/0.16/intel/2021.3/base/ooh35tk/lib/libpciaccess.so.0.11.1
7f2f0557a000-7f2f0557c000 r-xp 00000000 00:40 9245909053122673485        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libevent/2.1.12/intel/2021.3/base/up35cqn/lib/libevent_pthreads-2.1.so.7.0.1
7f2f0557c000-7f2f0577b000 ---p 00002000 00:40 9245909053122673485        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libevent/2.1.12/intel/2021.3/base/up35cqn/lib/libevent_pthreads-2.1.so.7.0.1
7f2f0577b000-7f2f0577c000 r--p 00001000 00:40 9245909053122673485        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libevent/2.1.12/intel/2021.3/base/up35cqn/lib/libevent_pthreads-2.1.so.7.0.1
7f2f0577c000-7f2f0577d000 rw-p 00002000 00:40 9245909053122673485        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libevent/2.1.12/intel/2021.3/base/up35cqn/lib/libevent_pthreads-2.1.so.7.0.1
7f2f0577d000-7f2f057ba000 r-xp 00000000 00:40 9245909053107098448        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libevent/2.1.12/intel/2021.3/base/up35cqn/lib/libevent_core-2.1.so.7.0.1
7f2f057ba000-7f2f059b9000 ---p 0003d000 00:40 9245909053107098448        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libevent/2.1.12/intel/2021.3/base/up35cqn/lib/libevent_core-2.1.so.7.0.1
7f2f059b9000-7f2f059ba000 r--p 0003c000 00:40 9245909053107098448        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libevent/2.1.12/intel/2021.3/base/up35cqn/lib/libevent_core-2.1.so.7.0.1
7f2f059ba000-7f2f059bb000 rw-p 0003d000 00:40 9245909053107098448        /projects/sems/install/rhel7-x86_64/sems/v2/tpl/libevent/2.1.12/intel/2021.3/base/up35cqn/lib/libevent_core-2.1.so.7.0.1
7f2f059bb000-7f2f059bc000 rw-p 00000000 00:00 0 
...
```

Extracting this line reporting the actual error:
```
*** Error in `/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe': malloc(): memory corruption (fast): 0x0000000001e81190 ***
```

**Comment by ndellingwood** [comment]
I reproduced the Ifpack2 unit test failure, occurring in `Ifpack2ILUT_double_int_longlong_Test0_UnitTest`
Add options for more detailed output and tagging the output procs:


```
mpirun --tag-output --bind-to none -np 4 /ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe --globally-reduce-test-result --output-show-proc-rank --output-to-root-rank-only=-1 --show-test-details=ALL --show-fail-src-location
...
[1,1]<stdout>:p=1 | 0. Ifpack2ILUT_double_int_longlong_Test0_UnitTest ... 
[1,1]<stdout>:p=1 |  Ifpack2::Version(): Ifpack2 VOTD
[1,2]<stdout>:p=2 |  Test that code {prec.setParameters(params);} does not throw : passed
[1,2]<stdout>:p=2 |  prec_dom_map_ptr = 0xc6d7d0 == mtx_dom_map_ptr = 0xc6d7d0 : passed
[1,2]<stdout>:p=2 |  prec_rng_map_ptr = 0xc6d7d0 == mtx_rng_map_ptr = 0xc6d7d0 : passed
[1,1]<stdout>:p=1 |  Test that code {prec.setParameters(params);} does not throw : passed
[1,1]<stdout>:p=1 |  prec_dom_map_ptr = 0x11877a0 == mtx_dom_map_ptr = 0x11877a0 : passed
[1,1]<stdout>:p=1 |  prec_rng_map_ptr = 0x11877a0 == mtx_rng_map_ptr = 0x11877a0 : passed
[1,3]<stdout>:p=3 |  Test that code {prec.setParameters(params);} does not throw : passed
[1,3]<stdout>:p=3 |  prec_dom_map_ptr = 0x189d6d0 == mtx_dom_map_ptr = 0x189d6d0 : passed
[1,3]<stdout>:p=3 |  prec_rng_map_ptr = 0x189d6d0 == mtx_rng_map_ptr = 0x189d6d0 : passed
[1,0]<stdout>:p=0 |  Test that code {prec.setParameters(params);} does not throw : passed
[1,0]<stdout>:p=0 |  prec_dom_map_ptr = 0x1197260 == mtx_dom_map_ptr = 0x1197260 : passed
[1,2]<stderr>:[kokkos-dev-2:208066] *** Process received signal ***
[1,2]<stderr>:[kokkos-dev-2:208066] Signal: Aborted (6)
[1,2]<stderr>:[kokkos-dev-2:208066] Signal code:  (-6)
[1,2]<stderr>:[kokkos-dev-2:208066] [ 0] [1,2]<stderr>:/lib64/libpthread.so.0(+0xf630)[0x7f6e70d03630]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 1] [1,2]<stderr>:/lib64/libc.so.6(gsignal+0x37)[0x7f6e7095c387]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 2] [1,2]<stderr>:/lib64/libc.so.6(abort+0x148)[0x7f6e7095da78]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 3] [1,2]<stderr>:/lib64/libc.so.6(+0x78f67)[0x7f6e7099ef67]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 4] [1,2]<stderr>:/lib64/libc.so.6(+0x7f474)[0x7f6e709a5474]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 5] [1,2]<stderr>:/lib64/libc.so.6(+0x82bb0)[0x7f6e709a8bb0]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 6] [1,2]<stderr>:/lib64/libc.so.6(__libc_malloc+0x4c)[0x7f6e709ab78c]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 7] [1,2]<stderr>:/projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/lib64/libstdc++.so.6(_Znwm+0x18)[0x7f6e711ba778]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 8] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/kokkos/core/src/libkokkoscore.so.14(_ZN6Kokkos6SerialC1Ev+0x2a)[0x7f6e71ec3f5a]
[1,2]<stderr>:[kokkos-dev-2:208066] [ 9] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/kokkos-kernels/libkokkoskernels.so.14(_ZNK6Kokkos4Impl11ParallelForIN10KokkosBlas4Impl15Nrm2_MV_FunctorINS_6SerialENS_4ViewIPdJNS_10LayoutLeftENS_6DeviceIS5_NS_9HostSpaceEEENS_12MemoryTraitsILj1EEEEEENS6_IPPKdJS8_SB_SD_EEEiEENS_10TeamPolicyIJS5_EEES5_E7executeEv+0x39)[0x7f6e7a67db39]
[1,2]<stderr>:[kokkos-dev-2:208066] [10] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/kokkos-kernels/libkokkoskernels.so.14(_ZN10KokkosBlas4Impl14MV_Nrm2_InvokeIN6Kokkos6SerialENS2_4ViewIPdJNS2_10LayoutLeftENS2_6DeviceIS3_NS2_9HostSpaceEEENS2_12MemoryTraitsILj1EEEEEENS4_IPPKdJS6_S9_SB_EEEiEEvRKT_RKT0_RKT1_bPNSt9enable_ifIXsr6Kokkos18SpaceAccessibilityISH_NSK_12memory_spaceEEE10accessibleEvE4typeE+0x735)[0x7f6e7a67d495]
[1,2]<stderr>:[kokkos-dev-2:208066] [11] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/kokkos-kernels/libkokkoskernels.so.14(_ZN10KokkosBlas4Impl4Nrm2IN6Kokkos6SerialENS2_4ViewIPdJNS2_10LayoutLeftENS2_6DeviceIS3_NS2_9HostSpaceEEENS2_12MemoryTraitsILj1EEEEEENS4_IPPKdJS6_S9_SB_EEELi2ELb0ELb1EE4nrm2ERKS3_RKSC_RKSG_RKb+0xbf)[0x7f6e7a67b6ff]
[1,2]<stderr>:[kokkos-dev-2:208066] [12] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/tpetra/core/src/libtpetra.so.14(_ZN10KokkosBlas12nrm2_squaredIN6Kokkos6SerialENS1_4ViewIPdJNS1_9HostSpaceEEEENS3_IPPKdJNS1_10LayoutLeftENS1_6DeviceIS2_S5_EEEEEEEvRKT_RKT0_RKT1_NSt9enable_ifIXsr6Kokkos7is_viewISH_EE5valueEiE4typeE+0x3de)[0x7f6e7c5b4dae]
[1,2]<stderr>:[kokkos-dev-2:208066] [13] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/tpetra/core/src/libtpetra.so.14(_ZN6Tpetra7Details4Impl11lclNormImplIN6Kokkos4ViewIPdJNS3_9HostSpaceEEEENS4_IPPKdJNS3_10LayoutLeftENS3_6DeviceINS3_6SerialES6_EEEEEEEvRKT_RKT0_mRKN7Teuchos9ArrayViewIKmEEbNS0_10EWhichNormE+0xb17)[0x7f6e7c5ad0b7]
[1,2]<stderr>:[kokkos-dev-2:208066] [14] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/tpetra/core/src/libtpetra.so.14(_ZN6Tpetra7Details8normImplIdN6Kokkos10LayoutLeftENS2_6DeviceINS2_6SerialENS2_9HostSpaceEEEdEEvPT2_RKNS2_4ViewIPPKT_JT0_T1_EEENS0_10EWhichNormERKN7Teuchos9ArrayViewIKmEEbbPKNSL_4CommIiEE+0x1e0)[0x7f6e7c5abd90]
[1,2]<stderr>:[kokkos-dev-2:208066] [15] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/tpetra/core/src/libtpetra.so.14(+0xac5630)[0x7f6e7c4b8630]
[1,2]<stderr>:[kokkos-dev-2:208066] [16] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/tpetra/core/src/libtpetra.so.14(_ZNK6Tpetra11MultiVectorIdixNS_12KokkosCompat23KokkosDeviceWrapperNodeIN6Kokkos6SerialENS3_9HostSpaceEEEE5norm2ERKNS3_4ViewIPdJS5_EEE+0x174)[0x7f6e7c5b7704]
[1,2]<stderr>:[kokkos-dev-2:208066] [17] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe[0x424706]
[1,2]<stderr>:[kokkos-dev-2:208066] [18] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/teuchos/core/src/libteuchoscore.so.14(_ZNK7Teuchos12UnitTestBase11runUnitTestERNS_18basic_FancyOStreamIcSt11char_traitsIcEEE+0x1c)[0x7f6e727b1c4c]
[1,2]<stderr>:[kokkos-dev-2:208066] [19] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos18UnitTestRepository15runUnitTestImplERKNS_12UnitTestBaseERNS_18basic_FancyOStreamIcSt11char_traitsIcEEE+0x19)[0x7f6e727b85e9]
[1,2]<stderr>:[kokkos-dev-2:208066] [20] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos18UnitTestRepository12runUnitTestsERNS_18basic_FancyOStreamIcSt11char_traitsIcEEE+0x16be)[0x7f6e727b52fe]
[1,2]<stderr>:[kokkos-dev-2:208066] [21] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/teuchos/core/src/libteuchoscore.so.14(_ZN7Teuchos18UnitTestRepository20runUnitTestsFromMainEiPPc+0x319)[0x7f6e727b30a9]
[1,2]<stderr>:[kokkos-dev-2:208066] [22] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe[0x41bbbb]
[1,2]<stderr>:[kokkos-dev-2:208066] [23] [1,2]<stderr>:/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f6e70948555]
[1,2]<stderr>:[kokkos-dev-2:208066] [24] [1,2]<stderr>:/ascldap/users/ndellin/Trilinos-dev/Build/SemsIntel2021_rc420/packages/ifpack2/test/unit_tests/Ifpack2_unit_tests.exe[0x41baa9]
[1,2]<stderr>:[kokkos-dev-2:208066] *** End of error message ***
--------------------------------------------------------------------------
```

**Comment by ndellingwood** [comment]
The malloc error is occuring when calling Tpetra's `norm2` at this point in the unit test: https://github.com/trilinos/Trilinos/blob/b6b853e9e7c79bb216daf262895eb5015cfa4923/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestILUT.cpp#L112
If I comment out that line and below the malloc error does not occur (breaks correctness of the test of course, but no malloc error nor signal abort)

**Comment by ndellingwood** [comment]
The executable enters this routine https://github.com/trilinos/Trilinos/blob/b6b853e9e7c79bb216daf262895eb5015cfa4923/packages/tpetra/core/src/Tpetra_Details_normImpl.hpp#L346 but does not make it out

**Comment by ndellingwood** [comment]
I think I chased down the failure in `Ifpack2ILUT_double_int_longlong_Test0_UnitTest` here is a summary:

* The `norms` Views created in the Ifpack2 unit test here https://github.com/trilinos/Trilinos/blob/b6b853e9e7c79bb216daf262895eb5015cfa4923/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestILUT.cpp#L109-L110 have size 1
* Going through the Tpetra `norm2` routine sequence, this eventually hits the Tpetra `normImpl` routine
  * The check for `numVecs` returns `2` here https://github.com/trilinos/Trilinos/blob/b6b853e9e7c79bb216daf262895eb5015cfa4923/packages/tpetra/core/src/Tpetra_Details_normImpl.hpp#L327-L329
  * An unmanaged View https://github.com/trilinos/Trilinos/blob/b6b853e9e7c79bb216daf262895eb5015cfa4923/packages/tpetra/core/src/Tpetra_Details_normImpl.hpp#L333 wraps the `norms` pointer (which is the pointer to data of the View created e.g. here https://github.com/trilinos/Trilinos/blob/b6b853e9e7c79bb216daf262895eb5015cfa4923/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestILUT.cpp#L109), but the sizes do not match - the unmanaged View is of size 2 (based on `numVecs`) whereas the `norms` points to an allocation of size 1. 
  * If I hack a change to the View to be size 2 (instead of 1) at https://github.com/trilinos/Trilinos/blob/b6b853e9e7c79bb216daf262895eb5015cfa4923/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestILUT.cpp#L109-L110 the memory corruption signal aborts go away

I'm not sure where this should be addressed, but the underlying problem seems to be a misuse of the unmanaged View (unmatched sizes between the View and underlying data). Adding @brian-kelley @jhux2 @csiefer2 @lucbv for any thoughts or guidance

**Comment by jhux2** [comment]
@ndellingwood Is the fix as simple as this?
```
Kokkos::View<STM*, Kokkos::HostSpace> norms("Initial norms",x->getNumVectors());
```

**Comment by brian-kelley** [comment]
@jhux2 I agree, that looks like the correct fix.

**Comment by ndellingwood** [comment]
@jhux2 @brian-kelley thanks, that seems to do the trick! I'll put in a separate PR for that change

**Comment by ndellingwood** [comment]
PR #12528 submitted with the Ifpack2 update

**Comment by ndellingwood** [comment]
Updated the PR:
* rebase on Trilinos develop branch to include fix from https://github.com/trilinos/Trilinos/pull/12528
* updated the Kokkos snapshot to include PRs: kokkos/kokkos#6595 and kokkos/kokkos#6600

**Comment by ndellingwood** [comment]
Cherry-picked commit f2d6484f9d5f40b27956bbfdb402472c3a3941e4 from #12541 to avoid compilation errors during retest. Git should resolve this in any case with merge back into develop

**Comment by ndellingwood** [comment]
Seems like the RETEST was applied consecutively without removing the label?
* https://github.com/trilinos/Trilinos/pull/12505#issuecomment-1816122538
* https://github.com/trilinos/Trilinos/pull/12505#issuecomment-1816124819 (start test, retest not removed)
* https://github.com/trilinos/Trilinos/pull/12505#issuecomment-1817241942 (retest label still listed)
* https://github.com/trilinos/Trilinos/pull/12505#issuecomment-1817242992 (relaunched the tests, no cdash results from previous run)

**Comment by ndellingwood** [comment]
No errors or failures reported, though it looks like the Cuda tests did not submit:  [PR-12505-test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables-2818](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=1275417&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and)

@trilinos/framework looks like this is related to #12498 ?

**Comment by ndellingwood** [comment]
@crtrott @lucbv @srajama1 the PR has passed, should be ready for review

**Comment by ndellingwood** [comment]
Cross-referencing release PRs:
* Kokkos: https://github.com/kokkos/kokkos/pull/6613
* KokkosKernels: https://github.com/kokkos/kokkos-kernels/pull/2040

**Review by lucbv — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Pull request merged**
