### PR TITLE
Kokkos promotion 3.1

### PR DESCRIPTION
**Pull request by crtrott**
This moves Kokkos and KokkosKernels to Release Version 3.1.00

### CODE REVIEW

**Comment by crtrott** [comment]
Testing Results are here: https://github.com/kokkos/kokkos/issues/2942

**Comment by crtrott** [comment]
@bartlettroscoe I am tracking down the failures, two of which are trivial and I got fixed. The last one is interesting though. In the ATDM testing scripts Kokkos_ENABLE_CUDA:BOOL=ON is correctly set in the CMAKE_CACHE.txt in the SEMS PR testing script it is not, even though the KokkosCore_config.h does have KOKKOS_ENABLE_CUDA set. Its really weird. That causes the Teptra example to fail (which assumes if you default a Kokkos::View and default a Tpetra object these are compatible [which they are not since Kokkos ends up with Cuda as default and Tpetra with Serial as default]) and I suspect also makes the Stokhos test fail since it mixes checks whether to use Cuda with Tpetra defines and Kokkos defines. I am actually surprised that so little goes wrong when Tpetra and Kokkos don't agree on the defaults!!

**Comment by bartlettroscoe** [comment]
>  In the ATDM testing scripts Kokkos_ENABLE_CUDA:BOOL=ON is correctly set in the CMAKE_CACHE.txt in the SEMS PR testing script it is not, even though the KokkosCore_config.h does have KOKKOS_ENABLE_CUDA set.

@crtrott, we may need to take a careful look at the Trilinos PR CUDA build configuration and match it up better with the ATDM Trilinos CUDA configuration.  I might even entertain having the Trilinos PR CUDA build be the ATDM CUDA build configuration on 'ride'.  I don't know how the @trilinos/framework team would feel about that but I think that might be the best path forward.  But that is not my decision to make.  Otherwise, someone needs to fix the Trilinos PR CUDA configuration that runs on 'ride'.

**Comment by crtrott** [comment]
Found it. The script wasn't updated to make the options all caps. The ATDM scripts were.

**Comment by crtrott** [comment]
OH: does the PR tester actually use the updated script from this PR? @bartlettroscoe

**Comment by bartlettroscoe** [comment]
> OH: does the PR tester actually use the updated script from this PR?

@crtrott, I think so but I am not sure.  The @trilinos/framework team would know.

**Comment by prwolfe** [comment]
> OH: does the PR tester actually use the updated script from this PR? @bartlettroscoe ([b14634b](https://github.com/trilinos/Trilinos/commit/b14634b7a470906d23cf69b425f5541faa98674f))

It should.

**Comment by crtrott** [comment]
yeah I looked at the configure file for the CUDA build and now it comes out correct.

**Comment by aprokop** [comment]
I just tried building ArborX against Trilinos/Kokkos. It failed with
```
CMake Error at CMakeLists.txt:4 (find_package):
  Could not find a configuration file for package "Kokkos" that is compatible
  with requested version "3.1".

  The following configuration files were considered but not accepted:

    /home/xap/local/opt/trilinos-kokkos/lib/cmake/Kokkos/KokkosConfig.cmake, version: unknown
```

**Comment by crtrott** [comment]
s there a way of just restarting one of the tests? It looks like the test failure was a system issue? @trilinos/framework

**Comment by crtrott** [comment]
We will merge this and fix Andreys problem separately with a hotfix.

**Comment by bartlettroscoe** [comment]
FYI: Looks like this merged triggered several ATDM Trilinos test failures and also broke the build of SPARC against Trilinos 'develop'.

**Pull request merged**
