### PR TITLE
(DO NOT MERGE) Tpetra: Fix #5117 (make TpetraCore build w/ deprecated code disabled)

### LINKED ISSUE #5117: Tpetra: CrsGraph & CrsMatrix still use deprecated enum value DynamicProfile
## Bug Report
@trilinos/tpetra 

### Description

When I disable deprecated code in Tpetra, I get the following build errors:
```
In file included from .../Trilinos/packages/tpetra/core/src/Tpetra_CrsGraph_SerialWrapperNode.cpp:52:
.../Trilinos/packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp:2582:59: error: use of undeclared identifier
      'DynamicProfile'; did you mean 'StaticProfile'?
    return rcp (new graph_type (map, maxNumEntriesPerRow, DynamicProfile, params));
                                                          ^~~~~~~~~~~~~~
                                                          StaticProfile
.../Trilinos/packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:131:5: note: 'StaticProfile' declared here
    StaticProfile
    ^
In file included from .../Trilinos/packages/tpetra/core/src/Tpetra_CrsGraph_SerialWrapperNode.cpp:54:
In file included from .../Trilinos/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp:66:
In file included from .../Trilinos/packages/tpetra/core/src/Tpetra_Import_Util2.hpp:64:
.../Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp:5039:43: error: use of undeclared identifier
      'DynamicProfile'; did you mean 'StaticProfile'?
                                          DynamicProfile, params));
                                          ^~~~~~~~~~~~~~
                                          StaticProfile
```
When I fix those and enable tests, I get the following build errors:
```
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_insertGlobalIndicesFiltered.cpp:137:16: error: no member
      named 'DynamicProfile' in namespace 'Tpetra'; did you mean 'StaticProfile'?
      {Tpetra::DynamicProfile, Tpetra::StaticProfile};
       ~~~~~~~~^~~~~~~~~~~~~~
               StaticProfile
.../Trilinos/packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:131:5: note: 'StaticProfile' declared here
    StaticProfile
    ^
...
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp:51:17: error: no member named
      'DynamicProfile' in namespace 'Tpetra'; did you mean 'StaticProfile'?
  using Tpetra::DynamicProfile;
        ~~~~~~~~^~~~~~~~~~~~~~
                StaticProfile
.../Trilinos/packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:131:5: note: 'StaticProfile' declared here
    StaticProfile
    ^
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp:143:25: error: use of undeclared identifier
      'DynamicProfile'; did you mean 'StaticProfile'?
      GRAPH graph(map,1,DynamicProfile);
                        ^~~~~~~~~~~~~~
                        StaticProfile
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp:53:17: note: 'StaticProfile' declared here
  using Tpetra::StaticProfile;
                ^
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp:459:29: error: use of undeclared identifier
      'DynamicProfile'; did you mean 'StaticProfile'?
      GRAPH graph(map,map,0,DynamicProfile);
                            ^~~~~~~~~~~~~~
                            StaticProfile
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp:53:17: note: 'StaticProfile' declared here
  using Tpetra::StaticProfile;
                ^
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp:474:29: error: use of undeclared identifier
      'DynamicProfile'; did you mean 'StaticProfile'?
      GRAPH graph(map,map,0,DynamicProfile);
                            ^~~~~~~~~~~~~~
                            StaticProfile
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp:53:17: note: 'StaticProfile' declared here
  using Tpetra::StaticProfile;
                ^
```
When I fix _those_ build errors, I get the following:
```
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests_Swap.cpp:415:15: error: no member named
      'DynamicProfile' in namespace 'Tpetra'; did you mean 'StaticProfile'?
using Tpetra::DynamicProfile;
      ~~~~~~~~^~~~~~~~~~~~~~
              StaticProfile
```
When I fix that, I get the following:
```
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_Issue601.cpp:100:52: error: no member named
      'DynamicProfile' in namespace 'Tpetra'; did you mean 'StaticProfile'?
    Tpetra::ProfileType profileTypes[] = { Tpetra::DynamicProfile, Tpetra::StaticProfile };
                                           ~~~~~~~~^~~~~~~~~~~~~~
                                                   StaticProfile
.../Trilinos/packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:131:5: note: 'StaticProfile' declared here
    StaticProfile
    ^
.../Trilinos/packages/tpetra/core/test/CrsGraph/CrsGraph_Issue601.cpp:107:39: error: no member named
      'DynamicProfile' in namespace 'Tpetra'; did you mean 'StaticProfile'?
          << ((profileType == Tpetra::DynamicProfile) ? "Dynamic" : "Static")
                              ~~~~~~~~^~~~~~~~~~~~~~
                                      StaticProfile
```
I get a few more after this in other tests in TpetraCore.

### Steps to Reproduce
1. SHA1:  2b9c4fe7efa01ce25554fb5e03af821fcf071734

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra 

## Description

Make TpetraCore build with deprecated code disabled (`Tpetra_ENABLE_DEPRECATED_CODE=OFF` and `KOKKOS_ENABLE_DEPRECATED_CODE=OFF`).  Some tests still fail in that case, but at least we can get the build working so that users can try the deprecation.

## Related Issues

* Closes #5117 
* Related to #5118

### CODE REVIEW

**Comment by mhoemmen** [comment]
Thanks @csiefer2 !  Let me see what @tjfulle and @kddevin have in mind before merging.

**Comment by tjfulle** [comment]
@kddevin and I have been working on a branch doing very similar code modifications.  @kddevin has worked on a lot of non Tpetra tests and I had fixed several Tpetra issues.  We put it on hold for a few days until I could finish up #5164.  Now that #5268 is merged, I had planned to continue on fixing broken tests with deprecated code off.  This branch will surely conflict with what we are doing.  If it is a hot-fix for another project, go ahead and merge.  If it can wait a day or two so I can get a pulse on where mine and @kddevin's efforts are at, that would be helpful.

**Comment by mhoemmen** [comment]
@tjfulle It can wait.  I just wanted to see how far I could get.

**Comment by kddevin** [comment]
Some of this work has already been done by me in tjfulle's fork, branch issue-5065, but not yet merged to Trilinos develop.
Please do not merge this branch until my work can be merged.

**Comment by mhoemmen** [comment]
#5117 is fixed now, so we can close this PR.

**Pull request closed without merging**
