### PR TITLE
fix MueLu testing

### PR DESCRIPTION
**Pull request by jhux2**
Auto-PR for SHA 73d0c05

---
This change is [Reviewable](https://reviewable.io/reviews/trilinos/trilinos/3185)

### CODE REVIEW

**Comment by jhux2** [comment]
@trilinos/framework I can't tell from the dashboard why this PR failed.

**Comment by lucbv** [comment]
@jhux2 it looks like the second round of autotester was passing, to bad you didn't merge at that point!
Hopefully the next round will pass again, the previous error looks more like a machine state error than anything code related...

**Comment by jhux2** [comment]
@trilinos/framework ping

**Comment by jhux2** [comment]
@trilinos/framework Should I just delete this PR and resubmit?

**Comment by allevin** [comment]
@jhux2 I looked at the Jenkins runs, looks like both jobs lost connection to the Jenkins server.  I am going to set the retest label and lets see what happens on the next run.

**Comment by jhux2** [comment]
Autotester is messed up.  Latest results are clean, but it appears to be hung up on the first failures.

**Pull request closed without merging**
