### PR TITLE
Amesos2 Superlu_dist-6.3 support

### PR DESCRIPTION
**Pull request by keitat**
@trilinos/Amesos2

## Motivation
The PR is intended for Issue #8062. The new SuperLU_DIST-6.3 has introduced new separated data types definitions in double and complex sparse matrix data so that these solvers can co-exist in the same application program. 

## Related Issues
None (please add!)

## Stakeholder Feedback
xSDK 0.6.0 release will have SuperLU_DIST-6.3.  To make Trilinos compatible to the xSDK 0.6.0, we need to add SuperLU_DIST-6.3. support.

## Testing
Testing needs the latest version of SuperLU_DIST(6.3 or later).  Need advice how to import the latest SuperLU_DIST. (Spack can do that, already).

 ## Additional Information
deal.II is one of the xSDK library that relies on Epetra and Amesos. This requires the change in Amesos (several additional lines) to support the latest SuerLU_DIST. I have a solution (additional source code) with Amesos.  It's up to Trilinos leadership.

### CODE REVIEW

**Comment by keitat** [comment]
@srajama1   I do not know how to apply the labels.

**Comment by cgcgcg** [comment]
@trilinos/amesos2

**Review by srajama1 — APPROVED** [review]
I am ok with these changes in principle. However, can you ensure xSDK libraries do not change interfaces in minor versions ? Isn't that part of xSDK policies ?

**Comment by keitat** [comment]
> I am ok with these changes in principle. However, can you ensure xSDK libraries do not change interfaces in minor versions ? Isn't that part of xSDK policies ?

See the discussion in #8062.  They could have done it as a major version up.

**Comment by keitat** [comment]
I am not sure how to add SuperLU_Dist-6.3 in the testing harness.  It is working with the older versions.

**Review by jwillenbring — CHANGES_REQUESTED** [review]
We need to redo this PR and reissue. I will coordinate with @keitat to do this. The contents of the PR are fine, we need to submit the PR based on develop instead of master.

**Comment by jwillenbring** [comment]
PRs #8137 and #8138 make this PR obsolete. Closing.

**Pull request closed without merging**
