### PR TITLE
MueLu: Hierarchical matrix MG

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
Add features to hierarchical matrix driver:
- binary matrix input files,
- coarse grid recompression,
- some smaller bug fixes.

### CODE REVIEW

**Review by pohm01 — APPROVED** [review]
That's a lot of files

**Comment by cgcgcg** [comment]
@pohm01 Yeah, I added a matrix reader that reads rank-local files.

**Comment by jhux2** [comment]
@cgcgcg Should those go in mueludata instead?  I can't tell how big the data is.  (That might not be the correct spelling, I forget.)

**Comment by cgcgcg** [comment]
@jhux2 There is 9 MB of data. How does mueludata work?

**Comment by jhux2** [comment]
@cgcgcg Ah, that's not much at all.  I sent you the link to the MueLu data repo.

**Comment by GrahamBenHarper** [comment]
Random ROL/Panzer failures?

**Pull request merged**
