### PR TITLE
ML: silence unused variable warnings

### PR DESCRIPTION
**Pull request by ibaned**
Since there is no @trilinos/ml, mentioning @aprokop and @bmpersc based on this file's history.

### CODE REVIEW

**Comment by ibaned** [comment]
Added a similar warning to this PR.

**Comment by ibaned** [comment]
ping?

**Comment by aprokop** [comment]
Adding more appropriate folks: @jhux2 @rstumin @csiefer2

**Comment by jhux2** [comment]
@ibaned Looks fine to me.

**Comment by ibaned** [comment]
@aprokop thanks for pointing me to the right people. I just created @trilinos/ml with those three.

@jhux2 thanks for taking a look. I'll start the checkin script to push this soon.

**Comment by aprokop** [comment]
Was this pushed/merged?

**Comment by ibaned** [comment]
whoops, good catch @aprokop .  this was pushed as 90c42e07246166946147de34f28570e2de133eb5 and cdc4f37feca59095c7447d6545e956eaa98256f1 by the checkin script.

**Pull request closed without merging**
