### PR TITLE
Phalanx: another use of space accessibility

### PR DESCRIPTION
**Pull request by rppawlo**
## Motivation

Fix another use of space accessibility

## Related Issues

* Closes `put-issue-number-here`

### CODE REVIEW

**Review by ndellingwood — CHANGES_REQUESTED** [review]
I tested the change with cuda/11.2 (UVM enabled) but ran into a segfault

```
0. PhalanxViewOfViews_ViewOfView_DefaultStreamInitialize_UnitTest ... (ptr->cuda_stream_synchronize_wrapper(stream)) error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/ndellin/trilinos/Trilinos/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:166
Backtrace:
[0x20004274a564] Kokkos::Impl::save_stacktrace()
[0x2000427184b8] Kokkos::Impl::host_abort(char const*)
[0x200042754d44] Kokkos::Impl::cuda_internal_error_abort(cudaError, char const*, char const*, int)
[0x200042756884] Kokkos::Impl::cuda_stream_synchronize(CUstream_st*, Kokkos::Impl::CudaInternal const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[0x200042756924] Kokkos::Impl::CudaInternal::fence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
[0x200042756aec] Kokkos::Cuda::fence(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
[0x10075e68] 
[0x10076594] 
[0x20004274a1e4] Kokkos::Impl::SharedAllocationRecord<void, void>::decrement(Kokkos::Impl::SharedAllocationRecord<void, void>*)
[0x10052884] 
[0x100528e0] 
[0x1003be3c] std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
[0x1003bf30] 
[0x1001ef48] 
[0x20002e017cf4] Teuchos::UnitTestBase::runUnitTest(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&) const
[0x20002e01e214] Teuchos::UnitTestRepository::runUnitTestImpl(Teuchos::UnitTestBase const&, Teuchos::basic_FancyOStream<char, std::char_traits<char> >&)
[0x20002e01f82c] Teuchos::UnitTestRepository::runUnitTests(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&)
[0x20002e020b00] Teuchos::UnitTestRepository::runUnitTestsFromMain(int, char**)
[0x20002d6a76dc] main
[0x200042cc9f5c] 
[0x200042cca0f4] __libc_start_main
Aborted (core dumped)
```

Here's the diff I retested with:
```diff
diff --git a/packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp b/packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
index 0c3e2ce2d6c..9865ddbd453 100644
--- a/packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
+++ b/packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
@@ -47,7 +47,7 @@ namespace PHX {
 
         // destroy inner views on host, outside of a parallel region
         constexpr size_t rank = Kokkos::View<D, P...>::rank();
-        static constexpr bool device_view_is_accessible_from_host = Kokkos::SpaceAccessibility<typename Kokkos::View<D, P...>::memory_space, Kokkos::HostSpace>::accessible;
+        static constexpr bool device_view_is_accessible_from_host = Kokkos::SpaceAccessibility<Kokkos::HostSpace, typename Kokkos::View<D, P...>::memory_space>::accessible;
         if (device_view_is_accessible_from_host) {
           if constexpr (rank == 0) {
             (*vov)() = {};
```

**Comment by ndellingwood** [comment]
@dalg24 helped with debugging this a bit farther, and adding a fence to the custom deleter got the test to a passing state:

```diff
diff --git a/packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp b/packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
index 0c3e2ce2d6c..4dc94a79bfc 100644
--- a/packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
+++ b/packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
@@ -39,6 +39,7 @@ namespace PHX {
       std::enable_if_t<
           Kokkos::is_view_v<typename Kokkos::View<D, P...>::value_type>>
       operator()(Kokkos::View<D, P...>* vov) const {
+        Kokkos::fence("fence before host cleanup vov");
         if (do_safety_check_) {
           if (vov->use_count() > 1) {
             Kokkos::abort("\n\n********\n ERROR - PHX::ViewOfViews - please free all instances of device Kokkos::View<View<...>> \n before deleting the host ViewOfView!\n********\n\n");
```

**Comment by ndellingwood** [comment]
@rppawlo I pushed the change mentioned above to add the fence to the custom deleter d8bb6eccba1d8107f2236be44bea82ec41b4e045, hopefully the fence label is okay?

**Comment by rppawlo** [comment]
@ndellingwood  - fence is fine! Thanks to you and @dalg24 for working on this. I still haven't got access to weaver... Can you still approve this?

**Review by ndellingwood — APPROVED** [review]

**Comment by ndellingwood** [comment]
@rppawlo looks like I could still approve, even after pushing a change to the branch 👍 
Thanks for your help working through the last couple bumps with the UVM builds!

**Pull request merged**
