### PR TITLE
Bring recent STK development into Trilinos.

### PR DESCRIPTION
**Pull request by alanw0**
Includes fixing nvidia build warnings in stk_topology.

@trilinos/<teamName>

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by alanw0** [comment]
It took me a couple tries... but now I think I'm requesting to merge the correct stk changes into the correct Trilinos branch (develop).

**Comment by mhoemmen** [comment]
@trilinos/stk

**Comment by mhoemmen** [comment]
@alanw0 looks like a STK test is failing.

**Comment by alanw0** [comment]
@mhoemmen Yes... so when I fix that stk test, do I just push a fix for that, which will allow this pull-request to continue, or do I need to start a new pull-request?

**Comment by prwolfe** [comment]
You can just push to the branch on your fork and this PR will get updated and re-run.

**Comment by alanw0** [comment]
@mhoemmen or @prwolfe I've pushed an attempted work-around, so hopefully it will go through now.

**Comment by mhoemmen** [comment]
@alanw0 should I merge this?

**Pull request merged**
