### PR TITLE
Custom system env for ATDM Trilinos configuration (#4933)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
I tested this locally on 'crf450' with:

```
$ cd ~/Trilinos.base/BUILDS/ATDM/CUSTOM_ENV/gnu-opt-openmp/

$ source ~/Trilinos.base/Trilinos/cmake/std/atdm/load-env.sh gnu-opt-openmp \
  ~/Trilinos.base/Trilinos/cmake/std/atdm/examples/my_sems_rhel6_config

$ cat do-configure
cmake \
-G Ninja \
-D Trilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
"$@" \
$HOME/Trilinos.base/Trilinos

$ rm -r CMake*

$ time ./do-configure -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Kokkos=ON -DTrilinos_ENABLE_Teuchos=ON -DTrilinos_ENABLE_SEACAS=ON \
  &> configure.out

real    0m8.355s
user    0m5.522s
sys     0m2.528s

$ time ninja -j20 &> make.out

real    2m8.571s
user    37m58.212s
sys     3m2.960s

$ time ctest -j20 &> ctest.out

real    1m26.750s
user    2m54.565s
sys     0m22.646s
```

which gave:

```
100% tests passed, 0 tests failed out of 185

Subproject Time Summary:
Kokkos     = 175.08 sec*proc (27 tests)
SEACAS     =   7.30 sec*proc (20 tests)
Teuchos    =  42.74 sec*proc (138 tests)

Total Test time (real) =  86.15 sec
```

@bathmatt, can you please take a look at:

* https://github.com/trilinos/Trilinos/compare/develop...bartlettroscoe:4933-atdm-custom-env?expand=1#diff-3b922030112cdbaf917bd43ba1f4f5a7

Is that simple enough?

I can provide a CUDA-enabled example for SEMS RHEL7 if that would help as well.

### CODE REVIEW

**Comment by bathmatt** [comment]
This looks reasonable, I'll test it on vortex and get back to you.  Probably a day or so..

**Comment by bartlettroscoe** [comment]
> This looks reasonable, I'll test it on vortex and get back to you. Probably a day or so..

Just make sure you pull this branch.

One thing we need to figure out is how this works with installs of Trilinos.  Should it install the user's custom configuration directory?

**Comment by bathmatt** [comment]
I think it should be no different than a supported platform, we need a load-matching-env.sh and it should work..

**Comment by bathmatt** [comment]
Panzer is about built on vortex...

**Comment by bathmatt** [comment]
My vortex configure 
```
# Example of how to set up your own custom ATDM Trilinos configuration on some
# machine.

echo "Using my custom Vortex Cuda env for compiler stack $ATDM_CONFIG_COMPILER to build $ATDM_CONFIG_BUILD_TYPE code with Kokkos node type $ATDM_CONFIG_NODE_TYPE"



# 1) Load modules, set paths, etc.

module load gcc/7.3.1 cmake/3.12.1
module load lapack/3.8.0-P9-gcc-4.9.3 

# 2) Set up env vars that will get picked up by ATDMDevEnvSettings.cmake when
# configuring Trilinos.

export ATDM_CONFIG_USE_NINJA=ON
export PATH=$PATH:/ascldap/users/mbetten/VortexHome/bin
export ATDM_CONFIG_BUILD_COUNT=20
export ATDM_CONFIG_CTEST_PARALLEL_LEVEL=4
export ATDM_CONFIG_KOKKOS_ARCH="Power9;Volta70"

# MPI Stuff
export MPICC=`which mpicc`
export MPICXX=`which mpicxx`
export MPIF90=`which mpif90`
export OMPI_CXX=${ATDM_CONFIG_TRILNOS_DIR}/packages/kokkos/bin/nvcc_wrapper
export LLNL_USE_OMPI_VARS="Y"
export NVCC_WRAPPER_DEFAULT_COMPILER=`which  g++`
export OMPI_CC=`which gcc`
export OMPI_FC=`which gfortran`


# Cuda stuff
export CUDA_LAUNCH_BLOCKING=1

# TPL stuff
TPL_INSTALL=/vscratch1/mbetten/install/gcc-cuda-9.2
export ATDM_CONFIG_USE_HWLOC=OFF
export LAPACK_ROOT=${LAPACK_DIR}
export ATDM_CONFIG_NETCDF_LIBS="-L${TPL_INSTALL}/lib;${TPL_INSTALL}/lib/libboost_program_options.a;${TPL_INSTALL}/lib/libboost_system.a;-lnetcdf;-lpnetcdf;-lhdf5_hl;-lhdf5;-lgfortran;-lz;-ldl"
export ATDM_CONFIG_LAPACK_LIBS="-L${LAPACK_ROOT};-llapack;-lgfortran"
export ATDM_CONFIG_BLAS_LIBS="-L${LAPACK_ROOT}/lib;-lblas"
export ZLIB_ROOT=${TPL_INSTALL}
export BOOST_ROOT=${TPL_INSTALL}
export HDF5_ROOT=${TPL_INSTALL}
export NETCDF_ROOT=${TPL_INSTALL}

# Done
export ATDM_CONFIG_COMPLETED_ENV_SETUP=TRUE
[

```

**Comment by bathmatt** [comment]
It fails to install 

```
CMake Error at cmake_install.cmake:78 (file):
  file INSTALL cannot find
  "/ascldap/users/mbetten/vortex/build/gcc-cuda/Trilinos/cmake/std/atdm/vortex".

```

It is atdm/example/vortex

**Comment by bathmatt** [comment]
I think fix the install issue and have a working load-matching-env.sh resolves this issue and we can merge it.

**Comment by bartlettroscoe** [comment]
@bathmatt, the current system on this PR will not work for installs, hence my questions in #4933 see https://github.com/trilinos/Trilinos/issues/4933#issuecomment-521278214.  We need to resolve that before we can merge.

**Comment by bathmatt** [comment]
Ping me at SNL when you are ready for final review..

**Comment by bartlettroscoe** [comment]
@bathmatt, I just pushed commit 15177a1 to this branch.  Can you please test this out and see if the installed `load_matching_env.sh` script loads you custom env?  It seems to work in my local testing.

**Comment by bartlettroscoe** [comment]
@bathmatt,

Can you please review documentation:

* https://github.com/trilinos/Trilinos/blob/a2bfed60e4693b3ee8d7d1dc55dd436ceb995d89/cmake/std/atdm/README.md#custom-systems-and-configurations

It is short.

FYI: I need to clean up commits a bit and force push before the final approval and merge.

**Comment by bartlettroscoe** [comment]
@bathmatt and @fryeguy52,

Can you please review:

* https://github.com/bartlettroscoe/Trilinos/blob/4933-atdm-custom-env/cmake/std/atdm/README.md#custom-systems-and-configurations

and provide a review (accept or otherwise) this PR so it can be merged?

I tested this as described below so I am pretty sure this works as it should.

<details>

<summary><b>TESTING DETAILS:</b> (click to expand)</summary>

.

First, I tested with:

```
$ cd Trilinos

$ . cmake/std/atdm/load-env.sh gnu-openmp-opt
Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'gnu-openmp-opt'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build RELEASE code with Kokkos node type OPENMP

$ . cmake/std/atdm/load-env.sh gnu-openmp-opt cmake/std/atdm/examples/my-sems-rhel6-config
Selecting custom system configuration 'my-sems-rhel6-config'
Setting compiler and build options for build-name 'gnu-openmp-opt'
Using my custom SEMS RHEL6 env for compiler stack GNU to build RELEASE code with Kokkos node type OPENMP

$ export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=~/Trilinos.base/Trilinos/cmake/std/atdm/examples/my-sems-rhel6-config

$ . cmake/std/atdm/load-env.sh gnu-openmp-opt
Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'gnu-openmp-opt'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build RELEASE code with Kokkos node type OPENMP

$ . cmake/std/atdm/load-env.sh my-sems-rhel6-config-gnu-openmp-opt
Selecting custom system configuration 'my-sems-rhel6-config'
Setting compiler and build options for build-name 'my-sems-rhel6-config-gnu-openmp-opt'
Using my custom SEMS RHEL6 env for compiler stack GNU to build RELEASE code with Kokkos node type OPENMP
```

I then tested some builds with:

```
$ cd ~/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/

$ export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=~/Trilinos.base/Trilinos/cmake/std/atdm/examples/my-sems-rhel6-config

$ ./checkin-test-atdm.sh \
  sems-rhel6-gnu-7.2.0-openmp-opt-dbg \
  my-sems-rhel6-config-gnu-openmp-opt-dbg \
  --enable-packages=Kokkos,Teuchos,Amesos2,SEACAS --local-do-all

***
*** ./checkin-test-atdm.sh  sems-rhel6-gnu-7.2.0-openmp-opt-dbg my-sems-rhel6-config-gnu-openmp-opt-dbg --enable-packages=Kokkos,Teuchos,Amesos2,SEACAS --local-do-all
***

ATDM_TRILINOS_DIR = '/home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/../../..'

Load some env to get python, cmake, etc ...

Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'default'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL
File local-checkin-test-defaults.py already exists, leaving it!

Running configure, build, and/or testing for 2 builds:
    sems-rhel6-gnu-7.2.0-openmp-opt-dbg
    my-sems-rhel6-config-gnu-openmp-opt-dbg


***
*** 0) Process build case sems-rhel6-gnu-7.2.0-openmp-opt-dbg
***

Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'sems-rhel6-gnu-7.2.0-openmp-opt-dbg'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build RELEASE-DEBUG code with Kokkos node type OPENMP

Running: checkin-test.py --st-extra-builds=sems-rhel6-gnu-7.2.0-openmp-opt-dbg ...

  ==> See output file checkin-test.sems-rhel6-gnu-7.2.0-openmp-opt-dbg.out

+ /home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/../../../cmake/tribits/ci_support/checkin-test.py '--make-options=-j 20' '--ctest-options=-j 10' --st-extra-builds=sems-rhel6-gnu-7.2.0-openmp-opt-dbg --default-builds= --allow-no-pull --send-email-to= --test-categories=NIGHTLY --ctest-timeout=600 --enable-packages=Kokkos,Teuchos,Amesos2,SEACAS --local-do-all --use-ninja --log-file=checkin-test.sems-rhel6-gnu-7.2.0-openmp-opt-dbg.out
+ ATDM_CHT_SINGLE_RETURN_CODE=0
+ set +x
sems-rhel6-gnu-7.2.0-openmp-opt-dbg: PASSED!
***
*** 1) Process build case my-sems-rhel6-config-gnu-openmp-opt-dbg
***

Selecting custom system configuration 'my-sems-rhel6-config'
Setting compiler and build options for build-name 'my-sems-rhel6-config-gnu-openmp-opt-dbg'
Using my custom SEMS RHEL6 env for compiler stack GNU to build RELEASE-DEBUG code with Kokkos node type OPENMP

Running: checkin-test.py --st-extra-builds=my-sems-rhel6-config-gnu-openmp-opt-dbg ...

  ==> See output file checkin-test.my-sems-rhel6-config-gnu-openmp-opt-dbg.out

+ /home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/../../../cmake/tribits/ci_support/checkin-test.py '--make-options=-j 20' '--ctest-options=-j 1' --st-extra-builds=my-sems-rhel6-config-gnu-openmp-opt-dbg --default-builds= --allow-no-pull --send-email-to= --test-categories=NIGHTLY --ctest-timeout=600 --enable-packages=Kokkos,Teuchos,Amesos2,SEACAS --local-do-all --use-ninja --log-file=checkin-test.my-sems-rhel6-config-gnu-openmp-opt-dbg.out
+ ATDM_CHT_SINGLE_RETURN_CODE=0
+ set +x
my-sems-rhel6-config-gnu-openmp-opt-dbg: PASSED!

Collect and report final results:

  ==> See output file checkin-test.final.out


--------------------------------



PASSED (NOT READY TO PUSH): Trilinos: crf450.srn.sandia.gov

Fri Aug 16 10:08:55 MDT 2019

Enabled Packages: Kokkos, Teuchos, Amesos2, SEACAS

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT_OPENMP => Test case MPI_RELEASE_DEBUG_SHARED_PT_OPENMP was not run! => Does not affect push readiness! (-1.00 min)
1) sems-rhel6-gnu-7.2.0-openmp-opt-dbg => passed: passed=194,notpassed=0 (0.90 min)
2) my-sems-rhel6-config-gnu-openmp-opt-dbg => passed: passed=194,notpassed=0 (5.70 min)

A current successful pull does *not* exist => Not ready for final push!

Explanation: In order to safely push, the local working directory needs
to be up-to-date with the global repo or a full integration has not been
performed!


REQUESTED ACTIONS: PASSED
```

</details>

**Pull request merged**
