### PR TITLE
Tpetra Distributor: add method to get reverse distributor

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/tpetra 

## Motivation
Allows to set parameters on reverse distributor

### CODE REVIEW

**Comment by lucbv** [comment]
I think I would like it better if you introduce a method like `setReverseDistributorParams` so as not to expose the object itself directly.

**Comment by jhux2** [comment]
Is this related to PR #7146?

**Comment by cgcgcg** [comment]
@jhux2 No, but working on #7146 I noticed that no parameters were set on the reverse distributor used for the doExport using an importer in RefMaxwell. This change seems desirable independent of #7146.

**Comment by kddevin** [comment]
@cgcgcg Would you please add a comment on how you tested this change?  Did you add a Tpetra test that exercises the method?  If not, it will not get exercised in PR testing.
We need this information for ASC's software quality assessments; we are trying to not approve PRs until test information is added.  Thanks!

**Comment by cgcgcg** [comment]
@kddevin Added a testing section to the description, will add a unit test in Tpetra for it.

**Comment by kddevin** [comment]
Thanks, @cgcgcg!

**Pull request merged**
