### PR TITLE
Ifpack2/Tpetra: Fixing multiproc issue in BlockCrs example

### PR DESCRIPTION
**Pull request by csiefer2**
Issue: #11195
Tests: Used application matrix
Stakeholder feedback: n/a

Fixes bug for matrices with non-contiguous rowmaps

### CODE REVIEW

**Review by jhux2 — DISMISSED** [review]
lgtm.

**Review by jhux2 — APPROVED** [review]
lgtm, thanks for the unit test!

**Comment by csiefer2** [comment]
@trilinos/framework @sebrowne I can't reproduce the test failure via following the reproduction instructions.

**Review by jhux2 — APPROVED** [review]
lgtm

**Pull request merged**
