### PR TITLE
@trilinos/tpetra Query environment variables with Tpetra

### PR DESCRIPTION
**Pull request by tjfulle**
Adds Tpetra::Details::Environment singleton class:
- query system for environment variables
- cache retrieved environment variables
- cache default variables on instantiation (TPETRA_DEBUG,
  TPETRA_USE_BLAS)
- setting environment variables capability is disabled

Commit also provides an updated method of loading configuration files
with the checkin-test.py script, allowing configuration files to have
extensions different than '.py'

Addresses: #654, #684, #688

Build/Test Cases Summary
Enabled Packages: TpetraCore, Ifpack2, Belos, Amesos2, Zoltan2, Xpetra, MueLu, Stokhos, Sacado
Disabled Packages: SEACAS,STK,Shards,FEI,ROL,Moertel,Panzer,ThreadPool,OptiPack,Rythmos,Intrepid,PyTrilinos
0) MPI_DEBUG => passed: passed=515,notpassed=0 (11.04 min)

### CODE REVIEW

**Comment by tjfulle** [comment]
@mhoemmen @trilinos/tpetra

**Comment by tjfulle** [comment]
I've got several other suggestions/comments on the checkin test script and I noticed that there is an open story #158 dealing with the checkin script/environment.  I'll post there.

**Comment by tjfulle** [comment]
@mhoemmen, I reverted the checkin-test.py file and re-committed/pushed.  Not sure if that is the right protocol...

**Comment by mhoemmen** [comment]
> @mhoemmen, I reverted the checkin-test.py file and re-committed/pushed. Not sure if that is the right protocol...

Right protocol would be to create a new commit which does not touch checkin-test.py.  That would make bisection easier.  If something went wrong with checkin-test.py in the first commit, that would get that first commit unfairly blamed for anything that went wrong.

I think you can just squash the two commits, to make it like you never changed checkin-test.py.  But do save your checkin-test.py changes!

**Comment by tjfulle** [comment]
@mhoemmen, Since I had already pushed the changes, squashing was a bit problematic...  I *think*, it might be done now?

**Comment by mhoemmen** [comment]
I still find it kinda scary to merge at the push of a button ;-) (should be harder than that somehow...)

Thanks @tjfulle !!!  Great work!!!

**Pull request merged**
