### PR TITLE
Trios:  Removing deprecated package trios #4864

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/framework @trilinos/trios 
Package trios was marked deprecated.  This PR removes it.
Also removed a few references to other packages previously removed from Trilinos.

## Motivation
See #4864 

## Testing

Configure / build with ATDM scripts (Panzer enabled) on cee-lan.

### CODE REVIEW

**Comment by kddevin** [comment]
@trilinos/muelu @jhux2 @csiefer2 @cgcgcg @lucbv 
While there's no way removing package trios from Trilinos should affect MueLu testing, I am seeing the failure below.  Is this a known issue?  Or bad luck that might resolve itself in a new round of testing?  Or a new problem?
https://testing.sandia.gov/cdash/testDetails.php?test=96878231&build=6080807
Thanks!

**Comment by brian-kelley** [comment]
@kddevin Yes, it's #6361.

**Comment by lucbv** [comment]
@kddevin yes it's something we need to take care of, I think I will just put a PR that reverts some changes to that unit-test and it should stop failing after that...

**Comment by kddevin** [comment]
Ah, good to know.  Thank you!

**Comment by kddevin** [comment]
@trilinos/intrepid2 @mperego @kyungjoo-kim 
While there's no way removing package Trios from Trilinos should affect Intrepid2's testing, I am seeing the error below.   Is this a known issue? Or bad luck that might resolve itself in a new round of testing? Or a new problem?
https://testing.sandia.gov/cdash/testDetails.php?test=96960370&build=6085246

**Comment by mperego** [comment]
@kddevin, I cannot see the dashboard, but it could be related to #6246. So, it might go through if you rerun the test.

**Pull request merged**
