### PR TITLE
Remove experimental from Tpetra block crs/multivector/vector.

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
@trilinos/tpetra 

## Description

This PR removes all experimental name space from block crs/multivector/vector.

## Motivation and Context

#4385

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@mhoemmen What you described is the current statue of the code. Tpetra_Block* headers include Tpetra_Experimental_Block* headers. I think that we want to remove the experimental namespace completely. The name space "Experimental" means that we can remove it anytime we want. Even if some downstream codes actually use the Experimental namespace for block matrix operations, it should be modified in the downstream codes. For now, the only downstream package is SPARC and I don't think that they use the experimental headers in their code. Just in case, would you make sure of it as I don't have access the code ?

**Comment by kddevin** [comment]
The "trilinos blessed" way to deprecate header files:  add something like the following to the header file, changing the claps message to a useful message.

```
#if !defined(TRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS)
#ifdef __GNUC__
#  warning "The package Claps is deprecated in April 2019; it will be removed from Trilinos in May 2019."
#endif
#endif
```

**Comment by mhoemmen** [comment]
@kyungjoo-kim wrote:
> What you described is the current status of the code.

Not exactly.  The current status of the code is as follows:

1. The actual declarations and definitions of the classes live in the `Tpetra::Experimental` namespace, in `Tpetra_Experimental_*` headers.
2. Each `Tpetra_*` header includes the corresponding `Tpetra_Experimental_*` header, and imports the corresponding class into the Tpetra namespace.

I had understood the end goal as follows:

1. Move the actual declarations and definitions of the classes into the Tpetra namespace, and into `Tpetra_*` headers.
2. Mark the `Tpetra_Experimental_*` headers as deprecated, using the procedure that Karen outlines above.
3. Have each `Tpetra_Experimental_*` header import the corresponding class into the `Tpetra::Experimental` namespace.

This is "deprecation without removal."

**Comment by mhoemmen** [comment]
Removal breaks backwards compatibility.  It doesn't matter whether or not SPARC uses the headers or namespace; what matters is that the hypothetical user's code isn't broken.

**Comment by mhoemmen** [comment]
SPARC does use the "Experimental" namespace and headers still.  I'm fixing that now, but that's not the point.  The point is that removing the headers breaks backwards compatibility.

**Comment by kyungjoo-kim** [comment]
Okay. I understand the concern. I will just leave the experimental headers.

**Comment by mhoemmen** [comment]
> I will just leave the experimental headers.

The experimental headers would also need to be changed, so that they just include the non-experimental headers and import their classes into the `Tpetra::Experimental` namespace.

I don't mean to get in the way -- I'm just worried about backwards compatibility.

**Comment by kyungjoo-kim** [comment]
I left all experiemantal headers and BlockExpNamespace.cpp for testing.

**Comment by mhoemmen** [comment]
SPAR-580 (reported by @bartlettroscoe ) suggests that we may have missed something with the BlockCrs writer.  We'll take a look.

**Comment by mhoemmen** [comment]
SPAR-580 was easy to fix in SPARC.  Your changes were just fine :-D .

**Comment by bartlettroscoe** [comment]
> SPAR-580 was easy to fix in SPARC. Your changes were just fine :-D .

But not strictly backward compatible (or SPARC was not including header files and using types correctly).  But I guess since SPARC was using "Experimental" types, there was no expectation for backwards compatibility anyway so this is all good..

**Comment by kyungjoo-kim** [comment]
@mhoemmen Thank you for fixing the problem in SPARC. As I do not have an access to SPARC, I do not even get such a notice of the failure. In Tpetra BlockExpNamespace, I tested it compiled with the experimental namespace but that does not seem to be enough.

**Comment by mhoemmen** [comment]
@kyungjoo-kim Don't worry about it :-)  I don't think you did anything wrong at all.  SPARC should have been including the new header files anyway; they've existed for a long time.  Doing that made the build work for both old and new versions of Trilinos.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

>  @kyungjoo-kim Don't worry about it :-) I don't think you did anything wrong at all

Yes, I agree.  Given that SPARC was pointing to "Experimental" stuff in the first place, there is no expectation of maintaining backward compatibility.  Just my opinion.

**Pull request merged**
