### PR TITLE
Ifpack2: Fix #5260 (Chebyshev using try-catch for control flow)

### LINKED ISSUE #5260: Ifpack2::Chebyshev uses try-catch as control flow
## Bug Report
@trilinos/ifpack2 @vbrunini 

### Description

`Ifpack2::Chebyshev` (actually `Ifpack2::Details::Chebyshev`) uses try-catch as control flow in ParameterList processing.  This hinders using an exception throw as a breakpoint when running in a debugger.  Sierra developers have complained about this for a while.

I have a fix in progress.

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/ifpack2 @vbrunini @trilinos/muelu 

## Description

1. Clean up `Ifpack2::Relaxation` initialize and compute.
2. Remove use of try-catch as control flow in `Ifpack2::Chebyshev`.

## Related Issues

* Closes #5260 
* Blocked by #4726

### CODE REVIEW

**Comment by csiefer2** [comment]
You are my hero!

**Comment by mhoemmen** [comment]
Stokhos :(

**Comment by mhoemmen** [comment]
@etphipp @crtrott @dhollman Y'all might be amused to note that the Stokhos build errors resulted from an attempt to return an expression from a lambda (Stokhos uses expression templates).

**Comment by mhoemmen** [comment]
@trilinos/tpetra @trilinos/ifpack2 @trilinos/muelu If any of you have time, could you please rereview?  I think I've fixed this.

**Comment by mhoemmen** [comment]
@trilinos/tpetra @trilinos/ifpack2 @trilinos/muelu Hold on, it turns out my build didn't enable MueLu in Stokhos.  I am still getting the following build error:
```
.../packages/ifpack2/src/Ifpack2_Relaxation_def.hpp:1135:60: error: cannot convert ‘Kokkos::Details::ArithTraits<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> > >::val_type {aka Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::OpenMP> >}’ to ‘const magnitude_type {aka const double}’ in initialization
              const magnitude_type d_i_real = KAT::real (d_i);
```
This is #5269.

**Comment by mhoemmen** [comment]
@trilinos/tpetra @trilinos/ifpack2 @trilinos/muelu @csiefer2 OK, I think I've fixed the Stokhos build errors.  This should be ready for review now.  Thanks!

**Comment by mhoemmen** [comment]
Oops, not a complete fix for `Kokkos::complex<T>` specialization of `Teuchos::ScalarTraits`.  Will need to look at this.

**Comment by mhoemmen** [comment]
I've been working on https://github.com/trilinos/Trilinos/issues/5279 and haven't gotten to this yet.  Will do soon.

**Comment by mhoemmen** [comment]
Just to save the error for when I can fix it:
```

Errors
--
Teuchos | Error building packages/teuchos/core/test/ScalarTraits/CMakeFiles/TeuchosCore_ScalarTraits_test.dir/ScalarTraits_test.cpp.oError while building C++ object file " packages/teuchos/core/test/ScalarTraits/CMakeFiles/TeuchosCore_ScalarTraits_test.dir/ScalarTraits_test.cpp.o" in target TeuchosCore_ScalarTraits_testErrorSource Filepackages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cppCommand[+] "/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.8.4/openmpi/1.10.1/bin/mpicxx"Directory/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/pull_request_testExit Condition1Standard ErrorIn file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraits.hpp:113:0,                  from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:44: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:137:3:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<double>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:351:61:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:93: error: cannot convert ‘Kokkos::complex<double>’ to ‘bool’ in return    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                              ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:137:3:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<float>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:354:60:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:93: error: cannot convert ‘Kokkos::complex<float>’ to ‘bool’ in return /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:144:92:   required from ‘static T Teuchos::ScalarTraits<T>::nan() [with T = Kokkos::complex<double>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:132:30:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<double>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:351:61:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:82: error: ‘this_type_is_missing_a_specialization’ is not a member of ‘Kokkos::complex<double>’    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                   ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:144:92:   required from ‘static T Teuchos::ScalarTraits<T>::nan() [with T = Kokkos::complex<float>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:132:30:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<float>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:354:60:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:82: error: ‘this_type_is_missing_a_specialization’ is not a member of ‘Kokkos::complex<float>’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:85: warning: control reaches end of non-void function [-Wreturn-type]    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                      ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:96: warning: control reaches end of non-void function [-Wreturn-type]    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                                 ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:85: warning: control reaches end of non-void function [-Wreturn-type]    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                      ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:96: warning: control reaches end of non-void function [-Wreturn-type]    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                                 ^ | packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp | [+] "/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.8.4/openmpi/1.10.1/bin/mpicxx" | /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/pull_request_test | 1 | In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraits.hpp:113:0,                  from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:44: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:137:3:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<double>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:351:61:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:93: error: cannot convert ‘Kokkos::complex<double>’ to ‘bool’ in return    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                              ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:137:3:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<float>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:354:60:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:93: error: cannot convert ‘Kokkos::complex<float>’ to ‘bool’ in return /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:144:92:   required from ‘static T Teuchos::ScalarTraits<T>::nan() [with T = Kokkos::complex<double>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:132:30:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<double>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:351:61:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:82: error: ‘this_type_is_missing_a_specialization’ is not a member of ‘Kokkos::complex<double>’    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                   ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:144:92:   required from ‘static T Teuchos::ScalarTraits<T>::nan() [with T = Kokkos::complex<float>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:132:30:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<float>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:354:60:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:82: error: ‘this_type_is_missing_a_specialization’ is not a member of ‘Kokkos::complex<float>’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:85: warning: control reaches end of non-void function [-Wreturn-type]    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                      ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:96: warning: control reaches end of non-void function [-Wreturn-type]    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                                 ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:85: warning: control reaches end of non-void function [-Wreturn-type]    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                      ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:96: warning: control reaches end of non-void function [-Wreturn-type]    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                                 ^


packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp
[+] "/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/4.8.4/openmpi/1.10.1/bin/mpicxx"
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/pull_request_test
1
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraits.hpp:113:0,                  from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:44: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:137:3:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<double>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:351:61:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:93: error: cannot convert ‘Kokkos::complex<double>’ to ‘bool’ in return    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                              ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:137:3:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<float>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:354:60:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:93: error: cannot convert ‘Kokkos::complex<float>’ to ‘bool’ in return /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:144:92:   required from ‘static T Teuchos::ScalarTraits<T>::nan() [with T = Kokkos::complex<double>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:132:30:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<double>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:351:61:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:82: error: ‘this_type_is_missing_a_specialization’ is not a member of ‘Kokkos::complex<double>’    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                   ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In instantiation of ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:144:92:   required from ‘static T Teuchos::ScalarTraits<T>::nan() [with T = Kokkos::complex<float>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:132:30:   required from ‘bool {anonymous}::testScalarTraits(Teuchos::FancyOStream&) [with Scalar = Kokkos::complex<float>; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp:354:60:   required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:82: error: ‘this_type_is_missing_a_specialization’ is not a member of ‘Kokkos::complex<float>’ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:85: warning: control reaches end of non-void function [-Wreturn-type]    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                      ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<double>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:96: warning: control reaches end of non-void function [-Wreturn-type]    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                                 ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static T Teuchos::UndefinedScalarTraits<T>::notDefined() [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:59:85: warning: control reaches end of non-void function [-Wreturn-type]    static inline T notDefined() { return T::this_type_is_missing_a_specialization(); }                                                                                      ^ /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp: In static member function ‘static bool Teuchos::ScalarTraits<T>::isnaninf(const T&) [with T = Kokkos::complex<float>]’: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp:146:96: warning: control reaches end of non-void function [-Wreturn-type]    static inline bool isnaninf(const T& x)     { return UndefinedScalarTraits<T>::notDefined(); }                                                                                                 ^
```

**Comment by mhoemmen** [comment]
I think I know what's wrong: I had the `Kokkos::complex<T>` specialization of `Teuchos::ScalarTraits` protected by both the `HAVE_TEUCHOS_COMPLEX` and `HAVE_TEUCHOSCORE_KOKKOSCORE` macros.  `Kokkos::complex<T>` does not depend in any way on Teuchos' "complex support," so its ScalarTraits specialization should only depend on the `HAVE_TEUCHOSCORE_KOKKOSCORE` macro.  I have a fix in progress.  I'll test with complex both enabled (my usual state, since Sierra enables complex) and disabled, before pushing.

**Comment by mhoemmen** [comment]
Just some signed/unsigned warnings that my compiler didn't pick up for some reason.  I will fix now.

**Comment by mhoemmen** [comment]
All builds passed except for a signed/unsigned comparison warning in the GCC 7.2.0 warnings-as-errors build.  I just pushed a fix for that and will retest.

**Comment by mhoemmen** [comment]
@trilinos/tpetra @trilinos/ifpack2 @trilinos/muelu @jhux2 @csiefer2 Woah, it passed!!!  Please review :-D

**Pull request merged**
