### PR TITLE
TSQR: Progress towards Kokkos-ization of CombineNative

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra 

## Description

I've started a slow migration of TSQR's QR factorization and apply implementation (in CombineNative) to use Kokkos.  For now, I'm just replacing raw pointers with Kokkos::View, but still LayoutLeft and Serial.

## Motivation and Context

ECP PEEKS project wants TSQR on different architectures, for CA-GMRES etc.

## How Has This Been Tested?

Locally, on my workstation.

### CODE REVIEW

**Comment by mhoemmen** [comment]
Somebody please approve this.  It passes all the tests (that's why there are so many commits), and it's a conservative set of changes that aim towards a fully Kokkos-ized TSQR implementation.  I'll be happy to walk through the changes with someone on the phone.

**Comment by mhoemmen** [comment]
@srajama1 wrote:
> Why is TSQR in Tpetra and not Belos ?

TSQR doesn't have to be in Tpetra, but it definitely does not belong in Belos.  TSQR requires Kokkos, kokkos-kernels, and MPI.  Belos does not require any of these things.  Belos only requires Teuchos.  It must be possible to build Belos without enabling Kokkos.  (At least until recently, if not currently, Kokkos would not build on Windows.  @csiefer2 can talk more about that.)

**Comment by srajama1** [comment]
Why can't Belos optionally depend on Kokkos, Kokkos Kernels etc ? The TSQR subpackage can require the use of these other packages when enabled.

**Comment by hkthorn** [comment]
@srajama1 @mhoemmen The TSQR algorithm is not uniquely required by the algorithms in Belos, the core kernel computes a QR factorization (as is obvious by the name).  This is a necessary kernel that comes up in many other iterative methods, like eigensolvers, model-order reduction, nonlinear-solvers/continuation methods.  Anywhere where you need to find an orthogonal basis for a set of vectors, this kernel will be useful and a more efficient implementation for next-generation platforms is necessary.  It does not belong in Belos.

**Comment by mhoemmen** [comment]
@csiefer2 @tjfulle Thanks! :D

**Comment by mhoemmen** [comment]
@trilinos/framework @jwillenbring Would you happen to know why I can't merge this?  I have two approving reviews, no disapproving reviews, and all the tests have passed.

**Comment by mhoemmen** [comment]
Never mind -- looks like it just needed some time to get through the system.  Thanks all

**Pull request merged**
