### PR TITLE
Panzer address mesh centroid roundoff

### PR DESCRIPTION
**Pull request by krcb**
@trilinos/panzer 

## Motivation

These changes ensure that a mesh centered around zero doesn't have a centroid
with a coordinate determined by roundoff error. For the line mesh, ensure that the
normal direction computation doesn't perform a divide by zero.

### CODE REVIEW

**Comment by krcb** [comment]
This shouldn't be merged until a downstream app gives the go ahead.

**Comment by eric-c-cyr** [comment]
Looked through this now. It looks fine. Moving on to app testing.

**Comment by krcb** [comment]
@rppawlo @eric-c-cyr I just pushed a change to fix the build error reported here (an unused variable). Could one of you re-review?

**Comment by eric-c-cyr** [comment]
@krcb Are we just waiting for @bathmatt now?

**Comment by krcb** [comment]
Yes.

On Oct 7, 2019, at 9:13 PM, Eric C. Cyr <notifications@github.com<mailto:notifications@github.com>> wrote:


@krcb<https://github.com/krcb> Are we just waiting for @bathmatt<https://github.com/bathmatt> now?

**Comment by jmgate** [comment]
@eric-c-cyr suggested we merge.

**Comment by krcb** [comment]
@jmgate Thanks!

**Pull request merged**
