### PR TITLE
Fix #4250, #4234, #4249, and #3823

### LINKED ISSUE #4250: TeuchosKokkosCompat: Test fails to build
@trilinos/teuchos @trilinos/kokkos @trilinos/tpetra 

A test in TeuchosKokkosCompat fails to build.  I get a few errors like the following:
```
.../Trilinos/packages/teuchos/kokkoscompat/test/linkTest.cpp: In member function ‘virtual void LinkTeuchosAndKokkos_NoInteraction_UnitTest::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const’:
.../Trilinos/packages/teuchos/kokkoscompat/test/linkTest.cpp:109:3: error: ‘initialize’ is not a member of ‘TestDevice {aka Kokkos::OpenMP}’
   TestDevice::initialize();
   ^
.../Trilinos/packages/teuchos/kokkoscompat/test/linkTest.cpp:126:3: error: ‘finalize’ is not a member of ‘TestDevice {aka Kokkos::OpenMP}’
   TestDevice::finalize();
   ^
```

## Related Issues
* Blocks #4249, #4234

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @trilinos/kokkos @trilinos/teuchos 

This fixes a few Teuchos issues, and one Tpetra issue.  The Tpetra fix is actually a work-around for kokkos-kernels issues.  @kyungjoo-kim might have some fixes there; see e.g., https://github.com/kokkos/kokkos-kernels/pull/373.

This may be "results impacting," because it affects how Tpetra computes dot products for complex Scalar types.  In particular, the work-around always uses `complex<double>` as the accumulator type.  This should improve accuracy for the `Scalar=complex<float>` case.

## Related Issues

* Closes #4250, #4234, #4249, #3823

### CODE REVIEW

**Comment by mhoemmen** [comment]
@lucbv You're the one who reported complex scalar types being broken in Tpetra::MultiVector, right?

**Comment by lucbv** [comment]
@mhoemmen, yes I did report that fairly early.

**Comment by ndellingwood** [comment]
Also adding reference to kokkos/kokkos-kernels#374, it looks like when that PR is complete it should fix the underlying BLAS tpl issue with zdot by providing configure-time (CMake) or makefile options to use the proper BLAS interface (some BLAS installs expect the dot result as the first argument to zdot and the routine has void return type, others provide the result via return type, etc).

@mhoemmen once the BLAS TPL issue is resolved in kokkos-kernels is the plan for Tpetra to go back to the `KokkosBlas::dot` routine or to continue using the routine your added in this PR? Just checking if a follow-on patch to Trilinos should be issued or if changes to Tpetra need to be made during the next promotion testing, or if you'd prefer no changes.

**Comment by mhoemmen** [comment]
@ndellingwood wrote:
> once the BLAS TPL issue is resolved in kokkos-kernels is the plan for Tpetra to go back to the `KokkosBlas::dot` routine or to continue using the routine your added in this PR?

The plan is for Tpetra to go back to the `KokkosBlas::dot` routine, once it works correctly.  The point of the work-around is to get Tpetra tests passing for complex Scalar types.

I do think it would make sense, especially for `float` and `complex<float>`, to bypass the BLAS' dot products and roll our own dot products that use an extended-precision accumulator.  However, I think the existing `KokkosBlas::dot` interface suffices for that.

**Pull request merged**
