### PR TITLE
STK: Snapshot 05-16-22 19:52

### PR DESCRIPTION
**Pull request by tasmith4**
@trilinos/stk

### CODE REVIEW

**Review by alanw0 — APPROVED** [review]

**Comment by alanw0** [comment]
@jwillenbring Jim, could you help me out again? I got a message from this PR saying the intel-19 build failed, but when I follow the link to the cdash page, there is no line for intel. There are lines for several builds, but not that one. How can I find that?
thanks

**Comment by jwillenbring** [comment]
@alanw0 So I need to see what happened here. The Intel 19 is a new build and may not be reporting to all the right places. In any case, here you can find the failure:

https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=150951

**Comment by alanw0** [comment]
> @alanw0 So I need to see what happened here. The Intel 19 is a new build and may not be reporting to all the right places. In any case, here you can find the failure:
> 
> https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=150951

@jwillenbring Thanks Jim! This was a failure related to stk code, which we can fix, but I just couldn't find the link.

**Comment by jwillenbring** [comment]
@alanw0 The issue that made the results hard to find in this case has been diagnosed and a fix is in the works for future runs.

**Pull request merged**
