### PR TITLE
MueLu: pairwise multipass aggregation, see issue #7008

### LINKED ISSUE #7008: MueLu: improving pairwise aggregation to perform multiple pass of pair aggregation
## Enhancement
@trilinos/muelu 

Adding multi-pass pairwise algorithm to muelu, currently the pairwise aggregation factory can only form aggregates of size 2 which might not coarsen fast enough to yield a computational efficient preconditioner.

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/muelu 

## Motivation
This will allow true testing of pairwise aggregation.
Currently a single pass algorithm is available but it probably won't yield good hierarchies from a computation stand-point.

## Related Issues

* Closes #7008 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Stakeholder Feedback
SPARC linear solvers, i.e. @rstumin 

## Testing
Multiple unit-test are added to make sure this feature works.
It was tested on local platform using OpenMP and complex

### CODE REVIEW

**Comment by lucbv** [comment]
@etphipp 
It looks like Stokhos is not playing nice with `Kokkos::create_mirror_view`, I am seeing the following build error locally (also appearing in previous auto-tester attempts):
```
/ascldap/users/lberge/Research/Trilinos_lucbv/packages/kokkos/core/src/Kokkos_CopyViews.hpp:3383:31: error: no matching function for call to ‘create_mirror(const Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::OpenMP> >*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1> >&)’
   return Kokkos::create_mirror(src);
          ~~~~~~~~~~~~~~~~~~~~~^~~~~
/ascldap/users/lberge/Research/Trilinos_lucbv/packages/kokkos/core/src/Kokkos_CopyViews.hpp:3282:51: note: candidate: ‘template<class T, class ... P> typename Kokkos::View<DataType, Properties>::HostMirror Kokkos::create_mirror(const Kokkos::View<D, P ...>&, typename std::enable_if<(std::is_same<typename Kokkos::ViewTraits<DataType, Properties ...>::specialize, void>::value && (! std::is_same<typename Kokkos::ViewTraits<DataType, Properties ...>::array_layout, Kokkos::LayoutStride>::value))>::type*)’
 inline typename Kokkos::View<T, P...>::HostMirror create_mirror(
                                                   ^~~~~~~~~~~~~
```

**Comment by etphipp** [comment]
Well, there are in fact overloads of create_mirror() for Stokhos scalar types, e.g.,

https://github.com/trilinos/Trilinos/blob/67064dc0bd94754b56ded6ee2a0a09a2dcc45433/packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp#L116

I'm not sure why the compiler isn't finding it.  There is tons of code that calls create_mirror() for Stokhos scalar types, so I know it works.  I'll have to checkout your PR and see if I can figure out what is wrong.

**Comment by etphipp** [comment]
I added a commit that appears to fix this.  The issue was the MueLu_ConfigDefs.hpp include in the Stokhos auto-generated ETI files.  This file also includes Kokkos headers which need to be included after Stokhos.  Replacing that include with MueLu_config.hpp appears to fix it.

**Comment by lucbv** [comment]
@etphipp thanks for your help on this!
The PR is now passing : )

@rstumin @csiefer2 if you guys want to look at this, it is ready now.

**Comment by lucbv** [comment]
@csiefer2 
no it does not look like it, at least I do not see any commits from you.
Please push your changes to my branch if you want them in this PR.

**Pull request merged**
