### PR TITLE
Fix compiling using Sacado with a CUDA device compiler and KOKKOS_ENABLE_CUDA=OFF

### PR DESCRIPTION
**Pull request by masterleinad**
@trilinos/kokkos
@trilinos/sacado

## Description
If a `CUDA` device compiler and `KOKKOS_ENABLE_CUDA=OFF`, still define
- `Kokkos::atomic_compare_exchange`
- `Kokkos::atomic_exchange`
- `Kokkos::atomic_fetch_add`
- `Kokkos::atomic_fetch_and`
- `Kokkos::atomic_fetch_or`
- `Kokkos::atomic_fetch_sub`

and don't define `Sacado::createGlobalMemoryPool` and `Sacado::destroyGlobalMemoryPool` with a `Kokkos::Cuda` parameter in that case.

## Motivation and Context
Fixes https://github.com/kokkos/kokkos/issues/1607 and https://github.com/dealii/dealii/issues/6423.

## How Has This Been Tested?
Compiling `Trilinos` configured without `CUDA` support, but with `Kokkos` and `Sacado` works.
Compiling (`deal.II`)[https://github.com/dealii/dealii/] with `CUDA` support and such a `Trilinos` configuration works and passes `deal.II`s test suite.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by lucbv** [comment]
@trilinos/kokkos @trilinos/sacado

**Comment by ibaned** [comment]
@masterleinad was this sufficient to get through the `deal.II` compile?

**Comment by ibaned** [comment]
I'll get the ball rolling on making a PR to Kokkos with these changes. If it gets approved there then we can let this go through as well as a hotpatch to Trilinos.

**Comment by ibaned** [comment]
see kokkos/kokkos#1892

**Comment by masterleinad** [comment]
> @masterleinad was this sufficient to get through the deal.II compile?

Yes, this is sufficient to compile `deal.II`. Thanks for forwarding to `Kokkos`!

**Comment by ibaned** [comment]
Hmm these seem to have broken the actual `KOKKOS_ENABLE_CUDA` build... I'll try to figure it out

**Comment by ibaned** [comment]
just to be clear... do you actually need the atomics to work on CPUs or GPUs? i.e. is Sacado being used inside threaded code? are you compiling with `nvcc` or `clang`? it seems like with your changes, when `__CUDA_ARCH__` is defined, then atomic functions are given a CPU implementation, which seems a bit strange to me.

**Comment by ibaned** [comment]
@masterleinad could you please try the branch I put up as  #3843 instead? That one at least does not break our KOKKOS_ENABLE_CUDA builds.

**Comment by masterleinad** [comment]
Superseded by #3843.

**Pull request closed without merging**
