### PR TITLE
changed how dynamic view is tracked

### PR DESCRIPTION
**Pull request by bathmatt**
@trilinos/kokkos

### CODE REVIEW

**Comment by bathmatt** [comment]
@crtrott should this go in to Trilinos or should we wait for an update and just have it in our repo with the profiling tools

**Comment by bathmatt** [comment]
@jmgate we may need to snap this into our repo..

**Comment by ndellingwood** [comment]
@bathmatt changes look good, a couple questions:
1. What motivated the change to call `kokkos_malloc` and `kokkos_free`, is that more performant?
2. Is there a matching PR to the kokkos repo so these changes aren't clobbered by the next release?

**Comment by bathmatt** [comment]
> @bathmatt changes look good, a couple questions:
> 
> 1. What motivated the change to call `kokkos_malloc` and `kokkos_free`, is that more performant?
> 2. Is there a matching PR to the kokkos repo so these changes aren't clobbered by the next release?

 The memory profiler missed these allocations, this will capture them.  There is another issue on a more complete fix.  I lost several days trying to track down the missing memory,

**Comment by ndellingwood** [comment]
@crtrott will PR kokkos/kokkos#3059 or work in progress related to issue kokkos/kokkos#3064 replace the changes in this PR during the next kokkos release? I want to get a cross-reference to make sure the changes @bathmatt needs aren't clobbered by the next promotion.

**Comment by bathmatt** [comment]
Any status update on this?

**Comment by bathmatt** [comment]
Not a problem, @jmgate can you cherry pick this one too?  We'll have to pave anyway when we get to 3.2 , and if the Kokkos weeks are like the empire weeks, we have a month or two :)

**Comment by jmgate** [comment]
Hah!  I'm actually going to have @dc-snl handle this one to make sure he's cool with the process before I take vacation in a few weeks.  I'll file an issue internally to track it.

**Comment by bathmatt** [comment]
Have @dc-snl close this when done then?
Thanks @jmgate

**Comment by rppawlo** [comment]
Closing this since the next promotion of kokkos will fix.

**Pull request closed without merging**
