### PR TITLE
Enable Xpetra and MueLu Experimental in standard CI build (#2317, #2462)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
**CC:** @trilinos/xpetra, @trilinos/muelu, @mhoemmen, @trilihos/framework

## Description

Since the ATDM APPs enable these, so should the CI and auto PR builds.  When
that changes, we can remove this.  This is one of the parts of #2462.

I tested this with:

```
$ ./checkin-test-sems.sh --enable-all-packages=on --local-do-all
```

and it passed the full CI build and I verified that experimental Xpetra and MueLu code are enabled.  See details below.

<details>
<summary>
  <b>DETAILS</b> (chick to expand)
</summary>

I tested this branch locally with:

```
$ ./checkin-test-sems.sh --enable-all-packages=on --local-do-all
```

and it returned:

```
passed: Trilinos/MPI_RELEASE_DEBUG_SHARED_PT: passed=2587,notpassed=0

Tue Mar 27 22:04:18 MDT 2018

Enabled Packages: 
Disabled Packages: PyTrilinos,Claps,TriKota Enabled all Packages
Hostname: crf450.srn.sandia.gov
Source Dir: /home/rabartl/Trilinos.base/Trilinos/cmake/tribits/ci_support/../../..
Build Dir: /home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT

CMake Cache Varibles: -DTrilinos_TRIBITS_DIR:PATH=/home/rabartl/Trilinos.base/Trilinos/cmake/tribits -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_TEST_CATEGORIES:STRING=BASIC -DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF -DDART_TESTING_TIMEOUT:STRING=300.0 -DBUILD_SHARED_LIBS=ON -DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON -DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake,cmake/std/sems/SEMSDevEnv.cmake -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=OFF -DTrilinos_ENABLE_Claps:BOOL=OFF -DTrilinos_ENABLE_TriKota:BOOL=OFF
Make Options: -j16
CTest Options: -j16 

Pull: Not Performed
Configure: Passed (2.79 min)
Build: Passed (89.59 min)
Test: Passed (15.20 min)

100% tests passed, 0 tests failed out of 2587

Label Time Summary:
Amesos               =  19.76 sec (14 tests)
Amesos2              =  10.78 sec (9 tests)
Anasazi              = 103.01 sec (71 tests)
AztecOO              =  16.08 sec (17 tests)
Belos                =  99.77 sec (72 tests)
Domi                 = 146.42 sec (125 tests)
Epetra               =  40.70 sec (61 tests)
EpetraExt            =  14.38 sec (11 tests)
FEI                  =  41.48 sec (43 tests)
Galeri               =   4.07 sec (9 tests)
GlobiPack            =   0.78 sec (6 tests)
Ifpack               =  58.52 sec (53 tests)
Ifpack2              =  41.91 sec (35 tests)
Intrepid             = 151.68 sec (152 tests)
Intrepid2            =  47.41 sec (144 tests)
Isorropia            =   7.37 sec (6 tests)
Kokkos               =  41.18 sec (23 tests)
KokkosKernels        =  71.84 sec (4 tests)
ML                   =  44.19 sec (34 tests)
MiniTensor           =   0.26 sec (2 tests)
MueLu                = 312.97 sec (84 tests)
NOX                  = 150.28 sec (106 tests)
OptiPack             =   5.93 sec (5 tests)
Panzer               = 590.07 sec (154 tests)
Phalanx              =   5.49 sec (27 tests)
Pike                 =   2.03 sec (7 tests)
Piro                 =  26.75 sec (12 tests)
ROL                  = 754.01 sec (153 tests)
RTOp                 =   9.47 sec (24 tests)
Rythmos              = 160.11 sec (83 tests)
SEACAS               =   8.02 sec (14 tests)
STK                  =  25.99 sec (12 tests)
Sacado               =  35.00 sec (292 tests)
Shards               =   0.53 sec (4 tests)
ShyLU_Node           =   0.50 sec (3 tests)
Stokhos              =  95.44 sec (75 tests)
Stratimikos          =  33.33 sec (40 tests)
Teko                 =  79.98 sec (19 tests)
Tempus               = 2233.98 sec (36 tests)
Teuchos              =  39.37 sec (137 tests)
ThreadPool           =   7.34 sec (10 tests)
Thyra                =  60.26 sec (81 tests)
Tpetra               = 165.46 sec (162 tests)
TrilinosCouplings    =  58.24 sec (24 tests)
Triutils             =   2.32 sec (2 tests)
Xpetra               =  42.53 sec (18 tests)
Zoltan               = 198.33 sec (19 tests)
Zoltan2              = 134.63 sec (101 tests)

Total Test time (real) = 912.05 sec

Total time for MPI_RELEASE_DEBUG_SHARED_PT = 107.59 min
```

It looks like experimental code in Xpetra and MueLu was enabled from looking at:

```
$ grep Experimental MPI_RELEASE_DEBUG_SHARED_PT/CMakeCache.txt  | grep "\(Xpetra\|MueLu\)"
MueLu_ENABLE_Experimental:BOOL=ON
Xpetra_ENABLE_Experimental:BOOL=ON
```

and:

```
$ find MPI_RELEASE_DEBUG_SHARED_PT/packages/xpetra -name "*config*" -exec grep -nHi "experimental" {} \;
MPI_RELEASE_DEBUG_SHARED_PT/packages/xpetra/sup/Xpetra_config.hpp:24:#define HAVE_XPETRA_EXPERIMENTAL
MPI_RELEASE_DEBUG_SHARED_PT/packages/xpetra/src/Xpetra_config.hpp:24:#define HAVE_XPETRA_EXPERIMENTAL

$ find MPI_RELEASE_DEBUG_SHARED_PT/packages/muelu/ -name "*config*" -exec grep -nHi "experimental" {} \;
MPI_RELEASE_DEBUG_SHARED_PT/packages/muelu/src/MueLu_config.hpp:20:#define HAVE_MUELU_EXPERIMENTAL
MPI_RELEASE_DEBUG_SHARED_PT/packages/muelu/src/Interface/MueLu_config.hpp:20:#define HAVE_MUELU_EXPERIMENTAL
```

So that is good evidence that experimental code in Xpetra and MueLu actually did get enabled.

</details>

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Note that the current auto PR builds don't test with this configuration yet so the auto PR builds will not be testing anything about this PR.

**Comment by bartlettroscoe** [comment]
> I honestly have really mixed feelings about enabling experimental code for these builds. I really think this needs to go back to the @trilinos/muelu and @trilinos/xpetra teams and we need to make sure expectations are consistent between all stakeholders. That said, it seems this is the right short-term solution.

@jwillenbring, I agree 100% on both counts, but this is not our call.  This is an issue that ATDM customers and Trilinos developers need to work out.

**Comment by jwillenbring** [comment]
> @jwillenbring, I agree 100% on both counts, but this is not our call. This is an issue that ATDM customers and Trilinos developers need to work out.

@bartlettroscoe, I agree with your statement, but I feel an obligation in the medium-term to uphold the definition of experimental code. It is not a meaningful designation if the purpose for the category is not respected.

**Comment by csiefer2** [comment]
#stillnotagoodidea

**Comment by mhoemmen** [comment]
@jwillenbring wrote:
> It is not a meaningful designation if the purpose for the category is not respected.

My guess is that Somebody told Somebody that they needed these flags in order to build stuff, and so the flags got turned on as Mystic Fairy Dust to sprinkle over the build.  I suspect they don't need the flags.

**Comment by csiefer2** [comment]
@mhoemmen I suspect this will all get undone next week once we establish that they don't need the Mystic Fairy Dust.

**Comment by jwillenbring** [comment]
We should establish if these flags are needed or not. I really do not want to turn on experimental code with the expectation people fix issues with it. That needs to be negotiated with the package teams.

If we do this, we need to target weeks, not months or years to resolving this and turning the experimental flags off.

**Comment by mhoemmen** [comment]
@jwillenbring My personal view is that if they can't identify what code they need that they think is experimental, then they don't need experimental code.

**Comment by bartlettroscoe** [comment]
> We should establish if these flags are needed or not. I really do not want to turn on experimental code with the expectation people fix issues with it. That needs to be negotiated with the package teams.
> 
> If we do this, we need to target weeks, not months or years to resolving this and turning the experimental flags off.

@jmgate, with your involvement with EMPIRE, could you answer if the EMPIRE build of Trilinos still needs these experimental flags?  They are still in the official EMPIRE configuration when I looked today.

I looked at the SPARC configurations of Trilinos and it looks like SPARC does not enable these options.

**Comment by jmgate** [comment]
Yeah let me pull all the latest updates and try building without them.

**Comment by tawiesn** [comment]
Thanks, @rppawlo @bathmatt @eric-c-cyr. I just looked through the MueLu stratimikos interface and can state that you definitely do not use the Q2Q1 algorithms which are guarded by the experimental flag.

Furthermore, if you mean the native Kokkos support for threading in MueLu, there are separate compile flags for it (MueLu_ENABLE_Kokkos_Refactor...).

So, i am 99.9% sure that there is no need for the Experimental flags any more even though i know nothing about EMPIRE, SPARC, etc...

If i were you, i would just give it a try...

**Comment by prwolfe** [comment]
This is good - actually enabling experimental code in the PR build is well beyond the scope of it's intent.  Thanks for checking into this.

**Comment by rppawlo** [comment]
> I suspect this will all get undone next week once we establish that they don't need the Mystic Fairy Dust.

I started digging around in Drekar. Here's a commit from April 2017 that specifically enabled it for an internal problem. So it was required about a year ago. Unfortunately I don't know the details of why. But if the mini-em tests are all passing I guess we are safe?

```
S1002730:DrekarBase rppawlo$ git show 7aaca740afaa1b5fcfbd7f
commit 7aaca740afaa1b5fcfbd7ffc79530db919e94182
Author: Eric C. Cyr <eccyr@sandia.gov>
Date:   Mon Apr 3 17:05:31 2017 -0600

    Adding MueLu/Experimental builds
    
    Only for RHEL6

diff --git a/drekar/build_scripts/RHEL6/configure-drekar.sh b/drekar/build_scripts/RHEL6/configure-drekar.sh
index 94c79584..a2962cc6 100755
--- a/drekar/build_scripts/RHEL6/configure-drekar.sh
+++ b/drekar/build_scripts/RHEL6/configure-drekar.sh
@@ -82,9 +82,9 @@ cmake \
 -D Trilinos_ENABLE_STKClassic:BOOL=OFF \
 -D Trilinos_ENABLE_STKMesh:BOOL=ON \
 -D Trilinos_ENABLE_STKUtil:BOOL=ON \
--D Trilinos_ENABLE_STKSearch:BOOL=ON \
 -D Trilinos_ENABLE_STKTopology:BOOL=ON \
--D Trilinos_ENABLE_STKTransfer:BOOL=ON \
+-D Trilinos_ENABLE_STKSearch:BOOL=OFF \
+-D Trilinos_ENABLE_STKTransfer:BOOL=OFF \
 -D Trilinos_ENABLE_STKDoc_tests:BOOL=OFF \
 -D Trilinos_ENABLE_STKUnit_tests:BOOL=OFF \
 -D Trilinos_ENABLE_STKUnit_test_utils:BOOL=OFF \
@@ -93,6 +93,10 @@ cmake \
 -D Trilinos_ENABLE_SHADOW_WARNINGS=OFF \
 -D Trilinos_ENABLE_OpenMP=${USE_OPENMP} \
 -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
+-D Trilinos_ENABLE_MueLu:BOOL=ON \
+-D MueLu_ENABLE_Experimental:BOOL=ON \
+-D Trilinos_ENABLE_Amesos2:BOOL=ON \
+-D Xpetra_ENABLE_Experimental:BOOL=ON \
 -D Phalanx_KOKKOS_DEVICE_TYPE:STRING="${NODE_TYPE}" \
 -D Panzer_ENABLE_FADTYPE:STRING="Sacado::Fad::DFad<RealType>" \
 -D Panzer_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
```

**Comment by mhoemmen** [comment]
@rppawlo Thanks for checking!  I'm not snarking at you :-) .  I'm happy that we're getting this worked out.  It always scares me how many build options Trilinos has; it's too hard to test them all, so it's really scary when we find out by surprise that someone is using an option that we labeled with a deliberately off-putting name like "Experimental."

**Comment by rppawlo** [comment]
Thanks @mhoemmen :) Definitely agree about the build options. I only bring this up because sometime in the last year I had to help debug some code and the answer was enable muelu experimental. We think it may have had to do with threading support at the time. Probably has been promoted out of experimental now.

**Comment by bartlettroscoe** [comment]
> So is it correct to say that if we get good news from @jmgate then we do not need to even consider enabling these options?

I think to be safe, the EMPIRE builds scripts for Trilinos need to remove these options and then build Trilinos and EMPIRE on all of their platforms to verify this.  Then we can remove these.

**Comment by jmgate** [comment]
Building now&hellip;

**Comment by jmgate** [comment]
Trilinos and all of EMPIRE build and test fine for me without these experimental flags.

<details>
<summary><b>Configuration</b> (click to expand)</summary>
<ul>
<li>anaconda3-5.1.0</li>
<li>boost-1.66.0</li>
<li>cmake-3.11.0</li>
<li>gcc-7.3.0</li>
<li>hdf5-1.10.1</li>
<li>lapack-3.8.0</li>
<li>netcdf-4.6.0</li>
<li>openmpi-3.0.0</li>
<li>papi-5.6.1.0</li>
<li>parallel-netcdf-1.9.0</li>
<li>parmetis-4.0.3</li>
<li>zlib-1.2.11</li>
</ul>
</details>

**Comment by bartlettroscoe** [comment]
> Trilinos and all of EMPIRE build and test fine for me without these experimental flags.

@jmgate, can you confirm that `-DXpetra_ENABLE_Experimental=ON` and `-DMueLu_ENABLE_Experimental=ON` have been removed from the `EM-Plamsa/BuildScripts/ALL/configure-trilinos.sh` file on the 'develop' branch of that repo?   Once that is done and confirmed that it works on all the platforms where EMPIRE builds, then we can remove these options from our configuration.  It is important that we match what ATDM customers are using.  Otherwise, something could sneek into MueLu experimental that EMPIRE relies on and then our automated builds will match catch that.

**Comment by jmgate** [comment]
Removed from BuildScripts&hellip;

**Comment by mhoemmen** [comment]
Thanks @jmgate !  Thanks all! :-D  It's always good news to see the build script get shorter :-D

**Pull request merged**
