### PR TITLE
Tool to automate creation of GitHub Issue for PR test failures

### PR DESCRIPTION
**Pull request by bartlettroscoe**
This tool makes it easy to create the Markdown for a new GitHub issue for failing Trilinos PR tests.

I will mention this tool in my TUG talk tomorrow.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@jhux2, @csiefer2, @rppawlo,

Can one of you please approve this PR so it can merge.  The only impact it will have is adding a new test to the package TrilinosFrameworkTests (which will be tested by the PR tester on all platforms).

**Review by jhux2 — APPROVED** [review]
lgtm

**Review by rppawlo — APPROVED** [review]

**Comment by e10harvey** [comment]
CC: @trilinos/framework

**Comment by bartlettroscoe** [comment]
@jhux2 or @rppawlo, can one of you please re-approve?  I was a bit hasty light night and committed a broken CMakeLists.txt file causing a test failure.  (NOTE, only the ats2 PR build took longer than 10 sec, see #11205.)

**Review by jhux2 — APPROVED** [review]
lgtm

**Pull request merged**
