### PR TITLE
Panzer: fix periodic bc matcher for HDiv gid passing 32bit int limit

### PR DESCRIPTION
**Pull request by rppawlo**
@trilinos/panzer 

## Motivation

See issue #10029 

## Stakeholder Feedback

Fixes issue

## Testing

New test added: ```panzer/adapters-stk/test/periodic_bcs/periodic_32bit_int_limit.cpp```

### CODE REVIEW

**Review by dridzal — DISMISSED** [review]
The changes to the integer types look good.

Denis

**Comment by rppawlo** [comment]
@trilinos/framework  - looks like the PR testing is stuck weaver. Could someone take a look?

**Comment by dridzal** [comment]
@rppawlo : it looks like there are build failures (unused variable) and test failures (intel, index ranges appear incorrect).

**Review by dridzal — APPROVED** [review]
This takes care of the unused variable warning.

**Comment by dridzal** [comment]
@rppawlo : There is also a failing test with Intel 17

https://testing.sandia.gov/cdash/test/110334736

It is not clear to me what the issue is, and why it only appears with this compiler.

**Comment by rppawlo** [comment]
@dridzal - yes - looking into that now.

**Review by dridzal — APPROVED** [review]
This is a reasonable workaround.

**Pull request merged**
