### PR TITLE
Tempus: StepperRKObserver - ensure no-null observer are added to the

### PR DESCRIPTION
**Pull request by sconde**
composite observer

This was causing segfault in many applications

@trilinos/tempus 

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by sconde** [comment]
@jmgate Can you let me know when this makes it through the pipeline please

**Comment by rppawlo** [comment]
@sconde - the autotester won't run, the PR conflicts with current trilinos. You will need to resolve the conflicts first.

**Comment by sconde** [comment]
> @sconde - the autotester won't run, the PR conflicts with current trilinos. You will need to resolve the conflicts first.

conflicts resolved. Can you please review the PR again?

**Comment by jmgate** [comment]
@sconde, this is in EMPIRE's fork now.

**Pull request merged**
