### PR TITLE
Kokkos snapshot

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos 
@trilinos/kokkos-kernels 

## Motivation
Final 3.5.0 snapshot containing updates and fixes for issues reported by users

## Testing
Autotester

### CODE REVIEW

**Comment by ndellingwood** [comment]
@rppawlo @PhilMiller this PR contains the DynamicView updates reported by kokkos/kokkos#4517
@etphipp this contains the kokkos update to modify the local deep copy signature needed for your sacado PR #9917 
@kddevin this contains the Kokkos::sort update related to kokkos/kokkos#4526 and the zoltan2 issue reported in #9909 
@e10harvey this contains a fix for nvcc_wrapper that may be related to and resolve the NVCC_WRAPPER_TMPDIR issues you reported in #9951

**Review by crtrott — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Review by lucbv — APPROVED** [review]
Looks good to me, thanks @ndellingwood

**Comment by crtrott** [comment]
why doesn't this test? @jwillenbring

**Comment by jwillenbring** [comment]
@crtrott We had machine issues last week. We feel those issues might be resolved, but there is a huge backlog of PRs.

**Pull request merged**
