### PR TITLE
Intrepid2: Set correct execution spaces for Projection tests

### PR DESCRIPTION
**Pull request by mperego**
@trilinos/intrepid2 

## Motivation
As exposed in #7435, new tests were added in #7201 with incorrect execution spaces. This PR fixes that.

Related to #7435.

### CODE REVIEW

**Comment by mperego** [comment]
@prwolfe Our old timing out friends are here. Because of copy and paste errors, some of the tests that they were supposed to run on Cuda were running on Serial. This PR fixes that. However, non of the new tests are timing out.  
This seems to becoming a recurrent issue. Would it make sense to increase the threshold for tests timing out?

**Comment by mperego** [comment]
@trilinos/framework Do you understand what's going on here? Is ride angry at me? This seems personal :P
Most of the tests that timeout are actually running with the RUN_SERIAL option.. and none of them has been added/changed in this PR.
Thanks.

**Comment by mperego** [comment]
@bartlettroscoe How does `RUN_SERIAL` work? Is it set correctly here?
https://github.com/trilinos/Trilinos/blob/9bf8db10d5319a466b8c24eced5f85bb71e1c2f7/packages/intrepid2/unit-test/Projection/Cuda/CMakeLists.txt
I tried to run it on ride but they don't seem to run serially when I use ctest -j8. Thanks.

**Comment by mperego** [comment]
So I tried to reproduce the issue by following the wiki. Here's what I did on ride
```
source $TRILINOS_DIR/cmake/std/sems/PullRequestCuda9.2TestingEnv.sh
cmake -C ~/trilinos-src/cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake -GNinja -DTrilinos_ENABLE_Intrepid2=ON $TRILINOS_DIR
cd packages/intrepid2/unit-test/Projection/
make np=16
bsub -Is -n 8 -q rhel7F bash
```

Here is the output of `ctest`
```
Test project /ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection
      Start  1: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1
 1/20 Test  #1: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1 ....   Passed   23.96 sec
      Start  2: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TET_MPI_1
 2/20 Test  #2: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TET_MPI_1 ....   Passed    8.36 sec
      Start  3: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_QUAD_MPI_1
 3/20 Test  #3: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_QUAD_MPI_1 ...   Passed    1.76 sec
      Start  4: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TRI_MPI_1
 4/20 Test  #4: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TRI_MPI_1 ....   Passed    1.35 sec
      Start  5: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_HEX_MPI_1
 5/20 Test  #5: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_HEX_MPI_1 ........   Passed    3.04 sec
      Start  6: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_TET_MPI_1
 6/20 Test  #6: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_TET_MPI_1 ........   Passed    1.52 sec
      Start  7: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_QUAD_MPI_1
 7/20 Test  #7: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_QUAD_MPI_1 .......   Passed    0.56 sec
      Start  8: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_TRI_MPI_1
 8/20 Test  #8: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_TRI_MPI_1 ........   Passed    0.54 sec
      Start  9: Intrepid2_unit-test_Projection_Serial_Test_Convergence_HEX_MPI_1
 9/20 Test  #9: Intrepid2_unit-test_Projection_Serial_Test_Convergence_HEX_MPI_1 ................   Passed   22.10 sec
      Start 10: Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1
10/20 Test #10: Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1 ................   Passed   25.40 sec
      Start 11: Intrepid2_unit-test_Projection_Serial_Test_Convergence_QUAD_MPI_1
11/20 Test #11: Intrepid2_unit-test_Projection_Serial_Test_Convergence_QUAD_MPI_1 ...............   Passed    0.89 sec
      Start 12: Intrepid2_unit-test_Projection_Serial_Test_Convergence_TRI_MPI_1
12/20 Test #12: Intrepid2_unit-test_Projection_Serial_Test_Convergence_TRI_MPI_1 ................   Passed    0.61 sec
      Start 13: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1
13/20 Test #13: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1 ......   Passed  467.39 sec
      Start 14: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TET_MPI_1
14/20 Test #14: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TET_MPI_1 ......   Passed   55.95 sec
      Start 15: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD_MPI_1
15/20 Test #15: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD_MPI_1 .....   Passed   25.36 sec
      Start 16: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TRI_MPI_1
16/20 Test #16: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TRI_MPI_1 ......   Passed   15.90 sec
      Start 17: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_HEX_MPI_1
17/20 Test #17: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_HEX_MPI_1 ..................   Passed   38.43 sec
      Start 18: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TET_MPI_1
18/20 Test #18: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TET_MPI_1 ..................   Passed   31.01 sec
      Start 19: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_QUAD_MPI_1
19/20 Test #19: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_QUAD_MPI_1 .................   Passed    1.75 sec
      Start 20: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TRI_MPI_1
20/20 Test #20: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TRI_MPI_1 ..................   Passed    1.35 sec

100% tests passed, 0 tests failed out of 20

Label Time Summary:
Intrepid2    = 727.22 sec*proc (20 tests)

Total Test time (real) = 727.30 sec
```

and here is the output of `ctest -j8`
```
Test project /ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection
      Start 13: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1
      Start 14: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TET_MPI_1
      Start 17: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_HEX_MPI_1
      Start 18: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TET_MPI_1
      Start 10: Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1
      Start 15: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD_MPI_1
      Start  1: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1
      Start  9: Intrepid2_unit-test_Projection_Serial_Test_Convergence_HEX_MPI_1
 1/20 Test  #1: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_HEX_MPI_1 ....   Passed   46.74 sec
      Start 16: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TRI_MPI_1
 2/20 Test #10: Intrepid2_unit-test_Projection_Serial_Test_Convergence_TET_MPI_1 ................   Passed   54.37 sec
      Start  2: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TET_MPI_1
 3/20 Test  #9: Intrepid2_unit-test_Projection_Serial_Test_Convergence_HEX_MPI_1 ................   Passed   61.57 sec
      Start  5: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_HEX_MPI_1
 4/20 Test  #5: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_HEX_MPI_1 ........   Passed    6.40 sec
      Start  3: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_QUAD_MPI_1
 5/20 Test  #2: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TET_MPI_1 ....   Passed   20.61 sec
      Start 19: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_QUAD_MPI_1
 6/20 Test  #3: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_QUAD_MPI_1 ...   Passed    7.00 sec
      Start  6: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_TET_MPI_1
 7/20 Test  #6: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_TET_MPI_1 ........   Passed    4.34 sec
      Start 20: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TRI_MPI_1
 8/20 Test #18: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TET_MPI_1 ..................   Passed  104.71 sec
      Start  4: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TRI_MPI_1
 9/20 Test #20: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TRI_MPI_1 ..................   Passed   25.89 sec
      Start 11: Intrepid2_unit-test_Projection_Serial_Test_Convergence_QUAD_MPI_1
10/20 Test  #4: Intrepid2_unit-test_Projection_Serial_Test_InterpolationProjection_TRI_MPI_1 ....   Passed    7.72 sec
      Start 12: Intrepid2_unit-test_Projection_Serial_Test_Convergence_TRI_MPI_1
11/20 Test #11: Intrepid2_unit-test_Projection_Serial_Test_Convergence_QUAD_MPI_1 ...............   Passed    7.61 sec
      Start  7: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_QUAD_MPI_1
12/20 Test #12: Intrepid2_unit-test_Projection_Serial_Test_Convergence_TRI_MPI_1 ................   Passed    0.99 sec
      Start  8: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_TRI_MPI_1
13/20 Test  #7: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_QUAD_MPI_1 .......   Passed    0.81 sec
14/20 Test  #8: Intrepid2_unit-test_Projection_Serial_Test_DeRhamCommutativity_TRI_MPI_1 ........   Passed    0.59 sec
15/20 Test #19: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_QUAD_MPI_1 .................   Passed   45.97 sec
16/20 Test #17: Intrepid2_unit-test_Projection_Cuda_Test_Convergence_HEX_MPI_1 ..................   Passed  261.30 sec
17/20 Test #14: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TET_MPI_1 ......   Passed  421.98 sec
18/20 Test #13: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1 ......   Passed  594.18 sec
19/20 Test #16: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TRI_MPI_1 ......   Passed  555.09 sec
20/20 Test #15: Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD_MPI_1 .....   Passed  608.10 sec

100% tests passed, 0 tests failed out of 20

Label Time Summary:
Intrepid2    = 2835.96 sec*proc (20 tests)

Total Test time (real) = 608.11 sec
```

@bartlettroscoe (@brian-kelley ) here you can see that `RUN_SERIAL` does not seem to have an effect (if I understand correctly how it is supposed to work).

**Comment by bartlettroscoe** [comment]
@mperego, look in the generated `CTestTestfile.cmake` file in the build directory where that test is defined.  If you see the `RUN_SERIAL` property set there, then it is up to CTest to honor that.  (If you don't see it there, then we can fix that.)  If CTest is not running tests with the `RUN_SERIAL` property set one at a time, then we need to get help from Kitware.

**Comment by mperego** [comment]
@bartlettroscoe it does not seem to be defined
```
# CMake generated Testfile for 
# Source directory: /ascldap/users/mperego/trilinos-src-devel/packages/intrepid2/unit-test/Projection/Cuda
# Build directory: /ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1 "/ascldap/users/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpiexec" "-np" "1" "-map-by" "socket:PE=4" "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX.exe" "PrintItAll")
set_tests_properties(Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1 PROPERTIES  ENVIRONMENT "CTEST_KOKKOS_DEVICE_TYPE=gpus" FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Intrepid2" PASS_REGULAR_EXPRESSION "TEST PASSED" PROCESSORS "1" REQUIRED_FILES "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX.exe" RESOURCE_GROUPS "1,gpus:1")
add_test(Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TET_MPI_1 "/ascldap/users/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpiexec" "-np" "1" "-map-by" "socket:PE=4" "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TET.exe" "PrintItAll")
set_tests_properties(Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TET_MPI_1 PROPERTIES  ENVIRONMENT "CTEST_KOKKOS_DEVICE_TYPE=gpus" FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Intrepid2" PASS_REGULAR_EXPRESSION "TEST PASSED" PROCESSORS "1" REQUIRED_FILES "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TET.exe" RESOURCE_GROUPS "1,gpus:1")
add_test(Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD_MPI_1 "/ascldap/users/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpiexec" "-np" "1" "-map-by" "socket:PE=4" "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD.exe" "PrintItAll")
set_tests_properties(Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD_MPI_1 PROPERTIES  ENVIRONMENT "CTEST_KOKKOS_DEVICE_TYPE=gpus" FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Intrepid2" PASS_REGULAR_EXPRESSION "TEST PASSED" PROCESSORS "1" REQUIRED_FILES "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD.exe" RESOURCE_GROUPS "1,gpus:1")
add_test(Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TRI_MPI_1 "/ascldap/users/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpiexec" "-np" "1" "-map-by" "socket:PE=4" "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TRI.exe" "PrintItAll")
set_tests_properties(Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TRI_MPI_1 PROPERTIES  ENVIRONMENT "CTEST_KOKKOS_DEVICE_TYPE=gpus" FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Intrepid2" PASS_REGULAR_EXPRESSION "TEST PASSED" PROCESSORS "1" REQUIRED_FILES "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_TRI.exe" RESOURCE_GROUPS "1,gpus:1")
add_test(Intrepid2_unit-test_Projection_Cuda_Test_Convergence_HEX_MPI_1 "/ascldap/users/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpiexec" "-np" "1" "-map-by" "socket:PE=4" "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_Convergence_HEX.exe" "PrintItAll")
set_tests_properties(Intrepid2_unit-test_Projection_Cuda_Test_Convergence_HEX_MPI_1 PROPERTIES  ENVIRONMENT "CTEST_KOKKOS_DEVICE_TYPE=gpus" FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Intrepid2" PASS_REGULAR_EXPRESSION "TEST PASSED" PROCESSORS "1" REQUIRED_FILES "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_Convergence_HEX.exe" RESOURCE_GROUPS "1,gpus:1")
add_test(Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TET_MPI_1 "/ascldap/users/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpiexec" "-np" "1" "-map-by" "socket:PE=4" "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TET.exe" "PrintItAll")
set_tests_properties(Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TET_MPI_1 PROPERTIES  ENVIRONMENT "CTEST_KOKKOS_DEVICE_TYPE=gpus" FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Intrepid2" PASS_REGULAR_EXPRESSION "TEST PASSED" PROCESSORS "1" REQUIRED_FILES "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TET.exe" RESOURCE_GROUPS "1,gpus:1")
add_test(Intrepid2_unit-test_Projection_Cuda_Test_Convergence_QUAD_MPI_1 "/ascldap/users/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpiexec" "-np" "1" "-map-by" "socket:PE=4" "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_Convergence_QUAD.exe" "PrintItAll")
set_tests_properties(Intrepid2_unit-test_Projection_Cuda_Test_Convergence_QUAD_MPI_1 PROPERTIES  ENVIRONMENT "CTEST_KOKKOS_DEVICE_TYPE=gpus" FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Intrepid2" PASS_REGULAR_EXPRESSION "TEST PASSED" PROCESSORS "1" REQUIRED_FILES "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_Convergence_QUAD.exe" RESOURCE_GROUPS "1,gpus:1")
add_test(Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TRI_MPI_1 "/ascldap/users/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpiexec" "-np" "1" "-map-by" "socket:PE=4" "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TRI.exe" "PrintItAll")
set_tests_properties(Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TRI_MPI_1 PROPERTIES  ENVIRONMENT "CTEST_KOKKOS_DEVICE_TYPE=gpus" FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Intrepid2" PASS_REGULAR_EXPRESSION "TEST PASSED" PROCESSORS "1" REQUIRED_FILES "/ascldap/users/mperego/trilinos-pr-build/packages/intrepid2/unit-test/Projection/Cuda/Intrepid2_unit-test_Projection_Cuda_Test_Convergence_TRI.exe" RESOURCE_GROUPS "1,gpus:1")
set_directory_properties(PROPERTIES LABELS "Intrepid2")
```

**Comment by bartlettroscoe** [comment]
@mperego, as (not) shown in the documentation at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-add-executable-and-test

the `RUN_SERIAL` argument is not supported by the `TRIBITS_ADD_EXECUTABLE_AND_TEST()` function.

**Comment by bartlettroscoe** [comment]
@mperego,

I see the last PR test iteration passed.  But note that there are still two Intrepid2 tests that take over 6 minutes to run shown [here](https://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=7258435) showing:

Subproject | Name | Status | Time | Proc Time | Labels | Summary | Processors
-- | -- | -- | -- | -- | -- | -- | --
Intrepid2 | Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1 | Passed | 7m 49s 30ms | 7m 49s 30ms | Intrepid2 | Summary | 1
Intrepid2 | Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1 | Passed | 6m 12s 690ms | 6m 12s 690ms | Intrepid2 | Summary | 1

We saw those two tests also randomly timing out as noted in https://github.com/trilinos/Trilinos/issues/3276#issuecomment-643630688.

I will work on #7112 to allow tests like these to have `RUN_SERIAL` set for only problematic builds like this one.  For builds where we don't have problems like this, we are just unnecessarily extending the testing wall clock time and wasting CPU cores.

**Comment by mperego** [comment]
> @mperego,
> 
> I see the last PR test iteration passed. But note that there are still two Intrepid2 tests that take over 6 minutes to run shown [here](https://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=7258435) showing:
> Subproject 	Name 	Status 	Time 	Proc Time 	Labels 	Summary 	Processors
> Intrepid2 	Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1 	Passed 	7m 49s 30ms 	7m 49s 30ms 	Intrepid2 	Summary 	1
> Intrepid2 	Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1 	Passed 	6m 12s 690ms 	6m 12s 690ms 	Intrepid2 	Summary 	1
> 
> We saw those two tests also randomly timing out as noted in [#3276 (comment)](https://github.com/trilinos/Trilinos/issues/3276#issuecomment-643630688).
> 
> I will work on #7112 to allow tests like these to have `RUN_SERIAL` set for only problematic builds like this one. For builds where we don't have problems like this, we are just unnecessarily extending the testing wall clock time and wasting CPU cores.

Thanks. I'll consider reducing the length of thoes tests in the future. It is interesting to me that despite the shorter tests like  Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_QUAD_MPI_1 timeout. It's like  Intrepid2_unit-test_Projection_Cuda_Test_InterpolationProjection_HEX_MPI_1 is making the other InterpolationProjection tests run slowly.

**Pull request merged**
