### PR TITLE
Panzer add hip support

### PR DESCRIPTION
**Pull request by rppawlo**
@trilinos/panzer 

## Motivation

Support HIP backend

### CODE REVIEW

**Review by etphipp — APPROVED** [review]

**Comment by rppawlo** [comment]
@e10harvey - this is the new PR that replaces #10129 .

I think I did do a force push to the previous PR. I usually do this after we get reviews back on the PR and have to make requested changes. Has something changed in PR testing that now prevents a force push?

**Comment by rppawlo** [comment]
@e10harvey @ZUUL42 - the new PR also failed with the same issue on cuda.

**Comment by ZUUL42** [comment]
We have opened an internal TRILINOSHD-72 ticket for this and will report back when we have something.

**Comment by e10harvey** [comment]
@rppawlo: It looks like the cuda errors related to packages/framework are finally resolved. Please see this [CDash Link](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=63&value1=Pull%20Request&field2=buildname&compare2=63&value2=PR-10187) for the most recent status.

**Review by etphipp — APPROVED** [review]

**Comment by rppawlo** [comment]
@trilinos/framework - Can you take a look at the failures from last night in https://github.com/trilinos/Trilinos/pull/10187#issuecomment-1050490349 ? All builds failed with "Status: Error", but when I look at the cdash site it looks like everything passed except cuda. The result for cuda reads:
```
    ...............................Build was aborted
Aborted by James M Willenbring
Archiving artifacts
[Checks API] No suitable checks publisher found.
Finished: ABORTED
```
 Is this an issue with the PR testing framework? I tried a retest this morning and it reported back that it timed out waiting for the clang build to start.

**Comment by ZUUL42** [comment]
@rppawlo, I don't see an immediately apparent reason for this behavior, but we're looking into it.

The Cuda builds currently report to [trilinos-cdash.sandia.gov](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-10187&field2=buildstamp&compare2=63&value2=Pull%20Request).

**Comment by etphipp** [comment]
Yay!!!!

**Pull request merged**
