### PR TITLE
TPLs: Add ROCTHRUST

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/framework @sebrowne @bartlettroscoe 

## Motivation

Add `ROCTHRUST` TPL support

## Testing
I confirmed configuration of kokkos@develop (pre-4.3.0 release) is successful with these changes, and with ROCTHRUST added to `LIB_OPTIONAL_TPLS`, on Caraway with rocm/5.6.1; build in progress

### CODE REVIEW

**Comment by masterleinad** [comment]
Does `Trilinos` care if `Kokkos` uses `rocThrust` under the hood? Does this TPL need to be exposed in `Trilinos`?

**Comment by ndellingwood** [comment]
> Does `Trilinos` care if `Kokkos` uses `rocThrust` under the hood? Does this TPL need to be exposed in `Trilinos`?

@masterleinad maybe not, but I wasn't sure how else to workaround the issues I was seeing here https://github.com/kokkos/kokkos/pull/6871#issuecomment-1996263156 (besides disabling rocthrust in Kokkos by default in Hip builds of Trilinos)

**Comment by masterleinad** [comment]
Yes, as I said before, I would prefer if we let `Kokkos` handle its (or at least this) TPLs itself if bundled. The respective `Kokkos` CMake option should then be used. All this should work better with #11779 and I would prefer just disabling `rocThrust` support for `Trilinos` (which implies not getting improved performance for `sort` and sort_by_key` until then).

**Comment by ndellingwood** [comment]
@masterleinad good point. I closed https://github.com/kokkos/kokkos/pull/6880 (adding ROCTHRUST as optional tpl lib), but I will leave this PR open for now as I think it should be orthogonal to Kokkos use and internal management of rocthrust as TPL (please correct me if I'm misunderstanding)

**Comment by masterleinad** [comment]
> I will leave this PR open for now as I think it should be orthogonal to Kokkos use and internal management of rocthrust as TPL (please correct me if I'm misunderstanding)

If `Trilinos` is not using `rocThrust` directly (and we disable rocThrust support in the `Kokkos` configuration when configuring from within `Trilinos`), I see little point in adding TPL support here. 
Ultimately, it comes down to how we want Trilinos and Kokkos to interact for shared TPLs going forward anyway. Ideally `Trilinos`/`TriBITS` would just defer to `Kokkos` for any shared TPL.

**Comment by ndellingwood** [comment]
> If `Trilinos` is not using `rocThrust` directly (and we disable rocThrust support in the `Kokkos` configuration when configuring from within `Trilinos`), I see little point in adding TPL support here.

@masterleinad yeah that's a good point; no sense adding additional support and potential testing fallout etc. for something not being used. Closing

**Comment by cwpearson** [comment]
Lack of rocThrust support in trilinos finally bit us in KokkosSparse::sort_crs_matrix. Can we revive this effort to allow Kokkos+Trilinos to use rocThrust one way or another?

**Pull request closed without merging**
