### PR TITLE
Tpetra: Fix #4344 & ETI-OFF build errors

### LINKED ISSUE #4344: Tpetra::DistObject: DualView arguments have wrong types
@trilinos/tpetra @kyungjoo-kim 

This concerns the following DistObject virtual methods that its subclasses must implement:

  - copyAndPermuteNew
  - packAndPrepareNew
  - unpackAndCombineNew

As of PR #4328, we have clarified how `DistObject::doTransferNew` expects these methods to behave, with respect to their DualView parameters.  Export and Import setup is responsible for ensuring that `permuteToLIDs`, `permuteFromLIDs`, `exportLIDs`, and `remoteLIDs` are sync'd on both host and device.  Thus, the above methods need not sync any of these four DualViews.  As a result, their type `const DualView<const LO*, buffer_device_type>&` is correct.  (`const DualView&` means you can't sync them; `DualView<const LO*, ...>` means you can't modify their entries.)

PR #4328 further clarifies that `packAndPrepareNew` may fill its `exports` and `numPacketsPerLID` DualView parameters wherever the subclass likes, either on host or device.  It is not responsible for sync'ing either of these two DualViews to any particular place; `DistObject::doTransferNew` must sync them wherever it needs them to be.  Similarly, `unpackAndCombineNew` may unpack received data (`imports` and `numPacketsPerLIDs`) wherever it wants, either on host or device, but is responsible for sync'ing them wherever it needs them.  `DistObject::doTransferNew` is not responsible for sync'ing them.

I justify the previous paragraph as follows:

  - Avoid unnecessary syncs to host, if the subclass knows how to unpack on device
  - Separation of concerns between communication and pack / unpack

This imposes the following requirements on `exports`, `imports`, and `numPacketsPerLIDs`:

  1. `DistObject::doTransferNew` allocates the `numPacketsPerLIDs` argument when it calls `packAndPrepareNew`, but `packAndPrepareNew` must allocate the `exports` output argument.  Thus, subclasses cannot reallocate `numPacketsPerLID`.
  2. `DistObject::doTransferNew` allocates the `imports` and `numPacketsPerLIDs` arguments when it calls `unpackAndCombineNew`; subclasses cannot reallocate them.
  3. Subclasses need to be able to sync any of these arrays wherever they like.
  4. `packAndPrepareNew` implementations access `exports` and `numPacketsPerLIDs` in write-only fashion.
  5. `unpackAndPrepareNew` implementations technically only need read-only access to `imports` and `numPacketsPerLIDs`.  However, `DistObject::doTransferNew` only accesses them in write-only fashion before calling `unpackAndPrepareNew`, and doesn't access them afterwards.  Thus, `unpackAndPrepareNew` implementations could freely write to these arrays, e.g., to use them as scratch space.

This means that the correct type of `imports` and `numPacketsPerLIDs` is `DualView<T*, ...>`.

  - Can't have `DualView<const T*, ...>`, because that would forbid sync'ing.
  - Can't have `const DualView&` or `const DualView`, because that would forbid sync'ing.
  - Can't have `DualView&`, because that would expose DistObject's internal DualViews to reallocation by subclasses.  Passing by value means that even if the subclass reallocates, the caller won't see that.  It's just like passing `double*` into a function, instead of `double*&`.

Currently, these arrays have type `const DualView<const T*, ...>&`.  This makes implementations do hacks in order to meet the above four requirements (esp. (2)).

I propose changing the types of `imports`, and `numPacketsPerLID` (as parameters to `packAndPrepareNew` and `unpackAndCombineNew`) from `const DualView<const T*, ...>&`, to `DualView<T*, ...>`.

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @ikalash 

1. Fix #4344, and document DistObject to clarify what DualViews can and should be sync'd
2. Fix build errors that show up only with ETI off: https://github.com/trilinos/Trilinos/issues/4334#issuecomment-462417954

## Related Issues

* Closes #4344

### CODE REVIEW

**Comment by mhoemmen** [comment]
This is my bad -- I'll look more closely at this one.

**Comment by mhoemmen** [comment]
I need to add a new commit to the PR to fix some issues, but otherwise this is almost done.

**Comment by mhoemmen** [comment]
@trilinos/tpetra This should be ready now.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> why change passing `DualView` by reference to passing by value in many places? (just curious)

That's the most correct expression of the semantics.

  - DistObject, the caller, does not permit callees to reallocate.  Hence, it does not pass by nonconst reference.
  - DistObject, the caller, _does_ permit callees to sync.  Hence, it cannot pass by const or const reference.  Furthermore, the DualView cannot be a view of const; it must be `DualView<T*, ...>`.  (DualView doesn't currently have a way to express "can't sync, but can't modify the entries."  Furthermore, in that case with DistObject, it's actually harmless for the callee to modify the entries.)

This only leaves passing the DualView by _nonconst_ _value_.

I'm imitating Ross' guide to the Teuchos Memory Management Classes, in particular the four pages of idioms.  The point is that the way that you pass the DualView exactly documents what callees can and cannot do with the DualView.  Readers can go through this elimination argument themselves to see what they can and cannot do.

**Comment by mhoemmen** [comment]
@tjfulle btw thanks for the review! :D

**Comment by mhoemmen** [comment]
@trilinos/framework I'm seeing stale test failures again :(

**Comment by mhoemmen** [comment]
@trilinos/framework This is fixing a build error with ETI off.  Would you consider a manual merge?

**Comment by mhoemmen** [comment]
@ikalash says this is blocking Albany's nightly testing against develop.

**Comment by mhoemmen** [comment]
It got through, yay!  @ikalash , this should fix Albany build errors with ETI off using Trilinos develop.

I don't recommend ever turning ETI off, and I think enabling `GO=unsigned long` at configure time would make DTK work with ETI on, but we still want to support the ETI off build.

**Comment by ikalash** [comment]
Thanks Mark!  I’ll look at whether we can get away with ETI on with DTK.

**Comment by mhoemmen** [comment]
@ikalash You'll almost certainly need to set `Tpetra_INST_INT_UNSIGNED_LONG:BOOL=ON`.

**Comment by ikalash** [comment]
@mhoemmen : I tried adding that option and it lets us build with code with ETI on + DTK.  This was not the case a few months ago - not sure what changed.  This is great news b/c we don't need to worry about a non-ETI build now, plus our code will build much faster.

**Comment by mhoemmen** [comment]
@ikalash Awesome! :-D  It does mean that you might be building more of Trilinos with `GO = unsigned long` than you were before, so if you encounter any interesting errors, please let us know.

**Comment by ikalash** [comment]
Ok, will do!

**Pull request merged**
