### PR TITLE
Framework: Enabling Ifpack2/MueLu PR tests w/ UVM off

### PR DESCRIPTION
**Pull request by csiefer2**
Issue: #10883
Tests: This
Stakeholder feedback: n/a

I opted for the "Turn Everything Back On and See What Doesn't Work" approach.

### CODE REVIEW

**Review by GrahamBenHarper — APPROVED** [review]

**Comment by ndellingwood** [comment]
I'm running into test failures like those in #11050 and https://github.com/trilinos/Trilinos/issues/10883 with PR #11047 (but unrelated to the changes in that PR). Can tests with previous failures in non-UVM Cuda builds be re-evaluated and disabled to prevent blocking PRs?
Related SEMS tickets opened:
https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-209
https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-210

**Comment by cgcgcg** [comment]
@ndellingwood Can you post what exactly is failing?

**Comment by jhux2** [comment]
Here are the errors from #11047:
```
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp: In instantiation of 'static Teuchos::RCP<Tpetra::CrsGraph<LO, GO> > tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::make_crs_graph(const Teuchos::RCP<const Teuchos::Comm<int> >&, const tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::StructuredBlock&, const tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::StructuredBlockPart&, bool, bool) [with Scalar = double; LO = int; GO = long long int]':
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:185:30:   required from 'void run_performance_test(const Input&) [with Scalar = double; LO = int; GO = long long int]'
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:365:37:   required from here
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp:357:18: error: '__T0' was not declared in this scope; did you mean '__y0'?
  357 |       auto sbppad(sbp);
      |             ~~~~~^~~~~~
      |             __y0
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp: In instantiation of 'static Teuchos::RCP<Tpetra::CrsGraph<LO, GO> > tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::make_crs_graph(const Teuchos::RCP<const Teuchos::Comm<int> >&, const tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::StructuredBlock&, const tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::StructuredBlockPart&, bool, bool) [with Scalar = std::complex<double>; LO = int; GO = long long int]':
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp:673:26:   required from 'static tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::Int tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::test_bcrs_matrix(const Teuchos::RCP<const Teuchos::Comm<int> >&, const tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::StructuredBlock&, const tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::StructuredBlockPart&, tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::Int, bool, bool) [with Scalar = std::complex<double>; LO = int; GO = long long int; tif_utest::BlockCrsMatrixMaker<Scalar, LO, GO>::Int = int]'
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:265:28:   required from 'LO run_teuchos_tests(const Input&, Teuchos::FancyOStream&, bool&) [with Scalar = std::complex<double>; LO = int; GO = long long int; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]'
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:320:36:   required from 'void Ifpack2BlockTriDi_Unit_UnitTest<Scalar, LO, GO>::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const [with Scalar = std::complex<double>; LO = int; GO = long long int; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]'
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:328:238:   required from here
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp:357:18: error: '__T0' was not declared in this scope; did you mean '__y0'?
  357 |       auto sbppad(sbp);
      |             ~~~~~^~~~~~
      |             __y0
```

and

```
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp:357:18: error: '__T0' was not declared in this scope; did you mean '__y0'?
  357 |       auto sbppad(sbp);
      |             ~~~~~^~~~~~
      |             __y0
/scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp: In 
```

**Comment by cgcgcg** [comment]
Isn't that the stuff that @csiefer2 fixed in #11043 ?

**Comment by ndellingwood** [comment]
Thanks @jhux2
In addition to the build errors above, there are unit test failures
```
Teko_DiagnosticLinearOp_test_MPI_1
MueLu_UnitTestsTpetra_kokkos_MPI_1
Ifpack2_AdditiveSchwarz_MPI_4
MueLu_UnitTestsTpetra_kokkos_MPI_4
MueLu_GeneralBlockSmoothing_MPI_4
MueLu_BlockSmoothingWithAverages_MPI_4
MueLu_DriverDiagonalModifications_MPI_1
```

some of which were previously reported failing in non-UVM builds #10883

**Comment by jhux2** [comment]
I think #11043 should fix these, no?

**Comment by ndellingwood** [comment]
The `Ifpack2_AdditiveSchwarz_MPI_4` failure is reported in #11050 and triaged back to #11049

**Comment by jhux2** [comment]
> In addition to the build errors above, there are unit test failures
> 
> ```
> Teko_DiagnosticLinearOp_test_MPI_1
> MueLu_UnitTestsTpetra_kokkos_MPI_1
> Ifpack2_AdditiveSchwarz_MPI_4
> MueLu_UnitTestsTpetra_kokkos_MPI_4
> MueLu_GeneralBlockSmoothing_MPI_4
> MueLu_BlockSmoothingWithAverages_MPI_4
> MueLu_DriverDiagonalModifications_MPI_1
> ```
> 
> some of which were previously reported failing in non-UVM builds #10883

Alright, I'll have a look at the MueLu tests.

**Comment by jhux2** [comment]
Quite a few things don't work with UVM off.   Reverting this PR should clear things up temporarily.

**Comment by cgcgcg** [comment]
I'm looking at the Teko one..

**Comment by csiefer2** [comment]
@jhux2 @cgcgcg Ross's recommended practice to do is (a) disable the failing tests so other PRs can merge (b) file an issue with the name of the test we disabled to remind us we disabled it

**Pull request merged**
