### PR TITLE
Teuchos fix

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/teuchos @trilinos/tpetra 

## Motivation
- Teuchos: Add missing function definitions for `setLongLongParameter`, `getLongLongParameter`.
- Teuchos: Remove declaration of `envSubstitute` that is missing a definition.
- Tpetra: Add a missing include.

### CODE REVIEW

**Comment by cgcgcg** [comment]
FYI @kliegeois

**Review by bartlettroscoe — COMMENTED** [review]
Given these functions had no definitions, I guess these are not being tested?

**Comment by cgcgcg** [comment]
@bartlettroscoe I have added them now to a previously existing test.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I have added them now to a previously existing test.

@cgcgcg, thanks for adding the tests!  I will wait to see this test code get run in the PR builds before I officially approve.

**Comment by bartlettroscoe** [comment]
The test results came back.  We can see updated test `TeuchosParameterList_ParameterList_test` running in 7 of the 8 PR builds [here](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-10958-test&field2=testname&compare2=65&value2=TeuchosParameterList_ParameterList_test) (where the 8th build runs just the framework Python tests).  However, only the first 1024 bytes of output is being displayed so I can't see any output that would indicate these new checks are running :-(

However, I was able to download the file:

* https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_clang-10.0.0/988/artifact/pull_request_test/Testing/Temporary/LastTest_20220831-1058.log

and in that file I can see:

```
62/3282 Testing: TeuchosParameterList_ParameterList_test_MPI_1
62/3282 Test: TeuchosParameterList_ParameterList_test_MPI_1

...

---------------------------------------------------
Use the nomember help function to access a long long as an int ...
---------------------------------------------------
Read value = 3 == 3 : passed
---------------------------------------------------
Use the nomember help function to access a long long as a double ...
---------------------------------------------------
Read value = 3 == 3 : passed
---------------------------------------------------
Use the nomember help function to access a long long as a std::string ...
---------------------------------------------------
Read value = "3" == "3" : passed
---------------------------------------------------
Use the nomember help function to access a long long as an long long ...
---------------------------------------------------
Read value = 3 == 3 : passed
---------------------------------------------------

...

  Max Iters : string = 3
   #  Accepted types: "int""long long", "double", "string".

...

```

Sad that I had to go to Jenkins to see what I needed to see.

**Review by bartlettroscoe — APPROVED** [review]
The changes look reasonable and the updated tests looks like it is running the updated code as described in https://github.com/trilinos/Trilinos/pull/10958#issuecomment-1233283382.

Thanks!

**Pull request merged**
