### PR TITLE
Zoltan2: Scotch and ParMETIS config time version check. (#160)

### PR DESCRIPTION
**Pull request by MicheldeMessieres**
@kddevin
I’ve modified FindTPLScotch and FindTPLParMETIS to check for Zoltan2 required versions.

Scotch requires: 6.0.3
ParMETIS requires: 4.0.3

There was already a compile time check for ParMETIS in TPLTraits.cpp which I removed since it would be redundant to the new config time check.

Also there was a compile time check for MPI and ParMETIS which I changed to a config time check.
Let me know if that is not desirable but it seems more appropriate to have them all together.

Proper behavior was checked using the following versions as tests:
Scotch: 6.0.4 and 5.1.12
ParMETIS: 4.0.3 and 3.2.0

### CODE REVIEW

**Comment by MicheldeMessieres** [comment]
@kddevin hi - fixes are pushed.

**Comment by bmpersc** [comment]
@MicheldeMessieres @kddevin there is now an file named "=" in the root directory of Trilinos that came in from this pull request. Is there any reason why I can't delete that file?

**Comment by krcb** [comment]
I don't think that file should be there, so please go ahead and remove.

**Comment by MicheldeMessieres** [comment]
@bmpersc I'll fix that in a moment.

**Comment by bmpersc** [comment]
@MicheldeMessieres I'll just remove it since I have direct access to the repo. I just wanted to make sure that there wasn't some need for it.

**Comment by MicheldeMessieres** [comment]
@bmpersc Thanks never noticed it

**Pull request merged**
