### PR TITLE
Tempus: Removed StepperStatus

### PR DESCRIPTION
**Pull request by ccober6**
@trilinos/tempus 

## Description

Removed StepperStatus as it duplicated SolutionStatus in many ways, and caused confusion.

Also added an pseudonym "Implicit Midpoint" for "IRK 1 Stage Theta Method".

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by ccober6** [comment]
@ikalash - I think this needs another review since I handled a simple merge conflict.  Can you re-review?  Thanks!

**Comment by ccober6** [comment]
@trilinos/framework - I am not sure why this PR is not getting through.  Can I get some help?  Thanks.

**Comment by ikalash** [comment]
Sorry about that.  If you send me the invite to review again, I will click "approved" instead of "comment".

________________________________

**Comment by allevin** [comment]
@ikalash I think you might be able to just update your review and change to accepted this PR's page in the upper right corner.

**Comment by ccober6** [comment]
@ikalash - you may be able to get to the "review" through the "Commits" tab at the top of the page.

**Comment by ikalash** [comment]
Done.

**Comment by ccober6** [comment]
@allevin - Thanks for the help.  

It would be clearer of the "Pre-Merge Inspection" would say something like "still waiting on an review approval", instead of "THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES".  It was not clear to me that the inspection meant an approved review.

**Comment by ccober6** [comment]
Yeah, it got through!

**Pull request merged**
