### PR TITLE
MueLu/Xpetra stuff

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
- Don't warn about mismatch of matrix block sizes, unless the user actually set a block size on the input matrix.
- Fix a bug in MLParameterListInterpreter #9690.
- Expose some additional args of `GetMatrixDiagonal`.

### CODE REVIEW

**Comment by cgcgcg** [comment]
Blocked by #9686.

**Review by jhux2 — DISMISSED** [review]
lgtm

**Comment by cgcgcg** [comment]
FYI @mperego

**Comment by mperego** [comment]
> FYI @mperego

Thanks!! And sorry I forgot to send you the error message.

**Comment by mayrmt** [comment]
@cgcgcg Do you see the possibility to cover the bug reported in #9690 with a test to prevent it in the future?

**Comment by cgcgcg** [comment]
@mayrmt I moderately improved the MueLu-ML tests by passing coordinates and nullspace through `MLParameterListInterpreter`. Unfortunately though, all our interface tests are using a 1D operator, so that particular bug would not have been caught.

**Comment by mperego** [comment]
@cgcgcg should we test this with Albany before it is merged, or are you relatively confident that this is not going to break Albany?

**Comment by cgcgcg** [comment]
@mperego I don't expect it to break Albany, but that doesn't mean it won't. However, I don't think that is is any more likely than any other PR to cause issues.

**Review by jhux2 — APPROVED** [review]
Zehr gut

**Pull request merged**
