### PR TITLE
Framework: Enabling the 'autocloser' github actions script

### LINKED ISSUE #8306: Framework:  Automating Issue / Pull Request Maintenance and Cleanup
Description
------------
Trilinos currently has over 1100 open issues and over 40 open pull requests. We have some open issues that date back to 2015 with no activity since 2017, and PR's that have also had no activity in over a year. This becomes difficult to manage from the framework side because it's hard to tell what issues have been abandoned and which ones should be kept around for some reason such as planning, documentation, etc.

This issue is to facilitate some discussion on my proposal to set up a [GitHub Action][1] which will automatically mark issues stale and close them out after long term inactivity.

Proposal
---------
I'd like to set up a GitHub Action to flag issues and pull requests as 'stale' and then close them based on the following rules:
1. Issues or Pull Requests with _no_ activity for 12 months will get a new flag: `FLAGGED FOR AUTO CLOSE`
2. If the Issue or PR has had no new activity after being flagged in (1) after another month, then the issue or PR is closed by the bot.
3. When being flagged or closed the bot can add a useful message to the comments explaining why it's being autoclosed.
4. Issues or PR's that we wish to be exempt from the bot can be given a label that would exempt it from this check.
    1. `NO AUTOCLOSE` - This could be a generic flag to exempt items from the bot.
    1. `DOCUMENTATION` - This could be something to track Issues that are used for tracking documentation.
    1. `PROJECT PLANNING` - This could be added for issues used for long term project planning type things.
    1. `CLOSED DUE TO INACTIVITY` - A label to apply to issues and PR's that were autoclosed by the bot (makes them more searchable).

The flag names here are mostly just a quick stab at what we might be able to do.  The main page for the particular runner we're looking at [is here][4]. It has quite a few control options. We can set a custom message that it will add to the comments for Issues or PR's when it's flagging them and when its closing them.  We can also add in a flag that would be applied to issues that are closed via the bot which might be useful if we need to dig through what was autoclosed.

I think we can iterate on what Labels we might want to use to exempt things from the bot and how long we might want to give before marking stuff for removal.  I had thought 1 year to flagging and then an additional month before closing since we do have things that stick around long term in Trilinos so enforcing a policy that people should touch issues and PR's at least once a year if they wish to keep them around isn't a huge ask. Adding in the ability to _explicitly_ exempt items from the bot also benefits us because those issues would become more easily searched.

I have a test repository to play around with the tool that marks things stale after 1 day and closes them after another day if they remain inactive. If you're interested, the repo is [here][3] with this [example issue][2] that shows some of the messages and flags, etc.

Let us know what you guys think. :D 

Interested People
------------------
@mentioning folks from today's planning meeting that seemed engaged in this issue. Feel free to tag others you think who might be interested.
@ccober6 
@srajama1 
@maherou 
@csiefer2 
@kddevin 
@bartlettroscoe 
@jwillenbring 
@prwolfe 
@trilinos/framework 

[1]: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions
[2]: https://github.com/william76/workflowTest/issues/7
[3]: https://github.com/william76/workflowTest/
[4]: https://github.com/actions/stale/

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework 

This PR enables the Issue/PR autocloser action for Trilinos.

## Related Issues
* Closes #8306

See #8306 for detailed information.

### CODE REVIEW

**Comment by william76** [comment]
FYI @prwolfe @jwillenbring

**Review by prwolfe — APPROVED** [review]

**Comment by william76** [comment]
@prwolfe any word on the issues with Ride?

**Comment by prwolfe** [comment]
No, won't even let me log in at this point. The queue on vortex is open again however. But that doesn't help this PR I'm afraid.

**Comment by william76** [comment]
> No, won't even let me log in at this point. The queue on vortex is open again however. But that doesn't help this PR I'm afraid.

Anything we can do? Should we disable the Ride builds (for now) or just wait till it clears up?

@jwillenbring @prwolfe should we resurrect the conversation about having a build-only test for CUDA that works on that special machine called: **`not a testbed`** ?

**Comment by jwillenbring** [comment]
I put a retest flag on this since ride is back up.

@william76 as far as a cuda build-only test, I am hoping that getting weaver and vortex online for our testing could help us mitigate the impact of one machine going down. It remains a valid point though. We could do build only for PR for example.

**Pull request merged**
