### PR TITLE
Correct proxy pattern for pip

### PR DESCRIPTION
**Pull request by prwolfe**
was http://www... now needs http://user:nopass@www...

@trilinos/framework 

## Motivation
A change in the proxy setting from SNL require adding a bit to the pip fetch line

### CODE REVIEW

**Review by jwillenbring — APPROVED** [review]
Looks good. Thanks for investigating the issue.

**Comment by prwolfe** [comment]
> Looks good. Thanks for investigating the issue.

Thanks to @e10harvey for pointing me in the right direction!

**Review by e10harvey — APPROVED** [review]
Thanks, @prwolfe !

**Review by jwillenbring — APPROVED** [review]
Sounds good as discussed at Stand-up.

**Comment by cgcgcg** [comment]
@trilinos/framework Can this PR be prioritized? Cause all other PRs fail until this one goes in, right?

**Comment by cgcgcg** [comment]
@prwolfe It appears that error is still there, but now it's simply ignored. Is this safe?

**Comment by prwolfe** [comment]
Safe?

This error is not checking the code, it’s plumbing. We are still looking at the issue and will fix it as soon as we can, but holding up everyone while I get there is not a good anser. The regex I used will avoid test failures but not catch the PIP errors. So it’s a small risk for a short term.

Paul

**Comment by prwolfe** [comment]
> @prwolfe It appears that error is still there, but now it's simply ignored. Is this safe?

I want to know what the intel 17 build failure is about ?

**Comment by jhux2** [comment]
@gsjaardema might know?  The file that fails seems to change.


https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-&field2=buildname&compare2=63&value2=test-Trilinos_pullrequest_intel_17.0.1&field3=buildstarttime&compare3=83&value3=NOW-14days

**Comment by cgcgcg** [comment]
In particular, is it possible that this is a residual from a previous test of #8637?

**Comment by prwolfe** [comment]
> In particular, is it possible that this is a testing residual from a previous test of #8637?

I think so and I set the flag for future testing to clean the build space.

@trilinos/framework - can I get a second person from the team to look at this and evaluate if I should force push it to get PR's moving? Honestly I can't see how that build failure could come from this code. If this was not blocking the entire PR system I would say no to a force, but at this point perhaps??

**Comment by jwillenbring** [comment]
> > In particular, is it possible that this is a testing residual from a previous test of #8637?
> 
> I think so and I set the flag for future testing to clean the build space.
> 
> @trilinos/framework - can I get a second person from the team to look at this and evaluate if I should force push it to get PR's moving? Honestly I can't see how that build failure could come from this code. If this was not blocking the entire PR system I would say no to a force, but at this point perhaps??

@prwolfe Given the extreme situation we are facing, if this currently running testing attempt fails, I think we can force push as you suggest. This is solely to fix the proxy so other tests don't fail.

**Comment by prwolfe** [comment]
> @prwolfe Given the extreme situation we are facing, if this currently running testing attempt fails, I think we can force push as you suggest. This is solely to fix the proxy so other tests don't fail.

Done

**Comment by cgcgcg** [comment]
Thanks @prwolfe!

**Pull request merged**
