### PR TITLE
[Shyu/Tacho] Tacho GPU tasking

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
This PR provides GPU tasking capability in Tacho (task based sparse direct cholesky). 

- this PR is based on recent addition/fix on Kokkos_Cuda_Task files
- thus, the PR shoul be tested when kokkos promotion to trilinos happens 
- the patch is included in the kokkos issue 1354. Some patch update is already done in kokkos.
[https://github.com/kokkos/kokkos/issues/1354](url)

## Description

- kokkos cuda task completes: single, per team, per thread, team broadcast, etc.
  - these changes should be unified with kokkos cuda team interface but it is not done yet.
- team level blas lapack: this is the main performance bottle neck. I put a naive implementation but it should be improved. 
- this code changes enable gpu tasking but it does not consider current code optimization on host architectures. as a side effect, it can slow down host version of the code. 

## Motivation and Context

- tacho gpu code is related to a mile stone delivery in this year.

## How Has This Been Tested?

the code has unit tests with default execution spaces. so, it will be automatically tested with a gpu machine.

### CODE REVIEW

**Comment by ndellingwood** [comment]
@kyungjoo-kim to make sure the autotester does not continually check this until the next Kokkos promotion, can we add [WIP] to the title?

**Comment by ndellingwood** [comment]
Following merge into Trilinos and kokkos of PR kokkos/kokkos#1471 for resolution of kokkos/kokkos#1470, and update of this branch to resolve conflicts, this will be ready for auto-testing. 
Cuda8 tests pass with the Kokkos fixes.

**Comment by ndellingwood** [comment]
Fix by @ibaned submitted in Trilinos PR #2393, matching Kokkos PR kokkos/kokkos#1471

**Comment by ndellingwood** [comment]
@kyungjoo-kim I pulled this commit, merged with Trilinos develop branch after PR #2393 was pushed via checkin script - build completes and all tests pass :)

```
Test project /home/ndellin/trilinos-ssh/Trilinos/Build/TachoCuda8PR/packages/shylu/shylu_node/tacho/unit-test
    Start 1: ShyLU_NodeTacho_Tacho_TestUtil
1/7 Test #1: ShyLU_NodeTacho_Tacho_TestUtil ..............   Passed    6.16 sec
    Start 2: ShyLU_NodeTacho_Tacho_TestSerial_double
2/7 Test #2: ShyLU_NodeTacho_Tacho_TestSerial_double .....   Passed    7.49 sec
    Start 3: ShyLU_NodeTacho_Tacho_TestSerial_dcomplex
3/7 Test #3: ShyLU_NodeTacho_Tacho_TestSerial_dcomplex ...   Passed    6.20 sec
    Start 4: ShyLU_NodeTacho_Tacho_TestOpenMP_double
4/7 Test #4: ShyLU_NodeTacho_Tacho_TestOpenMP_double .....   Passed    6.15 sec
    Start 5: ShyLU_NodeTacho_Tacho_TestOpenMP_dcomplex
5/7 Test #5: ShyLU_NodeTacho_Tacho_TestOpenMP_dcomplex ...   Passed    7.29 sec
    Start 6: ShyLU_NodeTacho_Tacho_TestCuda_double
6/7 Test #6: ShyLU_NodeTacho_Tacho_TestCuda_double .......   Passed    7.95 sec
    Start 7: ShyLU_NodeTacho_Tacho_TestCuda_dcomplex
7/7 Test #7: ShyLU_NodeTacho_Tacho_TestCuda_dcomplex .....   Passed    7.78 sec

100% tests passed, 0 tests failed out of 7
```

We can remove WIP

**Comment by kyungjoo-kim** [comment]
@ndellingwood 

I rebased it and pushed so that it is meageable. We can wait until auto tester finished.

**Comment by ndellingwood** [comment]
@kyungjoo-kim Is it possible to return to previous state and try a `merge --no-ff`?

**Comment by kyungjoo-kim** [comment]
@ndellingwood it is possible but I am not sure if it is right way to do. 
@bartlettroscoe Did we do anything wrong in this PR update ?

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe There used to be some merge conflict with rebase blah blahs... and github disables merge pull request button and it said we need to manually merge this PR to develop. So I did the following things:
```
git checkout --track tacho-gpu // in my repo
git fetch upstream
git merge upstream/develop
git pull --rebase
git push
```
This add all the other old commits back to dec 2017. Now github allows me to merge this pull request. Are we safe to merge this PR based on the steps I listed above to resolve the merge conflict?

git checkout

**Comment by kyungjoo-kim** [comment]
@allevin What is failures of the above auto tester ?

**Comment by jmgate** [comment]
> Are we safe to merge this PR based on the steps I listed above to resolve the merge conflict?

No.  There are ~70 or so commits on this branch that don't belong there.

**Comment by jmgate** [comment]
Added the "AT:  WIP" label so @trilinos-autotester doesn't keep testing this.  Once you fix the branch you can remove that label.

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim, something is now right with this PR branch.  You can not/should not merge this as is.  I am not sure why your rebase was not successful but one warning sign is that if you rebased your topic branch correctly, it should have not allowed you to push with just `git push`.  You should of had to do `git push -f`.   I would have to see the state if your local git repo to know what happened.

I tried to rebase your branch on top of `github/develop` and I got a ton of conflicits:

```
$ cd Trilinos/

[rabartl@crf450 Trilinos (develop)]$ git remote add kyungjoo-kim git@github.com:kyungjoo-kim/Trilinos.git

[rabartl@crf450 Trilinos (develop)]$ git fetch kyungjoo-kim 
...

[rabartl@crf450 Trilinos (develop)]$ git checkout --track kyungjoo-kim/tacho-gpu 
Branch tacho-gpu set up to track remote branch tacho-gpu from kyungjoo-kim.
Switched to a new branch 'tacho-gpu'

[rabartl@crf450 Trilinos (tacho-gpu)]$ git remote -v | grep ^github
github  git@github.com:trilinos/Trilinos.git (fetch)
github  git@github.com:trilinos/Trilinos.git (push)

[rabartl@crf450 Trilinos (tacho-gpu)]$ git fetch github
remote: Counting objects: 12, done.
remote: Total 12 (delta 10), reused 10 (delta 10), pack-reused 2
Unpacking objects: 100% (12/12), done.
From github.com:trilinos/Trilinos
   6bfb8dd..be11a2d  develop    -> github/develop
[rabartl@crf450 Trilinos (tacho-gpu)]$ git rebase github/develop 
First, rewinding head to replay your work on top of it...
Applying: Shylu/Tacho - CUDA unit tests
Using index info to reconstruct a base tree...
M       packages/shylu/shylu_node/tacho/src/TachoExp_NumericTools.hpp
M       packages/shylu/shylu_node/tacho/src/TachoExp_SupernodeInfo.hpp
M       packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholByBlocks.hpp
M       packages/shylu/shylu_node/tacho/src/TachoExp_Util.hpp
M       packages/shylu/shylu_node/tacho/unit-test/Tacho_TestCrsMatrixBase.hpp
.git/rebase-apply/patch:139: trailing whitespace.
  const double eps = std::numeric_limits<double>::epsilon()*10000;  
.git/rebase-apply/patch:158: trailing whitespace.
    {    
.git/rebase-apply/patch:168: trailing whitespace.
      
.git/rebase-apply/patch:401: trailing whitespace.
        if (relerr > eps) 
.git/rebase-apply/patch:530: trailing whitespace.
        if (relerr > eps) 
warning: squelched 216 whitespace errors
warning: 221 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging packages/shylu/shylu_node/tacho/unit-test/Tacho_TestCrsMatrixBase.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/unit-test/Tacho_TestCrsMatrixBase.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_Util.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_Util.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholByBlocks.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholByBlocks.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_SupernodeInfo.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_SupernodeInfo.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_NumericTools.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_NumericTools.hpp
error: Failed to merge in the changes.
Patch failed at 0001 Shylu/Tacho - CUDA unit tests
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

It looks like you rebased a bunch of the commits already in the github/develop branch as shown by:

```
[rabartl@crf450 Trilinos (tacho-gpu)]$ git log -1 --name-status 5f20ddb25630f69d99fb68088e40dc4d7c93a635
commit 5f20ddb25630f69d99fb68088e40dc4d7c93a635
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Mar 14 09:55:37 2018 -0600

    Line buffer log file output
    
    See comment in the file.

M       cmake/tribits/ci_support/checkin-test.py

[rabartl@crf450 Trilinos (tacho-gpu)]$ git log -1 --name-status --grep="Line buffer log file output" github/develop
commit 5f9eedc51009428b7ca8553fbcb800d1ba9b7541
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Mar 14 09:55:37 2018 -0600

    Line buffer log file output
    
    See comment in the file.

M       cmake/tribits/ci_support/checkin-test.py
```

See, you created a duplicate commit for my commit.  That is not good.  It looks almost like you rebased github/develop on top of your topic branch or something.

If there were no conflicts, I could fix this for you.  But I can give you the commands you need to fix your topic branch I think.

**Comment by ndellingwood** [comment]
Scrolling through the commits above, it looks like SHA 9992a95  was the most recent from kyungjoo-kim:tacho-gpu before things went wrong with the rebase, in case that helps as a re-starting point.

**Comment by bartlettroscoe** [comment]
I pushed a reset branch to the `tacho-gpu-fixed` branch in my GitHub fork `git@github.com:bartlettroscoe/Trilinos.git`.  That top commit is cf3452b.

I tried to merge that into the current 'develop' and got all kinds of merge conficits:

```
[rabartl@crf450 Trilinos (develop)]$ git merge tacho-gpu 
Auto-merging packages/shylu/shylu_node/tacho/unit-test/Tacho_TestCrsMatrixBase.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/unit-test/Tacho_TestCrsMatrixBase.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_Util.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_Util.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_SolveUpperChol.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_SolveUpperChol.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_SolveLowerChol.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_SolveLowerChol.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholPanel.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholPanel.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholByBlocksPanel.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholByBlocksPanel.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholByBlocks.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeCholByBlocks.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeChol.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_TaskFunctor_FactorizeChol.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_SupernodeInfo.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_SupernodeInfo.hpp
Auto-merging packages/shylu/shylu_node/tacho/src/TachoExp_NumericTools.hpp
CONFLICT (content): Merge conflict in packages/shylu/shylu_node/tacho/src/TachoExp_NumericTools.hpp
Automatic merge failed; fix conflicts and then commit the result.
```

I did not write this code so I can't safely resolve these merge conflicts myself.  Only a ShyLU developer can do that.

@kyungjoo-kim,

You might want to look over the topic-branch workflow material at:

* https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#heading=h.eezqw2tso48u

and

* https://www.atlassian.com/blog/archives/simple-git-workflow-simple

I will create a wiki page on the Trilinos GitHub site as part of #2295 that shows another way of setting up your local git repo and remotes to help keep things straight.

In the future, you might want to keep your topic branches shorter and use multiple topic branches to avoid lots of merge conflicts like this.  See some discussion about long-lived topic branches (that I and others call feature branches) at:

* https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#heading=h.s49ua5kor0n0

Are topic/feature branch workflows not loads of fun?

**Comment by bartlettroscoe** [comment]
@kyungjoo-kim,

Okay, I changed the topic branch to point to the last merge commit you did with `develop` which was f1c29a6 and pushed to my branch ` tacho-gpu-fixed` in my GitHub fork `git@github.com:bartlettroscoe/Trilinos.git`.   Now that branch merges cleanly with the current `develop` branch as of commit 06bfa04.

If you want, I force push my branch over your branch and update this PR if you want.

NOTE: Because you had to resolve merge conflicts, I can not rebase your branch or I will have to resolve the merge conflicts.  You might be able to rebase your branch if you had `git rerere` enabled as suggested in:

* https://github.com/trilinos/Trilinos/wiki/VC-%7C-Initial-Git-Setup

But if you did not have `git rerere` enabled, then don't bother trying to rebase this.  You will have to resolve all of the conflicts again.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe  

Thank you.

**Comment by jmgate** [comment]
You can always "Dismiss review" (link on the far right):

screen shot 2018-03-19 at 10 18 00 am

**Comment by bartlettroscoe** [comment]
> You can always "Dismiss review" (link on the far right):

@jmgate,

I don't see that link.  Where does appear for you?  At the top right under "Reviewers"?  For me this looks like:

image

Do you have some GitHub superpowers that allows you to dismiss GitHub reviews?

**Comment by mhoemmen** [comment]
I removed @hcedwar as a reviewer (he's quite occupied with other things at the moment; e-mail if you need details).

**Comment by jmgate** [comment]
> Do you have some GitHub superpowers that allows you to dismiss GitHub reviews?

That'd be pretty sweet, but I don't think so.  It's at the bottom right before the comment block.  You may need to click "Show all reviewers", but when there are changes requested I think this should be expanded by default:

screen shot 2018-03-19 at 10 59 00 am

**Comment by bartlettroscoe** [comment]
> That'd be pretty sweet, but I don't think so. It's at the bottom right before the comment block. You may need to click "Show all reviewers", but when there are changes requested I think this should be expanded by default:

@jmgate. Bingo. Thanks for the tip!  That was hidden. I removed my review.

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe 

How can I see error messages from the auto tester ? It passeed gcc 4.8.4 and gcc 4.9.3, then it says that it failed with gcc 4.8.4. What is difference between two gcc 4.8.4 tests ?

**Comment by bartlettroscoe** [comment]
> How can I see error messages from the auto tester ? It passeed gcc 4.8.4 and gcc 4.9.3, then it says that it failed with gcc 4.8.4. What is difference between two gcc 4.8.4 tests ?

@kyungjoo-kim,

The @trilinos/framework team should answer this since this is their system, but for what I know the only thing you can see on your own is on the "Pull Request" section of the new evaluation CDash site.  See the link I put in at:

* https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing#pull_request_testing

and if you click the link "Pull Request Builds" it takes you to:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildstarttime&compare2=84&value2=now

That is strange, because the CDash dispaly for the most recent build "89" at:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3379457&filtercount=2&showfilters=1&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

shows that it is passing the build (but perhaps the tests).

This is all I know.  You will have to ping the @trilinos/framework team for more details.

**Comment by ndellingwood** [comment]
@trilinos/framework Could you provide details about the failing gcc/4.8.4 build (Build Num: 89)? 
Build Num: 507 (Trilinos_autotester_test) Passed but Build Num: 89 (Trilinos_pullrequest_gcc_4.8.4) Failed, but both appear to be the same/similarly configured builds.

**Comment by bmpersc** [comment]
The root cause is that there were no tests run. Right now if no tests are run then the dashboard build is reporting a failure. However, looking at what was submitted to the dashboard for this build makes me wonder if there isn't a bigger issue going on. There apparently were no builds done either, but the list of chages would suggest there should be something built at least.

**Comment by bartlettroscoe** [comment]
>  The root cause is that there were no tests run. Right now if no tests are run then the dashboard build is reporting a failure. However, looking at what was submitted to the dashboard for this build makes me wonder if there isn't a bigger issue going on. There apparently were no builds done either, but the list of chages would suggest there should be something built at least.

@bmpersc,

This issue has been raised in https://github.com/trilinos/Trilinos/issues/2317#issuecomment-372839543 and https://github.com/trilinos/Trilinos/issues/2317#issuecomment-372848883.  The issue is that none of the actual ShyLU subpackages are PT.  The are all ST or EX and are therefore excluded from the TP build of Trilinos.

We can remove the outer dummy ShyLU package and ShyLU_Node and ShyLU_DD parent packagse from being PT but that does not really solve the problem.  A lager questions is, "How should the auto PR testing system handle the (non)testing of non-PT packages?" 

NOTE: The checkin-test.py script will also abort and not push when no tests are run in a case like this.  The logic is that if you asked for a test of changes to a project and no tests were run, then something has gone wrong and tests got skipped somehow.  Otherwise, if you really want to push changes that are untested, then do that manually.  But with the checkin-test.py script, you can define `--st-extra-builds` and `--extra-builds` to test non-PT packages so at least you can do some testing.  It is just that there is no such thing as a standard ST build of Trilinos so there is no way to standardize testing of ST as of now (other than to configure with `-DTrilinos_ENABLE_SECONDARY_TESTED_CODE=ON` and then mess around with the TPL enables/disables and other cmake options until you get something that can work with the SEMS env).

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe 

As we already verified the code with @ndellingwood and the failure simply dictates that there is not PT level test in the code, I am going to merge this to develop. 

Thank you.

**Pull request merged**
