### PR TITLE
Add coloring algo as option for Ifpack2 MTGS/MTSGS

### PR DESCRIPTION
**Pull request by brian-kelley**
(Address #8441). This is also to avoid random failures of Ifpack2/Belos tests that check the number of iterations.
Use deterministic coloring (VBDBIT) for these tests, so they should now pass every time.

This pulls over the necessary changes from https://github.com/kokkos/kokkos-kernels/pull/1199 , and adds the extra Ifpack2 logic to add the option "relaxation: mtgs coloring algorithm". I added a little explanation of it and the possible choices to the user guide PDF.

@trilinos/ifpack2
@trilinos/kokkos-kernels 

## Motivation

Mainly needed to stop random failures in nightly testing. But also useful to allow users to choose VBBIT over EB for faster setup (see #8441).

## Testing

Tested in the Ifpack2 unit tests for Relaxation, and in ifpack2/test/belos.

### CODE REVIEW

**Review by ndellingwood — DISMISSED** [review]
@brian-kelley changes look reasonable to me, please also add a link to the corresponding kokkos-kernels PR with the kokkos-kernels changes for tracking with the next release, thanks!

**Comment by brian-kelley** [comment]
@ndellingwood Done, I added that above (it was https://github.com/kokkos/kokkos-kernels/pull/1199).

**Review by srajama1 — DISMISSED** [review]
Thanks @brian-kelley ! This is a nice addition.

**Comment by brian-kelley** [comment]
@srajama1 @ndellingwood Could one of you re-review? I just added right-hand side vectors in MatrixMarket files to some Ifpack2/Belos problems (instead of generating randomly) so that those solves are deterministic.

**Pull request merged**
