### PR TITLE
Kokkos-Kernels: cherry pick of fixes needed for Ifpack2 MDF

### PR DESCRIPTION
**Pull request by lucbv**
This updates Kokkos Kernels to include changes from PR #1916 in the kokkos/kokkos-kernels repo.

@trilinos/kokkos-kernels 

## Motivation
This cherry-pick is required by PR #12078 to achieve the fix in Ifpack2 MDF implementation

## Related Issues

* Closes 
* Blocks #12078 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Stakeholder Feedback
@ndellingwood @tmranse 
Let me know if this looks good to unblock the PR to ifpack2?

## Testing
Tested locally and in Kokkos Kernels.

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]
Changes previously reviewed and approved in the kokkos-kernels repo, thanks @lucbv !

**Review by tmranse — APPROVED** [review]
lgtm

**Comment by tmranse** [comment]
FYI https://github.com/trilinos/Trilinos/pull/12078 passed and is merged so this can probably be closed now.

**Comment by lucbv** [comment]
Thanks @tmranse, I'll close this now

**Pull request closed without merging**
