### PR TITLE
Ifpack2: Minor performance improvements to Chebyshev

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA 076c244

### CODE REVIEW

**Comment by aprokop** [comment]
Can't you instead unconditionally set `debug` to false if `HAVE_IFPACK2_DEBUG` not defined?

Also, you seem to have accidentally deleted 
```diff
-  W.scale (dtemp1);
```

**Comment by csiefer2** [comment]
The deletion of W.scale is intentional.  elementWiseMultiply can do the scaling on the inside.

**Comment by csiefer2** [comment]
The debug_ was already there.  I just wanted the option to compile that code out.

**Comment by jhux2** [comment]
> The debug_ was already there. I just wanted the option to compile that code out.

So wouldn't it make sense to use Andrey's suggestion?  Or are you concerned that the `if` statements may hinder compiler optimization or runtime performance?

**Comment by csiefer2** [comment]
I added the #ifdefs because a little concerned about branch prediction doing something dumb.  But Andrey's idea should bypass that issue because those symbols should compile out.

Good call.

**Pull request closed without merging**
