### PR TITLE
Update PullRequestLinuxGCC4.9.3TestingSettings.cmake - DO NOT MERGE

### PR DESCRIPTION
**Pull request by jwillenbring**
@trilinos/framework

## Description

Setting warnings as errors flags for MPI GCC 4.9.3 build. This should be too aggressive and fail, but I want to baseline through testing.

## Motivation and Context

We want to keep warnings out of clean packages. We will need to do that on a package by package basis, but first I want to baseline where we are at.

One specific issue is if these are still the right warnings as errors flags to use.

### CODE REVIEW

**Comment by jwillenbring** [comment]
@prwolfe I am not asking for an approval review, but rather a comment on the correctness of the warnings as errors flags.

**Comment by jwillenbring** [comment]
This work is related to #3178.

**Comment by jwillenbring** [comment]
My second attempt to get the build to fail was successful:

/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp: In member function ‘void EpetraExt::HDF5::Read(const string&, Epetra_MultiVector*&, bool, const int&)’:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1225:36: error: ‘memspace_id’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   CHECK_STATUS(H5Sclose(memspace_id));
                                    ^
cc1plus: all warnings being treated as errors

Also, this appears to be doing what we want it to in terms of adding the options to the compile line, not replacing. Here is an example excerpt from a compile line prior to this change (in CDash syntax):

"-pedantic" "-Wall" "-Wno-long-long" "-Wwrite-strings" "-g" "-std=c++11" "-O3" "-DNDEBUG" "-fPIC" "-MD" "-MT" 

and after:

"-pedantic" "-Wall" "-Wno-long-long" "-Wwrite-strings" "-g" "-Wall" "-ansi" "-pedantic" "-Werror" "-Wno-unknown-pragmas" "-Wno-narrowing" "-Wno-pragmas" "-Wno-delete-non-virtual-dtor" "-std=c++11" "-O3" "-DNDEBUG" "-fPIC" "-MD" "-MT" 

should be able to remove the duplicate -pedantic and -Wall

I am going to next modify this so it adds the warnings as errors flags at the package level.

**Comment by william76** [comment]
@jwillenbring 
Hey Jim, this test PR looks like it's probably dated... is this something you want kept around or should we close it out?

**Pull request closed without merging**
