### PR TITLE
2330 fix kokkos arch list

### PR DESCRIPTION
**Pull request by bartlettroscoe**
This fixes the problem with KOKKOS_ARCH described in #2230.

This is an update to Kokkos itself under Trilinos which gets shapshotted in to Trilinos.  But I will create a PR on the kokkos/kokkos git repo itself so that the snapshot does not overwrite this change.

### CODE REVIEW

**Comment by ibaned** [comment]
@allevin can you tell us why this test failed?

**Comment by allevin** [comment]
@ibaned Looks like the Jenkins builder failed to clone from Gitlab-ex.  Let me reset the test status flag, to skip the 4 hour delay.

Commit message: "Tpetra: fixing matrix-matrix multiply for GPUs"
 > git rev-list 7fa1543ad9fafba9c24f02aa54e71624ce2765ef # timeout=10
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@gitlab-ex.sandia.gov:trilinos-project/TFW_single_configure_support_scripts.git # timeout=10
Fetching upstream changes from git@gitlab-ex.sandia.gov:trilinos-project/TFW_single_configure_support_scripts.git
 > git --version # timeout=10
using GIT_SSH to set credentials Trilinos ssh key
 > git fetch --tags --progress git@gitlab-ex.sandia.gov:trilinos-project/TFW_single_configure_support_scripts.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@gitlab-ex.sandia.gov:trilinos-project/TFW_single_configure_support_scripts.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:817)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1084)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
	at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:143)

**Comment by ibaned** [comment]
I was able to get the Kokkos develop branch to also accept commas (see https://github.com/kokkos/kokkos/pull/1460), so we are ready to make this the new interface (and document it).

**Comment by crtrott** [comment]
I merged kokkos/kokkos#1460 as well.

**Pull request merged**
