### PR TITLE
MueLu: Adapt offset calculation in amalgamation

### LINKED ISSUE #12665: MueLu: Constructing the correct amalgamation based strided DOF map for block-systems
## Enhancement

Hello everyone,

I am using `Teko` and `MueLu` for multi-physics block preconditioning and run into the following problem (in some parts already described in #11562):

In our in-house code we assemble `Xpetra`-based block systems (based on strided maps with offset), which we want to precondition with `Teko`. Thus we transform the `Xpetra` operator into a `Thyra` one, which means we loose (in some sense) the offset information of the strided maps, resulting in a wrong Dof Id to Node Id mapping in the amalgamation process in `MueLu`, when the single blocks are transformed back from `Thyra` to `Xpetra`. This afterwards results in wrong aggregates etc. ...

As I understand it there are 3 kinds of numbering schemes for blocked systems available:
Block X: ([GIDs], offset)

1. `Thyra`-style numbering:
Block 0: ([0, 1, 2, 3, ..., n], -)
Block 1: ([0, 1, 2, 3, ..., n], -)
...
All blocks start counting at 0 and no offset is defined.
In a conversion to `Xpetra` the offset would default to 0, which is fine and the Dof Id to Node Id mapping can be done properly.

2. `Xpetra`-style numbering I:
Block 0: ([0, 1, 2, 3, ..., n], 0)
Block 1: ([n+1, n+2, ..., 2n], n+1)
...
The blocks are numbered continuously, and an offset variable is set appropriately during map construction.
(Is that correct?)

3. `Xpetra`-style numbering II:
Block 0: ([0, 1, 2, 3, ..., n], 0)
Block 1: ([n+1, n+2, ..., 2n], 0)
The offset is always set to 0 and the GIDs are inherently constructed continuous.
This is the case we are using, which is troublesome and delivers a wrong Dof Id to Node Id as no proper offset is set/available.
And thus the integer division calculating Dof Id -> Node Id does weird things.

A fix would be to do the following:
```cpp
    std::vector<size_t> stridingData = stridedRowMap->getStridingData();
    RCP<const StridedMap> stridedMap = Teuchos::rcp(new StridedMap(stridedRowMap->lib(),
                                                                   Teuchos::OrdinalTraits<GO>::invalid(),
                                                                   stridedRowMap->getLocalElementList(),
                                                                   stridedRowMap->getIndexBase(),
                                                                   stridingData,
                                                                   stridedRowMap->getComm(),
                                                                   stridedRowMap->getStridedBlockId()));
```

We get the strided row map in the amalgamation procedure and based on that we construct a new strided map, which figures out the correct information (e.g. offset) by itself. For the first two cases, this should result in the same map, but for the third one in a map with a proper offset value set.

Our whole code is based on the third case numbering, which I therefore can't change.
What do you think, does this make sense in some way?

Best regards,
Max

@trilinos/muelu and @mayrmt

### PR DESCRIPTION
**Pull request by maxfirmbach**
@trilinos/muelu

## Motivation

There are some edge cases, were the offset for a strided map is not set correctly or at all, when using block matrix conversions from `Xpetra` to `Thyra` and vice-versa. Thus this MR proposes to calculate the offset from scratch similar to the `Xpetra::StridedMap` constructor with user-defined non-contiguous (arbitrary) distribution (Definition at line [269](https://docs.trilinos.org/dev/packages/xpetra/doc/html/Xpetra__StridedMap__def_8hpp_source.html#l00269) of file [Xpetra_StridedMap_def.hpp](https://docs.trilinos.org/dev/packages/xpetra/doc/html/Xpetra__StridedMap__def_8hpp_source.html)). 

## Related Issues

* Closes #12665
* Related to #13023 

## Additional Information
Relevant for block preconditioning with `Teko` for multi-physics problems and using `MueLu` to approximate the single field inverses.
@mayrmt

### CODE REVIEW

**Comment by mayrmt** [comment]
@maxfirmbach, is this change covered by existing tests or would it make sense to add a new test tailored to this change?

**Comment by maxfirmbach** [comment]
@mayrmt I added a minimal working example as unit-test. I hope the problem get's clear.

**Review by mayrmt — DISMISSED** [review]

**Review by mayrmt — APPROVED** [review]

**Comment by maxfirmbach** [comment]
Clang format is fixed, should be ready for testing now.

**Comment by maxfirmbach** [comment]
The auto-tester passing with the first go ... wow :laughing:

**Review by cgcgcg — APPROVED** [review]

**Comment by cgcgcg** [comment]
@maxfirmbach Good to merge?

**Comment by maxfirmbach** [comment]
All ready from my side :+1:

**Pull request merged**
