### PR TITLE
ifpack: fixes missing memory leak in Ifpack_Hypre

### LINKED ISSUE #7807: ifpack:  memory leak in Ifpack_Hypre
## Bug Report
@trilinos/ifpack

### Description

Normal usage of Ifpack_Hypre leaks memory.

### Steps to Reproduce
1. SHA1:  688a924
2. Configure script:  (built through cmake, standard configure of Epetra stack)
3. Configure log:  (if needed I can go searching...)
4. Build log:  (same as configure)
5. Input deck:  [attach here]
[solver_pc_boomeramg.cc.txt](https://github.com/trilinos/Trilinos/files/5045269/solver_pc_boomeramg.cc.txt)

See attached unittest. 

6. Compile and run valgrind:

`valgrind --leak-check=full solver_pc_boomeramg &> valgrind_out.txt`

7. Run log:
[valgrind_out.txt](https://github.com/trilinos/Trilinos/files/5045272/valgrind_out.txt)

### Why is it broken?

Effectively the issue is the following path through the code:

1. Use Hypre as a Preconditioner `SolverOrPreconditioner == Preconditioner`
2. Supply no Solver.  Ifpack_Hypre defaults to `PCG`.
 https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L73
3.  Despite not being asked to supply a Solver, Ifpack calls CreateSolver, which since there is a default value of a real solver (e.g. not NULL or comparable), Ifpack creates the object.  This allocates memory (in Hypre)
  https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L166
4. When `Compute()` is called, `SolverSetupPtr_` is _not_ called, because there it correctly checks and sees that a solver was not requested.  As a result, the flag  `IsSolverSetup_[0] == false`
https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L279
5. Since `IsSolverSetup_[0] == false`, `Destroy()` does _not_ call `DestroySolverPtr_`: 
https://github.com/trilinos/Trilinos/blob/master/packages/ifpack/src/Ifpack_Hypre.cpp#L142

Not calling `DestroySolverPtr_` leaks the memory.  Note, I have not confirmed that DestroySolverPtr_ can be called on a created but not setup Hypre solver, but one would hope so.

Note also that there is a comparable memory leak where you could replace "Solver" by "Preconditioner" and leak the PC object (if `UsePreconditioner_ == false`)

### Proposed fix

There are a few issues here, and fixes are pretty straightforward.  Pull request coming in the next few days.

1. Rename the flag IsSolverSetup_ to IsSolverCreated_, set it on creation, and destroy if created.  This would fix the memory leak.  (Respectively, IsPreconSetup_), and doing this makes the code safer.
2. Check whether `SolverOrPreconditioner_ != Preconditioner` before creating a solver.  Similarly, check whether `UsePreconditioner_ == true` before creating a preconditioner.  These shouldn't be created if they aren't going to be used.

### PR DESCRIPTION
**Pull request by ecoon**
@trilinos/ifpack

Apologies for the last pull request which was "dirty" since the commit was based on master.  This is on develop now, so should include only one commit...

## Motivation

Closes #7807 

## Testing

I believe there are no Ifpack_Hypre tests currently.  In the issue, I included source for a test, and we maintain a set of tests for this capability in Amanzi because we use it often.

## Additional Information

valgrind clean...

### CODE REVIEW

**Comment by cgcgcg** [comment]
@trilinos/ifpack

**Comment by csiefer2** [comment]
@cgcgcg and I have a branch with a bunch of related fixes.  I'll need to check that against this.

**Comment by ecoon** [comment]
@csiefer2 Is this being pulled into that branch then?  Would be nice to have this fixed as we currently have to patch it downstream.

**Comment by cgcgcg** [comment]
@ecoon It's on my list of things to do...

**Comment by cgcgcg** [comment]
Taken care of via #8060

**Pull request closed without merging**
