### PR TITLE
Kokkos + KokkosKernels Promotion To 4.0.0

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos @trilinos/kokkos-kernels 

## Motivation

Release Kokkos Ecosystem 4.0.0 into Trilinos

## Testing

Various nightly testing builds and upcoming AT testing

### CODE REVIEW

**Comment by ndellingwood** [comment]
@sebrowne SHA [612650d](https://github.com/trilinos/Trilinos/pull/11600/commits/612650dfa9de9cc7192e950eeb56c70cfd7c1403) includes my attempt to disable and modify a couple tests, would you review those changes to make sure I handled them correctly?

**Comment by ndellingwood** [comment]
Cross-referencing release PRs to stand-alone repositories:

kokkos/kokkos#5912
kokkos/kokkos-kernels#1699

**Review by lucbv — APPROVED** [review]
Looks good, thanks @ndellingwood

**Comment by ndellingwood** [comment]
We have a passing PR with the 4.0 release snapshots :)
Adding mentions to members of app teams:

@rppawlo for EMPIRE
@stanmoore1 for LAMMPS
@spdomin for NALU
@vbrunini for ARIA
@mperego @jewatkins for Albany and/or SPARC

**Comment by sebrowne** [comment]
@ndellingwood that syntax looks correct to me, as long as the test names are accurate (which I'm assuming they are since the autotester passed)

**Comment by vbrunini** [comment]
Everything looks good for Aria in clang & nvcc builds, thanks!

**Comment by rppawlo** [comment]
Seeing seg faults in empire unit tests with cuda. Will send some more info soon.

**Review by csiefer2 — COMMENTED** [review]
Looks good to me!

**Comment by ndellingwood** [comment]
@rppawlo any updates on status with the failures you encountered?

**Pull request merged**
