### PR TITLE
Techx 0007 phalanx package warnings fixes

### PR DESCRIPTION
**Pull request by bddavid**
##### Attention:
@jwillenbring 
@trilinos/phalanx
 
In this branch I have applied an [updated version](https://github.com/trilinos/Trilinos/files/81406/0007-Phalanx-Package-Warnings-Fixes-010616.patch.txt) of the patch described in issue #66.  The original patch had to be truncated due to changes in the code base since September, 2015 when this work was originally completed. However the warnings addressed by the original patch have been fixed/removed manually in this branch.

### CODE REVIEW

**Comment by jwillenbring** [comment]
@rppawlo 
I want to make sure Roger is aware of this pull request.

**Comment by jwillenbring** [comment]
@rppawlo 

Are you the right person to evaluate this pull request? Should we attempt to resolve the conflicts and merge this along with some of the other requests that came in from Tech-X?

**Comment by rppawlo** [comment]
I'm going to hold off on pulling this in.  The code in question may be completely removed once a new capability is added to kokkos next week.

**Comment by jwillenbring** [comment]
Thanks for the update. Good to get these closed soon one way or another.

**Comment by rppawlo** [comment]
The code in question has been deprecated. It no longer builds by default. This change has not been pushed yet - it is lumped into some other changes that are waiting for a kokkos snapshot before pushing. Will close this ticket once pushed to master.

**Comment by bartlettroscoe** [comment]
Can we close the associated Milestone/Epic "0007-Phalanx-Package-Warnings-Fixes"?

**Comment by rppawlo** [comment]
yes

________________________________

**Comment by bartlettroscoe** [comment]
I just closed the Milestone/Epic "0007-Phalanx-Package-Warnings-Fixes".

GitHub does not seem to provide any tacking of the creation or closing of these Milestones or Epics and provides no way to track a conversation about them.  That is not good.

**Pull request closed without merging**
