### PR TITLE
Kokkos + KokkosKernels Promotion To Version 2.7.00

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos 
@trilinos/kokkos-kernels 

## Description
This merges Kokkos and KokkosKernels versions 2.7.00 into Trilinos.
Changes were made to Kokkos, KokkosKernels, and Trilinos so that code will compile with Kokkos' deprecated code enabled and disabled. 

## [2.7.00](https://github.com/kokkos/kokkos/tree/2.7.00) (2018-05-24)
[Full Changelog](https://github.com/kokkos/kokkos/compare/2.6.00...2.7.00)

**Part of the Kokkos C++ Performance Portability Programming EcoSystem 2.7**

**Implemented enhancements:**

- Deprecate team\_size auto adjusting to maximal value possible [\#1618](https://github.com/kokkos/kokkos/issues/1618)
- DynamicView - remove restrictions to std::is\_trivial types and value\_type is power of two [\#1586](https://github.com/kokkos/kokkos/issues/1586)
- Kokkos::StaticCrsGraph does not propagate memory traits \(e.g., Unmanaged\) [\#1581](https://github.com/kokkos/kokkos/issues/1581)
- Adding ETI for DeepCopy / ViewFill etc. [\#1578](https://github.com/kokkos/kokkos/issues/1578)
- Deprecate all the left over KOKKOS\_HAVE\_ Macros and Kokkos\_OldMacros.hpp [\#1572](https://github.com/kokkos/kokkos/issues/1572)
- Error if Kokkos\_ARCH set in CMake [\#1555](https://github.com/kokkos/kokkos/issues/1555)
- Deprecate ExecSpace::initialize / ExecSpace::finalize [\#1532](https://github.com/kokkos/kokkos/issues/1532)
- New API for TeamPolicy property setting [\#1531](https://github.com/kokkos/kokkos/issues/1531)
- clang 6.0 + cuda debug out-of-memory test failure [\#1521](https://github.com/kokkos/kokkos/issues/1521)
- Cuda UniqueToken interface not consistent with other backends [\#1505](https://github.com/kokkos/kokkos/issues/1505)
- Move Reducers out of Experimental namespace [\#1494](https://github.com/kokkos/kokkos/issues/1494)
- Provide scope guard for initialize/finalize [\#1479](https://github.com/kokkos/kokkos/issues/1479)
- Check Kokkos::is\_initialized in SharedAllocationRecord dtor [\#1465](https://github.com/kokkos/kokkos/issues/1465)
- Remove static list of allocations [\#1464](https://github.com/kokkos/kokkos/issues/1464)
- Makefiles: Support single compile/link line use case [\#1402](https://github.com/kokkos/kokkos/issues/1402)
- ThreadVectorRange with a range  [\#1400](https://github.com/kokkos/kokkos/issues/1400)
- Exclusive scan + last value API [\#1358](https://github.com/kokkos/kokkos/issues/1358)
- Install kokkos\_generated\_settings.cmake [\#1348](https://github.com/kokkos/kokkos/issues/1348)
- Kokkos arrays \(not views!\) don't do bounds checking in debug mode [\#1342](https://github.com/kokkos/kokkos/issues/1342)
- Expose round-robin GPU assignment outside of initialize\(int, char\*\*\) [\#1318](https://github.com/kokkos/kokkos/issues/1318)
- DynamicView misses use\_count and label function [\#1298](https://github.com/kokkos/kokkos/issues/1298)
- View constructor should check arguments [\#1286](https://github.com/kokkos/kokkos/issues/1286)
- False Positive on Oversubscription Warning [\#1207](https://github.com/kokkos/kokkos/issues/1207)
- Allow \(require\) execution space for 1st arg of VerifyExecutionCanAccessMemorySpace [\#1192](https://github.com/kokkos/kokkos/issues/1192)
- ROCm: Add ROCmHostPinnedSpace [\#958](https://github.com/kokkos/kokkos/issues/958)
- power of two functions [\#656](https://github.com/kokkos/kokkos/issues/656)
- CUDA 8 has 64bit \_\_shfl [\#361](https://github.com/kokkos/kokkos/issues/361)
- Add TriBITS/CMake configure information about node types [\#243](https://github.com/kokkos/kokkos/issues/243)

**Fixed bugs:**

- CUDA atomic\_fetch\_sub for doubles is hitting CAS instead of intrinsic [\#1624](https://github.com/kokkos/kokkos/issues/1624)
- Bug: use of ballot on Volta [\#1612](https://github.com/kokkos/kokkos/issues/1612)
- Kokkos::deep\_copy memory access failures [\#1583](https://github.com/kokkos/kokkos/issues/1583)
- g++ -std option doubly set for cmake project [\#1548](https://github.com/kokkos/kokkos/issues/1548)
- ViewFill for 1D Views of larger 32bit entries fails [\#1541](https://github.com/kokkos/kokkos/issues/1541)
- CUDA Volta another warpsync bug [\#1520](https://github.com/kokkos/kokkos/issues/1520)
- triple\_nested\_parallelism fails with KOKKOS\_DEBUG and CUDA [\#1513](https://github.com/kokkos/kokkos/issues/1513)
- Jenkins errors in Kokkos\_SharedAlloc.cpp with debug build [\#1511](https://github.com/kokkos/kokkos/issues/1511)
- Kokkos::Sort out-of-bounds with empty bins [\#1504](https://github.com/kokkos/kokkos/issues/1504)
- Get rid of deprecated functions inside Kokkos [\#1484](https://github.com/kokkos/kokkos/issues/1484)
- get\_work\_partition casts int64\_t to int, causing a seg fault [\#1481](https://github.com/kokkos/kokkos/issues/1481)
- NVCC bug with \_\_device\_\_ on defaulted function [\#1470](https://github.com/kokkos/kokkos/issues/1470)
- CMake example broken with CUDA backend [\#1468](https://github.com/kokkos/kokkos/issues/1468)

## [2.7.00](https://github.com/kokkos/kokkos-kernels/tree/2.7.00) (2018-05-24)
[Full Changelog](https://github.com/kokkos/kokkos-kernels/compare/2.6.00...2.7.00)

**Implemented enhancements:**

- Tests: add capability to build a unit test standalone [\#233](https://github.com/kokkos/kokkos-kernels/issues/233)
- Make KokkosKernels work without KOKKOS\_ENABLE\_DEPRECATED\_CODE [\#223](https://github.com/kokkos/kokkos-kernels/issues/223)
- Replace KOKKOS\_HAVE\_\* FLAGS with KOKKOS\_ENABLE\_\* [\#219](https://github.com/kokkos/kokkos-kernels/issues/219)
- Add team-based scal, mult, update, nrm2 [\#214](https://github.com/kokkos/kokkos-kernels/issues/214)
- Add team based abs [\#209](https://github.com/kokkos/kokkos-kernels/issues/209)
- Generated CPP files moving includes inside the ifdef's [\#199](https://github.com/kokkos/kokkos-kernels/issues/199)
- Implement BlockCRS in Kokkoskernels [\#184](https://github.com/kokkos/kokkos-kernels/issues/184)
- Spgemm hash promotion [\#171](https://github.com/kokkos/kokkos-kernels/issues/171)
- Batched BLAS enhancement [\#170](https://github.com/kokkos/kokkos-kernels/issues/170)
- Document & check CMAKE\_CXX\_USE\_RESPONSE\_FILE\_FOR\_OBJECTS=ON in CUDA build [\#148](https://github.com/kokkos/kokkos-kernels/issues/148)

**Fixed bugs:**

- Update drivers in perf\_tests/graph to use Kokkos::initialize\(\) [\#200](https://github.com/kokkos/kokkos-kernels/issues/200)
- unit tests failing/hanging on Volta [\#188](https://github.com/kokkos/kokkos-kernels/issues/188)
- Inner TRSM: SIMD build error; manifests in Ifpack2 [\#183](https://github.com/kokkos/kokkos-kernels/issues/183)
- d2\_graph\_color doesn't have a default coloring mechanism [\#168](https://github.com/kokkos/kokkos-kernels/issues/168)
- Unit tests do not build with Serial backend [\#154](https://github.com/kokkos/kokkos-kernels/issues/154)

## How Has This Been Tested?
This set of changes has been tested on Shepard and White with Intel 17, GCC 5.3, NVCC 8.
Configurations according to kokkos-kernels/scripts/trilinos-integration test scripts.
A detailed list of test failures is provided below. No additional test failures compared to the current
trilinos/develop branch were observed. Both individual packages are passing their comprehensive
nightly test suites. This includes testing of more than 200 configuration spanning 25+ compiler versions and 9 hardware platforms ( Intel Skylake, Intel SandyBridge, Intel Haswell, Intel Haswell + NVIDIA K40, Intel KNL, ARM, Power8, Power8 + K80, Power8 + P100).

### CODE REVIEW

**Comment by ndellingwood** [comment]
Follow-on PR #2714

**Comment by ndellingwood** [comment]
Build failures discussed in #2735 were fixed by MueLu and ROL developers.

**Comment by ndellingwood** [comment]
# Testing Results Shepard Serial

## General Test Results: 
One failure on both pristine and updated branches:
`ML_MLP_Restart_MPI_4 (Failed)`

**Comment by ndellingwood** [comment]
# Testing Results Shepard Threads

## General Test Results: 
One failure on pristine (develop) branch, none on updated branch:
`ML_MLP_Restart_MPI_4 (Failed)`

**Comment by ndellingwood** [comment]
# Testing Results White OpenMP

## General Test Results: 
Same failures on both pristine and updated branches:
```
Anasazi_BlockDavidsonThyra_test_MPI_4 (Failed)
Anasazi_Epetra_BKS_nh_test_1_MPI_4 (Failed)
Anasazi_Epetra_BKS_solvertest_MPI_4 (Failed)
Anasazi_Epetra_BKS_test_1_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_auxtest_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_solvertest_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_0_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_1_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_2_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_3_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_4_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_5_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_6_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_7_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_8_MPI_4 (Failed)
Anasazi_Epetra_GeneralizedDavidson_solvertest_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_0_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_1_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_2_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_3_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_4_MPI_4 (Failed)
Anasazi_Epetra_IRTR_test_0_MPI_4 (Failed)
Anasazi_Epetra_IRTR_test_1_MPI_4 (Failed)
Anasazi_Epetra_IRTR_test_2_MPI_4 (Failed)
Anasazi_Epetra_IRTR_test_3_MPI_4 (Failed)
Anasazi_Epetra_LOBPCG_auxtest_MPI_4 (Failed)
Anasazi_Epetra_LOBPCG_simpletest_MPI_4 (Failed)
Anasazi_Epetra_LOBPCG_solvertest_MPI_4 (Failed)
Anasazi_Epetra_LOBPCG_test_MPI_4 (Failed)
Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_0_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_1_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_2_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_3_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_5_MPI_4 (Failed)
Anasazi_IRTRThyra_test_0_MPI_4 (Failed)
Anasazi_IRTRThyra_test_1_MPI_4 (Failed)
Anasazi_IRTRThyra_test_2_MPI_4 (Failed)
Anasazi_IRTRThyra_test_3_MPI_4 (Failed)
Anasazi_LOBPCGThyra_test_MPI_4 (Failed)
Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4 (Failed)
Belos_bl_fgmres_hb_MPI_4 (Failed)
Belos_bl_pgmres_hb_0_MPI_4 (Failed)
Belos_bl_pgmres_hb_1_MPI_4 (Failed)
Belos_bl_pgmres_hb_2_MPI_4 (Failed)
Belos_gcrodr_hb_MPI_4 (Failed)
Belos_prec_gcrodr_hb_1_MPI_4 (Failed)
Belos_pseudo_gmres_hb_MPI_4 (Failed)
Belos_pseudo_pgmres_hb_MPI_4 (Failed)
Ifpack2_GS_belos_MPI_1 (Failed)
Ifpack2_Jacobi_hb_belos_MPI_1 (Failed)
Ifpack2_Jacobi_hb_belos_MPI_2 (Failed)
Ifpack2_SGS_belos_MPI_1 (Failed)
Intrepid2_unit-test_Orientation_Serial_Test_Orientation_TET_MPI_1 (Failed)
NOX_LOCA_MultiPointTcubed_MPI_2 (Failed)
Stokhos_TpetraCrsMatrixMPVectorUnitTest_OpenMP_MPI_4 (Failed)
Stratimikos_Belos_GCRODR_strattest_MPI_4 (Failed)
Stratimikos_Thyra_Belos_StatusTest_UnitTests_MPI_1 (Failed)
```

**Comment by ndellingwood** [comment]
# Testing Results White Cuda

## General Test Results: 
Same failures on both pristine and updated branches:
```
Anasazi_BlockDavidsonThyra_test_MPI_4 (Failed)
Anasazi_Epetra_BKS_nh_test_1_MPI_4 (Failed)
Anasazi_Epetra_BKS_solvertest_MPI_4 (Failed)
Anasazi_Epetra_BKS_test_1_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_auxtest_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_solvertest_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_0_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_1_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_2_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_3_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_4_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_5_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_6_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_7_MPI_4 (Failed)
Anasazi_Epetra_BlockDavidson_test_8_MPI_4 (Failed)
Anasazi_Epetra_GeneralizedDavidson_solvertest_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_0_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_1_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_2_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_3_MPI_4 (Failed)
Anasazi_Epetra_IRTR_auxtest_4_MPI_4 (Failed)
Anasazi_Epetra_IRTR_test_0_MPI_4 (Failed)
Anasazi_Epetra_IRTR_test_1_MPI_4 (Failed)
Anasazi_Epetra_IRTR_test_2_MPI_4 (Failed)
Anasazi_Epetra_IRTR_test_3_MPI_4 (Failed)
Anasazi_Epetra_LOBPCG_auxtest_MPI_4 (Failed)
Anasazi_Epetra_LOBPCG_simpletest_MPI_4 (Failed)
Anasazi_Epetra_LOBPCG_solvertest_MPI_4 (Failed)
Anasazi_Epetra_LOBPCG_test_MPI_4 (Failed)
Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerGenTester_1_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_0_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_1_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_2_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_3_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4 (Failed)
Anasazi_Epetra_OrthoManagerMatTester_5_MPI_4 (Failed)
Anasazi_IRTRThyra_test_0_MPI_4 (Failed)
Anasazi_IRTRThyra_test_1_MPI_4 (Failed)
Anasazi_IRTRThyra_test_2_MPI_4 (Failed)
Anasazi_IRTRThyra_test_3_MPI_4 (Failed)
Anasazi_LOBPCGThyra_test_MPI_4 (Failed)
Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4 (Failed)
Belos_bl_fgmres_hb_MPI_4 (Failed)
Belos_bl_pgmres_hb_0_MPI_4 (Failed)
Belos_bl_pgmres_hb_1_MPI_4 (Failed)
Belos_bl_pgmres_hb_2_MPI_4 (Failed)
Belos_gcrodr_hb_MPI_4 (Failed)
Belos_prec_gcrodr_hb_1_MPI_4 (Failed)
Belos_pseudo_gmres_hb_MPI_4 (Failed)
Belos_pseudo_pgmres_hb_MPI_4 (Failed)
Intrepid2_unit-test_Orientation_Serial_Test_Orientation_TET_MPI_1 (Failed)
NOX_LOCA_MultiPointTcubed_MPI_2 (Failed)
ROL_test_elementwise_TpetraMultiVector_MPI_4 (Failed)
Stokhos_TpetraCrsMatrixMPVectorUnitTest_Serial_MPI_4 (Failed)
Stratimikos_Belos_GCRODR_strattest_MPI_4 (Failed)
Stratimikos_Thyra_Belos_StatusTest_UnitTests_MPI_1 (Failed)
TpetraCore_Core_initialize_where_tpetra_initializes_kokkos_MPI_1 (Failed)
TpetraCore_Core_initialize_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2 (Failed)
TpetraCore_Core_initialize_where_user_initializes_kokkos_MPI_1 (Failed)
TpetraCore_Core_initialize_where_user_initializes_mpi_MPI_4 (Failed)
```

Test not run on both branches:
`ROL_test_function_BlockOperatorCheck_MPI_1 (Not Run)`

**Comment by ndellingwood** [comment]
Merge conflict in ROL fixed and merged - `dimension_1` vs `extent(1)` at line 125 of `packages/rol/adapters/tpetra/src/vector/ROL_TpetraMultiVector.hpp`

**Comment by ndellingwood** [comment]
Updated develop and master branches of kokkos and kokkos-kernels ready for push to resp. repos once PR approved and merged into Trilinos.

**Comment by ibaned** [comment]
@ndellingwood I think the Trilinos Pull Request Autotester is in much better shape this time than last release, so I'm inclined to trust it to take the place of `checking-test-sems` this time. We can wait for @crtrott to make the final call though.

**Comment by crtrott** [comment]
Dan is right. This auto testing is supposed to take the place of checkin-test. We did our due diligence beyond that by running out integration testing but for the rest we gonna rely on the auto tester.

**Pull request merged**
