### PR TITLE
NOX: add Single-Step (Linear) Nonlinear Solver

### PR DESCRIPTION
**Pull request by ibaned**
See issue #926 for rationale.
Naming this Solver "Single Step" as opposed
to "Linear" should prevent some confusion.

### CODE REVIEW

**Comment by rppawlo** [comment]
@ibaned Looks great! The only thing missing are unit tests that exercise this capability. We don't allow code to be committed to nox without appropriate unit testing. Probably the best place to add a test is in the nox/test/epetra/Thyra directory. You can set up a simple nonlinear solve and then check that the number of nonlinear iterations one and that the problem is declared converged.

**Comment by ibaned** [comment]
@rppawlo it took me some time, but I managed to implement a test. I first went and generated a model evaluator that is linear in nature. Please see commit 27576bc.

**Comment by rppawlo** [comment]
Thanks @ibaned ! I am working on running the checkin test script now. If it passes, it will get merged in today.

**Comment by ibaned** [comment]
@rppawlo  did this pass the tests ?

**Comment by rppawlo** [comment]
@ibaned - sorry - had some trouble with the checkin test script on the test machine. Just resolved it with CSU support yesterday. Will try to push this in today.

**Pull request closed without merging**
