### PR TITLE
Teuchos: Fix #2018

### LINKED ISSUE #2018: Teuchos: Set Teuchos_ENABLE_COMPLEX if Trilinos_ENABLE_COMPLEX_FLOAT is set
See my comments here: https://github.com/trilinos/Trilinos/issues/2009#issuecomment-347218806

@trilinos/teuchos

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/teuchos Set `Teuchos_ENABLE_COMPLEX` by default, if either
`Trilinos_ENABLE_COMPLEX_DOUBLE` or `Trilinos_ENABLE_COMPLEX_FLOAT` are
set.  Before, `Teuchos_ENABLE_COMPLEX` was only set by default if
`Trilinos_ENABLE_COMPLEX_DOUBLE` was set.

This should help avoid issues such as #2009.

@trilinos/teuchos 

## Motivation and Context

It may be possible in the future for users to set `Trilinos_ENABLE_COMPLEX_FLOAT` but not `Trilinos_ENABLE_COMPLEX_DOUBLE`.  Also, users may not know about the (relatively newer) `Trilinos_ENABLE_<SCALAR>` CMake options.

## Related Issues

* Related to #2009

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by ibaned** [comment]
Lets see if the PR tester will kick in...

**Comment by mhoemmen** [comment]
Thanks @ibaned ! :-D

**Comment by mhoemmen** [comment]
@prwolfe @rrdrake this may be of interest to you; thanks!

**Comment by mhoemmen** [comment]
@bartlettroscoe The issue is a bit more complicated, in that `Teuchos_ENABLE_COMPLEX` touches both on instantiations, and on simple use of `std::complex<T>`.  For example, `Teuchos::ScalarTraits` won't get an `std::complex<T>` specialization (for `T=double` or `float`) unless `Teuchos_ENABLE_COMPLEX` is `ON`.

**Pull request merged**
