### PR TITLE
Disable Kokkos unit test Random_XorShift64 and Random_XorShift1024

### PR DESCRIPTION
**Pull request by e10harvey**
Related to #3282 

## How was this tested?
On a cee-rhel7 machine via:
```
nohup env Trilinos_PACKAGES=Kokkos ATDM_CTEST_S_DEFAULT_ENV=cee-rhel7-default ./ctest-s-local-test-driver.sh cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_dbg &> ctest-s-local-test-driver.out &
```
Evidence of the disable for `Random_XorShift64` is shown in [this](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2021-02-11&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_dbg&field3=testname&compare3=63&value3=KokkosAlgorithms_UnitTest_MPI_1&field4=testoutput&compare4=95&value4=Random_XorShift) query by clicking "Show Matching Output".

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@e10harvey, @trilinos/kokkos, @kddevin (Trilinos Data Services Lead).

If this unit test is going to be disabled for all ATDM Trilinos builds, it should be disabled for all Trilinos PR builds as well as it fails in PR testing as well.  For evidence of that, see https://github.com/trilinos/Trilinos/issues/3282#issuecomment-777648991.

**Review by bartlettroscoe — DISMISSED** [review]
This disable is fine but as I commented [above](https://github.com/trilinos/Trilinos/pull/8740#issuecomment-777650950), it should be disabled in Trilinos PR builds too.  (In fact, it is more important to disable it in PR builds since that blocks the merge to 'develop'.   Having this test randomly fail in nightly builds is just an annoyance.)

**Comment by e10harvey** [comment]
> This disable is fine but as I commented [above](https://github.com/trilinos/Trilinos/pull/8740#issuecomment-777650950), it should be disabled in Trilinos PR builds too. (In fact, it is more important to disable it in PR builds since that blocks the merge to 'develop'. Having this test randomly fail in nightly builds is just an annoyance.)

Thanks, @bartlettroscoe. I will make these updates.

**Review by bartlettroscoe — COMMENTED** [review]
@e10harvey, I would approve and allow this to merge but I think someone on the @trilinos/framework team or the @trilinos/kokkos teams should approve turning off this one unit test in Trilinos PR testing.

**Comment by ZUUL42** [comment]
It's good to see random test failures fixed across all compilers.
It passes all PR tests, so I'm good with it.
Since this directly changes @trilinos/kokkos across all builds, it would be good to see their approval.

**Comment by e10harvey** [comment]
Thanks, all. Kokkos is OK with this. Can this be merged?

**Review by bartlettroscoe — COMMENTED** [review]
Looks fine to me but one of the @trilinos/framework members should approve since this impact the PR testing.

**Review by ZUUL42 — APPROVED** [review]

**Pull request merged**
