### PR TITLE
Changes to MiniTensor

### PR DESCRIPTION
**Pull request by guybergel**
@trilinos/<teamName>

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@guybergel Pull requests must be made against the develop branch.

**Comment by mhoemmen** [comment]
@guybergel Also, please give your PR a more descriptive title -- "changes to X" describes pretty much every pull request ever :)

**Comment by jmgate** [comment]
@lxmota, it would have been good to wait for the @trilinos-autotester to run its testing before merging.

**Comment by lxmota** [comment]
Yes, I wasn’t sure how this worked so I tested the changes manually before merging.

Glad to know that this is done automatically now!

On Apr 6, 2018, at 08:08, Jason M. Gates <notifications@github.com<mailto:notifications@github.com>> wrote:


@lxmota<https://github.com/lxmota>, it would have been good to wait for the @trilinos-autotester<https://github.com/trilinos-autotester> to run its testing before merging.

**Comment by jmgate** [comment]
Very good&mdash;thanks.

**Pull request merged**
