### PR TITLE
Consolidate disables for all builds on 'mutrino' (#3183)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @gsjaardema, @fryeguy52 

## Description

This also adds back the disables for several SEACAS tests that got removed
when the file INTEL-RELEASE-OPENMP.cmake got renamed to the file
INTEL-RELEASE-OPENMP-HSW.cmake (not clear how that happened).

## Motivation and Context

The disables for the build `intel-opt-openmp-HSW` got removed on the file rename which resulted in these tests failing again in this build (see #3183) and this much duplication is bad.  We want less duplication.

## How Has This Been Tested?

I ran local configures with:

```
$  ./checkin-test-atdm.sh all --enable-packages=SEACAS --configure
```

which returned:

```
PASSED (NOT READY TO PUSH): Trilinos: mutrino

Tue Aug  7 14:33:08 MDT 2018

Enabled Packages: SEACAS

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT_OPENMP => Test case MPI_RELEASE_DEBUG_SHARED_PT_OPENMP was not run! => Does not affect push readiness! (-1.00 min)
1) intel-debug-openmp-HSW => passed: configure-only passed => Not ready to push! (1.21 min)
2) intel-opt-openmp-HSW => passed: configure-only passed => Not ready to push! (1.23 min)
3) intel-debug-openmp-KNL => passed: configure-only passed => Not ready to push! (1.67 min)
4) intel-opt-openmp-KNL => passed: configure-only passed => Not ready to push! (1.57 min)
```

For the build `intel-opt-openmp-HSW` for example, the configure output showed:

```
-- Including ATDM build treaks file /home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/mutrino/tweaks/INTEL-RELEASE-OPENMP-HSW.cmake ...
-- Setting default Piro_MatrixFreeDecorator_UnitTests_MPI_4_DISABLE=ON
-- Setting default MueLu_CreateOperatorTpetra_MPI_1_DISABLE=ON
-- Setting default MueLu_CreateOperatorTpetra_MPI_4_DISABLE=ON
-- Setting default MueLu_ParameterListInterpreterTpetra_MPI_1_DISABLE=ON
-- Setting default MueLu_ParameterListInterpreterTpetra_MPI_4_DISABLE=ON
-- Setting default MueLu_ParameterListInterpreterTpetraHeavy_MPI_1_DISABLE=ON
-- Setting default MueLu_ParameterListInterpreterTpetraHeavy_MPI_4_DISABLE=ON
-- Setting default SEACASAprepro_aprepro_array_test_DISABLE=ON
-- Setting default SEACASAprepro_aprepro_command_line_include_test_DISABLE=ON
-- Setting default SEACASAprepro_aprepro_command_line_vars_test_DISABLE=ON
-- Setting default SEACASAprepro_aprepro_test_dump_reread_DISABLE=ON
-- Setting default SEACASAprepro_aprepro_unit_test_DISABLE=ON
-- Setting default SEACASAprepro_lib_aprepro_lib_array_test_DISABLE=ON
-- Setting default SEACASAprepro_lib_aprepro_lib_unit_test_DISABLE=ON
-- Setting default SEACASExodus_exodus_unit_tests_nc5_env_DISABLE=ON
-- Setting default SEACASExodus_exodus_unit_tests_DISABLE=ON
```

That looks like the right set of disables.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

This PR passed testing yesterday and it was approved over 40 minutes ago but the PR tester has yet to mark this as okay to merge.  What is up with that?  Is this a defect in the PR tester or is the PR tester not running?

**Comment by jwillenbring** [comment]
> This PR passed testing yesterday and it was approved over 40 minutes ago but the PR tester has yet to mark this as okay to merge. What is up with that? Is this a defect in the PR tester or is the PR tester not running?

The instance of the autotester that looks at this PR is currently testing another PR, so it will not be looked at again until that PR testing is done.

**Comment by bartlettroscoe** [comment]
> The instance of the autotester that looks at this PR is currently testing another PR, so it will not be looked at again until that PR testing is done.

@jwillenbring, okay, then it might be good to update the documentation to warn users that it might take up to 4+ hours or more for the Trilinos PR tester to realize that it is okay to merge after the auto PR builds have passed and approval is submitted.

This means that even if an auto PR tester build does not crash then it could take upwards of 8+ hours or more to allow the merge of a PR even if the PR is approved just after a PR testing iteration is complete.  That means that unless you get your PR in very early the morning, then you may not be around to merge it in time for nightly testing the the next day.

**Comment by bartlettroscoe** [comment]
> Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set. Either set Label AT: AUTOMERGE or manually merge the PR...

@trilinos/framework, has the `AT: AUTOMERGE` feature been implemented?

**Comment by allevin** [comment]
@bartlettroscoe @trilinos/framework,

Yes, the Automerge feature has been enabled, but the @trilinos/framework team is in the process of testing with a few controlled/monitored PR's.  Please refrain from using the `AT: AUTOMERGE` label until we are satisfied with its operation. 

A notification will be sent out when it is available for general usage.

**Pull request merged**
