### PR TITLE
Xpetra blockcrs fix to remove build warning

### PR DESCRIPTION
**Pull request by lucbv**
As discussed previously, here is my little patch to remove the warnings stemming from the deprecated function call used in '''xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp'''
It follows what @mhoemmen did in Tpetra so I feel somewhat confident that it should be ok?

As it is my first attempt at using kokkos feel free to educate me : )

### CODE REVIEW

**Comment by lucbv** [comment]
I am still running tests, for some reason the mpi4 tests are taking their time...

**Comment by lucbv** [comment]
I have compiled with:
'''
-D Trilinos_ENABLE_Kokkos=OFF \
-D Trilinos_ENABLE_Tpetra=OFF \
'''
and the changes are not creating any problem there. I also ran MueLu's unit test in serial and mpi without problems.
I did find an unrelated issue that I explain in #1599

**Comment by lucbv** [comment]
@mhoemmen , I pushed an updated version that does the size check and then resizes the array accordingly if needed.

**Comment by mhoemmen** [comment]
> @mhoemmen, I pushed an updated version that does the size check and then resizes the array accordingly if needed.

Thanks @lucbv !  Does it pass CUDA tests?

**Comment by lucbv** [comment]
I ran both MueLu and Xpetra tests with CUDA on geminga and it passed all our tests.
I also did eptra only and OpenMP builds.

**Comment by lucbv** [comment]
Alright, I think we are all OK with this so I'll merge it in.
Thanks for the comments!

**Pull request merged**
