### PR TITLE
Panzer: Make Epetra optional (CMake setup)

### PR DESCRIPTION
**Pull request by JacobDomagala**
CMake setup for making Epetra optional for Panzer.

Changes: 
- Add `Panzer_ENABLE_Epetra` CMake flag 
- Move `PANZER_HAVE_EPETRA` define to panzer core (which is used by all subpackages)
- Make Epetra (and all Epetra related packages) optional for `disc-fe`

### CODE REVIEW

**Comment by JacobDomagala** [comment]
@rppawlo  This is the first PR with the CMake setup. After this is merged, we'll start creating separate PRs for each test/example subdirectory

**Review by rppawlo — DISMISSED** [review]

**Comment by JacobDomagala** [comment]
Last commit should fix the issue. I forgot that I've added `Panzer_ENABLE_Epetra` :)

**Review by rppawlo — APPROVED** [review]

**Comment by mperego** [comment]
@JacobDomagala @rppawlo This is great! So glad that Panzer no longer requires Epetra!

**Comment by rppawlo** [comment]
@mperego - this is not done yet. This first commit was just setting up the cmake code. Jacob and Arik will be putting up more PRs over the next few weeks to complete this.

**Comment by mperego** [comment]
Ah OK.. well it's good that you folks are working on it!

**Pull request merged**
