### PR TITLE
Fix sys/times.h include on MinGW

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by jwillenbring** [comment]
@krcb If you want, please quickly evaluate the pull requests 305-309 and see if it will not break the standard Windows build, including a 64 bit OS. If they are changes that obviously should be applied, please apply them (but confirm with @kddevin before applying changes to Zoltan). If they are questionable, let's discuss them at the next Tuesday meeting. Please don't sink a lot of time into this initial evaluation before we speak about it if anything is questionable. Thanks.

**Comment by crtrott** [comment]
If you eventually apply them you need also to issue a pull request against the develop branch of Kokkos.

**Comment by kddevin** [comment]
I accepted the Zoltan changes; let me know if we need to revert.

**Comment by krcb** [comment]
I'm looking at each of these now with ICL15.

**Comment by krcb** [comment]
This is going to take a while: recent changes to tribits appear to be not functional on Windows, so those will have to be resolved first. I'll open the appropriate tickets.

**Comment by bmpersc** [comment]
Some of the Windows issues are known, but haven't been worked enough to get a fix pushed back to Trilinos. In the hopes that I can save you some time here is a patch for something I've had to fix to get a bit further through the windows build. Please Tag me on any issues you open for windows builds.

[lapack.patch.txt](https://github.com/trilinos/Trilinos/files/227034/lapack.patch.txt)

**Pull request merged**
