### PR TITLE
SEACAS: install scripts using GNUInstallDirs folders

### PR DESCRIPTION
**Pull request by bartgol**
@trilinos/seacas 

## Motivation

The issue linked below explains the problem. Since the rest of Trilinos is already installing in those dirs, we should avoid creating the "lib" folder just for a handful of scripts.

I'm not sure if this mods are wanted, but since I got the notification from gh actions about the linked issue being marked for closure, and since it was a quick fix, I acted on it. Feel free to disregard.

## Related Issues

* Closes 12328

## Testing

This PR does not touch src code per se, but I verified that with this PR the installation is entirely using GNUInstallDirs folders (e.g., no lib and lib64 in the install folder, just lib64, on my machine), and the scripts are indeed installed in the correct folder

### CODE REVIEW

**Review by gsjaardema — APPROVED** [review]
Looks good to me.  I will backport these changes to the seacas github repository

**Comment by bartgol** [comment]
The DCO action fail puzzles me. I *always* gpg sign my commits. And in this branch, they ARE signed:
```bash
$ git log -3 --show-signature seacas/scripts-cmake-mods-issue-12328 
commit 529762f6b99be76178bc7c75f736380f21e9aa81 (origin/seacas/scripts-cmake-mods-issue-12328, seacas/scripts-cmake-mods-issue-12328)
gpg: Signature made Wed 25 Sep 2024 09:18:27 AM MDT
gpg:                using RSA key 995C558F17A8E1D89E26C5F757A78766BD664498
gpg:                issuer "lbertag@sandia.gov"
gpg: Good signature from "Luca Bertagna <lbertag@sandia.gov>" [ultimate]
Author: Luca Bertagna <lbertag@sandia.gov>
Date:   Wed Sep 25 09:18:27 2024 -0600

    SEACAS: consistent cmake indentation in scripts folder

commit 95be0fd84105a7a318d0c594d116c27ce52d78ce
gpg: Signature made Wed 25 Sep 2024 09:17:47 AM MDT
gpg:                using RSA key 995C558F17A8E1D89E26C5F757A78766BD664498
gpg:                issuer "lbertag@sandia.gov"
gpg: Good signature from "Luca Bertagna <lbertag@sandia.gov>" [ultimate]
Author: Luca Bertagna <lbertag@sandia.gov>
Date:   Wed Sep 25 09:17:47 2024 -0600

    SEACAS: removed non-GNUInstallDirs logic in scripts installation

commit eb8f9673bc32ded9b10fa7f12d80d55c9d7c0035
gpg: Signature made Wed 25 Sep 2024 09:15:52 AM MDT
gpg:                using RSA key 995C558F17A8E1D89E26C5F757A78766BD664498
gpg:                issuer "lbertag@sandia.gov"
gpg: Good signature from "Luca Bertagna <lbertag@sandia.gov>" [ultimate]
Author: Luca Bertagna <lbertag@sandia.gov>
Date:   Wed Sep 25 09:15:52 2024 -0600

    SEACAS: use GNUInstallDirs in scripts installation
```

As for the other two actions, I see
```
2024-09-25T15:47:56.1239124Z /home/runner/spack/opt/spack/linux-rhel8-x86_64/gcc-10.3.0/libx11-1.8.4-b4sowpioh7if4wlmcn4bcvxcxzyrsi5i/include/X11/Xlib.h:44:10: fatal error: X11/X.h: No such file or directory
2024-09-25T15:47:56.1241721Z    44 | #include <X11/X.h>
2024-09-25T15:47:56.1242827Z       |          ^~~~~~~~~
2024-09-25T15:47:56.1243587Z compilation terminated.
```
which makes me think it's not this PR's fault?

**Comment by bartgol** [comment]
> @bartgol , DCO is not a digital signature, but a "sign-off" that you agree to the Developer Certificate of Origin (DCO) ([wiki.linuxfoundation.org/dco](https://wiki.linuxfoundation.org/dco)). You can do this with "git commit -s". Follow the "Details" link to get information on how to move forward.

Ah, I thought -s simply added the GPG signature. Thanks!

**Comment by rppawlo** [comment]
> Ah, I thought -s simply added the GPG signature. Thanks!

It's annoying. Case matters here. Uppercase is gpg, lowercase is signoff.

**Comment by bartgol** [comment]
> > Ah, I thought -s simply added the GPG signature. Thanks!
> 
> It's annoying. Case matters here. Uppercase is gpg, lowercase is signoff.

If only the person who invented casing had chosen a fishing trip that day...

**Pull request merged**
