### PR TITLE
Mini em2

### PR DESCRIPTION
**Pull request by egphill**
Mini-em driver. Solves Maxwell equations with a simple source. Stresses Tpetra solver stack through Teko and MueLu. Includes edits from Paul Lin.

@trilinos/panzer 

@eric-c-cyr 

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Checklist

- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
It's a bit hard to tell what files to look at.  Would it help to rebase against develop instead (which you'll need to do anyway)?

**Comment by egphill** [comment]
Oh, my mistake. That's what I meant to do. Should I just close this request and open another?

**Comment by mhoemmen** [comment]
@egphill You may have to delete it -- I don't see a way to change a PR's base.

**Comment by jmgate** [comment]
For future reference, you can click "Edit" to the right of the pull request title, and there will be a *base* drop-down menu you can change.

**Pull request closed without merging**
