### PR TITLE
Techx ml warnings

### PR DESCRIPTION
**Pull request by bddavid**
Techx ml warnings-as-errors

Attention:
@jwillenbring 

Silenced majority of warnings emitted by ml package for gcc >= 4.6 using preprocessor directives.
Please review, and if acceptable pull.

### CODE REVIEW

**Comment by jwillenbring** [comment]
@jhux2 

Jonathan,

Who is the best person to evaluate this pull request?

**Comment by jhux2** [comment]
> @jhux2
> 
> Jonathan,
> 
> Who is the best person to evaluate this pull request

Jim,

  Guess that would be me.  I'll put it on my to-do list.

Jonathan

**Comment by jwillenbring** [comment]
@maherou Including Mike so he can follow the status of this.

**Comment by jwillenbring** [comment]
@jhux2 Are these changes reasonable? It would be good to close this PR. Would it be useful if we could eventually run the new pull request testing tool against the changes, or would that not be sufficient?

**Comment by allevin** [comment]
@jhux2 Note: This PR is targeted towards master not develop branch.  The autotester will not test this PR.

**Comment by jhux2** [comment]
Closing, as this needs to be resubmitted against develop.

**Pull request closed without merging**
