### PR TITLE
Kokkos + KokkosKernels Promotion To 4.4.01

### PR DESCRIPTION
**Pull request by ndellingwood**
@trilinos/kokkos @trilinos/kokkos-kernels 

## Motivation

Update snapshot of Kokkos Ecosystem patch release 4.4.1

## Testing
PR and nightly testing of changes to respective repos; AT will handle the rest of the testing

### CODE REVIEW

**Review by lucbv — APPROVED** [review]

**Comment by sebrowne** [comment]
Definitely RETEST this, there was a back-end issue with the autotester.

**Review by crtrott — APPROVED** [review]

**Comment by ndellingwood** [comment]
@trilinos/framework @sebrowne the PR passed the blocking AT checks, but the `PR-13446-test-rhel8_aue-gnu-12.1.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-4523`  job reported failures, though they should be unrelated to this PR (no changes to gtest and no related build system changes):

https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=1859432
```
In file included from /scratch/trilinos/workspace/Trilinos_PR_python3@2/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest[gtest-all.cc:42](https://github.com/trilinos/Trilinos//blob/900995ca92de717b75cf7247310a3ec4b994dc42/gtest-all.cc#L42):
/scratch/trilinos/workspace/Trilinos_PR_python3@2/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest/src/gtest-death-test.cc: In function 'bool testing::internal::StackGrowsDown()':
/scratch/trilinos/workspace/Trilinos_PR_python3@2/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest[gtest-death-test.cc:1306](https://github.com/trilinos/Trilinos//blob/900995ca92de717b75cf7247310a3ec4b994dc42/gtest-death-test.cc#L1306):24: error: 'dummy' may be used uninitialized [-Werror=maybe-uninitialized]
 1306 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
[CTest: warning matched] /scratch/trilinos/workspace/Trilinos_PR_python3@2/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest[gtest-death-test.cc:1295](https://github.com/trilinos/Trilinos//blob/900995ca92de717b75cf7247310a3ec4b994dc42/gtest-death-test.cc#L1295):13: note: by argument 1 of type 'const void*' to 'void testing::internal::StackLowerThanAddress(const void*, bool*)' declared here
 1295 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
[CTest: warning matched] /scratch/trilinos/workspace/Trilinos_PR_python3@2/Trilinos/packages/sacado/test/GTestSuite/googletest/googletest[gtest-death-test.cc:1304](https://github.com/trilinos/Trilinos//blob/900995ca92de717b75cf7247310a3ec4b994dc42/gtest-death-test.cc#L1304):7: note: 'dummy' declared here
 1304 |   int dummy;
      |       ^~~~~
[CTest: warning matched] cc1plus: all warnings being treated as errors
```

Is this a preexisting issue?

**Comment by crtrott** [comment]
Also that is in GTest: not any trilinos stuff or Kokkos stuff.

**Comment by sebrowne** [comment]
That config is not designed to test any packages, only run the Python unit tests for our code.  The fact that any packages got enabled is a mistake, hence changing that build to non-blocking for now.  No worries about any of those failures.

**Pull request merged**
