### PR TITLE
Tpetra: remove deprecated compatibility headers

### LINKED ISSUE #13262: Tpetra: delete deprecated headers in tpetra/core/compat for Trilinos release 16.0
## Enhancement

A number of headers in `packages/tpetra/core/compat` are marked as deprecated.

https://github.com/trilinos/Trilinos/blob/d71aa67247678321da0b4ca2e822f28b8aed8db4/packages/tpetra/core/compat/CMakeLists.txt#L33-L42

Can they be deleted for Trilinos release 16.0?

@trilinos/tpetra @csiefer2

### PR DESCRIPTION
**Pull request by jhux2**
Closes #13262.

@trilinos/tpetra 

## Motivation

Preparation for next Trilinos major release, should simplify #13261.

## Related Issues

* Closes #13262.

## Stakeholder Feedback

N/A

## Testing

N/A

### CODE REVIEW

**Comment by jhux2** [comment]
I guess this PR is on the wrong AT track?

**Review by brian-kelley — DISMISSED** [review]

**Comment by jhux2** [comment]
@trilinos/framework @sebrowne  This PR has failed a couple times on the same test, `STKDoc_tests_stk_mesh_doc_tests_MPI_4`.  The same test fails in #13261.

**Comment by alanw0** [comment]
@jhux2 Sorry about that! There is an issue open about that test, it is a random failure. I'm trying to figure it out with valgrind, usan, etc.

**Comment by jhux2** [comment]
Maybe blocked by #13244.

**Comment by jhux2** [comment]
@trilinos/framework The AT reports failing, but there are no errors showing on the dashboard.

**Comment by achauphan** [comment]
> @trilinos/framework The AT reports failing, but there are no errors showing on the dashboard.

@jhux2 looked over the logs, and it seems like our non-blocking python build still blocked due to an edge case where the `get_dependencies.sh` script fails (due to CEE GitLab outage issues)... so I will place a retest here.

**Comment by jhux2** [comment]
@achauphan Thanks for the help!

**Pull request merged**
