### PR TITLE
Seacas snapshot 12 06 21

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas

## Motivation

Automatic snapshot commit from seacas at 2592b65f7c
Origin repo remote tracking branch: 'origin/master'
Origin repo remote repo URL: 'origin = https://github.com/gsjaardema/seacas'

At commit:

commit 2592b65f7cbaff70a9dc035fb0a4331177980b38
Author:  Greg Sjaardema <gsjaardema@gmail.com>
Date:    Thu Dec 2 16:41:07 2021 -0700
Summary: EXODUS: Clean up tests for new netcdf (no attribute creation order)

* Added TextMesh capability to IOSS
* Added Catalyst2 capability to IOSS
* all code run through new update of clang-format
* ALGEBRA: Support more variables
* APREPRO: Catch exception due to problem with variable addition
* APREPRO: Accurate line numbers in warning/error output
* CONJOIN: Clean up lib::fmt usage, clang-format
* Clean out some `ssize_t` uses -- use int64_t instead.
* EPU: Support edge and face blocks now.
* Convert a few remaining `printf` and `fprintf` to use lib::fmt library instead
* FASTQ: Eliminate some intel fortran warnings
* EXODUS: Eliminate variable dimscale attachement if NetCDF-4 library supports it (PR into NetCDF for this)
* EXODUS (tests) -- Eliminate attribute ordering warnings for NetCDF that support not tracking attribute creation ordering
* IOSS: Add overload of `describe` functions that returns vector instead of taking as output argument.
  * Modify most SEACAS uses to use this overload.
* IOSS: Better io_shell --compare output
* IOSS: Better support stripping trailing underscore from field names.
* IOSS: Support different entity types with duplicate names (sideset and elementblock can have same name now)
* IOSS: Better reproducibility on side block names that avoid having an id in the generated name
* IOSS: Better detection of CGNS parallel/serial library use
* IOSS: Support CGNS library builds without CG_SCOPING enabled
* EXODUS.PY: Add testing support

### CODE REVIEW

**Comment by gsjaardema** [comment]
Apologies for the number of 'white-space' changes.  Updated to a new version of clang-format and it reformatted many of the argument lists that involved pointers and references....

**Review by prwolfe — COMMENTED** [review]
You're right - that's a lot of white space changes ...

**Review by prwolfe — APPROVED** [review]

**Comment by gsjaardema** [comment]
@alanw0 There are a couple changes to the alias retrieval in some stk_io-related code.  This is a change in IOSS to allow multiple entities of different types to have the same name.  The corresponding snapshot into Sierra has been prepared and passed all testing and will be comitted soon...

**Comment by alanw0** [comment]
Sounds great, Thanks Greg.

**Review by alanw0 — DISMISSED** [review]

**Comment by gsjaardema** [comment]
@alanw0 @prwolfe Sorry for the churn.  Looks like autotester passed this time.  Could one of you re-review the PR.
Thanks.

**Review by alanw0 — APPROVED** [review]

**Pull request merged**
