### PR TITLE
New proxy setting to match the change Friday

### PR DESCRIPTION
**Pull request by prwolfe**
@trilinos/framework 

## Motivation
Now that the python systems are using the correct proxies and cert files we are failing due to the internal script settings. This just changes them to the new proxy.

### CODE REVIEW

**Review by jhux2 — APPROVED** [review]
lgtm!

**Comment by jhux2** [comment]
Is it ok to set this to auto-merge?

**Comment by jhux2** [comment]
Doesn't this PR need itself to be able to merge?

**Comment by prwolfe** [comment]
I have a ticket in with the Jenkins admins. That has similar required changes. Then this should run and merge.

**Pull request merged**
