### PR TITLE
Tpetra: Update License and Copyright

### PR DESCRIPTION
**Pull request by ccober6**
Update the License and Copyright files to

 * Reflect NTESS and new contract
 * Utilize SPDX identifiers within files
 * Make copyright and license files consistent across Trilinos packages (i.e., LICENSE and COPYRIGHT)

@trilinos/tpetra

### CODE REVIEW

**Review by jhux2 — COMMENTED** [review]
Kokkos uses an Apache 2.0 license: https://kokkos.org/kokkos-core-wiki/license.html.  Is this equivalent to BSD-3?

**Comment by ccober6** [comment]
I do not think so.  I just translated what was previously there.  @crtrott, was Kokkos previously licensed under BSD-3-Clause?  Some files in Trilinos have listed Kokkos with BSD-3-Clause.  :(

**Comment by jhux2** [comment]
@ccober6 Addressing #13262 may help by removing some of the files entirely.

**Comment by jhux2** [comment]
May be blocked by #13244.

**Comment by ccober6** [comment]
@jhux2 @csiefer2 , can you review this?  :)

**Review by csiefer2 — APPROVED** [review]

**Pull request merged**
