### PR TITLE
silence OS X Clang warnings

### PR DESCRIPTION
**Pull request by ibaned**
I just tried to compile on my Mac for the first time in a while, saw these and fixed them.

Unfortunately I can't access CEE resources till the end of this week, so its unlikely I'll be able to checkin test these before then.

Just putting up the PR for safe keeping.

@trilinos/teuchos

### CODE REVIEW

**Comment by mhoemmen** [comment]
The "cast to `void`" trick for unused variable warnings doesn't always work.  See, e.g., #1720.

**Comment by ibaned** [comment]
Everything I know is a lie... I hope this was only the case in #1720 because there existed code paths that could stop control flow before reaching the cast to `void`. In my experience this is the only reliable technique for silencing unused variable warnings.

**Comment by mhoemmen** [comment]
@ibaned wrote:
> Everything I know is a lie...

Welcome to the club ;-) .  NVCC emits a lot more warnings than other compilers.  Not sure why.  We've even done the GCC pragma thing for ignoring unused variables, and it also doesn't work reliably.

**Comment by ibaned** [comment]
Okay, I've switched the void cast back to an if statement (though I still have never seen that fail).

Any objections to starting the checkin script for this?

**Comment by mhoemmen** [comment]
@ibaned No objections; thanks for working on this!

**Comment by mhoemmen** [comment]
Thanks @ibaned ! :-D

**Pull request merged**
