### PR TITLE
TriBITS: Update License and Copyright

### LINKED ISSUE #13133: TriBITS:  Update License and Copyright
## Documentation

Update the License and Copyright files to

1. Reflect NTESS and new contract
2. Utilize SPDX identifiers within files
3. Make copyright and license files consistent across Trilinos packages (i.e., LICENSE and COPYRIGHT)

### PR DESCRIPTION
**Pull request by ccober6**
Update the License and Copyright files to
 * Reflect NTESS and new contract
 * Utilize SPDX identifiers within files
 * Make copyright and license files consistent across Trilinos packages (i.e., LICENSE and COPYRIGHT)

@trilinos/tribits 

* Closes #13133

### CODE REVIEW

**Comment by rppawlo** [comment]
Since tribits is a snapshotted package, won't these changes just get erased on the next sync?

**Comment by ccober6** [comment]
Ah yes.  I guess we will see if TriBITS would like to incorporate this changes.  One complication is there are several files outside of cmake/tribits and cmake/commonTools that have the TriBITS copyright header.  Do you know if that is correct?  Should they have a Trilinos header?

**Comment by ccober6** [comment]
@bartlettroscoe , how would you like to handle this?  At this point, I would suggest that these are suggestions which you can take or leave.  But it is an attempt to update the copyright and license formats, and would match the rest of Trilinos.  Thoughts?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe , how would you like to handle this? At this point, I would suggest that these are suggestions which you can take or leave. But it is an attempt to update the copyright and license formats, and would match the rest of Trilinos. Thoughts?

I will pull off this commit and apply it to the TriBITS repo and update the TriBITS snaphsot, to be safe.  (These are good changes that cut down on the overhead of creating new files.)

**Comment by ccober6** [comment]
Great!  Appreciate you helping with this!

**Comment by bartlettroscoe** [comment]
@ccober6, I think this is ready to merge.  I did the following:

* Pulled of the changes under `cmake/tribits/` using `git format-path` (after cherry-picking the commit to the `tribits_github_snapshot` branch) and applied it to the TriBITS repo with `git am` and tested and merged to the 'master' branch in the TriBITS repo in the PR https://github.com/TriBITSPub/TriBITS/pull/609.
* Trimmed down the original commit to remove the `cmake/tribits/` changes and kept the `commonTools/` changes.
* Snapshotted the updated TriBITS 'master' branch into the Trilinos branch https://github.com/trilinos/Trilinos/tree/tribits_github_snapshot.
* Merged the updated branch `tribits_github_snapshot` into this branch.
* Added a commit to remove a copyright header from a `FindTPL<tplName>.cmake` file.

(That might sound like a lot of complexity but it made the snapshots and merges very clean.)

**Review by bartlettroscoe — APPROVED** [review]
I will go ahead and approve this PR so it can merge.  I can't review all of the changes line-by-line because there is over 9K of lines changed.

These changes to TriBITS got merged to the TriBITS repo first so this will not cause any problems with TriBITS integration.

**Pull request merged**
