### PR TITLE
Tribits: MKL+SYCL TPL support

### PR DESCRIPTION
**Pull request by brian-kelley**
## Motivation
This PR allows OneAPI/MKL with SYCL support to be enabled in Trilinos, where it wasn't before. With MKL+SYCL enabled, KokkosKernels can call MKL kernels on both host and device.

This just requires OneAPI 2024.1 or above, since before that, the SYCL libraries were not available for the intel_lp64 interface that Trilinos needs. intel_lp64 means that BLAS/LAPACK functions use int (32-bit) argument types for dimensions and strides, while the intel_ilp64 interface uses int64_t for these. ilp64 is not compatible with Teuchos BLAS and LAPACK wrappers.

- If MKL and SYCL are both on, then search for the MKL and MKL_SYCL CMake targets with the 32-bit (intel_lp64) interface.
- If MKL is on but SYCL is off, then use libmkl_rt for MKL (this automatically links in host libraries with lp64).
- If MKL is enabled, explicitly use the MKL host libraries for BLAS and LAPACK (meaning the ``BLAS::all_libs`` and ``LAPACK::all_libs`` targets just point back to MKL libraries).
- Add ``MKL_PROVIDES_BLAS_LAPACK`` cmake variable to tell Trilinos packages (especially KokkosKernels) whether BLAS/LAPACK should be called with int or MKL_INT.

@trilinos/tribits @bartlettroscoe 
@trilinos/kokkos-kernels 

## Testing

This is mostly just build system changes, not code changes. Some of the CMake is exercised by builds that use MKL on the host only. The SYCL-specific changes will be exercised soon by a nightly Trilinos performance build. I tested the changes in both cases manually.

### CODE REVIEW

**Comment by brian-kelley** [comment]
BTW, if anyone has an idea on how to provide a helpful error message for when OneAPI version is < 2024.1, I would like to do that. The problem is that now, I don't think there's a way to know the version until ``find_package(MKL ...)`` and that already errors out when ``intel_lp64`` is selected as the interface.

**Review by bartlettroscoe — CHANGES_REQUESTED** [review]
@brian-kelley, thanks for taking the time to set up these `FindTPL<tplName>.cmake` files.  This is an interesting use case where all of the requirements for a downstream TPL are supplied by an upstream TPL in some cases (specifically when `MKL` is enabled, that `MKL::all_libs` target provides everything that is needed by BLAS and LAPACK).  But the current TriBITS TPL support software may not be set up to smoothly support this use case.

First, this is a great change in that  makes it easier to use the MKL BLAS and LAPACK implementations on machines where the MKL is provided.  (That used to be a pain in the past with a bunch of different libraries you had to link against and in a specific order.)

However, there may be a significant problem with the installed TriBITS-generated `BLASConfig.cmake` and `LAPACKConfig.cmake` files that are documented [here](https://tribitspub.github.io/TriBITS/users_guide/index.html#requirements-for-findtpl-tplname-cmake-modules) when `TPL_ENABLE_MKL=ON` and `Kokkos_ENABLE_SYCL=OFF`.  I think the files `BLASConfig.cmake` and `LAPACKConfig.cmake` files will be incorrectly calling `find_package(MKL)` while the installed TriBITS-generated `MKLConfig.cmake`	file will **not**.    Have you tested this with any downstream CMake projects using KokkosKernels through Trilinos with `find_package(KokkosKernels)` to see how this works?

Other than that, this PR should address:

* Update the comment at https://github.com/brian-kelley/Trilinos/blob/278c810222470aa6a9ad647bbfdd15480719e608/cmake/TPLs/FindTPLMKL.cmake#L12-L17 to mention that enabling MKL provides BLAS and/or LAPACK implementations when BLAS and/or LAPACK TPLs are enabled.  Right now, it is an old comment from Mark H. that says that the MKL does **not** provide the BLAS and LAPACK implementations (which is no longer true with with this commit).

* Define the optional dependency of the TriBITS BLAS and LAPACK External Packages/TPLs on the MKL External Package/TPL in the files `FindTPLBLASDependencies.cmake` and `FindTPLLAPACKDependencies.cmake`, respectively (see [`FindTPL<tplName>Dependencies.cmake`](https://tribitspub.github.io/TriBITS/users_guide/index.html#tpldefsdir-findtpl-tplname-dependencies-cmake)).  That tells TriBITS that there is an optional dependency on these TPLs for some types of scenarios.

As an alternative and cleaner implementation that would likely solve the issue described above, you might just consider defining optional dependencies of the BLAS and LAPACK TPLs on the MKL TPL by adding the files `FindTPLBLASDependencies.cmake` and `FindTPLLAPACKDependencies.cmake`, respectively (the latter already exists and just needs to add `MKL`).  Then I think you can might be able to just call `tribits_tpl_find_include_dirs_and_libraries(BLAS)` and `tribits_tpl_find_include_dirs_and_libraries(LAPACK)` to create the required wrapper targets and `<tplName>Config.cmake` files for BLAS and LAPACK, respectively.  That might just work (but I would have to check the unit tests for that use case).  And if that does not already work, it would likely be easy to get that use case to work and I could add a HowTo to https://tribitspub.github.io/TriBITS/users_guide/index.html#howtos called "Creating `FindTPL<tplName>.cmake` where all dependencies are satisfied by an upstream enabled dependent External Package/TPL".  I think that would make the installed TriBITS-generated `BLASConfig.cmake` and `LAPACKConfig.cmake` files work correctly.

**Comment by brian-kelley** [comment]
@bartlettroscoe Thanks a lot for the review. I'm realizing that I didn't think through the "MKL-as-BLAS" logic enough, especially if the TPL cmake files installed with Trilinos are broken. But this was kind of an extra change on top of my original goal, which was to allow MKL to be used on SYCL/GPU.

Is it OK with you to do the MKL/BLAS/LAPACK logic later, and just reduce this PR down to the SYCL changes? In the next FY I will have more time to do the other part correctly using FindTPLDependencies.cmake.

**Comment by bartlettroscoe** [comment]
> Is it OK with you to do the MKL/BLAS/LAPACK logic later, and just reduce this PR down to the SYCL changes? In the next FY I will have more time to do the other part correctly using `FindTPL<tplName>Dependencies.cmake`.

@brian-kelley, yes, if you just implement that case where `TPL_ENABLE_MKL=ON` and `Kokkos_ENABLE_SYCL=ON`, I think everything will work correctly.

But now that I think about it, if you link to two libraries that implement BLAS and LAPACK functions (e.g. one from the MKL library and one from say NetLib BLAS and LAPACK), could you not get link problems?  (But if the separate BLAS and LAPACK libraries are listed on link line first, the matching functions would get selected over the functions in the MKL libs.  But since there is no enforced dependency between BLAS, LAPACK and MKL, there is no guarantee that the BLAS and LAPACK libs will be listed first on the link line.  That can be fixed by declaring that ordering in `FindTPLBLASDependencies.cmake` and `FindTPLLAPACKDependencies.cmake`.)

The best solution to this problem is to just implement, test, and document the use case where a downstream TPL is fully specified by an upstream TPL.  (In this case the BLAS and LAPACK TPLs are fully specified by the upstream MKL TPL.)  That will be super clean and robust.  Let me know if you want to go with that option.

**Pull request closed without merging**
