### PR TITLE
Teuchos: fix typing of TwoDArray::operator[]

### PR DESCRIPTION
**Pull request by ibaned**
This operator must be rarely used, because
the return type doesn't match the type of
the expression returned (it should be
`ArrayView<const T>`, not `const ArrayView<T>`).
I'm fixing this because I need this operator
to unit test some YAML functionality I'm
developing.
(I can't use the operator(i, j) because there can
be no commas in the argument to TEST_NOTHROW).

@trilinos/teuchos 

This is a precursor to an upcoming PR

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Are there no unit tests for TwoDArray?  Looks like that class was written by a student back in 2011.  As per the policy:

* https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy

We should add tests to cover new/changed code (even if tests were missing before).

**Comment by ibaned** [comment]
There is unit testing for TwoDArray here:

https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/test/TwoDArray/TwoDArray_UnitTests.cpp

It looks like the bug I found only manifests if you use the `const` variant of `operator[]`, so I've added that to the unit tests and confirmed that it detects this bug (ed952af).

**Comment by bartlettroscoe** [comment]
If these simple changes get tested as part of the tests for #1112, then I am fine with not adding any additional unit tests.

**Comment by bartlettroscoe** [comment]
> so I've added that to the unit tests and confirmed that it detects this bug (ed952af)

Boy, you work fast @ibaned.  Thanks.  Please go ahead and use the checkin-test-sems.sh script to push with `--do-all --push`.   The [CI build for Trilinos](http://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Linux-GCC-4.7.2-MPI_RELEASE_DEBUG_SHARED_PT_CI&field2=groupname&compare2=61&value2=Continuous&field3=buildstarttime&compare3=84&value3=now) looks 100% clean right now so that should go through just fine.

**Comment by ibaned** [comment]
pushed as 669c427 and af1cda1

**Pull request closed without merging**
