### PR TITLE
superlu_dist: compile fix for v5.4.0

### PR DESCRIPTION
**Pull request by balay**
This issue is with xsdk build of trilinos with latest superlu_dist [version 5.4.0

This patch fixes this issue for me.

Either a merge  - or  a more appropriate patch - that gets the trilinos build working with superlu_dist v5.4.0 would be great!

This incompatibility also prevents petsc from using trilinos with superlu_dist-v5.4.0

cc: @keitat  as xsdk liaison to trilinos - please follow-up on this issue - and fill up all the necessary trilinos requirements  so that PR gets accepted or this incompatibility is resolved via a different patch

cc: @jwillenbring, @curfman

### CODE REVIEW

**Comment by mhoemmen** [comment]
@ndellingwood , I think you've worked on this sort of this for @trilinos/amesos2 before, right?

**Comment by ndellingwood** [comment]
Hi @mhoemmen, I added some boiler plate to the superlu_dist interface in Amesos2 when dealing with non-contiguous GIDs, and also worked on enhancing a previous PR for SuperLU 5 support to Amesos2. I can look at expanding on this PR to Amesos2, but I've been away traveling a fair amount lately (lots of Kokkos trainings :) and won't have time to look into it for a couple weeks.

**Comment by mhoemmen** [comment]
@trilinos/amesos2 

@ndellingwood Thanks! :D  Please don't worry about it -- the xSDK folks can be responsible for testing.  I just want to make sure that this patch is sane :)

**Comment by jwillenbring** [comment]
@ndellingwood Are you able to evaluate this patch? We are moving forward with an xSDK release soon. If not, can you suggest someone who could? Thanks.

**Comment by ndellingwood** [comment]
Cross-reference issue #3508. 
@jwillenbring @keitat what versions of superlu_dist is Trilinos required to support? If support for versions 4 and 5 is required could you point me to a testbed/resource with these TPLs available? I can update the PR and test if I have access to the proper environment.

**Comment by ndellingwood** [comment]
@jwillenbring @balay I updated the PR to guard the changes based on older (<5.4.0) vs newer versions of Superlu_Dist. Amesos compiles and unit tests pass with 4.2.0 and 5.2.2, more extensive testing will need to be done by someone with the configurations and systems needed by xsdk.

**Comment by ndellingwood** [comment]
@jwillenbring @balay I thought because I pulled this PR I would be able to modify it but I had to push in a new branch and PR instead. I suggest closing this PR in place of #3532, or @balay can pattern match those changes to this PR and update it.

**Comment by davydden** [comment]
> I thought because I pulled this PR I would be able to modify it but I had to push in a new branch and PR instead. I suggest closing this PR in place of #3532, or @balay can pattern match those changes to this PR and update it.

alternatively you can create a PR to @balay 's fork of Trilinos to the branch in this PR.

**Comment by ndellingwood** [comment]
From @balay:

> Note: these fixes [whichever PR gets merged] would have to eventually go into branch trilinos-release-12-14-branch

cc: @jwillenbring

**Comment by ndellingwood** [comment]
Merged into develop branch, thanks for the PR @balay!

**Comment by balay** [comment]
> From @balay:
> 
> > Note: these fixes [whichever PR gets merged] would have to eventually go into branch trilinos-release-12-14-branch
> 
reminder to xsdk folk: @jwillenbring, @keitat . Can you get this merged in?
cc: @curfman

**Comment by ndellingwood** [comment]
@jwillenbring I added the Release 12.14 label, can this PR also be cherry-picked to the 12.14 branch?

**Pull request merged**
