### PR TITLE
aztecoo: Fix memory corruption in the AZ_pgmres function

### PR DESCRIPTION
**Pull request by AndrewUshakov**
## aztecoo: Fix memory corruption in the AZ_pgmres function

@trilinos/aztecoo

Summary of changes:

    * Correct signatures of the functions AZ_manage_memory, AZ_allocate and AZ_realloc;
    * Correct type of the size field of the mem_ptr and widget structs;
    * Correct types of some local variables;
    * Correct conversions of/to integer types.

## Motivation

Issue #10334

## Testing

N/A

### CODE REVIEW

**Comment by AndrewUshakov** [comment]
As I understand, issue still exist and influences on the GOMA software. Please review this pull request!

**Comment by jhux2** [comment]
Let's run this through PR testing.

**Comment by jhux2** [comment]
@AndrewUshakov Is it possible to test this without requiring a large input matrix?

**Comment by AndrewUshakov** [comment]
@jhux2: This pull request corrects an error caused by an incorrect (too short) length of the parameter used to reserve the memory needed for the computation. If the matrix is small, there is no error even without using the discussed pool request. On the other hand, without big matrix it is impossible to verify that this patch fully fixes the problem.

I can only suggest generating it for testing.

**Review by rstumin — APPROVED** [review]
This looks good.  I don't have any great ideas on a new large matrix test for this, so I think it is good as is.

**Pull request merged**
