### PR TITLE
Framework: Switch CUDA AT2 build to be non-UVM and enable tests

### PR DESCRIPTION
**Pull request by sebrowne**
@trilinos/framework 

## Motivation
Want to align the CUDA AT2 build with the old AutoTester one.

## Related Issues
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-673

### CODE REVIEW

**Comment by sebrowne** [comment]
The CUDA tests look good, with four exceptions, detailed here: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=211376

@trilinos/intrepid2 I show that failing test was set to RUN SERIAL for CUDA builds, I can do that here as well if that's still what we want to do.
@trilinos/panzer that test is on for all other configs, no obvious framework-side issues to me.
@trilinos/rol that test is on for all other configs, no obvious framework-side issues to me.
@trilinos/stratimikos we had that test disabled for our non-CUDA container as well, but again, nothing really obvious from our side.

If any developers from the tagged teams can provide any insight for the four failing tests (and they do fail reliably), it would be much appreciated!  I can turn them off, but I wanted to at least do SOME due diligence and see what the community thinks.

**Comment by CamelliaDPG** [comment]
> @trilinos/intrepid2 I show that failing test was set to RUN SERIAL for CUDA builds, I can do that here as well if that's still what we want to do.

Yes, please.  The `MonolithicExecutable` test is one that has a lot of test cases, and some of them are intensive, so that sharing compute resources with other tests can lead to timeouts.  We use RUN SERIAL to mitigate.

**Comment by rppawlo** [comment]
@cgcgcg - would you mind taking a look at the panzer/mini-em failure here? Looks to be a linear solver issue similar to what you have fixed in the past.

**Comment by cgcgcg** [comment]
I see this message in the output of the failing Stratimikos and Panzer tests:
```
--------------------------------------------------------------------------
The call to cuIpcGetMemHandle failed. This means the GPU RDMA protocol
cannot be used.
  cuIpcGetMemHandle return value:   1
  address: 0x42b363c80
Check the cuda.h file for what the return value means. Perhaps a reboot
of the node will clear the problem.
--------------------------------------------------------------------------
```

**Comment by masterleinad** [comment]
> I see this message in the output of the failing Stratimikos and Panzer tests:

That looks like issues with `cudaMallocAsync`, see https://kokkos.org/kokkos-core-wiki/known-issues.html?highlight=known+issues#cuda, and https://kokkosteam.slack.com/archives/C5BGU5NDQ/p1726216998539829.

**Comment by sebrowne** [comment]
We do not.  I did do some debuggery and that particular error went away when I disabled the `smcuda` btl in OpenMPI.  I can try that option as well (the test I was using to debug did still fail my way, but it was a NaN in Belos instead of the CUDA traceback).

**Comment by sebrowne** [comment]
New results with the Kokkos option, my disable of the smcuda BTL, and running the Intrepid2 test serially: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=217579

Seeing the same tests fail (except for the Intrepid2 one), but in perhaps more-straightforwards way?  I see NaN errors from Belos.

**Comment by cgcgcg** [comment]
@sebrowne Thanks for adding the option. Seems like the message went away. I'll have another look to see what's wrong.

**Comment by jhux2** [comment]
> Thanks for adding the option. Seems like the message went away. I'll have another look to see what's wrong.

Fyi, The option `-DKokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF` resolved the same warning I was seeing on the CEE lan, and more importantly it let to a 2x speedup.

**Comment by cgcgcg** [comment]
I just went down the rabbit hole. The issue in this test
https://sems-cdash-son.sandia.gov/cdash/test/8036828
is caused by a bug in OpenBLAS before 0.3.27
https://github.com/OpenMathLib/OpenBLAS/commit/7e9b1c08074d1e88f446fc5861f44c8844e93d30
(Essentially, a double variable was wrongly interpreted as complex double and then the imaginary part was used in a division. If the imaginary part happened to be zero this resulted in a NaN.)
Updating the container to a more recent version of OpenBLAS should fix that test.

**Comment by sebrowne** [comment]
Perfect, thank you so much!  I'll get on fixing it ASAP.

**Comment by sebrowne** [comment]
Aaand now we look better!  Only one test failure remaining: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=287245

Also have four build errors that I've been discussing with @ndellingwood (can also be seen here: https://github.com/trilinos/Trilinos/pull/13571#issuecomment-2463732988).  Tagging @mperego since it seems to be related to a recent change to Intrepid2, but not 100% positive how to reliably reproduce it for now (without the container).

**Comment by ndellingwood** [comment]
Thanks for the update @sebrowne , adding a reference link here for the nvcc compiler segfaults occurring in intrepid2, https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=287260

**Comment by mperego** [comment]
Those tests that fail to compile were part of tests added in my last Intrepid2 PR. They use team-level parallelism for `Intrepid2::Basis::getValues` function. 
@ndellingwood do you have a way to reproduce these failures without using containers?

**Comment by ndellingwood** [comment]
@mperego I don't have a reproducer of this specific build, but I have been running into issues with apparent hang during linking with cuda/11.8.0, I'll send to you offline

**Comment by sebrowne** [comment]
There is still one failing test (it has failed and passed before on this PR): https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=288533

That test, `Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests_MPI_1`, is marked as run serial, which does not seem to have fully corrected its failure-proneness.  I do see it failing in the MueLu team's nightly ASan build as well (though there it times out after making it further through the list of unit tests).  Will ponder what approach to take here.

**Comment by ndellingwood** [comment]
@sebrowne in case this is relevant to your work on this PR, I'm seeing an X11 tpl config error with the cuda-11-uvm AT2 jobs, not sure if the TPL needs to be disabled here?
```
Processing enabled external package/TPL: X11 (enabled by SEACASSVDI, disable with -DTPL_ENABLE_X11=OFF)
-- X11_LIBRARY_NAMES='X11'
-- Must find at least one lib in each of the lib sets "X11"
-- Searching for libs in X11_LIBRARY_DIRS=''
-- Searching for a lib in the set "X11":
--   Searching for lib 'X11' ...
-- ERROR: Did not find a lib in the lib set "X11" for the TPL 'X11'!
-- ERROR: Could not find the libraries for the TPL 'X11'!
```
https://github.com/trilinos/Trilinos/actions/runs/11943651519/job/33293100503?pr=13589

**Comment by sebrowne** [comment]
> @sebrowne in case this is relevant to your work on this PR, I'm seeing an X11 tpl config error with the cuda-11-uvm AT2 jobs, not sure if the TPL needs to be disabled here?

Yes, it does, but I'm going to leave standing the UVM build up "for real" for a later date.  I've disabled X11 for the non-UVM build here.

**Review by achauphan — APPROVED** [review]

**Pull request merged**
