### PR TITLE
compatibility with SuperLU 5

### PR DESCRIPTION
**Pull request by nschloe**
This is @bavier's patch from https://github.com/trilinos/Trilinos/issues/379.

### CODE REVIEW

**Comment by jwillenbring** [comment]
@srajama1 Is this something you can look at?

**Comment by srajama1** [comment]
I will look at this. @trilinos/amesos2 Please include the team id or me directly for future pull requests.

**Comment by nschloe** [comment]
@srajama1 Have you have a chance to look at it yet?

**Comment by srajama1** [comment]
Sorry, fell off the radar. Let me prioritize this.

**Comment by nschloe** [comment]
@srajama1 We're putting out a new release for Debian soon. Would be nice to get this in.

**Comment by bmpersc** [comment]
@ndellingwood 's Pull request #1643  basically includes this commit and addresses some of the concerns with variable naming. I'm closing this in favor of Nathan's PR. @nschloe thank you for your submission.

**Pull request closed without merging**
