### PR TITLE
Kokkos-kernels Resolve compilation error pertaining to cher, zher, cher2, and zher2 usage

### PR DESCRIPTION
**Pull request by MalachiTimothyPhillips**
Fix for https://github.com/trilinos/Trilinos/issues/12962
@ndellingwood Mind looking at this MR (or adding someone else)? Thanks!

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]
Thanks @MalachiTimothyPhillips !
Changes match those in https://github.com/kokkos/kokkos-kernels/pull/2183, which has been approved; after that PR presumably passes testing we can mark this AUTOMERGE

**Comment by MalachiTimothyPhillips** [comment]
Would I have avoided this following test error by creating the pull request under my Sandia handle (@malphil)?

https://github.com/trilinos/Trilinos/actions/runs/8822731702/job/24221588705?pr=12963

```
A job started hook has been configured by the self-hosted runner administrator
Run '/home/runner/snl_verify.sh'
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
[2024-04-24T20:14:56Z ERROR github_api_requester] Failure Status for user MalachiTimothyPhillips: 404 Not Found
[2024-04-24T20:14:56Z ERROR verification::job_approver] Initiating User MalachiTimothyPhillips is not approved to run jobs on this machine.
[2024-04-24T20:14:56Z INFO  verification] Job is not approved
Error: Process completed with exit code 1.
```

**Comment by ndellingwood** [comment]
> Would I have avoided this following test error by creating the pull request under my Sandia handle (@malphil)?
> 
> https://github.com/trilinos/Trilinos/actions/runs/8822731702/job/24221588705?pr=12963
> 
> ```
> A job started hook has been configured by the self-hosted runner administrator
> Run '/home/runner/snl_verify.sh'
>   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
> [2024-04-24T20:14:56Z ERROR github_api_requester] Failure Status for user MalachiTimothyPhillips: 404 Not Found
> [2024-04-24T20:14:56Z ERROR verification::job_approver] Initiating User MalachiTimothyPhillips is not approved to run jobs on this machine.
> [2024-04-24T20:14:56Z INFO  verification] Job is not approved
> Error: Process completed with exit code 1.
> ```

@MalachiTimothyPhillips that check is a non-blocking experimental check (we can merge without it passing), though I'm not sure of the failure cause - @sebrowne @trilinos/framework can you help us understand some of the nuances of this check?

**Comment by achauphan** [comment]
> 
> @MalachiTimothyPhillips that check is a non-blocking experimental check (we can merge without it passing), though I'm not sure of the failure cause - @sebrowne @trilinos/framework can you help us understand some of the nuances of this check?

Yep, so like the current AutoTester, the AutoTester2 will need a special label applied to the PR to approve PR testing on the latest commit made by a user outside of the Trilinos Developers GitHub team. @ndellingwood, just like how you applied the `AT: Pre-test Inspected` label earlier, you would need to add the `AT2-Start` label for AutoTester2, and then I believe anyone can request the jobs to re-run by clicking on the status check's 'details' -> 're-run jobs' in the top right.

**Pull request merged**
