### PR TITLE
Framework: Add RHEL8 Anaconda3 configuration

### PR DESCRIPTION
**Pull request by sebrowne**
@trilinos/framework 

## Motivation
Need this environment for running the Framework unit tests.

## Related Issues
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-653
https://cee-gitlab.sandia.gov/trilinos-project/srn-ini-files/-/merge_requests/76

## Testing
I ran the config + tests, and the only one that failed was because I don't have pytest-cov installed.  The scripts should take care of that for us, so this should be good to go (odds are, at least).

### CODE REVIEW

**Comment by sebrowne** [comment]
Unrelated GPU failure, RETESTing

**Review by achauphan — APPROVED** [review]

**Comment by sebrowne** [comment]
Appears to be another process failure, RETESTing

**Comment by sebrowne** [comment]
Internal repo was down, RETESTing

**Comment by sebrowne** [comment]
@achauphan can I get a fresh review?  Had to rebase

**Review by achauphan — APPROVED** [review]

**Pull request merged**
