### PR TITLE
packages/framework: Try to set CTEST_USE_LAUNCHERS to ON again

### PR DESCRIPTION
**Pull request by e10harvey**
@trilinos/framework, @bartlettroscoe, @zackgalbreath 

## Motivation

See #10836. 

## Testing

This will be tested manually before merging.

### CODE REVIEW

**Comment by e10harvey** [comment]
[Manual testing results](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-10955-test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-789&field3=buildstamp&compare3=61&value3=20220830-1700-Experimental).

**Comment by e10harvey** [comment]
According to https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic141&field2=buildname&compare2=61&value2=PR-__UNKNOWN__-test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-793&field3=buildstamp&compare3=61&value3=20220830-1712-Experimental, this change is not required.

**Comment by bartlettroscoe** [comment]
> According to https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic141&field2=buildname&compare2=61&value2=PR-__UNKNOWN__-test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-793&field3=buildstamp&compare3=61&value3=20220830-1712-Experimental, this change is not required.

@e10harvey, how does that CDash link show this change is not needed?

**Comment by e10harvey** [comment]
Please see the associated console output. It shows that CTEST_USE_LAUNCHERS is set to ON.

**Comment by bartlettroscoe** [comment]
> Please see the associated console output. It shows that CTEST_USE_LAUNCHERS is set to ON.

@e10harvey, what URL?

**Comment by e10harvey** [comment]
@bartlettroscoe : Please see https://do.sandia.gov/trilinos-ci/job/Trilinos_PR_python3/793/console.

**Pull request closed without merging**
