### PR TITLE
Tpetra: Fix #6838

### LINKED ISSUE #6838: Tpetra:  hang in graph->fillComplete
## Bug Report
@trilinos/tpetra 

@jhux2 @mhoemmen @rppawlo 

### Description
Running on 16 MPI ranks causes a critical problem to hang in a fill complete for EMPIRE

In this code in panzer in building the projection objects

```
Teuchos::RCP<const Tpetra::CrsGraph<LocalOrdinalT,GlobalOrdinalT,NodeT> >
BlockedTpetraLinearObjFactory<Traits,ScalarT,LocalOrdinalT,GlobalOrdinalT,NodeT>::
buildTpetraGraph(int i,int j) const
{
   using Teuchos::RCP;
   using Teuchos::rcp;

   // build the map and allocate the space for the graph and
   // grab the ghosted graph
   std::cout << "A "<<comm_->getRank()<<std::endl;
   RCP<const MapType> map_i = getMap(i);
   RCP<const MapType> map_j = getMap(j);
   std::cout << "B "<<comm_->getRank()<<std::endl;

   RCP<CrsGraphType> graph  = rcp(new CrsGraphType(map_i,0));
   RCP<const CrsGraphType> oGraph = getGhostedGraph(i,j);

   std::cout << "C "<<comm_->getRank()<<std::endl;
   // perform the communication to finish building graph
   RCP<const ExportType> exporter = getGhostedExport(i);
   std::cout << "D "<<comm_->getRank()<<std::endl;
   graph->doExport( *oGraph, *exporter, Tpetra::INSERT );
   std::cout << "E "<<comm_->getRank()<<std::endl;
   graph->fillComplete(map_j,map_i);
   std::cout << "F "<<comm_->getRank()<<std::endl;

   return graph;
}
```

 mpirun -np 16 /home/mbetten/build/debug/empire/EMPIRE-PIC/src/EMPIRE_PIC.exe --kokkos-numa=1 --kokkos-threads=1 --I=BDot.yaml

several times the code gets to and through this but after like 3 or 4 things we have all 16 ranks get to E and non get past that...  

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra 

## Motivation

Proposed fix for #6838.  Please do not merge yet; we want to test it in the application first.

## Related Issues

* Closes #6838 

## Stakeholder Feedback

See #6838 discussion; this is a candidate fix for a hang in EMPIRE.

## Testing

Tested locally, Tpetra only, Mac Clang + OpenMPI.

### CODE REVIEW

**Comment by bathmatt** [comment]
testing this now..
the instructions here cause a conflict btw.

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b mhoemmen-Fix-6838 develop
git pull https://github.com/mhoemmen/Trilinos.git Fix-6838
Step 2: Merge the changes and update on GitHub.

git checkout develop
git merge --no-ff mhoemmen-Fix-6838
git push origin develop

**Comment by bathmatt** [comment]
still hangs

**Comment by bathmatt** [comment]
wait, never mind, 
it looks like it is fixed..  
machine was being hammered and it started..

**Comment by mhoemmen** [comment]
@bathmatt Could you please confirm that these changes fix EMPIRE?  Thanks!

**Comment by bathmatt** [comment]
It fixed the deadlock, 
I've not ran the full suite of tests

**Comment by mhoemmen** [comment]
@bathmatt Thanks for the confirmation!

**Comment by mhoemmen** [comment]
Thanks everyone! :-D

**Comment by bathmatt** [comment]
Thanks!

**Pull request merged**
