### PR TITLE
Trilinos:  Deprecate four packages OptiPack, GlobiPack, Trios, Claps

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/optipack @trilinos/globipack @trilinos/trios @trilinos/claps @trilinos/framework 

## Description
The following four packages are scheduled for deprecation and removal from the Trilinos repository:
-   OptiPack
-    GlobiPack
-    Trios
-    Claps

The packages will be deprecated in mid-April 2019, and will be removed from the Trilinos develop and master branches in mid-May 2019.
This PR adds deprecation warnings.

## Motivation and Context
Reducing cost of Trilinos maintenance by removing unused / obsolete packages.

## How Has This Been Tested?

For Claps, OptiPack, GlobiPack:
cmake \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D CMAKE_BUILD_TYPE:STRING=DEBUG  \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
\
-D MPI_BASE_DIR:PATH=/Users/InstalledSoftware/openmpi-1.8.3 \
-D TPL_ENABLE_MPI:BOOL=ON \
\
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D Trilinos_ENABLE_GlobiPack:BOOL=ON \
\
-D Trilinos_ENABLE_OptiPack:BOOL=ON \
-D Trilinos_ENABLE_Piro:BOOL=ON \
-D Piro_ENABLE_OptiPack:BOOL=ON \
-D Piro_ENABLE_ROL:BOOL=OFF \
-D Trilinos_ENABLE_ROL:BOOL=OFF \
-D Trilinos_ENABLE_MOOCHO:BOOL=OFF \
-D Trilinos_ENABLE_Tempus:BOOL=OFF \
-D Trilinos_ENABLE_Stokhos:BOOL=OFF \
-D Trilinos_ENABLE_Rythmos:BOOL=OFF \
-D Trilinos_ENABLE_MueLu:BOOL=OFF \
-D Trilinos_ENABLE_Ifpack2:BOOL=OFF \
-D Trilinos_ENABLE_NOX:BOOL=OFF \
-D NOX_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Tpetra_INST_INT_INT:BOOL=ON \
-D Tpetra_INST_INT_LONG_LONG:BOOL=OFF \
-D Trilinos_ENABLE_TriKota:BOOL=OFF \
-D Piro_ENABLE_TESTS=ON \
-D Piro_ENABLE_EXAMPLES=ON \
-D OptiPack_HIDE_DEPRECATED_CODE=ON \
\
-D Trilinos_ENABLE_Claps:BOOL=ON \
-D Claps_ENABLE_EXAMPLES:BOOL=ON \
-D Claps_ENABLE_TESTS:BOOL=ON \
-D TPL_ENABLE_METIS:BOOL=ON \
-D METIS_LIBRARY_DIRS:FILEPATH="/Users/InstalledSoftware/ParMETIS_4.0.3/32bit" \
-D METIS_INCLUDE_DIRS:FILEPATH="/Users/InstalledSoftware/ParMETIS_4.0.3/32bit" \
\
-D Teuchos_ENABLE_STACKTRACE=OFF \
..

Trios builds did not succeed on my platform, but the deprecation warnings were correctly emitted.  The build errors did not appear to be related to these changes.

cmake \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D CMAKE_BUILD_TYPE:STRING=DEBUG  \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
\
-D MPI_BASE_DIR:PATH=/Users/InstalledSoftware/openmpi-1.8.3 \
-D TPL_ENABLE_MPI:BOOL=ON \
\
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D Trilinos_ENABLE_GlobiPack:BOOL=ON \
-D Trilinos_ENABLE_OptiPack:BOOL=ON \
\
-D Trilinos_ENABLE_Trios:BOOL=ON \
-D Trilinos_ENABLE_Triossupport=ON \
-D Trilinos_ENABLE_Triostests=ON \
-D Trilinos_ENABLE_Triosprograms=ON \
-D Trilinos_ENABLE_Triosexamples=ON \
-D Trilinos_ENABLE_Triosnnti=ON \
-D Trilinos_ENABLE_Triosnssi=ON \
\
-D Teuchos_ENABLE_STACKTRACE=OFF \
.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.  (DEPRECATION WARNINGS EMITTED)
- [ x] These changes break backwards compatibility. (THAT'S THE POINT)

### CODE REVIEW

**Comment by kddevin** [comment]
@bartlettroscoe and @rppawlo thanks for reviewing this PR.

@bartlettroscoe I did follow the instructions you cited; thanks.  By putting the deprecation warning in OptiPack_Config.h.in and GlobiPack_Config.h.in , they will be included in OptiPack_Config.h and GlobiPack_Config.h, which should be (and, indeed, appear to be) included in all headers.

I understand that deprecating these isn't the highest priority, but they were easy to do while deprecating the other packages.

**Comment by prwolfe** [comment]
The testing here seems to have failed to launch due to a Jenkins error.  I will report this to see and see if I can get it running again.

**Comment by kddevin** [comment]
A question for @trilinos/framework gurus:   

Using @bartlettroscoe 's instructions, I added deprecation warnings to header files of packages that will be deprecated.  The instructions tell me to use the #warning pre-processor directive.  But then the PR tests that specify -Werror fail.  

What is the correct way to deprecate header files and still pass the PR testing?  
Can -Werror be disabled for the packages that are going to be deprecated?

**Comment by ZUUL42** [comment]
> A question for @trilinos/framework gurus:
> 
> Using @bartlettroscoe 's instructions, I added deprecation warnings to header files of packages that will be deprecated. The instructions tell me to use the #warning pre-processor directive. But then the PR tests that specify -Werror fail.
> 
> What is the correct way to deprecate header files and still pass the PR testing?
> Can -Werror be disabled for the packages that are going to be deprecated?

[_Currently_ `Werror` can be set & turned off package by package](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake). _However_, we are moving towards setting `Werror` _universally_ as to cover new packages that are introduced. So that capability will go away soon.
Given that, as far as the "correct way" to warn about incoming deprecation while still having `Werror` set, I'll have to discuss that and get back to you.

**Comment by bartlettroscoe** [comment]
You could add `-Wno-error=deprecated-declaration` to the CXX_FLAGS for the deprecated packages as that will avoid triggering errors when deprecated warnings are emitted.

May not want to add `-Wno-error=deprecated-declaration` globally because we want to try to make sure people refactor downstream in Trilinos when they deprecate things. We want to make sure that users don't see deprecated warnings from incomplete deprecation and refactoring in Trilinos like what happened in #4770.  With that deprecation warning, there is nothing that SPARC could do to get rid of it.  That is not good.

**Comment by mhoemmen** [comment]
@bartlettroscoe The issue is that we don't have a way to deprecate an entire header file, other than to put a `#warning` in it.  Those are warnings, but _not_ deprecated warnings.

**Comment by bartlettroscoe** [comment]
@mhoemmen said:

> The issue is that we don't have a way to deprecate an entire header file, other than to put a #warning in it. Those are warnings, but not deprecated warnings.

Right.  I guess one could ifdef the warning like:

```
#if !defined(TRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS)
#  ifdef __GNUC__
#    warning "The package Trios is deprecated in April 2019; it will be removed from Trilinos in May 2019."
#  endif
#endif
```

Then `-DTRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS` could be added to the PR builds that have `-Werror`.    What about that?

**Comment by mhoemmen** [comment]
@bartlettroscoe You're brilliant :-D Thanks for the good idea!

**Comment by kddevin** [comment]
@trilinos/framework @ZUUL42 
Can the idea from @bartlettroscoe be implemented in the PR tests?  I can add the ifdef tests to the headers if you can add the cmake flag to the PR tests.
I'd like to get this PR into the minor release branch this week so that we can remove the packages for the major release later this year.

**Comment by bartlettroscoe** [comment]
@kddevin, you should be able to create a commit in your branch that adds these to the cmake_CXX_FLAGS var in the file:

```
Trilinos/cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
```

**Comment by kddevin** [comment]
Thanks, @bartlettroscoe 
I do not feel comfortable making a change to PR testing without @trilinos/framework approval.  
Are you granting that approval?

**Comment by ZUUL42** [comment]
@kddevin it's OK. I've been keeping an eye on this thread and this solution looks good to me.
It's easier to have it all set and tested in one PR. So, go ahead and add the flag you need to `PullRequestLinuxGCC7.2.0TestingSettings.cmake`. That's the only place we are setting -Werror currently.
That should get this PR finished and set a standard for how to deal with deprecation warnings in the future.

**Comment by kddevin** [comment]
@ZUUL42 @bartlettroscoe 
I implemented and pushed the suggested scheme.  I re-enabled testing for this PR.
Would you please re-review?  Thanks.

**Comment by ZUUL42** [comment]
@kddevin, that appears to only set it for Piro. Also that doesn't appear to be the latest version of the cmake file that is in develop. So, you're not seeing the line 
`set (OptiPack_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror" CACHE STRING "Warnings as errors setting")`
 that I would assume these warnings are becoming errors because of.

However, if we're still needing to make a change, I would say we should just set that flag for _all_ packages. Then this method is in place for any packages that needs to have deprecation warnings in the future, especially since all of the individual package lines will disappear one day soon.
So I'd add -DTRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS on line 26 at the end of all the other project wide Werror related flags.

Though my syntax could be off, but it may be we want something like:
`set (TRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS ON CACHE BOOL "Hide deprecated header warnings from Werror settings")`
I'll run a couple builds and confirm, but if anything you push passes the PR, great. I'll take care of anything else later in that case.

**Comment by kddevin** [comment]
@ZUUL42 
OK, I added the HIDE flag to Optipack and Globipack as well.
I hesitated to add it for all packages.  Individual package developers should be aware when they deprecate files, so doing their own packages is probably best.
I'll need a re-review.  Thanks!

**Comment by sethrj** [comment]
@kddevin Tracking down an "unused variable" warning through spack, it looks like this pull request removed the optional external repository package `Mesquite`. Was that intentional?  https://github.com/spack/spack/pull/24820

**Pull request merged**
