### PR TITLE
Extend fusedImport/Export interfaces Epetra - rebased

### PR DESCRIPTION
**Pull request by tawiesn**
Reordered patches, rebased on current develop branch

### CODE REVIEW

**Comment by mhoemmen** [comment]
This pull request supersedes #605.

**Comment by mhoemmen** [comment]
I am testing this, per request by @tawiesn .  @csiefer2 also has an interest in this.

**Comment by mhoemmen** [comment]
@tawiesn You may want to adjust the Epetra changes at some point, so that they don't print to std::cout in case of error.  This could end badly if the number of processes is large.  I'm prepared to accept the changes as-is (after finishing tests) if you wouldn't mind revisiting Epetra error output at some point (no rush).  Thanks!

**Comment by mhoemmen** [comment]
My MPI_DEBUG configuration (GCC 4.7.2, Kokkos and Teuchos bounds checking enabled) passes all 64 enabled MueLu tests.  MueLu_UnitTestsTpetra_MPI_1 takes nearly five minutes when I enable the bounds checking options; that's why it took so long :-) (total time: 827.95 s).

**Comment by mhoemmen** [comment]
My MPI_RELEASE configuration has some build errors:

[ 60%] Building CXX object packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_AggregationExportFactory.cpp.o
In file included from .../Trilinos/packages/muelu/src/Utils/MueLu_Utilities_decl.hpp:59:0,
                 from .../MPI_RELEASE/packages/muelu/src/MueLu_Utilities.hpp:1,
                 from .../Trilinos/packages/muelu/src/MueCentral/MueLu_Level.hpp:68,
                 from .../Trilinos/packages/muelu/src/MueCentral/MueLu_Factory.hpp:65,
                 from .../Trilinos/packages/muelu/src/MueCentral/MueLu_TwoLevelFactoryBase.hpp:51,
                 from .../Trilinos/packages/muelu/src/Utils/MueLu_AggregationExportFactory_decl.hpp:60,
                 from .../Trilinos/packages/muelu/src/Utils/MueLu_AggregationExportFactory_def.hpp:60,
                 from .../MPI_RELEASE/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_AggregationExportFactory.cpp:55:
.../Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp:507:88: error: conflicting declaration ‘const Teuchos::RCP<const Xpetra::Export<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > > exporter’
.../Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp:506:69: error: ‘exporter’ has a previous declaration as ‘const Xpetra::Export<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >& exporter’
.../Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp:505:5: error: ‘Xpetra::TpetraBlockCrsMatrix<Scalar, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >::TpetraBlockCrsMatrix(const Teuchos::RCP<const Tpetra::Experimental::BlockCrsMatrix<Scalar, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >&, const Xpetra::Export<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >&, const Teuchos::RCP<const Xpetra::Map<> >&, const Teuchos::RCP<const Xpetra::Map<> >&, const Teuchos::RCP<Teuchos::ParameterList>&)’ cannot be overloaded
.../Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp:488:5: error: with ‘Xpetra::TpetraBlockCrsMatrix<Scalar, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >::TpetraBlockCrsMatrix(const Teuchos::RCP<const Tpetra::Experimental::BlockCrsMatrix<Scalar, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> > >&, const Xpetra::Export<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >&, const Teuchos::RCP<const Xpetra::Map<> >&, const Teuchos::RCP<const Xpetra::Map<> >&, const Teuchos::RCP<Teuchos::ParameterList>&)’
make[2]: *** [packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_AggregationExportFactory.cpp.o] Error 1
make[1]: *** [packages/muelu/src/CMakeFiles/muelu.dir/all] Error 2
make: *** [all] Error 2

**Comment by mhoemmen** [comment]
The build errors might be easy to fix.  Let me try.

**Comment by mhoemmen** [comment]
Hm, not really.  It looks like the interface either wants an RCP or a reference.  Not my call to figure out which one you want.

**Comment by tawiesn** [comment]
Let me have a look.

**Comment by tawiesn** [comment]
I've created a patch where i remove the default parameters from the new constructors to avoid the conflicts with the pre-existing constructors (which have one parameter less). At some point we will probably get rid of the old constructors, since they should not be used any more. There is no reason to have them (backwards compatibility should be not a problem). But this is an extra step.
If you have time, could you test it?

Maybe it's a good idea if you run the checkin script but do not push. If the checkin script passes on your machine, i can merge the last two Xpetra related patches into one.

**Comment by mhoemmen** [comment]
> If you have time, could you test it?

Gladly! :-)
 
> Maybe it's a good idea if you run the checkin script but do not push. If the checkin script passes on your machine, i can merge the last two Xpetra related patches into one.

I'll work on that right now.

**Comment by mhoemmen** [comment]
> I've created a patch where i remove the default parameters from the new constructors to avoid the conflicts with the pre-existing constructors (which have one parameter less). At some point we will probably get rid of the old constructors, since they should not be used any more.

I'm a bit confused -- is that patch here on the pull request?  If not, could you send it to me, please?

**Comment by mhoemmen** [comment]
I'm testing the new patch now.

**Comment by mhoemmen** [comment]
MPI_DEBUG (GCC 4.7.2) passed tests.
Building MPI_RELEASE (Intel 16) now.
SERIAL_RELEASE (GCC 4.7.2) will be last.

**Comment by mhoemmen** [comment]
MPI_RELEASE passes tests.

**Comment by mhoemmen** [comment]
This pull request passes MueLu tests: MPI_DEBUG, SERIAL_RELEASE (both GCC 4.7.2) and MPI_RELEASE (Intel 16).

**Comment by tawiesn** [comment]
Merged and pushed the patches.
@mhoemmen, @csiefer2 Thanks for reviewing and testing!

**Pull request closed without merging**
