### PR TITLE
ifpack2: add missing print guard in blocktridiagcontainer

### PR DESCRIPTION
**Pull request by tmranse**
@trilinos/ifpack2 @kliegeois 

This MR fixes a missed printf statement that wasn't wrapped in a `IFPACK2_BLOCKTRIDICONTAINER_USE_PRINTF` leading to unwanted printing to `stdout` in apps using the container.

### CODE REVIEW

**Review by kliegeois — APPROVED** [review]
Thanks for doing this!

**Comment by tmranse** [comment]
@kliegeois any idea why I'm getting clang-format yelling for unrelated files? I can apply the patch anyways if you think that'd appease it

**Comment by kliegeois** [comment]
@tmranse yes, the clang format test is not yet `required` and therefore there are other files than the one you modified that are not yet compliant with the format.
You can disregard that check for now.

**Comment by tmranse** [comment]
> @tmranse yes, the clang format test is not yet `required` and therefore there are other files than the one you modified that are not yet compliant with the format. You can disregard that check for now.

Gotcha, thanks for the clarification. I don't think I have merge permissions so feel free to merge on my behalf when CI passes

**Pull request merged**
