### PR TITLE
Zoltan2: Refactor of BasisVectorAdapter to use Kokkos data structures

### PR DESCRIPTION
**Pull request by mperrinel**

### CODE REVIEW

**Review by egboman — APPROVED** [review]
These changes are as discussed in meetings. Thanks!

**Review by egboman — DISMISSED** [review]
Looks good. Thanks.

**Comment by JacobDomagala** [comment]
@egboman @stmcgovern Could any of you add `AT: PRE-TEST INSPECTED` label? Thanks.

**Comment by stmcgovern** [comment]
> Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging ERROR: LABEL SET BY UNAPPROVED USER 'stmcgovern', INSPECTION IS INVALID! - This PR must be re-inspected by approved user.

@egboman I'm no longer able to apply the label.

**Comment by egboman** [comment]
Added the label, so should run now I hope.

**Comment by cwschilly** [comment]
@egboman This should be good to go now, pending approval and another CI run

**Review by egboman — APPROVED** [review]
Thanks!

**Pull request merged**
