### PR TITLE
Panzer: IntegrationValues2 optimization

### PR DESCRIPTION
**Pull request by seanofthemillers**
@trilinos/panzer

## Motivation

This is an optimization to bypass a launch-latency bound interface in Intrepid2. Currently, if Intrepid2 is passed a cell indexed array for `Intrepid2::CellTools::setJacobian` or `Intrepid2::CellTools::mapToPhysicalFrame` it will run a separate `Intrepid2::Basis::getValues` call per cell. For large cell counts this becomes very slow as millions of (GPU) kernel launches stack up one after the other.

To get around this we introduced a new path for when uniform points are an option. This is not available for CV and Surface integration schemes.

@rppawlo This is an alternative to the Intrepid2 changes I was making (see https://github.com/seanofthemillers/Trilinos/tree/intrepid2_parallel_getValues). I'm currently seeing a 200x speedup in workset generation in MiniEM with HIP for a 20x20x20 grid of tets. While these changes will speedup MiniEM and drekar, it will not speedup charon or empire-fluid/hybrid. The Intrepid2 changes would improve charon/empire performance, but are pretty invasive to the Intrepid2 interface and need to be reviewed.

## Related Issues

* Closes `put-issue-number-here`

### CODE REVIEW

**Comment by mperego** [comment]
@seanofthemillers Thanks! This is how you want to call setJacobian for uniform quad points.

Later in June I'll start working on parallelizing the Intrepid2 basis functions, and I'll have a look to your branch.

**Comment by rppawlo** [comment]
Charon tests passed. EMPIRE tests are running...

**Review by rppawlo — APPROVED** [review]
Thanks @seanofthemillers !

**Comment by rppawlo** [comment]
empire tests passed as well!

**Comment by seanofthemillers** [comment]
@rppawlo Are these random failures? Between the two runs I'm seeing a repeated failure with CUDA-UVM-off, but the other failures seem to happen only once. Is this a CI issue, or something I should look into?

**Pull request merged**
