### PR TITLE
Ifpack2: Move Trisolve symbolic to initialize phase

### PR DESCRIPTION
**Pull request by vqd8a**
@trilinos/ifpack2 

It makes more sense to move the trisolve compute to Initialize() because only nonzero patterns of L and U are involved in this phase.

### CODE REVIEW

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by jhux2** [comment]
@vqd8a It looks like there are a few real failures in the PR tests, e.g., https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=10628443.

**Comment by vqd8a** [comment]
> @vqd8a It looks like there are a few real failures in the PR tests, e.g., https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=10628443.

@jhux2 Thanks. I am looking into these.

**Comment by vqd8a** [comment]
@jhux2 I made some changes: only do trisolver's compute in iluk's compute if the pointer changed. Otherwise, do nothing. All tests passed. Could you please take a look again? Thanks.

**Pull request merged**
