### PR TITLE
Seacas script syntax fix

### PR DESCRIPTION
**Pull request by gsjaardema**
@trilinos/seacas 

## Motivation

Variable being used in the CMakeLists.txt file was not defined correctly if the install destination was not specified.  Some test-only builds do not install so didn't define this variable which resulted in syntax error.

### CODE REVIEW

**Comment by gsjaardema** [comment]
@alanw0 @tokusanya @prwolfe 
Could one of you take a quick look at this and see if it looks ok.  If it ever makes it through regression testing, it would be good do get it in quick.  Gary Hennigan's team is waiting for this to fix their testing... @glhenni

**Review by alanw0 — DISMISSED** [review]
This looks ok to me, but I'm not well qualified to spot issues here so my review is mostly just a rubber stamp. I'm assuming Greg knows what he's doing. :-)

**Comment by prwolfe** [comment]
> 

A solid assumption ;->

**Review by prwolfe — APPROVED** [review]

**Comment by gsjaardema** [comment]
I have no idea how to get this merged.  I have retested it at least 10 times.  I don't think my changes can cause the cuda timeout. Any help or ideas welcome.   

This was supposed to be a 5 mikk no tie change a couple weeks ago

**Comment by jwillenbring** [comment]
This failed at least in part to not having https://github.com/trilinos/Trilinos/pull/10429 merged yet. That PR has now been applied.

**Review by prwolfe — APPROVED** [review]

**Pull request merged**
