### PR TITLE
ROL: Remove calls to deprecated Tpetra code

### LINKED ISSUE #10242: ROL: error building tests with Tpetra deprecated code off
## Bug Report
@trilinos/rol 

### Description
There's an error building ROL tests with Tpetra deprecated code off.
```
Trilinos/packages/rol/adapters/tpetra/src/function/ROL_TpetraBoundConstraint.hpp:374:46: error: no matching function for call to ‘Tpetra::MultiVector<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >::getLocalViewDevice()’
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=29876

Also see https://github.com/sandialabs/Albany/issues/796

### PR DESCRIPTION
**Pull request by mperego**
@trilinos/rol

## Motivation
Removes Tpetra deprecated code.

Closes #10242

### CODE REVIEW

**Comment by dridzal** [comment]
@mperego : Thank you for the modifications!  Does this version compile with deprecated code off?

**Comment by mperego** [comment]
> @mperego : Thank you for the modifications! Does this version compile with deprecated code off?

Yes!

**Comment by mperego** [comment]
> > @mperego : Thank you for the modifications! Does this version compile with deprecated code off?
> 
> Yes!

If you are fine with the modifications please approve.

**Comment by dridzal** [comment]
@mperego : A quick question, as I'm still figuring out the changes in Tpetra.  I've reviewed the code, and it seems there are two major changes.  First, the template parameter `ConstViewType` has been added in several places, due to the use of Tpetra access patterns, specifically

`ConstViewType x_lcl = xp->getLocalViewDevice(Tpetra::Access::ReadOnly);`

as an example.  The `ReadWrite` access type is also specified explicitly now, but that one did not require changes in the dependent code (which defaulted to the previously used `ViewType`).

Second, calls like

`map->getNodeNumElements()` and `map->getNodeElementList()`

were replaced with

`map->getLocalNumElements()` and `map->getLocalElementList()`.

Is my understanding correct?

**Comment by mperego** [comment]
@dridzal Yes, that's correct. The second change is a mere name change to avoid confusion.

**Review by dridzal — APPROVED** [review]

**Pull request merged**
