### PR TITLE
ifpack2/kokkos-kernels: Early return in kokkos kernels sparse trsv in the event numRows == 0

### PR DESCRIPTION
**Pull request by MalachiTimothyPhillips**
@jhux2 @csiefer2 

This should fix the immediate issue with #12928. I think adding some additional unit test coverage for this corner case would also be beneficial.

### CODE REVIEW

**Review by jhux2 — CHANGES_REQUESTED** [review]
Woops, needs to be against `develop`.

**Comment by jhux2** [comment]
@MalachiTimothyPhillips What's the corresponding PR for Kokkos-Kernels?

**Comment by MalachiTimothyPhillips** [comment]
> Woops, needs to be against develop.

I apparently make that mistake quite often 😅 

> @MalachiTimothyPhillips What's the corresponding PR for Kokkos-Kernels?

https://github.com/kokkos/kokkos-kernels/pull/2180

**Comment by MalachiTimothyPhillips** [comment]
Changes pointed to `develop` now

**Review by jhux2 — APPROVED** [review]
lgtm

**Pull request merged**
