### PR TITLE
tacho: remove volatile qualifiers from join method

### PR DESCRIPTION
**Pull request by ndellingwood**
Compatibility update for disable of kokkos deprecated code

@trilinos/tacho @trilinos/shylu 

## Motivation
Successfully compile with Kokkos' deprecated code disable

## Stakeholder Feedback

NA

## Testing

Locally testing confirmed successful compilation with Kokkos' deprecated code disabled; AT for more testing

### CODE REVIEW

**Comment by ndellingwood** [comment]
Not sure who is maintaining tacho, @srajama1 can you give this a review on the shylu side? Minimal change, just dropping the `volatile` quantifier from a join method in order to conform with current versions of kokkos when deprecated code is disabled?

**Comment by ndellingwood** [comment]
@iyamazaki would you be able to give a review from the shylu side? This PR has a one line change to remove a volatile qualifier from a join method, a compatibility update needed to compile with kokkos' deprecated code disabled

**Comment by iyamazaki** [comment]
Hi, @ndellingwood. Thank you for the fix!! This looks good, but I was wondering if this `join` function is still used anywhere? If not, I am wondering if we should just remove it?

**Review by iyamazaki — APPROVED** [review]
Ah, I now see how it is used.

**Comment by ndellingwood** [comment]
@iyamazaki thanks! The join method is used with a functor in parallel_reduce calls. I had tried removing the overload with the `volatile` qualifier but that broke compilation (the overload was still needed for the `const` qualifier)

**Pull request merged**
