### PR TITLE
Trilinos:  Deprecate four packages (second attempt)

### LINKED ISSUE #4904: Piro compilation error due to missing Optipack_Config.h file
Trilinos failed to compile in the Albany nightlies due to the following error in Piro:

```
repos/Trilinos/packages/piro/src/Piro_PerformAnalysis.hpp:53:10: fatal error: OptiPack_Config.h: No such file or directory
```

Did OptiPack_Config.h get removed?  Is it still needed?  Here is the more detailed error message:
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=83699

@trilinos/piro

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/piro @trilinos/optipack @trilinos/claps @trilinos/globipack @trilinos/framework 

## Description
Second attempt at deprecating Trios, Claps, OptiPack, GlobiPack.
First attempt caused issues that were not caught in PR testing.
First attempt caused problems for Albany and ATDM.  #4904 
Added more guards in Piro for OptiPack content.
See #4864 for details

## Motivation and Context
See #4864 

## Related Issues

* Closes #4904
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to #4864 
* Part of 
* Composed of 

## How Has This Been Tested?

Used ATDM testing instructions in #4904 

On Linux workstation (three cases):

Standard ATDM configuration for Piro:
```
cmake \
  -GNinja \
  -DMPI_EXEC=${MPI_EXEC} \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Piro=ON \
.. |& tee OUTPUT.CMAKE
```
```
      Start  1: Piro_UnitTests_MPI_1
 1/12 Test  #1: Piro_UnitTests_MPI_1 .............................   Passed    0.34 sec
      Start  2: Piro_Epetra_MatrixFreeOperator_UnitTests_MPI_4
 2/12 Test  #2: Piro_Epetra_MatrixFreeOperator_UnitTests_MPI_4 ...   Passed    0.27 sec
      Start  3: Piro_MatrixFreeDecorator_UnitTests_MPI_4
 3/12 Test  #3: Piro_MatrixFreeDecorator_UnitTests_MPI_4 .........   Passed    0.32 sec
      Start  4: Piro_EvalModel_MPI_4
 4/12 Test  #4: Piro_EvalModel_MPI_4 .............................   Passed    0.27 sec
      Start  5: Piro_ThyraSolver_MPI_4
 5/12 Test  #5: Piro_ThyraSolver_MPI_4 ...........................   Passed    0.42 sec
      Start  6: Piro_AnalysisDriver_MPI_4
 6/12 Test  #6: Piro_AnalysisDriver_MPI_4 ........................   Passed    0.32 sec
      Start  7: Piro_SecondOrderIntegrator_MPI_1
 7/12 Test  #7: Piro_SecondOrderIntegrator_MPI_1 .................   Passed    0.27 sec
      Start  8: Piro_NOXSolver_UnitTests_MPI_4
 8/12 Test  #8: Piro_NOXSolver_UnitTests_MPI_4 ...................   Passed    0.37 sec
      Start  9: Piro_LOCASolver_UnitTests_MPI_4
 9/12 Test  #9: Piro_LOCASolver_UnitTests_MPI_4 ..................   Passed    0.60 sec
      Start 10: Piro_RythmosSolver_UnitTests_MPI_4
10/12 Test #10: Piro_RythmosSolver_UnitTests_MPI_4 ...............   Passed    0.38 sec
      Start 11: Piro_Epetra_RythmosSolver_UnitTests_MPI_4
11/12 Test #11: Piro_Epetra_RythmosSolver_UnitTests_MPI_4 ........   Passed    0.32 sec
      Start 12: Piro_TempusSolver_UnitTests_MPI_4
12/12 Test #12: Piro_TempusSolver_UnitTests_MPI_4 ................   Passed    0.33 sec

100% tests passed, 0 tests failed out of 12

Subproject Time Summary:
Piro    =  14.99 sec*proc (12 tests)
```

ATDM with Piro and OptiPack enabled (verified that deprecation warnings are produced):
```
cmake \
  -GNinja \
  -DMPI_EXEC=${MPI_EXEC} \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Piro=ON \
  -DTrilinos_ENABLE_OptiPack=ON -DTrilinos_ENABLE_GlobiPack=ON \
..
```
```
       Start  1: GlobiPack_VersionUnitTests_MPI_1
 1/23 Test  #1: GlobiPack_VersionUnitTests_MPI_1 .......................   Passed    0.23 sec
      Start  2: GlobiPack_ArmijoPolyInterpLineSearch_UnitTests_MPI_1
 2/23 Test  #2: GlobiPack_ArmijoPolyInterpLineSearch_UnitTests_MPI_1 ...   Passed    0.22 sec
      Start  3: GlobiPack_GoldenQuadInterpBracket_UnitTests_MPI_1
 3/23 Test  #3: GlobiPack_GoldenQuadInterpBracket_UnitTests_MPI_1 ......   Passed    0.22 sec
      Start  4: GlobiPack_Brents1DMinimization_UnitTests_MPI_1
 4/23 Test  #4: GlobiPack_Brents1DMinimization_UnitTests_MPI_1 .........   Passed    0.22 sec
      Start  5: GlobiPack_BrentsLineSearch_UnitTests_MPI_1
 5/23 Test  #5: GlobiPack_BrentsLineSearch_UnitTests_MPI_1 .............   Passed    0.22 sec
      Start  6: GlobiPack_TestLagrPolyMeritFunc1DUnitTests_MPI_1
6/23 Test  #6: GlobiPack_TestLagrPolyMeritFunc1DUnitTests_MPI_1 .......   Passed    0.22 sec
      Start  7: OptiPack_VersionUnitTests_MPI_1
 7/23 Test  #7: OptiPack_VersionUnitTests_MPI_1 ........................   Passed    0.22 sec
      Start  8: OptiPack_NonlinearCGUnitTests_0_MPI_4
 8/23 Test  #8: OptiPack_NonlinearCGUnitTests_0_MPI_4 ..................   Passed    0.28 sec
      Start  9: OptiPack_NonlinearCGUnitTests_1_MPI_4
 9/23 Test  #9: OptiPack_NonlinearCGUnitTests_1_MPI_4 ..................   Passed    0.28 sec
      Start 10: OptiPack_NonlinearCGUnitTests_2_MPI_4
10/23 Test #10: OptiPack_NonlinearCGUnitTests_2_MPI_4 ..................   Passed    0.28 sec
      Start 11: OptiPack_NonlinearCGUnitTests_3_MPI_4
11/23 Test #11: OptiPack_NonlinearCGUnitTests_3_MPI_4 ..................   Passed    0.29 sec
      Start 12: Piro_UnitTests_MPI_1
12/23 Test #12: Piro_UnitTests_MPI_1 ...................................   Passed    0.27 sec
      Start 13: Piro_Epetra_MatrixFreeOperator_UnitTests_MPI_4
13/23 Test #13: Piro_Epetra_MatrixFreeOperator_UnitTests_MPI_4 .........   Passed    0.26 sec
      Start 14: Piro_MatrixFreeDecorator_UnitTests_MPI_4
14/23 Test #14: Piro_MatrixFreeDecorator_UnitTests_MPI_4 ...............   Passed    0.31 sec
      Start 15: Piro_EvalModel_MPI_4
15/23 Test #15: Piro_EvalModel_MPI_4 ...................................   Passed    0.26 sec
      Start 16: Piro_ThyraSolver_MPI_4
16/23 Test #16: Piro_ThyraSolver_MPI_4 .................................   Passed    0.40 sec
      Start 17: Piro_AnalysisDriver_MPI_4
17/23 Test #17: Piro_AnalysisDriver_MPI_4 ..............................   Passed    0.38 sec
      Start 18: Piro_SecondOrderIntegrator_MPI_1
18/23 Test #18: Piro_SecondOrderIntegrator_MPI_1 .......................   Passed    0.25 sec
      Start 19: Piro_NOXSolver_UnitTests_MPI_4
19/23 Test #19: Piro_NOXSolver_UnitTests_MPI_4 .........................   Passed    0.37 sec
      Start 20: Piro_LOCASolver_UnitTests_MPI_4
20/23 Test #20: Piro_LOCASolver_UnitTests_MPI_4 ........................   Passed    0.57 sec
      Start 21: Piro_RythmosSolver_UnitTests_MPI_4
21/23 Test #21: Piro_RythmosSolver_UnitTests_MPI_4 .....................   Passed    0.34 sec
      Start 22: Piro_Epetra_RythmosSolver_UnitTests_MPI_4
22/23 Test #22: Piro_Epetra_RythmosSolver_UnitTests_MPI_4 ..............   Passed    0.27 sec
      Start 23: Piro_TempusSolver_UnitTests_MPI_4
23/23 Test #23: Piro_TempusSolver_UnitTests_MPI_4 ......................   Passed    0.28 sec

100% tests passed, 0 tests failed out of 23

Subproject Time Summary:
GlobiPack    =   1.33 sec*proc (6 tests)
OptiPack     =   4.75 sec*proc (5 tests)
Piro         =  14.26 sec*proc (12 tests)

Total Test time (real) =   6.70 sec
```
Claps test (verified that deprecation warnings are produced)
```
cmake \
  -GNinja \
  -DMPI_EXEC=${MPI_EXEC} \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Claps=ON \
  -DTPL_ENABLE_METIS=ON \
  -D METIS_LIBRARY_DIRS:FILEPATH=${SEMS_METIS_LIBRARY_PATH} \
  -D METIS_INCLUDE_DIRS:FILEPATH=${SEMS_METIS_INCLUDE_PATH} \
..
```
```
    Start 1: Claps_TrivialSerial_UnitTest_MPI_1
1/1 Test #1: Claps_TrivialSerial_UnitTest_MPI_1 ...   Passed    0.32 sec

100% tests passed, 0 tests failed out of 1

Subproject Time Summary:
Claps    =   0.32 sec*proc (1 test)
```
I could not get Trios to compile, and I can not find evidence that anyone else does, either.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@kddevin, if you don't mind, can i rebase this branch on top of 'develop' and run a local build?

**Comment by kddevin** [comment]
@bartlettroscoe 
Don't do anything yet.
Because of the previous revert, today's merge from develop to my branch trashed a bunch of stuff.  
I need to fix more things.  I'll let you know when this is ready.

**Comment by kddevin** [comment]
@bartlettroscoe 
I think this PR is ready to go.
See the test results above using your ATDM scripts.

**Comment by kddevin** [comment]
@ikalash  @jrobbin 
I am attempting the OptiPack deprecation again.  I think the ATDM tests above are representative of your builds.
Let me know right away if it causes any problems for you once the PR merges.

**Pull request merged**
