### PR TITLE
tpetra: update spadd_* api for KOKKOSKERNELS_VERSION >= 40299

### PR DESCRIPTION
**Pull request by ndellingwood**
PR kokkos/kokkos-kernels#1962 introduced API updates to the spadd_* routines This is allowed as spadd resides in the Experimental namespace, but requires propagating backward-compatibility breaking changes to Trilinos

Resolve kokkos/kokkos-kernels#2089

@trilinos/tpetra @brian-kelley @csiefer2

## Motivation

Fix compilation errors with kokkos-kernels@develop branch

## Testing

Locally tested Tpetra in a Cuda build on Weaver (rhel8 queue) with this configuration:
```bash
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/weaver
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh weaver-cuda-11.2-opt
export OMPI_CXX="$KOKKOS_PATH/bin/nvcc_wrapper"


cmake \
      -D CMAKE_CXX_FLAGS='-g' \
      -D CMAKE_CXX_STANDARD="17" \
      -D CMAKE_INSTALL_PREFIX=$PWD/install \
      -D Trilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
      -D Trilinos_ASSERT_DEFINED_DEPENDENCIES=IGNORE \
      -D TPL_ENABLE_CUSOLVER:BOOL=OFF \
      -D TPL_ENABLE_CUBLAS:BOOL=OFF \
      -DTrilinos_ENABLE_TESTS=ON \
      -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
      -DTrilinos_ENABLE_COMPLEX_DOUBLE=ON \
      \
      -D Trilinos_ENABLE_Kokkos=ON \
      -D Kokkos_ARCH_VOLTA70=ON \
      -D Kokkos_ARCH_POWER9=ON \
      -D Kokkos_ENABLE_CUDA=ON \
      -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
      -D Kokkos_ENABLE_CUDA_UVM=OFF \
      -D Kokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF \
      -D KokkosKernels_ENABLE_TPL_CUSOLVER=OFF \
      -DTrilinos_ENABLE_Tpetra=ON \
      -D Tpetra_ENABLE_TESTS=ON \
      \
      -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
      -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

### CODE REVIEW

**Comment by ndellingwood** [comment]
@csiefer2 @brian-kelley if you have a moment could you give these changes a review? I fixed a couple mistakes to make this work with the kokkos-kernels package in Trilinos (I tested initial changes with kokkos-kernels@develop).

I updated the function signature for the `addSorted` routine to accept an arg to the number of columns, which matches more closely to that of `addUnsorted`, and guarded the changes based on KOKKOSKERNELS_VERSION. Other changes are to guard and update the spadd_* function calls

**Review by brian-kelley — APPROVED** [review]
Thanks @ndellingwood

**Comment by ndellingwood** [comment]
CI failure related to https://github.com/trilinos/Trilinos/issues/12696

**Comment by achauphan** [comment]
Heads up, this next AT run is going to fail. One of the nodes that the following builds were running on went offline in middle of their AutoTester run.
`Trilinos_PR_clang-11.0.1`

**Pull request merged**
