### PR TITLE
Add developer friendly script for reproducing GenConfig builds (#10867)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @trilinos/framework, @e10harvey, @rppawlo, @jhux2, @csiefer2, @srbdev 

### Internal Issues

* [TRILINOSHD-180](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-180)

### Description

As per #10867, this provides as small wrapper script that I have developed to make it easier and more robust to reproduce Trilinos PR builds using the new GenConfig system.  Script is super easy to use (as documented at the top of the script):

```
$ cd <any-build-dir>/

$ source <trilinosDir>/packages/framework/load-gen-config-env.sh \
    <full-build-name> [--ci-mode]

$ rm -rf CMake*

$ cmake -C GenConfigSettings.cmake \
    -D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES=OFF \
    -D Trilinos_ENABLE_TESTS=ON \
    -D Trilinos_ENABLE_<pkg1>=ON \
    [other options] \
    $TRILINOS_DIR

$  make
```

where `--ci-mode` needs to be passed in if running this in a driver script.  Easy as pie.

This script solves a number of problems:

* Does not require you to have to pass in the Trilinos source dir again since the script knows it is in Trilinos.
* Sets the `TRILINOS_DIR` env var (which needs to be set on some platforms but is not documented that it is needed)
* Sets the `WORKSPACE` env var (which needs to be set at least for the cuda-11 builds but is not documented that it is needed).
* Add the `--force` option which seems to be needed when running on various machines.

Without these things, you can't reproduce PR builds on the various supported platforms (unless you are running in a Trilinos Framework Jenkins build).

### How was this tested?

I tested this through a throw-away-integration-test-branch [10807-kokkos-kernels-cublas-titb](https://github.com/bartlettroscoe/Trilinos/tree/10807-kokkos-kernels-cublas-titb) as part of trying to reproduce some build errors as documented in https://github.com/trilinos/Trilinos/issues/10836#issuecomment-1216017031.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@jhux2, @rppawlo, @csiefer2, can you look this over and try this out to see if it makes it easier for you to reproduce Trilinos PR builds?  It makes it a lot easier for me to work with GenConfig.

Thanks!

**Comment by bartlettroscoe** [comment]
@e10harvey and @srbdev, can you please review if you see any big problems with this?  This does not have to be the official documented way to reproduce Trilinos PR builds but it should be made available for people who want to use it.

**Comment by jhux2** [comment]
@bartlettroscoe I'm going to try this out on a failing PR, and will let you know how it goes.

**Comment by jhux2** [comment]
@bartlettroscoe Hmm, this isn't working for me:
```
(.../trilinos/build-test-gen-config) s ~/trilinos/Trilinos-bartlettroscoe/packages/framework/load-gen-config-env.sh PR-10833-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-801
-bash: /home/jhu/trilinos/Trilinos-bartlettroscoe/packages/framework/GenConfig/gen-config.sh: No such file or directory
```

```
(~/.../packages/framework) pwd
/ascldap/users/jhu/trilinos/Trilinos-bartlettroscoe/packages/framework
(~/.../packages/framework) ls
ini-files/  pr_tools/  get_dependencies.sh*  load-gen-config-env.sh

```

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Hmm, this isn't working for me:

@jhux2, did you first run:

```
$ cd Trilinos/

$ ./packages/framework/get_dependencies.sh --srn
```

?

**Comment by jhux2** [comment]
> did you first run:
> 
> ```
> $ cd Trilinos/
> 
> $ ./packages/framework/get_dependencies.sh --srn
> ```

No, I grabbed your branch and followed the directions in the PR description above.

**Comment by jhux2** [comment]
I copied your script over to Trilinos `develop` head, which has `packages/framework/GenConfig`.  Some progress, but still errors:
```
(.../trilinos/build-test-gen-config) s ~/trilinos/Trilinos-trilinos/packages/framework/load-gen-config-env.sh PR-10833-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-801
Using system 'rhel7' based on matching hostname 'cee-build030'.
Matched environment name 'sems-gnu-7.2.0-openmpi-1.10.1-serial' in build name 'PR-10833-test-rhel7_sems-gnu-7.2.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-801'.
Traceback (most recent call last):
  File "/home/jhu/trilinos/Trilinos-trilinos/packages/framework/GenConfig/gen_config.py", line 834, in <module>
    main(sys.argv[1:])      # pragma: no cover
  File "/home/jhu/trilinos/Trilinos-trilinos/packages/framework/GenConfig/gen_config.py", line 810, in main
    gc.write_cmake_fragment()
  File "/home/jhu/trilinos/Trilinos-trilinos/packages/framework/GenConfig/gen_config.py", line 186, in write_cmake_fragment
    self.complete_config, "cmake_fragment"
  File "/home/jhu/trilinos/Trilinos-trilinos/packages/framework/GenConfig/gen_config.py", line 334, in complete_config
    f"{self.load_env.parsed_env_name}"
  File "/home/jhu/trilinos/Trilinos-trilinos/packages/framework/GenConfig/src/config_keyword_parser.py", line 78, in selected_options_str
    for flag in self.selected_options.keys():
  File "/home/jhu/trilinos/Trilinos-trilinos/packages/framework/GenConfig/src/config_keyword_parser.py", line 96, in selected_options
    self.__parse_selected_options()
  File "/home/jhu/trilinos/Trilinos-trilinos/packages/framework/GenConfig/src/config_keyword_parser.py", line 126, in __parse_selected_options
    self.__assert_all_build_name_options_are_valid()
  File "/home/jhu/trilinos/Trilinos-trilinos/packages/framework/GenConfig/src/config_keyword_parser.py", line 175, in __assert_all_build_name_options_are_valid
    raise ValueError(err_msg)
ValueError:

The build name contains the following invalid options:

  - PR-10833-test-rhel7
  - no-package-enables-801

Valid options can be found in '/home/jhu/trilinos/Trilinos-trilinos/packages/framework/ini-files/supported-config-flags.ini'.
```

**Comment by bartlettroscoe** [comment]
> No, I grabbed your branch and followed the directions in the PR description above.

@jhux2, okay, we could make the script do that step too automatically if the `<trilinosDir>/packages/framework/GenConfig/` directory does not exist.  But the question is, what should be the default argument for `get_dependencies.sh`?  I would guess it should be `--srn` if you want to reproduce PR builds.

**Comment by bartlettroscoe** [comment]
> I copied your script over to Trilinos `develop` head, which has `packages/framework/GenConfig`

@jhux2, what do you mean by "has" in "has `packages/framework/GenConfig`"?  The repo GenConfig is not stored in the Trilinos repo.  It is cloned using the command `./packages/framework/get_dependencies.sh --srn`.

**Comment by jhux2** [comment]
> > I copied your script over to Trilinos `develop` head, which has `packages/framework/GenConfig`
> 
> @jhux2, what do you mean by "has" in "has `packages/framework/GenConfig`"? The repo GenConfig is not stored in the Trilinos repo. It is cloned using the command `./packages/framework/get_dependencies.sh --srn`.

Ah, I think that I must have cloned `GenConfig` previously into `Trilinos/packages/framework`.

The instructions in the script don't say anything about running `get_dependencies.sh`.  I'll try that now.

**Comment by jhux2** [comment]
Running `get_dependencies.sh` cloned the GenConfig repo successfully.

I still see the error in https://github.com/trilinos/Trilinos/pull/10886#issuecomment-1224814625.  I've tried double quoting and back-slashes before the single dashes.  Neither has any effect.

**Comment by bartlettroscoe** [comment]
@jhux2, are you (and do yo think other Trilinos developers would be) interested in further developing this script to call get_dependencies.sh automatically and make this more turn-key and less error prone?  (Updating the GenConfig implementation is needed anyway in order to use the most up-to-date implementation in case there is a stale version.)

If so, I will add that and try to reproduce and address the error you are reporting [above](https://github.com/trilinos/Trilinos/pull/10886#issuecomment-1224814625).

**Comment by jhux2** [comment]
@bartlettroscoe I got the script working by chopping off the front and back parts of the build name.   Once I'm done, I'll massage the instructions a bit.  No need for you to work on this at the moment, thanks.

**Comment by jhux2** [comment]
@bartlettroscoe While testing your script, I found myself needing to refer to https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors.  I spent some time editing that wiki to fix some errors and make it easier (at least for me) to read.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe While testing your script, I found myself needing to refer to https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors. I spent some time editing that wiki to fix some errors and make it easier (at least for me) to read.

@jhux2, yea, the script in this PR did not mention get_dependencies.sh and did not have any hook to call it.  I am torn whether to add that or not (since if you don't update the GenConfig files, you could be using an old version of GenConfig).

Even with the fixes to the GenConfig files to not require to manually set the env vars TRILINOS_DIR and WORKSPACE, a script like this has the advantage that you don't need to specify the Trilinos source dir more than once.

**Comment by bartlettroscoe** [comment]
> The internal issue, TRILINOSHD-180 was resolved by modifying environment-specs.ini. Please consider closing this PR in favor of fewer scripts under framework maintenance.

@e10harvey, there some place in the Trilinos repo where I can put this script for my own usage?  This avoids having to duplicate the Trilinos source dir and makes it easier to list the commands needed to reproduce a Trilinos PR build.

**Comment by e10harvey** [comment]
> > The internal issue, TRILINOSHD-180 was resolved by modifying environment-specs.ini. Please consider closing this PR in favor of fewer scripts under framework maintenance.
> 
> @e10harvey, there some place in the Trilinos repo where I can put this script for my own usage? This avoids having to duplicate the Trilinos source dir and makes it easier to list the commands needed to reproduce a Trilinos PR build.

@bartlettroscoe: Sorry for the lengthy delay here. Maybe in `packages/framework/contrib`?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe: Sorry for the lengthy delay here. Maybe in `packages/framework/contrib`?

@e10harvey, any chance that `Trilinos/packages/framework/` can't be moved to `Trilinos/framework/` or some other place outside of `Trilinos/packages/`?  The subdirs under `Trilinos/packages/` should be reserved for Trilinos packages (i.e. TriBITS packages).  Otherwise, that is just confusing (at least it was for me).

CC: @sebrowne, @ccober6

**Comment by sebrowne** [comment]
@bartlettroscoe I'm fine with them living outside of packages/ .  I can create a story for that, but we likely won't schedule it for several sprints.  Does that work?

I do agree with @e10harvey about not wanting to add this to Framework's support load for the moment, but I'm also fine putting it into the repository as long as its not under a "framework" area.  Feel free to call me to discuss it more.

**Comment by bartlettroscoe** [comment]
I have replaced this with:

* https://gitlab-ex.sandia.gov/rabartl/run_trilinos_pr_builds

That makes it easy for me to reproduce PR builds and set up local build configurations based on GenConfig.  (It takes all of the boiler-plate out of it.)

**Pull request closed without merging**
