### PR TITLE
Belos: Add Tpetra-only pipelined CG & single all-reduce {CG,GMRES}

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/belos 

This closes https://github.com/trilinos/Trilinos/issues/748.

## Description

Add Tpetra-specific Belos solvers contributed by Ichitaro Yamazaki (UTK) and edited by Mark Hoemmen (SNL), and make the solvers available through the Tpetra specializations of Belos::SolverFactory.  The new solvers include:

  - Pipelined CG
  - Single all-reduce CG
  - Single all-reduce GMRES

The solvers are only available for Tpetra linear algebra.  This is because they depend on Tpetra-specific linear algebra operations.

## Motivation and Context

The new solvers perform less MPI communication than the corresponding standard CG and GMRES algorithms.  The pipelined solvers also have potential to overlap communication and computation.  Actual overlap achieved depends on the MPI implementation and the hardware.  Right now, the implementations just use `MPI_Iallreduce` for communication-computation overlap, and make no special effort to drive MPI progress.  We may optimize this in the future.

## How Has This Been Tested?

Mac, Clang, OpenMPI.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

**Comment by egboman** [comment]
Thanks, Mark. This is nice work but it would be good for Heidi to look it over before merging, so I removed the auto-merge label - hope that's OK.

**Comment by aprokop** [comment]
Is there documentation to point people to run the new solvers?

**Comment by rppawlo** [comment]
Are these available through stratimikos?

**Comment by mhoemmen** [comment]
@csiefer2 wrote:
> @mhoemmen What's up with the idot immediately followed by a wait pattern?

Ichi wrote that; bear with him :-)  (He wanted a consistent look between pipelined vs. single-reduce solvers.)  From what I've seen, there should be no significant ioverhead for doing that vs. just issuing an `MPI_Allreduce`.

**Comment by mhoemmen** [comment]
@rppawlo wrote:
> Are these available through stratimikos?

They will be available through Belos::SolverFactory.  If we want Stratimikos support, we need to go in and fix Stratimikos so it uses Belos::SolverFactory.  That should give build time improvements, since currently Stratimikos just includes all of the solvers individually.  We spent some effort with Tech-X earlier this summer to change Belos::SolverFactory so it hides solvers from users' compilation units.

**Comment by mhoemmen** [comment]
@aprokop wrote:
> Is there documentation to point people to run the new solvers?

Not yet.  Belos as a whole lacks a single source of documentation.  I'll welcome early adopters.

**Comment by csiefer2** [comment]
@mhoemmen That's all I wanted to know, thanks!

**Comment by srajama1** [comment]
Are there performance comparisons of the new solver w/ existing ones ?

**Comment by mhoemmen** [comment]
Ichi has performance comparisons.  If I remember right, pipelined CG goes about 20% faster.  Doing much better than that may take enabling MPI's progress thread, or managing progress manually, as in Paul Eller's dissertation work.

**Comment by hkthorn** [comment]
Also, just a comment, but the "single reduction" routine for orthogonalization in GMRES, projectAndNormalizeSingleReduce, can be implemented using the current MultiVector primitives.  It would be interesting to get that into Belos' templated code and see what the comparison is in the performance between the single-reduction CG, that is already in Belos, and the single-reduction GMRES with the native versions in Tpetra.  Pipelining is more challenging, but I like seeing the code!

**Comment by egboman** [comment]
> _Ichi has performance comparisons. If I remember right, pipelined CG goes about 20% faster. Doing much better than that may take enabling MPI's progress thread, or managing progress manually, as in Paul Eller's dissertation work._

Performance will obviously vary depending on the matrix, number of processors, network, etc. 
We are collecting some preliminary results for ECP but once the new solvers are in Trilinos, it would be nice to have applications try them out.

**Comment by mhoemmen** [comment]
@hkthorn I pushed a commit that addresses the header file include guard issue you observed.  It did not actually cause problems in the build or tests, because user code should never include a specific solver's header file.  It should always just access the solver through Belos::SolverFactory.  Each specific solver is actually a "factory for itself" and registers itself with the Tpetra specialization of Belos::SolverFactory.

**Comment by aprokop** [comment]
@egboman 
>  We are collecting some preliminary results for ECP but once the new solvers are in Trilinos, it would be nice to have applications try them out.

Once this is merged, and can be run (semi-)easily from an input deck, Exawind project would be glad to test it out.

**Comment by mhoemmen** [comment]
Those are legit build errors Clang didn't pick up.  I'll fix them.

**Comment by mhoemmen** [comment]
@hkthorn @egboman Please rereview; thanks!

**Comment by egboman** [comment]
@mhoemmen What does "Tpetra-only" mean? I understand Tpetra is required to compile/build, but what if the user has Epetra operator and multivectors - could he/she still use the new pipelined solvers?

**Comment by mhoemmen** [comment]
Thanks @hkthorn ! :D

**Comment by mhoemmen** [comment]
@egboman To clarify what I wrote above:

> The pipelined solvers use Tpetra interfaces and only work with Tpetra.

These solvers are different than Belos' "generic" solvers.  For an example of a "generic" Belos solver, see PseudoBlockGmresSolMgr.  "Generic" Belos solvers are templated on (SC, MV, OP), and they really do work for _any_ (SC, MV, OP), because they rely on the linear algebra interface defined by `Belos::MultiVecTraits` and `Belos::OperatorTraits`.

The pipelined solvers depend on a linear algebra operation (a nonblocking inner product) that does not exist in `Belos::MultiVecTraits`.  Adding that operation to `Belos::MultiVecTraits` would break builds for users who have their own specializations of `Belos::MultiVecTraits`.

**Comment by mhoemmen** [comment]
Not quite sure what's up with those tests.  I'll try a build with a different compiler to see if I can replicate.

**Comment by mhoemmen** [comment]
Closing in favor of #3467.

**Pull request closed without merging**
