### PR TITLE
Tpetra: replace deprecated View::dimension_0

### LINKED ISSUE #3293: Tpetra: Triple product calls deprecated Kokkos methods
@trilinos/tpetra @brian-kelley 

Tpetra's sparse triple product calls deprecated Kokkos methods.  Those methods are going away soon.  If you call them, that will break Sierra's build of Trilinos.

Here is an example of code that calls these methods: https://github.com/trilinos/Trilinos/blob/b783a65a6faed6a40372d404080ba2834f6af155/packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp#L966

## Possible Solution

`dimension_N` -> `extent(N)`

### PR DESCRIPTION
**Pull request by brian-kelley**
@trilinos/tpetra 

## Description

Replace deprecated Kokkos::View::dimension_0() with View::extent_0().
## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@trilinos/framework The build errors suggest that the PR tests did not get the new commit.

**Comment by cgcgcg** [comment]
@brian-kelley Thanks for taking care of this!

**Comment by mhoemmen** [comment]
Thanks y'all! :D

**Comment by mhoemmen** [comment]
@micahahoward @tcfisher @rrdrake @prwolfe FYI this helps fix Trilinos:develop (not master yet) for disabling deprecated Kokkos code.

**Pull request merged**
