### PR TITLE
Correct warnings in the test code

### PR DESCRIPTION
**Pull request by prwolfe**
These were causing failures in the warning-as-errors
builds.  Basically this moves one function that is
only in a single test into that source file and
splits another into a second header. This allows us
to share the test fixture where needed witout having
unused functions for the compiler to complain about.

closes issue #2286

@trilinos/<teamName>

## Related Issues

* Closes 2286

## Checklist

- [ x ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by prwolfe** [comment]
Basically I was just spitting the test fixtures so only the tests that need them were getting the function definitions.  I could have done this with CPP macros instead.  I did take a shot at the name and can change that as you like.  The tests in question don't have There in the name, so I picked the common name there.

**Comment by mhoemmen** [comment]
@prwolfe I wouldn't worry about it.  Thanks for working on this!  btw did you get a chance to test in your local build?  The PR autotester has been ... funky lately.

**Comment by prwolfe** [comment]
Yes - I did test it before I issued this PR.  But only on gcc 4.9.3. Thanks!

**Comment by mhoemmen** [comment]
@prwolfe Fun fact: the PR autotester had entire packages disabled like Ifpack2, Anasazi, and MueLu: 

https://github.com/trilinos/Trilinos/issues/2317#issuecomment-370935137

No wonder it was so fast ;-)

**Comment by mhoemmen** [comment]
Hopefully they are fixing that now.

**Comment by mhoemmen** [comment]
Thanks @prwolfe ! :D

**Pull request merged**
