### PR TITLE
MueLu_structured_aggregation

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/muelu 

## Description
These commit add a new aggregation factory to MueLu, the goal is to provide structured aggregation which is useful if line or plane smoothing is desired. It also provides good control over the coarsening rate. Finally provides a new option for coupled aggregation. This pull request is related to issue #2230 .

## Motivation and Context
This change is an enhancement and in the long run it will be part of a global coarsening strategy that allows for faster setup time on problems where the mesh is locally structured.

## How Has This Been Tested?
The aggregates produced by the StructuredAggregationFactory are tested in the Aggregates.cpp unit test and the aggregates are used to construct a prolongation operator with TentativePFactory in the StructuredAggregationFactory.cpp unit test.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by lucbv** [comment]
At the moment these changes allow only for a global lexicographic layout but I am currently working on the local lexicographic layout. Once these two are finished I would like to modify the algorithm to allow for an equivalent uncoupled approach while still preserving conforming aggregates on the processor boundary.
Finally more modifications will need to be made to the aggregate class to allow for linear or higher order interpolation.

**Comment by jmgate** [comment]
@lucbv, it looks like something might've gone wrong with your branch.  Dozens of commits were added to this PR today, but I'm guessing the last one "MueLu: adding structured aggregation algorithm" is the only one that should've been added.  Do you need help getting this branch back into a good state?

**Comment by lucbv** [comment]
@jmgate you're right, I wanted to push before a meeting but I did a mess so I'll revert and fix things...

**Comment by lucbv** [comment]
@jmgate , I think that I fixed everything and pushed again the one commit that needs to be added to this branch. Although I am not sure how to remove the panzer from my list of reviewers?

**Comment by lucbv** [comment]
@jmgate never mind, I just needed to check it out from the list of reviewers, that was easy!

**Comment by jmgate** [comment]
Excellent&mdash;thanks @lucbv.

**Comment by lucbv** [comment]
This last commit added three new classes: IndexManager, LocalLexicographicIndexManager and GlobalLexicographicIndexManager. The idea is to encapsulate all the arithmetic details related to the mesh layout and to provide an inheritance model to have specialized implementations for different mesh orderings.

Next up, I will actually remove from structured aggregation all the code that now resides in the IndexManager and refine the interaction between the two.

**Comment by lucbv** [comment]
Now the code is properly tested in my opinion so it is time for the review, removing the [WIP] tag.
@jhux2 @csiefer2 @aprokop

**Comment by allevin** [comment]
@lucbv The failures look like linking issues this is from build 379...

[ 84%] Linking CXX executable Stokhos_SacadoPCECommTests.exe
[ 84%] Linking CXX executable Stokhos_MatrixFreeOperatorUnitTest.exe
../../src/libstokhos_muelu.so.12.13: undefined reference to `MueLu::StructuredAggregationFactory<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::StructuredAggregationFactory()'
../../src/libstokhos_muelu.so.12.13: undefined reference to `MueLu::StructuredAggregationFactory<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 8, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::StructuredAggregationFactory()'
../../src/libstokhos_muelu.so.12.13: undefined reference to `MueLu::StructuredAggregationFactory<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 4, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::StructuredAggregationFactory()'
../../src/libstokhos_muelu.so.12.13: undefined reference to `MueLu::StructuredAggregationFactory<Sacado::UQ::PCE<Stokhos::DynamicStorage<int, double, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::StructuredAggregationFactory()'
../../src/libstokhos_muelu.so.12.13: undefined reference to `MueLu::StructuredAggregationFactory<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 32, Kokkos::Serial> >, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::StructuredAggregationFactory()'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_TensorProductBasisUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TensorProductBasisUnitTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by lucbv** [comment]
@allevin yes I forgot to generate cpp files for stokhos, I will do that now and check locally that the checkin script runs properly before pushing again.
By the way I have no idea of where I can look at the results of the auto-tester?

**Comment by allevin** [comment]
@lucbv The results are on the Jenkins log file and not everyone has visibility.  The Frameworks team is working to resolve this.  Hopefully soon you will be able to see the configure/build/test results of PR autotesting on CDash.  In the meantime, I try to keep an eye on failing runs and give people the results.

**Comment by lucbv** [comment]
@allevin thanks for the info, I was able to get the checkin test to run and pass with stokhos on so hopefully this should resolve the issues the autotester found.

**Comment by bartlettroscoe** [comment]
This merged branch just failed the standard CI build (see #2264).   But above, the PR testing as of yesterday says that it passesd.  How is that possible?  We will see how the "Clean" builds to tomorrow morning.

**Comment by bartlettroscoe** [comment]
Also, this branch testing should have failed due to the broken Stokhos test since 2/15/2018 as described in #2254.  Therefore, how is it possible that a automated build of this branch merged with `develop` would pass yesterday?

**Comment by jwillenbring** [comment]
@bartlettroscoe 

> This merged branch just failed the standard CI build (see #2264). But above, the PR testing as of yesterday says that it passesd. How is that possible? We will see how the "Clean" builds to tomorrow morning.

The testing of this pull request was actually done on February 9th. The autotester puts in a comment  once per day reminding of the status of the pull request - in this case it was that the tests had passed, but the pull request had not been inspected - until the PR is merged. If you look up to the comments from February 9th, those talk about the tests starting and passing, and provide additional detail in the fold-out.

The commit that caused issues with this one was applied on Feb 15, nearly a week after this test was done. The @trilinos/framework team has discussed the possibility of declaring the tests "stale" at some point and retesting, but it isn't clear if that is necessary in the general case. Ideally we would like to see PR's that have been tested be inspected and merged fairly quickly.

**Comment by bartlettroscoe** [comment]
> The commit that caused issues with this one was applied on Feb 15, nearly a week after this test was done. 

@jwillenbring,

This is what I suspected happened.  Thanks for looking into this.

So what this means is that the problem is that the current system makes the "additive test assumption of branches" described at:

   * https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#bookmark=id.d1jneh8ubsyn 

and the current PR testing system allows for many days (or even weeks) to go by between when a branch is tested and when it is merged.  Situations like that (like in this PR) are begging for a violation of the "additive test assumption of branches" given the current implementation and basic GitHub workflow (where it is not expected to merge a branch immediately after the final commit is pushed as that would leave no time for a code review and final sign off which can take days and even weeks in some cases).

Given the current implementation of the PR testing system, all developers should be instructed to follow the following workflow:

1. Create topic branch and push to their Trilinos fork
2. Create PR which will trigger the first set of automated PR tests
3. Have the reviews and push any commits to resolve issues found in the reviews
4. After the final auto PR testing for the last commit is pushed and the reviews are all complete and one is ready to click "merge", don't.  Instead ..
5. Rebase their topic branch on top of current 'develop'
6. Force push their rebased topic branch to their Trilinos fork
7. Let the auto PR testing system test their updated rebased branch again
8. As soon as that final round of testing is complete (which sends an email), watch their email carefully and when they see the email then immediately click the "merge" button. 

That should do the merge, test and final merge and test almost as fast as using the checkin-test-sems.sh script as described at:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing#other-workflows

Because of the immediate push after a successful merge, and test when using the checkin-test.py script, the CASL project might have seen a violation of the "additive test assumption of branches" perhaps twice in 7+ years.  It is that quick turn-round is the key to avoiding violations of that assumption.

But the above workflow with rebasing branches, forced pushes, etc. is more complex than most Trilinos developers will not be comfortable with doing.   And not everyone is set up to use the checkin-test-sems.sh script and using it for topic branches means manually merging the topic branch and not everyone would be able to that either.

Therefore, the best solution would be to have the “merge” button on GitHub not actually merge but to have the auto PR testing system stage this merge in a queue and then perform the a final merge with the updated ‘develop’ (when it ran), run the builds again, and then merge automatically once that last round of builds passes (or error out).  Can the @trilinos/framework team implement that?.

But until that feature (or some other auto merging feature) is complete, then given the current auto PR testing implementation, I personally will use the workflow:

1. Create a topic branch and post a PR and let the auto PR testing test the branch.
2. Once all of the reviews are complete and the final PR testing is complete, I will manually merge and push the branch locally with the checkin-test-sems.sh script.

In fact, that is exactly the workflow that I did with the PR #2246 (and I had to also rebase and force push the topic branch first to trick the automated PR system to test it again now that Trilinos was not broken anymore).

But I don't want to recommend this workflow to other people to use who are not already set up to use the checkin-test-sems.sh script and are comfortable using it.  I would not recommend this to any one new.  I would recommend they learn how to rebase their topic branches and force push as described above.

Can the @trilinos/framework team set up a wiki page to describe the workflow outlined above with the final rebase, force push, then merge (not involving the checkin-test-sems.sh script)?  I can help write up that wiki page (without any mention of the checkin-test-sems.sh script) if it would help.

**Comment by bartlettroscoe** [comment]
Could the auto PR system be updated to look for "[AUTOMERGE]" and when it sees it to do the local merge, testing, and then push all in the same Jenkins process?  If you stage these in a queue, you can avoid the "additive test assumption of branches" altogether (like the SST system does).

**Pull request merged**
