### PR TITLE
Introducing Teuchos Parser

### PR DESCRIPTION
**Pull request by ibaned**
This PR introduces the Teuchos Parser subpackage as proposed by #1371.
The subpackage includes the following:

 - table generators for regular expressions and LALR(1) parsers
 - a Language class to define a language format
 - a Reader base class that users subclass to build their parsers
 - Languages for subsets of regular expressions, XML, and YAML
 - Documentation for Language, Reader, and other important user-level classes
 - Unit tests, including for the built-in Languages
 - An example "Calc" program that evaluates scalar math expressions
 - Compiles under C++98

A few additions were made to `Teuchos::any` and `Teuchos_Assert.hpp` to support Teuchos Parser. No existing behavior was altered.

As of this PR, Teuchos Parser is not yet required by anything else in Trilinos (or Teuchos). I believe it makes sense to first introduce the code and let it go through a few cycles of CI testing before starting to use it in other parts of Trilinos.

@trilinos/teuchos @bartlettroscoe

### CODE REVIEW

**Comment by ibaned** [comment]
I know this is a lot of code, but can someone point out next steps?
I think it makes sense to have another developer at least skim over the changes before doing checkin testing and merging.

**Comment by bartlettroscoe** [comment]
I can help review this but it will be some time before I can get to this.  Also, what project needs this and how urgent is this?

Otherwise, since nothing is using this in Trilinos yet, it seems pretty low risk to push it and see how it goes.  But if we see any build or test failures on important builds, we can just change this from a "PT" (currently called "PS") subpackage to an "EX" subpackage (which will remove it from all of the automated testing).

If Trilinos had adopted the [TriBITS lifecycle]() like was planned many years ago, we would declare this to be early stage "Research Stable" (RS) or even "Exploratory" (EP) and therefore this would not impact any Trilinos customer already using Teuchos code.

**Comment by ibaned** [comment]
We have an internal application that will start using this to move away from STKExprEval as mentioned in  #1371. I like the idea of pushing this without too much delay so that said application can start using it out of the Trilinos develop branch. If we see a build failure, either I fix it quickly or we downgrade the subpackage as you mentioned until its fixed.

Although your link to the TriBITS lifecycle doesn't work for me, from what I recall this is probably closer to Research Stable, or at least it will be once downstream code depends on its API. Luckily its based on some fairly established literature and theory, so I don't expect radical design changes.

Having this in Trilinos develop within a week or two would be good. Until then I can keep working on it in branches, maybe start integrations with Teuchos ParameterList.

**Comment by bartlettroscoe** [comment]
@ibaned, if you want to avoid the problem with branches, you might just change this to an "EX" package for now and push.  That will not impact any automated Trilinos build but would avoid needing to deal with branches.  This is a good approach for doing software development called "Feature Toggle":

* https://martinfowler.com/articles/feature-toggles.html

In many ways, it is superior to using branches.

I think we would need to do some more extensive testing on different compilers before we make this "ST" or "PS".  Otherwise, so much of Trilinos depends on Teuchos that if the Teuchos build breaks, we have a huge ripple effect so more caution may be warranted.

I forgot the link to the TriBITS Lifecycle model:

* http://trac.trilinos.org/wiki/TribitsDevelopmentPractices

Based on what you said above, it would likely begin life as early-stage "Production Growth" and if it gets used in the Teuchos PL, it will need a higher maturity much faster.  Hence, before it gets used in the Teuchos PL, we would need a more detailed review.

**Comment by ibaned** [comment]
I'm fine with the "EX" designation pending review and testing. I'll make that change and run the checkin script tomorrow.

If there is an explicit list of compilers to test, I could work on that as well. I had a really tough time installing GCC 4.4.7 from source, so I used GCC 6.3.0 with `-std=c++98 -pedantic-errors`. If there are usable machines that have the relevant compilers installed, that would help.

**Comment by ibaned** [comment]
I've squashed these 90 commits into just 3, changed the type to "EX", and the checkin script has been running for a while. It is building and running tests because I added helpers in `Teuchos_any.hpp` and `Teuchos_Assert.hpp`. The compile is a 93%, if it and the tests pass we should see TeuchosParser as an EX subpackage in develop later today.

**Comment by ibaned** [comment]
Checkin test just passed, Teuchos Parser is in develop as these three commits:
5078b1f
63fd67d
315dff7
Closing this PR because it has effectively been (rebase-)merged

**Comment by ibaned** [comment]
Somehow it didn't originally get in as EX... I just fixed this, hopefully before it hit any CI systems...

**Pull request closed without merging**
