### PR TITLE
Fix change logic in get-changed-trilinos-packages.sh and PullRequestLinuxDriver.sh (#3133)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
@trilinos/framework 

## Description

This PR contains two sets of commits.

The first set of commits fixes the behavior of the `get-changed-trilinos-packages.sh` script to apply the correct global change logic for Trilinos.  This updates TriBITS snapshot and adds unit test to ensure that the logic in the file `Trilinos/cmake/ProjectCiFileChangeLogic.py` is getting correctly applied in the script `get-changed-trilinos-packages.sh` used by the Trilinos PR tester.  The unit testing of `get-changed-trilinos-packages.sh` was not strong enough.

The second set of changes in the commit b2cccbf5f5b2f56d31ce7fa2ae6c4957c938427c which passes in the correct SHA1 for selecting the set of changed files in the script `PullRequestLinuxDriver.sh`.  See #3265.

## Motivation and Context

The TriBITS scripts called by `get-changed-trilinos-packages.sh` were not pickup up the logic in `Trilinos/cmake/ProjectCiFileChangeLogic.py` and was instead likely using the logic in `TribitsExampleProject/cmake/ProjectCiFileChangeLogic.py` (see TriBITSPub/TriBITS@9b9822f5f2ab7183bdc47eec2193a5fbf6ab83d1).  As a result, PRs like #3251 were incorrectly triggering the enable of all Trilinos packages.

Also the modification to `PullRequestLinuxDriver.sh` in PR #3218 was using the wrong base SHA1 and was resulting in testing more packages than needed for the PR in many cases (see #3265).

The merge of this PR should complete #3133.

## How Has This Been Tested?

I expanded the unit tests for `get-changed-trilinos-packages.sh` to ensure it ignores a change to a `*.cmake` file under the `cmake/std/adm/` directory.  I also ran the script manually for a few PRs, including #3251, and saw that it is selecting the right packages to test (and no package in the case of PR #3251).

To test this updated script `PullRequestLinuxDriver.sh`, I did the following.

First, I created the separate dummy PR testing repo where the PR branch merges are done:

```
$ cd ~/junk/DummyTrilinosPRDriver
$ ls
Trilinos
$ cd Trilinos/
$ git remote -v
origin  git@github.com:trilinos/Trilinos.git (fetch)
origin  git@github.com:trilinos/Trilinos.git (push)
```

The I just ran the script `PullRequestLinuxDriver.sh` on this for a few real PRs.

First, I tested this for the PR #3260:

```
$ env \
  TRILINOS_SOURCE_BRANCH=tril-215-white-ride-cuda-9.2 \
  TRILINOS_SOURCE_REPO=https://github.com/bartlettroscoe/Trilinos \
  TRILINOS_SOURCE_SHA=c96c475fbbc3162e4618050c3e893dcb107a73e1 \
  TRILINOS_TARGET_BRANCH=develop \
  TRILINOS_TARGET_REPO=https://github.com/trilinos/Trilinos \
  TRILINOS_TARGET_SHA=45adc9002091ba1fc6ae296c72696f8717b8b885 \
  PULLREQUESTNUM=111 \
  JOB_BASE_NAME=Trilinos_pullrequest_gcc_4.8.4 \
  BUILD_NUMBER=222 \
  WORKSPACE=$PWD \
 ~/Trilinos.base/Trilinos/cmake/std/PullRequestLinuxDriver.sh \
 &> console.out

$ cmake -P packageEnables.cmake 
-- NOTE: No packages are being enabled!
 ```

That is the correct set of enables (i.e. no enables).  That will save me huge amounts of time (and would have allowed PR #3260 to be merged immediately).

Then I tested this for a few other PRs ...

**Testing for PR #3275:**

```
$ env \
  TRILINOS_SOURCE_BRANCH=sacado_cppunit_fix \
  TRILINOS_SOURCE_REPO=https://github.com/etphipp/Trilinos \
  TRILINOS_SOURCE_SHA=3fce9c6d41039f78d6f8def4d404e234ea06449a \
  TRILINOS_TARGET_BRANCH=develop \
  TRILINOS_TARGET_REPO=https://github.com/trilinos/Trilinos \
  TRILINOS_TARGET_SHA=4956217a66dba575a6c422dd43b6b2586fe85476 \
  PULLREQUESTNUM=111 \
  JOB_BASE_NAME=Trilinos_pullrequest_gcc_4.8.4 \
  BUILD_NUMBER=222 \
  WORKSPACE=$PWD \
 ~/Trilinos.base/Trilinos/cmake/std/PullRequestLinuxDriver.sh \
 &> console.out

$ cmake -P packageEnables.cmake 
-- Setting Trilinos_ENABLE_Sacado = ON
```

That looks correct.

**Testing for PR #2930:**

```
$ env \
  TRILINOS_SOURCE_BRANCH=import_stk \
  TRILINOS_SOURCE_REPO=https://github.com/prwolfe/Trilinos \
  TRILINOS_SOURCE_SHA=b2674b6c78f0ca1b0f6c3b79be1e7f5a18d9a34a \
  TRILINOS_TARGET_BRANCH=develop \
  TRILINOS_TARGET_REPO=https://github.com/trilinos/Trilinos \
  TRILINOS_TARGET_SHA=45adc9002091ba1fc6ae296c72696f8717b8b885 \
  PULLREQUESTNUM=111 \
  JOB_BASE_NAME=Trilinos_pullrequest_gcc_4.8.4 \
  BUILD_NUMBER=222 \
  WORKSPACE=$PWD \
 ~/Trilinos.base/Trilinos/cmake/std/PullRequestLinuxDriver.sh \
 &> console.out

$ cmake -P packageEnables.cmake 
-- Setting Trilinos_ENABLE_STK = ON
-- Setting Trilinos_ENABLE_STKDoc_tests = ON
-- Setting Trilinos_ENABLE_STKExprEval = ON
-- Setting Trilinos_ENABLE_STKIO = ON
-- Setting Trilinos_ENABLE_STKMesh = ON
-- Setting Trilinos_ENABLE_STKSearch = ON
-- Setting Trilinos_ENABLE_STKSearchUtil = ON
-- Setting Trilinos_ENABLE_STKSimd = ON
-- Setting Trilinos_ENABLE_STKTools = ON
-- Setting Trilinos_ENABLE_STKTopology = ON
-- Setting Trilinos_ENABLE_STKTransfer = ON
-- Setting Trilinos_ENABLE_STKUnit_test_utils = ON
-- Setting Trilinos_ENABLE_STKUnit_tests = ON
-- Setting Trilinos_ENABLE_STKUtil = ON
```

That looks correct. (FYI @prwolfe)

**Testing for PR #3258:** (Prior to updating the branch and the PR)

```
$ env \
  TRILINOS_SOURCE_BRANCH=3133-fix-logic \
  TRILINOS_SOURCE_REPO=https://github.com/bartlettroscoe/Trilinos \
  TRILINOS_SOURCE_SHA=b2cccbf5f5b2f56d31ce7fa2ae6c4957c938427c \
  TRILINOS_TARGET_BRANCH=develop \
  TRILINOS_TARGET_REPO=https://github.com/trilinos/Trilinos \
  TRILINOS_TARGET_SHA=45adc9002091ba1fc6ae296c72696f8717b8b885 \
  PULLREQUESTNUM=111 \
  JOB_BASE_NAME=Trilinos_pullrequest_gcc_4.8.4 \
  BUILD_NUMBER=222 \
  WORKSPACE=$PWD \
 ~/Trilinos.base/Trilinos/cmake/std/PullRequestLinuxDriver.sh \
 &> console.out

$ cmake -P packageEnables.cmake
-- Setting Trilinos_ENABLE_ALL_PACKAGES = ON
-- Setting Trilinos_ENABLE_TrilinosFrameworkTests = ON
```

That looks like the correct set of enables for the set of files that are being changed in that (this) PR.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@william76, can you please review this updated PR?  It fixes two sets of problems with the auto PR testing logic.

**Comment by bartlettroscoe** [comment]
So it looks like the Trilinos auto PR tester does not use the script `PullRequestLinuxDriver.sh` in the branch to drive testing.  It must use a version of the 'develop' branch or something.  You can see this in current PR testing iteration [here](https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3816094) which shows:

```
loading initial cache file /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.9.3/packageEnables.cmake
-- Setting Trilinos_ENABLE_ALL_PACKAGES = ON
-- Setting Trilinos_ENABLE_TrilinosFrameworkTests = ON
-- Setting Trilinos_ENABLE_Belos = ON
-- Setting Trilinos_ENABLE_TpetraCore = ON
```

That is not the right set of enables for the changes in the PR.  There are no changes to Belos or TpetraCore.

**Comment by william76** [comment]
@bartlettroscoe 
I'm not sure I'm following your previous comment, what do you mean that `PullRequestLinuxDriver.sh` isn't being used?

**Comment by bartlettroscoe** [comment]
> I'm not sure I'm following your previous comment, what do you mean that PullRequestLinuxDriver.sh isn't being used?

@william76, I just mean that `PullRequestLinuxDriver.sh ` is not getting used in the GCC 4.8.4 + OpenMP RP build as we discussed on Monday.

**Comment by william76** [comment]
@bartlettroscoe 

The cdash results you linked to are for a gcc 4.9.3 build... not a GCC 4.8.4 build.
I can't find the date/time that that job ran in the link you provided.  The 4.8.4 build did not use the PullRequestlinuxDriver script until yesterday when @prwolfe finished his checks of that build and changed it over to use script.  If your job ran before yesterday morning then it would have used the old system.

I just checked the jenkins job for 4.8.4 gcc and the gcc 4.8.4 OpenMP builds on Jenkins and they're both calling the `PullRequestLinuxDriver.sh` ... buuut the 4.8.4 OpenMP test doesn't appear to be used in Pull Request testing, since it last ran in June.  The three PR drivers for GCC 4.9.3, 4.8.4, and Intel 17.0.1 are all using the driver script now.

You should probably check in with @jwillenbring or @prwolfe on a OpenMP PR build... I don't think we run one based on the job names in Jenkins.

**Comment by prwolfe** [comment]
The “4.8.4_openmp” build that isn’t currently running was used during bootstrapping testing.  The one without the “openmp” is running everything now (and does use openmp).

I noticed my stk run yesterday built all packages for whatever reason as well.

Paul

**Comment by bartlettroscoe** [comment]
> I noticed my stk run yesterday built all packages for whatever reason as well.

@prwolfe, it is because of the defect described in Issue #3265 and fixed in PR #3258.

**Comment by bartlettroscoe** [comment]
Lets not merge this quite yet.  I realized a small tweak that needs to be made to get the right set of changed files in all cases and I am making some small changes to allow the script to be run locally to test the PR driver.  I will post the updated commit along with more detailed manual testing in a bit.

**Comment by bartlettroscoe** [comment]
@william76,

Where do you get the `simple_testing.cmake` and and `package_subproject_list.cmake` files that are used in the driver script `PullRequestLinuxDriver.sh`?  Without that, you can't fully test this driver script.

**Comment by william76** [comment]
@bartlettroscoe 
I don't know... I didn't write this script.  @prwolfe would probably know.

**Comment by bartlettroscoe** [comment]
@william76, I pushed updated commits.  I was able to modify the script to make it easy to test locally on any SEMS RHEL6 machine.  I think this is pretty solid.  I will contact you offline to see if we can walk through these changes carefully to see what was done as why.

**Comment by allevin** [comment]
@bartlettroscoe Ross, we are working on an improvement to the autotester to dump the last 100 lines of the log of each of the Jenkins runs into the Github Failed test report created by the AT.  It's not the same as having actual Jenkins access, but it might help out.  We need to do a bit more testing, but hopefully soon we can introduce it into the system.

**Comment by bartlettroscoe** [comment]
> Ross, we are working on an improvement to the autotester to dump the last 100 lines of the log of each of the Jenkins runs into the Github Failed test report created by the AT

@allevin, could the AT just attach the entire Jenkins job output as a file attachment with a `*.txt` extension or something?  That would not clutter up PR comments but would provide everything anyone would need to diagnose what was happening.

**Comment by allevin** [comment]
> @allevin, could the AT just attach the entire Jenkins job output as a file attachment with a `*.txt` extension or something?  That would not clutter up PR comments but would provide everything anyone would need to diagnose what was happening.

@bartlettroscoe I looked into this a bit this morning... Basically it looks like the Github API does not allow uploading files as issue attachments ([see this response from Github](https://github.com/isaacs/github/issues/1133#issuecomment-394363958)).  I also don't see any way to do is via PyGithub.  I will ping some of the developers at PyGithub and see if they are aware of anyway to do it.  I suspect they don't want automated systems to dump huge files onto their servers.

**Comment by bartlettroscoe** [comment]
> Basically it looks like the Github API does not allow uploading files as issue attachments (see this response from Github). I also don't see any way to do is via PyGithub. I will ping some of the developers at PyGithub and see if they are aware of anyway to do it. I suspect they don't want automated systems to dump huge files onto their servers.

@allevin, thanks for checking on this.  That makes sense.  Another option is to put the log file contents into a `<details> ... </details>` block a the very bottom of the comment.  That way, it will not bother anyone unless they want to see it.  But getting the last 100 lines might be enough to help.  Thanks!

**Comment by allevin** [comment]
> @allevin, thanks for checking on this. That makes sense. Another option is to put the log file contents into a <details> ... </details> block a the very bottom of the comment. That way, it will not bother anyone unless they want to see it. But getting the last 100 lines might be enough to help. Thanks!

That's exactly what we are doing.

**Pull request merged**
