### PR TITLE
TriBITS snapshot update 2023-03-29 (#11545)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Related to #11545 and implements use case 3 from TriBITSPub/TriBITS#63.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Hello @jwillenbring, @sebrowne, @rppawlo, @lucbv, this TriBITS update is needed for pre-installing packages and building downstream packages against this.  This TriBITS PR update should be maintaining about perfect backwards compatibility compared to what is already in the Trilinos 'develop' branch.  (NOTE: The updated [tribits/CHANGLOG.md](cmake/tribits/CHANGELOG.md) file is documenting some possible breaks in backward compatibility that have already been merged to Trilinos 'develop' but I failed to document before that.)

**Comment by lucbv** [comment]
@bartlettroscoe I have started reading this but it will take a bit of time go through everything especially since I am not CMake/TriBits expert.
Once comment: if this review take time it might be okay to create a seperate PR to tackle all the places where you update the cmake minimum required version as this is a fairly straightforward change that can be approved easily.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I have started reading this but it will take a bit of time go through everything especially since I am not CMake/TriBits expert.

@lucbv, these changes have already been reviewed in the TriBITS GitHub repo (see TriBITSPub/TriBITS#560).  This PR should just be a rubber stamp approval.  (It make no sense to do detailed reviews of a snapshot commit.)

**Review by sebrowne — COMMENTED** [review]
The spirit of the changes looks fine to me (I read use case 3 in the design doc)

**Review by sebrowne — APPROVED** [review]
I understand and approve of the concept, and I'm happy trusting the automatic testing to ensure that this does not break the current use cases.

**Comment by bartlettroscoe** [comment]
> I understand and approve of the concept, and I'm happy trusting the automatic testing to ensure that this does not break the current use cases.

@sebrowne, like every TriBITS change as part of this process, if there a problems, people will report them and they will be fixed quickly or if that can't be done quickly, the changes will be backed out and fixed offline.

**Review by lucbv — APPROVED** [review]
Good to go

**Pull request merged**
