### PR TITLE
Panzer: remove deprecated code

### PR DESCRIPTION
**Pull request by rppawlo**
pamgen factory was merged with exodus factory

I didn't remove this earlier so that we could provide time for apps to transition to new code. Since all apps are now updated it is safe to remove this object.

### CODE REVIEW

**Comment by rppawlo** [comment]
I accidentally submitted this as a PR against master branch. Even though I edited the ticket to change the target to develop, it is still failing the merge thinking that it is still merging into master. Might need to change the PR tester to recheck on the target merge branch. @prwolfe - are you the right person to contact on this?

 I will reopen a new PR.

**Comment by jmgate** [comment]
@rppawlo, I think you were just seeing a delayed email notification from GitHub.

**Comment by prwolfe** [comment]
Let's see

- The builds against master failed at 8:08AM
- You changed it to develop at 8:32 AM
- The 8:45 build tested PR #5518 which did not finish for 4h 2min
- you closed this PR at 10:53 AM before the test of #5518 completed

So I don't think this had anything to do with the change in branch being ignored, just bad timing.

**Comment by rppawlo** [comment]
Thanks @prwolfe !

**Pull request closed without merging**
