### PR TITLE
Kokkos Promotion 2.7.24

### PR DESCRIPTION
**Pull request by crtrott**
This promotes Kokkos and KokkosKernels to Version 2.7.24.

### CODE REVIEW

**Comment by crtrott** [comment]
I reran Blake and White tests using the scripts in the kokkos-kernels/scripts/trilinos-integration repos. Has some issues with jobs stopping to run but by manually rebuilding it looked all good. Here is test output:

# Blake Pthread 
### Updated:
```
Test project /ascldap/users/crtrott/TrilinosBuild/Blake/TrilinosIntegration/Pthreads/build_updated
        Start   1: KokkosCore_UnitTest_Serial_MPI_1
  1/1764 Test   #1: KokkosCore_UnitTest_Serial_MPI_1 ..............................................................   Passed    4.47 sec
...
        Start 1764: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3
1764/1764 Test #1764: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 ....................................................   Passed    0.90 sec


99% tests passed, 6 tests failed out of 1764

Label Time Summary:
Amesos2          =   4.34 sec (8 tests)
Anasazi          =  51.06 sec (74 tests)
Belos            =  62.71 sec (92 tests)
Ifpack           =  26.64 sec (41 tests)
Ifpack2          =  33.87 sec (42 tests)
Intrepid         = 115.91 sec (144 tests)
Intrepid2        =  46.88 sec (148 tests)
Isorropia        =   2.35 sec (4 tests)
Kokkos           =  80.50 sec (26 tests)
KokkosKernels    = 286.83 sec (8 tests)
ML               =  11.90 sec (16 tests)
MueLu            = 122.14 sec (59 tests)
NOX              =  71.74 sec (92 tests)
Panzer           =  95.98 sec (120 tests)
Phalanx          =  11.50 sec (22 tests)
ROL              = 112.93 sec (84 tests)
Sacado           =  61.26 sec (297 tests)
Stokhos          =  65.03 sec (79 tests)
Stratimikos      =  17.86 sec (23 tests)
Thyra            =  40.19 sec (81 tests)
Tpetra           = 106.56 sec (192 tests)
Xpetra           =   6.92 sec (17 tests)
Zoltan2          =  68.63 sec (101 tests)

Total Test time (real) = 1517.02 sec

The following tests FAILED:
	613 - Xpetra_CrsMatrix_UnitTests_MPI_4 (Not Run)
	615 - Xpetra_Matrix_UnitTests_MPI_4 (Not Run)
	616 - Xpetra_MatrixMatrix_UnitTests_MPI_4 (Not Run)
	618 - Xpetra_BlockedCrsMatrix_UnitTests_MPI_4 (Not Run)
	619 - Xpetra_ThyraBlockedOperator_UnitTests_MPI_4 (Not Run)
	1006 - Stratimikos_test_single_belos_thyra_solver_driver_nos1_nrhs8_MPI_1 (Failed)
Errors while running CTest
```

### Pristine:
```
Test project /ascldap/users/crtrott/TrilinosBuild/Blake/TrilinosIntegration/Pthreads/build_pristine
        Start   1: KokkosCore_UnitTest_Serial_MPI_1
  1/1764 Test   #1: KokkosCore_UnitTest_Serial_MPI_1 ..............................................................   Passed    4.84 sec
        Start   2: KokkosCore_UnitTest_Threads_MPI_1
...
        Start 1764: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3
1764/1764 Test #1764: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 ....................................................   Passed    1.07 sec

99% tests passed, 8 tests failed out of 1764

Subproject Time Summary:
Amesos2          =  21.20 sec*proc (8 tests)
Anasazi          = 391.79 sec*proc (74 tests)
Belos            = 1406.35 sec*proc (92 tests)
Ifpack           = 104.37 sec*proc (36 tests)
Ifpack2          =  97.30 sec*proc (42 tests)
Intrepid         = 870.84 sec*proc (144 tests)
Intrepid2        = 475.42 sec*proc (148 tests)
Isorropia        =  12.64 sec*proc (4 tests)
Kokkos           =  97.84 sec*proc (26 tests)
KokkosKernels    = 210.50 sec*proc (8 tests)
ML               = 113.60 sec*proc (16 tests)
MueLu            = 2190.79 sec*proc (58 tests)
NOX              = 1072.38 sec*proc (92 tests)
Panzer           = 505.14 sec*proc (120 tests)
Phalanx          =  16.14 sec*proc (22 tests)
ROL              = 591.47 sec*proc (84 tests)
Sacado           = 989.74 sec*proc (297 tests)
Stokhos          = 172.88 sec*proc (79 tests)
Stratimikos      =  30.10 sec*proc (23 tests)
Thyra            = 164.78 sec*proc (81 tests)
Tpetra           = 2023.20 sec*proc (192 tests)
Xpetra           = 158.50 sec*proc (17 tests)
Zoltan2          = 1476.67 sec*proc (101 tests)

Total Test time (real) = 6808.63 sec

The following tests FAILED:
	613 - Xpetra_CrsMatrix_UnitTests_MPI_4 (Not Run)
	615 - Xpetra_Matrix_UnitTests_MPI_4 (Not Run)
	616 - Xpetra_MatrixMatrix_UnitTests_MPI_4 (Not Run)
	618 - Xpetra_BlockedCrsMatrix_UnitTests_MPI_4 (Not Run)
	619 - Xpetra_ThyraBlockedOperator_UnitTests_MPI_4 (Not Run)
	1006 - Stratimikos_test_single_belos_thyra_solver_driver_nos1_nrhs8_MPI_1 (Failed)
	1047 - Intrepid_test_Discretization_Basis_HGRAD_LINE_Hermite_FEM_Test_01_MPI_1 (Timeout)
	1579 - ROL_adapters_tpetra_test_sol_TpetraSimulatedConstraintInterfaceCVaR_MPI_4 (Failed)
Errors while running CTest
```

# Blake Serial
### Updated
```
Test project /ascldap/users/crtrott/TrilinosBuild/Blake/TrilinosIntegration/Serial/build_updated
        Start   1: KokkosCore_UnitTest_Serial_MPI_1
  1/1797 Test   #1: KokkosCore_UnitTest_Serial_MPI_1 ..............................................................   Passed    4.64 sec
        Start   2: KokkosCore_UnitTest_Default_MPI_1
...
        Start 1797: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3
1797/1797 Test #1797: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 ....................................................   Passed    0.97 sec

99% tests passed, 2 tests failed out of 1797

Label Time Summary:
Amesos2          =   4.92 sec (9 tests)
Anasazi          =  69.79 sec (101 tests)
Belos            =  74.92 sec (107 tests)
Ifpack           =  26.79 sec (41 tests)
Ifpack2          =  36.60 sec (42 tests)
Intrepid         = 115.63 sec (144 tests)
Intrepid2        =  45.79 sec (148 tests)
Isorropia        =   2.89 sec (4 tests)
Kokkos           =  28.04 sec (24 tests)
KokkosKernels    = 111.04 sec (4 tests)
ML               =  12.04 sec (16 tests)
MueLu            = 132.55 sec (58 tests)
NOX              =  73.83 sec (92 tests)
Panzer           =  99.85 sec (120 tests)
Phalanx          =  11.36 sec (22 tests)
ROL              = 101.47 sec (84 tests)
Sacado           =  58.80 sec (293 tests)
ShyLU_Node       =   0.57 sec (3 tests)
Stokhos          =  66.45 sec (76 tests)
Stratimikos      =  17.99 sec (23 tests)
Thyra            =  40.41 sec (81 tests)
Tpetra           = 112.73 sec (192 tests)
Xpetra           =  13.25 sec (18 tests)
Zoltan2          =  68.72 sec (101 tests)

Total Test time (real) = 1340.94 sec

The following tests FAILED:
	1043 - Stratimikos_test_single_belos_thyra_solver_driver_nos1_nrhs8_MPI_1 (Failed)
	1612 - ROL_adapters_tpetra_test_sol_TpetraSimulatedConstraintInterfaceCVaR_MPI_4 (Failed)
```

### Pristine
```
Test project /ascldap/users/crtrott/TrilinosBuild/Blake/TrilinosIntegration/Serial/build_pristine
        Start   1: KokkosCore_UnitTest_Serial_MPI_1
  1/1797 Test   #1: KokkosCore_UnitTest_Serial_MPI_1 ..............................................................   Passed    3.65 sec
        Start   2: KokkosCore_UnitTest_Default_MPI_1
...
        Start 1797: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3
1797/1797 Test #1797: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 ....................................................   Passed    0.68 sec

99% tests passed, 2 tests failed out of 1797

Label Time Summary:
Amesos2          =   3.03 sec (9 tests)
Anasazi          =  46.90 sec (101 tests)
Belos            =  53.00 sec (107 tests)
Ifpack           =  17.38 sec (41 tests)
Ifpack2          =  27.56 sec (42 tests)
Intrepid         =  74.30 sec (144 tests)
Intrepid2        =  36.51 sec (148 tests)
Isorropia        =   1.54 sec (4 tests)
Kokkos           =  23.31 sec (24 tests)
KokkosKernels    =  88.78 sec (4 tests)
ML               =   8.52 sec (16 tests)
MueLu            = 121.26 sec (58 tests)
NOX              =  51.12 sec (92 tests)
Panzer           =  69.52 sec (120 tests)
Phalanx          =   7.16 sec (22 tests)
ROL              =  76.23 sec (84 tests)
Sacado           =  45.01 sec (293 tests)
ShyLU_Node       =   0.48 sec (3 tests)
Stokhos          =  48.11 sec (76 tests)
Stratimikos      =  12.72 sec (23 tests)
Thyra            =  24.56 sec (81 tests)
Tpetra           =  70.48 sec (192 tests)
Xpetra           =   9.11 sec (18 tests)
Zoltan2          =  48.66 sec (101 tests)

Total Test time (real) = 977.32 sec

The following tests FAILED:
	1043 - Stratimikos_test_single_belos_thyra_solver_driver_nos1_nrhs8_MPI_1 (Failed)
	1612 - ROL_adapters_tpetra_test_sol_TpetraSimulatedConstraintInterfaceCVaR_MPI_4 (Failed)
Errors while running CTest
```

**Comment by crtrott** [comment]
# White Cuda
### Updated
```
Test project /ascldap/users/crtrott/TrilinosBuild/White/Integration/Cuda/build_updated
        Start   1: KokkosCore_UnitTest_Serial_MPI_1
  1/1882 Test   #1: KokkosCore_UnitTest_Serial_MPI_1 ..............................................................   Passed    6.17 sec
        Start   2: KokkosCore_UnitTest_Cuda_MPI_1
...
        Start 1882: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3
1882/1882 Test #1882: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 ....................................................   Passed    3.30 sec

99% tests passed, 10 tests failed out of 1882

Subproject Time Summary:
Amesos2          =  39.07 sec*proc (8 tests)
Anasazi          = 394.84 sec*proc (74 tests)
Belos            = 427.74 sec*proc (92 tests)
Ifpack           =  93.04 sec*proc (36 tests)
Ifpack2          = 338.39 sec*proc (42 tests)
Intrepid         = 328.76 sec*proc (144 tests)
Intrepid2        = 215.83 sec*proc (255 tests)
Isorropia        =   9.62 sec*proc (4 tests)
Kokkos           = 194.89 sec*proc (27 tests)
KokkosKernels    = 226.63 sec*proc (8 tests)
ML               =  47.16 sec*proc (16 tests)
MueLu            = 1992.41 sec*proc (58 tests)
NOX              = 298.46 sec*proc (92 tests)
Panzer           = 575.20 sec*proc (120 tests)
Phalanx          =  16.47 sec*proc (22 tests)
ROL              = 1115.69 sec*proc (84 tests)
Sacado           = 137.42 sec*proc (300 tests)
Stokhos          = 266.46 sec*proc (83 tests)
Stratimikos      =  30.07 sec*proc (23 tests)
Thyra            =  96.17 sec*proc (81 tests)
Tpetra           = 942.50 sec*proc (194 tests)
Xpetra           = 246.78 sec*proc (18 tests)
Zoltan2          = 577.11 sec*proc (101 tests)

Total Test time (real) = 3767.25 sec

The following tests FAILED:
	366 - TpetraCore_Core_initialize_where_user_initializes_mpi_MPI_4 (Failed)
	367 - TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_MPI_4 (Failed)
	370 - TpetraCore_Core_initialize_where_tpetra_initializes_kokkos_MPI_1 (Failed)
	371 - TpetraCore_Core_ScopeGuard_where_tpetra_initializes_kokkos_MPI_1 (Failed)
	372 - TpetraCore_Core_initialize_where_user_initializes_kokkos_MPI_1 (Failed)
	373 - TpetraCore_Core_ScopeGuard_where_user_initializes_kokkos_MPI_1 (Failed)
	374 - TpetraCore_Core_initialize_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2 (Failed)
	375 - TpetraCore_Core_ScopeGuard_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2 (Failed)
	1679 - ROL_NonlinearProblemTest_MPI_4 (Timeout)
	1704 - ROL_test_elementwise_TpetraMultiVector_MPI_4 (Failed)
Errors while running CTest
```
Note Tpetra Test Failed because of warning about CUDA_MANAGED_FORCE_DEVICE_ALLOC not being set. Rerunning with that env variable results in passing tests:
```
bash-4.2$ ctest -R TpetraCore_Core_initialize
Test project /ascldap/users/crtrott/TrilinosBuild/White/Integration/Cuda/build_updated
    Start 364: TpetraCore_Core_initialize_where_tpetra_initializes_mpi_MPI_4
1/7 Test #364: TpetraCore_Core_initialize_where_tpetra_initializes_mpi_MPI_4 ...............................   Passed    1.46 sec
    Start 366: TpetraCore_Core_initialize_where_user_initializes_mpi_MPI_4
2/7 Test #366: TpetraCore_Core_initialize_where_user_initializes_mpi_MPI_4 .................................   Passed    1.34 sec
    Start 368: TpetraCore_Core_initialize_where_user_initializes_mpi_and_provides_comm_MPI_4
3/7 Test #368: TpetraCore_Core_initialize_where_user_initializes_mpi_and_provides_comm_MPI_4 ...............   Passed    1.22 sec
    Start 370: TpetraCore_Core_initialize_where_tpetra_initializes_kokkos_MPI_1
4/7 Test #370: TpetraCore_Core_initialize_where_tpetra_initializes_kokkos_MPI_1 ............................   Passed    0.98 sec
    Start 372: TpetraCore_Core_initialize_where_user_initializes_kokkos_MPI_1
5/7 Test #372: TpetraCore_Core_initialize_where_user_initializes_kokkos_MPI_1 ..............................   Passed    0.91 sec
    Start 374: TpetraCore_Core_initialize_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2
6/7 Test #374: TpetraCore_Core_initialize_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2 ...   Passed    0.98 sec
    Start 376: TpetraCore_Core_initialize_where_user_initializes_mpi_and_tpetra_initializes_kokkos_MPI_2
7/7 Test #376: TpetraCore_Core_initialize_where_user_initializes_mpi_and_tpetra_initializes_kokkos_MPI_2 ...   Passed    1.01 sec

100% tests passed, 0 tests failed out of 7

Subproject Time Summary:
Tpetra    =  21.94 sec*proc (7 tests)

Total Test time (real) =  25.07 sec
bash-4.2$ ctest -R TpetraCore_Core_ScopeGuard
Test project /ascldap/users/crtrott/TrilinosBuild/White/Integration/Cuda/build_updated
    Start 365: TpetraCore_Core_ScopeGuard_where_tpetra_initializes_mpi_MPI_4
1/7 Test #365: TpetraCore_Core_ScopeGuard_where_tpetra_initializes_mpi_MPI_4 ...............................   Passed    1.39 sec
    Start 367: TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_MPI_4
2/7 Test #367: TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_MPI_4 .................................   Passed    1.31 sec
    Start 369: TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_and_provides_comm_MPI_4
3/7 Test #369: TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_and_provides_comm_MPI_4 ...............   Passed    1.20 sec
    Start 371: TpetraCore_Core_ScopeGuard_where_tpetra_initializes_kokkos_MPI_1
4/7 Test #371: TpetraCore_Core_ScopeGuard_where_tpetra_initializes_kokkos_MPI_1 ............................   Passed    0.98 sec
    Start 373: TpetraCore_Core_ScopeGuard_where_user_initializes_kokkos_MPI_1
5/7 Test #373: TpetraCore_Core_ScopeGuard_where_user_initializes_kokkos_MPI_1 ..............................   Passed    0.90 sec
    Start 375: TpetraCore_Core_ScopeGuard_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2
6/7 Test #375: TpetraCore_Core_ScopeGuard_where_tpetra_initializes_mpi_and_user_initializes_kokkos_MPI_2 ...   Passed    0.99 sec
    Start 377: TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_and_tpetra_initializes_kokkos_MPI_2
7/7 Test #377: TpetraCore_Core_ScopeGuard_where_user_initializes_mpi_and_tpetra_initializes_kokkos_MPI_2 ...   Passed    1.01 sec

100% tests passed, 0 tests failed out of 7

Subproject Time Summary:
Tpetra    =  21.45 sec*proc (7 tests)

Total Test time (real) =  25.41 sec
```

### Pristine:
```
Test project /ascldap/users/crtrott/TrilinosBuild/White/Integration/Cuda/build_pristine
        Start   1: KokkosCore_UnitTest_Serial_MPI_1
  1/1882 Test   #1: KokkosCore_UnitTest_Serial_MPI_1 ..............................................................   Passed    6.16 sec
        Start   2: KokkosCore_UnitTest_Cuda_MPI_1
...
        Start 1882: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3
1882/1882 Test #1882: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 ....................................................   Passed    3.08 sec

99% tests passed, 2 tests failed out of 1882

Subproject Time Summary:
Amesos2          =  39.33 sec*proc (8 tests)
Anasazi          = 392.10 sec*proc (74 tests)
Belos            = 428.94 sec*proc (92 tests)
Ifpack           =  91.23 sec*proc (36 tests)
Ifpack2          = 338.70 sec*proc (42 tests)
Intrepid         = 328.56 sec*proc (144 tests)
Intrepid2        = 215.07 sec*proc (255 tests)
Isorropia        =   9.66 sec*proc (4 tests)
Kokkos           = 225.39 sec*proc (27 tests)
KokkosKernels    = 224.40 sec*proc (8 tests)
ML               =  46.47 sec*proc (16 tests)
MueLu            = 2044.64 sec*proc (58 tests)
NOX              = 319.03 sec*proc (92 tests)
Panzer           = 581.48 sec*proc (120 tests)
Phalanx          =  16.72 sec*proc (22 tests)
ROL              = 1102.39 sec*proc (84 tests)
Sacado           = 137.62 sec*proc (300 tests)
Stokhos          = 272.40 sec*proc (83 tests)
Stratimikos      =  29.25 sec*proc (23 tests)
Thyra            =  97.68 sec*proc (81 tests)
Tpetra           = 960.28 sec*proc (194 tests)
Xpetra           = 246.36 sec*proc (18 tests)
Zoltan2          = 570.08 sec*proc (101 tests)

Total Test time (real) = 3814.18 sec

The following tests FAILED:
	1679 - ROL_NonlinearProblemTest_MPI_4 (Timeout)
	1704 - ROL_test_elementwise_TpetraMultiVector_MPI_4 (Failed)
Errors while running CTest
```

# White OpenMP

### Updated
```
Test project /ascldap/users/crtrott/TrilinosBuild/White/Integration/OpenMP/build_updated
        Start   1: KokkosCore_UnitTest_Serial_MPI_1
  1/1872 Test   #1: KokkosCore_UnitTest_Serial_MPI_1 ..............................................................   Passed    6.41 sec
        Start   2: KokkosCore_UnitTest_OpenMP_MPI_1
...
        Start 1872: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3
1872/1872 Test #1872: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 ....................................................   Passed    1.16 sec

99% tests passed, 1 tests failed out of 1872

Subproject Time Summary:
Amesos2          =  17.29 sec*proc (9 tests)
Anasazi          = 234.49 sec*proc (74 tests)
Belos            = 291.62 sec*proc (92 tests)
Ifpack           =  94.21 sec*proc (36 tests)
Ifpack2          =  92.14 sec*proc (42 tests)
Intrepid         = 144.60 sec*proc (144 tests)
Intrepid2        = 129.38 sec*proc (248 tests)
Isorropia        =  10.61 sec*proc (4 tests)
Kokkos           = 101.49 sec*proc (27 tests)
KokkosKernels    = 445.71 sec*proc (8 tests)
ML               =  47.24 sec*proc (16 tests)
MueLu            = 429.80 sec*proc (58 tests)
NOX              = 232.24 sec*proc (92 tests)
Panzer           = 240.36 sec*proc (120 tests)
Phalanx          =  11.25 sec*proc (22 tests)
ROL              = 351.60 sec*proc (84 tests)
Sacado           = 112.99 sec*proc (297 tests)
ShyLU_Node       =   1.70 sec*proc (5 tests)
Stokhos          = 116.29 sec*proc (79 tests)
Stratimikos      =  29.20 sec*proc (23 tests)
Thyra            = 101.55 sec*proc (81 tests)
Tpetra           = 342.62 sec*proc (192 tests)
Xpetra           =  59.23 sec*proc (18 tests)
Zoltan2          = 279.29 sec*proc (101 tests)

Total Test time (real) = 2161.16 sec

The following tests FAILED:
	 32 - KokkosKernels_blas_serial_MPI_1 (Timeout)
Errors while running CTest
```

Rerunning KokkosKernels_blas_serial_MPI_1 shows the test passing in 390s.
```
bash-4.2$ ./KokkosKernels_blas_serial.exe 
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
[==========] Running 45 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 45 tests from serial
[ RUN      ] serial.abs_double
[       OK ] serial.abs_double (4 ms)
[ RUN      ] serial.abs_mv_double
[       OK ] serial.abs_mv_double (11 ms)
[ RUN      ] serial.asum_double
[       OK ] serial.asum_double (2 ms)
[ RUN      ] serial.axpby_double
[       OK ] serial.axpby_double (3 ms)
[ RUN      ] serial.axpby_mv_double
[       OK ] serial.axpby_mv_double (11 ms)
[ RUN      ] serial.axpy_double
[       OK ] serial.axpy_double (4 ms)
[ RUN      ] serial.axpy_mv_double
[       OK ] serial.axpy_mv_double (11 ms)
[ RUN      ] serial.dot_double
[       OK ] serial.dot_double (3 ms)
[ RUN      ] serial.dot_mv_double
[       OK ] serial.dot_mv_double (9 ms)
[ RUN      ] serial.mult_double
[       OK ] serial.mult_double (6 ms)
[ RUN      ] serial.mult_mv_double
[       OK ] serial.mult_mv_double (12 ms)
[ RUN      ] serial.nrm1_double
[       OK ] serial.nrm1_double (2 ms)
[ RUN      ] serial.nrm1_mv_double
[       OK ] serial.nrm1_mv_double (6 ms)
[ RUN      ] serial.nrm2_double
[       OK ] serial.nrm2_double (2 ms)
[ RUN      ] serial.nrm2_mv_double
[       OK ] serial.nrm2_mv_double (7 ms)
[ RUN      ] serial.nrm2_squared_double
[       OK ] serial.nrm2_squared_double (2 ms)
[ RUN      ] serial.nrm2_squared_mv_double
[       OK ] serial.nrm2_squared_mv_double (6 ms)
[ RUN      ] serial.nrminf_double
[       OK ] serial.nrminf_double (2 ms)
[ RUN      ] serial.nrminf_mv_double
[       OK ] serial.nrminf_mv_double (5 ms)
[ RUN      ] serial.reciprocal_double
[       OK ] serial.reciprocal_double (4 ms)
[ RUN      ] serial.reciprocal_mv_double
[       OK ] serial.reciprocal_mv_double (16 ms)
[ RUN      ] serial.scal_double
[       OK ] serial.scal_double (3 ms)
[ RUN      ] serial.scal_mv_double
[       OK ] serial.scal_mv_double (13 ms)
[ RUN      ] serial.sum_double
[       OK ] serial.sum_double (2 ms)
[ RUN      ] serial.sum_mv_double
[       OK ] serial.sum_mv_double (7 ms)
[ RUN      ] serial.team_abs_double
[       OK ] serial.team_abs_double (3 ms)
[ RUN      ] serial.team_abs_mv_double
[       OK ] serial.team_abs_mv_double (9 ms)
[ RUN      ] serial.team_axpby_double
[       OK ] serial.team_axpby_double (4 ms)
[ RUN      ] serial.team_axpby_mv_double
[       OK ] serial.team_axpby_mv_double (10 ms)
[ RUN      ] serial.team_axpy_double
[       OK ] serial.team_axpy_double (3 ms)
[ RUN      ] serial.team_axpy_mv_double
[       OK ] serial.team_axpy_mv_double (10 ms)
[ RUN      ] serial.team_dot_double
[       OK ] serial.team_dot_double (3 ms)
[ RUN      ] serial.team_dot_mv_double
[       OK ] serial.team_dot_mv_double (11 ms)
[ RUN      ] serial.team_mult_double
[       OK ] serial.team_mult_double (5 ms)
[ RUN      ] serial.team_mult_mv_double
[       OK ] serial.team_mult_mv_double (12 ms)
[ RUN      ] serial.team_nrm2_double
[       OK ] serial.team_nrm2_double (6 ms)
[ RUN      ] serial.team_scal_double
[       OK ] serial.team_scal_double (3 ms)
[ RUN      ] serial.team_scal_mv_double
[       OK ] serial.team_scal_mv_double (13 ms)
[ RUN      ] serial.team_update_double
[       OK ] serial.team_update_double (5 ms)
[ RUN      ] serial.team_update_mv_double
[       OK ] serial.team_update_mv_double (13 ms)
[ RUN      ] serial.update_double
[       OK ] serial.update_double (6 ms)
[ RUN      ] serial.update_mv_double
[       OK ] serial.update_mv_double (14 ms)
[ RUN      ] serial.gemv_double
[       OK ] serial.gemv_double (1642 ms)
[ RUN      ] serial.team_gemv_double
[       OK ] serial.team_gemv_double (3377 ms)
[ RUN      ] serial.gemm_double
[       OK ] serial.gemm_double (385371 ms)
[----------] 45 tests from serial (390673 ms total)

[----------] Global test environment tear-down
[==========] 45 tests from 1 test case ran. (390673 ms total)
[  PASSED  ] 45 tests.
```
### Pristine
```
Test project /ascldap/users/crtrott/TrilinosBuild/White/Integration/OpenMP/build_pristine
        Start   1: KokkosCore_UnitTest_Serial_MPI_1
  1/1872 Test   #1: KokkosCore_UnitTest_Serial_MPI_1 ..............................................................   Passed    5.85 sec
        Start   2: KokkosCore_UnitTest_OpenMP_MPI_1
...
        Start 1872: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3
1872/1872 Test #1872: PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 ....................................................   Passed    1.12 sec

100% tests passed, 0 tests failed out of 1872

Subproject Time Summary:
Amesos2          =  14.91 sec*proc (9 tests)
Anasazi          = 218.20 sec*proc (74 tests)
Belos            = 267.81 sec*proc (92 tests)
Ifpack           =  85.87 sec*proc (36 tests)
Ifpack2          =  86.12 sec*proc (42 tests)
Intrepid         = 131.17 sec*proc (144 tests)
Intrepid2        = 116.06 sec*proc (248 tests)
Isorropia        =  10.35 sec*proc (4 tests)
Kokkos           = 129.56 sec*proc (27 tests)
KokkosKernels    = 252.42 sec*proc (8 tests)
ML               =  42.87 sec*proc (16 tests)
MueLu            = 420.83 sec*proc (58 tests)
NOX              = 223.99 sec*proc (92 tests)
Panzer           = 207.94 sec*proc (120 tests)
Phalanx          =   9.56 sec*proc (22 tests)
ROL              = 316.50 sec*proc (84 tests)
Sacado           = 100.37 sec*proc (297 tests)
ShyLU_Node       =   1.49 sec*proc (5 tests)
Stokhos          =  95.44 sec*proc (79 tests)
Stratimikos      =  25.24 sec*proc (23 tests)
Thyra            =  90.42 sec*proc (81 tests)
Tpetra           = 305.85 sec*proc (192 tests)
Xpetra           =  56.09 sec*proc (18 tests)
Zoltan2          = 254.08 sec*proc (101 tests)

Total Test time (real) = 1838.38 sec
```

**Comment by crtrott** [comment]
Status of repositories for this test:

### Updated:
```
commit 4ff7eab1c82025a8ffd4f71539ff2954f69ed714
Author: Christian Trott <crtrott@sandia.gov>
Date:   Sat Nov 3 20:49:46 2018 -0600

    Snapshot of kokkos-kernels from commit 79a862434a3804062e471d7842f4220b2918aca8
    
    From repository at https://github.com/kokkos/kokkos-kernels
    
    At commit:
    commit 79a862434a3804062e471d7842f4220b2918aca8
    Merge: 17b0e57 1e117b0
    Author: Siva Rajamanickam <srajama@sandia.gov>
    Date:   Wed Oct 31 09:58:02 2018 -0600
    
        Merge pull request #336 from Tech-XCorp/techx-performance-class
    
        Kokkos: Add Performance class

commit 1e4d3da7736e2859f42c0987673d5fdfd720cb65
Author: Christian Trott <crtrott@sandia.gov>
Date:   Sat Nov 3 20:48:59 2018 -0600

    Snapshot of kokkos from commit c1510cec40f435c92eae84711b1d96a4cc1366cb
    
    From repository at https://github.com/kokkos/kokkos
    
    At commit:
    commit c1510cec40f435c92eae84711b1d96a4cc1366cb
    Merge: eca7be5 575df15
    Author: Christian Trott <crtrott@sandia.gov>
    Date:   Mon Oct 29 16:30:47 2018 -0600
    
        Merge pull request #1860 from kokkos/issue-1858
    
        Issue 1858 and 1859 fix

commit c285b26246e181e6b4ad3c2c31162dfd92c3daaf
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Thu Nov 1 18:27:16 2018 -0600

    Tpetra: Fix debug check in BlockCrsMatrix
```

### Pristine:
```
commit d193a2d2ac139a8c530abd5661ba9cd9165c5603
Merge: d7eaff0 d20b710
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Fri Nov 2 21:53:47 2018 -0600

    Merge Pull Request #3795 from alanw0/Trilinos/develop
    
    Automatically Merged using Trilinos Pull Request AutoTester
    PR Title: Fix nvidia compile issue in stk_search
    PR Author: alanw0

commit d20b71032e0b8d0699aacc7372c143046e7085c3
Author: Alan Williams <william@sandia.gov>
Date:   Fri Nov 2 20:08:10 2018 -0600

    Fix nvidia compile issue in stk_search

commit d7eaff0c7d4c11c77d2dc3c23f88538463531468
Merge: f8794e4 e7aad45
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Fri Nov 2 12:46:20 2018 -0600

    Merge Pull Request #3792 from trilinos/Trilinos/csiefer-e7aad45
    
    Automatically Merged using Trilinos Pull Request AutoTester
    PR Title: Ctest: Rocketman - A Sisyphean task?
    PR Author: csiefer2
```

**Comment by crtrott** [comment]
More discussion on this promotion can be found here: https://github.com/kokkos/kokkos/issues/1845

**Comment by crtrott** [comment]
Changes compared to prior test cycle were minor: removed a const marking in Tpetra and removed a const marking in cscal C extern function in KokkosKernels. Running Manually the GCC 4.8.4 PullRequest test passed. I also reran the OpenMP and Cuda test on white.

**Comment by ndellingwood** [comment]
@crtrott it looks like the test `Trilinos_pullrequest_gcc_4.9.3 # 2142` failed due to issues fetching the repo to test, not due to an actual failure:

```
ERROR: Timeout after 20 minutes
ERROR: Error fetching remote repo 'origin'
```

The rest of the tests passed. I don't think there is a way to override that failure to merge so I'll add the re-test label to relaunch so it finishes by tomorrow morning.

**Pull request merged**
