### PR TITLE
Panzer:  Remove Trailing Whitespace

### PR DESCRIPTION
**Pull request by jmgate**
@trilinos/panzer

## Description
This PR removes all trailing whitespaces from Panzer's `*.hpp` and `*.cpp` files.

## Motivation and Context
I have whitespace warnings turned on in my editor so I don't introduce any when modifying a file, but all the trailing whitespaces that were in Panzer made that setting relatively useless.

## How Has This Been Tested?
`ctest` shows all Panzer tests passing on my machine.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by jmgate** [comment]
Ah shuck&mdash;let me deal with these conflicts first.

**Comment by rppawlo** [comment]
Changes like this really need to be coordinated with the entire package development team. Basically anyone else doing development at the same time is now going to get hit with a ton of merge conflicts.

**Comment by jmgate** [comment]
Shall we do that coordination, or in practice does that mean this'll never happen?

**Comment by rppawlo** [comment]
I think just checking with panzer team to make sure that there are no large commits in local repos would be fine. We had this happen a few years ago and it really disrupted some code development because every change in a local branch had to be resolved - it was a big set of commits.

**Comment by jmgate** [comment]
Very good.  Let me whip up a little shell command so Panzer developers can easily remove trailing whitespaces from any files they've updated locally&mdash;that should resolve the conflicts before they're seen in a merge/rebase.

**Comment by jmgate** [comment]
@allevin, can we see what's failing here?

**Comment by allevin** [comment]
@jmgate Looks like the Panzer clean directory issue.

Also, Github is reporting merge conflicts.  


In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/panzer/disc-fe/src/Panzer_BCStrategy_Dirichlet_DefaultImpl_impl.hpp:68:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/panzer/disc-fe/src/Panzer_BCStrategy_Dirichlet_DefaultImpl.cpp:48:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/panzer/disc-fe/src/Panzer_DOF.hpp:1:31: fatal error: Panzer_DOF_decl.hpp: No such file or directory
 #include "Panzer_DOF_decl.hpp"
                               ^
compilation terminated.
make[2]: *** [packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_BCStrategy_Dirichlet_DefaultImpl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by jmgate** [comment]
Yeah the build needs to be cleaned.  There weren't merge conflicts when I last looked at this on Friday&mdash;I'll deal with them today.

**Comment by jmgate** [comment]
Panzer developers, you can do the following to avoid a trailing whitespace merge conflict when this PR gets merged in:
*  Ensure your local changes are committed.
*  `cd` to `Trilinos/packages/panzer`.
*  Run `for f in $(grep -rsIil panzer --include=*.*pp); do sed -i "s/\s\+$//" $f; done`.
*  Running `git diff --ignore-space-at-eol` should give you no output (that is, the only changes were spaces at the end of the line).
*  Commit your changes.

Then when you update your local repo, if you do run into merge conflicts, they shouldn't be related to trailing whitespaces.

@rppawlo, @eric-c-cyr, @egphill, @bathmatt, does this work for you?  Is there anyone else modifying Panzer who should be looped in?

**Comment by jmgate** [comment]
@jwillenbring, can this build be cleaned as well?  This inability to request a clean build via the PR system seems to be hampering the autotesting considerably.

**Comment by jwillenbring** [comment]
@jmgate I blew away the workspace for the failing build. Is this something that will cause a failure upon next run in any existing workspace? That is the difficult case for the autotester.

**Comment by jwillenbring** [comment]
@jmgate OK, so why didn’t I have to clean the other PR testing build? I am trying to figure out the best way to address this. Since jobs can be run on different nodes, cleaning one may not be sufficient, but Jenkins doesn’t give us a good way to clean all workspaces. It is bad for the merge conflict to cause issues with the associated PR, but worse for the merge conflict to cause an issue with an unrelated PR. If we clean all builds every time, we end up with a lot more overall compilation time.

**Comment by jmgate** [comment]
> If we clean all builds every time, we end up with a lot more overall compilation time.

I agree, and we definitely don't want that.  I'm starting to think we need some flag in a PR (perhaps something like "[CleanBuild]" in the Title) that tells the autotester that once this PR has been merged, all workspaces need to be cleaned.  I'm afraid I don't know enough about Jenkins to know how this might be implemented.

We could try to be smart about it, check all the packages affected by the PR, and only clean those package build directories, so the recompilation is still as fast as possible.  Or perhaps we could require the PR submitter to place "[CleanBuild] \<comma separated list of package names\>" in the Description somewhere, and that would tell us what build directories to clean.  Unfortunately, I doubt the autotester has the ability now to see something in a PR and them remember it needs to do something after the PR is merged.  Neither of these solutions really feels elegant to me&mdash;I'm just spitballing ideas&mdash;not sure what the best solution is.

The way I've seen this play out recently, though, is on January 4th, commit fc76398 made it into develop, which switched a handful of `_decl.hpp` files to just `.hpp`.  For the past month then we've had the autotester fail a number of times looking for the `_decl.hpp` files and not finding them.  Each time we've needed you or someone else with enough privileges to go clean the build manually, which I know is undue frustration on your end.

Alternatively Trilinos could try to implement a policy that filenames can't change, but that doesn't seem like a good idea.

Not sure what the best thing to do here is.

**Comment by jwillenbring** [comment]
@jmgate I spoke with @rppawlo yesterday and I have an idea of what we could possibly do to allow easier cleanup of these issues. I think we could potentially use a file to track which slaves have been cleaned for each PR testing build and trigger the cleaning with a key in the PR title as suggested. I will bring this up at a @trilinos/framework standup next week to confirm feasibility.

**Comment by jmgate** [comment]
Sounds great.  Thanks @jwillenbring.

**Comment by jmgate** [comment]
Closing without merging&hellip;

**Pull request closed without merging**
