### PR TITLE
Framework: Enable additional warnings-as-errors in Trilinos

### PR DESCRIPTION
**Pull request by achauphan**
# THIS PR WILL HAVE A MERGE DEADLINE OF 08/22/24 !!!

@trilinos/framework

## Motivation
Begin enabling as much warnings-as-errors as possible back into Trilinos, beginning with `-Werror=sign-compare -Werror=unused-variable -Werror=parentheses`.

With the introduction of deprecated package header warnings in #12828, `-Werror` had to be turned off from several PR testing configurations (gcc-serial, gcc-openmpi, & gcc-openmpi-openmp). Since then, we cannot be confident that Trilinos can compile with minimal warnings related to all currently supported packages. See Related Issues section for more context on how this began.

## Fixing errors caused by these flags

Enabling these warnings in this PR is likely to cause several build errors across several packages that need to be fixed individually by the packages' maintainers. To give time for package developers to resolve the new warnings-as-errors present, there will be a deadline for this PR getting merged. Packages containing errors will be pinged in this thread to resolve the issues.

Instructions for how to reproduce a specific packages' results with the new flags can be reference in #13311 

**NOTE:** You should not use this branch to reproduce the errors seen reported to CDash in this PR.

## Related Issues

- [TRILFRAME-658](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-658)
- #13107 
- #13127 
- #13213
- #13311 

## Testing
Letting the AutoTester to figure out which packages need fixes and when these flags are ready for a general release into `CMAKE_CXX_FLAGS`.

### CODE REVIEW

**Comment by achauphan** [comment]
@trilinos/muelu @trilinos/panzer could someone kind enough help resolve these errors after enabling a few new warnings-as-errors flags for each package? :)

**Comment by cgcgcg** [comment]
@achauphan  Can you post the warnings/errors?

**Comment by achauphan** [comment]
@cgcgcg 
```
Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp:265:23: error: comparison of integer expressions of different signedness: 'MueLu::ReitzingerPFactory<double, int, long long int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial> >::LO' {aka 'int'} and 'size_t' {aka 'long unsigned int'} [-Werror=sign-compare]
       if (current + 1 >= max_edges) {
           ~~~~~~~~~~~~^~~~~~~~~~~~
Trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp:180:10: error: unused variable 'Nn' [-Werror=unused-variable]
   size_t Nn = NodeMatrix->getLocalNumRows();
          ^~
```
```
Trilinos/packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DynRankView.cpp: In member function 'virtual void panzer::unit_test::tCartesianDOFMgr_DynRankView_threed_UnitTest::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const':
Trilinos/packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DynRankView.cpp:73:7: error: unused variable 'rank' [-Werror=unused-variable]
   int rank = comm.getRank(); // processor rank
       ^~~~
Trilinos/packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DynRankView.cpp:112:7: error: unused variable 'ux_num' [-Werror=unused-variable]
   int ux_num   = dofManager->getFieldNum("UX");
       ^~~~~~
Trilinos/packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DynRankView.cpp:113:7: error: unused variable 'uy_num' [-Werror=unused-variable]
   int uy_num   = dofManager->getFieldNum("UY");
       ^~~~~~
```
```
Trilinos/packages/panzer/dof-mgrPanzer_GlobalIndexer.hpp:258:50: error: comparison of integer expressions of different signedness: 'std::enable_if_t<true, long unsigned int>' {aka 'long unsigned int'} and 'const int' [-Werror=sign-compare]
      TEUCHOS_ASSERT(functor.local_lids.extent(1) >= num_dofs);
Trilinos/packages/panzer/dof-mgrPanzer_GlobalIndexer.hpp:259:51: error: comparison of integer expressions of different signedness: 'std::enable_if_t<true, long unsigned int>' {aka 'long unsigned int'} and 'const int' [-Werror=sign-compare]
      TEUCHOS_ASSERT(functor.global_lids.extent(1) >= num_dofs);

```
```
Trilinos/packages/panzer/disc-fePanzer_Interpolation.cpp:564:63: error: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'KokkosSparse::SparseRowViewConst<KokkosSparse::CrsMatrix<double, int, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void, long unsigned int> >::ordinal_type' {aka 'const int'} [-Werror=sign-compare]
                                          for(size_t kk = 0; kk<row.length; ++kk)
```

**Comment by achauphan** [comment]
Errors present in GCC serial PR test
@trilinos/pamgen 
```
Trilinos/packages/pamgen/test/rtc_test/rtcompiler-test.cc:270:16: error: unused variable 'epsilon' [-Werror=unused-variable]
   const double epsilon = 1.0e-15;
```

@trilinos/trilinoscouplings 
```
Trilinos/couplings/examples/scaling/example_CVFEM.cpp:214:7: error: unused variable 'numProcs' [-Werror=unused-variable]
   int numProcs=1;
       ^~~~~~~~
```

**Comment by achauphan** [comment]
Thank you @cgcgcg for getting all those fixes in! I was worried that this would produce a lot more errors than it actually did.

Either way, it looks like those fixes worked, just the Clang build ran into network issues with CEE GitLab again... retesting.

**Review by sebrowne — APPROVED** [review]

**Pull request merged**
