### PR TITLE
Fix reduced tarball configuration (#11976)

### LINKED ISSUE #11976: Tribits: make package_source creates tarballs with missing BuildStatsWrappers.cmake
## Bug Report

@trilinos/tribits @bartlettroscoe 

After using the `make package_source` option to generate packaged source code tarballs for a configuration of Trilinos, if I try to configure the packaged source with the same configuration I encounter errors due to the `build_stats` directory missing from the `commonTools` directory:

<details>

<summary><b>Configure error output</b> (click to expand)</summary>

```
-- The Current CXX Standard is : 17

Configuring Trilinos build directory

-- PROJECT_SOURCE_DIR='/Users/ndellin/Research/trilinos/TestPackageSource/trilinos-14.1-Source'
-- PROJECT_BINARY_DIR='/Users/ndellin/Research/trilinos/TestPackageSource/Build'
-- Trilinos_TRIBITS_DIR='/Users/ndellin/Research/trilinos/TestPackageSource/trilinos-14.1-Source/cmake/tribits'
-- TriBITS_VERSION_STRING='0.9 (Dev)'
-- CMAKE_VERSION='3.24.4'
-- CMAKE_GENERATOR='Unix Makefiles'
-- CMAKE_HOST_SYSTEM_NAME='Darwin'
-- Trilinos_HOSTNAME='s1067110'
-- PYTHON_EXECUTABLE='/opt/local/bin/python'

Setting up major user options ...

CMake Error at cmake/CallbackSetupExtraOptions.cmake:91 (include):
  include could not find requested file:

    /Users/ndellin/Research/trilinos/TestPackageSource/trilinos-14.1-Source/commonTools/build_stats/BuildStatsWrappers.cmake
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1167 (include)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1292 (tribits_repository_setup_extra_options_runner)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:140 (tribits_process_extra_repos_options_files)
  cmake/tribits/core/package_arch/TribitsProject.cmake:92 (tribits_project_impl)
  CMakeLists.txt:126 (TRIBITS_PROJECT)


CMake Error at cmake/CallbackSetupExtraOptions.cmake:92 (generate_build_stats_wrappers):
  Unknown CMake command "generate_build_stats_wrappers".
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1167 (include)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1292 (tribits_repository_setup_extra_options_runner)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:140 (tribits_process_extra_repos_options_files)
  cmake/tribits/core/package_arch/TribitsProject.cmake:92 (tribits_project_impl)
  CMakeLists.txt:126 (TRIBITS_PROJECT)


-- Configuring incomplete, errors occurred!
See also "/Users/ndellin/Research/trilinos/TestPackageSource/Build/CMakeFiles/CMakeOutput.log".
```

</details>

Copying the missing `commonTools/build_stats` from the original Trilinos source to the packaged source directory allows for configuration and compilation 

### Steps to Reproduce

1. SHA1:  fba42cea7c742468adcecb5b0201e5d12ef07703
2. Steps with just Teuchos enabled using gnu compilers

<details>

<summary><b>Reproduction details</b> (click to expand)</summary>

```bash
# Part 1: Simple configuration of Trilinos and run make package_source to generate packaged source code tarballs
mkdir -p build
cd build

cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_INSTALL_PREFIX=$PWD/install -DTrilinos_ENABLE_Teuchos=ON -DTeuchos_ENABLE_TESTS=OFF $TRILINOS_DIR

make package_source
# This will create e.g. trilinos-14.1-Source.tar.gz


# Part 2: Attempt to configure from the packaged source

# Create a new build directory to test the packaged source
mv trilinos-14.1-Source.tar.gz ..
cd ..
tar -zxv trilinos-14.1-Source.tar.gz
mkdir -p build_package_source
cd build_package_source

cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_INSTALL_PREFIX=$PWD/install -DTrilinos_ENABLE_Teuchos=ON -DTeuchos_ENABLE_TESTS=OFF $PWD/../trilinos-14.1-Source
# At this point configuration errors occur
```

</details>

## Tasks

* [x] Fix immediate problem in Trilinos (see PR #11977)
* [ ] Apply TriBITS fix to TriBITS repo and add missing TriBITS test case
* [ ] Experiment with trying to keep `commonTools/build_stats` even if the `TrilinosBuildStats` package is not enabled (e.g. by removing the exclude from `CPACK_SOURCE_IGNORE_FILES` in the file `cmake/CallbackDefineRepositoryPackaging.cmake`)
* [ ] Add new Trilinos tests to the `TrilinosInstallTests` package to test tarball creation and configure from expanded tarball source tree

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @ndellingwood, @dmdunla 

Fixes #11976 

NOTE: I will move the TriBITS commit 40e37d9a191 to the main TriBITS repo and add a test to better protect this use case.  (Seems TriBITS is not actually testing the configure of the reduced tarball, only the deleting of the non-enabled package directories.  I will update the test to check the actual configure of the reduced tarball.)

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]
Wow that was a fast fix, thanks @bartlettroscoe ! Changes look reasonable

**Comment by ndellingwood** [comment]
@bartlettroscoe I tested this with just an enable of Teuchos, but still seeing configuration errors when trying to configure from the packaged source:

```
-- The Current CXX Standard is : 17

Configuring Trilinos build directory

-- PROJECT_SOURCE_DIR='/Users/ndellin/Research/trilinos/trilinos-14.1-Source'
-- PROJECT_BINARY_DIR='/Users/ndellin/Research/trilinos/PR-11977-package-build'
-- Trilinos_TRIBITS_DIR='/Users/ndellin/Research/trilinos/trilinos-14.1-Source/cmake/tribits'
-- TriBITS_VERSION_STRING='0.9 (Dev)'
-- CMAKE_VERSION='3.24.4'
-- CMAKE_GENERATOR='Unix Makefiles'
-- CMAKE_HOST_SYSTEM_NAME='Darwin'
-- Trilinos_HOSTNAME='s1067110'
-- Found PythonInterp: /opt/local/bin/python (found suitable version "3.10.11", minimum required is "2.6") 
-- PYTHON_EXECUTABLE='/opt/local/bin/python'
-- Found Git: /opt/local/bin/git (found version "2.40.1") 

Setting up major user options ...


***
*** NOTE: Setting Trilinos_ENABLE_PyTrilinos=OFF because BUILD_SHARED_LIBS=OFF!
***

-- Setting Trilinos_ENABLE_TriKota=OFF because '/Users/ndellin/Research/trilinos/trilinos-14.1-Source/packages/TriKota/Dakota' does not exist!
-- Trilinos_GENERATE_REPO_VERSION_FILE='ON'

NOTE: Skipping generation of TrilinosRepoVersion.txt because project source is not a git repo!

Reading list of native TPLs from /Users/ndellin/Research/trilinos/trilinos-14.1-Source/TPLsList.cmake

-- After reading above TPLsList.cmake file: Trilinos_NUM_DEFINED_TPLS='122'

Reading list of native packages from /Users/ndellin/Research/trilinos/trilinos-14.1-Source/PackagesList.cmake


***
*** Error, the package TrilinosFrameworkTests directory /Users/ndellin/Research/trilinos/trilinos-14.1-Source/commonTools/framework does not exist!
***

CMake Error at cmake/tribits/core/package_arch/TribitsProcessPackagesAndDirsLists.cmake:562 (message):
  Stopping due to above error!
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsReadAllProjectDepsFilesCreateDepsGraph.cmake:221 (tribits_process_packages_and_dirs_lists)
  cmake/tribits/core/package_arch/TribitsReadAllProjectDepsFilesCreateDepsGraph.cmake:77 (tribits_read_defined_external_and_internal_toplevel_packages_lists)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:154 (tribits_read_all_project_deps_files_create_deps_graph)
  cmake/tribits/core/package_arch/TribitsProject.cmake:92 (tribits_project_impl)
  CMakeLists.txt:126 (TRIBITS_PROJECT)


-- Configuring incomplete, errors occurred!
```

I reported as missing `build_stats`, but apparently there are multiple components from `commonTools` that are missing, `build_stats` just happened to be the first package in the list

**Comment by bartlettroscoe** [comment]
@ndellingwood, I was able to reproduce your failure and it is fixed by setting `-D Trilinos_ASSERT_DEFINED_DEPENDENCIES=OFF` as described in:

* https://docs.trilinos.org/files/TrilinosBuildReference.html#creating-a-tarball-of-the-source-tree

which says:

> NOTE: When configuring from an untarred source tree that has missing packages, one must configure with:
> 
> ```
>     -D Trilinos_ASSERT_DEFINED_DEPENDENCIES=OFF
> ```
> 
> Otherwise, TriBITS will error out complaining about missing packages. (Note that `Trilinos_ASSERT_DEFINED_DEPENDENCIES` will default to `OFF` in release mode, i.e. `Trilinos_ENABLE_DEVELOPMENT_MODE==OFF`.)

**Comment by bartlettroscoe** [comment]
FYI: No results showed up on CDash from the [above](https://github.com/trilinos/Trilinos/pull/11977#issuecomment-1592297486) PR testing iteration.

**Comment by sebrowne** [comment]
Running it again, there were issues with the backing service last night and we got no builds.

**Comment by bartlettroscoe** [comment]
Shoot, one failing test in the PR iteration [above](https://github.com/trilinos/Trilinos/pull/11977#issuecomment-1593722918) blocked the merge of this PR 😢.  The failing test was:

* [`Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests_MPI_1`](https://trilinos-cdash.sandia.gov/test/28403615)

in the build:

* [`test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables`](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=956644&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and)

showing:

<details>

<summary><b>Detailed test failure output for Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests_MPI_1</b> (click to expand)</summary>

```
4. AnalyticPolynomialsMatch_Sacado_Fad_DFadType_Sacado_Fad_DFadType_HierarchicalNodalComparisons_UnitTest ... :0: : block: [865,0,0], thread: [0,95,0] Assertion `Allocation failed.` failed.
:0: : block: [963,0,0], thread: [0,127,0] Assertion `Allocation failed.` failed.
:0: : block: [975,0,0], thread: [0,95,0] Assertion `Allocation failed.` failed.
:0: : block: [867,0,0], thread: [0,63,0] Assertion `Allocation failed.` failed.
:0: : block: [962,0,0], thread: [0,63,0] Assertion `Allocation failed.` failed.
:0: : block: [864,0,0], thread: [0,31,0] Assertion `Allocation failed.` failed.
:0: : block: [910,0,0], thread: [0,95,0] Assertion `Allocation failed.` failed.
:0: : block: [886,0,0], thread: [0,31,0] Assertion `Allocation failed.` failed.
:0: : block: [885,0,0], thread: [0,127,0] Assertion `Allocation failed.` failed.
:0: : block: [832,0,0], thread: [0,31,0] Assertion `Allocation failed.` failed.
:0: : block: [958,0,0], thread: [0,31,0] Assertion `Allocation failed.` failed.
:0: : block: [863,0,0], thread: [0,63,0] Assertion `Allocation failed.` failed.
:0: : block: [866,0,0], thread: [0,63,0] Assertion `Allocation failed.` failed.
cudaStreamSynchronize(stream) error( cudaErrorAssert): device-side assert triggered ../Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:144
Backtrace:
                       [0x25f13a5]
                       [0x25ea76a]
                       [0x25ea79b]
                       [0x25f7dd4]
                       [0x25f89d6]
                        [0x8da515]
                        [0x8da8a1]
                        [0x8db3bc]
                        [0x8e6a4d]
                        [0x9eb41e]
                        [0x9ec7d4]
                       [0x25c2484]
                       [0x25c58a9]
                       [0x25c99db]
                       [0x25ca563]
                        [0x69ce61]
__libc_start_main [0x7f8400812555]
                        [0x6a4d29]
[ascicgpu051:287514] *** Process received signal ***
[ascicgpu051:287514] Signal: Aborted (6)
[ascicgpu051:287514] Signal code:  (-6)
```

</details>

I will search on CDash to see if this failure is isolated or not before putting on `AT: RETEST` to re-run the PR builds.

**Comment by bartlettroscoe** [comment]
Looking at [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2023-05-16&end=2023-06-15&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=65&value2=Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests&field3=status&compare3=61&value3=failed&field4=testoutput&compare4=97&value4=Signal%3A%20Aborted%20.6.) the above PR testing iteration seems to be the only time this test [Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests_MPI_1](https://trilinos-cdash.sandia.gov/test/28403615) has failed in this way in any PR builds so this might just be a random system issue (or a latent Trilinos bug; hard to tell).

I will put on `AT: RETEST` and I suspect this test will pass next time (and cross fingers that an unrelated failure does not occur).

**Pull request merged**
