### PR TITLE
Layout swap

### PR DESCRIPTION
**Pull request by bathmatt**
Make the code so you can swap layout in one spot

### CODE REVIEW

**Comment by bathmatt** [comment]
@jmgate @rppawlo what failed on this?

**Comment by jmgate** [comment]
Need more info.  What failures are we looking at?  I don't see anything.

**Comment by bathmatt** [comment]
Master Merge AutoTester — Run 1/2:All Jobs Finished; status = FAILURE

**Comment by jmgate** [comment]
Can you give me a link?

**Comment by bathmatt** [comment]
> Can you give me a link?

Down two inches from your comment.

**Comment by jmgate** [comment]
@allevin, can you enlighten us as to what this status means on this PR?
Screen Shot 2021-01-12 at 10 14 12 AM

We haven't seen the autotester comment on this PR yet, so we're not sure what it means.

**Comment by allevin** [comment]
> @allevin, can you enlighten us as to what this status means on this PR?
> Screen Shot 2021-01-12 at 10 14 12 AM
> 
> We haven't seen the autotester comment on this PR yet, so we're not sure what it means.

@jmgate It looks like the Master Merge utility is trying to run and is failing, I don't recall exactly all the details.  But I thought it created a PR targeted at master and then tested it.  @william76 and/or @jwillenbring may recall more about how it works.  Is this a normal Pull Request from a user?

**Comment by jmgate** [comment]
@trilinos/framework, can you look into what's going on behind the scenes here?  This is a standard PR from a Trilinos developer against the `develop` branch (from what I can see, it looks like it was created against the `develop` branch from the outset).  We're unsure why it looks like the master merge autotester is running against it instead of the standard PR one.

**Comment by prwolfe** [comment]
> @trilinos/framework, can you look into what's going on behind the scenes here? This is a standard PR from a Trilinos developer against the `develop` branch (from what I can see, it looks like it was created against the `develop` branch from the outset). We're unsure why it looks like the master merge autotester is running against it instead of the standard PR one.

It looks like a previous PR was targeted at master (#8568 ) - the master merge tester picked that up and properly failed. The normal start messages are in that PR, but the Failure note is in this one - not sure why.

**Comment by allevin** [comment]
> > @trilinos/framework, can you look into what's going on behind the scenes here? This is a standard PR from a Trilinos developer against the `develop` branch (from what I can see, it looks like it was created against the `develop` branch from the outset). We're unsure why it looks like the master merge autotester is running against it instead of the standard PR one.
> 
> It looks like a previous PR was targeted at master (#8568 ) - the master merge tester picked that up and properly failed. The normal start messages are in that PR, but the Failure note is in this one - not sure why.

@trilinos/framework @prwolfe @jmgate Once the master merge ran, it added the status for the "Master Merge AutoTester" to the PR.  There is really no easy way to remove a status that has been added.

From what I can see, its not marked as required so it should not block merging.  Once the PR is passing all tests and the 3 Required status's are green, the PR should be mergeable.  If not, someone with Admin powers may have not manually force the merge.

**Review by rppawlo — APPROVED** [review]

**Comment by bathmatt** [comment]
AFAIK @rppawlo is going to test and fix a couple of things and then we can merge this,

**Comment by rppawlo** [comment]
The Drekar failure was due to the intrepi2 change from last week, but the build can't get any further. I didn't see any issue up to that point. The changes here cause three conflicts that are easy to resolve. So we just need to decide which one to merge first - this or @seamill 's PR and then I can resolve the other commit. I am working on testing against charon right now.

**Comment by bathmatt** [comment]
@rppawlo I'm willing to hit merge once my Cuda test passes for EMPIRE, all the panzer unit tests passed so . . .

**Comment by rppawlo** [comment]
Sounds good. Once you merge this I'll resolve the conflicts with #8541 .

**Comment by rppawlo** [comment]
@bathmatt - Drekar and Charon are passing and I have the changes ready for @seamill 's PR.

**Pull request merged**
