### PR TITLE
Fix FEI build issue (warning-as-errors)

### LINKED ISSUE #2279: Warnings-as-errors need cleaned up
All three builds that use watnings-as-errors are showing 50+ failures.  We need to look into these to support customers that use this. See https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3400360

@trilinos/fei 2 failures from one file (packages/fei/base/fei_FEDataFilter.cpp) due to an unused variable

## Expectations

These warnings/errors should be resolved and the changes set as pull requests into develop to support Sierra and other codes. When those pull requests are merged the ticket should be closed.

## Current Behavior

Warnings-as-errors builds fail on the above conditions

## Your Environment

- **Relevant repo SHA1s:**  
- **Relevant configure flags or configure script:**  
- **Operating system and version:**  
- **Compiler and TPL versions:**  

## Related Issues

* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

### PR DESCRIPTION
**Pull request by prwolfe**
This was failing in warning-as-error builds and the if
statement was not clear.  This quiets the compiler and
make the fact that we are checking to see if the returned
pointer is not null explicit.

@trilinos/fei 

## Related Issues

* Closes #2279

## How Has This Been Tested?

Replicated warnings-as-error-builds locally

## Checklist

- [ x ] My commit messages mention the appropriate GitHub issue numbers.
- [ x ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ x ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by prwolfe** [comment]
Thanks for changing this to develop @jmgate - not sure how I did that.

**Comment by jmgate** [comment]
No worries.  By default the base branch will be `master` when creating a PR.  I've asked for GitHub to add a feature such that we can distinguish between a "default checkout" branch (which would be `master` for Trilinos) and a "default PR" branch (which would be `develop`), but it doesn't sound like that'll happen any time soon.

**Comment by mhoemmen** [comment]
I can't see any of these builds on the Dashboard, so I don't know what made them fail.

**Comment by mhoemmen** [comment]
@trilinos/framework is there some reason why the builds disappear so fast / never appear on the Dashboard?

**Pull request merged**
