### PR TITLE
Teuchos: support initializer_list construction in Array class

### PR DESCRIPTION
**Pull request by rppawlo**
@trilinos/teuchos 

## Motivation

Allow Array class to be constructed from std::initializer_list

## Stakeholder Feedback

Requested by ParameterList users

## Testing

New test added to Array tests

### CODE REVIEW

**Comment by rppawlo** [comment]
@tkordenbrock

**Review by bartlettroscoe — APPROVED** [review]
Looks great.  Thanks for putting this in @rppawlo!

**Review by bartlettroscoe — COMMENTED** [review]
The only suggestion that would improve this would be to move this test to one of the finer-grained unit tests in the file:

[teuchos/core/test/MemoryManagement/Array_UnitTests.cpp](https://github.com/rppawlo/Trilinos/blob/teuchos-array-init-list-ctor/packages/teuchos/core/test/MemoryManagement/Array_UnitTests.cpp).

Perhaps add this as the unit test `TEUCHOS_UNIT_TEST_TEMPLATE_1_DECL(Array, initailizerList, T)` here:

https://github.com/rppawlo/Trilinos/blob/19ce13f209d08b69535eb85dbc7e48b0a8bdf19a/packages/teuchos/core/test/MemoryManagement/Array_UnitTests.cpp#L218

?

The tests in the file `Array_test.cpp` are just legacy tests that were never transferred over to the full Teuchos unit test harness.


?

**Comment by rppawlo** [comment]
@bartlettroscoe - thanks for pointing that out! I didn't see the second test file. It is now moved over. Will need to be reapproved.

**Review by bartlettroscoe — APPROVED** [review]
Thanks for moving this unit test @rppawlo!

**Comment by bartlettroscoe** [comment]
@rppawlo, I think the error shown [here](https://trilinos-cdash.sandia.gov/viewBuildError.php?buildid=1203102):

```
../Trilinos/packages/teuchos/core/src/Teuchos_Array.hpp(867): error: no instance of constructor "std::vector<_Tp, _Alloc>::vector [with _Tp=int, _Alloc=std::allocator<int>]" matches the argument list
            argument types are: (Teuchos::RCP<std::vector<int, std::allocator<int>>>)
          detected during:
            instantiation of "Teuchos::Array<T>::Array(std::initializer_list<T>) [with T=int]" 
../Trilinos/packages/teuchos/core/test/MemoryManagement/Array_UnitTests.cpp(536): here
            instantiation of "void <unnamed>::Array_initializerList_UnitTest<T>::runUnitTestImpl(Teuchos::FancyOStream &, __nv_bool &) const [with T=int]" 
```

might be fixed to adding `explicit` to the new constructor.

Do you want me to take over fixing these errors and getting this merged?

**Comment by rppawlo** [comment]
If you have time, sure! That would be a big help.

**Comment by bartlettroscoe** [comment]
> If you have time, sure! That would be a big help.

@rppawlo, let me just make sure I still have access to an ascicgpu machine so that I can reproduce this and then it should not take long (in people time, just computer time).

**Comment by bartlettroscoe** [comment]
FYI: I have reproduced the build errors and am fixing it.  (I am also trying to get rid of some unused var warnings as well.)

**Comment by bartlettroscoe** [comment]
The fixing commit is be8cc207a094785d2d2cfa6ecc4e53f96831862b.  That passes the builds of the Trilinos PR configurations `cuda-11.4.2-uvm-of` and a debug version of `clang-11.0.1` but there were some failing tests for me locally.  I will post those results to CDash just to archive them.

**Comment by bartlettroscoe** [comment]
The `clang-11.0.1` debug build is posted at [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascicgpu17&field2=buildname&compare2=61&value2=teuchos-array-init-list-ctor_rhel7_sems-clang-11.0.1-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field3=buildstamp&compare3=61&value3=20231019-2049-Experimental) which shows two failing tests:

<html>
<body>


SubProject | Name | Status | Time | Proc Time | Details | Labels | Summary | Processors
-- | -- | -- | -- | -- | -- | -- | -- | --
MueLu | MueLu_UnitTestsTpetra_MPI_1 | Failed | 9s 150ms | 9s 150ms | Completed (Failed) | MueLu | Unstable | 1
MueLu | MueLu_UnitTestsTpetra_MPI_4 | Failed | 6s 600ms | 26s 400ms | Completed (Failed) | MueLu | Unstable | 4


</body>
</html>

Those tests show the failure:

```
68. FactoryFactory_double_int_longlong_Tpetra_KokkosCompat_KokkosSerialWrapperNode_BuildFactory_UnitTest ... 
 Processing file: RAPFactory.xml
 Processing file: SaPFactory.xml
 Processing file: TentativePFactory.xml
 Processing file: CoupledAggregationFactory.xml
 
 p=0: *** Caught standard std::exception of type 'MueLu::Exceptions::RuntimeError' :
 
  /fgs/rabartl/Trilinos.base/Trilinos/packages/muelu/src/Interface/MueLu_FactoryFactory_decl.hpp:413:
  
  Throw number = 14
  
  Throw test that evaluated to true: true
  
  MueLu::FactoryFactory: unknown factory name : CoupledAggregationFactory
 [FAILED]  (0.00423 sec) FactoryFactory_double_int_longlong_Tpetra_KokkosCompat_KokkosSerialWrapperNode_BuildFactory_UnitTest
 Location: /fgs/rabartl/Trilinos.base/Trilinos/packages/muelu/test/unit_tests/ParameterList/FactoryFactory.cpp:72
 ```

The problem is that the factory `CoupledAggregationFactory` is no longer supported, it was removed in the commit 7073b7543bc8399e79c6f433b27177ec50363900 7 months ago, but the file `CoupledAggregationFactory.xml` was still sitting in the build directory I was using.  But the unit test that fails just globs all of the files in the build directory:

https://github.com/trilinos/Trilinos/blob/22c8508e8f12d2f5c40897256c06a0f9f313c841/packages/muelu/test/unit_tests/ParameterList/FactoryFactory.cpp#L86

This makes it so that you can't trust the build directory and must blow away the build directory and start from scratch to avoid issues like this.

I will post a MueLu issue to fix that test.

**Comment by bartlettroscoe** [comment]
FYI: The last PR testing iteration [above](https://github.com/trilinos/Trilinos/pull/12411#issuecomment-1772034937) failed due to a single random test timeout which I reported in:

* https://github.com/trilinos/Trilinos/issues/12391#issuecomment-1772897924

We really need to implement rerunning of timing out tests.

**Comment by bartlettroscoe** [comment]
FYI: The last PR test iteration was taken out by a random build failure in the build:

* [rhel7_sems-intel-2021.3-sems-openmpi-4.0.5_release-debug_shared_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-off_no-package-enables](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=1211367&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and)

showing:

```
icpc: error #10106: Fatal error in /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/intel-oneapi-compilers/2021.3.0/gcc/8.3.0/base/fptsktp/compiler/2021.3.0/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for ../Trilinos/packages/intrepid2/unit-test/MonolithicExecutable/AnalyticPolynomialsMatchTests.cpp (code 1)
```

Note that this is a random failure in a different build than the time before as described in https://github.com/trilinos/Trilinos/issues/12391#issuecomment-1772897924.

If the PR tester had just rerun that one timed out test, then it would have passed and would have allowed this PR to merge.

And if the PR tester ran a rebuild, I bet that build error would have gone away.  Seems like most of these random failures could be addressed with a single retry of the build or test.

We are burning up a lot of test machine time with these random failures.

Putting `AT: RETEST` on this PR again and crossing fingers.

**Comment by rppawlo** [comment]
Thanks Ross! Looks like everything passed. Since I initiated the PR, I cannot approve your changes. You will have to approve to allow this to be merged.

**Review by bartlettroscoe — APPROVED** [review]
Everything finally passed so this is ready to merge.

**Pull request merged**
