### PR TITLE
MueLu: Disable MueLu test, add fix for MueLu_Driver

### PR DESCRIPTION
**Pull request by seanofthemillers**
@trilinos/MueLu

## Motivation

Currently there are some tests that pass in MueLu, but actually throw errors.

Changes:
- Enabled test failures via `MueLu_Driver.exe` by returning EXIT_FAILURE when a solver exception is thrown
- Disabled DriverTpetraIfpack2LinePartitioner test due to unknown failure

The disabled test will fail in serial mode due to solver error:
```
635: MueLu_Driver: solver crashed w/ message:/home/semiller/software/trilinos/Trilinos/packages/belos/src/BelosCGIter.hpp:501:
635: 
635: Throw number = 1
635: 
635: Throw test that evaluated to true: SCT::real(alpha[0]) <= zero
635: 
635: Belos::CGIter::iterate(): non-positive value for p^H*A*p encountered!
```

I'm not sure how the test works, so I disabled it.

### CODE REVIEW

**Comment by seanofthemillers** [comment]
@cgcgcg This might overlap with some of the issues you have been fixing with Muelu. Could you give this a look? If this is new, I will file an issue to fix the test that I disabled here.

**Comment by cgcgcg** [comment]
The code fixes look good, but I'd rather understand why that test is failing instead of disabling it outright on all platforms.

**Comment by cgcgcg** [comment]
@seanofthemillers Can describe the setting in which `MueLu_DriverTpetraIfpack2LinePartitioner_MPI_4` fails?

**Comment by seanofthemillers** [comment]
Just for completeness, my configure is:
```
cmake
-GNinja \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_BUILD_TYPE=Release \
-DTPL_ENABLE_MPI=ON \
-DTrilinos_ENABLE_Fortran=OFF \
-DCMAKE_CXX_COMPILER=mpicxx \
-DCMAKE_C_COMPILER=mpicc \
-DTrilinos_ENABLE_TESTS=$ENABLE_TESTS \
-DTrilinos_ENABLE_EXAMPLES=$ENABLE_TESTS \
-DTeuchos_ENABLE_STACKED_TIMER_IN_TIME_MONITOR=ON \
-DTrilinos_ENABLE_Kokkos=ON \
-D  Kokkos_ENABLE_SERIAL=ON \
-D  KokkosKernels_ENABLE_EXPERIMENTAL=ON \
-DTrilinos_ENABLE_Tpetra=ON \
-D  Tpetra_ENABLE_MMM_Timings=ON \
-DTrilinos_ENABLE_Amesos2=ON \
-D  Amesos2_ENABLE_TIMERS=ON \
-DTrilinos_ENABLE_Belos=ON \
-D  Belos_Tpetra_Timers=ON \
-DTrilinos_ENABLE_Ifpack2=ON \
-D  Ifpack2_ENABLE_TEUCHOS_TIME_MONITOR=ON \
-DTrilinos_ENABLE_MueLu=ON \
-D  MueLu_ENABLE_Kokkos_Refactor=ON \
-DTrilinos_ENABLE_Anasazi=ON \
-DTrilinos_ENABLE_ShyLU_NodeTacho=OFF \
-DTeuchos_KOKKOS_PROFILING:BOOL=ON \
-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
-DTPL_BLAS_LIBRARIES=$THERA_OPENBLAS_PATH/lib/libopenblas.so \
-DTPL_LAPACK_LIBRARIES=$THERA_OPENBLAS_PATH/lib/libopenblas.so \
$SOURCE_DIR
```

**Comment by cgcgcg** [comment]
@seanofthemillers Have a look at #11068. We wanted to keep the option to run several input decks and not error out.

**Comment by seanofthemillers** [comment]
@cgcgcg Nice work, it looks like your PR will cover what I have here. I'll go ahead and close this PR.

**Pull request closed without merging**
