### PR TITLE
Tpetra:  fixed incorrect directory results 

### LINKED ISSUE #7223: Panzer, Tpetra: periodic bc communication has incorrect indices
## Bug Report
@trilinos/panzer 
@trilinos/tpetra 
@kddevin 

### Description
For periodic BCs, the communication to send node information on a periodic sideset is losing values. We are seeing this when we exceed 128 cores on an empire problem. Local panzer unit testing is passing. exporting TPETRA_DEBUG=1 results in the output below. Since the maps were constructed with local and global sizes (not gid lists), the indices should be handled internally. The source map being constructed does not have entries on every node since the source represents a sideset.

The code in question starts on line 279 in:

Trilinos/packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_Matcher.cpp

```
*********** Caught Exception: Begin Error Report ***********
MultiVector single-column pack kernel had 6721 out-of bounds index/ices.  Here they are: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -\
1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, \
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,\
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1\
, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -\
1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
```

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/tpetra 
## Motivation

This PR fixes incorrect distributed contiguous directory results maps that have some empty processors.

The distributed contiguous directory has an array allMinGIDs_ of the minimum GID on each processor.  Thus, a processor i owns GIDs in the range [allMinGIDs[i], allMinGIDs_[i+1]).

When a processor has no GIDs, it reports the MAX value of global ordinal type as its GID.  Thus, in such cases, allMiinGIDs_ is not monotonic.  

The search algorithm used to locate a GID in the allMinGIDs_ array did not account for the MAX values for empty processors.  It could get stuck in the wrong processor because of the MAX values.

These changes account for the MAX values, skipping over processors that do not have GIDs.

If applicable, let us know how this merge request is related to any other open
issues or pull requests:

## Related Issues

* Closes #7223 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Stakeholder Feedback

@rppawlo  Would you please test this change in your application that exhibited the problem?

## Testing

Tested on mac with clang and current Tpetra tests; all passed.
Added new unit tests that exercise typical and corner cases (Directory_Issue7332.cpp).
One unit test replicates @rppawlo 's error from #7332 when run on seven processors.
With the original code, it was difficult to replicate #7332 on Trilinos' default four processors, but searching for invalid IDs did expose similar problems.

### CODE REVIEW

**Comment by rppawlo** [comment]
Thanks @kddevin ! testing now.

**Comment by rppawlo** [comment]
@kddevin - that fixed it! Thanks!

**Comment by kddevin** [comment]
I added new tests and fixed some corner cases tonight.
@tjfulle or @jhux2 :  this PR is ready for review.

**Comment by rppawlo** [comment]
@kddevin - I'm not a tpetra dev but would be happy to review if the other team members are busy.

**Comment by kddevin** [comment]
@rppawlo A review from you would be great.  @tjfulle did look at it once already, before I removed some unused variables (and thus, cancelled his review).

**Comment by rppawlo** [comment]
Thanks for fixing this @kddevin !

**Pull request merged**
