### PR TITLE
packages/framework: Disable kokkos serial in gcc 8.3.0 build

### PR DESCRIPTION
**Pull request by e10harvey**
## Motivation

https://github.com/trilinos/Trilinos/issues/7441

## Testing

Tested locally up to configure:
```
(rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp) $ grep -i kokkos_enable_serial CMakeCache.txt 
Kokkos_ENABLE_SERIAL:BOOL=OFF
```

### CODE REVIEW

**Comment by sebrowne** [comment]
So do we normally test with serial AND OpenMP enabled when we use OpenMP?

**Review by sebrowne — DISMISSED** [review]

**Review by sebrowne — CHANGES_REQUESTED** [review]
I'd like the MiniTensor test to stay enabled, but it should pass once #11343 is merged

**Comment by e10harvey** [comment]
Waiting for #11343 before testing again

**Review by sebrowne — APPROVED** [review]

**Comment by e10harvey** [comment]
The last failure was a timeout of [Adelus_vector_random_npr1_rhs4_MPI_4](https://trilinos-cdash.sandia.gov/test/16982362). I suspect now that cuda-11 has more packages enabled than it did before the c++17 deploy, the GPU machines are being oversubscribed. CC: @sebrowne, @DaveBeCoding

**Pull request merged**
