### PR TITLE
compile fixes for superlu_dit 6.0

### PR DESCRIPTION
**Pull request by balay**
This issue comes up with trilinos build with superlu_dist-6.0 [via xsdk] - and this patch fixes this issue.

cc: @jwillenbring

### CODE REVIEW

**Comment by mhoemmen** [comment]
@trilinos/amesos @trilinos/amesos2

**Comment by mhoemmen** [comment]
Thanks! :D

**Comment by mhoemmen** [comment]
@trilinos/framework

**Comment by balay** [comment]
> From @balay:
> Note: This PR needs to go into branch origin/trilinos-release-12-14-branch

reminder to xsdk folk: @jwillenbring, @keitat . Can you get this merged in?
cc: @curfman

**Pull request merged**
