### PR TITLE
Reorganizing coarse space construction

### PR DESCRIPTION
**Pull request by searhein**
@trilinos/shylu 

## Description

This pull request introduces several new features and some changes to existing code (to maintain one single framework for all `SchwarzOperators`).

-  Introduction of a new class that allows for the construction of coarse spaces from a partition of unity on interface of the nonoverlapping domain decomposition and the null space of the operator. Therefore, the class facilitates the construction of GDSW preconditioners for all kinds of problems for which the null space of the operator is known. The new class is called `IPOUCoarseOperator` for now. In fact, many coarse spaces, such as GDSW, RGDSW, and MsFEM coarse spaces can be constructed in that way. 
-  The interface partition of unity is constructed from the partition of the interface into faces, edges, and vertices. Therefore, additional classes had to be introduced, such as `CoarseSpace`, `InterfacePartitionOfUnity`, and `LocalPartitionOfUnityBasis`.

So far, only the GDSW preconditioner can be constructed in that way. The implementation of the construction of the RGDSW coarse space will be the next step.

## Motivation and Context

This is another step for providing a `Stratimikos/Thyra` adapter for `FROSch`. In order to obtain a general framework for all kinds of model problems, it is useful/necessary to be able to build the coarse space based on the null space of the problem, which should be provided by the user.

## How Has This Been Tested?

It was simple to test the new implementation since the iteration counts have to be equal to the iteration counts of the existing implementation. This is the case for a Laplacian model problem and for linear elasticity. In order to test the linear elastic model problem, maps, vectors, and matrices exported from deal.II were used; cf. the test `TwoLevelPreconditionerInputFiles`.

The resulting iteration counts are equal to the ones obtained from the existing implementation of the GDSW preconditioner for a reasonable number of configurations (combination of the number of subdomains, subdomain size, overlap, dimension, etc.)

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. 
The FROSch documentation will be subject of a separate PR.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by srajama1** [comment]
@searhein : Apparently there is a conflict in the test file that you need to fix before merging.

**Comment by searhein** [comment]
@srajama1 The problem was just the renaming of two files. I the commands suggested by Github for a manual merge and hope that it works smoothly now.

**Comment by srajama1** [comment]
I don't know why this says pre-merge inspection is pending. @jwillenbring : Any ideas why this PR is not allowed to merge ?

**Comment by srajama1** [comment]
Ok, apparently there is some latency for the status to change in github. I will check after some time to see this can be merged.

**Comment by searhein** [comment]
@srajama1 Alright, thank you.

**Comment by searhein** [comment]
@srajama1 It seems that everything is fine now 👍 Should I merge?

**Comment by jwillenbring** [comment]
CC: @allevin 

> I don't know why this says pre-merge inspection is pending. @jwillenbring : Any ideas why this PR is not allowed to merge ?

@srajama1 The autotester status flag for the two inspection requirements is determined by the autotester itself, not directly by the GitHub review (though this is heavily involved, GitHub doesn't know the difference itself between pre test and pre merge inspection, for example). The autotester will look at each open PR every 20 minutes, provided that the autotester instance assigned to that PR is not testing another PR. Until the autotester runs again, the status flag will not be updated.

**Comment by srajama1** [comment]
@searhein : please merge. I am ok with it.

**Pull request merged**
