### PR TITLE
Prof hooks

### LINKED ISSUE #7369: Kokkos:  Control Profiling Hooks Programmatically
## Enhancement
@trilinos/kokkos 

@bathmatt, can you please cherry-pick these commits from Kokkos onto `trilinos/Trilinos:develop` and then throw up a PR?  Thanks.
* kokkos/kokkos@5492068954436aa8fb690335c415a8ce43d23620
* kokkos/kokkos@345e68a1b541bb7cf556bf566bc5c39fd04f17be
* kokkos/kokkos@66182cf85c61967f8544ad9d2c2d34307b7e93c6
* kokkos/kokkos@62b79ffa2d7009f021cad2ade370c41438ce115f
* kokkos/kokkos@bf8ea65dabe4e684790d118ff784e8c36e8b6e95
* kokkos/kokkos@a5267286a5b4f122fa4713fc258ab0634810a7d0
* EM-Plasma/Trilinos@6eb13c2d2855957c1032257bc3ef398183afbe2c (note this is from our fork of Trilinos, not Kokkos)
* kokkos/kokkos@7d9cb822f951ac1c0a78a3e8826914f88ad44905
* kokkos/kokkos@ccc4cd020255e4caeab22a7cc7f9dfda5c2aa907
* kokkos/kokkos@527f3d794589f5e389ac35ebe9fbcc08c2f717c0
* kokkos/kokkos@503946a274282248d706a2177bf63797da5b416e

### PR DESCRIPTION
**Pull request by bathmatt**
closes #7369 

@trilinos/kokkos

### CODE REVIEW

**Comment by rppawlo** [comment]
@crtrott

**Comment by crtrott** [comment]
Please change the patch version to 99 in the root CMakeLists.txt. I'd like us to at least indicate that would be off the release now, for stuff like bug reports. Generally, I feel a bit hesitant about doing this (i.e. merging things other than critical bugfixes outside of releases), but if it helps you go for it).

**Comment by alanw0** [comment]
@bathmatt I'm happy to make this change in stk if that's the correct header to include from kokkos. (And presuming it's not a new header that we don't yet have in sierra or something.)

**Comment by crtrott** [comment]
@alanw0 that file is new. The old file still exists, not 100% sure why you need to change it. The fact that Matt feels he needed to, probably means we need to change something. This was not intended to break existing code.

**Comment by rppawlo** [comment]
@crtrott - probably a dumb question - but are you in a position to do a quick 3.2 release with the required commits instead? These changes are really helpful in performance monitoring of the apps!

**Comment by crtrott** [comment]
3.2 is probably 3 to 4 weeks out before it hits Trilinos these releases are  a significant investment on our side outside of purely bug fix releases like 3.1.1. That one was maybe a day worth of a person, but a full fledged release is more like a whole week of work. And as you can see with the issue in STK, that's exactly like one of the things which would break down during a release, and then we need to cycle on what to do. We may have the same thing with other stuff already in develop.

**Comment by bathmatt** [comment]
IT didn't compile with the old file for some reason, I can try and revert that and test..

**Comment by bathmatt** [comment]
Here is the error
```
(DESKTOP)-dir-clang-opt-openmp-shared [CLANG-7.0.1]$ 362 $ ninja 
[1/90] Building CXX object packages/stk/stk_mesh/stk_mesh/base/CMakeFiles/stk_mesh_base.dir/NgpProfilingBlock.cpp.o
FAILED: packages/stk/stk_mesh/stk_mesh/base/CMakeFiles/stk_mesh_base.dir/NgpProfilingBlock.cpp.o 
/projects/sems/install/rhel7-x86_64/sems/compiler/clang/9.0.0/openmpi/1.10.1/bin/mpicxx  -Dstk_mesh_base_EXPORTS -I. -Ipackages/stk -Ipackages/stk/stk_mesh/stk_mesh/base -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_mesh -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_mesh/stk_mesh/base -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_topology -Ipackages/stk/stk_util/stk_util/diag -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/diag -Ipackages/stk/stk_util/stk_util/command_line -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util -Ipackages/stk/stk_util -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/command_line -Ipackages/stk/stk_util/stk_util/registry -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/registry -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/environment -Ipackages/stk/stk_util/stk_util/parallel -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/parallel -Ipackages/stk/stk_util/stk_util/util -I/home/mbetten/Trilinos/Trilinos/packages/stk/stk_util/stk_util/util -I/home/mbetten/Trilinos/Trilinos/packages/seacas/libraries/aprepro_lib -I/home/mbetten/Trilinos/Trilinos/packages/seacas/libraries/exodus/include -Ipackages/seacas/libraries/exodus -I/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/clang/9.0.0/openmpi/1.10.1/parallel/include -I/projects/sems/install/rhel7-x86_64/sems/tpl/hdf5/1.10.6/clang/9.0.0/openmpi/1.10.1/parallel/include -Ipackages/kokkos/core/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/core/src -Ipackages/kokkos -I/projects/sems/install/rhel7-x86_64/sems/tpl/boost/1.59.0/clang/9.0.0/base/include -Ipackages/shards/src -I/home/mbetten/Trilinos/Trilinos/packages/shards/src -Ipackages/kokkos/algorithms/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/algorithms/src -Ipackages/kokkos/containers/src -I/home/mbetten/Trilinos/Trilinos/packages/kokkos/containers/src -fopenmp=libomp -std=c++11  -O3 -DNDEBUG -fPIC -MD -MT packages/stk/stk_mesh/stk_mesh/base/CMakeFiles/stk_mesh_base.dir/NgpProfilingBlock.cpp.o -MF packages/stk/stk_mesh/stk_mesh/base/CMakeFiles/stk_mesh_base.dir/NgpProfilingBlock.cpp.o.d -o packages/stk/stk_mesh/stk_mesh/base/CMakeFiles/stk_mesh_base.dir/NgpProfilingBlock.cpp.o -c /home/mbetten/Trilinos/Trilinos/packages/stk/stk_mesh/stk_mesh/base/NgpProfilingBlock.cpp
/home/mbetten/Trilinos/Trilinos/packages/stk/stk_mesh/stk_mesh/base/NgpProfilingBlock.cpp:23:79: error: no type named 'pushRegion' in namespace 'Kokkos::Profiling'
ProfilingBlock::ProfilingBlock(const std::string & name) { Kokkos::Profiling::pushRegion(name); }
                                                           ~~~~~~~~~~~~~~~~~~~^
/home/mbetten/Trilinos/Trilinos/packages/stk/stk_mesh/stk_mesh/base/NgpProfilingBlock.cpp:31:22: error: no member named 'popRegion' in namespace 'Kokkos::Profiling'
  Kokkos::Profiling::popRegion();
  ~~~~~~~~~~~~~~~~~~~^
2 errors generated.
ninja: build stopped: subcommand failed.
(DESKTOP)-dir-clang-opt-openmp-shared [CLANG-7.0.1]$ 363 $ 

```

**Comment by bathmatt** [comment]
OK, I clicked auto merge. I will leave this up to @crtrott to hit the approve button, recommend changes or close and comment.  I can wait a month and a half for it to come in naturally, as our branch has it,

**Comment by bathmatt** [comment]
@DavidPoliakoff is there anything that would cause the include to be different for gcc 4.8.4 and 7.2?  I'm seeing the error that the stk change resolved in the auto tester

```
/scratch/trilinos/jenkins/tr-test-7/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/stk/stk_ngp/stk_ngp/NgpProfilingBlock.cpp: In constructor ‘ngp::ProfilingBlock::ProfilingBlock(const string&)’:
/scratch/trilinos/jenkins/tr-test-7/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packagesstk_ngp/stk_ngp/NgpProfilingBlock.cpp:23:60: error: ‘pushRegion’ is not a member of ‘Kokkos::Profiling’
 ProfilingBlock::ProfilingBlock(const std::string & name) { Kokkos::Profiling::pushRegion(name); }
                                                            ^
/scratch/trilinos/jenkins/tr-test-7/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/stk/stk_ngp/stk_ngp/NgpProfilingBlock.cpp: In destructor ‘ngp::ProfilingBlock::~ProfilingBlock()’:
/scratch/trilinos/jenkins/tr-test-7/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packagesstk_ngp/stk_ngp/NgpProfilingBlock.cpp:31:3: error: ‘popRegion’ is not a member of ‘Kokkos::Profiling’
   Kokkos::Profiling::popRegion();
   ^
```

**Comment by alanw0** [comment]
@bathmatt that's our fault, we have two copies of that file temporarily. We moved the stk_ngp directory into the stk_mesh directory, but haven't yet deleted the stk_ngp directory. Sorry about that! We'll delete that right away.

**Comment by DavidPoliakoff** [comment]
Hey folks, we're going to discuss a path for this. I was under the illusion people included Kokkos purely through Kokkos_Core.hpp, so in some code reorganization I changed what Kokkos_Profiling_Interface.hpp does. We'll discuss a path forward

**Comment by bathmatt** [comment]
I think we can close this, and fix our branch for Sean on ubuntu, and wait for nature to take it's course

**Comment by DavidPoliakoff** [comment]
Hey folks. Regardless of whether this gets patched into Trilinos, it should wait for us to have an answer on not breaking downstream codes. We're working on that, I hope to have an answer for you today

**Comment by DavidPoliakoff** [comment]
Okay, I'll put in a PR against Kokkos shortly. Here's what we're thinking of doing:

`Kokkos_Profiling.hpp` will be moved up out of the `impl` directory, it will be officially supported to include `Kokkos_Profiling.hpp` in your applications. What this means for Trilinos is that for Kokkos versions >3.1.1, you include `Kokkos_Profiling.hpp` (note the lack of `impl/`). For earlier versions of Kokkos you do what you've always done, and include `impl/Kokkos_Profiling_Interface.hpp`.

Does this sound acceptable to people? Sorry for the inconvenience.

**Pull request closed without merging**
