### PR TITLE
PyTrilinos: Update FinMpi4Py.cmake to support Python 3

### PR DESCRIPTION
**Pull request by kliegeois**
@trilinos/pytrilinos 

## Motivation

This is a small PR to update the FindMpi4Py.cmake to support Python 3.

### CODE REVIEW

**Review by bartlettroscoe — COMMENTED** [review]
Fine by me but I don't know who can approve PyTrilinos changes at this point.  There is no automated testing for PyTrilinos so PR testing will not catch any problems.

**Comment by kliegeois** [comment]
> Fine by me but I don't know who can approve PyTrilinos changes at this point. There is no automated testing for PyTrilinos so PR testing will not catch any problems.

@bartlettroscoe thanks for your review! I do not know who can approve those changes too.

**Review by mhoemmen — APPROVED** [review]

**Comment by mhoemmen** [comment]
@kliegeois Just checking if I was somehow still a PyTrilinos admin.  I don't think I am any more.  In any case, the changes look reasonable (I've been writing a lot of Python 3 lately), assuming that FindMpi4Py.cmake works with Python 3.

**Review by mperego — APPROVED** [review]
Looks good to me!

**Pull request merged**
