### PR TITLE
MueLu: change Region tests to use xpetra randomize to fix failing tests

### PR DESCRIPTION
**Pull request by pohm01**
@trilinos/muelu

## Motivation
#10948
The randomize() function that is currently being used (tpetra?) to initialize the starting vector is only consistent for the first 128 terms when compared between different build configurations. This is causing the region regression tests to fail.
Switching the randomize() function to be the xpetra implementation appears to fix this.

## Testing
This PR is to fix failing muelu tests.

### CODE REVIEW

**Review by jhux2 — APPROVED** [review]
@pohm01 Lgtm, thank you

**Review by GrahamBenHarper — APPROVED** [review]
I can't believe this was the solution this whole time. Thanks @pohm01 and @cgcgcg :sweat_smile:

**Comment by mayrmt** [comment]
Should this be reported to the Tpetra team, maybe in a separate issue?

**Comment by pohm01** [comment]
@cgcgcg is the tpetra implementation the default randomize() in xpetra? Or is it something else? I forget what you said.

**Comment by brian-kelley** [comment]
@mayrmt I don't think there's a bug here - ``MultiVector::randomize`` uses the Kokkos parallel random generator, so it can't be expected to give the same results from run to run.

From https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1MultiVector.html:
```
Set all values in the multivector to pseudorandom numbers.

Note
    Do not expect repeatable results. 
    Behavior of this method may or may not depend on external use of the C library routines srand() and rand(). In particular, setting the seed there may not affect it here. 
```

Although... I will say the fact that the output isn't repeatable makes the function less useful. I ran into the same issue on some Ifpack2 tests - solve iteration counts were slightly higher only on some platforms because of a different random RHS, making the test fail. The solution was to save the RHS in a file to ensure it's always the same.

**Comment by cgcgcg** [comment]
I think the Tpetra/Kokkos implementation wasn't producing the same values independent of node type. But that's not a bug, and there isn't any promise that this would be the case. The Xpetra implementation is purely serial, that's why it always gives the same values.

**Comment by brian-kelley** [comment]
@pohm01 It sounds like this fixed the regression test failures, but keep in mind ``Xpetra::MultiVector::randomize(true)`` uses std::rand, which can have different implementations on different platforms/standard libraries. At least it's reproducible on a given platform from run to run, though.

**Comment by lucbv** [comment]
We might want to discuss this at our next MueLu stand-up, in general we like the idea of being able to check that math algorithms are giving identical results from run to run, that's a classic check for correctness. We could use a non-random input vector I guess?

**Review by mayrmt — APPROVED** [review]

**Comment by brian-kelley** [comment]
@lucbv One option is to have a deterministic random fill function that uses hashes of the seed and index, instead of the Kokkos RNG state pool. KokkosKernels has the xorshift* hash functions that would work for that, and it's even the same basic RNG that Kokkos random uses so the quality of the randomness would be about the same.

**Pull request merged**
