### PR TITLE
Framework: Initial infrastructure for weaver PR build

### PR DESCRIPTION
**Pull request by fryeguy52**
@trilinos/framework

### CODE REVIEW

**Comment by jwillenbring** [comment]
@fryeguy52 Is this PR still relevant? The PR is against master, so we will minimally need to change that, but I wonder if this can just be closed at this point.

**Comment by william76** [comment]
@fryeguy52 
@trilinos/framework 

Is this PR still relevant?

**Comment by e10harvey** [comment]
No. This can be closed.

**Comment by william76** [comment]
@trilinos/framework 
Closing this out due to @e10harvey comment above.
Given how many open PR's we have right now, we should be closing these out if they're no longer necessary.

**Pull request closed without merging**
