### PR TITLE
Intrepid2: Uncomment lines for Composite Tet in Cell Tools

### PR DESCRIPTION
**Pull request by mperego**
Simply uncommented a couple of lines to enable Composite TET when building HGRAD bases. This functionality is needed by Albany.

@trilinos/intrepid2 

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ x ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mperego** [comment]
Simple fix. Tests passed.

**Comment by etphipp** [comment]
Why are you asking for my review on this?  I don't have any knowledge of the lines of code in question.

**Comment by mperego** [comment]
@etphipp The only reason I asked you to review is that initially, I got a build error related to using "auto" for mpl FAD types, which had been fixed by replacing "auto" with the right type (see commit). Probably that build error is the reason why this pull request needed to reviewed in the first place.

**Comment by etphipp** [comment]
OK.  I'm not sure why you would have gotten a compiler error with auto.  The type it deduces is likely ViewFad, but that should be OK.  Just out of curiosity, can you post the compiler error?

**Comment by mperego** [comment]
@etphipp thanks for approving the code changes! Here is the error code using 'auto' for the declarations
`[ 28%] Building CXX object packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_BasisValues2.cpp.o
In file included from /home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEM.hpp:265:0,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Cell/Intrepid2_CellTools.hpp:80,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_C0_FEM.hpp:51,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/panzer/disc-fe/src/Panzer_IntrepidBasisFactory.hpp:50,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/panzer/disc-fe/src/Panzer_PureBasis.hpp:53,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/panzer/disc-fe/src/Panzer_BasisIRLayout.hpp:54,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp:51,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/panzer/disc-fe/src/Panzer_Workset.hpp:53,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/panzer/disc-fe/src/Panzer_Traits.hpp:65,
                 from /home/mperego/Trilinos/sources/Trilinos/packages/panzer/disc-fe/src/Panzer_BasisValues2.cpp:44:
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEMDef.hpp: In instantiation of ‘static Intrepid2::ordinal_type Intrepid2::Impl::Basis_HGRAD_TET_COMP12_FEM::getLocalSubTet(pointValueType, pointValueType, pointValueType) [with pointValueType = Sacado::Fad::ViewFad<double, 0u, 0u, Sacado::Fad::DFad<double> >; Intrepid2::ordinal_type = int]’:
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEMDef.hpp:180:53:   required from ‘static void Intrepid2::Impl::Basis_HGRAD_TET_COMP12_FEM::Serial<opType>::getValues(outputValueViewType, inputPointViewType) [with outputValueViewType = Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >; inputPointViewType = Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >; Intrepid2::EOperator opType = (Intrepid2::EOperator)0u]’
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEM.hpp:162:54:   required from ‘void Intrepid2::Impl::Basis_HGRAD_TET_COMP12_FEM::Functor<outputValueViewType, inputPointViewType, opType>::operator()(Intrepid2::ordinal_type) const [with outputValueViewType = Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>; inputPointViewType = Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>; Intrepid2::EOperator opType = (Intrepid2::EOperator)0u; Intrepid2::ordinal_type = int]’
/home/mperego/Trilinos/sources/Trilinos/packages/kokkos/core/src/Kokkos_Serial.hpp:383:9:   required from ‘typename std::enable_if<std::is_same<TagType, void>::value>::type Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits ...>, Kokkos::Serial>::exec() const [with TagType = void; FunctorType = Intrepid2::Impl::Basis_HGRAD_TET_COMP12_FEM::Functor<Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>, Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>, (Intrepid2::EOperator)0u>; Traits = {Kokkos::Serial, Kokkos::Schedule<Kokkos::Static>}; typename std::enable_if<std::is_same<TagType, void>::value>::type = void]’
/home/mperego/Trilinos/sources/Trilinos/packages/kokkos/core/src/Kokkos_Serial.hpp:402:7:   required from ‘void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits ...>, Kokkos::Serial>::execute() const [with FunctorType = Intrepid2::Impl::Basis_HGRAD_TET_COMP12_FEM::Functor<Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>, Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>, (Intrepid2::EOperator)0u>; Traits = {Kokkos::Serial, Kokkos::Schedule<Kokkos::Static>}]’
/home/mperego/Trilinos/sources/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp:191:4:   required from ‘void Kokkos::parallel_for(const ExecPolicy&, const FunctorType&, const string&, typename Kokkos::Impl::enable_if<(! Kokkos::Impl::is_integral<ExecPolicy>::value)>::type*) [with ExecPolicy = Kokkos::RangePolicy<Kokkos::Serial, Kokkos::Schedule<Kokkos::Static> >; FunctorType = Intrepid2::Impl::Basis_HGRAD_TET_COMP12_FEM::Functor<Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>, Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>, (Intrepid2::EOperator)0u>; std::string = std::basic_string<char>; typename Kokkos::Impl::enable_if<(! Kokkos::Impl::is_integral<ExecPolicy>::value)>::type = void]’
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEMDef.hpp:339:78:   required from ‘static void Intrepid2::Impl::Basis_HGRAD_TET_COMP12_FEM::getValues(Kokkos::DynRankView<outputValueValueType, outputValueProperties ...>, Kokkos::DynRankView<inputPointValueType, inputPointProperties ...>, Intrepid2::EOperator) [with ExecSpaceType = Kokkos::Serial; outputValueValueType = Sacado::Fad::DFad<double>; outputValueProperties = {Kokkos::LayoutStride, Kokkos::Serial}; inputPointValueType = Sacado::Fad::DFad<double>; inputPointProperties = {Kokkos::LayoutStride, Kokkos::Serial}; Kokkos::DynRankView<outputValueValueType, outputValueProperties ...> = Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>; Kokkos::DynRankView<inputPointValueType, inputPointProperties ...> = Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>]’
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEM.hpp:230:48:   required from ‘void Intrepid2::Basis_HGRAD_TET_COMP12_FEM<ExecSpaceType, outputValueType, pointValueType>::getValues(Intrepid2::Basis_HGRAD_TET_COMP12_FEM<ExecSpaceType, outputValueType, pointValueType>::outputViewType, Intrepid2::Basis_HGRAD_TET_COMP12_FEM<ExecSpaceType, outputValueType, pointValueType>::pointViewType, Intrepid2::EOperator) const [with ExecSpaceType = Kokkos::Serial; outputValueType = Sacado::Fad::DFad<double>; pointValueType = Sacado::Fad::DFad<double>; Intrepid2::Basis_HGRAD_TET_COMP12_FEM<ExecSpaceType, outputValueType, pointValueType>::outputViewType = Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>; Intrepid2::Basis_HGRAD_TET_COMP12_FEM<ExecSpaceType, outputValueType, pointValueType>::pointViewType = Kokkos::Experimental::DynRankView<Sacado::Fad::DFad<double>, Kokkos::LayoutStride, Kokkos::Serial>]’
/home/mperego/Trilinos/sources/Trilinos/packages/panzer/disc-fe/src/Panzer_BasisValues2.cpp:1554:1:   required from here
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEMDef.hpp:68:23: error: conversion from ‘Sacado::mpl::enable_if_c<true, Sacado::Fad::Expr<Sacado::Fad::AdditionOp<Sacado::Fad::Expr<Sacado::Fad::AdditionOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpecDefault> >::type {aka Sacado::Fad::Expr<Sacado::Fad::AdditionOp<Sacado::Fad::Expr<Sacado::Fad::AdditionOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpecDefault>}’ to non-scalar type ‘const Sacado::Fad::ViewFad<double, 0u, 0u, Sacado::Fad::DFad<double> >’ requested
         xyz = x + y + z,
                       ^
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEMDef.hpp:69:18: error: conversion from ‘Sacado::Fad::Expr<Sacado::Fad::AdditionOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpecDefault>’ to non-scalar type ‘const Sacado::Fad::ViewFad<double, 0u, 0u, Sacado::Fad::DFad<double> >’ requested
         xy = x + y,
                  ^
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEMDef.hpp:70:18: error: conversion from ‘Sacado::Fad::Expr<Sacado::Fad::AdditionOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpecDefault>’ to non-scalar type ‘const Sacado::Fad::ViewFad<double, 0u, 0u, Sacado::Fad::DFad<double> >’ requested
         xz = x + z,
                  ^
/home/mperego/Trilinos/sources/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEMDef.hpp:71:18: error: conversion from ‘Sacado::Fad::Expr<Sacado::Fad::AdditionOp<Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault>, Sacado::Fad::Expr<Sacado::Fad::GeneralFad<double, Sacado::Fad::ViewStorage<double, 0u, 0u, Sacado::Fad::DFad<double> > >, Sacado::Fad::ExprSpecDefault> >, Sacado::Fad::ExprSpecDefault>’ to non-scalar type ‘const Sacado::Fad::ViewFad<double, 0u, 0u, Sacado::Fad::DFad<double> >’ requested
         yz = y + z;
                  ^
make[2]: *** [packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_BasisValues2.cpp.o] Error 1
make[1]: *** [packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/all] Error 2
make: *** [all] Error 2`

**Comment by etphipp** [comment]
OK, the problem is the subsequent call to getLocalSubTet(), which tries to create a temporary of type ViewFad, which isn't allowed.  There is a way to handle that inside of getLocalSubTet() that would work if you used auto, but it requires some meta-programming.  What you did is a fine solution.

**Comment by mperego** [comment]
I see, thanks for the explanation!

**Pull request merged**
