### PR TITLE
Intrepid2: Kokkos::Impl::is_space<> --> Kokkos::is_space<> to squash deprecated warnings

### PR DESCRIPTION
**Pull request by japlews**
@trilinos/Intrepid2

## Motivation
Fix build warnings emanating from Sierra builds. Deprecated use of Kokkos concepts.

## Stakeholder Feedback
N/A

## Testing
N/A

### CODE REVIEW

**Comment by japlews** [comment]
@jhux2 @mperego

**Comment by jhux2** [comment]
@trilinos/intrepid2

**Review by kyungjoo-kim — APPROVED** [review]

**Comment by mperego** [comment]
thanks @japlews!

**Comment by mperego** [comment]
Thanks @japlews. I'll take care of it. Unfortunately now the PR testing is down and there is nothing we can do until it's restored. The framework team is working on it. I'll keep monitoring this and make sure it is merged as soon as possible.

**Comment by ndellingwood** [comment]
@mperego @kyungjoo-kim I think this is addressed by changes in #10253 ? e.g. SHA a1b11ae6992e230167300ca680763aa9d6ace72f ? Please take those changes into consideration before merge to avoid merge conflicts

**Comment by mperego** [comment]
@ndellingwood Yes, it seems so. Thanks for pointing this out. When do you think you'll be able to merge that PR?

**Comment by ndellingwood** [comment]
@mperego been blocked with some timeout issues on the tester and the Krino test failure, but once #10429 merges hopefully everything goes through okay

**Comment by japlews** [comment]
if/when I have some time I'll try to merge develop into my branch @ndellingwood.

**Comment by mperego** [comment]
@japlews I think that the changes in #10253  will take care of the warnings in a cleaner way. So I think we can discard your changes and close this PR if you are OK with that. Hopefully #10253 will be merged very soon (today).

**Comment by japlews** [comment]
Sounds great to me! I will close this PR.

**Pull request closed without merging**
