### PR TITLE
Zoltan2:   generateFiles capability in VectorAdapter to debug MJ for MueLu performance testing

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/zoltan2 @trilinos/muelu  @pwxy 

## Description

This PR adds a function VectorAdapter::generateFiles that applications can call immediately before partitioning to create input files that @trilinos/zoltan2 can use to try to reproduce errors that the users see.

The generateFiles method sits in the VectorAdapter class and uses only VectorAdapter methods or methods in BaseAdapter.  Classes that derive from VectorAdapter (e.g., XpetraMultiVectorAdapter) do not need to implement this method.

Also, while I was at it, I cleaned up some of the unit test code and completed a "TODO" in the XpetraMultiVectorInput.cpp test.

Remaining to be done:  adding generateFiles() methods to the Graph, Mesh, and Matrix adapters.

## Motivation and Context
@trilinos/muelu reported a hang in MJ's premigration for some large performance tests.  @trilinos/zoltan2 was unable to reproduce the problem without the MueLu data.   Now a call to the input adapter's generateFiles method will create files that @trilinos/zoltan2 can use to replicate the issue.

`Zoltan2::XpetraMultiVectorAdapter<RealValuedMultiVector> adapter(coords, weights, strides);
adapter.generateFiles("kdd", *(row_map->getComm()));
`

## Related Issues
https://gitlab-ex.sandia.gov/jhu/TrilinosSolverPerformance/issues/20

## How Has This Been Tested?

Generated files are compared to the input Chaco files in the unit test of the XpetraMultiVectorAdapter.  Chaco file headers, coordinates, and vertex weights are compared.

See verifyGeneratedFiles in XpetraMultiVectorInput.cpp

Invocations of this test are run using chaco inputs with no weights, single weights, and multiple weights.  

All Zoltan2 tests pass.
Since changes only add a new method, downstream testing is not needed.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
See https://github.com/trilinos/Trilinos/issues/3276#issuecomment-462067485 for PR test failures.

**Comment by kddevin** [comment]
These problems were not caused by #3276.  
In subsequent commits:
- I removed an unneeded conversion that caused problems in CUDA.
- I changed the names of files being written to prevent collisions when tests were run concurrently.
These two changes should address the CUDA and serial test failures.
For example, now on white:
```
100% tests passed, 0 tests failed out of 108
Subproject Time Summary:
Zoltan2    = 857.82 sec*proc (108 tests)
Total Test time (real) =  54.39 sec
```
Ready to retest.

**Comment by kddevin** [comment]
@trilinos/framework @william76 @ZUUL42 
This PR appears to be blocked by an autotester problem.
The PR tester is reporting g++ compiler internal errors when compiling MueLu files.

https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4543744&filtercount=2&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and

Is there something I can do to resolve this problem and get the PR merged? Using the instructions to reproduce PR errors, I was able to successfully build Trilinos on a linux workstation; the MueLu files reporting errors in CDASH above compiled without problem in my attempt to reproduce.

According to the google, these errors arise from insufficient memory; most recommendations are for reducing concurrency in the build.  But the concurrency level is not something I can control for PR testing.

**Comment by jwillenbring** [comment]
@kddevin cc: @trilinos/framework 

I will put a retest flag on for now. If the test hits a different node or there is a lower load on the machine, this might pass. That said, we will need to revisit our settings for this build. We have had to do this before when the memory requirements change.

**Comment by kddevin** [comment]
@mhoemmen @cgcgcg @srajama1 @jhux2 @pwxy 
The PR tester finally didn't fail, and the tests have passed.
If someone does a re-review (for the changes I made two days ago), we can merge this PR and try it so we can reproduce the MJ hang that you saw in your performance testing.
Thanks for your help!

**Comment by kddevin** [comment]
Thanks, @cgcgcg !

**Pull request merged**
