### PR TITLE
Mark directories required during installation testing.

### PR DESCRIPTION
**Pull request by bavier**

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
CC: @crtrott 

It think you need to make this PR against the Kokkos repo:

* https://github.com/kokkos/kokkos

They snapshot Kokkos from that repo into Trilinos 'develop'

**Comment by bavier** [comment]
@bartlettroscoe This commit touches more than just Kokkos; Panzer, MueLu, Pike, Stokhos, ...

Do I need to split the kokkkos patches out and open a separate pull request?

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework 

Just curious, but what is the motivation for this change?  Why is this change being made?

**Comment by mhoemmen** [comment]
@bavier wrote:
> Do I need to split the kokkos patches out and open a separate pull request?

It looks like you need to apply this patch all at once, for all the packages in Trilinos, including Kokkos, in order for this to work correctly.  Is that right?  If so, what we could do is the following:

  1. Prepare a separate Kokkos patch
  2. Submit a Kokkos pull request with that patch
  3. Apply the Trilinos pull request (including changes to the Kokkos snapshot in Trilinos)

We do allow changes to the Kokkos snapshot in Trilinos, for example as emergency bug fixes, or if there's no other way to fix the issue (e.g., a backwards-incompatible TriBITS change that would require touching all the CMakeLists.txt files in all the Trilinos packages).  However, those changes would get clobbered on the next Kokkos -> Trilinos snapshot.  Kokkos changes are supposed to flow from Kokkos master to Trilinos develop via snapshot.

**Comment by bavier** [comment]
@bartlettroscoe @mhoemmen This patch is to more fully support installation testing against a system-installed Trilinos library.  The patches shouldn't need to be made to all packages at once; they are each incremental improvements.

@bartlettroscoe Many packages provide test-only headers in their `test`, or other, directory that are not installed during `make install`.  If someone were to later configure Trilinos for installation testing, e.g. with the following, to run MueLu's tests with the installed Trilinos:
```
$ tar xf trilinos-12.6.3-Source.tar.bz2 && CD trilinos-12.6.3-Source
$ mkdir build && cd build
$ cmake \
    -DTrilinos_INSTALLATION_DIR=<trilinos-install-prefix> \
    -DTrilinos_ENABLE_MueLu:BOOL=YES \
    -DMueLu_ENABLE_TESTS:BOOL=YES \
    [...] \
    ..
$ make -j
$ make test ARGS=-j
```
They would find they'd get preprocessor errors about not being able to locate the `MueLu_TestHelpers.hpp` header.

**Comment by bartlettroscoe** [comment]
@bavier, I got you.  Getting installation testing working again is a worthy goal.

Note that I had made an attempt a while back to remove the override of the raw CMake `INCLUDE_DIRECTORIES()` command that was put in and instead use the [TRIBITS_INCLUDE_DIRECTORIES()](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-include-directories).  The issue is that TriBITS should be wrapping and extending raw CMake, it should not be redefining raw CMake (IMHO).

But we can complete that refactoring later so I don't have a problem with a change like this as long as it passes all of the existing tests.

The problem is that it is currently hard to safely make changes like this because it is hard to test all of Trilinos to know if you have broken anything.  That is the goal of #482.  There are recurring CI failures even now:

*  http://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&date=2016-08-19

So if you want to do the testing and push, I say go for it.  There is not anything more for me to review that what can be seen in the diffs.  But this should only impact installation testing so I would think this is pretty safe.

**Comment by jwillenbring** [comment]
@bartlettroscoe Since this affects only installation testing, should someone just click the "Merge pull request" button?

**Comment by mhoemmen** [comment]
@jwillenbring While I personally wouldn't mind if somebody merged this, it would be nicer if we separated out the Kokkos commits.  The next Kokkos snapshot into Trilinos will clobber those, so it would be better to make them a Kokkos pull request.

**Comment by jwillenbring** [comment]
@mhoemmen Should we go ahead and merge this now? Sounds like Christian is going to take care of things on the Kokkos end.

**Comment by mhoemmen** [comment]
@jwillenbring wrote:
> Should we go ahead and merge this now?

Done :-D

**Pull request merged**
