### PR TITLE
MueLu: Workaround for #2894

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA f21bd35

### CODE REVIEW

**Comment by mhoemmen** [comment]
One of those "failure didn't show up on the Dashboard" things again :(

**Comment by csiefer2** [comment]
A bunch of stuff upstream from what I touched failed to build.  Awesome!

@trilinos/framework A little help here?

**Comment by jwillenbring** [comment]
This is another case of the clone timing out from GitHub. When that happens, nothing gets reported to the dashboard. We have discussed this, but do not know at this time how to provide more useful information. The individual tests are a black box to the autotester, and the jobs themselves cannot report to cdash when the clone fails. Hopefully the retest will pass. This has been happening a lot again this week. GitHub seems to go through spurts where we have failed clones.

**Comment by mhoemmen** [comment]
@jwillenbring Could we please turn off the bad build for PR testing until this gets resolved?  It looks like it's always the Intel build whose clone times out.

**Comment by jwillenbring** [comment]
CC: @trilinos/framework @bmpersc 

@mhoemmen I think that may just be due to the fact that that build fires off slightly after the other 2, and the pipe is clogged from GitHub. It shouldn’t be, but people are seeing their Trilinos clones time out more and more (even customers who use Trilinos for their testing). That said, I just found that on the ASCIC Jenkins build farm I could adjust the timeout. That is an option I have not previously seen or heard of. I changed the default timeout for cloning from 10 to 20 minutes. The clone most often fails when it was very far along, so I am hopeful this adjustment will help. I am also going to explore shallow clones, but I don’t want to end up with other issues. I don’t feel confident enough to do that without testing on a fork first, but increasing the timeout should be very low risk. Let’s see if the timeout makes a difference.

**Comment by mhoemmen** [comment]
@jwillenbring Do y'all seriously clone fresh each time for every PR build?  Must we kill all the pixels and start anew each time :(

**Comment by jwillenbring** [comment]
@mhoemmen 

>Do y'all seriously clone fresh each time for every PR build? Must we kill all the pixels and start anew each time :(

This may have been the case quite a while back, I cannot recall for sure, but here is a more recent comment:

 > This script can be run in a mode where the driver scripts are run from one
 Trilinos git repo and operate on another Trilinos git repo that gets
 manipulated in order to merge the "source" topic branch into the "target"
 branch.  This makes it easy to test changes to the PR scripts.  But if this
 script is run from ${PWD}/Trilinos, then these repos are one and the same
 and we get the correct behavior for PR testing.

That said, where we tend to have the failure trouble is with fetching the branch from the fork that we are testing the candidate change on, not with cloning the repo initially.

**Pull request merged**
