### PR TITLE
Warning fix in Tacho

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
## Motivation

Remove warnings which detected from applications.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
@MicheldeMessieres This fixes your issue, too.

**Comment by MicheldeMessieres** [comment]
@kyungjoo-kim I'm still seeing the issues with TPL_ENABLE_Cholmod. That causes these tests to fail for me:

	  4 - ShyLU_NodeTacho_Tacho_TestSerialDoubleTaskScheduler (SEGFAULT)
	  5 - ShyLU_NodeTacho_Tacho_TestSerialDoubleTaskSchedulerMultiple (SEGFAULT)
	  6 - ShyLU_NodeTacho_Tacho_TestSerialDoubleChaseLevTaskScheduler (SEGFAULT)
	  7 - ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexTaskScheduler (SEGFAULT)
	  8 - ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexTaskSchedulerMultiple (SEGFAULT)
	  9 - ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexChaseLevTaskScheduler (SEGFAULT)
	 14 - Amesos2_Tacho_Solver_Test (ILLEGAL)
Didn't check scheduler tests yet but the Tacho solver is failing in METIS_NodeND in Metis FreeGraph.

**Comment by kyungjoo-kim** [comment]
This does not make sense. PR test so far passed with trilinos ss library. The modification here is not to use tpl cholmod anymore in graph analysis. So, it won't mix with the TPL.

I cannot reproduce your error. 
```
[kyukim @bread] unit-test > ctest 
Test project /home/kyukim/Work/lib/trilinos/build/bread/tacho/release/packages/shylu/shylu_node/tacho/unit-test
      Start  1: ShyLU_NodeTacho_Tacho_TestUtilTaskScheduler_MPI_1
 1/15 Test  #1: ShyLU_NodeTacho_Tacho_TestUtilTaskScheduler_MPI_1 ..........................   Passed    0.31 sec
      Start  2: ShyLU_NodeTacho_Tacho_TestUtilTaskSchedulerMultiple_MPI_1
 2/15 Test  #2: ShyLU_NodeTacho_Tacho_TestUtilTaskSchedulerMultiple_MPI_1 ..................   Passed    0.20 sec
      Start  3: ShyLU_NodeTacho_Tacho_TestUtilChaseLevTaskScheduler_MPI_1
 3/15 Test  #3: ShyLU_NodeTacho_Tacho_TestUtilChaseLevTaskScheduler_MPI_1 ..................   Passed    0.20 sec
      Start  4: ShyLU_NodeTacho_Tacho_TestSerialDoubleTaskScheduler_MPI_1
 4/15 Test  #4: ShyLU_NodeTacho_Tacho_TestSerialDoubleTaskScheduler_MPI_1 ..................   Passed    0.22 sec
      Start  5: ShyLU_NodeTacho_Tacho_TestSerialDoubleTaskSchedulerMultiple_MPI_1
 5/15 Test  #5: ShyLU_NodeTacho_Tacho_TestSerialDoubleTaskSchedulerMultiple_MPI_1 ..........   Passed    0.21 sec
      Start  6: ShyLU_NodeTacho_Tacho_TestSerialDoubleChaseLevTaskScheduler_MPI_1
 6/15 Test  #6: ShyLU_NodeTacho_Tacho_TestSerialDoubleChaseLevTaskScheduler_MPI_1 ..........   Passed    0.21 sec
      Start  7: ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexTaskScheduler_MPI_1
 7/15 Test  #7: ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexTaskScheduler_MPI_1 ...........   Passed    0.23 sec
      Start  8: ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexTaskSchedulerMultiple_MPI_1
 8/15 Test  #8: ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexTaskSchedulerMultiple_MPI_1 ...   Passed    0.21 sec
      Start  9: ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexChaseLevTaskScheduler_MPI_1
 9/15 Test  #9: ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexChaseLevTaskScheduler_MPI_1 ...   Passed    0.22 sec
      Start 10: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskScheduler_MPI_1
10/15 Test #10: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskScheduler_MPI_1 ..................   Passed    0.22 sec
      Start 11: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskSchedulerMultiple_MPI_1
11/15 Test #11: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleTaskSchedulerMultiple_MPI_1 ..........   Passed    0.20 sec
      Start 12: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleChaseLevTaskScheduler_MPI_1
12/15 Test #12: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleChaseLevTaskScheduler_MPI_1 ..........   Passed    0.21 sec
      Start 13: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleComplexTaskScheduler_MPI_1
13/15 Test #13: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleComplexTaskScheduler_MPI_1 ...........   Passed    0.22 sec
      Start 14: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleComplexTaskSchedulerMultiple_MPI_1
14/15 Test #14: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleComplexTaskSchedulerMultiple_MPI_1 ...   Passed    0.22 sec
      Start 15: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleComplexChaseLevTaskScheduler_MPI_1
15/15 Test #15: ShyLU_NodeTacho_Tacho_TestOpenMPDoubleComplexChaseLevTaskScheduler_MPI_1 ...   Passed    0.22 sec

100% tests passed, 0 tests failed out of 15

Label Time Summary:
ShyLU_Node    =   3.31 sec*proc (15 tests)

Total Test time (real) =   3.33 sec
```

**Comment by MicheldeMessieres** [comment]
@kyungjoo-kim I didn't try with Trilinos SS. I just meant when I build with my own SuiteSparse I was still seeing the issues we discussed earlier. So I have these settings:
  -DCholmod_LIBRARY_DIRS="/Users/michel/Documents/SuiteSparse/lib" \
  -DCholmod_LIBRARY_NAMES="cholmod,camd,camd.2,colamd,ccolamd,suitesparseconfig" \
  -DCholmod_INCLUDE_DIRS="/Users/michel/Documents/SuiteSparse/include" \
  -DTPL_ENABLE_Cholmod=ON \
Which is causing some conflict with Tacho - this may very well just be my own setup issue. From your comment I thought you were expecting this would now be resolved. I will look into it further.

**Comment by kyungjoo-kim** [comment]
trilinos ss is required library from tacho. so, you don't have to explicitly enable the package and it will be automatically enabled when tacho is enabled. With this PR, it removes possibilities to mix with TPLs and trilinos ss.

**Comment by MicheldeMessieres** [comment]
@kyungjoo-kim My metis.h switches to my SuiteSparse version when I turn on TPL_ENABLE_Cholmod. That seems to be the source of my problems. I'll follow up with you off line as I think it's unrelated to these changes. Thanks.

**Pull request merged**
