### PR TITLE
PullRequestLinuxDriver.sh: add a retry loop for the github fetch

### PR DESCRIPTION
**Pull request by prwolfe**
We are seeing more issues when communicating to github
so I am adding a retry loop.

@trilinos/framework 

## Description
This adds a loop to retry fetching the source branch from GitHub. We see this failure infrequently.

## How Has This Been Tested?
This was tested by setting up an autotester that looked at PR's into this branch on my fork and creating a whitespace commit on a throw-away branch. The resulting PR can test the driver script as the target branch.

### CODE REVIEW

**Comment by prwolfe** [comment]
@jwillenbring - I added the sleep you requested.

Thanks!

**Comment by prwolfe** [comment]
Jim,

The shell interprets $((... )) as a directive to do the math. I could use 'let $I*20` instead but this is what I'm used to.

**Comment by jwillenbring** [comment]
This PR is crashing the autotester due to a unicode issue. I am going to modify the comments above to fix this because  a PR is not being tested due to this issue. These are the two snippets I will modify:

$Openparen) necessary on the sleep command? I didn’t try it, but (Dollari*20Closeparen 

$OpenParen(Dotdotdot )Closeparen as a directive to do the math. I could use 'let $I*20'

**Comment by prwolfe** [comment]
Well that's odd.

**Comment by jwillenbring** [comment]
Temporarily closing

**Comment by jwillenbring** [comment]
@allevin 

> I saw this happening yesterday, and tried a quick and dirty fix, but no go. I will investigate this morning.

Thanks. Go ahead and open this if you have something to test. I left it closed for now so it doesn't interfere with testing other PRs.

**Pull request merged**
