### PR TITLE
PyTrilinos: Add a cmake define for HAVE_TPETRA_INST_INT_LONG_LONG.

### LINKED ISSUE #10362: PyTrilinos: build failure
@trilinos/PyTrilinos

I previously had a successful build, using a certain build script and am trying to update the build (develop branch). More specifically this is info from my TrilinosRepoVersion.txt file

```
*** Base Git Repo: Trilinos
d360fc6 [Tue Mar 22 17:00:28 2022 -0700]
Merge pull request #10344 from Sbte/develop
```

During the build I see warnings such as 
```
[ 76%] Swig source /ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/packages/PyTrilinos/src/EpetraExt.i
/ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/builds/blake_Albany/packages/PyTrilinos/src/LOCA.AbstractPYTHON_wrap.cpp(4606): warning #576: handler is potentially masked by previous handler for type "Swig::DirectorException &"
      catch (Swig::DirectorMethodException & e)
             ^
```

```
[ 76%] Linking CXX shared module PyTrilinos/_Galeri.so
In file included from /ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/packages/PyTrilinos/src/PyTrilinos_Tpetra_Util.hpp(57),
                 from /ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/packages/PyTrilinos/src/PyTrilinos_Tpetra_Headers.hpp(51),
                 from /ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/builds/blake_Albany/packages/PyTrilinos/src/TpetraPYTHON_wrap.cpp(3702):
/ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/builds/blake_Albany/packages/PyTrilinos/src/PyTrilinos_config.h(127): warning #47: incompatible redefinition of macro "PYTRILINOS_GLOBAL_ORD" (declared at line 129)
  #define PYTRILINOS_GLOBAL_ORD long long
```

I do not recall seeing this warning previously and it seems related to the recent merge [10344](https://github.com/trilinos/Trilinos/pull/10344/commits/093845011b4184bd4e7cf8e1b8aadb8895bc8f81).

```
Scanning dependencies of target PyTrilinos_LOCA_Hopf
/ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/builds/blake_Albany/packages/PyTrilinos/src/TpetraPYTHON_wrap.cpp(5547): error: no instance of function template "PyTrilinos::convertToDistArray" matches the argument list
            argument types are: (Tpetra::MultiVector<int, int, int, DefaultNodeType>)
      return PyTrilinos::convertToDistArray(*self);
             ^
/ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/packages/PyTrilinos/src/PyTrilinos_Tpetra_Util.hpp(104): note: this candidate was rejected because at least one template argument could not be deduced
  convertToDistArray(const Tpetra::MultiVector< Scalar,
```

```
[ 76%] Building CXX object packages/PyTrilinos/src/CMakeFiles/PyTrilinos_LOCA_Hopf.dir/LOCA.HopfPYTHON_wrap.cpp.o
/ascldap/users/thartla/trilinos/Trilinos_new/Trilinos/builds/blake_Albany/packages/PyTrilinos/src/TpetraPYTHON_wrap.cpp(12548): error: a value of type "Teuchos::RCP<Tpetra::MultiVector<int, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::Serial::memory_space>>> *" cannot be assigned to an entity of type "Teuchos::RCP<Tpetra::MultiVector<int, int, int, DefaultNodeType>> *"
      smartarg1 = PyTrilinos::convertPythonToTpetraMultiVector< int >(obj0, &newmem);
```

### PR DESCRIPTION
**Pull request by Sbte**
@trilinos/pytrilinos

## Related Issues

Fixes #10362
Closes #10363

## Testing

I tested the build with the configuration described in #10362 as well as the configuration that exposed the original issue.

### CODE REVIEW

**Comment by cgcgcg** [comment]
@trilinos/pytrilinos @pyt-viper

**Review by pyt-viper — APPROVED** [review]
These changes look fine to me.

**Comment by mperego** [comment]
@Sbte @cgcgcg can we merge this?

**Comment by Sbte** [comment]
@mperego If it's up to me, then sure, but I don't think it is, and I also think there's nothing I could do about it.

**Comment by mperego** [comment]
OK, just wanted to make sure you were OK with that before merging it. Thank you for the fix.

**Pull request merged**
