### PR TITLE
muelu: Fix multiple symbol definition encountered in Cuda 11.6 RDC build

### PR DESCRIPTION
**Pull request by vbrunini**
@trilinos/muelu

This resolved an error I encountered while trying to test builds of SIERRA on ATS-2 with Cuda 11.6

### CODE REVIEW

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by vbrunini** [comment]
@jhux2 Do you need to do something to get the PR tester to run?

**Comment by jhux2** [comment]
@vbrunini I thought my approval would be sufficient, but maybe not.

**Comment by ccober6** [comment]
@jwillenbring is working through the PRs in a metered fashion, as opening up the gates to all the waiting PRs would overload the system.  So please be patience as we work back to a more normal status.

**Comment by jhux2** [comment]
> @jwillenbring is working through the PRs in a metered fashion, as opening up the gates to all the waiting PRs would overload the system. So please be patience as we work back to a more normal status.

@ccober6 I forgot to add the pre-test inspected label, which is required to kick off the AT.

**Pull request merged**
