### PR TITLE
MueLu: Missing header fixes

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA 1a98b5b

### CODE REVIEW

**Comment by csiefer2** [comment]
@aprokop For future reference can you please delete my branches when you merge?

**Comment by aprokop** [comment]
@csiefer2 I don't think I can, I would probably need to be a collaborator on your fork to do that.

**Comment by csiefer2** [comment]
@aprokop If I were using a fork, this would be true, but I'm just branching on trilinos/Trilinos...

**Comment by aprokop** [comment]
@csiefer2 Mea culpa. Will do do this next time.

**Comment by csiefer2** [comment]
#andnowyouknow

**Pull request merged**
