### PR TITLE
Tpetra: Removing the incorrect ETI_DEVICES

### PR DESCRIPTION
**Pull request by csiefer2**
We don't use them and they're not consistent with the ETI_NODES

Issue: #12106
Tests: n/a
Stakeholder feedback: n/a

### CODE REVIEW

**Review by jhux2 — APPROVED** [review]
lgtm

**Review by jhux2 — CHANGES_REQUESTED** [review]
What about https://github.com/trilinos/Trilinos/blob/67e9032a6d0524d57e6e6bad55b2550a062f0c0a/packages/tpetra/core/guide/src/Obtaining/Building.rst?plain=1#L107?

**Comment by sebrowne** [comment]
@csiefer2 checked it out, looks like one of those builds lost a connection to GitHub when it attempted to check out Trilinos.  That same one already passed this time.  Probably a random connection hiccup.

**Review by jhux2 — APPROVED** [review]
Consider me happy.

**Pull request merged**
