### PR TITLE
Panzer: Fixing integration values side qp construction

### PR DESCRIPTION
**Pull request by eric-c-cyr**
These were not correctly being reordered. This change
fixes this.

1) Adding reorder function to utilities

   This function automates the reordering of an array by a specified vector

2) side points in IV2, handling ref_ip_coords in a consistent way

3)  Extracting sorting function in IntegrationValues

    Adding unit test for 1d sorting

4) Core, fixing globbing issue

   Toucing CMakeLists.txt

5) Adding 2d coordinates test to IV2

   This is a copy of the 1D one (but in 2D). It excercises the periodic case

6) Updating unit tests associated with sorting face quadrature rules

7) Adding swap function for quadrature points

   Incorporated into the reordering routines and added unit tests

@trilinos/<teamName>

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by eric-c-cyr** [comment]
I've built and tested at this point, this is ready for merge whenever.

**Comment by rppawlo** [comment]
Relaunched this PR in autotester. Not sure what happened - it failed on one platform with every test not being able to find the executable.

**Comment by eric-c-cyr** [comment]
@bartlettroscoe I'm struggling with the 4.8.4 build. CDash seems to be telling me the Panzer_version test (which is an always pass sort) outputs

```
--------------------------------------------------------------------------
mpiexec was unable to launch the specified application as it could not find an executable:

Executable: --bind-to
Node: ascic143

while attempting to start process rank 0.
--------------------------------------------------------------------------
```

**Comment by rppawlo** [comment]
@allevin @jwillenbring - can one of you help with Eric's question?

**Comment by bartlettroscoe** [comment]
@eric-c-cyr said:

> @bartlettroscoe I'm struggling with the 4.8.4 build. CDash seems to be telling me the Panzer_version test (which is an always pass sort) outputs

See https://github.com/trilinos/Trilinos/pull/2964#issuecomment-398373595.

**Comment by rppawlo** [comment]
All the PRs seem to now be broken. How did that change get through?

**Pull request merged**
