### PR TITLE
Check and abort if existing subdirs are not git repos (#10766)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Should address #10766.  See git commit log for detail.

## How was this tested?

I tested this by first creating the non-git subdir:

```
$ cd Trilinos/

$ mkdir packages/framework/srn-ini-files
```

Then I ran:

```
$ ./packages/framework/get_dependencies.sh --srn

STATUS: GenConfig: Fetching remote repo

...
      
HEAD is now at 924a08a Merge branch 'del-gen-symlinks' into 'master'

STATUS: GenConfig: Update submodules
Submodule path 'deps/ConfigParserEnhanced': checked out 'a8fb13a54e567eb851d5b43da2c9b783a68c509e'
Submodule path 'deps/DetermineSystem': checked out 'cb425283a77d1af4b555a3e118848a8abcf271ec'
Submodule path 'deps/KeywordParser': checked out 'ce456627c38eac6c8a08d3558ca88f01a348d827'
Submodule path 'deps/LoadEnv': checked out '0b36cff47e3c5442e7a0cbf79d5d8a0bc2788f04'
Submodule path 'deps/LoadEnv/deps/ConfigParserEnhanced': checked out 'a8fb13a54e567eb851d5b43da2c9b783a68c509e'
Submodule path 'deps/LoadEnv/deps/DetermineSystem': checked out 'cb425283a77d1af4b555a3e118848a8abcf271ec'
Submodule path 'deps/LoadEnv/deps/KeywordParser': checked out 'ce456627c38eac6c8a08d3558ca88f01a348d827'
Submodule path 'deps/LoadEnv/deps/SetEnvironment': checked out '9ab6a4c0f1b8f18f99902871f77c3664803038dc'
Submodule path 'deps/SetEnvironment': checked out '9ab6a4c0f1b8f18f99902871f77c3664803038dc'
Submodule path 'deps/SetProgramOptions': checked out '5532fb07315a11d1cfbee14dd8671ac7c6d8dd5f'

STATUS: srn-ini-files: Fetching remote repo
ERROR: The directrory /ascldap/users/rabartl/Trilinos.base/Trilinos/packages/framework/srn-ini-files is not a git repository!
  ==> Please delete /ascldap/users/rabartl/Trilinos.base/Trilinos/packages/framework/srn-ini-files and run again
```

I then remove that directory and ran it again with:

```
$ cd Trilinos/

$ rm -rf packages/framework/srn-ini-files

$ ./packages/framework/get_dependencies.sh --srn

STATUS: GenConfig: Fetching remote repo
...
HEAD is now at 924a08a Merge branch 'del-gen-symlinks' into 'master'

STATUS: GenConfig: Update submodules
Submodule path 'deps/ConfigParserEnhanced': checked out 'a8fb13a54e567eb851d5b43da2c9b783a68c509e'
Submodule path 'deps/DetermineSystem': checked out 'cb425283a77d1af4b555a3e118848a8abcf271ec'
Submodule path 'deps/KeywordParser': checked out 'ce456627c38eac6c8a08d3558ca88f01a348d827'
Submodule path 'deps/LoadEnv': checked out '0b36cff47e3c5442e7a0cbf79d5d8a0bc2788f04'
Submodule path 'deps/LoadEnv/deps/ConfigParserEnhanced': checked out 'a8fb13a54e567eb851d5b43da2c9b783a68c509e'
Submodule path 'deps/LoadEnv/deps/DetermineSystem': checked out 'cb425283a77d1af4b555a3e118848a8abcf271ec'
Submodule path 'deps/LoadEnv/deps/KeywordParser': checked out 'ce456627c38eac6c8a08d3558ca88f01a348d827'
Submodule path 'deps/LoadEnv/deps/SetEnvironment': checked out '9ab6a4c0f1b8f18f99902871f77c3664803038dc'
Submodule path 'deps/SetEnvironment': checked out '9ab6a4c0f1b8f18f99902871f77c3664803038dc'
Submodule path 'deps/SetProgramOptions': checked out '5532fb07315a11d1cfbee14dd8671ac7c6d8dd5f'

STATUS: srn-ini-files: Cloning from 'git@cee-gitlab.sandia.gov:trilinos-project/srn-ini-files.git'
Cloning into 'srn-ini-files'...
...

STATUS: srn-ini-files: Merging tip of remote tracking branch
Already up to date.

STATUS: Link files from srn-ini-files

INFO: You selected the following LoadEnv ini files:

lrwxrwxrwx 1 rabartl rabartl 119 Jul 19 18:01 GenConfig/deps/LoadEnv/ini_files/environment-specs.ini -> /ascldap/users/rabartl/Trilinos.base/Trilinos/packages/framework/srn-ini-files/trilinos/framework/environment-specs.ini
lrwxrwxrwx 1 rabartl rabartl 93 Jul 19 18:01 GenConfig/deps/LoadEnv/ini_files/supported-envs.ini -> /ascldap/users/rabartl/Trilinos.base/Trilinos/packages/framework/ini-files/supported-envs.ini
lrwxrwxrwx 1 rabartl rabartl 119 Jul 19 18:01 GenConfig/deps/LoadEnv/ini_files/supported-systems.ini -> /ascldap/users/rabartl/Trilinos.base/Trilinos/packages/framework/srn-ini-files/trilinos/framework/supported-systems.ini

INFO: You selected the following GenConfig ini files:

lrwxrwxrwx 1 rabartl rabartl 91 Jul 19 18:01 GenConfig/ini_files/config-specs.ini -> /ascldap/users/rabartl/Trilinos.base/Trilinos/packages/framework/ini-files/config-specs.ini
lrwxrwxrwx 1 rabartl rabartl 101 Jul 19 18:01 GenConfig/ini_files/supported-config-flags.ini -> /ascldap/users/rabartl/Trilinos.base/Trilinos/packages/framework/ini-files/supported-config-flags.ini

INFO: If these symlinks do not point to the desired ini files, please re-run:

    ./packages/framework/get_dependencies.sh [--son|--srn]
```

And I ran it again:

```
$ ./packages/framework/get_dependencies.sh --srn

...

STATUS: srn-ini-files: Fetching remote repo
...

STATUS: srn-ini-files: Merging tip of remote tracking branch
Already up to date.

...
```

And I was able to run:

```
$ cat load-env.sh
TRILINOS_SRC=${HOME}/Trilinos.base/Trilinos
source ${TRILINOS_SRC}/packages/framework/GenConfig/gen-config.sh \
  rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables \
  --force \
  ${TRILINOS_SRC}

$ . load-env.sh
Setting system to 'rhel7' based on specification in build name 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Matched environment name 'sems-clang-10.0.0-openmpi-1.10.1-serial' in build name 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.
Matched complete configuration 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'
  for build name 'rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'.


```

without it crashing like in #10766.

### CODE REVIEW

**Review by e10harvey — APPROVED** [review]
Thanks, @bartlettroscoe !

**Comment by bartlettroscoe** [comment]
Wow, GitHub has become more intelligent!  I merged in the 'develop' branch and resolved and conflict and pushed the merge commit https://github.com/trilinos/Trilinos/pull/10778/commits/6765daf6cf590afbccbf79fd009ffc755dab9a23 and GitHub did not wipe out the review!  (That seems a little risky since the merge commit could contain arbitrary change that don't just come from a simple merging of the two branches.)

**Comment by bartlettroscoe** [comment]
FYI: The build `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables` did not even show up on CDash [here](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-10778-test&field2=buildstarttime&compare2=84&value2=NOW) but all of the other builds passed.

Hello @jwillenbring, as all of the other builds passed and given the changes in the PR that are really not system dependent, can we just manually merge this PR?  Otherwise, adding `AT: RETEST` is just going to be using up testing resources that can be better used to test the backlog of PRs waiting to be tested (as shown [here](https://github.com/trilinos/Trilinos/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3A%22AT%3A+RETEST%22) currently that are 9 PR with the `AT: RETEST` label waiting to be tested).

**Comment by bartlettroscoe** [comment]
@e10harvey reported in [TRILINOSHD-136](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-136) just now that he disabled the cuda-11 PR build.  Not clear if if should put `AT: RETEST` on this PR and rerun all of the remaining builds from scratch that already passed or of someone on the framework team should just manually merge this PR.

**Comment by bartlettroscoe** [comment]
The word was to put "AT: RETEST" on and retest everything (and cross fingers there is not network failure this time).

**Comment by jwillenbring** [comment]
Having reviewed this PR and in consultation with @bartlettroscoe, for one run of the autotester 2 days ago, all the test s passed except the CUDA 11 build. That build subsequently passed, but reported a final state of failure. The CDash link for the CUDA 11 build that passed is here: https://trilinos-cdash.sandia.gov/build/335603

For these reasons, this PR is a good candidate for a force push. The builds have all passed, just not at the same time, and the failures that occurred were outside of the scope of the changes in the PR itself. It does not make sense for this PR to clog up the PR swim lanes when things return to normal since it has passed all the tests already.

**Comment by bartlettroscoe** [comment]
Thanks @jwillenbring!

**Pull request merged**
