### PR TITLE
Zoltan2: Update License and Copyright

### PR DESCRIPTION
**Pull request by ccober6**
Update the License and Copyright files to

 * Reflect NTESS and new contract
 * Utilize SPDX identifiers within files
 * Make copyright and license files consistent across Trilinos packages (i.e., LICENSE and COPYRIGHT)

@trilinos/zoltan2

### CODE REVIEW

**Comment by ccober6** [comment]
@egboman , can I get your review on this?  If not can I get someone else to review it?

**Review by egboman — APPROVED** [review]
Thanks, looks good. (Sorry, was on vacation.)

**Comment by ccober6** [comment]
No problem.  Thanks for the review!

**Comment by ccober6** [comment]
@sebrowne and @trilinos/framework. This is consistently failing for gcc10-openmpi416 and not posting to CDash.  There may be something wrong here.  I will retest again.

**Pull request merged**
