### PR TITLE
Stk snapshot as of 20200603

### PR DESCRIPTION
**Pull request by alanw0**
@trilinos/<teamName>

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
CC: @kddevin 

@alanw0, the Intel-17 errors shown [here](https://testing.sandia.gov/cdash/viewConfigure.php?buildid=7191846) shows:

```
CMake Error at cmake/RepositoryDependenciesSetup.cmake:64 (MESSAGE):
  STKBalance requires long or long long global indices, but Trilinos is using
  int indices (likely via Tpetra_INST_INT_INT or Tpetra_INST_INT_UNSIGNED).
  Disable STKBalance or specify Tpetra_INST_INT_LONG_LONG.
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:967 (INCLUDE)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1733 (TRIBITS_READ_ALL_PACKAGE_DEPENDENCIES)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:165 (TRIBITS_READ_PACKAGES_PROCESS_DEPENDENCIES_WRITE_XML)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)
```

Looks like this is due to:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/PullRequestLinuxIntelTestingSettings.cmake#L23

which is:

```
set (Tpetra_INST_INT_INT ON CACHE BOOL "INST_INT_INT ON")
```

Looks like this got set in commit 1c30904f9e1ed61bbc3261fda5569b11b3d9fb77 to protect usage by Charon?

My suggestion would be to add:

```
set (Trilinos_ENABLE_STKBalance OFF CACHE BOOL 
  "Hard disabled since Tpetra_INST_INT_INT=ON in this build" FORCE)
```

to the file `Trilinos/cmake/std/PullRequestLinuxIntelTestingSettings.cmake`.  I would just add a commit for that in this PR and then you should be good to go.

Let me know if you have any other questions about this.

**Comment by alanw0** [comment]
@bartlettroscoe Thanks for the diagnosis and suggestion for moving forward. Hopefully I am misunderstanding the situation but it seems like you're saying that Charon's activation of int testing necesitates the complete disabling of stk-balance testing for this build. Does this system really force that kind of trade-off?

**Comment by bartlettroscoe** [comment]
CC: @kddevin, @jwillenbring, @ZUUL42 

@alanw0,

**NOTE: Prior to the merge of PR #7414, STKBalance was not getting tested in any Trilinos PR builds!!!!!**  Please keep that in mind in the below discussion for context.

> Hopefully I am misunderstanding the situation but it seems like you're saying that Charon's activation of int testing necesitates the complete disabling of stk-balance testing for this build. Does this system really force that kind of trade-off?

That is the quickest fix I could think of given the logic at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/RepositoryDependenciesSetup.cmake#L15

which is:

```
#########################################################################
# STKBalance does not work with GO=INT or GO=UNSIGNED
# Note and disable it if it was set as a dependence of STK
# Error out if it was explicitly requested by user

SET(KDD_INT_INT OFF)     # Current default
SET(KDD_INT_UNSIGNED OFF)  # Current default
SET(KDD_INT_LONG OFF)      # Current default
SET(KDD_INT_LONG_LONG ON)  # Current default

IF (NOT ("${Tpetra_INST_INT_INT}" STREQUAL ""))
  SET(KDD_INT_INT ${Tpetra_INST_INT_INT})
  if (${KDD_INT_INT})
    SET(KDD_INT_LONG_LONG OFF)
  ENDIF()
ENDIF()

IF(NOT ("${Tpetra_INST_INT_UNSIGNED}" STREQUAL ""))
  SET(KDD_INT_UNSIGNED ${Tpetra_INST_INT_UNSIGNED})
  if (${KDD_INT_UNSIGNED})
    SET(KDD_INT_LONG_LONG OFF)
  ENDIF()
ENDIF()

IF(NOT ("${Tpetra_INST_INT_LONG}" STREQUAL ""))
  SET(KDD_INT_LONG ${Tpetra_INST_INT_LONG})
  if (${KDD_INT_LONG})
    SET(KDD_INT_LONG_LONG OFF)
  ENDIF()
ENDIF()

IF(NOT ("${Tpetra_INST_INT_LONG_LONG}" STREQUAL ""))
  SET(KDD_INT_LONG_LONG ${Tpetra_INST_INT_LONG_LONG})
ENDIF()

IF ((NOT ${KDD_INT_LONG}) AND (NOT ${KDD_INT_LONG_LONG}))
  IF ("${${PROJECT_NAME}_ENABLE_STKBalance}" STREQUAL "")
    # STKBalance may be enabled but only implicitly (as a dependence of STK);
    # give a message but turn off STKBalance support
    MESSAGE("NOTE:  int global indices are enabled in Trilinos. "
            "Because STKBalance requires long or long long "
            "global indices, STKBalance will be disabled.  "
            "To make this warning go away, do not request "
            "int global indices in Trilinos (that is,  do not "
            "set Tpetra_INST_INT_INT=ON or "
            "Tpetra_INST_INT_UNSIGNED=ON)." )
    SET(${PROJECT_NAME}_ENABLE_STKBalance OFF)
  ELSEIF (${PROJECT_NAME}_ENABLE_STKBalance)
    # STKBalance was explicitly enabled by the user, so error out
    MESSAGE(FATAL_ERROR 
            "STKBalance requires long or long long global indices, "
            "but Trilinos is using int indices "
            "(likely via Tpetra_INST_INT_INT or Tpetra_INST_INT_UNSIGNED).  "
            "Disable STKBalance or specify Tpetra_INST_INT_LONG_LONG.")
  ENDIF()
ENDIF()
```

It looks like that code was written by @kddevin in the commit 0e8c093  (with my guidance if I remember right) as shown by:

```
$ git log-short -STpetra_INST_INT_INT --grep=stk -- cmake/RepositoryDependenciesSetup.cmake
0e8c093 "stk:  changes that check for appropriate global ordinal type during configure rather than waiting to flag problem during compilation. #5541"
Author: K. Devine <kddevin@sandia.gov>
Date:   Tue Oct 15 17:00:48 2019 -0600 (8 months ago)
```

So I think you need to talk with @kddevin who created the commit 0e8c093c276332d396c5a46de2c0c62ff2609405 and @ZUUL42 who created commit 1c30904f9e1ed61bbc3261fda5569b11b3d9fb77 that sets:

```
set (Tpetra_INST_INT_INT ON CACHE BOOL "INST_INT_INT ON")
```

Those make it impossible for this Intel 17 build to allow the enable of STKBalance.

Here are all of the options to that could be used to resolve this:

* **Option-1:** Remove `Tpetra_INST_INT_INT=ON` by reverting commit 1c30904f9e1ed61bbc3261fda5569b11b3d9fb77 
  * **Pro:** STKBalance will get tested in intel-17 builds protecting customers like ATDM.
  * **Con:** Charon usage is not being protected
* **Option-2:** Disable STKBalance in this Intel-17 PR build either as I suggest [above](https://github.com/trilinos/Trilinos/pull/7486#issuecomment-639970350) or change the logic in `Trilinos/cmake/RepositoryDependenciesSetup.cmake` to `FORCE` disable it.
  * **Pro:** Charon usage will be protected.
  * **Con:** STKBalance will get no intel testing which is not good for ATDM or other customers that use STKBalance with Intel compilers
* **Option-3:** Refactor STKBalance to work with `GO=int` so it can be enabled in this intel-17 PR build.
  * **Pro:** All customers  (ATDM, Charon, etc.) will be protected as STKBalance will get tested in all PR builds
  * **Con:** Charon developers will need to do some work.
* **Option-4:** Get Charon to switch to using Trilinos with 64bit GO and remove `Tpetra_INST_INT_INT=ON` by reverting commit 1c30904f9e1ed61bbc3261fda5569b11b3d9fb77.
  * **Pro:** All customers  (ATDM, Charon, etc.) will be protected as STKBalance will get tested in all PR builds
  * **Con:** STK developers will need to do some work.

Note, this is not a TriBITS issue.  TriBITS has nothing to do with this.  This is a Trilinos and STK issue.    Therefore, I really don't need to be part of this conversation (but I am happy to provide my analysis and advise if it is deemed helpful).

**Comment by bartlettroscoe** [comment]
@alanw0, @kddevin, @ZUUL42, @jwillenbring,

Actually, this has nothing to do with the changes in PR logic with the merge of PR #7414 on 5/26/2020.  That is because STKBalance was already listed as a Primary Tested (PT) package so it was getting tested in all of the PR builds prior to PR #7444 

Instead, this PR #7486 is the first time a major STK snapshot update since the commit https://github.com/trilinos/Trilinos/commit/f3c00a7cfa3d4608345836936cb03b4d32098f82 on 4/1/2020 that updated STKBalance source code:

```
f3c00a7 "Snapshot of stk as of 4/01/2020"
Author: Alan Williams <william@sandia.gov>
Date:   Wed Apr 1 12:23:19 2020 -0600 (9 weeks ago)

   0.0% packages/stk/cmake/
   3.5% packages/stk/stk_balance/stk_balance/internal/
   1.0% packages/stk/stk_balance/stk_balance/
   1.5% packages/stk/stk_io/stk_io/
   4.6% packages/stk/stk_mesh/stk_mesh/base/
  15.1% packages/stk/stk_mesh/stk_mesh/baseImpl/
   0.4% packages/stk/stk_performance_tests/stk_mesh/
  17.9% packages/stk/stk_simd/stk_simd/disimd/
   0.7% packages/stk/stk_topology/stk_topology/topology_detail/
   0.1% packages/stk/stk_transfer/stk_transfer/copy_by_id/
  42.9% packages/stk/stk_unit_tests/stk_balance/
   9.5% packages/stk/stk_unit_tests/stk_mesh/ngp/
   0.2% packages/stk/stk_unit_tests/stk_ngp/
   0.9% packages/stk/stk_unit_tests/stk_util/diag/
   0.9% packages/stk/stk_util/stk_util/
   0.0% packages/stk/
```

After that STK update, @ZUUL42 merged commit 1c30904f9e1ed61bbc3261fda5569b11b3d9fb77 PR #7235 merged to 'develop' on 4/22/2020.  The motivation for that is in Issue #6570 (which was posted by @kddevin).  Therefore, I think you and @kddevin can work this out together.

**Comment by alanw0** [comment]
@bartlettroscoe I don't want to start a war here... I remember when Karen did that commit; STKBalance used to insist on long long, and she helped to improve the situation so that STKBalance would accept either long or long long, depending on what Tpetra/Zoltan2 is configured with, which was much better than our previous run-time failure. But this new development of turning STKBalaance off if int is activated took me by surprise. But that's ok.

In any case, your option-3 does seem to be the best choice, but it may take us a little time due to other priorities and so forth.

**Comment by alanw0** [comment]
I think I will close this PR and put in the PullRequestLinuxIntelTestingSettings.cmake change as a separate thing, and then try again with a stk update.

**Comment by bartlettroscoe** [comment]
> I don't want to start a war here

@alanw0, I did not mean to imply that anything improper was being done here.  Everyone had good intentions here but the impact of of STKBalance for commit https://github.com/trilinos/Trilinos/commit/1c30904f9e1ed61bbc3261fda5569b11b3d9fb77 was just  not considered.  (Trilinos configuration is so complex because of all the little issues like this that no one can remember all of this stuff.)

**Comment by alanw0** [comment]
@bartlettroscoe Yes I understand, we have our share of dusty corners in our code.

**Comment by rppawlo** [comment]
Starting next week I'll be working on getting Charon switched over to Tpetra and using the LO/GO defined by Tpetra. Hopefully that will help fix this issue. This work will take some time as their entire test suite is built on the epetra stack and there are capabilities missing in the Tpetra stack (not the tpetra package per se, but certain BCs are hard coded to epetra data structures at the moment). cc'ing the Charon team @glhenni

**Pull request closed without merging**
