### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by sebrowne**
@trilinos/<teamName>

### CODE REVIEW

**Comment by sebrowne** [comment]
Closed in favor of https://github.com/sebrowne/Trilinos/pull/2 for prototyping

**Comment by ccober6** [comment]
@sebrowne Here is an example of a closed PR.  It looks like deleting it may lose the branch.  Thoughts?

**Comment by sebrowne** [comment]
Yes, that does seem to be the implication it's giving in the message next to the button.  Best leave them around until we decide on whether "main repo" branches will be allowed going forwards and then socialize that decision, in my opinion.

**Comment by ccober6** [comment]
[like]  Ober, Curtis C. reacted to your message:
________________________________
From: Samuel Browne ***@***.***>
Sent: Wednesday, March 6, 2024 5:32:59 PM
To: trilinos/Trilinos ***@***.***>
Cc: Ober, Curtis C. ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [trilinos/Trilinos] Create codeql.yml (PR #11995)


Yes, that does seem to be the implication it's giving in the message next to the button. Best leave them around until we decide on whether "main repo" branches will be allowed going forwards and then socialize that decision, in my opinion.

**Pull request closed without merging**
