### PR TITLE
MueLu RefMaxwell fixes

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation

- Dump to file as soon as object has been created. This makes it easier to debug setup issues.
- Nuke edge BCs in D0 after creating (2,2) hierarchy
- Allow iterating more than 1 it on sub-hierarchies.
- Fix ETI off build.
- Display edge length stats in verbose output.

### CODE REVIEW

**Comment by brian-kelley** [comment]
@cgcgcg Does this fix this test failure in PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_Epetra_MPI_4? It's showing up in a GO=int build in the tpetra-remove-deprecated branch.
 
```
******* WARNING *******
Level::Set: unable to store "RAP reuse data" generated by factory RAPFactory[15](0x800d7d0) on level 1, as it has not been requested and no keep flags were set for it
RefMaxwell (2,2): Build (MueLu::RepartitionFactory)
RefMaxwell (2,2): Build (MueLu::Zoltan2Interface)
Zoltan2 parameters:
----------
algorithm = multijagged
partitioning_approach = partition   [unused]
mj_premigration_option = 1   [unused]
num_global_parts = 3   [unused]
----------
RefMaxwell (2,2): Zoltan2 multijagged
  Teko: "buildInverse" could not construct the inverse operator using "Thyra::MueLuRefMaxwellPreconditionerFactory"
  
  *** THROWN EXCEPTION ***
  getIDsKokkosView called but not on Tpetra!
  ************************
  Teko: "buildInverse" could not construct the inverse operator using "Teko::AutoClone<mini_em::FullMaxwellPreconditionerFactory, mini_em::FullMaxwellPreconditionerFactory>"
  
  *** THROWN EXCEPTION ***
terminate called after throwing an instance of 'terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::exception'
std::exception'
std::exception'
  std::exception
  ************************
  what():    what():  std::exception  what():  std::exception

std::exception[s1042556:59661] *** Process received signal ***
```

**Comment by cgcgcg** [comment]
@brian-kelley No, I wasn't aware of that issue. Is that another issue that's related to Zoltan2 switching MultiJagged over to Kokkos?

**Comment by brian-kelley** [comment]
@cgcgcg Yes, it's actually just a multijagged problem.

**Comment by kddevin** [comment]
Regarding, "getIDsKokkosView called but not on Tpetra!"
Are you using Epetra underneath Xpetra?  This statement is printed only when 
(map_->lib() != Xpetra::UseTpetra)
for Xpetra::Map map_.
I'm guessing when GO=int, Panzer tests with Epetra as well as Tpetra.  We can fix this behavior, but I don't expect it to be a blocker for this issue.  Is it?
@MicheldeMessieres

**Comment by jhux2** [comment]
@kddevin Yes, the test @brian-kelley mentioned is using Epetra.

**Comment by brian-kelley** [comment]
@cgcgcg @kddevin @jhux2 I'm replicating that on a fresh develop to make sure it hasn't already been fixed, then I'll open an issue.

**Pull request merged**
