### PR TITLE
Belos:  Fix Doxygen documentation to include Tpetra examples

### PR DESCRIPTION
**Pull request by hkthorn**
@trilinos/belos

## Motivation

A user commented on #6370 about where to get tutorial information.  The Doxygen examples are useful for illustrating how to use the Belos solvers and can serve as tutorial material.  In review, it was noticed that the Tpetra examples are not being picked up by the Doxygen documentation for Belos, so that is being corrected.

## Related Issues

* Closes `put-issue-number-here`

## Testing

No testing, this is documentation.

### CODE REVIEW

**Review by jhux2 — APPROVED** [review]
lgtm

**Comment by hkthorn** [comment]
@jhux2 I'm confused.  I don't see test failures resulting from these documentation changes, just warnings coming from other packages about things unrelated to these changes.  The clang-format failure is coming from Teko, not the changes to Belos.  Am I missing something?

**Comment by brian-kelley** [comment]
@hkthorn I saw the same format check failure in my PR which also didn't touch Teko. I think the Teko files in develop branch are already misformatted according to this check.

@trilinos/framework Is this a failure that blocks PRs from being merged?

**Comment by brian-kelley** [comment]
OK yes, the Teko files were misformatted but #13014 fixes that.

**Comment by jhux2** [comment]
@brian-kelley But afaik, that shouldn't block a merge.  It didn't for #13002.

**Comment by cgcgcg** [comment]
The clang format issue has nothing to do with this. The PR with the formatting fix #13014 is also failing.

**Pull request merged**
