### PR TITLE
WIP: Improve 'mutrino' test run-times some (ATDV-131, TRIL-219)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
CC: @fryeguy52 

These improvements are based on the work by Brad King at Kitware in:

* https://gitlab.kitware.com/snl/project-1/issues/91

Also see [ATDV-131](https://sems-atlassian-srn.sandia.gov/browse/ATDV-131)

## How was this tested?

I ran this  on 'mutrino' in some extensive testing in summarized in [ATDV-131](https://sems-atlassian-srn.sandia.gov/browse/ATDV-131?focusedCommentId=34363&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-34363).  The final commit to use `ctest -j4` for both the builds was verified on 'mutrino' with:

```
$  env \
      Trilinos_PACKAGES=Panzer \
      CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=FALSE \
      CTEST_DO_CONFIGURE=OFF \
      CTEST_DO_BUILD=FALSE \
    ./ctest-s-local-test-driver.sh intel-opt-openmp-HSW intel-opt-openmp-KNL
***
*** ./ctest-s-local-test-driver.sh  intel-opt-openmp-HSW intel-opt-openmp-KNL
***

ATDM_TRILINOS_DIR = '/home/rabartl/Trilinos.base/Trilinos'

Load some env to get python, cmake, etc ...

Hostname 'mutrino' matches known ATDM host 'mutrino' and system 'mutrino'
Setting compiler and build options for buld name 'default'
Using mutrino compiler stack INTEL to build DEBUG code with Kokkos node type SERIAL and KOKKOS_ARCH=HSW

Running builds:
    intel-opt-openmp-HSW
    intel-opt-openmp-KNL


Running Jenkins driver Trilinos-atdm-mutrino-intel-opt-openmp-HSW.sh ...


real    6m15.261s
user    0m2.926s
sys     0m0.814s

Running Jenkins driver Trilinos-atdm-mutrino-intel-opt-openmp-KNL.sh ...


real    14m15.213s
user    0m2.558s
sys     0m0.617s
```

which posted to CDash builds:

* HSW: https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4976653
* KNL:  https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4976655

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@fryeguy52, can you please review and approve so we can merge this?  I will manually merge to 'atdm-nightly' after I set up a better workflow for that.

**Comment by bartlettroscoe** [comment]
CC: @fryeguy52 , @bradking 

These updated merged to 'atdm-nightly' in the merge commit 25919843365f222cbca25e818abcd5ee178c430e caused a mass of new test failures in testing yesterday as seen in:

* ['mutrino' HSW and KNL builds since 2019-04-28](https://testing.sandia.gov/cdash/index.php?project=Trilinos2&filtercount=2&showfilters=1&filtercombine=or&field1=block&field1count=2&field1field1=buildname&field1compare1=61&field1value1=Trilinos-atdm-mutrino-intel-opt-openmp-HSW&field1field2=buildstarttime&field1compare2=83&field1value2=2019-04-28&field2=block&field2count=2&field2field1=buildname&field2compare1=61&field2value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2field2=buildstarttime&field2compare2=83&field2value2=2019-04-28)

showing:

* [Trilinos-atdm-mutrino-intel-opt-openmp-HSW on 2019-05-02](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4981143): 40 new test failures
* [Trilinos-atdm-mutrino-intel-opt-openmp-KNL on 2019-05-02](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4980167): 79 new test failures

All of the new failing tests that I looked at (just a few) have the error:

```
srun: error: nid00030: task 0: Bus error (core dumped)
```

Also as you can see in that above query, the decrease in wallclock time to run the test is underwhelming with the times:

* HSW tests only going down from 3h 1m 15s to 2h 24m 27s
* KNL tests only going down from 4h 18m 12s to 3h 10m 43s

Therefore, I need to back out the merge commit 25919843365f222cbca25e818abcd5ee178c430e and we to the 'atdm-nightly' branch  and we need to investigate what is happening.

I have added "AT: WIP" so we can stop avoid the PR tester running this anymore.

**Comment by bartlettroscoe** [comment]
FYI: I reverted these changes in the 'atdm-nightly' branch (by pushing to the 'atdm-nightly-manual-updates' branch) in the commit 8945aeaa027eae9ca6bd53d1eb3f354820bc6961 that I just pushed.

**Comment by william76** [comment]
@bartlettroscoe 
This PR has been closed due to inactivity. Please re-open and post a comment if it should be kept around.

**Pull request closed without merging**
