### PR TITLE
commonTools: get-changes-trilinos-packages.sh

### PR DESCRIPTION
**Pull request by e10harvey**
- Update macro to use FORCE set

@trilinos/framework

## Motivation

While trying to work through #10839  @srbdev found several errors in https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors and updated that documentation. Another error that we found was during step 10 where `Trilinos_ENABLE_ALL_PACKAGES` was already set in the cmake cache, and so, is never overwritten by the value specified in `packageEnables.cmake`. After checking `packages/framework/ini-files`, it is clear that something else in the trilinos cmake is caching `Trilinos_ENABLE_ALL_PACKAGES`. This PR addresses this silent error during step 10 by using a "forceful" cmake cache  variable set.

## Stakeholder Feedback

@bartlettroscoe: Please let me know if there is a better way to address this reproducibility problem. 

## Testing

Tested this change locally. The PR AutoTester will also use this script here.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@e10harvey, first, I would like to suggest to not put put **any** package enable-related set() statements in the initial configure by Gen Config or the fragment file produced by Gen Config.  Put all package enable-related settings including `Trilinos_ENABLE_ALL_PACKAGES`, `Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES` and `Trilinos_ENABLE_TESTS` in the file `packageEnablers.cmake`.    That solves the problem.

Otherwise, stop using this two-phase cmake configure process.  Always have gen-config.sh produce an CMake fragment file `GenConfigSettings.cmake` when loading the env and then configure **one time** with:

```
cmake -C packageEnables.cmake -C GenConfigSettings.cmake [option options] <tril-src-dir>
```

That is more efficient, more straightforward, and more like a developer would actually use CMake if given a choice.

In summary, the trick to dealing with overriding CMake cache var setting is to put your set() statements first.  That is, the first call:

```
set(<someCacheVar> <someValue> CACHE <type> "<doc>")
```

for a cache var name `<someCacheVar>` determines the default value for the cache var.  All later set() cache var statements are ignored.  This is how CMake is designed to work/

So, if you want the cache var settings in `<fragmentFile2>.cmake` to override those in `<fragmentFile1>.cmake` you list them first as:

```
cmake -C <fragmentFile2>.cmake -C <fragmentFile1>.cmake [option options] <tril-src-dir>
```

You want to never use `FORCE`, otherwise, any options the user passes in with `-D<cacheVar>=<userVal>` will get ignored and you never want that to be the case.  The number-one purpose of cache vars is to allow the user to override them on the command-line (or by providing their fragment file first on the command-line with `-C <userFragmentFile>.cmake`).

But if you are not convinced, then I propose to add a option `--use-set-force` to this Python tool to optionally add `FORCE` and then you can use that in the PR tester.  But for other usages as described above, you would not do this.

**Comment by e10harvey** [comment]
> @e10harvey, first, I would like to suggest to not put put **any** package enable-related set() statements in the initial configure by Gen Config or the fragment file produced by Gen Config. Put all package enable-related settings including `Trilinos_ENABLE_ALL_PACKAGES`, `Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES` and `Trilinos_ENABLE_TESTS` in the file `packageEnablers.cmake`. That solves the problem.

@bartlettroscoe: This does not meet the user requirements for gen config - we must allow package enable statements. Trilinos_ENABLE_ALL_PACKAGES is not set by gen config but instead, something else in the trilinos cmake infrastructure. 

> Otherwise, stop using this two-phase cmake configure process.

I agree. We will update the documentation and close this pull request.



> You want to never use `FORCE`, otherwise, any options the user passes in with `-D<cacheVar>=<userVal>` will get ignored and you never want that to be the case. The number-one purpose of cache vars is to allow the user to override them on the command-line (or by providing their fragment file first on the command-line with `-C <userFragmentFile>.cmake`).

+1

Thank you for your feedback.

**Comment by bartlettroscoe** [comment]
>  This does not meet the user requirements for gen config - we must allow package enable statements. Trilinos_ENABLE_ALL_PACKAGES is not set by gen config but instead, something else in the trilinos cmake infrastructure.

What user asked for this?  I bet if you go back to that user and explained the downsides of setting package enable-related vars in the CMake fragment file, they would be fine in taking them out.  And if you can't identify that user, then that is not a real requirement.

**Comment by e10harvey** [comment]
> > This does not meet the user requirements for gen config - we must allow package enable statements. Trilinos_ENABLE_ALL_PACKAGES is not set by gen config but instead, something else in the trilinos cmake infrastructure.
> 
> What user asked for this? I bet if you go back to that user and explained the downsides of setting package enable-related vars in the main GenConfig CMake fragment file, then they would be fine in taking them out. And if you can't identify that user, then that is not a real requirement.

Package enable vars are a Trilinos-specific problem related to how CMake cache variables work while GenConfig is a project-agnostic tool.

**Pull request closed without merging**
