### PR TITLE
Framework: Bring over fixes for Mac OSX install for Trilinos 13.0 (#7881, #9105)

### LINKED ISSUE #9105: TriBITS: Problem with Mac using BSD stat vs. Gnu stat
### Description
This is specific to Release 13.0.1. I just ran into the exact same bug that was reported in Issue #7881. Looking at the history, the fix went into the master branch after the 13.0.0 release, and it never got ported to the release-13 branch. I can work around it for now, but it would be nice to have it in a Trilinos release.

### PR DESCRIPTION
**Pull request by bartlettroscoe**
@TBird2001, @trilinos/framework 

This should resolve #9105 (which is related to #7881 resolved on 'develop' and 'master' already).

This brings over the fixes to TriBITS in PR TriBITSPub/TriBITS#327 along with other changes/fixes to these files.

It would have been much harder to try to bring over only the changes to fix the Mac OSX problem since the version of TriBITS in the Trilinos 13.0 branch is from almost 1 year ago.

The new changes should avoid calling any of this code by default due to changes pulled over from PR TriBITSPub/TriBITS#327 as well.

See below development and testing details.  I tested on Linux but this should also be tested on Mac OSX as well just be safe.

<details>

<summary><b>Development and testing details:</b> (click to expand)</summary>

.

The TriBITS changes to fix this are in PR:

* https://github.com/TriBITSPub/TriBITS/pull/327

that impact the files:

* tribits/core/installation/set_installed_group_and_permissions.cmake.in
* tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake 

in the TriBITS commits afb7f2e7d7afd938394b032421840a731b4b2eaa and ef76b3c70a17c3ae1fbe54a801612155140382bf.

What version of TriBITS is in Trilinos 13.0 branch?

```
[rabartl@crf450 Trilinos (trilinos-release-13-0-branch)]$ git log --name-status  -- cmake/tribits/

commit b2023856bb136d722d86bbe858407ed73180ea48
Merge: 98d6064 af035f1
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri May 22 13:41:54 2020 -0600

    Merge branch 'tribits_github_snapshot' into 6697-pr-test-st-packages (#6697)

commit af035f13e78fa6271bbdb820bc7fd6b00d2cf6fe
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri May 22 13:40:26 2020 -0600

    Automatic snapshot commit from tribits at 52acd38
    
    Origin repo remote tracking branch: 'github/master'
    Origin repo remote repo URL: 'github = git@github.com:TriBITSPub/TriBITS.git'
    
    At commit:
    
    commit 52acd38d2c480c86f5924b475073836d476041bc
    Author:  Roscoe A. Bartlett <rabartl@sandia.gov>
    Date:    Fri May 22 13:24:22 2020 -0600
    Summary: Add get-tribits-packages.py (trilinos/Trilinos#6697)

M       cmake/tribits/ci_support/TribitsDependencies.py
A       cmake/tribits/ci_support/get-tribits-packages.py
```

Wow, TriBITS from May 22, 2020!  That is almost a year ago!

So what changes to those files occurred in that time?

```
$ git log-short --name-status github/master --not 52acd38 -- \
  tribits/core/installation/set_installed_group_and_permissions.cmake.in \
  tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake

1ed3811 "Generate error when trying to set install perms/group mod options on Windows (#314)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Sep 22 16:06:21 2020 -0600 (8 months ago)

M       tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake

362e27d "Fix stat command args for Linux (trilinos/Trilinos#7881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Sep 22 10:09:42 2020 -0600 (8 months ago)

M       tribits/core/installation/set_installed_group_and_permissions.cmake.in

b862c6a "Fix install perms mods and tests to work on MacOSX for real (trilinos/Trilinos#7881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Sep 22 08:22:16 2020 -0600 (8 months ago)

M       tribits/core/installation/set_installed_group_and_permissions.cmake.in

ef76b3c "Don't run any extra commands if group/perms options not set (trilinos/Trilinos#7881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Sep 16 14:42:34 2020 -0600 (8 months ago)

M       tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake

afb7f2e "Use stat -f for MacOSX (trilinos/Trilinos#7881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Sep 16 14:39:26 2020 -0600 (8 months ago)

M       tribits/core/installation/set_installed_group_and_permissions.cmake.in

6165385 "Rename local var CMAKE_INSTALL_REFIX to avoid Trilinos/Dakota integration problems (trilinos/Trilinos#7636)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Jul 6 16:38:42 2020 -0600 (10 months ago)

M       tribits/core/installation/set_installed_group_and_permissions.cmake.in
```

Other files changed as part of these comments?

```
$ git log-short --name-status -1 1ed3811 -- tribits
1ed3811 "Generate error when trying to set install perms/group mod options on Windows (#314)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Sep 22 16:06:21 2020 -0600 (8 months ago)

M       tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake

$ git log-short --name-status -1 362e27d -- tribits
362e27d "Fix stat command args for Linux (trilinos/Trilinos#7881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Sep 22 10:09:42 2020 -0600 (8 months ago)

M       tribits/core/installation/set_installed_group_and_permissions.cmake.in

$ git log-short --name-status -1 b862c6a -- tribits
b862c6a "Fix install perms mods and tests to work on MacOSX for real (trilinos/Trilinos#7881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Sep 22 08:22:16 2020 -0600 (8 months ago)

M       tribits/core/installation/set_installed_group_and_permissions.cmake.in

$ git log-short --name-status -1 ef76b3c -- tribits
ef76b3c "Don't run any extra commands if group/perms options not set (trilinos/Trilinos#7881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Sep 16 14:42:34 2020 -0600 (8 months ago)

M       tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake

$ git log-short --name-status -1 afb7f2e -- tribits
afb7f2e "Use stat -f for MacOSX (trilinos/Trilinos#7881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Sep 16 14:39:26 2020 -0600 (8 months ago)

M       tribits/core/installation/set_installed_group_and_permissions.cmake.in

$ git log-short --name-status -1 6165385 -- tribits
6165385 "Rename local var CMAKE_INSTALL_REFIX to avoid Trilinos/Dakota integration problems (trilinos/Trilinos#7636)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Jul 6 16:38:42 2020 -0600 (10 months ago)

M       tribits/core/installation/set_installed_group_and_permissions.cmake.in
````

Therefore, it looks like I might be able to just copy over the two files:

```
tribits/core/installation/set_installed_group_and_permissions.cmake.in
tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake 
```

and that should do it.

So here is what I did:

```
$ gitdist-status --dist-repos=.,TriBITS
---------------------------------------------------------------------------------------------------------
| ID | Repo Dir        | Branch                       | Tracking Branch                     | C | M | ? |
|----|-----------------|------------------------------|-------------------------------------|---|---|---|
|  0 | Trilinos (Base) | trilinos-release-13-0-branch | github/trilinos-release-13-0-branch |   |   |   |
|  1 | TriBITS         | master                       | github/master                       |   |   |   |
---------------------------------------------------------------------------------------------------------

$ gitdist --dist-repos=.,TriBITS log-short --name-status -1 

*** Base Git Repo: Trilinos
4796b92 "Merge Pull Request #8315 from trilinos/Trilinos/jwillenbring-release-13-0-1"
Author: trilinos-autotester <trilinos@sandia.gov>
Date:   Fri Nov 13 17:13:13 2020 -0700 (6 months ago)


*** Git Repo: TriBITS
e000daa "Merge branch 'tril-9104-windows-include' (trilinos/Trilinos#9104)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed May 5 11:20:36 2021 -0600 (23 hours ago)

$ cp TriBITS/tribits/core/installation/set_installed_group_and_permissions.cmake.in \
  cmake/tribits/core/installation/

$ cp TriBITS/tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake \
  cmake/tribits/core/package_arch/

$ git status
On branch trilinos-release-13-0-branch
Your branch is up-to-date with 'github/trilinos-release-13-0-branch'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   cmake/tribits/core/installation/set_installed_group_and_permissions.cmake.in
        modified:   cmake/tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake

no changes added to commit (use "git add" and/or "git commit -a")
```

I committed this as:

```
3b4b5ab "Bring over fixes for Mac OSX install (#7881, #9105)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Thu May 6 13:50:08 2021 -0600 (4 seconds ago)

M       cmake/tribits/core/installation/set_installed_group_and_permissions.cmake.in
M       cmake/tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake
```

and I tested this locally with:

```
$ cd ~/Trilinos.base2/BUILDS/ATDM/gnu-shared-opt/

$ cat load-env.sh
. ~/Trilinos.base2/Trilinos/cmake/std/atdm/load-env.sh gnu-shared-opt

$ . load-env.sh
Hostname 'crf450' matches known ATDM host 'crf450' and system 'sems-rhel7'
Setting compiler and build options for build-name 'gnu-shared-opt'
Using SEMS RHEL7 compiler stack GNU-7.2.0 to build RELEASE code with Kokkos node type SERIAL
[rabartl@crf450 gnu-shared-opt (crf450)]$ 

$ cat do-configure
#!/bin/bash
cmake \
-GNinja \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
-DTrilinos_ENABLE_TESTS=ON \
"$@" \
~/Trilinos.base2/Trilinos

$ time ./do-configure \
  -DTrilinos_ENABLE_TeuchosCore=ON \
  -DCMAKE_INSTALL_PREFIX=$PWD/install \
  -DTrilinos_MAKE_INSTALL_GROUP=wg-1400-all \
  &> configure.out

real    0m10.973s
user    0m5.572s
sys     0m2.438s

$ time make &> make.out $

real    0m23.073s
user    4m37.717s
sys     0m22.394s

$ time make install &> make.install.out

real    0m0.309s
user    0m0.096s
sys     0m0.207s

$ tail -n 2 make.install.out 
-- 0: Running: chgrp -R wg-1400-all /ascldap/users/rabartl/Trilinos.base2/BUILDS/ATDM/gnu-shared-opt/install
-- 0: Running: chmod -R g+rwX,o+rX /ascldap/users/rabartl/Trilinos.base2/BUILDS/ATDM/gnu-shared-opt/install

$ ls -ld install
drwxrwxr-x 6 rabartl wg-1400-all 4096 May  6 14:09 install
```

That looks good to me.

</details>

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Responding to https://github.com/trilinos/Trilinos/issues/9105#issuecomment-833911533 in this PR ...

> @bartlettroscoe, I just tested it on my Mac, and the installation went smoothly. The fix appears to have worked!

Excellent!

@trilinos/framework, @jwillenbring,

Can someone please review and approve this PR so that it can be merged to the release branch and go out in the next minor release?

**Comment by mperego** [comment]
@bartlettroscoe is `RUN_SERIAL` `ON` for that failing test?
I'm OK turning the test off for the Cuda 9.2 PR, as long as we keep that enabled for the Cuda-10 PR builds. What do you think @CamelliaDPG ?

**Comment by CamelliaDPG** [comment]
> @bartlettroscoe is `RUN_SERIAL` `ON` for that failing test?
> I'm OK turning the test off for the Cuda 9.2 PR, as long as we keep that enabled for the Cuda-10 PR builds. What do you think @CamelliaDPG ?

We've had issues in the past with this test getting resource-starved thanks to apparent contention with other tests; I think the RUN_SERIAL fix is the best route, assuming that it is OFF right now.  But I do think CUDA-10 coverage would be enough, if it came to that.

**Comment by bartlettroscoe** [comment]
>  I think the RUN_SERIAL fix is the best route, assuming that it is OFF right now.

@CamelliaDPG and @mperego,

Can I make this change in this PR branch?  This `Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1` test timed-out again in the last PR iteration as well as shown [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Clean&field2=buildname&compare2=65&value2=PR-9110-test-Trilinos_pullrequest&field3=status&compare3=61&value3=failed&field4=buildstarttime&compare4=84&value4=now).

Also note (as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Clean&field2=buildname&compare2=65&value2=PR-9110-test-Trilinos_pullrequest&field3=status&compare3=61&value3=failed&field4=buildstarttime&compare4=84&value4=now) that the test `SEACASAprepro_lib_aprepro_lib_array_test` failed as shown [here](https://testing.sandia.gov/cdash/test/69897595) showing the error:

```
================================================================================

TEST_2

Running: "diff" "-w" "/scratch/trilinos/jenkins/ascic142/workspace/trilinos-folder/Trilinos_pullrequest_clang_7.0.1/Trilinos/packages/seacas/libraries/aprepro_lib/test-array.stderr.gold" "/scratch/trilinos/jenkins/ascic142/workspace/trilinos-folder/Trilinos_pullrequest_clang_7.0.1/pull_request_test/packages/seacas/libraries/aprepro_lib/test-array.stderr"

--------------------------------------------------------------------------------

19,20c19,20
< $  {Greg        = "Is the author of this code"} (immutable)
< Aprepro: There were 0 errors detected during parsing.
---
> $  {Greg      Aprepro: There were 0 errors detected during parsing.
> 	= "Is the author of this code"}	(immutable)

--------------------------------------------------------------------------------

TEST_2: Return code = 1
TEST_2: Pass criteria = Zero return code [FAILED]
TEST_2: Result = FAILED

================================================================================
```

There is zero chance that changes in this PR are causing that test to fail.

@gsjaardema, can we disable the test `SEACASAprepro_lib_aprepro_lib_array_test` on the `trilinos-release-13-0-branch`?

**Comment by mperego** [comment]
> I think the RUN_SERIAL fix is the best route, assuming that it is OFF right now.
> 
> @CamelliaDPG and @mperego,
> 
> Can I make this change in this PR branch? This Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1 test timed-out again in the last PR iteration as well as shown here.

@bartlettroscoe  Yes, feel free to make the change in this PR branch. Thanks!

**Comment by bartlettroscoe** [comment]
> > I think the RUN_SERIAL fix is the best route, assuming that it is OFF right now.
> > ...
>
> @bartlettroscoe Yes, feel free to make the change in this PR branch. Thanks!

So we have another problem.  The version of TriBITS in 'trilinos-release-13-0-branch' was based on the TriBITS version TriBITSPub/TriBITS@52acd38d2c480c86f5924b475073836d476041bc from almost a year ago.  But TriBITS support for setting the RUN_SERIAL test property as a cache var was added later in TriBITS commit TriBITSPub/TriBITS@c42eb66 added 8 months ago.

So we can't just add:

```
set(Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1_SET_RUN_SERIAL ON \
  CACHE BOOL "")
```

to the file `cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake`.  It will not have any impact.

At this point, I am going to leave this to the Trilinos developers to decide how to get this PR to merge.  I have done my part in applying the patch to fix #9105 in 'trilinos-release-13-0-branch'.  This not my fault that the PR tests are not passing and will not allow this to merge.

I will note that from looking at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos

there does not appear to be any regular testing of Trilinos on the 'trilinos-release-13-0-branch' branch.  Therefore, even if the Trilinos test suite 100% passed on these PR builds when that branch was first cut, changes to those platforms could break the PR builds and tests and no one would know it.  Then, when someone went to post a PR to apply a patch, things could be failing do to changes to the platforms (like might have occurred here).  In fact, it looks like there was never any intention to set up automated builds supporting the Trilinos 13.0 release as there is no "Nightly Release 13.0" CDash group even defined at:

* https://testing.sandia.gov/cdash/manageBuildGroup.php?projectid=1

I am just guessing this is what happened but that is a fair bet why this test is failing on the release branch.  (Otherwise, no one would have put out a Trilinos release with known failing PR build tests.)

**Comment by william76** [comment]
@bartlettroscoe is this a WIP or do you think it's sorted out?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe is this a WIP or do you think it's sorted out?

@william76, no, this is not WIP, it is ready to merge.  It just will not pass the PR testing due to existing failures that have nothing to do with this PR.  See [above](https://github.com/trilinos/Trilinos/pull/9110#issuecomment-836786268) where I said:

> At this point, I am going to leave this to the Trilinos developers to decide how to get this PR to merge. I have done my part in applying the patch to fix #9105 in 'trilinos-release-13-0-branch'. This not my fault that the PR tests are not passing and will not allow this to merge.

**Pull request closed without merging**
