### PR TITLE
Panzer: Remove extensive recomputing of Jacobian from IntegrationValues2

### PR DESCRIPTION
**Pull request by seanofthemillers**
@trilinos/Panzer

## Motivation

Right now `IntegrationValues2::evaluateEverything` is recomputing the Jacobian many times, when it should only be computed once. These changes are meant to fix the issue.

### CODE REVIEW

**Comment by seanofthemillers** [comment]
@rppawlo This is the issue/fix I mentioned in the EMPIRE meeting today. I'm still building/testing on my end.

**Comment by rppawlo** [comment]
Thanks @seanofthemillers ! I'll run some checks against the sandia apps to test.

**Comment by seanofthemillers** [comment]
@rppawlo Using MiniEM I'm seeing a 4x speedup in workset generation (workset size = 12k). We go from:
image
To:
image

We may want to put together a follow up issue to handle the Jacobian evaluation and cubature point evaluation calls. It appears that they are evaluating the Jacobian/Points on a cell-by-cell basis, which  is heavily launch latency bound on GPUs. Based on what I'm seeing in the IntegrationValues2.cpp file, this might have to happen in Intrepid2.

Is there anything I can do to help with the failures? I can't access the CDash site.

**Review by rppawlo — APPROVED** [review]

**Comment by rppawlo** [comment]
Good to go! Thanks @seanofthemillers !

**Comment by seanofthemillers** [comment]
@rppawlo I believe I fixed the tests. It turns out that some of the fixes I made for the jacobian call exposed some bad/missing logic in IntegrationValues2 regarding permutations in boundary condition worksets. This update was enough of a change that you may want to test again with Charon/Drekar/EMPIRE.

**Comment by cgcgcg** [comment]
@rppawlo Can this be merged, or did you want to run this once more with some apps?

**Comment by rppawlo** [comment]
@cgcgcg - charon passed. I'm running with empire now - if that passes, we can merge.

**Review by rppawlo — APPROVED** [review]

**Pull request merged**
