### PR TITLE
Reverting changes to LAPACK GEES routines to address bugs #3992 and #3989

### PR DESCRIPTION
**Pull request by hkthorn**
@trilinos/anasazi 

## Description

Failures on ATDM platforms started after PR #3951, where the interaction
with the BKS and Generalized Davidson solver and LAPACK GEES changed to
address issues with MKL 18.0.[1-3].  While it seems that checking for the
optimal workspace size should be safe before performing the eigensolve using GEES,
it appears there are memory issues with GEES in MKL 17.0.x, where the use
of the optimal memory size is resulting in bad behavior and potential seg
faults.  So, it's a catch 22 and I am going back to the previous version
of these solvers that have been solid for years.

## Motivation and Context

This should address ATDM test failures on CEE platforms.  It will likely reintroduce the test failures for Mutrino, but you can't have it all.

## How Has This Been Tested?

On Chama and CEE machines.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

This is just a checkout of the previous version of the file that was passing on the affected platforms.  No other modifications of those solvers have been made.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@micahahoward @rrdrake FYI

**Comment by hkthorn** [comment]
@bartlettroscoe @fryeguy52 Say what?  Is there a Jenkins issue here?

**Comment by bartlettroscoe** [comment]
@hkthorn , I cced @fryeguy52 because he is going to try the Intel 18.9.5 update

**Comment by hkthorn** [comment]
@bartlettroscoe Very well.

**Comment by mhoemmen** [comment]
I don't want to click "Approve" but I'm OK that Ross did :-)

**Pull request merged**
