### PR TITLE
Tpetra:  replace serial search with unordered_map for inserting into dense rows #8794

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/tpetra   #8794 

## Motivation

A serial search in insert_crs_indices slowed down nonzero insertion for very dense rows.  
This PR substitutes an unordered_map for the serial search when rows are dense enough.
A test program Bug8794.cpp exercises the capability on a matrix with dense and sparse rows.
A utility program insertCrsIndicesThreshold.cpp computes the cross-over point between the serial search and the unordered_map.  
Also,  unused, untested method findLocalIndices is removed.

If this PR is accepted, the same logic should be added to find_crs_indices as well.

This PR results in faster fillComplete time for power-law type graphs such as twitter (39M rows, 861M nonzeros)
The old and new times to read and distribute the matrix market file and build the matrix (using insertGlobalValues and fillComplete) with a 1D matrix distribution on three processors of ghost are shown below:
```
old:  buildMatrixFromMM Time: 8837.17
new:  buildMatrixFromMM Time: 2243.39
```

## Stakeholder Feedback

@crdohrm @shardest

## Testing

Tested on ghost cluster, intel 19, serial node.

Threshold value determined by insertCrsIndicesThreshold.cpp:
```
Timer Name        Global time (num calls)
--------------------------------------------------------------------------------
nz=0001 search    1.728e-05 (10)
nz=0001 table     1.988e-05 (10)
nz=0101 search    5.487e-05 (10)
nz=0101 table     9.694e-05 (10)
nz=0201 search    0.0001193 (10)
nz=0201 table     0.0001787 (10)
nz=0301 search    0.0002249 (10)
nz=0301 table     0.0002584 (10)
nz=0401 search    0.0003714 (10)
nz=0401 table     0.0003631 (10)
--------------------------------------------------------------------------------
nz=0501 search    0.0005369 (10)
nz=0501 table     0.0004293 (10)
nz=0601 search    0.0007555 (10)
nz=0601 table     0.0005018 (10)
nz=0701 search    0.0009922 (10)
nz=0701 table     0.0005908 (10)
nz=0801 search    0.00128 (10)
nz=0801 table     0.0006674 (10)
nz=0901 search    0.001605 (10)
nz=0901 table     0.0007455 (10)
--------------------------------------------------------------------------------
nz=1001 search    0.001964 (10)
nz=1001 table     0.0008356 (10)
...
nz=9801 search    0.1878 (10)
nz=9801 table     0.01123 (10)
nz=9901 search    0.1917 (10)
nz=9901 table     0.01138 (10)
```

### CODE REVIEW

**Comment by kddevin** [comment]
#8794

**Comment by kddevin** [comment]
This PR results in faster fillComplete time for power-law type graphs such as twitter (39M rows, 861M nonzeros)
The old and new times to read and distribute the matrix market file and build the matrix (using insertGlobalValues and fillComplete) with a 1D matrix distribution on three processors of ghost are shown below:
```
old:  buildMatrixFromMM Time: 8837.17
new:  buildMatrixFromMM Time: 2243.39
```

**Review by kyungjoo-kim — APPROVED** [review]
It looks good to me. Do you also have comparison with three array constructor ? The issue from the application is that it costs a lot more when it uses the insert interface constructing trasposed graph. I just wonder if the performance of this approach can be comparable to its three array constructor with manual constructor of transposed graph.

**Comment by kddevin** [comment]
@kyungjoo-kim  Thanks for your review.  For the transpose use case, the three-array constructor is still the way to go.  It should be more efficient than insertGlobalValues, even with these changes.

**Review by kyungjoo-kim — APPROVED** [review]

**Pull request merged**
