### PR TITLE
[WIP]  Tempus:  Step control strategy

### PR DESCRIPTION
**Pull request by sconde**
@trilinos/tempus 

## Description

This is my attempt at defining the step control strategy. 

`TimeStepControl` will call the `stepControlStrategy_`'s `getNextTimeStep` method, which can be a composite of strategies (such as @ikalash's *BDF2 step control*, ramping, time scale, I controller, PI Controller, etc). The implementation of these strategies (and new ones) will be application dependent. 
This cleans up `TimeStepControl`. 

Also, this will prevent code duplication and minimizes tests from failing if/when `TimeStepControl` should change in the future (at least in Drekar).

**NOTE** This is just an idea. The code is certainly not ready to be merge yet. If we decide to adopt this idea, I will go ahead and clean up and add a `setStepControlStrategy` method to `TimeStepControl`. This will allow applications to add strategies or override `stepControlStrategy_` altogether. Like it is done with integrator observer (for output)

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by ikalash** [comment]
@sconde : I don't have time to look at this today but I should tomorrow.  I'll also check that this does not break any Albany tests.

**Comment by ikalash** [comment]
@sconde : I reviewed this branch as well as tested Albany built on top of it.  Everything passes.  I really like how you cleaned up the output - thanks for doing that!  My one comment is about the name of the Tempus::StepControlStrategyVSBDF2 class.  I would vote for removing BDF2 from the name.  Even though this time step control algorithm is from a thesis on BDF2, it's not limited to BDF2 steppers (@ccober6  please correct me if I'm wrong).  I'm not sure what would be a better name.  We could call it StepControlStrategyVSDenner for the author of the thesis it's from (I assume "VS" stands for "Variable Step"), though Denner is not the original author of the scheme, so maybe that person's name is more appropriate.  @ccober6 , maybe you have some thoughts on this?

**Comment by ccober6** [comment]
I have not had a chance to review it yet, but a suggestion following Irina'a comments.  Tempus::StepControlStrategyVSBDF2 may be should be something like Tempus::TimeStepControlStrategyBasicVS.  This control is not particular to any Stepper, like Irina mentioned, and is intended as a basic variable step control.  We should make sure we cite Denner in the doxygen notes (I think this is already true).  I would keep the "TimeStepControl" part of the name to be consistent with other names.  The name is long, and am open to suggestions to shorten it.

**Comment by ikalash** [comment]
I'm good with Tempus::TimeStepControlStrategyBasicVS.  I do cite the Denner thesis in the doxygen / commenting, yes.

**Comment by sconde** [comment]
@ikalash @ccober6 I will update to reflect the suggestions. Should the strategy parameterlist validation get handled by the time step control or by the strategy itself?

**Comment by ccober6** [comment]
Yeah, I think the strategy is the better place to do the ParameterList validation.  Otherwise TimeStepControl needs to know about all the strategies validation, versus the strategy knowing its own validation.

**Comment by sconde** [comment]
I've updated so that the strategy parameter validation is done outside of TSC. 

I've also tried to make it backward compatible. For now, a sublist is populated and the VS parameters are copied and passed to `TimeStepControlStrategyBasicVS`. Not sure if this is the best way to do this but so far it's able to catch the old tests.

**Comment by sconde** [comment]
@ccober6 @ikalash @rppawlo are you able to review this PR?

**Comment by ccober6** [comment]
It is moving up my list.  I will try to look at it today.

**Comment by ikalash** [comment]
Looks good to me too.

**Pull request merged**
