### PR TITLE
Phalanx: remove debug print statement

### PR DESCRIPTION
**Pull request by rppawlo**
@trilinos/<teamName>

## Related Issues

* Closes 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by jmgate** [comment]
Is this PR also failing because of those `_decl.hpp` files we removed from Panzer last week?  Looking at the changes, there shouldn't be any reason for testing to fail.  If this is what's holding us up, we really need to be able to tell the @trilinos-autotester when to do a clean build.

**Comment by rppawlo** [comment]
@jmgate - this change removed a debug print statement. No way it should have failed. Guessing it is the build directory that needs to be cleaned out. @bathmatt put together a jenkins job to clean out all workspaces on a particular machine. Perhaps we could do something similar for the trilinos testing. @trilinos-autotester

**Comment by jmgate** [comment]
Looping in @allevin, @jwillenbring&hellip;

**Comment by allevin** [comment]
@jmgate @rppawlo I'm looking at it now.  Odd behaviour on the Jenkins Testing jobs.  Both Build 186 and 188 are locked up after the "Found Doxygen" line:  

-- Performing Test FINITE_VALUE_HAVE_GLOBAL_ISINF - Success
-- Performing Test FINITE_VALUE_HAVE_STD_ISINF
-- Performing Test FINITE_VALUE_HAVE_STD_ISINF - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1")

**Comment by allevin** [comment]
Also, it looks like Builds 321 and 323 both failed due to the Panzer build dir issue.

**Comment by allevin** [comment]
@jmgate Currently, the configuration for the Trilinos Autotester is that all PR's must have an inspection before merging.  I believe that @jwillenbring has it set this way for soft-launch testing.

**Comment by jwillenbring** [comment]
>This all looks fine to me. @allevin, why was a review needed if this was coming from a Trilinos developer? I realize we can still merge it in regardless, but I didn't think the @trilinos-autotester would require a review in this case. Perhaps because it was coming from @rppawlo's fork instead of from a branch in Trilinos itself?

@jmgate The wording is like this because we originally planned to require an inspection prior to merging (after the soft launch). We decided against this for now at TUG, but the parameter has not been updated (I was thinking that this would be unnecessary because you actually can merge, but this makes the message confusing). Thanks.

**Comment by jmgate** [comment]
Gotcha.  Many thanks.

**Pull request merged**
