### PR TITLE
Pull Issue3832 changes for GCC 7.2.0 builds from master to dev

### PR DESCRIPTION
**Pull request by ZUUL42**
@trilinos/framework 

## Description

Pulling Issue3832 changes from GCC 7.2.0 builds from master to dev

## Motivation and Context

PR builds to dev are failing 7.2.0 PR test.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by ZUUL42** [comment]
I'm trying to get the 7.2.0 changes from #4003 into develop since that PR took the changes straight from my issue branch to master. This seems like the most direct way to do that. If there is a better way, please let me know.

**Comment by william76** [comment]
@csiefer2 filed #4034 as well.  I haven't had time to research this, but it looks like all incoming PR's are currently breaking, so we need to get things fixed.  
I am concerned about what might happen if we merge master into develop here since this is dragging along 30 commits, which look like merge commits for the develop->master stuff... is there any way letting this go through would possibly break something in develop?

@ZUUL42 it's probably a little on the tedious side, but I'd be more comfortable if you made a new topic branch on your fork and copy the files that are in master that you need into develop from #4003 and create a new PR that goes from that topic branch into develop...

Anyways, it's after 5pm today and we have our standup in the morning -- we should definitely go over this tomorrow morning first thing.

**Comment by william76** [comment]
@trilinos/framework 
@jwillenbring 
@prwolfe 
@ZUUL42 
I went into the autotester config on gitlab and disabled the 7.2.0 test from PR testing for PR's going into develop so that peoples' PR's can get through.  We can re-enable this once we get the scripts sorted out for the 7.2.0 test.  I left 7.2.0 enabled for the develop->master testing since I think those files are on master since #4003 went into master.

**Comment by mhoemmen** [comment]
> This seems like the most direct way to do that. If there is a better way, please let me know.

If it's a small number of commits, you could just cherry-pick them, then immediately do the develop-to-master promotion manually and resolve any resulting merge conflicts, no?

**Comment by prwolfe** [comment]
No – your comments below match my expectations as well. I never even reference master in the trilinos project.

-----------------------------------------------------------------------
Recommending policy and creating automation to
enable DevOps in the Trilinos and CTH organizations.

**Comment by prwolfe** [comment]
@william76 - thanks for that work-around I think it's much safer than merging master back into develop. The main worry is that most of these are merge commits meaning that they may do odd things if merged back into develop.

@mhoemmen - sleep man. 11:00pm is not working hours ;->.

**Comment by mhoemmen** [comment]
@prwolfe neither is 06:00 ;-P

**Pull request closed without merging**
