### PR TITLE
Stratimikos: fix CMake for Amesos2 disabled

### PR DESCRIPTION
**Pull request by ibaned**
@trilinos/stratimikos 

## Description

Try to fix a use case brought up by @hkthorn
in respose to #1090

## Motivation and Context

@hkthorn has a build where configure fails in this file.

## How Has This Been Tested?

Not tested by me yet, I intend to use the checkin script.
@hkthorn could test her case if possible.

## Checklist

- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@ibaned, the branch `stratimikos-amesos2` has already been rebased and merged.  Therefore, another branch should be created for this.

**Comment by ibaned** [comment]
@bartlettroscoe what is the downside of doing two pull requests with the same branch name?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe what is the downside of doing two pull requests with the same branch name?

To be 100% clear, that branch should be created off of 'develop' and then I guess there is no harm.  But my opinion is that a branch called something like `stratimikos-amesos2-fix1` might be better.

**Comment by ibaned** [comment]
this branch was recreated off of develop, so its only the same name but not the same history as the last one. unfortunately I don't see a way to change the source branch without creating a whole new PR, but I'll try to give them different names in the future.

**Pull request merged**
