### PR TITLE
Kokkos refactor options #2674

### PR DESCRIPTION
**Pull request by fryeguy52**
@bartlettroscoe 

Addresses #2674

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@fryeguy52, I pulled the branch and did the configure on 'waterman' with:

```
$ ./checkin-test-atdm.sh cuda-9.2-opt-Power9-Volta70 --enable-packages=MueLu --configure
```

and it showed these options being set correctly:

```
$ grep -i refactor cuda-9.2-opt-Power9-Volta70/packages/xpetra/src/Xpetra_config.hpp
#define HAVE_XPETRA_KOKKOS_REFACTOR

$ grep -i refactor cuda-9.2-opt-Power9-Volta70/packages/muelu/src/MueLu_config.hpp 
#define HAVE_MUELU_KOKKOS_REFACTOR
#define HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT
```

I am testing this more fully on 'waterman' with:

```
$ bsub -x -Is -n 20 \
   ./checkin-test-atdm.sh \
   cuda-9.2-debug-Power9-Volta70 cuda-9.2-opt-Power9-Volta70 \
   --enable-packages=MueLu,Panzer --local-do-all
```

@fryeguy52, can you run this command as well and see what happens?  I will report back here when the above command finishes for me.

**Comment by bartlettroscoe** [comment]
FYI:

After running:

```
$ bsub -x -Is -n 20 \
   ./checkin-test-atdm.sh \
   cuda-9.2-debug-Power9-Volta70 cuda-9.2-opt-Power9-Volta70 \
   --enable-packages=MueLu,Panzer --local-do-all
```

on 'waterman' I verified that the Kokkos Refactor options are being turned on by doing:

```
$ grep -i refactor cuda-9.2-opt-Power9-Volta70/packages/xpetra/src/Xpetra_config.hpp
#define HAVE_XPETRA_KOKKOS_REFACTOR

$ grep -i refactor cuda-9.2-opt-Power9-Volta70/packages/muelu/src/MueLu_config.hpp 
#define HAVE_MUELU_KOKKOS_REFACTOR
#define HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT

$ grep -i refactor cuda-9.2-debug-Power9-Volta70/packages/xpetra/src/Xpetra_config.hpp
#define HAVE_XPETRA_KOKKOS_REFACTOR

$ grep -i refactor cuda-9.2-debug-Power9-Volta70/packages/muelu/src/MueLu_config.hpp 
#define HAVE_MUELU_KOKKOS_REFACTOR
#define HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT
```

but it returned the test results shown below.

**/cuda-9.2-debug-Power9-Volta70/ctest.out**:

```
98% tests passed, 5 tests failed out of 204

Subproject Time Summary:
MueLu     = 4702.44 sec*proc (46 tests)
Panzer    = 9569.09 sec*proc (158 tests)

Total Test time (real) = 1885.54 sec

The following tests FAILED:
	 12 - MueLu_UnitTestsTpetra_MPI_1 (Timeout)
	 13 - MueLu_UnitTestsTpetra_MPI_4 (Timeout)
	178 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 (Failed)
	182 - PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 (Timeout)
	204 - PanzerMiniEM_MiniEM-BlockPrec_RefMaxwell_MPI_4 (Failed)
Errors while running CTest
```

**cuda-9.2-opt-Power9-Volta70/ctest.out**:

```
98% tests passed, 4 tests failed out of 204

Subproject Time Summary:
MueLu     = 4642.98 sec*proc (46 tests)
Panzer    = 9757.75 sec*proc (158 tests)

Total Test time (real) = 1908.33 sec

The following tests FAILED:
	 12 - MueLu_UnitTestsTpetra_MPI_1 (Timeout)
	 13 - MueLu_UnitTestsTpetra_MPI_4 (Timeout)
	178 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 (Failed)
	182 - PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 (Timeout)
```

so that does not seem to have helped anything :-(

@fryeguy52, can you please verify these results for yourself?

I will next try to enable `Tpetra_ASSUME_CUDA_AWARE_MPI=ON` (see #3405) and see if that helps anything.

**Comment by bartlettroscoe** [comment]
I tried setting `Tpetra_ASSUME_CUDA_AWARE_MPI=ON` in commit fbe17abf806c9a8e2dc65a0c87cd062691ac9fc2 that I just pushed to this branch and it does not seem to help anything.  

I tested this with:

```
$ bsub -x -Is -n 20 \
   ./checkin-test-atdm.sh \
   cuda-9.2-debug-Power9-Volta70 cuda-9.2-opt-Power9-Volta70 \
   --enable-packages=MueLu,Panzer --local-do-all
```

and verified that it got enabled with:

```
$ grep -i assume cuda-9.2-debug-Power9-Volta70/packages/tpetra/core/src/TpetraCore_config.h 
/* Define when Tpetra assumes that the MPI implementation is CUDA aware */
#define TPETRA_ASSUME_CUDA_AWARE_MPI

$ grep -i assume cuda-9.2-opt-Power9-Volta70/packages/tpetra/core/src/TpetraCore_config.h 
/* Define when Tpetra assumes that the MPI implementation is CUDA aware */
#define TPETRA_ASSUME_CUDA_AWARE_MPI
```

which gave the test results:

**cuda-9.2-debug-Power9-Volta70/ctest.out:**
```
97% tests passed, 6 tests failed out of 204

Subproject Time Summary:
MueLu     = 4746.42 sec*proc (46 tests)
Panzer    = 9209.44 sec*proc (158 tests)

Total Test time (real) = 1828.60 sec

The following tests FAILED:
         12 - MueLu_UnitTestsTpetra_MPI_1 (Timeout)
         13 - MueLu_UnitTestsTpetra_MPI_4 (Timeout)
        178 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 (Failed)
        182 - PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 (Timeout)
        185 - PanzerAdaptersSTK_PoissonInterfaceExample_3d_MPI_4 (Failed)
        187 - PanzerAdaptersSTK_PoissonInterfaceExample_3d_MPI_4-ConvTest (Failed)
Errors while running CTest
```

**cuda-9.2-opt-Power9-Volta70/ctest.out:**
```
97% tests passed, 6 tests failed out of 204

Subproject Time Summary:
MueLu     = 4697.15 sec*proc (46 tests)
Panzer    = 9641.61 sec*proc (158 tests)

Total Test time (real) = 1884.50 sec

The following tests FAILED:
         12 - MueLu_UnitTestsTpetra_MPI_1 (Timeout)
         13 - MueLu_UnitTestsTpetra_MPI_4 (Timeout)
        178 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 (Failed)
        182 - PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 (Timeout)
        185 - PanzerAdaptersSTK_PoissonInterfaceExample_3d_MPI_4 (Failed)
        187 - PanzerAdaptersSTK_PoissonInterfaceExample_3d_MPI_4-ConvTest (Failed)
Errors while running CTest
```

So as you can see, setting `Tpetra_ASSUME_CUDA_AWARE_MPI=ON` actually increases the number of test failures for the current OpenMPI 2.1.2 env on 'waterman'.

I will remove the commit fbe17abf806c9a8e2dc65a0c87cd062691ac9fc2 from this branch.  Also, I will do a baseline build with the version of Trilinos without setting these Kokkos Refactor options just to be sure.

**Comment by bartlettroscoe** [comment]
FYI: For the baseline Trilinos version that this topic branch is based off of which is commit 1d0e85e, on 'white' I ran:

```
$ bsub -x -Is -n 20 \
   ./checkin-test-atdm.sh \
   cuda-9.2-debug-Power9-Volta70 cuda-9.2-opt-Power9-Volta70 \
   --enable-packages=MueLu,Panzer --local-do-all
```

which showed the configured files:

```
$ grep -i refactor cuda-9.2-debug-Power9-Volta70/packages/xpetra/src/Xpetra_config.hpp
/* #undef HAVE_XPETRA_KOKKOS_REFACTOR */
$ grep -i refactor cuda-9.2-debug-Power9-Volta70/packages/muelu/src/MueLu_config.hpp
/* #undef HAVE_MUELU_KOKKOS_REFACTOR */
/* #undef HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT */

$ grep -i assume cuda-9.2-debug-Power9-Volta70/packages/tpetra/core/src/TpetraCore_config.h
/* Define when Tpetra assumes that the MPI implementation is CUDA aware */
/* #undef TPETRA_ASSUME_CUDA_AWARE_MPI */

$ grep -i refactor cuda-9.2-opt-Power9-Volta70/packages/xpetra/src/Xpetra_config.hpp
/* #undef HAVE_XPETRA_KOKKOS_REFACTOR */

$ grep -i refactor cuda-9.2-opt-Power9-Volta70/packages/muelu/src/MueLu_config.hpp
/* #undef HAVE_MUELU_KOKKOS_REFACTOR */
/* #undef HAVE_MUELU_KOKKOS_REFACTOR_USE_BY_DEFAULT */

$ grep -i assume cuda-9.2-opt-Power9-Volta70/packages/tpetra/core/src/TpetraCore_config.h
/* Define when Tpetra assumes that the MPI implementation is CUDA aware */
```

it gave the test results:

**cuda-9.2-debug-Power9-Volta70/ctest.out:**
```
99% tests passed, 3 tests failed out of 203

Subproject Time Summary:
MueLu     = 4682.58 sec*proc (45 tests)
Panzer    = 9546.08 sec*proc (158 tests)

Total Test time (real) = 1806.09 sec

The following tests FAILED:
	 13 - MueLu_UnitTestsTpetra_MPI_4 (Timeout)
	177 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 (Failed)
	181 - PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 (Timeout)
Errors while running CTest
```

**cuda-9.2-opt-Power9-Volta70/ctest.out:**
```
99% tests passed, 3 tests failed out of 203

Subproject Time Summary:
MueLu     = 4712.23 sec*proc (45 tests)
Panzer    = 9671.95 sec*proc (158 tests)

Total Test time (real) = 1813.14 sec

The following tests FAILED:
	 13 - MueLu_UnitTestsTpetra_MPI_4 (Timeout)
	177 - PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4 (Failed)
	181 - PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3 (Timeout)
```

So comparing to using the Kokkos refactor options [above](https://github.com/trilinos/Trilinos/pull/3482#issuecomment-423669406) and the Kokkos refactor + assume MPI CUDA aware options [above](https://github.com/trilinos/Trilinos/pull/3482#issuecomment-423669406), you get the least MueLu and Panzer failures if you don't change anything :-(

**Comment by bartlettroscoe** [comment]
FYI: I hard reset this branch to remove the commit fbe17ab.

@fryeguy52, I think we should go ahead and do some more detailed testing turning these options on on a few platforms to see how it looks.  Since the EMPIRE Trilinos build is using these options, we really have no choice but to enable them.

**Comment by csiefer2** [comment]
#saddayforpeoplewhodontusebash

**Pull request closed without merging**
