### PR TITLE
Intrepid2: fix shadowed ExecutionSpace using

### PR DESCRIPTION
**Pull request by japlews**
@trilinos/intrepid2

## Motivation

Minor fix, shadowed using for ExecutionSpace already available in the class definition.

### CODE REVIEW

**Comment by japlews** [comment]
@mperego @jhux2, these are showing up in Sierra platform and compiler evaluation builds.

**Comment by jhux2** [comment]
@trilinos/intrepid2

**Review by CamelliaDPG — APPROVED** [review]
Looks good to me.  Thanks, @japlews!

**Comment by japlews** [comment]
@CamelliaDPG or @mperego, looks like automerge didn't get set. Would you merge this for me when you have a spare moment? Thanks!

**Comment by CamelliaDPG** [comment]
Thanks, @jhux2!

**Pull request merged**
