### PR TITLE
Belos GmresPolyOp: Avoid some FPEs.

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/belos 

## Motivation
Avoid some FPEs coming out of log10.

@jennloe

### CODE REVIEW

**Comment by jennloe** [comment]
@hkthorn could review??  I don't have write access.

**Comment by cgcgcg** [comment]
@jwillenbring Could we add @jennloe to the @trilinos organization?

**Comment by jwillenbring** [comment]
> @jwillenbring Could we add @jennloe to the @trilinos organization?

@cgcgcg I sent an invite.

**Comment by cgcgcg** [comment]
@jwillenbring Thanks!

**Pull request merged**
