### PR TITLE
zoltan2:  fixed ArrayView usage in graph metrics' directory calls

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/zoltan2 

## Description
When some processors have no IDs to partition or no graph edges, the graph metrics calculation core-dumped or caused a hang.  The culprit was attempts to compute the address of element 0 of an ArrayView of length zero.  I added tests for zero-length arrays before the attempted accesses.

## Motivation and Context
Test Zoltan2_zoltanCompare.exe failed in the metric computation for input graph nograph (which doesn't have edges).  These changes allow Zoltan2_zoltanCompare.exe to succeed.

## Related Issues
* Related to   #1533 

## How Has This Been Tested?
New tests are added that exercise the graph metrics in these conditions:
chacoGraphMetricTestNoGraph.xml -- tests graph metric computation on graph with no edges
chacoGraphMetricTestNoGraphNoDistribute.xml -- tests on graph with no edges and all input on rank 0
chacoGraphMetricTestNoDistribute.xml -- tests on graph with all input on rank 0
chacoGraphMetricTest.xml -- tests on graph with edge weights

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [ x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
`Teuchos::ArrayView` has a `.getRawPtr()` method.  See also https://github.com/trilinos/Trilinos/issues/2749.

**Comment by kddevin** [comment]
@mhoemmen From #4234, is it now safe to assume getRawPtr() returns NULL if a zero-length ArrayView is created?  The documentation says it returns NULL only if unsized, not if the specified size is zero.
https://trilinos.org/docs/dev/packages/teuchos/doc/html/classTeuchos_1_1ArrayView.html#a690d98de2e5ad95cfd11bb0a321485bd

**Comment by mhoemmen** [comment]
@kddevin wrote:
> From #4234, is it now safe to assume getRawPtr() returns NULL if a zero-length ArrayView is created?

If you create an ArrayView from a raw pointer and a length, yes.  I would prefer that code not assume this, however, because it is _not_ true for `std::vector` or other C++ Standard Library classes.  Begin and end iterators always make a valid range, but a valid empty range is `[p, p)` for any possibly nonnull pointer `p`.

**Comment by kddevin** [comment]
@mhoemmen Thanks.  It is probably best, then, to leave the code as-is.

**Comment by mhoemmen** [comment]
@MicheldeMessieres Yup, Intel license server is down.  Framework is working on it.

**Comment by mhoemmen** [comment]
@MicheldeMessieres wrote:
> But having to special case the 0 handling is also awkward.

I did fix `Teuchos::ArrayView` so that you can create it from an `std::vector` directly, without needing you to make the pointer null if the length is null.  (ArrayView now does that check for you.  I retained the existing behavior, that the pointer is always null if the length is null.  C++ Standard Library classes like `std::vector` and `std::span` do _not_ promise this, though, so be careful.)

**Pull request merged**
