### PR TITLE
Tempus: minor add to build App with Tempus ETI off

### PR DESCRIPTION
**Pull request by sconde**
this will avoid the multiple definition linking error

@trilinos/tempus 

## Motivation

To be able to build Drekar with Tempus ETI OFF.

### CODE REVIEW

**Review by rppawlo — DISMISSED** [review]

**Comment by ccober6** [comment]
@sconde I just merged #8549, so this should be able to go through now.

**Comment by sconde** [comment]
@rppawlo can you review this again please? It is now going directly into the develop branch

**Review by ccober6 — APPROVED** [review]
Looks good!

**Review by rppawlo — DISMISSED** [review]

**Comment by ccober6** [comment]
No longer an issue.  Closing.

**Pull request closed without merging**
