### PR TITLE
Anasazi: create tpetra version of ModalSolverUtils test

### PR DESCRIPTION
**Pull request by cwschilly**
@trilinos/anasazi 
@hkthorn 

This PR creates an updated version of ModalSolverUtils that uses `Tpetra` instead of `Epetra`

### CODE REVIEW

**Review by hkthorn — DISMISSED** [review]
LGTM.  Thanks!

**Comment by cwschilly** [comment]
Hello @hkthorn , I had to remove an unused variable to pass the -Werror pipeline. Could you please re-approve and add the testing label?

**Review by hkthorn — APPROVED** [review]
LGTM

**Comment by cwschilly** [comment]
Hello @hkthorn , I made another small change to this PR. Could you please re-approve and add the 'AT: PRE-TEST INSPECTED' label?

**Comment by sebrowne** [comment]
This branch MUST be rebased prior to merge given the 'develop' change (re-adds forbidden files).

**Review by sebrowne — DISMISSED** [review]
Please rebase to eliminate extraneous commits.

**Comment by cwschilly** [comment]
@hkthorn I have rebased this PR to remove the unwanted commits. Could you please re-approve and add the `AT:PRE-TEST INSPECTED` label?

**Review by hkthorn — APPROVED** [review]

**Review by hkthorn — APPROVED** [review]
LTGM

**Pull request merged**
