### PR TITLE
9184 winllvmparbuild: fix winllvm parallel builds with modification to muelu, zoltan2, belos

### PR DESCRIPTION
**Pull request by jrobcary**
@trilinos/belos
@trilinos/zoltan2
@trilinos/muelu

## Motivation
Failure to build on Windows with LLVM

Closes issues #8202 and #9184

The problems were:

Belos: uses addressof to create a constexpr, which is not allowed, but for which there is a workaround.

Zoltan2: Need to use time.h instead of sys/time.h on Windows.  Need to define ssize_t on Windows.

MueLu: Need implementation to get host-order IP address without using inet_network, which does not exist on windows.

### CODE REVIEW

**Comment by jrobcary** [comment]
For convenience, here is the test code:


[testinet.cxx.txt](https://github.com/trilinos/Trilinos/files/6561631/testinet.cxx.txt)

**Comment by jhux2** [comment]
@trilinos/belos @trilinos/zoltan2 @trilinos/muelu @csiefer2

**Review by jhux2 — APPROVED** [review]
Approving to start autotester.  Do not merge until all code owners have reviewed.

**Comment by csiefer2** [comment]
@kddevin  Any objections?

**Comment by jennloe** [comment]
@hkthorn probably needs to approve this for Belos.

**Review by kddevin — APPROVED** [review]
Zoltan2 changes are OK.

**Pull request merged**
