### PR TITLE
kokkos-kernels: Fix BLAS mangling

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @kyungjoo-kim 

## Description

Patch kokkos-kernels to fix BLAS mangling.  We'll also add these changes to kokkos-kernels.

## Motivation and Context

Sierra needs Trilinos to build with XL.

## Related Issues

* Related to https://github.com/kokkos/kokkos-kernels/issues/369

### CODE REVIEW

**Comment by mhoemmen** [comment]
@theguruat12 @rrdrake

**Comment by ibaned** [comment]
This breaks all downstream apps that disable Fortran with
```
fatal error: KokkosKernels_FortranMangling.h: No such file
```

**Comment by mhoemmen** [comment]
@ibaned Wow, that's terribly annoying.  I thought CMake would at least give a helpful configure-time error if it didn't have Fortran.  OK, let me revert this change and figure out what to do if not building with Fortran.

**Comment by ibaned** [comment]
@mhoemmen thanks!

**Comment by mhoemmen** [comment]
FYI, CMake does actually give a configure-time error :-)  Also, please don't delete the branch -- I plan on fixing this.

**Pull request merged**
