### PR TITLE
Local ordinal long (#454)

### PR DESCRIPTION
**Pull request by cihanuq**
These commits add ETI support for LO=long and GO=long and fixes MueLu issues when using LO != int, see issue #454

### CODE REVIEW

**Comment by jwillenbring** [comment]
CC: @trilinos/muelu

**Comment by mhoemmen** [comment]
@cihanuq Thanks for working on this!  Some of the changes are good ideas anyway (e.g., using int in LAPACK, since LAPACK libraries may not support 64-bit integer types in their interfaces).  It may make sense for us to break this up into a sequence of commits so we can test packages individually.  We can work on that unless you want to.

**Comment by mhoemmen** [comment]
Thanks for working on this, @cihanuq !  No hurry, just feel free to post here once you're ready for us to review changes.

**Comment by cihanuq** [comment]
Just letting you know that I probably won't have time to work on this in the near future as I'm off to a new job but we have been building and using Trilinos from this branch successfully so anything you can migrate over would be nice for our users.

**Comment by mhoemmen** [comment]
@cihanuq Thanks for the heads-up!  I appreciate your work on this.  I've been working on some urgent things this summer and haven't had a chance to evaluate your branch yet.  Will take a look soon.  Best wishes with your new job!

**Comment by mhoemmen** [comment]
@cihanuq btw what packages do your users care most about?

**Comment by cihanuq** [comment]
@mhoemmen Thanks and no worries! We are using Tpetra, Belos, Amesos2, Ifpack2 and MueLu.

**Comment by mhoemmen** [comment]
> Thanks and no worries! We are using Tpetra, Belos, Amesos2, Ifpack2 and MueLu.

@cihanuq Thanks for the list!  That limits my concerns what might break if I add this feature.  I'll take a look at the pull request as soon as I can.

**Comment by mhoemmen** [comment]
I haven't had a chance to look at this in detail.  Let me express some concerns:

  1. This won't work for Kokkos::Cuda right now, given that Kokkos::Cuda's default size_type is int.
  2. Furthermore, Kokkos would need more extensive testing with very large arrays before I'm convinced that it works correctly with 64-bit local ordinal types.
  3. A correct implementation would need to use a 64-bit BLAS and LAPACK interface.
  4. Anasazi and Belos might need a redesign in order to choose the local ordinal type according to the linear algebra library, rather than just using int.

For these reasons, I've decided to defer accepting this pull request.

**Comment by mhoemmen** [comment]
Closing due to out-of-date-ness, but keeping for reference.  I'm not entirely convinced that even Kokkos is currently fully correct for the case of 64-bit local indices, especially on GPUs.  This would take a very large effort to revive.  I would rather not have `LO = long long` compile until we've shown via extensive testing that it's correct.

**Pull request closed without merging**
