### PR TITLE
MueLu: in Hierarchy::Iterate(), cache the result of description() and…

### PR DESCRIPTION
**Pull request by CamelliaDPG**
MueLu: in `Hierarchy::Iterate()`, cache the result of `description()` and `ShortClassName()`, and use a new Monitor constructor that accepts strings instead of calling these.  

Details:
`description()` calls `GetGlobalNumLevels()` and `GetOperatorComplexity()`, both of which have nontrivial cost.  `GetGlobalNumLevels()` in particular performs an `MPI_Reduce`.  In cases where there are many calls to `Iterate()` for a relatively small matrix, these calls have a measurable cost as a percentage of the overall solve time.

Similarly, `ShortClassName()` results in a call to `Teuchos::demangleName()`, which as previously noted (in issue #1432) has measurable cost.

### CODE REVIEW

**Comment by CamelliaDPG** [comment]
@trilinos/muelu

**Comment by CamelliaDPG** [comment]
Hmm… I was attempting to squash two commits into one, and somehow managed to get 8 commits out.  Sorry about that.  The relevant changes are in commit fa5530e4af11c3d8947206521fafcf33bf67fe9c.

@aprokop, thank you for your review--that makes sense.  I think this revision addresses your concerns.  Do you agree?

In this revision, the description gets cached when `description()` is called, and reset during `Hierarchy::Setup()`, `Hierarchy::SetupRe()`, and `HierarchyManager::SetupHierarchy()`.  The result of `ShortClassName()` is cached for the lifetime of the `Describable` object.  Because now both `ShortClassName()` and `description()` are simply returning the cached value, there is no longer any need to create a separate constructor for `Monitor`.

This design should be more efficient all around, and cleaner, than my previous version.  The question is whether there are any cases in which a Hierarchy can be reused in a way that will invalidate the description without a call to `Setup()`, `SetupRe` or `HierarchyManager::SetupHierarchy()`.  

(I have, by the way, run the MueLu tests with this version.  They pass--though that was also true of the previous version.)

**Comment by CamelliaDPG** [comment]
@aprokop Sorry for the noisy PR; I keep trying to squash commits and getting the opposite result—I do seem to have had success last time squashing things on their way from my branch back into develop, so there is reason for optimism that I won't muck up the git log when I do the actual push.  I have now incorporated your proposed revisions.  Would you please take another look?  If it looks OK, I'll run the check-in script.  Thanks!

**Comment by aprokop** [comment]
@CamelliaDPG You can simply do the following:
```bash
$ git checkout develop
$ git pull develop
$ git checkout MueLuHierarchyPerformanceTweaks
$ git rebase develop
$ git push -f
```

This would force-update this PR, but will skip the commits on develop. And I think in general, you should not squash commits when PR is still in review, just push commits on top of it. This way, a reviewer sees progress and can look at the last commits individually.

Overall, the PR looks good to me. Would be super nice if you added a unit test for this feature if it's not too much effort. But don't think that's absolutely necessary.

**Comment by CamelliaDPG** [comment]
@aprokop Thanks!  I did write a short unit test, and am running the check-in script now.

**Comment by CamelliaDPG** [comment]
@aprokop @jhux2 @csiefer2 When running the check-in script, everything passes except for the final pull.  pullFinal.out has the following:
```
Already up-to-date.
Interactive rebase already started
```
There appear to be no further details.  I have tried running several times, each time with the same result.  Manual pulls succeed.  I have also tried adding `--force-push`, but this fails in the same way.  Shall I just do a `git push`?  Or is there something else you would advise?  Thanks!

**Comment by tawiesn** [comment]
Seems that you've tried to rebase which failed. Have you tried 

> git rebase --abort

and tried it again?

**Comment by aprokop** [comment]
@CamelliaDPG You may want to add some indicator to you PS1 prompt to indicate the git status. There are multiple ways available, I use [this](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh). This would allow you to more clearly figure things out.

**Comment by CamelliaDPG** [comment]
Thanks, @tawiesn and @aprokop!  @tawiesn's suggestion worked; the push succeeded.  And I have also taken @aprokop's advice and used `git-prompt.sh` to give me some clearer feedback at the command line as to what state my git repo is in.

**Comment by jmgate** [comment]
> @CamelliaDPG You may want to add some indicator to you PS1 prompt to indicate the git status. There are multiple ways available, I use [this](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh). This would allow you to more clearly figure things out.

You could also try [LiquidPrompt](https://github.com/nojhan/liquidprompt), though some think it overkill.

**Comment by CamelliaDPG** [comment]
Changes incorporated and pushed; closing.

**Pull request closed without merging**
