### PR TITLE
Zoltan2: Split Zoltan2 into Zoltan2Core and Zoltan2Sphynx (empty for now)

### PR DESCRIPTION
**Pull request by seheracer**
@trilinos/zoltan2 @kddevin @egboman @srajama1 

## Motivation

This PR adds two new packages: 
-- Zoltan2Core: Usual Zoltan2. The source code of Zoltan2 has been moved to Zoltan2Core.
-- Zoltan2Sphynx: New partitioner Sphynx. This package is empty for now and will have the source code after the SNL copyright is complete.

With this change, Zoltan2 does not have any source code anymore, but only serves as an encapsulating package for Zoltan2Core and Zoltan2Sphynx. Zoltan2 has a required dependency to Zoltan2Core and an optional dependency to Zoltan2Sphynx. 

Tests and examples of Zoltan2 remain to belong to Zoltan2 (i.e., not moved to Zoltan2Core). This means the Zoltan2 testing configuration shouldn't change for any users.

This Zoltan2 split is needed to break a circular dependency problem between Zoltan2 and MueLu. This problem arises once Sphynx is added to Zoltan2, because Sphynx depends on MueLu. 

## Stakeholder Feedback

No changes to current users. The only change is that libzoltan2.a is now placed in `${BUILD_DIR}/packages/zoltan2/core/src/` and previously it was in `${BUILD_DIR}/packages/zoltan2/src/`.

## Testing

Zoltan2 tests are passing in the CUDA build with the following configuration script:
```
cmake \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
-DCMAKE_BUILD_TYPE:STRING=RELEASE \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Tpetra_INST_CUDA:BOOL=ON \
-D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
-D Tpetra_INST_INT_INT:BOOL=OFF \
-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_TESTS:BOOL=OFF \
-DTrilinos_ENABLE_EXAMPLES:BOOL=OFF \
-DTPL_ENABLE_MPI:BOOL=ON \
-DTPL_ENABLE_CUDA:BOOL=ON \
-DTPL_ENABLE_ParMETIS:BOOL=ON \
-DTPL_ENABLE_METIS:BOOL=ON \
-DKokkos_ENABLE_CUDA:BOOL=ON \
-DTpetra_ENABLE_CUDA:BOOL=ON \
-DKokkos_ENABLE_CUDA_LAMBDA:BOOL=ON \
-DKokkos_ENABLE_CUDA_UVM:BOOL=ON \
-DZoltan2_ENABLE_TESTS:BOOL=ON \
-DZoltan2_ENABLE_EXAMPLES:BOOL=ON \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_Xpetra:BOOL=ON \
-DTrilinos_ENABLE_Epetra:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DMueLu_ENABLE_Kokkos_Refactor:BOOL=ON \
-DTrilinos_EXTRA_LINK_FLAGS:STRING="-lcusolver" \
../
```
Output:
```
...
100% tests passed, 0 tests failed out of 112

Subproject Time Summary:
Zoltan2    = 1548.08 sec*proc (112 tests)
```

### CODE REVIEW

**Comment by seheracer** [comment]
@kddevin @srajama1 @egboman Do you know how to eliminate this configuration error:
https://testing.sandia.gov/cdash/viewConfigure.php?buildid=7247940

```
CMake Error at cmake/RepositoryDependenciesSetup.cmake:64 (MESSAGE):
  STKBalance requires long or long long global indices, but Trilinos is using
  int indices (likely via Tpetra_INST_INT_INT or Tpetra_INST_INT_UNSIGNED).
  Disable STKBalance or specify Tpetra_INST_INT_LONG_LONG.
```

This build enables Ifpack2, MueLu and STKBalance (because this PR changes their dependencies from Zoltan2 to Zoltan2Core and their HAVE_<PACKAGENAME>_ZOLTAN2 macros) but it does not enable Tpetra_INST_INT_LONG_LONG for some reason.

**Comment by kddevin** [comment]
This error is likely related to #7490 .
@alanw0 @seheracer

**Comment by alanw0** [comment]
@seheracer @kddevin Yes, I've had a PR (#7490) attempting to go through for about a week now which does nothing more than turn off stk-balance for this build (intel-17). But it keeps failing for unrelated reasons (unrelated packages fail testing on other builds). I also have a commit (not yet pushed) that will allow stk-balance to work with int, no longer require long or long-long. But at this point I have no idea how to get any PR to go through.

**Comment by seheracer** [comment]
I just checked; `make install` copies the Zoltan2 libraries and header files in `$INSTALL_DIR/lib` and `$INSTALL_DIR/include`, respectively, as expected.

**Comment by kddevin** [comment]
@trilinos/framework @trilinos/zoltan2 @trilinos/zoltan 
Frameworks gurus:  PR #7584 adds a new test file zdrive.inp.color-gids, exercising the code change that was made in #7584.  The new file seems to be available to this PR's testing, and is causing test failures (as it would without the code change in #7584).  

Since #7584 has not yet merged to develop, why would files added by #7584 be available to this PR? 
 
I suspect the build directory was not cleaned, and a copy of this file persisted in the build directory and thus was run.  If the build directory is cleaned, this zdrive.inp.color-gids file will go away and not interfere with other PR's testing.

**Comment by jwillenbring** [comment]
I applied the flag to start with clean PR testing workspaces. We will see if that resolves this issue.

**Comment by seheracer** [comment]
> I applied the flag to start with clean PR testing workspaces. We will see if that resolves this issue.

Thanks, @jwillenbring !

**Comment by lucbv** [comment]
@kddevin 
There was a similar issue in MueLu PR #7552 this was discussed [here](https://github.com/trilinos/Trilinos/issues/3276#issuecomment-647592892), eventually it was suggested to use [TRIBITS_ADD_ADVANCED_TEST()](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-add-advanced-test) .
Hopefully this helps a bit to avoid having "rogue" test file linger in build directories?

**Comment by seheracer** [comment]
https://github.com/trilinos/Trilinos/pull/7584 has been merged. This will hopefully solve the problem in the next autotest (because the file zdrive.inp.color-gids was due to https://github.com/trilinos/Trilinos/pull/7584).

**Pull request merged**
