### PR TITLE
Automatic snapshot commit from seacas at 729e904fa5

### PR DESCRIPTION
**Pull request by gsjaardema**
Origin repo remote tracking branch: 'origin/master'
Origin repo remote repo URL: 'origin = https://github.com/gsjaardema/seacas'

At commit:

commit 729e904fa5ce3905da73a9856c17f30f1be5ffab
Author:  Greg Sjaardema <gsjaardema@gmail.com>
Date:    Fri Jan 22 07:46:47 2021 -0700
Summary: Merge pull request #210 from ibaned/hdf5-targets

* EPU: Enum class instead of enum in many places
* EPU: Support for `szip` compression in addition to `zlib`
* EPU: Support for `netcdf5` output
* EPU: Assembly support
* EPU: Now uses `original_global_id_map` if present.
* EXODIFF: Better diagnostics in mapping failures
* EXODIFF: Edge block and face block support
* EXODIFF: Warning fixes
* NAS2EXO: New application
* NEMSLICE: integer size issues
* SLICE: Fix partial input/output issue
* APREPRO: Eliminate potential duplicat symbol issues in getline
* EXODUS: SZIP support if present in netCDF
* EXODUS: Assembly names can be read via ex_get_names
* EXODUS: fix some tests on netCDF symbols (if vs ifdef)
* IOSS: Avoid some symbol clashes
* IOSS: Fix parallel exodus append (needs netCDF patch though)
* IOSS: Szip support
* IOSS: enum class instead of enum several places
* IOSS: integer size issue in transform
* IOSS: Use hash classes instead of std::unorderd_map to speed up some areas
* IOSS: avoid symbol clash in getline
* IOSS: windows build fixes
* IOSS: add option to output a sideset with boundary faces to io_shell
* PYTHON: fixes for assemblies
* FMT: New version
* CATCH2: new version
* HASH: New versions
* Eliminate shadow warnings

@trilinos/<teamName>

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@prwolfe, we me transiting off ATDM shortly here, can you take over reviewing and approving these SEACS PRs for @gsjaardema?  Are there other reviewers that @gsjaardema could add to the requested reviewers list to help out reviewing SEACS PRs?

CC: @jwillenbring, @trilinos/framework, @e10harvey

**Comment by prwolfe** [comment]
> @prwolfe, we me transiting off ATDM shortly here, can you take over reviewing and approving these SEACS PRs for @gsjaardema? Are there other reviewers that @gsjaardema could add to the requested reviewers list to help out reviewing SEACS PRs?
> 
> CC: @jwillenbring, @trilinos/framework, @e10harvey

I'm happy to look at them - you just usually get to them before I get in to the office. As for others to add, I think we should look at which packages utilize SEACAS and point at their owners. From a quick git grep I see moertel, pamgen, panzer, percept, stk, and tempus as candidates.

Paul

**Comment by prwolfe** [comment]
Gregg,

There are 2 failures in testing. One is a framework issue we brought up at standup yesterday that I believe @william76 is looking into (proxy failures when attempting to contact a pip repository.) The other is a compile failure in the intel 17 build. 

Paul

**Review by prwolfe — APPROVED** [review]

**Comment by prwolfe** [comment]
I am still working through the python3 issue and this will need retested when that is merged.

**Comment by gsjaardema** [comment]
There seem to be some strange random  failures in some suplib fortran routines that haven't changed.  The failing files change from build to build on intel-17.

**Pull request merged**
