### PR TITLE
KokkosKernels: Add missing dependency on CUBLAS (#10807)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
### Next Action Status

Waiting for problems with Trilinos or PR builds to be resolved (see #10858) before PR will pass PR builds ...

### Internal issues

* [TRILINOSHD-159](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-159)

### Description

This should fix link errors on an ATS2 configuration missing cublas link symbols (see #10807).

The matching PR for the separate kokkos-kernels repo is:

* https://github.com/kokkos/kokkos-kernels/pull/1481

I would recommend that this PR gets merged right away and also merge the kokkos-kernels PR https://github.com/kokkos/kokkos-kernels/pull/1481 so that the next time kokkos-kernels gets snapshotted into Trilinos 'develop', then it will not overwrite the changes from  https://github.com/trilinos/Trilinos/pull/10808.

### CODE REVIEW

**Comment by vqd8a** [comment]
@bartlettroscoe Thank you. It fixes the CUBLAS link errors.

**Review by lucbv — APPROVED** [review]
Looks good, the change is also approved and being merged in Kokkos Kernels develop

**Comment by lucbv** [comment]
I'm not sure who is in charge of this type of things, but it would make sense to add me as member of the kokkos-kernels team and remove jeremy.
@jwillenbring do you know who should do that?

**Comment by jwillenbring** [comment]
> I'm not sure who is in charge of this type of things, but it would make sense to add me as member of the kokkos-kernels team and remove jeremy.
> @jwillenbring do you know who should do that?

I can.  Done.

**Review by lucbv — DISMISSED** [review]

**Comment by lucbv** [comment]
Thanks @jwillenbring

**Comment by bartlettroscoe** [comment]
NOTE: Only results for two builds for the PR iteration [above](https://github.com/trilinos/Trilinos/pull/10808#issuecomment-1206861251) actually showed up on CDash.

**Comment by bartlettroscoe** [comment]
FYI: My best attempt to reproduce the build error:

```
<trilinosDir>/packages/thyra/adapters/epetra/test/EpetraOperatorWrapper/EpetraOperatorWrapper_UnitTests.cpp(54): catastrophic error: cannot open source file "Trilinos_Util_CrsMatrixGallery.h"
  #include "Trilinos_Util_CrsMatrixGallery.h"
                                             ^
```

for the 'vortex' builds was given in https://github.com/trilinos/Trilinos/issues/10842#issuecomment-1208682513 and I failed (i.e. I could not get a failure, it passed).

I used the exact same versions of the repos.

**Comment by bartlettroscoe** [comment]
FYI: Current status: Many errors in PR builds that can't be reproduced manually and are illogical. Next: Waiting for Trilinos Framework team or someone else to get to the bottom of what is happening ...

**Comment by bartlettroscoe** [comment]
At this point, I am not going to add the `AT: RETEST` label anymore.  The PR builds are failing the same way every time for like 9 PR build attempts over the last 2 weeks.  There is no sense in beating a dead horse.

Someone is going to have to debug the PR testing system to determine what is happening here.

**Comment by bartlettroscoe** [comment]
NOTE: I removed `AT: RETEST` and please don't set again until issue #10842 is resolved (which we now know what is causing this and will formulate a solution and get it merged to 'develop' which will fix your PR builds the next time they run).

**Comment by bartlettroscoe** [comment]
FYI: I merged the branches from PRs #10871 and #10872 into this PR topic branch so that they can be tested for real.

**Comment by bartlettroscoe** [comment]
FYI: The test failure [TpetraTSQR_SequentialTsqr_contiguousCacheBlocks_MPI_1](https://trilinos-cdash.sandia.gov/test/10269121) shown on CDash for the build [PR-10808-test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables-407](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=378014&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and) is nonsense. That test never even ran.  See https://github.com/trilinos/Trilinos/pull/10871#issuecomment-1214277434.

**Comment by bartlettroscoe** [comment]
@lucbv, can you please reapprove this PR?  The PRs #10871 and #10872 who's topic branches have been merged to this PR branch (so they could be tested) have both been approved to merged (and PR #10872 has already been merged).

This PR should not pass all or the PR builds now that /tmp/ has been cleared out on 'ascic142' (see #10875).

**Review by lucbv — APPROVED** [review]
Still looks fine

**Comment by bartlettroscoe** [comment]
NOTE: And a new set of failures the the last PR testing iteration [above](https://github.com/trilinos/Trilinos/pull/10808#issuecomment-1217401222) that had nothing to do with the PR changes itself (see #10893).  This PR is never going to get merged at this rate.

**Pull request merged**
