### PR TITLE
Corrected functions to compile with VS2022

### PR DESCRIPTION
**Pull request by ViNN280801**
@trilinos/kokkos

## Motivation
This change addresses a compilation issue under MSVC in Visual Studio 2022. The compiler reports a C2535 error indicating that two overloaded functions are identical, despite having different `enable_if` conditions. Adding additional conditions to the `enable_if` clauses ensures that the MSVC compiler can distinguish between the two overloaded functions.

## Testing
The changes have been tested locally to ensure that they resolve the compilation issue without affecting the functionality of the code. The functions are covered by existing unit tests in the Kokkos package.

### Request for Improved Windows Support

During the process of compiling Trilinos on Windows, I encountered numerous issues related to the build system and compatibility with MSVC in Visual Studio 2022. These challenges included but were not limited to:

- Overloaded functions causing compilation errors under MSVC.
- Long file path issues that required registry modifications: (Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open source file: 'C:\Users\vladislavsemykin\Downloads\Trilinos\Trilinos\build\packages\kokkos-kernels\sparse\eti\generated_specializations_cpp\gauss_seidel_symbolic\Sparse_gauss_seidel_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_SERIAL_MEMSPACE_HOSTSPACE.cpp': No such file or directory	kokkoskernels	C:\Users\vladislavsemykin\Downloads\Trilinos\Trilinos\build\packages\kokkos-kernels\sparse\eti\generated_specializations_cpp\gauss_seidel_symbolic\Sparse_gauss_seidel_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_SERIAL_MEMSPACE_HOSTSPACE.cpp	1		
). I have this file, but still getting an error, so, I guess that naming is too long.
- Difficulty in configuring CMake with the appropriate include and library paths.
- and other issues, even "syntax errors" (though I compile it in C++20 and C17 (all the projects)).

Given the increasing use of Windows as a development platform, I kindly request the Trilinos development team to consider making the build process more accessible and robust for Windows users. Enhancements such as detailed Windows-specific build instructions, automated scripts to handle common issues, and pre-configured environment setups would greatly benefit the community.

Thank you for considering this request, and please let me know if there is anything I can do to assist with improving the Windows build process.

### CODE REVIEW

**Comment by cgcgcg** [comment]
@ViNN280801 Please open a PR with these changes directly against https://github.com/kokkos/kokkos. For the Kokkos-Kernels specific issue, please report it here: https://github.com/kokkos/kokkos-kernels. We do not test Trilinos on Windows, but since you are building there: would you mind giving more details on the other issues you are seeing? In particular, what syntax errors are there?

**Comment by ViNN280801** [comment]
> @ViNN280801 Please open a PR with these changes directly against https://github.com/kokkos/kokkos. For the Kokkos-Kernels specific issue, please report it here: https://github.com/kokkos/kokkos-kernels. We do not test Trilinos on Windows, but since you are building there: would you mind giving more details on the other issues you are seeing? In particular, what syntax errors are there?

Okay, I'll do that. As for syntax errors, I'm sure it's because of some compiler settings. Because I successfully compiled the entire Trilinos on Fedora 34 and Debian 12, but now I needed to do it on Windows and it turned out to be problematic. Examples of the "syntax errors":
31>C:\<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(33,107): error C2146: syntax error: missing ')' before identifier 'A'
31>C:\<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(33,107): error C3646: 'A': unknown override specifier
31>C:\<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(33,108): error C2988: unrecognizable template declaration/definition
31>C:\<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(33,108): error C2059: syntax error: ','
31>C:\<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(34,91): error C2059: syntax error: ')'
31>C:\<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(34,93): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
31>C:\<MYPATH>\Trilinos\Trilinos\packages\shylu\shylu_node\tacho\src\impl\Tacho_Lapack_Team.hpp(69,107): error C2146: syntax error: missing ')' before identifier 'A'

false positives of some kind.

**Comment by cgcgcg** [comment]
@ViNN280801 Could you try replacing `__restrict__` with `KOKKOS_RESTRICT` and see if that fixes it?

@iyamazaki FYI.

**Comment by ViNN280801** [comment]
> @ViNN280801 Could you try replacing `__restrict__` with `KOKKOS_RESTRICT` and see if that fixes it?
> 
> @iyamazaki FYI.

image

just the same

**Comment by cgcgcg** [comment]
@ViNN280801 I think you might have replaced `KOKKOS_RESTRICT` with `__restrict__`, not the other way around. `KOKKOS_RESTRICT` is a macro that resolves to `__restrict` on Windows, see https://github.com/trilinos/Trilinos/blob/19640f36be2fca0d02ba096dda34b91b5c55878a/packages/kokkos/core/src/Kokkos_Macros.hpp#L195-L199

**Comment by ViNN280801** [comment]
yes, this solved some of the problems, but I'm still in the process of building for Windows, as soon as it works, I'll provide instructions on how I managed to do it.

**Comment by cgcgcg** [comment]
@ViNN280801 Thanks!

**Comment by ndellingwood** [comment]
The Kokkos changes would need submission of corresponding PR to https://github.com/kokkos/kokkos , and acceptance to the repo before acceptance+merging to Trilinos; adding @dalg24 @crtrott @masterleinad for tracking

**Comment by ViNN280801** [comment]
So, I collected some information that I've done to compile almost all the packages (Amesos2, Belos, Intrepid2, Kokkos, KokkosKernels, NOX, ROL, RTOp, Sacado, Shards, Stokhos, Stratimikos, Tacho, Teuchos, Tempus, Thyra, Tpetra, MiniTensor, Adelus, SEACAS, ShyLU, Galeri). I had a lot of compilation issues with C++ std version (changed for all the projects to C++20), problems with FMT support of the utf-8 (added flag `/utf-8` to packages that uses FMT). And as I understand in Windows ENVs are not so good as in Linux, and I had to add to multiple packages include&library directories of FMT and MPI. For example:
image
image
image
image

VS22 printed to me unresolved links and some issues like "Cannot find `mpi.h`" for <...> package, and I corrected each package manually, like I showed it above.

After the build I have the setup file
image


What about the code, I changed some files, and I wrote these files with changes:

[Fixing fmt issue constant expr in e.txt](https://github.com/user-attachments/files/16522414/Fixing.fmt.issue.constant.expr.in.e.txt)
[Fixing fmt problem in pe_input.C.txt](https://github.com/user-attachments/files/16522415/Fixing.fmt.problem.in.pe_input.C.txt)
[Modification fmt code in sys_info.C suplib_cpp project.txt](https://github.com/user-attachments/files/16522416/Modification.fmt.code.in.sys_info.C.suplib_cpp.project.txt)
[Replaced return type in Intrepid2_DerivedBasis_HVOL_QUAD.hpp.txt](https://github.com/user-attachments/files/16522417/Replaced.return.type.in.Intrepid2_DerivedBasis_HVOL_QUAD.hpp.txt)
[Added enable_if to Tpetra_Import_Util2.hpp.txt](https://github.com/user-attachments/files/16522418/Added.enable_if.to.Tpetra_Import_Util2.hpp.txt)
[Replaced enable_if in Kokkos_View.hpp.txt](https://github.com/user-attachments/files/16522419/Replaced.enable_if.in.Kokkos_View.hpp.txt)

I compile the Trilinos with MSYS2 using the following command (added some flags like utf-8 and c++20 std):
```bash
cmake -G "Visual Studio 17 2022" \
      -DCMAKE_BUILD_TYPE=Release \
      -DTrilinos_ENABLE_TESTS=OFF \
      -DTrilinos_ENABLE_ALL_PACKAGES=ON \
      -DTPL_ENABLE_MPI=ON \
      -DTrilinos_ENABLE_Epetra=OFF \
      -DTrilinos_ENABLE_EpetraExt=OFF \
      -DTrilinos_ENABLE_Tpetra=ON \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DMPI_EXEC="C:/Program Files/Microsoft MPI/Bin/mpiexec.exe" \
      -DMPI_C_COMPILER="C:/msys64/mingw64/bin/mpicc.exe" \
      -DMPI_CXX_COMPILER="C:/msys64/mingw64/bin/mpicxx.exe" \
      -DCMAKE_C_FLAGS="/std:c17" \
      -DCMAKE_CXX_FLAGS="/std:c++20 /utf-8" \
      -DCMAKE_INCLUDE_PATH="$ENV{INCLUDE}" \
      -DCMAKE_LIBRARY_PATH="\"C:/Program Files/fmt/lib\";\"C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64\"" \
      -DCMAKE_EXE_LINKER_FLAGS="/LIBPATH:\"C:/Program Files/fmt/lib\" /LIBPATH:\"C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64\"" \
      ..
```

But before I did this:
```bash
pacman -Syu
```

```bash
pacman -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-cmake mingw-w64-x86_64-msmpi 
```

```bash
mingw-w64-x86_64-openblas mingw-w64-x86_64-blas mingw-w64-x86_64-netcdf mingw-w64-x86_64-lapack
```

Windows have a constraint with length of the files (260 if I correctly understand), so to shorten the paths, at first I turned on long paths using group policy (**gpedit.msc**), and moved to the C:/ dir:

```
# Move `Trilinos` dir to the C:/ to shorten the length of paths
cd /c/Trilinos
```

Last point is the __restrict__ keyword that ruins some packages:
# Tacho_Lapack_Team.hpp -> replace `__restrict__` with macro `KOKKOS_RESTRICT` (25 occurences)
# Tacho_Blas_Team.hpp -> replace `__restrict__` with macro `KOKKOS_RESTRICT` (65 occurences)
# Tacho_LDL_Eternal.hpp -> replace `__restrict__` with macro `KOKKOS_RESTRICT` (7 occurences)
# Tacho_LU_Eternal.hpp -> replace `__restrict__` with macro `KOKKOS_RESTRICT` (4 occurences), ...
# Just replace within entire solution (Alt+A in VS22)

As a result result I have Trilinos here:
image
image
image
image

I checked my installation on my project, and everything seems to be fine:

```bash
cmake -G "Visual Studio 17 2022" `
      -DMPIEXEC_EXECUTABLE:FILEPATH="C:/Program Files/Microsoft MPI/Bin/mpiexec.exe" `
      -DMPI_C_HEADER_DIR:PATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Include" `
      -DMPI_CXX_HEADER_DIR:PATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Include" `
      -DMPI_C_LIB_NAMES:STRING="msmpi" `
      -DMPI_CXX_LIB_NAMES:STRING="msmpi" `
      -DMPI_msmpi_LIBRARY:FILEPATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64/msmpi.lib" `
      -DMPI_C_LIBRARIES:FILEPATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64/msmpi.lib" `
      -DMPI_CXX_LIBRARIES:FILEPATH="C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64/msmpi.lib" `
      -DMPI_C_COMPILER="cl.exe" `
      -DMPI_CXX_COMPILER="cl.exe" `
      ..
```

VS22 sees includes:

image

**Comment by ViNN280801** [comment]
And I have a user-friendly suggestion - it'll be very convenient if Trilinos has precompiled files for different architechtures, like mpi, tbb, gmsh, and others have. Because:

1) Compiling Trilinos is very difficult, comprehensive process that takes an incredibly long time;
2) It's not so convenient to compile it manually (yes, it's cool CMake/Make experience, I agree with it)
3) This will allow you to have different versions of pre-compiled packages for different architectures

**Comment by jhux2** [comment]
This PR should be set to merge against `develop`, not `master`.

**Comment by iyamazaki** [comment]
Thank you for the changes, @ViNN280801!! I am locally building just to be sure. So, the main changes are to replace `__restrict__` with `KOKKOS_RESTRICT` in Tacho?

**Review by iyamazaki — APPROVED** [review]
Thank you, @ViNN280801! I could also build and run example on V100.

**Comment by dalg24** [comment]
Presumably you want to target the develop branch though?

**Comment by ViNN280801** [comment]
@dalg24, yes, of course. @cgcgcg suggested me to opennew PR, I don't know have you seen it already or not (https://github.com/trilinos/Trilinos/pull/13342), in that PR I consider only this problem with `__restrict__`/`__restrict` keyword and compilation. And that PR is for `develop` branch.

**Comment by ViNN280801** [comment]
And I wanted to ask u about helping with such kind of problems.

image

Do you need to fix these problems for the Windows? I think, I can help you with this (compile Trilinos without error using MSVC Visual Studio 17 2022)

**Comment by iyamazaki** [comment]
Sorry.. I thought it has been already changed, can you switch to merge into `develop` branch.

**Comment by ViNN280801** [comment]
> Sorry.. I thought it has been already changed, can you switch to merge into `develop` branch.

done!

**Review by iyamazaki — APPROVED** [review]

**Pull request merged**
