### PR TITLE
Add compiler flag for Visual Studio builds.

### PR DESCRIPTION
**Pull request by mplooster**
@trilinos/framework 

Added the /bigobj flag for Visual Studio builds. Without this flag,
it is impossible to get a debug build. See issue #1159.

### CODE REVIEW

**Comment by mplooster** [comment]
@bartlettroscoe I was able to get a debug build on Windows after making this change.

**Comment by mplooster** [comment]
@bartlettroscoe Scratch that last comment. Turns out I had a dirty build and this commit doesn't solve the problem. I will make another commit that addresses it soon.

**Comment by mplooster** [comment]
I'm not sure this flag can be added in the Trilinos top-level CMake file because MSVC is not defined until _after_ the TRIBITS_PROJECT() macro has run, which is too late for it to be of any use. Unless someone knows of another CMake/TriBits variable that can help, I suspect this change will need to be made somewhere in TriBits.

**Comment by bartlettroscoe** [comment]
> I'm not sure this flag can be added in the Trilinos top-level CMake file because MSVC is not defined until after the TRIBITS_PROJECT() macro has run, which is too late for it to be of any use

Then add it to `Trilinos/cmake/CallbackSetupExtraOptions.cmake`:

* https://tribits.org/doc/TribitsDevelopersGuide.html#repodir-cmake-callbacksetupextraoptions-cmake

That way it will be available to other TriBITS projects as well that pull in Trilinos.

TriBITS provides a number of project/repository/package specific call back points.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#full-tribits-project-configuration

**Comment by mplooster** [comment]
> Then add it to Trilinos/cmake/CallbackSetupExtraOptions.cmake:
> 
> https://tribits.org/doc/TribitsDevelopersGuide.html#repodir-cmake-callbacksetupextraoptions-cmake
> That way it will be available to other TriBITS projects as well that pull in Trilinos.

Cool!

Unfortunately, that is still to early. In the link you supplied, the CallbackSetupExtraOptions.cmake file is included in step 7. The compiler is identified and the environment is setup later, in step 11. Ideally, the flag would be added in that step, but in theory it could happen anytime before all the subdirectories are added (step 14). The only callback I can see in between these steps is the Version.cmake file, which doesn't seem like a good place to do it (and when I tried it for fun, I ran into CMake variable scope issues). So, it looks like a callback won't work in this case, unless you know of one that isn't obvious in the links you provided.

If you would prefer to avoid modifying TriBits itself, the only solution I see at this point is to add the flag on a per-package basis. By the time individual packages are included in CMake everything is defined and adding the additional flag should work without a problem (in fact, MueLu does this for gcc).

**Comment by bartlettroscoe** [comment]
> Unfortunately, that is still to early. In the link you supplied, the CallbackSetupExtraOptions.cmake file is included in step 7. The compiler is identified and the environment is setup later, in step 11. Ideally, the flag would be added in that step, but in theory it could happen anytime before all the subdirectories are added (step 14).

Hum, I guess that is right.  I did not realize that `MSVC` was not set until after the compilers were enabled and processed.  I guess what TriBITS needs is another call-back point like `<repoDir>/cmake/CallbackPostEnvSetup.cmake` that is processed right after step 11 "Probe and setup the environment" where these types of tweaks could be put in before the various TriBITS packages are processed.  That would not be too hard to add.  We can add a backlog item in https://github.com/TriBITSPub/TriBITS/issues/ to add support for that file and give this use case as a motivation.  This should not be a lot of work (most of the work is just adding the automated testing to TriBITS proper).

But for now, you can just add `/bigobj` as a configure argument to the Jenkins job to get it running.  When I get around to adding support for `<repoDir>/cmake/CallbackPostEnvSetup.cmake`, then we can put it there.

Does that sound like a plan?

**Comment by mplooster** [comment]
> But for now, you can just add /bigobj as a configure argument to the Jenkins job to get it running. When I get around to adding support for <repoDir>/cmake/CallbackPostEnvSetup.cmake, then we can put it there.
> 
> Does that sound like a plan?

Mostly. Adding the flag to my configure scripts works, but it also clears out the compiler flags that would otherwise be set (like `/DWIN32 /D_WINDOWS /W3 /GR /EHsc`). At this point, my recommendation would be to add the flag in the CMake file of the packages that need them, until TriBits can be modified. If done properly, this would preserve the flags that are already set while enabling `/bigobj`.

**Comment by bartlettroscoe** [comment]
> At this point, my recommendation would be to add the flag in the CMake file of the packages that need them, until TriBits can be modified. If done properly, this would preserve the flags that are already set while enabling /bigobj.

Okay

**Comment by mplooster** [comment]
@trilinos/rol 
@trilinos/muelu 

Could you review these additional changes that affect your packages?

**Comment by jhux2** [comment]
> Could you review these additional changes that affect your packages?

@mplooster As long as this doesn't affect our other builds (and I don't see how it would), I have no objections.

**Comment by mplooster** [comment]
@trilinos/rol Any thoughts from your team?
@trilinos/framework If there are no objections, can someone merge this pull request?

**Comment by jwillenbring** [comment]
Given the changes are ifdef'ed for visual studio, I highly doubt the @trilinos/rol team will object to the change. If we don't hear any concerns from them by 4/11/17, let's go ahead and merge this.

@bmpersc could you merge this change if there are no objections by 4/11/17?

**Comment by mplooster** [comment]
@trilinos/framework After looking around some more, I found one more possible solution to this problem. Apparently, Visual Studio allows you to set compiler options in the [environment variable CL](https://msdn.microsoft.com/en-us/library/kezkeayy.aspx). Instead of changing the CMakeList.txt file for these specific packges, I could just add the option to the environment variable in the nightly build, and all the packages would get it. This solution also seems to avoid the problem I mentioned earlier for setting the CMake flag in the configure script (i.e., clearing out other compiler flags). Would you prefer this solution?

**Comment by bartlettroscoe** [comment]
> Visual Studio allows you to set compiler options in the environment variable CL. 

Sounds like a good initial solution, just to get this up and running initially.

**Comment by mplooster** [comment]
> Sounds like a good initial solution, just to get this up and running initially.

Ok. I will do that instead, and close this pull request.

**Pull request closed without merging**
