### PR TITLE
Xpetra: Fixing Albany build fail

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA b0b5617

### CODE REVIEW

**Comment by ikalash** [comment]
Looks like there is a new set of Xpetra-related errors on a broader range of testbeds, e.g. the CEE, having to do with Xpetra: 

```
[ 68%] Building CXX object packages/xpetra/sup/CMakeFiles/xpetra-sup.dir/Utils/Xpetra_IteratorOps.cpp.o
In file included from repos/Trilinos/packages/xpetra/sup/Matrix/Xpetra_Matrix.hpp:60,
                 from repos/Trilinos/packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp:54,
                 from repos/Trilinos/packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.cpp:50:
/.../repos/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp: In static member function 'static Teuchos::RCP > Xpetra::CrsMatrixFactory >::Build(const Teuchos::RCP >&, size_t, Xpetra::ProfileType, const Teuchos::RCP&)':

repos/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp:288:126: error: invalid new-expression of abstract class type 'Xpetra::TpetraCrsMatrix >'

         return rcp( new TpetraCrsMatrix(rowMap, maxNumEntriesPerRow, pftype, plist) );
                                                                                                                              ^
In file included from repos/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp:54,
                 from repos/Trilinos/packages/xpetra/sup/Matrix/Xpetra_Matrix.hpp:60,
                 from repos/Trilinos/packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp:54,
                 from repos/Trilinos/packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.cpp:50:
```

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81736

Will this PR fix those too?  If not, I can open a separate issue.

**Comment by csiefer2** [comment]
I'm guessing yes.

**Comment by ikalash** [comment]
It's weird that those builds were fine yesterday but not today.  That suggests something got pushed yesterday that broke things.  Anyway, I'm happy to test if this PR fixes the issues once it's merged.

**Comment by csiefer2** [comment]
The offending commits made their way into develop at ~8pm MT the night before last.  Most of the nightly pulls missed it...

**Pull request merged**
