### PR TITLE
Galeri: copy missing header during installation

### LINKED ISSUE #10996: Galeri: header "Galeri_Exception.h" missing after installation
## Bug Report
@trilinos/galeri 

### Description

When configuring Galeri with

```cmake
-D Trilinos_ENABLE_Galeri:BOOL=ON \
  -D Galeri_ENABLE_Epetra:BOOL=OFF \
  -D Galeri_ENABLE_Xpetra:BOOL=ON \
```

to use it with Tpetra through Xpetra, the `make install` does not copy the file `packages/galeri/src-epetra/Galeri_Exception.h` to the `include/` directory. However, it is included at least by the following files from the `packages/galeri/src-xpetra/` directory:

- `packages/galeri/src-xpetra/Galeri_XpetraCartesian.hpp`
- `packages/galeri/src-xpetra/Galeri_XpetraUtils.hpp`

### How can this be resolved?

Make sure, that the installation process copies the missing header to the `include/` directory.

A long-term solution could be to move the header outside of `src-epetra` to a place, that's independent of Epetra or Xpetra

### PR DESCRIPTION
**Pull request by mayrmt**
@trilinos/galeri 
@searhein 

## Motivation

Move some files, that are used by both the Epetra and Xpetra portion of Galeri, to the new directory `headers/`.

This PR adapts the inclusion of header files in various `CMakeLists.txt` as well.

## Related Issues

* Closes #10996.

## Testing

Verified on my machine. 
- Xpetra/Tpetra build still works.
- Epetra build verified through a Trilinos build with essentially only `Ifpack` enabled.

The problem, when using an installed Trilinos/Galeri in an application code (as originally described in #10996) works with these modifications.

### CODE REVIEW

**Review by jhux2 — DISMISSED** [review]
lgtm

**Comment by jhux2** [comment]
@mayrmt fyi, AT is still not working properly, so this PR won't merge.

**Comment by mayrmt** [comment]
I've changed the approach to solve the problem described in #10996. See the updated description of this PR for details.

**Review by jhux2 — APPROVED** [review]
lgtm.  One minor comment is that there are many header files that don't belong in the "headers" directory, which might confuse some.

**Pull request merged**
