### PR TITLE
Remove calls to Tpetra deprecated code

### PR DESCRIPTION
**Pull request by mperego**
More deprecated code removals

@trilinos/stokhos 
@trilinos/moertel 

## Motivation

Related to #10191.

### CODE REVIEW

**Review by rppawlo — APPROVED** [review]
Thanks @mperego !

**Comment by mperego** [comment]
B.t.w. these are the easy fixes. I'm not sure it will complitely fix Stockos or Morteal but it could.

**Review by etphipp — APPROVED** [review]
Looks good.  Thanks Mauro!

**Comment by mperego** [comment]
@rppawlo any clue of why the stk test is failing? is it an heisenbug?

**Comment by rppawlo** [comment]
@mperego - I really don't know. It looks like ioss can't read the exodus file from disk (or maybe the exodus file is corrupted). Don't know how this would happen. The file is copied over at compile time and is very small. This test has been passing fine for a year and nothing in panzer has changed that would affect this. Maybe a change in ioss? Using the framework build instructions, I cannot reproduce this on my local machines (only seems to happen in gcc 7.2 debug builds). Ran the tests in question 100 times through ctest without a single failure. My best guess is that the degrees_of_freedom variable is uninitialized causing the random failure in this debug build check. Maybe I can get on the actual test machine where this is failing?

@gsjaardema - any ideas? Any recent changes that might have caused this?

```
IOSS WARNING: No nodes were found in the model, file 'diffsideids.exo'

IOSS WARNING: No elements were found in the model, file 'diffsideids.exo'
PanzerAdaptersSTK_PoissonInterfaceTpetra.exe: /scratch/trilinos/jenkins/ascic166/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0_debug/Trilinos/packages/seacas/libraries/ioss/src/Ioss_NodeBlock.C:33: Ioss::NodeBlock::NodeBlock(Ioss::DatabaseIO*, const string&, int64_t, int64_t): Assertion `degrees_of_freedom == 1 || degrees_of_freedom == 2 || degrees_of_freedom == 3' failed.
[ascic166:43652] *** Process received signal ***
[ascic166:43652] Signal: Aborted (6)
[ascic166:43652] Signal code:  (-6)
```

**Comment by mperego** [comment]
@rppawlo Thanks. The second time the test passed.

**Comment by mperego** [comment]
Now the issue is related to krino #10420.

**Pull request merged**
