### PR TITLE
TriBITS Snapshot 2022-12-12 working toward TriBITSPub/TriBITS#63

### PR DESCRIPTION
**Pull request by bartlettroscoe**
### Description

Update of TriBITS containing a number of refactorings and extensions working toward TriBITSPub/TriBITS#63 (and EPIC TriBITSPub/TriBITS#367).  Some other issues are addressed as well like getting rid of deprecated usage of some TriBITS functionality.

This includes the TriBITS PRs and direct commits (from most recent to least recent):

* TriBITSPub/TriBITS#555
* TriBITSPub/TriBITS#553
* TriBITSPub/TriBITS#552
* TriBITSPub/TriBITS@07aeef0f
* TriBITSPub/TriBITS#550
* TriBITSPub/TriBITS#547
* TriBITSPub/TriBITS#549
* TriBITSPub/TriBITS#546
* TriBITSPub/TriBITS#544
* TriBITSPub/TriBITS#541
* TriBITSPub/TriBITS#540
* TriBITSPub/TriBITS#539
* TriBITSPub/TriBITS#538
* TriBITSPub/TriBITS#537
* TriBITSPub/TriBITS#535
* TriBITSPub/TriBITS#532
* TriBITSPub/TriBITS#531
* TriBITSPub/TriBITS#530
* TriBITSPub/TriBITS#529

**NOTE**: In addition, this contains individual commits for each Trilinos package to remove the usage of the deprecated TriBITS macros `include_directories()` and `set_and_inc_dirs()`.    The large number of commits and files changed is due to those updates.

**NOTE:** I will apply the changes to the external repos to those repos (i.e. for KokkosKernals, SEACAS, and Sierra).

### Testing

I tested locally on SNL RHEL7 machine 'crf450' with:

```
$ ssh crf450

$ cd ~/Trilinos.base/BUILDS/PR/pr_builds/

$ ./run_trilinos_pr_builds.py  \
  -b tribits-master-2022-12-12 \
  -c Trilinos_TRIBITS_DIR:STRING=cmake/tribits \
  -p ALL_PACKAGES -j 16 -r clang-11.0.1

...

Configure PASSED!

Build PASSED!

100% tests passed, 0 tests failed out of 3466

...
```

which posted to CDash [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=crf450&field2=buildname&compare2=61&value2=tribits-master-2022-12-12_rhel7_sems-clang-11.0.1-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field3=buildstamp&compare3=61&value3=20221220-1840-Experimental).

<details>

<summary><b>Full run_trilinos_pr_bulids.py output for clang-11.0.1 build:</b> (click to expand)</summary>

<br>

```
=================================
Running set of Trilinos PR builds
=================================

Tue Dec 20 11:38:23 MST 2022

***
*** Repo status and versions:
***

Trilinos Src Dir: /home/rabartl/Trilinos.base/Trilinos

---------------------------------------------------------------------------------------------------------------------------------
| ID | Repo Dir                         | Branch                      | Tracking Branch                            | C  | M | ? |
|----|----------------------------------|-----------------------------|--------------------------------------------|----|---|---|
|  0 | Trilinos (Base)                  | tribits-snapshot-2022-12-12 | rab-github/tribits-snapshot-2022-12-12-tmp | 21 |   |   |
|  1 | packages/framework/GenConfig     | HEAD                        |                                            |    |   |   |
|  2 | packages/framework/son-ini-files | master                      | origin/master                              |    |   |   |
|  3 | packages/framework/srn-ini-files | master                      | origin/master                              |    |   |   |
|  4 | TriBITS                          | master                      | github/master                              |    |   |   |
|  5 | TriBITS/TriBITSDoc               | master                      | github/master                              |    |   |   |
|  6 | run_trilinos_pr_builds           | master                      | glex-rabartl/master                        |    |   |   |
---------------------------------------------------------------------------------------------------------------------------------

(tip: to see a legend, pass in --dist-legend.)

Repository versions:
*** Base Git Repo: Trilinos
aacf63de2ae034fe46a257fa094c6dd6eb06fcd1 [Tue Dec 20 11:36:43 2022 -0700] <rabartl@sandia.gov>
Merge branch 'tribits_github_snapshot' into tribits-snapshot-2022-12-12 (#11411)
*** Git Repo: packages/framework/GenConfig
924a08af66f0a0573b5dd1128179731489339aec [Wed Jun 15 15:55:48 2022 +0000] <eharvey@sandia.gov>
Merge branch 'del-gen-symlinks' into 'master'
*** Git Repo: packages/framework/son-ini-files
6c30e48f45bf0d839f0fdbc143f4f3f69cae671a [Mon Jul 18 16:33:38 2022 +0000] <jfrye@sandia.gov>
Merge branch 'cuda-11-config' into 'master'
*** Git Repo: packages/framework/srn-ini-files
d1c76f866658ffa18051cb18f6a6584f544a01ae [Tue Dec 13 11:07:01 2022 -0700] <eharvey@sandia.gov>
Merge branch 'TRILFRAME-495' into 'master'
*** Git Repo: TriBITS
3879de003986ced56bd5ffcb10149fbd3746e6c5 [Tue Dec 20 13:34:23 2022 -0500] <rabartl@sandia.gov>
Merge pull request #555 from bartlettroscoe/554-add-run-serial (#554)
*** Git Repo: TriBITS/TriBITSDoc
70d9dca0c622d3f320b71185c135461291c354c2 [Mon Jul 26 13:02:26 2021 -0600] <rabartl@sandia.gov>
Add back update_repos_and_publish_web_docs.sh (TriBITSPub/TriBITS#386)
*** Git Repo: run_trilinos_pr_builds
3ab406f14d8467bdb7b50c595c7268d7f9380022 [Mon Dec 12 16:17:05 2022 -0700] <rabartl@sandia.gov>
Update the set of PR builds

See results on CDash at:

    https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Experimental&field2=buildname&compare2=65&value2=tribits-master-2022-12-12_&field3=buildstarttime&compare3=84&value3=now

Final set of builds: clang-11.0.1

Generating the build directory and scripts: clang-11.0.1

  full-build-name: 'rhel7_sems-clang-11.0.1-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables'

***
*** Running configure, build, and test for PR build 'clang-11.0.1'
***

Full build name: rhel7_sems-clang-11.0.1-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables

Tue Dec 20 11:38:25 MST 2022

Running: source load-env.sh --ci-mode &> load-env.out

Running: ./do-configure &> configure.out


real    1m46.999s
user    1m9.689s
sys     0m40.232s

Running: make dashboard &> make.dashbaord.out

real    154m49.682s
user    2307m40.227s
sys     60m12.430s

Results of configure, build, and tests:

Configure PASSED!

Build PASSED!

100% tests passed, 0 tests failed out of 3466

Link to this build's results on CDash:

    https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=crf450&field2=buildname&compare2=61&value2=tribits-master-2022-12-12_rhel7_sems-clang-11.0.1-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field3=buildstamp&compare3=61&value3=20221220-1840-Experimental


Tue Dec 20 14:15:13 MST 2022

See results on CDash at:

    https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Experimental&field2=buildname&compare2=65&value2=tribits-master-2022-12-12_&field3=buildstarttime&compare3=84&value3=now
```

</details>

### Tasks

* [x] Get PR builds to pass
* [x] Pull off commits and apply to external repos: 
  * [x] KokkosKernels ... See https://github.com/kokkos/kokkos-kernels/pull/1635
  * [x] SEACAS  ... See https://github.com/sandialabs/seacas/pull/361
  * [x] Krino ... See [Sierra MR #3177](https://cee-gitlab.sandia.gov/sierra/base/-/merge_requests/3177)
  * [x] STK ... See [Sierra MR #3177](https://cee-gitlab.sandia.gov/sierra/base/-/merge_requests/3177)
  * [x] Percept ... There are no CMakeLists.txt files in the native Sierra repo copy of Percept!
* [x] Get PR approved
* [ ] Merge PR

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
FYI: Last PR iteration failed due to one timing out test `PanzerAdaptersSTK_main_driver_energy-ss-blocked-tp` in the PR build `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables` and it seems to have only timed out this once in PR testing as shown in [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-12-01&end=2022-12-13&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=buildname&compare2=63&value2=rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field3=testname&compare3=61&value3=PanzerAdaptersSTK_main_driver_energy-ss-blocked-tp).  And when the test passes, it completes in under 4m 18s.

But note that we are getting over 1300 `CMake Deprecation Warning` messages of the form:

```
CMake Deprecation Warning at cmake/tribits/core/utils/MessageWrapper.cmake:77 (message):
  TriBITS command 'include_directories' is deprecated.

  

  Use tribits_include_directories() instead.
Call Stack (most recent call first):
  cmake/tribits/core/utils/TribitsDeprecatedHelpers.cmake:81 (message_wrapper)
  cmake/tribits/core/utils/TribitsDeprecatedHelpers.cmake:114 (tribits_deprecated)
  cmake/tribits/core/package_arch/TribitsIncludeDirectories.cmake:93 (tribits_deprecated_command)
  commonTools/gtest/CMakeLists.txt:8 (INCLUDE_DIRECTORIES)
```

I will need to make those go away before I merge this PR.

**Comment by bartlettroscoe** [comment]
Back when I first created this PR, I tried testing on my machine 'ceerws1113' and it failed because system lapack.so was mssing.

For the Trilinos GenConfig configuration for clang-11.0.1, it failed build with the global Ninja failure:

```
ninja: error: '/usr/lib64/liblapack.so', needed by 'packages/teuchos/numerics/src/libteuchosnumerics.so.13.5', missing and no known rule to make it
```

as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ceerws1113&field2=buildname&compare2=61&value2=tribits-master-2022-12-12_rhel7_sems-clang-11.0.1-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables&field3=buildstamp&compare3=61&value3=20221213-0002-Experimental

The SEMS modules just don't work on many of the CEE machines.  (If they would build BLAS and LAPACK with Spack, this would not keep being a problem.)

**Review by GrahamBenHarper — APPROVED** [review]
The MueLu changes look good. All I see are changes from `INCLUDE_DIRECTORIES` to `TRIBITS_INCLUDE_DIRECTORIES`. Are there any other changes that we should be aware of at the package level?

**Comment by bartlettroscoe** [comment]
> The MueLu changes look good. All I see are changes from `INCLUDE_DIRECTORIES` to `TRIBITS_INCLUDE_DIRECTORIES`. Are there any other changes that we should be aware of at the package level?

@GrahamBenHarper, as described [above](https://github.com/trilinos/Trilinos/pull/11380):

> **NOTE:** In addition, this contains individual commits for each Trilinos package to remove the usage of the deprecated TriBITGS macros `include_directories()` and `set_and_inc_dirs()`. The large number of commits and files changed is due to those updates.

And if you look at the commit summaries [here](https://github.com/trilinos/Trilinos/pull/11380/commits), you will see that is the case (except for KokkosKernels in https://github.com/trilinos/Trilinos/pull/11380/commits/acca2f92fc18d7470770bd02a8dc2c6725e0850c).

**Comment by bartlettroscoe** [comment]
I am finding it impossible to use git format-patch and git am to apply the changes to the SEACAS repo.  It looks like there are lots of piece meal commits directly against the Trilinos branch for SEACAS.  There are no recent clean snapshot so there is no base version to run git am against.  Therefore, I will have to apply the refactoring scripts directly on the externa SEACAS repo.

**Review by alanw0 — APPROVED** [review]
Thanks @bartlettroscoe I think this all looks fine.
The fei package is approaching end-of-life anyway, although it is still used in sierra some...
For the stk changes, I'll grab the commit and bring it to sierra so that we don't overwrite it next time we snapshot stk back to trilinos.

**Comment by bartlettroscoe** [comment]
>  I'll grab the commit and bring it to sierra so that we don't overwrite it next time we snapshot stk back to trilinos.

Hello @alanw0, I was going to do that at the same time that I grabbed the changes for Krino and Percept (which also live in the Sierra base repo).

**Comment by alanw0** [comment]
> > I'll grab the commit and bring it to sierra so that we don't overwrite it next time we snapshot stk back to trilinos.
> 
> Hello @alanw0, I was going to do that at the same time that I grabbed the changes for Krino and Percept (which also live in the Sierra base repo).

ok, sounds fine. I couldn't remember if you ended up getting access to sierra gitlab a while back.

**Comment by bartlettroscoe** [comment]
> @alanw0, I seem to have access to the cee-gitlab repo for Sierra base so I will try posting a MR for the (trivial) changes for STK, Krino, and Percept.

@alanw0, it looks like the snapshots don't contain the SHA1s from the originating git repo so it is not clear how to apply the patches back to the Sierra base repo.   For example, the latest STK snapshot commit only shows:

```
$ git log -1 73ab2e96b9e
commit 73ab2e96b9e93bf8bda9f877f5549073812f3497 (github/stk-snapshot)
Author: Timothy A. Smith <tasmit@sandia.gov>
Date:   Thu Dec 15 14:27:20 2022 -0700

    STK: Snapshot 12-15-22 14:26
```

A date in git is not well defined.  Is this the commit or author date of the commit of the top commit in the repo?  Is this the time on the wall that the snapshot was created from the main branch of the originating repo?  What branch?  The 'master' branch?  It is not clear.

What is needed is the SHA1 for the originating git repo.  Such a snapshot commit is generated using a tool like [snapshot-dir.py](https://tribitspub.github.io/TriBITS/users_guide/index.html#snapshot-dir-py-help).  For example, for the TriBITS snapshots you see commits like:

```
commit 03df3a0672e9aaa7802c9b37b3fb114c68e5b313 (github/tribits_github_snapshot, tribits_github_snapshot)
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Dec 20 11:35:29 2022 -0700

    Automatic snapshot commit from tribits at c2f52215
    
    Origin repo remote tracking branch: 'github/master'
    Origin repo remote repo URL: 'github = git@github.com:TriBITSPub/TriBITS.git'
    Git describe: Vera4.0-RC1-start-1418-g3879de00
    
    At commit:
    
    commit c2f52215a2bf6d1004c5422164f0019952fcc1f2
    Author:  Roscoe A. Bartlett <rabartl@sandia.gov>
    Date:    Tue Dec 20 11:15:04 2022 -0700
    Summary: Add RUN_SERIAL to tribits_add_executable_and_test() (#554)
```

That leaves no ambiguity at all about what version was snapshotted in and where it came from.

**Comment by alanw0** [comment]
@bartlettroscoe our snapshotting script does inject a small breadcrumb that may be helpful. Take a look at packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp and search for STK_VERSION_STRING. We drop a little info in there which (I think) contains the sha1 from the sierra base repo at the time of the snapshot.

**Comment by bartlettroscoe** [comment]
@alanw0, given that these charges are created by just running some simple refactoring scripts, I will just run those scripts on the subdirs in the Sierra base repo to create the commits.   But it would be good to define the process of bringing back the commits to make it fool-proof.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe our snapshotting script does inject a small breadcrumb that may be helpful. ... packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp ...

@alanw0, but what about for Krino and Percept?  Those don't contain that file.

**Comment by bartlettroscoe** [comment]
@alanw0, what is the date time stamp in a commit like a14f1d2e7bd:

```
commit a14f1d2e7bd240a80c30db7016844b90ff82e2b6
Author: Alan B. Williams <william@sandia.gov>
Date:   Wed Nov 23 09:02:22 2022 -0700

    STK: Snapshot 11-23-22 09:02
```

mean?

**Comment by alanw0** [comment]
@bartlettroscoe 
1. yes I think it should be reasonable to run your script on the sierra subdirs to make this change.
2. yes it's true that percept and krino don't contain that stk file, nor any file with snapshot-versioning info. I'll see whether we can coordinate something along those lines with the authors of those packages.
3. the date-stamp in our current snapshot commit message is relatively meaningless, it is simply the time at which the snapshot script raked code out of a clone of sierra and put it into a clone of trilinos.

we clearly need some better tracking info, I'll see what we can do.

**Comment by bartlettroscoe** [comment]
It would appear that the native Sierra repo copy of percept does not contain any CMakeLists.txt files?  Therefore, there is nothing to sync back?

**Comment by bartlettroscoe** [comment]
> the date-stamp in our current snapshot commit message is relatively meaningless, it is simply the time at which the snapshot script raked code out of a clone of sierra and put it into a clone of trilinos.

@alanw0, if the script that does the snapshotting pulls from the 'master' branch in the cee-gitlab repo for Sierra right before it creates the snapshot, then we should be able to determine what version of the repo this came from by looking at `git log --first-parent` on the 'master' branch.

**Comment by bartlettroscoe** [comment]
With PRs and MRs for all of these changes posted on the native repos (see **Tasks** [above](https://github.com/trilinos/Trilinos/pull/11380#issue-1493221616)), this is ready to merge.  All that is needed is to merge those PRs and MRs.

**Comment by bartlettroscoe** [comment]
All of the external PRs and MRs have been created, and of those, all but the KokkosKernels PR  https://github.com/kokkos/kokkos-kernels/pull/1635 have been merged.  Therefore, to avoid the testing going stale, I will merge this PR.

NOTE: There is some more breaks in backward compatibility in the new items in [tribits/CHANGELOG.md](https://github.com/trilinos/Trilinos/pull/11380/files#diff-344da4816d49ad8e76548f2548091cfe8be8af04a6f300463273473b12c12b20).

**Comment by bartlettroscoe** [comment]
There are some problems reported with these TriBITS changes in https://github.com/trilinos/Trilinos/issues/11426 and https://github.com/sandialabs/Albany/issues/879.

Therefore, I will put in a PR to back out this merge commit for now so we can keep things clean during the holiday break.

**Pull request merged**
