### PR TITLE
MueLu: enable mj_premigration_option by default for Zoltan2

### PR DESCRIPTION
**Pull request by aprokop**
@trilinos/muelu

### CODE REVIEW

**Comment by aprokop** [comment]
I think it would be great if @mndevec has come up with metrics that would not do this if it's not necessary. The expectation is that we may skip this if:
- We are not communication bound
  For instance if each processor has more than 10k dof
- The number of parts is close to the number of processors.
  This may happen in MueLu if we are rebalancing due to a significant imbalance and not because we coarsened too much.

**Comment by srajama1** [comment]
@aprokop : Note that there is a small variation of the option using 16 instead of 1. We are still waiting for confirmation that this actually helps in threaded runs. You might want to use that, if that hypothesis is confirmed, with multithreaded MueLU.

**Comment by aprokop** [comment]
Related to #1538.

**Comment by aprokop** [comment]
@srajama1 Isn't 16 correspond to the number of cores per node? Even if it's true, won't that value be machine dependent, and thus more tricky to figure out?

**Comment by jhux2** [comment]
@aprokop @srajama1 @mndevec What's the impact of having this option enabled, even for smaller scale problems?

**Comment by srajama1** [comment]
@aprokop : Can you expose this as an input option for performance optimization instead of fixing it.

@jhux2 : There could be a small performance impact for smaller problems, but we could avoid that by doing this only at scale. However, all of this will be heuristics, that could break in some configuration. I would rather expose it in input and use it only when needed.

**Comment by aprokop** [comment]
> @aprokop : Can you expose this as an input option for performance optimization instead of fixing it.

Yes, it is always exposed, this PR is about setting the default value for it. Judging by @pwxy's results, 1 sound reasonable, and should not cause issues at small scale.

**Comment by jhux2** [comment]
@aprokop I agree with the default value of 1.  Even if there is a slight cost at small scale, I'd gladly pay that for better scaling.

**Comment by srajama1** [comment]
@aprokop : Got it, Thanks !

**Comment by jjellio** [comment]
@jhux2 I've posted some timings from Cori on the other issue thread  #1538 

The results seem good, yet at the same time they are not conclusive.  We need to look at this more

**Comment by aprokop** [comment]
According to the recent discussion in #1538, any positive value will do the same thing. Thus, setting to 1 should be fine.

**Comment by jhux2** [comment]
@aprokop @srajama1 @mndevec @jjellio Should this be merged?

**Comment by srajama1** [comment]
Looks good to be merged.

**Comment by aprokop** [comment]
I'm fine with merging it too.

**Comment by jhux2** [comment]
This broke a bunch of tests in Nalu.  I don't have time to look at this ... so am planning to revert until I do.

**Comment by mndevec** [comment]
Instead of
```c++
defaultZoltan2Params->set("mj_premigration_option", 1);
```
below
```c++
defaultZoltan2Params->set("mj_premigration_option", "1");
```
might be the fix to the problem. I am not %100 sure though. 

@kddevin  : should parameter list always receive string?

**Comment by kddevin** [comment]
@jhux2 how did it break the Nalu tests?  Builds?  Runtime error?  Or different answers?

**Comment by mndevec** [comment]
@kddevin : I am assuming it is the issue here:
https://github.com/NaluCFD/Nalu/issues/354

**Comment by kddevin** [comment]
@mndevec I think Teuchos parameter lists can accept the argument as either an integer or a string.  For example, in Zoltan2 testing, the unit test AllParameters.cpp passes the value as a string, but in partitioning test MultiJaggedTest.cpp, it is passed as an integer.

**Comment by kddevin** [comment]
@mndevec OK; thanks.  We probably need to check the validator for mj_premigration_option.

**Comment by kddevin** [comment]
@jhux2 
Does MueLu set the parameter this way?
defaultZoltan2Params->set("mj_premigration_option", 1);
I do not know where to look in MueLu to find the parameter setting code.

The error message in Nalu looks as if a string is being passed.  I thought passing a string was OK, but if changing it to an int helps, that's an easy solution.

**Comment by mndevec** [comment]
https://github.com/trilinos/Trilinos/pull/1649/commits/198fd2826ed907bcf33d028d7de469bdee8ddaa1
^This commit^ points to where the parameter is set. It is setting it as int, not as a string.

**Comment by kddevin** [comment]
(Oops -- I accidentally put this in the Nalu bug at first.  I deleted it there and am copying it here.  My bad.  Very sorry.)
@jhux2 @aprokop 
After a closer look, I think the problem is not in how mj_premigration_option is set (string or int); either of those will work.
The problem is that in MueLu_Zoltan2Interface_def.hpp, near line 152, the defaultZoltan2Params list is merged with Zoltan2Params. In that operation, the parameter value is fetched as a string, instead of as an int.
Zoltan2Params.set(pName, defaultZoltan2Params->getstd::string(pName));
This code probably worked before because all the other Zoltan2 parameters used by MueLu were either strings or did not have validators that checked the type. Since mj_premigration_option uses EnhancedNumberValidator, its return type for defaultZoltan2Params->get must be int.
Does ParameterList have a method returning the parameter type? If so, MueLu could check it here and provide the right kind of get() as the second argument.

**Comment by aprokop** [comment]
@kddevin If Zoltan2 can use both `string` and `int` as an option, the easiest thing would be to change the default in `MueLu` to use `string` as this won't require auto-detecting the type.

One thing that bothers me is why the tests pass for this PR. We do have tests that use `multijagged` algorithm, so they should have hit the issue.

**Comment by jhux2** [comment]
> After a closer look, I think the problem is not in how mj_premigration_option is set (string or int); either of those will work.
> The problem is that in MueLu_Zoltan2Interface_def.hpp, near line 152, the defaultZoltan2Params list is merged with Zoltan2Params. In that operation, the parameter value is fetched as a string, instead of as an int.
[snip]
> Does ParameterList have a method returning the parameter type? If so, MueLu could check it here and provide the right kind of get() as the second argument.

@kddevin Thank you for looking into this.  It does not appear that ParameterList has a way to return the type of the entry.  If Zoltan2 uses only `int` and `string`, we could check for one or the other here:

```cpp
    // Merge defalt Zoltan2 parameters with user provided
    // If default and user parameters contain the same parameter name, user one is always preferred
    for (ParameterList::ConstIterator param = defaultZoltan2Params->begin(); param != defaultZoltan2Params->end(); param++) {
      const std::string& pName = defaultZoltan2Params->name(param);
      if (!Zoltan2Params.isType<std::string>(pName))
        Zoltan2Params.set(pName, defaultZoltan2Params->get<std::string>(pName));
      if (!Zoltan2Params.isType<int>(pName))
        Zoltan2Params.set(pName, defaultZoltan2Params->get<int>(pName));
    }

```

**Comment by aprokop** [comment]
@jhux2 Actually, a much safer and robust option would be to just do:
```c++
Zoltan2Params.setEntry(pName, defaultZoltan2Params->getEntry(pName));
```

**Comment by jhux2** [comment]
> @jhux2 Actually, a much safer and robust option would be to just do:
> 
> Zoltan2Params.setEntry(pName, defaultZoltan2Params->getEntry(pName));

Yes, of course!

**Comment by kddevin** [comment]
@aprokop 
Regarding setting the parameter:  set() takes any kind of argument; EnhancedNumberValidator does the conversion from string to int.
You ask a good question:  how did the PR test not catch the error?

**Pull request merged**
