### PR TITLE
8062 amesos superludist 13 0 branch

### PR DESCRIPTION
**Pull request by keitat**
This is a fix required by xSDK-0.6.0 release ( #8062 ), which includes the new SuperLU_DIST-6.3.
https://github.com/xiaoyeli/superlu_dist

@trilinos/amesos  
@trilinos/amesos2

## Motivation
SuperLU_DIST-6.3 introduced a few API changes.  We are adding an extra support to adapt the changes.

## Related Issues

#8062
#8067

## Stakeholder Feedback
xSDK team, in particular deal.II developers, wants to keep the support of SuperLU_DIST and SuperLU for the 1st generation packages.

## Testing
The tester needs SuperLU_DIST-6.3.  Please add this to the TPL lists being tested.
xSDK team will test the build process of the whole Trilinos library and example programs (Amesos2 and Amesos).

### CODE REVIEW

**Comment by jhux2** [comment]
@keitat If SuperLU_dist isn't being tested nightly already, a path forward is that you set up your own nightly test on your local workstation.  That way, you can configure Trilinos exactly as you like and use the precise version of SuperLU_dist that xsdk needs.   The MueLu and Tpetra teams do this already.

**Comment by jwillenbring** [comment]
@srajama1 Can you review these changes for the 13.0 release branch?

**Comment by jwillenbring** [comment]
@balay Did you have a chance to test this branch at all?

**Comment by balay** [comment]
yes - I grabed the patch and using it in the xsdk branch as mentioned at 
https://github.com/xsdk-project/xsdk-issues/issues/106

https://github.com/xsdk-project/spack-xsdk/commit/db80a1e15213ecfc4a3e46915d50cb86fd169b2b

**Comment by jwillenbring** [comment]
@balay reports that this patch works with the new superludist. 

[xsdk-project/xsdk-issues#106](https://github.com/xsdk-project/xsdk-issues/issues/106)

Can someone from @trilinos/amesos2 approve this change?

**Review by ndellingwood — APPROVED** [review]

**Pull request merged**
