### PR TITLE
Set TEST_0 PASS_REGULAR_EXPRESSION and untangle test-block and overall args

### PR DESCRIPTION
**Pull request by bartlettroscoe**
I noticed this while looking over this failing test on CDash like [here](https://testing-dev.sandia.gov/cdash/testDetails.php?test=3844&build=5393854).

I should update the TriBITS documentation to advise people not to set  FINAL_PASS_REGULAR_EXPRESSION but instead determine pass/fail at the `TEST_<idx>` block level. 

## How was this tested?

I configured, built, and ran this single ShyLU_NodeHTS locally and it showed:

```
$ ctest -VV
UpdateCTestConfiguration  from :/home/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/gnu-openmp-dbg-pt/DartConfiguration.tcl
Parse Config file:/home/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/gnu-openmp-dbg-pt/DartConfiguration.tcl
 Add coverage exclude regular expressions.
SetCTestConfiguration:CMakeCommand:/home/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.12.2/bin/cmake
UpdateCTestConfiguration  from :/home/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/gnu-openmp-dbg-pt/DartConfiguration.tcl
Parse Config file:/home/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/gnu-openmp-dbg-pt/DartConfiguration.tcl
Test project /home/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/gnu-openmp-dbg-pt
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: ShyLU_NodeHTS_hts_test_1
1: Test command: /home/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.12.2/bin/cmake "-DTEST_CONFIG=" "-P" "/home/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/gnu-openmp-dbg-pt/packages/shylu/shylu_node/hts/test/ShyLU_NodeHTS_hts_test_1.cmake"
1: Environment variables: 
1:  OMP_NUM_THREADS=2
1: Test timeout computed to be: 600
1: 
1: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1: 
1: Advanced Test: ShyLU_NodeHTS_hts_test_1
1: 
1: Selected Test/CTest Propeties:
1:   CATEGORIES = BASIC
1:   PROCESSORS = 2
1:   TIMEOUT    = DEFAULT
1: 
1: Running test commands: TEST_0
1: 
1: ================================================================================
1: 
1: TEST_0
1: 
1: Running: "/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/7.2.0/openmpi/1.10.1/bin/mpiexec" "--bind-to" "none" "-np" "1" "/home/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/gnu-openmp-dbg-pt/packages/shylu/shylu_node/hts/test/hts_test.exe"
1: 
1: --------------------------------------------------------------------------------
1: 
1: HTS Test: Passed
1: 
1: --------------------------------------------------------------------------------
1: 
1: TEST_0: Return code = 0
1: TEST_0: Pass criteria = Match REGEX {Passed} [PASSED]
1: TEST_0: Result = PASSED
1: 
1: ================================================================================
1: 
1: OVERALL FINAL RESULT: TEST PASSED (ShyLU_NodeHTS_hts_test_1)
1: 
1: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1: 
1/1 Test #1: ShyLU_NodeHTS_hts_test_1 .........   Passed    8.63 sec

100% tests passed, 0 tests failed out of 1

Subproject Time Summary:
ShyLU_Node    =  17.26 sec*proc (1 test)

Total Test time (real) =   8.63 sec
```

Note the criteria:

```
TEST_0: Pass criteria = Match REGEX {Passed} [PASSED]
```

NOTE, you might also want to use the `ALWAYS_FAIL_ON_NONZERO_RETURN` option as well documented at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#test-idx-exec-cmnd-test-blocks-and-arguments-tribits-add-advanced-test

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
I tried to set reviewers who modified this package recently but there are are not many recent commits as shown by:

```
$ git log-short -- packages/shylu/shylu_node/hts/
847a14e "Set TEST_0 PASS_REGULAR_EXPRESSION and untangle test-block and overall args"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed Apr 22 07:58:42 2020 -0600 (27 minutes ago)

7a25eb3 "ShyLU HTS: fix memset-zero of std::complex"
Author: Brian Kelley <bmkelle@sandia.gov>
Date:   Sat Dec 7 14:45:44 2019 -0700 (5 months ago)

896d751 "ShyLU: Fix build errors when Scalar=complex<float> is enabled"
Author: Mark Hoemmen <mhoemme@sandia.gov>
Date:   Wed Oct 10 16:47:09 2018 -0600 (1 year, 6 months ago)

203fc76 "ShyLU/HTS: Partially fix #2942."
Author: Andrew M. Bradley <ambradl@sandia.gov>
Date:   Thu Jun 14 13:12:20 2018 -0600 (1 year, 10 months ago)

2a6a0af "shylu_hts: comment out 'unused' variable in .cpp"
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Thu Feb 22 11:31:23 2018 -0700 (2 years, 2 months ago)

f57ee58 "ShyLU: Fixing some variable names"
Author: Alexander Heinlein <alexander.heinlein@uni-köln.de>
Date:   Fri Oct 6 17:32:00 2017 -0600 (2 years, 7 months ago)

d66d3b2 "ShyLU: Further changes for splitting the package"
Author: Alexander Heinlein <alexander.heinlein@uni-köln.de>
Date:   Thu Oct 5 15:34:00 2017 -0600 (2 years, 7 months ago)

193e84f "ShyLU: changing the names for consistency"
Author: Alexander Heinlein <alexander.heinlein@uni-köln.de>
Date:   Tue Oct 3 11:48:31 2017 -0600 (2 years, 7 months ago)

73bbea7 "Moving config file"
Author: Alexander Heinlein <alexander.heinlein@uni-köln.de>
Date:   Mon Oct 2 16:03:09 2017 -0600 (2 years, 7 months ago)

8b0f850 "Adding FROSch and Splitting ShyLU"
Author: Alexander Heinlein <alexander.heinlein@uni-köln.de>
Date:   Mon Oct 2 16:01:28 2017 -0600 (2 years, 7 months ago)
```

**Comment by ndellingwood** [comment]
@bartlettroscoe changes look good to me, I'm adding @ambrad to see if he can give an okay as well

**Comment by bartlettroscoe** [comment]
@trilinos/shylu 

**WARNING:** PR testing did not actually run this test!!!!  See [CDash results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-7229-test&field2=buildstarttime&compare2=84&value2=NOW).

@trilinos/framework, how is that possible?  The configure output shown [here](https://testing.sandia.gov/cdash/viewConfigure.php?buildid=6846525) at the top shows:

```
loading initial cache file /home/trilinos/jenkins/ride/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
loading initial cache file /home/trilinos/jenkins/ride/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/packageEnables.cmake
-- NOTE: No packages are being enabled!
```

I can't see where that logic is being performed but this needs to be fixed ASAP!

**Comment by bartlettroscoe** [comment]
FYI: This not getting tested looks to be related to #6697 and some bug with testing Primary Tested vs Secondary Tested code.

**Comment by bartlettroscoe** [comment]
Let me fix #6697 so that this gets tested and then we can merge?

**Comment by bartlettroscoe** [comment]
FYI: Once PR #7414 merges to 'develop', then we can run another PR test iteration for this PR and ShyLU_NodeHTS and other ST packages will get tested in PR testing.

**Comment by bartlettroscoe** [comment]
Now that PR #7414 just merged, we can retest this PR and the PR tester should actually test ShyLU_NodeHTS.

**Comment by bartlettroscoe** [comment]
FYI: Note that, as predicted, the last PR testing iteration shown [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-7229-test&field2=buildstarttime&compare2=84&value2=NOW) (sort by "Start Time") we see that indeed the `ShyLU_NodeHTS` package is being enabled as well as all of its downstream packages and tests and examples.  If you look at the configure output for one of the builds such as [here](https://testing.sandia.gov/cdash/viewConfigure.php?buildid=7111206) you see:

```
Explicitly enabled SE packages on input (by user):  ShyLU_NodeHTS 1

...

Sweep forward enabling all forward library dependent packages because Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES=ON ...

-- Setting Trilinos_ENABLE_ShyLU_Node=ON because Trilinos_ENABLE_ShyLU_NodeHTS=ON
-- Setting Trilinos_ENABLE_Ifpack2=ON because Trilinos_ENABLE_ShyLU_NodeHTS=ON
-- Setting Trilinos_ENABLE_ShyLU=ON because Trilinos_ENABLE_ShyLU_Node=ON
-- Setting Trilinos_ENABLE_Teko=ON because Trilinos_ENABLE_Ifpack2=ON
-- Setting Trilinos_ENABLE_MueLu=ON because Trilinos_ENABLE_Ifpack2=ON
-- Setting Trilinos_ENABLE_ShyLU_DDFROSch=ON because Trilinos_ENABLE_Ifpack2=ON
-- Setting Trilinos_ENABLE_Stokhos=ON because Trilinos_ENABLE_Ifpack2=ON
-- Setting Trilinos_ENABLE_ROL=ON because Trilinos_ENABLE_Ifpack2=ON
-- Setting Trilinos_ENABLE_Piro=ON because Trilinos_ENABLE_Ifpack2=ON
-- Setting Trilinos_ENABLE_PanzerAdaptersSTK=ON because Trilinos_ENABLE_Ifpack2=ON
-- Setting Trilinos_ENABLE_PanzerMiniEM=ON because Trilinos_ENABLE_Teko=ON
-- Setting Trilinos_ENABLE_NOX=ON because Trilinos_ENABLE_Teko=ON
-- Setting Trilinos_ENABLE_Tempus=ON because Trilinos_ENABLE_NOX=ON
-- Setting Trilinos_ENABLE_TrilinosCouplings=ON because Trilinos_ENABLE_NOX=ON
-- Setting Trilinos_ENABLE_ShyLU_DDBDDC=ON because Trilinos_ENABLE_MueLu=ON
-- Setting Trilinos_ENABLE_ShyLU_DD=ON because Trilinos_ENABLE_ShyLU_DDBDDC=ON
-- Setting Trilinos_ENABLE_Panzer=ON because Trilinos_ENABLE_PanzerAdaptersSTK=ON

...

Processing enabled package: ShyLU_Node (HTS, Tacho, Tests, Examples)
-- ShyLU_NodeHTS_hts_test_1: Added test (BASIC, PROCESSORS=2)!
-- ShyLU_NodeTacho_Tacho_TestUtilTaskScheduler_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- ShyLU_NodeTacho_Tacho_TestUtilTaskSchedulerMultiple_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- ShyLU_NodeTacho_Tacho_TestUtilChaseLevTaskScheduler_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- ShyLU_NodeTacho_Tacho_TestSerialDoubleTaskScheduler_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- ShyLU_NodeTacho_Tacho_TestSerialDoubleTaskSchedulerMultiple_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- ShyLU_NodeTacho_Tacho_TestSerialDoubleChaseLevTaskScheduler_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexTaskScheduler_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexTaskSchedulerMultiple_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!
-- ShyLU_NodeTacho_Tacho_TestSerialDoubleComplexChaseLevTaskScheduler_MPI_1: Added test (BASIC, NUM_MPI_PROCS=1, PROCESSORS=1)!

...
```

and we see packages with 1 or more tests [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=7111175&filtercount=1&showfilters=1&field1=testspassed&compare1=43&value1=1) showing:

| SubProject | C Err | C Warn | B Err | B Warn | Not Run | Fail | Pass | Proc Time | Order |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | 
TrilinosCouplings | 0 | 0 | 0 | 0 | 0 | 0 | 22 | 1m 11s | 14
Panzer | 0 | 0 | 0 | 0 | 0 | 0 | 169 | 41m 34s | 13
Piro | 0 | 0 | 0 | 0 | 0 | 0 | 16 | 7m 13s | 12
ROL | 0 | 0 | 0 | 0 | 0 | 0 | 180 | 36m 53s | 11
Stokhos | 0 | 0 | 0 | 0 | 0 | 0 | 76 | 2m 25s | 10
Tempus | 0 | 0 | 0 | 0 | 0 | 0 | 146 | 38m 50s | 9
Rythmos | 0 | 0 | 0 | 0 | 0 | 0 | 83 | 2m 40s | 8
ShyLU_DD | 0 | 0 | 0 | 0 | 0 | 0 | 56 | 2m 30s | 7
MueLu | 0 | 0 | 0 | 0 | 0 | 0 | 63 | 7m 42s | 6
NOX | 0 | 0 | 0 | 0 | 0 | 0 | 107 | 4m 6s | 5
Teko | 0 | 0 | 0 | 0 | 0 | 0 | 19 | 2m 36s | 4
Stratimikos | 0 | 0 | 0 | 0 | 0 | 0 | 39 | 44s | 3
Ifpack2 | 0 | 0 | 0 | 0 | 0 | 0 | 46 | 1m 7s | 2
ShyLU_Node | 0 | 0 | 0 | 0 | 0 | 0 | 10 | 8s | 1

Excellent!

I will now merge this.

**Pull request merged**
