### PR TITLE
Tempus: Implementation of HHT-Alpha method

### PR DESCRIPTION
**Pull request by hillyuan**
@trilinos/tempus

## Description
1. HHT-Alpha method based upon ”Hilber, H.M, Hughes,T.J.R and Taylor, R.L. "Improved Numerical Dissipation for Time Integration Algorithms  in Structural Dynamics" Earthquake Engineering and Structural Dynamics, 5:282-292 , 1977" is implemented at Tempus::StepperHHTAlpha

2. Before this modification, it semms like that Tempus::StepperHHTAlpha was implemeted as Newmark-beta method and  planned to acomplish the algorithm according to G.M. Hulbert and J. Chung's paper in 1996, which is generally called "Generalized-Alpha method". In this modification, the former StepperHHTAlpha class is renamed as StepperGeneralizedAlpha, which I am going to implement later.

3. To define HHT-alpha scheme, only the parameter allowed to input is "Alpha=...". Other parameters (beta & gamma) are calculated automaticcally to assure this algorithm second-order accurate. The accuracy is comfirmed by the test case in /package/tempus/test/HHTAlpha/Tempus_Newmark_Sincos_SecondOrder.xml

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by rppawlo** [comment]
@ccober6 @ikalash

**Comment by mhoemmen** [comment]
Sorry, I'm not a Tempus developer and don't feel competent to review this.  I've tried CC'ing some people who might know how to review this.  If you know how to get in touch with them by e-mail or phone, you might try that.

**Comment by mhoemmen** [comment]
@ccober6 Sorry, didn't mean to rush you :-)

**Comment by ccober6** [comment]
Not a problem, just too many fires.  :)

**Pull request closed without merging**
