### PR TITLE
MueLu: composite block diagonal prolongator

### PR DESCRIPTION
**Pull request by rstumin**
Auto-PR for SHA 2912d1d

### CODE REVIEW

**Comment by mayrmt** [comment]
@rstumin A very general question: what's the conceptual difference between this implementation and the approach by @tawiesn / @pohm01, where they also combine prolongators of blocks of an `Xpetra::BlockedMatrix` to form a block-diagonal prolongator for a multiphysics system (and `R` and `RAP`, smoothers, rebalancing, .... )?

**Comment by rstumin** [comment]
> 

@mayrmt Can you point me to some code to look at? I'm grepping on things in both MueLu and Xpetra, but I'm not totally sure which is the relevant code that I should be looking at?

**Comment by pohm01** [comment]
@rstumin Not sure all the files involved in the Tobais style blocked, but here are the relevant unit tests that I can think of:
``muelu/test/unit_tests/BlockedPFactory.cpp``
``muelu/test/unit_tests/BlockedRAPFactory.cpp``
``muelu/test/unit_tests/BlockedRepartition.cpp``
``muelu/test/unit_tests/SubBlockAFactory.cpp``

There are also some old xml floating around in tests that use this. Not sure how up-to-date any of them are. For example
``muelu/test/navierstokes/myXML.xml``
``muelu/test/meshtying/meshtying2D_medium_simple.xml``

I also have some old xml inputs I was using for Drekar that did this as well.
I'll dig into this PR to see what it is doing different

**Comment by mayrmt** [comment]
@rstumin Relevant files are located in

- `packages/xpetra/src/BlockedMatrix/`
- `packages/xpetra/src/BlockedCrsMatrix/`
- `packages/xpetra/src/BlockedMap/`
- `packages/xpetra/src/BlockedMultiVector/`
- `packages/xpetra/src/BlockedVector/`
- `packages/muelu/src/Transfers/BlockedTransfers/`
- `packages/muelu/src/Transfers/BlockedSmoothers/`
- `packages/muelu/src/Misc/MueLu_BlockedRAPFactory_*`

They all rely on the concept of a "blocked" system represented in Xpetra data structures.

I am happy to provide more context, if needed. We are using these implementations to design multi-level block preconditioners for multi-physics systems (fluid/solid interaction, contact mechanics, fluid/beam interaction). @tawiesn and @pohm01 used it for MHD.

**Pull request merged**
