### PR TITLE
Teuchos: Fix #2273

### LINKED ISSUE #2273: Teuchos: Add CMake test to set HAVE_TEUCHOS_KOKKOS_PROFILING
See #2271, in particular my comment here: https://github.com/trilinos/Trilinos/pull/2272#issuecomment-367517327

Teuchos actually does define a CMake option (`Teuchos_KOKKOS_PROFILING`) that controls `HAVE_TEUCHOS_KOKKOS_PROFILING`, but the default value of the CMake option is `OFF`.  It doesn't check Kokkos' CMake options at all.  We need Teuchos to enable this automatically by default, if the Kokkos package is enabled and if Kokkos profiling is enabled.

@trilinos/teuchos 

## Motivation and Context

Lots of Trilinos packages use Teuchos timers.  We want those packages to get the advantage of Kokkos profiling, without needing to change their existing Teuchos timer infrastructure.  We also want this capability to exist by default; users shouldn't have to set nondefault CMake options to get it.

## Definition of Done

- [ ] Make Teuchos' CMake logic enable `Teuchos_KOKKOS_PROFILING` by default, if the Kokkos package is enabled and if Kokkos profiling is enabled.
- [ ] Test that the Teuchos code that uses Kokkos profiling hooks actually builds and runs correctly, since it hasn't been building or running by default.

## Related Issues
* Related to #2271

### PR DESCRIPTION
**Pull request by mhoemmen**
Make Teuchos timers use Kokkos profiling hooks by default.

@trilinos/teuchos @nmhamster 

## Description

Teuchos already had a CMake option, Teuchos_KOKKOS_PROFILING, for
making Teuchos timers use Kokkos profiling hooks.  However, that
option was OFF by default.  This commit makes Teuchos use the
KOKKOS_ENABLE_PROFILING CMake option for the default value of
Teuchos_KOKKOS_PROFILING.  Since Kokkos enables profiling by default,
this should make Teuchos use Kokkos profiling hooks by default.

I have NOT finished testing this locally yet.

## Motivation and Context

This change will make Kokkos profiling hooks record useful information for large parts of Trilinos.  In particular, MueLu makes heavy use of Teuchos timers.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@bartlettroscoe Thanks!  I can test locally with Kokkos disabled.  That's really the only option I haven't tried yet.  (Before this PR, the profiling option was ON in Kokkos and OFF in Teuchos.  After this PR, the profiling option was ON in both Kokkos and Teuchos.  That only leaves as untested (a) disabling Kokkos completely, and (b) turning off Kokkos profiling.)

**Comment by bartlettroscoe** [comment]
@mhoemmen,

Once you finish testing this and push this, I will set up a Jenkins build of Trilinos with Kokkos disabled (which will not be that much anymore so it should go fast).

**Comment by mhoemmen** [comment]
Sorry, I got interrupted yesterday and this morning, and didn't have a chance to finish testing.  I'll work on this today.

**Comment by mhoemmen** [comment]
Here is why testing with Kokkos disabled was a good idea:
```
CMake Error at cmake/tribits/core/utils/AssertDefined.cmake:79 (MESSAGE):
  Error, the variable KOKKOS_ENABLE_PROFILING is not defined!
Call Stack (most recent call first):
  packages/teuchos/CMakeLists.txt:340 (ASSERT_DEFINED)
```
I have a tiny bit of work to do first ;-) .

**Comment by mhoemmen** [comment]
#2337 blocks downstream testing.

**Comment by bartlettroscoe** [comment]
@mhoemmen, I think you will need to rebase your branch on top of 'develop' and force push to your branch in your fork to trigger another round of testing for this.

**Comment by mhoemmen** [comment]
@bartlettroscoe Thanks!  The changes all relate to making this work when the Kokkos package is disabled.  The autotester doesn't test that case by default, but I tested it by hand.

**Pull request merged**
