### PR TITLE
STK: Simd volatile overloads

### PR DESCRIPTION
**Pull request by tasmith4**
@trilinos/stk

## Motivation

Added temporary volatile overloads for stk_simd as per discussion in Kokkos issue [2770](https://github.com/kokkos/kokkos/issues/2770).

## Testing

Tested by stk_simd unit tester.

### CODE REVIEW

**Comment by mhoemmen** [comment]
@trilinos/stk @alanw0

**Comment by alanw0** [comment]
Mark @mhoemmen thanks! I don't remember if you've met Timothy (tasmith4) he's one of the newer stk guys. I need to figure out who to ask to get him added to our trilinos GitHub team.

**Comment by mhoemmen** [comment]
@trilinos/framework @jwillenbring Could you please add @tasmith4 to the list of Trilinos developers, and to the stk team?

**Comment by mhoemmen** [comment]
@alanw0 wrote:
>  I don't remember if you've met Timothy....

I have actually!  Welcome to the team btw : - )

**Comment by jwillenbring** [comment]
> @trilinos/framework @jwillenbring Could you please add @tasmith4 to the list of Trilinos developers, and to the stk team?

I sent an invite.

**Pull request merged**
