### PR TITLE
Fixed IndexBase to IndexBase64

### PR DESCRIPTION
**Pull request by gpkc**

### CODE REVIEW

**Comment by jwillenbring** [comment]
@krcb could you evaluate and if appropriate apply the change?

**Comment by gpkc** [comment]
@mhoemmen Oh, sorry about that. My mistake. Should I reopen the PR with the correct target branch?

**Comment by krcb** [comment]
@gpkc I've change the base branch of the PR to develop. The instructions for doing so are at: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request. We will run this through a test cycle and depending on the results, merge.

**Comment by mhoemmen** [comment]
Thanks @krcb and @gpkc !

**Comment by MicheldeMessieres** [comment]
This was tested and will now merge.

**Pull request merged**
