### PR TITLE
Another attempt at using Sacado with a CUDA device compiler and KOKKOS_ENABLE_CUDA=OFF

### PR DESCRIPTION
**Pull request by ibaned**
@trilinos/kokkos 
@trilinos/sacado 
@masterleinad 

## Description
see #3841

### CODE REVIEW

**Comment by masterleinad** [comment]
With the following patch, this is working for me as well
```
diff --git a/packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp b/packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
index 3574413e34..31794561e3 100644
--- a/packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
+++ b/packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
@@ -310,9 +310,9 @@ T atomic_compare_exchange( volatile T * const dest_v, const T compare, const T v
 
 // dummy for non-CUDA Kokkos headers being processed by NVCC
 #if defined(__CUDA_ARCH__) && !defined(KOKKOS_ENABLE_CUDA)
-__inline__ __device__
 template <typename T>
-T atomic_compare_exchange(volatile T * const, const Kokkos::Impl::identity<T>, const Kokkos::Impl::identity_t<T>)
+__inline__ __device__
+T atomic_compare_exchange(volatile T * const, const T, const T)
 {
   return T();
 }
diff --git a/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp b/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp
index f1ca386ea4..89b9d5e918 100644
--- a/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp
+++ b/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp
@@ -421,16 +421,16 @@ void atomic_assign( volatile T * const dest_v , const T val )
 
 // dummy for non-CUDA Kokkos headers being processed by NVCC
 #if defined(__CUDA_ARCH__) && !defined(KOKKOS_ENABLE_CUDA)
-__inline__ __device__
 template <typename T>
-T atomic_exchange(volatile T * const, const Kokkos::Impl::identity<T>)
+__inline__ __device__
+T atomic_exchange(volatile T * const, const T)
 {
   return T();
 }
 
 template < typename T >
 __inline__ __device__
-void atomic_assign(volatile T * const, const Kokkos::Impl::identity<T>)
+void atomic_assign(volatile T * const, const T)
 {
 }
 #endif
diff --git a/packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Or.hpp b/packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Or.hpp
index d146ef3148..fcf1e33d2d 100644
--- a/packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Or.hpp
+++ b/packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Or.hpp
@@ -153,7 +153,7 @@ T atomic_fetch_or( volatile T * const dest_v , const T val )
 #if defined(__CUDA_ARCH__) && !defined(KOKKOS_ENABLE_CUDA)
 template< typename T >
 __inline__ __device__
-T atomic_fetch_or(volatile T* const, Kokkos::Impl::identity_t<T>) {
+T atomic_fetch_or(volatile T* const, T) {
   return T();
 }
 #endif
diff --git a/packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp b/packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
index 89c0df8fa1..fb5104bfb2 100644
--- a/packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
+++ b/packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
@@ -308,7 +308,7 @@ T atomic_fetch_sub( volatile T * const dest_v , const T val )
 #if defined(__CUDA_ARCH__) && !defined(KOKKOS_ENABLE_CUDA)
 template< typename T >
 __inline__ __device__
-T atomic_fetch_or(volatile T* const, Kokkos::Impl::identity_t<T>) {
+T atomic_fetch_sub(volatile T* const, Kokkos::Impl::identity_t<T>) {
   return T();
 }
 #endif
```

**Comment by ibaned** [comment]
Hmm I applied a slightly different version of those patches, still trying to see if `identity_t` works... please let me know if it is sufficient of if it still needs patching. Thanks!

**Comment by masterleinad** [comment]
> Hmm I applied a slightly different version of those patches, still trying to see if `identity_t` works... please let me know if it is sufficient of if it still needs patching. Thanks!

It works with this patch:
```
diff --git a/packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp b/packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
index 843a077adc..e6f36142cc 100644
--- a/packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
+++ b/packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
@@ -310,8 +310,8 @@ T atomic_compare_exchange( volatile T * const dest_v, const T compare, const T v
 
 // dummy for non-CUDA Kokkos headers being processed by NVCC
 #if defined(__CUDA_ARCH__) && !defined(KOKKOS_ENABLE_CUDA)
-__inline__ __device__
 template <typename T>
+__inline__ __device__
 T atomic_compare_exchange(volatile T * const, const Kokkos::Impl::identity_t<T>, const Kokkos::Impl::identity_t<T>)
 {
   return T();
diff --git a/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp b/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp
index 9b268c8b4a..8c8855a267 100644
--- a/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp
+++ b/packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp
@@ -421,8 +421,8 @@ void atomic_assign( volatile T * const dest_v , const T val )
 
 // dummy for non-CUDA Kokkos headers being processed by NVCC
 #if defined(__CUDA_ARCH__) && !defined(KOKKOS_ENABLE_CUDA)
-__inline__ __device__
 template <typename T>
+__inline__ __device__
 T atomic_exchange(volatile T * const, const Kokkos::Impl::identity_t<T>)
 {
   return T();
```

Just swapping `template <typename T>` and `__inline__ __device__` in two places. Thanks for fixing my initial attempt. 
As you figured, currently a dummy implementation is sufficient for compiling. We are not using `Kokkos` at all, but `Sacado` includes it.
I guess this is the last iteration here. :slightly_smiling_face:

**Comment by ibaned** [comment]
Hurray we have converged!
I just pushed your last patch, please double-check that we are on the same page and then I will accept this into Trilinos. Thanks!

**Comment by ibaned** [comment]
I think we can ignore the above failure, lets see what the next round of testing says.

**Comment by masterleinad** [comment]
> Hurray we have converged!
I just pushed your last patch, please double-check that we are on the same page and then I will accept this into Trilinos. Thanks!

The `diff ` between the branch I tested this with and the one here is empty. :smiley:
Thank you! I am glad we solved that issue!

**Comment by ibaned** [comment]
I'm happy surprised that it did not require a rewrite of Kokkos!

**Comment by etphipp** [comment]
Sure.  I was a little confused at to what was going on (I think I approved a previous PR), so I was trying to stay out of it.

**Comment by mhoemmen** [comment]
@ibaned I was out at the C++ meeting all last week; back now! :D

**Comment by ibaned** [comment]
@mhoemmen no problem, hope it was good!

**Comment by masterleinad** [comment]
Thanks! What is the number of the release where this PR will be visible?

**Comment by ibaned** [comment]
@masterleinad not sure... possibly @maherou or @jwillenbring might now what the Trilinos release roadmap looks like.

**Pull request merged**
