### PR TITLE
ROL: Replace M_PI with Teuchos::ScalarTraits

### PR DESCRIPTION
**Pull request by mplooster**
@trilinos/teuchos 
@trilinos/rol 
Based on discussion in #1179, add pi() to Teuchos::ScalarTraits and replaced M_PI in ROL with this new function. Addresses #1178.

### CODE REVIEW

**Comment by Sbte** [comment]
This breaks compilation of PyTrilinos:

```
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsByte_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:7735:22: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<char>’
       result = (char)Teuchos::ScalarTraits< char >::SWIGTEMPLATEDISAMBIGUATOR pi();
                      ^
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsShort_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:9178:23: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<short int>’
       result = (short)Teuchos::ScalarTraits< short >::SWIGTEMPLATEDISAMBIGUATOR pi();
                       ^
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsUshort_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:9926:32: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<short unsigned int>’
       result = (unsigned short)Teuchos::ScalarTraits< unsigned short >::SWIGTEMPLATEDISAMBIGUATOR pi();
                                ^
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsInt_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:10738:21: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<int>’
       result = (int)Teuchos::ScalarTraits< int >::SWIGTEMPLATEDISAMBIGUATOR pi();
                     ^
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsUint_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:11486:30: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<unsigned int>’
       result = (unsigned int)Teuchos::ScalarTraits< unsigned int >::SWIGTEMPLATEDISAMBIGUATOR pi();
                              ^
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsLong_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:12234:22: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<long int>’
       result = (long)Teuchos::ScalarTraits< long >::SWIGTEMPLATEDISAMBIGUATOR pi();
                      ^
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsUlong_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:12982:31: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<long unsigned int>’
       result = (unsigned long)Teuchos::ScalarTraits< unsigned long >::SWIGTEMPLATEDISAMBIGUATOR pi();
                               ^
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsLongLong_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:13730:27: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<long long int>’
       result = (long long)Teuchos::ScalarTraits< long long >::SWIGTEMPLATEDISAMBIGUATOR pi();
                           ^
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp: In function ‘PyObject* _wrap_ScalarTraitsUlongLong_pi(PyObject*, PyObject*)’:
/home/sven/Trilinos/build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp:14478:36: error: ‘pi’ is not a member of ‘Teuchos::ScalarTraits<long long unsigned int>’
       result = (unsigned long long)Teuchos::ScalarTraits< unsigned long long >::SWIGTEMPLATEDISAMBIGUATOR pi();
                                    ^
```

**Comment by mplooster** [comment]
@Sbte Hmmm...it appears that the errors come from the template classes where pi was not defined because it doesn't make sense to have, for example, an unsigned long long version of pi. I would have assumed that these classes would have picked up the definition of pi in Teuchos_ScalarTraitsDecl.hpp, but perhaps I missed something that would affect the SWIG wrapping.

@trilinos/teuchos Any thoughts on why these changes would affect the SWIG wrapping? I thought I followed what was typically done for Teuchos_ScalarTraits, but the evidence indicates otherwise.

**Comment by bartlettroscoe** [comment]
> Any thoughts on why these changes would affect the SWIG wrapping? I thought I followed what was typically done for Teuchos_ScalarTraits, but the evidence indicates otherwise.

I have no idea.  PyTrilinos is a bit of a challenge to maintain because there is zero automated testing for PyTrilinos in Trilinos automated testing (see #891).

**Comment by mplooster** [comment]
After looking around more, I found [this](https://github.com/trilinos/Trilinos/blob/d32692b1d55da92911c1d4f6e1d339a050b36ce7/packages/PyTrilinos/src/Teuchos_Traits.i). It looks like I might need to add a %ignore in SWIG to handle pi for these templates (see line 282).

@trilinos/framework Is there someone who develops PyTrilinos that could confirm this potential solution?

**Comment by bartlettroscoe** [comment]
>  Is there someone who develops PyTrilinos that could confirm this potential solution?

I believe that person is @wfspotz.  @wfspotz, can you please comment on how to fix PyTrilinos?  Also, note that PyTrilinos still has no automated testing at all (see #891).

**Comment by mhoemmen** [comment]
@mplooster wrote:
> I would have assumed that these classes would have picked up the definition of pi in `Teuchos_ScalarTraitsDecl.hpp` ...

Specializations of a templated class are entirely new classes.  They don't inherit from the most generic version of the class.

**Comment by mplooster** [comment]
@mhoemmen Thanks for the clarification.

**Pull request merged**
