### PR TITLE
Switch from testing-vm to testing.sandia.gov

### PR DESCRIPTION
**Pull request by bartlettroscoe**
I noticed today that at some point I could not get to testing-vm.sandia.gov in
the browser but I could get to testing.sandia.gov.  Therefore, I figured this
might be the cause of the CDash upload problem I reported to Kitware today for
the build Trilinos-atdm-waterman-cuda-9.2-release-debug in:

* https://gitlab.kitware.com/snl/project-1/issues/89

I tested this locally on 'crf450' with:

```
$ env Trilinos_PACKAGES=Kokkos,Teuchos  \
  ./ctest-s-local-test-driver.sh sems-rhel6-gnu-7.2.0-openmp-release-debug
```

which showed, for example:

```
Submit files (using http)
   Send to track: Experimental
   Using HTTP submit method
   Drop site:http://testing.sandia.gov/cdash/submit.php?project=Trilinos
   Uploaded: /ascldap/users/rabartl/Trilinos.base/BUILDS/ATDM/CTEST_S/Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug/SRC_AND_BUILD/BUILD/Testing/20190320-2350/Test.xml
   Submission successful
```

and that showed up on CDash at:

* https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4759203

### CODE REVIEW

**Comment by prwolfe** [comment]
These are the same IP address according to ping, and infant theme gets resolved from testing-vm to testing before the ip lookup happens

```
s979713:~ prwolfe$ ping testing-vm.sandia.gov
PING testing.sandia.gov (addr)
```

If we move this we need to change the sems-autotester so that the generated links we put in the GitHub comments is corrected as well.

**Comment by jwillenbring** [comment]
> If we move this we need to change the sems-autotester so that the generated links we put in the GitHub comments is corrected as well.

This should work now already, right? Should we just change this?

**Comment by prwolfe** [comment]
> > If we move this we need to change the sems-autotester so that the generated links we put in the GitHub comments is corrected as well.
> 
> This should work now already, right? Should we just change this?

Yes - I will get a PR in for the autotester today. Until I do the links in GitHub PRs will be broken.

**Comment by bartlettroscoe** [comment]
@trilinos/framework, it is critical that this PR get merged since it seems to fix the submit failures to CDash we have been seeing since yesterday.

**Comment by bartlettroscoe** [comment]
@trilinos/framework,

Trying to to submit to `testing-vm.sandia.gov` has stopped all ATDM Trilinos builds as well.

I have verified with the TriBITS repo that switching from submitting to `testing.sandia.gov` fixes the CDash submits.  However, this PR that makes the same switch for Trilinos does not seem to be working since the Jenkins build output, for example at:

* https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_pullrequest_gcc_4.8.4/2962/console

shows the PR tester is still trying to submit to `testing-vm.sandia.gov`:

```
CTEST_DROP_LOCATION = /cdash/submit.php?project=Trilinos
CDash URL1 = https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=tr-test-0.novalocal&field2=buildname&compare2=61&value2=PR-4685-test-Trilinos_pullrequest_gcc_4.8.4-2962&field3=buildstamp&compare3=61&value3=20190323-2103-Pull Request
CDash URL2 = https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=0&filtercombine=and&field1=buildname&compare1=61&value1=PR-4685-test-Trilinos_pullrequest_gcc_4.8.4-2962&field2=buildstamp&compare2=61&value2=20190323-2103-Pull Request
CDash URL3 = https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=0&filtercombine=and&field1=buildname&compare1=61&value1=PR-4685-test-Trilinos_pullrequest_gcc_4.8.4-2962&field2=buildstamp&compare2=61&value2=20190323-2103-Pull Request
Starting configure step.
   Each . represents 1024 bytes of output
    ..................................................  Size: 50K
    ..................................................  Size: 100K
    ..................................................  Size: 150K
    ..................................................  Size: 200K
    ..................................................  Size: 250K
    ..................................................  Size: 300K
    ..................................................  Size: 350K
    ..................................................  Size: 400K
    ................................. Size of output: 432K
   Error when uploading file: /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/pull_request_test/Testing/20190323-2103/Configure.xml
   Error message was: The requested URL returned error: 503 Service Unavailable
   Problems when submitting via HTTP
configure submit error = -1
Configure suceeded.
```

Someone on the framework team will need to manually merge this branch in order to fix the Trilinos PR testing system.

I am going to manually merge this and some other branches to the `atdm-nightly` branch to get ATDM Trilinos builds running again in the meantime.

**Comment by mhoemmen** [comment]
@bartlettroscoe If I had the power, I would do it for you.  This is blocking so much work.

**Comment by prwolfe** [comment]
Looking at the request by @ZUUL42 I think it covers whats in this one and more. I would use that one.

**Comment by prwolfe** [comment]
> Someone on the framework team will need to manually merge this branch in order to fix the Trilinos PR testing system.

I pushed changes to all of the testing-vm references in our other repos this morning. Only this and the one in the sems repository are still outstanding. I expect this was in simple_testing.cmake  in our gitlab-ex space. I will check this today.

**Comment by mhoemmen** [comment]
@trilinos/framework @william76 Please just merge this without running through PR testing.

**Comment by prwolfe** [comment]
Obsolete - closing

**Pull request closed without merging**
