### PR TITLE
Kokkos promotion ci check

### PR DESCRIPTION
**Pull request by ndellingwood**
This PR contains tentative snapshots of release-candidate-4.0.0 branches, and associated compatibility updates in Trilinos, for the purpose of checking status of these branches with the configurations used by PR testing.

The final release branches are not yet complete and this PR **should not** be merged in the event of passing CI checks

### CODE REVIEW

**Comment by ndellingwood** [comment]
Marking WIP

**Compilation error summary**:

**All builds** have similar compilation error in Compadre:
```
In file included from /scratch/trilinos/jenkins/ascic115/workspace/Trilinos_PR_clang-11.0.1/Trilinos/packages/compadre[Compadre_KokkosParser.cpp:1](https://github.com/trilinos/Trilinos//blob/master/Compadre_KokkosParser.cpp#L1):
/scratch/trilinos/jenkins/ascic115/workspace/Trilinos_PR_clang-11.0.1/Trilinos/packages/compadre[Compadre_KokkosParser.hpp:25](https://github.com/trilinos/Trilinos//blob/master/Compadre_KokkosParser.hpp#L25):16: error: unknown type name 'KokkosInitArguments'
  KokkosParser(KokkosInitArguments args, bool print_status = false);
               ^
/scratch/trilinos/jenkins/ascic115/workspace/Trilinos_PR_clang-11.0.1/Trilinos/packages/compadre[Compadre_KokkosParser.cpp:6](https://github.com/trilinos/Trilinos//blob/master/Compadre_KokkosParser.cpp#L6):28: error: unknown type name 'KokkosInitArguments'
KokkosParser::KokkosParser(KokkosInitArguments args, bool print_status) {
```

**Trilinos_PR_cuda-11.4.2-uvm-off** errors in Stokhos (same for each of 4 errors):
```
Error building packages/stokhos/src/CMakeFiles/stokhos_muelu_mp_16_serial.dir/MueLu_Zoltan2Interface_MP_Vector_16_Serial.cpp.o 
Error building packages/stokhos/src/CMakeFiles/stokhos_muelu_mp_16_cuda.dir/MueLu_Zoltan2Interface_MP_Vector_16_Cuda.cpp.o 
Error building packages/stokhos/src/CMakeFiles/stokhos_muelu_pce_serial.dir/MueLu_Zoltan2Interface_UQ_PCE_Serial.cpp.o 
Error building packages/stokhos/src/CMakeFiles/stokhos_muelu_pce_cuda.dir/MueLu_Zoltan2Interface_UQ_PCE_Cuda.cpp.o 

/projects/sems/install/rhel7-x86_64/sems/v2/tpl/cuda/11.4.2/gcc/10.1.0/base/ex2t3fn/targets/x86_64-linux/include/cub/agent/agent_radix_sort_onesweep.cuh(225): error: expected an identifier

1 error detected in the compilation of "trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/pull_request_test/packages/stokhos/src/MueLu_Zoltan2Interface_MP_Vector_16_Serial.cpp".
```

----
----

**Unit test failures**:

**All builds**:

`TrilinosCouplings_Example_Maxwell_Tpetra_MueLu_MPI_1` - needs `is_finalized` check
```
Error: Kokkos::finalize() has already been called.
```

`TrilinosInstallTests_doInstall` - fail appears due compilation errors resulting in unavailable package libs
```
CMake Error at /scratch/trilinos/jenkins/ascic115/workspace/Trilinos_PR_clang-11.0.1/pull_request_test/packages/compadre/src/cmake_install.cmake:57 (file):
  file INSTALL cannot find
  "/scratch/trilinos/jenkins/ascic115/workspace/Trilinos_PR_clang-11.0.1/pull_request_test/packages/compadre/src/libcompadre.so.13.5":
  No such file or directory.
Call Stack (most recent call first):
  /scratch/trilinos/jenkins/ascic115/workspace/Trilinos_PR_clang-11.0.1/pull_request_test/packages/compadre/cmake_install.cmake:47 (include)
  /scratch/trilinos/jenkins/ascic115/workspace/Trilinos_PR_clang-11.0.1/pull_request_test/cmake_install.cmake:347 (include)
```

----

**Trilinos_PR_cuda-11.4.2-uvm-off**

`Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests_MPI_1`
```
4. AnalyticPolynomialsMatch_Sacado_Fad_DFadType_Sacado_Fad_DFadType_HierarchicalNodalComparisons_UnitTest ... :0: : block: [947,0,0], thread: [0,31,0] Assertion `Allocation failed.` failed.
:0: : block: [879,0,0], thread: [0,127,0] Assertion `Allocation failed.` failed.
:0: : block: [859,0,0], thread: [0,95,0] Assertion `Allocation failed.` failed.
:0: : block: [775,0,0], thread: [0,31,0] Assertion `Allocation failed.` failed.
:0: : block: [848,0,0], thread: [0,95,0] Assertion `Allocation failed.` failed.
:0: : block: [861,0,0], thread: [0,31,0] Assertion `Allocation failed.` failed.
:0: : block: [848,0,0], thread: [0,127,0] Assertion `Allocation failed.` failed.
:0: : block: [943,0,0], thread: [0,127,0] Assertion `Allocation failed.` failed.
:0: : block: [912,0,0], thread: [0,127,0] Assertion `Allocation failed.` failed.
:0: : block: [902,0,0], thread: [0,95,0] Assertion `Allocation failed.` failed.
:0: : block: [860,0,0], thread: [0,31,0] Assertion `Allocation failed.` failed.
:0: : block: [904,0,0], thread: [0,63,0] Assertion `Allocation failed.` failed.
:0: : block: [860,0,0], thread: [0,127,0] Assertion `Allocation failed.` failed.
cudaStreamSynchronize(stream) error( cudaErrorAssert): device-side assert triggered /scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:144
```

`KokkosCore_UnitTest_CudaTimingBased_MPI_1` failure - spurious, this test should be disabled in all Cuda builds...

` TpetraCore_Issue1454_MPI_4`
```
0. Distributor_Issue1454_UnitTest ... 
 
 p=0: *** Caught standard std::exception of type 'std::out_of_range' :
 
  /scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/tpetra/core/test/Distributor/Issue1454.cpp:174:
  
  Throw number = 1
  
  Throw test that evaluated to true: (imports_host(i)) != (i / 3)
  
  Error, (imports_host(i) = 0) != (i / 3 = 1)!
 [FAILED]  (0.557 sec) Distributor_Issue1454_UnitTest
 Location: /scratch/trilinos/workspace/Trilinos_PR_cuda-11.4.2-uvm-off/Trilinos/packages/tpetra/core/test/Distributor/Issue1454.cpp:90
```

----

**Trilinos_PR_gcc-8.3.0-debug**

` FEI_fei_ubase_MPI_3` - random failure reported in #11530 

----

**Trilinos_PR_gcc-8.3.0-serial**

`KokkosCore_UnitTest_Serial1` - known failing subtest, that I disabled with SHA [7e16f4f](https://github.com/trilinos/Trilinos/pull/11544/commits/7e16f4f0fbab746c3e6b6c0058882958f61e63f1) ...
```
[  FAILED  ] serial.join_backward_compatibility (0 ms)
```

**Comment by PhilMiller** [comment]
That `join_backward_compatibility` test is not something that should fail arbitrarily. Something's going wrong there that we should fix.

**Comment by PhilMiller** [comment]
Oh, I see, it's deprecated code enablement that's causing the failure. That's fine.

**Comment by ndellingwood** [comment]
Was not able to reproduce the Stokhos compilation errors in the Cuda build, nor the Tpetra and Intrepid2 unit test failures. Retesting PR (with temp update for the compadre error and trilinoscouplings test) to check these failures reproduce

**Comment by ndellingwood** [comment]
Reproduced the `TpetraCore_Issue1454_MPI_4` failure from the Trilinos_PR_cuda-11.4.2-uvm-off build; the test passes when `CUDA_LAUNCH_BLOCKING=1`, so likely a missing fence somewhere

**Comment by ndellingwood** [comment]
The `Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests_MPI_1` test passes for me in the cuda/11.4.2 non-uvm build

**Comment by ndellingwood** [comment]
This PR served its purpose, all failures have been accounted for and should be addressed

**Pull request closed without merging**
