### PR TITLE
Panzer: add required test dependence on pamgen for adapters-ioss #2206

### PR DESCRIPTION
**Pull request by rppawlo**
pamgen is now required for adapters-ioss tests #2206

### CODE REVIEW

**Comment by jmgate** [comment]
Is this good to merge then?

**Comment by rppawlo** [comment]
> Is this good to merge then?

just waiting on autotester to run

**Comment by jmgate** [comment]
Blast.  I wonder if this is again due to needing a clean build directory.

**Comment by rppawlo** [comment]
@allevin - can you post this build failure? Suspect is it a machine whose workspace needs to be wiped.

**Comment by allevin** [comment]
Here you go... Build #349

[ 64%] Built target teko
[ 64%] Building CXX object packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_ExplicitModelEvaluator.cpp.o
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/panzer/disc-fe/src/Panzer_EquationSet_DefaultImpl_impl.hpp:46:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/panzer/disc-fe/src/Panzer_EquationSet_DefaultImpl.cpp:50:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/panzer/disc-fe/src/Panzer_DOF.hpp:1:31: fatal error: Panzer_DOF_decl.hpp: No such file or directory
 #include "Panzer_DOF_decl.hpp"
                               ^
compilation terminated.
make[2]: *** [packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_EquationSet_DefaultImpl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/panzer/disc-fe/src/Panzer_BCStrategy_Dirichlet_DefaultImpl_impl.hpp:68:0,
                 from /scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/Trilinos/packages/panzer/disc-fe/src/Panzer_BCStrategy_Dirichlet_DefaultImpl.cpp:48:
/scratch/trilinos/workspace/trilinos-folder/Trilinos_autotester_test/BUILD_pull_request/packages/panzer/disc-fe/src/Panzer_DOF.hpp:1:31: fatal error: Panzer_DOF_decl.hpp: No such file or directory
 #include "Panzer_DOF_decl.hpp"
                               ^
compilation terminated.
make[2]: *** [packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_BCStrategy_Dirichlet_DefaultImpl.cpp.o] Error 1
Scanning dependencies of target nox
[ 64%] Building CXX object packages/nox/src/CMakeFiles/nox.dir/NOX_Abstract_Vector.C.o
[ 64%] Building CXX object packages/nox/src/CMakeFiles/nox.dir/NOX_Abstract_Group.C.o
[ 64%] Building CXX object packages/nox/src/CMakeFiles/nox.dir/NOX_LineSearch_Factory.C.o
[ 64%] Building CXX object packages/nox/src/CMakeFiles/nox.dir/NOX_LineSearch_Utils_Slope.C.o

**Comment by jmgate** [comment]
@jwillenbring, can you clean out the build on this machine as well?  We really need a way to be able to clean these builds automatically somehow.

**Pull request merged**
