### PR TITLE
KokkosKernels: Fix multiple gemm issues with complex type 

### PR DESCRIPTION
**Pull request by seheracer**
@trilinos/kokkos-kernels 

## Motivation

This PR 
1. fixes the issue https://github.com/trilinos/Trilinos/issues/6470 and
2. applies the same changes in KK PR https://github.com/kokkos/kokkos-kernels/pull/550 

Note to @brian-kelley: your recent changes in `kokkos-kernels/src/blas/impl/KokkosBlas3_gemm_impl.hpp` in KK develop do not exist in Trilinos develop (before and after this PR).
  

## Testing

```
[sacer@kokkos-dev-2 testing]$ ../scripts/test_all_sandia --spot-check --arch=Volta70
Running on machine: sems
Going to test compilers:  gcc/5.3.0 gcc/7.2.0 intel/17.0.1 clang/3.9.0 cuda/9.2
Testing compiler gcc/5.3.0
Testing compiler gcc/7.2.0
Testing compiler intel/17.0.1
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-7.2.0-Serial-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-release
  PASSED gcc-7.2.0-Serial-release
Testing compiler cuda/9.2
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED intel-17.0.1-OpenMP-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job cuda-9.2-Cuda_OpenMP-release
  PASSED cuda-9.2-Cuda_OpenMP-release
  Starting job cuda-9.2-Cuda_Pthread-release
  PASSED cuda-9.2-Cuda_Pthread-release
  Starting job cuda-9.2-Cuda_Serial-release
  PASSED cuda-9.2-Cuda_Serial-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=214 run_time=395
cuda-9.2-Cuda_OpenMP-release build_time=509 run_time=198
cuda-9.2-Cuda_Pthread-release build_time=466 run_time=264
cuda-9.2-Cuda_Serial-release build_time=474 run_time=271
gcc-5.3.0-OpenMP-release build_time=208 run_time=109
gcc-7.2.0-Serial-release build_time=180 run_time=190
intel-17.0.1-OpenMP-release build_time=394 run_time=118
#######################################################
FAILED TESTS
#######################################################
```

### CODE REVIEW

**Comment by ndellingwood** [comment]
@seheracer please add me as reviewer for the matching kokkos-kernels PR with the conjugate-transpose updates.

**Comment by ndellingwood** [comment]
> Thanks for the fix! I really hope we aren't trying to compete with cuBLAS or MKL. It's good to have this fallback, but I really want `KokkosBlas::gemm` to call cuBLAS or MKL if applicable. I hope that's the case.

@mhoemmen the fallback changes in this PR were to address a pretty drastic shortcoming in performance in the cublas implementation, I'll let @seheracer expand on details.

**Comment by mhoemmen** [comment]
@ndellingwood Ah, OK, sorry.  Never mind then.  I think I know the context.  Hopefully there is a branch that uses cuBLAS where it is fast.

**Comment by ndellingwood** [comment]
> Hopefully there is a branch that uses cuBLAS where it is fast.

@mhoemmen yes, that is how it is intended to work. With certain matrix shapes the cublas gemm is quite slow and the code path related to this PR will be taken, otherwise cublas is used.

**Comment by seheracer** [comment]
@mhoemmen There are 3 versions of GEMM we are talking about:
1)  cuBLAS GEMM: This is the default for KokkosBlas::gemm when CUDA and cuBLAS are enabled. However, for A^TB with tall and skinny matrices, cuBLAS gemm is slow and NVIDIA confirmed this. That's why we implemented DotBasedGEMM, which is faster than cuBLAS gemm when some conditions hold. 

2) DotBasedGEMM: This replaces cuBLASgemm call when some conditions (tall&skinny, etc.) hold. Since this is replacement for cuBLAS gemm, it gets called only when CUDA and cuBLAS are enabled and the above-referred conditions hold.

3) Fallback GEMM: This gets called when no TPLs are enabled (I'm not 100% sure though).           

This PR is confusing because it fixes some issues in both DotBasedGEMM and fallback GEMM, both related to complex scalar types. Sorry for the confusion.

**Comment by seheracer** [comment]
Failing tests are probably due to:

https://github.com/trilinos/Trilinos/issues/6361
https://github.com/trilinos/Trilinos/pull/6476

@lucbv Does this error look the same as those in the above-mentioned MueLu issues?  

```
+ther
+
default/EasyParameterListInterpreter/driver_drekar1_np4.xml : failed
Testing: default/EasyParameterListInterpreter/driver_drekar2_np4.xml
--- default/Output/driver_drekar2_tpetra.gold_filtered	2019-12-19 02:04:03.867718262 -0700
+++ default/Output/driver_drekar2_tpetra.out_filtered	2019-12-19 02:04:03.875718380 -0700
@@ -469,3 +469,5 @@
 Smoother (level 3) pre  : <Direct> solver interface
 Smoother (level 3) post : no smoother

```

**Comment by lucbv** [comment]
@seheracer you are correct

**Comment by mhoemmen** [comment]
@seheracer @ndellingwood Thanks for explaining!

**Comment by seheracer** [comment]
@lucbv I rebased to the current develop branch that has your changes from today and now it's asking for muelu approval.

**Comment by srajama1** [comment]
> Thanks for the fix! I really hope we aren't trying to compete with cuBLAS or MKL. It's good to have this fallback, but I really want `KokkosBlas::gemm` to call cuBLAS or MKL if applicable. I hope that's the case.

We have reported this to NVIDIA and they have fixed it as well. Consider Kokkos Kernels as a reference implementation until you get the fix in cublas. This is a model that helps our users make progress instead of waiting for the next release.

**Comment by srajama1** [comment]
BTW, none of these improvements in Kokkos kernels will matter if Tpetra keeps calling vendor BLAS/LAPACK directly and short circuiting Kokkos Kernels.

**Comment by mhoemmen** [comment]
Show the lines of code in which this is the case and file an issue.

**Comment by srajama1** [comment]
@kddevin is taking care of this.

**Pull request merged**
