### PR TITLE
Framework: Update CMake minimum requirement to 3.17.x

### PR DESCRIPTION
**Pull request by william76**
@trilinos/framework 

## Motivation
Updates the minimum CMake requirement for Trilinos to 3.17.0

- Part of #8401 
- Part of #8520
- Depends on #8521

### CODE REVIEW

**Comment by csiefer2** [comment]
@william76 Can we switch the default cmake on our systems from 3.10.3 to 3.17.1?

**Comment by william76** [comment]
FYI @jwillenbring

**Review by ZUUL42 — APPROVED** [review]

**Comment by csiefer2** [comment]
Miranda updated the modules!

**Comment by william76** [comment]
#8521 merged in, so I've removed the WIP flag so this will run through a cycle of the tester.

We won't merge this in until sometime next week once the @trilinos/framework team has had a chance to get together and make the go/no-go determination.

**Comment by william76** [comment]
@jwillenbring @ZUUL42 @e10harvey @prwolfe 
Looks like this passed as well as the other PR which upped the CMake version in use to 3.17.  I'll most likely be out most of next week but I might be on some in the afternoons -- depending on when I get relieved from child duty ;) -- If you guys want to merge this in sometime then it's fine.  It's probably a good idea to send out the email Monday and maybe do the merge around Tues @ COB?  That'd give you guys the rest of the week to field any issues.

We might need to update some documentation regarding the Intel build somewhere... setting `CMAKE_EXE_LINKER_FLAGS` in the .cmake file worked for me everywhere _but_ the PR's, which seemed to require setting the `LDLFAGS` envvar. It makes me wonder if that compiler check wants some other CMake var set?

**Review by e10harvey — APPROVED** [review]

**Comment by jwillenbring** [comment]
I am going to throw the automerge flag on this. Testing looks reasonably decent today, so this will give us a little time before the end of the day to start to see if there are any issues.

**Pull request merged**
