### PR TITLE
MueLu: More Driver upgrades

### PR DESCRIPTION
**Pull request by csiefer2**
Auto-PR for SHA cb87f9d

### CODE REVIEW

**Comment by aprokop** [comment]
Can't you do this through an input deck? Like stationary one-level multigrid with identity coarse solver?

**Comment by csiefer2** [comment]
@aprokop  Sure.  But I want to hammer in on the matvec without distractions.  I'm using this for some performance testing...

**Comment by aprokop** [comment]
I understand that. But you tradeoff by adding extra code that will need to be maintained.

**Comment by csiefer2** [comment]
Indeed.  And I'm prepared to maintain it.

**Pull request merged**
