### PR TITLE
Re-enable STK, PIRO, NOX and Panzer in cuda 11 no-uvm builds

### PR DESCRIPTION
**Pull request by rppawlo**
@trilinos/<teamName>

## Motivation

STK, PIRO, NOX and Panzer are all disbled in the cuda 11 no-uvm PR builds. Not sure why. Reenabling to get a baseline to see what we need to fix.

### CODE REVIEW

**Comment by cgcgcg** [comment]
@rppawlo Looks like further down in the file a couple of Piro and Panzer tests are being disabled. Would it make sense to enable them as well?

**Comment by rppawlo** [comment]
Thanks for pointing that out @cgcgcg . I know some of those were disabled due to excessive runtimes early on in ATDM. They might be ok now that most code is correctly using cuda kernels. I will wait for the current round of CI testing to finish and then enable those as well.

**Comment by bartlettroscoe** [comment]
@rppawlo, what this PR motivated by #11085?

Note that changing this file will (or at least should) trigger the enable of every Trilinos package and their tests (see #11057).  And that will run every build, not just this one CUDA build being impacted by this change.

FYI: I have developed a tool to make it easier to drive Trilinos PR builds using GenConfig locally (see [run_trilinos_pr_builds](https://gitlab-ex.sandia.gov/rabartl/run_trilinos_pr_builds/-/blob/master/README.md)). That way, you don't take up PR testing resources just to test out a single build.  For example, if you have access to an ascicgpu machine, you setup the Trilinos repo as:

```
$ cd <trilinos-src>
$ git clone git@gitlab-ex.sandia.gov:rabartl/run_trilinos_pr_builds.git
$ echo /run_trilinos_pr_builds/ >> .git/info/exclude
$ ./packages/framework/get_dependencies.sh --srn
```

then you run:

```
$ cd <some-base-dir>/

$ ln -s <trilinosSrcDir>/run_trilinos_pr_builds/run_trilinos_pr_builds.py .

$ ./run_trilinos_pr_builds.py \
  -b reenable-packages \
  -p STK,Piro,NOX \
  -j 32 -t 8 \
  cuda-11.4.2-uvm-off
```

and that will configure, build, and run tests locally (archiving everything in local log files) and post to CDash (and print the CDash URL).

And that will only enable the packages STK, Piro and NOX with their tests and the packages and the tests downstream from those (instead of everything).

Just an idea that might reduce the load in the PR testing system and provide faster results.

**Comment by bartlettroscoe** [comment]
FYI: Without the PR #11057, this PR would not trigger the testing of anything.  The fact that this PR was posted with the expectation that all packages would get tested is confirmation that the change in #11057 was needed.

**Comment by rppawlo** [comment]
This has been completed in other PRs. Closing.

**Pull request closed without merging**
