### PR TITLE
Stratimikos: most adapters need Epetra

### PR DESCRIPTION
**Pull request by ibaned**
The dependency on Epetra of most Stratimikos
solver adapters was not properly encoded in CMake
because until recently Epetra was a required
dependency of Stratimikos.
This commit disables solver interfaces that
require Epetra when Epetra is disabled.

@bartlettroscoe  this follows up on #313

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@iband, This will likely not be enough to fix this.  You will also need to set  HAVE_STRATIMIKOS_ML to OFF.  Otherwise, the Stratimikos::DefaultLinearSolverBuilder will try pull in support for the ML preconditioner factory and that can't work.

**Comment by ibaned** [comment]
yep, you're right. I just forced-pushed a more in-depth version of this. will start the build with ML now....

**Comment by ibaned** [comment]
The build with ML enabled and Epetra disabled just succeeded with this commit.

**Comment by bartlettroscoe** [comment]
@iband,

Do you want me to test and push?

**Comment by bartlettroscoe** [comment]
I verified that this commit allows Stratimkos to build with:

```
$  ./do-configure -DTrilinos_ENABLE_Epetra=OFF -DTrilinos_ENABLE_Stratimikos=ON
$ make -j16
```

No tests run because tests get disabled as shown in the configure output:

```
-- Setting Stratimikos_ENABLE_TESTS=OFF because Stratimikos has a required test/example dependence on disabled package ThyraEpetraAdapters
```

 am running the checkin-test-sems.sh script right now to push this.

**Comment by bartlettroscoe** [comment]
This has been pushed as the rebased commit 167da14:

```
167da14 "Stratimikos: most adapters need Epetra (#313)"
Author: Dan Ibanez <daibane@sandia.gov>
Date:   Wed Feb 8 13:49:58 2017 -0700 (58 minutes ago)

M       packages/stratimikos/adapters/CMakeLists.txt
M       packages/stratimikos/src/CMakeLists.txt
```

I amended the log message to put in the original issue ID #313 for better tracability.

Closing as complete (because GitHub is not smart enough to recognize the rebased and amended commit satisfies the pull request).

**Pull request closed without merging**
