### PR TITLE
packages/framework: Add ascdo gnu 10.3.0 builds

### PR DESCRIPTION
**Pull request by e10harvey**
## Motivation

[TRILFRAME-495](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-495) - evaluate MVP.

## Testing

Manually:

## ascdo-gnu-10.3.0-serial
```
$ source ../packages/framework/GenConfig/gen-config.sh rhel7_ascdo-gnu-10.3.0-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_all --cmake-fragment ascdo-gnu-10.3.0 ..
<snip>
********************************************************************************
           E N V I R O N M E N T  L O A D E D  S U C E S S F U L L Y
********************************************************************************



********************************************************************************
          T Y P E  exit  T O  L E A V E  T H E  E N V I R O N M E N T
********************************************************************************


********************************************************************************
                      B E G I N  C O N F I G U R A T I O N
********************************************************************************


Please run:

  $ cmake -C /path/to/fragment.cmake /path/to/src

where "/path/to/fragment.cmake" is replaced with your generated cmake fragment file
and "/path/to/src" is replaced with your build source.

(rhel7_ascdo-gnu-10.3.0-serial) $ cmake -C ascdo-gnu-10.3.0 ..
<snip>
Finished configuring Trilinos!

-- If publishing results using Trilinos, please cite us: https://trilinos.github.io/cite.html
-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/Trilinos/genConfigTrilframe-495

(rhel7_ascdo-gnu-10.3.0-serial) $ make -i -j32
<snip>
/path/to/packages/seacas/libraries/ioss/src/main/io_modify.C: In function 'bool {anonymous}::handle_rename(const std::vector<std::__cxx11::basic_string<char> >&, Ioss::Region&)':
/path/to/packages/seacas/libraries/ioss/src/main/io_modify.C:1134:7: error: 'ex_entity_type' was not declared in this scope; did you mean 'get_entity_type'?
 1134 |       ex_entity_type exo_type  = Ioex::map_exodus_type(ioss_type);
      |       ^~~~~~~~~~~~~~
      |       get_entity_type
<snip>
(rhel7_ascdo-gnu-10.3.0-serial) $ ctest -j32
<snip>
99% tests passed, 12 tests failed out of 2552

Subproject Time Summary:
Amesos                     =   0.71 sec*proc (4 tests)
Amesos2                    =   1.17 sec*proc (9 tests)
Anasazi                    =  35.94 sec*proc (78 tests)
AztecOO                    =   0.96 sec*proc (17 tests)
Belos                      =  95.81 sec*proc (146 tests)
Compadre                   =  43.21 sec*proc (29 tests)
Domi                       =  21.64 sec*proc (25 tests)
Epetra                     =  15.29 sec*proc (64 tests)
EpetraExt                  =   3.33 sec*proc (12 tests)
FEI                        =   7.48 sec*proc (18 tests)
Galeri                     =   1.20 sec*proc (8 tests)
Ifpack                     =  14.79 sec*proc (46 tests)
Ifpack2                    =  24.19 sec*proc (40 tests)
Intrepid                   = 738.57 sec*proc (144 tests)
Intrepid2                  = 950.17 sec*proc (183 tests)
Isorropia                  =   0.53 sec*proc (6 tests)
Kokkos                     = 577.42 sec*proc (40 tests)
KokkosKernels              = 292.03 sec*proc (17 tests)
Komplex                    =   0.05 sec*proc (1 test)
ML                         =  14.22 sec*proc (32 tests)
MiniTensor                 =   0.12 sec*proc (2 tests)
Moertel                    =   0.00 sec*proc (2 tests)
MueLu                      = 433.24 sec*proc (52 tests)
NOX                        =  64.62 sec*proc (81 tests)
Pamgen                     =   8.31 sec*proc (67 tests)
Panzer                     =   0.54 sec*proc (5 tests)
Phalanx                    =  10.81 sec*proc (37 tests)
Piro                       = 491.41 sec*proc (18 tests)
ROL                        = 1704.36 sec*proc (178 tests)
RTOp                       =   1.02 sec*proc (22 tests)
Rythmos                    = 431.94 sec*proc (85 tests)
SEACAS                     =  40.00 sec*proc (16 tests)
STK                        =  19.55 sec*proc (10 tests)
Sacado                     =  12.17 sec*proc (299 tests)
Shards                     =   0.43 sec*proc (4 tests)
ShyLU_Node                 =   9.17 sec*proc (6 tests)
Stokhos                    = 190.34 sec*proc (57 tests)
Stratimikos                =  52.89 sec*proc (39 tests)
Teko                       =  71.29 sec*proc (14 tests)
Tempus                     = 7894.79 sec*proc (158 tests)
Teuchos                    =   3.65 sec*proc (119 tests)
Thyra                      =   8.69 sec*proc (58 tests)
Tpetra                     = 287.15 sec*proc (165 tests)
TrilinosATDMConfigTests    =  39.22 sec*proc (12 tests)
TrilinosBuildStats         =   1.59 sec*proc (2 tests)
TrilinosCouplings          = 157.89 sec*proc (19 tests)
TrilinosFrameworkTests     =   8.16 sec*proc (8 tests)
TrilinosInstallTests       =   1.52 sec*proc (2 tests)
Triutils                   =   0.10 sec*proc (2 tests)
Xpetra                     =   2.88 sec*proc (18 tests)
Zoltan                     =   5.92 sec*proc (36 tests)
Zoltan2                    =  76.81 sec*proc (40 tests)

Label Time Summary:
ConvergenceTest    =   9.11 sec*proc (3 tests)
IntegrationTest    =  25.81 sec*proc (17 tests)
UtilityTest        =   0.02 sec*proc (1 test)
convergence        =   9.11 sec*proc (3 tests)
integration        =  25.81 sec*proc (17 tests)
kdtree             =   8.27 sec*proc (8 tests)
kokkos             =  25.83 sec*proc (18 tests)
manifold           =   9.11 sec*proc (3 tests)
nanoflann          =   8.27 sec*proc (8 tests)
staggered          =  10.92 sec*proc (3 tests)
utility            =   0.02 sec*proc (1 test)
vector             =   7.76 sec*proc (4 tests)

Total Test time (real) = 754.54 sec

The following tests FAILED:
	1231 - ShyLU_NodeTacho_Tacho_Test_Util.x (Not Run)
	1232 - ShyLU_NodeTacho_Tacho_Test_ETI_double_Serial.x (Not Run)
	1233 - ShyLU_NodeTacho_Tacho_Test_ETI_float_Serial.x (Not Run)
	1234 - ShyLU_NodeTacho_Tacho_Test_ETI_complex_double_Serial.x (Not Run)
	1235 - ShyLU_NodeTacho_Tacho_Test_ETI_complex_float_Serial.x (Not Run)
	1245 - SEACASIoss_pamgen_exodus_io_info (Failed)
	1248 - SEACASIoss_Utst_iofx (Not Run)
	1250 - SEACASIoss_Utst_blob_write_read (Subprocess aborted)
	1935 - Moertel_TwoSquares (Not Run)
	1936 - Moertel_Hex_3D (Not Run)
	2551 - TrilinosInstallTests_doInstall (Failed)
	2552 - TrilinosInstallTests_find_package_Trilinos (Not Run)
Errors while running CTest
```

## rhel7_ascdo-gnu-10.3.0-openmp
```
$ source ../packages/framework/GenConfig/gen-config.sh rhel7_ascdo-gnu-10.3.0-openmp_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_all --cmake-fragment ascdo-gnu-10.3.0-openmp ..
<snip>
********************************************************************************
           E N V I R O N M E N T  L O A D E D  S U C E S S F U L L Y
********************************************************************************



********************************************************************************
          T Y P E  exit  T O  L E A V E  T H E  E N V I R O N M E N T
********************************************************************************


********************************************************************************
                      B E G I N  C O N F I G U R A T I O N
********************************************************************************


Please run:

  $ cmake -C /path/to/fragment.cmake /path/to/src

where "/path/to/fragment.cmake" is replaced with your generated cmake fragment file
and "/path/to/src" is replaced with your build source.

(rhel7_ascdo-gnu-10.3.0-openmp) $ cmake -C ascdo-gnu-10.3.0-openmp ..
<snip>
Finished configuring Trilinos!

-- If publishing results using Trilinos, please cite us: https://trilinos.github.io/cite.html
-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/Trilinos/genConfigTrilframe-495-openmp

(rhel7_ascdo-gnu-10.3.0-openmp) $ make -i -j32
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.h:10:10: fatal error: ioex_export.h: No such file or directory
<snip>
/path/to/Trilinos/packages/moertel/example/TwoSquares/../ExodusInterface.h:56:10: fatal error: exodusII.h: No such file or directory
<snip>
/path/to/Trilinos/packages/moertel/example/Hex3D/../ExodusInterface.h:56:10: fatal error: exodusII.h: No such file or directory
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1134:7: error: 'ex_entity_type' was not declared in this scope; did you mean 'get_entity_type'?
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1135:53: error: 'exo_type' was not declared in this scope
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1135:34: error: 'ex_put_name' was not declared in this scope
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1136:19: error: 'EX_NOERR' was not declared in this scope
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1137:9: error: 'Ioex' has not been declared
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1861:5: error: 'ex_get_all_times' was not declared in this scope
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1865:7: error: 'ex_put_time' was not declared in this scope
<snip>
(rhel7_ascdo-gnu-10.3.0-openmp) $ ctest -j32
<snip>
99% tests passed, 7 tests failed out of 2750

Subproject Time Summary:
Amesos                     =   1.78 sec*proc (4 tests)
Amesos2                    =   2.79 sec*proc (9 tests)
Anasazi                    =  63.16 sec*proc (78 tests)
AztecOO                    =   1.40 sec*proc (17 tests)
Belos                      = 161.98 sec*proc (146 tests)
Compadre                   =  37.64 sec*proc (29 tests)
Domi                       =  31.81 sec*proc (25 tests)
Epetra                     =  24.67 sec*proc (64 tests)
EpetraExt                  =   4.90 sec*proc (12 tests)
FEI                        =  13.66 sec*proc (18 tests)
Galeri                     =   2.60 sec*proc (8 tests)
Ifpack                     =  31.99 sec*proc (46 tests)
Ifpack2                    =  44.86 sec*proc (40 tests)
Intrepid                   = 953.83 sec*proc (144 tests)
Intrepid2                  = 1376.09 sec*proc (350 tests)
Isorropia                  =   0.90 sec*proc (6 tests)
Kokkos                     = 1185.04 sec*proc (46 tests)
KokkosKernels              = 695.69 sec*proc (23 tests)
Komplex                    =   0.07 sec*proc (1 test)
ML                         =  28.38 sec*proc (32 tests)
MiniTensor                 =   0.26 sec*proc (2 tests)
Moertel                    =   0.00 sec*proc (2 tests)
MueLu                      = 645.50 sec*proc (52 tests)
NOX                        = 132.00 sec*proc (81 tests)
Pamgen                     =  12.79 sec*proc (67 tests)
Panzer                     =   0.97 sec*proc (5 tests)
Phalanx                    =  11.56 sec*proc (37 tests)
Piro                       = 795.77 sec*proc (18 tests)
ROL                        = 2487.21 sec*proc (178 tests)
RTOp                       =   1.18 sec*proc (22 tests)
Rythmos                    = 639.83 sec*proc (85 tests)
SEACAS                     =  51.76 sec*proc (16 tests)
STK                        =  26.50 sec*proc (10 tests)
Sacado                     =  22.15 sec*proc (305 tests)
Shards                     =   0.55 sec*proc (4 tests)
ShyLU_Node                 =  26.29 sec*proc (10 tests)
Stokhos                    = 355.07 sec*proc (65 tests)
Stratimikos                =  90.03 sec*proc (39 tests)
Teko                       = 115.90 sec*proc (14 tests)
Tempus                     = 11323.61 sec*proc (158 tests)
Teuchos                    =   4.94 sec*proc (119 tests)
Thyra                      =  12.57 sec*proc (58 tests)
Tpetra                     = 492.18 sec*proc (166 tests)
TrilinosATDMConfigTests    =  48.79 sec*proc (12 tests)
TrilinosBuildStats         =   2.13 sec*proc (2 tests)
TrilinosCouplings          = 252.81 sec*proc (19 tests)
TrilinosFrameworkTests     =  10.09 sec*proc (8 tests)
TrilinosInstallTests       =   2.43 sec*proc (2 tests)
Triutils                   =   0.17 sec*proc (2 tests)
Xpetra                     =   5.62 sec*proc (18 tests)
Zoltan                     =   8.31 sec*proc (36 tests)
Zoltan2                    = 115.36 sec*proc (40 tests)

Label Time Summary:
ConvergenceTest    =   9.28 sec*proc (3 tests)
IntegrationTest    =  20.84 sec*proc (17 tests)
UtilityTest        =   0.03 sec*proc (1 test)
convergence        =   9.28 sec*proc (3 tests)
integration        =  20.84 sec*proc (17 tests)
kdtree             =   7.48 sec*proc (8 tests)
kokkos             =  20.88 sec*proc (18 tests)
manifold           =   9.28 sec*proc (3 tests)
nanoflann          =   7.48 sec*proc (8 tests)
staggered          =   7.45 sec*proc (3 tests)
utility            =   0.03 sec*proc (1 test)
vector             =   6.75 sec*proc (4 tests)

Total Test time (real) = 1730.07 sec

The following tests FAILED:
	1268 - SEACASIoss_pamgen_exodus_io_info (Failed)
	1271 - SEACASIoss_Utst_iofx (Not Run)
	1273 - SEACASIoss_Utst_blob_write_read (Subprocess aborted)
	2125 - Moertel_TwoSquares (Not Run)
	2126 - Moertel_Hex_3D (Not Run)
	2749 - TrilinosInstallTests_doInstall (Failed)
	2750 - TrilinosInstallTests_find_package_Trilinos (Not Run)
Errors while running CTest
```

## rhel7_ascdo-gnu-10.3.0-openmpi-4.1.4-serial
```
$ source ../packages/framework/GenConfig/gen-config.sh rhel7_ascdo-gnu-10.3.0-openmpi-4.1.4-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all --cmake-fragment ascdo-gnu-10.3.0-openmpi-4.1.4-serial ..
<snip>
********************************************************************************
           E N V I R O N M E N T  L O A D E D  S U C E S S F U L L Y
********************************************************************************



********************************************************************************
          T Y P E  exit  T O  L E A V E  T H E  E N V I R O N M E N T
********************************************************************************


********************************************************************************
                      B E G I N  C O N F I G U R A T I O N
********************************************************************************


Please run:

  $ cmake -C /path/to/fragment.cmake /path/to/src

where "/path/to/fragment.cmake" is replaced with your generated cmake fragment file
and "/path/to/src" is replaced with your build source.

(rhel7_ascdo-gnu-10.3.0-openmpi-4.1.4-serial) $ cmake -C ascdo-gnu-10.3.0-openmpi-4.1.4-serial ..
<snip>
Finished configuring Trilinos!

-- If publishing results using Trilinos, please cite us: https://trilinos.github.io/cite.html
-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/Trilinos/genConfigTrilframe-495-openmpi

(rhel7_ascdo-gnu-10.3.0-openmpi-4.1.4-serial) $ make -i -j32
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.h:10:10: fatal error: ioex_export.h: No such file or directory
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1134:7: error: 'ex_entity_type' was not declared in this scope; did you mean 'get_entity_type'?
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1135:53: error: 'exo_type' was not declared in this scope
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1135:34: error: 'ex_put_name' was not declared in this scope
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1136:19: error: 'EX_NOERR' was not declared in this scope
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1137:9: error: 'Ioex' has not been declared
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1861:5: error: 'ex_get_all_times' was not declared in this scope
<snip>
/path/to/Trilinos/packages/seacas/libraries/ioss/src/main/io_modify.C:1865:7: error: 'ex_put_time' was not declared in this scope
<snip>
/path/to/Trilinos/packages/moertel/example/TwoSquares/../ExodusInterface.h:56:10: fatal error: exodusII.h: No such file or directory
<snip>
/path/to/Trilinos/packages/moertel/example/Hex3D/../ExodusInterface.h:56:10: fatal error: exodusII.h: No such file or directory
<snip>
(rhel7_ascdo-gnu-10.3.0-openmpi-4.1.4-serial) $ ctest -j32
<snip>
99% tests passed, 12 tests failed out of 3308

Subproject Time Summary:
Adelus                     = 2217.44 sec*proc (57 tests)
Amesos                     =  33.39 sec*proc (13 tests)
Amesos2                    =  24.34 sec*proc (10 tests)
Anasazi                    = 267.73 sec*proc (77 tests)
AztecOO                    =  22.73 sec*proc (17 tests)
Belos                      = 554.80 sec*proc (147 tests)
Compadre                   = 109.94 sec*proc (29 tests)
Domi                       = 362.96 sec*proc (125 tests)
Epetra                     =  94.15 sec*proc (64 tests)
EpetraExt                  =  23.99 sec*proc (10 tests)
FEI                        =  90.50 sec*proc (43 tests)
Galeri                     =   5.24 sec*proc (7 tests)
Ifpack                     = 133.76 sec*proc (48 tests)
Ifpack2                    = 286.37 sec*proc (55 tests)
Intrepid                   = 1809.47 sec*proc (144 tests)
Intrepid2                  = 1407.53 sec*proc (183 tests)
Isorropia                  =  12.32 sec*proc (6 tests)
Kokkos                     = 1475.49 sec*proc (40 tests)
KokkosKernels              = 675.91 sec*proc (17 tests)
Komplex                    =   1.46 sec*proc (1 test)
ML                         = 103.64 sec*proc (34 tests)
MiniTensor                 =   2.62 sec*proc (2 tests)
Moertel                    =   1.17 sec*proc (3 tests)
MueLu                      = 1975.85 sec*proc (118 tests)
NOX                        = 568.15 sec*proc (111 tests)
Panzer                     = 789.31 sec*proc (90 tests)
Phalanx                    =  39.54 sec*proc (37 tests)
Pike                       =   5.84 sec*proc (7 tests)
Piro                       = 2101.41 sec*proc (19 tests)
Pliris                     =   3.96 sec*proc (2 tests)
ROL                        = 7261.92 sec*proc (200 tests)
RTOp                       =  23.98 sec*proc (24 tests)
Rythmos                    = 1265.53 sec*proc (83 tests)
SEACAS                     =  89.75 sec*proc (17 tests)
STK                        = 6518.22 sec*proc (21 tests)
Sacado                     = 164.63 sec*proc (299 tests)
Shards                     =   2.53 sec*proc (4 tests)
ShyLU_DD                   = 304.88 sec*proc (68 tests)
ShyLU_Node                 =  12.71 sec*proc (6 tests)
Stokhos                    = 655.70 sec*proc (76 tests)
Stratimikos                = 185.14 sec*proc (44 tests)
Teko                       = 641.45 sec*proc (19 tests)
Tempus                     = 23085.07 sec*proc (158 tests)
Teuchos                    = 229.56 sec*proc (146 tests)
Thyra                      = 104.26 sec*proc (82 tests)
Tpetra                     = 812.78 sec*proc (271 tests)
TrilinosATDMConfigTests    =  30.52 sec*proc (12 tests)
TrilinosBuildStats         =   0.46 sec*proc (2 tests)
TrilinosCouplings          = 472.69 sec*proc (21 tests)
TrilinosFrameworkTests     =   4.85 sec*proc (8 tests)
TrilinosInstallTests       =   1.38 sec*proc (3 tests)
Triutils                   =   3.08 sec*proc (2 tests)
Xpetra                     =  39.44 sec*proc (19 tests)
Zoltan                     = 2136.92 sec*proc (39 tests)
Zoltan2                    = 783.66 sec*proc (168 tests)

Label Time Summary:
ConvergenceTest    =  11.54 sec*proc (3 tests)
IntegrationTest    =  79.37 sec*proc (17 tests)
UtilityTest        =   0.28 sec*proc (1 test)
convergence        =  11.54 sec*proc (3 tests)
integration        =  79.37 sec*proc (17 tests)
kdtree             =  18.75 sec*proc (8 tests)
kokkos             =  79.64 sec*proc (18 tests)
manifold           =  11.54 sec*proc (3 tests)
nanoflann          =  18.75 sec*proc (8 tests)
staggered          =  24.21 sec*proc (3 tests)
utility            =   0.28 sec*proc (1 test)
vector             =  24.91 sec*proc (4 tests)

Total Test time (real) = 14987.87 sec

The following tests FAILED:
	1455 - SEACASIoss_pamgen_exodus_io_info (Failed)
	1456 - SEACASIoss_io_info_config_has_zoltan_MPI_1 (Failed)
	1459 - SEACASIoss_Utst_iofx_MPI_1 (Not Run)
	1461 - SEACASIoss_Utst_blob_write_read_MPI_1 (Failed)
	2072 - STKUnit_tests_stk_mesh_unit_tests_MPI_4 (Timeout)
	2078 - STKUnit_tests_stk_io_unit_tests_MPI_1 (Failed)
	2084 - STKDoc_tests_stk_io_doc_tests_MPI_1 (Failed)
	2237 - Moertel_TwoSquares_MPI_1 (Not Run)
	2238 - Moertel_Hex_3D_MPI_1 (Not Run)
	3306 - TrilinosInstallTests_doInstall (Failed)
	3307 - TrilinosInstallTests_find_package_Trilinos (Not Run)
	3308 - TrilinosInstallTests_simpleBuildAgainstTrilinos (Not Run)
Errors while running CTest
```

### CODE REVIEW

**Review by sebrowne — DISMISSED** [review]

**Review by sebrowne — APPROVED** [review]

**Comment by sebrowne** [comment]
Merge conflicts, adding WIP to avoid autotester traceback

**Comment by e10harvey** [comment]
@sebrowne: Force merge?

**Comment by sebrowne** [comment]
@e10harvey Can you merge develop into this branch to resolve the merge conflicts instead?  Then the autotester should be able to handle it again.

**Comment by sebrowne** [comment]
Oh wait you already did.  I'm going to just have it retest and see how that goes

**Review by sebrowne — APPROVED** [review]

**Pull request merged**
