### PR TITLE
Tpetra: code reduction in MultiVector async group transfer tests

### PR DESCRIPTION
**Pull request by tasmith4**
@trilinos/tpetra 

## Motivation
Test refactoring and consolidation.

## Testing
Test refactoring -- tests should continue to pass

### CODE REVIEW

**Comment by tasmith4** [comment]
@trilinos/framework @jwillenbring when I click the "test results" links above, they take me to an empty CDash page.  Is there another way for me to find out why the autotester is failing?

**Review by csiefer2 — APPROVED** [review]

**Comment by DaveBeCoding** [comment]
>

**Comment by DaveBeCoding** [comment]
@tasmith4 If you are still having trouble on the CDash can you please use the Trilinos Help Desk.

**Comment by tasmith4** [comment]
Hi @DaveBeCoding, I opened a ticket at https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-116

**Comment by tasmith4** [comment]
closing since the cdash link is consistently broken

**Pull request closed without merging**
