### PR TITLE
MueLu: remove several unused variables

### PR DESCRIPTION
**Pull request by ibaned**
indicated by compiler warnings

@trilinos/muelu

### CODE REVIEW

**Comment by jhux2** [comment]
Changes to MueLu_CloneRepartitionInterface_def.hpp and MueLu_RepartitionInterface_def.hpp look fine to me.  I'll let @lucbv comment on the changes to MueLu_GeneralGeometricPFactory_def.hpp.

**Comment by lucbv** [comment]
This looks good to me. It actually points out some more work that need to be done on that algorithm, thanks for looking at it @ibaned

**Comment by ibaned** [comment]
Thanks @jhux2 @lucbv for reviewing.
I'll start the checkin test process to push this change.

**Comment by ibaned** [comment]
pushed as a510fa1

**Pull request closed without merging**
