### PR TITLE
Framework: Fix checkouts of branches

### PR DESCRIPTION
**Pull request by sebrowne**
If it exists as a ref on source_remote, check it out as such.  This allows passing a branch or a SHA as a ref.

User Support Ticket(s) or Story Referenced: TRILFRAME-567
@trilinos/framework 

## Motivation
Nightly/scheduled runs tend to use branch names as opposed to SHAs.

### CODE REVIEW

**Comment by sebrowne** [comment]
@srbdev @fryeguy52 @jmlapre can I get a review?

**Comment by sebrowne** [comment]
@gsjaardema I'm seeing this test fail and there's no way it's related to this PR: https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=1017960

I think this test is sporadically failing

**Review by jmlapre — DISMISSED** [review]

**Comment by sebrowne** [comment]
@gdsjaar I'm going to disable that test to get this PR through.

**Comment by sebrowne** [comment]
@jmlapre @srbdev @fryeguy52 can I get a fresh review now that I disabled the failing test?

**Review by srbdev — APPROVED** [review]

**Pull request merged**
