### PR TITLE
WIP:  Panzer Owned and Ghosted GlobalEvaluationData Changes

### PR DESCRIPTION
**Pull request by jmgate**
@eric-c-cyr and @rppawlo, we already did a code review of this refactor a while back, but changes pushed to Drekar required a refactor of the refactor (yay!).

The gist of it is Panzer's `GlobalEvaluationData` classes now have `operator[]()` and `at()` methods which take a local ID and give you the appropriate element of either the owned or ghosted vector.  This way the user (in Panzer, Drekar, or elsewhere) doesn't need to know anything about the data being split out under the hood.

Should we ditch the `at()` routines?  I included them for the sake of completeness and to mimmic the functionality of STL containers, but perhaps the bounds checking should happen in `operator[]()` surrounded by some `#ifdef`.  Or maybe it already happens if `-D Trilinos_ENABLE_DEBUG` since they're `Epetra_Vector`s and `Thyra::VectorBase`s behind the scenes&mdash;is that right?

In order to build and test this PR, you'll also need to pull the `panzerGatherScatter` branch from `DrekarBase`.

Note that I'll clean up the commit history of this branch before the merge to `develop`.  This is just so we can talk it over.

### CODE REVIEW

**Comment by jmgate** [comment]
Including @ssmabuza on the discussion.  He requests:

> Is it possible to have the files with "Panzer_BasisIRLayout" modified to include this additional public data member:
>  ```
>  Teuchos::RCP<PHX::DataLayout> local_mat_layout =
>    Teuchos::rcp(new PHX::MDALayout<panzer::Cell, panzer::BASIS, panzer::BASIS>(
>    this->numCells(), this->cardinality(), this->cardinality()));
>  ```
> This helps with creating local element matrices.

Sibu, can we talk this through in the meeting I set up for next Wednesday?  I'm afraid I don't see right off the bat how this relates to this PR.

**Comment by eric-c-cyr** [comment]
I would say add it to PureBasis, though I also don't see what it has to do with the PR.

**Comment by eric-c-cyr** [comment]
@ssmabuza Do you have a patch for such a thing (a particularly design and set of members in mind?) This would not be hard to add.

**Comment by ssmabuza** [comment]
@eric-c-cyr This is to provide the layout for `PHX::MDField` local matrix-like objects in the evaluators. Currently, we only have functional, basis and a few other layouts. At the moment I am bypassing this issue by creating in the constructor a pointer to `PHX::DataLayout`. `local_mat_layout` can be added to `BasisIRLayout` and in `panzer::BasisIRLayout::setup(const panzer::PointRule & point_rule)` we can simply add the line I sent to you above.

**Comment by jmgate** [comment]
Outcomes from yesterday's code review:
* Move forward declarations into the panzer namespace&mdash;check that they're even needed.
* Remove at() routines.
* Move operator[] routines and associated data from derived classes into base classes to avoid virtual function calls.

**Comment by jmgate** [comment]
@eric-c-cyr, @rppawlo:  It looks like we have forward declarations outside the `panzer` namespace in more than just the code I've touched.  Should I create an issue to deal with all those?

**Comment by jmgate** [comment]
The issue with forward declarations will be handled for all of Panzer through #1548.

**Comment by jmgate** [comment]
`at()` and associated routines removed.

**Comment by jmgate** [comment]
Moved `operator[]()` routines and `ownedView_` and `ghostedView_` data to base classes.  Testing now.

**Comment by jmgate** [comment]
Tests pass.  Rebasing on latest Trlinos/develop and DrekarBase/master.

**Pull request merged**
